### ISSUE TITLE
Implement support to rbl operator into libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1000]
Operator **rbl** needs to be implemented inside libmodsecurity.

The documentation of the operator can be found here:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#rbl

The file already exist in the repository:
https://github.com/SpiderLabs/ModSecurity/blob/libmodsecurity/src/operators/rbl.cc

**Comment by zimmerlezen** [comment]
Support added by: 049e4eb69df4d3f7cd17d0a5c853b132b1e239bb
