### ISSUE TITLE
Implement support to the GLOBAL, IP, SDBM_DELETE_ERROR and SESSION variables in libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1009]
Those variables are related to collections which are not implemented yet.

More information about it can be found at ModSecurity reference manual: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual

**Comment by zimmerlezen** [comment]
GLOBAL, IP are already ready. SESSION was moved to another ticket. SDBM_DELETE_ERROR is no longer necessary.
