### ISSUE TITLE
Implement support to the PERF_* variables in libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1011]
The following variables needs to be implemented inside libModSecurity:
- PERF_ALL
- PERF_COMBINED
- PERF_GC
- PERF_LOGGING
- PERF_PHASE1
- PERF_PHASE2
- PERF_PHASE3
- PERF_PHASE4
- PERF_PHASE5
- PERF_RULES
- PERF_SREAD
- PERF_SWRITE

More information about these variables can be found at ModSecurity reference manual: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual

**Comment by zimmerle** [comment]
Instead of using the performance variables which can actually have a negative impact on  performance, we would suggest the utilization of Linux instrumentation tools. The utilization of _stap_, for instance, can lead the same results as the Performance variables plus it allows the user to use the existent tools such as _flame-charts_ to plot the performance information in a easy to read way. There is a stap example in the nginx repository: https://github.com/SpiderLabs/ModSecurity-nginx/blob/master/ngx-modsec.stp

Having said that, I am closing this issue.

**Comment by dune73** [comment]
DURATION can be used to substitute the timings for phase 1 through 5. But the other ones would demand systemtap. DURATION also is buggy and not implemented correctly (if correctness means equal to 2.9.x).

Also the substitution is much more complicated than the native availablity of the perf variables.

I'm going into some length on this problem and the use cases for the performance variables in this ML message: https://sourceforge.net/p/mod-security/mailman/message/36276827/
