### ISSUE TITLE
Implement support to the REQBODY_* variables in libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1013]
The following variables needs to be implemented inside libModSecurity:

- REQBODY_ERROR
- REQBODY_ERROR_MSG
- REQBODY_PROCESSOR
- REQBODY_PROCESSOR_ERROR
- REQBODY_PROCESSOR_ERROR_MSG

More information about these variables can be found at ModSecurity reference manual: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual

**Comment by zimmerle** [comment]
The variables REQBODY_PROCESSOR_ERROR_MSG and REQBODY_ERROR_MSG are the same. 
REQBODY_ERROR_MSG and REQBODY_PROCESSOR_ERROR are also the same.

**Comment by zimmerle** [comment]
REQBODY_PROCESSOR implemented at: 7cb27eb9fc80fba0237af72a5560740f10b24b8b

**Comment by zimmerlezen** [comment]
REQBODY_PROCESSOR_ERROR_MSG, REQBODY_ERROR_MSG, REQBODY_ERROR_MSG and REQBODY_PROCESSOR_ERROR were implemented at ebe84247580cbc7d0a68e6f974f12bd333f26fc1
