### ISSUE TITLE
Implement support to variable STREAM_OUTPUT_BODY inside libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1022]
More information about STREAM_OUTPUT_BODY can be found at ModSecurity reference manual: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual

**Comment by zimmerle** [comment]
As of now, we don't have a proper way to handle the content in a stream manner. It won't be different from use others variables that represents the same data. Therefore I am marking this as won't implement. At least for this next version.

**Comment by kanhajinis** [comment]
Hi @zimmerle,

Any update on this variable as this is holding me to use libmodsecurity as I have many response based rules which are dependent on this directive (STREAM_OUTPUT_BODY). Any alternative for same is also okey for me.
