### ISSUE TITLE
Implement support to variable USERAGENT_IP inside libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1025]
More information about USERAGENT_IP can be found at ModSecurity reference manual: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual

**Comment by victorhora** [comment]
This feature is tied to an specific Apache module as such it belongs to the Apache connector and can't be implemented on libModSecurity. Marking as won't implement.
