### ISSUE TITLE
Implement support to variable WEBSERVER_ERROR_LOG inside libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1028]
More information about WEBSERVER_ERROR_LOG can be found at ModSecurity reference manual: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual

**Comment by zimmerle** [comment]
The variable WEBSERVER_ERROR_LOG is used by OWASP CRS version 3 and version 2, both versions read this variable to identify a possible request violation that was treated internally by Apache. As result of the reading, in case there is a request violation, a warning is generated.

Since it is not feasible to implement it in all platforms that we desire to support, I am removing the support to this variable. If you think otherwise, please re-open this issue for discussion.

**Comment by dune73** [comment]
I agree the single CRS rule using this is not very useful. But the variable in general seems worthwhile. 

Why is not feasible to support it on other platforms? 

We have other variables that are empty in certain phases. Why can't it be empty, if the platform does not support it?
