### ISSUE TITLE
XSS Bypassing ModSecurity

### ISSUE THREAD

**Issue by sohaibunix** [SpiderLabs/ModSecurity#1030]
I could inject XSS payload ,
this link includes demo video , vulnerable code and payloads :
https://drive.google.com/file/d/0B8Cfu7lkKSERZ0x2NDd0RmtaNlk/view?usp=sharing
Youtube Demo : https://www.youtube.com/watch?v=yvU3jEM2AVA

**Comment by csanders-git** [comment]
Hey @sohaibunix,
For future individuals looking at this topic, any security related information should be sent to security@modsecurity.org. 

Additionally, this would likely be a problem with OWASP CRS not modsecurity which has its own github https://github.com/SpiderLabs/owasp-modsecurity-crs/

On that note it appears you're testing with old versions of rules
I tested your findings and each of them was detected by at least one rule. Most often 
[Tue Dec 15 10:44:52.475103 2015] [:error] [pid 5694:tid 140381649250048] [client 127.0.0.1] ModSecurity: Access denied with code 404 (phase 2). detected XSS using libinjection. [file "/usr/local/apache2/modsecurity-crs/rules/REQUEST-41-APPLICATION-ATTACK-XSS.conf"] [line "44"] [id "973343"] [rev "2"] [msg "XSS Attack Detected via Libinjection"] [data "Matched Data: dd found within ARGS:x: 5.htaccess.aspx-->\\x22>'>'\\x22<img src=\\x22dd\\x22 onerror=\\x22prompt('XSS')\\x22>"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "9"] [tag "Host: localhost"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"] [tag "https://libinjection.client9.com/"] [hostname "localhost"] [uri "/testsite.php"] [unique_id "VnA1dH8AAAEAABY@OpAAAABB"]

Please make sure you are using the 3.x ruleset (https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/v3.0.0-dev/). Thank you.
