### ISSUE TITLE
Segmentation fault error while applying SecRemoteRules 

### ISSUE THREAD

**Issue by saransingh** [SpiderLabs/ModSecurity#1032]
Hello,

I am using mod_security version 2.9.0-RC2  with apache(2.2.31).
My curl version is curl 7.40.0 (x86_64-redhat-linux-gnu) libcurl/7.40.0 NSS/3.19.1 Basic ECC zlib/1.2.8 libidn/1.18 libssh2/1.4.2.
Server : Amazon linux AMI release 2015.09

Please assist.

**Comment by zimmerle** [comment]
Hi @saransingh 

Any chance to upgrade to version 2.9.0 ? 

https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.0
