### ISSUE TITLE
Missing info for "Rule processing failed"

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1034]
When a rule processing fails, we have no info about which rule.

In re.c, replace
msr_log(msr, 1, "Rule processing failed.");
by
msr_log(msr, 1, "Rule processing failed (id=%s, msg=%s).", rule->actionset->id, rule->actionset->msg);

**Comment by zimmerle** [comment]
Hi @marcstern,

This seems to be a duplicate of the issue #391

**Comment by marcstern** [comment]
Indeed
Sorry, i couldn't find the first one, so I assumed it wasn't ported to github :-(
