### ISSUE TITLE
Help to write correctly rule

### ISSUE THREAD

**Issue by shrv** [SpiderLabs/ModSecurity#1035]
A task
It is necessary for a particular URI. For a certain rule ID remove arg chek out.

Create a rule:
SecRule REQUEST_URI "@beginsWith  /wanted/vacancy/anketa/" "phase:1,t:none,pass, \
nolog,ctl:ruleRemoveTargetById=973333;ARGS:work[company][]
Does not work. 
ModSecurity: No action id present within the rule Wrapped exception

Written as a rule:
SecRule REQUEST_URI "@beginsWith  /wanted/vacancy/anketa/" "phase:2,chain,t:none,id:902212,nolog"
  SecRuleUpdateTargetById 973333 !ARGS:work[company][]
Does not work/
ModSecurity: Execution phases can only be specified by chain starter rules

How to write a rule right?
Thank you

**Comment by csanders-git** [comment]
Hey @shrv, Rules have some requirements. All 'starting' rules must contain an ID. any rule that features the 'chain' action means that it expects another rule (without an id) to follow. If you have other questions please feel free to comment back

**Comment by shrv** [comment]
Thank you, rule with a "chain" i understood.

But that is not true in the first rule?
With CTL?

**Comment by csanders-git** [comment]
The first rule has no id. rules must contain an ID

**Comment by shrv** [comment]
Thank you
