### ISSUE TITLE
nginx refactoring branch / buffering problem

### ISSUE THREAD

**Issue by tapouillo** [SpiderLabs/ModSecurity#1036]
Hi,

I noticed a buffering problem with that branch:
https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

I'm using x-sendfile to allow the download of a video (on a backend server, with nginx, and with proxy_buffering off; ).
The mod-security is configured on a separate server, with a proxy pass configuration.
(internet -> modsec servers -> backend servers)
The modsecurity configuration is set to disable buffering (parse response body off).

When I download a video file, the download is not starting immediatly, and I see in the logs, that the backend server is sending the video to the modsecurity servers, then when it is finished, the download is starting in my browser. no matter what configuration I tried on the servers, the proxy_buffering options or the modsecurity options to avoid buffering).

Now, I tried with apache2/modsecurity, with exacttly the same configuration of modsecurity, and apache as proxypass, and on the same servers:  the download starts immediatly and is not buffered on the modsecurity servers, and the log is appearing in the logfile of the backend server only when the download is finished (not before when it is buffered).

**Comment by zimmerle** [comment]
Hi @tapouillo,

This issue most likely will be fixed on ModSecurity version 3 (libModSecurity) + Nginx connector, there are further information available here: 
 - https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity
 - https://github.com/SpiderLabs/ModSecurity-nginx
 - https://www.trustwave.com/Resources/SpiderLabs-Blog/An-Overview-of-the-Upcoming-libModSecurity/

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
