### ISSUE TITLE
unknown directive "ModSecurityEnabled"

### ISSUE THREAD

**Issue by elialum** [SpiderLabs/ModSecurity#1039]
Was able to succesfully build libmodsec on centos 7.
Grabbed some modsec rules from comodo to test, and tried to enable modsec using this directive in the virtual host conf file - 

ModSecurityEnabled on

Getting the following error - 

nginx: [emerg] unknown directive "ModSecurityEnabled" in /etc/nginx/conf.d/foo.conf:76
nginx: configuration file /etc/nginx/nginx.conf test failed

Not sure how to continue from here ? 

---

BTW, I Created a "copy & paste", this should work on a centos 7 minimal, assuming you installed "development tools" 

yum install gcc-c++ flex bison curl-devel curl yajl yajl-devel GeoIP-devel doxygen zlib-devel
cd /opt/
git clone https://github.com/SpiderLabs/ModSecurity
cd ModSecurity
git checkout libmodsecurity
sh build.sh
git submodule init
git submodule update
./configure
yum install ftp://195.220.108.108/linux/fedora/linux/updates/23/x86_64/b/bison-3.0.4-3.fc23.x86_64.rpm
make
make install

cd /opt/
git clone https://github.com/SpiderLabs/ModSecurity-nginx
cd /opt/ModSecurity-nginx
git checkout experimental
cd /opt
wget http://nginx.org/download/nginx-1.9.2.tar.gz
tar -xvzf nginx-1.9.2.tar.gz
cd /opt/nginx-1.9.2
/bin/cp -f /usr/sbin/nginx /usr/sbin/nginx_original_bkp
./configure --add-module=/opt/ModSecurity-nginx 
make
make install

**Comment by zimmerle** [comment]
Hi @elialum,

Thank you for the compilation recipe. I've just created a wiki page for that kind of recipes: 
 - https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes

The configuration for ModSecurity version 3 changed a little bit in nginx, please have a look at the example available here:
- https://github.com/SpiderLabs/ModSecurity-nginx#usage-example-injecting-rules-within-nginx-configuration

We've changed that to make it more closer to others nginx's configurations.

**Comment by elialum** [comment]
Hi,

Thanks ! Was able to get it running using the given example. 
However, most of the common rule sets (tried owsap / comodo) returns errors - 

Just one example - 

nginx: [emerg] "rewrite" directive Rules error. File: /owsap/SpiderLabs-owasp-modsecurity-crs-60c8bc9/slr_rules/modsecurity_crs_46_slr_et_lfi_attacks.conf. Line: 17. Column: 162. invalid character WW  in /etc/nginx/nginx.conf:42

I was able to get owsap running with "hand picked" rules, can't get comodo to even start working. 
Haven't tried atomic rules yet, but since owsap didn't worked, I don't think any of them will ? 

Thanks,
Eli.

**Comment by zimmerle** [comment]
Hi @elialum,

In fact, some of the operators/variables/transformation are not available, plus the parser is very restrictive. However, I would spec you to be able to load the OWASP 3.0.0-dev without further problems. 

Here is the list of missing features:
 - https://github.com/SpiderLabs/ModSecurity/labels/libmodsecurity
(look for the "missing - something" labels)
