### ISSUE TITLE
Improper execution/parsing of last written "CHAIN" rule

### ISSUE THREAD

**Issue by bhaumik-merchant** [SpiderLabs/ModSecurity#1042]
Problem Statement:

Let’s say, we are having 100 rules in a configuration and 100th rule is chain rule with rule-id say 1010. In another words, there are no rules after rule-id: 1010 in the configuration. It has been observed with modsecurity 2.9 that, if the last rule of the configuration is chain rule (parent rule) and is not having trailing child rule after “chain” apache will not throw error/exception also rule will not work as per the expectation. You must need at least one “NON CHAIN” rule after a chain rule at the end of the configuration (as a last rule of modsecurity configuration).

I.e.
Rule: Create a rule to block user with username "usr1" and password "password". 
Accurate rule:
SecRule ARGS:uid "usr1" "deny,log,msg:'Testing Chain rule',phase:2,id:1728,status:403,chain"
SecRule ARGS:passw "password"

Expected Result:  If REQUEST_BODY is like "uid=usr1&passw=password&btnSubmit=Login" then intruder should be blocked
Actual Result: with REQUEST_BODY "uid=usr1&passw=password&btnSubmit=Login", intruder blocked.
Test: PASSED

Faulty Rule

SecRule ARGS:uid "usr1" "deny,log,msg:'Testing Chain rule',phase:2,id:1728,status:403,chain"

(Note: see, there are no child rules for above parent rule.)
Expected Result: If there are no rules after a rule which has “chain” directive then at the time of restarting/reloading apache, it should throw an error via mod_security like "ModSecurity: Disruptive actions can only be specified by chain starter rules."
Actual Result: While restarting/reloading apache, it is not throwing any error also not blocking "usr1" as the username.
Test: FAILED

Fix:

SecRule ARGS:uid "usr1" "deny,log,msg:'Testing Chain rule',phase:2,id:1728,status:403,chain"
# 
# 

SecRule ARGS:_nonexisting "NKkccne" "pass,nolog,phase:1,id:1290"

(Note: some random child with id 1290 after ruleid: 1728)
Expected Result: If there are no rules after a rule which has “chain” directive then at the time of restarting/reloading apache, it should throw an error via mod_security like "ModSecurity: Disruptive actions can only be specified by chain starter rules."
Actual Result: While restarting/reloading apache, it is throwing an error "ModSecurity: Disruptive actions can only be specified by chain starter rules."
Test: PASSED

**Comment by csanders-git** [comment]
This is an interesting problem. My assumption is that it is just ignoring the chain and that it doesn't crash when it reaches that rule. If this is the case while we most certainly will except a pull request for this, by the creation our own SecRule parser in v3 this issue should be solved.

**Comment by victorhora** [comment]
This should no longer be a concern with libModSecurity (aka v3).

https://github.com/SpiderLabs/ModSecurity/tree/v3/master
