### ISSUE TITLE
ModSecurity: Found another rule with the same id

### ISSUE THREAD

**Issue by matthewferguson694** [SpiderLabs/ModSecurity#1043]
Hi All,

I am trying to install Modsecurity WAF on an amazon linux box on ec2.  I can't seem to find this dup ID, if it exists.  Evidence below :)

# sudo /etc/init.d/httpd restart
Stopping httpd:                                            [FAILED]
Starting httpd: Syntax error on line 97 of /usr/local/apache/conf/crs/modsecurity_crs_10_setup.conf:
ModSecurity: Found another rule with the same id
                                                           [FAILED]

# cat modsecurity_crs_10_setup.conf | grep id:
  "id:'900001', \
  "id:'900002', \
  "id:'900003', \
  "id:'900004', \
  "id:'900005', \
  "id:'900006', \
  "id:'900007', \
  "id:'900008', \
  "id:'900009', \
  "id:'900010', \
  "id:'900011', \
  "id:'900012', \
  "id:'900013', \
  "id:'900014', \
  "id:'900015', \
  "id:'900016', \
  "id:'900017', \
  "id:'900018', \
  "id:'900019', \
  "id:'900020', \
  "id:'900021', \

tail /etc/httpd/conf/httpd.conf

<IfModule security2_module>
        Include /usr/local/apache/conf/crs/modsecurity_crs_10_setup.conf
        Include /usr/local/apache/conf/crs/activated_rules/*.conf
</IfModule>

**Comment by csanders-git** [comment]
A couple things. 
This is the ModSecurity Github and there is a seperate github for OWASP CRS. (https://github.com/SpiderLabs/owasp-modsecurity-crs). This will be closed and if you have further issues questions belong there or on the OWASP CRS mailing list :). 

Second there are no duplicate in current versions of CRS (or any previous versions). We do not really have enough information to solve this problem but perhaps you include modsecurity_crs_!0_setup twice?

Third in either event I recommend upgrading to the newest version. We are putting together v3.0.0-rc1 as we speak but it is already quite a bit more sophisticated then v2.x. Either way you feel (2.x or 3.x) i'd upgrade from the github repo. 
Hopefully that helps. good luck

**Comment by matthewferguson694** [comment]
Thanks for the information, I will add a reminder to check back in a week on github for 3.x :)
