### ISSUE TITLE
Implement the support to setuid action in modsec v3

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1048]
The support for setuid is not yet implemented.

Further information about it can be found here:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#setuid

**Comment by zimmerle** [comment]
Implemented. d96d54eeed4201db8045bd7aa02f6775c9cdc47a

**Comment by ossie-git** [comment]
This never made it into 2.9.1, did it?

**Comment by zimmerle** [comment]
@ossie-git This is about implementing something that was on 2.9.1 but wasn't on v3.
