### ISSUE TITLE
Mod security on IIS 8,5 failed please can you advise?

### ISSUE THREAD

**Issue by michalhocky** [SpiderLabs/ModSecurity#1053]
Thank you.

[log.txt](https://github.com/SpiderLabs/ModSecurity/files/90496/log.txt)

**Comment by jhba** [comment]
ADMIN CONSOLE --> msiexec /i ModSecurityIIS_2.9.0-64b.msi /l*v log.txt

**Comment by sarbur** [comment]
@jhba - see "log.txt" under the "Thank you". I will try to replicate the issue tomorrow on a clean environment. Unfortunately not sure if I will be able to replicate the exact circumstances.
Issue: we tried to install modsecurity 2.9.0 x64 on IIS 8.5 sitting on W2012 R2. Install failed and killed  the QA environment. operations could not be resumed until all installation traces were hunted down and removed manually.
Possible interactions with windows security:
- the binary is not signed (even dependencywalker sees the file as "non PE/DOS"). don't use GPG with MS, it doesn't work
- does not create a restore point (? - not sure if really an issue but did pop up in the logs)

Suggestions:
- do give a dependency list in the changelog for each release
- do specify what products was tested with before release
- do provide a cleanup script, if installation fails
