### ISSUE TITLE
Undefined term "intercept" in audit log docs

### ISSUE THREAD

**Issue by byron-hawkins** [SpiderLabs/ModSecurity#1055]
The documentation for the audit logs specifies that certain logs parts are only available if ModSecurity is configured to intercept the request or response (see https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLogParts). The term "intercept" cannot be associated to anything else in the documentation. How does one configure ModSecurity to "intercept" the request or response? Please correct the documentation by changing the word "intercept" to another word that is used elsewhere in the documentation, so that the reader can learn how to activate this component of ModSecurity.

**Comment by csanders-git** [comment]
This almost assuredly refers to the use of SecResponseBodyAccess and SecRequestBodyAccess. I will note these where needed. Thank you.
