### ISSUE TITLE
SecAuditLogParts 'E' not working

### ISSUE THREAD

**Issue by byron-hawkins** [SpiderLabs/ModSecurity#1056]
When running ModSecurity 2.9.0 in Apache 2.4.7-1ubuntu4.8, the 'E' part of SecAuditLogParts is not working. Here is my ModSecurity configuration in apache2.conf:

    SecStatusEngine On
    SecRequestBodyAccess On
    SecResponseBodyAccess On
    SecAuditEngine On
    SecAuditLog /var/log/apache2/sec.log
    SecAuditLogType Serial
    SecAuditLogParts ABCEFHZ
    SecResponseBodyMimeType text/plain text/html application/x-httpd-php
    SecResponseBodyLimit 524288
    SecResponseBodyLimitAction ProcessPartial

I've also tried `SecAuditLogType Concurrent` and numerous variations of the configuration, and have sent successful HTTP requests for both `text/html` and `application/x-httpd-php` pages.. It prints all logs parts except the 'E', which is the only part I need.

**Comment by zimmerle** [comment]
Hi @byron-hawkins,

Make sure the content type is list on SecResponseBodyMimeType [1] and SecResponseBodyAccess [2] is set to "On" 

[1] https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secresponsebodymimetype
[2] https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secresponsebodyaccess
