### ISSUE TITLE
mod_security post file problem，it's sames a bug

### ISSUE THREAD

**Issue by xumjbn** [SpiderLabs/ModSecurity#1057]
when use wget post a binary file，the Conten-Type is application/x-www-form-urlencoded, the mod_security will match the some rules, and handler it. That will make the apache memory leaked.

**Comment by zimmerle** [comment]
Hi @xumjbn,

What is your ModSecurity version and platform? Which rules are you using?

**Comment by xumjbn** [comment]
#### HI@zimmerle 
I get  apache-2.4.17 from https://github.com/apache/httpd,
get mod_security2.9.0 from https://www.modsecurity.org/tarball/2.9.0/modsecurity-2.9.0.tar.gz,
and use the base_rules and optional_rules get from https://github.com/SpiderLabs/owasp-modsecurity-crs

     The platform is centos7

I am damn sure it happed, when used wget pos a binary file, with the Conten-Type is application/x-www-form-urlencoded, mod_security will treat the binary file as the urlencoded argments, and the handler process will use almost all memory of the system.

**Comment by csanders-git** [comment]
Can you provide the sample binary file along with the rules that are triggered?

**Comment by xumjbn** [comment]
Yes,I used pcre2-10.20.tar.gz for test, and make the base_rules and optional_rules opened, you can try it.

**Comment by zimmerle** [comment]
Not able to reproduce in v2/master. Therefore closing the issue.
