### ISSUE TITLE
How to NOT log post data in PART C of modsec_audit.log

### ISSUE THREAD

**Issue by tizzythegrey** [SpiderLabs/ModSecurity#1058]
Right now i have modsec 2.5 installed on apache. Seem to work fine except for the part where it clearly shows PII info like ssn and password in post. SantiseArgs seem to not work for json posts. So my question are (1), how to do santise json post or (2), how do i make sure part C is not in my logs?

**Comment by csanders-git** [comment]
The version of modsec you're running is quite old - some of these issues might be fixed in newer version.
To remove a part of an audit log you can use ctl as follows ctl:auditLogParts=-C
