### ISSUE TITLE
problem posting a text with "select" on a server with cPanel 11.52.2.2. and ModSecurity enabled

### ISSUE THREAD

**Issue by gianlucaponti** [SpiderLabs/ModSecurity#1061]
Hi,

doing some debugging of a problem I have on a website I made for a client, I found that even doing a simple HTML post of a textarea containing the text _"select"_ is returning a 404 error (with double quotes":

```
<form action="" method="post">
	<textarea name="mytext">"select"</textarea>
	<input type="submit" value="send" />
</form>
```

Unfortunately the hosting my client is using is on a shared server of a big Italian hosting company and I have no access on which rule is giving error.
Even in the error log that I can read on the admin panel there aren't info about what is going on if I enable the ModSecurity option.

The problem disappear if I disable the ModSecurity option.

As additional info I can say that about 1 month ago the problem disappeared by itself and a week ago has come back.
I suppose because of a continuos update of the server by the hosting company.
Actually the version of cPanel is 11.52.2.2.

I don't know if there any possibilities to fix this problem I have without having access to the server configuration.

I have done some test adding rules on the .htacess file on the local domain, but on the error log I found that this kind of rules are not allowed there.

Any help would be very appreciated!
Thank you.

**Comment by csanders-git** [comment]
you either need information on what the rule is that is triggering or the ability to turn off a rule (configuration access). You also didn't include what ruleset you are using, modsecurity itself out of the box doesn't block anything it requires a ruleset. For instance, OWASP CRS, if this is a problem with CRS please post such a problem with a more detailed error on that projects github page, thank you
