### ISSUE TITLE
apr_table_copy: t's pool is not an ancestor of p Abort trap (core dumped)

### ISSUE THREAD

**Issue by rhclayto** [SpiderLabs/ModSecurity#1062]
OpenBSD 5.8, Apache 2.4.16, latest modsecurity compiled & installed successfully. pcre-8.37, 
apr-1.5.2.

However, whenever enabling any config with a SecRule in it, I get the following error:

```
apr_table_copy: t's pool is not an ancestor of p
Abort trap (core dumped)
```

Commenting out all SecRules removes the error.

Almost identical to https://github.com/SpiderLabs/ModSecurity/issues/873 except that I'm on Apache & not nginx. As such, the suggestion there to use the nginx_refactoring branch does not apply.

This same problem also occurred for me on OpenBSD 5.6, Apache 2.2.

Any ideas?

**Comment by gwurr3** [comment]
having this same issue. also with nginx

**Comment by gwurr3** [comment]
i'm on OpenBSD 5.9

**Comment by gwurr3** [comment]
both the nginx in ports (1.9) and also the latest stable 	nginx-1.10.1 have the same issue.
tried with both latest nginx_refactoring branch and with normal 2.9 from https://www.modsecurity.org/tarball/2.9.1/modsecurity-2.9.1.tar.gz

**Comment by theguly** [comment]
same issue on openbsd 6.0/apache2.4.23 with modsec downloaded through git

**Comment by victorhora** [comment]
This shouldn't be a concern with [libModSecurity](https://github.com/SpiderLabs/ModSecurity/tree/v3/master).

OpenBSD support for libModSecuirity should be stable as of https://github.com/SpiderLabs/ModSecurity/commit/dce2fed3101bbea51eba0634d17b593a8368ce8c

Thanks!

**Comment by asterite3** [comment]
This would happen if APR is compiled with `APR_POOL_DEBUG` (configure option `--enable-pool-debug=yes`).

In this case `apr_table_copy` will make an assetion that memory pool for the new table is a descendant of a pool of original table, which is violated at least here https://github.com/SpiderLabs/ModSecurity/blob/9675653/apache2/re.c#L1250

**Comment by emerzon** [comment]
> This would happen if APR is compiled with `APR_POOL_DEBUG` (configure option `--enable-pool-debug=yes`).
> 
> In this case `apr_table_copy` will make an assetion that memory pool for the new table is a descendant of a pool of original table, which is violated at least here https://github.com/SpiderLabs/ModSecurity/blob/9675653/apache2/re.c#L1250

Not only, this also causes a segfault when running over musl. Glibc seems to wrap this error silently.
