### ISSUE TITLE
no folders created /opt/

### ISSUE THREAD

**Issue by jnico** [SpiderLabs/ModSecurity#1063]
Unsure if its a problem with debian 8 modsecurity packages ( libapache2-mod-security2 libapache2-modsecurity ) though the folder /opt/modsecurity/ isn't created. Has this been seen before at all.

**Comment by csanders-git** [comment]
Unfortunatly we do not package these, you'll have to contact the debian packager. However I will say that when install ModSecurity the only thing one would expect to see would be the compiled module (.so) that would be generated for apache. This is typically placed in apaches module directory (maybe /etc/apache2/modules/ on debian?) You might be describing some CRS specific issues, which is a different package.
