### ISSUE TITLE
Conditional logging of "Stopwatch"

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1067]
Each time a rule triggers and is logged, it generates a line in the audit log with the "Stopwatch".
This wastes a lot of disk space and is not interesting for everybody.
We should have a directive (or a compile flag) to disable that logging.
Ex. of compile flag: #marcstern@9e68805

**Comment by csanders-git** [comment]
Perhaps this should be turned off but in general can not all of these be solved by directing your logs through a script first and then onto disk? Something like SecAuditLog "|/opt/removeExtra.py" ?
