### ISSUE TITLE
Conditional logging of "Response-Body-Transformed: Dechunked"

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1068]
Each time a rule triggers and is logged, it generates a line in the audit log with the "Response-Body-Transformed: Dechunked" in case the response was dechunked.
This wastes a lot of disk space and is the normal behaviour, not a real warning.
We should have a directive (or a compile flag) to disable that logging.
Ex. of compile flag: #marcstern@9e68805

**Comment by zimmerle** [comment]
Fixed at: 41ae8db5715a14807328082c31d126acd11d9f79
