### ISSUE TITLE
Conditional logging of "Server"

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1070]
Each time a rule triggers and is logged, it generates a line in the audit log with the "Server".
This wastes a lot of disk space and is not interesting if you have a good configuration management.
We should have a directive (or a compile flag) to disable that logging.
Ex. of compile flag: #marcstern@9e68805

**Comment by csanders-git** [comment]
I think there are two areas to consider here - we already allow configuration of which audit areas you want to store. I will say however that i see your point. I think a compile time flag might be a pretty good solution ... how would this apply to JSON?

**Comment by marcstern** [comment]
A configuration directive (or option) is obviously more flexible, but I will obviously be OK with a compile time flag

**Comment by csanders-git** [comment]
In general I am going to highlight this as a feature request for libmodsecurity. The capability to determine the platform you are on deterministicly is useful.
An example would be SecRule PLATFORM "@contains IIS" XYZ"
