### ISSUE TITLE
SecHashEngine Doesn't work with newer version of libxml2

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/ModSecurity#1072]
When using libxml2-2.9.3-1 SecHashingEngine didn't function properly
When using libxml2-2.7.6 SecHashingEngine works properly.

The exploration continues.

**Comment by csanders-git** [comment]
Looks like the break happened with 2.9.0
2.8.0 works and is the last version before 2.9.0

**Comment by csanders-git** [comment]
libxml2-2.9.0-rc0 does not work - so 2.8.0 is the last known working version

**Comment by csanders-git** [comment]
[2.8-2.9DIFFS.txt](https://github.com/SpiderLabs/ModSecurity/files/121141/2.8-2.9DIFFS.txt)

**Comment by csanders-git** [comment]
Check at msc_crypt.c:1081returns true when it shouldn't - and we return.

**Comment by csanders-git** [comment]
In functional version we skip #ifdef  LIBXML2_NEW_BUFFER

**Comment by csanders-git** [comment]
xmlOutputBufferGetSize(output_buf) is returning 0

**Comment by csanders-git** [comment]
It appears xmlOutputBufferGetSize cannot be called on an output_buf after it has been flushed with xmlOutputBufferFlush(output_buf);

**Comment by csanders-git** [comment]
Seems like this originated here -> https://mail.gnome.org/archives/xml/2013-June/msg00006.html

**Comment by csanders-git** [comment]
https://github.com/SpiderLabs/ModSecurity/commit/5cf5ff043a366748adf31066576f0dc08e0cdcc5

**Comment by dune73** [comment]
Good writeup. THanks. 
Just to please the search-engine: It's SecHashEngine (not SecHashingEngine).

**Comment by dune73** [comment]
OK, tried to work around this, but no avail. Actually libxml2 and modsec rule version overlap and I am not totally sure which product is being described at every occurrence. Here is what I did.

- Compiled libxml2 2.7.8 -> OK
- Compiled apache 2.4.18 against libxml2 2.7.8 -> OK
- Compiled modsecurity 2.9.1 against libxml2 2.7.8-> OK -> But standard apache fails with execution error
- Compiled modsecurity 2.9.1 against apache-with-libxml2-2.7.8 and against libxml2 2.7.8 -> Compilation failure
- Compiled modsecurity 2.8.0 against standard apache -> OK -> But bug did not go away.

So I am a bit at loss here. What did I get wrong?

**Comment by victorhora** [comment]
Can't reproduce this issue with the current codebase of v2. 

I believe commit https://github.com/SpiderLabs/ModSecurity/commit/a24957469261873d8596aac005677cac3d0abbd2 should have fixed this already. Thanks.
