### ISSUE TITLE
DOCS: Incorect requirement to install Apache 

### ISSUE THREAD

**Issue by udf2457** [SpiderLabs/ModSecurity#1074]
The NGINX section of your docs (https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Installation_for_NGINX) says you have to install Apache.

But that's not true anymore (if it was true at all in the first place !).

No need to install all the bloat that comes with Apache, all you need is :...

`sudo apt-get install apache2-threaded-dev libxml2-dev`
(or the equivalent for non deb/ubuntu systems)

Then just

```
./configure --enable-standalone-module
make
```

Much cleaner, fewer files, and .... no Apache ... yay !  ;-

**Comment by csanders-git** [comment]
I'm sure @zimmerle  will add something here but I think this statement was meant to indicate that you need parts of Apache (for instance the headers which we still see). You also need the APR. Both of these things are counter intuitive when compiling Nginx i think we can all agree :-P perhaps we could update this wiki page to be more clear about build steps though :)

**Comment by zimmerle** [comment]
Hi, 

In fact, for version 2.9.1-rc1 (most recent one) we still need the Apache dependency. I believe that ```apt-get install``` installed the Apache as a dependency of apache2-threaded-dev.

ModSecurity version 3 (under development) does not depends on Apache nor Apr. Further information can be found here: https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/

Issue #661 contains more information about the Apache dependence.

**Comment by udf2457** [comment]
Well, actually, not quite !

The benefit of  apache2-threaded-dev vs apache2 (or whatever the "normal" package is called) is that  apache2-threaded-dev only installs dev tools and binaries.  Apache2 installs the whole caboodle (config files, init scripts and all that nonsense)

**Comment by csanders-git** [comment]
@udf2457 I have updated the docs with this information :)
