### ISSUE TITLE
DOCS: Still talking about ModSecurityPass

### ISSUE THREAD

**Issue by udf2457** [SpiderLabs/ModSecurity#1075]
Hi, 

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Installation_for_NGINX (configuration steps).

Still banging on about ModSecurityPass despite  "remove Nginx ModSecurityPass command" in  #27 

(oh, I see you mention the new way below the old way... perhaps you should consider inverting it ;-)

**Comment by csanders-git** [comment]
So is the suggestion just to change the order?

**Comment by udf2457** [comment]
Well, ideally you would remove the old-version content.  ;-)

But if you don't want to do that, then surely you should be promoting the new version and putting old-version config stuff in small print ?

**Comment by csanders-git** [comment]
I'll probably add a note - do you remember what version we removed ModSecurityPass in?

**Comment by udf2457** [comment]
2.7.2 I believe.

**Comment by csanders-git** [comment]
it appears you are correct.

**Comment by csanders-git** [comment]
Alright @udf2457 I have updated the wiki tell me if you think this reads better. Thank you for your feedback we do appreciate fixes like this :)

**Comment by udf2457** [comment]
@csanders-git  beautiful, thank you !
