### ISSUE TITLE
owasp-modsecurity-crs and NGINX 

### ISSUE THREAD

**Issue by udf2457** [SpiderLabs/ModSecurity#1076]
Hi,

I seem to be having difficulty integrating the OWASP ruleset for NGINX with ModSecurity because the ModSecurity plugin for NGINX does not allow multiple ModSecurityConfig parameters and therefore its unclear how I should include all the rule conf files.

Have tried highlighting it as a documentation issue at owasp-modsecurity-crs (https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/282) , but they came back saying "use includes" but  I'm not sure how ?  Since ModSecurity config format doesn't appear to have includes directives, and as mentioned only ModSecurityConfig parameter is allowed and using a standard NGINX include directive just breaks it ?

At the moment I'm left I'm guessing there is a bit of missing functionality that needs to be coded in to the NGINX plugin ?

**Comment by csanders-git** [comment]
Alright i've updated the documentation on the wiki. See https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Installation_for_NGINX
Hopefully this answers your questions. I will be closing out the other ticket in CRS as well. If you have issues please reopen the ticket here.
