### ISSUE TITLE
YAJL m4 file has problems

### ISSUE THREAD

**Issue by LinuxJedi** [SpiderLabs/ModSecurity#1077]
The YAJL m4 file appears to have a couple of problems:

1. The pkg-config detection doesn't work in Fedora. This is because it depends on CFLAGS being set which are not for Fedora's YAJL package (patch for this attached)

2. YAJL_POSSIBLE_PATHS is missing /usr/lib64

[yajl-fix.diff.zip](https://github.com/SpiderLabs/ModSecurity/files/128066/yajl-fix.diff.zip)

**Comment by LinuxJedi** [comment]
(this is for libmodsecurity branch)

**Comment by zimmerle** [comment]
Hi @LinuxJedi,

Thanks for the report and patch. It is now fixed. Commits: 28008be616df86a1b9d212d99bf2f273d2832bb1 and d528b8ea6d97ad3b1fbe187c4041769bc5893110.

**Comment by csanders-git** [comment]
@LinuxJedi awesome work - fixes a problem many would have.
