### ISSUE TITLE
Valgrind issues found in libmodsecurity

### ISSUE THREAD

**Issue by LinuxJedi** [SpiderLabs/ModSecurity#1078]
Found using the unit tests wrapped in valgrind.

- src/utils/msc_tree.cc:122 uses malloc, src/utils/ip_tree.cc:47 uses delete
- src/utils/msc_tree.cc:116 uses malloc, src/utils/ip_tree.cc:54 uses delete
- src/utils/msc_tree.cc:76 uses malloc, src/utils/ip_tree.cc:51 uses delete
- src/utils/msc_tree.cc:219 uses malloc, src/utils/ip_tree.cc:42 uses delete
- src/utils/msc_tree.cc:763 off by one read (should probably be bytes-1)
- src/utils/acmp.cc:358 calloc isn't freed
- src/utils/acmp.cc:497 calloc isn't freed
- src/operators/rx.h:40 new isn't freed
- src/operators/verify_cc.cc:78 needs to use pcre_free when done

**Comment by zimmerle** [comment]
Full output of `make check-valgrind-memcheck', include the listed issues and a few more. They are listed at:

https://gist.github.com/zimmerle/9733074f945a463246e454359108b706

**Comment by zimmerle** [comment]
As of: 21777aec41ec829181e9cea50ebf88d8cb47630c all the issues were closed.
