### ISSUE TITLE
ModSecurity processing phases are *not* shown

### ISSUE THREAD

**Issue by do11** [SpiderLabs/ModSecurity#1080]
> https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#processing-phases
> Below is a diagram of the standard Apache Request Cycle. In the diagram, the 5 ModSecurity processing phases are shown.

Diagram is not visible. Link is pointing to https://camo.githubusercontent.com/ffbcb1caf4b9f624c4cbe69b683194e8efd5089f/687474703a2f2f6d6f6473656375726974792e6f72672f672f4170616368655f726571756573745f6379636c652d6d6f6473656375726974792e6a7067 which shows "Not Found" text.

**Comment by csanders-git** [comment]
Somehow @github lost it - interesting. My thought is that it is supposed to be https://blog.spiderlabs.com/.a/6a0133f264aa62970b0133f6519639970b-800wi

**Comment by csanders-git** [comment]
Does this seem to fit?

**Comment by do11** [comment]
I don't know if it's fit, as I didn't see previous state of the doc. Currently, doc is still w/o picture. Do you suggest me to edit wiki and put new url in place of non-working?

**Comment by csanders-git** [comment]
I will update it, I just wanted another opinion from someone else who read it before hand.

**Comment by zimmerle** [comment]
Hi @csanders-git, that is the correct image.

**Comment by csanders-git** [comment]
Thank you for reporting this issue. I have updated the wiki with this image which is now hosted off modsecurity.org
