### ISSUE TITLE
whitelisting an ip/network issue

### ISSUE THREAD

**Issue by mgaulton** [SpiderLabs/ModSecurity#1085]
I have recently rebuilt an Opensuse leap 42.1 box and realized apache was broken. i reinstalled apache2 and mod_security2 from packages and started configuring.

Not sure how to crrect this. My googlefu is failing me. Trying to add exceptions for my local hosts as below, gives me "Feb 24 15:06:37 server6 start_apache2[11315]: AH00526: Syntax error on line 3 of /etc/apache2/mod_security2.d/whitelist.conf:
Feb 24 15:06:37 server6 start_apache2[11315]: ModSecurity: Disruptive actions can only be specified by chain starter rules." 
SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" phase:1,nolog,allow,ctl:ruleEngine=Off,ctl:auditEngine=Off
SecRule REMOTE_ADDR "@ipMatch 192.168.2.1/24" phase:1,nolog,allow,ctl:ruleEngine=Off,ctl:auditEngine=Off

**Comment by csanders-git** [comment]
What you have looks nice, perhaps you have an unfinished chain rule somewhere, it's not listed in your example. Additionally, 'allow' and ctl:ruleEngine=Off are a bit different in their function. When allow occurs the packet processing stops and everything is good. when ctl:ruleEngine is off it still will go through the remainder of the rules and trigger alerts but not undertake disruptive actions. In this case I have a feeling you just want allow. Also please do make sure that this rule occurs before the other rules are listed.

**Comment by mgaulton** [comment]
Its in a standalone file in the /etc/apache2/mod_security.d folder. No chain involved. If i comment out the lines, everything else works. I'll try renaming the file to load it first.

**Comment by mgaulton** [comment]
Renamed whitelist.conf to 000-whitelist.conf and the message changed to 'ModSecurity: No action id present within the rule' and adding a uniq id resolved that. Working (pending more testing) are below. Thanks

SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" phase:1,id:'1000000001',nolog,allow,ctl:ruleEngine=Off,ctl:auditEngine=Off
SecRule REMOTE_ADDR "@ipMatch 192.168.2.1/24" phase:1,id:'1000000002',nolog,allow,ctl:ruleEngine=Off,ctl:auditEngine=Off

**Comment by csanders-git** [comment]
Yes, you probably took the example from an older documentation before ID's were required. I'm glad you got it working. Feel free to join us on the IRC channel #modsecurity if you have any more issues, or continue to post here if it's more comfortable :)

**Comment by mgaulton** [comment]
Awesome, thanks.
