### ISSUE TITLE
another packaging issue

### ISSUE THREAD

**Issue by sholdowa** [SpiderLabs/ModSecurity#1088]
This is on a debian jessie server if relevant.

It seems that it is impossible to build from source without having apxs installed. I've tried just building for nginx using all variants up to 

./configure --disable-apache2-module --enable-standalone-module --disable-mlogc --disable-apxs

( and without-apxs, and with-apxs=no )

each time configure returned
configure: looking for Apache module support via DSO through APXS
configure: error: couldn't find APXS

The only way I managed to get it to build was to install apache2-dev and then

./configure --enable-standalone-module --disable-mlogc

**Comment by csanders-git** [comment]
This is a known issue with ModSecurity for Nginx and one of the reasons behind libmodsecurity (v3)

**Comment by zimmerle** [comment]
Please, check the issue: #661
