### ISSUE TITLE
SecAuditLogParts section identifiers are surprising

### ISSUE THREAD

**Issue by stig** [SpiderLabs/ModSecurity#1089]
It would be nice if the `I` directive resulted in a audit log section separator containing the letter `I` rather than `C`. I was attempting to stop the request body from going to the audit log, but was led on a wild goose chase due to the section identifier being `C` rather than `I`.

To be clear, the audit log contained a separator like this:

```
--c7036611-C--
```

despite our setting of:

```
SecAuditLogParts ABIJDEFHZ
```

I _eventually_ realised that it was the `I` part that resulted in the `C` section identifier, but I think this is a clear violation of the principle of least surprise. I would instead have expected the section separator to be like the below:

```
--c7036611-I--
```

**Comment by zimmerle** [comment]
Hi @stig,

The information on different segments was documented here: https://github.com/SpiderLabs/ModSecurity/wiki/ModSecurity-2-Data-Formats#parts

As of version 3 we have the logging in a JSON format, those letters are not used any longer. For backwards compatibility we still have an option to use this old format. We are not thinking in changing it, to keep the compatibility.
