### ISSUE TITLE
Users cannot block /aux/ using IIS.

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/ModSecurity#1090]
When a user using ModSecurity for IIS tries to deny access to a reserved folder URL - the log indicates that it blocked the site successfully, but a 500-level error is always reported.

There are several other extensions that this effects too. 
http://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/

**Comment by csanders-git** [comment]
![matt](https://cloud.githubusercontent.com/assets/4632287/13717507/06613d40-e7b0-11e5-85de-37af6e6a3a71.png)

**Comment by zimmerle** [comment]
@csanders-git is this related to this specific version of IIS or it is something that is a problem in all versions that we support?

**Comment by csanders-git** [comment]
All versions of IIS

**Comment by martinhsv** [comment]
@csanders-git,

Is this still a real issue?
