### ISSUE TITLE
Cannot build with --with-yajl on ubuntu 14.04, modsecurity 2.9.1

### ISSUE THREAD

**Issue by systeminsightsbuild** [SpiderLabs/ModSecurity#1092]
I have tried all manner of --with-yajl="*", but always 
```
checking for libyajl config script... no
checking for yajl install... no
configure: optional yajl library not found
```

There are similar issues for other platforms, and also issues going back as far as 2014 that are closed, but which have no indication as to the resolution in the issue.

**Comment by memelet** [comment]
Ok, I did not try _all_ -with-yajl paths. This worked:
```
./configure --with-yajl="/usr/lib/x86_64-linux-gnu /usr/include/yajl"
```

**Comment by csanders-git** [comment]
interesting. In general the problem is that some yajl packages don't ship with a pkgconfig script.

**Comment by azurit** [comment]
This is problem also on Debian Stretch.
