### ISSUE TITLE
Installation modsecurity 2.9.1 on Debian 7

### ISSUE THREAD

**Issue by bobak69** [SpiderLabs/ModSecurity#1093]
Hi,
When installing modsecurity-2.9.1-RC1 or 2.9.1 on my debian 7, i've some problems during build :
```
$ ./configure --prefix=/home/share/modsecurity --with-apxs=/usr/bin/apxs2
$ make
```
……
[make[1]: Entering directory `/root/temp/modsecurity-2.9.1/mlogc'
gcc -DHAVE_CONFIG_H -I. -I../apache2  -D_REENTRANT -D_GNU_SOURCE -I../apache2  -I/usr/include/apr-1.0                                                                                                                                        -DWITH_CURL  -g -O2  -I/usr/include/apr-1.0 -I/usr/include -MT mlogc-mlogc.o -MD -MP -MF .deps/mlogc-m                                                                                                                                       logc.Tpo -c -o mlogc-mlogc.o `test -f 'mlogc.c' || echo './'`mlogc.c
mlogc.c: In function 'logc_init':
mlogc.c:1281:10: error: 'CURL_SSLVERSION_TLSv1_0' undeclared (first use in this function)
mlogc.c:1281:10: note: each undeclared identifier is reported only once for each function it appears i                                                                                                                                       n
mlogc.c:1284:10: error: 'CURL_SSLVERSION_TLSv1_1' undeclared (first use in this function)
mlogc.c:1287:10: error: 'CURL_SSLVERSION_TLSv1_2' undeclared (first use in this function)
make[1]: *** [mlogc-mlogc.o] Error 1
make[1]: Leaving directory `/root/temp/modsecurity-2.9.1/mlogc'
make: *** [all-recursive] Error 1](url)

**Comment by csanders-git** [comment]
please ensure that you have curl development headers and openssl installed. These are required for mlogc to function.

**Comment by bobak69** [comment]
Curl development headers and openssl is already installed.
```
$ apt-get install libcurl4-openssl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libcurl4-openssl-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  libfontconfig1-dev libpthread-stubs0 libpthread-stubs0-dev libx11-doc x11proto-kb-dev xtrans-dev
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

```
$ apt-get install openssl
Reading package lists... Done
Building dependency tree
Reading state information... Done
openssl is already the newest version.
The following packages were automatically installed and are no longer required:
  libfontconfig1-dev libpthread-stubs0 libpthread-stubs0-dev libx11-doc x11proto-kb-dev xtrans-dev
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by csanders-git** [comment]
I'm not sure how to get this working on debian - but I can work through if needed. Apparently there is no libcurl-dev it's a virtual package but you might also need (apt-get install libcurl4-gnutls-dev). at worst case you can always compile without mlogc using the --disable-mlogc comment

**Comment by zimmerle** [comment]
Hi @bobak69,

You can also share the output of the configure scripts, you should have something similar to:

```
checking for libcurl config script... /usr/bin/curl-config
checking if libcurl is at least v... yes, 7.43.0
checking if libcurl is linked with gnutls... no
configure: using curl v7.43.0
```
