### ISSUE TITLE
How I configure for blocking mode rules 

### ISSUE THREAD

**Issue by bobak69** [SpiderLabs/ModSecurity#1095]
All commercial rules detections are Warning and no blocking.
How,but the free rules are working properly. 
How I configure for blocking mode rules on  ModSecurity 2.9.0 (Debian 7) ?

In my configuration file, I have:
```
SecRuleEngine On
SecDefaultAction "phase:1,deny,log"
```

**Comment by csanders-git** [comment]
The commercial rules use 'block' in the same way as the CRS rules, please also set a phase:2 block.
