### ISSUE TITLE
Reason for 981172 (PCRE limits exceeded) ?

### ISSUE THREAD

**Issue by nestoru** [SpiderLabs/ModSecurity#1096]
Greetings,

We are experiencing 981172 for simple requests like the below however we are unable to replicate when handcrafting the request using the cookies reported my modsecurity. A simple request to the resource below for example does not cause modsecurity to complain either. 

> [15/Mar/2016:19:55:16 --0400] Vuig5KwQAikAABojW@IAAADM 192.168.5.122 63429 172.16.2.41 443
> --7b334e38-B--
> GET /resources/images/svg/loader.svg HTTP/1.1
> Host: bh.sample.com
> Connection: keep-alive
> Accept: image/webp,image/*,*/*;q=0.8
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
> Referer: https://bh.sample.com/resources/css/app.css?version=1.2124.0
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: en-US,en;q=0.8
> Cookie: JSESSIONID=BA7126354A1B1E378E295DA5DBD0C6A3.sample-app3; connect.sid=s%3A8Z-CWL1eO0k1H7ZJtaE-4lqP-1_OdNSy.vgumV%2BsDeAhBrvy%2FUAFVp8K4PJR6%2FPX0zHdogQI%2Bip8; _ga=GA1.2.2048708085.1413477326; _gat=1
> 
> --7b334e38-F--
> HTTP/1.1 200 OK
> Last-Modified: Tue, 15 Mar 2016 17:22:09 GMT
> Accept-Ranges: bytes
> Content-Length: 1673
> Cache-Control: max-age=2592000, no-store
> Expires: Thu, 14 Apr 2016 23:55:16 GMT
> X-Frame-Options: sameorigin
> X-XSS-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> X-WebKit-CSP: default-src 'self'
> X-Permitted-Cross-Domain-Policies: master-only
> Content-Security-Policy: default-src 'self' 'unsafe-inline'; script-src 'self' https://www.google-analytics.com; img-src 'self' https://www.google-analytics.com
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Keep-Alive: timeout=15, max=98
> Connection: Keep-Alive
> Content-Type: image/svg+xml
> 
> --7b334e38-E--
> 
> --7b334e38-H--
> Message: Rule 7f883dc48ae8 [id "981172"][file "/etc/modsecurity/modsecurity_crs_41_sql_injection_attacks.conf"][line "157"] - Execution error - PCRE limits exceeded (-8): (null).
> Stopwatch: 1458086116267757 8497 (- - -)
> Stopwatch2: 1458086116267757 8497; combined=7524, p1=308, p2=7205, p3=2, p4=0, p5=8, sr=85, sw=1, l=0, gc=0
> Response-Body-Transformed: Dechunked
> Producer: ModSecurity for Apache/2.7.7 (http://www.modsecurity.org/); OWASP_CRS/2.2.8.
> Server: Apache
> Engine-Mode: "DETECTION_ONLY"
> 
> --7b334e38-Z--

For now it would look like we will have to exclude the rule:
`SecRule REQUEST_URI "@contains /" "phase:1,t:none,pass,id:'17',nolog,ctl:ruleRemoveById=981172"`

Any help would be really appreciated. Best regards,
- Nestor

**Comment by csanders-git** [comment]
In general this has to do with the steps required to process the regex rules. It is possible to increase these such that these will not occur. The problem is that this is a balance between causing a DOS condition where extremely complicated input (to parse) can be provided by an attacker versus how deep you want your regex to process. In general tuning SecPcreMatchLimitRecursion and SecPcreMatchLimit will take care of the issue :) Please see the reference monitor for more details on this: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secpcrematchlimit

**Comment by nestoru** [comment]
Thanks for the feedback. The question is why this request will not generate any alert when manually crafted? It will appear like the alert does not happen 100% of the time as even though I see the alerts for some requests I am unable to further replicate them.

**Comment by csanders-git** [comment]
I am unsure of why you can't reproduce these requests - this rule seems to deal with REQUEST_COOKIES values and REQUEST_COOKIES_NAMEs
