### ISSUE TITLE
error compiling v2.9.1

### ISSUE THREAD

**Issue by AcidS76** [SpiderLabs/ModSecurity#1103]
Hello, i'm trying today to compile v2.9.1 (currently i use v2.9). I have downloaded the .tar version, the .zip and git too but when i run make, i get after a bit this error:

/usr/bin/ld: cannot find -lyajl
collect2: error: ld returned 1 exit status
make[2]: *** [mod_security2.la] Error 1
make[2]: Leaving directory `/tmp/ModSecurity/apache2'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/ModSecurity/apache2'
make: *** [all-recursive] Error 1

i'm running Ubuntu 14.04 with kernel 4.5.0, 64bit and i followed these steps:
- unzip the archive on /tmp
- ./autogen.sh
- ./configure
- make
and at this step, i get those errors... Could you help me? Thanks

**Comment by csanders-git** [comment]
You'll need YAJL https://lloyd.github.io/yajl/ (which is a JSON parsing library). Version 2.9.1 requires it to support JSON audit logging. Most Distributions support installation of yajl via their repo's something like apt-get install libyajl-dev (untested)
