### ISSUE TITLE
most stable nginx branch, `nginx_refactoring`?

### ISSUE THREAD

**Issue by efx** [SpiderLabs/ModSecurity#1105]
I've noticed that `nginx_refactoring` [is recommended ](http://modsecurity.org/download.html) as the branch to use when compiling modsecurity.
I also saw that there are multiple other nginx branches. Is `nginx_refactoring` still the most stable branch to use for compiling nginx with modsecurity?

**Comment by csanders-git** [comment]
yes, this is correct.
