### ISSUE TITLE
Append/prepend actions triggered on partial rule chain match

### ISSUE THREAD

**Issue by metheoryt** [SpiderLabs/ModSecurity#1117]
I have following default action in my modsec installation:
```
SecContentInjection On
SecDefaultAction "phase:4,log,auditlog,append:'MODSEC_MATCH:%{rule.id}',pass"
```
I use content injection for testing purposes, it should trigger on rule/rule chain match, it returns id of matched rule, when matches. Also I have next chain:
```
SecRule ARGS chain \
  "chain, \
  msg:'Chained rule fired!', \
  id:'900001', \
  phase:1, \
  block, \
  t:none
    SecRule REQUEST_HEADERS:X-Catch-Me here
```
I got `MODSEC_MATCH:900001` on request to `/?smth=chain` with header `X-Catch-Me: here` - OK.
BUT, when I send request `/?smth=chain` WITHOUT my super-header, I get `MODSEC_MATCH:900001` too. I tried to change default action `pass` to `deny`, and it works fine, (except that it injects nothing in response). Also, other actions (`log` and `auditlog`) don't trigger together with `prepend`, they behave as they should.

software version:
```
ModSecurity for nginx (STABLE)/2.9.0
nginx version: nginx/1.9.4
```

**Comment by metheoryt** [comment]
I built nginx with latest version of nginx_refactoring branch, but got exactly same bug. Who knows another way to provide fired rule ID's with response, please, give me a clue!

**Comment by zimmerle** [comment]
Hi @metheoryt you may wnat to read about the setvar action:
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#setvar
