### ISSUE TITLE
How to block an IP on a page (chaining is OR function, I need AND function)

### ISSUE THREAD

**Issue by vincentcox** [SpiderLabs/ModSecurity#1119]
I need to block an IP on a page. 
So for example, user with IP 127.0.0.1 is not allowed on /my-precious/, but is allowed on the rest of the site.
How do I achieve that? 
Chaining is an OR function I think, so it will not be sufficient here.

**Comment by csanders-git** [comment]
Chaining is actually an and function it is the OR function we don't really have and one must use variables in order to acoomplish so if you chained "@ipmatch 127.0.0.1" chained with REQUEST_URI "@contains /my-precious/"
