### ISSUE TITLE
installation of the ModSecurity-nginx connector lssues

### ISSUE THREAD

**Issue by maxwalk** [SpiderLabs/ModSecurity#1120]
1、env:
Centos 7 Minimal 1511+ModSecurity-nginx+nginx-1.8.1
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes >> Sent by @elialum (See: #1039)

2、error:
 ./configure: error: ngx_http_modsecurity requires the ModSecurity library.

3、Detail:

[root@modsec nginx-1.8.1]# ./configure --add-module=/opt/ModSecurity-nginx 
checking for OS
 + Linux 3.10.0-327.el7.x86_64 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
checking for gcc -pipe switch ... found
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... not found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... found
checking for Linux specific features
checking for epoll ... found
checking for EPOLLRDHUP ... found
checking for O_PATH ... found
checking for sendfile() ... found
checking for sendfile64() ... found
checking for sys/prctl.h ... found
checking for prctl(PR_SET_DUMPABLE) ... found
checking for sched_setaffinity() ... found
checking for crypt_r() ... found
checking for sys/vfs.h ... found
checking for nobody group ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for kqueue ... not found
checking for crypt() ... not found
checking for crypt() in libcrypt ... found
checking for F_READAHEAD ... not found
checking for posix_fadvise() ... found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... not found
checking for dlopen() in libdl ... found
checking for sched_yield() ... found
checking for SO_SETFIB ... not found
checking for SO_ACCEPTFILTER ... not found
checking for TCP_DEFER_ACCEPT ... found
checking for TCP_KEEPIDLE ... found
checking for TCP_FASTOPEN ... found
checking for TCP_INFO ... found
checking for accept4() ... found
checking for eventfd() ... found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 4 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for setproctitle() ... not found
checking for pread() ... found
checking for pwrite() ... found
checking for sys_nerr ... found
checking for localtime_r() ... found
checking for posix_memalign() ... found
checking for memalign() ... found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found
checking for System V shared memory ... found
checking for POSIX semaphores ... not found
checking for POSIX semaphores in libpthread ... found
checking for struct msghdr.msg_control ... found
checking for ioctl(FIONBIO) ... found
checking for struct tm.tm_gmtoff ... found
checking for struct dirent.d_namlen ... not found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional modules
adding module in /opt/ModSecurity-nginx
checking for ModSecurity library ... not found
checking for ModSecurity library in /usr/local/modsecurity ... not found
 ./configure: error: ngx_http_modsecurity requires the ModSecurity library.
[root@modsec nginx-1.8.1]#

**Comment by manishmalik** [comment]
Possible duplicate #1118  (although in that issue op was using Ubuntu ).

**Comment by maxwalk** [comment]
Tried……
I think it is different

**Comment by uxbod** [comment]
Hello, do any of you have a working installation with CentOS 7, using RPM builds, and care to share your recipe(s) ? Thanks - Phil

**Comment by maxwalk** [comment]
set the environment variables:
        export MODSECURITY_INC="/opt/ModSecurity/headers/"
        export MODSECURITY_LIB="/opt/ModSecurity/src/.libs/"

and fix my problem.

**Comment by csanders-git** [comment]
@maxwalk I updated the recipe.

**Comment by uxbod** [comment]
Hello, do any of you have a working installation with CentOS 7, using RPM builds, and care to share your recipe(s) ? Thanks - Phil

**Comment by csanders-git** [comment]
@uxbod libmodsecurity is in constant development - we don't provide rpm builds ourselves although some people have been building their own... the receipes are available in the wiki https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes
