### ISSUE TITLE
unable to compile custom module for ModSecurity

### ISSUE THREAD

**Issue by tinduonguit** [SpiderLabs/ModSecurity#1121]
I want to write a custom parser for ModSec. Although I included "msc_parsers.h" I couldn't reuse parse_arguments function (which is in msc_parsers.c) and got this error :

/usr/share/apr-1.0/build/libtool --silent --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -prefer-pic -pipe -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security  -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE  -pthread  -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -I../apache2/ -I/usr/include/libxml2  -c -o test.lo test.c && touch test.slo
/usr/share/apr-1.0/build/libtool --silent --mode=link --tag=disable-static x86_64-linux-gnu-gcc -std=gnu99 -Wl,--as-needed -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now    -o test.la  -rpath /usr/lib/apache2/modules -module -avoid-version    test.lo
.libs/test.o: In function `test_complete':
/home/vagrant/ModSecurity/test/test.c:112: undefined reference to `parse_arguments'
/usr/bin/ld: .libs/test.so: hidden symbol `parse_arguments' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
apxs:Error: Command failed with rc=65536
.

The command :
apxs -I ../apache2/ -I /usr/include/libxml2 -ca test.c

**Comment by zimmerle** [comment]
Hi @tinduong94,

Not sure if you saw, but there is a ModSecurity secrules parser implemented inside the "libmodsecurity" branch. That will be used as part of version 3.0. It is complete independent of Apache. 
Did you saw that?

**Comment by tinduong94** [comment]
Hi @zimmerle ,

I did not saw that :) But currently my server is not using that version. Is there any solution to the mentioned compiling problem ? Or is there any way to reuse add_argument function on custom module ?

**Comment by zimmerle** [comment]
Hi,

The function that you mentioned, is defined here:
https://github.com/SpiderLabs/ModSecurity/blob/master/apache2/msc_parsers.c#L238-L336

**Comment by tinduong94** [comment]
Hi @zimmerle ,

There is no way to reuse these functions by including it ? (ex #include "msc_parsers.c" does not work) ?Have to copy and paste it into code to use ?

**Comment by zimmerle** [comment]
What exactly do you mean?

It seems to me that it depends on your implementation. You should not include the .c file, rather you should compile it and send altogether with your code (the compiled version of it) to the linker, that will solve the dependency.

**Comment by tinduong94** [comment]
Sorry for my bad explaination, but in short:

I want to reuse parse_arguments function (which is in https://github.com/SpiderLabs/ModSecurity/blob/master/apache2/msc_parsers.c) in my custom parser. I'm modifying https://github.com/SpiderLabs/ModSecurity/blob/master/ext/mod_reqbody_example.c to make it work but don't know how.

Can you give me the instructions ?

Thanks.

**Comment by zimmerle** [comment]
Hi @tinduonguit,

Please check the IIS and Nginx modules, they may help to understand the code a little bit better.
