### ISSUE TITLE
Nginx + modsecurity - rules triggered but only warning in log file

### ISSUE THREAD

**Issue by stratokako** [SpiderLabs/ModSecurity#1126]
Hello, I've got modsecuirty installed with nginx standalone. Calling an url as : http://www.mydomain.eu?<script>.... triggers the rule but the home page is rendered and the request is not blocked as I'm expecting. 

Warning. Pattern match "\\< ?script\\b" at ARGS_NAMES:<script>. [file "/etc/nginx/modsecurity/modsecurity.conf"] [line "1787"] [id "958051"] [rev "2"] [msg "Cross-site Scripting (XSS) Attack"] [data "Matched Data: <script found within ARGS_NAMES:<script>: <script>"] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "8"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A2"] [tag "OWASP_AppSensor/IE1"] [tag "PCI/6.5.1"]

I've got : 

SecRuleEngine On
SecRequestBodyAccess On

How can it be? Regards, Samuele

**Comment by zimmerle** [comment]
Please check the SecRuleEngine configuration:

- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secruleengine
