### ISSUE TITLE
How to use LUAJIT to improve performance

### ISSUE THREAD

**Issue by vincentcox** [SpiderLabs/ModSecurity#1127]
In the book of Ivan Ristic they mention LUAJIT to improve the performance of lua scripts triggered in modsecurity. They refer to:https://www.purehacking.com/blog/josh-zlatin/speeding-up-lua-script-execution-in-modsecurity
But I don't have " /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2.0.0" file when I install luajit via "apt-get install luajit". Any idea's?

**Comment by csanders-git** [comment]
I'm actually very curious to see if this works flawlessly with more recent versions.
I was able to install liblua from yum (i'm on fedora) it placed things into /usr/lib64/
I had the following files
libluajit-5.1.so        libluajit-5.1.so.2.0.4         libluajit-5.1.so.2      

It looks like on linux the SO is provided via the libluajit-5.1-dev package (http://packages.ubuntu.com/wily/libluajit-5.1-dev) ... Keep us updated on if the latest version works.

**Comment by vincentcox** [comment]
Thanks, the dev package delivered me the .so files. Unfortunately Modsecurity doesn't load it in.
apache.conf file:
```
LoadFile libxml2.so.2
LoadFile /usr/lib/x86_64-linux-gnu/libluajit-5.1.so
LoadModule security2_module /usr/lib/apache2/modules/mod_security2.so
#LoadModule security2_module /usr/lib/apache2/modules/mod_security2.so
ServerName localhost
# This is the main Apache server configuration file.  It contains the

```
Output error.log file when restarting the server:
```
[Thu Apr 21 20:09:08.000725 2016] [:notice] [pid 25459] ModSecurity for Apache/2.7.7 (http://www.modsecurity.org/) configured.
[Thu Apr 21 20:09:08.000776 2016] [:notice] [pid 25459] ModSecurity: APR compiled version="1.5.1-dev"; loaded version="1.5.1-dev"
[Thu Apr 21 20:09:08.000786 2016] [:notice] [pid 25459] ModSecurity: PCRE compiled version="8.31 "; loaded version="8.31 2012-07-06"
[Thu Apr 21 20:09:08.000792 2016] [:notice] [pid 25459] ModSecurity: LUA compiled version="Lua 5.1"
[Thu Apr 21 20:09:08.000795 2016] [:notice] [pid 25459] ModSecurity: LIBXML compiled version="2.9.1"
[Thu Apr 21 20:09:08.009255 2016] [so:warn] [pid 25459] AH01574: module security2_module is already loaded, skipping
[Thu Apr 21 20:09:09.027059 2016] [mpm_prefork:notice] [pid 25460] AH00163: Apache/2.4.7 (Ubuntu) mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
```
It seems that apache is still using the normal lua version...
And also my script is not faster, so I think it is not loading the luaJIT.
Any idea's?
