### ISSUE TITLE
Python script from ModSecurity

### ISSUE THREAD

**Issue by kavat** [SpiderLabs/ModSecurity#1133]
Hi All,
I have to configure a rule that it calls a python script and it has to elaborate the return of this script. At the moment I write this:

SecRule REQUEST_HEADERS:Content-Type "application/json" "id:'1000003',phase:4,log,setenv:richiesta=%{STREAM_INPUT_BODY},exec:/etc/modsecurity/includes/pythons/test.py"

It works correctly (it has been execute by apache and it logs some phrases on my trace) but I don't know how give the output and use it.

Can you help me please?

Thanks
Andrea

**Comment by csanders-git** [comment]
ModSecurity does not support receiving the stdout of scripts like this. You may consider dealing with LUA to get direct access to variables.

**Comment by kavat** [comment]
Whats is Python branch?

**Comment by csanders-git** [comment]
https://github.com/SpiderLabs/ModSecurity/tree/experimental_python_support

**Comment by kavat** [comment]
Can you explain me better please?

**Comment by csanders-git** [comment]
it is an experimental branch without documentation/support that provides support for using python in similar ways you can use LUA now giving you access to modsecurity variables. You can use similar logic within libmodsecurity.

**Comment by kavat** [comment]
Ok, I understand this.
I can execute yet a Python script, but how can I link this to modsecurity rules?

**Comment by csanders-git** [comment]
huh?

**Comment by kavat** [comment]
I wrote a Python script that it works fine with modsecurity, I wrote rule with exec action that it sends a buffer to this script. The script elaborates this buffer and logs in my trace. My problem is the comunication from script to modsecurity. Are there any metodology to return anything?

**Comment by csanders-git** [comment]
The script you execute must write something (anything) to stdout; if it doesn’t, ModSecurity will assume that the script failed, and will record the failure.

**Comment by kavat** [comment]
My script print a string in stdout, and it works fine. My problem is: how have I to do to deny a request from modsecurity from my script?

**Comment by csanders-git** [comment]
giving no output will be treated as false whereas output to stdout will be treated as success.
