### ISSUE TITLE
Implement a SharedMemory mechanism as Collection backend on libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1141]
ModSecurity version 3 architecture allow the utilization of multiple backends, including a shared memory one. The support should be implemented. The interface is available here:

https://github.com/SpiderLabs/ModSecurity/blob/libmodsecurity/headers/modsecurity/collection/collection.h

**Comment by zimmerle** [comment]
As of: 833089eb70f6049c73db5ce9394e765594e43e9e collections can be saved using LMDB. LMDB support the access from multiprocess. Further info about LMDB: https://github.com/LMDB/lmdb

**Comment by HOSTED-POWER** [comment]
Hi,

How to configure mod_security to use this LMDB? Could someone please post config sample, thanks a lot!

**Comment by HOSTED-POWER** [comment]
Any update on how to configure it?

**Comment by Roger-Man** [comment]
@HOSTED-POWER 
Hi,
If you have lmdb installed, you could enable it by passing `--with-lmdb` to modsecurity `configure` script.
Good luck

**Comment by HOSTED-POWER** [comment]
Hey Roger-Man,

Thanks a lot for your feedback! Just pass it and it will use it? :)

Any idea about redis by coincidence?

**Comment by zimmerle** [comment]
Hi @HOSTED-POWER,

Redis is not yet supported. Check #1139.

**Comment by Roger-Man** [comment]
Hi @HOSTED-POWER 

Hi just pass it and the `configure` script uses it. But, Hey just don't pass it. Its so buggy and ends up in [nginx](http://nginx.org/) worker process to crash and exit. This result in user session termination with empty responses. The logs complain about 

> double free or corruption

May be thats why no one including @zimmerle answered you how to configure it for a long time. I know he actively replies the posts.
