### ISSUE TITLE
New implementation for scripting output

### ISSUE THREAD

**Issue by kavat** [SpiderLabs/ModSecurity#1145]
Hi,
to satisfy a need I had to develope a solution to execute a script from modsecurity and elaborate its output. The steps are:
- create new action (exec_ritorno)
- the request execs the script if the is matched
- the script must return a single string with format KEY=VALUE
- the string is exploded in a global variable with name KEY and value VALUE and with a further rule we can check it

Is it possible to include this in next release?
If you have some questions write me!

Thanks
Andrea

**Comment by zimmerle** [comment]
Hi @kavat,

Why not use environment variables?
