### ISSUE TITLE
POST request is not handled correctly

### ISSUE THREAD

**Issue by miwoow** [SpiderLabs/ModSecurity#115]
Nginx 1.4.1
ModSecurity 2.7.4

server {
        listen 80;
        server_name www.xxxx.co;

```
    location / {
        ModSecurityEnabled on;
        ModSecurityConfig modsecurity.conf;
        proxy_pass http://111.111.111.111:80/;
        proxy_set_header Host www.xxxx.co;
        proxy_read_timeout 180s;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
```

}

2013/06/07 16:59:34 [debug] 656#0: *4 http init upstream, client timer: 0
2013/06/07 16:59:34 [debug] 656#0: *4 http script copy: ""
2013/06/07 16:59:34 [debug] 656#0: *4 http script copy: ""
2013/06/07 16:59:34 [debug] 656#0: *4 http script copy: "Connection: close^M
"
2013/06/07 16:59:34 [debug] 656#0: *4 http script copy: "Content-Length: "
2013/06/07 16:59:34 [debug] 656#0: *4 http script var: "122"
2013/06/07 16:59:34 [debug] 656#0: *4 http script copy: "^M
"
2013/06/07 16:59:34 [alert] 656#0: *4 no upstream configuration, client: 111.111.111.111, server: blog.xxxx.co, request: "POST /wp-login.php HTTP/1.1", host: "blog.xxxx.co", referrer: "http://blog.xxxx.co/wp-login.php"

It looks like http script engine not parse proxy_**\* configure.

**Comment by jinri** [comment]
I am getting the same issue  with the same versions of Nginx-1.8.1 & ModSecurity.nginx_refactoring.
anyone have idea solved this peoblems?
