### ISSUE TITLE
Custom transformation function example

### ISSUE THREAD

**Issue by void-in** [SpiderLabs/ModSecurity#1155]
First of all, we really appreciate a wonderful project that Mod Security is. Is there an example for a custom transformation function? I searched but couldn't find any. We want to maintain the internal IP address ranges in a file according to the departments (such as 10.10.1.0/24 -> Marketing), the transform function should take the IP as input and return the department to which it is assigned. 

Would really appreciate some help as we have configured quite a few advanced rules in ModSecurity and understand all its working but haven't done any work with the library.

**Comment by zimmerle** [comment]
Hi @void-in,

I am not sure if a custom transformation is really what you want. You mentioned that you need to have the department name based on the IP address. You want to use this information for a whitelist?

**Comment by void-in** [comment]
@zimmerle Thanks for the reply. Yeah. It would be something like this:
A file having IP address to department mapping.
```
10.1.1.0/24 marketing
10.1.2.0/24 development
```
I want to match the REMOTE_ADDR to their corresponding department name and then based upon the time of access and the department name we decide whether to allow the access or deny.

**Comment by zimmerle** [comment]
There are various way to do that, for example: you can set a environment variable (or other collection) [1] to classify the ip address based on ipmatch from file [2]. later you can read this variable to classify whenever the request should be authorized or not, considering the time [3]. Other possibility is to use a Lua script: [4].

[1] https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#setvar or https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#setenv
[2] https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#ipMatchFromFile
[3] https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#time_hour
[4] https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleScript

**Comment by void-in** [comment]
@zimmerle Thank you so much. These are excellent references. Let me get onto these. Thank you once again for your time.
