### ISSUE TITLE
ModSecurity is defaulting to index.html on POST

### ISSUE THREAD

**Issue by jeremyBass** [SpiderLabs/ModSecurity#1157]
I have a question here http://unix.stackexchange.com/questions/284861/modsecurity-is-defaulting-to-index-html-on-post and the issue I keep getting is that this is rewriting the uri to have `index.html` on the end of it.   I can't find anything in the docs about this behavior.  

The issue I believe here is either the docs are not clear enough for a dev to find out what to change to prevent this or maybe it's a bug in itself as the uri does already have `index.php` in it and so it's already  clear it's a php file.

**Comment by zimmerle** [comment]
Hi @jeremyBass,

ModSecurity works in different phases of the request, depending on the phase you may get the url before it be rewritten or after. 

You can get the details about each phase in the ModSecurity reference manual:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Processing_Phases

**Comment by jeremyBass** [comment]
@zimmerle Thank you for getting back.  I'm not seeing where this is setting the url to include `index.html` .  Could you be a little more pointed please?  I appreciate the help.
