### ISSUE TITLE
Endless timeout when SecRemoteRules cannot contact the remote server

### ISSUE THREAD

**Issue by pblim** [SpiderLabs/ModSecurity#1159]
If block INPUT via iptables from remote host with rules, apache doesnt want to get up.
Process is killed:
systemd[1]: httpd.service start operation timed out. Terminating.
SecRemoteRulesFailAction isn`t work.

But if i block OUTPUT to remote host, apache starts and directive SecRemoteRulesFailAction works.
Is the difference in behavior when properly send packet and when it can not send.

**Comment by zimmerlezen** [comment]
Hi @pblim,

In the first test scenario, If you complete remove the "SecRemoteRules" apache starts fine? I am asking because it may not be related to the SecRemoteRules at all.

**Comment by zimmerle** [comment]
Hi @pblim,

In the first test scenario, If you complete remove the "SecRemoteRules" apache starts fine? I am asking because it may not be related to the SecRemoteRules at all.

**Comment by pblim** [comment]
First scenario:
iptables -A INPUT -s 204.13.202.117 -j DROP #trustwave remote host
also
iptables -A OUTPUT -d 204.13.202.117 -j DROP #trustwave remote host

Enabled:
SecRemoteRulesFailAction Warn
SecRemoteRules [key] https://dashboard.modsecurity.org/rules/download/plain

Result:
Apache doesn`t start:
systemd[1]: httpd.service start operation timed out. Terminating.
systemd[1]: httpd.service stop-final-sigterm timed out. Killing.
systemd[1]: httpd.service: main process exited, code=killed, status=9/KILL
systemd[1]: Failed to start The Apache HTTP Server.

Second scenario:
iptables -A OUTPUT -d 204.13.202.117 -j REJECT #trustwave remote host
Enabled:
SecRemoteRulesFailAction Warn
SecRemoteRules [key] https://dashboard.modsecurity.org/rules/download/plain

Result:

Apache starts fine but w/o remote rules.
[Tue Jun 14 18:34:22.842733 2016] [:notice] [pid 12162:tid 140319987071040] ModSecurity: Loaded 0 rules from: 'https://dashboard.modsecurity.org/rules/download/plain'.
[Tue Jun 14 18:34:22.842746 2016] [:notice] [pid 12162:tid 140319987071040] ModSecurity: Problems loading external resources: Failed to download: "https://dashboard.modsecurity.org/rules/download/plain" error: Couldn't connect to server. 

Third scenario:
iptables -A INPUT -s 204.13.202.117 -j DROP #trustwave remote host
also
iptables -A OUTPUT -d 204.13.202.117 -j DROP #trustwave remote host

Disabled:
SecRemoteRulesFailAction Warn
SecRemoteRules [key] https://dashboard.modsecurity.org/rules/download/plain

Result: Apache starts fine because it does not attempt to download rules

Conclusion:
In first scenario there is no response.
In second scenario SecRemotRules got answer with reject.
Probably curl timeout is longer then apache`s timeout.

**Comment by zimmerle** [comment]
Hi @pblim,

ModSecurity uses libcurl to download the rules from the remote server. Turns out that the timeout may be bigger than your systemd considers to be normal. In that case, you may want to change the timeout value from the system.d. You can check the timeout value using:

```
systemctl show apache2.service -p TimeoutStopUSec
```

[You may need to adapt it according to your distro]
