### ISSUE TITLE
Accessing TX macro within SESSION

### ISSUE THREAD

**Issue by tanshul22** [SpiderLabs/ModSecurity#1162]
I am trying to access a TX macro on the session. I am able to set the variable on the session successfully but unable to retrieve it. Is something like this possible?

```
SecAction "phase:2,pass,setvar:'session.%{TX.1}=+1',nolog,id:50000001"
SecRule SESSION:%{TX.1} "@gt 2" "phase:2,pause:250,deny,status:429,log,id:50000005"
```

**Comment by quenenni** [comment]
Here is an example with TX variable incrementing and tested later on I did in the past.
Maybe that will help you with your case:
```
SecRule REQUEST_METHOD "^POST$" "phase:1,chain,t:none,nolog,pass,setvar:tx.score=1"
  SecRule REQUEST_FILENAME "wp-admin/theme-editor.php" "chain,t:none,setvar:tx.score=+1"
  SecRule TX:SCORE "@eq 2" "ctl:ruleRemoveById=958941"
```

**Comment by tanshul22** [comment]
Thanks for your reply @quenenni. I came accross the solution using `TX` earlier but unfortunately it doesn't solve my problem. I am storing the session counts in a persistent collection and thus need to refer to it outside the scope of a `transaction`. I'm not a ModSecurity pro but I feel like there should be a way to access a dynamically set variable as I demonstrate above. To elaborate `setvar:'session.%{TX.1}=+1'` seems to work but fetching this value via `SESSION:%{TX.1}` does not.
