### ISSUE TITLE
libmodsecurity compile fails during example linking

### ISSUE THREAD

**Issue by LinuxJedi** [SpiderLabs/ModSecurity#1165]
The multithread_c example is not linking pthread which is causing the following error on CentOS 7:

```
/usr/bin/ld: multi-multi.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: note: 'pthread_create@@GLIBC_2.2.5' is defined in DSO /lib64/libpthread.so.0 so try adding it to the linker command line
```

**Comment by zimmerle** [comment]
Hi LinuxJedi,

Thank you for the report. The issue was fixed already, thanks to @phantom-az.

Commit: 767289c8daa4a0a75d52cac6cf5689b816de2edc
