### ISSUE TITLE
Application Errors thrown after ModSecurity v.2.9.1 installation on IIS 8.5

### ISSUE THREAD

**Issue by fcbenoit** [SpiderLabs/ModSecurity#1169]
I am trying to install ModSecurity v.2.9.1 on IIS 8.5 using the stock configuration.  The installation completes successfully, but after an iisreset, I see the following 6 errors in the Event Log (all with the message same):

[Application] [Information] [1] [ModSecurity] [WIN-BMJVHVOFS37]
The description for Event cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

I have uninstalled and re-installed using the verbose loggingg per the IIS Troublshooting Guide on your Wiki.  The log file is attached.

[modsecurity_log.txt](https://github.com/SpiderLabs/ModSecurity/files/328164/modsecurity_log.txt)

**Comment by zimmerle** [comment]
Hi @fcbenoit, 

You may want to see the item details. Apart from this error message, the information about the event should be listed on the details.
