### ISSUE TITLE
SecRemoteRules - ModSecurity: Error parsing actions: Unknown action: \\

### ISSUE THREAD

**Issue by jwillberg** [SpiderLabs/ModSecurity#1172]
both versions 2.9.0 & 2.9.1
[Mon Jun 27 16:12:05.018321 2016] [:notice] [pid 17018] ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/) configured.

Trying load apache - modsecurity.conf:
SecRemoteRules 576d00bb44b4c576d00bb44bc3 https://rules.malware.expert/download.php?rules=generic

Then get always this error:
ModSecurity: Found another rule with the same id

Remote rules is 1 line, id not matter which try use:
SecRule REQUEST_HEADERS:User-Agent "\<\?" 		"id:400115,t:lowercase,deny,status:500,log,msg:'Malware expert - user-agent: php execute'"

**Comment by zimmerle** [comment]
Hi @jwillberg ,

That is a know bug within Apache. See here: https://bz.apache.org/bugzilla/show_bug.cgi?id=55910

You may want to update your apache.
