### ISSUE TITLE
Possible representation bug in uploads part of JSON audit log format

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/ModSecurity#1173]
I have the following entry in the JSON audit log format:

```
...
    "uploads": {
        "info": [
            "file_size",
            48458,
            "file_name",
            "example.png",
            "content_type",
            "<Unknown Content-Type>"
        ],
        "total": 48458
    }
...
```
Within the info tag, there is a list of items and not a list of key-value pairs as would be expected. It might have to do with the way the data is represented within ModSecurity (-> corresponding native audit log format part "J" is a CSV), but this seems to be a bug to me.

**Comment by zimmerle** [comment]
Linking this issue with #1174, as they seems to be on the same piece of code.

**Comment by p0pr0ck5** [comment]
Not the same issue as #1174, but looks like an easy fix. `msc_logging.c:1363` opens this with `yajl_gen_array_open` instead of `yajl_gen_map_open`. Not sure why I did this :p I'll have a PR for this within a day or two.

**Comment by zimmerle** [comment]
Thanks @p0pr0ck5 ;)

**Comment by dune73** [comment]
Thank you guys.

**Comment by p0pr0ck5** [comment]
@dune73 can you try the fix in https://github.com/p0pr0ck5/ModSecurity/commit/e54b1504fc0105248b874b4f50b3f9614c347679? I won't have time to test for a bit but this should resolve the issue, small oversight on my part. We don't log file upload data so I wasn't as thorough as I should have been.

**Comment by p0pr0ck5** [comment]
^ Once this is tested I'll submit the PR

**Comment by dune73** [comment]
Looks good here:

```
    "uploads": {
        "info": [
            {
                "content_type": "<Unknown Content-Type>",
                "file_name": "tmp1",
                "file_size": 457
            }
        ],
        "total": 457
    }

```

Thank you for the quick fix.

**Comment by zimmerle** [comment]
Pull request #1181 was merged! thanks!
