### ISSUE TITLE
Fail to get remote rules.

### ISSUE THREAD

**Issue by acmonde** [SpiderLabs/ModSecurity#1183]
I have used directive
 SecRemoteRules [key] https://dashboard.modsecurity.org/dashboard/rules/download/plain
in the file "modsecurity_crs_10_setup.conf.example."
I received a massage:
 "ModSecurity: SecRemoteRules: ModSecurity was not compiled with SecRemoteRules support." 
when I restarted Apache serve. What's wrong with that?

**Comment by zimmerle** [comment]
Hi @acmonde,

The support for SecRemoteRules is optional in ModSecurity. During the compilation phase you can choose to enable or disable it. If you have libCurl-dev packages installed it will be enabled by default.
You need to recompile your ModSecurity with support to SecRemoteRules.

**Comment by acmonde** [comment]
Thank you for replying! Could you tell me the exact operating to enable the SecRemoteRule?

**Comment by acmonde** [comment]
Thank you for replying! Could you tell me the exact operating to enable the SecRemoteRule?

**Comment by acmonde** [comment]
@zimmerle Thank you for replying! Could you tell me the exact operating to enable the SecRemoteRules? Should I decrypt ?

**Comment by zimmerle** [comment]
@acmonde did you compiled ModSecurity by your self? or are you using your distribution packages?

**Comment by acmonde** [comment]
@zimmerle  OK, I will try it. Thank you!

**Comment by acmonde** [comment]
@zimmerle Could you tell me how to check if I download the rules? I review the code and I find the &downloaded_content is NULL in the function msc_remote_download_content(mp, remote_rules_server->uri,remote_rules_server->key, &downloaded_content, error_msg);

**Comment by zimmerle** [comment]
Hi @acmonde,

You should have a notification in your error logs, saying that the rules were loaded successfully. It also tells you how many rules were loaded. There is no need to patch the code.

**Comment by acmonde** [comment]
@zimmerle Thank you for responsing me paciently. I have donwloaded the rules. The reason is the uri from email is wrong. I used the uri from dashboard and finished it.
