### ISSUE TITLE
ModSecurity 2.9.1 is not compiling with curl 7.49.1

### ISSUE THREAD

**Issue by Elavarasan83** [SpiderLabs/ModSecurity#1184]
Mod security 2.9.1 is not compiling when latest libcurl version(curl-7.49.1) is used.
libcurl generates libcurl_imp.lib but mod security is looking for libcurl.lib
Does Mod security 2.9.1 works with curl-7.49.1? If yes then is it enough to change the curl library file name in the makefile.win( $(CURL)\libcurl.lib to $(CURL)\libcurl_imp.lib).
Please clarify.

**Comment by zimmerle** [comment]
Hi @Elavarasan83, 

Are you trying to compile ModSecurity for Windows? It should be workable on a variate of version of libCurl, how you are trying to compile it?

**Comment by Elavarasan83** [comment]
Hi zimmerle,
Thanks for the response.

Yes, l'm compiling for windows. Curl generates libcurl_imp.lib. Modsecurity is looking for libcurl.lib. After changing the curl library file name in modsecurity make file, the compiltion is successful.
Is curl necessary for modsecurity? Can we compile modsecurity without curl?
