### ISSUE TITLE
bad memory access in collection store

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1188]
version from trunk, compiled on Windows x64 (VC14) for httpd 2.4.23.
persist_dbm.c, collection_store(), line 528
   blob[blob_offset + 2 + len - 1] = '\0';
   => Exception 0xC0000005: Access violation reading location 0x000000005F5F4E41

var    0x0000000012f571f8 {
 name=0x0000000012f57598 "__name"
 name_len=318076280
 value=0x000000005f5f4e41 <Error reading characters of string.>
 value_len    318076360    unsigned int
}

This is for a custom counter using only numerics (increment only):
te[i].key   0x0000000012f4afd8 "blocked"

var->value points to an invalid memory location.
Btw, is it normal that name_len is incorrect?

How to troubleshoot this?

**Comment by zimmerle** [comment]
Hi @marcstern,

The first thing that we have to check is if the version of APR that was used during the compilation and/or loading time is the same one that was used by Apache. The version mismatch may lead to problems like this one that you have. During the startup of ModSecurity, it prints out those version numbers in the error_log. Can you check?

**Comment by marcstern** [comment]
APR compiled version="1.5.2"; loaded version="1.5.2"

**Comment by zimmerle** [comment]
Hi @marcstern,

It seems that the version is right. What about the compilation flags? Apr, Apache and ModSecurity were compiled by you?

**Comment by marcstern** [comment]
Same compile options for all modules/dll (same problem without debug and full optimisation).

CL options:
/RTCc /MP /FR"Debug\" /GS /Zc:rvalueCast- /Qpar- /W3 /wd"4100" /wd"4133" /wd"4244" /wd"4267" /wd"4311" /wd"4312" /wd"4710" /wd"4711" /wd"4820" /wd"4996" /Gy /FAu /Zc:wchar_t /guard:cf /Zi /Gm- /Od /Ob0 /sdl- /fp:precise /D "_CRT_SECURE_NO_WARNINGS" /D "_WIN32_WINNT=0x0600" /D "WINDOWS" /D "_WINDLL" /D "_WIN64" /D "WIN64" /D "_WIN32" /D "WIN32" /D "x_UNICODE" /D "xUNICODE" /D "NOCOMM" /D "NOKANJI" /D "NOMCX" /D "NOHELP" /D "NOPROFILER" /D "NOSOUND" /D "_DEBUG" /fp:except /errorReport:prompt /GF- /WX- /Zc:forScope /RTC1 /GR- /arch:AVX /Gd /Oy- /MDd /openmp- /Fa"Debug\" /nologo /Fo"Debug\"

LINK options:
/ALLOWBIND /MANIFEST /NXCOMPAT /FUNCTIONPADMIN:6 /DYNAMICBASE:NO "advapi32.lib" "comctl32.lib" "comdlg32.lib" "gdi32.lib" "iphlpapi.lib" "kernel32.lib" "mswsock.lib" "rpcrt4.lib" "shell32.lib" "user32.lib" "uuid.lib" "winspool.lib" "wldap32.lib" "ws2_32.lib" "wtsapi32.lib" "ole32.lib" "oleaut32.lib" "odbc32.lib" "odbccp32.lib" /RELEASE /LARGEADDRESSAWARE /IMPLIB:"Debug\libaprutil-1.lib" /DLL /LTCG:NOSTATUS /MACHINE:X64 /WINMD:NO /WX:NO /OPT:NOREF /SAFESEH:NO /CLRSupportLastError /INCREMENTAL:NO /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /OPT:NOICF /ERRORREPORT:PROMPT /CLRUNMANAGEDCODECHECK /NOLOGO /TSAWARE:NO /ASSEMBLYDEBUG:DISABLE /TLBID:1 /DELAYSIGN:NO

**Comment by zimmerle** [comment]
Hi @marcstern,

I was not able to reproduce your problem, did you managed to reproduce the same problem/error in another computer?

**Comment by marcstern** [comment]
Related to a combination of compile options. Not sure which ones :-(
