### ISSUE TITLE
Rules id conflict check does not work between multiple added rulesets

### ISSUE THREAD

**Issue by p0pr0ck5** [SpiderLabs/ModSecurity#1192]
When two rulesets are merged via multiple calls to `msc_rules_add_(file/remote)`, the checks done in `parser/driver.cc` do not adequately check for duplicate rule IDs since it appears to only check the newly added rules. For example:

rules.conf:
```
SecRule ARGS:foo bar "id:12345,deny,phase:1"
```

rules2.conf:
```
SecRule ARGS:foo bar "id:12345,deny,phase:1"
```

Adding the second rule file (or a duplicate call to a single rule string via `msc_rules_add`) does not error; indeed, none of the parser checks would work between multiple merged sets as a result of the existing design. Is this intended?

**Comment by zimmerle** [comment]
Closed.
