### ISSUE TITLE
SecDataDir in VirtualHost

### ISSUE THREAD

**Issue by RaphaelDG** [SpiderLabs/ModSecurity#1194]
Hi,
I'm trying to configure ModSecurity in a virtualhost environment. 
Everything is okay, but I still have a problem that I don't understand.  

`Message: collection_retrieve_ex: Unable to retrieve collection (name "global", key "global"). Use SecDataDir to define data directory first.
Message: collection_retrieve_ex: Unable to retrieve collection (name "ip", key "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"). Use SecDataDir to define data directory first.`

Okay right, I need to configure SecDataDir, but when I want to restart apache with SecDataDir configured, I have the following error: " SecDataDir is not allowed with Virtual Host".

I searched in different ways but I didn't find a working solution.

Thanks you very much.

**Comment by zimmerle** [comment]
Hi @RaphaelDG,

In additional to the virtual hosting, are you using apache with any kind of chroot environment?

**Comment by RaphaelDG** [comment]
Hi @zimmerle 
Yes I'm using apache in chroot environment and this is the only way.

**Comment by RaphaelDG** [comment]
Any help?

**Comment by zimmerle** [comment]
Hi @RaphaelDG,

Make sure the path that you are using also exists inside the chroot. Otherwise it will not find the path to the file

**Comment by RaphaelDG** [comment]
@zimmerle if you speak about the path declared with SecDataDir it's impossible for me because I can't use this directive.
Other path for audit.log and error.log are corrects.

**Comment by zimmerle** [comment]
This directive needs to be specified on the "global"  configuration, inside your chroot you have to have the path available.

**Comment by victorhora** [comment]
Closing this one because of lack of feedback from reporter. Assuming issue is solved, if not please let us know and we will reopen it.
