### ISSUE TITLE
add functionality

### ISSUE THREAD

**Issue by shrv** [SpiderLabs/ModSecurity#1195]
Good afternoon.

I would like to express the wish to add functionality.

I faced on a number of resources with such a situation, when the valid requests, with a sufficiently large number of parameters and their values for a long time are processed on the WAF. Is it possible to add functionality exemption request and to request further on the basis of the processing time?

**Comment by zimmerle** [comment]
Hi @shrv,

Can you give us a detailed example? It will be easy for us to classify whenever this exception should be handled by ModSecurity core or by the rules.

**Comment by shrv** [comment]
I am sorry that the answer for a long time.

Example:

Request Details
H E A D E R
POST /test9/release19/ConstructorService.svc/File?type=apphtm&__uid=17&sid=da090c1c-8893-4164-9bac-29f7530152d2 HTTP/1.0
X-Security: 1
Host: test.example.com
X-Real-IP: xx.xx.xx.xx
X-Forwarded-Host: test.example.com
X-Forwarded-Server: test.example.com
X-Forwarded-For: xx.xx.xx.xx
Connection: close
Content-Length: 122764
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:49.0) Gecko/20100101 Firefox/49.0
Accept: */*
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Referer: https://test.example.com/test9/Release19/app.htm
Cookie: CP=NPO.10.106.65.22.636106536149945752; kd-q={"q":"AuthKey_Demo_kolya_kolya","v":1,"t":636106545027050014,"name":"kd-q"}; CID=W+5QDlfra0aXerp9BgjRAg==; baseUrl=https://test.example.com/test9/release19/ConstructorService.svc/; kd-ticket=c0d26a21-4b30-427e-acfa-980d278bf061; download1475046743669=1
B O D Y
JTNDIURPQ1RZUEUlMjBodG1sJTNFJTBBJTNDaHRtbCUzRSUzQ2hlYWQlM0UlMEElM0NtZXRhJTIwY2hhcnNldCUzRCUyMnV0Zi04JTIyJTNFJTBBJTNDbWV0YSUyMGtleXdvcmRzJTNEJTIyQ1BDRF9XQVRFUk1BUkslMjIlM0UlMEElM0NtZXRhJTIwbmFtZSUzRCUyMnZpZXdwb3J0JTIyJTIwY29udGVudCUzRCUyMndpZHRoJTNEZGV2aWNlLXdpZHRoJTJDJTIwaW5pdGlhbC1zY2FsZSUzRDEuMCUyMiUzRSUwQSUzQ21ldGElMjBodHRwLWVxdWl2JTNEJTIyWC1VQS1Db21wYXRpYmxlJTIyJTIwY29udGVudCUzRCUyMklFJTNEZWRnZSUyMiUzRSUwQSUzQ3RpdGxlJTNFJUQwJTlBJUQwJUJFJUQwJUJEJUQxJTgxJUQxJTgyJUQxJTgwJUQxJTgzJUQwJUJBJUQxJTgyJUQwJUJFJUQxJTgwJTIwJUQwJUI0JUQwJUJFJUQwJUIzJUQwJUJFJUQwJUIyJUQwJUJFJUQxJTgwJUQwJUJFJUQwJUIyJTIwJUQwJTlBJUQwJUJFJUQwJUJEJUQxJTgxJUQxJTgzJUQwJUJCJUQxJThDJUQxJTgyJUQwJUIwJUQwJUJEJUQxJTgyJUQwJTlGJUQwJUJCJUQxJThFJUQxJTgxJTIwJTNDJTJGdGl0bGUlM0UlMEElM0NsaW5rJTIwcmVsJTNEJTIyc2hvcnRjdXQlMjBpY29uJTIyJTIwaHJlZiUzRCUyMmZhdmljb24uaWNvJTIyJTIwdHlwZSUzRCUyMmltYWdlJTJGeC1pY29uJTIyJTNFJTBBJTNDc2NyaXB0JTIwc3JjJTNEJTIyc2NyaXB0Lm1pbi5qcyUyMiUzRSUzQyUyRnNjcmlwdCUzRSUwQSUwQSUzQ2xpbmslMjByZWwlM0QlMjJzdHlsZXNoZWV0JTIyJTIwaHJlZiUzRCUyMmZpbmFsLmNzcyUyMiUyMHR5cGUlM0QlMjJ0ZXh0JTJGY3NzJTIyJTNFJTBBJTBBJTBBJTBBJTNDc2NyaXB0JTIwaWQlM0QlMjJ0cGwtdmlldyUyMiUyMHR5cGUlM0QlMjJ0ZXh0JTJGeC1qcXVlcnktdG1wbCUyMiUzRSUwQSUzQ2RpdiUyMGlkJTNEJTIyJTdCJTdCJTNBdWlkJTdEJTdEJTIyJTNFJTNDJTJGZGl2JTNFJTBBJTNDJTJGc2NyaXB0JTNFJTBBJTNDc2NyaXB0JTIwaWQlM0QlMjJ0cGwtY29udGV4dG1lbnUlMjIlMjB0eXBlJTNEJTIydGV4dCUyRngtanF1ZXJ5LXRtcGwlMjIlM0UlMEElM0NkaXYlMjBpZCUzRCUyMiU3QiU3QiUzQXVpZCU3RCU3RCUyMiUyMGNsYXNzJTNEJTIyY29udGV4dE1lbnUlMjBoaWRkZW4lMjIlM0UlMEElN0IlN0Jmb3IlMjBpdGVtcyU3RCU3RCUwQSU3QiU3QmlmJTIwJTIzZGF0YSUyMCUzRCUzRCUyMCUyMi0lMjIlN0QlN0QlMEElM0NkaXYlMjBjbGFzcyUzRCUyMmNvbnRleHRNZW51LXNwbGl0dGVyJTIyJTNFJTNDJTJGZGl2JTNFJTBBJTdCJTdCZWxzZSU3RCU3RCUwQSUzQ2RpdiUyMGNsYXNzJTNEJTIyY29udGV4dE1lbnUtaXRlbS0lN0IlN0IlM0FpZCU3RCU3RCUyMGNvbnRleHRNZW51LWl0ZW0lN0IlN0JpZiUyMGRpc2FibGVkJTdEJTdEJTIwZGlzYWJsZWQlN0IlN0IlMkZpZiU3RCU3RCUyMiUzRSUwQSU3QiU3QmlmJTIwY2hlY2tlZCU3RCU3RCUyMCUyMCUyMCUyMCUyMCUzQ2RpdiUyMGNsYXNzJTNEJTIya2QtdGljayUyMiUzRSUzQyUyRmRpdiUzRSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3QiU3QiUyRmlmJTdEJTdEJTBBJTdCJTdCaWYlMjByYWRpbyU3RCU3RCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ2RpdiUyMGNsYXNzJTNEJTIya2QtcmFkaW8lMjIlM0UlM0MlMkZkaXYlM0UlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0IlN0IlMkZpZiU3RCU3RCUwQSU3QiU3QmlmJTIwZXhjbGFtYXRpb24lN0QlN0QlMjAlM0NkaXYlMjBjbGFzcyUzRCUyMmtkLWV4Y2xhbWF0aW9uJTIyJTNFJTNDJTJGZGl2JTNFJTIwJTIwJTdCJTdCJTJGaWYlN0QlN0QlMEElN0IlN0IlM0FsYWJlbCU3RCU3RCUwQSUzQyUyRmRpdiUzRSUwQSU3QiU3QiUyRmlmJTdEJTdEJTBBJTdCJTdCJTJGZm9yJTdEJTdEJTBBJTNDJTJGZGl2JTNFJTBBJTNDJTJGc2NyaXB0JTNFJTBBJTBBJTNDc2NyaXB0JTIwaWQlM0QlMjJ0cGwtYnV0dG9uJTIyJTIwdHlwZSUzRCUyMnRleHQlMkZ4LWpxdWVyeS10bXBsJTIyJTNFJTBBJTNDc3BhbiUyMGlkJTNEJTIyJTdCJTdCJTNBdWlkJTdEJTdEJTIyJTIwY2xhc3MlM0QlMjIlN0IlN0JpZiUyMHN0eWxlJTdEJTdEa2QtYnV0dG9uLS0lN0IlN0IlM0FzdHlsZSU3RCU3RCU3QiU3QmVsc2UlN0QlN0RrZC1idXR0b24lN0IlN0IlMkZpZiU3RCU3RCUyMCU3QiU3QiUzQWNzc0NsYXNzJTdEJTdEJTIwJTdCJTdCaWYlMjBkaXNhYmxlZCU3RCU3RGtkLWJ1dHRvbi0tZGlzYWJsZWQlN0IlN0IlMkZpZiU3RCU3RCUyMiUyMHN0eWxlJTNEJTIyJTdCJTdCaWYlMjAhdmlzaWJsZSU3RCU3RGRpc3BsYXklM0Fub25lJTNCJTdCJTdCJTJGaWYlN0QlN0QlN0IlN0JpZiUyMGNzcyU3RCU3RCU3QiU3QiUzQWNzcyU3RCU3RCU3QiU3QiUyRmlmJTdEJTdEJTIyJTIwJTdCJTdCaWYlMjB0aXRsZSU3RCU3RHRpdGxlJTNEJTIyJTdCJTdCJTNBdGl0bGUlN0QlN0QlMjIlN0IlN0IlMkZpZiU3RCU3RCUzRSUwQSU3QiU3QmlmJTIwbGVmdEljb24lN0QlN0QlM0NzcGFuJTIwY2xhc3MlM0QlMjJrZC1idXR0b25fX2ljb24lMjBpY28tJTdCJTdCJTNBbGVmdEljb24lN0QlN0QlMjIlM0UlM0MlMkZzcGFuJTNFJTdCJTdCJTJGaWYlN0QlN0QlMEElN0IlN0JpZiUyMGljb24lN0QlN0QlM0NzcGFuJTIwY2xhc3MlM0QlMjJrZC1idXR0b25fX2ljb24tc3ltJTIwaWNvLSU3QiU3QiUzQWljb24lN0QlN0QlMjIlM0UlM0MlMkZzcGFuJTNFJTdCJTdCJTJGaWYlN0QlN0QlMEElN0IlN0IlM0F0ZXh0JTdEJTdEJTBBJTdCJTdCaWYlMjByaWdodEljb24lN0QlN0QlM0NzcGFuJTIwY2xhc3MlM0QlMjJrZC1idXR0b25fX2ljb24lMjBpY28tJTdCJTdCJTNBcmlnaHRJY29uJTdEJTdEJTIyJTNFJTNDJTJGc3BhbiUzRSU3QiU3QiUyRmlmJTdEJTdEJTBBJTNDJTJGc3BhbiUzRSUwQSUzQyUyRnNjcmlwdCUzRSUwQSUzQ3NjcmlwdCUyMGlkJTNEJTIydHBsLXNlYXJjaGJveCUyMiUyMHR5cGUlM0QlMjJ0ZXh0JTJGeC1qcXVlcnktdG1wbCUyMiUzRSUwQSUzQ2RpdiUyMGNsYXNzJTNEJTIybXRiX19zZWFyY2gtY29udGFpbmVyJTIyJTIwaWQlM0QlN0IlN0IlM0F1aWQlN0QlN0QlM0UlMEElM0NpbnB1dCUyMGNsYXNzJTNEJTIybXRiX19zZWFyY2gtaW5wdXQlMjIlMjB0

Response Details
H E A D E R
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-
Content-Length: 182
Cache-Control: private
Set-Cookie: baseUrl=https://test.example.com/test9/release19/ConstructorService.svc/; path=/
Connection: close

Performance timings	Duration: 103764.198 msec 
Combined: 103755.901 msec 
Phase 1: 0.402 msec 
Phase 2: 103753.761 msec 
Phase 3: 0.002 msec 
Phase 4: 0.084 msec 
Phase 5: 1.652 msec 
Storage read: 0.086 msec 
Storage write: 0 msec 
Logging: 0 msec 
Garbage collection: 0 msec


Offer №2

Enter the concept of a list of processed cookies
In order that the rules would be checked and processed only cookies that resource, and the rest ignored. Because, even if they were present is 'bad' request, they are still ignored by the server and not processed. If necessary I can give an example from one of the resource indicating the list of its cookies and

**Comment by zimmerle** [comment]
Hi @shrv,

You may want to look at:
 - https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#perf_rules

**Comment by shrv** [comment]
Oh, I am very inattentive
Thank you!

On the question №2 can I say?

> Enter the concept of a list of processed cookies
In order that the rules would be checked and processed only cookies that resource, and the rest ignored. Because, even if they were present is 'bad' request, they are still ignored by the server and not processed. If necessary I can give an example from one of the resource indicating the list of its cookies and

**Comment by zimmerle** [comment]
Hi @shrv,

We cannot not foresee which cookie will be used by an unknown application, therefore, there is no way to process only what is in use. Since we don't know what is in use. Also, even if it is not expected to be used, it may be used to transport, for instance, a payload. Thus, the inspection will be mandatory.

**Comment by shrv** [comment]
@zimmerle good afternoon
I understand you, I had not thought about this option.
Then of course my bad option.
Thank you for your answers, please close this conversion

Thank you for what you do :)
