### ISSUE TITLE
ModSecurity-nginx_refactoring block http POST 

### ISSUE THREAD

**Issue by smashpunk** [SpiderLabs/ModSecurity#1196]
I'm using ModSecurity-nginx_refactoring with Nginx 1.10.x on AWS.
However, I find if set SecRequestBodyAccess On, then the POST will be failed.
the log is as below

2016/07/28 09:39:33 [error] 1361#0: [client 10.64.1.48] ModSecurity: Warning. Operator EQ matched 1 at SESSION:IS_NEW. [file "/usr/local/nginx/conf/owasp-modsecurity-crs/optional_rules/modsecurity_crs_16_session_hijacking.conf"] [line "24"] [id "981054"] [msg "Invalid SessionID Submitted."] [hostname ""] [uri "/man/system/moveIndex.xhtml"] [unique_id "AcAfAcAcAcAc1JAcscAlhcKc"]
2016/07/28 09:39:33 [alert] 1361#0: *219 no upstream configuration, client: 10.64.1.48, server: XXXX, request: "POST /man/system/moveIndex.xhtml HTTP/1.1", host: "XXXX:YYYY", referrer: "http://XXXX:YYYY/man/page/system/login.jsp"

I've check the issues in this repository, however, seems no certain resolution. Any idea?

**Comment by zimmerle** [comment]
Closing as it seems to be a duplicate of #748

**Comment by smashpunk** [comment]
@zimmerle  actaully, I've used the package from https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring to compile with nginx 1.10.1 before I report my issue.
every post will be blocked...
I've tried to compile refactoring modsecurity with nginx 1.8 and 1.6, they ran into the same issue also.
