### ISSUE TITLE
Is this a mistake?

### ISSUE THREAD

**Issue by freebird2016** [SpiderLabs/ModSecurity#1197]
In version 2.9.1-RC-1 , file standalone/api.c , lines 446 , there is ap_add_input_filter("HTTP_IN", NULL, r, r->connection) and no ap_pass_brigade function and ap_remove_input_filter(f). Is that means no using of function ap_http_in_filter that register in ap_register_input_filter("HTTP_IN", ap_http_in_filter, NULL, AP_FTYPE_RESOURCE) or I am wrong ?

**Comment by zimmerle** [comment]
Hi @freebird2016,

You can paste here the links for the code hosted on Github, also you can highlight the lines that you think is important for the understanding of your question. That way will be easy to understand your question.

**Comment by freebird2016** [comment]
Hi zimmerle,
https://github.com/SpiderLabs/ModSecurity/blob/master/standalone/api.c
    In lines 446
    ap_filter_t *f = ap_add_input_filter("HTTP_IN", NULL, r, r->connection);
    apr_bucket_brigade* bb_out;
    status = hookfn_fixups(r);
    ap_remove_input_filter(f);
there is only add_input_filter and  remove_input_filter. Is the filter named HTTP_IN used? 
Thanks

**Comment by zimmerle** [comment]
Hi @freebird2016,

That is the filter used to make the request body inspection.
