### ISSUE TITLE
Syntax error in modsecurity_crs_16_session_hijacking.conf

### ISSUE THREAD

**Issue by Organic-Marble** [SpiderLabs/ModSecurity#1199]
In this line 

```
SecRule &SESSION:SESSIONID "@eq 1" "chain,phase:5,id:'981063',nolog,pass,t:none"
        SecRule REMOTE_ADDR "^(\d{1,3}\.\d{1,3}\.\d{1,3}\.)"  "chain,nolog,capture,t:none"
        SecRule TX:1 ".*" "chain,t:sha1,t:hexEncode,setvar:session.ip_hash=%{matched_var}"

```
The string [chain,] immediately before the [t:sha1] causes an error.  Removing the erroneous string fixes it.

This appeared in my server config after I updated from Ubuntu 14.04 to 16.04

**Comment by p0pr0ck5** [comment]
@Organic-Marble may I suggest you update your rulesets to the latest available from https://github.com/SpiderLabs/owasp-modsecurity-crs/commits/master/optional_rules/modsecurity_crs_16_session_hijacking.conf? The issue you're noting was fixed over two and a half years ago (see https://github.com/SpiderLabs/owasp-modsecurity-crs/commit/e2fbef4ce89fed0c4dd338002b9a090dd2f6491d) :)

**Comment by Organic-Marble** [comment]
Thanks! I have ver 2.2.9 which is what is at the link you pointed me 
to.  Ubuntu must be picking up an old version of some of the rules in a 
repo.

**Comment by csanders-git** [comment]
2.2.9 has been a rolling release for some time. You may expect it to be made legacy quite soon.

**Comment by Organic-Marble** [comment]
Thanks! Did a compare, found a few differences, updating.  Really 
appreciate your reply.
Bill

**Comment by csanders-git** [comment]
@Organic-Marble keep an eye on the v3.0.0 branch. As this is where the real work is done.

**Comment by Organic-Marble** [comment]
Copy that!  Thanks again.
