### ISSUE TITLE
JSON parser handle is not released

### ISSUE THREAD

**Issue by eff7** [SpiderLabs/ModSecurity#1201]
Hello,

when using ModSecurity with JSON parsing enabled, we identified a significant memory leak.

It appears that when using the JSON parser to parse request body, a yajl handle is allocated using `yajl_alloc`, but is never reased. The function `json_cleanup` in `msc_json.c` does not clean up anything.

the suggested fix is below: (in `apache2/msc_json.c`  line 308)
```
/**
 * Frees the resources used for JSON parsing.
 */
apr_status_t json_cleanup(modsec_rec *msr) {
    msr_log(msr, 4, "JSON: Cleaning up JSON results");
	if (msr->json->handle != NULL) {
		yajl_free(msr->json->handle);
		msr->json->handle = NULL;
	}

    return 1;
}
```
Thanks

**Comment by zimmerle** [comment]
Hi @eff7,

Thank you! Do you want to send it in a format of a pull request?

**Comment by eff7** [comment]
@zimmerle created pull request.

**Comment by zimmerle** [comment]
@eff7

Thanks!
