### ISSUE TITLE
Using pause in SecRule causes segmentation fault

### ISSUE THREAD

**Issue by tomsommer** [SpiderLabs/ModSecurity#1203]
Using "pause:2000" in SecDefaultAction works fine, using it in SecRule causes a segmentation fault when triggered.

Example:
`SecRule REQUEST_HEADERS:User-Agent "test" "id:1,pause:2000"`

Using modsecurity-2.9.1 in Apache 2.4.20

**Comment by zimmerle** [comment]
Hi @tomsommer,

I was not able to reproduce it here. Do you mind to share your debug logs?

Also, can you paste here the versions of APR that you are using (Loaded and Compiled)? There is a message in your error_log, just after start Apache that contains the version of all dependencies.

**Comment by tomsommer** [comment]
> [Mon Aug 22 09:30:18.011148 2016] [:notice] [pid 554314] ModSecurity: APR compiled version="1.3.9"; loaded version="1.5.2"

Debug log just stops after it hits the pause rule, not seeing any error.

**Comment by tomsommer** [comment]
tried with

```
[Mon Aug 29 10:25:39.010134 2016] [:notice] [pid 649877] ModSecurity: APR compiled version="1.5.2"; loaded version="1.5.2"
[Mon Aug 29 10:25:39.010141 2016] [:notice] [pid 649877] ModSecurity: PCRE compiled version="7.8 "; loaded version="7.8 2008-09-05"
[Mon Aug 29 10:25:39.010149 2016] [:notice] [pid 649877] ModSecurity: LIBXML compiled version="2.7.6"
```

Same problem

**Comment by zimmerle** [comment]
Hi @tomsommer,

Those mismatch problems could be very trick. Make sure that you have a really empty environment before compile ModSecurity with the new APR.

The APR mismatch may be leading you to the segfault. I tested it here and I was not able to reproduce the problem. Do you have other machine to test? Can you cleanup those older versions of APR before continue with the tests?

**Comment by tomsommer** [comment]
I tried with a clean APR. This segfaults every time:

```
  SecDefaultAction "status:406,phase:2,deny"
  SecRule REQUEST_HEADERS:User-Agent "curl" "id:2,pause:2000"
```

This works:
```
  SecDefaultAction "status:406,phase:2,deny"
  SecRule REQUEST_HEADERS:User-Agent "curl" "id:2,pause:2000,deny"
```

**Comment by zimmerle** [comment]
Hi @tomsommer,

Can you run your Apache inside GDB?

There are some info on how to do it here: https://github.com/SpiderLabs/ModSecurity/wiki/Debugging-ModSecurity#running-gdb
