### ISSUE TITLE
Performance issue with large XML or JSON in body

### ISSUE THREAD

**Issue by eff7** [SpiderLabs/ModSecurity#1205]
Hi,
When a POST request contains very large (e.g. millions of nodes) XML or JSON data _AND_ the xml/json parser is enabled, there is a considerable performance hit. a message containing a few megabytes of data can take minutes to process.
Both are related to target evaluation from slightly different locations.

**XML** - when a rule contains a target of XML:/* , the process of collecting the text from all nodes is repeated for each rule - this is the place where time is consumed.
**JSON** - when a rule contains a target of ARGS, the process of creating args from all json elements is repeated for each rule.

I think a caching mechanism for rule targets, can solve the issue. If the target collection after parsing is cached for the lifetime of each phase, it would need to be performed only once.

What do you think? Is this a direction worth following? Are there other ways to solve this problem?

**Comment by zimmerle** [comment]
Hi @eff7,

IMHO the better way to handle the XML and JSON parser will be to have it in streamer. The streamer will really speedup the things. I don't think it will help the 2.x too much due to its architecture, but definitely it will be a big improvement for 3.x. What do you think?

**Comment by eff7** [comment]
Hi @zimmerle ,

As far as I understand, streaming may help the parsing phase (I see json parsing is already using the streaming model).
In the scenario I  described, the parsing itself does not have a big impact since it only happens once per message. after that, you have a json/xml object attached to the request.

the large overhead is when each rule accesses this object to retrieve the same information over and over (like the json converted to ARGS table).
this has a big impact when the content contains many nodes. we decided not to use json parsing for this reason.
i believe that caching this ARGS table (or any other target that was created) will be a great time saver.
when i cached the output of XML:/* processing time for a large file went from 25 min to 10 sec.

i see there is a caching for transformations, but this happens after target construction. the caching i refer to would cache the target values themselves.

**Comment by zimmerle** [comment]
Hi @eff7,

I am assuming that you are using version 2.x, right?

**Comment by eff7** [comment]
@zimmerle ,

Yes. does vesion 3 behave differently?

**Comment by zimmerle** [comment]
@eff7, yep. In version 3 the values are save into a hashtable for further access, however, we are not supporting the stream method yet. It is important to not keep the entire request body in memory.

**Comment by eff7** [comment]
@zimmerle ,
maybe i am not expessiong it right ...
there is no problem with the size of the message itself. large requests are processed just fine in most cases. the issue i am facing is that each rule processing will create the rule targets again from the raw (or parsed) info.

many targets - and json body content is an example - do not change across rules.
creating the target table is itself time consuming for the specific targets i pointed out (see my first post)

is the ARGS table saved across rules in version 3? this would help a lot.
XML is a bit more tricky since the value depends on the xpath. but in many cases you want the full content (/*), so this could be saved also.

**Comment by zimmerle** [comment]
Hi @eff7,

Yes, the table is saved and re-used among the different phases. Keep the buffer to process the request body when it is all there may be very expensive. Depending on the server, and amount of request per second, that may be the most expensive operation in v3. It worth to implement it in stream, using 0 buffers. Using only the buffers that are provided by the webserver.

In your specific case, upgrade to ModSecurity version 3 maybe a good thing. In our load tests, the caching for transformation was not a good idea in all the cases, depending on the transformation the cache was more expensive than the transformation itself.
