### ISSUE TITLE
Rule message leaks to other transaction

### ISSUE THREAD

**Issue by zyongqing** [SpiderLabs/ModSecurity#1206]
## Testing

When we use the rule which in `modsecurity_crs_20_protocol_violations.conf` for tesing:

```
SecRule REQUEST_URI "\%((?!$|\W)|[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})" \
        "chain,phase:2,rev:'2',ver:'OWASP_CRS/2.2.9',maturity:'6',accuracy:'8',t:none,block,msg:'URL Encoding Abuse Attack Attempt',
id:'950107',tag:'OWASP_CRS/PROTOCOL_VIOLATION/EVASION',severity:'4'"
        SecRule REQUEST_URI "@validateUrlEncoding" "setvar:'tx.msg=%{rule.msg}',setvar:tx.anomaly_score=+%{tx.warning_anomaly_score}
,setvar:tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/EVASION-%{matched_var_name}=%{matched_var}"
```
### First payload

`GET /dataproxy.jsp?webname=%A5 HTTP/1.1`

m_rulesMessages in transaction count `0`
### Second payload

`GET /dataproxy.jsp?webname=%AZ HTTP/1.1`

m_rulesMessages in transaction count `1`
### Third payload

Then we submit first payload again:
`GET /dataproxy.jsp?webname=%A5 HTTP/1.1`

m_rulesMessages in transaction count `1`

The rulesMessages leaks from second payload to third payload :(
## Analyze

We check the source code and find:

```
rule.cc

bool Rule::evaluate(Transaction *trasn) {
...
    if ((!m_log_message.empty() || !m_log_data.empty())
            && !ruleMessage->m_match.empty()) {
            ruleMessage->m_data = m_log_data;
            trasn->m_rulesMessages.push_back(ruleMessage);
        } else {
            delete ruleMessage;
    }
...
}
```

When second payload evaluated, m_log_message set the message and leaks to third payload.
When third payload running, first rule return 1. Whatever chain rule result return,  trasn->m_rulesMessages.push_back will be invoked.

**Comment by zimmerle** [comment]
Rule messages got a huge refactoring, this is no longer a problem.
