### ISSUE TITLE
`utf8toUnicode` buffer misallocation

### ISSUE THREAD

**Issue by katef** [SpiderLabs/ModSecurity#1208]
The `utf8toUnicode` transformation function reads utf8 sequences and formats out codepoints as hex sequences.

We are considering the C implementation here:
https://github.com/SpiderLabs/ModSecurity/blob/046b5537368c2a5c3ef9c25b64f0041d3932b373/apache2/re_tfns.c#L348
however I think the following also applies to the C++ implementation here:
https://github.com/SpiderLabs/ModSecurity/blob/libmodsecurity/src/actions/transformations/utf8_to_unicode.cc

The maximum unicode codepoint is U+10FFFF. This is stored in four UTF-8 bytes max:
https://stijndewitt.com/2014/08/09/max-bytes-in-a-utf-8-char/

Regardless of however many UTF-8 bytes are used, output is formatted as a literal `%`, literal `u`, followed by sprintf of `"%x"` for the hex value of the codepoint. So that outputs `%u10ffff` for the maximum codepoint. This is 8 characters long including the prefix; the hex digits are in storage allocated by `apr_psprintf()`:

```
unsigned char *unicode = NULL;
unicode = apr_psprintf(mp, "%x", d);
```

The literal `%` `u` prefix is written to `data`. The eight characters are then copied out to data:

```
*data++ = '%';
*data++ = 'u';
length = strlen(unicode);
for(j=0; j<length; j++) {
    *data++ = unicode[j];
}
```

But `data` was allocated to have a maximum space for 7 characters per _byte_ of UTF-8 input:

```
len = input_len * 7 + 1;
data = rval = apr_palloc(mp, len);
```

Single-byte sequences are not output as hex sequences. So the smallest number of bytes
per codepoint is 2, and the maximum 4.

How many bytes are written out, given each byte consumed:

| utf8 in |  | bytes out | factor |
| --- | --- | --- | --- |
| 1 | → | 1 | 1/1 = 1 |
| 2 | → | 8 | 8/2 = 4 |
| 3 | → | 8 | 8/3 = 2.66 |
| 4 | → | 8 | 8/4 = 2 |

So without considering whether any particular byte is a UTF-8 sequence or not, the worse case given input_len alone is a factor of 4. Hence:

```
len = input_len * 4 + 1;
```

**Comment by zimmerle** [comment]
Hi @katef,

Better if you can submit it in a format of a patch, so you can keep the authorship of the change, what do you think?

**Comment by victorhora** [comment]
This makes sense for me. I've submitted a commit for testing here: https://github.com/SpiderLabs/ModSecurity/commit/6926f404d1c662302fa92e7b4a9d902fde5b562a
And v3 branch here: https://github.com/SpiderLabs/ModSecurity/commit/318d45236fb872f984e5308fc8c0a117a68d9c7e

If all goes well, I believe we can merge for 2.9.3. 

Thanks :)

**Comment by victorhora** [comment]
Fixed in v2: https://github.com/SpiderLabs/ModSecurity/commit/b600669d02d2344089c8b024f75c806619cb3135

And v3: https://github.com/SpiderLabs/ModSecurity/commit/ecad8c6c7e0aca3225c432f0ea5b11e160c6c5ce

Thanks for your contribution @katef :)

**Comment by katef** [comment]
Wonderful, thank you :)
