### ISSUE TITLE
`utf8toUnicode` renders overlong sequences with a trailing byte

### ISSUE THREAD

**Issue by katef** [SpiderLabs/ModSecurity#1209]
Testing with the overlong sequence `\xf0\x80\x80\xaf`, the `utf8toUnicode` transformation produces the following output: `%u002f\xf0`

That's a literal `%`, literal `u`, four hex digits `002f` and a single byte `\xf0`

Looking at its source, this function seems intended to always produce six-digit hex sequences, not four.

Markus Kuhn's [UTF-8-text.txt|https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt] file recommends:
> According to ISO 10646-1:2000, sections D.7 and 2.3c, a device receiving UTF-8 shall interpret a "malformed sequence in the same way that it interprets a character that is outside the adopted subset" and "characters that are not within the adopted subset shall be indicated to the user" by a receiving device. One commonly used approach in UTF-8 decoders is to replace any malformed UTF-8 sequence by a replacement character (U+FFFD), which looks a bit like an inverted question mark, or a similar symbol. It might be a good idea to visually distinguish a malformed UTF-8 sequence from a correctly encoded Unicode character that is just not available in the current font but otherwise fully legal, even though ISO 10646-1 doesn't mandate this. In any case, just ignoring malformed sequences or unavailable characters does not conform to ISO 10646, will make debugging more difficult, and can lead to user confusion.

I do not know if this is appropriate for ModSecurity's needs. However there's a choice to make here - to either:
* treat the overlong sequence as valid and emit a six-digit hex sequence
* emit the replacement character verbatim
* emit the replacement character as a hex sequence
* pass through bytes as-is

The current behaviour of outputting four digits followed by a stray byte seems undesirable in any of these cases.

**Comment by csanders-git** [comment]
my understanding is that the first solution is a bad choice as it may lead to security issues. 
http://unicode.org/reports/tr36/

Not sure which one is the best beyond that one :)

**Comment by zimmerle** [comment]
Hi @katef, is that ok if a close this in favor of #1211 ?

@csanders-git Any input on the utf8toHex tranformation?

**Comment by katef** [comment]
Hi @zimmerle,
I don't think this ticket should be closed unless the function is removed. `utftoHex` would obsolete this, but it's not present yet. And when that is present, what's your policy on backwards compatibility for older rules still written for `utf8toUnicode`? Those will need updating. Meanwhile this bug still exists.

**Comment by zimmerle** [comment]
Hi @katef,

Do you mind in reply to @csanders-git concerns?
