### ISSUE TITLE
After response body substitution, there are two different Content-Length in response header

### ISSUE THREAD

**Issue by 203328517** [SpiderLabs/ModSecurity#1210]
After response body substitution, there are two Content-Length in response header.For example,my original response body is 'abc', after substitution,response body is now 'abcdef',then i check my ie browser response header,there are two Content-Length,one is 'Content-Length 6', the other is 'Content-Length 3',but when i use firefox, i get the 'Corrupted Content Error' error(i guess because of the different Content-Length)......Are there any ways to let the two Content-Length value both 6 or just remove one of the wrong 'Content-Length 3'.....Thank you very much.          mod+nginx+proxy

**Comment by zimmerle** [comment]
Hi @203328517 Which version of ModSecurity are you running? I would recommend to use the libmodsecurity with ModSecurity-nginx connector.
