### ISSUE TITLE
No "large" files working with Response_body in logging mode

### ISSUE THREAD

**Issue by rahendri** [SpiderLabs/ModSecurity#1215]
Hi, im pretty new to modsecurity and somehow i got stuck. 

I created a really simpel rule that i only want to log. 

`SecRule RESPONSE_BODY "DATADATA" "phase:4,rev:'1', id:'29092016',deny,log,msg:'Data has been seen'"`

This works when i create a simple html file only containing the DATADATA. But when i add more than 22 lines (I just put a count 1 to 22 per line), the rule will not log anymore. So i think i oversee some buffer somewhere. But the filesize is not bigger then 78 bites. 

I run Modsecurity on a fresh installed Ubuntu, with all the newest pakages. 
```
uname -a
linux ubuntu 4.4.0-31-generic 

apache 2.4.18-2ubuntu3.1
libapache2-mod-security2 2.9.0-1
```

It all runs in a VM. 

Anyone any idea what i do wrong? 

PS i tested modsecurity with a recular SQLi in blocking mode and that also works fine.

**Comment by zimmerle** [comment]
Hi @rahendri,

Please check your ModSecurity configuration file, there are a limits for the body inspection, check here: 
https://github.com/SpiderLabs/ModSecurity/blob/master/modsecurity.conf-recommended#L38

**Comment by rahendri** [comment]
Thank you for the response, i actually did change these values before.  And even lager than what you pont at.  This did not help anything, as far as i noticed it. 

SecRequestBodyLimit 134217728
SecRequestBodyNoFilesLimit 1048576

**Comment by lifeforms** [comment]
@rahendri Are you using mod_deflate? If so, maybe at 22 lines the compression is kicking in. This is just a wild guess. You can try disabling it with `sudo a2dismod -f deflate` and re-enable it with `sudo a2enmod deflate`. If disabling mod_deflate prevents your problem, then it might be issue #944 .

**Comment by rahendri** [comment]
Thank you very much, this indeed made it work again!

**Comment by zimmerle** [comment]
@lifeforms good catch.
