### ISSUE TITLE
How to enable OWASP CRS and SLR Rules side by side

### ISSUE THREAD

**Issue by pislisSniflis** [SpiderLabs/ModSecurity#1222]
Hi,

I guest before this my site quite secure using only OWASP CRS but to enhance the feature and to reduce headache during complex attack, I need to buy the commercial rules.

Current setting I just leave the OWASP CRS as is (which is will effect the admin login because CRS will trigger false alarm) and I include the commercial one which is SLR.

How can I use both rules without having false alarm from OWASP CRS?

**Comment by csanders-git** [comment]
There is no issue enabling both OWASP CRS and the SLR rules. It is recommended that you if you are using anomaly mode that you individually include all of the rules manually up to but not including REQUEST-949-BLOCKING-EVALUATION.conf (CRS v3.0.0) and then use the SecRemoteRules directive. Subsequent to the SecRemoteRules directive you should be include the remainder of the CRS rule files. If you are not enabling anaomly scoring mode then you may enable include the SecRemoteRule directive anyway subsequent to the CRS rule inclusions. Hopefully this solves your issue.
