### ISSUE TITLE
when i complie the example，missing a directory

### ISSUE THREAD

**Issue by calistochen** [SpiderLabs/ModSecurity#1226]
root/install_libmodsecurity/ModSecurity/examples/simple_example_using_c
[root@t simple_example_using_c]# make
/bin/sh ../../libtool  --tag=CC   --mode=link gcc -I../../headers -I../..  -g -O2   -o test test-test.o -L../../src/.libs/ -lmodsecurity -L/root/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0/lib/ -L/usr/lib64/ -lrt   
../../libtool: line 7475: cd: ../../src/.libs/: No such file or directory
libtool:   error: cannot determine absolute directory name of '../../src/.libs/'
make: *** [test] Error 1
[root@t simple_example_using_c]#

**Comment by zimmerle** [comment]
Hi @calistochen,

You don't need to run **make** inside the examples directory, instead you want to compile the library itself. By compiling the library the samples will be also compiled.
