### ISSUE TITLE
something wrong when i complie libmodsecurity【../src/collection/backend/lmdb.h:26:18: fatal error: lmdb.h: No such file or directory】

### ISSUE THREAD

**Issue by calistochen** [SpiderLabs/ModSecurity#1228]
[root@calisto-centos ModSecurity]# make
Making all in others
make[1]: Entering directory `/home/calisto/ModSecurity/others'
depbase=`echo libinjection/src/libinjection_html5.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../src     -g -O2 -MT libinjection/src/libinjection_html5.lo -MD -MP -MF $depbase.Tpo -c -o libinjection/src/libinjection_html5.lo libinjection/src/libinjection_html5.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../src -g -O2 -MT libinjection/src/libinjection_html5.lo -MD -MP -MF libinjection/src/.deps/libinjection_html5.Tpo -c libinjection/src/libinjection_html5.c  -fPIC -DPIC -o libinjection/src/.libs/libinjection_html5.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../src -g -O2 -MT libinjection/src/libinjection_html5.lo -MD -MP -MF libinjection/src/.deps/libinjection_html5.Tpo -c libinjection/src/libinjection_html5.c -o libinjection/src/libinjection_html5.o >/dev/null 2>&1
depbase=`echo libinjection/src/libinjection_sqli.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../src     -g -O2 -MT libinjection/src/libinjection_sqli.lo -MD -MP -MF $depbase.Tpo -c -o libinjection/src/libinjection_sqli.lo libinjection/src/libinjection_sqli.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../src -g -O2 -MT libinjection/src/libinjection_sqli.lo -MD -MP -MF libinjection/src/.deps/libinjection_sqli.Tpo -c libinjection/src/libinjection_sqli.c  -fPIC -DPIC -o libinjection/src/.libs/libinjection_sqli.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../src -g -O2 -MT libinjection/src/libinjection_sqli.lo -MD -MP -MF libinjection/src/.deps/libinjection_sqli.Tpo -c libinjection/src/libinjection_sqli.c -o libinjection/src/libinjection_sqli.o >/dev/null 2>&1
depbase=`echo libinjection/src/libinjection_xss.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../src     -g -O2 -MT libinjection/src/libinjection_xss.lo -MD -MP -MF $depbase.Tpo -c -o libinjection/src/libinjection_xss.lo libinjection/src/libinjection_xss.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../src -g -O2 -MT libinjection/src/libinjection_xss.lo -MD -MP -MF libinjection/src/.deps/libinjection_xss.Tpo -c libinjection/src/libinjection_xss.c  -fPIC -DPIC -o libinjection/src/.libs/libinjection_xss.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../src -g -O2 -MT libinjection/src/libinjection_xss.lo -MD -MP -MF libinjection/src/.deps/libinjection_xss.Tpo -c libinjection/src/libinjection_xss.c -o libinjection/src/libinjection_xss.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o libinjection.la  libinjection/src/libinjection_html5.lo libinjection/src/libinjection_sqli.lo libinjection/src/libinjection_xss.lo  
libtool: link: ar cru .libs/libinjection.a libinjection/src/.libs/libinjection_html5.o libinjection/src/.libs/libinjection_sqli.o libinjection/src/.libs/libinjection_xss.o 
libtool: link: ranlib .libs/libinjection.a
libtool: link: ( cd ".libs" && rm -f "libinjection.la" && ln -s "../libinjection.la" "libinjection.la" )
make[1]: Leaving directory `/home/calisto/ModSecurity/others'
Making all in src
make[1]: Entering directory `/home/calisto/ModSecurity/src'
/bin/sh ../ylwrap parser/seclang-parser.yy y.tab.c parser/seclang-parser.cc y.tab.h `echo parser/seclang-parser.cc | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output parser/seclang-parser.output -- bison -y  
updating location.hh
updating position.hh
updating stack.hh
updating parser/seclang-parser.hh
(CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/sh /home/calisto/ModSecurity/missing autoheader)
configure.ac:88: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
build/yajl.m4:4: PROG_YAJL is expanded from...
configure.ac:88: the top level
configure.ac:93: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
build/libgeoip.m4:10: PROG_GEOIP is expanded from...
configure.ac:93: the top level
configure.ac:98: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
build/lmdb.m4:4: PROG_LMDB is expanded from...
configure.ac:98: the top level
rm -f stamp-h1
touch config.h.in
cd .. && /bin/sh ./config.status src/config.h
config.status: creating src/config.h
config.status: src/config.h is unchanged
make  all-am
make[2]: Entering directory `/home/calisto/ModSecurity/src'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT parser/libmodsecurity_la-seclang-parser.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-parser.Tpo -c -o parser/libmodsecurity_la-seclang-parser.lo `test -f 'parser/seclang-parser.cc' || echo './'`parser/seclang-parser.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT parser/libmodsecurity_la-seclang-parser.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-parser.Tpo -c parser/seclang-parser.cc  -fPIC -DPIC -o parser/.libs/libmodsecurity_la-seclang-parser.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT parser/libmodsecurity_la-seclang-parser.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-parser.Tpo -c parser/seclang-parser.cc -o parser/libmodsecurity_la-seclang-parser.o >/dev/null 2>&1
mv -f parser/.deps/libmodsecurity_la-seclang-parser.Tpo parser/.deps/libmodsecurity_la-seclang-parser.Plo
/bin/sh ../ylwrap parser/seclang-scanner.ll lex.yy.c parser/seclang-scanner.cc -- flex  
/home/calisto/ModSecurity/src/parser/seclang-scanner.ll:455: warning, rule cannot be matched
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT parser/libmodsecurity_la-seclang-scanner.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-scanner.Tpo -c -o parser/libmodsecurity_la-seclang-scanner.lo `test -f 'parser/seclang-scanner.cc' || echo './'`parser/seclang-scanner.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT parser/libmodsecurity_la-seclang-scanner.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-scanner.Tpo -c parser/seclang-scanner.cc  -fPIC -DPIC -o parser/.libs/libmodsecurity_la-seclang-scanner.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT parser/libmodsecurity_la-seclang-scanner.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-scanner.Tpo -c parser/seclang-scanner.cc -o parser/libmodsecurity_la-seclang-scanner.o >/dev/null 2>&1
mv -f parser/.deps/libmodsecurity_la-seclang-scanner.Tpo parser/.deps/libmodsecurity_la-seclang-scanner.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT parser/libmodsecurity_la-driver.lo -MD -MP -MF parser/.deps/libmodsecurity_la-driver.Tpo -c -o parser/libmodsecurity_la-driver.lo `test -f 'parser/driver.cc' || echo './'`parser/driver.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT parser/libmodsecurity_la-driver.lo -MD -MP -MF parser/.deps/libmodsecurity_la-driver.Tpo -c parser/driver.cc  -fPIC -DPIC -o parser/.libs/libmodsecurity_la-driver.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT parser/libmodsecurity_la-driver.lo -MD -MP -MF parser/.deps/libmodsecurity_la-driver.Tpo -c parser/driver.cc -o parser/libmodsecurity_la-driver.o >/dev/null 2>&1
mv -f parser/.deps/libmodsecurity_la-driver.Tpo parser/.deps/libmodsecurity_la-driver.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT libmodsecurity_la-transaction.lo -MD -MP -MF .deps/libmodsecurity_la-transaction.Tpo -c -o libmodsecurity_la-transaction.lo `test -f 'transaction.cc' || echo './'`transaction.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-transaction.lo -MD -MP -MF .deps/libmodsecurity_la-transaction.Tpo -c transaction.cc  -fPIC -DPIC -o .libs/libmodsecurity_la-transaction.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-transaction.lo -MD -MP -MF .deps/libmodsecurity_la-transaction.Tpo -c transaction.cc -o libmodsecurity_la-transaction.o >/dev/null 2>&1
mv -f .deps/libmodsecurity_la-transaction.Tpo .deps/libmodsecurity_la-transaction.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT audit_log/libmodsecurity_la-audit_log.lo -MD -MP -MF audit_log/.deps/libmodsecurity_la-audit_log.Tpo -c -o audit_log/libmodsecurity_la-audit_log.lo `test -f 'audit_log/audit_log.cc' || echo './'`audit_log/audit_log.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/libmodsecurity_la-audit_log.lo -MD -MP -MF audit_log/.deps/libmodsecurity_la-audit_log.Tpo -c audit_log/audit_log.cc  -fPIC -DPIC -o audit_log/.libs/libmodsecurity_la-audit_log.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/libmodsecurity_la-audit_log.lo -MD -MP -MF audit_log/.deps/libmodsecurity_la-audit_log.Tpo -c audit_log/audit_log.cc -o audit_log/libmodsecurity_la-audit_log.o >/dev/null 2>&1
mv -f audit_log/.deps/libmodsecurity_la-audit_log.Tpo audit_log/.deps/libmodsecurity_la-audit_log.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT audit_log/libmodsecurity_la-writer.lo -MD -MP -MF audit_log/.deps/libmodsecurity_la-writer.Tpo -c -o audit_log/libmodsecurity_la-writer.lo `test -f 'audit_log/writer.cc' || echo './'`audit_log/writer.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/libmodsecurity_la-writer.lo -MD -MP -MF audit_log/.deps/libmodsecurity_la-writer.Tpo -c audit_log/writer.cc  -fPIC -DPIC -o audit_log/.libs/libmodsecurity_la-writer.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/libmodsecurity_la-writer.lo -MD -MP -MF audit_log/.deps/libmodsecurity_la-writer.Tpo -c audit_log/writer.cc -o audit_log/libmodsecurity_la-writer.o >/dev/null 2>&1
mv -f audit_log/.deps/libmodsecurity_la-writer.Tpo audit_log/.deps/libmodsecurity_la-writer.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT audit_log/writer/libmodsecurity_la-https.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-https.Tpo -c -o audit_log/writer/libmodsecurity_la-https.lo `test -f 'audit_log/writer/https.cc' || echo './'`audit_log/writer/https.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/writer/libmodsecurity_la-https.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-https.Tpo -c audit_log/writer/https.cc  -fPIC -DPIC -o audit_log/writer/.libs/libmodsecurity_la-https.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/writer/libmodsecurity_la-https.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-https.Tpo -c audit_log/writer/https.cc -o audit_log/writer/libmodsecurity_la-https.o >/dev/null 2>&1
mv -f audit_log/writer/.deps/libmodsecurity_la-https.Tpo audit_log/writer/.deps/libmodsecurity_la-https.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT audit_log/writer/libmodsecurity_la-serial.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-serial.Tpo -c -o audit_log/writer/libmodsecurity_la-serial.lo `test -f 'audit_log/writer/serial.cc' || echo './'`audit_log/writer/serial.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/writer/libmodsecurity_la-serial.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-serial.Tpo -c audit_log/writer/serial.cc  -fPIC -DPIC -o audit_log/writer/.libs/libmodsecurity_la-serial.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/writer/libmodsecurity_la-serial.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-serial.Tpo -c audit_log/writer/serial.cc -o audit_log/writer/libmodsecurity_la-serial.o >/dev/null 2>&1
mv -f audit_log/writer/.deps/libmodsecurity_la-serial.Tpo audit_log/writer/.deps/libmodsecurity_la-serial.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT audit_log/writer/libmodsecurity_la-parallel.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-parallel.Tpo -c -o audit_log/writer/libmodsecurity_la-parallel.lo `test -f 'audit_log/writer/parallel.cc' || echo './'`audit_log/writer/parallel.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/writer/libmodsecurity_la-parallel.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-parallel.Tpo -c audit_log/writer/parallel.cc  -fPIC -DPIC -o audit_log/writer/.libs/libmodsecurity_la-parallel.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT audit_log/writer/libmodsecurity_la-parallel.lo -MD -MP -MF audit_log/writer/.deps/libmodsecurity_la-parallel.Tpo -c audit_log/writer/parallel.cc -o audit_log/writer/libmodsecurity_la-parallel.o >/dev/null 2>&1
mv -f audit_log/writer/.deps/libmodsecurity_la-parallel.Tpo audit_log/writer/.deps/libmodsecurity_la-parallel.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include   -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include  -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT libmodsecurity_la-modsecurity.lo -MD -MP -MF .deps/libmodsecurity_la-modsecurity.Tpo -c -o libmodsecurity_la-modsecurity.lo `test -f 'modsecurity.cc' || echo './'`modsecurity.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -fPIC -O3 -I ../headers -DWITH_GEOIP -I/usr/include -DWITH_YAJL -I/home/calisto/install_libmodsecurity/lloyd-yajl-66cb08c/build/yajl-2.1.0//include -I/usr/local/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-modsecurity.lo -MD -MP -MF .deps/libmodsecurity_la-modsecurity.Tpo -c modsecurity.cc  -fPIC -DPIC -o .libs/libmodsecurity_la-modsecurity.o
In file included from modsecurity.cc:22:0:
../src/collection/backend/lmdb.h:26:18: fatal error: lmdb.h: No such file or directory
 #include <lmdb.h>
                  ^
compilation terminated.
make[2]: *** [libmodsecurity_la-modsecurity.lo] Error 1
make[2]: Leaving directory `/home/calisto/ModSecurity/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/calisto/ModSecurity/src'
make: *** [all-recursive] Error 1

**Comment by zimmerle** [comment]
Hi @calistochen,

Which branch are you trying to use? You may want to use gits to paste this large content, otherwise it will be very difficult to read.

**Comment by zimmerle** [comment]
@calistochen: When you paste this data to gits, please include the config.log.

**Comment by zimmerle** [comment]
Please update your local repo. There were recent changes that may fix the compilation issue for you.

**Comment by calistochen** [comment]
i think i fix than
