### ISSUE TITLE
Add jsondecode to transformation functions

### ISSUE THREAD

**Issue by fuckingbaidu** [SpiderLabs/ModSecurity#1229]
POST /api/xxx.do HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 58
Host: xxx

param=%7B%22form%22%3A%7B%22sysPlatform%22%3A%221%22%7D%7D

------------------------------------------------------------------------------------------------------------------

As you can see above,the post data is first json encoded,then url encoded,and send to server by adding "param=" prefix.

Currently modsecurity doesn't support such format
It simply urldecode the post_body into "param={"form":{"sysPlatform":"1"}}" and search for attacking vectors,then block the request(%22 will trigger SQLi rules)

So,can you add jsondecode to transformation functions?
Or is there any other way to solve my problem?

**Comment by zimmerle** [comment]
@fuckingbaidu: Thanks for the input the subject was already discussed on issue: #555 
It is on todo list to be created.
