### ISSUE TITLE
which IDE can I import this project？

### ISSUE THREAD

**Issue by calistochen** [SpiderLabs/ModSecurity#1230]

**Comment by zimmerle** [comment]
We have several sub-projects:
 - ModSecurity version 2.x for Apache (including modsec-wrapper)
 - ModSecurity version 2.x for IIS
 - ModSecurity version 2.x for NGINX
 - ModSecurity verison 3.x (aka libModSecurity)

You might want to choose your IDE depending on the sub-project that you want to work with. But, The IDE is really about your taste. I do like **vim** [1]. Vim is what I use most of the time. KDevelop [2] is also cool. For the IIS project I use **Visual Studio** [3].

[1] http://www.vim.org/
[2] https://www.kdevelop.org/
[3] https://www.visualstudio.com/

**Comment by calistochen** [comment]
thx

**Comment by calistochen** [comment]
thx @zimmerle
