### ISSUE TITLE
how do i test the example?

### ISSUE THREAD

**Issue by calistochen** [SpiderLabs/ModSecurity#1234]
when i run ./multi .
[root@t multiprocess_c]# ./multi 
Rules: 
Phase: 0 (0 rules)
Phase: 1 (0 rules)
Phase: 2 (1 rules)
    Rule ID: 1--0x253cc20
Phase: 3 (5 rules)
    Rule ID: 0--0x253cf00
    Rule ID: 2--0x253d510
    Rule ID: 3--0x253db40
    Rule ID: 4--0x253e0d0
    Rule ID: 5--0x253e5d

what should i do next?

**Comment by calistochen** [comment]
oh,,, I delete this 
SecDebugLog /dev/stdout
SecDebugLogLevel 9

**Comment by zimmerle** [comment]
Hi @calistochen,

Let us know if you find any other issue ;)
