### ISSUE TITLE
Not able to access an image.

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1236]
My application has some set of images like www.example.com/Images/x.png. And I'm not able to access them after enabling modsecurity. I couldn't find any working solution for this after searching. Some were suggesting to disable modsecurity for a folder. Anyway is there any correct method of allowing users to access this image ? I get "Site cant be reached error" and Im able to access the same image after disabling modsecurity though.

**Comment by zimmerle** [comment]
Hi @vishaalgc,

Can you give us further details about your environment? is it nginx? What about the ModSecurity version ?

Are you running any rules set?

**Comment by vishaalgc** [comment]
Modsecurity version 2.9.1
nginx/1.9.15
I included all the base_rules given by modsecurity directly.

------------------------------
#Load all Rule
Include base_rules/*.conf
------------------------------
Please let me know if needed more details.

**Comment by zimmerle** [comment]
Hi @vishaalgc,

Please, try to use the nginx-refactoring branch, or the libModSecurity:
www.github.com/SpiderLabs/ModSecurity-nginx
