### ISSUE TITLE
allMatch action

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/ModSecurity#1239]
In writing rule exclusions and virtual patches, it is often required to validate a certain parameter, such as `ARGS:foo "@streq good"`.

However, a user can submit multiple parameters with the same name, e.g. `foo=bad&foo=good`.

There is currently no easy way to require _all_ of these parameters to match. If you write `SecRule ARGS:foo "@streq good" "id:1,allow"`, then the rule would match as soon as one `foo=good` parameter is present, even if there's another one, which may be interpreted in various ways by the web application.

If the rule writer knows that the variable only should occur once, then they can add a chain to ensure `&ARGS:foo "@eq 1"`.

But, for some APIs, the parameter really can occur multiple times in a benign request. There is currently not a good way to facilitate validating _all_ selected variables without doing a difficult dance with creating tx variables.

It would be useful to have something like an `allMatch` modifier that would require a match to ALL mentioned variables, as a condition for the rule to match.

Context: https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/599#issuecomment-252291013

**Comment by victorhora** [comment]
As of now I think you might be able to accomplish what you're looking for with these rules:

```
SecRule ARGS "@rx (bad)|(good)" "id:1,pass,capture"
SecRule TX.0 "@streq good" "id:2,pass"
SecRule TX.1 "@streq bad" "id:3,block"
```

Or maybe trying to match it with [QUERY_STRING](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#QUERY_STRING), [REQUEST_URI](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#REQUEST_URI) or [REQUEST_LINE](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#REQUEST_LINE)

We could get a new ```allMatch``` action for 3.0.4 release, but thinking again, it seems like de-facto webservers such as Apache and Nginx does not take two parameters with the same name into consideration internally. 

For instance, if I submit parameters with the same name like ``foo=bad&foo=good`` this is what I get with on Apache access_log:

```
::1 - - [28/Sep/2018:23:52:36 -0400] "GET /?foo=bad HTTP/1.1" 200 10933 "-" "curl/7.38.0"
```

And Nginx:

```
127.0.0.1 - - [28/Sep/2018:23:57:33 -0400] "GET /?foo=bad HTTP/1.1" 200 8 "-" "Wget/1.16 (linux-gnu)"
```

I could only reproduce a valid scenario to test this by using a custom ModSec's v3 test case like this: https://gist.github.com/victorhora/4140a8f42e935d5ce157bb78ae2b9927

We might not rely on the webservers normalization routines to parse data, but in this case I'm not sure what's the value of developing such a feature.

Thoughts?

**Comment by martinhsv** [comment]
I'm going to go ahead and close this because:
- it's been open way too long overall
- it's been open way too long 'pending feedback' without response
- there are multiple ways to accomplish what is needed, including the suggestion by @victorhora 
- it is too much of a niche scenario (in my opinion) to warrant adding a new action when there are multiple ways to accomplish the underlying need

An additional way to register a match when any value of a particular name fails to have a certain value (e.g. 'good'):
```
SecRule ARGS:foo "@rx ^((?!(good$)).*)" ...        <== use negative lookahead to match anything other than 'good'
```
