### ISSUE TITLE
hmac implementation conflicts with hmac(3) in libc

### ISSUE THREAD

**Issue by sevan** [SpiderLabs/ModSecurity#1241]
NetBSD now includes an implementation of `hmac(3)` in libc and will feature in v8.0 when that's released. When trying to build modsecurity 2.9.1 on NetBSD-HEAD, the build fails as the implementation in msc_crypt.h conflicts.

`In file included from modsecurity.h:48:0,`
              `from apache2_config.c:17:`
`msc_crypt.h:30:16: error: conflicting types for 'hmac'`
 `char DSOLOCAL *hmac(modsec_rec *msr, const char *key, int key_len,`
          `^`
`In file included from modsecurity.h:19:0,`
`from apache2_config.c:17:`
`/usr/include/stdlib.h:303:10: note: previous declaration of 'hmac' was here`
 `ssize_t  hmac(const char *, const void *, size_t, const void *, size_t, void *,`
`^`

**Comment by zimmerle** [comment]
Hi @sevan,

Sorry for the delay. What is your compiler and version ?

**Comment by sevan** [comment]
Now on GCC 5.4.0

**Comment by zimmerle** [comment]
Still getting the same problem with GCC 5.4 ? What about old releases of NetBSD? it is just happening with this new one ?

**Comment by sevan** [comment]
I'm using the base compiler & `hmac(3)` is implemented in the libc. Older releases shouldn't be affected as `hmac(3)` was implemented in the head of the tree & will feature in the 8.0 release which hasn't even been branched yet.

**Comment by sevan** [comment]
[Viable solution to integrate](https://mail-index.netbsd.org/pkgsrc-changes/2016/12/24/msg150545.html)?

**Comment by victorhora** [comment]
Renaming the function seems to work fine. Since https://github.com/SpiderLabs/ModSecurity/commit/b3fa87dc7cc8eec21adf8c26e7f0e373b0bb935d this should not be a problem anymore and I can confirm compilation now completes successfully on NetBSD 8.0.

Thanks for the report! :)
