### ISSUE TITLE
nginx 1.11.5, arch linux, modsecurity 2.9.1 worker process exited with error 11, core dumped.

### ISSUE THREAD

**Issue by lilmike** [SpiderLabs/ModSecurity#1244]
Hi,
I'm running nginx 1.11.5 and modsecurity 2.9.1. Every so often, however, the worker process exits with error 11, core dumped. I'm not sure how to debug this as I don't get any information except the core dumped message in the error log even when set to debug, but if anyone has any suggestions/ideas let me know.
Thanks,
-Michael.

**Comment by zimmerle** [comment]
please use the libModSecurity + ModSecurity-nginx-connectort:

https://github.com/SpiderLabs/ModSecurity-nginx
