### ISSUE TITLE
Is Project LibModSecurity down  ? Is it updated to new project

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1245]
Im trying to get to [link](https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity) suggested in documentation of Nginx-Modsecurity connector plugin. Is it down or moved to somewhere else ?

**Comment by zimmerle** [comment]
Hi @vishaalgc,

Recently the repository was renamed to:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master

The documentation that you are currently looking into is out-dated. Do you mind to share where you find it? so that I can update the link.
