### ISSUE TITLE
Add option for SecDebugLog to be in JSON format

### ISSUE THREAD

**Issue by bitsofinfo** [SpiderLabs/ModSecurity#1247]
Would be great if there was an option for SecDebugLog to be in JSON format

**Comment by zimmerle** [comment]
Hi @bitsofinfo,

What do you have in mind in terms of structure? Usually we put something somehow has an structure inside a JSON. I am not sure what would be this structure for the DebugLogs.

**Comment by zimmerle** [comment]
This subject did not grabbed too much attention. It seems to me that it may not be a good idea. However 3.0 is ready to support any kind of customization on the debuglogs.
