### ISSUE TITLE
Google Safe Browsing Database URL Instructions give 404 error

### ISSUE THREAD

**Issue by inetbiz** [SpiderLabs/ModSecurity#1250]
For the URL: wget http://sb.google.com/safebrowsing/update?client=api&apikey=KEY&version=goog-malware-hash:1:-1

where **KEY** is my API KEY.

**Comment by zimmerle** [comment]
Hi @inetbiz,

Do you mind to share where did you get this url from ?

**Comment by inetbiz** [comment]
@zimmerle https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secgsblookupdb

**Comment by zimmerle** [comment]
Hi @inetbiz,

Thanks. Site updated.
