### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sqanto** [SpiderLabs/ModSecurity#1252]
Hello 

Ubuntu 16.04
modsecurity-2.9.1/
nginx version: nginx/1.10.0
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
built with OpenSSL 1.0.2j  26 Sep 2016
TLS SNI support enabled
configure arguments: --user=www-data --group=www-data --with-debug --with-http_ssl_module --add-module=../modsecurity-2.9.1/nginx/modsecurity --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --prefix=/etc/nginx

modsec_audit.log :
HTTP/1.1 500 Internal Server Error

--ce7a8900-H--
Message: Audit log: Failed to lock global mutex: Permission denied
Apache-Handler: IIS
Stopwatch: 1478520624000758 762040 (- - -)
Stopwatch2: 1478520624000758 762040; combined=391, p1=119, p2=244, p3=0, p4=0, p5=28, sr=9, sw=0, l=0, gc=0
Producer: ModSecurity for nginx (STABLE)/2.9.1 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: ModSecurity Standalone
Engine-Mode: "ENABLED"

--ce7a8900-Z--

SecRequestBodyAccess On
(but disabled every Body rule)

Post;
{
	"id": "d9a6f349-bf99-3d02-f441-0b2daf3ea0e2",
	"name": "mod_sec",
	"description": "",
	"order": [
		"f493837d-9401-5905-c287-09538f0e37cf"
	],
	"folders": [],
	"timestamp": 1478523154212,
	"owner": 0,
	"public": false,
	"requests": [
		{
			"id": "f493837d-9401-5905-c287-09538f0e37cf",
			"headers": "Origin: https://example.com\nUpgrade-Insecure-Requests: 1\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36\nContent-Type: application/x-www-form-urlencoded\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\nReferer: https://example.com/de/site/contact\nAccept-Encoding: gzip, deflate, br\nAccept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4\nCookie: hsfirstvisit=https%3A%2F%xxx.com%2Fde%2F||1234566; _ga_privy=GA1.2.377565081.sdfgserhgrt; _csrf=adgdafgsdfgr\n",
			"url": "https://example.com/de/site/contact POST",
			"preRequestScript": null,
			"pathVariables": {},
			"method": "POST",
			"data": [
				{
					"key": "LoginForm[identityName]",
					"value": "expert"
				},
				{
					"key": "LoginForm[password]",
					"value": "XXXXX"
				},
				{
					"key": "LoginForm[rememberMe]",
					"value": "0"
				},
				{
					"key": "LoginForm[username]",
					"value": "XXX@XXX.com"
				},
				{
					"key": "_csrf",
					"value": "XXXXX"
				},
				{
					"key": "login-button",
					"value": ""
				},
				{
					"key": "redirect",
					"value": ""
				}
			],
			"dataMode": "urlencoded",
			"version": 2,
			"tests": null,
			"currentHelper": "normal",
			"helperAttributes": {},
			"time": 1478523182407,
			"name": "https://example.com/de/site/contact",
			"description": "",
			"collectionId": "d9a6f349-bf99-3d02-f441-0b2daf3ea0e2",
			"responses": []
		}
	]
}

I hope someone can help 

THX

**Comment by zimmerle** [comment]
Is this nginx_refactoring branch ? 

I may want to use the ModSecurity-nginx connector 
https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by sqanto** [comment]
Not sure i use
https://www.modsecurity.org/tarball/2.9.1/modsecurity-2.9.1.tar.gz
from 
https://www.modsecurity.org/download.html
thx i try with master https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by sqanto** [comment]
Sorry but i compile this verision https://github.com/SpiderLabs/ModSecurity-nginx

but the problem is the same

There are other ideas ?

THX for help :)

**Comment by zimmerle** [comment]
You are getting the error "Message: Audit log: Failed to lock global mutex: Permission denied"  with the ModSecurity-nginx ?

**Comment by sqanto** [comment]
No this message is no longer just 500 Internal

**Comment by zimmerle** [comment]
Do you have any loaded rule that may be forcing a 500 error?

**Comment by sqanto** [comment]
I use the OWASP https://www.owasp.org/index.php/Category:OWASP_ModSecurity_Core_Rule_Set_Project
Basic rules.
And for debugging i white-list everything 

I try today a other ruleset

**Comment by fuckingbaidu** [comment]
still a bug today
solved by:

`CFLAGS="-DDEFAULT_USER=\\\"nginx\\\" -DDEFAULT_GROUP=\\\"nginx\\\"" \
CPPFLAGS="-I/usr/include/apr-1 -I/usr/include/httpd" \
./configure \
--disable-mlogc \
--with-yajl \
--enable-standalone-module`
