### ISSUE TITLE
crash with Request Method:POST and http response 302 with no content or err500

### ISSUE THREAD

**Issue by Eltenestn** [SpiderLabs/ModSecurity#1254]
The issue  is much like #750 , but it's a bit different .
In the environment nginx1.10.1 + ModSecurity2.9.1 + wordpress4.5.4, When publishing, editing, saving the article , the post request for the 302, into the non-response state . When deleting the article, delete the article for the first time normal, then delete the article will prompt an error .  there is no information in the modsec_audit.log, nginx in the error message:
```
[Alert] 19682 # 0: worker process 23877 exited on signal 11
[Alert] 19682 # 0: worker process 23878 exited on signal 11
[Alert] 19682 # 0: worker process 23879 exited on signal 11
```
When I set this:
```
SecAuditLog /var/log/modsec_audit.log
SecAuditLogType Concurrent
SecAuditLogStorageDir /opt/modsecurity/var/audit/
```
Nginx no longer has an error message, and modec_audit.log records a post request of 302 with an error status of 500. 
Set SecRequestBodyAccess Off, SecResponseBodyAccess Off Problem remains.
Will in the end is where an error occurred? Is there a solution? Thank you!

New tracking information：
The above settings are not changed, the error is not resolved, but do not know why error_nginx.log there has been new information, not so regular before, it seems like intermittent, these new error messages appear in the absence of the login wordpress Background to operate when.

```
2016/11/08 04:09:55 [alert] 4295#0: worker process 4343 exited on signal 11
2016/11/08 09:55:18 [alert] 4295#0: worker process 4495 exited on signal 11
2016/11/08 11:46:03 [alert] 4295#0: worker process 4958 exited on signal 11
2016/11/08 13:34:31 [alert] 4295#0: worker process 5133 exited on signal 11
2016/11/08 14:05:57 [alert] 4295#0: worker process 5339 exited on signal 11
2016/11/08 15:34:48 [alert] 4295#0: worker process 5397 exited on signal 11
2016/11/08 19:14:33 [alert] 4295#0: worker process 5514 exited on signal 11
2016/11/08 20:26:32 [alert] 4295#0: worker process 5822 exited on signal 9
2016/11/08 20:26:37 [alert] 4295#0: worker process 5935 exited on signal 9
2016/11/08 20:30:14 [alert] 4295#0: worker process 5936 exited on signal 9
2016/11/08 20:30:18 [alert] 4295#0: worker process 5964 exited on signal 9
2016/11/08 20:37:30 [alert] 4295#0: worker process 5965 exited on signal 9
2016/11/08 20:37:37 [alert] 4295#0: worker process 5991 exited on signal 9
```

When the wordpress use https login, post data no response, send data to 0, can not login.
and error_nginx.log : 
`[alert] 9154#0: worker process 9813 exited on signal 11`

**Comment by Eltenestn** [comment]
When the wordpress use https login, post data no response, send data to 0, can not login.

**Comment by Eltenestn** [comment]
I don't know if you can understand my problem, but I really can not solve these problems, I feel a little random.

**Comment by zimmerle** [comment]
Hi @edieterich,

Please try the ModSecurity-nginx connector available at:
http://www.github.com/SpiderLabs/ModSecurity-nginx
