### ISSUE TITLE
configure script throws an error | ./configure: line 6988: syntax error near unexpected token <<<' ./configure: line 6988:

### ISSUE THREAD

**Issue by aarvee11** [SpiderLabs/ModSecurity#1260]
root@nginx# sh build.sh
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build'.
libtoolize: copying file `build/libtool.m4'
libtoolize: copying file `build/ltoptions.m4'
libtoolize: copying file `build/ltsugar.m4'
libtoolize: copying file `build/ltversion.m4'
libtoolize: copying file `build/lt~obsolete.m4'
root@portal-haproxy-v2:/usr/src/ModSecurity# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for bison... bison -y
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking whether make sets $(MAKE)... (cached) yes
checking for flex... /usr/bin/flex
checking for bison... /usr/bin/bison
checking for bison... /usr/bin/bison
checking for "others/libinjection/src/libinjection_html5.c"... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
configure: Nothing about GeoIP was informed during the configure phase. Trying to detect it on the platform...
configure: using YAJL v2.0.4
configure: Nothing about GeoIP was informed during the configure phase. Trying to detect it on the platform...
configure: using GeoIP v1.6.0
configure: Nothing about LMDB was informed during the configure phase. Trying to detect it on the platform...
*** LOOKING AT PATH:  /usr/lib
*** LOOKING AT PATH:  /usr/local/lib
*** LOOKING AT PATH:  /usr/local/liblmdb
*** LOOKING AT PATH:  /usr/local/lmdb
*** LOOKING AT PATH:  /usr/local
*** LOOKING AT PATH:  /opt/liblmdb
*** LOOKING AT PATH:  /opt/lmdb
*** LOOKING AT PATH:  /opt
*** LOOKING AT PATH:  /usr
configure: LMDB library found at: /usr/lib/x86_64-linux-gnu//liblmdb.so
configure: LMDB headers found at: /usr/include
*** LOOKING AT PATH:  /usr/lib64
configure: LMDB library found at: /usr/lib/x86_64-linux-gnu//liblmdb.so
configure: LMDB headers found at: /usr/include
*** LOOKING AT PATH:  /opt/local
configure: LMDB library found at: /usr/lib/x86_64-linux-gnu//liblmdb.so
configure: LMDB headers found at: /usr/include
configure: using LMDB v
checking for libcurl config script... /usr/bin/curl-config
./configure: line 6271: test: : integer expression expected
./configure: line 6274: test: : integer expression expected
./configure: line 6278: test: : integer expression expected
checking if libcurl is at least v... yes, 7.35.0
checking if libcurl is linked with gnutls... no
configure: using curl v7.35.0
checking for libxml2 config script... /usr/bin/xml2-config
./configure: line 6414: test: : integer expression expected
./configure: line 6417: test: : integer expression expected
./configure: line 6420: test: : integer expression expected
checking if libxml2 is at least v2.6.29... yes, 2.9.1
configure: using libxml2 v2.9.1
checking for libpcre config script... /usr/bin/pcre-config
./configure: line 6528: test: : integer expression expected
./configure: line 6531: test: : integer expression expected
./configure: line 6534: test: : integer expression expected
./configure: line 6537: test: : integer expression expected
checking for PCRE JIT... yes
configure: using pcre v8.31
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
./configure: line 6988: syntax error near unexpected token `<<<'
./configure: line 6988: `<<<<<<< HEAD'

**Comment by zimmerle** [comment]
Hi @aarvee11,

Please paste the logs into a _code block_ or use _gist_. Are you trying to compile libModSecurity ? what is your distro? Are you trying to use the mainline ?

**Comment by aarvee11** [comment]
3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Nginx:- nginx-1.11.2 (Mainline version)
downloaded modsecurity git from v3/master

**Comment by aarvee11** [comment]
So what I have observed it is that, If I clone the git from "master" branch and checkout later, it s failing, but if I clone the v3/master directly, it does not fail. and I am able to compile the code properly.
