### ISSUE TITLE
question on forking requests on apache

### ISSUE THREAD

**Issue by dp80** [SpiderLabs/ModSecurity#1262]
We have need to fork requests while we migrate our infrastructure.  We were thinking of using ModSecurity module and adding a capability to forward copy of request to our new url.
my question is if it is possible to do that using modsecurity or should I be looking at different module or solution which are better for this purpose?

**Comment by bostrt** [comment]
would something more basic like mod_proxy work?

**Comment by dp80** [comment]
mod_proxy can work too i think.  But, can we specify the rules in config file for mod_security  to do the forking?

**Comment by bostrt** [comment]
I'm not sure if I really understand your use case but maybe the proxy action will help you: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#proxy
