### ISSUE TITLE
How to configure mod_proxy with Nginx

### ISSUE THREAD

**Issue by MohammadBilalArif** [SpiderLabs/ModSecurity#1264]
I am using ```modsecurity``` with ```Nginx``` as a reverse proxy for ```apache```. I want my reverse proxy to redirect traffic to honeynet according to rules. This [example](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#proxy) could not clear me. This feature look limited to apache only. How I could do this with ```Nginx```?

**Comment by zimmerle** [comment]
Hi @MohammadBilalArif,

The proxy action is only workable in Apache.
