### ISSUE TITLE
Problem nolog for REMOTE_ADDR

### ISSUE THREAD

**Issue by RaphaelDG** [SpiderLabs/ModSecurity#1267]
Hi,
I'm trying to nolog for a particular IP `10.68.***.96` and `127.0.0.1` address but it seem not working...

I already tried the following configurations (I know that some of them are depreciated but it's for the test):
```
SecRule REMOTE_ADDR "@ipMatch 10.68.***.96,127.0.0.1" "id:210798,phase:1,nolog,deny"
SecRule REMOTE_ADDR "@ipMatch 10.68.***.96,127.0.0.1" "phase:1,nolog,deny,id:210797"

SecRule REMOTE_ADDR "@ipMatch 10.68.***.96" phase:1,t:none,nolog,deny,id:123474737
SecRule REMOTE_ADDR "^10.68.***.96" "phase:1,nolog,deny,id:'167001'"

SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" phase:1,id:'1000000001',nolog,deny,ctl:ruleEngine=Off,ctl:auditEngine=Off
SecRule REMOTE_ADDR "@ipMatch 10.68.***.96" phase:1,id:'1000000002',nolog,deny,ctl:ruleEngine=Off,ctl:auditEngine=Off

```

Your help is welcome, and I searched a lot before asking you here.

Thanks in advance.

**Comment by zimmerle** [comment]
Hi @RaphaelDG,

You may want to look the @ipMatch entry in our reference manual:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#ipmatch

The wildcards are not supported instead you can use Network Block/CIDR.
