### ISSUE TITLE
Audit log contains all requests, regardless to configured "relevancy"

### ISSUE THREAD

**Issue by defanator** [SpiderLabs/ModSecurity#1269]
With the default configuration,

    SecAuditEngine RelevantOnly
    SecAuditLogRelevantStatus "^(?:5|4(?!04))"
    SecAuditLogParts ABIJDEFHZ
    SecAuditLogType Serial
    SecAuditLog /var/log/modsec_audit.log

and OWASP CRS v3.0.0, libmodsecurity produces audit log entries for requests that should not be "relevant", according to the configuration.

Setup is: nginx/1.11.5, libmodsecurity from current head of v3/master, modsecurity-nginx from current head of master, OWASP CRS v3.0.0.

nginx is configured to proxy all requests to some external site.

Request:

    127.0.0.1 - - [22/Nov/2016:15:04:27 +0000] "GET / HTTP/1.1" 200 7788 "-" "curl/7.38.0"

libmodsecurity debug log:

    [8] Checking if this request is suitable to be saved as an audit log.
    [8] This request was marked to be saved via auditlog action.
    [8] Checking if this request is relevant to be part of the audit logs.
    [5] Saving this request as part of the audit logs.
    [8] Request was relevant to be saved. Parts: -1

libmodsecurity audit log:

    ---vFoAP90z---A--
    [22/Nov/2016:15:04:26 +0000] 14798270666.953897 127.0.0.1 47918 127.0.0.1 80
    ---vFoAP90z---B--
    GET / HTTP/1.1
    REQUEST_HEADERS:User-Agent: curl/7.38.0
    REQUEST_HEADERS:Host: localhost
    REQUEST_HEADERS:Accept: */*
    ---vFoAP90z---D--
    ---vFoAP90z---E--
    ---vFoAP90z---F--
    RESPONSE_HEADERS:ETag: "582b28cb-1e6c"
    RESPONSE_HEADERS:Server: nginx/1.11.5
    RESPONSE_HEADERS:Date: Tue, 22 Nov 2016 15:04:27 GMT
    RESPONSE_HEADERS:Content-Length: 7788
    RESPONSE_HEADERS:Content-Type: text/html; charset=utf-8
    RESPONSE_HEADERS:Connection: keep-alive
    RESPONSE_HEADERS:Last-Modified: Tue, 15 Nov 2016 15:24:59 GMT
    RESPONSE_HEADERS:Accept-Ranges: bytes
    ---vFoAP90z---H--
    ---vFoAP90z---I--
    ---vFoAP90z---J--
    ---vFoAP90z---Z--

nginx error log does not contain any messages from libmodsecurity.

**Comment by ChrisRovers** [comment]
I am seeing this as well - same setup, though nginx 1.11.6

**Comment by zimmerle** [comment]
Similar to: #1275

**Comment by ogarrett** [comment]
With SecAuditEngine Off, I still see relevant requests being logged.  For example:

```
SecRuleEngine On

SecAuditEngine Off
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/modsec_audit.log

# Basic test rule
SecRule ARGS:testparam "@contains test" "id:1234,deny,log,status:403"
```

Requests like http://localhost/?testparam=test trigger the rule and are logged to the audit log, even with SecAuditEngine Off

**Comment by zimmerle** [comment]
Fixed. 1218d8c845cc36787b1bed90150f99045a71cd09

**Comment by defanator** [comment]
Just tested new code (head of v3/master), and it doesn't appear to be fixed. I'm experimenting with the default audit log configuration:

    SecAuditEngine RelevantOnly
    SecAuditLogRelevantStatus "^(?:5|4(?!04))"
    SecAuditLogParts ABCIJDEFHKZ
    SecAuditLogType Serial
    SecAuditLog /var/log/modsec_audit.log

I run 2 requests, first one is returning 200, second one is being blocked by CRS rule. Audit log contains both of those:

    ---voYjpOoP---A--
    [20/Dec/2016:10:04:55 +0000] 148222829587.838474 127.0.0.1 44130 127.0.0.1 80
    ---voYjpOoP---B--
    GET / HTTP/1.1
    Host: localhost
    User-Agent: curl/7.50.1
    Accept: */*
    
    ---voYjpOoP---C--
    
    ---voYjpOoP---D--
    
    ---voYjpOoP---F--
    ETag: "5857a136-1ee3"
    Connection: keep-alive
    Server: nginx/1.11.7
    Date: Tue, 20 Dec 2016 10:04:55 GMT
    Content-Length: 7907
    Content-Type: text/html; charset=utf-8
    Last-Modified: Mon, 19 Dec 2016 08:58:30 GMT
    Accept-Ranges: bytes
    
    ---voYjpOoP---H--
    
    ---voYjpOoP---I--
    
    ---voYjpOoP---J--
    
    ---voYjpOoP---K--
    
    ---voYjpOoP---Z--
    
    ---PrukAQcX---A--
    [20/Dec/2016:10:05:04 +0000] 148222830488.397469 127.0.0.1 44136 127.0.0.1 80
    ---PrukAQcX---B--
    GET /?param="><script>alert(1);</script> HTTP/1.1
    Host: localhost
    User-Agent: curl/7.50.1
    Accept: */*
    
    ---PrukAQcX---C--
    
    ---PrukAQcX---D--
    
    ---PrukAQcX---F--
    Connection: keep-alive
    Server: nginx/1.11.7
    Date: Tue, 20 Dec 2016 10:05:04 GMT
    Content-Length: 169
    Content-Type: text/html
    
    ---PrukAQcX---H--
    ModSecurity: Warning. detected XSS using libinjection. [file "/etc/nginx/modsec/owasp-v3/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "17"] [id "941100"] [rev "2"] [msg "XSS Attack Detected via libinjection"] [data "Matched Data:  host user-agent accept found within ARGS:param: "><script>alert(1);</script>"] [severity "2"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"]
    ModSecurity: Warning. Matched "Operator `@rx' with parameter `(?i)([<\xffffffef\xffffffbc\xffffff9c]script[^>\xffffffef\xffffffbc\xffffff9e]*[>\xffffffef\xffffffbc\xffffff9e][\s\S]*?)' against variable `ARGS:param' (Value: `"><script>alert(1);</script>' ) " at ARGS:param [file "/etc/nginx/modsec/owasp-v3/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "56"] [id "941110"] [rev "2"] [msg "XSS Filter - Category 1: Script Tag Vector"] [data "Matched Data: <script> found within ARGS:param: "><script>alert(1);</script>"] [severity "2"] [ver "OWASP_CRS/3.0.0"] [maturity "4"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"]
    ModSecurity: Warning. Matched "Operator `@rx' with parameter `(?i)<[^\w<>]*(?:[^<>\"'\s]*:)?[^\w<>]*(?:\W*?s\W*?c\W*?r\W*?i\W*?p\W*?t|\W*?f\W*?o\W*?r\W*?m|\W*?s\W*?t\W*?y\W*?l\W*?e|\W*?s\W*?v\W*?g|\W*?m\W*?a\W*?r\W*?q\W*?u\W*?e\W*?e|(?:\W*?l\W*?i\W*?n\W*?k|\W*?o (3246 characters omitted)' against variable `ARGS:param' (Value: `"><script>alert(1);</script>' ) " at ARGS:param [file "/etc/nginx/modsec/owasp-v3/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "231"] [id "941160"] [rev "2"] [msg "NoScript XSS InjectionChecker: HTML Injection"] [data "Matched Data: <script found within ARGS:param: "><script>alert(1);</script>"] [severity "2"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"]
    ModSecurity: Warning. Matched "Operator `@ge' with parameter `%{tx.inbound_anomaly_score_threshold}' against variable `TX:ANOMALY_SCORE' (Value: `15' ) " at TX:ANOMALY_SCORE [file "/etc/nginx/modsec/owasp-v3/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "38"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 15)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"]
    ModSecurity: Warning. Matched "Operator `@ge' with parameter `%{tx.inbound_anomaly_score_threshold}' against variable `TX:INBOUND_ANOMALY_SCORE' (Value: `15' ) " at TX:INBOUND_ANOMALY_SCORE [file "/etc/nginx/m

(output is trimmed due to buffering - if I repeat second request, a part of previous records appear)
