### ISSUE TITLE
Mod Security v3 Problem with beginsWith

### ISSUE THREAD

**Issue by void-in** [SpiderLabs/ModSecurity#1276]
So the following rule when used with beginsWith is not blocking the HTTP GET request:
```
SecRule SERVER_NAME "@streq www.example.com" "chain,id:220000018,phase:1,log,deny,msg:'blocked'"
SecRule REQUEST_FILENAME "@beginsWith /nicoppoc-status" "chain"
SecRule REMOTE_ADDR "!@ipMatch 1.0.0.0/8"
```
However, when the second rule is changed and ```@rx``` operator is used instead of ```beginsWith```
, the rule starts working.
```
SecRule SERVER_NAME "@streq www.example.com" "chain,id:220000018,phase:1,log,deny,msg:'blocked'"
SecRule REQUEST_FILENAME "@rx /nicoppoc-status" "chain"
SecRule REMOTE_ADDR "!@ipMatch 1.0.0.0/8"
```
The log can be seen in the apache access logs:
```
37.58.58.206 - - [30/Nov/2016:16:18:34 +0500] "GET /nicoppoc-status/ HTTP/1.1" 200 78513 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
37.58.58.206 - - [30/Nov/2016:16:20:14 +0500] "GET /nicoppoc-status/ HTTP/1.1" 403 218 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
```
First line of log is from the first rule (HTTP status 200) while the second line is from the second rule.

**Comment by zimmerle** [comment]
Hi @void-in,

Do you happens do have the DebugLogs associated with those two requests?

**Comment by zimmerle** [comment]
Hi @void-in,

Naming convention apart, the request file name may contains the full patch till the requested file. Which may explain why @rx was working and no @beginsWith. The DebugLogs can help you to sort out this problem.
