### ISSUE TITLE
Restrict wiki to collaborators only

### ISSUE THREAD

**Issue by bostrt** [SpiderLabs/ModSecurity#1277]
Can the wiki be restricted to collaborators only? Right now, it is open for anyone with a github account to edit.

**Comment by zimmerle** [comment]
Hi @bostrt,

That sounds to be a good idea. However, I have to mention that we have received a quite good contribution on that front. I hope that this need for authorization will not intimidate the contributors. After all, all contributions are very welcomed.

Wiki permission changed.
