### ISSUE TITLE
STREAM_OUTPUT_BODY @rsub on 403 deny by rule

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/ModSecurity#1280]
Hi,

i'm trying to replace the string "UNIQUEID" in the server error page response body with "%{UNIQUE_ID}" (i'm usign ModSecurity 2.9.1 on openresty). It seems to work only when i directly request the error page, for example: `curl http://mywebsite/403.html` and it seems not work when a rule matches and the 403 status is sent to the user.

**modsecurity.conf**
```
SecRule STREAM_OUTPUT_BODY "@rsub s/UNIQUEID/%{UNIQUE_ID}/" "phase:4,id:24,t:none,pass"
```

**nginx.conf**
```
error_page 403 /403;

location = /403 {
   default_type 'text/plain';
   content_by_lua_block {
      ngx.say('Request ID: REQID')
   }
}
```

**request /403**
```
$ curl -s 'http://mywebsite.xx/403'
Request ID: AbAc8cAcAIAcAcAcAcvcjcDc
```

**block by rule**
```
$ curl -s 'http://mywebsite.xx/?a=1+AND+1=1--'
Request ID: UNIQUEID
```

any idea?
thank you!

-theMiddle

**Comment by zimmerle** [comment]
Hi @theMiddleBlue,

Please use the ModSecurity-nginx connector:
www.github.com/SpiderLabs/ModSecurity-nginx

Notice that content injection is not yet supported on libModSecurity.
