### ISSUE TITLE
Partial analysis of multipart

### ISSUE THREAD

**Issue by thierry-f-78** [SpiderLabs/ModSecurity#1284]
Hi everyone.

I activated partial processing of the body like this:

`SecRequestBodyLimitAction ProcessPartial`

It is running with posts of type "application/x-www-form-urlencoded", but with multipart nody, I have always the same response in the logs:

`Multipart parsing error: Multipart: Final boundary missing.`

But, I send a anntack in the first bytes of the post:

`curl 'http://127.0.0.1:8008/' -F 'a="%20OR%201=1' -F b=@b`

"b" is a big file, and I controlled that "a" is in the firsts bytes of the request.

This is the expected behavior ? It exists a method for analysis partial body in multipart ?

Thanks
Thierry

**Comment by zimmerle** [comment]
Hi @thierry-f-78,

The multipart needs to be completed before analysed. Unfortunately there is no partial multipart inspection. You may be able to use a external tool with Lua or Python to perform the analysis based on our specific needs.

**Comment by thierry-f-78** [comment]
Ok, thank you.
