### ISSUE TITLE
Parsing Error on SecRuleUpdateTargetBy<> directives

### ISSUE THREAD

**Issue by aankuragr** [SpiderLabs/ModSecurity#1287]
When the following directive is added to the rules file, nginx start fails with parsing error

SecRuleUpdateTargetByTag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION" !REQUEST_COOKIES

The error reported by nginx is 

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/xxxxx/conf/modsec_activated_rules/all_active.conf. Line: 30. Column: 8. invalid character U in /usr/local/nginx/conf/nginx.conf:139

The same error is reported for SecRuleUpdateTargetById directive as well.

Testing with v3/master code.
Latest commit id : 64e2927922daba2ea267537268dce3dd328a6553

**Comment by zimmerle** [comment]
Implemented. - fba9c20ea1e4d37bcb30d86745476b13676a52c7.
