### ISSUE TITLE
modsecurity 2.9.1 implicit-function-declaration

### ISSUE THREAD

**Issue by abucodonosor** [SpiderLabs/ModSecurity#1291]
Hi ,

I noticed some implicit-function-declaration warnings from gcc in my build logs.

`mod_security-2.9.1-1-x86_64.log:msc_tree.c:861:19: warning: implicit declaration of function 'inet_pton' [-Wimplicit-function-declaration]`

#include <arpa/inet.h> <-- guard by #if APR_HAVE_ARPA_INET_H , can't see that in any *config*.h file(s) ?!

`mod_security-2.9.1-1-x86_64.log:msc_util.c:2709:13: warning: implicit declaration of function 'inet_pton' [-Wimplicit-function-declaration]`

#include <arpa/inet.h> <-- missing

`mod_security-2.9.1-1-x86_64.log:msc_status_engine.c:198:10: warning: implicit declaration of function 'ioctl' [-Wimplicit-function-declaration]`

#include <sys/ioctl.h> <-- missing

`mod_security-2.9.1-1-x86_64.log:msc_status_engine.c:478:9: warning: implicit declaration of function 'gethostbyname' [-Wimplicit-function-declaration]`

#include <netdb.h> <-- missing
#include <sys/socket.h> <-- only defined for DARWIN ?

gcc version is 6.2.1..

I can provide an patch but since I only can test the code on Linux I guess is 
better you guys handle these.

Regards,

Gabriel C

**Comment by victorhora** [comment]
I couldn't reproduce this warning from GCC (6.4) here. Tried to forcefully getting them by adding -Wall and -Wimplicit, and -pedantic but no warnings here regarding implicit declarations.

I believe commit https://github.com/SpiderLabs/ModSecurity/commit/7ead7f4d23ee6bb2f491842826071624f06cba32 should have covered all of these.

Thanks!
