### ISSUE TITLE
Mod Security v3 false positive

### ISSUE THREAD

**Issue by faridz88** [SpiderLabs/ModSecurity#1292]
Hi
Modsecurity v3 detects intervention on all requests even when no rule is matched or even when loaded rule file is empty.
output of `ModSecurity/test/benchmark/benchmark` also confirms that.

**Comment by zimmerle** [comment]
Hi @faridz88,

This is odd, can you confirm your libModSecurity version (last commit hash) and some input on the rules that you are using ?
