### ISSUE TITLE
segment fault with modsecurity2.9.1 and nginx1.8.1

### ISSUE THREAD

**Issue by mwang911** [SpiderLabs/ModSecurity#1296]
The fault is in the function ngx_http_upstream_copy_allow_ranges
and the direct reason is r->upstream->conf is NULL.  
Apparently, http header "Accept-Ranges"  is included in response packet.

I checked the stack info with gdb and finally found something incorrect in the function ngx_http_modsecurity_save_headers_out  in which the r->upstream is set to &ngx_http_modsecurity_upstream. 

All the variables in ngx_http_modsecurity_upstream are set to zero except the variable "cacheable". And of course r->upstream->conf is NULL which leads to the segment fault.

In fact, I have no idea why r->upstream should be set to &ngx_http_modsecurity_upstream.

**Comment by zimmerle** [comment]
Hi @mwang911,

Please use the ModSecurity-nginx connector instead of the nginx_refactoring branch.

More about the ModSecurity-nginx connector is available here:
https://github.com/SpiderLabs/ModSecurity-nginx
