### ISSUE TITLE
IIS 7 not working in DetectionOnly mode.

### ISSUE THREAD

**Issue by WithWings4** [SpiderLabs/ModSecurity#1300]
After installing Mod Security 2.9.1 x64 on a Server 2012 with Exchange 2010 (All Exchange roles, Mailbox, Client Access, Hub Transport) I observe the following behavior:

Powershell trips these rules:
960010
960015

ActiveSync trips these rules:
960010 (android)
960015 (android)
981204 (android)
973338 (iOS)

When trying to connect via Powershell virtual directory (using the Exchange Management shell / Console (EMS / EMC), which connect internally via Powershell, through IIS).

The ActiveSync rules are tripped via mobile devices logging into the Microsoft-Server-ActiveSync virtual directory (devices can either use this virtual directory, or the Exchange Web Services to access their mailbox, in addition to IMAP / POP3):

I can login to Outlook Web App (Outlook Web Access was the old name), but immediately see a 'Bad Request' after login on the auth.owa page.

Disabling these rules via modsecurity_crs_15_customrules.conf (in ..\owasp_crs\base_rules)
SecRuleRemoveByID 960010
SecRuleRemoveByID 960015

Suppressed all Application Event Log warnings except 973338 (981204 disappeared as well). OWA still doesn't work (Bad Request after login), and Powershell still doesn't work.

modsecurity.conf is default (set to):
SecRuleEngine DetectionOnly

changing this to 'Off', and recycling IIS (iisreset) allows the server to function normally.

Prerequisites are installed (Roles & Features / VC Redistributable 2013). The installer completes without error, and can be removed / reinstalled without issue. Additional Roles / Features are present (required for Exchange 2010)

Powershell itself throws:
 'VERBOSE: Connecting to <ExchangeServer>
[<ExchangeServer>] Connecting to remote server failed with the following er
ror message : The WinRM client cannot process the request. It **cannot determine
the content type of the HTTP response from the destination computer. The conten
t type is absent or invalid.** For more information, see the about_Remote_Trouble
shooting Help topic.
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:Re
   moteRunspace) [], PSRemotingTransportException
    + FullyQualifiedErrorId : PSSessionOpenFailed

This is in triplicate (as Powershell usually does).

Interestingly Exchange (most versions) will leave the user logged in, if you just close the tab in the browser. If I have logged in already with SecRuleEngine Off, and I can simply go back to OWA in a new tab after setting SecRuleEngine to DetectionOnly, and doing an iisreset it goes straight into the mailbox (as it normally would, since I didn't log out).

This leads me to believe that there isn't much to be done for Exchange to work with modsecurity installed. Given most things are running as local system, and there is no longer TMG, or similar available I would like to get this running, as Exchange is rather open from an attack surface point of view. It would benefit many people.

I am having trouble locating documentation for white listing virtual directories. I was planning on leaving it running in DetectionOnly to see what attacks are flagged, and going from there. Even in just IDS mode it would be invaluable. 

I can test this server most days, so if you guys need me to reconfigure something let me know. So far the real issue is that DetectionOnly doesn't seem to be functioning (or else something is broken, when it tries to run).

**Comment by zimmerle** [comment]
Hi @WithWings4,

I am assuming that you are using the default OWASP CRS that cames with the installer. I would recommend to upgrade it to the CRS version 3. You can get further information here: 

https://github.com/SpiderLabs/owasp-modsecurity-crs

**Comment by WithWings4** [comment]
I tried re-installing with no rules (to be as clean as possible). It behaved exactly the same way.

I fixed it after coming across lelekos bug report (#1299 "POST problem (IIS)" by adding:

SecStreamInBodyInspection On

anywhere within the C:\Program Files\ModSecurity IIS\modsecurity.conf file, not after a hash (comment), on it's own line.
