### ISSUE TITLE
x-forwarded-for on Logs !

### ISSUE THREAD

**Issue by lelekos** [SpiderLabs/ModSecurity#1302]
Hello,

I have succesfuly installed mod security on IIS8.5 and using it on a website with about 500.000 page views per day. Very satisfied with results.

However, our web servers are behind a reverse proxy. For this reason we cannot see the source IP of the attacker:

`[client [OUR.IP]:41520] ModSecurity: Access denied with code 403 (phase 2). Matched phrase "eval(" at ARGS:1. [file "C:\/Program Files/ModSecurity IIS/b/b.conf"] [line "3"] [id "49459"] [msg "NO"] [severity "WARNING"] [hostname "NODE2"] [uri "/?1=@ini_set(%22display_errors%22,%220%22);@set_time_limit(0);@set_magic_quotes_runtime(0);echo%20'-%3E%7C';file_put_contents(dirname($_SERVER%5B'SCRIPT_FILENAME'%5D).'/cache/cachee.php','%3C?php%20eval($_POST%5Bshine%5D);?%3E');echo%20'%7C%3C-';"] [unique_id "13979173249800486753"]`

Where [OUR.IP] it should be the X-FORWARDED-FOR header.

Is that possible?
If not, may I request it as new feature?

Thanks
Alex

**Comment by zimmerle** [comment]
There is a discussion being held on our users mailing list with the very same subject:
https://sourceforge.net/p/mod-security/mailman/mod-security-users/?viewmonth=201701

I am closing this issue.
