### ISSUE TITLE
GeoIP2 ?

### ISSUE THREAD

**Issue by porjo** [SpiderLabs/ModSecurity#1307]
I made the mistake of trying to use Maxmind's newer [GeoIP2](http://dev.maxmind.com/geoip/geoip2/geolite2/) database format, only to find the debug log full of `No geo data for "x.x.x.x" (country -16282110).` errors.

It would be good to:

- make it clear in the documentation that ModSecurity only supports the legacy [GeoIP](http://dev.maxmind.com/geoip/legacy/downloadable/) format
- include support for the newer GeoIP2 format (if possible)

Thanks

**Comment by csanders-git** [comment]
By documentation are you suggesting the inline documentation or in the reference manual or both ?

**Comment by porjo** [comment]
I had in mind the reference manual entry for [SecGeoLookupDb](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecGeoLookupDb)

**Comment by csanders-git** [comment]
@porjo good stuff, I updated the reference manual :). I'll take a look at adding support for v2 to libmodsecurity also, unless you are interested in this project.

**Comment by linux4me** [comment]
On the [Maxmind site](http://dev.maxmind.com/geoip/legacy/geolite/) there is an announcement that says:

> We will be discontinuing updates to the GeoLite Legacy databases as of April 1, 2018. You will still be able to download the April 2018 release until January 2, 2019. GeoLite Legacy users will need to update their integrations in order to switch to the free GeoLite2 or commercial GeoIP databases by April 2018. 

Is an update to ModSecurity to use GeoIP2 in the works?

**Comment by csanders-git** [comment]
Thanks @linux4me. This came up in the CRS meeting. Starting January 2nd without support in libmodsec for GeoIP2, the geoLookup operator will not work on any version of ModSecurity. Ideally CRS would like 2 months to issue a minor release that indicates that the feature is broken on ModSecv2 and only supported on ModSecv3. 

This would put this request on the modsec team to have this available before October 2018. Is this feasible?

**Comment by zimmerle** [comment]
On v3/master already.
