### ISSUE TITLE
GeoIP doesn't correctly print missing file name

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/ModSecurity#1309]
We get the error message shown from "src/parser/seclang-parser.cc" 4564L but it doesn't correctly get the file.

Error Opening file 
nginx: [emerg] "root" directive Rules error. File: <<reference missing or not informed>>. Line: 5. Column: 62. Failed to load the GeoDB from:   in /usr/local/nginx/conf/nginx.conf:124

#ifdef WITH_GEOIP
        std::string file = modsecurity::utils::find_resource(yystack_[0].value.as< std::string > (),
            driver.ref.back());
        if (GeoLookup::getInstance().setDataBase(file) == false) {
            std::stringstream ss;
            ss << "Failed to load the GeoDB from: ";
            ss << file;
            driver.error(yystack_[1].location, ss.str());
            YYERROR;
        }

**Comment by zimmerle** [comment]
Fixed by: c97db2f36191371a1d9ce69a18385a12fcfcf2a4
