### ISSUE TITLE
LibModsecurity Obselete ?

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1310]
Is libmodsecurity project not in use anymore ? I have started working on mod security after many days, So for usage which latest documentation should I follow ? As I see modsecurity-nginx connector project says install libmodsecurity first. Like mentioned in [this](https://github.com/SpiderLabs/ModSecurity-nginx) link.

**Comment by zimmerle** [comment]
Hi @vishaalgc,

libmodsecurity will be the ModSecurity version 3. If you want to use ModSecurity with nginx I would recommend to use the libmodsecurity+ModSecurity-nginx connector.

**Comment by vishaalgc** [comment]
@zimmerle  Can you guide me the link for libmodsecurity ?

**Comment by zimmerle** [comment]
It is available here: https://github.com/SpiderLabs/ModSecurity/tree/v3/master
