### ISSUE TITLE
ModSecurity-Nginx compilation issue

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1314]
After compilation of modsecurity, I downloaded nginx tar file and compiled it into ModSecurity-Nginx folder as suggested in [this](https://github.com/SpiderLabs/ModSecurity-nginx) documentation. I'm using this command ./configure --add-module=/path/your/modsecurity-for-nginx and its giving me an error saying
" checking for modsecurity library in ... not found ./configure error : ngx_http_modsecurity_module requires the MODSECURITY LIBRARY, but we cannot find modsecurity there."  Am i missing something here?

**Comment by zimmerle** [comment]
Hi @vishaalgc 

Did you had the chance to get ModSecurity installed before tried to compile the nginx connector?
