### ISSUE TITLE
Mosecurity-nginx compilation issue

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1315]
Modsecurity-nginx make error throwing an error after installing modsecurity correctly and compiling modsecurity nginx in CENTOS 7 Minimal. The error i get while i "make" is "error NGX_HTTP_VERSION_20 undeclared (first use in this function), 
    case NGX_HTTP_VERSION_20:"

How to resolve this ?

**Comment by zimmerle** [comment]
Hi @vishaalgc,

That sounds to me an error on nginx, not really in ModSecurity-nginx. What happens if you try to compile it without ModSecurity?

**Comment by vishaalgc** [comment]
@zimmerle  When i compile normal nginx "make" is not throwing any error. but when i configure nginx with path using this command "./configure --add-module=/opt/ModSecurity-nginx" as mentioned in the documentation. Its throwing the error mentioned above. however no errors when i just use "./configure" while compiling nginx

**Comment by zimmerle** [comment]
What is the version of your nginx ?

**Comment by vishaalgc** [comment]
@zimmerle  Nginx version : 1.9.2. i followed the compilation recipe for Centos 7 minimal given in [https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes](url) documentation link.

**Comment by defanator** [comment]
Hi @vishaalgc,

the reason of the error you were observing is that nginx/1.9.2 did not have HTTP/2 support, it was introduced a bit later in nginx/1.9.5.

I have just committed the fix here:
https://github.com/SpiderLabs/ModSecurity-nginx/commit/618edd29ea3f77ab7be93557e25a66255f9acd56

I'd encourage you to use latest mainline version of nginx (1.11.9 at the moment) though, 1.9.2 is quite outdated.

**Comment by zimmerle** [comment]
Closing as @defanator already provide the fix and guidance. Thanks ;)
