### ISSUE TITLE
AIX - modsecurity-2.9.1: Memory fault(coredump)

### ISSUE THREAD

**Issue by flynn1973** [SpiderLabs/ModSecurity#1317]
OS: IBM AIX
Compiler: IBM XLC
httpd: 2.4.25
mod_security: 2.9.1
build command line: ./configure --with-apxs=$APPATH/bin/apxs --with-apr=$APPATH/apr --with-apu=$APPATH/apr --with-lua=$TOOLSPATH

root@aixbuildhost61: /tmp/apachetest/modules # ldd mod_security2.so
mod_security2.so needs:
         /usr/lib/libc.a(shr_64.o)
         /tmp/apachetest/apr/lib/libcrypto.a(libcrypto.so.1.0.0)
         /usr/lib/libpthread.a(shr_xpg5_64.o)
         /tmp/apachetest/apr/lib/libxml2.a(libxml2.so.2)
         /tmp/apachetest/apr/lib/libpcre.a(libpcre.so.1)
         /tmp/apachetest/apr/lib/libiconv.a(libiconv.so.2)
         /tmp/apachetest/apr/lib/libcurl.a(libcurl.so.4)
         /unix
         /usr/lib/libcrypt.a(shr_64.o)
         /usr/lib/libxlsmp.a(smprt_64.o)
         /tmp/apachetest/apr/lib/libldap.a(libldap-2.4.so.2)
         /tmp/apachetest/apr/lib/liblber.a(liblber-2.4.so.2)
         /usr/lib/libpthreads.a(shr_xpg5_64.o)
         /usr/lib/libs.a(shr_64.o)

root@aixbuildhost61: /tmp/apachetest/bin # ./apachectl start
./apachectl[81]: 11665608 Memory fault(coredump)

root@aixbuildhost61: /tmp/apachetest/bin # dbx httpd core
Type 'help' for help.
[using memory image in core]
reading symbolic information ...

Segmentation fault in apr_tables.apr_array_push [/tmp/apachetest/modules/mod_security2.so] at 0x90000000356e910 ($t1)
0x90000000356e910 (apr_array_push+0x10) 809f0010         lwz   r4,0x10(r31)
(dbx) where
apr_tables.apr_array_push() at 0x90000000356e910
mod_security2.register_hooks() at 0x9000000035bf3bc
ap_register_hooks@AF123_81() at 0x100021420
ap_add_module() at 0x1000203e8
ap_add_loaded_module() at 0x100020074
mod_so.load_module() at 0x100064714
IPRA.$invoke_cmd() at 0x10001a33c
IPRA.$execute_now() at 0x100019fa4
IPRA.$ap_build_config_sub() at 0x100019dc4
ap_build_config() at 0x10001f614
ap_process_resource_config() at 0x10001ddc8
ap_read_config() at 0x10001eddc
main() at 0x100000860

**Comment by bostrt** [comment]
I'm no expert with AIX but I'm sure anyone who is will need a bit more information. Can you share what version of APR you are using? Also, does this memory fault always occur on startup when modsecurity is enabled?

**Comment by flynn1973** [comment]
we are not building from source anymore...closing.
