### ISSUE TITLE
Logging and Testing in Modsecurity-nginx + Libmodsecurity

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1319]
Hi,

   I have compiled libmodsecurity with ModSecurity-Nginx connector over Nginx-1.10.3 correctly without any issues. Now im looking at usage example at [`this`](https://github.com/SpiderLabs/ModSecurity-nginx). How do i add logging and do actual tests if the modsecurity is working or not in this setup ? Because im not seeing any difference in requests so far, so any info on how to add logs for this, May be an usage example would be great.

**Comment by Airis777** [comment]
Hi @vishaalgc ,

try look [here](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual). 
As far as I understood the question you need to use SecAudit* directives.

**Comment by zimmerle** [comment]
Hi @vishaalgc,

There are different ways to test if ModSecurity is really working, the most "informative" one is by enabling the DebugLogs - https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDebugLog
