### ISSUE TITLE
normalizePath vs normalisePath - inconsistent in wiki

### ISSUE THREAD

**Issue by jnazarioFastly** [SpiderLabs/ModSecurity#1320]
seeing inconsistencies in the wiki, "z" vs "s".

compare these two:
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#normalisePath
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#normalizePath

pick one. i believe the "z" is used in the actual transform function.

**Comment by csanders-git** [comment]
Thanks @jnazarioFastly you are correct the 'z' is the best practice. The 's' versions still work however they are only there for backwards compatibility. I have updated the documentation accordingly.
