### ISSUE TITLE
modsecurity / nginx error

### ISSUE THREAD

**Issue by jynxy** [SpiderLabs/ModSecurity#1321]
Hi, trying to add modsecurity with nginx but getting this issue, what am i doing wrong i had it working fine before on a previous version.

/usr/bin/ld: /root/sources/modsecurity-2.9.1/nginx/modsecurity/../../standalone/.libs/standalone.a(standalone_la-api.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/root/sources/modsecurity-2.9.1/nginx/modsecurity/../../standalone/.libs/standalone.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

i assume this is something to do with -fPIC but cant seem to get that to work,

**Comment by zimmerle** [comment]
Hi @jynxy,

You may want to try ModSecurity connector with libModSecurity:
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes

**Comment by jynxy** [comment]
Thanks for the reply,

What i dont understand is i had this working before, ive just changed the version of relevant libs etc to the latest versions and this has stopped working.

Thanks
