### ISSUE TITLE
Compile with "--enable-docs" fails

### ISSUE THREAD

**Issue by Ziris85** [SpiderLabs/ModSecurity#1322]
Evening everyone. I've been searching around for a while on if this is already a known issue and only found stuff from 4 years ago on sourceforge, so I apologize if I missed something. I tried compiling both the **v2.9.1** point release and the latest source available here and get the same issue. Whenever I configure with `--enable-docs`, the subsequent `make` fails with the following:
```
Making all in docs
/bin/sh: line 20: cd: docs: No such file or directory
make: *** [all-recursive] Error 1
```
There is a `doc` (no **s**) directory, but that looks to be for doxygen stuff, and I presume this flag is creating manpage documentation or something else?

Any help I can get on this would be greatly appreciated. Thanks!

**Comment by bostrt** [comment]
Looks like the doc directory does need to be renamed to doc**s**. Also, there's no Makefile in the doc directory so the documentation won't actually be built. I'm not very good with autoconf or I would submit a patch to try and help out here.

In the meantime, @Ziris85, you can build the docs manually but doing:

```
# cd ModSecurity
# doxygen doc/doxygen-apache.conf 
# doxygen doc/doxygen-nginx.conf
etc
```

After running those doxygen commands, the generated docs will be in `ModSecurity/doc/apache/html/index.html`

**Comment by zimmerle** [comment]
Fixed. #1415
