### ISSUE TITLE
Syntax error on line 56 of /etc/modsecurity/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf

### ISSUE THREAD

**Issue by breeman1** [SpiderLabs/ModSecurity#1323]
Hi,

I have installed version 3 of the modsecurity rules and when I start the apache server I get this error below;

 `service apache2 restart`           
 * Restarting web server apache2                                                                                                                                [fail] 
 * The apache2 configtest failed.
Output of config test was:
`AH00526: Syntax error on line 56 of /etc/modsecurity/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf:`
Error creating rule: Failed to resolve operator: detectXSS
Action 'configtest' failed.
The Apache error log may have more information.

Line 56 of the suspect conf file is `setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/XSS-%{matched_var_name}=%{tx.0}"`

The apache log do not seem to indicate much as to the cause of this error;

`tail -f /var/log/apache2/error.log 
[Tue Feb 07 17:15:25.172925 2017] [core:notice] [pid 1263] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 07 17:26:08.825041 2017] [mpm_prefork:notice] [pid 1263] AH00169: caught SIGTERM, shutting down
[Tue Feb 07 17:26:10.000216 2017] [:notice] [pid 1829] ModSecurity for Apache/2.7.7 (http://www.modsecurity.org/) configured.
[Tue Feb 07 17:26:10.000355 2017] [:notice] [pid 1829] ModSecurity: APR compiled version="1.5.1-dev"; loaded version="1.5.1-dev"
[Tue Feb 07 17:26:10.000360 2017] [:notice] [pid 1829] ModSecurity: PCRE compiled version="8.31 "; loaded version="8.31 2012-07-06"
[Tue Feb 07 17:26:10.000367 2017] [:notice] [pid 1829] ModSecurity: LUA compiled version="Lua 5.1"
[Tue Feb 07 17:26:10.000369 2017] [:notice] [pid 1829] ModSecurity: LIBXML compiled version="2.9.1"
[Tue Feb 07 17:26:11.003272 2017] [mpm_prefork:notice] [pid 1830] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Tue Feb 07 17:26:11.003344 2017] [core:notice] [pid 1830] AH00094: Command line: '/usr/sbin/apache2'
[Tue Feb 07 18:02:48.775470 2017] [mpm_prefork:notice] [pid 1830] AH00169: caught SIGTERM, shutting down`

I am not quite sure how to debug this error further and I need help. Thanks.

**Comment by csanders-git** [comment]
The OWASP Core Rule Set v3.0.0 requires a modern version (less than a few years old) of ModSecurity 2.8 or greater. Prior to this time libinjection wasn't part of the modsecurity platform. This is likely why you are seeing this message. Please update your ModSecurity :)
