### ISSUE TITLE
Error on "---" text input 

### ISSUE THREAD

**Issue by rodelarode** [SpiderLabs/ModSecurity#1325]
Denies posted data when i use multipart/form-data enctype and write "---" in any text field input at the very begining. 

ModSecurity: Access denied with code 44 (phase 2). Match of "eq 0" against "MULTIPART_UNMATCHED_BOUNDARY" required. [file "/etc/httpd/conf.d/mod_security.conf"] [line "30"] [id "200003"] [msg "Multipart parser detected a possible unmatched boundary."] ..... AH01579: Invalid response status 44,

**Comment by zimmerle** [comment]
Hi @rodelarode,

Can you share your ModSecurity version?

**Comment by rodelarode** [comment]
here is the details from my apache log realted to mod security. Hope it helps

[Sun Feb 12 04:00:04.459545 2017] [:notice] [pid 20820] ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/) configured.
[Sun Feb 12 04:00:04.459554 2017] [:notice] [pid 20820] ModSecurity: APR compiled version="1.5.0"; loaded version="1.5.1"
[Sun Feb 12 04:00:04.459556 2017] [:warn] [pid 20820] ModSecurity: Loaded APR do not match with compiled!
[Sun Feb 12 04:00:04.459559 2017] [:notice] [pid 20820] ModSecurity: PCRE compiled version="8.21 "; loaded version="8.21 2011-12-12"
[Sun Feb 12 04:00:04.459561 2017] [:notice] [pid 20820] ModSecurity: LUA compiled version="Lua 5.1"
[Sun Feb 12 04:00:04.459563 2017] [:notice] [pid 20820] ModSecurity: LIBXML compiled version="2.9.1"
[Mon Feb 13 04:00:04.219118 2017] [:notice] [pid 31230] ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/) configured.
[Mon Feb 13 04:00:04.219127 2017] [:notice] [pid 31230] ModSecurity: APR compiled version="1.5.0"; loaded version="1.5.1"
[Mon Feb 13 04:00:04.219130 2017] [:warn] [pid 31230] ModSecurity: Loaded APR do not match with compiled!
[Mon Feb 13 04:00:04.219132 2017] [:notice] [pid 31230] ModSecurity: PCRE compiled version="8.21 "; loaded version="8.21 2011-12-12"
[Mon Feb 13 04:00:04.219134 2017] [:notice] [pid 31230] ModSecurity: LUA compiled version="Lua 5.1"
[Mon Feb 13 04:00:04.219136 2017] [:notice] [pid 31230] ModSecurity: LIBXML compiled version="2.9.1"
[Tue Feb 14 04:00:04.615212 2017] [:notice] [pid 9383] ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/) configured.
[Tue Feb 14 04:00:04.615222 2017] [:notice] [pid 9383] ModSecurity: APR compiled version="1.5.0"; loaded version="1.5.1"
[Tue Feb 14 04:00:04.615225 2017] [:warn] [pid 9383] ModSecurity: Loaded APR do not match with compiled!
[Tue Feb 14 04:00:04.615228 2017] [:notice] [pid 9383] ModSecurity: PCRE compiled version="8.21 "; loaded version="8.21 2011-12-12"
[Tue Feb 14 04:00:04.615230 2017] [:notice] [pid 9383] ModSecurity: LUA compiled version="Lua 5.1"
[Tue Feb 14 04:00:04.615231 2017] [:notice] [pid 9383] ModSecurity: LIBXML compiled version="2.9.1"
[Wed Feb 15 04:00:03.970873 2017] [:notice] [pid 18855] ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/) configured.
[Wed Feb 15 04:00:03.970882 2017] [:notice] [pid 18855] ModSecurity: APR compiled version="1.5.0"; loaded version="1.5.1"
[Wed Feb 15 04:00:03.970884 2017] [:warn] [pid 18855] ModSecurity: Loaded APR do not match with compiled!
[Wed Feb 15 04:00:03.970887 2017] [:notice] [pid 18855] ModSecurity: PCRE compiled version="8.21 "; loaded version="8.21 2011-12-12"
[Wed Feb 15 04:00:03.970889 2017] [:notice] [pid 18855] ModSecurity: LUA compiled version="Lua 5.1"
[Wed Feb 15 04:00:03.970891 2017] [:notice] [pid 18855] ModSecurity: LIBXML compiled version="2.9.1"
[Wed Feb 15 20:09:57.583734 2017] [:notice] [pid 26854] ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/) configured.
[Wed Feb 15 20:09:57.583742 2017] [:notice] [pid 26854] ModSecurity: APR compiled version="1.5.0"; loaded version="1.5.1"
[Wed Feb 15 20:09:57.583745 2017] [:warn] [pid 26854] ModSecurity: Loaded APR do not match with compiled!
[Wed Feb 15 20:09:57.583747 2017] [:notice] [pid 26854] ModSecurity: PCRE compiled version="8.21 "; loaded version="8.21 2011-12-12"
[Wed Feb 15 20:09:57.583749 2017] [:notice] [pid 26854] ModSecurity: LUA compiled version="Lua 5.1"
[Wed Feb 15 20:09:57.583751 2017] [:notice] [pid 26854] ModSecurity: LIBXML compiled version="2.9.1"
[Thu Feb 16 04:00:04.215377 2017] [:notice] [pid 30750] ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/) configured.
[Thu Feb 16 04:00:04.215387 2017] [:notice] [pid 30750] ModSecurity: APR compiled version="1.5.0"; loaded version="1.5.1"
[Thu Feb 16 04:00:04.215389 2017] [:warn] [pid 30750] ModSecurity: Loaded APR do not match with compiled!
[Thu Feb 16 04:00:04.215392 2017] [:notice] [pid 30750] ModSecurity: PCRE compiled version="8.21 "; loaded version="8.21 2011-12-12"
[Thu Feb 16 04:00:04.215394 2017] [:notice] [pid 30750] ModSecurity: LUA compiled version="Lua 5.1"
[Thu Feb 16 04:00:04.215396 2017] [:notice] [pid 30750] ModSecurity: LIBXML compiled version="2.9.1"

**Comment by zimmerle** [comment]
Hi @rodelarode,

It does help, but I am afraid that I will need to have more details. Do you happens to have the data in question? Are you able to replicate the issue systematically ?

A wild guess, based on the ModSecurity error message, is that it seems that the request stopped to being transmitted before expected.

**Comment by zimmerle** [comment]
I am closing this issue as we didn't receive any feedback for the user. Apparently it was about a request that was terminated before complete.
