### ISSUE TITLE
Nginx with ModSecurity = Safari error

### ISSUE THREAD

**Issue by yvgorshkov** [SpiderLabs/ModSecurity#1326]
I compile nginx 1.11.9 with mod_security 2.9.1
When contacting the Safari browser to a site in the log comes out error:

> 2017/02/11 19:09:29 [alert] 8949#8949: worker process 10426 exited on signal 11
> 2017/02/11 19:09:29 [alert] 8949#8949: worker process 10427 exited on signal 11
> 2017/02/11 19:09:29 [alert] 8949#8949: worker process 10819 exited on signal 11
> 2017/02/11 19:09:34 [alert] 8949#8949: worker process 10424 exited on signal 11
> 2017/02/11 19:09:34 [alert] 8949#8949: worker process 10821 exited on signal 11
> 2017/02/11 19:09:34 [alert] 8949#8949: worker process 10820 exited on signal 11

After the debugger has collected the following information:

> Program received signal SIGSEGV, Segmentation fault.
> ngx_http_upstream_copy_allow_ranges (r=0x7263980, h=0x7ffdcebe9640, offset=<optimized out>) at src/http/ngx_http_upstream.c:5040
> 5040    src/http/ngx_http_upstream.c: Нет такого файла или каталога.
> (gdb)

With version 3.0 of the module is the same error.
With version 2.9.0 works fine.

Nginx -V

> nginx version: nginx/1.11.9
> built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
> built with OpenSSL 1.0.2k  26 Jan 2017
> TLS SNI support enabled
> configure arguments: --add-module=../modsecurity_nginx-2.9.1/nginx/modsecurity --user=nginx --group=nginx --prefix=/usr --sbin-path=/usr/sbin --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --http-log-path=/var/log/nginx/access_log --error-log-path=/var/log/nginx/error_log --with-ipv6 --without-mail_imap_module --without-mail_smtp_module --with-http_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_gzip_static_module --with-http_dav_module --with-cc-opt=''-D FD_SETSIZE=32768'' --with-http_v2_module --with-openssl=/usr/local/src/openssl-1.0.2k --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_flv_module --with-http_gunzip_module --with-http_mp4_module --with-http_random_index_module --with-http_secure_link_module --with-http_slice_module --with-http_sub_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-debug

Assembly log
[nginx_compiling.txt](https://www.sendspace.com/file/iyt11a)

**Comment by zimmerle** [comment]
Hi @yvgorshkov,

Please use the ModSecurity-nginx instead ModSecurity 2.9.1. You can find more information here: https://github.com/SpiderLabs/ModSecurity-nginx/
