### ISSUE TITLE
Question: Windows Server Nano and ModSecurity

### ISSUE THREAD

**Issue by eosfor** [SpiderLabs/ModSecurity#1327]
Hello Team, did you ever tried to install and test it on Server Nano?

**Comment by WithWings4** [comment]
I'm not part of the team, but I have had issues running it on IIS (full blown install). Specifically something with .net 4.0 crashing w3wp.exe, and blaming kernelbase.dll

For WSUS / Exchange it *seems* to be stable (using 3.0 rules, with blocking turned off, and 'SecStreamInBodyInspection On' added to the modsecurity.conf file) These are 2012 boxes, haven't tested 2012 R2, and even in this mode it broke a third party app using IIS, and kept crashing w3wp.exe

**Comment by zimmerle** [comment]
Hi @eosfor,

I didn't had the chance to test it. Please do share your findings ;)
