### ISSUE TITLE
Nginx does not handle the global rules.

### ISSUE THREAD

**Issue by yvgorshkov** [SpiderLabs/ModSecurity#1328]
Nginx does not handle the global rules.

> http {
> modsecurity on;
> modsecurity_rules_file /etc/nginx/nginx-modsecurity.conf;

If you register for a particular domain in the section server - it works.
What you need to do to work the global rules?

PS: ModSecurity-nginx

**Comment by zimmerle** [comment]
Hi @yvgorshkov.

Thank you for the report, I have moved this issue over the ModSecurity-nginx project, as it seems to be related to the connector, not to the ModSecurity library.
