### ISSUE TITLE
JSON Audit Log (v3/master)

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/ModSecurity#1331]
Hi,

This is not a real issue... but maybe can be useful. I'm reading the JSON audit log, i think that the "request method" is in the wrong parameter key on the JSON object:

```JSON
{
    "transaction": {
        "client_ip": "10.0.0.1",
        "time_stamp": "Tue Feb 21 08:52:17 2017",
        "server_id": "21f343330a49bdd82b0ed58322ecf1bf7d72013b",
        "client_port": 58005,
        "host_ip": "10.0.0.1",
        "host_port": 80,
        "id": "14876671370.793770",
        "request": {
            **"protocol": "GET",**
            "http_version": 1.1,
            "uri": "/?asd=asd",
...
}
```

Don't you think that using "protocol" for describe the request method can lead to misinterpretations? Isn't "method" a better description for it?

Thank you,
Best Regards.

-theMiddle

**Comment by zimmerle** [comment]
Hi @theMiddleBlue,

You are absolutely right! Maybe it was a copy&paste error. I dunno. It is fixed already. Changes are available here: https://github.com/SpiderLabs/ModSecurity/tree/v3/dev/parser

Thank you!
