### ISSUE TITLE
How do I configure SecWebApp for multiple virtual hosts on Microsoft IIS ?

### ISSUE THREAD

**Issue by bobwilmes** [SpiderLabs/ModSecurity#1333]
On Microsoft the IIS Manager defines virtual hosts through a graphic display panel like this:
http://www.visualwin.com/Host-Header/

Help please - I need to find a way to setup the SecWebApp configuration for IIS similar
to the Unix/Linux style configuration files like this:
<VirtualHost *:80> 
ServerName app1.com 
ServerAlias www.app1.com
SecWebAppId "App1"
SecRule REQUEST_COOKIES:PHPSESSID !^$ chain,nolog,pass 
SecAction setsid:%{REQUEST_COOKIES.PHPSESSID} 
... 
</VirtualHost>  

<VirtualHost *:80> 
ServerName app2.com 
ServerAlias www.app2.com
SecWebAppId "App2"
SecRule REQUEST_COOKIES:PHPSESSID !^$ chain,nolog,pass 
SecAction setsid:%{REQUEST_COOKIES.PHPSESSID} 
... 
</VirtualHost>

**Comment by victorhora** [comment]
You can do this kind of customization by tweaking with your web.config files. See the [README.TXT](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/iis/wix/README.TXT) for IIS.

Also these comments / issues may provide additional information to help you:

https://github.com/SpiderLabs/ModSecurity/issues/1656#issuecomment-437504283
https://github.com/SpiderLabs/ModSecurity/issues/1386#issuecomment-296510631
https://github.com/SpiderLabs/ModSecurity/issues/787
https://github.com/SpiderLabs/ModSecurity/issues/769
