### ISSUE TITLE
v3/dev/Parser or v3/master

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1336]
Hi,

  Im new to github, i was using modsecurity with "git checkout -b v3/master origin/v3/master" earlier. I have setup everything using this branch and its good. Recently an issue #1330 happened with me too and the fix was added in v3/dev/parser. Now to get that fix i took a new vm, used command "git checkout -b v3/dev/parser origin/v3/dev/parser" while compiling modsecurity and modsecurity-nginx. Right now i'm getting an error while compiling modsecurity on this branch but i had no issues in master. Whats the correct branch to use and how should i proceed ?

  Im following normal compilation recipees in documentation of modsecurity given.

**Comment by victorhora** [comment]
Hi @vishaalgc 

You can get the latest v3/dev/parser libmodsecurity branch using git clone like the following:
``
$ git clone -b v3/dev/parser https://github.com/SpiderLabs/ModSecurity.git
$ git clone -b v3/dev/parser https://github.com/SpiderLabs/ModSecurity-nginx
``
Please try this and let us know of the results.

On a side note, I did noticed that the current compilation recipes are suggesting using nginx v1.9.2. You could get the following compilation error while compiling nginx against libmodsecurity: 
``
error: ‘NGX_HTTP_VERSION_20’ undeclared (first use in this function)
``

You can pass by the error by commenting out this case switch snippet, or, better yet, by using a more recent version of nginx like the current latest version (1.11.10).

**Comment by victorhora** [comment]
Actually I just noticed that @defanator already applied a patch specifically to fix this compilation error with older versions of nginx :)

[https://github.com/SpiderLabs/ModSecurity-nginx/commit/618edd29ea3f77ab7be93557e25a66255f9acd56](url)

But looks like this was only applied on the master branch. I will suggest applying the same for the v3/dev/parser branch.

**Comment by vishaalgc** [comment]
hi @victorhora,

   I have taken latest v3/dev/parser and while compiling modsecurity i found warning saying "warning yywrap redefined" and after that i compiled nginx 1.10.3 stable and found error while make saying 

/opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c:426:5: error: passing argument 2 of ‘msc_set_log_cb’ from incompatible pointer type [-Werror]
     msc_set_log_cb(conf->modsec, ngx_http_modsecurity_log);
     ^
In file included from /opt/ModSecurity-nginx/src/ngx_http_modsecurity_common.h:25:0,
                 from /opt/ModSecurity-nginx/src/ngx_http_modsecurity_module.c:21:
/opt/ModSecurity/headers/modsecurity/modsecurity.h:325:6: note: expected ‘ModSecLogCb’ but argument is of type ‘void (*)(void *, const char *)’
 void msc_set_log_cb(ModSecurity *msc, ModSecLogCb cb);

This error is produced on executing make in nginx. Please help me with this,

Thanks,
Vishaal

**Comment by defanator** [comment]
@victorhora, @vishaalgc, I've just updated the [v3/dev/parser](https://github.com/spiderlabs/modsecurity-nginx/tree/v3/dev/parser) branch of ModSecurity-nginx with the fix for building with older nginx versions.

Though I tend to think that using the most recent mainline version of nginx (1.11.10 at the moment) is the best way to test/evaluate ModSecurity connector.

**Comment by zimmerle** [comment]
The branch /v3/dev/parser is now part of the v3/master, so I am closing this issue.
