### ISSUE TITLE
Server Status page totally messed up on apache 2.4.25 with MPM Event

### ISSUE THREAD

**Issue by tjikkun** [SpiderLabs/ModSecurity#1337]
I have Apache 2.4.25 running with MPM Event, but as soon as I load mod_security the Apache status page goes all bonkers: I see stuff like:
Total accesses: 9985310457595812052 - Total Traffic: 12398867456.0 GB
CPU Usage: u5.40831e+11 s1.87 cu0 cs0 - 1.56e+11% CPU load
2.89e+16 requests/sec - 35834876.0 GB/second - 1 B/request
Also the requests have incorrect IP's sometimes (73.101 as example, it is missing 2 dots)

**Comment by bostrt** [comment]
@tjikkun what version of mod_security are you using? Do you have any SecRule/Actions applied or are you just loading the module?

**Comment by tjikkun** [comment]
@bostrt Ah good questions. Sorry I forgot to mention this happens with both 2.9.0 and 2.9.1, haven't tested older versions.

As to your second question, I hadn't really thought about it but I did some digging and as it turns out just loading the module does not show the problem, minimum config to reproduce needs to have
SecConnReadStateLimit <any number>

**Comment by tjikkun** [comment]
I found the issue, will try to put in a pull request tomorrow, should also fix #786
