### ISSUE TITLE
where is libmodsecurity

### ISSUE THREAD

**Issue by calistochen** [SpiderLabs/ModSecurity#1338]
excuse me,why could't i found the patch of libmodsecurity,and WIKI ,i could't see any about libmodsecurity

**Comment by p0pr0ck5** [comment]
Are you looking for the actual source code?

https://github.com/SpiderLabs/ModSecurity/tree/v3/master

**Comment by bostrt** [comment]
@calistochen In addition to @p0pr0ck5's comment, the wiki pages can be found https://github.com/SpiderLabs/ModSecurity/wiki/ModSecurity-version-3-(earlier-release-candidate-1)

More links are on the right of the wiki page.
