### ISSUE TITLE
New .example file to whitelist IP addresses

### ISSUE THREAD

**Issue by ishenkoyv** [SpiderLabs/ModSecurity#1342]
Hi
It would be good to have some additional .example file which will be loaded after REQUEST-901-INITIALIZATION.conf, like application specific one. In case of usage webserver behind loadbalancer (e.g. AWS ELB) tx.real_ip is calculated inside the initialization config and REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf can't be used.
Thanks

**Comment by zimmerle** [comment]
Hi @ishenkoyv, 

I guess the best place for this specific issue is on the OWASP CRS project:
https://github.com/SpiderLabs/owasp-modsecurity-crs
