### ISSUE TITLE
Caddy web server support 

### ISSUE THREAD

**Issue by medfx** [SpiderLabs/ModSecurity#1344]
Any plans to support the next generation web server caddy in the future?
https://github.com/mholt/caddy

How does the ModSecurity team decides which web servers get native support?

**Comment by zimmerle** [comment]
Hi @medfx.

As of ModSecurity version 3 the link between the ModSecurity library and the WebServer will be held by something called connector. The connector main function is to create a layer between ModSecurity and Web Server.

You can check more about version 3 here:
https://github.com/SpiderLabs/ModSecurity/wiki#modsecurity-3

The nginx connector for version 3 is available here:
https://github.com/SpiderLabs/ModSecurity-nginx

Are you interested in start the development of the Caddy connector?

**Comment by csanders-git** [comment]
@medfx i'd like to help you with this if you're willing to work on the project with me.

**Comment by medfx** [comment]
@csanders-git I'm willing to help. The problem is that I have never used C, C++ or Go before. I'm a web developer in search of a secure web server. I think Caddy is great, but would be even better with ModSecurity. So tell me if and where I can help you.

**Comment by Nurmagoz** [comment]
what happened to this ticket? is it support or not? cc @zimmerle

**Comment by redoracle** [comment]
I am also looking for ModSecurity to be able to work with Caddy, I have been using it with NGinx for the last 10 years after transitioning from Apache but now I have moved to Caddy. I miss ModSecurity a lot :)

**Comment by airween** [comment]
> I am also looking for ModSecurity to be able to work with Caddy, I have been using it with NGinx for the last 10 years after transitioning from Apache but now I have moved to Caddy. I miss ModSecurity a lot :)

Have you seen [Coraza](https://github.com/corazawaf/)?

**Comment by redoracle** [comment]
Just looking into it :)
