### ISSUE TITLE
request_body_processor/json.h:17:29: fatal error: yajl/yajl_parse.h: No such file or directory

### ISSUE THREAD

**Issue by jinri** [SpiderLabs/ModSecurity#1346]
**when i build the v3/master ,i have this problem**

`
a-transaction.o
In file included from transaction.cc:41:0:
request_body_processor/json.h:17:29: fatal error: yajl/yajl_parse.h: No such file or directory
 #include <yajl/yajl_parse.h>
                             ^
compilation terminated.
make[2]: *** [libmodsecurity_la-transaction.lo] Error 1
make[2]: Leaving directory `/home/gjf/work/ModSecurity/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/gjf/work/ModSecurity/src'
make: *** [all-recursive] Error 1
`

**Comment by jinri** [comment]
Is this way can solve it?
[(http://stackoverflow.com/questions/1338496/mgtwitterengine-for-iphone-sdk-errors)]
`git clone git://github.com/lloyd/yajl
cd yajl
./configure
sudo make install`

**Comment by jinri** [comment]
git clone git://github.com/lloyd/yajl
cd yajl
./configure
sudo make install

**Comment by csanders-git** [comment]
@jinri I take it the issue is solved then?

**Comment by zimmerle** [comment]
Closing this as it seems that the issue is already solved.
