### ISSUE TITLE
External Auth with Modsecurity Issue

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1348]
Hi,

   Whenever i try to connect to facebook, Linked In, twitter from my application, modsecurity is blocking the requests. The response i get is 

  <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.11.10</center>
</body>
</html>

On further checking logs i found out these warnings.

ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `TX' (Value: `0' ) [file "/opt/owasp-modsecurity-crs/rules/REQUEST-912-DOS-PROTECTION.conf"] [line "80"] [id "912100"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""]
ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/usr/local/nginx/conf/modsec.conf"] [line "50"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "Unknown request body processor: application/text; charset=utf-8"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [ref "v1128,1"]
ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `TX' (Value: `0' ) [file "/opt/owasp-modsecurity-crs/rules/REQUEST-912-DOS-PROTECTION.conf"] [line "74"] [id "912110"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""]

Any ideas on how to resolve this ?

Thanks,
Vishaal

**Comment by zimmerle** [comment]
Hi @vishaalgc,

That was using v3? or v2.x?

**Comment by vishaalgc** [comment]
@zimmerle  This was using v3 latest.

**Comment by zimmerle** [comment]
Related to #1356

**Comment by zimmerle** [comment]
As of d15b57895b475da735f02eced50cac2148e94231 this is no longer an issue.
