### ISSUE TITLE
master/v3 audit log missing

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/ModSecurity#1349]
Hi,

i've a problem with nginx + modsecurity3 (master/v3 + nginx connector). It seems that no all requests are logged by using concurrent audit log...

I've configured the audit log as the following:
```
SecAuditEngine On
SecAuditLogRelevantStatus ".*"
SecAuditLogParts ABCIJDEFHZ
SecAuditLogType concurrent
SecAuditLog /usr/local/nginx/logs/modsec_audit.log
SecAuditLogStorageDir /usr/local/nginx/logs/modsecurity
```

my test:
```
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=1"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=2"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=3"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=4"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=5"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=6"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=7"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=8"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=9"
curl -H "Referer:() {:;}; sleep 10" "http://mywebsite/?test.log=10"
```

grep on all audit log files:
```
# grep 'test\.log' /usr/local/nginx/logs/modsecurity/20170310/*/*
/usr/local/nginx/logs/modsecurity/20170310/20170310-1050/20170310-105033-14891394331.000000:            "uri": "/?test.log=3",
/usr/local/nginx/logs/modsecurity/20170310/20170310-1050/20170310-105038-14891394381.000000:            "uri": "/?test.log=8",
```

It seems that only 2 requests has been logged... anyone has the same problem? am I missing something?

thank you,
Best Regards!

-theMiddleBlue

**Comment by zimmerle** [comment]
Hi @theMiddleBlue,

Thanks for the report. Under investigation ;)

**Comment by theMiddleBlue** [comment]
Hi @zimmerle 

after some other tests, i've improved my configuration:

- I've comment out the SecAuditLog parameter and now seems it works better

- Configuring multiple server (or virtual host) logging on the same directory, it cause the overwrite of audit file when concurrent request occur. Configuring each server on different and dedicated directory it works better.

Hope this help,
thank you!

-theMiddle

**Comment by zimmerle** [comment]
Hi @theMiddleBlue,

As of d15b57895b475da735f02eced50cac2148e94231 you can specify the **auditlogs** configurations in the global section. Also, you should be able to use the same log file for different _vhosts_, without loosing content.
