### ISSUE TITLE
ModSecurity: Warning. Match of "beginsWith POST" against "REQUEST_LINE" required

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#1350]
I wrote this rule to make true only the post requests would be written into the audit log:
SecRule REQUEST_LINE "!@beginsWith POST" "phase:1,pass,ctl:auditEngine=Off,noauditlog,id:50".
This rule has already worked,but I notice that there are some error messages in the error log files:

ModSecurity: Warning. Match of "beginsWith POST" against "REQUEST_LINE" required.

I solved this problem for the time being by adding the action of 'nolog',but are there potential problems?
Thank you!

**Comment by p0pr0ck5** [comment]
These are not errors; it's just the entry ModSecurity generates when a rule matches. Adding `nolog` is the appropriate solution. :)
