### ISSUE TITLE
master/v3 action allow doesn't work

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/ModSecurity#1351]
Hi,

it seems that the "allow" action doesn't work as expected with the following configuration:

```
SecDefaultAction "phase:1,log,auditlog,deny,status:403"
SecDefaultAction "phase:2,log,auditlog,deny,status:403"

SecRule REQUEST_FILENAME "^\/test\.php$" "id:998,phase:request,chain"
SecRule REQUEST_METHOD "^POST$" "id:998,phase:request,log,allow"
```

trying to make a POST request to `/test.php` i get always a status 403. I tried using `ctl:ruleEngine=Off` but it has no effect. Am I doing something wrong? Which is the best way to disable the ruleEngine on a specific request?

Thank you,
Best Regards.

-theMiddle

**Comment by zimmerle** [comment]
6421ff087a25331f9b389781432960e919659a4a should fix this issue by printing the right error message
