### ISSUE TITLE
Apache segmentation fault

### ISSUE THREAD

**Issue by LukeP21** [SpiderLabs/ModSecurity#1353]
Specifying ctl:ruleRemoveTargetByTag= with only 1 parameter causes Apache to pass a configtest but seg fault.

Example:              
ctl:ruleRemoveTargetByTag=attack-disclosure

Tested on both:
Apache/2.4.23 with modsecurity-2.9.1
Apache/2.2.15 with modsecurity-2.9.1

I'm aware it should be ctl:ruleRemoveByTag=attack-disclosure just made a mistake and noticed seg faults.

**Comment by zimmerle** [comment]
Closed as of: 9ac9ff8
