### ISSUE TITLE
Questions about apache+v3 libmodsecurity

### ISSUE THREAD

**Issue by bali2016** [SpiderLabs/ModSecurity#1355]
As I know in the v3 modsecurity, there is a connector for different platforms, it doesn't need to wrapper the  Apache internals to link ModSecurity to different platforms.  Looks like the enhancement is only for non-apache platform, so I have wonderings here:

1. Will Apache need a connector when use v3 modsecurity?
2. Will apache+v3libmodsecurity have a better performace than apache+v2.xmodscurity?  I think it should have not much improvment, because it currently doesn't need to wrapper. Want someone to give a sure answer.

**Comment by zimmerle** [comment]
Hi @bali2016,

The motivation and goals for v3 is linked in our wiki page -
https://github.com/SpiderLabs/ModSecurity/wiki

Yes, Apache is going to need a connector. We do have a earlier stage development for a connector here:
https://github.com/SpiderLabs/ModSecurity-apache

Once fully implemented, the idea is that the libModSecurity will be faster. Technically the connectors are not really a wrapper.

**Comment by bali2016** [comment]
Thanks for your reply. :+1:
