### ISSUE TITLE
Issue with Uploading images

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1356]
hi,

  When i try to upload images onto my server i'm getting this error in logs, 

ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/usr/local/nginx/conf/modsec.conf"] [line "50"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "Unknown request body processor: image/jpeg"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [ref "v167,1"]

Using the latest modsecurity v3 and Modsecurity-nginx Connector. Any ideas on how to resolve this ?

Thanks,
Vishaal

**Comment by victorhora** [comment]
Hi @vishaalgc 

I was trying to reproduce your issue by crafting a standard multipart/format-data POST "upload" request with a JPEG file on the body and didn't catch similar errors.

Could you please share some more info like the POST request, versions info and debug log?

Thanks.

**Comment by zimmerle** [comment]
Hi @vishaalgc and @victorhora,

Running some tests on v3 I figured that it was issuing the error message to every unknown content type. 
As of: d15b57895b475da735f02eced50cac2148e94231 this error message should not appear anymore.
