### ISSUE TITLE
Request timeout with 408 with POST request

### ISSUE THREAD

**Issue by pipozzz** [SpiderLabs/ModSecurity#1358]
Hello,

I'm experiencing request timeout with no log when posting image larger than 10kB and limits have set to 20MB, so request do no get to upstream.

SecDefaultAction "phase:1,log,auditlog,deny,status:403
SecDefaultAction "phase:2,log,auditlog,deny,status:403
SecRequestBodyLimit 20971520
SecRequestBodyNoFilesLimit 20971520

**Comment by zimmerle** [comment]
Hi @pipozzz ,

Can you give us more details on your ModSecurity deployment? Version for ModSecurity and web server would be very valuable.

**Comment by zimmerle** [comment]
Looks like a nginx with ModSec 2.x. Closing this issue.
