### ISSUE TITLE
Modsecurity1.9 + nginx An unsolved problem

### ISSUE THREAD

**Issue by houhuijian** [SpiderLabs/ModSecurity#1360]
This is a particularly interesting question，When I use the nginx reverse proxy function,If you only add a server, and the port is used 80，Modsecurity works very well（Of course, early to solve a lot of problems, for example, can not upload more than 8K pictures such as the problem），But when I add a second server, the problem arises，When I add the second server to use the port is also 80，Can not post request, that post request will be blocked，
![image](https://cloud.githubusercontent.com/assets/12180923/24243600/9ccb239e-0ff6-11e7-99cf-28861aaab0f0.png)
When the second server port is modified to non-80，Everything is fine，But the reverse proxy is the use of different domain names, the use of the same port, why use modsecurity will be such a problem, I hope we can help solve，

**Comment by zimmerle** [comment]
Hi @houhuijian,

Please have a try on ModSecurity-nginx connector - 
https://github.com/SpiderLabs/ModSecurity-nginx
