### ISSUE TITLE
modsecurity 2.9.1 for nginx nonsupport subrequest ?

### ISSUE THREAD

**Issue by knight06** [SpiderLabs/ModSecurity#1361]
nginx: 1.10.1
modsecurity: 2.9.1
nginx.conf:

location /loc1  {
            #ModSecurityEnabled on;
            #ModSecurityConfig  modsecurity.conf;
            content_by_lua  ' ngx.location.capture('/loc2')';
}

location /loc2 {
            ModSecurityEnabled on;
            ModSecurityConfig  modsecurity.conf;
            proxy_pass http://192.168.0.11:8080$request_uri;
}

1. only enable ModSecurity in /loc1, the rules take effect. 
2. only enable ModSecurity in /loc2, the rules have no effect. that is to say, the ModSecurity does not take effect in the nginx internal subrequest.

Any good suggestions? Thanks!

**Comment by zimmerle** [comment]
Hi @knight06 you may want to try ModSecurity v3 with nginx -
https://github.com/SpiderLabs/ModSecurity-nginx
