### ISSUE TITLE
LuaJIT with ModSecurity 2.9

### ISSUE THREAD

**Issue by JackHopkins** [SpiderLabs/ModSecurity#1362]
Has anyone got LuaJIT to work with ModSecurity 2.9? 
Where is Lua5.1 loaded from, and would it be possible to subvert this step?

**Comment by zimmerle** [comment]
Hi @JackHopkins,

What kind of problems you are having with the Lua integration?

To check where ModSecurity is loading the Lua library from, you can use ldd - 

```
ldd mod_security2.so 
(...)
       liblua.so => /usr/lib/liblua.so (0x00007fb2fe611000) 
       libm.so.6 => /usr/lib/libm.so.6 (0x00007fb2fe2fe000) 
(...)
``` 

There is also the version confirmation during the ModSecurity load on error log.

As for the build time, you can check the configure script output.

**Comment by JackHopkins** [comment]
Thanks for your swift reply!
I would like to execute my scripts using LuaJIT, considering the speed up that this entails. 
I have the LuaJIT .so file, but I'm not sure how to replace Lua5.1 in Modsecurity with this. Do you have any ideas?

**Comment by zimmerle** [comment]
In your Apache configuration you should have a line to load ModSecurity, it should be something similar to:
```
LoadModule security2_module /path/to/mod_security2.so
```

Just before load ModSecurity you can load your LuaJIT .so file. As following:
```
LoadFile /path/to/your/lua-jit.so
```

Lua and LuaJIT are binary compatible, so this change should be enough.

**Comment by JackHopkins** [comment]
I've done this, and in my error log it still says "Lua5.1", along with no speed up.
I have even replaced the content of /usr/lib/liblua.so with the content from /usr/lib/libluajit.so, which was unsuccessful.
Is there a step that I'm missing?

**Comment by zimmerle** [comment]
If you replaced the content of the **lua.so** file, with **libjit.so**. I am sure that it loaded the JIT version :)

Regarding the _error log_, the notice that what you saw there was built upon the **compilation time**. So it will not report any change on **run time**. Here is the relevant piece of code:
https://github.com/SpiderLabs/ModSecurity/blob/8559dd3b8bfab22a06d1372a2a20fcaa207c96be/apache2/mod_security2.c#L129-L132

I am not so sure, however, why you are not having any benefits in terms of performance.

**Comment by JackHopkins** [comment]
Thanks a lot for clearing that up for me. Its good to know that ModSecurity loaded the right version, so now I can go hunting for whatever is hitting the performance.

Cheers!
