### ISSUE TITLE
Rotate ability for SecDebugLog

### ISSUE THREAD

**Issue by macapone** [SpiderLabs/ModSecurity#1367]
We use cronolog for rotating all of our apache logs.  Currently, for SecAuditLog, this works in mod_security 3.0:

SecAuditLogType Serial
SecAuditLog "|/usr/local/sbin/cronolog --symlink=/usr/local/apache/logs/modsec_audit.log /usr/local/apache/logs/modsec_audit_%m%d%y.log"

however, piping the DebugLog fails:
SecDebugLog "|/usr/local/sbin/cronolog --symlink=/usr/local/apache/logs/modsecurity.log /usr/local/apache/logs/modsecurity_%m%d%y.log"

Syntax error on line 175 of /usr/local/apache/modsecurity.d/modsecurity.conf:
ModSecurity: Failed to open debug log file: /usr/local/apache/|/usr/local/sbin/cronolog --symlink=/usr/local/apache/logs/modsecurity.log /usr/local/apache/logs/modsecurity_%m%d%y.log

Can the SecDebugLog directive be fixed to allow the same pipe handling as the Audit Log?

**Comment by zimmerle** [comment]
Hi @macapone,

In ModSecurity version 3, you can have a custom DebugLog back-end. The DebugLogs are meant to write the rules, not really to be used in production. That is why we never had the pipe functionality implemented for it. Enable the debuglogs in production may reduce significantly the performance.

If you are intend to build an UI for rules customization, I would suggest the implementation of a custom DebugLog engine while calling the libModSecurity API.
