### ISSUE TITLE
Feature Request: t:uppercase is missing

### ISSUE THREAD

**Issue by angeloxx** [SpiderLabs/ModSecurity#1370]
Current version of the Reference Manual refers to a transform (https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#base64decode) t:uppercase that does not exist. It isn't a great issue, but in some circumstances it can be helpful and it is the perfect complement to the lowercase transform function. Now I've implemented it in Lua but I'm not so happy.

**Comment by csanders-git** [comment]
yeah, interesting. In general i can't think of a reason where uppercase would be needed versus lowercase on the backend like this as ascetics don't matter. In any event i've created a pull request to update the docs

**Comment by csanders-git** [comment]
@angeloxx I removed a reference, what were you thinking as the use case for this transformation? I'm more than happy to add it as a feature to v3 if we determine that it makes sense.

**Comment by angeloxx** [comment]
Thank you @csanders-git for your question; my use case is very trivial, I need to log the SHA1 version of the sessionid and I want it in uppercase format to find it easly in the log file. It isn't the most common use of a transform, but if the lowercase is available I think is a good idea to implement the uppercase also. 
To be more serious, always in the same context will be useful to also have the SHA256 (or similar) hashing algorithm because the md5 and sha1 - in our use case - is too weak.

**Comment by victorhora** [comment]
@angeloxx I've submitted pull request #1439 for this feature in libModSecurity. It should be accepted to the main v3 branch once @zimmerle finishes his review process. You might want to give it a try before to see if helps with your needs.

**Comment by victorhora** [comment]
I will close this one now and update the docs once the patch is accepted in the master. Let us know if anything and we reopen it if needed.

**Comment by victorhora** [comment]
Added to the Reference manual as of [4a6998b](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual/4a6998b367be2409042a806c8c3bf0cde4c2932c)
