### ISSUE TITLE
Apache2: mod_session should populate ENV vars before rule execution

### ISSUE THREAD

**Issue by nickmarden** [SpiderLabs/ModSecurity#1372]
Proposed patch: https://github.com/SpiderLabs/ModSecurity/pull/1371

The fixup hook processing order in `mod_security2.c` allows mod_env to run its fixups before ModSecurity takes over, but does not offer the same opportunity to mod_session.

We would like to use mod_session to keep track of whether a particular client IP + session has answered our captcha challenge. This requires access to the `ENV:HTTP_SESSION` value populated by `SessionEnv`.

In the current implementation of mod_security2, the fact that mod_session is registered to fire after mod_security2 (or, more precisely, isn't registered to fire _before_ mod_security2) in the fixup phase means that the environment variable HTTP_SESSION is not yet set when we'd like it to be.

```
<LocationMatch ^/captcha>
  Session On
  SessionEnv On
  SessionMaxAge 3000
  SessionCookieName bon-session path=/
  SessionHeader X-Bot-Or-Not-Session
</Location>

<Location /stuff-protected-by-captcha>
  Session On
  SessionEnv On
  SessionCookieName bon-session path=/

  SecRuleEngine On

  # skip to the bottom if the bot-or-not session contains the correct client_ip and user_agent
  SecRule ENV:HTTP_SESSION "bon_client_ip" "id:12344,phase:2,skipAfter:END_BOT_CHALLENGE,pass"

  # maintain a leaky bucket counter per client ip that increases by 1 for each request and decreases by 1 every 10 seconds
  SecAction "id:12345,phase:2,initcol:ip=%{CLIENT_IP},pass,msg:'init leaky bucket'"
  SecAction "id:12346,phase:2,pass,setvar:IP.leakybucketcounter=+1,msg:'increment leaky bucket'"
  SecAction "id:12347,phase:5,deprecatevar:IP.leakybucketcounter=1/10,pass,msg:'decrement leaky bucket'"

  # redirect to the captcha is the counter has exceeded the threshold
  SecRule IP:LEAKYBUCKETCOUNTER "@gt 5" "id:12348,phase:2,setenv:CHALLENGE=yes,pass"
  RewriteCond %{ENV:CHALLENGE} ^yes$
  RewriteRule ^(/stuff-protected-by-captcha.*)$ "/captcha/challenge?r=$1" [B]

  SecMarker END_BOT_CHALLENGE
</Location>
```

**Comment by victorhora** [comment]
I'm closing this issue due to lack of feedback from the community.

If this feature is deemed important, let us know and we can reopen for revaluation. See also https://github.com/SpiderLabs/ModSecurity/pull/1371#issuecomment-424200802
