### ISSUE TITLE
Error in reference to #inspectfile on wiki

### ISSUE THREAD

**Issue by trakons** [SpiderLabs/ModSecurity#1376]
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#inspectfile
Please change 
`SecRule FILES_TMPNANMES "@inspectFile inspect.lua" "id:160"`
to
`SecRule FILES_TMPNAMES "@inspectFile inspect.lua" "id:160"`

The `--disable-summary` are deprecated in code:
```
#!/usr/bin/perl
#
# runav.pl
# Copyright (c) 2004-2011 Trustwave
#
# This script is an interface between ModSecurity and its
# ability to intercept files being uploaded through the
# web server, and ClamAV


$CLAMSCAN = "clamscan";

if ($#ARGV != 0) {
    print "Usage: runav.pl <filename>\n";
    exit;
}

my ($FILE) = shift @ARGV;

$cmd = "$CLAMSCAN --stdout --disable-summary $FILE";
$input = `$cmd`;
$input =~ m/^(.+)/;
$error_message = $1;

$output = "0 Unable to parse clamscan output [$1]";

if ($error_message =~ m/: Empty file\.?$/) {
    $output = "1 empty file";
}
elsif ($error_message =~ m/: (.+) ERROR$/) {
    $output = "0 clamscan: $1";
}
elsif ($error_message =~ m/: (.+) FOUND$/) {
    $output = "0 clamscan: $1";
}
elsif ($error_message =~ m/: OK$/) {
    $output = "1 clamscan: OK";
}

print "$output\n";
```

**Comment by trakons** [comment]
`--disable-summary` is replaced by `--no-summary`

**Comment by csanders-git** [comment]
Thank you for your changes. Great looking out. Is clamAV working as expected now? let me know if you have any additional changes. Have a great day!

**Comment by zimmerle** [comment]
@csanders-git  Any specific reason to tag this as "libmodsecurity"?

**Comment by csanders-git** [comment]
it was our only missing documentation tag ;) @zimmerle

**Comment by defanator** [comment]
May be useful to check: https://github.com/SpiderLabs/ModSecurity/issues/1610#issuecomment-374595049
