### ISSUE TITLE
Segmentation Fault (11)

### ISSUE THREAD

**Issue by bjdijk** [SpiderLabs/ModSecurity#1387]
Testing mod_security release 2.9.1 on httpd 2.4.18 and httpd 2.2.15 seems to trigger a segmentation fault if mod_security is loaded, the engine is switched off for the vhost by SecRuleEngine Off but the Custom Logs still refer to mod_security directives like below.

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %v %A %p %R %{BALANCER_WORKER_ROUTE}e \
        %X \"%{cookie}n\" %{UNIQUE_ID}e %I %O %{ratio}n%% %D %{TX.perf_modsecinbound}M %{TX.perf_application}M \
        %{TX.perf_modsecoutbound}M %{TX.INBOUND_ANOMALY_SCORE}M %{TX.OUTBOUND_ANOMALY_SCORE}M" extended
CustomLog logs/appdanqas_ssl_access_log extended

Not sure why, but commenting these out, resolve the segmentation faults reported

**Comment by zimmerle** [comment]
Hi @bjdijk,

Do you mind to share ModSecurity initialization lines? It is part of your Apache **error_log** and contains details about all ModSecurity dependencies. The segfault could be consequence of a version mismatch.

**Comment by bjdijk** [comment]
This is what I have for httpd-2.4

[Tue Apr 18 13:08:18.852531 2017] [core:notice] [pid 17614] core dump file
size limit raised to 18446744073709551615 bytes
[Tue Apr 18 13:08:18.860224 2017] [ssl:warn] [pid 17614] AH01916: Init: (
127.0.0.1:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Tue Apr 18 13:08:18.861458 2017] [suexec:notice] [pid 17614] AH01232:
suEXEC mechanism enabled (wrapper: /opt/rh/httpd24/root/usr/sbin/suexec)
[Tue Apr 18 13:08:18.861616 2017] [jk:warn] [pid 17614] No JkLogFile
defined in httpd.conf. Using default /etc/httpd/logs/mod_jk.log
[Tue Apr 18 13:08:18.861731 2017] [jk:warn] [pid 17614] No JkLogFile
defined in httpd.conf. Using default /etc/httpd/logs/mod_jk.log
[Tue Apr 18 13:08:18.863085 2017] [:notice] [pid 17614] ModSecurity for
Apache/2.9.1 (http://www.modsecurity.org/) configured.
[Tue Apr 18 13:08:18.863103 2017] [:notice] [pid 17614] ModSecurity: APR
compiled version="1.3.9"; loaded version="1.5.1"
[Tue Apr 18 13:08:18.863111 2017] [:warn] [pid 17614] ModSecurity: Loaded
APR do not match with compiled!
[Tue Apr 18 13:08:18.863119 2017] [:notice] [pid 17614] ModSecurity: PCRE
compiled version="8.40 "; loaded version="8.13 2011-08-16"
[Tue Apr 18 13:08:18.863127 2017] [:warn] [pid 17614] ModSecurity: Loaded
PCRE do not match with compiled!
[Tue Apr 18 13:08:18.863133 2017] [:notice] [pid 17614] ModSecurity: YAJL
compiled version="2.1.0"
[Tue Apr 18 13:08:18.863140 2017] [:notice] [pid 17614] ModSecurity: LIBXML
compiled version="2.7.6"
[Tue Apr 18 13:08:18.863218 2017] [:notice] [pid 17614] ModSecurity:
StatusEngine call: "2.9.1,Apache,1.3.9/1.5.1,8.40/8.13
2011-08-16,(null),2.7.6,3c49f810d6f91d4ff1831cc02d604de11a3c4b69"
[Tue Apr 18 13:08:18.971758 2017] [:notice] [pid 17614] ModSecurity:
StatusEngine call successfully sent. For more information visit:
http://status.modsecurity.org/
[Tue Apr 18 13:08:19.163851 2017] [auth_digest:notice] [pid 17616] AH01757:
generating secret for digest authentication ...
[Tue Apr 18 13:08:19.168529 2017] [ssl:warn] [pid 17616] AH01916: Init: (
127.0.0.1:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Tue Apr 18 13:08:19.169973 2017] [lbmethod_heartbeat:notice] [pid 17616]
AH02282: No slotmem from mod_heartmonitor
[Tue Apr 18 13:08:19.172323 2017] [jk:warn] [pid 17616] No JkLogFile
defined in httpd.conf. Using default /etc/httpd/logs/mod_jk.log
[Tue Apr 18 13:08:19.172423 2017] [jk:warn] [pid 17616] No JkLogFile
defined in httpd.conf. Using default /etc/httpd/logs/mod_jk.log
[Tue Apr 18 13:08:19.181423 2017] [mpm_prefork:notice] [pid 17616] AH00163:
Apache/2.4.18 (Red Hat) OpenSSL/1.0.1e-fips mod_jk/1.2.41 configured --
resuming normal operations
[Tue Apr 18 13:08:19.181467 2017] [core:notice] [pid 17616] AH00094:
Command line: 'httpd'

And this for httpd-2.2

[Tue Mar 28 10:35:33 2017] [notice] suEXEC mechanism enabled (wrapper:
/usr/sbin/suexec)
[Tue Mar 28 10:35:34 2017] [warn] Init: (127.0.0.1:443) You configured
HTTP(80) on the standard HTTPS(443) port!
[Tue Mar 28 10:35:34 2017] [notice] ModSecurity for Apache/2.9.1 (
http://www.modsecurity.org/) configured.
[Tue Mar 28 10:35:34 2017] [notice] ModSecurity: APR compiled
version="1.3.9"; loaded version="1.3.9"
[Tue Mar 28 10:35:34 2017] [notice] ModSecurity: PCRE compiled version="7.8
"; loaded version="7.8 2008-09-05"
[Tue Mar 28 10:35:34 2017] [notice] ModSecurity: YAJL compiled
version="2.1.0"
[Tue Mar 28 10:35:34 2017] [notice] ModSecurity: LIBXML compiled
version="2.7.6"
[Tue Mar 28 10:35:34 2017] [notice] ModSecurity: StatusEngine call:
"2.9.1,Apache,1.3.9/1.3.9,7.8/7.8
2008-09-05,(null),2.7.6,3e3be20c9f054ed680b7af8b87a5277d1fe8b82d"
[Tue Mar 28 10:35:34 2017] [notice] ModSecurity: StatusEngine call
successfully sent. For more information visit:
http://status.modsecurity.org/
[Tue Mar 28 10:35:34 2017] [notice] Digest: generating secret for digest
authentication ...
[Tue Mar 28 10:35:34 2017] [notice] Digest: done
[Tue Mar 28 10:35:35 2017] [warn] Init: (127.0.0.1:443) You configured
HTTP(80) on the standard HTTPS(443) port!
[Tue Mar 28 10:35:35 2017] [warn] pid file /etc/httpd/run/httpd.pid
overwritten -- Unclean shutdown of previous Apache run?
[Tue Mar 28 10:35:35 2017] [notice] Apache/2.2.15 (Unix) DAV/2
mod_jk/1.2.41 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips configured -- resuming
normal operations

Do you see anything odd with this config?



2017-04-17 23:16 GMT+02:00 Felipe Zimmerle <notifications@github.com>:

**Comment by angeloxx** [comment]
I confirm: if access log refers to a ModSec variable (ie. %{PERF_COMBINED}M) and the Engine is off for a specific vhost, Apache segfault for every request.
