### ISSUE TITLE
No way to provide path for modsec-shared-collections and modsec-shared-collections.lock files

### ISSUE THREAD

**Issue by ashumal** [SpiderLabs/ModSecurity#1388]
I have latest nginx 1.12.0 compiled with modsecurity nginx connector.
Libmodsecurity is builded with LMDB support.
In case of Modsecuirty is switched On in nginx configuration I see modsec-shared-collections and modsec-shared-collections.lock files located in root folder /.
I have found no way to configure path for both files, so I have no choise and should remove LMDB from dependencies of Libmodsecuirty, just remove this package before the compilation of Libmodsecurity.

Please, advise possible fixes, how can I say to my web server move both files to specific location?

Thank you.

**Comment by zimmerle** [comment]
Hi @ashumal,

I would recommend the compilation of the libModSecurity without the LMDB support. You can achieve that using the parameter: ```--without-lmdb``` while running the configure script.
