### ISSUE TITLE
Paypal connectivity issue

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/ModSecurity#1390]
Hi,

   Im using third party braintree payment portal in my application and with modsecurity on, its not allowing me to add a paypal information. Logs are as below

---eP5OaC5S---D--

---eP5OaC5S---F--
Server: nginx/1.11.12
Date: Wed, 19 Apr 2017 05:54:06 GMT
Content-Length: 576
Content-Type: text/html
Connection: close

---eP5OaC5S---H--
ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/usr/local/nginx/conf/modsec.conf"] [line "50"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "XML parsing error: parse error: premature EOF\x0a"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [ref "v1127,1"]

---eP5OaC5S---I--

---eP5OaC5S---J--

---eP5OaC5S---Z--

Any ideas on how to resolve this ?
Im using latest modsecurity version over nginx 1.11.12

**Comment by zimmerle** [comment]
Related to #1392

**Comment by zimmerle** [comment]
Hi @vishaalgc,

I would expect the browser send an: ```{}``` as an empty JSON, not an empty request as I saw on #1392. 

Is that ModSecurity version 2 or version 3? Do you mind to share the "C" section of the auditlog? I want to know what do you have in your request body.

**Comment by vishaalgc** [comment]
Hi @zimmerle 

 This is the total log.

---Mig5P5Ep---A--
[26/Apr/2017:06:04:42 -0400] 14932010821.000000 125.19.76.66 46836 125.19.76.66 443
---Mig5P5Ep---B--
POST /Payment/Billing/ChangeToPaypal HTTP/1.1
Accept-Encoding: gzip, deflate, br
Cookie: __RequestVerificationToken=DQf-8Pk8JQNP3UOi-DxXWkZyBgKA5KNLKj9oejQrQqer5c-XAsBwOr_9HEctVbLh5rQXY2YvRocIkBtf8XWHvuMCrchtMxJanQyurFzznRw1; ASP.NET_SessionId=ejivq2woyo0k2gfrbx3aiibh; .AspNet.ApplicationCookie=0ZlAV2I1nzLjiAqFSmpUKrgAo7GzJVEUDAExmjxKRT8Z_eLsPqQC0hD_LrLl28WjjwRp6_lqH0ssXLIrD1VymWeomUprUEnYLjuAjKMb9wdh2-03kkTgKaDURyYIG_GYtN1MFqv-XeK7LFbzjZ5y8L_dadckgWcReUa4QIOko41upXXlMr4NcmyNT9ui-ODPeXs-sFYGKhxvzEyezMNHCtRayyWAKcWclxCmHKGhi8x1yqF1_4WmmDbzw3TUlTz1x3LvDLAIcSn8WnohRrMoOq3nq9gT6Qj-5X_wV6s_0gGy-5Muq0Q8xL5SrwiWb_JH_YAlLTJ2bA2m846VJ_X8u9u1pnqcQfxP3f-hg5K2i4CQytQFC9-4yNOn7kKZAcJTEFSRgopNjVSFDA243hS21tDmMukBbLo4o-N6pN-R7qQ
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Content-Type: application/json; charset=utf-8
X-Requested-With: XMLHttpRequest
Referer: abcde.com/Payment/Billing/Subscription
Origin: abcde.com
Accept: */*
Content-Length: 0
Connection: keep-alive
Host: abcde.com
Accept-Language: en-US,en;q=0.8,hi;q=0.6

---Mig5P5Ep---D--

---Mig5P5Ep---F--
Server: nginx/1.11.12
Date: Wed, 26 Apr 2017 10:04:42 GMT
Content-Length: 576
Content-Type: text/html
Connection: close

---Mig5P5Ep---H--
ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/usr/local/nginx/conf/modsec.conf"] [line "50"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "XML parsing error: parse error: premature EOF\x0a"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [ref "v1189,1"]

---Mig5P5Ep---I--

---Mig5P5Ep---J--

---Mig5P5Ep---Z--

**Comment by victorhora** [comment]
This log helps a bit @vishaalgc but it seems like its missing the "C" section of the AuditLog with the full body data as mentioned by @zimmerle.

You should have something like this on your [modsecurity.conf](https://github.com/SpiderLabs/ModSecurity/blob/master/modsecurity.conf-recommended#L187) file:

[SecAuditLogParts](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLogParts) ABIJDEFHZ

Try changing this line to: SecAuditLogParts AB**C**IJDEFHZ

Restart ModSecurity, fire the request again and you should get the "C" section :)

**Comment by zimmerle** [comment]
I am closing this issue due to the lack of feedback.

I would guess that paypal library is using a a WebSockets or a empty string as an empty JSON, in both cases ModSecurity will be working as expected.
