### ISSUE TITLE
how to get libmodsecurity current status?

### ISSUE THREAD

**Issue by 7ym0n** [SpiderLabs/ModSecurity#1394]
I using libmodsecurity, multi fork(), how get current HTTP header or HTTP body process is done?

**Comment by zimmerle** [comment]
Hi @7ym0n,

Are you refering to the [multi.c](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/examples/multiprocess_c/multi.c) example?

In the example itself it is calling the all the necessary functions. Check here:
https://github.com/SpiderLabs/ModSecurity/blob/v3/master/examples/multiprocess_c/multi.c#L73-L79
