### ISSUE TITLE
modsecurity 2.9.1 issue on RHEL7.3

### ISSUE THREAD

**Issue by rahims99** [SpiderLabs/ModSecurity#1397]
/mod_security2.so into server: /local/apache22/33/modules/mod_security2.so: undefined symbol: ap_unixd_set_global_mutex_perms

modsecurity: 2.9.1
RHEL 7.3
Apache HTTP 2.2.32

Above same version of modsecurity works fine with Apache HTTP 2.4.25 and RHEL 7.3

**Comment by zimmerle** [comment]
Hi @rahims99,

Most likely you have in your environment different versions for apr/apache. During the compilation the old source is being used, and you are trying to run ModSecurity with the newest version. Please double check if that happens in a clean system.
