### ISSUE TITLE
Installing under IIS 10 fails

### ISSUE THREAD

**Issue by Mikasa77** [SpiderLabs/ModSecurity#1405]
Few others seem to have the same issue but no resolution, if that's not the case apologies for raising a new one.

**Version:** ModSecurityIIS_2.9.1-64b.msi
**Platform:** Windows Server 2016 1607 (OS Build 14393.1066)

**Error:** There is a problem with this Windows Installer package.

Install tested on 2 servers, same results. Redists installed for 2010 and 2013 VS.
Install runs, console pops up when 32bit components are selected and fails.
Install runs, no console when all components are selected and fails.
Installs fine if i don't select the auto configure options.

Log output from installer: https://gist.github.com/Mikasa77/1511e93135c1058010ae4a8679baf460

**Comment by victorhora** [comment]
Hey @Mikasa77 

I got a fresh install of Windows Server 2016 ([14393.rs1_release.161220-1747](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2016/?i=1)) and on my setup the installer is running fine.

I tried reproducing using the following methods:

* Install using all default options
* Install using all default options but deselecting the 32 bit module installation
* Install using all default options but deselecting the 64 bit module installation
* A combination of the previous methods and deselecting the automatic configuration

All of them resulted in a successful installation by looking the msi installer output, Event viewer logs  and also testing some payloads being successfully blocked by ModSecurity (403).

All that said I believe it's safe to say that the current installer should work and support IIS 10 under Windows Server 2016. But it could be related with the fact that I have a fresh install and there could be some peculiarity with your setup.

From your logs, I'm guessing that the installer is really failing specifically during the [module installation / setup step](https://gist.github.com/Mikasa77/1511e93135c1058010ae4a8679baf460#file-log-txt-L2262-L2268).

If you haven't yet, I think it wouldn't hurt checking if your user have sufficient permissions to run the installer. If unsure maybe try executing with elevated permissions or a more privileged user just to try isolating the possibility of being a privilege issue.

You could also try checking the steps on the [IIS Troubleshooting page](https://github.com/SpiderLabs/ModSecurity/wiki/IIS-Troubleshooting) and running the actual command that appears to be failing and getting a verbose output like the following:

`"C:\Windows\system32\inetsrv\appcmd.exe" install module /name:"ModSecurity IIS (32bits)" /image:"%SystemRoot%\SysWOW64\inetsrv\ModSecurityIIS.dll" /preCondition:"bitness32" /debug`

If all is good the output of appcmd.exe should be something like this:

`INFO ( name:ModSecurity IIS (32bits), image:C:\Windows\SysWOW64\inetsrv\ModSecurityIIS.dll, preCondition:bitness32, timetaken:31, hresult:00000000, objects:2 )`
`GLOBAL MODULE object "ModSecurity IIS (32bits)" added`
`MODULE object "ModSecurity IIS (32bits)" added`

Let us know the results of your tests :)

**Comment by victorhora** [comment]
Closing this one. If there's any issue feel free to add a comment and / or reopen the issue. Thanks.
