### ISSUE TITLE
OEL 6 compile error

### ISSUE THREAD

**Issue by joshgibs** [SpiderLabs/ModSecurity#1408]
I get the following compile error:

mod_security2.c: In function ‘hook_connection_early’:
mod_security2.c:1455: error: ‘sb_handle’ undeclared (first use in this function)
mod_security2.c:1455: error: (Each undeclared identifier is reported only once
mod_security2.c:1455: error: for each function it appears in.)
mod_security2.c:1455: error: ‘sbh’ undeclared (first use in this function)
mod_security2.c:1487: error: ‘APLOG_TRACE3’ undeclared (first use in this function)
make[2]: *** [mod_security2_la-mod_security2.lo] Error 1
make[2]: Leaving directory `/home/nginx/spiderlabs/ModSecurity/apache2'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/nginx/spiderlabs/ModSecurity/apache2'
make: *** [all-recursive] Error 1

**Comment by victorhora** [comment]
This is related with the merge of #1340. The patch should be working good with Apache 2.4 but its breaking on Apache 2.2.

There's already a fix on the way as pointed out at #1407 and I'm going to close the one so we can handle related problems on #1407. Feel free to add your comments there and keep following it for an update.
