### ISSUE TITLE
not block

### ISSUE THREAD

**Issue by JoyChou93** [SpiderLabs/ModSecurity#1416]
when I curl this
```
?xx=%3Cscript%3Ealert(1)%3C/script%3E
```
I can see xss detect in log/error.log
But the response code is 200,not 403.

**Comment by JoyChou93** [comment]
Soved
Rule set deny

**Comment by victorhora** [comment]
@JoyChou93  other then setting your disruptive action directly on the rule you can also set a default action for your rules using the [SecDefaultAction](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDefaultAction) directive.

Just keep in mind that this directive will probably impact on the way that ModSecurity handles your rules and might change your [security model behaviour ](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Attack_Prevention_and_Virtual_Patching). 

You may also want to take a look at OWASP CRS anomaly scoring modes to better understand these models: https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/crs-setup.conf.example#L88-L126
