### ISSUE TITLE
nginx 1.12.0 use mod_security error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1420]
latest,I used nginx  it's version  1.12.0 stable and the most newer modsecurity  the nginx error log show "[alert] 115742#115742: worker process 117998 exited on signal 11"   the dmesg is "nginx[128070]: segfault at d8 ip 00000000004962ee sp 00007fffaa4f24d0 error 4 in nginx[400000+3f8000]
nginx[128071]: segfault at d8 ip 00000000004962ee sp 00007fffaa4f24d0 error 4 in nginx[400000+3f8000]
nginx[127906]: segfault at d8 ip 00000000004962ee sp 00007fffaa4f24d0 error 4 in nginx[400000+3f8000]
nginx[128072]: segfault at d8 ip 00000000004962ee sp 00007fffaa4f24d0 error 4 in nginx[400000+3f8000]
nginx[128073]: segfault at d8 ip 00000000004962ee sp 00007fffaa4f24d0 error 4 in nginx[400000+3f8000]
nginx[128074]: segfault at d8 ip 00000000004962ee sp 00007fffaa4f24d0 error 4 in nginx[400000+3f8000]"
the error number is four  so it is means during the read operation to nginx user mode application access address is invalid .when we add proxy_force_ranges on  in nginx.conf ,the nginx is working,so I want to know your mod_security  have a bug?

Why add proxy_force_range  command can resolved this bug?

![bug](https://cloud.githubusercontent.com/assets/17851645/26147345/dee868fe-3b25-11e7-943f-9a20fe026cc4.png)
![bug2](https://cloud.githubusercontent.com/assets/17851645/26147346/dee97b0e-3b25-11e7-958c-ad24e3b3494b.png)

**Comment by JarRoDk** [comment]
I had this same issue https://github.com/SpiderLabs/ModSecurity/issues/1419#issuecomment-301817005
i think you must use ModSecurity-nginx

Now i fighting with lose functionality: 
`nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsecurity_status.conf. Line: 209. Column: 23. Invalid input:  SecContentInjection On in `

**Comment by zimmerle** [comment]
Hi @JarRoDk, 

Indeed. Content injection is no longer supported.

**Comment by zimmerle** [comment]
Hi @Hello-Linux,

@JarRoDk pointed you in the right direction ;) ModSecurity-nginx connector is what you are looking for. Available here: https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by Hello-Linux** [comment]
@JarRoDk  @zimmerle   I have to use  ModSecurity-nginx? but I use ModSecurity is normal when  i add the "proxy_force_ranges on" in the nginx.conf  and I want to know  What is the difference between the two versions? I think most people use Modsecurity  in production!

**Comment by Hello-Linux** [comment]
@JarRoDk when I make the Modsecurity-nginx is show some error "checking for ModSecurity library in "/usr/local/modsecurity/include" and "/usr/local/modsecurity/lib" (specified by the MODSECURITY_LIB and MODSECURITY_INC env) ... not found
./configure: error: ngx_http_modsecurity_module requires the ModSecurity library and MODSECURITY_LIB is defined as "/usr/local/modsecurity/include" and MODSECURITY_INC (path for modsecurity.h) "/usr/local/modsecurity/lib", but we cannot find ModSecurity there."

**Comment by Hello-Linux** [comment]
@zimmerle  how to instlal libmodsecurity  Please tell us a detailed process

**Comment by JarRoDk** [comment]
@Hello-Linux please look here https://github.com/SpiderLabs/ModSecurity/issues/1419#issuecomment-302313648
