### ISSUE TITLE
Missing macro expansion

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/ModSecurity#1421]
Many ModSecurity operators do not do macro expansion. This means, variables such as %{TX.test} will not be expanded. Ideally all operators would support this (where it makes sense). But right now, there is especially a need for macro expansion on the `@contains` operator.

https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/699 demands this AFAICS.

**Comment by p0pr0ck5** [comment]
Thoughts on making such expansion configurable on a per-operator basis? The string manipulation required for expansions can get expensive, and when it's not necessary, I'd imagine the cost of doing such a lookup on for every single operator invocation would be nontrivial.

**Comment by zimmerle** [comment]
@p0pr0ck5 in v3 the macro expansion is sorted in the parser. The resolution happens in real time as a give nrule may change the value of a variable. There is no plan to perform any optimization in v2.

**Comment by dune73** [comment]
Agree on skipping optimizations in v2. `@contains` is rarely used though; I think we could live with the performance overhead.

**Comment by victorhora** [comment]
Hey @dune73 I was looking at this issue and the [docs](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#contains) and I'm wondering if I'm not entirely understanding what's missing. I've used the following rules to test:
```
SecRule ARGS "@unconditionalMatch" "phase:1,log,pass,setvar:TX.test=EXPANDMYMACRO,id:1,logdata:'TX.test:%{TX.test}'"
SecRule ARGS "@contains %{TX.test}" "phase:1,id:2,log,deny,logdata:'Matched Data: %{MATCHED_VAR_NAME}: %{MATCHED_VAR}. TX.test:%{TX.test}'"
```

For libModSecurity It looks like macro expansion for @contains is performed here: https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/operators/contains.cc#L27
And this is what I get in the logs when using the rules above:

```
---Q1k0Uoq7---H--
ModSecurity: Warning. Matched "Operator `UnconditionalMatch' with parameter `' against variable `ARGS:a' (Value: `EXPANDMYMACRO' ) [file "/usr/local/nginx/conf/modsecurity.conf"] [line "211"] [id "1"] [rev ""] [msg ""] [data "TX.test:EXPANDMYMACRO"] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref "v13,15"]
ModSecurity: Warning. Matched "Operator `Contains' with parameter `%{TX.test}' against variable `ARGS:a' (Value: `EXPANDMYMACRO' ) [file "/usr/local/nginx/conf/modsecurity.conf"] [line "341"] [id "2"] [rev ""] [msg ""] [data "Matched Data: ARGS:a: EXPANDMYMACRO. TX.test:EXPANDMYMACRO"] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref "o0,15v13,15"]
```

For 2.9.x it looks like the macro expansion is performed here: https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/re_operators.c#L2069
And this is what I get in the logs when using the rules above:

```
Message: Warning. Unconditional match in SecAction. [file "/etc/modsecurity/modsecurity.conf"] [line "426"] [id "1"] [data "TX.test:EXPANDMYMACRO"]
Message: Access denied with code 403 (phase 1). String match "EXPANDMYMACRO" at ARGS:a. [file "/etc/modsecurity/modsecurity.conf"] [line "427"] [id "2"] [data "Matched Data: ARGS:a: EXPANDMYMACRO. TX.test:EXPANDMYMACRO"]
```

Can you check on your side or tell me if I'm missing something?

**Comment by dune73** [comment]
Confirm. There is macro expansion on contains.

```
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][5] Rule 55ad95838b08: SecRule "ARGS:b" "@contains %{TX.a}" "phase:2,id:1008,pass,log,msg:'XXX6: %{MATCHED_VAR}'"
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][4] Transformation completed in 0 usec.
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][4] Executing operator "contains" with param "%{TX.a}" against ARGS:b.
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][9] Target value: "12345 abcdef 123"
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][9] Resolved macro %{TX.a} to: abcdef
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][4] Operator completed in 4 usec.
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][9] Resolved macro %{MATCHED_VAR} to: 12345 abcdef 123
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][2] Warning. String match "abcdef" at ARGS:b. [file "/apache/conf/httpd.conf_pod_2017-06-03_05:33"] [line "137"] [id "1008"] [msg "XXX6: 12345 abcdef 123"]
[03/Jun/2017:05:37:19 +0200] [localhost/sid#55ad9582e1f0][rid#7f4fbc04ac30][/][4] Rule returned 1.
```

Sorry for the bogus report. I thought I had checked this, but it was a month ago or so and I must have made a mistake.

**Comment by dune73** [comment]
I think I got the reason. I used to do macro expansion on `ARGS:a` when it should be `ARGS.a`.

**Comment by csanders-git** [comment]
We should add a supports macro expansion to the documentation.

**Comment by victorhora** [comment]
No worries @dune73, thanks for checking. Looks like all of us thought this was a missing feature until digging it deeper. We're glad it's one less thing to worry about for the next release :)

Good idea @csanders-git. I'll add some that I double checked yesterday to the docs, please add the ones you know too.
