### ISSUE TITLE
Install Mod_security-nginx error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1422]
when I make the Modsecurity-nginx is show some error "configure.ac:40: error: possibly undefined macro: AM_PROG_AR
configure:20298: error: possibly undefined macro: AM_DEFAULT_VERBOSITY
" ??? why?

![error](https://cloud.githubusercontent.com/assets/17851645/26191908/529e3726-3be2-11e7-82be-c446eb403ad2.png)

I have to use ModSecurity-nginx? but I use ModSecurity is normal when i add the "proxy_force_ranges on" in the nginx.conf and I want to know What is the difference between the two versions? I think most people use Modsecurity in production but no ModSecurity-nginx

**Comment by zimmerle** [comment]
Hi @Hello-Linux,

The differences are explained here: https://www.trustwave.com/Resources/SpiderLabs-Blog/An-Overview-of-the-Upcoming-libModSecurity/

Apart from that ``build.sh`` error did you managed to have ModSecurity compiled?

**Comment by Hello-Linux** [comment]
@zimmerle   yes

**Comment by Hello-Linux** [comment]
@zimmerle   I don't quite understand what you ask

**Comment by zimmerle** [comment]
That error does not means that ModSecurity won't work. I am asking to continue the compilation process in order to identify if that particular error is causing you any trouble or not.
