### ISSUE TITLE
Install mod_security-nginx error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1423]
when I first install  the libmodsecurity but   show some error in centos 6.8 
![error](https://cloud.githubusercontent.com/assets/17851645/26209255/e12bb068-3c1e-11e7-9fee-30f1bd40e0ce.png)

**Comment by zimmerle** [comment]
Hi @Hello-Linux,

Please make sure that you have **autotools** and **automake** installed in your system.
