### ISSUE TITLE
install modsecurity-nginx error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1424]
My environment is centos 6.8 and  I already installed the libmodsecurity but when I install nginx it show "checking for ModSecurity library ... not found
checking for ModSecurity library in /usr/local/modsecurity ... not found" why?

![error1](https://cloud.githubusercontent.com/assets/17851645/26243990/83dca622-3cc0-11e7-9dd3-2ef7af52c2cf.png)
![error2](https://cloud.githubusercontent.com/assets/17851645/26243991/83f3f336-3cc0-11e7-833d-d5e819ed680e.png)
![error3](https://cloud.githubusercontent.com/assets/17851645/26243992/840bd8fc-3cc0-11e7-9205-a0869f688804.png)

**Comment by zimmerle** [comment]
Please, check if you have files under: **/usr/local/modsecurity**

**Comment by Hello-Linux** [comment]
@zimmerle  secondly, the /usr/local/modsecurity is already exist,why is not found???

**Comment by Hello-Linux** [comment]
![error4](https://cloud.githubusercontent.com/assets/17851645/26244257/92bfcc40-3cc1-11e7-9725-a257066ddd81.png)

**Comment by zimmerle** [comment]
Make sure you have **LD_LIBRARY_PATH** pointing to **/usr/local/modsecurity/lib**.

**Comment by Hello-Linux** [comment]
@zimmerle   I  try run the export MODSECURITY_INC=/usr/local/modsecurity/lib
         export MODSECURITY_LIB=/usr/local/modsecurity/include  but  it is invalid

**Comment by Hello-Linux** [comment]
@zimmerle  I can give you a advice?You personally use centos install modsecurity - nginx?I doubt you now the waf - nginx is not suitable for centos version
