### ISSUE TITLE
Install libmodsecurity error in centos6.5 and centos7

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1426]
@victorhora      I according to you give steps for centos6.5,but  the error libmodsecurity is still exist "show lib-modsecurity  not found"
and the curl I use 7.19.7  and when  Irun "git checkout -b v3/master origin/v3/master" is error and run "git checkout -b experimental origin/experimental" also error  the build.sh  is not exists

and I install centos 7 minimal and use centos 7 install method is also error "the libmodsecurity is not found"

I now suspect you give installation method is wrong
![error1](https://cloud.githubusercontent.com/assets/17851645/26272764/731532bc-3d53-11e7-9b5f-f7350e1cd207.png)
![error2](https://cloud.githubusercontent.com/assets/17851645/26272765/737e9f36-3d53-11e7-85cb-9f0495e8eba2.png)
![error3](https://cloud.githubusercontent.com/assets/17851645/26272766/74ef41b8-3d53-11e7-9711-83adce47bfed.png)

**Comment by victorhora** [comment]
@Hello-Linux,

If you have further questions or issues with your libModSecurity installation on CentOS, please don't create new issues for the same subject. Add them to one of the other threads with the same subject: #1425

**Comment by Hello-Linux** [comment]
@victorhora   today I install libmodsecurity  on centos7,but  I have some issues about configuration.
 If I use modsecurity-nginx so I don't use the modsecurity.conf and crs-setup.conf and unicode.mapping file ??????   and If I have mang rules file, I must be a one to add this command about modsecurity_rules_file??
