### ISSUE TITLE
Install libmodsecurity on centos6.5  for Nginx error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1428]
@csanders-git @victorhora When I according to "libModSecurity: https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes" about centos 6.5 and I already install libmodsecurity successful . ItBelow is the error screenshot
![erroe2](https://cloud.githubusercontent.com/assets/17851645/26385296/1ee292f4-4071-11e7-9b13-c898428da6bc.png)
![err1](https://cloud.githubusercontent.com/assets/17851645/26385356/9bf88884-4071-11e7-944f-2879873e3e1f.png)
![err4](https://cloud.githubusercontent.com/assets/17851645/26385357/9bfaf754-4071-11e7-9650-b2b7dec92923.png)

**Comment by victorhora** [comment]
@Hello-Linux please try not to create new issues for the same subject. Add your comments, issues to the issues you already created related to the same subject like #1425. 

Thank you.
