### ISSUE TITLE
Nginx_modsecurity 2.7.5 causes system to swap

### ISSUE THREAD

**Issue by toastedpenguin** [SpiderLabs/ModSecurity#143]
Trying to use 2.7.5 with nginx 1.4.1 on CentOS 6.4 and i am using the recommended modecurity.conf that was part of the source files.

nginx is setup as a reverse caching proxy to tomcat 7.0.42 and it is setup for SSL using openssl 1.0.1e.

When modsecurity is enabled and a request for the site nginx is the proxy for is made, everything is ok, but when using a form submission such as the site's sign in page and either an incorrect or correct login is submitted the system nginx/modsecurity is running on immediately starts to swap and the CPU load increases.  The site never responds to the request and eventually times out.

Setting SecResponseBodyAccess to Off eliminates the issue.

**Comment by zimmerle** [comment]
Won't fix in 2.x. Fixed in libmodsecurity

Further information available here - https://github.com/SpiderLabs/ModSecurity-nginx
