### ISSUE TITLE
Use Owasp-modsecurity-core-rule for 403

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1430]
@client9  @hideaki  @ishworgurung  @athmane  @bostrt  When I send a normal post request to our web server like '/index.php?act=store_goods_online&op=edit_save_goods&inajax=1'   Then Trigger the rule "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf  The  rule ID  is 942100"  and I want to know How to trigger and how To solve this 403??

The log show --------------------------------------------------------------------------------
{
    "transaction": {
        "client_ip": "192.168.1.215",
        "time_stamp": "Thu May 25 17:17:20 2017",
        "server_id": "5090f3178ec7a095c7d58ac45b871aba12519e81",
        "client_port": 52573,
        "host_ip": "192.168.1.215",
        "host_port": 443,
        "id": "14957038401.000000",
        "request": {
            "method": "POST",
            "http_version": 2.0,
            "uri": "/index.php?act=store_goods_online&op=edit_save_goods&inajax=1",
            "headers": {
                "host": "www.linuxidc.com",
                "user-agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0",
                "cookie": "lc_invitation_opened=opened; lc_window_state=minimized; PHPSESSID=mutefmcledd1piphivngp0eno4; 67_CA_storemsgnewnum1=8590; _ga=GA1.2.1151987944.1495703782; _gid=GA1.2.277400621.1495703793; _gat=1; _ym_uid=1495703782776776336; _ym_isad=2; __lc.visitor_id.6797601=S1495703789.6abcad6466; _ym_visorc_40742754=w; 67_CA_msgnewnum1=0; 67_CA_cart_goods_num=0; 67_CA_nation_id=2",
                "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                "accept-language": "zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3",
                "content-length": "12661",
                "accept-encoding": "gzip, deflate, br",
                "content-type": "application/x-www-form-urlencoded",
                "referer": "https://www.linuxidc.com/index.php?act=store_goods_online&op=edit_goods&commonid=143566",
                "upgrade-insecure-requests": "1"
            }
        },
"response": {
            "http_code": 403,
            "headers": {
                "Server": "nginx",
                "Date": "Thu, 25 May 2017 05:42:03 GMT",
                "Content-Length": "162",
                "Content-Type": "text/html",
                "Connection": "close"
            }
        },
        "producer": {
            "modsecurity": "ModSecurity v3.0.0-alpha (Linux)",
            "connector": "ModSecurity-nginx v0.1.1-beta",
            "secrules_engine": "Enabled",
            "components": [
                "OWASP_CRS/3.0.2\""
            ]
        },
        "messages": [
            {
                "message": "SQL Injection Attack Detected via libinjection",
                "details": {
                    "match": "detected SQLi using libinjection.",
                    "reference": "v12638,16t:utf8toUnicode,t:urlDecodeUni,t:removeNulls,t:removeComments",
                    "ruleId": "942100",
                    "file": "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf",
                    "lineNumber": "17",
                    "data": "Matched Data: host user-agent accept accept-language accept-encoding content-type content-length referer upgrade-insecure-requests cookie found within ARGS:custom[46][name]: Материал",
                    "severity": "2",
                    "ver": "OWASP_CRS/3.0.0",
                    "rev": "1"

And I want to know This variable about @detectsqli  operator, based on libinjection and I have to install libinjection on my webserver？？ I want to know why this @detectsqli Returns true for  SQL injection payload  so it uses LibInjection to detect SQLi attacks!!!  I think our post request is normal,and  why the @detectsqli rerurn true????       I am very confused about this phenomenon

**Comment by Hello-Linux** [comment]
And I want to know This variable about @detectSQLi  represents what??

**Comment by victorhora** [comment]
@Hello-Linux 

This question is more specific to the OWASP Core Ruleset.

It could be a false positive with your rules. I didn't looked deeply at your logdata, but check the parameters from your POST request. Maybe this one is the culprit: custom[46][name]: Материал

You can find information about the @detectSQLi operator on the [Reference Manual](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#detectSQLi). You can also see how it is implemented [here](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/operators/detect_sqli.cc). 

You don't need to install libInjection on your server. libInjection is linked automagically with your libModSecurity code prior to compile when you do the "git submodule" steps of your installation.

Now that you have ModSecurity running have a look at [some nice CRS tutorials](https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/) and ModSecurity [reference documentation and books](https://modsecurity.org/documentation.html).

If you have further issues and questions with OWASP Core Rules, please direct them either the [mail list](https://lists.owasp.org/mailman/listinfo/owasp-modsecurity-core-rule-set) or [OWASP CRS Github](https://github.com/SpiderLabs/owasp-modsecurity-crs)

**Comment by Hello-Linux** [comment]
Thank you!!!
