### ISSUE TITLE
modsecurity-nginx make CPU load very high in centos6.5

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1431]
When I was in the test environment to use modsecurity - nginx appeared in the process of high CPU load
and I stop the modsecurity the cpu is low

![qq 20170526085735](https://cloud.githubusercontent.com/assets/17851645/26476855/161a7144-41f4-11e7-8dd6-6ef2a93dbac7.png)
![qq 20170526085828](https://cloud.githubusercontent.com/assets/17851645/26476854/1619f44e-41f4-11e7-8515-535fa4d4db96.png)

**Comment by zimmerle** [comment]
That is the expected behavior. Do you expect something different?
