### ISSUE TITLE
ModSecurity for NGINX - problem switching to experimental branch

### ISSUE THREAD

**Issue by MPLLC** [SpiderLabs/ModSecurity#1437]
The various compilation recipes have the following command towards the end:

`$ git checkout -b experimental origin/experimental`

However, when I attempt that, I get the following fatal error:

    fatal: Cannot update paths and switch to branch 'experimental' at the same time.
    Did you intend to checkout 'origin/experimental' which can not be resolved as commit?

Looking at both the ModSecurity repo and the NGINX wrapper repo, I don't see an experimental branch listed.  Should I just ignore that step now that I've cloned the wrapper into a local directory?

**Comment by victorhora** [comment]
Hi @MPLLC 

Yes that git command is incorrect. ModSecurity-nginx repository doesn't an experimental branch anymore and that's why you're getting that error. You should be ok if simply skip the checkout step entirely.

I'll update the documentation accordingly.

**Comment by victorhora** [comment]
Docs fixed as of [#ad9f567](https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes/ad9f56792da96d85a9e23c42123eae4507cefe7f)

Closing this one. If you find further issues feel free to add a comment here and we reopen it if necessary.
