### ISSUE TITLE
missing SecWebAppId in libmodsecurity

### ISSUE THREAD

**Issue by asdfuken** [SpiderLabs/ModSecurity#1442]
Hello, I'm getting " Invalid input:  SecWebAppId 1"
If it was removed, is there a future replacement ? it's a very useful function.
`SecWebAppId 1`
Using Modsecurity Nginx Connector and modsecurity V3 master

`nginx version: nginx/1.13.1
built by gcc 4.9.2 (Debian 4.9.2-10) 
built with OpenSSL 1.0.1t  3 May 2016
TLS SNI support enabled
configure arguments: --prefix=/opt/private/src/nginx/ --sbin-path=/opt/private/bin/nginx --pid-path=/opt/public/run/nginx.pid --error-log-path=/opt/public/logs/nginx_error.log --http-log-path=/opt/public/logs/nginx_access.log --add-module=/opt/private/src/ModSecurity-nginx/ --with-http_gzip_static_module --with-http_stub_status_module --with-http_ssl_module --with-http_gunzip_module --with-http_sub_module --add-module=../ngx_devel_kit/ --add-module=../lua-nginx-module/ --add-module=../encrypted-session-nginx-module/ --add-module=../set-misc-nginx-module/ --add-module=../srcache-nginx-module/`

And a final question, is modsecurity v3 considered stable?

Thank you

**Comment by zimmerle** [comment]
Hi @asdfuken,

Indeed. SecWebAddId is not yet ready in libModSecurity. Adding in our todo list.

**Comment by zimmerle** [comment]
Implemented as part of 082a3e328759c0824479c34e1dc0e234686156bb
