### ISSUE TITLE
DetectOnly for one vhost

### ISSUE THREAD

**Issue by fernal9301** [SpiderLabs/ModSecurity#1444]
Hello, guys! Could you please tell me how to make DetectOnly for specific rule to  one virtual host  in apache. I can't find any in documentation. The problem is I don't want to use  SecRuleRemoveById because I want to log possible attacks. If I just use it I don't see any logs.

**Comment by bostrt** [comment]
@fernal9301 Do you mean DectectionOnly mode like mentioned here? https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secruleengine I'm not sure if you can turn on DetectionOnly for a specific rule but you write your rule in such a way that it is not disruptive (i.e. don't use block, deny, drop, proxy, redirect, allow) but still log out when the rule matches using https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#log

**Comment by fernal9301** [comment]
I clarify. I've got a redmine, and cant upload any files to tasks. When I review logs I saw couple rules worked  f.ex id:920420, id:xxxxxx, id:xxxxxx. 
What I need. I need to disable particular rule 920420  for one Virtualhost but log it, and continue process request by other rules. I made a custom conf file -> and include it in virtualhost config 


```
<VirtualHost *:443>
...
        Include /opt/modsecurity/etc/testdomain.ru/RuleSetTest.conf
...
</VirtualHost>

```


Content of RuleSetTest.conf

```

SecRuleUpdateActionById 920420 "chain,log,pass,status:200"


``` 

I tried to update action, so it can pass through rule with id:920420 and go further but it doesn't work this way. 


original 920420: 


```
#
# Restrict which content-types we accept.
#
SecRule REQUEST_METHOD "!^(?:GET|HEAD|PROPFIND|OPTIONS)$" \
  "phase:request,\
   chain,\
   t:none,\
   block,\
   msg:'Request content type is not allowed by policy',\
   rev:'2',\
   ver:'OWASP_CRS/3.0.0',\
   maturity:'9',\
   accuracy:'9',\
   id:920420,\
   severity:'CRITICAL',\
   logdata:'%{matched_var}',\
   tag:'application-multi',\
   tag:'language-multi',\
   tag:'platform-multi',\
   tag:'attack-protocol',\
   tag:'OWASP_CRS/POLICY/ENCODING_NOT_ALLOWED',\
   tag:'WASCTC/WASC-20',\
   tag:'OWASP_TOP_10/A1',\
   tag:'OWASP_AppSensor/EE2',\
   tag:'PCI/12.1'"
     SecRule REQUEST_HEADERS:Content-Type "^([^;\s]+)" \
       "chain,\
        capture"
          SecRule TX:0 "!^%{tx.allowed_request_content_type}$" \
            "t:none,\
             ctl:forceRequestBodyVariable=On,\
             setvar:'tx.msg=%{rule.msg}',\
             setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},\
             setvar:tx.%{rule.id}-OWASP_CRS/POLICY/CONTENT_TYPE_NOT_ALLOWED-%{matched_var_name}=%{matched_var}"

```

What works great is the ```SecRuleRemoveById 920420``` but no log  at all it's silently pass.

**Comment by void-in** [comment]
You can do this through SecRule or SecRuleRemoveById. For example:
```
SecRule SERVER_NAME "myredmine.com" "id:1,phase:1,pass,nolog,ctl:ruleRemoveTargetById=xxxxxxx"
```
One thing should be noted here that you have to include this rule BEFORE the xxxxxx rule it is removing.

**Comment by fernal9301** [comment]
If I understand you right , I need to do smth like that: 

Just add  in my custom .conf file 

``` 
SecRuleUpdateActionById 920420 "chain,log,pass,status:200"
SecRule SERVER_NAME "testdomain.ru" "id:1,phase:1,pass,nolog,ctl:ruleRemoveById=920420"
```

Right?

**Comment by fernal9301** [comment]
I did it this way 

config for Virtualhost 

```
<VirtualHost *:443>
...
        Include /opt/modsecurity/etc/testdomain.ru/RuleSetTest.conf
...
</VirtualHost>

```

Content of /opt/modsecurity/etc/testdomain.ru/RuleSetTest.conf

``` 
SecRule SERVER_NAME "testdomain.ru" 
  "id:920420,\
   phase:1,\
   pass,\
   log,\
   msg:'Request content type is not allowed by policy',\
   ctl:ruleRemoveById=920420"

```

So, just replace id:1 with  id or a rule ( so I can see in my logs rule_id ) and  nolog replace with log, and add msg - from original 920420 rule 

Log looks like this:

```

--36df9076-H--
Message: Warning. Pattern match "testdomain.ru" at SERVER_NAME. [file "/opt/modsecurity/etc/testdomain.ru/RuleSetTest.conf"] [line "1"] [id "920420"] [msg "Request content type is not allowed by policy"]
Apache-Handler: proxy-server
Stopwatch: 1496905133458764 54418 (- - -)
Stopwatch2: 1496905133458764 54418; combined=3204, p1=257, p2=2628, p3=88, p4=153, p5=78, sr=24, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/); OWASP_CRS/3.0.0.
Server: Apache/2.4.10 (Debian)
Engine-Mode: "ENABLED"

--36df9076-Z--

```

Any comments, I did it right or not? 
Thanks  bostrt, void-id  for your help!

**Comment by fernal9301** [comment]
By the way I've got another question about the rule scope. If I just add rule in virtualhost config like that:

```

<VirtualHost *:443>
...
        Include /opt/modsecurity/etc/testdomain.ru/RuleSetTest.conf
...
</VirtualHost>

``` 
Then if I don't write ``` SERVER_NAME "testdomain.ru"  ```  for match, but add other info. What will be result impact?  All clients (Virtualhosts) will impact this rule or only Virtualhost where I include this rule.

**Comment by fernal9301** [comment]
The Issue stays the same. Previous solution doesn't work as I want. I don't want remove rule by id 

My question is how to change action in one rule for particular domain(vhost)? Is it possible to match 
not by SERVERNAME, f.ex. but by rule id?

**Comment by zimmerle** [comment]
Hi @fernal9301,

Some configurations are global, some not. Ideally you need to put the rules for an specific vhost within its configuration. The configuration merge process will put the configuration on its compartments, make it valid for the vhost only.
