### ISSUE TITLE
modsecurity 3 components link to libmodsecurity is broken

### ISSUE THREAD

**Issue by efx** [SpiderLabs/ModSecurity#1445]
Under the ModSecurity 3 header, I think the libModSecurity should link to https://github.com/SpiderLabs/ModSecurity/tree/v3/master ?

**Comment by victorhora** [comment]
Hi @efx 

I'm not sure if I get you. You mean the link on the README file?

**Comment by efx** [comment]
hi @victorhora , sorry meant the wiki header: https://github.com/SpiderLabs/ModSecurity/wiki#modsecurity-3

**Comment by victorhora** [comment]
Got it! I just fixed and you can see in the [history](https://github.com/SpiderLabs/ModSecurity/wiki/Home/_history).

Thanks for spotting this!
