### ISSUE TITLE
Design error: sanitiseArg and friends have limited use

### ISSUE THREAD

**Issue by drwetter** [SpiderLabs/ModSecurity#1447]
Hi *,

forgive my provoking approach but what is the point of those parameters to prevent logging of sensible parameters if they are doing their job only by 50%  -- i.e. sanitizing the audit_log and not the error_log?

Normally I would expect that those parameters do both or there's another set of parameters for the error_log.

In the current environment we centrally collect Apache (access and error logs) from numerous web servers. Under some circumstances third parties have access to thos logs. This is a huge security, privacy and compliance issue if e.g. other means like  ``SecRuleUpdateTargetById`` are not properly implemented (and this is error prone to implement).

Any chance that this will be addressed ?

Thx, Dirk

**Comment by void-in** [comment]
So we have implemented a setup like yours and always ship Apache error logs to the SIEM. However, we always configure custom log messages in the SecRule directives through the msg and logdata attributes.
```
SecRule SERVER_NAME "myserver.com" "id:1,chain,log,pass,sanitizeArgs:pass,msg:'Login',logdata:'USERNAME=%{tx.username}'"
 SecRule ARGS_POST:user "@rx (.+)" "t:none,setvar:tx.user=%{matched_var}"
```
This way, you are shipping only the relevant parts of your logs to the third party while the audit logs will sanitize the mentioned arguments.

Hope that would be helpful.

**Comment by victorhora** [comment]
@void-in solution should work well to sanitize potentially sensitive data.

In addition I think that choosing to just don't log to errorlog at all could work for you as well. If you look at the [sanitiseArg](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#sanitiseArg) example below based on the reference manual:
```
# Never log passwords 
SecAction "nolog,auditlog,phase:2,id:131,sanitiseArg:password,sanitiseArg:newPassword,sanitiseArg:oldPassword"
```

You will see that's exactly what's suggested by always appending the [nolog](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#nolog) action when using sanitize actions.

**Comment by drwetter** [comment]
Hi guys,

it seems to me somebody's missing the point here. 

**sanitiseArg is for audit-log only. I care about the error log too^Wmostly.**, 

So again my question: What's the point of ``sanitise*`` commands if it does only 50% of one would expect? (yes & thx, I know workarounds for the error log but that is not my point here).

See also #1132 .

Cheers, Dirk

**Comment by victorhora** [comment]
Well, I see your point @drwetter. So let's keep track of this feature on #1132 as it's tagged to be implemented on libModSecurity (aka v3).

In the meantime, it depends what you're logging and your LogLevel configuration (if using Apache). For instance, this is what it's logged by default when using [sanitizeMatched](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#sanitiseMatchedBytes) / [sanitizeMatched](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#sanitiseMatchedBytes) or [sanitizeArg](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#sanitiseArg) rules:

error_log:
 ```
ModSecurity: Warning. CC# match "\\d{13,16}" at ARGS:a. [offset "0"]
ModSecurity: Warning. Unconditional match in SecAction.
```

access_log:
```
192.168.37.1 - - [07/Jun/2017:00:33:49 -0400] "GET /test?a=1***********4004 HTTP/1.0" 404 462 "-" "-"
192.168.37.1 - - [07/Jun/2017:00:34:02 -0400] "POST /test HTTP/1.0" 404 457 "-" "-"
192.168.37.1 - - [07/Jun/2017:00:40:24 -0400] "GET /test?a=**************** HTTP/1.0" 404 462 "-" "-"
```

So I think you could get away with this for now as the error_log is not that verbose by default and the access_log will be sanitized correctly.
