### ISSUE TITLE
Website Access Via IP Address Allowed? - Mod Security 2.9.1

### ISSUE THREAD

**Issue by nikhilbhalwankar** [SpiderLabs/ModSecurity#1448]
Hi,

I have installed ModSecurity 2.9.1 with CRS 3.0 on CentOS 7 on which production website runs. For previous version, if I try to access website via IP address, I used to get **Host Header is Numeric IP Address** on logs. Alos web browser correctly used to give forbidden message.

However for Modsecurity 2.9.1, I am getting only warning and website access via IP is allowed. I tried from desktop, laptop and mobile all connected to different networks. **SecRuleEngine** is **On**

How can I confirm if ModSecurity is really working?

**Comment by void-in** [comment]
Send a message to the website such as http://1.1.1.1/page?a=/bin/bash

The CRS 3.0 is using a threshold value to determine if the request is malicious or not based upon how many rules gets matched. But the above request should trip the threshold in the default configuration and you should see an access forbidden error.

**Comment by victorhora** [comment]
Closing this one as @void-in recommendation should suffice.
