### ISSUE TITLE
When  update libinjection for modsecurity-nginx

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1449]
A few days ago I see the apache  updates libinjection to v3.10.0 and I want to know the  date for update nginx‘s  libinjection。。。。。  But I want to know what's good about that update libinjection
The old libInjection ....v2.9.0-815-g616a95b

**Comment by Hello-Linux** [comment]
@zimmerle  ？

**Comment by zimmerle** [comment]
Hi @Hello-Linux,

libInjection change log is available here: https://github.com/client9/libinjection/blob/master/CHANGELOG.md

libModSecurity will be upgraded soon.

**Comment by Hello-Linux** [comment]
@zimmerle  OK
