### ISSUE TITLE
How can I defence webshell denpend on  @fuzzyHash 

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1451]
This article  “https://www.trustwave.com/Resources/SpiderLabs-Blog/ModSecurity-Advanced-Topic-of-the-Week--Detecting-Malware-with-Fuzzy-Hashing/”   say use @fuzzyHash can defence webshell，Whether or not a detailed tutorial to give me？

now I use the fuzzHash  the nginx error 
![error777](https://user-images.githubusercontent.com/17851645/26962981-817722f6-4d1c-11e7-8637-a97de6ef3be5.png)

”

**Comment by victorhora** [comment]
Duplicate issue. Please refer to #1450.
