### ISSUE TITLE
No "space" between response length and referer in audit index log

### ISSUE THREAD

**Issue by Pjack** [SpiderLabs/ModSecurity#1452]
Hi,
In the audit.log, there is no space between response length and the referrer.
Like "4096-"  in the sample,  I expect it should be  "4096 -".

mysite.com 60.251.40.253 - - [24/May/2017:05:39:13 +0000] "GET /?cmd=/bin/sh HTTP/1.1" 403 4096- "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36" 14956043531.000000 - /var/log/modsec/20170524/20170524-0539/20170524-053913-14956043531.000000 0 4923.000000 md5:77693aae8f970b2be632583e171c9c51

I check the function toOldAuditLogFormatIndex, we may output space after "tellp()"
https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/transaction.cc#L1351

Thanks!

**Comment by zimmerle** [comment]
Hi @Pjack, Thanks for the bug report. It is now fixed - 4726912ec83c07d8482d9800dcea9b5c37c4540e
