### ISSUE TITLE
TX:MSC_PCRE_LIMITS_EXCEEDED

### ISSUE THREAD

**Issue by oleg9301** [SpiderLabs/ModSecurity#1455]
Hello Guys,

I have next env:

```
modsecurity-crs (3.0.0-3~bpo8+1) (debian  jessie-backports)
libapache2-mod-security2 (2.9.1-2~bpo8+1) (debian  jessie-backports)
protected site: redmine
```

When I'm trying to post some russian text I have next modsec_audit.log

```
Message: Rule 7fd6fc3ceea0 [id "942360"][file "/usr/share/modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"][line "451"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Access denied with code 403 (phase 2). Match of "streq 0" against "TX:MSC_PCRE_LIMITS_EXCEEDED" required. [file "/etc/modsecurity/modsecurity.conf"] [line "101"] [id "200005"] [msg "ModSecurity internal error flagged: TX:MSC_PCRE_LIMITS_EXCEEDED"]
Action: Intercepted (phase 2)
Apache-Handler: proxy-server
Stopwatch: 1497347533996070 38777 (- - -)
Stopwatch2: 1497347533996070 38777; combined=33008, p1=389, p2=32571, p3=0, p4=0, p5=48, sr=36, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/); OWASP_CRS/3.0.0.
Server: Apache/2.4.10 (Debian)
Engine-Mode: "ENABLED"
```
But I have next lines in modsecurity.conf
```
SecPcreMatchLimit 1000000
SecPcreMatchLimitRecursion 1000000
```
When I try to search this option in other files: "grep -R 'SecPcreMatchLimit' /" "grep -R 'SecPcreMatchLimitRecursion' /" I see only modsecurity.conf.
When I type SecPcreMatchLimit && SecPcreMatchLimitRecursion directly in REQUEST-942-APPLICATION-ATTACK-SQLI.conf this error disappear. But I want to configure this options in modsecurity.conf or in virtualhost configuration.

**Comment by victorhora** [comment]
This is weird @oleg9301. SecPcreMatchLimit* rules are normally to be set on modsecurity.conf. I'm having a hard time thinking on why this is only working when you set them on a configuration file inside CRS.

Can you make sure these directives are not accidentally commented out on your modsecurity.conf? And feel free to share your configuration files on a [Gist ](https://gist.github.com/) so we can try helping you more.

**Comment by oleg9301** [comment]
My modsecurity.conf
https://gist.github.com/oleg9301/9d55793276d0c20ed1f294313f573486

**Comment by oleg9301** [comment]
I changed order loading my conf files my /etc/apache2/mods-enabled/security2.conf and error disappear.

new file 

```
cat /etc/apache2/mods-enabled/security2.conf 
<IfModule security2_module>
        SecDataDir /var/cache/modsecurity
        Include /etc/modsecurity/modsecurity.conf
        Include /usr/share/modsecurity-crs/owasp-crs.load
</IfModule>
```
Why it works in this way?
