### ISSUE TITLE
Use operator   @beginWith  error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1458]
When  I send a request_uri is "/index.php?act=seller_center&op=statistics&rand=24954191" and my rule is "SecRule REQUEST_URI "@beginswith /index.php?act=store"
"id:1004,phase:1,pass,nolog,
ctl:ruleRemoveById=949110" but rule id 1004  that his uri is not match the "/index.php?act=seller_center&op=statistics&rand=24954191"，and I found the request I send has match the rule that his id is 1004  why？ The operator beginwith is not a exact match？

**Comment by void-in** [comment]
The rule is looking for act=store while the generate url is act=seller_center so why you think it would match?

**Comment by Hello-Linux** [comment]
@void-in  you can  see https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/806
