### ISSUE TITLE
v2.9.2 release date

### ISSUE THREAD

**Issue by davidjrh** [SpiderLabs/ModSecurity#1460]
Hi folks, 

I have tried to build the v2.9.2 by my own with no success (I'm trying to build the IIS module). Is there any release date for v2.9.2? 

Thanks, 
David Rodriguez

**Comment by bostrt** [comment]
@davidjrh there's no a v2.9.2 released yet. Did you build from the master branch? If so, what error message did you receive during the build process?

**Comment by davidjrh** [comment]
Hi @bostrt , at the end, with the some hardcore help from Cesar Abreu, we got the build working from the v2\master branch.

In any case, would be awesome to have an automated build process running, so we could get nightly builds, etc. I know this is resource consuming, but with a minimum of 1 build per week, I think there are free resources outhere that could be used. I don't have too much time, but if I can help on anything, let me know.

**Comment by bostrt** [comment]
@davidjrh Maybe there's something the ModSecurity maintainers can do with the current TravisCI integration. 

@zimmerle @victorhora will need to defer any further discussion to you.

**Comment by victorhora** [comment]
2.9.2 is being cooked and should be coming out soon. In the meantime I did an IIS test build last week but notice that indeed [the docs for building](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/iis/dependencies/howto.txt) the IIS version and the [batch scripts](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/iis/build_dependencies.bat) are outdated. I'll submit a pull request to get those updated asap.

**Comment by victorhora** [comment]
@davidjrh @bostrt There's a pull request which fixes some hardcoded stuff and allows some customization and downloads all the required dependencies etc. It should make the IIS build a breeze... 
It is currently pending proper review and test by the buildbots and @zimmerle, but my initial tests suggests that it's fine:

https://github.com/SpiderLabs/ModSecurity/pull/1479/commits/01a27cb3e44d11aecf957fe3a931ccdf994d4cd6

The howto.txt was also updated: https://github.com/victorhora/ModSecurity/blob/01a27cb3e44d11aecf957fe3a931ccdf994d4cd6/iis/dependencies/howto.txt

There might be some work left to be done regarding some reported issues with the MSI installer (i.e. uninstall) but this should be enough to get it going if you need a current build from master until 2.9.2 is all ready for release. Let me know if you find any issues.
