### ISSUE TITLE
Implement the support for "SecDisableBackendCompression" directive in libModSecurity

### ISSUE THREAD

**Issue by victorhora** [SpiderLabs/ModSecurity#1470]
The support for "SecDisableBackendCompression" is not yet implemented.

Further information about this directive available here:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDisableBackendCompression

**Comment by victorhora** [comment]
It was realized that this feature should not be implemented in libModSecurity core but rather on the connectors if due necessary.

**Comment by zoltan-fedor** [comment]
Sorry for commenting on the closed issue, but are there any timelines on this being implemented?
Without this, libModSecurity is pretty much useless in a reverse proxy mode - as you either need to turn off compression both on the backend and the front (which you can't do in production) or turn off response body inspection (which is then a major security risk).

**Comment by zimmerle** [comment]
@zoltan-fedor  the compression can be disabled in the web server configuration, regardless of ModSecurity utilization.
