### ISSUE TITLE
Implement support for "SecRuleUpdate" directives family in libModSecurity

### ISSUE THREAD

**Issue by victorhora** [SpiderLabs/ModSecurity#1474]
The support for  "SecRuleUpdateActionById", "SecRuleUpdateTargetById" , "SecRuleUpdateTargetByMsg" and "SecRuleUpdateTargetByTag" are not yet implemented.

Further information about these directives available here:

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleUpdateActionById

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleUpdateTargetById

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleUpdateTargetByMsg

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleUpdateTargetByTag

**Comment by zimmerle** [comment]
SecRuleUpdateTargetByTag was implemented as part of the fix for: #1287

**Comment by zimmerle** [comment]
SecRuleUpdateTargetById was implemented at: e14dc602e52a9fc231352729aaea16df3b239e14

**Comment by zimmerle** [comment]
SecRuleUpdateTargetByMsg implemented at: 4d7fd5c30a92f6a6e519ef233bb78428f60d8152.
I think it is safe to close this issue.
