### ISSUE TITLE
Request Body XML Processor also validating the payload?

### ISSUE THREAD

**Issue by skabople** [SpiderLabs/ModSecurity#1475]
I seem to be tripping ruleid 960912 which checks to see if the REQBODY_ERROR variable is set. I turned on debugging to 9 and checked the logs. Here is my log:

```
Second phase starting (dcfg 7fccce2fa510).
Input filter: Reading request body.
Input filter: Bucket type TRANSIENT contains 1 bytes.
XML: Initialising parser.
Input filter: Bucket type TRANSIENT contains 1023 bytes.
XML parsing error: XML: Failed parsing document.
Input filter: Bucket type TRANSIENT contains 1 bytes.
Input filter: Bucket type TRANSIENT contains 2047 bytes.
Input filter: Bucket type TRANSIENT contains 1 bytes.
Input filter: Bucket type TRANSIENT contains 4095 bytes.
Input filter: Bucket type TRANSIENT contains 1 bytes.
Input filter: Bucket type TRANSIENT contains 8191 bytes.
```

I also created a test script to check what is wrong with my XML since modsec couldn't seem to tell me what exactly the error was. The funny thing is that I did find something wrong (no DTD) with processing my XML but only if I tell libxml parser to validate the XML. I think I found the code that validates it in the apache2 folder in the ModSecurity repo:

[msc_xml.c](https://github.com/SpiderLabs/ModSecurity/blob/caadf97524a4861456be176a8cb91dcbb76b97e4/apache2/msc_xml.c#L96-L99)

On line 97 in that file, is the following validating the XML `msr->xml->parsing_ctx->wellFormed` if not then what is as it seems it shouldn't be. The phrase 'Well Formed' indicates that the xml is the correct syntax but not necessarily "valid".

**Comment by zimmerle** [comment]
Hi @skabople,

Thank you for your observation, I will update the manual accordingly.
