### ISSUE TITLE
Implement support for remaining "SecRuleRemove" directives family in libModSecurity

### ISSUE THREAD

**Issue by victorhora** [SpiderLabs/ModSecurity#1476]
[SecRuleRemoveByID](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/seclang-scanner.ll#L289) is known to be [implemented](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/rules.cc#L208) and working well but SecRuleRemoveByMsg and SecRuleRemoveByTag are not yet implemented.

Further information about these directives available here:

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleRemoveByMsg
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleRemoveByTag

**Comment by feanorknd** [comment]
Nowadays this directives are not being handle and cannot be used from Nginx at current branches.

**Comment by zimmerle** [comment]
SecRuleRemoveByMsg was already implemented. Still pending the SecRuleRemoveByTag implementation

**Comment by jirihradil** [comment]
+1

**Comment by zimmerle** [comment]
Implemented as part of ec667a46099a96f55b30eba4ec1de64c22d8fb6d
