### ISSUE TITLE
Implement support for "ssdeep" "InspectFile" directives family in libModSecurity

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#1478]
The two operator have not in libmodsecurity,and I hope all opearator in modsecurity Must be synchronized to the libmodsecurity
![suppt](https://user-images.githubusercontent.com/17851645/27668824-e1aaf334-5cb5-11e7-8383-571c02986865.png)

**Comment by victorhora** [comment]
@Hello-Linux we appreciate your effort to support the community but the implementation for both of these operators are already being tracked on the issues below:

[Implement support to fuzzyHash operator into libmodsecurity (#997) ](https://github.com/SpiderLabs/ModSecurity/issues/997) 
[Implement support to inspectFile operator into libmodsecurity (#999) ](https://github.com/SpiderLabs/ModSecurity/issues/999)

You can check the project [labels](https://github.com/SpiderLabs/ModSecurity/labels) to find out some of the tagged issues such as  [libmodsec - missing features](https://github.com/SpiderLabs/ModSecurity/labels/libmodsec%20-%20missing%20features) or [libmodsec - missing operators](https://github.com/SpiderLabs/ModSecurity/labels/libmodsec%20-%20missing%20operators).

It's also a good idea to use the search feature for Github issues before creating new ones. There's a high chance that your issue or question is already answered or already being handled on a different issue ;)

Thanks!
