### ISSUE TITLE
Implement Skip action for SecRequestBodyLimitAction

### ISSUE THREAD

**Issue by tomsommer** [SpiderLabs/ModSecurity#1480]
Based on #1471 I would like to request a feature to add a Skip action to `SecRequestBodyLimitAction` because partial processing can result in requests being terminated.

**Comment by zimmerle** [comment]
Hi @tomsommer,

I believe that you can ignore incomplete requests based on the logic of your rules, for instance: checking the variable INBOUND_ERROR_DATA.
