### ISSUE TITLE
ModSecurity: SecPcreMatchLimit not allowed in VirtualHost

### ISSUE THREAD

**Issue by itbuiductai** [SpiderLabs/ModSecurity#1481]
I try to configure modsecurity with a virtual host in apache then it alerted the error: "ModSecurity: SecPcreMatchLimit not allowed in VirtualHost". Why SecPcreMatchLimit was not allowed in Virtual host? any option of mod_sec is same that.

**Comment by victorhora** [comment]
Hi @itbuiductai,

Yes, indeed there are a few directives that aren't allowed to be placed inside VirtualHost configurations, namely:

* [SecPcreMatchLimit](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/apache2_config.c#L2924-L2941)
* [SecPcreMatchLimitRecursion](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/apache2_config.c#L2943-L2960)


* [SecChrootDir ](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/apache2_config.c#L1392-L1417)
* [SecDataDir](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/apache2_config.c#L1441-L1452)
* [SecGuardianLog](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/apache2_config.c#L1591-L1640)
* [SecServerSignature](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/apache2_config.c#L2484-L2492)

You should place these inside your global server-wide (not per VirtualHost) configuration. Normally this will be placed inside your [modsecurity.conf](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/modsecurity.conf-recommended#L88-L92) configuration file.

**Comment by victorhora** [comment]
I've added notes on the reference manual to make this limitation clearer:

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecPcreMatchLimit

**Comment by itbuiductai** [comment]
Hi @victorhora 
yes, i see.
But then we can only use a modsecurity.conf template per webserver.
do you know anyway to configure modsecurity.conf per virtualhost?
what is important of SecPcreMatchLimit?
Thanks

**Comment by victorhora** [comment]
You should be able to safely set different VirtualHosts just fine with your ModSecurity configuration. As long as your "template" don't use any of the directives mentioned above inside your VirtualHost context and just have this one directive set globally. 

You might have a legitimate reason for needing to set different SecPcreMatchLimit values for different web applications, but you should be able to get away with it by just setting the value globally.

You can learn about SecPcreMatchLimit on the reference manual: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecPcreMatchLimit

**Comment by itbuiductai** [comment]
Thanks @victorhora ,
I hope you received my message. Pls, contact with me as soon as you agree,
best regard!
