### ISSUE TITLE
@DetectXSS doesn't have a capture option.

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/ModSecurity#1482]
while DetectSQLi has a capture option which puts data into tx.0 DetectXSS doesn't. This behavior is inconsistent and confusing. It should be fixed in order to prevent confusion on behalf of developers. Also @victorhora indicated that he would add elements that support capture to the reference manual.

**Comment by victorhora** [comment]
Proposed fix at: #1488 

Reference manual updated stating the operators which supports "capture" actions: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual/8a14f18461156f31cbb609afb7feac2d63cd4744
