### ISSUE TITLE
MODSEC-311: Modsecurity CoreRuleSet V 2.2.3: Rule 981244 

### ISSUE THREAD

**Issue by rwells9444** [SpiderLabs/ModSecurity#1490]
MODSEC-311: Modsecurity CoreRuleSet V 2.2.3: Rule 981244 (modsecurity_crs_41_sql_injection_attacks.conf) creates false positives because of expressions, that have SQL- Keywords. An example from a  text field asking what your favorite quote is :
"time sure flies when you are having fun!"

**Comment by csanders-git** [comment]
CRS 2.2.3 wasn't designed to be FP free it was designed to be configured. Try running this with the much more recent and tuned CRS 3.0

**Comment by victorhora** [comment]
@rwells9444 please try following @csanders-git suggestions.

If you're still having issues specifically with the CoreRuleSet, please direct those to CoreRuleSet Github here:

https://github.com/SpiderLabs/owasp-modsecurity-crs

**Comment by rwells9444** [comment]
csanders. thanks for the help!  Sorry for the delayed response. It took two days for my web hosting provider to make the correction, and I wanted to verify it was corrected before I replied. I'm up and running thanks to you!!
Victor, thanks for the url.  I've got it bookmarked!!
