### ISSUE TITLE
Why i m seeing this for every wp-login.php request???

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [SpiderLabs/ModSecurity#1491]
![image](https://user-images.githubusercontent.com/11312949/27925537-84a0e0e2-629e-11e7-8c85-8915d4d757f7.png)

Why i m seeing this Please explain me how to get this fixed. its not something I should contact each and everyhost and ask them to whitelist it. its somethign related to you mod_security

Please advise

**Comment by bostrt** [comment]
@MansoorAliKhanOfficial I do not see the connection between mod_security and that error message. It looks like WordPress.org has blocked you IP address for some reason. You may need to reach out in the WordPress forums.

**Comment by MansoorAliKhanOfficial** [comment]
no its not like that, even my own domain's wp-login.php is doing the same. so there is some stupid stuff going on. Please help......

**Comment by zimmerle** [comment]
Hi @MansoorAliKhanOfficial what leads you to believe that this particular issue is related to ModSecurity?

**Comment by MansoorAliKhanOfficial** [comment]
because its happening to when every i try to login to wp-login.php for any WP site, either its WP.org or myown personal site.

**Comment by bostrt** [comment]
@MansoorAliKhanOfficial This looks like an issue with WordPress' JetPack settings. 

https://goo.gl/okvyPM
