### ISSUE TITLE
pmfromfile in ModSecurity3.0(libmodsecurity)

### ISSUE THREAD

**Issue by Ngsand** [SpiderLabs/ModSecurity#1492]
Hi,
A bit of surprise came with the use of ModSecurity 3.0(libmodsecurity).
When I tried to set two files using the operator @pmfromfile, I get the message:"Failed to open file".
SecRule SERVER_NAME "@pmfromfile hosts.data host2.data" "deny,log,tag:'SERVER_NAME:%{SERVER_NAME}',id:10001004"

Rules error. File: 900.conf. Line: 2. Column: 19. Failed to open file: hosts.data host2.data. Looking at: 'hosts.data host2.data'

Does the @pmfromfile operator in ModSecurity3.0 support reading multiple files?

**Comment by zimmerle** [comment]
Hi @Ngsand,

Indeed, the parser for v3 does not understand multiple files on @pmfromfile. Use multiple rules to achieve your goal is a problem for you?

**Comment by Ngsand** [comment]
OK， I got it.
