### ISSUE TITLE
 error: couldn't find APXS

### ISSUE THREAD

**Issue by shorman88** [SpiderLabs/ModSecurity#1494]
Hello,

I'm trying to build modsecurity 2.9.1 with httpd 2.4.26 on CentOS 6.9 but i'm keep getting the below error:
```
configure: using curl v7.19.7
configure: looking for Apache module support via DSO through APXS
configure: error: couldn't find APXS

```
here is my **modsecurity configure param**:

`./configure --with-apx=/opt/httpd/bin/apxs --prefix=/opt/modsecurity --with-apr=/opt/httpd/bin --with-apu=/opt/httpd/bin`

 **httpd configure:**
`./configure --enable-headers --enable-expires --enable-unique-id --enable-proxy --enable-rewrite --prefix=/opt/httpd --with-included-apr`

As per the documentation to report any incompatibility issue with any of apache 2.x version, i'm submitting this issue hopefully you can help.

Thanks.

Ayman

**Comment by bostrt** [comment]
@shorman88 I see `--with-apx` in the command line args. Should be `--with-apxs`.

**Comment by victorhora** [comment]
Closing this one based on @bostrt comment. This should fix your issue @shorman88 

Thanks @bostrt!
