### ISSUE TITLE
pause action stops security processing

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1504]
In mod_security2.c, perform_interception():
case ACTION_PAUSE :
            status = DECLINED;
            message = apr_psprintf(msr->mp, "Paused Access%s.", phase_text);
            msr->was_intercepted = 0;
            msr->allow_scope = ACTION_ALLOW;
The last line is supposed to stop security processing!

**Comment by marcstern** [comment]
Mistake

**Comment by marcstern** [comment]
Mistake (at least to test)

**Comment by zimmerle** [comment]
?

**Comment by zimmerle** [comment]
?

**Comment by marcstern** [comment]
Actually, in case https://github.com/SpiderLabs/ModSecurity/issues/1505 is solved, there is a bug in this code. However, due to the other bug, it does not occur.
Let's discuss the other one first.

**Comment by marcstern** [comment]
Cannot reproduce in httpd 2.4 with MS 2.9.2 => ignore this

**Comment by zimmerle** [comment]
Hi @marcstern on #1505 you said that the issue is not reproducible. Does this means that this one is not reproducible either?
