### ISSUE TITLE
"allow" does not allow in the same phase

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1505]
SecAction "phase:1,allow"
SecAction "phase:1,deny"
=> denied

msr->allow_scope is only checked at the beginning of the phases, but it doesn't stop the current processing.

**Comment by marcstern** [comment]
Cannot reproduce it with trunk

**Comment by zimmerle** [comment]
Hi @marcstern,

Can you give us a little more details on this issue report? I am not sure if I understood. Keep in mind that those reports will be here for the community, as a knowledge base. Therefore, there will be good to have a very detailed description of the issue that you are facing.

**Comment by marcstern** [comment]
Cannot reproduce in httpd 2.4 with MS 2.9.2 => ignore this
