### ISSUE TITLE
Wiki modification: ENV clarifications

### ISSUE THREAD

**Issue by jimyolin** [SpiderLabs/ModSecurity#1507]
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#ENV

Just like to see ENV be clarified that it is not just environment variables set by Modsecurity, but includes all environmental variables available (at least in Apache2)

Also, since lack of examples just off of google. Usage of ENV in a msg action:
SecRule TX:ANOMALY_SCORE "@gt 0" "phase:5,id:22,nolog,auditlog,msg:'%{env.ssl_protocol}'"

**Comment by victorhora** [comment]
Hi @jimyolin 

Thanks for your note here. Indeed other variables are accessible from within "env".

I've just added a note in the reference manual to add the missing information.

If there's anything else missing, feel free to reopen the issue.
