### ISSUE TITLE
ctl:ruleEngine=On run not correctly

### ISSUE THREAD

**Issue by itbuiductai** [SpiderLabs/ModSecurity#1508]
Hi @zimmerle @victorhora 
I ran some tests with your "ctl:ruleEngine" configuration a few day ago. I saw that may be it runs incorrectly.
I have the following context:
------------------------------
SecRuleEngine DetectionOnly
....
SecRule ARGS_NAMES "name" \
"chain, \
id:'12345679',phase:1,t:none,ctl:ruleEngine=On,nolog,deny"
SecRule REQUEST_URI "@contains /admin"
....
include CRS rule here!
------------------------------
Explain somethings:
We have two conditions in a chain: 
     1) ARGS_NAMES == "name" ? 
     2) REQUEST_URI == /admin ?
correctly, If both of them are True then Deny the user request.
But when ARGS_NAMES == "name" is true and REQUEST_URI == /admin is False then something is wrong.
All of rules was included after that will run with ON Mode, for example CRS rules. I don't understand for that. It likes a trigger to Enable evil rules kill my user requests.
By logic, I think ON mode will only run inside this rule. And it will not effect to others.
Thanks for all!

**Comment by lkarsten** [comment]
Under the assumption that this is about libmodsecurity, see #1495 as well. As far as I can tell, ctl:RuleEngine is not implemented and ignored when executing rule sets.

**Comment by zimmerle** [comment]
Support for ctl:ruleEngine was added at: 4bec6b001902033c43537710d548d731048af210
