### ISSUE TITLE
Manipulate REQUEST_URI and REQUEST_HEADER data directly from ModSec

### ISSUE THREAD

**Issue by jamuse** [SpiderLabs/ModSecurity#151]
the STREAM_INPUT_BODY variable does not currently allow you to manipulate REQUEST_URI or REQUEST_HEADER data. While you can use mod_headers for cookie manipulation there is no way to manipulate GET parameters. Can this functionality be added directly to ModSecurity?

**Comment by zimmerle** [comment]
Due to limitation to support such feature in different webservers, the @rsub is no longer an option in v3.0. Therefore, closing this issue.
