### ISSUE TITLE
Can't locate API module structure `security2_module' symbol is undefined

### ISSUE THREAD

**Issue by johnmckinght** [SpiderLabs/ModSecurity#1512]
Hai,

been trying to setup modsecurity in AWS AMI
following [Compilation Recipe for AWS](https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes#amazon-linux) the only different is i specify a prefix and sysconfdir
``[root@ip- work]# ./configure --sysconfdir=/etc --prefix=/usr``
its the only different from the setup

my current os-system
```
[root@ip- work]# cat /etc/issue
Amazon Linux AMI release 2017.03
Kernel \r on an \m
```
httpd version
```
[root@ip- work]# httpd -v
Server version: Apache/2.4.25 (Amazon)
Server built:   Jan 19 2017 16:55:49
```
after finish compiling
```
[root@ip- work]# ls /usr/lib/ | grep -i modsec
libmodsecurity.a
libmodsecurity.la
libmodsecurity.so
libmodsecurity.so.3
libmodsecurity.so.3.0.0
```
my configuration is just simple, after ``make`` and ``make install`` i then link the following file above which is ``libmodsecurity.so.3.0.0`` to ``/etc/httpd/modules/`` as ``mod_security2.so``
```
[root@ip- lib]# ln -s $PWD/libmodsecurity.so.3.0.0 /etc/httpd/modules/mod_security2.so
[root@ip- lib]# ls -l /etc/httpd/modules/ | grep -i sec
lrwxrwxrwx 1 root root     32 Jul 25 11:32 mod_security2.so -> /usr/lib/libmodsecurity.so.3.0.0
```
create httpd module configuration for modsecurity
```
[root@ip- conf.modules.d]# cat 00-modsecurity.conf 
LoadModule security2_module modules/mod_security2.so
```
now when i try to start the httpd it failed like this
```
[root@ip- conf.modules.d]# /etc/init.d/httpd start
Starting httpd: httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.modules.d/00-modsecurity.conf: Can't locate API module structure `security2_module' in file /etc/httpd/modules/mod_security2.so: /etc/httpd/modules/mod_security2.so: undefined symbol: security2_module
                                                           [FAILED]
```
now see ``security2_module symbol is undefined`` and it said ``can't locate API module structure``.
i've been using modsecurity before on ``debian jessie`` with ``Apache/2.4.10`` with the same LoadModule configuration with no issue like this.

are the name of the module is now different in branch v3/master ?
the power of google now useless i've been searching for two hour now
a kind help/advice would be really helpful, thanks.

**Comment by johnmckinght** [comment]
i ended up switch back to branch v2/master
```
[root@ip- modsec]# git branch
* v2/master
```
with same module config
```
[root@ip- conf.modules.d]# cat 00-modsecurity.conf 
LoadModule security2_module modules/mod_security2.so
```
starting and listing httpd module
```
[root@ip- modsec]# /etc/init.d/httpd start
Starting httpd:                                            [  OK  ]
[root@ip- modsec]# httpd -M | grep -i sec
 security2_module (shared)
```
just before i finally given up and switching to branch v2, i set the configuration to
``LoadModule security3_module modules/mod_security3.so`` i assume because i did compile v3/master branch but its still failed and won't load the module.

**Comment by zimmerle** [comment]
Hi @johnmckinght,

Version 3 demands two different components: The library and the connector. You have installed the library. The connector is available here:

- https://github.com/SpiderLabs/ModSecurity-apache
