### ISSUE TITLE
 SecRequestBodyInMemoryLimit not used in V3

### ISSUE THREAD

**Issue by AndrewFromMelbourne** [SpiderLabs/ModSecurity#1516]
Looking at the code for Modsecurity V3, the configuration directive 
SecRequestBodyInMemoryLimit  is not used. The parser accepts the value of SecRequestBodyInMemoryLimit and uses it to set the value of driver.m_requestBodyInMemoryLimit. However, driver.m_requestBodyInMemoryLimit is not used in any other part of the code.

**Comment by zimmerle** [comment]
Hi @AndrewFromMelbourne,

The request size is taken into consideration into this block here:
https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/transaction.cc#L871-L903

As you can see the values are being handled.

**Comment by AndrewFromMelbourne** [comment]
In seclang-scanner.ll
```
CONFIG_DIR_REQ_BODY_IN_MEMORY_LIMIT     (?i:SecRequestBodyInMemoryLimit)
```
In seclang-parser.yy
```
    | CONFIG_DIR_REQ_BODY_IN_MEMORY_LIMIT
      {
        driver.m_requestBodyInMemoryLimit.m_set = true;
        driver.m_requestBodyInMemoryLimit.m_value = atoi($1.c_str());
      }
```

Searching all the files from the release for m_requestBodyInMemoryLimit
```
$ find . -type f | xargs grep m_requestBodyInMemoryLimit
./headers/modsecurity/rules_properties.h:    ConfigDouble m_requestBodyInMemoryLimit;
./src/parser/seclang-parser.cc:        driver.m_requestBodyInMemoryLimit.m_set = true;
./src/parser/seclang-parser.cc:        driver.m_requestBodyInMemoryLimit.m_value = atoi(yystack_[0].value.as< std::string > ().c_str());
./src/parser/seclang-parser.yy:        driver.m_requestBodyInMemoryLimit.m_set = true;
./src/parser/seclang-parser.yy:        driver.m_requestBodyInMemoryLimit.m_value = atoi($1.c_str());
```

m_requestBodyLimit is set from CONFIG_DIR_REQ_BODY_LIMIT
```
    | CONFIG_DIR_REQ_BODY_LIMIT
      {
        driver.m_requestBodyLimit.m_set = true;
        driver.m_requestBodyLimit.m_value = atoi($1.c_str());
      }
```
which in the scanner is SecRequestBodyLimit not SecRequestBodyInMemoryLimit 
```
CONFIG_DIR_REQ_BODY_LIMIT               (?i:SecRequestBodyLimit)
```

I according to the documentation
```
Description: Configures the maximum request body size that ModSecurity will store in memory.
```

I had assumed that this would have put an upper limit to the size of the buffer created in Transaction::requestBodyFromFile() that is used to read the request from file.

**Comment by AndrewFromMelbourne** [comment]
Hi @zimmerle have you had a chance to read my reply?

**Comment by zimmerle** [comment]
Hi @AndrewFromMelbourne,

Sorry for the delay. Indeed, SecRequestBodyInMemoryLimit was not being used. I've changed the parser to state that this configuration is no longer available. Here goes the reason:

LibModSecurity is able to deal with request body in a file or in a buffer (chunked or not). Nginx has this property [client_body_buffer_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size) which controls whenever a request should be saved to a file or used as a buffer. If it is a file, ModSecurity will use the file to perform the inspection. If not, the buffer will be used.

**Comment by AndrewFromMelbourne** [comment]
Thanks very much @zimmerle!
