### ISSUE TITLE
Reference Manual only lists copyright of Trustwave but fails to mention other contributors

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/ModSecurity#1518]
It is important to note that much of this content is generated from Ivan's book so this is highly misleading. But even if this wasn't the case, this project is licensed under Apache 2.0 license and if you're going to be listing contributors you need to indicate that this document was not just generated solely by Trustwave

**Comment by zimmerle** [comment]
Hi @csanders-git,

Thank you for bought this up. Can you refer to us other Apache projects where the copyright is also redirected to the contributors? For instance: HTTPD and/or any of its modules? The link to the copyright notice will be perfect.

About Ivan's book, do you mind to tell what contents are taken (or generated) from Ivan's book? I am going to need further information to move forward with this issue.

**Comment by zimmerle** [comment]
Closing this issue as we don't hear any feedback form @csanders-git
