### ISSUE TITLE
Allocate 10000 rules range for Fastly

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/ModSecurity#1522]
I'd like to request a 10000 rules range for Fastly (https://www.fastly.com).

**Comment by victorhora** [comment]
Done.

The following has been updated to reflect the reserved range:

* https://github.com/SpiderLabs/OWASP-CRS-Documentation/commit/df9914a236c18ca83e85f9e437cc74be61d3c7c5
* https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#id
* https://www.modsecurity.org/CRS/Documentation/ruleid.html

**Comment by fgsch** [comment]
Great. Thanks!
