### ISSUE TITLE
Bugs in parsing SetVar action in ModSecurity V3

### ISSUE THREAD

**Issue by asterite3** [SpiderLabs/ModSecurity#1529]
SetVar action is special in that it is parsed by rule language parser (while other actions parse their payload themselves, in a code that implements them). When setvar's payload is enclosed in quotes, tokenizer (`seclang-scanner`) incorrectly identifies the closing quote as a part of content, i. e. a value assigned to a variable: `val'` is considered to be a singe token.

This can be shown with this program:
```C++
#include "modsecurity/modsecurity.h"
#include "modsecurity/rules.h"

static void logCb(void *data, const void *ruleMessagev) {
    std::cout << (char *) ruleMessagev << std::endl;
}

const char * req_uri = "/test?param=attack";

int main() {
    modsecurity::ModSecurity *modsec = new modsecurity::ModSecurity();
    modsecurity::Rules *rules = new modsecurity::Rules();
    modsecurity::Transaction * modsecTransaction;

    modsec->setServerLogCb(logCb, modsecurity::TextLogProperty);

    rules->loadFromUri("test.conf");

    modsecTransaction = new modsecurity::Transaction(modsec, rules, NULL);
    modsecTransaction->processURI(req_uri, "GET", "1.1");
    modsecTransaction->processRequestHeaders();
    modsecTransaction->processRequestBody();

    delete modsecTransaction;
    delete rules;
    delete modsec;
    return 0;
}
```
And this config in `test.conf`:
```
SecAction "id:1, nolog, setvar:'tx.bad_value=attack'"

SecRule ARGS:param "@streq %{tx.bad_value}" id:2

SecAction "id:3, log, msg:'tx.bad_param_value=`%{tx.bad_value}`'"
```
The expected output is two messages: alert, because param value `attack` matches the one in the rule, and that logging `SecAction` will report that value of `tx.bad_value` is `attack`. Instead, it prints:
```
[client ] ModSecurity: Warning.  [file "test.conf"] [line "3"] [id "3"] [rev ""] [msg "tx.bad_param_value=`attack'`"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""] [hostname ""] [uri "/test"] [unique_id "150175798088.495305"
```
Alert is not raised, variable value is `attack'`.

This breaks rules/actions setting variables with quote syntax and hence some rules using those variables. For example, SecRule with id `901162` sets variable `tx.allowed_request_content_type`:
```
setvar:'tx.allowed_request_content_type=application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/x-amf|application/json|text/plain'"
```
Rule `920420` uses this variable to validate `Content-Type` header. The quote will become a part of regex, so the last alternative in the regex will be `text/plain'` causing requests with content type `text/plain` to be blocked by the rule (to test this, #1528 needs be fixed and #1525 merged, otherwise the rule won't work anyway).

**Comment by asterite3** [comment]
I would like to fix this, but I am not sure which approach is better. The most trivial, cheap fix is to just have tokenizer ignore single quote is it sees it at the end of the content: https://github.com/seclab-msu/ModSecurity/commit/54bc4c2a1c1cde19c8a6d81b4a1f3b3077fa72f7
It will fix the problem described above, but parsing won't be perfect: for example, it will allow to omit the closing quote:
```
SecAction "id:1, setvar:'tx.ab=11"
```
Also, it still won't allow to have comma `,` or (escaped) double quote `"` inside variable value even if quotes are used to enclose expression. Escaped single quotes (`\'`) won't appear without slashes in the resulting variable value. All these features were supported in V2.

**Comment by asterite3** [comment]
There are some more problems with parsing SetVar expression, which I found while testing this issue.
There is a form of SetVar expression without operation and value assigned, just variable name: `setvar:TX.score`. In this case, variable is created and initialized to 1.
If this form is used, parser will eat any actions after this SetVar and consider them to be a part of variable name. For example, with this config
```
SecAction "id:1, setvar:tx.val, nolog"
SecAction "id:2, log, msg:'tx.val=`%{tx.val}`'"
```
The output is
```
[client ] ModSecurity: Warning.  [file "test.conf"] [line "1"] [id "1"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""] [hostname ""] [uri "/test"] [unique_id "150298799092.429383"]
[client ] ModSecurity: Warning.  [file "test.conf"] [line "1"] [id "2"] [rev ""] [msg "tx.val=``"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""] [hostname ""] [uri "/test"] [unique_id "150298799092.429383"]
```
The logging of rule with id 1 is not suppressed, because `nolog` was not parsed as an action, variable `tx.val` is not created. In fact, it can be shown that a variable with name `tx.val, nolog` is created:
```
SecAction "id:1, setvar:tx.val, nolog"
SecAction "id:2, log, msg:'tx.val=`%{tx.val, nolog}`'"
```
Output:
```
[client ] ModSecurity: Warning.  [file "test.conf"] [line "1"] [id "1"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""] [hostname ""] [uri "/test"] [unique_id "15029880176.916457"]
[client ] ModSecurity: Warning.  [file "test.conf"] [line "1"] [id "2"] [rev ""] [msg "tx.val=`1`"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""] [hostname ""] [uri "/test"] [unique_id "15029880176.916457"]
```

Also, for some reason, parser will allow any number of single quotes (not just one) and **double** quotes before collection name. This config
```
SecAction "id:1, nolog, setvar:"""""""""'''''tx.val=1337" # this is ok
SecAction "id:2, log, msg:'tx.val=`%{tx.val}`'"
```
does not produce an error, the output will be:
```
[client ] ModSecurity: Warning.  [file "test.conf"] [line "1"] [id "2"] [rev ""] [msg "tx.val=`1337`"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""] [hostname ""] [uri "/test"] [unique_id "150298896235.127318"]
```
Any number of single and double quotes is also allowed after variable name, before equals sign:
Config
```
SecAction "id:1, nolog, setvar:tx.val""""""""''''=1"
SecAction "id:2, log, msg:'tx.val=`%{tx.val}`'"
```
Output:
```
[client ] ModSecurity: Warning.  [file "test.conf"] [line "1"] [id "2"] [rev ""] [msg "tx.val=`1`"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref ""] [hostname ""] [uri "/test"] [unique_id "150298838565.509711"]
```

**Comment by asterite3** [comment]
Another way to fix the initial issue as well as probelms described afterwards is to change how parsing SetVar expressions is made. Expressions can be parsed in two modes: one is when expression begins with a single quote and thus considred to be enclosed in quotes, second if it is not enclosed in quotes. In fact, this is how an expression is parsed in V2 (https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/re.c#L1106):
```c
        if (*p == '\'') { /* quoted value */
            // ...
        } else { /* non-quoted value */
            // ...
        }
```
With "quoted mode", opening a quote without closing it can be prohibited, commas can be allowed inside variable values (and even names).
Also, syntax analyzer can be used to have character escapes, this will allow to have escaped single (`\'`) quotes or double quotes (`\"`), or some other characters (whitespaces, newlines) - and have them without slashes in the resulting values.

This is more or less implemented in https://github.com/seclab-msu/ModSecurity/commit/4ef2d6b673821b83d1295f15e9ca22b73b1faac6, problems described above should be fixed there, I tried to make parsing SetVar behave close to how it is in V2.

The third possible approach to fix described issues is not to parse SetVar with rule language parser and to pass the whole expression to SetVar constructor and parse it manually (in `c++`) there, but, as far as I understand, this is not a preferred option since this is how SetVar was processed before commit  e9555513.

I can make a pull request with either proposed solution (https://github.com/seclab-msu/ModSecurity/commit/54bc4c2a1c1cde19c8a6d81b4a1f3b3077fa72f7 or https://github.com/seclab-msu/ModSecurity/commit/4ef2d6b673821b83d1295f15e9ca22b73b1faac6), or update any of them in some way if nesessary.

**Comment by zimmerle** [comment]
Hi @asterite3,

Thanks ;) Under test at branch: v3/dev/pull_1529.

**Comment by zimmerle** [comment]
Merged ;) 

I would prefer to process everything possible during the configuration time, so we keep the CPU free for the repetitive task of address different requests. That said, I think the best is go with seclab-msu/ModSecurity@4ef2d6b. Already tested and merged. 

I have removed the stuff from #1525. Still the commit is on your name ;)

Thank you!
