### ISSUE TITLE
`ctl:ruleRemoveTargetById` non-standard characters in collection-key

### ISSUE THREAD

**Issue by tryone144** [SpiderLabs/ModSecurity#1533]
I'm currently using libmodsecurity3 at https://github.com/SpiderLabs/ModSecurity/commit/0508395f8d5d988a0febdfaad17fd68ff92afa44,  https://github.com/SpiderLabs/ModSecurity-nginx/commit/abbf2c47f6f3205484a1a9db618e067dce213b89 build into nginx 1.13.3 and the core-rule-set v3.0.2.

I found this while trying to disable rules for specific request parameters using the `ctl:ruleRemoveTargetById` action. These parameters are auto-generated by the asp.net framework and look like `ctl00$mainContext$txtSearch`.

But loading the following rule fails with `[...] Invalid action:  $mainContext$txtSearch" [...]` (note the trailing `"`):
```
SecRule REQUEST_URI "@beginsWith /Search.aspx" \
  "id:100,phase:1,pass,nolog,t:none,\
  ctl:ruleRemoveTargetById=941100;ARGS:ctl00$mainContext$txtSearch"
```
Whereas specifying `ctl:ruleRemoveTargetById=941100;ARGS:test` works as intended.

A look inside [/src/parser/seclang-scanner.ll](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/seclang-scanner.ll) reveals, that [line 421](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/seclang-scanner.ll#L421) expects the argument to match the expression in [line 338](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/seclang-scanner.ll#L338):
```
[0-9A-Za-z_\/\.\-\*\:\;\]\[]+
```

It should be possible to fix this issue by allowing characters like `$` as well.
#717 also suggests adding support for regex selection.

From looking at this file, it appears that both other `ctl:ruleRemove*By*` actions are affected as well, as are other collections like `REQUEST_COOKIES`.

**Comment by zimmerle** [comment]
Hi @tryone144,

Thanks for the report. Fixed.
