### ISSUE TITLE
Audit Log Files Content Missing in Concurrent Mode, Modsecurity v3 & Nginx

### ISSUE THREAD

**Issue by aelyasi** [SpiderLabs/ModSecurity#1534]
My Configuration for Audit Log File is:

```
SecAuditEngine On
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Concurrent
SecAuditLogStorageDir /var/log/ramdisk/audit/

```
and When we Test Modsecurity with Traffic Generator, Modsecurity Create thousands of Log File with empty Content:

```
20170812-222312-150259099222.281288
20170812-222312-150259099222.436954
20170812-222312-150259099222.890531
....
....
```
is there any Misconfiguration?

**Comment by zimmerle** [comment]
Hi @aelyasi,

What do you have in your debug logs? what is the ModSecurity version that you are working with ?

**Comment by aelyasi** [comment]
hi @zimmerle 

the Problem was about Yajl Libraries. I didn't install the Yajl Libraries. But Modsecurity Doesn't Report any Error.
(Modsecurity V3)
(Debug Log was ok)
thanks
