### ISSUE TITLE
Wiki: Reference SecConnEngine in SecConn*StateLimit sections

### ISSUE THREAD

**Issue by nicjansma** [SpiderLabs/ModSecurity#1544]
Hi,

I couldn't find a way to edit the wiki myself?  So a small request.

Could you add a small reference in these sections:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecConnReadStateLimit
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecConnWriteStateLimit

To this:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secconnengine

(i.e. that you should turn `SecConnEngine On` if you want requests actually dropped).

I spent a few hours trying to figure out why the log was correctly catching a simulated Slow Read attack while not dropping anything.  The log didn't obviously state that the attack was being detected but not blocked, so I couldn't figure out what was going on:

```
[date] [:warn] [pid n] [client i:p] ModSecurity: Access denied with code 400. Too
many threads [141] of 50 allowed in WRITE state from [ip] - Possible DoS
Consumption Attack [Rejected]
```

It wasn't until I stumbled upon `SecConnEngine On` that the attack was properly detected and connections were dropped.

The `SecConnEngine` wiki section does also not state what the default is (which in my distribution, appears to be `DetectionOnly`).

The `SecConnEngine`, `SecConn*StateLimit` sections in the wiki would also be useful to be next to each other in the wiki, since they should be alphabetically.

Thanks! (or happy to do this myself if there is a way for me to edit the wiki)

**Comment by zimmerle** [comment]
Thanks @nicjansma,

Documentation updated accordingly
