### ISSUE TITLE
apache modsecurity and syslog

### ISSUE THREAD

**Issue by simpleuser99** [SpiderLabs/ModSecurity#1549]
Hello.
Currently my modsec send log to syslog, but I don't understand what syslog facility and severity modsec use. As a result. logs fall into different places on rsyslog server.
How can I set facility and severity? What other options are there for managing the logging for rsyslog ?
In apache config I set `ErrorLog syslog:local3` and I want to modsec forward log same way/

**Comment by void-in** [comment]
Define local3 log facility in your rsyslog.conf file and specify a particular file such as:
```
local3.* /var/log/syslog
```
All the local3 logs will be saved in the /var/log/syslog file.

**Comment by simpleuser99** [comment]
@void-in  I anderstand you. But, I have
```
local1.info                                     /var/log/php.log
local3.info                                     /var/log/httpd_error.log
```

And I view part of modsec logs in /var/log/httpd_error.log and part of /var/log/php.log/
I don't understand. how modsec log forward with local1 ?

**Comment by simpleuser99** [comment]
who have any ideas ?

**Comment by zimmerle** [comment]
Hi @simpleuser99,

ModSecurity has three different kind of logging: debug, audit, error. I guess you are indent to redirect the error log to syslog. And by your description you managed to do it? am i right?
