### ISSUE TITLE
SegFault of nginx when SecResponseBodyAccess is On

### ISSUE THREAD

**Issue by intelbg** [SpiderLabs/ModSecurity#1550]
Hello,
I am using the latest version of ModSecurity (branch 3), also tried the nginx-refactory branch, but always receive on some pages 400 bad request and nginx receive seagull.

Log from nginx error_log:

2017/08/30 15:48:21 [notice] 29467#0: signal 17 (SIGCHLD) received
2017/08/30 15:48:21 [notice] 29467#0: cache loader process 29482 exited with code 0
2017/08/30 15:48:21 [notice] 29467#0: signal 29 (SIGIO) received

Log from /var/log/mesages:

Aug 30 15:47:56 server kernel: [701385.141652] nginx[29478]: segfault at 10 ip 00007f3512e4fa11 sp 00007fff9e3d5600 error 4 in libapr-1.so.0.3.9[7f3512e39000+2b000]

Tried everything including:
- Different branches
- proxy_force_ranges on
- Increasing all nginx and modest limits and playing with all buffer settings of nginx.

Neither one helped me. I read the nginx and modest is not good implementation and read a lot of themes but problem still exists. Please give me an advices.

**Comment by zimmerle** [comment]
Hi @intelbg,

This error message is most certainly not generate by the utilization of ModSecurity version 3 with the Nginx connector. Make sure that you are really using the nginx connector with version 3. You can find further information on how to compile/setup it here:
https://github.com/SpiderLabs/ModSecurity-nginx

The error message explicit state the libapr utilization, which is no longer exist in version 3. Please double check and let us know ;)

**Comment by intelbg** [comment]
I have compiled libmodsecurity and when compile nginx with nginx-connector I receive the following error on ./configure step:

 ./configure: error: ngx_http_modsecurity_module requires the ModSecurity library.

I also tried:

export LD_LIBRARY_PATH=/usr/local/modsecurity/lib/

But it's the same.

**Comment by intelbg** [comment]
The question is why compiling modsecurity library miss files in /usr/local/modsecurity/lib as there aren't compilation errors? There is only libmodsecurity2.so. Also I use the git branch or version 3, shouldn't it be libmodsecurity3.so?

**Comment by intelbg** [comment]
Ok, I found the problem. The right way to obtain the version 3 of modest is the following:

git clone -b v3/master https://github.com/SpiderLabs/ModSecurity
git submodule init
git submodule update

When I did  git checkout -b origin/v3/master before that it did not obtain 3, but 2.9.  Until here it's ok, BUT, when I execute build.sh I get the following error:
 
configure.ac:44: error: possibly undefined macro: AM_PROG_AR
configure:20298: error: possibly undefined macro: AM_DEFAULT_VERBOSITY

How can I resolve it?

**Comment by intelbg** [comment]
So.... I resolved the issue from the previous posts with upgrading autoconf, automate, gcc, g++ and installing ncurses + ncurses-libs + devel packages. Now I am using modsecurity v3 with nginx-connector as you suggested. When I loaded the crs file with the rules there were a lot of errors:

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/nginx/conf/modsecurity.conf. Line: 50. Column: 33. As of ModSecurity version 3.0, SecRequestBodyInMemoryLimit is no longer supported. Instead, you can use your web server configurations to control those values. ModSecurity will follow the web server decision.  in /usr/local/nginx/conf.d/pipi.conf:11257

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/nginx/conf/modsecurity.conf. Line: 287. Column: 43. SecDefaultActions can only be placed once per phase and configuration context. Phase 2 was informed already.  in /usr/local/nginx/conf.d/pipi.conf:11257

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/nginx/conf/modsecurity.conf. Line: 22. Column: 29. Invalid input:  SecStreamInBodyInspection On in /usr/local/nginx/conf.d/pipi.conf:11257

Invalid input:  SecStreamOutBodyInspection On in /usr/local/nginx/conf.d/pipi.conf:11257

one.conf. Line: 4. Column: 30. Invalid input:  SecStreamOutBodyInspection On in 

e /usr/local/nginx/conf/nginx.conf test

ginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/nginx/conf/modsecurity-one.conf. Line: 8. Column: 41. ContentInjection is not yet supported.  in /usr/local/nginx/conf.d/pipi.conf:11257

So, now my questions are:

1. I commented these lines with these modsecurity directives. Are they all unsupported and do you think that commenting them is causing 404 ? (before it worked but returned 400)?

2. Is the old crs file compatible or I should use new for version 3?

3. Any other recommendations after switching to nginx connector?

here is my nginx user.conf file:

modsecurity on;  in the server block

location / {

     modsecurity_rules_file /usr/local/nginx/conf/modsecurity-one.conf;

        proxy_pass	http://xxxxx:8080;

**Comment by intelbg** [comment]
Where I can see the replacement of these modsecurity options for version 3? I didn't see an wiki like for modsecurity 2.X? How can I set default action and control it?
