### ISSUE TITLE
Memory leaks when using rule with  @validateSchema

### ISSUE THREAD

**Issue by dennus** [SpiderLabs/ModSecurity#1553]
Hello!
I'm try to use libmodsecurity-3.0.0 rc1 with latest nginx-connector sources, and when I try to validate xml using @validateSchema rule, I see that nginx-worker process memory is grow very fast. No another rules is used, only validation. 
E.g., I'm run ab with this params :
`ab -T text/xml -p request.xml -n 10000 -c 100 -k http://localhost:8081/xml_request`
Before running test, worker proccess used 68M memory
After second:
664,7813
After third:
1255,145
After fouth
1847,445
And finally, after five attempt:
2438,094

No memory cleared after all.

**Comment by zimmerle** [comment]
Fixed as part of 41bf7f7
