### ISSUE TITLE
centos 6.5 install modsecV3 error

### ISSUE THREAD

**Issue by 365moods** [SpiderLabs/ModSecurity#1554]
when i run build.sh, report this err msg:

`
bash build.sh

libtoolize: putting auxiliary files in .'. libtoolize: copying file./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, build'. libtoolize: copying filebuild/libtool.m4'
libtoolize: copying file build/ltoptions.m4' libtoolize: copying filebuild/ltsugar.m4'
libtoolize: copying file build/ltversion.m4' libtoolize: copying filebuild/lt~obsolete.m4'
configure.ac:44: warning: macro AM_PROG_AR' not found in library configure.ac:44: warning: macroAM_PROG_AR' not found in library
configure.ac:44: error: possibly undefined macro: AM_PROG_AR
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
configure:19307: error: possibly undefined macro: AM_DEFAULT_VERBOSITY
autoreconf: /usr/bin/autoconf failed with exit status: 1
configure.ac:44: error: possibly undefined macro: AM_PROG_AR
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.
configure:19307: error: possibly undefined macro: AM_DEFAULT_VERBOSITY
`

**releaseinfo
autoconf : 2.63
automake: 1.11.1
libtool: 2.4**

**Did anyone else meet?
adn anyone who can help?**

**Comment by victorhora** [comment]
Hi,

Which version you're trying to setup? RC1 of libModSecurity?

You might want to follow the compilation recipes here: https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes

**Comment by alexdavydov** [comment]
In my experience, it's not possible to build modsecv3 with stock CentOS/RHEL 6 toolchain. For one, v3 is written in C++11 which is not supported by GCC 4.4 that ships with EL6.

CentOS 7 userland works for me (GCC 4.8, Automake 1.13, Autoconf 2.69, Libtool 2.4, flex 2.5, bison 2.7)

**Comment by csanders-git** [comment]
I wrote the recipe for 6.5 it is possible just a royal PITA

**Comment by zimmerle** [comment]
Hi @365moods, Please upgrade your distro and or follow the receipts to have all the basic dependencies met.

**Comment by caukie** [comment]
> Hi @365moods, Please upgrade your distro and or follow the receipts to have all the basic dependencies met.

Maybe you should update dependency  toolchain version into the Compilation-recipes.
