### ISSUE TITLE
centos7 ModSecurity v3 only  use single CPU ?

### ISSUE THREAD

**Issue by zorogong** [SpiderLabs/ModSecurity#1555]
centos7 ModSecurity v3 only  use single CPU, environment:
openresty 1.11.2
modsecurity v3.0.0 rc1
ModSecurity-nginx

**Comment by met3or** [comment]
Can I see your vhost & nginx configuration?

**Comment by met3or** [comment]
@zorogong - Hi, worker_processes value is set to `worker_processes  auto; ` which will set the workers to the amount of CPU's you have on the system.

I will assume you have more than a single core on your system but you can be absolutely sure by running the command:

`cat /proc/cpuinfo`

Can you also provide the output of the following command:

`nginx -V`

Thanks for the info so far,

**Comment by zorogong** [comment]
just now, i have found the reason,  i used all the attacks request  when i test it,  because of the configuration below

SecAuditLogType Serial

I'm going to get rid of this configuration and it won't happen again
