### ISSUE TITLE
NULL pointer 'rule->actionset'

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1556]
At several places in the code, we access 'rule->actionset' without checking if it isn't NULL.
Although we may expect that it's never NULL, this is explicitely checked in the same files/functions at some other places.

Unless it's assessed that it can't be NULL, we must add a check.
In case it really can't be NULL, all checks that it isn't should be removed (and a comment could be added to indicate that).

PS: I was checking this because I have some crashes under high load (unless I removed compila optimization).

List of (possible) problems:

apache2_config.c: 242, 244, 895, 896, 914
re.c: 1634, 1908, 2143
re_operators.c: 2843, 3151, 3443

**Comment by zimmerle** [comment]
Indeed that is a good practice to check if a variable is null or not before use it. I see no reason why do not have those checks inplace.

**Comment by zimmerle** [comment]
Modification is under our buildbots

**Comment by victorhora** [comment]
Merged at https://github.com/SpiderLabs/ModSecurity/commit/aab128f810dcb8b557d3435fba703805a732b298 https://github.com/SpiderLabs/ModSecurity/commit/96756533bae550df3db929b6bb281d713b8509b3

Thanks.
