### ISSUE TITLE
Possible NULL pointer 'real_col_name' in re_actions.c in init_collection()

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1557]
'real_col_name' is used at several places without checking if it isn't NULL.
On line 2068, this is explicitely checked.
In case it really can't be NULL, this check should be removed (and a comment could be added to indicate that), otherwise, the NULL case should be added at the (6) other places.

**Comment by zimmerle** [comment]
Indeed, that is a good practice to check whenever the variable is null or not before access it.

**Comment by zimmerle** [comment]
It seems to me that real_col_name is being checked before used in all cases that it is used. Even when it is used as a parameters to sub-sequent calls. Therefore i am marking this issue as closed.

**Comment by marcstern** [comment]
In init_collection(), on lines 1980, 2036, 2071, 2079, 2081, 2084 it's used without check
