### ISSUE TITLE
Using uninitialized buffer in msc_crypt.c in hmac()

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1558]
On line 203, 'hmac_key' may be assigned to an uninitialised buffer 'nkey'.
On lines 209/210, it is used as source of memmove().

I suppose that 'key' should be copied in 'hmac_key' first.

**Comment by zimmerle** [comment]
To make it easy to be read by further users whom eventually hit this issue, I would like to point  that I believe that @marcstern is mentioning the line 203 of the file: msc_crypt.c. Or even: https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/msc_crypt.c#L203

Same file is used for lines 209/210 -
 https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/msc_crypt.c#L209

**Comment by zimmerle** [comment]
In [https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/msc_crypt.c#L203|203] I think there is a pointer attribution and the memory content is not relevant. It seems like only the memory space is important on that specific transaction.

**Comment by zimmerle** [comment]
In [https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/msc_crypt.c#L209](209) also in [https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/msc_crypt.c#L210](210) we have a memmove, copying the content of key to hmac_ipad and hmac_opad, respectively.  Is that your understanding ?

**Comment by marcstern** [comment]
if (key_len > HMAC_PAD_SIZE-1) on line 202, we have on line 203:
   hmac_key = nkey;
   => nkey being unintialized => hmac_key is unintialized

On line 209, we use the uninitialized hmac_key as source:
   memmove (hmac_ipad, hmac_key, key_len);
