### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by mboelen** [SpiderLabs/ModSecurity#1560]
The website linked in GitHub description links to HTTP, which does not do a redirect to HTTPS. Seeing there is a HTTPS version, updating the URL might be a quick win: https://modsecurity.org/

**Comment by zimmerle** [comment]
Hi @mboelen,

Indeed, the website is not listed as HTTPS, the reason for that is the fact that we don't spect this specific site to hold any sensitive information. In any case, the url was changed.

**Comment by mboelen** [comment]
Thanks :)
