### ISSUE TITLE
configure issues

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1569]
There are 2 problems with the dependencies checks in the configure script:

1. Minor one: if we don't use a dependency, it is still checked and a warning is generated in the log. Ex: without specifying "--with-lua", the LUA dependency is still checked.
OK, it's a minor one but having "false positive" warnings is confusing and really leads to trouble because of problem 2

2. When a needed dependency is not found, the script simply ignores it and the module is compiled without the needed support. There is a (not highly visible) warning but you usually won't notice it before installing and running the module. Example: you only notice the problem at run-time when analysing your audit log and see the message "JSON support was not enabled"

I think that the correct way would be to check the dependencies only when they are needed and, if they're missing, stop the processing as it's an error.

**Comment by zimmerle** [comment]
Hi @marcstern,

Not sure how a user cannot see if the dependency was found or not. There is a pretty neat configuration summary. As detailed below. 

<img width="720" alt="screen shot 2017-09-25 at 4 09 14 pm" src="https://user-images.githubusercontent.com/428268/30826206-13277522-a20c-11e7-800b-dd9357d507e4.png">

Get you give us more details on it?

**Comment by marcstern** [comment]
I'm speaking about v2.9x.

./configure --with-lua => command works (exit status 0), no warning.
The only thing we have is about 30 lines with "checking for ...". In the middle, we have
   checking for lua install... no
   configure: optional lua library not found

If with specify that we want to build the library with LUA (or anything else) support, it should break if it can't, not build a library without the support we requested.
