### ISSUE TITLE
input_filter only process one part of request body when request body's lenth lager then configure limit

### ISSUE THREAD

**Issue by huangyidegit** [SpiderLabs/ModSecurity#1570]
use modsecurity 2.9.1
in modsecurity.conf,part of configure is below:
SecRequestBodyAccess On
SecRequestBodyLimit 13107200 
SecRequestBodyNoFilesLimit 131072
SecRequestBodyInMemoryLimit 131072
SecRequestBodyLimitAction ProcessPartial 

when I send a file by QQ (a chiness chat tool) ,the debug messages show that request body lenth is larger
 then limit,and turns to store packes to file,then the issue appears,the input_filter function only read 8192
 bytes from file and forwarding them,then it stop.and the file do not continue sending.
I edit /modsecurity/apache2/apache2_io.c, at line 81,add retry label,at line 117 ,add if(ac) goto label,then the issue disappeared.

Have any friends meet the problem? I need your help ,best thanks ^_^.

**Comment by zimmerle** [comment]
Hi @huangyidegit,

I've notice that you are using the ModSecurity version 2.9.1. That is not our most recent versions. The newest one is the v2.9.2. I would advice you to change to version 2.9.2 before continue the tests as I expect to have some differences in this particular subject.

What happens if you remove the ```SecRequestBodyInMemoryLimit``` option from your configuration?

**Comment by huangyidegit** [comment]
@zimmerle ,
thank you for answer my questions!
I take your advise and use v2.9.2 for test,and remove the  the SecRequestBodyInMemoryLimit option from configuration,the issue still exists.
I have read the source code,in modSecurity.h file, defined a macro REQUEST_BODY_DEFAULT_INMEMORY_LIMIT , the value is 131072,and it is referenced by init_directory_config function ,so ,remove the option is no use.~_~

**Comment by zimmerle** [comment]
Hi @huangyidegit,

Sorry, I meant: ```SecRequestBodyLimitAction```. You can check further info here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secrequestbodylimitaction
