### ISSUE TITLE
undefined macro: m4_esyscmd_s

### ISSUE THREAD

**Issue by sckuchi** [SpiderLabs/ModSecurity#1575]
Hello, 

I am trying to compile Mod security for nginx and getting the following error. Tried looking for solutions online, but no luck. 

These are the steps that I am following to compile ModSecurity 
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes#centos-6x

configure.ac:6: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:20331: error: possibly undefined macro: AM_DEFAULT_VERBOSITY
autoreconf: /usr/bin/autoconf failed with exit status: 1
configure.ac:6: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:20331: error: possibly undefined macro: AM_DEFAULT_VERBOSITY

```
cat /etc/redhat-release
CentOS release 6.8 (Final)

libtool 2.2.6b
Autoconf 2.63
```

Do let me know if there's anymore information required.

**Comment by zimmerle** [comment]
Hi @sckuchi,

Most likely you will have to upgrade your autoconf. Notice the CentOS recipe, where it is upgraded to 2.69.
