### ISSUE TITLE
Incomplete JSON parsing => security vulnerability

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#1576]
** Content was removed by @zimmerle on 2017-Sep-27

**Comment by zimmerle** [comment]
Dear @marcstern,

Regardless of the content, do you really think that it is a good idea to publish a possible security bypass on GitHub ?

**Comment by marcstern** [comment]
In this case, there is very few information an attacker can use.
In case you have a vulnerability in your application in a JSON request without JSON object, then ModSecurity doesn't protect you. Point There is no way to use that info to tweak an attack to bypass ModSecurity.
This disclosure doesn't introduce an additional risk

**Comment by marcstern** [comment]
I created a (one line) pull request for this: https://github.com/SpiderLabs/ModSecurity/pull/1577

**Comment by marcstern** [comment]
Remark: In my patch, I used an empty ARG name. This looks the most logical approach; however, in a strict environment, you should have a rule forbidding (for non-JSON requests) an empty ARG name.
You obviously have the possibility to fine-tune your rule to not apply it to JSON requests but, if this syntax is totoally usual (but is it really?), then we may use a non-empty name (ex: "unnamed") to not trigger that kind of problem.
Any experience with this syntax (in any direction)?

**Comment by marcstern** [comment]
This patch is trivial and has a high value, why not adding it in the 2.9 trunk?

**Comment by zimmerle** [comment]
I think you meant to make this comment on the related pull request, not in this issue. The pull request can be found at #1577. The pull request is under review, it will be merged once the review is done.

**Comment by zimmerle** [comment]
This is already fixed in v3.0. The solution adopted is different from the ticket #1577. In v3 the json parser understands the array structures into array_n format, where "n" is the position of the element. Also, we moved from string concatenation to a stack structure making the implementation more robust. Fix is still pending for v2.

**Comment by zimmerle** [comment]
Thanks @marcstern.

Merged as part of: 9b6d4b2bb9887e6647be585db1dfb03bd7114925 and 25e5543c7f66c97871d9202cd15b9945de90faf1.
