### ISSUE TITLE
Can I transfer parameters to external script when I use the of 'exec' Action?

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#1578]
Can i write like this:

phase:1,deny,msg:'attack',log,id:39,exec:'/usr/test.sh %{rule.msg}'

**Comment by zimmerle** [comment]
Hi @prince-java,

You can use environment variables instead. 

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#setenv
