### ISSUE TITLE
Crashing while staring nginx

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1579]
Originally reported on #1563 by @sethinsd. There is a crash after loading nginx + modsecurity while there are too many hosts configured. Waiting for @sethinsd to get further details on this specific issue.

**Comment by sethinsd** [comment]
I just recompiled with the rules files from @Cloaked9000 and nginx started successfully without hardly any delay at all. I then edited nginx.conf and uncommented the modsecurity on; and modsecurity_rules_file statements and ran sudo nginx -s reload and it reloaded pretty quickly.
I have this on a QA box right now, but will probably try this with some load at some point this week and see how it holds up.

Hopefully this resolves the issue =]

**Comment by zimmerle** [comment]
Closing this. Details on #1563
