### ISSUE TITLE
ModSecurity 2.9 - SecAuditLogType Concurrent not working

### ISSUE THREAD

**Issue by mmfjunior1** [SpiderLabs/ModSecurity#1580]
Hi!
I have an Ubuntu Server and Apache. The Concurrent logging not working. If I switch to serial mode, the logging process works.
My dirs have the write and read permissions.
Any idea?
Thanks a lot.

**My conf**
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4)"
SecAuditLogType Concurrent
SecAuditLog /var/log/apache2/audit_log
SecAuditLogParts ABIFHZ
SecDataDir /var/asl/data/msa
SecTmpDir /tmp
SecAuditLogStorageDir /var/asl/data/audit
SecResponseBodyLimitAction ProcessPartial
SecAuditLogDirMode 0770

**Comment by zimmerle** [comment]
Hi @mmfjunior1,

Make sure you don't have SELinux or AppArmor blocking the file to be written. That is normally the reason.

**Comment by mmfjunior1** [comment]
Hi @zimmerle .
That's right!
Thank you for help!
