### ISSUE TITLE
ip.pag creating large file after rotating

### ISSUE THREAD

**Issue by jdarow** [SpiderLabs/ModSecurity#1581]
We have several Centos servers that were recently upgraded to apache 2.4.  Somehow our rotate cron got disabled and the ip.pag files got very large (18gb in one example).

Deleting the file and restarting apache cleared the file very briefly, then it would recreate almost immediately as 18gb again.  This created slowdowns and processes stuck on L (logging).  The file appears to be a sparse file.

Turning off modsec and then deleting both the ip.pag and ip.dir files then turning modsec back on has so far resolved the issue.

The entries from a head and a tail of ip.pag seemed to all be normal behavior and the timestamps were all since rotation, but the large sparse file may have been the culprit for the slowdowns.  Why did it create such a large file?

I don't believe there are issues with our rules as only a few of the dozen servers all running the same rules exhibited this behavior and the rules haven't changed anytime recently.

**Comment by zimmerle** [comment]
Hi @jdarow,

The collection file is kept in both: memory and disk. A random factor dictate whenever the memory is dumped to the disk. Deleting/Rotating the file is good when there was a problem to remove old-expired collections, that does not have a representation in-memory anymore.

To further analyse the content of your ip.pag you can use modsec-sdbm-util, you can find it here: https://github.com/SpiderLabs/modsec-sdbm-util

Our general advice, regarding huge collections, is to reduce the expiration time to a value that fits your environment better. Therefore, reducing the amount of data to be saved.

**Comment by jdarow** [comment]
We changed the SecCollectionTimeout to 600 and had it rotating ip.pag every 2 minutes.  Neither helped...

27.6 requests/sec - 0.9 MB/second - 32.9 kB/request
   1491 requests currently being processed, 107 idle workers

L_LLLLLLL_LLLLLLLWLL_LLLLLLLLLLLLLLLL_LLLLLLLLLLLLLLLLLLLLL_LLLL
LLLLLLLLLLLLLLLLLLLLLLL_LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL_L
LLLLLL_K__LLLLLL_LLLLLLLLLLLLLL_L_LL_LLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLKLLLLLLLLLLLLLLLLLLL_LL_LLLLLLLLLLLL
LLLLLLLLLLLLLLLL_LL__LLLLLLLLLLLLLL_WLL_LLLLLL_LL_LLLLLLLLRLLLLL
LLLLLLLLL.LLLLLL_LLLLLLLLLLLLLLLLLLLLLL.LLLL_LLLLLLLLLLLL_LLLLLL
LLL_LL_LL.LLLLL_LL_L_LLLLLKLL_LLL_LLLLLLLLLLLKLLLLLLLLLLLLLLLLLL
LLLLLLWLWLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
_LLLLLLLL_LLLL_L_LLL_LLLLLLLLLLLLLL_LLLL_L.LLLLLLLWL_LLLLLLL_LLL
LLLLL_LLLLLLLLLLLL.LLLLWLLL_LLLLLWLLLLL__LLLLLLLLLLRLLLLLKLLLLLL
LLLLLLLL_LLLLLLWL.LLLLLLLL_LWLLLLLW_LLL_LLLLLLLRLLLL_LWLLLLLL__L

Now we have another server on apache 2.2 with different mod security rules exhibiting the same behavior...

326 requests currently being processed, 43 idle workers

.LLLLLL.LL.LL.LL_LLLLLLL.LLL.LLLLLLL.L._LLLLLLKLL_LLLLLLKLL..LLL
..LL_LLL...LLLLLLL.LL.LLL.L..L.LL..L_...LLLL.._L_L.LLLL.LLLLLL..
.W.LLLL_L_..L_LLL_.L.L.L.LL..LLLKLLLL.LL..LLLLLLLLL..LLWL.L_LL..
._LL._LL.L.R...L.._L.LLL_LLLLLLLLLLLLLL._LLKKLLL..LLLLLL_L..LL.L
_.L_LLL.L.LL_..LL.LLLLRL_L._.LLCL.L..._L.LLL.LL..L_LL.LLL.LLLRLL
..LWL.LLL.LLL..LLLL..LLL_.LLLLLL_LLWL.._LLLLL.LL_LL.LLL.L.L_LLLL
.L.L.L_..L.L_L..L..LL_..L.L.LL.L.LL._LLLL.L.L...L_L_LLK_...L..LL
.LLLLLL.L.L.LL..L..L_L.L.LLL.__LLLLL.LLL.LRLLLL.._LL_LLLLLLL_.L.

**Comment by zimmerle** [comment]
Hi @jdarow,

It seems like the problem was within the comodo rules, is that it?
