### ISSUE TITLE
Memory leak mediated by PHP bug?

### ISSUE THREAD

**Issue by mrsant** [SpiderLabs/ModSecurity#1582]
Centos 7, Apache 2.4/Modsec2.9 provided by cPanel EasyApache 4 along with the atomiccorp rules - however, these tests were done without ANY rules configured, and this problem still occurs. Request a page that contains this:

```
<?php
ini_set( 'error_log', '/');
$not_array = null;
for ($x = 0; $x <= 20000000; $x++) { 
foreach ($not_array as $value) {
echo "oops, this shouldn't appear!<br />\n";
}
}
echo "finished!";
?>
```

These conditions exist in a number of bad wordpress installations we have seen - the result is explosive growth of apache error_log (+200k PHP warnings a second), and massive memory consumption of the httpd listener.

```
# ps aux | grep 34131
nobody 34131 132 1.7 12829492 1702660 ? Sl 08:37 0:59 /usr/sbin/httpd
```
After less than a minute... almost 40Gb of ram consumed:
```
nobody 34131 117 39.2 50409324 38765192 ? Sl 08:37 3:24 /usr/sbin/httpd
```

This continues until the server becomes non-responsive. As soon as we unload Modsecurity, the problem goes away - some nuisance logging still occurs, but memory consumption remains normal.

**Comment by zimmerle** [comment]
Hi @mrsant,

I am afraid I am going to need further information. You mentioned Apache 2.4 and ModSecurity 2.9 what are the minor version of those? Even better if you can paste here the ModSecurity startup versions banner. It is part of your error_log immediate after initialize your Apache.

**Comment by mrsant** [comment]
As requested. 

```
# httpd -v
Server version: Apache/2.4.27 (cPanel)
```

From error_log on startup
```
ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
ModSecurity: APR compiled version="1.5.2"; loaded version="1.5.2"
ModSecurity: PCRE compiled version="8.32 "; loaded version="8.32 2012-11-30"
ModSecurity: LUA compiled version="Lua 5.1"
ModSecurity: LIBXML compiled version="2.9.1"
```

PHP version we have tested on (although others exhibit the same issue)
PHP Version 5.6.31 - provided by CloudLinux as part of PHP Selector

It was Cloudlinux who originally tested this (having been given only the above info) and found the issue was mitigated by removing the modsec module.

**Comment by victorhora** [comment]
We couldn't reproduce this issue. Can you please confirm if this issue happens with a fresh build of ModSecurity (as opposed to CPANEL's custom build)? I'm wondering if this isn't related with a particularity of the environment or customization.

Thanks.

**Comment by victorhora** [comment]
Closing due to lack of feedback.

If the issue persists, let us know and we can try to investigate further. Thanks!
