### ISSUE TITLE
ARGS with chinese character is prone to false positives

### ISSUE THREAD

**Issue by surnamedd** [SpiderLabs/ModSecurity#1587]
args with chinese character such as 国库支付
encoded  
\\xe5\\x9b\\xbd\\xe5\\xba\\x93\\xe6\\x94\\xaf\\xe4\\xbb\\x98
and the rule 981318 contains (^[\"'`´’‘;]+|[\"'`´’‘;]+$)
encoded 
(^[\\\"\'`\\xc2\\xb4\\xe2\\x80\\x99\\xe2\\x80\\x98;]+|[\\\"\'`\\xc2\\xb4\\xe2\\x80\\x99\\xe2\\x80\\x98;]+$)
\\xe and \\xe4\\xbb\\x98 matched.
this is prone to false positives.
is there any way to slove this problem? thank you！

**Comment by zimmerle** [comment]
Hi @surnamedd,

Please inform the ModSecurity versions and ruleset name and version that you are using.

**Comment by surnamedd** [comment]
Hi @zimmerle ，
My ModSecurity version is v2.9 and the ruleset name is modsecurity_crs_41_sql_injection_attacks.conf
my url is  http://www.stsczj.gov.cn/index.php/search?atype=国库支付
this is not a malicious request (actually, it is desired) but it still match an alert to the rule
and most  false positives are caused for the same reason

**Comment by victorhora** [comment]
Hi @surnamedd 

I'm guessing you're using the CRS 2.2 as you're mentioning rule ID 981318 as per: 

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v2.2/master/base_rules/modsecurity_crs_41_sql_injection_attacks.conf#L64

This rule has been superseded by rule ID 942110 in CRS 3 as per:
https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/id_renumbering/IdNumbering.csv#L1095

So I strongly suggest that you move to CRS 3 before anything as there's many enhancements including lower chance of false positives such as this one and CRS 2.2 is getting deprecated.

If you're still having issues after updating to CRS 3, maybe you should try using a different codepage (maybe [950](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/unicode.mapping#L88-L89)?) at your [SecUnicodeMapFile](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#) configuration.

**Comment by beimuaihui** [comment]
i just type 各大百货,then CRS 3 response error :

**Comment by beimuaihui** [comment]
i just type 各大百货,then CRS 3 response error :      owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "17"] [id "942100"]

**Comment by victorhora** [comment]
@beimuaihui 

As mentioned, try using a different codepage (maybe 950?) at your SecUnicodeMapFile configuration.

If you still have issues you may want to check if your version of ModSecurity is up to date and you can try changing the "t:utf8toUnicode" action to "t:utf8toUnicode,t:urlDecodeUni" for transformation functions on the rules as this seems to alleviate those issues.

Please follow up at https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/794

**Comment by beimuaihui** [comment]
i tried using "SecUnicodeMapFile unicode.mapping 936" but still response error 942100, "SecUnicodeCodePage" not supported in Modsecurity3.
i have to temporarily  ignore it for pure chinese character.

SecRule REQUEST_FILENAME|ARGS|ARGS_NAMES|REQUEST_HEADERS|XML:/*|!REQUEST_HEADERS:Referer "^[\\u4e00-\\u9fa5\\s\\,\\.\\?\\!]+$" "phase:request,id:3200000,nolog,ctl:ruleRemoveById=942100"

**Comment by beimuaihui** [comment]
i tried using "SecUnicodeMapFile unicode.mapping 936" but still response error 942100, "SecUnicodeCodePage" not supported in Modsecurity3.
i have to temporarily ignore it for pure chinese character.

SecRule REQUEST_FILENAME|ARGS|ARGS_NAMES|REQUEST_HEADERS|XML:/*|!REQUEST_HEADERS:Referer "^[\\\\u4e00-\\\\u9fa5\\\\s\\\\,\\\\.\\\\?\\\\!]+$" "phase:request,id:3200000,nolog,ctl:ruleRemoveById=942100"

**Comment by zimmerle** [comment]
Hi @beimuaihui,

SecUnicodeMapFile is now fully working on v3. Closing this issue.
