### ISSUE TITLE
Problem of "Rule action" at Phase H

### ISSUE THREAD

**Issue by nobodysz** [SpiderLabs/ModSecurity#1592]
Hi ~

I have compiled libmodsecurity v3, when requests were blocked with `SecRuleEngine On`.

```
---w26BhY4m---H--
ModSecurity: Warning. detected SQLi using libinjection. [file "/data/webserver/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "17"] [id "942100"] [rev "1"] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: host found within ARGS:sdfsdf: 1' or '1"] [severity "2"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"] [ref "v711,8t:utf8toUnicode,t:urlDecodeUni,t:removeNulls,t:removeComments"]
```
The rule action is "Warning". but I guess it should be "Access denied with code"?
Reference resources in waf-fle：
```
$ActionStatus[0]  = "Access denied with connection close"; // action: Drop
$ActionStatus[1]  = "Access denied with code";  // action: Deny
$ActionStatus[2]  = "Access denied with redirection"; // action: Redirect
$ActionStatus[3]  = "Access denied using proxy to"; // action: Proxy
$ActionStatus[10] = "Access allowed";  // action: Allow
$ActionStatus[11] = "Access to phase allowed";
$ActionStatus[12] = "Access to request allowed";
$ActionStatus[13]  = "Paused Access"; // action: Pause
$ActionStatus[14]  = "Pausing transaction for"; // action: Pause
$ActionStatus[20] = "Warning";  // action: Pass or Detection Only
```

**Comment by nobodysz** [comment]
And when set SecAuditEngine On ,All requests seem to have been warned at Phase H.

**Comment by zimmerle** [comment]
Hi @nobodysz,

What is your  SecDefaultAction status for this phase? Notice that this specific rule may not got the request blocked, instead it may increased the _anomaly_score_.

**Comment by nobodysz** [comment]
Hi @zimmerle ,
This is my SecDefaultAction  conf:

```
SecDefaultAction "phase:1,log,auditlog,deny,status:403"
 SecDefaultAction "phase:2,log,auditlog,deny,status:403"

```

**Comment by zimmerle** [comment]
As of 39fb75c34d47c07cd53f48f8652416bd75d144b5 this issue is partially solved. Notice that the error code is not yet filled. Working on it ...

**Comment by nobodysz** [comment]
Now I update to `39fb75c` , The Phase H with non malicious request is blank.
But I can't understand why the action is `Warning` ,not `Access denied with code` when malicious requests are blocked?

**Comment by zimmerle** [comment]
As of 34e8b140e5b551c4218e37888e3957bcc4f5e843 the behavior is the same [or very close] as ModSec 2.x on Apache.

**Comment by nobodysz** [comment]
@zimmerle  Thanks for fix it. I upgraded my version and it's normal.
