### ISSUE TITLE
Error message issued when "SecRequestBodyLimitAction ProcessPartial" parameter set

### ISSUE THREAD

**Issue by truman-test** [SpiderLabs/ModSecurity#1593]
Why do these errors occur in Detectiononly mode, ProcessPartial and what do they mean?

+ Apache Version: httpd-2.4.23
+ ModSecurity Version: modsecurity-2.9.1
+ Relevant configuration parameters are as follows:
SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecRequestBodyLimit 31457280
SecRequestBodyNoFilesLimit 31457280
SecRequestBodyInMemoryLimit 31457280
SecRequestBodyLimitAction ProcessPartial

+ Apache error log
[Tue Oct 17 17:32:09.142527 2017] [:error] [pid 31034:tid 140583171503872] [client 10.61.235.135:34459] [client 10.61.235.135] ModSecurity: Error reading request body: Partial results are valid but processing is incomplete [hostname "test.net"] [uri "/test"] [unique_id "WeXACQo8AI4AAHk6XIoAAACH"]

+ ModSecurity log
Oct 17 17:32:09 10.60.0.142 {"transaction": {"time":"17/Oct/2017:17:32:09 +0900","transaction_id":"WeXACQo8AI4AAHk6XIoAAACH","remote_address":"10.61.235.135","remote_port":34459,"local_address":"10.60.0.142","local_port":1080},"request":{"request_line":"POST /test HTTP/1.1","headers":{"Host":"test.net","Content-Type":"application/x-www-form-urlencoded","Connection":"keep-alive","Accept":"*/*","User-Agent":"AppleWebKit/604.1.38 (KHTML, like Gecko) Mobile/15A421","Accept-Language":"ko-kr","Accept-Encoding":"br, gzip, deflate","Content-Length":"324"}},"response":{"protocol":"HTTP/1.1","status":500,"headers":{"Vary":"Accept-Encoding","Content-Encoding":"gzip","Cache-Control":"no-cache, no-store, must-revalidate","Content-Length":"1166","Connection":"close","Content-Type":"text/html; charset=UTF-8"}},"audit_data":{}}

**Comment by zimmerle** [comment]
Already discussed at: #918.

Most likely you request is reaching the request body limit and the processing is partial as selected in the configuration.

**Comment by truman-test** [comment]
@zimmerle 
I don't know when I see #918
I wonder why this log is happening
**ModSecurity: Error reading request body: Partial results are valid but processing is incomplete**
SecRequestBodyLimitAction ProcessPartial setting, but action taken?
Or what should I do?
