### ISSUE TITLE
Triggering ModSec from an application

### ISSUE THREAD

**Issue by szepeviktor** [SpiderLabs/ModSecurity#1595]
My [hosting provider](https://rackforest.com/) runs modsec on its web servers.
Is there a way for Apache or PHP to trigger a **core** modsec rule in the response?

I mean I have [a long list of rules](https://github.com/szepeviktor/wordpress-fail2ban/blob/master/block-bad-requests/wp-fail2ban-bad-request-instant.inc.php) in my WordPress WAF but the hoster will surely not add a rule only for me.

Please advise.

**Comment by szepeviktor** [comment]
Now I read that they have the https://www.imunify360.com/ ruleset.

**Comment by zimmerle** [comment]
Hi @szepeviktor,

Not sure what exactly you want to do, but usually the trigger is the user input or the web server output. The rule (or rules set) uses ModSecurity engine to classify if the request or response is harmful or not. After processing the content, ModSecurity can take a disruptive action (deny, redirect..), log the data or even do absolutely nothing :)

What exactly you are trying to aiming?

**Comment by szepeviktor** [comment]
I am used to using Fail2ban. My WAF calls PHP `error_log()` which lands in Apache's error.log and the IP address gets banned by Fail2ban.
Is there a way to get an IP address permanently banned by modsec? Or trigger a very critical error which hopefully ends up in banning that IP by another system/firewall running on the hoster's server?

**Comment by szepeviktor** [comment]
> or the web server output

So is there a way to output something that triggers a critical rule?
