### ISSUE TITLE
Feature request: nginx request_id

### ISSUE THREAD

**Issue by asdfuken** [SpiderLabs/ModSecurity#1596]
Since Nginx version 1.11 $unique_id variable is included by default.
I think it is useful when you want to share your unique id between your reverse proxy and your server and you can't send modsecurity's unique id in the headers because it's not available as a nginx variable.

I managed to patch my ngx_http_modsecurity.c ngx_http_modsecurity_create_ctx  changing the random salted string generated with this:
``` 
    ngx_str_t variable_name = ngx_string("request_id");
    ngx_int_t hash = ngx_hash_key (variable_name.data, variable_name.len);
    ngx_http_variable_value_t * uid = ngx_http_get_variable(r, &variable_name, hash);
```
I guess it would be a great feature.

Thank you

**Comment by victorhora** [comment]
Hi @asdfuken 

You're more than welcome to submit a pull request for features to get evaluated by the community. Maybe we could think about adding this as a configuration or compile time (ifdef) directive.

But I strongly encourage suggesting/adding new features to libModSecurity as although support for 2.x is still ongoing, 3.x is the main development focus now.

**Comment by victorhora** [comment]
This feature is now available in libModSecurity: https://github.com/SpiderLabs/ModSecurity/commit/4dd28127577eca0bf854db5c134a4134db6ff1ec
