### ISSUE TITLE
bad unicode maping in detectsqli 

### ISSUE THREAD

**Issue by alaa-ahmed-a** [SpiderLabs/ModSecurity#1601]
the rule with id 980130 decode the url in different (wrong) way, for example 
"%D8%B1%D9%82%D9%8A%D8%A9+%D8%A7%D8%AD%D9%85%D8%AF+%D9%85%D8%AD%D9%85%D8%AF+%D8%B9%D8%AB%D9%85%D8%A7%D9%86" is actually "رقية احمد محمد عثمان" but its decoded as " 1BJ) '-E/ E-E/ 9+E'F" ".
i cant really tell if its decoded like this only in libinjection but this wrong decoded string is not triggering any other rule.

**Comment by zimmerle** [comment]
Hi @alaa-ahmed-a,

What is the version of your ModSecurity? are you using unicode mapping?

**Comment by alaa-ahmed-a** [comment]
hi felipe 

I'm quite sure that i installed modsecurity version 2.9.1 but after restarting httpd and check the log i see "ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/) configured." 
so im not sure what is the version installed, if you have a better way to check the version please tell me. 
the unicode mapping is used. 


Best regards 









ALAA AHMED ABDALLA MOHAMMED 


Network Engineer 


Nile Center for Technology Research (NCTR) 
NTC Building-Khartoum 
Sudan 
E-mail: alaa.abdalla @nctr.sd 

Website: www.nctr.sd

**Comment by victorhora** [comment]
Hi @alaa-ahmed-a 

Do notice that CRS rule ID [980130](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/RESPONSE-980-CORRELATION.conf#L66-L73) is related only with correlation so its probably some other rule evaluated prior to 980130 which is probably increasing the score of this rule and maybe leading to a false positive block. Check your audit / debug logs to find out.

I'm not sure if this is libInjections's fault. This seems related with CRS issue [794 ](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/794#issuecomment-307599677).

There is a known problem with outdated unicode mapping file, so please the following:

1) You're running the latest versions (2.9.2 or 3.0.0) of ModSecurity. Either upgrade / use a distro with the latest version, or if you manually compiled it, make sure that your "LoadModule security2_module" directive is pointing to the latest / correct file.

2) Check if by changing your [SecUnicodeMapFile](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecUnicodeMapFile) directive on your modsecurity.conf to a proper codepoint for Arabic characters (say [1256  (ANSI - Arabic) ](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/unicode.mapping#L25) you can get it properly decoded.

3) Depending on your setup you might need to use Apache's Location directives to be able to use different codepoints for your website like so: https://github.com/SpiderLabs/ModSecurity/issues/348#issuecomment-308223206

If you still can't solve the problem, please follow up on #348 or CRS [794](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/794).

Thanks.

**Comment by alaa-ahmed-a** [comment]
i compiled modsec 2.9.2 now and changed the unicode from ASCII to 1256, now all is working fine.
sorry for the inconvenient and thank you for your help.

**Comment by alaa-ahmed-a** [comment]
hi @victorhora 
I'm using modsec version 2.9.2 and the latest unicode mapfile
i found out that i have the same problem as issue 794 as you mentioned.
arabic characters in unicode mapfile are not really arabic, its latin, i found that arabic characters like ع (U+0639) is not in the unicode mapfile at all.
can you briefly tell me how to add it like you did for Russian letters? or its not the solution here ? because i will have to add all the Arabic letters.

**Comment by victorhora** [comment]
Hi @alaa-ahmed-a,

Well that's unfortunate. You mean that the content of [1256 (ANSI - Arabic) ](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/unicode.mapping#L26https://github.com/SpiderLabs/ModSecurity/blob/v2/master/unicode.mapping#L26) on the unicode.mapping file is all incorrect!?

Well there has been some discussion on how to solve these unicode decode issues but we don't have a solution for it now other than maybe adding the missing bits to the mapping file. 

Maybe you could search for an up to date mapping file? Or you can use this as reference for the transforms if you really need to add them: http://unicode.org/repos/cldr/trunk/common/transforms/

**Comment by alaa-ahmed-a** [comment]
hi @victorhora 
yeah the content of 1256 (ANSI - Arabic) on the unicode.mapping file is incorrect. you can check from http://www.utf8-chartable.de/unicode-utf8-table.pl
I just edited it to be like :
1256  (ANSI - Arabic)
0620:41 0621:41 0622:43 0623:45 0624:45 0625:45 0626:45 0627:49 0628:49 0629:4f 062a:55 062b:55 062c:55 062d:46 062e:43 062f:44 0630:45 0631:46 0632:47 0633:48 0634:49 0635:4a 0636:4b 0637:4c 0638:4d 0639:4e 063a:4f 0641:41 0642:42 0643:43 0644:44 0645:45 0646:46 0647:47 0648:48 0649:49 064a:4a 064b:4b 064c:4c 064d:4d 064e:4e 064f:4f 0650:50 0651:51 0652:52

The mapping i did is nonsense really but now the ModSecurity is decoding Arabic into English letters. still don't think its the best thing to do, so I'm excited about what solution you will come up with, but till then can you add something similar to what i did in unicode.mapping file for other Arabic operators.  
 really THANK YOU

**Comment by victorhora** [comment]
That's for the feedback @alaa-ahmed-a 

Well if this solution worked for you, maybe you could help other users that needs at least some Arabic support by submitting a pull request with your changes? :)

**Comment by alaa-ahmed-a** [comment]
hi @victorhora 
I'm newbie in github so i dont really know how to make a pull request. i tried to make one but it failed in all checks, can you please help ?

**Comment by victorhora** [comment]
@alaa-ahmed-a 

Actually there's nothing entirely wrong with your pull request. There's only two issues:

a) The Travis checks are known to be failing sometimes do don't worry too much about them

b) Your pull request includes several commits from other users. This probably happened because your local repository was not in sync with the master in Github.

You can try again with this nice tutorial from Digital Ocean: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

If you still have issues let me know and we can look into analyzing and merging your push differently :)

Thanks for your contribution! :)
