### ISSUE TITLE
ModSecurity: Exec: Execution failed while reading output

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#1605]
The Shell Script execute successful,but I found those error messages in logfile,how to solve this problem?

**Comment by victorhora** [comment]
Although a given script is being executed make sure your script is:

a) Exiting cleanly
b) The script has the proper permissions (say 655)
c) To be safe, try placing the script on a directory owned by the webserver user.

Also try enabling [full debug log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDebugLogLevel) to investigate the issue.
