### ISSUE TITLE
Release date of v3

### ISSUE THREAD

**Issue by ceasbz** [SpiderLabs/ModSecurity#1606]
Hello,

Did you have any idea what is the release date of [v3/master](https://github.com/SpiderLabs/ModSecurity/tree/v3/master) version?

At currently status, are recommended to use in production environment?

**Comment by zimmerle** [comment]
Hi @ceasbz,

The release candidate one was released recently, it is available here -
https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.0-rc1

**Comment by uxbod** [comment]
Hi was trying with that and asked the question: 

" Good day, 

Have just downloaded libmodsecurity v3 rc1 from the url [ https://github.com/SpiderLabs/ModSecurity/releases/download/v3.0.0-rc1/modsecurity-v3.0.0-rc1.tar.gz | https://github.com/SpiderLabs/ModSecurity/releases/download/v3.0.0-rc1/modsecurity-v3.0.0-rc1.tar.gz ] but when I run the configure it is reporting: 

ModSecurity - v2.9.0-913-ga2427df2 for Linux 

Mandatory dependencies 
+ libInjection ....v2.9.0-913-ga2427df2 
+ SecLang tests ....a2427df2 

Am I using the correct release for use with the NGINX connector ? 

Thanks - Phil 
"

**Comment by zimmerle** [comment]
Hi @uxbod,

It may a different issue. This issue is regarding the release date for ModSecurity. It may be a issue within the library release.
