### ISSUE TITLE
Nginx w/ModSecurity 3.0 doesn't shut down workerprocesses

### ISSUE THREAD

**Issue by petermollerud** [SpiderLabs/ModSecurity#1616]
After running Nginx 1.12.1 with ModSecurity 3 for a while, we have noticed that when we issue "service nginx stop" on Redhat EL6 - Nginx is unable to shut down all of its worker processes. They must be killed off separately using "kill". This is kind of annoying and isn't how it should be.

**Comment by zimmerle** [comment]
Issue moved to [SpiderLabs/ModSecurity-nginx #73](https://github.com/SpiderLabs/ModSecurity-nginx/issues/73) via [**ZenHub**](https://www.zenhub.com/)
