### ISSUE TITLE
How to log real-ip when modsecurity deploy with cdn

### ISSUE THREAD

**Issue by nobodysz** [SpiderLabs/ModSecurity#1620]
Dear ModSecurity-Team~
I deploy modsecurity with nginx,but the source ip at audit log will be cdn's ip,not user real-ip, I don't know how can I log real-ip to audit log.

Real-ip is set at header "remoteip"

**Comment by victorhora** [comment]
If the [REMOTE_ADDR](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#REMOTE_ADDR) variable didn't worked for you, you might try checking which header your CDN provides with real client IP. Maybe X-Forwarded-For?

You could do something like storing the value X-Forwarded-For in a variable and then doing matches on this variable for your rules in similar fashion as the CRS does with the [initialization of IP collection](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-901-INITIALIZATION.conf#L243-L251).

Just be careful with blindly trusting X-Forwarded-For ;)

**Comment by nobodysz** [comment]
Hi , @victorhora ~
I set `REQUEST-901-INITIALIZATION.conf` as you said :
```
SecAction \
  "id:901321, \
  phase:1, \
  t:none, \
  initcol:global=global, \
  initcol:ip=%{x_forwarded_for}_%{tx.ua_hash}, \
  setvar:tx.real_ip=%{x_forwarded_for}, \
  nolog, \
  pass"
```

But it still records the proxy IP 100.116.239.107 .
And the request header are:

```
GET /index HTTP/1.0
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
Content-Length: 12
Connection: close
X-Forwarded-For: 192.168.1.2
Host: www.test.com
```

**Comment by nobodysz** [comment]
@zimmerle Excuse me , are there something wrong with my config, or bug?

**Comment by zimmerle** [comment]
Hi @nobodysz,

Where are you getting the ip address from?

**Comment by nobodysz** [comment]
Hi, @zimmerle ,
The real ip is set to http header `RemoteIp` .(`$http_remoteip` in nginx )
I had try to set 
```
SecAction \
  "id:901321, \
  phase:1, \
  t:none, \
  initcol:global=global, \
  initcol:ip=%{http_remoteip}_%{tx.ua_hash}, \
  setvar:tx.real_ip=%{http_remoteip}, \
  nolog, \
  pass"
```
but it dosen't work.

**Comment by zimmerle** [comment]
So, How you know that it is not working? Where did you saw the wrong ip address?

**Comment by nobodysz** [comment]
Hi @zimmerle  ,
 I saw the wrong ip address in audit_log,

**Comment by zimmerle** [comment]
You will have to have a rule that specifically ask to log the ip address. in the example above you have the CRS configured to use, what seems to be, the correct ip address. Most likely the logs from CRS will contain the right ip address. The auditlog entry which says from where a request was established from, is immutable, it will always point to the ip address from your cdn, the real origin of the request.

**Comment by nobodysz** [comment]
@zimmerle Thanks for your reply , I set real user ip to `Use Client IP from header` at waf-fle sessons , and It meets my needs .
