### ISSUE TITLE
SecMarker+SecRuleUpdateActionById doesn't work as expected

### ISSUE THREAD

**Issue by xjjy1083** [SpiderLabs/ModSecurity#1626]
SecRule TX:/^PM_SQLI_DATA_*/ "\band\b ?(?:\d{1,10}|[\'\"\(][^=]{1,10}[\'\"\)]) ?[=<>]+" \
    "phase:2,capture,t:none,deny,log,auditlog,status:403,msg:'12010',id:'12010070',tag:'1201',logdata:'%{TX.0}',severity:'2',,skipAfter:RULE1"
SecMarker RULE1
SecRuleUpdateActionById 12010070 "pass,auditlog,severity:2,status:403"

trigger 12010070 rule will generate tow logs, one is deny, another is pass.

**Comment by zimmerle** [comment]
Hi @xjjy1083,

Can you give us further details on the version of ModSecurity?

**Comment by xjjy1083** [comment]
sorry,true question is how to load rules dynamically in ModSecurity configuration file？

**Comment by xjjy1083** [comment]
The version of ModSecurity is 2.9.0.

**Comment by victorhora** [comment]
@xjjy1083 

As far as I can recall, loading rules dynamically might not work as you are expecting. What you can do is maybe using [ctl](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#ctl) actions to change rules dynamically or using [SecRuleUpdateActionById](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRuleUpdateActionById) (and cousins) as you suggested to change the rule after loading it.

**Comment by victorhora** [comment]
Going to close this one. Let us know if this need further investigation or warrants thinking about new features for future versions. Thanks!
