### ISSUE TITLE
CRS Rules Log Only

### ISSUE THREAD

**Issue by nekromantik** [SpiderLabs/ModSecurity#1628]
Hi 
I am using CRS ruletset version 3.
I also have trustwave rules installed and would like to keep CRS to logging only and trustwave to block.
How can I set CRS to log only and not block while keeping trustwave to block?
Thanks

**Comment by LeeShan87** [comment]
Hi @nekromantik 

The only way that I can think of is to change the deny action to pass in the [https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-949-BLOCKING-EVALUATION.conf](url) rules.

**Comment by victorhora** [comment]
The approach suggested by @LeeShan87 of [changing the action](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-949-BLOCKING-EVALUATION.conf#L50) might work indeed, but you would have be careful when updating the CRS as this directive would be replaced to the default value hence why we usually recommend performing changes to [RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example)

So maybe a more elegant solution would be taking advantage of the [SecRuleUpdateActionById](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleUpdateActionById) directive and doing something like:

SecRuleUpdateActionById 949110 t:none,**pass**,log,tag:'application-multi',tag:'language-multi',tag:'platform-multi',tag:'attack-generic',setvar:tx.inbound_tx_msg=%{tx.msg},setvar:tx.inbound_anomaly_score=%{tx.anomaly_score}"

Adding this directive to [RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example).
