### ISSUE TITLE
information about upgrading to v3 

### ISSUE THREAD

**Issue by b-harper** [SpiderLabs/ModSecurity#1631]
Congratulations on 3.0.0!

I am curious about upgrade process from v2 to v3.  The [Migration Matrix][0] has not been updated yet.  Any chance, a v2 configuration would would on v3?

[0]: https://github.com/SpiderLabs/ModSecurity/wiki/ModSecurity-Migration-Matrix

**Comment by zimmerle** [comment]
Hi @b-harper,

That depends on your web server. For Apache users our recommendation is not to upgrade yet. Our Apache connector is still under tests. If you are a nginx user, you can proceed with the upgrade. In that case, the rules will be the same. For further information, have a look here: https://github.com/SpiderLabs/ModSecurity-nginx#what-is-the-difference-between-this-project-and-the-old-modsecurity-add-on-for-nginx

**Comment by b-harper** [comment]
Hey @zimmerle,

I am just getting back from sometime off.  Thanks for the information.  I do have a followup question that I can't seem to find the answer.  Is 2.9.2 the last release for the 2.x branch?
