### ISSUE TITLE
collections_remove_stale: Failed deleting collection

### ISSUE THREAD

**Issue by edgreenberg** [SpiderLabs/ModSecurity#1635]
Just installed 2.9.2.  Still getting these:  Message: collections_remove_stale: Failed deleting collection (name "ip", key "x.x.x.x_c4cec15ef22e6f8b45b90bbea4b5e887cb5c72a3"): Internal error
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client x.x.x.x] 

Centos 7, compiled locally on machine.

**Comment by zimmerle** [comment]
Please check #576
