### ISSUE TITLE
different quote characters in JSON logging

### ISSUE THREAD

**Issue by rm3nchaca** [SpiderLabs/ModSecurity#1638]
Hi!
I've been testing the JSON output and found that it generates something like Operator `Rx' with parameter....
I suppose it should be 'Rx' instead of  `Rx'

https://github.com/SpiderLabs/ModSecurity/blob/c1cd668acb820824e791ba802396c60900eae9c1/src/rule.cc#L245

Thanks!

**Comment by zimmerle** [comment]
That is actually by design. To be clear to the user that the string should be sanitized before saved.
