### ISSUE TITLE
Modsecurity prevents mediawiki login on ISS10

### ISSUE THREAD

**Issue by Qbone2089** [SpiderLabs/ModSecurity#1642]
I have removed all rules, but I am still not able to login  to my mediawiki installation. No logs are generated.

**Comment by victorhora** [comment]
Hi,

Which rules / ruleset you have loaded? Which configuration directives you're using?

Which version of ModSecurity you're using?

Have you checked Windows EventLog for ModSecurity events?

**Comment by victorhora** [comment]
Setting [SecStreamInBodyInspection](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecStreamInBodyInspection) to "On" should solve your issue.

Thanks.
