### ISSUE TITLE
SecResponseBodyAccess Off does not have an effect

### ISSUE THREAD

**Issue by zoltan-fedor** [SpiderLabs/ModSecurity#1643]
Hey,

We had to turn off SecResponseBodyAccess due to the lack of SecDisableBackendCompression flag in libmodsecurity (and/or NGinx connector) (see https://github.com/SpiderLabs/ModSecurity/issues/1470), but simply setting the SecResponseBodyAccess flag to Off had no effect, we also had to set the SecResponseBodyMimeType to some non-existent type to stop the response body being inspected.

NGinx 1.13.7
ModSeurity 3.0.0

Original setting:
```
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml
```

Setting still inspecting the response body:
```
SecResponseBodyAccess Off
SecResponseBodyMimeType text/plain text/html text/xml
```

Settings which finally stoped response body inspection
```
SecResponseBodyAccess Off
SecResponseBodyMimeType text/nosuchtype
```

**Comment by chirswind** [comment]
hello there ,I'm using modSecutity for Nginx ,and met the same problem too,seting SecResponseBodyAccess Off &SecResponseBodyMimeType text/nosuchtype does not have an effect to me.

**Comment by zimmerle** [comment]
Somewhat related to SpiderLabs/ModSecurity-nginx#84

**Comment by zimmerle** [comment]
The compression can be disabled on the web server and/or proxy configuration. That is the main reason why the _SecDisableBackendCompression_  is no longer supported on v3.

As of 42a472adbda21e6ecc4711fd37d704cdb3d98fbb the body inception is respecting the configuration flag.
