### ISSUE TITLE
How to use c++ variable in SECRULE

### ISSUE THREAD

**Issue by tomarsumit** [SpiderLabs/ModSecurity#1647]
How to use c++ variable in SECRULE:
string name = "github"
SecRule REQUEST_URI|ARGS|REQUEST_BODY \"log="**name**"\" \"log,id:410000,deny,msg:'Access Denied'\"") <<

**Comment by void-in** [comment]
If I understand you correctly, you want to match "name" with the double quotes around. It can be done like:
```
SecRule REQUEST_URI|ARGS|REQUEST_BODY "log=\"name\"" "log,id:410000,deny,msg:'Access Denied'"
```
This with match if the URI, GET/POST variables or the request body has the string literal:
```
log="name"
```
in it.

**Comment by tomarsumit** [comment]
Hi,
Thank You
I want to use the value of "name" in secrule i.e 
**log = github**

**Comment by void-in** [comment]
Why can't you create something like:
```
SecRule REQUEST_URI|ARGS|REQUEST_BODY "log=\S+" "log,id:410000,deny,msg:'Access Denied'"
```
This way, any non-spacing value in log will match.

**Comment by tomarsumit** [comment]
Thank You Waqas Ali.

**Comment by victorhora** [comment]
Closing this one as the issue seems solved. Thanks @void-in :)
