### ISSUE TITLE
ModSecurity braking cetain (login) requests in DetectionOnly mode

### ISSUE THREAD

**Issue by feamsr00** [SpiderLabs/ModSecurity#1648]
Hello,

I have found that after installing MS, that several applications will no longer process logins correctly. It *appears* that certain requests have tokens\hashes (e.g. CSRF tokens) stripped out of them (quite undesirable!) This affected several applications across several implementations (PHP, Java, FCGI, ARR, etc). 

This behaviour ceased *only* with SecRuleEngine set to Off.

I have no other events or unusual configuration* to report. A new installation which was normal and no errors were reported.

IIS 8
Win Server 2012 v6.2 b9200
ModSecurity v3.0.0

*I did upgrade the rules to v3 but considering it is not supposed to be *acting* on _anything_ this is moot.

(I'd wager this is affecting #1642)

**Comment by victorhora** [comment]
Hi,

That's an interesting behaviour. Which rules / ruleset you have loaded? Which configuration directives you're using?

Also, you're using ModSecurity v3 (libModSecurity) with IIS? Or maybe you have Nginx as reverse proxy to your IIS? Or you're talking about CRS v3?

**Comment by feamsr00** [comment]
Hi!
I'm using ModSecurity as a module in IIS. While it does act as a proxy for some sites. this behaviour was observed in proxied and unproxied sites.

Considering I haven't customised the rule set. Is it ok to upload here?

**Comment by okazakov** [comment]
Hi there,

I'm observing the same behavior.

I run an ASP.NER MVC website in IIS on Win Server 2012.
Straight vanilla install of 2.9.2 ModSecurity without even adding CRS v3, - only what comes out of box with ModSecurity.

Same as feamsr00, I set:
SecRuleEngine DetectionOnly

Simple get requests render pages fine, but any POST'ing ends up with an error along the lines of:

====================================
Server Error in '/' Application.
A public action method 'BlahBlahAction' was not found on controller 'MyWebApplication.Web.Controllers.CommonController'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Web.HttpException: A public action method 'BlahBlahAction' was not found on controller 'MyWebApplication.Web.Controllers.CommonController'.

Source Error:

Line 20: @section top {
Line 21:     @Html.Partial("../Misc/Background")
Line 22:     @Html.Action("BlahBlahAction", "Common")
Line 23: }
Line 24: 
====================================

Someone suggested setting "SecStreamInBodyInspection On" here: https://serverfault.com/questions/456900/does-modsecurity-2-7-1-work-with-asp-net-mvc-3/482478#482478

I tried and confirm that it fixes the issue, but no idea why. In the same post they mention that they raised this issue and provide a link, but the link is broken. This is why I am here - I was looking for an open issue and stumbled upon this one that seems to be about the same problem.

Regards.
Oleg.

**Comment by ajcoll5** [comment]
Can confirm. Running default ModSecurity 2.9.2-64b install with IIS 8.5.9600.16384 on Server 2012 R2 with the March updates. ASP sites with forms auth and Wordpress sites were just going back to the login screen - even with it set to detection only mode. Nothing in the event logs. Setting "SecStreamInBodyInspection" as suggested in Oleg's post resolved the issue.

**Comment by victorhora** [comment]
Yes, setting [SecStreamInBodyInspection](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecStreamInBodyInspection) to "On" should solve the issue.

Thanks for your help @okazakov :)

**Comment by feamsr00** [comment]
Whoa, slow down there @victorhora. That might be a **workaround** but that doesn't make any semantical sense as a solution. 

SecStreamInBodyInspection (which is only documented to be appropriate up to ver 2.9.x) seems to be designed as a way to widen visibly into incoming data. Which I would assume would allow richer analysis in some way. That said, there remains no meaningful reason why the DO mode (a mode which should have **ZERO** side effects) would require that flag to function _correctly_. Moreover, without a reason why DO *should* require SecStreamInBodyInspection, I'm not grasping why this issue shouldn't be corrected and fixed instead of closed and dismissed.

Perhaps I'm missing something but may I ask you to just elaborate on the rational to close this bug?

**Comment by feamsr00** [comment]
In a further effort to be helpful, if you closed this bug report in an effort to triage issues, might I suggest instead using a "Has-Workaround" label?

**Comment by victorhora** [comment]
@feamsr00 Please bear in mind that the for the IIS build, we currently recommend setting SecStreamInBodyInspection to On. This feature will be enabled by default in 2.9.3 (See #1299).

The problem with the slowdown with the uploads is not present anymore since afae690 (issue #1366), so it should be safe to add this for most environments.


The issue is closed due to the workaround being fit for most people as so far we haven't stumbled upon any complaints that SecStreamInBodyInspection not being an usable solution for IIS builds.

Please notice that ModSecurity 2.x (including the IIS version) is in maintenance stage. At this stage the focus for v2 is only for fixing security issues and major bugs. So the focus of development of new features and major improvements is directed for the 3.x branch and not for 2.x.

So the case of requiring SecStreamInBodyInspection for IIS is not considered a major v2.x bug that warrants halting v3.x development for fixing it.

You can expect that this workaround will not be necessary once we have an IIS-Connector for libModSecurity (v3.x).

Thanks for your contribution.

**Comment by victorhora** [comment]
> In a further effort to be helpful, if you closed this bug report in an effort to triage issues, might I suggest instead using a "Has-Workaround" label?

I like the idea of a "Has-Workaround" label as we can use it for other issues. Done. Thanks!
