### ISSUE TITLE
class modsecurity::Rule destructor should be virtual

### ISSUE THREAD

**Issue by JayCase** [SpiderLabs/ModSecurity#1650]
Ref: v3.0.0, modsecurity/rule.h
Rule has virtual methods but non-virtual destructor.

gcc  4.8, for example:
modsecurity/rule.h:45:7: warning: 'class modsecurity::Rule' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]

modsecurity/rule.h:86:20: warning: deleting object of polymorphic class type 'modsecurity::Rule' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]

**Comment by zimmerle** [comment]
Fixed. Thanks.
