### ISSUE TITLE
Possibility of changing ids

### ISSUE THREAD

**Issue by mmfjunior1** [SpiderLabs/ModSecurity#1659]
Hello everyone!
What are the chances that the ids will change in the next version of rules?
If this is possible, is there any tool to reduce the impact of changing ids?
Thank you.

**Comment by victorhora** [comment]
Hi @mmfjunior1,

This GitHub page is related only with ModSecurity the WAF engine and not rules. 

As your question mentions rules and IDs I think it's more related with Core Rule Set (CRS) project so you should direct these questions there: https://github.com/SpiderLabs/owasp-modsecurity-crs

In the meantime have a look at the ID renumbering file that should help with the change of IDs between CRS 2 and CRS 3. As far as I know there's no current plan to change those IDs:

https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/v3.0/master/id_renumbering

Good luck.

**Comment by mmfjunior1** [comment]
@victorhora Thank you! : D
