### ISSUE TITLE
mod_security v3 hwo to build for apache?

### ISSUE THREAD

**Issue by disaster123** [SpiderLabs/ModSecurity#1661]
I can't find any documentation how to build mod_security v3 for apache. The old --with-apxs= configure option does not exist as well.

Just trying to load the .so does not work as well:
LoadModule security3_module /usr/local/modsecurity/lib/libmodsecurity.so

httpd: Syntax error on line 9 of /usr/local/apache2/conf/httpd.conf: Syntax error on line 1 of /usr/local/apache2/conf/modules-enabled.d/00_mod_security.load: Can't locate API module structure `security3_module' in file /usr/local/modsecurity/lib/libmodsecurity.so: /usr/local/modsecurity/lib/libmodsecurity.so: undefined symbol: security3_module

Greets,
Stefan

**Comment by lexvisio** [comment]
It seems the correct module is mod_security3.so, which was not installed when I ran make install from my download of ModSecurity-apache-master yesterday (make install installed nothing). 

I had to copy mod_security3.so from ModSecurity-apache-master/src/.libs/mod_security3.so to my apache modules directory. I made the same assumption about libmodsecurity.so, which is how I ended up here.

Given the popularity of ModSecurity with Apache, I had hoped to see this connector move out of beta along with ModSecurity V3.

Jeff
Debian 9, fresh install, Apache httpd 2.4.29

**Comment by felipee07** [comment]
You will need compile ModSecurity V3 first and then compile 
https://github.com/SpiderLabs/ModSecurity-apache for the connector.

**Comment by le0li9ht** [comment]
After moving the module to /etc/httpd/modules location its giving the following error.


[root@-103 modules]# httpd -t
AH00526: Syntax error on line 95 of /etc/httpd/modsecurity.d/owasp-modsecurity-crs/crs-setup.conf:
Invalid command 'SecDefaultAction', perhaps misspelled or defined by a module not included in the server configuration

**Comment by zimmerle** [comment]
@le0li9ht v3 works differently on Apache, ModSecurity rules should be placed into a `modsecurity_rules` block like the following:

```
 'SecRule ARGS "evil" "phase:3,id:113,log,status:402,block,deny"'
```

**Comment by brianp9906** [comment]
Where is the configuration information like "modsecurity_rules" block you refer to?

**Comment by csanders-git** [comment]
For more information on how to build Apache + v3 check out this dockerfile which succesfully builds apache for v3: https://github.com/CRS-support/modsecurity-docker/blob/v3/ubuntu-apache/Dockerfile

**Comment by brianp9906** [comment]
Got it thanks.

**Comment by swamisvr** [comment]
hello ,

I need to disable the modssecurity V3 on single domain
