### ISSUE TITLE
Invalid action

### ISSUE THREAD

**Issue by 7ym0n** [SpiderLabs/ModSecurity#1662]
use this rule:

SecRule ARGS "@eq test" \
    "log,\
    block,\
    t:none,\
    msg:'',\
    severity:'EMERGENCY',\
    ver:'OWASP_CRS/3.0.0',\
    maturity:'0',\
    accuracy:'0',\
    phase:1,\
    id:100000,\
    tag:'attack-disclosure'"

Problems loading the rules --Rules error. File: conf/test_rules/test.conf. Line: 4. Column: 9. Invalid action:  msg:'',\

Why?

msg: 'test' is work.

**Comment by victorhora** [comment]
Hi @7ym0n,

The [msg](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#msg) action expects some string to be associated with the rule. An empty msg action will result in a parsing error on libModSecurity.
