### ISSUE TITLE
ModSecurity could be preventing Basic Authentication coming from mod_jk

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#167]
MODSEC-16: The issue has been reported on the mailing list. I've also run into it on the tomcat-users mailing list:
http://mail-archives.apache.org/mod_mbox/tomcat-users/200809.mbox/%3C215811.93737.qm@web55203.mail.re4.yahoo.com%3E

After having looked at a single audit log entry, it would seem that the response did not contain the WWW-Authenticate header, which is required for Basic Authentication to be triggered.

**Comment by fernandohlmaia** [comment]
Dear. I still have the same problem. I have a form in php with basic authentication. In the logs, appearance that entered the rule id: 921130. My content is limited, I do not know how to solve. Every help is welcome.
