### ISSUE TITLE
PATCH: ModSecurity v3 with --disable-shared fails to compile examples and causes Nginx building failure

### ISSUE THREAD

**Issue by ivanbaldo** [SpiderLabs/ModSecurity#1670]
Hello.
./configure --disable-shared doesn't work when linking the examples, so I had to add --disable-examples too.
But then, trying to rebuild Nginx with the Nginx Connector also fails in the linking fase.
Maybe it is related, maybe not...
Thanks!!!

**Comment by ivanbaldo** [comment]
This patch fixes not only the examples when using --disable-shared, but anything that you compile against the resulting libmodsecurity (like for example Nginx with the static libmodsecurity).
Sorry but I am too lazy to create a fork and pull request for such a small change.
Thanks a lot!

`diff --git a/configure.ac b/configure.ac
index 88c9220..17da624 100644
--- a/configure.ac
+++ b/configure.ac
@@ -318,7 +318,7 @@ AM_CONDITIONAL([USE_MUTEX_ON_PM], [test $mutexPm = true])
 
 # General link options
 if test "$PLATFORM" != "MacOSX"; then
-    GLOBAL_LDADD="-lrt  "
+    GLOBAL_LDADD="-lrt -lm -lstdc++ "
 fi
 
 if test "$aflFuzzer" == "true"; then
`

**Comment by ivanbaldo** [comment]
Correction: that patch doesn't correct ModSecurity-nginx connector compilation.
In my case, I have to add all the libraries:
```sh
sed -i 's/-lmodsecurity/-lmodsecurity -lm -lstdc++ -lyajl -lxml2 -lcurl -lGeoIP -lfuzzy/g' \
  ModSecurity-nginx/config
```
The correct way is to use pkg-config I think, storing the libraries needed by the compiled libmodsecurity and then using pkg-config in the connectors and anyone willing to compile and link against libmodsecurity.
Thanks for looking into this.

**Comment by zimmerle** [comment]
Hi @ivanbaldo,

As of 0461c1c0652a2b389165da917b1fd45f75b572c3, disable shared is working as expected. The output of the compilation is a .la file. Examples are no longer broken.
