### ISSUE TITLE
Makefile (CURL_VERSION) Error 

### ISSUE THREAD

**Issue by umarfarook882** [SpiderLabs/ModSecurity#1673]
Hi @zimmerle @victorhora, Makefile Error While installing the ModSecurity 2.9.2 (stable) with option 
``--with-curl=/usr/bin/curl``
 
**Makefile Error**
![makefile-error](https://user-images.githubusercontent.com/22318677/36023246-cdee9956-0db1-11e8-9042-07e68f8f79f6.png)

**Makefile Error Reason**
![makefile-error-reason](https://user-images.githubusercontent.com/22318677/36023466-95394a24-0db2-11e8-9b07-08bb0b166b94.png)

If i  run ModSecurity 2.9.2 (stable) without the option ``--with-curl=/usr/bin/curl``, its working fine :)
Anyway, I just want you guys to know about this issue.

**Comment by victorhora** [comment]
Hi @umarfarook882,

Thanks for the report :)

Notice that this behaviour is expected as the "--with-curl" option is intended for the path where either the [curl-config](https://curl.haxx.se/libcurl/using/curl-config.html) script is located or the path where your installation of libcurl is located, and not for the actual cURL binary (/usr/bin/curl).

So if you do ``--with-curl=/usr/bin/curl-config`` or ``--with-curl=/usr`` (based on the output of /usr/bin/curl-config --prefix) it should work fine :)

Let us know if for any reason this is not the case for your environment.
