### ISSUE TITLE
ModSecurity V3 Log Collector

### ISSUE THREAD

**Issue by shmobasheri** [SpiderLabs/ModSecurity#1676]
Is there any log collector for modsec v3??!

**Comment by victorhora** [comment]
Hi @shmobasheri,

libModSecurity already have native support for saving logs in JSON format using the [SecAuditLogFormat](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLogFormat) directive.

Also an HTTPS transport is available for the [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLogType) which allows sending the logs directly to a remote server.
