### ISSUE TITLE
ModSecurity fails in Ubuntu 16.04

### ISSUE THREAD

**Issue by potnii** [SpiderLabs/ModSecurity#1679]
`apachectl -M | grep --color security` gives 
`ModSecurity: Failed to open the audit log file: /var/log/apache2/modsec_audit.log` .

`sudo ls -l  /var/log/apache2/modsec_audit.log`
`-rw-r----- 1 root root 13371 Feb 21 12:08 /var/log/apache2/modsec_audit.log` 

**I tried to change rights and ownership to this file, but problem doesn't disappear.**

And at the same time modsec_audit.log contains
`Message: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/etc/modsecurity/modsecurity.conf"] [line "61"] [id "200002"] [msg "Failed to parse req$
Action: Intercepted (phase 2)
Stopwatch: 1519207731890507 2131 (- - -)
Stopwatch2: 1519207731890507 2131; combined=105, p1=87, p2=13, p3=0, p4=0, p5=5, sr=0, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/).
Server: Apache
Engine-Mode: "ENABLED"`

ModSecurity rules are standart.

Also testing modsecurity by `curl 'http://site/?q="><script>alert(1)</script>'` gives no result.

What was done wrong? Followed standart installation ...

**Comment by felipee07** [comment]
delete /var/log/apache2/modsec_audit.log, restart apache2 and see what happens.  Is apache2 running as www-data ?

**Comment by victorhora** [comment]
@felipee07 is correct.

@potnii, also, make sure to also check the permissions of the /var/log/apache2 folder itself to see if it allows file creation on this folder.

Also, check that [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLogType) is set to Serial. If you set to Concurrent you might need to created the directory for saving concurrent logs yourself.

Lastly, bear in mind that ModSecurity itself is only the WAF engine. If you need rules to block generic attacks like the one you've mentioned you should install and configure something like the [Core Rule Set](https://github.com/SpiderLabs/owasp-modsecurity-crs).

**Comment by potnii** [comment]
@felipee07 New file was created after deleting old one.
`-rw-r----- 1 root root 0 Feb 21 21:48 /var/log/apache2/modsec_audit.log`

`ps aux | egrep '(apache|httpd)`
`root     30975  0.0  3.3 420952 33640 ?        Ss   21:48   0:00 /usr/sbin/apache2 -k start
www-data 30978  0.1  4.2 502396 43284 ?        S    21:48   0:02 /usr/sbin/apache2 -k start
www-data 30979  0.2  4.2 502420 43080 ?        S    21:48   0:02 /usr/sbin/apache2 -k start
www-data 30981  0.1  4.4 502412 44760 ?        S    21:48   0:01 /usr/sbin/apache2 -k start
www-data 30994  0.1  4.0 502412 41296 ?        S    21:49   0:01 /usr/sbin/apache2 -k start
www-data 30995  0.2  4.0 502404 41300 ?        S    21:49   0:02 /usr/sbin/apache2 -k start
www-data 30996  0.1  4.2 502396 43340 ?        S    21:49   0:02 /usr/sbin/apache2 -k start
www-data 30999  0.3  4.6 503520 47084 ?        S    21:49   0:04 /usr/sbin/apache2 -k start
www-data 31000  0.0  4.0 502376 41096 ?        S    21:49   0:00 /usr/sbin/apache2 -k start
www-data 31001  0.2  3.9 502384 40376 ?        S    21:49   0:02 /usr/sbin/apache2 -k start
www-data 31002  0.1  4.2 502292 43276 ?        S    21:49   0:02 /usr/sbin/apache2 -k start`

`ps -ef | egrep '(httpd|apache2|apache)' | grep -v `whoami` | grep -v root | head -n1 | awk '{print $1}`
`www-data`

@victorhora SecAuditLogType is set to Serial. 
Problem didn't disappear (

**Comment by felipee07** [comment]
@potnii
Did you set SecUploadKeepFiles to **On**?
Theses folders are writable by www-data ? SecTmpDir SecDataDir SecUploadDir
Is AppArmor enabled ? 

Also try, it will be very helpful.
SecDebugLog /tmp/debug.log
SecDebugLogLevel 9

**Comment by potnii** [comment]
@felipee07 Thank you so much, you really helped me. 
Setting ownership to www-data:www-data and file permissions from 600 to 660 solved my problem.
