### ISSUE TITLE
line 6690: syntax error near unexpected token `dlopen'

### ISSUE THREAD

**Issue by arash-rais** [SpiderLabs/ModSecurity#1680]
Hi i got this error when running ./configure file whats the problem?

    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking for g++... g++
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking for style of include used by make... GNU
    checking dependency style of g++... gcc3
    checking for gcc... gcc
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for ar... ar
    checking the archiver (ar) interface... ar
    checking whether make sets $(MAKE)... (cached) yes
    checking for "others/libinjection/src/libinjection_html5.c"... yes
    ./configure: line 4666: PKG_PROG_PKG_CONFIG: command not found
    configure: Nothing about GeoIP was informed during the configure phase. Trying to detect it on the         
    platform...
    configure: YAJL library was not found
    ./configure: line 4914: PKG_PROG_PKG_CONFIG: command not found
    configure: Nothing about GeoIP was informed during the configure phase. Trying to detect it on the     
    platform...
    configure: GeoIP library was not found
    ./configure: line 5174: PKG_PROG_PKG_CONFIG: command not found
    configure: Nothing about LMDB was informed during the configure phase. Trying to detect it on the         
    platform...
    *** LOOKING AT PATH:  /usr/lib
    *** LOOKING AT PATH:  /usr/local/lib
    *** LOOKING AT PATH:  /usr/local/liblmdb
    *** LOOKING AT PATH:  /usr/local/lmdb
    *** LOOKING AT PATH:  /usr/local
    *** LOOKING AT PATH:  /opt/liblmdb
    *** LOOKING AT PATH:  /opt/lmdb
    *** LOOKING AT PATH:  /opt
    *** LOOKING AT PATH:  /usr
    *** LOOKING AT PATH:  /usr/lib64
    *** LOOKING AT PATH:  /opt/local
    configure: LMDB library was not found
    *** LOOKING AT PATH:  /usr/lib
    *** LOOKING AT PATH:  /usr/local/lib
    *** LOOKING AT PATH:  /usr/local/fuzzy
    *** LOOKING AT PATH:  /usr/local/libfuzzy
    *** LOOKING AT PATH:  /usr/local
    *** LOOKING AT PATH:  /opt
    *** LOOKING AT PATH:  /usr
    *** LOOKING AT PATH:  /usr/lib64
    *** LOOKING AT PATH:  /opt/local
    configure: SSDEEP library was not found
    *** LOOKING AT PATH:  /usr/lib
    *** LOOKING AT PATH:  /usr/local/lib
    *** LOOKING AT PATH:  /usr/local/lib64
    *** LOOKING AT PATH:  /usr/local/lua
    *** LOOKING AT PATH:  /usr/local/liblua
    *** LOOKING AT PATH:  /usr/local
    *** LOOKING AT PATH:  /opt
    *** LOOKING AT PATH:  /usr
    *** LOOKING AT PATH:  /usr/lib64
    *** LOOKING AT PATH:  /opt/local
    configure: LUA library was not found
    checking for libcurl config script... /usr/bin/curl-config
    ./configure: line 5918: test: : integer expression expected
    ./configure: line 5921: test: : integer expression expected
    ./configure: line 5924: test: : integer expression expected
    checking if libcurl is at least v... yes, 7.38.0
    checking if libcurl is linked with gnutls... no
    configure: using curl v7.38.0
    checking for libxml2 config script... no
    configure: *** libxml2 library not found.
    checking for libpcre config script... /usr/bin/pcre-config
    ./configure: line 6174: test: : integer expression expected
    ./configure: line 6177: test: : integer expression expected
    ./configure: line 6180: test: : integer expression expected
    ./configure: line 6183: test: : integer expression expected
    checking for PCRE JIT... yes
    configure: using pcre v8.35
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking string usability... no
    checking string presence... no
    checking for string... no
    checking iostream usability... no
    checking iostream presence... no
    checking for iostream... no
    checking sys/utsname.h usability... yes
    checking sys/utsname.h presence... yes
    checking for sys/utsname.h... yes
    ./configure: line 6690: syntax error near unexpected token `dlopen'
    ./configure: line 6690: `LT_INIT(dlopen)'

**Comment by felipee07** [comment]
apt-get install pkg-config

**Comment by victorhora** [comment]
Indeed @felipee07.
I believe the package is also called pkg-config on RPM based distros so something like "yum install pkg-config" will also work if that's the case.

Also you might want to make sure you have "build-essentials", "autoconf", "automake" etc installed prior to building. 

Lastly, you might need to do some "clean up" on your local clone before trying to compile again as you might need to run autogen.sh again if you didn't had those packages prior to running the configure script.

**Comment by arash-rais** [comment]
Hi
I follow these steps but still error is here

    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking for g++... g++
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking for style of include used by make... GNU
    checking dependency style of g++... gcc3
    checking for gcc... gcc
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for ar... ar
    checking the archiver (ar) interface... ar
    checking whether make sets $(MAKE)... (cached) yes
    checking for "others/libinjection/src/libinjection_html5.c"... yes
    ./configure: line 4666: PKG_PROG_PKG_CONFIG: command not found
    configure: Nothing about GeoIP was informed during the configure phase. Trying to detect it on the     platform...
    configure: YAJL library was not found
    ./configure: line 4914: PKG_PROG_PKG_CONFIG: command not found
    configure: Nothing about GeoIP was informed during the configure phase. Trying to detect it on the     platform...
    configure: GeoIP library was not found
    ./configure: line 5174: PKG_PROG_PKG_CONFIG: command not found
    configure: Nothing about LMDB was informed during the configure phase. Trying to detect it on the     platform...
    *** LOOKING AT PATH:  /usr/lib
    *** LOOKING AT PATH:  /usr/local/lib
    *** LOOKING AT PATH:  /usr/local/liblmdb
    *** LOOKING AT PATH:  /usr/local/lmdb
    *** LOOKING AT PATH:  /usr/local
    *** LOOKING AT PATH:  /opt/liblmdb
    *** LOOKING AT PATH:  /opt/lmdb
    *** LOOKING AT PATH:  /opt
    *** LOOKING AT PATH:  /usr
    *** LOOKING AT PATH:  /usr/lib64
    *** LOOKING AT PATH:  /opt/local
    configure: LMDB library was not found
    *** LOOKING AT PATH:  /usr/lib
    *** LOOKING AT PATH:  /usr/local/lib
    *** LOOKING AT PATH:  /usr/local/fuzzy
    *** LOOKING AT PATH:  /usr/local/libfuzzy
    *** LOOKING AT PATH:  /usr/local
    *** LOOKING AT PATH:  /opt
    *** LOOKING AT PATH:  /usr
    *** LOOKING AT PATH:  /usr/lib64
    *** LOOKING AT PATH:  /opt/local
    configure: SSDEEP library was not found
    *** LOOKING AT PATH:  /usr/lib
    *** LOOKING AT PATH:  /usr/local/lib
    *** LOOKING AT PATH:  /usr/local/lib64
    *** LOOKING AT PATH:  /usr/local/lua
    *** LOOKING AT PATH:  /usr/local/liblua
    *** LOOKING AT PATH:  /usr/local
    *** LOOKING AT PATH:  /opt
    *** LOOKING AT PATH:  /usr
    *** LOOKING AT PATH:  /usr/lib64
    *** LOOKING AT PATH:  /opt/local
    configure: LUA library was not found
    checking for libcurl config script... /usr/bin/curl-config
    ./configure: line 5918: test: : integer expression expected
    ./configure: line 5921: test: : integer expression expected
    ./configure: line 5924: test: : integer expression expected
    checking if libcurl is at least v... yes, 7.38.0
    checking if libcurl is linked with gnutls... no
    configure: using curl v7.38.0
    checking for libxml2 config script... no
    configure: *** libxml2 library not found.
    checking for libpcre config script... /usr/bin/pcre-config
    ./configure: line 6174: test: : integer expression expected
    ./configure: line 6177: test: : integer expression expected
    ./configure: line 6180: test: : integer expression expected
    ./configure: line 6183: test: : integer expression expected
    checking for PCRE JIT... yes
    configure: using pcre v8.35
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking string usability... no
    checking string presence... no
    checking for string... no
    checking iostream usability... no
    checking iostream presence... no
    checking for iostream... no
    checking sys/utsname.h usability... yes
    checking sys/utsname.h presence... yes
    checking for sys/utsname.h... yes
    ./configure: line 6690: syntax error near unexpected token `dlopen'
    ./configure: line 6690: `LT_INIT(dlopen)'

**Comment by felipee07** [comment]
Delete repo and start over. Did you install pkg-config ? dpkg -l pkg-config

/.build.sh
./configure
make
make install

**Comment by arash-rais** [comment]
Thanks it works, my file build.sh had problem while executing.

**Comment by zimmerle** [comment]
@felipee07  meant:

./build.sh
