### ISSUE TITLE
Upgrading from v3.0.0-rc1 to v3.0.0 cause major slow down in Nginx and 100% CPU

### ISSUE THREAD

**Issue by swdee** [SpiderLabs/ModSecurity#1682]
We have been running v3.0.0-rc1 for a several months successfully.  Today we upgraded to v3.0.0 and upon installation it makes Nginx become rather slow and unresponsive.

Under "rc1"  requesting a small CSS file loads in milliseconds, but when switching out to v3.0.0 Nginx takes around 20 seconds to serve this file.  CPU usage for the Nginx process jumps to 100%, but under "rc1" it is 1.3% CPU.

Nothing in error logs indicate a problem and I am not sure how to go about debugging this further?  What do you need me to provide to give you useful data to problem solve this?

**Comment by swdee** [comment]
Is the a regression in v3.0.0 as this closed ticket #1641 suggests 100% CPU issues that are fixed in master and look to be targeted for a v3.0.1 release?

**Comment by zimmerle** [comment]
Please upgrade to the most recent version on v3/master. This fix will be in v3.0.1
