### ISSUE TITLE
No mod_security2.so created after installation

### ISSUE THREAD

**Issue by ASchwad** [SpiderLabs/ModSecurity#1684]
Hey there,

i tried to install ModSecurity to my CentOS7 Apache following the instructions in the compilation recipes from elialum (#1039).
The libraries got installed successfully but the module mod_security2.so has not been installed in the httpd/modules... Libraries have been installed in: /usr/local/modsecurity/lib

previously i installed modSecurity via yum without any issues, but i wanted to update to access the 3.0 OWASP CRS.

What am i doing wrong? Am i installing at the wrong place?

Thanks in advance!
Alex

**Comment by felipee07** [comment]
@ASchwad 

This guide was design for LibModSecurity v3. If you want version v2 you could just apt-get install libapache2-mod-security2.

**Comment by zimmerle** [comment]
Hi @ASchwad,

Currently we support two different major versions of ModSecurity: Family 3.x and 2.x; We recommend the version 2 to our Apache users:
https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.2
