### ISSUE TITLE
modesecurity 2.9.1 - Apache core dump

### ISSUE THREAD

**Issue by modsupport** [SpiderLabs/ModSecurity#1686]
Hi Team,

We are using modsecurity version 2.9.1 with Apache version httpd-2.2.15-60

Apache config
==========
# /etc/httpd/conf/httpd.conf
LoadModule security2_module modules/mod_security2.so

Receiving below error message while starting the Apache service

# /etc/init./httpd start

Starting httpd: /bin/bash: line 1:   989 Illegal instruction     /usr/sbin/httpd

Mod sec Config
===========
# /etc/httpd/conf.d/modsecurity.conf

SecRemoteRules < KEY> https://dashboard.modsecurity.org/rules/download/plain

apache works fine if i hash above SecRemoteRules line.

**Comment by victorhora** [comment]
Can you provide more information on this error? Which distro are you using? 

I'm aware that some old distros (e.g. RHEL 6) ships Apache 2.2.x without apr_crypto support which is mandatory for the SecRemoteRules functionality. This could lead to the issue you are experiencing.

Maybe you can try upgrading to Apache 2.4 and / or ModSec 2.9.2.

**Comment by modsupport** [comment]
SecRemoteRules was working fine for RHEL 6.5, we upgraded it to RHEL 6.8 and it was also working fine. But after some weeks, we received below error message while starting the service on same server.

#/etc/init./httpd start
Starting httpd: /bin/bash: line 1: 989 Illegal instruction   Ccore dumped) /usr/sbin/httpd

Recently, we got the new license key to download the rules but still same above problem persists while starting the service.

# uname -m
x86_64

# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.8 (Santiago)

# RPMS
httpd-2.2.15-60.el6_9.6.x86_64
httpd-devel-2.2.15-60.el6_9.6.x86_64

libgcc-4.4.7-18.el6.x86_64
gcc-4.4.7-18.el6.x86_64
make-3.81-23.el6.x86_64
libxml2-2.7.6-21.el6_8.1.x86_64
libxml2-devel-2.7.6-21.el6_8.1.x86_64
pcre-devel-7.8-7.el6.x86_64
libcurl-devel-7.19.7-53.el6_9.x86_64

Is there any way we can check the apr_crypto support is enabled or not for the SecRemoteRules functionality? Let me know if you need any more details.

Your help is greatly appreciated.

**Comment by zimmerle** [comment]
Hi @modsupport,

Is your ModSec custom compiled? if so, did you happens to compile it again after the upgrade?

**Comment by modsupport** [comment]
yes. but if you start the service (without enabling license key), it shows modsecurity 2.9.1 is configured and already mod_security2.so is present /etc/httpd/modules -> ../../usr/lib64/httpd/modules and it's enabled in http.conf file

LoadModule security2_module modules/mod_security2.so

#tail -f error_log
[notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[notice] ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/) configured.
[notice] ModSecurity: APR compiled version="1.3.9"; loaded version="1.3.9"
[notice] ModSecurity: PCRE compiled version="7.8 "; loaded version="7.8 2008-09-05"
[notice] ModSecurity: LIBXML compiled version="2.7.6"
[notice] ModSecurity: Status engine is currently disabled, enable it by set SecStatusEngine to On.
[notice] Digest: generating secret for digest authentication ...
[notice] Digest: done
[notice] Apache/2.2.15 (Unix) DAV/2 configured -- resuming normal operations

**Comment by victorhora** [comment]
If you try to recompile again, does your configure script outputs something similar to this:

<pre>
checking for libcurl config script... /usr/bin/curl-config
checking if libcurl is at least v... yes, 7.47.0
checking if libcurl is linked with gnutls... no
configure: using curl v7.47.0
configure: looking for Apache module support via DSO through APXS
configure: found apxs at /usr/bin/apxs2
configure: checking httpd version
configure: httpd is recent enough
checking for libpcre config script... /usr/bin/pcre-config
configure: using pcre v8.38
checking for libapr config script... /usr/bin/apr-1-config
configure: using apr v1.5.2
checking for libapu config script... /usr/bin/apu-1-config
configure: using apu v1.5.4
</pre>

Does it finds all the required dependencies including the ones required for SecRemoteRules (libcURL)?

Can you also test with [2.9.2](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.2) or the current [master/v2](https://github.com/SpiderLabs/ModSecurity/tree/v2/master) branch to see if the issue still happens?

**Comment by modsupport** [comment]
Please see the compile logs for v.2.9.1

# ./configure --prefix=/root/tmp/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... yes
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gawk... (cached) gawk
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for perl... /usr/bin/perl
checking for env... /bin/env
checking for ANSI C header files... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for C/C++ restrict keyword... __restrict
checking for pid_t... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working memcmp... yes
checking for atexit... yes
checking for getcwd... yes
checking for memmove... yes
checking for memset... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking for fchmod... yes
checking for strcasestr... yes
Checking platform... Identified as Linux
checking for libcurl config script... /usr/bin/curl-config
./configure: line 13855: test: : integer expression expected
./configure: line 13858: test: : integer expression expected
./configure: line 13861: test: : integer expression expected
checking if libcurl is at least v... yes, 7.19.7
checking if libcurl is linked with gnutls... no
configure: using curl v7.19.7
configure: looking for Apache module support via DSO through APXS
configure: found apxs at /usr/sbin/apxs
configure: checking httpd version
configure: httpd is recent enough
checking for libpcre config script... /usr/bin/pcre-config
configure: using pcre v7.8
checking for libapr config script... /usr/bin/apr-1-config
configure: using apr v1.3.9
checking for libapu config script... /usr/bin/apu-1-config
configure: using apu v1.3.9
checking for libxml2 config script... /usr/bin/xml2-config
checking if libxml2 is at least v2.6.29... yes, 2.7.6
configure: using libxml2 v2.7.6
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for liblua config script... no
checking for lua install... no
configure: optional lua library not found
checking for libyajl config script... no
checking for yajl install... no
configure: optional yajl library not found
checking for ssdeep path... no
configure: optional ssdeep library not found
configure: WARNING: APR util was not compiled with crypto support. SecRemoteRule will not support the parameter 'crypto'
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tools/Makefile
config.status: creating apache2/Makefile
config.status: creating build/apxs-wrapper
config.status: creating mlogc/mlogc-batch-load.pl
config.status: creating tests/regression/misc/40-secRemoteRules.t
config.status: creating tests/regression/misc/50-ipmatchfromfile-external.t
config.status: creating tests/regression/misc/60-pmfromfile-external.t
config.status: creating tests/run-unit-tests.pl
config.status: creating tests/run-regression-tests.pl
config.status: creating tests/gen_rx-pm.pl
config.status: creating tests/csv_rx-pm.pl
config.status: creating tests/regression/server_root/conf/httpd.conf
config.status: creating tools/rules-updater.pl
config.status: creating mlogc/Makefile
config.status: creating tests/Makefile
config.status: creating apache2/modsecurity_config_auto.h
config.status: executing depfiles commands
config.status: executing libtool commands

after make and make install command ....it install the libary mod_security2.so under /root/tmp/lib which we have copied in /etc/httpd/moudles --->/usr/lib64/httpd/modules 

after starting the service ( by enabling the licences key), it gives the same error message.
 # /etc/init.d/httpd restart
Stopping httpd:                                            [  OK  ]
Starting httpd: /bin/bash: line 1:  6373 Illegal instruction     /usr/sbin/httpd                                                          [FAILED]

I will try to compile/test with 2.9.2 and share you the result.

**Comment by modsupport** [comment]
I complied modsecurity version 2.9.2 and tried to start the service by enabling licence key but it gives similar error message.

# modsecurity.conf
SecRemoteRules  <KEY> https://dashboard.modsecurity.org/rules/download/plain

# http.conf
LoadModule security2_module modules/mod_security2.so

#  /etc/init.d/httpd restart
Stopping httpd:                                            [  OK  ]
Starting httpd: /bin/bash: line 1: 13721 Illegal instruction     /usr/sbin/httpd
                                                           [FAILED]

Kindly help us to resolve this issue.

**Comment by victorhora** [comment]
<pre>
configure: WARNING: APR util was not compiled with crypto support. SecRemoteRule will not support the parameter 'crypto'
</pre>

This output from your configure script tells that apr crypto is not supported on your setup. But thinking again, if you're not using the parameter "crypto" on your SecRemoteRules it shouldn't lead to a crash.

Please check if debug logs from ModSecurity and Apache provides any clues

**Comment by victorhora** [comment]
@modsupport it seem like you're using a quite old version of Apache (2.2.15-2010). Can you try with the latest release ([2.2.34](https://archive.apache.org/dist/httpd/httpd-2.2.34.tar.bz2))?

You might also consider upgrading to Apache 2.4.x as 2.2.x is officially [end of life](https://httpd.apache.org/) since January.

If the issue persists, let us know.
