### ISSUE TITLE
Uploads of a particular format not allowed in Mod security with Nginx

### ISSUE THREAD

**Issue by NisariAIT** [SpiderLabs/ModSecurity#1688]
I am using modsecurity with nginx(v1.13.6) on ubuntu 16.04. When I try to upload a jpeg image via an API to my web server, I get the following error in the modsecurity error log.

ModSecurity: Multipart parsing error: Multipart: Invalid Content-Disposition header (-12): form-data; name="file1"; filename="aaa.jpeg"". [hostname ""] [uri "/api/upload"] [unique_id "AcAcCcAcAcVKAcAjAczcmlAc"]
2018/02/27 13:01:06 [error] 21549#0: [client 103.92.19.39] ModSecurity: Access denied with code 400 (phase 2). Match of "eq 0" against "MULTIPART_STRICT_ERROR" required. [file "/usr/local/nginx/conf/modsecurity.conf"] [line "81"] [id "200003"] [msg "Multipart request body failed strict validation: PE 1, BQ 0, BW 0, DB 0, DA 0, HF 0, LF 0, SM 0, IQ 1, IP 0, IH 0, FL 0"] [hostname ""] [uri "/api/upload"] [unique_id "AcAcCcAcAcVKAcAjAczcmlAc"]
2018/02/27 13:01:06 [error] 21549#0: [client 103.92.19.39] ModSecurity: Audit log: Failed to lock global mutex: Permission denied [hostname ""] [uri "/api/upload"] [unique_id "AcAcCcAcAcVKAcAjAczcmlAc"]
2018/02/27 13:01:06 [error] 21549#0: [client 103.92.19.39] ModSecurity: Audit log: Failed to unlock global mutex: Permission denied [hostname ""] [uri "/api/upload"] [unique_id "AcAcCcAcAcVKAcAjAczcmlAc"]

I get the following as the response from the server.

02-27 18:18:52.590 3721-4870/com.org D/OkHttp: <-- 400 Bad Request https://mydomain.com/api/upload (1004ms)
02-27 18:18:52.590 3721-4870/com.org D/OkHttp: Server: nginx/1.10.3
02-27 18:18:52.590 3721-4870/com.org D/OkHttp: Date: Tue, 27 Feb 2018 12:49:10 GMT
02-27 18:18:52.590 3721-4870/com.org D/OkHttp: Content-Length: 173
02-27 18:18:52.590 3721-4870/com.org D/OkHttp: Connection: close
02-27 18:18:52.590 3721-4870/com.org D/OkHttp: Content-Type: text/html
02-27 18:18:52.590 3721-4870/com.org D/OkHttp: Content-Length: 173
02-27 18:18:52.590 3721-4870/com.org D/OkHttp: Connection: close
02-27 18:18:52.592 3721-4870/com.org D/OkHttp: <html>
02-27 18:18:52.592 3721-4870/com.org D/OkHttp: <head><title>400 Bad Request</title></head>
02-27 18:18:52.592 3721-4870/com.org D/OkHttp: <body bgcolor="white">
02-27 18:18:52.592 3721-4870/com.org D/OkHttp: <center><h1>400 Bad Request</h1></center>
02-27 18:18:52.592 3721-4870/com.org D/OkHttp: <hr><center>nginx/1.10.3</center>
02-27 18:18:52.592 3721-4870/com.org D/OkHttp: </body>
02-27 18:18:52.592 3721-4870/com.org D/OkHttp: </html>
02-27 18:18:52.592 3721-4870/com.org D/OkHttp: <-- END HTTP (173-byte body)
 
Is there any way to write a rule that allows all the requests that has a particular field set in the request header so that it is not an anomaly to the OWASP rules and is not blocked at the server's firewall? Or what else can be done to overcome this error? Any help would be greatly appreciated.

**Comment by csanders-git** [comment]
Yes it is. To clarify this is not a problem with owssp  rules but rather the rule suggested in modsec.conf.reccomended. which are sane defaults provided by modsecurity. Since it is in a file that won't be clobbered by updates it's fine to change this file.

You could make this a chained rule such that it only matches if it doesn't meet a regex (free handing the following on mobile but you should get the idea)

```
Secrule request_uri "!@rx /test/potato/" "I'd:1, block, chain"
   Secrule MULTIPART_STRICT_ERROR "@eq 1" "t:none"


The only thing to remember is , in this case since there are no transforms all the actions (message tags etc) go in the first secrule in the chain.

It is also possible to disable a certain rule of a previous rule triggers using the ctl action but in this case there is no real need

**Comment by NisariAIT** [comment]
Thanks for the clarification. I am new to modsecurity. So, where should I add the Rule to check the request_uri? I added it to the file at /usr/local/nginx/conf/modsecurity.conf. This is the modified rule. But, I get syntax errors when I restart nginx. How should the syntax be and is this the correct place that the chained rule should be added?
SecRule REQBODY_ERROR "!@eq 0" chain  request_uri "!@rx /api/upload/" \
"id:'200002', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"
