### ISSUE TITLE
Make MD5 or SHA from file upload

### ISSUE THREAD

**Issue by makitos666** [SpiderLabs/ModSecurity#1689]
I'm trying to get all the files that are uploaded to my apache server saved in a log.

So far, with the basic configuration. I have the name of the file, its weight and other information.

Can you also save a file Hash in those logs?

Thank you!

**Comment by zimmerle** [comment]
do you want to have the hash in the error_log?

**Comment by makitos666** [comment]
While every time a file is sent, the hash appears, I do not care in which log file is stored

**Comment by zimmerle** [comment]
This may be helpful for you: 

```
SecUploadKeepFiles On
SecUploadDir /tmp
SecRule FILES_TMP_CONTENT "." "id:1,phase:3,t:none,t:sha1,t:hexEncode"
```

**Comment by makitos666** [comment]
I suppose we are close, but in the error.log the hash does not appear

SecUploadDir /tmp
SecUploadKeepFiles On
SecRule FILES_TMP_CONTENT "." "id:1,phase:3,t:none,t:sha1,t:hexEncode"

error.log:
[Tue Feb 27 09:00:19.278339 2018] [:error] [pid 1181] [client 192.168.86.1] ModSecurity: Warning. Pattern match "." at FILES_TMP_CONTENT:uploaded. [file "/etc/modsecurity/modsecurity.conf"] [line "160"] [id "1"] [hostname "192.168.86.136"] [uri "/DVWA/vulnerabilities/upload/index.php"] [unique_id "WpWOo38AAQEAAASdgKIAAAAB"]

**Comment by victorhora** [comment]
@makitos666  Have you tried looking in the [audit_log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLog) or [debug_log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDebugLog)?
