### ISSUE TITLE
Unable to work with ModSecurity V3 in Centos7

### ISSUE THREAD

**Issue by le0li9ht** [SpiderLabs/ModSecurity#1692]
Hi,

I'm using the centos7 httpd 2.4.29 version with php7.0 installed. I installed ModSecurity V3 from source. Then I tried to install the Modsecurity-apache connector but i failed to do so using make and make install commands. But the compilation generated `security3_module.so` file which I have moved to
>  /etc/httpd/modules

After enabling the module 
```

LoadModule security3_module modules/mod_security3.so
<IfModule security3_module>
               Include modsecurity.d/owasp-modsecurity-crs/crs-setup.conf
              Include modsecurity.d/owasp-modsecurity-crs/rules/*.conf
</IfModule>

```

But then I'm getting the following error.  
```

[root@103 modules]# httpd -t
AH00526: Syntax error on line 95 of /etc/httpd/modsecurity.d/owasp-modsecurity-crs/crs-setup.conf:
Invalid command 'SecDefaultAction', perhaps misspelled or defined by a module not included in the server configuration

```

**Comment by zimmerle** [comment]
@le0li9ht v3 works differently on Apache, ModSecurity rules should be placed into a `modsecurity_rules` block like the following:

```
 'SecRule ARGS "evil" "phase:3,id:113,log,status:402,block,deny"'
```
