### ISSUE TITLE
missing rule_message structure for c api

### ISSUE THREAD

**Issue by merdang** [SpiderLabs/ModSecurity#1695]
how i can use rule_message structure in c, there is rule_message class for c++, but no eligibility for use it in c code. @zimmerle

**Comment by zimmerle** [comment]
Indeed @merdang. The Rule message is only available for the C++ API. C api most rely on the simple log message. Are you working in a opensource project?

**Comment by merdang** [comment]
no, I'm just testing callback function in C. I saw your Apache and nginx connectors' code, and realized that you use just simple const char* to log in callback function. In your test cases with c there is no callback function test :) thanks for your reply :)
