### ISSUE TITLE
ModSec v3 verifyCC operator doesn't capture

### ISSUE THREAD

**Issue by michaelgranzow-avi** [SpiderLabs/ModSecurity#1698]
According to the reference manual (https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#verifycc) explanation of operator verifyCC: "This operator supports the "capture" action."

However, the code in VerifyCC::evaluate() never stores the matched variables in the TX collection, whether or not "capture" is in the action list of the rule.

**Comment by zimmerle** [comment]
Fixed at: 70ace0faa4fe274eafbeb06465e89c2ab459e553. Thanks
