### ISSUE TITLE
LibModSecurity + Nginx + ClamAV

### ISSUE THREAD

**Issue by nekromantik** [SpiderLabs/ModSecurity#1699]
Hi all
Using latest version of ModSecuity and nginx connector.
However even in debug level 9 it still wont show me what issue is.

I have a rule below:
`SecRule FILES_TMPNAMES "@inspectFile /usr/local/nginx/sbin/test.lua" "phase:2,t:none,log,deny,msg:'Malicous File Attachment Identified.',id:99999"`

And in modsec settings I have enabled secresponsebody and following:
`SecTmpSaveUploadedFiles On
            SecUploadDir /usr/local/nginx/tmp
            SecUploadKeepFiles On
            SecUploadFileMode 0777
`
I have a test php page to upload a file to nginx server but even with test virus it does not pick anything up. Here is debug log:
https://pastebin.com/GjdXM3yF

and here is the lua script

https://gist.github.com/angeloxx/97714f9108b3642460564acdcd37b34a

thanks

**Comment by zimmerle** [comment]
Hi @nekromantik,

According to your debuglog, the rule id 99999 is pointing towards: `/usr/local/nginx/sbin/runav.pl` not yours Lua script. As highlighted here:

```
(...)
[9] Skipped rule id '0' due to a SecMarker: END-RESPONSE-980-CORRELATION
[9] Rule: END-RESPONSE-980-CORRELATION
[4] Out of a SecMarker after skip 3.000000 rules.
[4] (Rule: 99999) Executing operator "InspectFile" with param "/usr/local/nginx/sbin/runav.pl" against FILES_TMPNAMES.
[4] Rule returned 0.
[9] Matched vars cleaned.
(...)
```

**Comment by nekromantik** [comment]
@zimmerle Sorry forgot to get correct logging but we get the same exact returned 0 with no additional errors or messages. I can get you correct log but it wont show you anything different which is what is throwing me off. Do you want the correct log?

**Comment by victorhora** [comment]
@nekromantik even though the issue was closed you can still interact with it. Please share the correct logs so we can confirm if there's an issue.

Reopening for now.

**Comment by nekromantik** [comment]
@victorhora 
Here is debug log:
https://pastebin.com/5GW0La0W

and here is the lua script which I have renamed to clam.lua

https://gist.github.com/angeloxx/97714f9108b3642460564acdcd37b34a

**Comment by victorhora** [comment]
@nekromantik I could run Lua scripts with the latest codebase of libModSecurity and Nginx connector. This is what I see on the debug logs:

```
[4] (Rule: 345) Executing operator "InspectFile" with param "/usr/local/nginx/conf/match-log.lua" against ARGS:res.
[9]  T (0) t:trim: "whee"
[9] Target value: "whee" (Variable: ARGS:res)
[9] echo 123
[9] Returning from lua script: Lua script matched.
...
[4] Rule returned 1.
```

I ran the following Lua script:

```
function main()
    m.log(9, "echo 123");
    return "Lua script matched.";
end
```

Against the following rule:

```
SecRule ARGS:res "@inspectFile /usr/local/nginx/conf/match-log.lua" "id:345,phase:2,log,auditlog,deny,status:403,t:none,t:trim"
```

You may also want to try running the Lua script with the [SecRuleScript](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleScript) directive. If Lua support is not enabled or if you have syntax errors you should see something like the following:

```
/usr/local/nginx/conf/match-log.lua: 1: /usr/local/nginx/conf/match-log.lua: Syntax error: "(" unexpected
2018/03/10 13:12:33 [emerg] 36687#0: "modsecurity_rules_file" directive Rules error. File: /usr/local/nginx/conf/modsecurity.conf. Line: 390. Column: 155. Failed to load script: Lua support was not enabled.  in /usr/local/nginx/conf/nginx.conf:24
```
Ensure that LUA support is enabled on your environment. You should see something like the following on the output of the ./configure script:

```
...
configure: LUA library found at: /usr/lib/x86_64-linux-gnu//liblua5.3.so
configure: LUA headers found at: /usr/include/lua5.3
configure: LUA version from includes: 503
configure: using LUA -llua5.3
...

ModSecurity - v3.0.0-55-g70ace0f for Linux

 Optional dependencies
   + LUA                                           ....found v503
      -llua5.3 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -I/usr/include/lua5.3
```

Depending on your distro you might a package named liblua5.3-0-dev or similar. LUA 5.2+ is required. Optionally you may install Lua from sources.

**Comment by nekromantik** [comment]
@victorhora I can run lua scripts on the command line without ModSec. We are using clam 5.3 on centos

**Comment by victorhora** [comment]
@nekromantik have you ensured that LUA support is enabled on your ModSecurity by following/confirming the steps described? 

I suggest you make sure you can run a simple LUA script from ModSecurity first to then try running your LUA script that calls ClamAV.

**Comment by kadirerdogan** [comment]
@victorhora this issue should be reopened and it's a modsecurity bug in lua engine. The problem occurs because current implementation (v3) of the inspectFile operator does not pass FILES_TMPNAMES parameter to lua engine.


```
bool InspectFile::evaluate(Transaction *transaction, const std::string &str) {
    if (m_isScript) {
        return m_lua.run(transaction); 
    } else {
    ...
```
This function should pass "str" parameter to lua engine as ``` return m_lua.run(transaction,str);```
And also there should be some changes in **src/engine/lua.h** and **src/engine/lua.cc** file accordingly. The fix should not effect other script calls like **exec** action


Modsecurity v2 does not hit this problem so i have used a similar method to fix the bug in v3. I am planning to make a pull request. 

I have tested the fix for below rules with below lua scripts and it works as intended
```
SecRule FILES_TMPNAMES "@inspectFile /usr/local/nginx/scanfile.lua" "id:1001,phase:2,t:none,log,auditlog,deny"
  
SecRule REQUEST_METHOD "@streq POST" "id:1002,exec:/usr/local/nginx/luatest.lua"
```
luatest.lua:
```
function main()
        m.log(1,"modsec lua exec action test ");
end
```
scanfile.lua:
```
function fsize(filename)
   file = io.open(filename,"r")
   local current = file:seek()
   local size = file:seek("end")
   file:seek("set",current)
   file:close()
   return size
end

function main(filename)

        m.log(1,"Inspection for "..filename);

   -- Configure paths
   local clamdscan  = "/usr/bin/clamdscan"
   local clamscan  = "/usr/bin/clamscan"

   -- failoverOnClamdFailure: failover to clamscan if clamdscan report an error
   local failoverOnClamdFailure = true

   -- fail (and block) if clamdscan (and clamscan) fails
   local failOnError = false

   -- local var
   local agent = "clamdscan"

   -- Skip empty items because if clamd is not working and you
   -- use the clamscan agent an empty file can take about 12 secs 
   -- to be analyzed
   if fsize(filename) == 0 then
     m.log(1, "[scanav skipped, file " .. filename .." size is zero]")
     return nil
   end

   -- The system command we want to call with fdpass flag to 
   -- do not incur in a permission issue
   local cmd = clamdscan .. " --fdpass --stdout --no-summary"

   -- Run the command and get the output
   local f = io.popen(cmd .. " " .. filename .. " || true")
   local l = f:read("*a")
   f:close()

   -- Check the output for the FOUND or ERROR strings which indicate
   -- an issue we want to block access on
   local isVuln = string.find(l, "FOUND")
   local isError = string.find(l, "ERROR")
  -- If clamdscan fails and you want failover to the traditional clamscan...
   if isError and failoverOnClamdFailure then
     -- Try to use the clamscan program
     m.log(1, "[clamdscan fails (" .. l .. "), failover to clamscan]")
     agent = "clamscan"
     cmd = clamscan .. " --stdout --no-summary"
     f = io.popen(cmd .. " " .. filename .. " || true")
     l = f:read("*a")
     f:close()
     isVuln = string.find(l, "FOUND")
     isError = string.find(l, "ERROR")
   end

   if isVuln then
     m.log(1, "[" .. agent .. " scanner message: " .. l .. "]\n")
     return "Virus Detected"
   elseif isError and failOnError then
     -- is a error (not a virus) a failure event?
     m.log(1, "[" .. agent .. " scanner message: " .. l .. "]\n")
     return "Error Detected"
   else
     return nil
   end
end

```

virussample.txt
```
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
```
