### ISSUE TITLE
libmodsecurity + nginx + inspectfile clamav

### ISSUE THREAD

**Issue by nekromantik** [SpiderLabs/ModSecurity#1700]
Hi all
Using latest version of ModSecuity and nginx connector.
However even in debug level 9 it still wont show me what issue is.

I have a rule below:
SecRule FILES_TMPNAMES "@inspectFile /usr/local/nginx/sbin/clam.lua" "phase:2,t:none,log,deny,msg:'Malicous File Attachment Identified.',id:99999"

And in modsec settings I have enabled secresponsebody and following:
SecTmpSaveUploadedFiles On SecUploadDir /usr/local/nginx/tmp SecUploadKeepFiles On SecUploadFileMode 0777
I have a test php page to upload a file to nginx server but even with test virus it does not pick anything up. Here is debug log:
https://pastebin.com/5GW0La0W

and here is the lua script which I have renamed to clam.lua

https://gist.github.com/angeloxx/97714f9108b3642460564acdcd37b34a

thanks

**Comment by victorhora** [comment]
Duplicate with #1699.
