### ISSUE TITLE
REQUEST-920-PROTOCOL-ENFORCEMENT : Expecting a variable, got:  :  MULTIPART_SEMICOLON_MISSING

### ISSUE THREAD

**Issue by stevepaul-alonso** [SpiderLabs/ModSecurity#1704]
owasp-modsecurity-crs-3.0.2/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf. Line: 169. Column: 390. Expecting a variable, got:  :  MULTIPART_SEMICOLON_MISSING

Got this error message when reloading nginx with modsecurity3. 
nginx version - 1.13.9

**Comment by csanders-git** [comment]
See the following ticket https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1021

**Comment by victorhora** [comment]
This a known issue @stevepaul-alonso. Follow @csanders-git comment and also see #1701 if you need more information.

**Comment by stevepaul-alonso** [comment]
I got it fixed. Thank you very much.
