### ISSUE TITLE
The number of mlogc processes does not equal to its configuration

### ISSUE THREAD

**Issue by BAOLONGtrann** [SpiderLabs/ModSecurity#1707]
Dear,
When using mlogc, I found this isssue:
- In file mlog.conf, I configured maximum_connections as 10 (I expected the number of mlogc processes is not over 10)
- However, when I run mlogc with httpd+modsec, I found that the total mlogc processes is 123

What is wrong with config maximum_connections? And how can I control the number of mlogc processes?

**Comment by victorhora** [comment]
@BAOLONGtrann I couldn't reproduce this issue. As soon as you launch httpd you see a spike in mlogc PIDs?

Could you share your mlogc.conf configuration and mlogc-error.log?

**Comment by BAOLONGtrann** [comment]
I've reprocedured this issue as following:
- Step1: restart apache (with graceful)
- Step2: Count mlogc processes by command "ps -ef|grep mlogc|wc -l". It give the result 58 processes of mlogc:
[root@localhost mlogc]# ps -ef|grep mlogc|wc -l
58
[root@localhost mlogc]# ps -ef|grep mlogc
root     43888 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43889 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43890 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43891 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43892 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43893 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43894 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43895 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43896 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43897 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43898 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43899 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43900 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43901 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43902 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43903 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43904 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43905 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43906 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43907 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43908 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43909 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43910 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43911 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43912 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43913 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43914 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43915 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43916 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43917 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43918 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43919 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43920 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43921 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43922 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43923 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43924 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43925 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43926 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43927 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43928 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43929 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43930 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43941 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43948 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43953 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43960 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43965 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43972 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43975 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43982 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43987 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     43990 12509  1 10:34 ?        00:00:02 /usr/local/bin/mlogc /etc/mlogc.conf
root     43997 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     44000 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     44007 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     44012 12509  0 10:34 ?        00:00:00 /usr/local/bin/mlogc /etc/mlogc.conf
root     46218 41169  0 10:37 pts/1    00:00:00 grep mlogc

**Comment by BAOLONGtrann** [comment]
My mlogc config as following:
# How many concurrent connections to the server
# are we allowed to open at the same time? Log collector uses
# multiple connections in order to speed up audit log transfer.
# This is especially needed when the communication takes place
# over a slow link (e.g. not over a LAN).
MaxConnections      10

# How many requests a worker will process before recycling itself.
# This is to help prevent problems due to any memory leaks that may
# exists.  If this is set to 0, then no maximum is imposed. The default
# is 1000 requests per worker (the number of workers is controlled by the
# MaxConnections limit).
MaxWorkerRequests   1000

**Comment by BAOLONGtrann** [comment]
PS: I also logging to error log to debug the number of current_workers when creating and deleting a thread. It give the result current_workers less than 10. I don't understand. If current_thread is less than 10, why the number pid of mlogc processes is much more than 10. My mlogc-error-log as following:

[Thu Mar 15 10:38:09 2018] [1] [43990/0] Delete worker with current_workers=6, max_connections=10, thread=16fe400
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Delete worker with current_workers=5, max_connections=10, thread=16fe370
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Delete worker with current_workers=4, max_connections=10, thread=16fe520
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Delete worker with current_workers=3, max_connections=10, thread=16fe760
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Creating new worker0 with current_workers=2, max_connections=10
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Worker creation completed: 16fe910
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Creating new worker0 with current_workers=3, max_connections=10
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Worker creation completed: 16fe9a0
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Creating new worker0 with current_workers=4, max_connections=10
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Worker creation completed: 16fea30
[Thu Mar 15 10:38:09 2018] [1] [43990/0] Creating new worker0 with current_workers=5, max_connections=10

**Comment by victorhora** [comment]
@BAOLONGtrann Which version of ModSecurity / MlogC you're running?

**Comment by BAOLONGtrann** [comment]
@victorhora I use modsec at version 2.9.0

**Comment by victorhora** [comment]
Try upgrading to 2.9.2. Or better yet, try the latest codebase from [master](https://github.com/SpiderLabs/ModSecurity/tree/v2/master).

If the problem persists let us know and we can reopen the issue and investigate further.
