### ISSUE TITLE
make: "/rootModSecurity/Makefile" line 3101: Missing dependency operator

### ISSUE THREAD

**Issue by bryn1u** [SpiderLabs/ModSecurity#1708]
Hello guys,

Im trying to install ModSec but im getting error at the beginnig process some issue.
I did:

> [root@proton ~/build/ModSecurity]# ./build
> [root@proton ~/build/ModSecurity]# ./configure
> [root@proton ~/build/ModSecurity]# make
> make: "/root/build/ModSecurity/Makefile" line 3101: Missing dependency operator
> make: "/root/build/ModSecurity/Makefile" line 3103: Need an operator
> make: "/root/build/ModSecurity/Makefile" line 3105: Need an operator
> make: "/root/build/ModSecurity/Makefile" line 3109: Missing dependency operator
> make: "/root/build/ModSecurity/Makefile" line 3113: Need an operator
> make: "/root/build/ModSecurity/Makefile" line 3115: Need an operator
> make: "/root/build/ModSecurity/Makefile" line 3128: Need an operator
> make: "/root/build/ModSecurity/Makefile" line 3130: Error in archive specification: ""
> make: "/root/build/ModSecurity/Makefile" line 3135: warning: duplicate script for target "ifeq" ignored
> make: "/root/build/ModSecurity/Makefile" line 3112: warning: using previous script for "ifeq" defined here
> make: "/root/build/ModSecurity/Makefile" line 3136: Missing dependency operator
> make: "/root/build/ModSecurity/Makefile" line 3137: warning: duplicate script for target "ifeq" ignored
> make: "/root/build/ModSecurity/Makefile" line 3112: warning: using previous script for "ifeq" defined here
> make: "/root/build/ModSecurity/Makefile" line 3137: warning: duplicate script for target "(no,yes)" ignored
> make: "/root/build/ModSecurity/Makefile" line 3112: warning: using previous script for "(no,yes)" defined here
> make: "/root/build/ModSecurity/Makefile" line 3138: Need an operator
> make: "/root/build/ModSecurity/Makefile" line 3140: Need an operator
> make: "/root/build/ModSecurity/Makefile" line 3141: Need an operator
> make: "/root/build/ModSecurity/Makefile" line 3143: Need an operator
> make: Fatal errors encountered -- cannot continue
> make: stopped in /root/build/ModSecurity
> [root@proton ~/build/ModSecurity]# 

What am i doing wrong ?
Thank you.

**Comment by victorhora** [comment]
It seems like you're either missing some dependencies (e.g. automake / autoconf) or the build / configure script failed to run successfully. 

Try following the compilation recipes here: https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes
