### ISSUE TITLE
Best practices to reduce ModSecurity 3.0 Library size

### ISSUE THREAD

**Issue by binaryanomaly** [SpiderLabs/ModSecurity#1710]
Hi,

I have added ModSecurity 3.0 to nginx according to this guide https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/ which worked fine so far.
I use a docker multi-stage build to separate build overhead from the final container image to keep the final container size small and portable. Still ModSecurity makes the container size growing by magnitudes.
/usr/local/modsecurity ends up being around 236 MB
Additionally I need to install libgeoip1 libxml2 liblmdb0 libyajl2 which adds on top.

Are there any best practices, recommended compilation flags, etc. to reduce the size occupied by ModSecurity in a lean container scenario?

Thanks.

**Comment by csanders-git** [comment]
You can always base it on a smaller distro like scratch. If you share your Dockerfile, we'd be more than willing to use it as a base on our dockerhub and allow the community to try and drive down the size.

**Comment by binaryanomaly** [comment]
I use debian:stretch-slim which is pretty small and definitely not the cause here. I was around 75MB with the final container before adding ModSecurity and am now around 430 MB.

I can share my docker image tomorrow - have to clean it up a bit first as it's totally work in progress right now.

**Comment by victorhora** [comment]
@binaryanomaly have you tried stripping the binary symbols with the [strip utility from GNU BinUtils](https://linux.die.net/man/1/strip)?

On a quick run here I've managed to reduce the file lib sizes from ~170Mb down to ~4.9MB.
You may also try disable building / installing the lib examples, test utilities and docs to see what you get.

There's a few other tricks you can try to reduce the overall size of binaries and your Docker images. I had good results in the past with binary packer compression tools like [UPX](https://upx.github.io/). I'm not sure how well or if it actually works for libs, but you can give it a try and let us know :)

**Comment by binaryanomaly** [comment]
Thanks @victorhora that already helped to cut down the container size significantly from 430mb to 190mb! With a few more optimizations I'm now down to around 120mb which is okish.
Around 50mb alone is from libgeoip1 libxml2 liblmdb0 libyajl2, suppose I could cut that down by building the libraries from source and not using the distro ones but that is a bit tedious.

If there's interest I can share my dockerfile but it's still a mess right now.

**Comment by csanders-git** [comment]
tjere os omterest!

**Comment by binaryanomaly** [comment]
Then here you go:
https://gist.github.com/binaryanomaly/3f04758d6bd2a26f018fce2d05def9be

It should work in the current condition but is still messy as I'm in progress of trying to find the sweet spot between maintainability and small image size. In its current state the container created is 120mb.

**Comment by victorhora** [comment]
@binaryanomaly this pull request might also help with getting a smaller container if that's what you're looking for:

https://github.com/CRS-support/modsecurity-docker/pull/4

On a quick test here I managed to get a container with ~12MB (as opposed to ~300MB) :)

**Comment by binaryanomaly** [comment]
Thanks. I'm more Team Debian/nginx though 😂
I'm not obsessed with container size 50-70mb is well ok, just not 500mb.

**Comment by binaryanomaly** [comment]
Btw. I have replaced the Dockerfile with a what I think better version. ModSecurity build an and nginx are separated now and it's overall cleaner and more consolidated: https://gist.github.com/binaryanomaly/3f04758d6bd2a26f018fce2d05def9be
