### ISSUE TITLE
Apache + ModSecurity 2.9.1 Memory leak issue

### ISSUE THREAD

**Issue by truman-test** [SpiderLabs/ModSecurity#1718]
Hello Team
Memory leak issue during operation. I would like to ask you if there is anything reported.
(In addition, graceful is used for operation and distribution of apache.)

# OS
CentOS release 6.8 (Final)

# Apache (httpd-2.4.10-include-apr.tar.gz)
Server version: Apache/2.4.25 (Unix)
Server built:   Feb 14 2017 14:46:44
Server's Module Magic Number: 20120211:67
Server loaded:  APR 1.5.2, APR-UTIL 1.5.4
Compiled using: APR 1.5.2, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     worker
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/usr/local/apache2"
 -D SUEXEC_BIN="/usr/local/apache2/bin/suexec"
 -D DEFAULT_PIDLOG="logs/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

# Apache Configure
"./configure" \
"--prefix=/usr/local/apache2" \
"--with-included-apr" \
"--enable-proxy" \
"--enable-proxy-ajp" \
"--enable-proxy-http" \
"--enable-proxy-balancer" \
"--enable-dav" \
"--enable-rewrite" \
"--enable-deflate" \
"--enable-headers" \
"--enable-logio" \
"--enable-expires" \
"--enable-ssl" \
"--with-mpm=worker" \
"--enable-nonportable-atomics=yes" \
"$@"

# ModSecurity
modsecurity-2.9.1

# RPM
pcre-devel-7.8-7.el6.x86_64
zlib-devel-1.2.3-29.el6.x86_64
libxml2-devel-2.7.6-21.el6_8.1.x86_64
cmake-2.8.12.2-4.el6.x86_64
expat-devel-2.0.1-11.el6_2.x86_64
bzip2-1.0.5-7.el6_0.x86_64

# ModSecurity Conf
SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecRequestBodyLimit 3072
SecRequestBodyNoFilesLimit 3072
SecRequestBodyInMemoryLimit 3072
SecRequestBodyLimitAction ProcessPartial
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml null
SecResponseBodyLimit 4096
SecResponseBodyLimitAction ProcessPartial
SecAuditEngine On
SecRule REQUEST_URI "/server-status" "phase:1,id:1000,pass,nolog,ctl:ruleEngine=Off"
SecAuditLogParts ABCJFEZ
SecAuditLogType Serial
SecAuditLog "|/usr/bin/socat -b 61440 - UDP-SENDTO:10.20.255.10:8888"
SecAuditLogFormat JSON
SecArgumentSeparator &
SecCookieFormat 0
SecUnicodeMapFile unicode.mapping 20127

# Memory 
<img width="584" alt="2018-03-22 11 36 21" src="https://user-images.githubusercontent.com/26159198/37748018-5a1b22ae-2dc5-11e8-992a-84241cf701c9.png">

**Comment by zimmerle** [comment]
Hi @truman-test,

Thanks for the report. What happens to be the loaded rules?

**Comment by truman-test** [comment]
Hi @zimmerle , 
I'm only use ModSecurity to logging https traffic.
not loaded a separate rules

**Comment by zimmerle** [comment]
In that case, I believe you are facing a problem due to APR version mismatch. Make sure that the version loaded in run time is the same that you have used to compile your ModSecurity.

**Comment by truman-test** [comment]
@zimmerle 
apr version is the same apache loaded and compiled modsecurity
Is there anything I can check?

**Comment by zimmerle** [comment]
There are those initial lines in error logs that show ModSecurity startup info. Do you mind to paste it here? The lines that contains the dependencies and versions in the error log.
