### ISSUE TITLE
LocationMatch & SecRuleRemoveById vs ctl:ruleRemoveById

### ISSUE THREAD

**Issue by bitsofinfo** [SpiderLabs/ModSecurity#1722]
Modsec 2.9.2: 

Confused about the following, these two stanzas appear to have the exact same result:

```
SecRule REQUEST_FILENAME "@streq /cat" \
    "phase:2,nolog,pass,id:199,ctl:ruleRemoveById=950005"
```

OR

```
<LocationMatch "/cat">
SecRuleRemoveById 950005
</LocationMatch>
```
Using either of the above seem to work the same:

Calls to `wget http://localhost/dog?/etc/passwd` are denied with 403

Calls to `wget http://localhost/cat?/etc/passwd` work with 200

Yet from what I've read `ctl:ruleRemoveById` is a runtime "per request" removal, while `SecRuleRemoveById` is a global directive... yet I still seeing it taking effect on a per request basis?

OR is the difference, that a completely separate set of `SecRules` is created for `LocationMatch /cat` vs those for everything other than `LocationMatch /cat` ? 

Why does it matter which one I use?

Reason for confusion is based off this issue https://github.com/SpiderLabs/ModSecurity/issues/424 and this article https://www.netnea.com/cms/apache-tutorial-7_including-modsecurity-core-rules/

> So these are startup rule exclusions. Excluding a rule in this manner is simple and readable, but it is also a drastic step which we will not use in a production setup very often. Because, if our issues with the rule 920300 are limited to a single legitimate agent checking the availability of our service by requesting the index page, we can limit the exclusion to this individual request.

So why is `LocationMatch /cat` based `SecRuleRemoveById` bad? Seems like its achieving the exact same desired result as the `ctl:ruleRemoveById` method, while all other locations are properly enforced (such as a GET on `/dog?etc/passwd` returns 403)

**Comment by csanders-git** [comment]
There is nothing wrong with your approach save that it is dependant on the web server. Not all web servers that support modsec support this capability

**Comment by bitsofinfo** [comment]
Thanks for the info. Do you know however if the `LocationMatch` based way is a runtime per http thread removal, or just a separate copy of all the rules loaded/filtered at httpd start, but scoped to that location?

**Comment by csanders-git** [comment]
My understanding of v2 is that it is a separate copy loaded from httpd start - which I think is one of the major changes slotted for v3. But you'd need to check with @zimmerle

**Comment by zimmerle** [comment]
```ctl:ruleRemoveById=950005```, like you mentioned, is a run time thing that allocates memory per request. The **location** one allocates memory in rules-load-time. It means that on long term, the location option should perform better.
