### ISSUE TITLE
Modsecurity v3 - how to check if it's working, logs empty

### ISSUE THREAD

**Issue by bryn1u** [SpiderLabs/ModSecurity#1724]
Hey guys,

I have a strange "issue". My modsec v3 under nginx probably works but there is nothing in log. And i want to ask how can i check if it's working ?
 ```
 server {
        server_name proton.edu.pl www.proton.edu.pl;
        charset off;
        index index.php index.html;
        access_log /home/proton/logs/proton.access.log;
        error_log /home/proton/logs/proton.error.log notice;
        ssi on;
        set $root_path /home/proton/domains/proton.edu.pl/public_html;
        root $root_path;
        listen 79.137.56.144:443;
        autoindex on;

        ssl on;
        ssl_certificate /etc/ssl/proton.edu.pl/proton.crt;
        ssl_certificate_key /etc/ssl/proton.edu.pl/proton.key;

        **modsecurity on;
        modsecurity_rules_file /usr/local/etc/modsecurity/main.conf;**

        location / {

        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
            expires     max;
        }
       location ~ [^/]\.php(/|$) {
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            if (!-f $document_root$fastcgi_script_name) {
                return  404;
            }
            fastcgi_pass    127.0.0.1:9000;
            fastcgi_index   index.php;
            include         /usr/local/etc/nginx/fastcgi_params;
            try_files $uri =404;
        }
    }
}
```
Config: /usr/local/etc/modsecurity/main.conf
```
Include /usr/local/etc/modsecurity/modsecurity.conf
Include /usr/local/etc/modsecurity/owasp-modsecurity-crs/crs-setup.conf
Include /usr/local/etc/modsecurity/owasp-modsecurity-crs/rules/rules.conf
```
I have an options Log in modsecurity.conf
SecDebugLog /var/log/modsec_debug.log
SecDebugLogLevel 3
and
SecAuditLogType Serial
SecAuditLog /var/log/modsec_audit.log

Someone can help me ? I would be really graceful. Thank you,

**Comment by victorhora** [comment]
Sorry for the long delay @bryn1u 

That's strange indeed. Have you double checked that the version of Nginx that your are running is really loading those configuration directives from your nginx.conf?

Can you post the output of "nginx -V"? It should show information about the Nginx connector, either compiled dynamically or statically.

Double check on your modsecurity.conf that [SecRuleEngine](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRuleEngine) is either set to "On" or "DetectionOnly".

In addition, keep in mind that the default configuration of [SecAuditLogRelevantStatus](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogRelevantStatus) will log to the AuditLog if you either trig a 4xx or 5xx error. So you might want to change your [SecAuditEngine](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditEngine) to "On" to make sure everything that passes through your webserver and the WAF is logged.

As a last step, you may want to increase your [SecDebugLogLevel](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecDebugLogLevel) to "9" and you should also see something there even if it doesn't trigger any rule.

**Comment by victorhora** [comment]
Closing this one as it seems more like an usage issue. If there's really a problem, let us know and we can reopen and investigate. Thanks.
