### ISSUE TITLE
Cache/cheapen evaluated Rule variables

### ISSUE THREAD

**Issue by p0pr0ck5** [SpiderLabs/ModSecurity#1732]
Piggybacking off #1731, it seems that calling `Rule::getFinalVars` can be quite expensive, due to the number of dynamic allocations is requires. It seems to me that the resulting data set could be cached within a transaction, such that the same set of variables and exclusions (which would always return an identical vector of `VariableValue` ptrs) can be reused. This would result in a performance gain by avoiding the need to recreate a new vector for every iteration (not accounting for transformations, which could be used to compute the values within the vector).

**Comment by zimmerle** [comment]
Dynamic allocations are not so popular on v3.0.3 as used to be in v3.0.2. As now the shared pointers are in place. Therefore, i am closing the issue as i it is kinda out of date.
