### ISSUE TITLE
SecChrootDir in ModSecurity 3?

### ISSUE THREAD

**Issue by xocuer** [SpiderLabs/ModSecurity#1736]
Hi,

I'm trying to migrate to ModSecurity 3, docs are not ready at this moment, so how can i use SecChrootDir?

Thank you

**Comment by victorhora** [comment]
@xocuer 

[SecChrootDir](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecChrootDir) is not supported on libModSecurity yet.

libModSecurity 3 docs are being worked on at this moment, for now you can use the v2 docs at: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29.

If you are curious about a feature being supported on libModSecurity, look for the "Supported on libModSecurity" tag on the reference manual.

**Comment by xocuer** [comment]
Thanks for the reply @victorhora 

Do you know if in the future SecChrootDir will be supported?

**Comment by victorhora** [comment]
Hi @xocuer 

Actually I believe SecChrootDir should be deprecated for quite some time as [Chroodir](https://httpd.apache.org/docs/2.4/mod/mod_unixd.html#chrootdir) is available in Apache Core since 2.2.10 so there should be no need to have the feature implemented in libModSecurity.
