### ISSUE TITLE
Allow the final boundary message to be suppressed

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#174]
MODSEC-21: The message where we complain about the final boundary missing can be confusing because it is not clear if it is a result of ModSecurity failing to parse request body in some edge cases (should not appear in 2.5.6 or later), a genuinely invalid request body (see MODSEC-19 for an example), or simply a truncated request body (a client disconnects). For those who understand the problem, we provide no facilities to suppress the message.

We should stop logging the error message ourselves, but raise the REQBODY_ERROR flag (see below), placing the message into REQBODY_ERROR_MSG. We would then add a rule to the default ModSecurity configuration to check for this condition and issue a warning.

Furthermore, we should create REQBODY_ERROR and REQBODY_ERROR_MSG as aliases for REQBODY_PROCESSOR_ERROR and REQBODY_PROCESSOR_ERROR_MSG, respectively, then deprecate the old names.

**Comment by mailtoyogeshpatel** [comment]
We have a following  rule 
SecRule REQBODY_ERROR "!@eq 0" \
"id:'200001', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"

in modsecurity log file we are getting so many logs like following :
"
Message: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "D:/tools/Apache2.4.x/conf/extra/highq/modsec/modsecurity.conf"] [line "132"] [id "200001"] [msg "Failed to parse request body."] [data "Error reading request body: Client went away."] [severity "CRITICAL"]
"
i want to stop logging only  if REQBODY_ERROR_MSG contains "Client went away." How to achieve this?
