### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by rayenmessaoudi** [SpiderLabs/ModSecurity#1746]
any guide to install the last release modsecurity v3.0.2 with apache2 ?

**Comment by zimmerle** [comment]
There is not official recipe. However, you can have a look on the project documentation in the compilation section. There you can find the steps to have it compiled and installed.

Documentation for libmod:
- https://github.com/SpiderLabs/ModSecurity/tree/v3/master#unix-linux-macos-freebsd-

Documentation for apache connector:
- https://github.com/SpiderLabs/ModSecurity-apache#compilation

Let as know if you have any issues following those steps.
