### ISSUE TITLE
Timestamp is removed from the auditlog index

### ISSUE THREAD

**Issue by Pjack** [SpiderLabs/ModSecurity#1762]
Hi,

I am using modsecurity v3 with the tag v3.0.2 in github.
Here is my settings in modsecurity.conf

SecAuditLogType Parallel
SecAuditLog /var/log/modsec/audit.log
SecAuditLogFileMode 0640
SecAuditLogDirMode 0750
SecAuditLogFormat JSON

The column in audit log index is different in this version compare to v.3.0.0
LOCAL_USER and timestamp are removed from the index.

The precise code position is src/transaction.cc

    /** TODO: Check variable */
    //ss << utils::string::dash_if_empty(
    //    this->m_collections.resolveFirst("LOCAL_USER").get());
    //ss << " ";
    //ss << tstr << " ";

Related git commit is:
https://github.com/SpiderLabs/ModSecurity/commit/6f7fdd9493428d68403c8f599948d1a4c75262ea#diff-ca92f1093d28e1b2545d642955a0f9fd

May I confirm if this is an accident? 
LOCAL_USER may be not useful, but timestamp is useful to identify when the request occur. 
Will we add the timestamp back to audit log index?

Thanks!

**Comment by zimmerle** [comment]
Hi @Pjack,

Thank you for let us know. It is fixed by: d0b423fdd7a1bee766b4d51b13f2084e92f894a9
