### ISSUE TITLE
SecAuditLogParts and PUT requests

### ISSUE THREAD

**Issue by GitHubUser4234** [SpiderLabs/ModSecurity#1764]
Hi,

For `SecAuditLogParts`, we can configure the `I`  which supposedly will log request bodies in all cases except when multipart/form-data encoding is used in POST requests. The thing is that when PUT requests are used, they aren't covered by the `I`. It looks like in order to prevent disk space issues here, one has to either remove the  `I` completely or even set the `SecRequestBodyAccess` to `off`. But the goal is to  log request bodies in all other cases. Would it be possible to adjust the  `I` setting to cover PUT requests or offer an alternative setting? Or maybe I'm mistaken and there already is an alternative setting/workaround? Thanks for any help :)

**Comment by victorhora** [comment]
@GitHubUser4234 Which version of ModSecurity you are using? Please provide as much detail as possible so the community can better assist you.

**Comment by GitHubUser4234** [comment]
Sure, that would be ModSecurity 2.9.0 with Apache 2.2 on Redhat 6.9. 

Some basic Modsecurity settings:

SecRuleEngine on
SecArgumentSeparator "&"
SecAuditEngine RelevantOnly
SecAuditLogDirMode 0770
SecAuditLogParts ABIFHZ
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogType Concurrent
SecCookieFormat 0
SecPcreMatchLimit 250000
SecPcreMatchLimitRecursion 250000
SecReadStateLimit 1024
SecRequestBodyAccess On
SecRequestBodyLimit 134217728
SecRequestBodyInMemoryLimit 131072
SecRequestBodyNoFilesLimit 131072
SecResponseBodyAccess Off
SecResponseBodyMimeType text/html text/plain text/xml
SecResponseBodyLimit  534388
SecResponseBodyLimitAction ProcessPartial
SecServerSignature Apache
SecTmpDir /var/tmp
SecUploadKeepFiles off

Please let me know in case any other particular info is needed, thanks a lot!

**Comment by victorhora** [comment]
Hi @GitHubUser4234 

In version 2.x there's are some limitations where PUT bodies are not inspected, which would explain why you're not being able to see the content with the "I" section of SecAuditLogParts.

This was also discussed at https://github.com/SpiderLabs/ModSecurity/issues/939, but it should be already supported on the new version of (lib)ModSecurity (3.x) so I suggest you should try it out to see if it works for you.

**Comment by GitHubUser4234** [comment]
@victorhora thanks for the reply, however I think there was a misunderstanding. It's not that the content with the "I" section of SecAuditLogParts cannot be seen, it's that it CAN be seen. Supposedly PUT bodies should only be logged with a "C" section of SecAuditLogParts but skipped with an "I" to prevent disk space issues. So unfortunately, the issue doesn't look resolved.

**Comment by GitHubUser4234** [comment]
@victorhora Would you please reopen the issue so the community would be able to see this, thanks

**Comment by victorhora** [comment]
@GitHubUser4234 thanks for your feedback. 

I would suggest that you test with a more recent version (i.e. [2.9.2](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.2)) as I see that you are running ModSecurity 2.9.0. Or better yet, you might want to check against the current [master](https://github.com/SpiderLabs/ModSecurity/tree/v2/master) as there's a number of recent fixes there.

If the issue still exists we can reopen the issue and investigate further.

Thanks!

**Comment by GitHubUser4234** [comment]
> I would suggest that you test with a more recent version (i.e. 2.9.2) as I see that you are running ModSecurity 2.9.0. Or better yet, you might want to check against the current master as there's a number of recent fixes there.

Unfortunately newer versions of ModSecurity are not provided by Redhat yet and we are required to stick to what Redhat has to offer. So as there doesn't seem to be an alternative setting/workaround for now, it looks like removing the "I" section would be the least evil in order to prevent disk space problems for large file uploads using PUT. When a new version is available through Redhat, I might revisit this issue.
