### ISSUE TITLE
rule syntax error

### ISSUE THREAD

**Issue by rayenmessaoudi** [SpiderLabs/ModSecurity#1766]
Hi guys i m not able to restart apache due to this error
my modsecurity version is 2.9.2
AH00526: Syntax error on line 40 of /usr/share/modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf:
Error parsing actions: Unknown action: \
Action 'configtest' failed.

error log
https://gist.github.com/rayenmessaoudi/4752385111f54cd265449dcdcbf1f27a

**Comment by victorhora** [comment]
@rayenmessaoudi 

As @Lifeforms correctly pointed out on his [comment](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1074#issuecomment-386710599), this an issue with older versions of Apache to correctly handle rule formatting.

Please follow @Lifeforms [comment](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1074#issuecomment-386710599) for further information on workarounds.
