### ISSUE TITLE
modsec 2.9.2 and fail2ban

### ISSUE THREAD

**Issue by rayenmessaoudi** [SpiderLabs/ModSecurity#1768]
Hi all,
Recently i installed modsecurity v2.9.2 and my problem is the modsec_audit.log does not have the same format like other version and also i noticed the creation of new folder with the current date contains the real modsec_audit logs so i can't use the fail regex in the fail2ban tool in order to set up Fail2ban with Mod_Security 2.9.2

http://www.fail2ban.org/wiki/index.php/HOWTO_fail2ban_with_ModSecurity2.5

my config file : 

LoadModule security2_module /usr/lib/apache2/modules/mod_security2.so
LoadModule unique_id_module /usr/lib/apache2/modules/mod_unique_id.so
<IfModule security2_module>
    SecRuleEngine On
    SecRequestBodyAccess On
    SecDebugLog /var/log/apache2/modsec_debug.log
    SecDebugLogLevel 3
    SecTmpDir /tmp/
    SecUploadDir /tmp/
    SecDataDir /tmp/
    SecAuditEngine On
    SecAuditLogType concurrent
    SecAuditLogParts ABIDEFGHZ
    SecAuditLog /var/log/apache2/modsec_audit.log
    IncludeOptional /usr/share/modsecurity-crs/*.conf
    IncludeOptional /usr/share/modsecurity-crs/rules/*.conf
</IfModule>

**Comment by rayenmessaoudi** [comment]
problem solved juste i need to change SecAuditLogType concurrent ==> Serial

**Comment by victorhora** [comment]
Closing as assuming problem was solved. Thanks for letting us know @rayenmessaoudi.
