### ISSUE TITLE
strange behaviour for my rule.

### ISSUE THREAD

**Issue by quenenni** [SpiderLabs/ModSecurity#1772]
Hello,

I struggled these last few days to understand why all the POST requests weren't treated anymore by modsec.

I finally found the custom rule I did that created that problem.

The purpose of this rule is to deactivate modsec engine when accessing with POST requests 2 specific files on a specific domain name:
```
SecRule REQUEST_METHOD "^POST$"                     "phase:request,id:1500,t:none,log,chain,allow,ctl:ruleEngine=off"
  SecRule REQUEST_HEADERS:Host "^xxx.yyyyyyyy.net$"        "chain"
  SecRule REQUEST_FILENAME "^/bro_(editor|main).php$"
```

But this rule just deactivate modsec engine for all POST requests (for all files on every domain names)

If I change it this way (just ordering differently the rules), it works well:
```
SecRule REQUEST_FILENAME "^/bro_(editor|main).php$" "phase:request,id:1500,t:none,log,chain,allow,ctl:ruleEngine=off"
  SecRule REQUEST_METHOD "^POST$"                       "chain"
  SecRule REQUEST_HEADERS:Host "^xxx.yyyyyyyy.net$"
```

But I don't understand why...
For me, the first way to do it should be good too.

Can someone explain me why the first rule is wrong?

----- 
* Debian wheezy
  Apache                                                2.2.22-13+deb7u12
  libapache2-mod-security2               2.8.0-2~bpo70+1

* Debian Jessie
  Apache                                                 2.4.10-10+deb8u12
  libapache2-mod-security2                2.9.1-2~bpo8+1

**Comment by csanders-git** [comment]
The CTL action takes effect on the part of the chain where it is placed (like transforms). As a result moving the CTL to the bottom rule should also solve the problem. Thanks for the report, this is a tricky part of the language.  Let me know if that doesn't make sense.

**Comment by quenenni** [comment]
Thanks for your quick help. 

Why doesn't it take into consideration the 'chain' option, telling it to wait for other rules before acting?

If I understand you correctly, these 2 rules react the same way:
```
SecRule REQUEST_METHOD "^POST$"                     "phase:request,id:1500,t:none,log,chain,allow,ctl:ruleEngine=off"
  SecRule REQUEST_HEADERS:Host "^xxx.yyyyyyyy.net$"        "chain"
  SecRule REQUEST_FILENAME "^/bro_(editor|main).php$"
```
```
SecRule REQUEST_METHOD "^POST$"                     "phase:request,id:1500,t:none,log,allow,ctl:ruleEngine=off"
```

> As a result moving the CTL to the bottom rule should also solve the problem

You mean something like this?
```
SecRule REQUEST_METHOD "^POST$"  "phase:request,t:none,log,chain,allow,setvar:tx.score=1"
  SecRule REQUEST_HEADERS:Host "^xxx.yyyyyyyy.net$"        "t:none,chain,setvar:tx.score=+1"
  SecRule REQUEST_FILENAME "^/bro_(editor|main).php$"     "t:none,chain,setvar:tx.score=+1"
  SecRule TX:SCORE "@eq 3" "ctl:ruleEngine=Off"
```

Few years ago, I was using this writing for my rules (the setvar & TX:score thingy) but I switched to the one above (from reading manuals), but maybe I was wrong.

I mean, without the 'score' var being incremented and tested at the end to be sure all rules were valid, does modsec activate the rule as soon as one line pass the test, without considering the other lines after, even if there is a 'chain' option?

**Comment by quenenni** [comment]
I've re-read the doc, and it's still unclear how exactly the CTL action is managed in the process.

I've done some tests this w-e and I can say that without a CTL action, it works as I thought:
```
SecRule REQUEST_HEADERS:Host "^xxx.yyyyyyyy.net$"  "phase:request,id:1500,t:none,log,block,msg:'test POST 1'"
```
```
SecRule REQUEST_HEADERS:Host "^xxx.yyyyyyyy.net$"  "phase:request,id:1500,t:none,log,block,msg:'test POST 2', chain"
  SecRule REQUEST_METHOD "^POST$"
```
The second rule, the request is blocked only for POST.
If I use 'pass' instead of 'block' in the params, it works also as I thought it should.

So, it's only the CTL action that is ran on the same line it's put.
Is it intended or not?

If it is, can we play with that, like this ie:
```
SecRule REQUEST_HEADERS:Host "^xxx.yyyyyyyy.net$"  "phase:request,id:1500,t:none,log,pass,ctl:ruleRemoveById=111"
  SecRule REQUEST_METHOD "^POST$"   "chain, ctl:ruleRemoveById=112"
  SecRule REQUEST_FILENAME "^/bro_(editor|main).php$"   "ctl:ruleEngine=off"
```
Meaning the rule 111 will be deactivate for all requests to xxx.yyyyy.net.
Rule 112 will be deactivited for all POST requests to xxx.yyyy.net 
And the modsec engine will be off for all POST requests to xxx.yyyy.net  to bro_editor.php and bro_main.php files?

Is that a thing? (I like that :))

PS: And now, I have to check all my custom rules. I guess lots of them don't really react the way I thought they would be ~ saaad sad face ~

**Comment by victorhora** [comment]
Hi @quenenni,

@csanders-git is right. If you change your ctl action to the last chained rule it should work in the way your expecting. Using variables/scores shouldn't be mandatory for your case.

This can be verified with the following test ruleset:

```
SecRule REQUEST_METHOD "^POST$"                     "phase:1,id:1500,t:none,log,chain,pass"
  SecRule REQUEST_HEADERS:Host "localhost"        "chain"
  SecRule REQUEST_FILENAME "^/bro_(editor|main).php$" "ctl:ruleEngine=off"

SecRule ARGS_POST "@contains value" "phase:2,id:1501,t:none,auditlog,log,deny"
```

And the rules can be tested like so:

```
$ curl -i -s -k  -X $'POST' -H $'Host: localhost' -H $'Content-Type: application/x-www-form-urlencoded' --data $'param1=value1' $'http://192.168.37.134:8080/bro_main.php'
```

The request as is should result in anything other than a "deny". But if you change any aspect of the request that won't trigger the first set of chained rules (id:1500) but still triggers the second rule (id:1501) you should get a "deny" and the corresponding log entry. You can test by changing the Host header.

The "AND" condition for the rule with the use of chained rules usually returns "true" (match) only if all the conditions of all the rules match, but it seems like this is not always true for all the actions such as ctl. So because with your rule there would always be a match with any POST request for the first rule, the ctl action would be executed immediately before the rest of chain is assessed.

**Comment by victorhora** [comment]
IMO, I don't think this is a bug but more of particularity of v2, but at this moment I'm not sure exactly which actions have this behaviour. Maybe it's worth checking and updating the manual for v2.

That being said, the note regarding the [chain](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#chain) action may suggest that the logical AND is for disruptive actions:

``
Note : Rule chains allow you to simulate logical AND. The disruptive actions specified in the first portion of the chained rule will be triggered only if all of the variable checks return positive hits. If any one aspect of a chained rule comes back negative, then the entire rule chain will fail to match. Also note that disruptive actions, execution phases, metadata actions (id, rev, msg, tag, severity, logdata), skip, and skipAfter actions can be specified only by the chain starter rule.
``

Lastly I've confirmed that this behaviour doesn't happen on v3 which seems "more accurate" in my opinion.
