### ISSUE TITLE
Custom anomaly_score threshold for a specific rule

### ISSUE THREAD

**Issue by intelbg** [SpiderLabs/ModSecurity#1773]
Hello,
Is it possible to set a custom threshold anomaly score for one specific rule, for example if I am blocked because of xss rule 941100 to lower it's sensitivity so being not blocked only for it?

In example to set it like:
...
 	setvar:tx.anomaly_score=lower-value-her,\
...

I tried but it does not work. I would like to accomplish this for one specific rule, not to play with the global inbound and outbound anomaly score threshold. 
Thank you in advance for the information!

**Comment by victorhora** [comment]
Hi @intelbg 

This questions seems more specific with usage of Core Rule Set itself. I would suggest that you look into the resources described at the [README](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/README.md) there. There's some useful material including the best practices to handle false positives with the CRS and ModSecurity. 
If you need further help you can also direct your question to the CRS GitHub or mailing list and lots of people there might be able to help you :)

If you believe that it's not the case and it's bug or missing functionality for ModSecurity (v2? v3?), please let us know and we can reopen the issue for further investigation. Thanks.
