### ISSUE TITLE
Mod security doesn’t prevent some XSS if Errordocument 404 is activated. 

### ISSUE THREAD

**Issue by jmbonnefond** [SpiderLabs/ModSecurity#1776]
Hi there, 

I’ve a strange behavior with mod security and XSS prevention. 
I use ModSecurity for Apache/2.9.0; OWASP_CRS/3.0.2 and apache 2.4.12. 
I’m testing XSS injection with Firefox 59.0.2.

When I get this URL :  https://www.XXXXX.com/index.php?a=a"><script>alert(1)</script>

Mod security detects it (with rule id 941100) and apply the appropriate answer, (here, a redirect to google for the test) and the client navigator is effectively redirected.

Message: Access denied with redirection to http://www.google.com/ using status 302 (phase 2). detected XSS using libinjection. [file "/etc/modsecurity/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "66"] [id "941100"] [rev "2"] [msg "XSS Attack Detected via libinjection"] [data "Matched Data:  found within ARGS:a: a\x22><script>alert(1)</script>"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "9"] [tag "Host: www.XXXXX.com"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"]
Action: Intercepted (phase 2)
Apache-Handler: application/x-httpd-php
Stopwatch: 1526653839027828 913 (- - -)
Stopwatch2: 1526653839027828 913; combined=344, p1=247, p2=57, p3=0, p4=0, p5=39, sr=40, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/); OWASP_CRS/3.0.2.
Server: Apache/2.4.12 (Ubuntu)
Engine-Mode: "ENABLED"

However I now test another quite similar URL (removing the ?a=a part) :  https://www.XXXXX.com/index.php"><script>alert(1)</script>

This time, mod security still detect a XSS injection (with a different rule : 941110) and tell that the redirection is applied but the navigator get the script injection as a result instead of the redirection.

Message: Access denied with redirection to http://www.google.com/ using status 302 (phase 2). Pattern match "(?i)([<\xef\xbc\x9c]script[^>\xef\xbc\x9e]*[>\xef\xbc\x9e][\\s\\S]*?)" at REQUEST_HEADERS:Referer. [file "/etc/modsecurity/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "101"] [id "941110"] [rev "2"] [msg "XSS Filter - Category 1: Script Tag Vector"] [data "Matched Data: <script> found within Request_Headers:Referee: https://www.XXXXX.com/index.php\x22><script>alert(1)</script>"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "4"] [accuracy "9"] [tag "Host: www.XXXXX.com"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"]
Action: Intercepted (phase 2)
Stopwatch: 1526652296256574 1350 (- - -)
Stopwatch2: 1526652296256574 1350; combined=522, p1=344, p2=132, p3=0, p4=0, p5=46, sr=70, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/); OWASP_CRS/3.0.2.
Server: Apache/2.4.12 (Ubuntu)
Engine-Mode: "ENABLED"

Note that this behavior seems to be correlated with the ErrorDocument directive redirection :

-If there is a directive : ErrorDocument 404 /404.php  Then I’m sensible to the XSS injection
-If there is no ErrorDocument declared, I got a 404 error : The requested URL /index.php"><script>alert(1)</script> was not found on this server.
-If there is a directive : ErrorDocument 404 https://www.XXXXX.com/404.php Then I’m redirected to the 404.php page loosing the full URL path.

It seems like in case of a 404 error, the error document take precedence before mod security even if mod security tells it has Intercepted the request. 

I’d like to keep the URL full URL info in case of a 404 document.

Any idea ?

**Comment by zimmerle** [comment]
Hi @	jmbonnefond,

ModSecurity works integrated with other(s) Apache modules that you may have configured. The modules works given a priority list and the request phase. ModSecurity is catching your request in a given phase and another Apache module is manipulating the request after that, leading you to this particular problem. I would recommend a different status code or configuration schema to make sure that the request is really terminated.
