### ISSUE TITLE
Binary package fails to install on Ubuntu/Debian

### ISSUE THREAD

**Issue by 1Sara1** [SpiderLabs/ModSecurity#1777]
Following directions from:
**https://www.modsecurity.org/download.html**

**sudo apt-get install libapache2-mod-security**

**E: Unable to locate package libapache2-mod-security**

**Comment by LeeShan87** [comment]
Hi,

What is your os version? 
libalpache2-mod-security packages available for Debian 7,8,9 [https://packages.debian.org/stretch/libapache2-modsecurity](https://packages.debian.org/stretch/libapache2-modsecurity)
For Ubuntu 14.04, 16,04, 17.10 [https://packages.ubuntu.com/trusty/libapache2-modsecurity](https://packages.ubuntu.com/trusty/libapache2-modsecurity)

**Comment by victorhora** [comment]
@1Sara1 please check the links provided by @LeeShan87. You might also be missing some configuration on your [sources.list files ](https://wiki.debian.org/SourcesList).

**Comment by eman1986** [comment]
looks like in ubuntu it's ```sudo apt-get install libapache2-mod-security2```

**Comment by RitaVratask** [comment]
I was having the same issue and `sudo apt-get install libapache2-mod-security2` worked for me.

Thanks!

**Comment by rljoia** [comment]
`sudo apt-get install libapache2-mod-security2` install v2.9.2, instead of 2.9.3. How can I install v2.9.3 on ubuntu images? I suppose if I could use `sudo apt-get install libapache2-mod-security`, the installed version will be v2.9.3.

**Comment by airween** [comment]
> How can I install v2.9.3 on ubuntu images?

What is your Ubuntu version?

**Comment by rljoia** [comment]
> > How can I install v2.9.3 on ubuntu images?
> 
> What is your Ubuntu version?

Bionic (18.04)

**Comment by airween** [comment]
> > What is your Ubuntu version?
> 
> Bionic (18.04)

As you can see [here](https://packages.ubuntu.com/bionic/httpd/libapache2-mod-security2), in that OS version the packaged version of mod-security is 2.9.2.

You can make your own package - or compile the module from the source.

**Comment by rljoia** [comment]
> here

Thanks. I noticed that "eoan" version already have the [v2.9.3 installed](https://packages.ubuntu.com/eoan/httpd/libapache2-mod-security2).

**Comment by airween** [comment]
Yes, as you can [see](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.3), the 2.9.3 was released in December of 2018, so it can't be part of 18.04 nor 18.10.

**Comment by zimmerle** [comment]
The Best place to discuss the subject related to packing is on the distro issue management; there you can reach the package developers and the distro contributors.
