### ISSUE TITLE
Log file not closing

### ISSUE THREAD

**Issue by doppelt** [SpiderLabs/ModSecurity#1789]
Hi

I want to report a bug in a new plesk extension:

its the \'application \'firewall utility (modsecurity)\'

after its installed and turned on, if you click on the app link under tools/security

there is a link at the bottom of the page to view the\' Log\'

but if you click on the log to view it, a pop up windows appears, but that window does never close. only if you exit the plesk panel and log back in to close the last active session

thanks

**Comment by zimmerle** [comment]
Hi @doppelt,

I am afraid that this is not the best place to open this issue. I would recommend you to open it under the "Plesk" project as this extension is not built nor maintained by us. Therefore there is no much we can do about it. Hope you understand.
