### ISSUE TITLE
v3/master: build issue - autoconf

### ISSUE THREAD

**Issue by fabianfrz** [SpiderLabs/ModSecurity#1791]
the autoconf build instructions seem to be having a bug or the version is incompatible with current autotools version.

## autoconf version:
`autoconf (GNU Autoconf) 2.69`

## configure

```
./configure: line 2127: syntax error near unexpected token `-Wall'
./configure: line 2127: `AM_INIT_AUTOMAKE(-Wall -Werror foreign subdir-objects)'
```

## autoconf

```
configure.ac:42: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:47: error: possibly undefined macro: AM_PROG_AR
configure.ac:81: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:348: error: possibly undefined macro: AC_CONFIG_FILES
configure.ac:357: error: possibly undefined macro: AM_COND_IF
```

**Comment by zimmerle** [comment]
Hi @fabianfrz,

Make sure that you also have the automake installed. Where did you got the build instructions from?

**Comment by fabianfrz** [comment]
I used the common automake commands since the repository does not contain build instructions. As an Arch Linux user I do have a very new autotools version. It sometimes has compatibillity issues with old autotools files.

**Comment by zimmerle** [comment]
Hi @fabianfrz,

Indeed we don't have specific instructions/recipes for every distro, however we provide a generic instructions here: 

- https://github.com/SpiderLabs/ModSecurity/tree/v3/master#unix-linux-macos-freebsd-

You should be fine with ArchLinux, that is what I use on the daily bases.
