### ISSUE TITLE
detect_utf8_character: logic error

### ISSUE THREAD

**Issue by tinselcity** [SpiderLabs/ModSecurity#1794]
I think for the "compute character number" the "...0x3F) < 6)" [here](https://github.com/SpiderLabs/ModSecurity/blob/0e2ec1c14f23f440580c0a41f9c0efe2b4952946/apache2/re_operators.c#L4324) should have been a left bit shift "...0x3F) << 6)"

```c
        else {
            unicode_len = 4;
            /* compute character number */
            d = ((c & 0x07) << 18) | ((*(p_read + 1) & 0x3F) << 12) | ((*(p_read + 2) & 0x3F) < 6) | (*(p_read + 3) & 0x3F);
        }
```
Apologies if I'm mistaken

**Comment by tinselcity** [comment]
FYI that might also be present in v3 [here](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/operators/validate_utf8_encoding.cc#L89)

**Comment by zimmerle** [comment]
Fixed! Thanks!
