### ISSUE TITLE
query string with slashes changes REQUEST_BASENAME value

### ISSUE THREAD

**Issue by tinselcity** [SpiderLabs/ModSecurity#1795]
I realize this is invalid but we had an issue with a user url that had unencoded forward slashes in the query string getting interpreted as the **REQUEST_BASENAME** for a request

eg:
https://mycoolwebsit.com/my_app.asp?apath=/my/cool/path.com

**REQUEST_BASENAME** would end up being **path.com** although I think it should have been **my_app.asp**.

I think it's due to basename determination [here](https://github.com/SpiderLabs/ModSecurity/blob/2ab08a625eb8e6cfadd757708e742b0b2a2b18f9/apache2/msc_util.c#L823) which walks backwards until it sees the first slash character.

[which is called as](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/re_variables.c#L2024):
```c

/* REQUEST_BASENAME */

static int var_request_basename_generate(modsec_rec *msr, msre_var *var, msre_rule *rule,
    apr_table_t *vartab, apr_pool_t *mptmp)
{
    char *value = file_basename(mptmp, msr->r->parsed_uri.path);
    return var_simple_generate(var, vartab, mptmp, value);
}
```

**Comment by zimmerle** [comment]
4585216 confirms that v3 is working correctly.

**Comment by zimmerle** [comment]
fecc429 confirms that v2 is working correctly.
