### ISSUE TITLE
snort/suricata interpreter mangles data files with pipes in the strings

### ISSUE THREAD

**Issue by tinselcity** [SpiderLabs/ModSecurity#1796]
We're having an issue where **pmf** operator will interpret pipes `|` in the data files as snort/suricata data and will interpret the remainder of the string as binary.

So a string like:
```
my hacker shell | is really cool
```
in a data file -meant to catch signatures in payloads will become something like:
```
my hacker shell | <binary stuff...>
```
eg
```
my hacker shell ��
```

Is there a way to disable the snort/suricata interpreter and just add the strings as is to the Aho–Corasick trie?

**Comment by zimmerle** [comment]
The @pmf operator has no configuration flag. Anything that it is different from its original functionality can be handled in a different operator name with custom code.
