### ISSUE TITLE
ModSecurity causes application to crash when uploading files > 10kb 

### ISSUE THREAD

**Issue by tonyzeng91** [SpiderLabs/ModSecurity#1798]
We have a WAF with nginx and modsecurity. When uploading files bigger than 10kb it causes the application to crash. We have the default modsecurity configuration. Any idea on what is causing this issue? 

```
SecRuleEngine DetectionOnly
SecRequestBodyLimit 13107200 
SecRequestBodyNoFilesLimit 131072
SecResponseBodyLimit 524288
```

**Comment by zimmerle** [comment]
Hi @tonyzeng91, Can you share with us the version of your ModSecurity?

**Comment by tonyzeng91** [comment]
Hi @zimmerle we are using modsecurity 2.9 version.

**Comment by zimmerle** [comment]
Hi @tonyzeng91, 

This issue was a duplicate of #839. You may upgrade to ModSecurity version 3.

- https://github.com/SpiderLabs/ModSecurity-nginx
