### ISSUE TITLE
potential off by one in parse_arguments

### ISSUE THREAD

**Issue by tinselcity** [SpiderLabs/ModSecurity#1799]
In parse arguments in the length check [here](https://github.com/SpiderLabs/ModSecurity/blob/71f650ad48c8b92ddf76817a86824b66a431a0d5/apache2/msc_parsers.c#L269)

```c
            while ((s[i] != '=') && (s[i] != argument_separator) && (i < inputlength)) {
```
The bounds checking happens after the deref s[i] -so if i == inputlength the deref on the buffer in s will run off the end before the bounds check (i < inputlength)

**Comment by zimmerle** [comment]
Thanks @tinselcity.

Fixed as of: 89f5427
