### ISSUE TITLE
Custom rules in 2.9.0 not working with 3.0.0

### ISSUE THREAD

**Issue by NisariAIT** [SpiderLabs/ModSecurity#1800]
The custom rules that I used earlier with 2.9 version of modsecurity does not work with new compilation(modsecurity v3.0 and connector). The error that I receive while restarting nginx is:

`SecRuleUpdateActionById is not yet supported  in /usr/local/nginx/conf/nginx.conf:49`

 Is there anything that I should change for this error to be fixed? My custom rule is as follows: `SecRuleUpdateActionById 200004 "allow"`
How can I add this rule in version 3.0.0?

**Comment by tsyj** [comment]
Is there a plan to support the SecRuleUpdateActionById directive in the near future?

**Comment by smart0088** [comment]
Is there a plan to support the SecRuleUpdateActionById directive in the near future? @zimmerle

**Comment by zimmerle** [comment]
Hi @tsyj,

Trying to have it implemented for v3.0.3. Placed the milestone label.

**Comment by jonah-potter** [comment]
Can anyone recommend a workaround until `SecRuleUpdateActionById` support is added, aside from editing the rule directly?

**Comment by zimmerle** [comment]
fixed in current v3/master.
