### ISSUE TITLE
setenv not effective, and 'deny' still loads page

### ISSUE THREAD

**Issue by nathanstretch** [SpiderLabs/ModSecurity#1802]
Using ModSecurity 2.9.2 on Apache 2.4.33. I've simplified the situation as far as possible, but have run into a wall. I'm working within a virtualhost config. Here's what I'm trying to do:

```
SecAction "pass,setenv:TESTPAGE=1,id:10001001"
Header always set X-Debug "IsTest" env=TESTPAGE
```
With no other rules, this should always set the X-Debug header, but it doesn't. To try to figure out why, first I deleted the SecAction and just did this:

```
RewriteRule .* - [E=TESTPAGE]
Header always set X-Debug "IsTest" env=TESTPAGE
```
Sure enough, the header was set in that case, so I know headers are working and environment variables can be set/checked. Then I tried this:

`SecAction "deny,status:503,setenv:TESTPAGE=1,id:10001001"
`

And indeed I got a 503 http code, so I know the SecAction is being processed. Given those two things, the only possibility is that ModSec is failing to set the environment variable as it should, but I don't know of any reason why that should be the case.

Also, it appears that 'deny' is not actually preventing the page from loading.  It changes the http status code, but doesn't block processing.  This wasn't the case in the past, but I don't know when it changed.

**Comment by nathanstretch** [comment]
It appears this has something to do with using mod_proxy_fcgi (which we use to serve php scripts via php-fpm).  When I test on straight html files, the setenv does appear to work.  However, the status codes don't work.  When I set 'deny' for an html file, it returns 404, regardless of the status code I specify.  (As I mentioned, status codes work properly on php files, but the 'deny' doesn't prevent processing.  So, two separate problems here?

**Comment by zimmerle** [comment]
Hi @nathanstretch,

That may or may not be a problem. ModSecurity interacts with other modules in a sequence. Depending on the modules orders, the fcgi will be executed prior to ModSecurity. Therefore reading the empty env var. 

Regarding the incorrect status code, it will be better if you could share yours debug log.

**Comment by nathanstretch** [comment]
Can you provide more info on what modules would prevent mod security from setting environment variables?  Regarding status codes, what debug log are you referring to?
