### ISSUE TITLE
setvar tx.paranoia_level on v3/master ignored

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/ModSecurity#1808]
Referencing here an issue open on owasp-modsecurity-crs that it seems related to libmodsecurity v3/master:  https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1127

**Comment by csanders-git** [comment]
thanks for opening this @theMiddleBlue

**Comment by victorhora** [comment]
Indeed, it seemed like the variables were being treated as case sensitive, but according to v2 behaviour and the [reference manual](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#setvar) should be case insensitive.

PR #1810 is up for evaluation and should fix this issue.

**Comment by zimmerle** [comment]
fixed by: d810de9166794be2bee972fffb0e09cb0b8d6ec5
