### ISSUE TITLE
Wrong field of msr variable when create new module for modsecurity 2.9

### ISSUE THREAD

**Issue by eternal-flame** [SpiderLabs/ModSecurity#1811]
When i attached this example https://github.com/SpiderLabs/ModSecurity/blob/v2/master/ext/mod_var_remote_addr_port.c into Modsecurity to learn how to create custom modules, the whole apache went down with error log "[Thu Jun 21 10:06:25.009395 2018] [core:notice] [pid 17836] AH00051: child pid 17840 exit signal Segmentation fault (11), possible coredump in /etc/apache2".

After some try modified this file, i found a problem with variable msr, here i used ap_log_error function of apache to log fields of msr variable. 
Struct modsec_rec:
![image](https://user-images.githubusercontent.com/28984391/41696741-db285f12-753f-11e8-8d41-006d890cfaf8.png)
(U guys can find full struct declaration in file modsecurity.h)

Result when i logged request line:
![image](https://user-images.githubusercontent.com/28984391/41696828-464af73c-7540-11e8-89ea-0d59dfdbeb52.png)
![image](https://user-images.githubusercontent.com/28984391/41697003-0d0faffc-7541-11e8-830c-ddd2c03fbd30.png)

It actually logged the request method

Result when i logged request method:
![image](https://user-images.githubusercontent.com/28984391/41697059-504dd302-7541-11e8-86dc-7c532fd0e620.png)
![image](https://user-images.githubusercontent.com/28984391/41697070-5a13c8ec-7541-11e8-884f-3177a78141fe.png)

It actually logged the request uri

And so on...
I can't find where this mistake started, but seem it don't effect the rules set. Can someone explain what wrong and fix this.

**Comment by zimmerle** [comment]
Hi @eternal-flame, 

It smells like you have a version mismatch. Please double check if your Apache and apr versions are the same in compilation and run time. 

You can verify ModSecurity startup information on the error log. It should tell you if there is such mismatch.

**Comment by eternal-flame** [comment]
Thank you very much, it's exactly what happen!
