### ISSUE TITLE
ModSecurity converting £ (%C2%A3) from query string to `ARGS:note' (Value: `\xffffffc2\xffffffa3' )

### ISSUE THREAD

**Issue by danielwrayois** [SpiderLabs/ModSecurity#1812]
Hi,

We are seeing an issue with our application and ModSecurity when using specific characters, such as £, and € symbols.

Our application performs a POST request with a body that is parsed without issue, however it also includes a query string as part of that POST request, which is being caught by ModSecurity and evaluated as being outside of the acceptable byte range.

We have tried setting the encoding type to UTF-8, for the client, and proxies, but this does not alter the character handling in ModSecurity.

The issue seems to be the conversion of `%C2%A3` to `\xffffffc2\xffffffa3`

nginx version: nginx/1.11.9
ModSecurity version: 3
OS version: Ubuntu 16.04 LTS

**URI**
/api/tenancies/xxxx/comment?note=Payment+of+%C2%A3100+Per+week

**Nginx log**
```
[21/Jun/2018:08:56:03 +0000] bytes_sent="192" http_referer="-" user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"  client_addr="xxx.xxx.xxx.xxx" client_request="POST /api/tenancies/xxxx/comment?note=Payment+of+%C2%A3100+Per+week HTTP/1.1" upstream_addr="-" upstream_status="403" upstream_connection_time="-" upstream_header_time="-" upstream_response_time="-" response_time="0.000" request_id="70628f08c456f14edff01390be331849" session_id="uid=0501000A69582B5B900B262C02070303"
```

**ModSecurity log**
```
2018/06/21 08:56:03 [info] 15312#15312: *25 [client xxx.xxx.xxx.xxx] ModSecurity: Warning. Matched "Operator `@validatebyterange' with parameter `1-255' against variable `REQUEST_UR
I' (Value: `/api/tenancies/xxxx/comment?note=Payment+of+\xffffffc2\xffffffa3100+Per+week` ) " at REQUEST_URI [file "/etc/nginx/conf.d/modsecurity/rules/REQUEST-920-PROTOCOL-ENFO
RCEMENT.conf"] [line "490"] [id "920270"] [rev "2"] [msg "Invalid character in request (null character)"] [data ""] [severity "0"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accurac
y "9"] [hostname "xxx.xxx.xxx.xxx"] [uri "/api/tenancies/xxxx/comment"] [unique_id "152957136334.949135"], client: xxx.xxx.xxx.xxx, server: dev-001.xxx.co.uk, request
: "POST /api/tenancies/xxxx/comment?note=Payment+of+%C2%A3100+Per+week HTTP/1.1", host: "dev-001.xxx.co.uk"
```
**Text entry**
![payment_note](https://user-images.githubusercontent.com/34679764/41710175-ead72fae-753c-11e8-8f67-d231a889d8b9.png)

**Chrome Dev Output**
![payment_content](https://user-images.githubusercontent.com/34679764/41710184-f065ee06-753c-11e8-8448-f4abc9828449.png)

I can provide the Nginx and ModSecurity Debian packages if required for testing.

**Comment by danielwrayois** [comment]
Hi,

After a bit more investigation it looks as if the decoding from UTF-8 of two bytes or more to ASCII isn't working.

We have tested all characters allowed in the lookup table up to ASCII character 126 that are of one byte UTF-8, after that no further characters work when using UTF-8 encoding in the query string ARGS or the REQUEST_URI.

**Comment by zimmerle** [comment]
No longer an issue on d302b99ec539e64bc3d04295a5b9928aaa11b70f. Added a test case for it: https://github.com/SpiderLabs/ModSecurity/commit/d302b99ec539e64bc3d04295a5b9928aaa11b70f#diff-1106c1d9c86532fb5916c9af97fdd8d3
