### ISSUE TITLE
When will modsecurity version 3 availble for download on modsecurity website

### ISSUE THREAD

**Issue by muzammel111** [SpiderLabs/ModSecurity#1815]
Dear All,
I am currently using modsecurity version 2.9.2, as i see the version 3.0.0 announcement on modsecurity website but its still not available to download from https://www.modsecurity.org/download.html , only download option from github website.  I want to know when download of version 3 will available from modsecurity website like version 2.9.2  https://www.modsecurity.org/tarball/2.9.2/modsecurity-2.9.2.tar.gz ?

**Comment by zimmerle** [comment]
Hi @muzammel111,

We are slowing move everything towards GitHub. Starting with v3 the releases will be only published on GitHub. You can find the releases details here:

- https://github.com/SpiderLabs/ModSecurity/releases

**Comment by muzammel111** [comment]
Thankyou so much Mr. zimmerle  for quick response. So its mean modsecurity.org will obsolete soon ?.  And official modsecurity code etc based on github ?

**Comment by zimmerle** [comment]
Hi @muzammel111,

We are just avoiding to maintain the download in two different places, since v3 users are more concentrated on GitHub, it became a natural choice. But the website won't be discontinued.
