### ISSUE TITLE
Need help to upgrade modsecurity from 2.9.2 to 3.0.2

### ISSUE THREAD

**Issue by muzammel111** [SpiderLabs/ModSecurity#1819]
Dear Forum,

I need guidance about upgrade of manually compile modesecurity from version 2.9.2 to 3.0.2, can i remove the currently version (2.9.2) firstly by using make clean && make uninstall ? or just direct compile & make of new version (3.0.2) to take effect? .

**Comment by zimmerle** [comment]
Hi @muzammel111, 

It is safe to install the libModSecurity in parallel to version 2.x. You may want to keep the v3-only when compiling the nginx connector.

For the compilation itself, there are some recipes here:
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

**Comment by muzammel111** [comment]
Respected Zimmerle,
I am confusing about seeing thread -> https://github.com/SpiderLabs/ModSecurity/issues/1661 which is older from this thread, in which you suggest apache connector for V3. But in this thread you said you need v3 only for nginx ? kindly please clear.
