### ISSUE TITLE
Performance issue with commercial ruleset in modsecv3 on nginx

### ISSUE THREAD

**Issue by invent-uk** [SpiderLabs/ModSecurity#1832]
Having used the Trustwave commercial ruleset on ModSecv2 for a number of months we tasked with migrating to ModSecv3. The maximum throughput appears to be significantly reduced with a large ruleset indicating that there is a performance problem within the parsing engine of ModSecv3.

Platform: ModSecv3 (Master or 3.0.2) with Nginx connector running on Centos 6.9 or 7.
Previously the throughput of modsecv2 with trustwave ruleset (30k rules) was around 130rps. With the same hardware it is reduced to around 25rps.

Loading a batch of dummy rules seems to have a similar effect: 

seq 30000 | xargs -I {} echo "SecRule REQUEST_URI "@contains child" \"id:99{},allow\"" >> example.rules

**Comment by p0pr0ck5** [comment]
@refinitive please see #1734 as well as https://sourceforge.net/p/mod-security/mailman/mod-security-users/thread/CAE8hE%3DofVGHU9r8Jxf7T5S3M557n4f3n52OoBo-OzKnuRSzydA@mail.gmail.com/.

**Comment by invent-uk** [comment]
Hi @p0pr0ck5 , thanks for the info. I've looked through the links and they don't indicate a solution. Based on this not being more widely reported I get the impression most users are using the CRS ruleset and as such are not impacted by the non-linear performance impact of increasing the ruleset size. Could you confirm whether the latest version is passing performance criteria at 30,000 rules?

**Comment by p0pr0ck5** [comment]
Hey @refinitive, apologies for the confusion. I wasn't pointing you to a solution, but rather more discussion and information on this topic. As there's already been quite a lot of opinionated chatter surrounding this, I wanted to tie your report into existing conversations, not spark a new one here as it's not likely to gain any traction.

Might you consider contacting Trustwave support to get their take on it?

**Comment by zimmerle** [comment]
Hi @refinitive,

Please use Trustwave SOC to understand if you are using an optimal configuration. Things like inspect or not response body could impact significant on performance.
