### ISSUE TITLE
ModSecurity blocks saving a page on Mediawiki (403 Forbidden)

### ISSUE THREAD

**Issue by n0q82l01w6x53** [SpiderLabs/ModSecurity#1833]
I'm kind of wondering why does that happen...
The ModSecurity version is 3.0 and I'm using the OWASP rule set.
Also, the web server is nginx.

**Comment by n0q82l01w6x53** [comment]
Nevermind, it was a false positive with MULTIPART_UNMATCHED_BOUNDARY in the rule set. Disabled that and it works fine.

**Comment by csanders-git** [comment]
Thanks for your feedback we'll look into it on the CRS side
