### ISSUE TITLE
Modsecurity 2.9.2 causes duplicate headers with Nginx

### ISSUE THREAD

**Issue by mangelot** [SpiderLabs/ModSecurity#1834]
With modsecurity active we receive duplicate headers 
Content-Length and Connection "Keep-alive" are both listed twice.
when disabling modsecurity the problem doesn't exist.

**Comment by zimmerle** [comment]
Hi @mangelot,

Please use the ModSecurity version 3 with the nginx connector:
https://github.com/SpiderLabs/ModSecurity-nginx
