### ISSUE TITLE
[mlogc] Implement Content-Type header in curl request

### ISSUE THREAD

**Issue by umarfarook882** [SpiderLabs/ModSecurity#1837]
Hi, I am not  able to parse the curl request body content in framework like `express js`. Express js required content-type header in the request to identify and parse the body content. It will be good implementing `Content-Type` header option either in `mlogc.conf` file or in `mlogc.c` while sending the curl request. 

Thanks in advance :)

**Comment by victorhora** [comment]
If you are using libModSecurity, try using the HTTPS transport by setting the SecAuditLogType to "HTTPS" which allows sending the logs directly to a remote server without the usage of a log collector such as MLogC.

This transport uses libcURL on the backend that, on the current implementation, should [set the Content-Type to JSON](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/audit_log/writer/https.cc#L55) by default which in turn should solve the issue you're facing.
