### ISSUE TITLE
[mlogc] SecAuditLog throwing error "Invalid input" for concurrent logging.

### ISSUE THREAD

**Issue by umarfarook882** [SpiderLabs/ModSecurity#1839]
Hi, `SecAuditLog` throws a error invalid input for `|/usr/bin/mlogc /etc/apache2/modsecurity.d/mlogc.conf` on `ModSecurity v3.0.2-70 geed6b5f8` (Ubuntu 18:04)

![error_modsec](https://user-images.githubusercontent.com/22318677/42733382-2e62ac2a-884e-11e8-8442-a0a07a719c1f.png)

**Comment by victorhora** [comment]
Hey @umarfarook882 

It seems like this is a duplicate with #1498.

For libModSecurity we suggest using the HTTPS transport by setting the [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType) to "HTTPS" which allows sending the logs directly to a remote server without the usage of a log collector such as MLogC.

For detailed information on this implementation, please refer to: [https.cc](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/audit_log/writer/https.cc) and [https_client.cc](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/utils/https_client.cc)

**Comment by umarfarook882** [comment]
Thanks @victorhora , I am already using `HTTPS transport`. but problem is we don't have any kind of authentication to validate the curl request coming from the libModSecurity in remote server. In mlogc, we had option like `SensorUsername` and `SensorPassword`

**Comment by victorhora** [comment]
Well, the HTTPS transport by itself provides confidentiality through TLS Encryption, so your logs should be somewhat safe from someone sniffing or MiTM, but yes the lack of authentication could allow someone sending invalid / erroneous log entries and polluting your logs.

You could have a certain level of restriction of which entity can write audit log entries to your log server by simply using source based IP filtering on the receiving end... 

If this is not enough, maybe the simplest approach would be using something like ["ModSec-key" ](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/utils/https_client.cc#L49-L51) option as already used in [SecRemoteRules](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRemoteRules) to achieve a simple authentication method. But then whatever you have on your receiving end of the logs would need to validate this key before accepting/saving the log entries.

libcURL also has simplified support for basic authentication as described here as well: https://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html. This would have the advantage of being an easier replacement with mLogC.

Hope this helps.
