### ISSUE TITLE
nginx 60000 connections  and cpu cost 100%

### ISSUE THREAD

**Issue by 18301385759** [SpiderLabs/ModSecurity#1842]
aliyun, centos7.4 and 16vcpus 32G mem  

nginx run long time  and  the cpu cost 100 % , use top command , there 1cpu or 2cpus are working ,which cpu cost 100%. restart the nginx , and there will be ok .  and 16 vcpus  are all working together . but after a while , ther only left 1vcpus are working .  always  ,  

the nginx cpu mode , i use auto , number  , affinity , which all doesnt work .

nginx-configure:

load_module /usr/local/nginx/modules/ngx_http_modsecurity_module.so;
user  nginx;
worker_processes        16;
           
pid                     /var/run/nginx.pid;
worker_rlimit_nofile    65535;

events {
    use epoll;
    accept_mutex off;
    worker_connections  10240;
}

**Comment by 18301385759** [comment]
1

**Comment by longlnk** [comment]
I have same problem, but all CPUv is 100%.

**Comment by DenysFrasinich** [comment]
Hello.  I had high CPU utilisation and random nginx crashes with package "libmodsecurity" from CentOs repo. But after i rebuild libmodsecurity without liblmdb support, crashes gone. Configuration option "--with-lmdb=no". I think, it could be problem with old version of liblmdb in CentOS repo. If you want to try i could share my rpm spec file here.

**Comment by kwenjoe** [comment]
I have same problem, only 1 cpu working and cost to 100% ,even if configuration option "--with-lmdb=no"

**Comment by zimmerle** [comment]
I Would like to invite you guys to test the most recent version of v3/master and let me know if that is still a problem for you.

**Comment by kwenjoe** [comment]
I still has the same problem , after nginx and modsecurity run about 7-8 days, only 1 cpu working and performance will become poor. 
I use ubuntu 16.04 , nginx 14.0 and have 12 vcpus 8G ram .
If any other things I provide can help fix this issue, please let me know.
