### ISSUE TITLE
Problem with stack reverse proxy nginx+ modsecurity

### ISSUE THREAD

**Issue by alterego2004** [SpiderLabs/ModSecurity#1843]
A good day! I have problem with modsecurity. On my infrastructure I have Web Front End reverse proxy nginx with modsecurity . I sent from client side POST query and have next error:
HTTP/1.1
Content-Type: text/html
Content-Length: 166
Connection: close

--33bd627d-E--
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

--33bd627d-H--
Apache-Handler: IIS
Stopwatch: 1531838335000585 3003464 (- - -)
Stopwatch2: 1531838335000585 3003464; combined=1412809, p1=422, p2=1412064, p3=61, p4=209, p5=52, sr=138, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for nginx (STABLE)/2.9.1 (http://www.modsecurity.org/); OWASP_CRS/3.0.2.
Server: ModSecurity Standalone
Engine-Mode: "ENABLED"
 How I may debug this error?
PS.
**nginx -V**
nginx version: nginx/1.12.0
built with OpenSSL 1.0.2k-freebsd  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --modules-path=/usr/local/libexec/nginx --with-file-aio --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --with-http_addition_module --with-http_auth_request_module --add-dynamic-module=/usr/ports/www/nginx/work/headers-more-nginx-module-84241e4 --with-http_dav_module --with-http_flv_module --with-http_gzip_static_module --with-http_gunzip_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_stub_status_module --with-http_sub_module --add-module=/usr/ports/www/nginx/work/modsecurity-2.9.1/nginx/modsecurity --with-pcre --with-http_v2_module --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-mail=dynamic --without-mail_imap_module --without-mail_pop3_module --without-mail_smtp_module --with-mail_ssl_module --with-http_ssl_module

 ****uname -a****
FreeBSD free 11.1-RELEASE-p11 FreeBSD 11.1-RELEASE-p11 #0: Thu Jun 21 03:46:08 UTC 2018

**tail error.log**
1905#100097: ModSecurity for nginx (STABLE)/2.9.1 (http://www.modsecurity.org/) configured.
2018/07/17 17:37:54 [notice] 1905#100097: ModSecurity: APR compiled version="1.5.2"; loaded version="1.5.2"
2018/07/17 17:37:54 [notice] 1905#100097: ModSecurity: PCRE compiled version="8.40 "; loaded version="8.40 2017-01-11"
2018/07/17 17:37:54 [notice] 1905#100097: ModSecurity: LUA compiled version="Lua 5.1"
2018/07/17 17:37:54 [notice] 1905#100097: ModSecurity: YAJL compiled version="2.1.0"
2018/07/17 17:37:54 [notice] 1905#100097: ModSecurity: LIBXML compiled version="2.9.4"
2018/07/17 17:37:54 [notice] 1905#100097: ModSecurity: StatusEngine call: "2.9.1,nginx,1.5.2/1.5.2,8.40/8.40 2017-01-11,Lua 5.1,2.9.4,4ff88aaddbd209d8026924c2cc2836b408698823"
2018/07/17 17:37:54 [notice] 1905#100097: ModSecurity: StatusEngine call successfully sent. For more information visit: http://status.modsecurity.org/

With best Regards

**Comment by victorhora** [comment]
@alterego2004 I see that you are running ModSecurity 2.9.1 with Nginx. There are known issues with Nginx running ModSecurity 2.x which there are no plans to fix.

So you may want to upgrade to ModSecurity 3.x (libModSecurity) and use the ModSecurity-nginx connector: https://github.com/SpiderLabs/ModSecurity-nginx
