### ISSUE TITLE
Operator @rbl doesn't properly set tx.0 on v3/master

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/ModSecurity#1845]
Hi,

I'm testing the `@rbl` operator with a my DNS server / zone. It works well, except for the `tx.0` variable. Using `capture` on the Rule, the `tx.0` variable has the `REMOTE_ADDR` value instead of DNS response (useful for categorizing).

Not sure if I'm doing it wrong or it's a bug. Any idea?

Test Rule:
```
SecRule REMOTE_ADDR "@rbl dnsbl.example.com" "phase:2,\
   id:171,\
   capture,\
   pass,\
   log,\
   auditlog,\
   msg:'Response: %{tx.0}'"
```

Debug log:
```
[4] (Rule: 171) Executing operator "Rbl" with param "dnsbl.example.com" against REMOTE_ADDR.
[9] Target value: "172.17.0.1" (Variable: REMOTE_ADDR)
[2] RBL lookup of 172.17.0.1 succeeded.
[7] Added RXL match TX.0: 172.17.0.1
[9] Matched vars updated.
[4] Running [independent] (non-disruptive) action: log
[9] Saving transaction to logs
[4] Running [independent] (non-disruptive) action: msg
[9] Saving msg: Response: 172.17.0.1
[4] Rule returned 1.
[9] (SecDefaultAction) Running action: log
[9] Saving transaction to logs
[9] (SecDefaultAction) Running action: auditlog
[4] (SecDefaultAction) ignoring action: deny (rule does not cotains block)
[9] (SecDefaultAction) Running action: status
[4] Running (non-disruptive) action: capture
[4] Running (disruptive)     action: pass
[8] Running action pass
[4] Running (non-disruptive) action: auditlog
```

Nginx version:
```
nginx version: openresty/1.13.6.2
built by gcc 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 
```

libModSecurity version:
```
ModSecurity - v3.0.2-70-geed6b5f8 for Linux
 
 Mandatory dependencies
   + libInjection                                  ....v3.0.2-70-geed6b5f8
   + SecLang tests                                 ....eed6b5f8
 
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (GeoIP) v1.6.12
         -lGeoIP, -I/usr/include/
   + LibCURL                                       ....found v7.58.0 
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl, -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.4
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....found v502
      -llua5.2 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -DWITH_LUA_5_2 -I/usr/include/lua5.2
 
 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled
```

thanks

**Comment by victorhora** [comment]
Hi @theMiddleBlue 

I've quickly glanced at the operator implementation code and I'm not sure if this is a bug at this moment. Can you please check if this behaviour differs from ModSecurity v2?

**Comment by theMiddleBlue** [comment]
uhm I've tested with ModSecurity v2 and the message is different but it doesn't contains the response...

audit log
```
[Sat Jul 21 00:41:44.791562 2018] [:error] [pid 576:tid 140107018569472] [client 172.17.0.1:43202] [client 172.17.0.1] ModSecurity: Warning. RBL lookup of 1.0.17.172.dnsbl.example.com succeeded at REMOTE_ADDR. [file "/etc/apache2/modsecurity.d/modsecurity.conf"] [line "234"] [id "171"] [msg "Response: RBL lookup of 1.0.17.172.dnsbl.example.com succeeded at REMOTE_ADDR."] [hostname "localhost"] [uri "/"] [unique_id "W1KBSLxF45PMenYbHFS9KQAAAAM"]
```

debug log:
```
[21/Jul/2018:00:41:44 +0000] [localhost/sid#7f6d441e25e8][rid#7f6d340f30a0][/][4] Recipe: Invoking rule 7f6d443332f8; [file "/etc/apache2/modsecurity.d/modsecurity.conf"] [line "234"] [id "171"].
[21/Jul/2018:00:41:44 +0000] [localhost/sid#7f6d441e25e8][rid#7f6d340f30a0][/][5] Rule 7f6d443332f8: SecRule "REMOTE_ADDR" "@rbl dnsbl.example.com" "phase:2,id:171,capture,pass,log,auditlog,msg:'Response: %{tx.0}'"
[21/Jul/2018:00:41:44 +0000] [localhost/sid#7f6d441e25e8][rid#7f6d340f30a0][/][4] Transformation completed in 5 usec.
[21/Jul/2018:00:41:44 +0000] [localhost/sid#7f6d441e25e8][rid#7f6d340f30a0][/][4] Executing operator "rbl" with param "dnsbl.example.com" against REMOTE_ADDR.
[21/Jul/2018:00:41:44 +0000] [localhost/sid#7f6d441e25e8][rid#7f6d340f30a0][/][4] Operator completed in 65071 usec.
[21/Jul/2018:00:41:44 +0000] [localhost/sid#7f6d441e25e8][rid#7f6d340f30a0][/][2] Warning. RBL lookup of 1.0.17.172.dnsbl.example.com succeeded at REMOTE_ADDR. [file "/etc/apache2/modsecurity.d/modsecurity.conf"] [line "234"] [id "171"] [msg "Response: RBL lookup of 1.0.17.172.dnsbl.example.com succeeded at REMOTE_ADDR."]
[21/Jul/2018:00:41:44 +0000] [localhost/sid#7f6d441e25e8][rid#7f6d340f30a0][/][4] Rule returned 1.
```

what I'm missing?

DNS query / response:
```bash
dig 1.0.17.172.dnsbl.example.com

; <<>> DiG 9.10.6 <<>> 1.0.17.172.dnsbl.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64008
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;1.0.17.172.dnsbl.example.com. IN	A

;; ANSWER SECTION:
1.0.17.172.dnsbl.example.com. 0 IN	A	127.1.10.3

;; Query time: 71 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Jul 21 02:46:50 CEST 2018
;; MSG SIZE  rcvd: 76
```

**Comment by theMiddleBlue** [comment]
(not related to this issue): thinking about the `@rbl` operator, it would be great if it could query not only type **A** but also type **TXT**. It could be used to store more information about the IP reputation. What do you think about?

**Comment by csanders-git** [comment]
Classic let's abuse DNS as a DB... Love the idea, we could even monkey patch an approved communication protocol (i.e spf/dkim style)

**Comment by theMiddleBlue** [comment]
@victorhora if you need it, I can send you (via DM slack/IRC) the real domain name which I'm using for this test (and even add specific record A)

**Comment by theMiddleBlue** [comment]
I made a workaround using Nginx + Lua by setting the DNS response to a response header (`X-DNSBL`) that is intercepted by a ModSecurity rule:

Nginx configuration:
```perl
location /test {
   modsecurity on;
   modsecurity_rules_file /usr/local/openresty/nginx/conf/modsecurity.conf;
   default_type 'text/html';                                                                    
                                                                                                        
   set $dnsblres 0;               
   rewrite_by_lua_block {
      local resolver = require "resty.dns.resolver"
      local r, err = resolver:new{
         nameservers = {"8.8.8.8"},
         retrans = 1,
         timeout = 2000,
      }
                                                                                                               
      local clientip = ngx.var.remote_addr
      a,b,c,d = clientip:match("([%d]+).([%d]+).([%d]+).([%d]+)")

      local apikey = "abcdef12345"
      local dnsblhost = apikey.."."..d.."."..c.."."..b.."."..a..".dnsbl.example.com"
      local answers, err, tries = r:query(dnsblhost, nil, {})

      e,f,g,h = answers[1].address:match("([%d]+).([%d]+).([%d]+).([%d]+)")

      if e == '127' then
         ngx.var.dnsblres = answers[1].address
      end
   }

   more_set_headers "X-DNSBL: $dnsblres";
   # ...
}
```

libModSecurity Test Rule:
```perl
SecRule RESPONSE_HEADERS:X-DNSBL "@rx 127\.([0-9]+)\.([0-9]+)\.([0-9]+)" "id:172,\
        phase:3,\
        capture,\
        pass,\
        log,\
        msg:'Test DNSBL: last_seen=%{tx.1} severity=%{tx.2} category=%{tx.3}'"
```

HTTP Response:
```
curl -v 'http://localhost/test'
> GET /test HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: openresty/1.13.6.2
< Date: Tue, 31 Jul 2018 08:18:42 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-DNSBL: 127.1.10.3
...
```
Test log:
```
Tue Jul 31 10:18:42 2018 [172] Test DNSBL: last_seen=1 severity=10 category=3
```

I'm just a little bit worried about performance... Maybe using the `@rbl` operator is more performant and easy than all this.

**Comment by p0pr0ck5** [comment]
Using @rbl with Nginx is a terrible idea, because the worker process is blocked on the socket read. It will ruin performance.

**Comment by theMiddleBlue** [comment]
thanks @p0pr0ck5. the only problem I see using `resty.dns.resolver` is that it hasn't any caching mechanism and it sends a DNS query on each request (unlike `@rbl` that uses his cache).

**Comment by p0pr0ck5** [comment]
rbl uses cache?

Also, writing a cache wrapper is trivial work, and there are existing clients like https://github.com/Kong/lua-resty-dns-client. 

Anything in libmodecurity that involves communicating with external services natively will wreck your throughput. Until there’s a method override mechanism that allows it to hook into an existing event loop, id very strongly discourage using it in nginx/openresty.

**Comment by theMiddleBlue** [comment]
thanks for the advice. I'll try `lua-resty-dns-client`, at the moment, in my script, I'm caching all DNS query using `ngx.shared.DICT` and it seems to work fine, but I don't know how it could affect performances. Probably is better to use `lua-resty-dns-client` instead to reinvent the wheel.

**Comment by zimmerle** [comment]
ModSecurity version 2 saves a verbose string with all the matching details. Like the example below:

https://github.com/SpiderLabs/ModSecurity/blob/49495f1925a14f74f93cb0ef01172e5abc3e4c55/apache2/re_operators.c#L3719-L3720

In version 3 we just have the matching ip address:

https://github.com/SpiderLabs/ModSecurity/blob/065c2e67b64656e1db0026c3f3307d7ee3cddd6f/src/operators/rbl.cc#L226-L227

It seems like @theMiddleBlue found another way to do the checking which is more suitable to what he needs. Therefore I am going to call this issue as closed. Please re-open if you think otherwise.

**Comment by celesteking** [comment]
Can we have docs updated with what match goes where? What happens if RBL returns 127.1.2.3 , what ends up in what var? tx.0? tx.1?

**Comment by mhoran** [comment]
@zimmerle this seems to break https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/46171c0ef335f92b26787ce269e397c480286155/rules/REQUEST-910-IP-REPUTATION.conf#L168-L171. While pointed out in this thread that there is a performance penalty to the `@rbl` check in nginx, I still spent a few hours trying to track down why this didn't work.

Perhaps the `@rbl` rules should be removed from `REQUEST-910-IP-REPUTATION.conf`, since this no longer seems possible to implement in version 3?

**Comment by theseion** [comment]
I don't understand the rational behind this change. It is now no longer possible to determine the type of threat for which an IP was listed, which means I can only use `@rbl` to block unconditionally. The CRS rules make a nice distinction between the different categories and I really don't want to block search IP's for example.

A fix would be trivial in my opinion: simply put the fake encoding IP into `TX:0` instead of the IP (which is in `TX:REAL_IP` anyway). Then rules can match whatever they like. That would make it easy to adapt the existing rules.

I agree with @mhoran: if the `@rbl` rules are so bad, then they should be removed or at least it should be documented accordingly.

I vote to reopen this issue.
