### ISSUE TITLE
The dependencies of ModSecurity should be updated.

### ISSUE THREAD

**Issue by hsluoyz** [SpiderLabs/ModSecurity#1848]
I'm building ModSecurity against Windows 10, but the following dependencies has already been deprecated for long time. For example, VS2008 has long be deprecated and is even hard to find and download from the Internet. Until Jul 25th, 2018, the dependency state is:

Dependency | Current | Latest
----|----|----
Visual Studio | 2008 | 2017
CMake | v2.8.0 | v3.12.0
Apache | 2.2.17 | 2.4.34
PCRE | v8.12 | PCRE is v8.42, PCRE2 is v10.31
LibXML2 | v2.7.7 | v2.9.8
Lua | v5.1.4 | v5.3.5
cURL | v7.21.4 | v7.61.0

The second argument is that new version compilers and libraries can bring better performance, and performance is critical to ModSecurity.

So I believe this project should move on to up-to-update dependencies. It may involve the compatibility issue for other platforms too. But I think this has to be done sooner or later.

```
PREREQUISITES:

    Microsoft Visual Studio C++                                                     tested with Visual Studio 2008 (aka VC9)

    CMake build system from:   http://www.cmake.org/                                tested with CMake v2.8.0

    Apache 2.2.x  from:        http://httpd.apache.org/                             tested with Apache 2.2.17
        Apache must be built from source using the same Visual Studio compiler as mod_security.

    PCRE  Perl Compatible Regular Expression library from: http://www.pcre.org/     tested with PCRE v8.12

    LibXML2 from: http://xmlsoft.org/                       tested with LibXML2 v2.7.7
        Note that LibXML2 v2.7.8 does not build correctly for Windows

    Lua Scripting Language from:  http://www.lua.org/       tested with Lua v5.1.4

    cURL multiprotocol file transfer library from: http://curl.haxx.se/             tested with cURL v7.21.4
```

**Comment by victorhora** [comment]
Hi @hsluoyz,

Just prior to the 2.9.2 release last year we did a refactory of the build process and all the dependencies. See https://github.com/SpiderLabs/ModSecurity/commit/1e8b4669eb2d8825d8fdf86fdd638b807942b123.

The [2.9.2 IIS release binaries](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.2) uses the following dependencies:

Dependency | Version 
----|----|
Visual Studio | 2013
CMake | v3.8.2
Apache | 2.4.27
PCRE | v8.40
LibXML2 | v2.9.4
Lua | v5.3.4
cURL | v7.54
ZLib | 1.2.11
YAJL | 2.1.0
SSDEEP | 2.13

The list can be verified here: https://github.com/SpiderLabs/ModSecurity/blob/v2/master/iis/build_dependencies.bat
 
The [howto.txt](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/iis/dependencies/howto.txt) file was also updated to state the dependencies which are known to work with ModSecurity 2.9.x IIS build.

We plan to do yet another refresh of those dependencies to their latest versions prior to the next 2.9.x release, but in the meantime you are more than welcome to do your own build and let us know if you run into issues with the dependencies that we can try to help :)

Unfortunately the [README_WINDOWS.TXT](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/README_WINDOWS.TXT) is outdated. We'll try to get up to date prior to the 2.9.3 release. In the meantime, use [howto.txt](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/iis/dependencies/howto.txt) as reference for building.

**Comment by victorhora** [comment]
Dependencies list updated at https://github.com/SpiderLabs/ModSecurity/commit/e0a087b54036537f1145e86a602094d8a3d2933f

Thanks for your contribution :)
