### ISSUE TITLE
redirect action on libModSecurity is relying upon SecDefaultAction by default

### ISSUE THREAD

**Issue by victorhora** [SpiderLabs/ModSecurity#1850]
It seems like the [redirect](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#redirect) action on the [current master](https://github.com/SpiderLabs/ModSecurity/commit/eed6b5f86d00ce7d6bf5e14d6f03647bafd6251d) is behaving differently from ModSecurity v2.

When investigating an issue it was found that in order for the action to work as intended, on my environment, it was mandatory for the rule writer to specify the actual [status code](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#status) for the redirect in the form of:

```
SecRule REQUEST_URI "@contains /administrator" "id:2000001,\
phase:1,\
log,\
status:301,\
redirect:'http://1.1.1.1/failed.html',\
t:none,\
msg:"Unauthorized administrator request'"
```

One could expect that by simply adding the [redirect](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#redirect) action and omitting the status code libModSecurity would still trigger the 302 by default when the action is initialized [here](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/actions/disruptive/redirect.cc#L31-L34) but instead it's triggering the [SecDefaultAction](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecDefaultAction) defined for the phase on which the rule is running even without specifying the [block](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#block) action.

**Comment by prince-java** [comment]
How about add a disruptive action to this rule, such as 'deny'?

**Comment by zimmerle** [comment]
Fixed :)
