### ISSUE TITLE
Is there a timeline when building ModSecurity 3.x on Windows will be provided?

### ISSUE THREAD

**Issue by hsluoyz** [SpiderLabs/ModSecurity#1851]
I'm a Windows user. As the README (https://github.com/SpiderLabs/ModSecurity/blob/v3/master/README.md) said: 

``Windows build is not ready yet.``.

I found that it has been nearly one year since the first release of ``v3.0.0-rc1``, when will Windows build be provided? Thanks.

**Comment by victorhora** [comment]
Hi @hsluoyz 

Indeed, Windows is not officially supported for building ModSecurity at this point. I'd say this is mostly due the fact we didn't had much traction on attempts to start working on a connector for IIS which would probably be the main reason why people would like to have the library compiled for Windows.

This means that even if you get ModSecurity compiled for your Windows environment you probably would only be able to use it with either NGINX ([ModSecurity-nginx connector](https://github.com/SpiderLabs/ModSecurity-nginx)) or Apache ([ModSecurity-apache connector](https://github.com/SpiderLabs/ModSecurity-apache)) and not with Microsoft IIS.

That being said If you would still like to see libModSecurity for Windows, I can see an attempt of [preliminary support here](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/unique_id.cc#L19-L22). I honestly  haven't tried this myself but you are more than welcome to try compiling on Windows and let us know of possible problems you're facing and the community should be able to support you as time permits :)

Thanks.

**Comment by jayanth-ganganahalli** [comment]
Hi,
I am trying to build mod_security v3.0.3 on windows machine. Is there a way to compile the source code? Please help.

**Comment by zimmerle** [comment]
Hi @jayanth-ganganahalli,

There are some pieces of system-dependent software that needs to be written (or changed) in order to get it compiled for windows. Other than those small pieces it should compile fine with any c++11 env.

**Comment by jayanth-ganganahalli** [comment]
Hi @zimmerle 
Thanks for your quick reply.
Can I know what changes I should do in order to compile v3.0.3 source code?

**Comment by zimmerle** [comment]
> Hi @zimmerle
> Thanks for your quick reply.
> Can I know what changes I should do in order to compile v3.0.3 source code?

Don't know all of them by heart, but there is some platform dependent code already here:
https://github.com/SpiderLabs/ModSecurity/blob/d5b93c1013ca9c9a96c75369576b54832e9a2b48/src/utils/system.cc#L126-L131

Windows build was considered from the initial development process, so it was somewhat compartmentalized to allow an easy change whenever we manage to step forward on that direction. You are more than welcome to help us with that journey. 

Most of the platform-dependent code is part of the utils directory -
https://github.com/SpiderLabs/ModSecurity/search?q=__OpenBSD__&unscoped_q=__OpenBSD__

**Comment by mguinness** [comment]
Issue https://github.com/SpiderLabs/ModSecurity/issues/2480 contains the following comment that sounds hopeful.

> That is good to hear. We are aiming not only to have it working for Nginx / Apache on windows **but also IIS**.

**Comment by zimmerle** [comment]
@mguinness We are waiting to hear the feedback form @gianks on the issue #2480. The first step is to have the ModSecurity library compiled on Windows. @gianks is working on it.

**Comment by fir3wall** [comment]
Hello @zimmerle 

Are there is any update or plan of action for Windows builds ?
