### ISSUE TITLE
Compile from live upstream error

### ISSUE THREAD

**Issue by spacerunner5** [SpiderLabs/ModSecurity#1853]
I can compile a live upstream version of mod_security v3 "by hand" using git clone, build.sh, ./configure, make etc. However, wrapping it into a gentoo ebuild package throws the following error:

*** No rule to make target '../../src/.libs/libmodsecurity.a', needed by 'modsec-rules-check'.  Stop.

Build log is at [https://pastebin.com/SQMxL2Lt](https://pastebin.com/SQMxL2Lt)

what could be wrong?

**Comment by victorhora** [comment]
@ste7677, are you the maintainer of libModSecurity within Gentoo?

I think this have something to do with the way that Gentoo is building the package. What's probably happening there is that the Makefile is failing to run here:  https://github.com/SpiderLabs/ModSecurity/blob/v3/master/tools/rules-check/Makefile.am#L9

This means that probably all other examples/tools will fail to compile successfully as they all use the same $(top_builddir) path:

```
/tools/rules-check/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./test/benchmark/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./test/benchmark/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./test/fuzzer/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./test/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./test/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./test/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./examples/reading_logs_via_rule_message/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./examples/reading_logs_with_offset/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
./examples/using_bodies_in_chunks/Makefile.am:	$(top_builddir)/src/.libs/libmodsecurity.a \
```

You could probably get away around the build error by specifying `./configure --enable-examples=no --with-yajl=no`  to forcefully disable building the examples and the Test Utilities (which relies on YAJL) but then you would not have JSON support as --with-yajl=no disables JSON support as well but as of now, there's no specific flag to disable only the Test Utilities.

Other than that, I would suggest double checking Gentoo ebuild best practices to make sure you're not missing anything when trying to build the package.

**Comment by spacerunner5** [comment]
@victorhora, No, I am not the maintainer. Unfortunately, according to [https://packages.gentoo.org/packages/www-apache/mod_security](https://packages.gentoo.org/packages/www-apache/mod_security) the package needs a new maintainer. 

Currently, only 2.x branch is supported in gentoo packages. That' why I try to modify an ebuild to be able to use the 3.x branch as well as upstream.

The lastest 2.x package available on gentoo seems to work (2.9.1-r1).

**Comment by spacerunner5** [comment]
1. Narrowed it down. Following your advice on [Installing from source on Ubuntu](https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x#ubuntu-1504) will **fail too** as soon as I configure with

./configure --disable-static

any advice possible?

2. Is documentation on compile options for libmodsecurity available somewhere?

**Comment by zimmerle** [comment]
Hi @ste7677,

You can use the ```./configure --help``` to have all the compilation options listed, including its description.

I miss in your build the ***.a*** generation. As of 16ab99ce3e23ca5953a07bba3a45fa70c6227c13 we are using the ***.la*** instead. You should be fine.
