### ISSUE TITLE
Reformat ModSecurity 2.x's README in Markdown

### ISSUE THREAD

**Issue by hsluoyz** [SpiderLabs/ModSecurity#1857]
I'm new to this project and I want to learn it. But the first thing I encountered is that the format of the README hurts my eyes :( Markdown is a neutral and de-facto dominating standard for open-source intro pages. It is not only useful in GitHub but also other places. So I think we should delete TXTs and use Markdown instead.

I saw ModSecurity 3.0 already uses Markdown, it's a good thing. However, ModSecurity 2.x still has many users. My team believes ModSecurity 3.0 is not mature enough for now: there are still many bugs and the performance cannot reach 2.x temporarily. Moreover, ModSecurity 3.0 is not available on Windows but I'm a Windows user :(.

So we think ModSecurity 2.x and 3.0 will coexist for some time. And it's still necessary to improve 2.x if there's some kind of needs. What do you think? Thanks.

Update:
----

I already made a PR: https://github.com/SpiderLabs/ModSecurity/pull/1856. Please review it. Thanks!

**Comment by hsluoyz** [comment]
BTW, I already sent an issue about the deprecated dependency for 2.x here: https://github.com/SpiderLabs/ModSecurity/issues/1848. And that issue seems to be assigned now. Fixing it will need to update the README. But the original README doesn't have a good format. This is why this issue (and PR) comes :)

**Comment by victorhora** [comment]
Fixed as of https://github.com/SpiderLabs/ModSecurity/commit/e0a087b54036537f1145e86a602094d8a3d2933f

Thanks for your contribution :)
