### ISSUE TITLE
How to inspect the content of the file which is being uploaded

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#1858]
SecRule REQUEST_BODY "@contains eval" "chain,phase:2,block,log,id:100023"
SecRule REQUEST_BODY "@contains base64_decode"

I want to Intercept the file being uploaded which contains 'eval' and 'base64_decode',but it does't work.
SecRequestBodyAccess has been set to on.

**Comment by victorhora** [comment]
Note the following from the [Reference Manual](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#REQUEST_BODY):


> REQUEST_BODY
> Holds the raw request body. This variable is available only if the URLENCODED request body processor was used, which will occur by default when the application/x-www-form-urlencoded content type is detected, or if the use of the URLENCODED request body parser was forced.
> 
> SecRule REQUEST_BODY "^username=\w{25,}\&password=\w{25,}\&Submit\=login$" "id:43"
> 
> As of 2.5.7, it is possible to force the presence of the REQUEST_BODY variable, but only when there is no request body processor defined using the ctl:forceRequestBodyVariable option in the REQUEST_HEADERS phase.


Depending on your request you might need to have a rule at a previous phase (e.g. phase:1) to forcefully fill the [REQUEST_BODY](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#REQUEST_BODY) variable a with [ctl:forceRequestBodyVariable=on](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#ctl) action.
