### ISSUE TITLE
How to hide header in modsec_audit log

### ISSUE THREAD

**Issue by appop** [SpiderLabs/ModSecurity#1862]
We have token in header, when there have an error, all header print in log, So how to hide this ?

**Comment by victorhora** [comment]
Try tuning with the [SecAuditLogParts](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogParts) directive.

For straight usage questions, please use [mod-security-users](https://sourceforge.net/projects/mod-security/lists/mod-security-users) mailing list. Thanks!
