### ISSUE TITLE
Can not get information from MLogC request

### ISSUE THREAD

**Issue by mcardoso27** [SpiderLabs/ModSecurity#1863]
Hi, I'm doing a service to store ModSecurity Logs to MongoDB. I have installed ModSecurity 2.9.2 and Apache on Ubuntu 18.04 via apt. I'm using node with express and typescript, when I want to get the information transaction of the request, I found that body, params and query are empty.

From this code:

```
    public auditReceiver(req: Request, res: Response) {

        console.log('req.body ======', req.body);
        console.log('req.params ======', req.params);
        console.log('req.query ======', req.query);
        console.log('req.headers ======', req.headers);
        console.log('req.rawHeaders ======', req.rawHeaders);
        console.log('REQUEST', req);

        res.json(req.body);
    }
```

I have this output:

> req.body ====== undefined
req.params ====== {}
req.query ====== {}
req.headers ====== { host: 'localhost:3000',
  authorization: 'Basic U0VOU09SX1VTRVJOQU1FOlNFTlNPUl9QQVNTV09SRA==',
  accept: '*/*',
  'x-content-hash': 'md5:0b866366330a4815964e0619a3710280 ',
  'x-forensiclog-summary':
   'localhost ::1 - - [31/Jul/2018:23:02:51 --0300] "GET /mutillidae/index.php?page=user-info.php&username=%27+or+true+--+&password=mypassword&user-info-php-submit-button=View+Account+Details HTTP/1.1" 200 10031 "-" "-" W2EUy-3PXE5dtDVi7TfhqwAAAAE "-" /20180731/20180731-2302/20180731-230251-W2EUy-3PXE5dtDVi7TfhqwAAAAE 0 80030 md5:0b866366330a4815964e0619a3710280 ',
  'content-length': '80030' }
req.rawHeaders ====== [ 'Host',
  'localhost:3000',
  'Authorization',
  'Basic U0VOU09SX1VTRVJOQU1FOlNFTlNPUl9QQVNTV09SRA==',
  'Accept',
  '*/*',
  'X-Content-Hash',
  'md5:0b866366330a4815964e0619a3710280 ',
  'X-ForensicLog-Summary',
  'localhost ::1 - - [31/Jul/2018:23:02:51 --0300] "GET /mutillidae/index.php?page=user-info.php&username=%27+or+true+--+&password=mypassword&user-info-php-submit-button=View+Account+Details HTTP/1.1" 200 10031 "-" "-" W2EUy-3PXE5dtDVi7TfhqwAAAAE "-" /20180731/20180731-2302/20180731-230251-W2EUy-3PXE5dtDVi7TfhqwAAAAE 0 80030 md5:0b866366330a4815964e0619a3710280 ',
  'Content-Length',
  '80030' ]

If I don't use MLogC to sending ModSecurity Logs, and I store the logs in my computer, the logs stored correctly in JSON format.

> {
  "transaction": {
    "time": "29/Jul/2018:23:08:48 --0300",
    "transaction_id": "W15zMFo53pU9Z6TkGwH3IQAAAAA",
    "remote_address": "::1",
    "remote_port": 40354,
    "local_address": "::1",
    "local_port": 80
  },
  "request": {
    "request_line": "POST /mutillidae/index.php?page=login.php HTTP/1.1",
    "headers": {
      "Host": "localhost",
      "Connection": "keep-alive",
      "Content-Length": "64",
      "Cache-Control": "max-age=0",
      "Origin": "http://localhost",
      "Upgrade-Insecure-Requests": "1",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Referer": "http://localhost/mutillidae/index.php?page=login.php",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "es-US,es;q=0.9,es-419;q=0.8,en;q=0.7",
      "Cookie": "showhints=1; PHPSESSID=6sjj69dmurcdcc6dqqi4l49f72"
    },
    "body": [
      "username=%27+or+true+--+&password=&login-php-submit-button=Login"
    ]
  },
  "response": {
    "protocol": "HTTP/1.1",
    "status": 403,
    "headers": {
      "Content-Length": "304",
      "Keep-Alive": "timeout=5, max=100",
      "Connection": "Keep-Alive",
      "Content-Type": "text/html; charset=iso-8859-1"
    },
...and continuous well...
 

Which part of the request should I analyze to get all the information? Or where can I get documentation about how MLogC makes the request?

PD: here is the code, https://github.com/mcardoso27/audit-log-receiver-modsecurity

**Comment by victorhora** [comment]
Have you tried tuning [SecAuditLogParts](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogParts)? 

Can you try including type "C" in the [default](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/modsecurity.conf-recommended#L187) and also double checking that [SecRequestBodyAccess](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRequestBodyAccess) is enabled to see if it makes any difference?

MLogC is not very well documented. If you need more information, your best bets would be going over the [INSTALL](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/mlogc/INSTALL), and [mlogc-default.conf](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/mlogc/mlogc-default.conf) files or digging into the code at [mlogc.c](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/mlogc/mlogc.c).

I've added a sample MlogC request that contains body, headers etc on a Gist [here](https://gist.github.com/victorhora/1b51986c1627b8b62717de7898daed40). As far as I can tell, [this JSON is valid](https://jsoneditoronline.org/?id=7ec0e9c045d7475dbf23104fdc10fdf0) and one should be able to get the body content by parsing the JSON looking for the _"body"_ object.

**Comment by victorhora** [comment]
I'm closing this one as it doesn't seem to be a bug with ModSecurity or MlogC. Let us know if you think otherwise.

By the way, you may consider using libModSecurity with the [HTTP transport](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType) to send the logs to your storage service to make it future proof as MlogC will not be supported for ModSecurity v3 ;)

**Comment by mcardoso27** [comment]
Thank you! I'll keep this in mind, anything you notice.
