### ISSUE TITLE
Mod Security is not detecting XSS.

### ISSUE THREAD

**Issue by Vaibhavgoe** [SpiderLabs/ModSecurity#1864]
We have configured dvwa application protecting with modsecuirty. But there is one XSS is not detecting by mod secuirty. the signature is /vulnerabilities/view_source.php?id=%22%3e%3cA+%3d%22%2fWF_XSRF1894.html%22%3einjected+link%3c%2fA%3e.
Other XSS are blocking by mod security.

Can anyone help, how to protect it with this type of signature

**Comment by victorhora** [comment]
@Vaibhavgoe, 

Please bear in mind that ModSecurity is the WAF engine. You need to have proper rules set and configured for protection agains web attacks such as XSS. For to 

From your report, I'm guessing you might be using the [Core Rule Set](https://github.com/SpiderLabs/owasp-modsecurity-crs). If that's the case, I highly suggest you to read the documentation on how to properly configure and tune the rules available here: https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/INSTALL

Particularly, I'm pretty sure that if you [raise your paranoia level](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/crs-setup.conf.example#L130-L177) from the default of "_1_" to "_2_" or higher you should get ModSecurity triggering this XSS.

If you have any further question concerning using the rules, please direct them at OWASP CRS (mailing list / Slack) and the community will support you.
