### ISSUE TITLE
Installable package

### ISSUE THREAD

**Issue by bellaxie** [SpiderLabs/ModSecurity#1873]
Hi there,

Is it possible to provide a installable package on Ubuntu so it can be installed via apt-get?

**Comment by victorhora** [comment]
Yes there is: https://packages.ubuntu.com/artful/libapache2-modsecurity

But this is for version [2.9.1](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.1) (March/2016).

If you're using Nginx, I recommend going for libModSecurity 3.x ("3.0.3-pre"). You can follow the installation instructions here: https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

If you're stuck with Apache for any reason, I would recommend going for at least [2.9.2](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.2) (or "2.9.3-pre"). These steps should suffice to compile 2.9.x: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#Installation_for_Apache

**Comment by bellaxie** [comment]
Hi victorhora, thanks for the info, I'm using Nginx, and I've followed the instruction to install libModSecurity 3 manually. The reason I'm asking for an apt package is because I want to automate the installation thru Puppet, compiling from source on each target machine doesn't sound a very good idea...

**Comment by victorhora** [comment]
Hi @bellaxie, I understand you're looking for a libModSecurity (3.x) Ubuntu/Debian package right?

In this case I would suggest getting in touch with the maintainer (@inittab) of the ModSecurity packages for those distros to see if this is possible at this time. 

@inittab let us know if you need our support in some way :)

Cheers

**Comment by inittab** [comment]
Hi! I'll look into creating those packages as soon as I return from vacation (couple of weeks). Thanks for the help offer @victorhora , I'll let you know if I need a hand with them (or at least a second opinion). Cheers!

**Comment by luckyraul** [comment]
@inittab Hi, any updates about these packages?

**Comment by inittab** [comment]
Hi, I uploaded the first packaging to Debian Sid some weeks ago, but the build daemons are failing to build them, some tests fail in some archs. Here's my call for help on the packagers list:
https://sourceforge.net/p/mod-security/mailman/mod-security-packagers/?viewmonth=201810
Still working on it.
Oh, and the packaging repo:
https://salsa.debian.org/agi/modsecurity
