### ISSUE TITLE
Missing @ in !ipMatch

### ISSUE THREAD

**Issue by edwingustafson** [SpiderLabs/ModSecurity#1874]
You probably want an @ before ipMatch in example usage for SecConnWriteStateLimit.

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#secconnwritestatelimit

**Comment by victorhora** [comment]
@edwingustafson, we are in the process of some major updates to the documentation to better reflect supported features and to make it easier to update the manual, so you can expect better overall documentation soon :)

In the meantime, I've changed the docs to update the change you have suggested. Thanks for your contribution :)

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)/_history
