### ISSUE TITLE
SecServerSignature is not supported

### ISSUE THREAD

**Issue by cyberblackhole** [SpiderLabs/ModSecurity#1880]
I'm using 

Apache/2.4.29 (Ubuntu). 
modsecurity v3.0.2.

When I use `SecServerSignature "some server name and version"`.

```
<IfModule security3_module>
                modsecurity_rules 'SecServerSignature "some server name and version"'

```
I get the below error

`SecServerSignature is not supported`

Is there an alternative for this?.

**Comment by victorhora** [comment]
@Goron1606 

As stated on the reference manual [SecServerSignature](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecServerSignature) is not implemented on v3.

Also, I see this feature as highly reliant on the connector to do the proper interfacing, so I guess it will take some time until we can get it done.

Unless you have a specific use case scenario for this, you should be fine by using the [headers_more](https://www.nginx.com/resources/wiki/modules/headers_more/#name) extension of Nginx to change the "Server" header. I believe you can probably do the same with Apache or other webservers.
