### ISSUE TITLE
SecStreamOutBodyInspection/SecStreamInBodyInspection is not supported.

### ISSUE THREAD

**Issue by cyberblackhole** [SpiderLabs/ModSecurity#1882]
Hello,

Am using
- Apache/2.4.29 (Ubuntu)
- modsecurity v3.0.2

When I use **STREAM_OUTPUT_BODY** and run configtest I get the below error message
`SecStreamOutBodyInspection is not supported.`

Is there any alternative?

**Comment by victorhora** [comment]
The [RESPONSE_BODY](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#RESPONSE_BODY) variable should allow you to inspect the output body.
