### ISSUE TITLE
Tweaking rules

### ISSUE THREAD

**Issue by dmarlow** [SpiderLabs/ModSecurity#1893]
Sorry if it's been asked before. I'm looking to tweak some rules and want to make sure I understand things and my reasoning is sound.

I'm using 2.9.2 on IIS 10 and am looking at this rule, for example:
```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*|!REQUEST_HEADERS:via "(?i:\b(?:coalesce\b|root\@))" \
        "phase:2,rev:'2',ver:'OWASP_CRS/2.2.9',maturity:'9',accuracy:'8',capture,t:none,t:urlDecodeUni,ctl:auditLogParts=+E,block,id:'950908',msg:'SQL Injection Attack.',logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',tag:'OWASP_CRS/WEB_ATTACK/SQL_INJECTION',setvar:'tx.msg=%{rule.msg}',setvar:tx.sql_injection_score=+%{tx.critical_anomaly_score},setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/SQL_INJECTION-%{matched_var_name}=%{tx.0}"
```

If I don't want request cookies or headers inspected, just the args and body, can I simply strip out the parameters in the rule such that it looks like this now?

```
SecRule ARGS_NAMES|ARGS|XML:/* \
        "phase:2,rev:'2',ver:'OWASP_CRS/2.2.9',maturity:'9',accuracy:'8',capture,t:none,t:urlDecodeUni,ctl:auditLogParts=+E,block,id:'950908',msg:'SQL Injection Attack.',logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',tag:'OWASP_CRS/WEB_ATTACK/SQL_INJECTION',setvar:'tx.msg=%{rule.msg}',setvar:tx.sql_injection_score=+%{tx.critical_anomaly_score},setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/SQL_INJECTION-%{matched_var_name}=%{tx.0}"
```

We get a lot of false positives via request cookies and headers and wish to only consider certain rules for certain sources.

Thanks!

**Comment by dmarlow** [comment]
Or better yet.. is there a "minimum" or "lite" version of the rules to start out with?

**Comment by victorhora** [comment]
Hi @dmarlow,

Yes, your reasoning is correct, but I have a few recommendations for you:

* Upgrade your version of the OWASP CRS. From your rules, it seems like you are using version 2.2.9. This is now deprecated and users of this version are highly encouraged to move to CRS 3.x. See https://modsecurity.org/crs/ for more info on CRS 3 and check the [INSTALL file](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/INSTALL).

* If you still need to change CRS to fit your needs I would recommend using the [SecRuleUpdateTargetById](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRuleUpdateTargetById) (and cousins) to change the targets. This is a best practice which among other things would allow you to keep your customizations even when there are rule updates.

If you have more questions or concerns regarding OWASP CRS, please direct them at the CRS project here: https://github.com/SpiderLabs/owasp-modsecurity-crs

Thanks.

**Comment by dmarlow** [comment]
@victorhora thanks for the information. One last (stupid) question. Can I run on version 2.9.2 and target a higher rule set? I was always under the assumption that I had to wait to upgrade before using newer rule sets.

**Comment by dmarlow** [comment]
If I would have just looked past the first 2 sentences of the pages you sent, I would have found this nugget:

>  CRS is designed to be used with ModSecurity (although many other
>  projects also use the provided rules). CRS version 3.x is designed for
>  ModSecurity 2.8 or above.

**Comment by victorhora** [comment]
1) Your question is not stupid :)

2) I was about to answer your question when I saw your latest comment. So it seems like all is good on that area :)

Good luck ;)
