### ISSUE TITLE
ModSecurity installer issues

### ISSUE THREAD

**Issue by dmarlow** [SpiderLabs/ModSecurity#1894]
I'm going to try a work-around, but wondering if there's an issue with the installer. Here's the scenario:

I use Azure Cloud Services and install a specific .NET version, then install ModSecurity. It sometimes works, sometimes not. When it doesn't work, everything just hangs. The installer doesn't ever exit and the VM gets stuck in a strange provisioning state. Here's what the ModSecurity installer log looks like:

Though when I log in to the VM, there isn't anything else running. I'm going to try re-ordering the installation so ModSec goes first, but in case any one else runs across this, maybe there's an issue with the ModSec installer not retrying or not exiting properly?

```
=== Verbose logging started: 9/10/2018  18:48:41  Build type: SHIP UNICODE 5.00.10011.00  Calling process: D:\Windows\system32\msiexec.exe ===
MSI (c) (30:78) [18:48:41:618]: Resetting cached policy values
MSI (c) (30:78) [18:48:41:618]: Machine policy value 'Debug' is 0
MSI (c) (30:78) [18:48:41:618]: ******* RunEngine:
           ******* Product: E:\approot\bin\Startup\ModSecurityIIS_2.9.2-64b.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (30:78) [18:48:41:618]: Client-side and UI is none or basic: Running entire install on the server.
MSI (c) (30:78) [18:48:44:759]: Failed to grab execution mutex. System error 258.
MSI (c) (30:78) [18:48:44:962]: Cloaking enabled.
MSI (c) (30:78) [18:48:44:962]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (30:78) [18:48:44:978]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (c) (30:78) [18:48:44:978]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (30:78) [18:48:45:368]: MainEngineThread is returning 1618
=== Verbose logging stopped: 9/10/2018  18:48:45 ===

MSI (s) (50:90) [18:49:31:150]: User policy value 'DisableRollback' is 0
MSI (s) (50:90) [18:49:31:150]: Machine policy value 'DisableRollback' is 0
MSI (s) (50:90) [18:49:31:150]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (50:90) [18:49:31:150]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (50:90) [18:49:31:150]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (50:90) [18:49:31:150]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (50:90) [18:49:31:150]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (s) (50:90) [18:49:31:150]: Post-install cleanup: removing installer file 'D:\Windows\Installer\3922.mst'
MSI (s) (50:90) [18:49:31:150]: Destroying RemoteAPI object.
MSI (s) (50:BC) [18:49:31:150]: Custom Action Manager thread ending.
```

**Comment by dmarlow** [comment]
Forgot to mention: IIS 10 on Windows Server 2016.

**Comment by victorhora** [comment]
I believe this is related with having either simultaneous installation process running at the same time or for some reason (which is outside of our control) the installer executable (msiexec.exe) is still running in the background between installs (either of the same package or different MSIs).

A reboot or killing msiexec.exe process prior to running the installer should fix the issue. See https://kb.acronis.com/content/56544 for more reference of this error.

Maybe this is a bug with the WIX installer itself. We'll try to use a newer version of the installer for the next 2.9.x release (2.9.3) to see if it solves this issue.

Thanks for the report.
