### ISSUE TITLE
Storage path seems not work for AuditLogType HTTPS

### ISSUE THREAD

**Issue by mcardoso27** [SpiderLabs/ModSecurity#1896]
Hi, im using the v3.0.2 of ModSecurity and ModSecurity-Apache v0.1.1-beta for connection. I'm using SecAuditLogType HTTPS and I am able to receive the request with transaction information into the server. When everything is OK, the server storage the transaction, but when something goes wrong the server doesn't response with 200 status (it responses 400 or 500), however ModSecurity doesn't storage the audit log anywhere. It seems that ignore the SecAuditLogStorageDir directive.
Also, looking for errors in Apache error.log file, I didn't find anything.

This is the audit log configuration in modsecurity.conf:
> SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType HTTPS
SecAuditLog http&#58;//localhost:3000/audit-receiver
SecAuditLogStorageDir /opt/modsecurity/var/audit/
SecAuditLogFormat JSON

Where can i look for the missing audit logs? Or some kind of error logs like those the generate by mlogc in mlogc-error.log?

**Comment by victorhora** [comment]
@mcardoso27 

When using the HTTPS transport for audit logs, your Debug Logs should show something like "_Sending logs to:_ " <URL>" ([https.cc#L51](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/audit_log/writer/https.cc#L51)) prior to sending the logs.

If there's an error, you should see something like "_Cannot save the audit log:_ <errormsg>" ([audit_log.cc#L319](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/audit_log/audit_log.cc#L319)) on your Debug Logs.

As of now the [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType) directive only supports saving the logs to a single place. If you choose HTTP it will assume that your receiving server will be available and responding with 200 status. As far as I know, audit logs won't be saved elsewhere if your receiving end fails to store them.

You can see how the HTTPS writer uses cURL here: [HttpsClient::download()](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/utils/https_client.cc#L63-L124)
