### ISSUE TITLE
Can we use new CRS rules against Modsecurity version 2.9.2 ?

### ISSUE THREAD

**Issue by muzammel111** [SpiderLabs/ModSecurity#1902]
Respected Support,

I am currently using the modsecurity version 2.9.2, i want to update CRS rules to gain more protection benefits, can i simply update CRS rules using git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git Or i need to upgrade modsecurity version to 3.0.2 before rules upgrade ?. Please guide is there any conflict or compatibility issue.

Regards,
Muzi

**Comment by victorhora** [comment]
Yes, it should work. You can follow the installation steps described in the [INSTALL file of the CRS project](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/INSTALL#L77-L227).

If you have further questions regarding CRS usage, please direct them to the CRS project.

Thanks!

**Comment by muzammel111** [comment]
Thank you so much for your support and guidance.

Thanks !
