### ISSUE TITLE
In ModSecurity 3.0, when the parameter value in the POST request is null, the parsed parameter name is incorrect.

### ISSUE THREAD

**Issue by smart0088** [SpiderLabs/ModSecurity#1904]
In ModSecurity 3.0, when the parameter value in the POST request is null, the parsed parameter name is incorrect.

The following is the specific request test data：
---------------------------------------------------------------------------------------------------------
POST /test HTTP/1.1
Host: www.test.com
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
Accept-Language: zh-CN,zh;q=0.9
Content-Length: 34
Content-Type: application/x-www-form-urlencoded

action=test1&filename=&acdir=test2

---------------------------------------------------------------------------------------------------------

When the value of the "filename" parameter is null, the POST request parameter name should be "filename", and the actual parsed parameter name is "filename="。Below is a screenshot of the modsecurity debug log：

![image](https://user-images.githubusercontent.com/1448821/45681947-67aeaf00-bb71-11e8-8b1c-45c83fc6768d.png)

**Comment by zimmerle** [comment]
fixed as of: #2197.
