### ISSUE TITLE
how libmodsecurity process keepalived http request

### ISSUE THREAD

**Issue by hbt19860104** [SpiderLabs/ModSecurity#1905]
Hi!
I use msc_new_transaction, msc_process_connection, msc_process_uri, msc_add_request_header, msc_process_request_headers, msc_append_request_body, msc_process_request_body, and use msc_transaction_cleanup when connection is disconnect. When process keepalived requests, I call msc_process_uri, msc_add_request_header ...... , repeatly. But the latter request process cost so much time i function msc_process_request_body(even more than 1 second some time). Is there some problems i use libmodsecurity functions?

Thanks a lot!

huangbt

**Comment by zimmerle** [comment]
Hi @hbt19860104,

You have to cleanup the transaction to every new transaction.  Otherwise, the variables wont be clean, leading to a massive usage of memory. Which may lead to this huge time to process a request.

**Comment by hbt19860104** [comment]
ok, thank you very much
