### ISSUE TITLE
Add "Compilation Recipe" for v3.x: Mac OSX High Sierra (10.13.x)

### ISSUE THREAD

**Issue by scottcc** [SpiderLabs/ModSecurity#1907]
Hello. There's some good instructions for compilation of the various parts on this page:

https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

I thought I'd add the steps I've found to work when using current tip-of-master branches with:

* Mac OSX 10.13.6
* nginx 1.15.3

I've done relatively minimal testing, but a suggestion to add the below SecRule appeared to work for me when I tested it. Perhaps others might find useful - I've cloned the wiki, and made the changes in the below branch for your perusal and inclusion if you wish.

Tested rule:
`SecRule ARGS:testparam "@contains test" "id:1234,deny,status:403"`

https://github.com/scottcc/ModSecurity.wiki.scottcc/blob/add-osx-10.13/Compilation-recipes-for-v3.x.md

Thanks!
./scc

**Comment by victorhora** [comment]
Hi @scottcc 

Thank you very much for your contribution.

It has been added here:

https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x#mac-osx-1013

Feel free to send over more contributions in case you have something else in hand :)

Cheers!
