### ISSUE TITLE
This version of ModSecurity was not compiled with GeoIP or MaxMind support.

### ISSUE THREAD

**Issue by nix0x00** [SpiderLabs/ModSecurity#1911]
Hi,

I am trying to install ModSec module with Nginx and for that I need GeoIP. I have installed libmaxminddb by following tar.gz installation mentioned here: https://github.com/maxmind/libmaxminddb

And then I downloaded (https://github.com/leev/ngx_http_geoip2_module) and compiled successfully, but owasp modsecurity rules is showing me this error even though I compiled it with maxmind.

`nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs-3.0.0/rules/REQUEST-910-IP-REPUTATION.conf. Line: 69. Column: 20. This version of ModSecurity was not compiled with GeoIP or MaxMind support.  in /etc/nginx/nginx.conf:62`

Please tell me how can I know if libmaxminddb was installed correctly?

**Comment by victorhora** [comment]
Which version of ModSecurity you're running? 2.9.x? 3.0.x? Notice that libMaxMind is only supported on libModSecurity (aka ModSecurity v3).

If you are running v3, make sure you have at least [v3.0.2](https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.2) or cloning from latest master.

If you are running 2.9.x, only GeoIP is supported (which is getting deprecated).

**Comment by nix0x00** [comment]
Hi, I downloaded it again and compiled, this time it's giving me a different error.

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs/rules/REQUEST-901-INITIALIZATION.conf. Line: 298. Column: 119. Expecting an action, got:  ctl:requestBodyProcessor=URLENCODED" in /etc/nginx/nginx.conf:62

**Comment by victorhora** [comment]
@nix0x00 

You are probably downloading libModSecurity 3.0.2 release? 3.0.2 doesn't support [ctl:requestBodyProcessor=URLENCODED](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#ctl).

The support for this feature was added on this commit: https://github.com/SpiderLabs/ModSecurity/commit/f999f54eda0674fe3f453bf939b9abcd2aa0290a

If you want to run the latest CRS you need to clone libModSecurity from the current master. You can follow the instructions here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29

**Comment by prajyodh** [comment]
I get the same error.
I have installed GeoIP-devel by sudo yum install GeoIP-devel
before configure and build module for nginx connector.
Modsecurity : Using v3/master
Nginx version : 1.14.1
ModSecurity-nginx : master

**Comment by victorhora** [comment]
@prajyodh 

Check if the Compilation Recipes helps you:

https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

Also check if using MaxMind instead works better. This issue might help you: https://github.com/SpiderLabs/ModSecurity/issues/2041#issuecomment-471242930

If your problem persists, please open a new issue and provide as many details as possible as per the issue template: https://github.com/SpiderLabs/ModSecurity/issues/new?template=bug-report-for-version-3-x.md

Thanks!
