### ISSUE TITLE
Incomplete pkg-config for static linking

### ISSUE THREAD

**Issue by dridi** [SpiderLabs/ModSecurity#1918]
Hello,

I tried to build the `v3/master` branch today to attempt a static linking of `libmodsecurity` in an autotools project. While this works fine, ultimately when I try to run the executable I get this:

> dlerror: undefined symbol: xmlFree

After a quick look at your `modsecurity.pc` file I realized that the private dependencies are missing. You should at least advertise `Libs.private` for linking and maybe `Requires.private` if some of your dependencies' API leak into your own headers (eg. a type from another library).

I'm only reporting this and not submitting a patch because you have optional dependencies so I'm not sure how to best piece it together.

More info on static linking and private dependencies:

https://people.freedesktop.org/~dbn/pkg-config-guide.html#writing

cc @gquintard

**Comment by victorhora** [comment]
Hey @Dridi 

Thanks for your report. As far as I can recall, only [PCRE is mandatory](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/build/pcre.m4#L101-L103) now.

The remainder of dependencies (GeoIP/MaxMind, libcURL, YAJL, LBMD, Lua and Ssdeep) are all optional.

That being said, I believe there should be a way to allow the .pc file to support both dynamically and statically linking. Do you want to submit a pull request? :)

**Comment by dridi** [comment]
I can't promise a patch, but I would definitely help review it.

**Comment by victorhora** [comment]
Sounds good. This improvement is tagged for the [3.0.4 release](https://github.com/SpiderLabs/ModSecurity/milestone/13). Thanks!
