### ISSUE TITLE
Modsecurity chain rule is not working.

### ISSUE THREAD

**Issue by ravi115** [SpiderLabs/ModSecurity#1921]
Hi,
After installing the latest modsecurity, I'm facing these below issue.

-  Rules are not working as expected (the rule is defined to prevent the brute force attack).
-  Timers are also not working.
-  comparison operator like @gt is not working as expected.

**Below is the rule defined to prevent the brute force attack**

             SecAction phase:1,id:109,pass,initcol:ip=%{REMOTE_ADDR},log
             SecRule IP:bf_block "@eq 1" "phase:1,drop,log,id:10001,msg:'IP address (%{REMOTE_ADDR}) blocked because of suspected brute-force attack'"
             SecRule REQUEST_URI "@rx ^/login/(.*)$" "phase:3,chain,t:none,log,pass,id:10002,msg:'Multiple authentication failures from IP address (%{REMOTE_ADDR})',setvar:ip.bf_counter=+1"
             SecRule RESPONSE_STATUS "401" "t:none,log"
             SecRule ip:bf_counter "@gt 5" "id:10004,t:none,setvar:IP.bf_block,setvar:!ip.bf_counter,expirevar:IP.block=60,msg:'attack'"

**Expected:**

- It should block the IP Address for 60 seconds if there is more than 5 times invalid(Response_Status: 401) login attempts.  

**Actual:**

- It is blocking the IP Address for arbitrary amount of  seconds even if there is more than 5 times of successful/unsuccessful login attempts.

----------------------------**See the below installation process and other information** -----------------

**_The installation process is as below:_**

1. apt-get install libapache2-mod-security
2. but I deleted the files and directory under /usr/share/modsecurity which basically consists some default rules and it blocking some desired operation on the server. hence deleted those file.
3. restarted the apache2 webserver.       
                    service apache2 restart.

**The modsecurity folder structure**

- /etc/modsecurity has below files:
         
                         - unicode.mapping
                         - crs
                         - modsecurity.conf

**security2.conf file configuration in  /etc/apache2/mods-available/security2.conf**

                                      
                         <IfModule security2_module>
                               # Default Debian dir for modsecurity's persistent data
                               SecDataDir /var/cache/modsecurity

                               # Include all the *.conf files in /etc/modsecurity.
                               # Keeping your local configuration in that directory
                               # will allow for an easy upgrade of THIS file and
                               # make your life easier
                               IncludeOptional /etc/modsecurity/*.conf
 
                               # Include OWASP ModSecurity CRS rules if installed
                               #IncludeOptional /usr/share/modsecurity-crs/owasp-crs.load
                        </IfModule>
                         

please help on this asap.

Thanks in advance!

**Comment by victorhora** [comment]
@ravi115 Based on your issue description, I'm assuming that "latest modsecurity" is release 2.9.2? Or you're just cloning the latest code from master (pre-2.9.3)? Bear in mind there's also libModSecurity 3.x.

I see that at one point you do ```expirevar:IP.block=60```, but I'm not seeing any other rule setting ```IP.block``` so one of your issues could be related to that.

You may want to use this as reference for what you're trying to do: https://www.trustwave.com/Resources/SpiderLabs-Blog/Defending-WordPress-Logins-from-Brute-Force-Attacks/
