### ISSUE TITLE
geoLookup fails on IPv6 address

### ISSUE THREAD

**Issue by AIM-Media-Indiana** [SpiderLabs/ModSecurity#1923]
Hello!

I am trying to get the GeoLookup working but can't seem to get a valid lookup.  Here is the debug log entry (url removed for security):

`[4] (Rule: 2000000) Executing operator "GeoLookup against REMOTE_ADDR.
 [9] Target value: "::ffff:50.235.235.226" (Variable: REMOTE_ADDR)
[4] Rule returned 0.`

Here are the results from ./config:

`ModSecurity - v3.0.2-107-gbc3d3f1 for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.0.2-107-gbc3d3f1
   + SecLang tests                                 ....bc3d3f1

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (MaxMind) v
         /usr/lib/x86_64-linux-gnu//libmaxminddb.so, /usr/include/x86_64-linux-gnu/, -DWITH_MAXMIND -I/usr/include/x86_64-linux-gnu/
      * (GeoIP) v1.6.9
         -lGeoIP, -I/usr/include/
   + LibCURL                                       ....found v7.47.0
      -L/usr/lib/x86_64-linux-gnu -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl, -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.3
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....not found

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled`

I do have a pointer to the database.  I'm using the newest free MaxMind Country database (not the .dat).  This is all running on Ubuntu 16.04 with the newest version of nginx.

I've also checked the nginx logs and they aren't showing any errors.  I'm at a loss.  It appears that maybe it's not able to parse the address correctly?

**Comment by victorhora** [comment]
@AIM-Media-Indiana 

> GeoIP/MaxMind ....found
(MaxMind) v
/usr/lib/x86_64-linux-gnu//libmaxminddb.so, /usr/include/x86_64-linux-gnu/, -DWITH_MAXMIND -I/usr/include/x86_64-linux-gnu/
(GeoIP) v1.6.9
-lGeoIP, -I/usr/include/

Both GeoIP and libMaxMind are installed on your system? If that's so, I'm wondering if there's a chance that the configure script got lost deciding which implementation to use. If it happens to use GeoIP, you could be having issues.

Double check that only -DWITH_MAXMIND is enabled on your build and that -DWITH_GEOIP is not enabled.

Also, I'm unsure if you are using 3.0.2 or the current codebase from master. Make sure that you have https://github.com/SpiderLabs/ModSecurity/commit/d97688804ee2c5fba46ff718fdc74c24eb2376cc on your codebase. Prior to this commit GeoLookup was not working with libMaxMind.

If the issue still persists, let us know and we can investigate further.
