### ISSUE TITLE
Unable to parse Content-Type header "application/json" and "application/xml" getting 400 error "Failed to parse request body"

### ISSUE THREAD

**Issue by vikasmunjal** [SpiderLabs/ModSecurity#1925]
Basically, The Content-Type header is just used as info for our application. The header is there so our app can detect what data was returned and how it should handle it. We need to look at the header, and if it's application/json then parse it as JSON. This is what we are doing with our application.

In mod security v3/master when we are sending HTTP GET requests with Content-Type header "application/json" and "application/xml", one of the mod security rule is blocking this request and throwing back the below error. I have reproduced the error and attached the screen shot of the error.
[Please click here for finding attached screenshots](https://pasteboard.co/HIA6TGy.png)
[Please click here for finding attached screenshots](https://pasteboard.co/HIA7yMG.png)

ERROR
---------------------------------------------------------
`"ModSecurity: Warning. Matched "Operator `Eq' with parameter` 0' against variable `REQBODY_ERROR' (Value:` 1' ) [file "/etc/nginx/modsec/modsecurity.conf"] [line "47"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"]"` 

This is huge block for me. Please suggest the permanent fix for this.

**Comment by zimmerle** [comment]
Hi @vikasmunjal,

Let me see if i understood correctly, you are sending a GET request, with Content-type: application/json ?

If so, you may want to disable the [request body validation](https://github.com/SpiderLabs/ModSecurity/blob/49495f1925a14f74f93cb0ef01172e5abc3e4c55/modsecurity.conf-recommended#L59-L60). If i understood correctly you are trying to give a custom use case for the headers which is leading ModSecurity to spot that.
