### ISSUE TITLE
How can i replace the returned_403_error_page with my templates in nginx

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#1926]
# desc 
I have make the `/etc/nginx/vhost/waf.conf` like this and it run well that can replace the default error-page  with common nginx error in `192.168.2.9:8080`  such as 404, 403 or 503. but it not expire with the modsec returned http status like 403 or others we made in modsec rules. 

```
    location ErrorPages {
        alias /home/error_templates/dist;
        # internal;
    }
    error_page 400 /ErrorPages/HTTP400.html;
    error_page 401 /ErrorPages/HTTP401.html;
    error_page 403 /ErrorPages/HTTP403.html;
    error_page 404 /ErrorPages/HTTP404.html;
    ...
    error_page 503 /ErrorPages/HTTP503.html;

    location / {

        proxy_pass http://192.168.2.9:8080/;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         ....
        proxy_intercept_errors on;
    }
```

**Comment by ghost** [comment]
I have tried it like this but also no use and it cant get response then.
```
SecRule RESPONSE_STATUS "@eq 403" "id:1234567403, phase:3, log, msg:'403-Error-Page-OpenResty',redirect:'https://192.168.3.2:1180/ErrorPages/HTTP403.html'"
```

**Comment by zimmerle** [comment]
Hi @actanble,

One thing there is very valuable is to enable the **DebugLogs**. It will help you to identify the rule processing details, which is useful to see the variable values, if a rule matched or not, etc....

To enable it:
```
SecDebugLog /tmp/log.txt
SecDebugLogLevel 9
```
