### ISSUE TITLE
IP collection database file ip.pag is huge, causing a slowdown

### ISSUE THREAD

**Issue by tlghacc** [SpiderLabs/ModSecurity#1928]
Hello,

I'd like to report an issue similar to #1581. The symptoms are pretty much the same - when the server gets hit by larger scale brute force attack (not a DDoS, just bots trying to guess WordPress passwords), modsecurity blocks the offenders but creates large ip.pag file in the process. As of late, the file size tends to be something above 3GB, but in the past I've seen even bigger files (8-10GB.) The file is sparse and usually has something around 10 to 20MB of real data.

When this happens, the server experiences significant load increase as tens of Apache processes constantly chew through gigabytes worth of zeroes. This requires manual intervention - generally blocking offending IP addresses in the firewall - and mostly defeats the purpose of modsecurity in this case.

The author of #1581 later blamed some Comodo rules for the situation but I believe this is not the case here. The anti-bruteforce rules we use are derived from owasp-crs DoS protection (REQUEST-912-DOS-PROTECTION), with the main difference being that instead of counting all requests to dynamic content we only count requests to login pages that fail. (Blocking is the same though, exceeding a threshold for login requests increases a burst counter, exceeding a burst threshold sets a flag in the IP collection and subsequent requests are dropped.)

I tried to look up similar problems and found a few that related to problems with expired variables. I don't believe this is the case here either - I tried modsec-sdbm-util on the database file and it reported no errors or problems. Output follows:

Database ready to be used.
 [|] 290 records so far.
Total of 291 elements processed.
0 elements removed.
Expired elements: 0, inconsistent items: 0

The output was stuck for around 10 seconds after the utility printed out the "290 records so far" - strace showed that it was read()ing through a lot of zeroes in 1024B long chunks. This is consistent with the behaviour I observed with Apache, it's caused by one or few elements that for some reason get placed after a gigabytes long gap.

Is there a solution to this? Should you need more information, I will try to dig out what I can.

The versions used are modsecurity 2.8 and Apache 2.4.10 from Debian Jessie and modsecurity 2.9 and Apache 2.4.25 from Debian Stretch. The problem presents itself even with newest modsecurity 2.9.2 from Stretch-backports.

**Comment by zimmerle** [comment]
Hi @tlghacc,

I don't name this scenario as o bug, but a limitation. The *sdbm* files used on the v2 are not ideal to save data such as DoS count. That may lead you to scenarios like the one that you are illustrating. You can try to reduce the expire time, mount a memory disk to hold the collection data, yet, depending on the amount of info to be saved the problem will return.

Another tips is to put _modsec-sdbm-util_ to shrink the database on a crontab process, that should help a lot.

**Comment by tlghacc** [comment]
Hello, alright, thanks for the reply

Some remarks just in case someone finds this while googling the problem - I don't believe storing the collection data on memory disk will make much of a difference. Considering the file is sparse, most of the data is not actually stored on the hard drive anyway. The slowdown is not caused by reading from slow drive, it's caused just by reading bunch of zeroes that are generated by the kernel on the fly. (It might save some time by not having the kernel generate the data all the time, but then again, eating gigabytes worth of memory for this on each and every one of our webservers is really not an option.)

I did not try this, but I don't believe _modsec-sdbm-util_ shrink will help either - according to it's usage, shrink _Removes all the expired elements as long as others not well formatted items from the database._ Since the items in the database are not expired nor invalid, I don't expect it to remove any of them.

In the end I found a workaround that seems to be effective, albeit very ugly. Made a simple Ruby script that checks the database file every 15 seconds and when its file size exceeds data size by a preset threshold, the file gets truncated, deleting that one record at the end. This is of course completely wrong and may come to bite me in the future, but it is preferable to having our webservers either clogged or constantly watched by someone.

**Comment by zimmerle** [comment]
The RAM disk can speed up the shrink process the occurs internally on modsecurity reducing the empty spaces. Also beneficial to _modsec-sdbm-util_ for the same reason.

There is an option `-n` on the modsec-sdbm-util which effectively create a new database without the sparse data.

**Comment by AMa78** [comment]
This is an ongoing issue.

We have an ip.pag file that grows to over 1.6gb, with ~800k of non-sparse data, at which point Apache workers start getting stuck on 'L'ogging tasks, producing a slowdown that at one point threatened the hosting server.

Removing the file just has it repopulate to a size that slows the system in 15mins or less.

The RAM disk solution is both temporary and inadequate: the file will grow beyond what ever RAM disk size is provisioned.   The _modsec-sdbm-util_ does not remove pointless space, so running on a RAM disk just fails to remove the bloat 'faster'.  

Recreating a new database with -n (or by deleting the files on cron task) is both faintly ridiculous and a temporary fix; the file will grow again, and the 'fix' will need to be reapplied constantly.

Suggesting specific rules that *might* be at issue is not helpful: unless there is some way to tell which rules are responsible, this is just guessing.

We're redirecting the .pag to /dev/null, which seems irresponsible from a logging standpoint, but the only way to put a single stable fix in place. 

When and how does ModSecurity plan to address this?

**Comment by zimmerle** [comment]
Hi @AMa78,

The .pag files holds data for persistent collections. If you have created very large collections, is very likely that you are going to have very large collections. What are the rules that you are using to create such collections?

**Comment by AMa78** [comment]
We have a collection of about 500 rules from public sources.  There's no
way to tell which of these is populating the persistent collection?  Or
which are the worst offenders for over-doing it?

Thanks,
Ashley Majzels,
Client Care Services

Terracor Business Solutions
204.477.5342 ext. 126
164 Marion St. | R2H 0T4
Winnipeg | Manitoba | Canada

<ashley.majzels@terracor.ca>  <http://www.terracor.ca/>
<https://www.facebook.com/terracorbusinesssolutions/>
<https://twitter.com/zeckoShop>
<https://ca.linkedin.com/company/terracor-business-solutions>

**Comment by zimmerle** [comment]
The SecRule is some-what-similar to a scripting language. The external resources need to be blocked, otherwise, the users will create temporariry files or collections without concerns about the computational resources available.
