### ISSUE TITLE
SecAuditLogType HTTPS to https://mydomain.com/Save.php , log is null (ModeSecurity V3)

### ISSUE THREAD

**Issue by 0CrazyGuy9** [SpiderLabs/ModSecurity#1934]
Hi ModSecurity

Version ModSecurity 3

My config 
SecAuditLogType HTTPS 
SecAuditLog https://mydomain.com/Save.php

Save.php
`<?php
$data .= var_export($_POST, true);
$data .= file_get_contents('php://input');
$myfile = fopen("/tmp/post.txt", "w");
fwrite($myfile, $data);
fflush($myfile);
fclose($myfile);
?>`

result 
array ()
{"error":"ModSecurity was not compiled with JSON support."}

why ?

if use "SecAuditLogType Concurrent", can log json data.

**Comment by zimmerle** [comment]
Hi @0CrazyGuy9,

The support for JSON depends on a third party library there is likely to not be installed in your system. The JSON support is required to enable ```SecAuditLogType HTTPS```.

By the end of the configure script there is a summary like this:
```
ModSecurity - v3.0.2-132-gc63d269f for Linux
 
 Mandatory dependencies
   + libInjection                                  ....v3.0.2-132-gc63d269f
   + SecLang tests                                 ....c63d269f
 
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (MaxMind) v1.3.2
         -lmaxminddb , -DWITH_MAXMIND 
      * (GeoIP) v1.6.12
         -lGeoIP , -I/usr/include/ 
   + LibCURL                                       ....found v7.61.1 
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl , -DWITH_YAJL -I/usr/include/yajl 
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.8
      -lxml2 -lz -llzma -licui18n -licuuc -licudata -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....found 
      -lfuzzy -L/usr/lib/, -DWITH_SSDEEP -I/usr/include
   + LUA                                           ....found v503
      -llua5.3 -L/usr/lib/, -DWITH_LUA -I/usr/include
 
 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled

```

Make sure you have YAJL (-dev) installed and it appears in modsec config.

**Comment by 0CrazyGuy9** [comment]
> Hi @0CrazyGuy9,
> 
> The support for JSON depends on a third party library there is likely to not be installed in your system. The JSON support is required to enable `SecAuditLogType HTTPS`.
> 
> By the end of the configure script there is a summary like this:
> 
> ```
> ModSecurity - v3.0.2-132-gc63d269f for Linux
>  
>  Mandatory dependencies
>    + libInjection                                  ....v3.0.2-132-gc63d269f
>    + SecLang tests                                 ....c63d269f
>  
>  Optional dependencies
>    + GeoIP/MaxMind                                 ....found 
>       * (MaxMind) v1.3.2
>          -lmaxminddb , -DWITH_MAXMIND 
>       * (GeoIP) v1.6.12
>          -lGeoIP , -I/usr/include/ 
>    + LibCURL                                       ....found v7.61.1 
>       -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
>    + YAJL                                          ....found v2.1.0
>       -lyajl , -DWITH_YAJL -I/usr/include/yajl 
>    + LMDB                                          ....disabled
>    + LibXML2                                       ....found v2.9.8
>       -lxml2 -lz -llzma -licui18n -licuuc -licudata -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2
>    + SSDEEP                                        ....found 
>       -lfuzzy -L/usr/lib/, -DWITH_SSDEEP -I/usr/include
>    + LUA                                           ....found v503
>       -llua5.3 -L/usr/lib/, -DWITH_LUA -I/usr/include
>  
>  Other Options
>    + Test Utilities                                ....enabled
>    + SecDebugLog                                   ....enabled
>    + afl fuzzer                                    ....disabled
>    + library examples                              ....enabled
>    + Building parser                               ....disabled
>    + Treating pm operations as critical section    ....disabled
> ```
> Make sure you have YAJL (-dev) installed and it appears in modsec config.

Thank you

my info correct?

`ModSecurity - v3.0.2-112-g68398a5 for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.0.2-112-g68398a5
   + SecLang tests                                 ....68398a5

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (GeoIP) v1.5.0
         -lGeoIP  , -I/usr/include/
   + LibCURL                                       ....found v7.29.0
      -lcurl  ,  -DWITH_CURL
   + YAJL                                          ....found v2.0.4
      -lyajl  , -DWITH_YAJL
   + LMDB                                          ....not found
   + LibXML2                                       ....found v2.9.1
      -lxml2 -lz -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....not found

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled
`

**Comment by 0CrazyGuy9** [comment]
> Make sure you have YAJL (-dev) installed and it appears in modsec config.

Thank you 

**but issue still , Save.php $_POST data is null.**

+ YAJL                                          ....found v2.0.4 ( there found)
      -lyajl  , -DWITH_YAJL



ModSecurity - v3.0.2-112-g68398a5 for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.0.2-112-g68398a5
   + SecLang tests                                 ....68398a5

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (GeoIP) v1.5.0
         -lGeoIP  , -I/usr/include/
   + LibCURL                                       ....found v7.46.0
      -L/opt/curl/lib -lcurl, -I/opt/curl/include -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.0.4
      -lyajl  , -DWITH_YAJL
   + LMDB                                          ....not found
   + LibXML2                                       ....found v2.9.1
      -lxml2 -lz -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....found v501
      -lluajit-5.1 -L/usr/lib64/, -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled

**Comment by zimmerle** [comment]
```{"error":"ModSecurity was not compiled with JSON support."}```

Still getting this one? if so, make sure the library was compiled and installed correctly.

**Comment by 0CrazyGuy9** [comment]
> `{"error":"ModSecurity was not compiled with JSON support."}`
> 
> Still getting this one? if so, make sure the library was compiled and installed correctly.

Yeah, still this error, all compiled correctly.

please help, i don't have any idea for it.

Save.php aways get this info.

**Comment by zimmerle** [comment]
Is likely that your connector is leading the library in a different path. Try:
```
find / -iname libmodsecurity.so
```

**Comment by 0CrazyGuy9** [comment]
> Is likely that your connector is leading the library in a different path. Try:
> 
> ```
> find / -iname libmodsecurity.so
> ```

for you info

# find / -iname libmodsecurity.so
/usr/local/modsecurity/lib/libmodsecurity.so
/opt/ModSecurity/src/.libs/libmodsecurity.so

it correctly ?

**Comment by zimmerle** [comment]
Please try:

```
$ ldd /usr/local/modsecurity/lib/libmodsecurity.so
```

**Comment by 0CrazyGuy9** [comment]
> ldd /usr/local/modsecurity/lib/libmodsecurity.so

for you info

ldd /usr/local/modsecurity/lib/libmodsecurity.so
        linux-vdso.so.1 =>  (0x00007ffc547b2000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00002aea54e21000)
        libGeoIP.so.1 => /usr/local/lib/libGeoIP.so.1 (0x00002aea5508a000)
        librt.so.1 => /lib64/librt.so.1 (0x00002aea552be000)
        libxml2.so.2 => /lib64/libxml2.so.2 (0x00002aea554c6000)
        libz.so.1 => /lib64/libz.so.1 (0x00002aea55830000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aea55a46000)
        liblmdb.so => /lib/liblmdb.so (0x00002aea55c4a000)
        liblua-5.1.so => /lib64/liblua-5.1.so (0x00002aea55e5f000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00002aea5608d000)
        libfuzzy.so.2 => /usr/local/lib/libfuzzy.so.2 (0x00002aea562ef000)
        libyajl.so.2 => /lib64/libyajl.so.2 (0x00002aea564f4000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00002aea566fe000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aea56a05000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aea56d07000)
        /lib64/ld-linux-x86-64.so.2 (0x00002aea547c2000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aea570d4000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00002aea572ea000)
        libssh2.so.1 => /lib64/libssh2.so.1 (0x00002aea5751d000)
        libssl3.so => /lib64/libssl3.so (0x00002aea57747000)
        libsmime3.so => /lib64/libsmime3.so (0x00002aea57999000)
        libnss3.so => /lib64/libnss3.so (0x00002aea57bc0000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00002aea57eed000)
        libplds4.so => /lib64/libplds4.so (0x00002aea5811c000)
        libplc4.so => /lib64/libplc4.so (0x00002aea58320000)
        libnspr4.so => /lib64/libnspr4.so (0x00002aea58525000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aea58763000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00002aea5897f000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00002aea58bcc000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00002aea58eb4000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00002aea590e7000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00002aea592eb000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00002aea594fa000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00002aea5974f000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00002aea59975000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00002aea59be7000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00002aea5a048000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00002aea5a256000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00002aea5a45a000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00002aea5a673000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00002aea5a890000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00002aea5aab7000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00002aea5acee000)

**Comment by 0CrazyGuy9** [comment]
Hi Zimmerle
Now is ok, can recv log data. maybe "yum update lua*" make this error, when i reinstall, every thing is fine 

Thank you

**Comment by zimmerle** [comment]
good to hear :)

**Comment by sharmashivanand** [comment]
How did you resolve it? Does ldd give the same result after fixing? was it a library issue?

**Comment by sharmashivanand** [comment]
I'm facing the same issue: Nginx 1.18.0

```
ModSecurity -  for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.9.2-46-gbfba51f
   + SecLang tests                                 ....a3d4405

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (GeoIP) v1.6.12
         -lGeoIP , -I/usr/include/
   + LibCURL                                       ....found v7.74.0
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl , -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.10
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....found
      -lfuzzy -L/usr/lib/x86_64-linux-gnu/, -DWITH_SSDEEP -I/usr/include
   + LUA                                           ....found v501
      -llua5.1 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include/lua5.1

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled
```

```
╰─# ldd  /usr/local/modsecurity/lib/libmodsecurity.so
        linux-vdso.so.1 (0x00007ffc793c2000)
        libcurl.so.4 => /lib/x86_64-linux-gnu/libcurl.so.4 (0x00007fd4b2ff1000)
        libGeoIP.so.1 => /lib/x86_64-linux-gnu/libGeoIP.so.1 (0x00007fd4b2fb3000)
        libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fd4b2e05000)
        liblua5.1.so.0 => /lib/x86_64-linux-gnu/liblua5.1.so.0 (0x00007fd4b2dd5000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd4b2d62000)
        libfuzzy.so.2 => /lib/x86_64-linux-gnu/libfuzzy.so.2 (0x00007fd4b2d5b000)
        libyajl.so.2 => /lib/x86_64-linux-gnu/libyajl.so.2 (0x00007fd4b2d4c000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd4b2b7f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd4b29ba000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd4b32f9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd4b29a0000)
        libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007fd4b2973000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007fd4b2952000)
        librtmp.so.1 => /lib/x86_64-linux-gnu/librtmp.so.1 (0x00007fd4b2931000)
        libssh2.so.1 => /lib/x86_64-linux-gnu/libssh2.so.1 (0x00007fd4b28fc000)
        libpsl.so.5 => /lib/x86_64-linux-gnu/libpsl.so.5 (0x00007fd4b28e8000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fd4b2855000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fd4b2561000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fd4b250e000)
        libldap_r-2.4.so.2 => /lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007fd4b24b6000)
        liblber-2.4.so.2 => /lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007fd4b24a5000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007fd4b2497000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd4b247a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd4b2458000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd4b2452000)
        libicuuc.so.67 => /lib/x86_64-linux-gnu/libicuuc.so.67 (0x00007fd4b2267000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fd4b223f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd4b20fb000)
        libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007fd4b1f79000)
        libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fd4b1d79000)
        libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007fd4b1d2e000)
        libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007fd4b1ce6000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fd4b1c65000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fd4b1b45000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fd4b1a6b000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fd4b1a3b000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fd4b1a33000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fd4b1a24000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fd4b1a0a000)
        libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fd4b19ed000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007fd4b19ca000)
        libicudata.so.67 => /lib/x86_64-linux-gnu/libicudata.so.67 (0x00007fd4afeaf000)
        libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fd4afd7b000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fd4afd65000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fd4afd3f000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fd4afd38000)
        libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007fd4afd2a000)
```

**Comment by sharmashivanand** [comment]
Ok. It was a PHP issue. For anyone else landing here, the data can only be retreived with php://input if you are using PHP and is not available via $_POST.
