### ISSUE TITLE
About ModSecurity V3 send log json format , error on C#

### ISSUE THREAD

**Issue by 0CrazyGuy9** [SpiderLabs/ModSecurity#1938]
Hi ModSecurity

when use C# Recv json log

Invalid JavaScript property identifier character: -. Path ''

like "cache-control":"max-age=0", can't convert to C# JSON code "string cache-control {get;set;} " // not allow "-". , so can't convert to C# object     obj.cache-control 

it's bug ?

**Comment by zimmerle** [comment]
I am afraid i didn't quite understood what you have being asking.

I am not familiar with C# Recv JSON log. Can you provide more details?

**Comment by 0CrazyGuy9** [comment]
"transaction": {
		"client_ip": "2.3.4.5",
		"time_stamp": "Wed Oct 24 21:28:56 2018",
		"server_id": "3a8097ae11d640196c04f984bfb6a09203b42474",
		"client_port": 50347,
		"host_ip": "2.3.4.5",
		"host_port": 443,
		"unique_id": "154038773611.711690",
		"request": {
			"method": "GET",
			"http_version": 2.0,
			"uri": "/?a=1%20and%201%20=%201",
			"headers": {
				"host": "www.aaaa99900.com",
				"cache-control": "max-age=0",
				"upgrade-insecure-requests": "1",
				"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36",
				"dnt": "1",
				"cookie": "pgv_pvid=6865589778; _ga=GA1.2.1815405811.1536984854",
				"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
				"accept-encoding": "gzip, deflate, br",
				"accept-language": "zh,zh-CN;q=0.9,en-US;q=0.8,en;q=0.7"
			}
		},

C#  Language convert to json object.

"cache-control" "user-agent" Not a legal variable.

**Comment by zimmerle** [comment]
That seem to be a valid json to me:

```
{  
   "transaction":{  
      "client_ip":"2.3.4.5",
      "time_stamp":"Wed Oct 24 21:28:56 2018",
      "server_id":"3a8097ae11d640196c04f984bfb6a09203b42474",
      "client_port":50347,
      "host_ip":"2.3.4.5",
      "host_port":443,
      "unique_id":"154038773611.711690",
      "request":{  
         "method":"GET",
         "http_version":2.0,
         "uri":"/?a=1%20and%201%20=%201",
         "headers":{  
            "host":"www.aaaa99900.com",
            "cache-control":"max-age=0",
            "upgrade-insecure-requests":"1",
            "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36",
            "dnt":"1",
            "cookie":"pgv_pvid=6865589778; _ga=GA1.2.1815405811.1536984854",
            "accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
            "accept-encoding":"gzip, deflate, br",
            "accept-language":"zh,zh-CN;q=0.9,en-US;q=0.8,en;q=0.7"
         }
      }
   }
}
```

https://jsonformatter.curiousconcept.com/

**Comment by zimmerle** [comment]
Hey @0CrazyGuy9, 

Did you managed to figure out the issue? can I close this?

**Comment by 0CrazyGuy9** [comment]
> Hey @0CrazyGuy9,
> 
> Did you managed to figure out the issue? can I close this?

Thank you
