### ISSUE TITLE
INSTALLATION NOT WORKING

### ISSUE THREAD

**Issue by Link-XInc** [SpiderLabs/ModSecurity#1940]
Dear All,

We are a company and we would like to use ModSecurity for our servers. We heard that v3.0.2 had released but the installation did not work for us. Please could you provide a step-by-step installation process for it? We use Ubuntu 16.04 with apache 2.4.18. We hope to hear from you soon.

Kind Regards,
Link-X Team

**Comment by ghost** [comment]
What does the error log state?


aronetics.com
Security | Infrastructure | Analytics
+1 216 307 5760

**Comment by Link-XInc** [comment]
Where is the error log?

**Comment by ghost** [comment]
Contact me at my company and I'll assist.


aronetics.com
Security | Infrastructure | Analytics
+1 216 307 5760

**Comment by zimmerle** [comment]
Hi @jhngrn,

I am not sure if it is polite to use this space to make propaganda of your company or services. That is an open source software issue tracking platform. Ideally we like to have people around to help and share knowledge. Even if you are not charging this gentleman over there, the communication should be registered here, for the benefit of other users that may face the same problem.

**Comment by zimmerle** [comment]
Hi @Link-XInc,

You can find the compilation recipes here:
 - https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

And here:
 - https://github.com/SpiderLabs/ModSecurity/blob/v3/master/README.md#compilation
 - https://github.com/SpiderLabs/ModSecurity-apache/blob/master/README.md#compilation

Differently from version 2, the version 3 depends on two different pieces of software: **core** and **connector**. Keep in mind that the Apache connector for version 3 is _not production ready yet_. My advice for Apache users is to keep using v2.

**Comment by ghost** [comment]
Eh, it's no charge to talk them through it. Yet:

Most logs are in /var/log if you've setup proper reporting in /etc
