### ISSUE TITLE
Some problem in class RequestHeaders_DictElementRegex, loss regex expression

### ISSUE THREAD

**Issue by tdoubley** [SpiderLabs/ModSecurity#1942]
**Describe the bug**

class RequestHeaders_DictElementRegexp : public Variable {
 public:
    explicit RequestHeaders_DictElementRegexp(std::string dictElement)
        : Variable("REQUEST_HEADERS"),
        m_r(dictElement) { }
    Utils::Regex m_r;
};
should be
class RequestHeaders_DictElementRegexp : public Variable {
 public:
    explicit RequestHeaders_DictElementRegexp(std::string dictElement)
        : Variable("REQUEST_HEADERS:regex(" + dictElement + ")"),
        m_r(dictElement) { }
    Utils::Regex m_r;
};
ModSecurity v3.0.2

**Comment by zimmerle** [comment]
Hi @tdoubley,

To avoid code repetition, I've changed the **variables-kind classes** to use a macro. Here is how the code looks in the most recent version of our code:

https://github.com/SpiderLabs/ModSecurity/blob/b05901e8ae5935cbdbb8db331c11b9b6e8134a42/src/variables/request_headers.h#L32-L34

The macro is defined here:

https://github.com/SpiderLabs/ModSecurity/blob/b05901e8ae5935cbdbb8db331c11b9b6e8134a42/src/variables/variable.h#L36-L57

Notice also, that now we have a specialized class ```VariableRegex```. This class is the one responsible to set the variable name:

https://github.com/SpiderLabs/ModSecurity/blob/b05901e8ae5935cbdbb8db331c11b9b6e8134a42/src/variables/variable.h#L592-L595

IMHO this new method is more elegant, and should avoid problems like the one you have spotted. Thank you.

I am going to close the issue as this is already fixed on master.
