### ISSUE TITLE
nginx: [emerg] "modsecurity_rules_file" directive Rules error Expecting an action

### ISSUE THREAD

**Issue by kjakub** [SpiderLabs/ModSecurity#1945]
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/conf/modsecurity.conf. Line: 23. Column: 82. Expecting an action, got:  "id: in /etc/nginx/nginx.conf:48wercase,pass,nolog,ctl:requestBodyProcessor=XML"

from: 

https://raw.githubusercontent.com/SpiderLabs/ModSecurity/v3.0.2/modsecurity.conf-recommended

with 

nginx-1.15.5 (reproducable on other versions too)

git clone --depth 1 -b v3/master --single-branch https://github.com/SpiderLabs/ModSecurity
cd ModSecurity
git submodule init
git submodule update
./build.sh
./configure
make
make install

git clone --depth 1 https://github.com/SpiderLabs/ModSecurity-nginx.git
./configure --with-compat --add-dynamic-module=./ModSecurity-nginx
make modules
cp objs/ngx_http_modsecurity_module.so /etc/nginx/

**Comment by zimmerle** [comment]
Hi @kjakub,

Do you mind to share your nginx.conf?

**Comment by defanator** [comment]
@kjakub please check if you have CRLF line terminators in your modsecurity.conf, and try to use the original one with Unix-style line feeds instead. Will it work?

**Comment by zimmerle** [comment]
As of bfe917b6b1ed81a58b80f87c0e4058e9c63aea59 the parser is now able to handle the files CRLF or LF.

**Comment by kjakub** [comment]
:+1: thank you
