### ISSUE TITLE
rules_properties.cc fails to build - worked earlier today.

### ISSUE THREAD

**Issue by HankQuiter** [SpiderLabs/ModSecurity#1946]
Building in Docker Alpine linux fails on "rules_properties.cc" it built properly earlier on today.

Here is all I can get out of the Docker build process.   I started the copy of the text a number of files before rules_properties.cc for context.
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/     -DWITH_YAJL -I/usr/include/yajl   -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include  -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT libmodsecurity_la-rule_script.lo -MD -MP -MF .deps/libmodsecurity_la-rule_script.Tpo -c -o libmodsecurity_la-rule_script.lo `test -f 'rule_script.cc' || echo './'`rule_script.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-rule_script.lo -MD -MP -MF .deps/libmodsecurity_la-rule_script.Tpo -c rule_script.cc  -fPIC -DPIC -o .libs/libmodsecurity_la-rule_script.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-rule_script.lo -MD -MP -MF .deps/libmodsecurity_la-rule_script.Tpo -c rule_script.cc -o libmodsecurity_la-rule_script.o >/dev/null 2>&1
mv -f .deps/libmodsecurity_la-rule_script.Tpo .deps/libmodsecurity_la-rule_script.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/     -DWITH_YAJL -I/usr/include/yajl   -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include  -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT libmodsecurity_la-unique_id.lo -MD -MP -MF .deps/libmodsecurity_la-unique_id.Tpo -c -o libmodsecurity_la-unique_id.lo `test -f 'unique_id.cc' || echo './'`unique_id.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-unique_id.lo -MD -MP -MF .deps/libmodsecurity_la-unique_id.Tpo -c unique_id.cc  -fPIC -DPIC -o .libs/libmodsecurity_la-unique_id.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-unique_id.lo -MD -MP -MF .deps/libmodsecurity_la-unique_id.Tpo -c unique_id.cc -o libmodsecurity_la-unique_id.o >/dev/null 2>&1
mv -f .deps/libmodsecurity_la-unique_id.Tpo .deps/libmodsecurity_la-unique_id.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/     -DWITH_YAJL -I/usr/include/yajl   -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include  -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT libmodsecurity_la-rules_exceptions.lo -MD -MP -MF .deps/libmodsecurity_la-rules_exceptions.Tpo -c -o libmodsecurity_la-rules_exceptions.lo `test -f 'rules_exceptions.cc' || echo './'`rules_exceptions.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-rules_exceptions.lo -MD -MP -MF .deps/libmodsecurity_la-rules_exceptions.Tpo -c rules_exceptions.cc  -fPIC -DPIC -o .libs/libmodsecurity_la-rules_exceptions.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-rules_exceptions.lo -MD -MP -MF .deps/libmodsecurity_la-rules_exceptions.Tpo -c rules_exceptions.cc -o libmodsecurity_la-rules_exceptions.o >/dev/null 2>&1
mv -f .deps/libmodsecurity_la-rules_exceptions.Tpo .deps/libmodsecurity_la-rules_exceptions.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/     -DWITH_YAJL -I/usr/include/yajl   -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include  -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT libmodsecurity_la-rules_properties.lo -MD -MP -MF .deps/libmodsecurity_la-rules_properties.Tpo -c -o libmodsecurity_la-rules_properties.lo `test -f 'rules_properties.cc' || echo './'`rules_properties.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/local/include -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-rules_properties.lo -MD -MP -MF .deps/libmodsecurity_la-rules_properties.Tpo -c rules_properties.cc  -fPIC -DPIC -o .libs/libmodsecurity_la-rules_properties.o
rules_properties.cc: In static member function 'static void modsecurity::ConfigUnicodeMap::loadConfig(std::__cxx11::string, double, modsecurity::RulesProperties*, std::__cxx11::string*)':
rules_properties.cc:50:48: error: no match for 'operator[]' (operand types are 'std::shared_ptr<int []>' and 'int')
     driver->m_unicodeMapTable.m_unicodeMapTable[0x3002] = 0x2e;
                                                ^
rules_properties.cc:52:48: error: no match for 'operator[]' (operand types are 'std::shared_ptr<int []>' and 'int')
     driver->m_unicodeMapTable.m_unicodeMapTable[0xff61] = 0x2e;
                                                ^
rules_properties.cc:54:48: error: no match for 'operator[]' (operand types are 'std::shared_ptr<int []>' and 'int')
     driver->m_unicodeMapTable.m_unicodeMapTable[0xff0e] = 0x2e;
                                                ^
rules_properties.cc:56:48: error: no match for 'operator[]' (operand types are 'std::shared_ptr<int []>' and 'int')
     driver->m_unicodeMapTable.m_unicodeMapTable[0x002e] = 0x2e;
                                                ^
rules_properties.cc:109:64: error: no match for 'operator[]' (operand types are 'std::shared_ptr<int []>' and 'int')
                     driver->m_unicodeMapTable.m_unicodeMapTable[code] = Map;
                                                                ^
In file included from /usr/include/c++/6.4.0/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/6.4.0/memory:82,
                 from ../headers/modsecurity/modsecurity.h:80,
                 from ../headers/modsecurity/rules_properties.h:32,
                 from rules_properties.cc:16:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h: In instantiation of 'std::__shared_ptr<_Tp, _Lp>& std::__shared_ptr<_Tp, _Lp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Tp1 = int []; _Del = std::default_delete<int []>; _Tp = int []; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]':
/usr/include/c++/6.4.0/bits/shared_ptr.h:310:4:   required from 'std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Tp1 = int []; _Del = std::default_delete<int []>; _Tp = int []]'
rules_properties.cc:44:62:   required from here
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: error: no matching function for call to 'std::__shared_ptr<int [], (__gnu_cxx::_Lock_policy)2u>::__shared_ptr(std::remove_reference<std::unique_ptr<int []>&>::type)'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1149:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__weak_ptr<_Tp, _Lp>&, std::nothrow_t) [with _Tp = int []; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(const __weak_ptr<_Tp, _Lp>& __r, std::nothrow_t)
       ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1149:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1097:2: note: candidate: template<class _Alloc, class ... _Args> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...)
  __shared_ptr(_Sp_make_shared_tag __tag, const _Alloc& __a,
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1097:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   candidate expects at least 2 arguments, 1 provided
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:979:17: note: candidate: constexpr std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t) [with _Tp = int []; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u; std::nullptr_t = std::nullptr_t]
       constexpr __shared_ptr(nullptr_t) noexcept : __shared_ptr() { }
                 ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:979:17: note:   no known conversion for argument 1 from 'std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}' to 'std::nullptr_t'
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:976:2: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::auto_ptr<_Up>&&)
  __shared_ptr(std::auto_ptr<_Tp1>&& __r);
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:976:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   'std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}' is not derived from 'std::auto_ptr<_Up>'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:964:2: note: candidate: template<class _Tp1, class _Del, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::unique_ptr<_Up, _Ep>&&)
  __shared_ptr(std::unique_ptr<_Tp1, _Del>&& __r)
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:964:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:951:11: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__weak_ptr<_Tp1, _Lp>&)
  explicit __shared_ptr(const __weak_ptr<_Tp1, _Lp>& __r)
           ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:951:11: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   'std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}' is not derived from 'const std::__weak_ptr<_Tp>'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:943:2: note: candidate: template<class _Tp1, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::__shared_ptr<_Tp1, _Lp>&&)
  __shared_ptr(__shared_ptr<_Tp1, _Lp>&& __r) noexcept
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:943:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   'std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}' is not derived from 'std::__shared_ptr<_Tp>'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:935:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::__shared_ptr<_Tp, _Lp>&&) [with _Tp = int []; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(__shared_ptr&& __r) noexcept
       ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:935:7: note:   no known conversion for argument 1 from 'std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}' to 'std::__shared_ptr<int [], (__gnu_cxx::_Lock_policy)2u>&&'
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:931:2: note: candidate: template<class _Tp1, class> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp1, _Lp>&)
  __shared_ptr(const __shared_ptr<_Tp1, _Lp>& __r) noexcept
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:931:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   'std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}' is not derived from 'const std::__shared_ptr<_Tp>'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:926:7: note: candidate: std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp, _Lp>&) [with _Tp = int []; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       __shared_ptr(const __shared_ptr&) noexcept = default;
       ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:926:7: note:   no known conversion for argument 1 from 'std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}' to 'const std::__shared_ptr<int [], (__gnu_cxx::_Lock_policy)2u>&'
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:922:2: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(const std::__shared_ptr<_Tp1, _Lp>&, _Tp*)
  __shared_ptr(const __shared_ptr<_Tp1, _Lp>& __r, _Tp* __p) noexcept
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:922:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   'std::remove_reference<std::unique_ptr<int []>&>::type {aka std::unique_ptr<int []>}' is not derived from 'const std::__shared_ptr<_Tp>'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:917:9: note: candidate: template<class _Deleter, class _Alloc> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t, _Deleter, _Alloc)
         __shared_ptr(nullptr_t __p, _Deleter __d, _Alloc __a)
         ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:917:9: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   candidate expects 3 arguments, 1 provided
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:912:2: note: candidate: template<class _Deleter> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::nullptr_t, _Deleter)
  __shared_ptr(nullptr_t __p, _Deleter __d)
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:912:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   candidate expects 2 arguments, 1 provided
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:903:2: note: candidate: template<class _Tp1, class _Deleter, class _Alloc> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*, _Deleter, _Alloc)
  __shared_ptr(_Tp1* __p, _Deleter __d, _Alloc __a)
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:903:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   mismatched types '_Tp1*' and 'std::unique_ptr<int []>'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:894:2: note: candidate: template<class _Tp1, class _Deleter> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*, _Deleter)
  __shared_ptr(_Tp1* __p, _Deleter __d)
  ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:894:2: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   mismatched types '_Tp1*' and 'std::unique_ptr<int []>'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:884:11: note: candidate: template<class _Tp1> std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*)
  explicit __shared_ptr(_Tp1* __p)
           ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:884:11: note:   template argument deduction/substitution failed:
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:1019:4: note:   mismatched types '_Tp1*' and 'std::unique_ptr<int []>'
    __shared_ptr(std::move(__r)).swap(*this);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:879:17: note: candidate: constexpr std::__shared_ptr<_Tp, _Lp>::__shared_ptr() [with _Tp = int []; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]
       constexpr __shared_ptr() noexcept
                 ^~~~~~~~~~~~
/usr/include/c++/6.4.0/bits/shared_ptr_base.h:879:17: note:   candidate expects 0 arguments, 1 provided
make[3]: *** [Makefile:2169: libmodsecurity_la-rules_properties.lo] Error 1
make[3]: Leaving directory '/opt/ModSecurity/src'
make[2]: *** [Makefile:3373: all-recursive] Error 1
make[2]: Leaving directory '/opt/ModSecurity/src'
make[1]: Leaving directory '/opt/ModSecurity/src'
make[1]: *** [Makefile:1191: all] Error 2
make: *** [Makefile:1013: all-recursive] Error 1

to duplicate add the following to a Dockerfile and build: "docker build -t vangelis ."

FROM nginx:1.15.3-alpine

LABEL maintainer="someone"

ENV NGINX_VERSION 1.15.3

RUN apk add --no-cache --virtual .build-deps \
        gcc \
        libc-dev \
        make \
        pcre-dev \
        zlib-dev \
        linux-headers \
        libxslt-dev \
        gd-dev \
        perl-dev \
    && apk add --no-cache --virtual .libmodsecurity-deps \
        libxml2-dev \
        git \
        libtool \
        automake \
        autoconf \
        g++ \
        flex \
        bison \
        yajl-dev \
        curl-dev \
        lua-dev \
        git \
    && apk add --no-cache \
        geoip \
        geoip-dev \
        doxygen \
        yajl \
        libstdc++ \
        sed \
        curl \
        lua \
        gnupg \
    && curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
    && curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc \
    && export GNUPGHOME="$(mktemp -d)" \
        && GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
        && echo $GPG_KEYS \
        && found=''; \
        for server in \
                ha.pool.sks-keyservers.net \
                hkp://keyserver.ubuntu.com:80 \
                hkp://p80.pool.sks-keyservers.net:80 \
                pgp.mit.edu \
        ; do \
                echo "Fetching GPG key $GPG_KEYS from $server"; \
                gpg --keyserver $server --keyserver-options timeout=10 --recv-keys $GPG_KEYS && found=yes && break; \
        done; \
        test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
        gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
        && mkdir /opt \
        && mv nginx.tar.gz /opt/

RUN rm -rf "$GNUPGHOME" nginx.tar.gz.asc \
        # forward request and error logs to docker log collector
        && ln -sf /dev/stdout /var/log/nginx/access.log \
        && ln -sf /dev/stderr /var/log/nginx/error.log \
        && mkdir -p /opt/SSDEEP \
    && cd /opt/SSDEEP \
    && git clone -b master --single-branch https://github.com/ssdeep-project/ssdeep.git \
    && cd /opt/SSDEEP/ssdeep \
    && autoreconf -i \
    && ./configure \
    && make \
    && make install \
    && make installcheck

RUN mkdir /opt/ModSecurity \
    && cd /opt/ModSecurity \
    && echo "Installing ModSec Library" \
    && git clone -b v3/master --single-branch https://github.com/SpiderLabs/ModSecurity . \
    && git submodule init \
    && git submodule update \
    && ./build.sh \
    && ./configure && make && make install

**Comment by victorhora** [comment]
@HankQuiter 

This was already fixed earlier today at https://github.com/SpiderLabs/ModSecurity/commit/18cdffdbca75e6b9f790f6df2807a32cd805c0a0

See https://github.com/SpiderLabs/ModSecurity/issues/1941 for more information.

Thanks.
