### ISSUE TITLE
@pmf operator on libModSecurity3 is not ignoring "#" on an otherwise empty line as it should

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/ModSecurity#1948]
**The CRS rule 913100 is based on scanners-user-agents.data and this file contains lines with only a `#`. A user-agent with a `#` leads to a false positive.**

**Logs and dumps**

See https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1215

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

```curl -v localhost -H "User-Agent: Sogou Pic Spider/3.0(+http://www.sogou.com/docs/help/webmasters.htm#07)"```

**Expected behavior**

All lines starting with `#` are being ignored like with ModSec 2.x.

**Comment by victorhora** [comment]
Hi @dune73 

Thanks for the report. It seems like this is a duplicate of https://github.com/SpiderLabs/ModSecurity/issues/1645. Do you mind sharing your findings there so we can better keep track of the issues?

Thanks.

**Comment by dune73** [comment]
Don't mind at all. Thanks for the pointer.
