### ISSUE TITLE
Multipart: Skipping invalid part 7f94eed17be8 (part name missing)

### ISSUE THREAD

**Issue by nachtsheim** [SpiderLabs/ModSecurity#1952]
Hi! I get the metioned error message in apache error log and there is no way to exclude this check or anything like this. The request gets respondet by http status 200, so everything works as supposed. The error seems to be more like a warning?

Is there a way to stop this warning. I don't want it in the apache error.log

modsec audit log:
--91566c04-A--
[13/Nov/2018:13:49:19 +0100] W@rITcWtEVqF0WI3OXKxBAAAAAc xxx.xxx.191.142 59246 xxx.xxx.254.9 443
--91566c04-B--
POST /api/xxx HTTP/1.1
Accept: */*
Content-Type: multipart/form-data; boundary=---------------------------7e229fea50a98
Referer: https://xxx.de/xxx/xxx.php?address=12345&rating=1&radius=20
Accept-Language: de-DE,de;q=0.5
Origin: https://xxx.de
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
Host: xxx
Content-Length: 424
DNT: 1
Connection: Keep-Alive
Cache-Control: no-cache

--91566c04-I--
address=12345&country=&radius=20
--91566c04-F--
HTTP/1.1 200 OK
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
X-RateLimit-Limit: 6000
X-RateLimit-Remaining: 5999
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/json

--91566c04-H--
Message: Multipart: Skipping invalid part 7f94eed17be8 (part name missing): (offset 0, length 0)
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client xxx.xxx.191.142] ModSecurity: Multipart: Skipping invalid part 7f94eed17be8 (part name missing): (offset 0, length 0) [hostname "xxx"] [uri "/api/xxx"] [unique_id "W@rITcWtEVqF0WI3OXKxBAAAAAc"]
Apache-Handler: application/x-httpd-php
Stopwatch: 1542113357110089 2038163 (- - -)
Stopwatch2: 1542113357110089 2038163; combined=3746, p1=776, p2=2802, p3=0, p4=0, p5=167, sr=141, sw=1, l=0, gc=0
Producer: ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/3.0.2.
Server: Apache/2.4.37 (Ubuntu)
Engine-Mode: "ENABLED"

--91566c04-J--
Total,0

--91566c04-Z--

**Comment by marcstern** [comment]
This is a real protocol violation and should be detected (and blocked), otherwise we allow for (easy) attacks evasions.
If you allow this, you should force the url-encoded parser to parse the body correctly.

**Comment by nachtsheim** [comment]
Currently it is not blocked (http response status code 200). Maybe because we did 
"SecRuleRemoveById" 200003 and 920140. 

So IE11 works not rfc compliant and so we have to change the frontend javascript code to work around this IE11 behavior?

**Comment by victorhora** [comment]
Can you confirm if this also happens in libModSecurity (3.x)?

Thanks.
