### ISSUE TITLE
Be able to set path for shared-locations

### ISSUE THREAD

**Issue by pfischermx** [SpiderLabs/ModSecurity#1953]
First off I'm aware of https://github.com/SpiderLabs/ModSecurity/issues/1388

However I wonder if there are some workarounds you are aware. I'm building the module with the OS (Centos) packages of libmodsecurity, those packages unfortunately were compiled with libmdbm so even if I build a local libmodsecurity during my build this would still depend on the libmodsecurity library that is running on each host.

So with that said, is there a way to set the path of those files? Having them under root (/) seems a bit off, I can understand it if run within a container but on baremetal hosts it might be nicer to have them on a separate path.

Is there a way to set the path? Couldn't find shared-location on neither code so no sure where is it invoked/created.

Oh and on the OS I'm using 3.0.2.

Thanks!

**Comment by zimmerle** [comment]
Hi @pfischermx, 

You can set the prefix of libModSecurity with the`--prefix` option, passed to the `./configure` script. Is that what you are looking for?

**Comment by pfischermx** [comment]
@zimmerle Not precisely. modsecurity will create modsec-shared-collections and modsec-shared-collections-lock files under /:

$ ls -1 /mod*
/modsec-shared-collections
/modsec-shared-collections-lock
[pfischer@staging-traffic-manager03.dev ~]$ 

From what I understand there is no way to change the path of those files (to something like /var/run or /var/db or something) and the way to prevent those files in getting created is to compile libmodsecurity without libmdbm. The problem is that I'm using a Centos provided package on our hosts, and that libmodsecurity package was compiled with libmdbm.

So the question is: is there a way to change the path or can we add an option :-)
