### ISSUE TITLE
How to use pm operator with mutex ?

### ISSUE THREAD

**Issue by luchy0120** [SpiderLabs/ModSecurity#1954]
Dear Modsecurity team , I want to ask when using Modsecurity with pm operator ,  whether we should add --enable-mutex-on-pm during configuration .
Is it used under multithread situation ?

**Comment by zimmerle** [comment]
Hi @luchy0120,

This is not meant to be used in a regular environment. That was implemented to facilitate the testing of the library in different environments. Should be safe to use without the mutex. Do you have any specific use case that you can think in a benefit of using it?

**Comment by luchy0120** [comment]
Hi @zimmerle , is acmp_process_quick thread-safe ? Could pm be used in a multi-thread environment ?
