### ISSUE TITLE
Comodo WAF Rules doesnt work with Modsecurity v3.0.3

### ISSUE THREAD

**Issue by slushz** [SpiderLabs/ModSecurity#1962]
Comodo WAF Rules doesnt work with Modsecurity v3.0.3

**Comment by zimmerle** [comment]
Hi @slushz,

I am not sure what exactly i can do to help. Can you explain to us what is the exactly problem?

**Comment by zimmerle** [comment]
I am going to close this issue as we are not having feedback.
