### ISSUE TITLE
sanitise* actions implementation

### ISSUE THREAD

**Issue by ldbobby** [SpiderLabs/ModSecurity#1963]
**Describe the bug**

A bit confused the below sanitise* actions are supported yet as I see code for it, but I get errors similar to "SanatiseMatched is not yet supported." when trying to use them. If they're not yet supported, curious if you might have an ETA for implementation?

sanitiseArg
sanitiseMatched
sanitiseMatchedBytes
sanitiseRequestHeader
sanitiseResponseHeader

**Logs and dumps**

Nov 20 15:54:55 example.com nginx[11178]: nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/modsec.conf. Line: 23. Column: 90. Action: SanatiseResponseHeader is not yet supported.  in /...ginx/nginx.conf:66
Nov 20 15:58:23 example.com nginx[13439]: nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/modsec.conf. Line: 29. Column: 91. Action: SanatiseMatched is not yet supported.  in /etc/nginx/nginx.conf:66
Nov 20 15:59:23 example.com nginx[13734]: nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/modsec.conf. Line: 32. Column: 32. Action: SanatiseArg is not yet supported.  in /etc/nginx/nginx.conf:66
Nov 20 15:59:55 example.com nginx[13954]: nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/modsec.conf. Line: 47. Column: 65. Action: SanatiseMatched is not yet supported.  in /etc/nginx/nginx.conf:66

**Server:**
 - ModSecurity version (and connector): ModSecurity v3.0.2 with nginx-connector v1.0.0
 - WebServer: nginx-1.15.6
 - OS (and distro): Centos7

**Comment by victorhora** [comment]
@ldbobby 

Yes, these are still pending implementation. See the entries about the sanitise actions on the reference manual: (e.g. [sanitiseArg](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#sanitisearg)) 

> Supported on libModSecurity: TBI 

(To be implemented)

As of now, a number of issues are targeted to be fixed for the 3.0.4 release. See the [milestone for 3.0.4](https://github.com/SpiderLabs/ModSecurity/milestone/13)

There's no ETA for 3.0.4 yet, it could happen before the end of the year or some time after that, it really depends on the amount of effort necessary to fix all those 50+ issues as well as other stuff that happens and we can't predict.

There's already an issue tracking the implementation of these features on v3: https://github.com/SpiderLabs/ModSecurity/issues/1898

Please keep track of that issue and add your comments and observations there if needed.

As a last point, I recommend using the latest released version of libModSecurity ([3.0.3](https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.3)) as there's a lot of fixes and improvements between the two versions.

Thanks.

**Comment by ldbobby** [comment]
@victorhora Would you know of any other way to achieve the same effect via libmodsecurity without the Sanitise* directives? Or would the best route be to modify the log_format in the nginx.conf?

**Comment by victorhora** [comment]
@ldbobby you could try stripping parts of your audit_log by tuning the [SecAuditLogParts](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogParts) but be advised there's not too much fine grained tuning.

You could maybe create a script that sanitizes the audit_log for you once in a while with the risk that the data would be saved on disk first and only then be erased/sanitized.

Another alternative to saving the audit_logs locally in disk, is sending them to a remote server via the HTTPS transport for the [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType) directive and then your receiving end could do any kind of processing/sanitizing on it before saving on disk. See https://github.com/SpiderLabs/ModSecurity/issues/1839#issuecomment-405381882
