### ISSUE TITLE
JSON parsing error: lexical error: invalid char in json text.\\x0a

### ISSUE THREAD

**Issue by 001appsec007** [SpiderLabs/ModSecurity#1964]
OWASP CRS 3.0

"message": "Failed to parse request body.",
 "details": {
   "message": "Warning. Match of \"eq 0\" against \"REQBODY_ERROR\" required.",
   "data": "JSON parsing error: lexical error: invalid char in json text.\\x0a",
   "file": "rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf",
   "line": "143"
 },

POST request with JSON payload sent but not special characters or empty string and it's very strange issue to get it resolved.

Similar Issue 
https://github.com/SpiderLabs/ModSecurity-nginx/issues/125

**Comment by 001appsec007** [comment]
Please find dummy JSON format which is similar to actual payload..

{"test_val":false,"test":[{"test":"test_test_test.doc","_val":"1-a1b2c3d4e5e7e8e9te","testTypeDiff":"valueTest","state":"process","_values":{"test":0,"testone":["a1b2c3d4e5e7e8e9te"]},"testID":"test:+0000000000","testQ":"test:+0000000000","_test":"test_test_test.doc","testType":"dummy","testValue":"testValue","work":"8.0"}]}

**Comment by 001appsec007** [comment]
@victorhora 
This is "BLOCKER" for us which triggered for many requests. Could you please help in suggesting FIX ASAP for same ?

**Comment by zimmerle** [comment]
Hi @001appsec007,

What happens to be the ModSecurity version that you are currently running? Can you give more details on the request?

**Comment by 001appsec007** [comment]
@zimmerle 

I figured out this issue when JSON payload string contains ENTER (/n character identical to ASCII value //xoa) which is reproducible when request made through Burp and captured following issue as violation which is blocking all requests..

This ENTER i have added manually then posted via Burp found same issue in logs. But unclear cut is JSON is not creating any ENTER or /n  in middle of strings which is observed in Wireshark pcap..

How we should mitigate that ? or is this "False Positive" ?

**Comment by 001appsec007** [comment]
This is first time we introduced WAF OWASP CRS 3.0 to our existing application & earlier we don't have CRS rule engine.

**Comment by zimmerle** [comment]
@001appsec007 there are two different things: **ModSecurity** which is your WAF engine. The **CRS** which is a set of rules that once loaded into ModSecurity attempts to mitigate generic attacks on our web application. Depends where is the enter it may lead you to a invalid JSON. Which may be correctly report by the conjunction: ModSecurity + set of rules.

**Comment by 001appsec007** [comment]
In below JSON payload a Line Break is entered after "1-a1b2c3d" results to same error when manually sent this request via CRS 3.0

{"test_val":false,"test":[{"test":"test_test_test.doc","_val":"1-a1b2c3d
4e5e7e8e9te","testTypeDiff":"valueTest","state":"process","_values":{"test":0,"testone":["a1b2c3d4e5e7e8e9te"]},"testID":"test:+0000000000","testQ":"test:+0000000000","_test":"test_test_test.doc","testType":"dummy","testValue":"testValue","work":"8.0"}]}

**Comment by zimmerle** [comment]
Hi @001appsec007,

This is indeed a invalid json:
```
 ✘  ~  jsonlint                                                                                                                           ✘ 1 
{"test_val":false,"test":[{"test":"test_test_test.doc","_val":"1-a1b2c3d
4e5e7e8e9te","testTypeDiff":"valueTest","state":"process","_values":{"test":0,"testone":["a1b2c3d4e5e7e8e9te"]},"testID":"test:+0000000000","testQ":"test:+0000000000","_test":"test_test_test.doc","testType":"dummy","testValue":"testValue","work":"8.0"}]}Error: Parse error on line 1:
...st_test.doc","_val":"1-a1b2c3d4e5e7e8e9
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
    at Object.parseError (/home/zimmerle/.nvm/versions/node/v8.0.0/lib/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/home/zimmerle/.nvm/versions/node/v8.0.0/lib/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at parse (/home/zimmerle/.nvm/versions/node/v8.0.0/lib/node_modules/jsonlint/lib/cli.js:82:14)
    at ReadStream.<anonymous> (/home/zimmerle/.nvm/versions/node/v8.0.0/lib/node_modules/jsonlint/lib/cli.js:149:41)
    at emitNone (events.js:110:20)
    at ReadStream.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```

**Comment by 001appsec007** [comment]
@zimmerle 

Could you please parse this json format...

{"test_val":false,"test":[{"test":"test_test_test.doc","_val":"1-a1b2c3d4e5e7e8e9te","testTypeDiff":"valueTest","state":"process","_values":{"test":0,"testone":["a1b2c3d4e5e7e8e9te"]},"testID":"test:+0000000000","testQ":"test:+0000000000","_test":"test_test_test.doc","testType":"dummy","testValue":"testValue","work":"8.0"}]}

**Comment by 001appsec007** [comment]
@zimmerle 

The above one is valid JSON but still we are getting "JSON parsing error: lexical error: invalid char in json text.\\x0a".

We verified HEX values \x0A (Line Feed Character) & 5C also in PCAP but still facing same error. Could you please help on this.

**Comment by victorhora** [comment]
@001appsec007 you could use any online JSON lint tool such as: https://jsonlint.com/
 
> {"test_val":false,"test":[{"test":"test_test_test.doc","_val":"1-a1b2c3d4e5e7e8e9te","testTypeDiff":"valueTest","state":"process","_values":{"test":0,"testone":["a1b2c3d4e5e7e8e9te"]},"testID":"test:+0000000000","testQ":"test:+0000000000","_test":"test_test_test.doc","testType":"dummy","testValue":"testValue","work":"8.0"}]}

This JSON in particular shows as valid.

There's a chance that your particular client/library that handles the JSON that gets sent to ModSecurity is screwing up something and breaking the JSON.

Please go over issue https://github.com/SpiderLabs/ModSecurity/issues/1879 as a user was complaining about a similar problem with JSON parsing, when in the end it was found that the problem was the way that Python was handling the JSONs.

See https://github.com/SpiderLabs/ModSecurity/issues/1879#issuecomment-423645508 and try to reproduce all those steps to understand where the issue lies. If you are still certain that the issue is with libModSecurity please provide detailed data/logs/confs/reproducible steps (e.g. https://github.com/SpiderLabs/ModSecurity/issues/1879) to support this with the results of your tests so we can investigate further.

Thanks.
