### ISSUE TITLE
ModSecurity 3.x closed network installation.

### ISSUE THREAD

**Issue by lexugax** [SpiderLabs/ModSecurity#1965]
**Describe the bug**

I need to install ModSecurity for Apache in RedHat servers. Previous to version 3, it was easy to do this as the installation did not involve reaching a GIT repository. Is there a way to install it without the installation process requiring connection to the internet?

**Logs and dumps**

**To Reproduce**

**Expected behavior**

**Rule Set (please complete the following information):**

**Additional context**

I tried following the installation instructions for Centos 7.

**Comment by victorhora** [comment]
@lexugax there should be numerous ways to accomplish that. For instance:

* Simply download the released v3.0.3 zip package from the [releases page](https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.38);
* Run a git checkout anywhere that has connectivity and then zip the folder;
* See if you can use any of the pre-built RPM packages available ;(https://pkgs.org/download/libmodsecurity)
* Create your own RPM (you could maybe use the spec file of those RPMs as starting point);
   * Add the custom RPMs to your servers RPM repo

As far as I know, nobody has packaged libModSecurity (v3) specifically for RedHat yet.

You could use a similar approach to get the [Apache-connector.](https://github.com/SpiderLabs/ModSecurity-apache)

**Comment by lexugax** [comment]
Thanks for your reply.
I am still having issues with some of these options. I tried downloading the zip file or running a git checkout in another location, but when I run sh build.sh, the script also tries to connect to git, which takes me back to square one. Also, due to my company's policies, I can't just download the pre-build packages from the specified site.

**Comment by victorhora** [comment]
As far as I can recall, the git errors that you might be getting when you run build.sh should only be warnings as I think the script tries to figure out the version using git. I believe you should still be able to move forward and run the configure script (./configure) and then compile (make).

You might also check the feasibility of running buid.sh elsewhere, zipping the package and then running the configure script. This might work if you have all the dependencies met.

As far as I know the RPM packages from that link are "official" builds for those Linux distros. They're probably "as official" as the RPM packages from RHEL and most of the times built by the same person/entity.

You might consider purchasing commercial support for ModSecurity to fit specific needs of your company's policies.

Good luck ;)

**Comment by lexugax** [comment]
Thanks!
