### ISSUE TITLE
ModSecurity: JSON parsing error: lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by MZSN** [SpiderLabs/ModSecurity#1971]
I am getting the error written in the title whenever my application hits my server. It is blocking all requests even the login requests as well. The difference only here is I have used end to end encryption. Is it why I am getting this error?

**Comment by MZSN** [comment]
I am using these versions:
[Mon Dec 03 15:30:04.000666 2018] [:notice] [pid 21180] ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured.
[Mon Dec 03 15:30:04.000895 2018] [:notice] [pid 21180] ModSecurity: APR compiled version="1.5.1"; loaded version="1.5.2"
[Mon Dec 03 15:30:04.000905 2018] [:warn] [pid 21180] ModSecurity: Loaded APR do not match with compiled!
[Mon Dec 03 15:30:04.000913 2018] [:notice] [pid 21180] ModSecurity: PCRE compiled version="8.35 "; loaded version="8.38 2015-11-23"
[Mon Dec 03 15:30:04.000920 2018] [:warn] [pid 21180] ModSecurity: Loaded PCRE do not match with compiled!
[Mon Dec 03 15:30:04.000926 2018] [:notice] [pid 21180] ModSecurity: LUA compiled version="Lua 5.1"
[Mon Dec 03 15:30:04.000931 2018] [:notice] [pid 21180] ModSecurity: YAJL compiled version="2.1.0"
[Mon Dec 03 15:30:04.000937 2018] [:notice] [pid 21180] ModSecurity: LIBXML compiled version="2.9.2"
[Mon Dec 03 15:30:04.001064 2018] [:notice] [pid 21180] ModSecurity: StatusEngine call: "2.9.0,Apache/2.4.18 (Ubuntu),1.5.1/1.5.2,8.35/8.38 2015-11-23,Lua 5.1,2.9.2,70492375a351b640f06e3b8b78047625d9867712"

**Comment by zimmerle** [comment]
Hi @MZSN, 

Do you mind to post the JSON that is triggered such rule? You can use [Gits](https://gist.github.com/) to do it. Without actually seen the data it will be very hard to help you.

**Comment by MZSN** [comment]
The data is encrypted with AES-256 so even if I share it. It will be useless to look at? The login call was also encrypted so it blocked it as well using rule

ModSecurity: JSON parsing error: lexical error: invalid char in json text.\n [hostname "xyz"] [uri "/login"] [unique_id "W-@dDn8AAQEAAGpoh3UAAAAA"]

ModSecurity: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/etc/modsecurity/modsecurity.conf"] [line "71"] [id "200002"] [msg "Failed to parse request body."] [data "JSON parsing error: lexical error: invalid char in json text.\\x0a"] [severity "CRITICAL"] [hostname "xyz"] [uri "/login"] [unique_id "W-@dDn8AAQEAAGpoh3UAAAAA"]

**Comment by MZSN** [comment]
My application is end to end encrypted and when it hits modsecurity ssl offloading occurs and at app server the end to end encryption is removed. But modsecurity is blocking everything as end to end encrypted so if its not possible to scan the payload can I just allow URLs in these request? Like if the packet is destined to my desired url it should not be scanned? Thanks

**Comment by zimmerle** [comment]
Hi @MZSN,

It seems like you have to whitelist the urls that are giving you trouble. How to whitelist rally depends on your application logic. You can use "virtual folders" or add exceptions within action tags.

**Comment by zimmerle** [comment]
Marking it as 'close' as it seems the user already solved the problem.
