### ISSUE TITLE
unit test for utf8ToUnicode

### ISSUE THREAD

**Issue by tdoubley** [SpiderLabs/ModSecurity#1974]
**Describe the bug**
The name of utf8ToUnicode is wrong.
In this function the class name is utf8**T**oUnicode
Transformation* Transformation::instantiate(std::string a) {
    ...
    IF_MATCH(utf8ToUnicode) { return new Utf8ToUnicode(a); }
    return new Transformation(a);
}
but in test file utf8toUnicode.json the class name is utf8**t**oUnicode,
it will lead to IF_MATCH return false， and return instance of Transformation，all test is wrong

**Server (please complete the following information):**
 -  ModSecurity v3.0.2

**Comment by zimmerle** [comment]
Hi @tdoubley,

Wants to make a patch for it?

**Comment by tdoubley** [comment]
Hi @zimmerle ，
Yes， I will do it，It's mypleasure

**Comment by zimmerle** [comment]
@tdoubley you can find me an felipe at zimmerle dot org. Lets fix this together ;)
