### ISSUE TITLE
CssDecode have some problem

### ISSUE THREAD

**Issue by tdoubley** [SpiderLabs/ModSecurity#1976]
**Describe the bug**
```
std::string CssDecode::evaluate(std::string value,
    Transaction *transaction) {

    char *tmp = reinterpret_cast<char *>(
        malloc(sizeof(char) * value.size() + 1));
    memcpy(tmp, value.c_str(), value.size() + 1);
    tmp[value.size()] = '\0';

    CssDecode::css_decode_inplace(reinterpret_cast<unsigned char *>(tmp),
        value.size());

    std::string ret(tmp, 0, value.size()); 
    free(tmp);
    return ret;
}
```
the ret size is equal value, but in pritical the size should equal to the return value of css_decode_inplace, it could be lead to bug, although the unit test is all pased, it because the '\0' on the end of tmp, when call construcator of string ,it will be cut of by '\0'.

**Logs and dumps**

**To Reproduce**

**Expected behavior**

**Server (please complete the following information):**
 - ModSecurity 3.0.02

**Rule Set (please complete the following information):**

**Additional context**

**Comment by zimmerle** [comment]
Hi @tdoubley,

The term **inplace**, in the _css_decode_inplace_ function means that no memory is allocated to produce the output. Instead the transformation is saved in the same memory area of its input. In this particular case, the decoded string may be shorter than the original, so a ```\0``` is placed following its last character, as described here:

https://github.com/SpiderLabs/ModSecurity/blob/1ecd9713061c3534626bf6a5f59d1c928c0c52bb/src/actions/transformations/css_decode.cc#L187-L188

Did you happens to find a use case scenario where the decoded content is also leaking info ?
