### ISSUE TITLE
Fix inet addr handling on 64 bit big endian systems

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#1980]
Contribution from @airween :)

Originally reported at: https://github.com/airween/ModSecurity/commit/db4bd42d18ed1dd1844f1c0ce596237349f0d997

**Comment by zimmerle** [comment]
Merged! ;) Thanks.

**Comment by zimmerle** [comment]
Back ported to v2 at 0dcbb8b08796a08fc043fa53134e85fc9d207cba

**Comment by airween** [comment]
Thanks for the help to point the solution to @jrtc27. :)

And special thanks to @glaubitz for sparc64 access.

**Comment by DHager** [comment]
Thanks for this, just encountered the problem in the wild and was afraid I'd have to teach myself more C to properly fix it :)
