### ISSUE TITLE
Installing modsecurity 3.0.3 using yum repository

### ISSUE THREAD

**Issue by AnnuA** [SpiderLabs/ModSecurity#1981]
I want to install latest stable modsecurity for apache on Ubuntu and Centos. 
But  when I am installing using 'yum install mod_security' it is installing 2.9.2 version.
The 3.0.3 version is not available in repositories?
I would have to install it by compiling source code only?

**Comment by zimmerle** [comment]
I've just tested the Transfer issue in GitHub :) it seems to work fine.

@AnnuA as @defanator mentioned, that is the best place to questions related to libModSec. We have some info on the wiki here:
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

**Comment by victorhora** [comment]
3.x (including 3.0.3) is available in a number of RPM-based distros:

https://pkgs.org/download/libmodsecurity

But I think there's no RHEL version. But it should be possible to create your own RPM package by using the spec file of these packages as starting point.

Its also available in some APT-based distros:

https://tracker.debian.org/pkg/modsecurity
https://packages.ubuntu.com/disco/libmodsecurity3

I believe these are development/testing versions, but anyways they are there :)
