### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by yuynagforhacker** [SpiderLabs/ModSecurity#1986]
Hi:
Recently, there has been a problem that has been bothering me. When I upload the image, the image binary exists ../ and I know this is not compliant, but there is no way to make smart judgments. This has affected my business and needs help. thanks

**Comment by zimmerle** [comment]
Hi @yuynagforhacker, 

This may not be related to ModSecurity, but to the rules set that you have loaded. Are you using any public ruleset?

**Comment by yuynagforhacker** [comment]
Using the owasp rule base, the problem occurs again LFI rules, rule number 930110. It has been temporarily resolved, but I believe that my solution must not be the best, the solution is to replace the `..\ ../` in the rule with `\..\ /../` This issue has been posted in the owasp issue[https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1264](url)
