### ISSUE TITLE
configuration script can't receive environment variables

### ISSUE THREAD

**Issue by gwijayas** [SpiderLabs/ModSecurity#1995]
**Describe the bug**

configuration script can't receive environment variables

From issue #1994 I think more simpler if we could override environment for configuration. On my Ubuntu 16.04, the result of configuration script `./configure`:
```shell
ModSecurity - v3.0.3 for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.9.2-30-gbf234eb
   + SecLang tests                                 ....e6b03e4

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (MaxMind) v
         /usr/lib/x86_64-linux-gnu//libmaxminddb.so, /usr/include/x86_64-linux-gnu/, -DWITH_MAXMIND -I/usr/include/x86_64-linux-gnu/
      * (GeoIP) v1.6.12
         -lGeoIP  , -I/usr/include/
   + LibCURL                                       ....found v7.47.0
      -L/usr/lib/x86_64-linux-gnu -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl  , -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.4
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....found
      -lfuzzy -L/usr/lib/x86_64-linux-gnu/, -DWITH_SSDEEP -I/usr/include
   + LUA                                           ....found v501
      -lluajit-5.1 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include/lua5.3

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled
```
I try to focus just for lua. So, the library tha choose is luajit. But, the header location is for lua-5.3.

I have try these:
```shell
CPPFLAGS="-I/usr/include/luajit-2.0" ./configure
```
But the result of configuration process is still pointing to `/usr/include/lua5.3`

**Comment by zimmerle** [comment]
Hi @gwijayas,

There are different problems here, the first problem is the version mismatch in between the lua header and the lua library. A possible solution for it is an attempt to compile something that is exclusively available in a given header version, therefore identify the mismatch.

The support for adding CFLAGS via environment variable seems to be a neat feature, and it is already supported. However it won't remove the existing definition. As an alternative you can force Lua lookup with the ```--with-lua=/usr/include/luajit-2.0``` configuration flag.

Regardless the linker here, in the end it is going to use whatever is loaded by nginx, as we share the process space.

Please let me known if --with-lua solve the problem.

**Comment by zimmerle** [comment]
Hi @gwijayas,

I am assuming ```--with-lua ``` worked for you, therefore I am closing this issue. Please re-open the issue, if that was not the case.
