### ISSUE TITLE
IIS 64b MSI contains 32b dll's causing errors

### ISSUE THREAD

**Issue by victorhora** [SpiderLabs/ModSecurity#1998]
**Describe the bug**

Our friends from Apache Lounge (@SteffenAL) have reported an issue with ModSecurity IIS build/msi installer seems to be missing correct DLLs when installed on some versions of Windows.

The 32b works fine. Wonder what happens when install the 64b on a clean machine without Modsec installed before and the dependent dll's are not in the machine path. 

You can try it on a machine where ModSecurity never has been  installed or the dependent dll's are not in the machine path.

_**This issue needs further investigation as it's not currently reproducible on a test Windows 7 VM.**_

**To Reproduce**

Steps to reproduce the behaviour:

- extract the msi with: >msiexec /a ModSecurityIIS_2.9.3-64b.msi /qb TARGETDIR=x:\xxxx\Modsec64  

- Execute: > x:\xxxx\Modsec64\SystemFolder\inetsrv\mlogc.exe gives error

**Expected behavior**

The MSI installer should **_ideally_** work on all supported versions of MS Windows and MS IIS.

**Server (please complete the following information):**
 - ModSecurity version (and connector): 2.9.3 32b/64bit msi installers
 - WebServer: IIS?
 - OS (and distro): 

**Additional context**

In the extracted .msi I see in the Win folder xxx110.dll's that is Visual Studio 2012, and in System folder xxx120.dll's  that is Visual Studio 2013. And also I see in SysemFolder/inetserv also xxx120.dll's. Wonder why 2012 and 2013 and the 120 twice.  It is advised and best practice from Microsoft not the place that dll's but use the Visual C++ Redistributables for Visual Studio, for example for 2012 https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by icing** [comment]
FYI: I have nothing to do with ApacheLounge or Windows builds. You are probably talking about @SteffenAL here?

**Comment by victorhora** [comment]
Correct @icing. My bad. It's now fixed. Thanks! :)

**Comment by martinhsv** [comment]
This issue was not reproducible by the ModSecurity team even back three years ago.

Moreover, both the ModSecurity version and the versions of Windows it is intended to run on have advanced.

Closing ...
