### ISSUE TITLE
mod_security issues with rule 217130 and errors 500

### ISSUE THREAD

**Issue by ibertrix** [SpiderLabs/ModSecurity#2001]
Hi,

  I have Apache as SSL proxy server with http2 enabled and Apache as non-SSL backend since I have Varnish in between.

  Since around one week I am having issues with rule 217130 and getting this in my logs:

  Access denied with code 500 (phase 1) (Error: Connection drop requested but failed to close the  socket

  since I have CSF as a firewall, a ddos attack is reported and the IP is blocked but these are valid connections. 

  root@server [~]# httpd -version
Server version: Apache/2.4.37 (cPanel)
Server built:   Dec  3 2018 16:16:44

These are the Cpanel packages I have installed:
ea-apache24-2.4.37-1.1.2.cpanel.x86_64
ea-apache24-mod_security2-2.9.2-10.10.1.cpanel.x86_64

 Googling around it seems 2 years ago there might be a similar issue:
 
 https://github.com/SpiderLabs/ModSecurity/issues/992

**Comment by zimmerle** [comment]
Hi @ibertrix,

Can you give me further details on what is rule 217130?

**Comment by zimmerle** [comment]
@ibertrix i am assuming you found the answer to your problem. If not, please reopen the issue, answering the question above.

**Comment by ibertrix** [comment]
I had to downgrade mod_security:

ea-apache24-mod_security2-2.9.2-10.10.1.cpanel.x86_64

I have to say that the rules are coming from Comodo free mod_security rules, sorry for the confusion
