### ISSUE TITLE
nginx module + libmodsecurity not support "Transfer-Coding:chunked" request?

### ISSUE THREAD

**Issue by huifeidexingyuner** [SpiderLabs/ModSecurity#2004]
1.  Browser access  http://192.168.192.131/?id=1 and 1=1   ，Can intercept

2.
but,use burpsuit send the request as follows->

POST /simplepost/info.php HTTP/1.1
Host: 192.168.192.131
Origin: http://192.168.192.131
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: */*
Referer: http://192.168.192.131/simplepost/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8
Connection: close
Transfer-Coding:chunked

3
a=1 and 1=1
0
(two /r/n)

**the result is->**
**Normal access, no interception.**

why?

**Comment by zimmerle** [comment]
Hi @huifeidexingyuner,

Did you created a custom rule? or are you using any public rule set?

**Comment by zimmerle** [comment]
@huifeidexingyuner I am going to close this issue until we here more form you. Chunked transfer is supported in modsec.
