### ISSUE TITLE
hello, I want ask some question about rules

### ISSUE THREAD

**Issue by herono2010** [SpiderLabs/ModSecurity#2009]
hello, I want ask some question about rules. How do I write a rule that:

blocking upload files ending in ".php/.aspx" . these  upload files are handled in the body of the POST request .

thanks very much .

**Comment by victorhora** [comment]
Hi @herono2010 
  
Have a look at the [endsWith](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#endsWith) operator and [FILES_NAMES](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#FILES_NAMES) variable.

The full link to the Reference Manual is here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29.

And although some of the resources regarding documentation on ModSecurity.org are a bit outdated, there's some good stuff there that might help you too: https://www.modsecurity.org/documentation.html

Good luck!

**Comment by herono2010** [comment]
I've solved this problems. the rule like this:
SecRule FILES_NAMES|FILES "^.*\.(php|exe|pcap|html)$" "deny,msg:'Attempted multipart/form-data bypass', severity:'2', id:'100000087', ver:'OWASP_CRS/2.2.9', rev:'1', maturity:'9', accuracy:'7', logdata:'%{matched_var} wangzhao FILES value:%{FILES} FILE_NAMES value:%{FILES_NAMES}', phase:2, t:none,t:urlDecodeUni, tag:'OWASP_CRS/PROTOCOL_VIOLATION/INVALID_REQ', tag:'CAPEC-272'"

**Comment by herono2010** [comment]
the FILES is upload file names .  the FILE_NAMES is Web page code . like filewz .
<input type="file" name="filewz" id="fileww" />

**Comment by victorhora** [comment]
Hi @herono2010

Thanks for reporting back on a rule that works for you. I'm sure other people from the community will find this useful :)
