### ISSUE TITLE
Xml and Json Parsers send error messages to console when parsing fails

### ISSUE THREAD

**Issue by JaiHarpalani** [SpiderLabs/ModSecurity#2010]
**Describe the bug**

If the xml or json parser is enabled, and parsing fails, error messages are dumped to the console. There should be a way to disable these error messages.

**Logs and dumps**

An example of an error message for an xml parse error:

body.xml:1: parser error : Extra content at the end of the document
^

**To Reproduce**

With XML parsing enabled, Issue a POST request such as following which contains badly formatted xml:

POST /mule1/index.html HTTP/1.1
Host: <hostname>
Content-type: application/xml
Content-Length: 19

<root><foo/></root>

**Expected behavior**

A method to stop the error message from showing up on the console is needed.

**Server (please complete the following information):**
 - ModSecurity version V3.0.2
 - WebServer: n/a
 - OS (and distro): CentOS 7

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? OWASP CRS
 - What is the version number? V3.0.2

**Additional context**

**Comment by zimmerle** [comment]
Hi @JaiHarpalani,

Thank you for the report. In the past, we had a clash between the "catch-all" error method for modsec/libxml and the method utilized by the API consumer. Which made us remove the error handler function. In order to circumvent the problem, we have been compiling without stdout output.

Let's see if you can find an elegant way to deal with that problem.

**Comment by zimmerle** [comment]
Error handlers are enabled on the **@validateSchema** operator - 
https://github.com/SpiderLabs/ModSecurity/blob/42a16c71cfb995bb2cd76dab02f6fe7aa6b596be/src/operators/validate_schema.cc#L59-L68

Checking the feasibility to have it globally enabled.

**Comment by zimmerle** [comment]
Closed as of: 05e9e7cf31fe78a2dcf66719b8aef555354daf54
