### ISSUE TITLE
Build commands replaced with pkg-config in yocto project bitbake builds

### ISSUE THREAD

**Issue by chuckwolber** [SpiderLabs/ModSecurity#2013]
When building modsecurity v3 in a (Yocto) bitbake recipe for embedded environments, the builds can fail because xml2-config and pcre-config are deprecated in favor of pkg-config.

I am working on a fix to replace the xml2-config and pcre-config references in the m4 macro files with pkg-config. I should have a pull request shortly.

**Comment by victorhora** [comment]
Let us know if you need support with a pull request @chuckwolber. Thanks :)

**Comment by chuckwolber** [comment]
Thanks, and sorry for the delay. I will try to get it fixed shortly.

**Comment by zimmerle** [comment]
Hi, @chuckwolber 

Any progress on this?
