### ISSUE TITLE
Windows Event Log

### ISSUE THREAD

**Issue by dmarlow** [SpiderLabs/ModSecurity#2020]
I'm curious how logs are controlled for ModSec. For example, is it possible to disable writing to the event log for anything that isn't an "error" in ModSec? Or maybe there are other logging options?

Reason I ask is that during load tests and vulnerability scans the event log can end up receiving a lot of warning messages and things slow down considerably (svchost.exe process starts to consume a lot of CPU writing to the event log).

**Comment by victorhora** [comment]
Hey @dmarlow,

Sorry for the delayed response. Please see my comments below:

> I'm curious how logs are controlled for ModSec. 

You basically have three types of logs: [auditlog](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#auditlog), [log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#log) and [debuglog](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecDebugLog). 
\
You can tune the audit log by the SecAudit* related directives (e.g. [SecAuditEngine ](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditEngine)) and the same is also true for the debug log (see [SecDebugLog](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecDebugLog)). 

But as far as I recall, there's no much tuning of the "plain" [log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#log) other than customization of [logdata](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#logdata) and [msg](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#msg) actions.

To simplify things, we can assume that the "plain" [log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#log) action is the one that saves log data to Apache's error log. 

**On the IIS build, this "error" log is the only one one that gets pushed to the EventViewe**r. The other log types (Audit/Debug) will get saved to disk on their respective files as per the [SecAuditLog](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLog) and [SecDebugLog](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecDebugLog).

> For example, is it possible to disable writing to the event log for anything that isn't an "error" in ModSec? Or maybe there are other logging options?

Following the rationale above, it means that every ModSec rule that have the [log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#log) action defined and that matches for a given transaction will get generate an entry on the EventViewer.

You can change this in many ways: 

* Remove the [log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#log) action from the rules;

* Add the [nolog](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#nolog) action to your rules;

* Use (or change) [SecDefaultAction](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecDefaultAction) and either omit the [log](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#log) action (if present), or add the [nolog](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#nolog) action;

* Add a [SecRuleUpdateActionById](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecRuleUpdateActionById) directive using the same rationale as above.

Bear in mind the following note from the [Reference Manua](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#nolog)l: _Although nolog implies noauditlog, you can override the former by using nolog,auditlog._

> Reason I ask is that during load tests and vulnerability scans the event log can end up receiving a lot of warning messages and things slow down considerably (svchost.exe process starts to consume a lot of CPU writing to the event log).

The solutions proposed above should alleviate or eliminate this issue.

Good luck :)
