### ISSUE TITLE
make check  errors

### ISSUE THREAD

**Issue by trafico10** [SpiderLabs/ModSecurity#2022]
Can you tell me what it means?
and how to solve it
use ubuntu 18 nginx

Making check in others
make[1]: Entering directory '/opt/ModSecurity-nginx/ModSecurity/others'
/bin/bash: libinjection/src/.dirstamp: Permission denied
make[1]: *** [Makefile:510: libinjection/src/.dirstamp] Error 1
make[1]: Leaving directory '/opt/ModSecurity-nginx/ModSecurity/others'
make: *** [Makefile:1018: check-recursive] Error 1

**Comment by trafico10** [comment]
okay. sorry
do not add sudo

Testsuite summary for modsecurity 3.0
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/opt/ModSecurity-nginx/ModSecurity'
make[2]: Leaving directory '/opt/ModSecurity-nginx/ModSecurity'
make[1]: Leaving directory '/opt/ModSecurity-nginx/ModSecurity'

**Comment by victorhora** [comment]
@trafico10 

I would guess that your problem is here:
```
/bin/bash: libinjection/src/.dirstamp: Permission denied
```

Check that the user compiling the code (running $make) owns and have appropriate permissions to run the compiler/linker and create the output files on the same folder where the source for ModSecurity is.
