### ISSUE TITLE
[ModSecurity 2.9.3] Apr crypto unknown type name

### ISSUE THREAD

**Issue by gspaivaequals** [SpiderLabs/ModSecurity#2042]
Hey guys, I'm trying to install 2.9.3 version od modsecurity and after I run 'make' I'm getting the following error : 
```
In file included from modsecurity.h:49:0,
                 from apache2_config.c:17:
msc_remote_rules.h:54:9: error: unknown type name 'apr_crypto_key_t'
         apr_crypto_key_t **apr_key,
         ^
msc_remote_rules.h:55:9: error: unknown type name 'apr_crypto_t'
         apr_crypto_t *f
```
In configure I used the following:
`./configure --with-apxs=/usr/local/apache2/bin/apxs --with-yajl`

I'm using Apache 2:
```
Server version: Apache/2.4.38 (Unix)
Server loaded:  APR 1.6.5, APR-UTIL 1.6.1
Compiled using: APR 1.6.5, APR-UTIL 1.6.1
Architecture:   64-bit
```
My operational system is:
CentOS Linux release 7.5.1804

Is there something I've be missing?

Already thanks!

**Comment by victorhora** [comment]
Hi @gspaivaequals,

The error message suggest that your version for Apache Runtime (APR) does not have support for crypto routines. This is required by some functionalities of ModSecurity.

I would suggest checking if your version of APR support crypto and upgrading or installing a proper version that have such support.
