### ISSUE TITLE
Modsecuirty : Loaded APR does not match with complied

### ISSUE THREAD

**Issue by surajy93** [SpiderLabs/ModSecurity#2044]
Kindly review image error log
![log](https://user-images.githubusercontent.com/42316893/54073410-bdf0e500-42ac-11e9-92d6-b4d01141e992.PNG)

**Comment by victorhora** [comment]
Hi @surajy93,

This means that your build of ModSecurity was **compiled** with a given version of Apache Runtime (APR) but it is now **running** with a different version of APR. You can either recompile ModSecurity or change your APR version (this can be more tricky to do).

ModSecurity may still work with that inconsistency, but you may face some stability issues or crashes.
