### ISSUE TITLE
Improve tag support in JSON logger

### ISSUE THREAD

**Issue by Paladin** [SpiderLabs/ModSecurity#2047]
**Describe the bug**
It's not a bug it's a feature.....request?

When using JSON log output, any tagging the rules do is not exposed to a json parser. In the audit_data attributes "messages" and "error_messages" the tags are shown as [tag "tagName"] but that doesn't make them visible to any JSON parser looking at them, without doing further regex or other string handling operations. (Likewise for the rule ID and the msg fields).

It would be more useful if the tags could be collected and exposed to the parser as well. Since they're typically in both audit_data.messages and audit_data.error_messages, you could probably settle for pulling them out of just one of the two and collecting them in a "tags" array. My preference would be for the array to be at the root level of the record, but putting them in the "transaction" structure or even at the audit_data level would be workable.

**Logs and dumps**

Here's relevant section of current log output. It's the "messages" attribute of the audit_data structure:
"messages":["Warning. Match of \"pm AppleWebKit Android\" against \"REQUEST_HEADERS:User-Agent\" required. [file \"/etc/httpd/owasp/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf\"] [line \"1268\"] [id \"920300\"] [rev \"3\"] [msg \"Requ
est Missing an Accept Header\"] [severity \"NOTICE\"] [ver \"OWASP_CRS/3.0.0\"] [maturity \"9\"] [accuracy \"8\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-protocol\"] [tag \"OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACC
EPT\"] [tag \"WASCTC/WASC-21\"] [tag \"OWASP_TOP_10/A7\"] [tag \"PCI/6.5.10\"] [tag \"paranoia-level/1000000\"]"]

(Yes, there's a joke in there to hide possibly confidential information.)

For the purposes of this example, the output should have this added at the appropriate point:

{"tags":["application-multi", "language-multi", "platform-multi", "attack-protocol", "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT", "WASCTC/WASC-21", "OWASP_TOP_10/A7", "paranoia-level/1000000"]}

**Comment by zimmerle** [comment]
Hi @Paladin,

Thank you for the report.  What is your ModSecurity version?

**Comment by Paladin** [comment]
Oh, sorry about that:

OWASP Rule Set : 3.0.2
mod_security: 2.9.2 
OS: Centos 7.6.1010
webserver: apache 2.4.37

I've been thinking about v3, but haven't had the time to spin up something to test it on, yet. It's not in the repos I normally pull from, so TBH I've been lazy about it.

**Comment by zimmerle** [comment]
This is something that we already have on v3, an example of the v3 auditlogs -

```json
"messages":[
         {
            "message":"",
            "details":{
               "match":"Matched \"Operator `Contains' with parameter `test' against variable `ARGS:param2' (Value: `test2' )",
               "reference":"o0,4v20,4o0,4v32,5",
               "ruleId":"1556",
               "file":"t.json",
               "lineNumber":"3",
               "data":"",
               "severity":"0",
               "ver":"",
               "rev":"",
               "tags":[
                  "a",
                  "b",
                  "c"
               ],
               "maturity":"0",
               "accuracy":"0"
            }
         }
      ]
```
