### ISSUE TITLE
Preferred way to add firewall rule

### ISSUE THREAD

**Issue by szepeviktor** [SpiderLabs/ModSecurity#2050]
Hello!

I've searched for "iptables" without success.

Could you tell me what solution **you guys are using** for making ModSecurity _tell_ (Linux) firewall to block an IP address?
Thank you.

**Comment by zimmerle** [comment]
Hi, @szepeviktor 

There is no preferable way to de such thing, that is really up to your requirements. If you need to do that, I would suggest a Lua script to feed an ordinary file with the list of IPs that you want to block. In a second process, you can read that file and finally feed the _iptables_ rules. That way, you will manage to keep privilege separation.

**Comment by szepeviktor** [comment]
Thank you.
I thought there is an example Lua script just for writing the attacking IP to a file.
