### ISSUE TITLE
Nginx 403 display is incorrect

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2051]
After installing modsecurity, I customized the 403 page., but it always redirected to nginx's own 403. Does modsecurity force the 403 page to redirected to the default 403 page?

This is my config:
 error_page  403       /403.html;
    location = /403.html {
        root html;
      }
    location = /wangjun {
        return 403;
          }
when I curl /wangjun It‘s working for 403  But when I triggered the modsecurity rule and jumped to nginx default 403, why?
the mod audit.log show

 "---UlxxkFzx---E--
<html>\x0d\x0a<head><title>403 Forbidden</title></head>\x0d\x0a<body>\x0d\x0a<center><h1>403 Forbidden</h1></center>\x0d\x0a<hr><center>nginx</center>\x0d\x0a</body>\x0d\x0a</html>\x0d\x0a

---UlxxkFzx---F--
HTTP/2.0 403
Server: nginx
Date: Thu, 28 Mar 2019 02:31:08 GMT
Content-Length: 146
Content-Type: text/html
Connection: close"

**Comment by victorhora** [comment]
Hi @Hello-Linux 

This is known limitation and it's being tracked at https://github.com/SpiderLabs/ModSecurity-nginx/issues/76.

Please check the issue and follow up with your observations there.

Thanks!

**Comment by kjbmobile1** [comment]
Stop tracking i am revoking your permission as of right now get out of my ass and my device now your rights have been revoke now do i need to report it to the proper uthorities

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Hello-Linux** [comment]
thank you
