### ISSUE TITLE
There is error with my rule not running even producing error with start nginx  

### ISSUE THREAD

**Issue by ibeata** [SpiderLabs/ModSecurity#2055]
**Describe the bug**

myenv
- openresty 1.13.6.2
- Modsecruity-nginx 1.0.0

**Logs and dumps**
```
[root@localhost web]# nginx 
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /var/local/share/patch_rules/dynamic.conf. Line: 2. Column: 150. Expecting an action, got:  "noauditlog,\ in /etc/nginx/vhost/80.conf:3

```

/var/local/share/patch_rules/dynamic.conf.
```
SecRule TX:REAL_IP "!@pmf /var/local/share/patch_rules/patch_rule_datas/WhiteIpUrlList/url12.data" 
     "noauditlog,\
      redirect:/403_forbidden.html,\
      id:282560035,\
      phase:request,\
      chain"
          SecRule REQUEST_FILENAME "@contains /winter"
```

In other machine , I run it well , but now it not run; what reason is it .

**Comment by ibeata** [comment]
I have tried it many times and it can be loaded if the string without '\\', but the crs-rules can be run if ruletxt having '\'.

**Comment by theMiddleBlue** [comment]
Hi @ibeata 

have you tried to avoid newline before the action? something like:

```
SecRule TX:REAL_IP "!@pmf /var/local/share/patch_rules/patch_rule_datas/WhiteIpUrlList/url12.data" "noauditlog,\
      redirect:/403_forbidden.html,\
      id:282560035,\
      phase:request,\
      chain"
          SecRule REQUEST_FILENAME "@contains /winter"
```

?

**Comment by ibeata** [comment]
> Hi @ibeata
> 
> have you tried to avoid newline before the action? something like:
> 
> ```
> SecRule TX:REAL_IP "!@pmf /var/local/share/patch_rules/patch_rule_datas/WhiteIpUrlList/url12.data" "noauditlog,\
>       redirect:/403_forbidden.html,\
>       id:282560035,\
>       phase:request,\
>       chain"
>           SecRule REQUEST_FILENAME "@contains /winter"
> ```
> ?

Not useful too, it can be effect unless seting all line in one line.

**Comment by ibeata** [comment]
@theMiddleBlue Not useful too, it can be effect unless seting all line in one line.  this error pruduced when i   remove `iptables` in cenots7. and then i can't run many packages.

**Comment by zimmerle** [comment]
Hi @ibeata,

Can you share with us what is your ModSecurity version? I want to check the version of your libModsecurity.

**Comment by ibeata** [comment]
i have redeploy it and run ok. i will open it until it happens. so i would close it at now.
