### ISSUE TITLE
Customer is unable to purchase an order from my site because mod_security is blocking it!

### ISSUE THREAD

**Issue by B8033783** [SpiderLabs/ModSecurity#2056]
Neither me or my customer is using mod security, my site is neopharmacies.com. She is getting the following message at checkout when using both pc and iphone on 2 different browsers:

"Not Acceptable!

An appropriate representation of the requested resource could not be found on this server. This error was generated by mod_security."

I have a screenshot but I can't attach it here, neither I can contact you and send it as you've made it impossible on your site. 

I will contact the regulation authorities and complain about your violation of every possible free market policy. This is outrageous!

**Comment by victorhora** [comment]
Hi @B8033783,

I believe you might be facing a false positive with your current ruleset or your improper configuration of ModSecurity on your environment. 

In order for the community to help you, you need to create an issue following the guidelines from our issue template available below providing as much information as possible from your environment:

https://github.com/SpiderLabs/ModSecurity/issues/new?template=bug-report-for-version-2-x.md

There's also a chance that your CDN or hosting provider has configured / enforced a ModSecurity on your environment (but failed to properly tune it) and in that case you need to reach out to them to properly tune it or disable your WAF if you wish to do so.

If you need prompt/enterprise support for your environment I would suggest you getting in touch with a vendor that can provide commercial support to you (e.g. https://www.modsecurity.org/help.html)
