### ISSUE TITLE
Add new operator @verifySVNR

### ISSUE THREAD

**Issue by Rufus125** [SpiderLabs/ModSecurity#2062]
Adding a new operator that detects Austrian social security numbers.

Meaning and calculation:
https://de.wikipedia.org/wiki/Sozialversicherungsnummer#%C3%96sterreich
https://de.wikipedia.org/wiki/Sozialversicherungsnummer#Berechnung
Unfortunately, I could only find links in German.

I have already written the code and will open a PR.

**Comment by zimmerle** [comment]
This was merged already :) thank you.
