### ISSUE TITLE
Hex encoding with wrong display

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2065]
**Describe the bug**

Hex encoding with wrong display:

   t:hexEncode: "ffffff91ffffffecffffffe6334bffffffebffffff87f...

in place of

   t:hexEncode: "91ece6334beb879a824a06c33b4cb4240e4c6f56"

I join patch in attachment.
[0001-fix-minor-Error-encoding-hexa-decimal.patch.txt](https://github.com/SpiderLabs/ModSecurity/files/3067352/0001-fix-minor-Error-encoding-hexa-decimal.patch.txt)

**To Reproduce**

Enable debug to 9
Load OWASP rule 901318

**Server (please complete the following information):**
 - ModSecurity v3.0.3
 - Direct integration

**Comment by victorhora** [comment]
Hi @tech-ozon-io,

Thanks for your contribution! :)

Do you mind submitting it in the form of a Pull Request? That way it triggers our buildbots to test the patch and makes it easy to have your name under as one of the contributors of ModSecurity ;)

Thanks!

**Comment by ghost** [comment]
HI Victor,

unfortunately, I'm a little bit dumb. I don't understand the pull-request system.

I understood: 

- I checked out the Modsec project,

- I write the patch in a new branch,

- I push the branch,

- I create the pull-request.

Git says me that I can't push new branch because I do not have right on the Modsec project.
I'm sure that something is wrong in this process, but I don't understand what.

Explain to me, and I will do a pull-request.

**Comment by ghost** [comment]
I found the way for pull request. that's done.

**Comment by zimmerle** [comment]
Merged already :) thanks!
