### ISSUE TITLE
Not able to access ModSecurity v3 reference manual

### ISSUE THREAD

**Issue by yashhere** [SpiderLabs/ModSecurity#2069]
<img width="1440" alt="Screenshot 2019-04-15 at 11 39 14 AM" src="https://user-images.githubusercontent.com/13733968/56110772-4ed57300-5f73-11e9-8e97-5d557b533c62.png">

Not sure, if this is the right place to post this issue. If this is not, please give proper directions, where I can get a fix.

**Comment by victorhora** [comment]
Hi @yashhere 

Yes, we've been working on a major update for the reference manual specifically for 3.x, but that is not ready yet.

For now, please use the link to the v2 reference manual which also covers for v3.x version:

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29

Thanks.
