### ISSUE TITLE
A thread deadlock occurred  when writing to SecAuditLog

### ISSUE THREAD

**Issue by xjjy1083** [SpiderLabs/ModSecurity#2079]
**A thread deadlock occurred  when writing to SecAuditLog**

`220 bool SharedFiles::write(const std::string& fileName, 
221     const std::string &msg, std::string *error) { 
 
222     std::pair<msc_file_handler *, FILE *> a;
223     std::string lmsg = msg;
224     size_t wrote;
225     bool ret = true;
226 
227     a = find_handler(fileName);
228     if (a.first == NULL) {
229         error->assign("file is not open: " + fileName);
230         return false;
231     }
232 
233     pthread_mutex_lock(&a.first->lock);                                                                                                            234     wrote = fwrite(reinterpret_cast<const char *>(lmsg.c_str()), 1,
235         lmsg.size(), a.second);  
236     if (wrote < msg.size()) {
237         error->assign("failed to write: " + fileName);
238         ret = false;
239     }
240     fflush(a.second);
241     pthread_mutex_unlock(&a.first->lock);
242 
243     return ret;
244 }`

A deadlock occurred at line 233.

**Comment by xjjy1083** [comment]
@zimmerle @victorhora

**Comment by victorhora** [comment]
Hi @xjjy1083,

Thanks for your report. Can you please provide more specific details on the ModSecurity version that this is happening? Does this behaviour also happens on the latest code from master?

Based on the output of the function names of your debugging session I believe you are talking about v3, but it help us a lot if you can tell us in detail and preferably follow the guidelines of the issue report template: https://github.com/SpiderLabs/ModSecurity/issues/new?template=bug-report-for-version-3-x.md

Thanks.

**Comment by zimmerle** [comment]
Closing this issue as it is missing feedback. There is indeed a critical section on the code, but the circumstances that lead this hypothetical deadlock are unknow.
