### ISSUE TITLE
The client is not blocked for 600 seconds for cc attack

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2081]
**Describe the bug**
When a client is making more than 60 requests (excluding static files) within
5 seconds, this is considered a 'burst'. After two bursts, the client is
not blocked for 600 seconds

my config is:
SecAction \
 "id:900700,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.dos_burst_time_slice=5',\
  setvar:'tx.dos_counter_threshold=60',\
  setvar:'tx.dos_block_timeout=600'"

But after 600 seconds I still can't access the site locally. Why?Shouldn't it be limited to 600 seconds?

Another problem is that my local IP is banned, but the website can be accessed normally after I change other browsers!Why? And when I restart my nginx server I can visit the website normally! why?
So I think This IP ban ended up not working for me!

And I see the #1803 his file is very working,But if I Change the browser type I'll have normal access the web server So I think this disabling policy is only for the combination of the browser and the IP address and not for the IP address alone。I hope the authorities fix these bugs quickly, as these are frequently used features!

**Logs and dumps**

Output of:
the audit log is:
610:ModSecurity: Warning. Matched "Operator `Ge' with parameter `2' against variable `IP:1.119.143.3_43ffffffc3236dffffffd4fffffff8ffffffceffffffb0fffffff153637fffffff81116bffffff83ffffffd4ffffffc46605::::DOS_BURST_COUNTER' (Value: `2' ) [file "/etc/nginx/modsecurity.d/rules/REQUEST-912-DOS-PROTECTION.conf"] [line "227"] [id "912170"] [rev ""] [msg "Potential Denial of Service (DoS) Attack from 1.119.143.3 - # of Request Bursts: 2"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-dos"] [hostname "1.119.143.3"] [uri "/category/wljz"] [unique_id "155713785952.253004"] [ref ""]

**Comment by victorhora** [comment]
Hi @Hello-Linux 

Isn't your issue the same as the one already being tracked at #1803 ?

**Comment by zimmerle** [comment]
Marking as a duplicate of #1803 as @Hello-Linux seems to be discussing the issue there.
