### ISSUE TITLE
SecRuleRemoveByTag regex wildcard

### ISSUE THREAD

**Issue by tomsommer** [SpiderLabs/ModSecurity#2083]
`SecRuleRemoveByTag` is apparently a wildcard, so `SecRuleRemoveByTag WEB` by default removes any tags with `WEB*`

This is not well documented nor perhaps intended?

It makes it hard to remove isolated tags, for instance if your tags are called `foo` and `foo-bar` and you do `SecRuleRemoveByTag foo`, even `foo-bar` tags are removed

**Comment by victorhora** [comment]
Hi @tomsommer 

Thanks for reporting. Can you please let us know if this behaviour happens both in v2 and v3?

It would be great if you could follow the issue template (eg. https://github.com/SpiderLabs/ModSecurity/issues/new?template=bug-report-for-version-2-x.md).

**Comment by tomsommer** [comment]
modsecurity-2.9.3
httpd-2.4.39
Linux 2.6.32-954.3.5.lve1.4.63.el6.x86_64

SecRuleRemoveByTag actions are not logged in debugLog, I checked

**Comment by zimmerle** [comment]
Hi, @tomsommer

I have failed to mark #2109  as a duplicate of this. Doing it now. As you may notice there was a discussion on #2109 about this particular issue.
