### ISSUE TITLE
Support for sanitise/sanitize args, headers, etc... in v3

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/ModSecurity#2089]
Hi,

is there a plan on when "sanitize actions" will be implemented in v3?

- sanitiseArg 
- sanitiseMatched
- sanitiseMatchedBytes
- sanitiseRequestHeader
- sanitiseResponseHeader

thanks!

**Comment by victorhora** [comment]
Hi @theMiddleBlue,

Yes, the sanitize actions are currently **planned** to be implemented as part of 3.0.4 and we already have an issue to track these here at https://github.com/SpiderLabs/ModSecurity/issues/1898. Please add your comments/concerns to that issue.

You can see all the issues/improvements tagged for 3.0.4/2.9.4 by checking the milestones:

https://github.com/SpiderLabs/ModSecurity/milestone/13
https://github.com/SpiderLabs/ModSecurity/milestone/14

Thanks
