### ISSUE TITLE
Regarding Custom rules in Modsecuirty - whitelisting parameters

### ISSUE THREAD

**Issue by Vaibhavgoe** [SpiderLabs/ModSecurity#2090]
We are trying to whitelist the pasword parameter in our application .  below rule is not working 
SecRule ARGS_NAMES "password" "id:2,phase:2,log,allow,ctl:ruleEngine=Off"

can anyone please suggest, how to achieve the same.

**Comment by csanders-git** [comment]
That will work, it is likely the location of that rule that is the problem - This rule should be placed BEFORE rules you want it to effect. ALSO, and maybe more important. be very precise if your going to use the default regex operator. i.e ^passworod$, i'd recommend using @streq instead (https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#streq)

For more examples check out https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example

**Comment by victorhora** [comment]
Closing this one based @csanders-git comment. Thanks.

**Comment by Vaibhavgoe** [comment]
Thanks a lot....it is working
