### ISSUE TITLE
Minor spellcheck in wiki ('sigle')

### ISSUE THREAD

**Issue by sblondon** [SpiderLabs/ModSecurity#2104]
In https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29 an 'n' character is lacking:
`deleting all sigle quotes` -> `deleting all single quotes`

I don't send a PR because I didn't find a way to fork the wiki.

**Comment by zimmerle** [comment]
Fixed! Thank you @sblondon!
