### ISSUE TITLE
Missing throw in Operator::instantiate?

### ISSUE THREAD

**Issue by marduone** [SpiderLabs/ModSecurity#2106]
Building ModSecurity 3.0.3 package (openSUSE Tumbleweed, GCC 9) produced the following compiler warning which the build system flagged as an error:  
```
[  293s] operators/operator.cc: In static member function 'static modsecurity::operators::Operator* modsecurity::operators::Operator::instantiate(std::string, std::string)':
[  293s] operators/operator.cc:140:48: warning: control reaches end of non-void function [-Wreturn-type]
[  293s]   140 |     std::string op_ = utils::string::tolower(op);
[  293s]       |                                                ^
```

Looking at the code in question, it seems that the warning is caused by a missing throw keyword right at the end of the function, where I suppose you want to throw an invalid argument exception if none of operator checks match.

The following patch got rid of that compiler warning:  
```c++
--- modsecurity-v3.0.3.orig/src/operators/operator.cc
+++ modsecurity-v3.0.3/src/operators/operator.cc
@@ -191,7 +191,7 @@ Operator *Operator::instantiate(std::str
         return new UnconditionalMatch();
     }
 
-    std::invalid_argument("Operator not found.");
+    throw std::invalid_argument("Operator not found.");
 }
 
 }  // namespace operators
```

While the above patch seems correct to me, I am not 100% sure whether this is a genuine bug in the code or just newer GCC being stricter and flagging non-issues as warnings.

**Comment by zimmerle** [comment]
Thank you @marduone. The code is now on our master branch.
