### ISSUE TITLE
Error Compile nginx 1.13.4+modsecurity

### ISSUE THREAD

**Issue by kulitkerang** [SpiderLabs/ModSecurity#2108]
my folder :
- cd /usr/src/nginx-1.13.4
- and i try #./configure --user=www-data --group=www-data --add-module=/usr/src/ModSecurity/nginx/modsecurity --with-http_ssl_module --with-http_v2_module
- and next i try make

this error i see is :
cc: error: /usr/src/ModSecurity/nginx/modsecurity/../../standalone/.libs/standalone.a: No such file or directory
objs/Makefile:253: recipe for target 'objs/nginx' failed

how to fix it ? thanks

**Comment by zimmerle** [comment]
Hi @kulitkerang,

Make sure you have followed the compilation recipes stated here: 
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

**Comment by kulitkerang** [comment]
ohh okay thanks
