### ISSUE TITLE
variable check/comparison isn't working in ruid2

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2121]
**Describe the bug**

When using Apache mod_ruid2 with mod_security2-2.9.3, some rules (conditional in this case) aren't working. Specifically, a very common WordPress brute force rule where "SecRule "ip:bf_counter" "@gt 10" returns 0. This rule works under suexec with no issue.

**Logs and dumps**

https://github.com/SpiderLabs/ModSecurity/issues/2117#issuecomment-503035779

**To Reproduce**

- Ensure you are running prefork+mod_ruid2
- Use the provided ruleset (at the bottom)
- Fail logging into a WordPress site on that server >10 times, you shouldn't be blocked
- The counter variable is incremented but nothing else occurs
- Switch to event+mod_suexec
- Fail logging into a WordPress site again and this should result in blocking you

**Expected behavior**

Support/compatibility for ruid2 was recently released, so I would expect all rules to be compatible.

**Server (please complete the following information):**
 - ModSecurity version (and connector): ea-apache24-mod_security2-2.9.3-2.el7.cloudlinux
 - WebServer: ea-apache24-2.4.39-3.el7.cloudlinux.2.x86_64
 - OS: CloudLinux release 7.6 (Vladimir Lyakhov)
- Kernel: 3.10.0-962.3.2.lve1.5.25.6.el7.x86_64
- Arch: x86_64
- Environment: kvm

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? no others
 - What is the version number? N/A

```
SecAction phase:1,nolog,pass,initcol:ip=%{REMOTE_ADDR},initcol:user=%{REMOTE_ADDR},id:6
<Locationmatch "/wp-login.php">
# Setup brute force detection.
# React if block flag has been set.
SecRule user:bf_block "@gt 0" "deny,status:401,log,id:7,msg:'ip address blocked for 5 minutes, more than 10 WordPress login attempts in 3 minutes.'"
# Setup Tracking. On a successful login, a 302 redirect is performed, a 200 indicates login failed.
SecRule RESPONSE_STATUS "^302" "phase:5,t:none,nolog,pass,setvar:ip.bf_counter=0,id:8"
SecRule RESPONSE_STATUS "^200" "phase:5,chain,t:none,nolog,pass,setvar:ip.bf_counter=+1,deprecatevar:ip.bf_counter=1/180,id:9"
SecRule ip:bf_counter "@gt 10" "t:none,setvar:user.bf_block=1,expirevar:user.bf_block=300,setvar:ip.bf_counter=0"
</locationmatch>
```

**Comment by zimmerle** [comment]
Hi @afortman-cPanel,

In #2117 I have spotted a possible problem with these rules. It is: the values of the collection are not absolute as it depends on arbitrary sync. A lot of variables could affect the syncing operation, for instance, the number of workers/threads that you have working in your webserver. I am not aware of the details on the ruid2 implementation; regardless I will give it a shout reading the debug logs to understand the values saved on those collections upon the execution of rule 9.

You are saying that the rules are working well with suexec, but perhaps is just because the thresholds at rule 9 was adjusted in that sense. It worth to debug in the use case that you also think that it is working, just to double-check.

**Comment by karljohns0n** [comment]
I have the same issue on a lot of cPanel servers with ruid2 since cPanel has upgraded to mod_security2-2.9.3. It always worked fine in combination with CSF firewall to block robots that bruteforce.

```
SecAction phase:1,nolog,pass,initcol:ip=%{REMOTE_ADDR},initcol:user=%{REMOTE_ADDR},id:10011
<LocationMatch "/wp-login.php">
        SecRule user:bf_block "@gt 0" "deny,status:401,log,msg:'ip address blocked for 20 minutes, more than 3 login attempts in 5 minutes.',id:10011"
        # Setup Tracking.  On a successful login, a 302 redirect is performed, a 200 indicates login failed.
        SecRule RESPONSE_STATUS "^302" "phase:5,t:none,nolog,pass,setvar:ip.bf_counter=0,id:10012"
        SecRule RESPONSE_STATUS "^200" "phase:5,chain,t:none,nolog,pass,setvar:ip.bf_counter=+1,deprecatevar:ip.bf_counter=1/300,id:10013"
        SecRule ip:bf_counter "@gt 3" "t:none,setvar:user.bf_block=1,expirevar:user.bf_block=1200,setvar:ip.bf_counter=0"
</LocationMatch>
```
