### ISSUE TITLE
msg "Failed to parse request body."  data "JSON parsing error: lexical error: invalid char in json text.\x0a"

### ISSUE THREAD

**Issue by mf33a2t556d** [SpiderLabs/ModSecurity#2122]
on Solaris 11 use IBM_HTTP_Server/8.5.5.10 (Unix) and modsecurity v 2.9.3

uname -a
SunOS 5.11 11.3 sun4v sparc sun4v

IBM_HTTP_Server/8.5.5.10 (Unix)

Issue is : unable to trigger alert for SQL Injection rule, getting the following error in debug log : msg "Failed to parse request body."  data "JSON parsing error: lexical error: invalid char in json text.\x0a"

audit log : 

--00006d1d-A--
[24/Jun/2019:16:45:19 --0400] 4@mdXgrIHEoAAAZoQusAAAAY 111.111.111.111 45424 100.100.100.100 9586
--00006d1d-B--
POST /myapp/myextract/myexcelreport HTTP/1.1
Accept: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Content-Type: application/json; charset=utf-8
Referer: https://mytest.web.server/myapp/mypath/index.html
Accept-Language: en-CA
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
Host: localhost:9586
Content-Length: 69
Cache-Control: no-cache
ARM_CORRELATOR: 002ECC00303030303243334630303035384331374533453935343232303030313546394430303031354639440001
X-Forwarded-For: 103.103.103.103
$WSXCTCONTEXTID: 4@lUIo5qVxMAACw-NCQAAAAs
$WSCS: TLS_RSA_WITH_AES_128_GCM_SHA256
$WSIS: true
$WSSC: https
$WSPR: HTTP/1.1
$WSRA: 101.101.101.101
$WSRH: 101.101.101.101
$WSSN: mytest.web.server
$WSSP: 443
$WSSI: JuFzMZOzbdt/5ktZiZa0Vt9c93N9hY6NlEVweLSfbRg=
Surrogate-Capability: WS-ESI="ESI/1.0+"
$WSFO: TRUE
_WS_HAPRT_WLMVERSION: -1
Expect: 100-Continue

--00006d1d-C--
select * from mytable where first_name = 'myfirstname' and last_name = 'mylastname'
--00006d1d-F--
HTTP/1.1 200 OK
X-Powered-By: Servlet/3.0
Content-Disposition: myqueryReport.xlsx
Content-Length: 4079
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: DENY
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Content-Language: en-CA

--00006d1d-E--

--00006d1d-H--
Message: JSON parsing error: lexical error: invalid char in json text.

Message: Warning. Match of "eq 0" against "REQBODY_ERROR" required. [file "/conf/modsecurity.conf"] [line "61"] [id "200002"] [msg "Failed to parse request body."] [data "JSON parsing error: lexical error: invalid char in json text.\x0a"] [severity "CRITICAL"]
Stopwatch: 1561409119427934 367422 (- - -)
Stopwatch2: 1561409119427934 367422; combined=39887, p1=138, p2=39736, p3=6, p4=2, p5=5, sr=0, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/).
Server: IBM_HTTP_Server
Engine-Mode: "DETECTION_ONLY"

--00006d1d-Z--

debug log : 

[24/Jun/2019:16:45:19 --0400] [mytest.web.server/sid#1e7c90][rid#edb780][/myapp/myextract/myexcelreport][2] JSON parsing error: lexical error: invalid char in json text.

[24/Jun/2019:16:45:19 --0400] [mytest.web.server/sid#1e7c90][rid#edb780][/myapp/myextract/myexcelreport][2] Warning. Match of "eq 0" against "REQBODY_ERROR" required. [file "/conf/modsecurity.conf"] [line "61"] [id "200002"] [msg "Failed to parse request body."] [data "JSON parsing error: lexical error: invalid char in json text.\x0a"] [severity "CRITICAL"]

Please kindly help to resolve the issue

**Comment by zimmerle** [comment]
Seems to be a duplicate of: #1964
