### ISSUE TITLE
Installation problems with packages and scripts (update wiki)

### ISSUE THREAD

**Issue by Theoooooo** [SpiderLabs/ModSecurity#2126]
I'm following the installation configuration for CentOS7 1804 Minimal installation. Just to precise it's a fresh install of CentOS. No other package has been installed before i start doing the installation of ModSecurity.

While following the installation of the version 3.x, i encounter many problems that are present possibly because of packages that are not listed in the requirements.

There is a list of all the problems i encounter :

- Packages needed but not present in the installation process : libtool, automake, autoconf

- Errors while executing build.sh :
```
[root@modsecurity ModSecurity]# ./build.sh
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build'.
libtoolize: copying file `build/libtool.m4'
libtoolize: copying file `build/ltoptions.m4'
libtoolize: copying file `build/ltsugar.m4'
libtoolize: copying file `build/ltversion.m4'
libtoolize: copying file `build/lt~obsolete.m4'
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
```

- Errors while executing configure :
```
checking for libpcre config script... no
configure: *** pcre library not found.
configure: error: pcre library is required
```
But the package pcre is already installed :
```
[root@modsecurity ModSecurity]# yum install pcre
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.jaleco.com
 * extras: mirrors.mit.edu
 * updates: mirrors.seas.harvard.edu
Package pcre-8.32-17.el7.x86_64 already installed and latest version
Nothing to do
```
And the package libpcre is not available :
```
[root@modsecurity ModSecurity]# yum install libpcre
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.jaleco.com
 * extras: mirrors.mit.edu
 * updates: mirrors.seas.harvard.edu
No package libpcre available.
Error: Nothing to do
```

If you got the answer to these problems, i will update this topic if everything is resolved

**Comment by defanator** [comment]
@Theoooooo try `yum install pcre-devel`.

**Comment by Theoooooo** [comment]
@defanator Thanks for the reply. There is the output of the 2 script after i install pcre-devel :

build.sh :
```
[root@modsecurity ModSecurity]# ./build.sh
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build'.
libtoolize: copying file `build/libtool.m4'
libtoolize: copying file `build/ltoptions.m4'
libtoolize: copying file `build/ltsugar.m4'
libtoolize: copying file `build/ltversion.m4'
libtoolize: copying file `build/lt~obsolete.m4'
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
```

configure :
```
ModSecurity -  for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.9.2-30-gbf234eb
   + SecLang tests                                 ....5d85f36

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (GeoIP) v1.5.0
         -lGeoIP  , -I/usr/include/
   + LibCURL                                       ....found v7.29.0
      -lcurl  ,  -DWITH_CURL
   + YAJL                                          ....found v2.0.4
      -lyajl  , -DWITH_YAJL
   + LMDB                                          ....not found
   + LibXML2                                       ....found v2.9.1
      -lxml2 -lz -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....found v501
      -llua-5.1 -L/usr/lib64/, -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled
```

I'm following the other part of the installation and i will come back if there is any errors

**Comment by Theoooooo** [comment]
@defanator after doing "make install", the libs has been installed at ``` /usr/local/modsecurity/lib ```

But what to do next ? 
I'm following the documentation of the 2.x version for nginx but it tell you to download the standalone version at this link : https://www.modsecurity.org/download.html. 
I'm just confused right now of what is the next step ...

**Comment by zimmerle** [comment]
Hi @Theoooooo,

There are two different versions of ModSecurity being maintained:
 - Version 2.x - [v2/master](https://github.com/SpiderLabs/ModSecurity/tree/v2/master)
 - Verison 3.x - [v3/master](https://github.com/SpiderLabs/ModSecurity/tree/v2/master)

Version 3 is the best choice for nignx users. In order to have it working with nignx there are two steps that you have to follow. The first step is to install the library. Apparently, you already installed. In the second step, you need to install the nginx connector - 

https://github.com/SpiderLabs/ModSecurity-nginx


There are some installation recipes here:
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x
