### ISSUE TITLE
is it possible to use variable for SecRemoteRules keys or param?

### ISSUE THREAD

**Issue by redbox-cdn** [SpiderLabs/ModSecurity#2132]
Is it possible to use variable for SecRemoteRules keys or param?

I would like to  set existing requst header value in SecremoteRules.

**Comment by zimmerle** [comment]
Hi @redbox-cdn,

That is not possible. The Rules are loaded per webserver instantiation. At the time that the rules are loaded, there is no information about the client. I am curious though, what would be your use case? 

Perhaps you can achieve similar functionality (from the user perspective) with a different approach.

**Comment by redbox-cdn** [comment]
Hi  Sorry for my late reply.

I would like to cosider to change policy per users dynamically.

Example, as I can see  the rules are loaded per web server instantiation, I will create small API on the remote server.
remote server will detected query or keys header and then I hope correct policy is deliver per users.
ex: in case of modsec key :user1.
Web server(remote) will  response of user1.conf.

*In additon, modsec web server must re-loaded.

**Comment by zimmerle** [comment]
The best way to achieve such functionality is to expend ModSecurity with Lua or Python. That way you can dynamically apply logic based on parameters. Load the rules on every hit, will cause a very huge impact on performance, not to mention that won't be an easy way to recover from rules errors.

**Comment by redbox-cdn** [comment]
I will consider Lua scripting. 

Thanks
