### ISSUE TITLE
use include files in modsecurity_rules_remote

### ISSUE THREAD

**Issue by carolfly86** [SpiderLabs/ModSecurity#2133]
Hi,

Can we use `include` directives in a remote file specified in`modsecurity_rules_remote` to reference to other remote files? 

I tried a simple example as below:
``` 
modsecurity on;
modsecurity_rules_remote my-server-key https://xxx.s3.amazonaws.com/include.conf;
```

and include.conf 
```include https://xxx.s3.amazonaws.com/modsecurity.conf```

It would complain 
```nginx: [emerg] "modsecurity_rules_remote" directive Rules error. File: https://xxx.s3.amazonaws.com/include.conf. Line: 1. Column: 61. https://xxx.s3.amazonaws.com/modsecurity.conf: Not able to open file. Looking at: 'https://xxx.s3.amazonaws.com/modsecurity.conf'```

**Comment by carolfly86** [comment]
I think `SecRemoteRules` can be used to reference a specific file, but if we need to reference multiple files it doesn't seem to work with `SecRemoteRules key https://xxx.s3.amazonaws.com/*.conf`

**Comment by zimmerle** [comment]
Hi @carolfly86,

The SecRemoteRule is not a directory inclusion, rather it is an HTTP request. The best way to achieve what you are looking for is to have all files together in a single file, leading to a single HTTP request 

Notice that includes - regardless local or from remote rules - does not accept an HTTP request.
