### ISSUE TITLE
Debian 10 

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2135]
What is the installation process for debian 10?

**Comment by MrBorderline** [comment]
https://www.linuxjournal.com/content/modsecurity-and-nginx

**Comment by victorhora** [comment]
It depends which version of ModSecurity you're trying to install:

For version 3.x: You can probably use the Compilation Recipe for Ubuntu (with slightly different package names): https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x#ubuntu-1504 

For version 2.x: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#Installation_Methods

There might deb packages for Debian 10 for them too.
