### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by musklor** [SpiderLabs/ModSecurity#2138]
Hello,
Nextcloudpi : v1.15.3
Error : Request Entity Too Large
When : upload
Board : RPI3B
Post_max_size = 10G
upload_max_filesize = 10G
Debian buster (OK with Debian stretch)

libapache2-mod-security2/stable,now 2.9.3-1 armhf  [installé]
  Tighten web applications security for Apache

libmodsecurity-dev/stable 3.0.3-1 armhf
  ModSecurity v3 library component (development files)

libmodsecurity3/stable 3.0.3-1 armhf
  ModSecurity v3 library component

modsecurity-crs/stable,now 3.1.0-1 all  [installé, automatique]
  OWASP ModSecurity Core Rule Set

Script used (installation and configuration) https://github.com/nextcloud/nextcloudpi/blob/master/bin/ncp/SECURITY/modsecurity.sh

**Comment by eddie4** [comment]
Did you see the size limit in the modsecurity config?
line 38 & 39
https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended

**Comment by musklor** [comment]
I tried with a large SecRequestBodyLimit but no way

**Comment by airween** [comment]
It's not so clear what are you using, because you wrote:

> libapache2-mod-security2/stable,now 2.9.3-1 armhf [installé]
> Tighten web applications security for Apache
> 
> libmodsecurity-dev/stable 3.0.3-1 armhf
> ModSecurity v3 library component (development files)
> 
> libmodsecurity3/stable 3.0.3-1 armhf
> ModSecurity v3 library component

`libapache2-mod-security2` is an **Apache** module. The ModSecurity v2 works only with Apache (as stable).

`libmodsecurity3` is a library, and currently works only with **nGinx** (from the most popular webservers), but not with the Apache. I don't know about nginx module for Debian/Raspbian, but may be you've found one, just not listed above.

You wrote that you set up the `post_max_size = 10G` and `upload_max_filesize = 10G` variables, but these are PHP variables.

How do you configured your webserver? Have you set up any limit?

Note, that the script what you've [linked](https://github.com/nextcloud/nextcloudpi/blob/bcef6bf36d05fcdbc9391ccf7aa557aa730c6f77/bin/ncp/SECURITY/modsecurity.sh#L73-L74) contains
```
# UPLOADS ( 5 MB max excluding file size )
SecRequestBodyNoFilesLimit 5242880
```
a limit. Did you increased it?

**Comment by musklor** [comment]
Already tried. In fact I use "nextcloudpi" and since debian buster I can't upload with modsecurity v2 enabled. (The script didn't change) I'd like to help "nextcloudpi dev".
We use libapache2-mod-security2/stable,now 2.9.3-1 and modsecurity-crs/stable,now 3.1.0-1 all
https://github.com/nextcloud/nextcloudpi/issues/959

**Comment by airween** [comment]
And what do you see in error.log/modsec_debug.log?

**Comment by musklor** [comment]
Modsec_debug.log is empty
Error.log

 Jul 30 00:00:02.805824 2019] [ssl:warn] [pid 18342:tid 1996135840] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name                                                                       [Tue Jul 30 00:00:02.808749 2019] [mpm_event:notice] [pid 18342:tid 1996135840] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1c configured -- resuming normal operations                                                                       [Tue Jul 30 00:00:02.808783 2019] [core:notice] [pid 18342:tid 1996135840] AH00094: Command line: '/usr/sbin/apache2'                                           [Tue Jul 30 23:23:43.207843 2019] [mpm_event:notice] [pid 18342:tid 1996135840] AH00493: SIGUSR1 received.  Doing graceful restart                              [Tue Jul 30 23:23:43.496771 2019] [ssl:warn] [pid 18342:tid 1996135840] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jul 30 23:23:43.504553 2019] [mpm_event:notice] [pid 18342:tid 1996135840] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1c   configured -- resuming normal operations
[Tue Jul 30 23:23:43.504584 2019] [core:notice] [pid 18342:tid 1996135840] AH00094: Command line: '/usr/sbin/apache2'

**Comment by airween** [comment]
Could you try it **without** modsecurity? Just disable it, any other settings remains as it is.

**Comment by musklor** [comment]
Without modsecurity I can upload a large file.

**Comment by airween** [comment]
I can't help more based on these information - see another topics, eg:
https://talk.plesk.com/threads/modsecurity-post-failure-with-413-request-entity-too-large.339896/

**Comment by victorhora** [comment]
@musklor can you provide more details? Also make sure you set SecRequestBodyLimit as well. Also try with "SecRequestBodyLimitAction ProcessPartial"

**Comment by musklor** [comment]
With "SecRequestBodyLimitAction ProcessPartial", I have a connection error.
SecRequestBodyLimit very large.

Apache 2.4.38
libapache2-mod-security2/stable,now 2.9.3-1 and modsecurity-crs/stable,now 3.1.0-1 all

**Comment by zimmerle** [comment]
Hi @musklor,

It is very likely that you are facing a bug in version 2.x for nginx. Any chance to upgrade to version 3?

**Comment by musklor** [comment]
Apache issue
