### ISSUE TITLE
Add a new collection that keeps track of which transformations modified a target

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#214]
MODSEC-63: The TFN collection would be populated with target-key=modified-transformation-list

{noformat}
SecRule ARGS "bar" "t:none,t:trim,t:lowercase,t:replaceComments...
{noformat}

{noformat}
GET /?foo=+Foo/_+bar+_/&bar=Bar
{noformat}

Would yield:

{noformat}
TFN:ARGS:foo = t:trim,t:lowercase,t:replaceComments
TFN:ARGS:bar = t:lowercase
{noformat}

And then you could do an anomaly adjustment based off this data:

{noformat}
SecRule TFN "@contains t:replaceComments" "pass,nolog,setvar:tx.anomaly=+5"
{noformat}

**Comment by zimmerle** [comment]
The TFN collection will be always populated within the content specified in the RULE itself and in the default action. With that, it will be possible to know those by the time that the rule is written. I am not sure if there is the need for such variable.
