### ISSUE TITLE
Regarding Modsecurity rule for mp4

### ISSUE THREAD

**Issue by Vaibhavgoe** [SpiderLabs/ModSecurity#2141]
Dear All, 
     We have configured nginx web server as reverse proxy and enable mod security.  There is one mp4 file buffering in application with HTML 5 video tag. When we disable the modsecurity in nginx,  it is playing perfectly. But when we enable it,  it is not playing.. And showing 504 gateway error. There is no modsecurity error log also to identify the issue. Even we set the secruleengine as detectiononly, the same problem occur. Please help us to resolve the issue

**Comment by airween** [comment]
I assume you're using libmodsecurity3 with nGinx.

You can set up the debug log in your configuration file:

```
SecDebugLog /var/log/nginx/modsec_debug.log
SecDebugLogLevel 9
```
Could you paste here your set up?
```
grep DebugLog /path/to/your/modsecurity.conf
```

**Comment by Vaibhavgoe** [comment]
Thanks for reply,
 we have checked that lesser size of mp4 file is working fine. but large size mp4 file is not buffering. 
The setting for responselimit in modsecurity conf file is as follow.
SecResponseBodyAccess On
SecResponseBodyMimeTypesClear
SecResponseBodyMimeType text/plain text/html text/xml 
SecResponseBodyLimit 249112638
SecResponseBodyLimitAction ProcessPartial

Please lets us know to set any value

Thanks

**Comment by airween** [comment]
I'm not sure that the response 504 triggered by ModSecurity. That's why it would be good to see the error/debug logs...

**Comment by Vaibhavgoe** [comment]
by analyzing the debug log. we found the following error
Initialising transaction (txid dcAcAcAcAcAMAcRcAcAcAcAc).
 Transaction context created (dcfg 7f9bc24be980).
Starting phase REQUEST_HEADERS.
 Second phase starting (dcfg 7f9bc24be980).
 Input filter: This request does not have a body.
 Starting phase REQUEST_BODY.
Hook insert_filter: Adding output filter (r 7f9bc24440a0).
 Starting phase RESPONSE_HEADERS.
 Output filter: Not buffering response body for unconfigured MIME type "video/mp4".
Output filter: Completed receiving response body (non-buffering).
Starting phase RESPONSE_BODY.
Output filter: Output forwarding complete.
 Initialising logging.
 Starting phase LOGGING.
Recording persistent data took 0 microseconds.
 Audit log: Ignoring a non-relevant request.

Please suggest

**Comment by csanders-git** [comment]
Add that mime type to your allowed list :)

**Comment by Vaibhavgoe** [comment]
This issue is not related to mime type. small size in file is working fine.

**Comment by airween** [comment]
Could you try it **without** modsecurity? (On the same environment, of course...)

**Comment by Vaibhavgoe** [comment]
yes it is working fine by disabling the modsecurity in nginx configuration file. after enable it, it is not working.

**Comment by airween** [comment]
We have to see your full modsec_debug.log, not just the chunked lines what you shared above. Also need your nginx's error.log.

**Comment by zimmerle** [comment]
Hi @Vaibhavgoe,

Is this really version 3 or version 2? There is a known bug in version 2 regarding the buffer sizes that can cause exactly that behavior. If that is the case I strongly recommend you to move forward to version 3.
