### ISSUE TITLE
www.modsecurity.org SSL certificate expired

### ISSUE THREAD

**Issue by mstrokin** [SpiderLabs/ModSecurity#2142]
Subj.

**Comment by mstrokin** [comment]
Firefox still complains about the certificate because it uses weak/insecure encryption

**Comment by h0l0gram** [comment]
[SSL/TLS check](https://www.ssllabs.com/ssltest/analyze.html?d=modsecurity.org) shows that the server does not support TLS 1.2 nor 1.3. No Forward Secrecy but insecure RC4 (TLS_RSA_WITH_RC4_128_*).
I assume that disabling the weak RC4 ciphers and enabling TLS 1.2 and 1.3 will fix this issue.

**Comment by zimmerle** [comment]
Certificate renewed.
