### ISSUE TITLE
Are ModSec & RuleSet thread-safe ?

### ISSUE THREAD

**Issue by psetevik** [SpiderLabs/ModSecurity#2144]
Just an information request.

Assuming a multhreaded application (N "worker" threads), can one use same instance of ModSec (eg modsec = msc_init();) and RuleSet (eg rules = msc_create_rules_set();) in different threads ? Are these read-only and thread-safe after the creation ?

Or do I need to create these per-thread ?

And lastly, can I reuse MSC Transactions so I dont have to create these anew every time . Is there a reset function to prepare for new conn/req/resp ?

**Comment by zimmerle** [comment]
Hi @psetevik,

Both (msc_init and msc_create_rule_set) are meant to be used before the fork. Every process should share the same memory space as the rule could consume a significative amount of memory; we don't want to replicate that.

With that said, if you have to reload the rules I would recommend creating new workes, something that depends on the size of your rules that you want to load. We have a rule reload on the 3.1-experimental branch, with some test/example application - https://github.com/SpiderLabs/ModSecurity/tree/v3/dev/3.1-experimental/examples/configuration_reload

The reuse of the object Transaction is something that we consider to support but it is not ready yet. On 3.1 experimental branch, we already have a stack allocator which meant to work with its full benefit whenever the object reuse is ready. Want to help us with that?
