### ISSUE TITLE
Concurrent logging buggy without /etc/passwd

### ISSUE THREAD

**Issue by azurit** [SpiderLabs/ModSecurity#2147]
**Describe the bug**

When running in environment without /etc/passwd (or without access to it), concurrent logging is very buggy as it cannot find user names, the uninitialized/empty memory data is used as names of files in /tmp and in SecAuditLogStorageDir. The problem is in file apache2/msc_logging.c, function construct_auditlog_filename, lines:

```
char *username;
...
apr_uid_name_get(&username, uid, mp);

```

The return value of function apr_uid_name_get should be checked and if getting user name failed, something other should be used (i suggest UID).

**Server (please complete the following information):**
 - ModSecurity version (and connector): 2.9.3
 - WebServer: apache 2.4.25 running in very strict environment done using apparmor
 - OS (and distro): Debian Stretch

**Comment by azurit** [comment]
Also file apache2/persist_dbm.c, functions collection_retrieve_ex, collection_store and collections_remove_stale.

**Comment by zimmerle** [comment]
Hi @azurit,

Thank you for the report, I am liking this issue to #2046 as it seems to be related.

**Comment by martinhsv** [comment]
Closing per duplicate previously cited.
