### ISSUE TITLE
 Execute sh bulid.sh installation error 

### ISSUE THREAD

**Issue by jiangsi520** [SpiderLabs/ModSecurity#2150]
When I executed sh bulid. sh, the following errors occurred. They were all installed according to the method provided in the installation document.
![16K{YKSB2E({SQ2U@2Q% OK](https://user-images.githubusercontent.com/30169495/63215057-62782c80-c153-11e9-985a-aef24cac4d15.png)

**Comment by csanders-git** [comment]
make sure you have cmake, libtool, automake, and make

**Comment by jiangsi520** [comment]
> 确保你有cmake，libtool，automake和make

I have installed all four of the packages you mentioned, or there will be the above mistakes. Is there any relationship between the packages?

**Comment by csanders-git** [comment]
yes,  there is a relationship between these packages.

**Comment by jiangsi520** [comment]
> 是的，这些包之间存在关系。

 The same problem still happens.

**Comment by csanders-git** [comment]
I recommend taking a look at how the docker files build modsec, they build on top of Ubuntu, https://github.com/CRS-support/modsecurity-docker
