### ISSUE TITLE
Wiki - modsecurity3 missing dependency

### ISSUE THREAD

**Issue by gotwf** [SpiderLabs/ModSecurity#2153]
Wiki documentation for Minimal Centos7 module neglects to include pcre-devel in dependency installation.  No big deal, just thought you may want to know.  Page here:

https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

**Comment by zimmerle** [comment]
Hi @gotwf,

Fixed! Thanks!
