### ISSUE TITLE
  Has modsecruity 3 removed CSRF protection? If not, where is the relevant configuration file?

### ISSUE THREAD

**Issue by jiangsi520** [SpiderLabs/ModSecurity#2158]
Has modsecruity 3 removed CSRF protection? If not, where is the relevant configuration file?

**Comment by zimmerle** [comment]
Hi @jiangsi520,

ModSecurity itself does not provide to your site any specific protection, that is up to the rules. Please double check the rules that you are using to see if they offer the CSRF protection that you are looking for.
