### ISSUE TITLE
Implement parameterized actions

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#216]
MODSEC-65: Allow arbitrary parameters for actions:

{noformat}
# Instead of:

SecRule ARGS "@pmFromFile some/file.pm" "..."
# This:

SecRule ARGS "@pm(file) some/file.pm" "..."
# And then expand without having to add more operators:

SecRule ARGS "@pm(file,boundLeft,boundRight) some/file.pm" "..."
{noformat}

**Comment by victorhora** [comment]
Closing as there was no feedback or further interest on this issue / feature.
