### ISSUE TITLE
ModSecurity 3 - Log Format and Nginx Variables

### ISSUE THREAD

**Issue by danielwrayois** [SpiderLabs/ModSecurity#2160]
Hi, I am wondering if it possible to include Nginx variables into the ModSecurity 3 log output, for example our systems capture unique request and session ID's and we would find it very useful to include these two unique parametes in a ModSecurity event. This will allow our monitoring solution to show a combination of Nginx access.log (accepted) requests, and ModSecurity events / error.log (failed) requests in one stream under a users session ID.

I would like to change the log output to be as follows:

`2019/08/29 09:59:06 [error] 13#13: *1031 [client xxx.xxx.xxx.xxx] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator "Rx" with parameter "<script>" against variable "ARG
S:note" (Value: "<script>alert(1)</script>" ) [file "/etc/nginx/conf.d/modsecurity/modsecurity_main.conf"] [line "64"] [id "53"] [rev ""] [msg "XSS <script> tag detected"] [data ""] [se
verity "3"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "xxx.xxx.xxx.xxx"] [uri "/api/xxx/xxx/xxx"] [unique_id "156707274637.310556"] [ref "o0,8v1601,25"], client: xxx.xxx.xxx.xxx, server: dev-xxx.xxx.co.uk, request: "POST /api/xxx/xxx/xxx HTTP/1.1", host: "dev-xxx.xxx.co.uk", request_id: "a885bbb7dc0a73b8e592bdae4818b3c0", session_id: "id=020011AC909E675D0D005D8C02D70303"`

The **request_id**, and **session_id** variables are generated by Nginx, and are available in the Nginx log output. Is there a way to insert these values into ModSecurity's log output?

Failing that, is the **unique_id** variable value from ModSecurity available for output into the Nginx error.log or access.log?

**Comment by airween** [comment]
Hi @danielwrayois,

I think that your imagined feature isn't available without any hack.

In my opinion, the **request_id** and **session_id** variables are depends on your transaction. All of them generated by your webserver (nginx). ModSecurity - as I know - doesn't read any environment from the used webserver.

I guess your included log comes from your nginx's error.log. The ModSecurity generated part started here:

```ModSecurity: Access denied...``` (see the [source](https://github.com/SpiderLabs/ModSecurity/blob/d5b93c1013ca9c9a96c75369576b54832e9a2b48/src/rule_message.cc#L73))

end finished with these:

```...[ref "o0,8v1601,25"]```([source](https://github.com/SpiderLabs/ModSecurity/blob/d5b93c1013ca9c9a96c75369576b54832e9a2b48/src/rule_message.cc#L48))

The date at the beginning of line, level, id... (prefix) and the `client: xxx.xxx.xxx, and...so...on` appended by nginx.

May be you can make an own non-disruptive `SecRule` at the begin of your list, which matches the request header, if the name is `Cookie` (if your session travels in the Cookie header), which [captures](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#capture) the value (note, the capture works only with `@rx` operator), and [logs](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#log) it without any other action. Then all of your request will be logged - if you want to do that. Hope this helps.

**Comment by zimmerle** [comment]
Hi @danielwrayois,

Please refer to https://github.com/SpiderLabs/ModSecurity-nginx#modsecurity_transaction_id That should do what you are looking for.
