### ISSUE TITLE
ModSecurity 3.x compilation in Windows x64 (for Apache Httpd)

### ISSUE THREAD

**Issue by Elavarasan83** [SpiderLabs/ModSecurity#2163]
Regarding ModSecurity 3.x compilation in Windows x64 (for Apache Httpd)

We want to migrate ModSecurity 2.9.x to 3.0.3. ModSecurity is used in Apache Httpd(reverse proxy) in our project. Readme says ModSecurity build is not ready for Windows.  

When will the build for Windows made available? Will we get build for Windows for future ModSecurity > v3.0.3 releases? 
Are there any security vulnerabilities, memory leaks that are addressed in v3.0.3 but not in 2.9.x? 

Please clarify.

**Comment by zimmerle** [comment]
Hi @Elavarasan83, 

ModSecurity v3 for Apache is still under testing is not recommended to production yet. Currently we don't have a recipe on how to compile ModSecurity v3 for windows.

**Comment by Elavarasan83** [comment]
Hi @zimmerle 
Thanks for the response.
If we remain in 2.9.x then do we miss any critical security fixes or memory leak fixes?

**Comment by zimmerle** [comment]
It is safe to remain in 2.9 for Apache. This is still under maintenance.
