### ISSUE TITLE
Error reporting when compiling and installing libModSecurity

### ISSUE THREAD

**Issue by jiangsi520** [SpiderLabs/ModSecurity#2164]
When compiling and installing libModSecurity, try the following commands. Make errors. What causes this problem?
![11](https://user-images.githubusercontent.com/30169495/64579516-c2aa6900-d3b5-11e9-9c68-85e3f53116f6.png)

I use V3 version The operating system is centos7。

**Comment by csanders-git** [comment]
Looks like you are missing maxmind development headers.

**Comment by jiangsi520** [comment]
Hello, are you talking about the missing bag? Libmaxminddb-1.3.2.tar.gz, if so, I have installed this package

**Comment by csanders-git** [comment]
The error is indicating that it cannot find that it may be in an abnormal location. try using the locational flag.

**Comment by jiangsi520** [comment]
Hello: I found that the target directory for compilation is the package under / usr / local / lib, but I have this package in Figure 2. So I'm very doubtful now. Are there any other places to configure?
![Y_ _VCVTI0W0{9%}_DL8M9D](https://user-images.githubusercontent.com/30169495/64589043-bbe01e00-d3d6-11e9-9f8e-d28ce4ee7b7f.png)

![MK5N} _}5O_B9_5VP8VHU}J](https://user-images.githubusercontent.com/30169495/64588925-673ca300-d3d6-11e9-8e0b-021e53d4cced.png)

**Comment by airween** [comment]
Try to pass the CFLAGS and CXXFLAGS to configure script:

```
export CFLAGS="-L/usr/local/lib" CXXFLAGS="-L/usr/local/lib" && ./configure --...
...

make
```

**Comment by zimmerle** [comment]
HI @jiangsi520,

Libmaxminddb needs to be in your library path. Check your LD_LIBRARY_PATH to points to your libmaxminddb. Check it here: https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux
