### ISSUE TITLE
Configure Modsecurity in Apache2.4 Windows server

### ISSUE THREAD

**Issue by sbind29893** [SpiderLabs/ModSecurity#2166]
I want to Configure Modsecurity on Apache2.4 windows sever.
I want to prevent SQLinjection & XSS attacks at server level.

**Comment by zimmerle** [comment]
Hi @sbind29893,

Do you have ModSecurity installed already?

**Comment by martinhsv** [comment]
Closing due to length of time open and lack of response from poster.
