### ISSUE TITLE
Parsing of directives with blanks leads to error

### ISSUE THREAD

**Issue by thorstenkampe** [SpiderLabs/ModSecurity#2174]
**Describe the bug**
Multiple directives in ModSecurity's configuration file lead to a generic error when there is more than one blank between key and value.

**To Reproduce**
Put `SecAuditLog /var/log/modsec_audit.log` into ModSecurity's configuration file
```
> nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```
Now add one more space between `SecAuditLog` and the value:
```
> nginx -t
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsecurity.conf. Line: 23. Column: 45. Invalid input:  SecAuditLog  /var/log/nginx/modsec_audit.log in /etc/nginx/nginx.conf:37
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Expected behavior**

I expect no error because putting multiple spaces between key and value works for most directives.

**Server (please complete the following information):**
 - ModSecurity version (and connector): libmodsecurity3 3.0.3-1 with nginx-connector v1.0.0
 - WebServer: nginx-1.16.1
 - OS (and distro): Ubuntu 19.10

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? No.
 - What is the version number? OWASP Core Rule Set not installed

**Additional context**
The following directives also generate an error with multiple spaces:
```
SecRequestBodyLimit
SecRequestBodyNoFilesLimit
```

The following directives do NOT generate an error with multiple spaces
```
SecRuleEngine
SecRequestBodyAccess
SecRequestBodyLimitAction
SecResponseBodyAccess
SecAuditEngine
SecAuditLogRelevantStatus
SecAuditLogParts
SecAuditLogType
```

**Comment by zimmerle** [comment]
This was fixed at: dc78c0e180d09aa1b2f0ffad1a8d6967e69f984f
