### ISSUE TITLE
Docker build for httpd-alpine

### ISSUE THREAD

**Issue by hcomnetworkers** [SpiderLabs/ModSecurity#2176]
I'm a bit lost on creating a httpd-alpine container with modsecurity and all the internet is only full of nginx variants.

I have this Dockerfile:
```Dockerfile
FROM httpd:2.4.41-alpine

ENV MODSECURITY_INC=/opt/modsecurity/headers/
ENV MODSECURITY_LIB=/opt/modsecurity/src/.libs/

RUN apk add --no-cache --virtual .build-modsec \
  automake \
  autoconf \
  build-base \
  libtool \
  libxml2-dev \
  linux-headers \
  git \
  pcre-dev \
  && cd /opt \
  && git clone --depth 1 --branch v3.0.3 git://github.com/SpiderLabs/ModSecurity.git modsecurity \
  && cd modsecurity \
  && git submodule init \
  && git submodule update \
  && ./build.sh \
  && ./configure \
  && make \
  && make install \
  && cd /opt \
  && git clone --depth 1 --branch v0.0.9-beta1 git://github.com/SpiderLabs/ModSecurity-apache.git modsecurity-apache \
  && cd modsecurity-apache \
  && ./autogen.sh \
  && ./configure \
  && make \
  && make install \
  && cd /opt \
  && cp /opt/modsecurity-apache/src/.libs/mod_security3.so /usr/local/apache2/modules/ \
  && apk del .build-modsec
```

It builds successfully. And with a `LoadModule security3_module modules/mod_security3.so` the apache configtest says the syntax is OK and when I start apache it at least looks happy:

> bash-5.0# apachectl -D FOREGROUND
[2019-10-02 07:49:06.132048] [notice] [pid 12] src/mod_security3.c(254): [client ModSecurity: ModSecurity-Apache v0.1.1-beta configured.
[2019-10-02 07:49:06.135229] [notice] [pid 12] event.c(3085): [client AH00489: Apache/2.4.41 (Unix) OpenSSL/1.1.1c configured -- resuming normal operations
[2019-10-02 07:49:06.135261] [notice] [pid 12] log.c(1562): [client AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'

The thing is: The image is 946 MB in size, that is 819 MB more than the original `httpd:2.4.41-alpine` I started with. When installing libapache2-mod-security2 in the Ubuntu-based httpd image via `apt-get` it only adds 78 MB to the image and although that is version 2 and not 3, I doubt 819 MB is all needed. I have no idea what I can delete now. I'm not familiar enough with building things with `make`. It looks like the `src`-folder is still required after the `make`, which is already weird for me because it's "src", it's not "build".

Any help would be appreciated! You can also use this Dockerfile as an example for an apache-build in the docs - there seem to be only nginx examples, yet.

**Comment by zimmerle** [comment]
Hi @hcomnetworkers 

There are two versions families of ModSecurity that are currently being supported: 2.x and 3.x. It is recommended for Apache users to stay in 2.x until we manage to have a stable release for the Apache connector. For Nginx, the recommendation is to use the 3.x family.

It seems like you are compiling the libModSecurity, rather than install a binary package. Once you have installed the library (make install) it is safe to remove the entire source code directory.
