### ISSUE TITLE
How to use modsecparser and mlogc?

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#2182]
Recently I found out that the modsecparser can writes audit logs into a Postgres database,the mlogc can send audit logs to a central repository,but I can't find how to install them,I just found some configuration messages on https://github.com/Ixolit/modsecparser or https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29

**Comment by zimmerle** [comment]
Hi @prince-java,

The modsecparser is an independent project maintained by @terrorobe.

The mlogc is distributed altogether with ModSecurity version 2. 

Whait is the verision of your ModSecurity?

**Comment by prince-java** [comment]
> Hi @prince-java,
> 
> The modsecparser is an independent project maintained by @terrorobe.
> 
> The mlogc is distributed altogether with ModSecurity version 2.
> 
> Whait is the verision of your ModSecurity?

The verision of my ModSecurity is 2.9.3.
I find out there is a folder named "mlogc" in the tar file,but I don't know how to install、use or configuration.

**Comment by prince-java** [comment]
@zimmerle 
Thank you for response!
The verision of my ModSecurity is 2.9.3.
I find out there is a folder named "mlogc" in the tar file,but I don't know how to install、use or configuration.

**Comment by zimmerle** [comment]
Mlogc will be built upon the compilation of ModSec. Proceed with the regular compilation and the binary will be generated in that folder.

**Comment by prince-java** [comment]
My ModSecurity has been installed.After that,there is a file named 'mlogc' in /usr/local/modsecurity/bin.
I just don't how to use it, add mlogc-default.conf in /usr/local/modsecurity-2.9.3/mlogc into httpd.conf?

**Comment by prince-java** [comment]
SecAuditLog "|/usr/local/modsecurity/bin/mlogc /usr/local/modsecurity-2.9.3/mlogc/mlogc-default.conf",like this?

**Comment by zimmerle** [comment]
There are some information here -
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secauditlog
