### ISSUE TITLE
.eml files blocked

### ISSUE THREAD

**Issue by Nithinbs18** [SpiderLabs/ModSecurity#2183]
Hello team,

I have ModSecurity setup with Nginx and all the incoming .eml files to the container are being blocked by ModSec can you please let me know a workaround of the rule responsible for blocking this.
Thank you very much in advance.
BR,
Nithin

**Comment by airween** [comment]
Did you checked your debug and audit logs? What did you see there?

**Comment by zimmerle** [comment]
Hi @Nithinbs18,

It is very likely that the issue that you are facing is not related to ModSecurity itself, but to the rules that you have loaded. With further details on the reason why it got blocked, we can address the issue better.

Please re-open if needed.
