### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by sergiospa** [SpiderLabs/ModSecurity#2185]
Hello,
I just wanted to check if there's any plan to make it easy to get JSON logs from ModSecurity. I've googled this and it seems like this is not an out of the box feature. I mean, there's no ModSecurity package yet you can just download and install to get JSON logs.
The only way, for now, seems to be compiling your own package.

This would be an awesome feature.
Best regards,
Sergio.

**Comment by zimmerle** [comment]
Hi @sergiospa,

ModSecurity is natively capable to generate the Audit logs into a JSON format.  However, it depends to be compiled with such support. What is the version of ModSecurity that you have running? is it a distro package or did you have it compiled by your self?

**Comment by sergiospa** [comment]
Hi @zimmerle ,
Thanks for your quick response.
By following this tutorial: https://malware.expert/tutorial/install-modsecurity-with-apache-on-ubuntu-16-04-lts/ , I installed ModSecurity for Apache 2.9.3 in Ubuntu 19.04. However I'm not sure if the ModSecurity version is the same, I didn't know how to check it. Maybe these logs help:
```
root@vagrant-ubuntu-19:/var/log/apache2# cat /var/log/apache2/error.log | grep -i modsecurity
[Thu Oct 17 13:24:42.531357 2019] [:notice] [pid 26987:tid 140117718084544] ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/) configured.
[Thu Oct 17 13:24:42.531380 2019] [:notice] [pid 26987:tid 140117718084544] ModSecurity: APR compiled version="1.6.5"; loaded version="1.6.5"
[Thu Oct 17 13:24:42.531382 2019] [:notice] [pid 26987:tid 140117718084544] ModSecurity: PCRE compiled version="8.39 "; loaded version="8.39 2016-06-14"
[Thu Oct 17 13:24:42.531384 2019] [:notice] [pid 26987:tid 140117718084544] ModSecurity: LUA compiled version="Lua 5.1"
[Thu Oct 17 13:24:42.531385 2019] [:notice] [pid 26987:tid 140117718084544] ModSecurity: YAJL compiled version="2.1.0"
[Thu Oct 17 13:24:42.531387 2019] [:notice] [pid 26987:tid 140117718084544] ModSecurity: LIBXML compiled version="2.9.4"
[Thu Oct 17 13:24:42.531388 2019] [:notice] [pid 26987:tid 140117718084544] ModSecurity: Status engine is currently disabled, enable it by set SecStatusEngine to On.
[Thu Oct 17 13:24:48.737386 2019] [:notice] [pid 27116:tid 140715415907264] ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/) configured.
[Thu Oct 17 13:24:48.737416 2019] [:notice] [pid 27116:tid 140715415907264] ModSecurity: APR compiled version="1.6.5"; loaded version="1.6.5"
[Thu Oct 17 13:24:48.737419 2019] [:notice] [pid 27116:tid 140715415907264] ModSecurity: PCRE compiled version="8.39 "; loaded version="8.39 2016-06-14"
[Thu Oct 17 13:24:48.737421 2019] [:notice] [pid 27116:tid 140715415907264] ModSecurity: LUA compiled version="Lua 5.1"
[Thu Oct 17 13:24:48.737422 2019] [:notice] [pid 27116:tid 140715415907264] ModSecurity: YAJL compiled version="2.1.0"
[Thu Oct 17 13:24:48.737424 2019] [:notice] [pid 27116:tid 140715415907264] ModSecurity: LIBXML compiled version="2.9.4"
[Thu Oct 17 13:24:48.737425 2019] [:notice] [pid 27116:tid 140715415907264] ModSecurity: Status engine is currently disabled, enable it by set SecStatusEngine to On.
[Thu Oct 17 14:18:10.741088 2019] [:notice] [pid 27497:tid 140242167065536] ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/) configured.
[Thu Oct 17 14:18:10.741110 2019] [:notice] [pid 27497:tid 140242167065536] ModSecurity: APR compiled version="1.6.5"; loaded version="1.6.5"
[Thu Oct 17 14:18:10.741113 2019] [:notice] [pid 27497:tid 140242167065536] ModSecurity: PCRE compiled version="8.39 "; loaded version="8.39 2016-06-14"
[Thu Oct 17 14:18:10.741114 2019] [:notice] [pid 27497:tid 140242167065536] ModSecurity: LUA compiled version="Lua 5.1"
[Thu Oct 17 14:18:10.741116 2019] [:notice] [pid 27497:tid 140242167065536] ModSecurity: YAJL compiled version="2.1.0"
[Thu Oct 17 14:18:10.741117 2019] [:notice] [pid 27497:tid 140242167065536] ModSecurity: LIBXML compiled version="2.9.4"
[Thu Oct 17 14:18:10.741133 2019] [:notice] [pid 27497:tid 140242167065536] ModSecurity: StatusEngine call: "2.9.3,Apache/2.4.38 (Ubuntu),1.6.5/1.6.5,8.39/8.39 2016-06-14,Lua 5.1,2.9.4,3b690cc5c1c48c60b331194a7fbf3282e82ffe41"

```

I was not able to get JSON logs with that installation. Then, I followed the steps shown here: https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x. I followed the steps for Ubuntu 15.04 even though I'm running 19.04, and I wasn't able to get the JSON logs still. I must be missing something I guess...

**Comment by molu8bits** [comment]
Hi @sergiospa 

Errors generated into Apache "error.log" don't support JSON logging as they are probably generated directly by Apache - not by the module.

I think you should check modsec_audit.log - that file supports JSON logging and you'll find there much more information.
This is just configuration option and supported since long time ago. All modsecurity2 >= 2.9 support that. Works with modsecurity3 as well. There are some drawbacks with the current structure but generally each log is reported as a valid JSON entry.

All you need is to configure following options in your mod_security.conf (example comes from Ubuntu)

> SecAuditLogType               Serial
> SecAuditLog                   /var/log/apache2/modsec_audit.log
> SecAuditLogFormat       JSON

Then restart and all new log entries will be added as JSON to  /var/log/apache2/modsec_audit.log

**Comment by prince-java** [comment]
Hi @zimmerle 
I have a similar question,when i add "SecAuditLogFormat JSON" into modsecurity.conf,it appears some error:
`[root@VM_0_15_centos ~]# /usr/local/apache/bin/apachectl -t
AH00526: Syntax error on line 199 of /usr/local/apache/conf/modsecurity/modsecurity.conf:
Invalid command 'SecAuditLogFormat', perhaps misspelled or defined by a module not included in the server configuration`

The version of ModSecurity I installed is 2.9.3,the version of Apache is 2.4.41.
Best regards.

**Comment by prince-java** [comment]
Hi @zimmerle 
I have a similar question,when i add "SecAuditLogFormat JSON" into modsecurity.conf,it appears some error:
`[root@VM_0_15_centos ~]# /usr/local/apache/bin/apachectl -t

AH00526: Syntax error on line 199 of /usr/local/apache/conf/modsecurity/modsecurity.conf:
Invalid command 'SecAuditLogFormat', perhaps misspelled or defined by a module not included in the server configuration`

The version of ModSecurity I installed is 2.9.3,the version of Apache is 2.4.41.
Best regards.
