### ISSUE TITLE
JSON request body contains =calc|a!z  value mod security doesn't capture

### ISSUE THREAD

**Issue by jofisiva** [SpiderLabs/ModSecurity#2187]
**Describe the bug**
The JSON request body contains calculator function 
{
  "name": "=calc|a!z"
}

<IfModule security2_module>
  Include modsecurity-crs/crs-config.conf
   Include modsecurity-crs/rules/REQUEST-901-INITIALIZATION.conf

  Include modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  Include modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
</IfModule>

SecRule REQUEST_HEADERS:Content-Type "application/json" \
     "id:'200001',phase:1,t:none,t:lowercase,log,nolog,ctl:requestBodyProcessor=JSON"

SecRule REQBODY_ERROR "!@eq 0" \
"id:'200002', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"

SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
"id:'200003',phase:2,t:none,log,deny,status:400, \
msg:'Multipart request body failed strict validation: \
PE %{REQBODY_PROCESSOR_ERROR}, \
BQ %{MULTIPART_BOUNDARY_QUOTED}, \
BW %{MULTIPART_BOUNDARY_WHITESPACE}, \
DB %{MULTIPART_DATA_BEFORE}, \
DA %{MULTIPART_DATA_AFTER}, \
HF %{MULTIPART_HEADER_FOLDING}, \
LF %{MULTIPART_LF_LINE}, \
SM %{MULTIPART_MISSING_SEMICOLON}, \
IQ %{MULTIPART_INVALID_QUOTING}, \
IP %{MULTIPART_INVALID_PART}, \
IH %{MULTIPART_INVALID_HEADER_FOLDING}, \
FL %{MULTIPART_FILE_LIMIT_EXCEEDED}'"

modsecurity doesn't throw any error 

 httpd -v
Server version: Apache/2.2.15 (Unix)
Server built:   Jul 12 2017 13:32:34

**Comment by zimmerle** [comment]
Hi @jofisiva,

Thank you for the report, however, that is more about a rule issue than an issue within ModSecurity. You may want to open an issue at CRS - https://github.com/SpiderLabs/owasp-modsecurity-crs/
