### ISSUE TITLE
Releases, new versions?

### ISSUE THREAD

**Issue by scaarup** [SpiderLabs/ModSecurity#2188]
Hi.

This is not a bug report but I don't know where else to reach out to you. So the thing is, that I am building an rpm with libmodsecurity when a new version is out. 
Looking at releases, 3.0.3 was released almost a year ago. There have been many commits to the v3/master though. Now I discovered that CHANGES has been updated in v3/master, but "v3.0.4 - YYYY-MMM-DD (to be released)" maybe indicates that a "real" release is coming up? Are we to expect a minor release once per year? Or should I just look for commits to v3/master and consider that a new version? If yes, where can I see a changelog?

Thanks.

**Comment by zimmerle** [comment]
Hi @scaarup,

We are aiming to have a release before the end of the year. It is very likely to be v3.1.0 instead of v3.0.4. We are short on resources that is why the release is taking so long.

You can refer to the CHANGELOG file the list all changes.

**Comment by scaarup** [comment]
Thanks @zimmerle ,
Do you recommend that I, throughout the year, build rpms from commits to v3/master and consider them as production ready? Or should I only go for what is actually released as releases?

**Comment by zimmerle** [comment]
The master should be safe to use. There are few issues listed here on GitHub, but I don't see it as impeditive.
