### ISSUE TITLE
"MULTIPART_STRICT_ERROR"

### ISSUE THREAD

**Issue by Raviyellaram** [SpiderLabs/ModSecurity#2194]
Hi ,

We have facing front end "Internal Server Error" 500 for one of my application url.

Below mentioned observations has been captured in modsecurity logs.

Message: Access denied with code 44 (phase 2). Match of "eq 0" against "MULTIPART_STRICT_ERROR" required. [file "/xxxx/xxxx/xxxx/modsecurity.conf"] [line "82"] [id "3"] [msg "Multipart request body failed strict validation: PE 0, BQ 0, BW 0, **DB 1**, DA 0, HF 0, LF 0, SM , IQ 0, IH 0, IH 0"]
Apache-Error: [file "http_request.c"] [line 107] [level 3] AH01579: Invalid response status %i
Action: Intercepted (phase 2)

It's failing with Data Before Filed . Need to understand the field variable and resolution to fix it.

**Comment by martinhsv** [comment]
Hi @Raviyellaram 
I'm not entirely clear on what you are asking.  You have an HTTP request that is triggering MULTIPART_STRICT_ERROR because there is data in the request body that is before the first boundary.

If you are confident that nonstandard multipart requests are harmless for certain requests, and you just want to remove those detections, then you could turn off the rule for that particular request type.  One way to do this:  if the MULTIPART_STRICT_ERROR rule is 200003, you can turn it off in a SecRule with ctl:ruleRemoveById=200003

**Comment by Raviyellaram** [comment]
>  I'm not entirely clear on what you are asking. You have an HTTP request that is triggering MULTIPART_STRICT_ERROR because there is data in the request body that is before the first boundary.

I just wanted to understand MULTIPART STRICT ERROR VALUES in detailed .

Please find the below configuration values in modsecurity.conf

SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
"id:'3',phase:2,t:none,log,deny,status:44,msg:'Multipart request body \
failed strict validation: \
PE %{REQBODY_PROCESSOR_ERROR}, \
BQ %{MULTIPART_BOUNDARY_QUOTED}, \
BW %{MULTIPART_BOUNDARY_WHITESPACE}, \
DB %{MULTIPART_DATA_BEFORE}, \
DA %{MULTIPART_DATA_AFTER}, \
HF %{MULTIPART_HEADER_FOLDING}, \
LF %{MULTIPART_LF_LINE}, \
SM %{MULTIPART_SEMICOLON_MISSING}, \
IQ %{MULTIPART_INVALID_QUOTING}, \
IH %{MULTIPART_INVALID_HEADER_FOLDING}, \
IH %{MULTIPART_FILE_LIMIT_EXCEEDED}'"

Suggest any sites for documentation

**Comment by martinhsv** [comment]
I won't go through them all, but I'll provide a few notes:

REQBODY_PROCESSOR_ERROR - this captures several major parsing errors. One example is if the Content-Type header says 'multipart/form-data' but no boundary is specified

MULTIPART_DATA_BEFORE - there is data in the body before the first boundary

MULTIPART_DATA_AFTER - there is data in the body after the final boundary

MULTIPART_INVALID_QUOTING - for example if there is a single quote within a "name":

```
-----------------------------6214859758024792871666769140
Content-Disposition: form-data; name="use'r_ID"

1
-----------------------------6214859758024792871666769140
```

MULTIPART_INVALID_PART - multiple conditions can generate this.  One example is if there is nothing at all between two boundaries:

```
-----------------------------6214859758024792871666769140
-----------------------------6214859758024792871666769140
```

MULTIPART_INVALID_HEADER_FOLDING - this has to do with continuing a header across multiple lines.  E.g.

```
-----------------------------6214859758024792871666769140
Content-Disposition: form-data;
 name="user_ID"

1
-----------------------------6214859758024792871666769140
```

I hope that helps.
