### ISSUE TITLE
expirevar does not take effect

### ISSUE THREAD

**Issue by grdey1** [SpiderLabs/ModSecurity#2200]
I am using the v3/master code, and I want to test the dos attack rule(REQUEST-912-DOS-PROTECTION.conf).
I found that the dos rule matched OK, but the expirevar action seemed has no effect.
After the ip entered the deny state, it would always in that state.
I use the InMemoryPerProcess class backend(not the lmdb class).

I have checked some issues related to this like #1803, #1778, #1754,
but got only more confused.
I have also checked the whole source code, found nothing about the expirevar related logic(but I can found the logic in the 2.x series).

so anyone can give some me advice? do the v3/master code implemented the expirevar action?

Thanks

**Comment by zimmerle** [comment]
Closing in favor of #1803.
