### ISSUE TITLE
Disabled rules in dashboard not updated

### ISSUE THREAD

**Issue by miguel-sharpmobile** [SpiderLabs/ModSecurity#2207]
**Describe the bug**

Disabled rules on the dashboard through https://dashboard.modsecurity.org/ does not propagate to the downloaded rules file.

Steps to reproduce:

**To Reproduce**

A **curl** command line that mimics the original request and reproduces the problem. Or a ModSecurity v3 test case.

1. Disable all rules through the dashboard
2. Configure ModSecurity with SecRemoteRules [key] https://dashboard.modsecurity.org/rules/download/plain

**Expected behavior**

Rules not to be included when disabled through the dashboard

**Server (please complete the following information):**
 - ModSecurity v3.0.1 with nginx-connector v1.0.0
 - WebServer: nginx
 - OS (and distro): Linux Ubuntu

**Rule Set (please complete the following information):**
Commercial rules
**Additional context**

**Comment by zimmerle** [comment]
Hi @miguel-sharpmobile,

Thank you for the report, however, that is no the best channel for this kind of issue. I would like to invite you to go over Trustwave support. There they will be able to help you better.
