### ISSUE TITLE
'ON' check on URLs in REQUEST_HEADERS:Referer: for 941100 

### ISSUE THREAD

**Issue by theBlueclouds** [SpiderLabs/ModSecurity#2209]
We found that 941100 rule is acting in the referrer for urls. But the regex provided, did not match the url. We suspect the regex provided in the documentation and the one that is actually triggered is different. We would need the correct regex to match the request. 

The regex mentioned in the [941100 rule](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf#L31) is : "(?i)([\s\"'`;\/0-9\=\x0B\x09\x0C\x3B\x2C\x28\x3B]+on[a-zA-Z]+[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=)".

This is our hit/match :-
_details_file_s : rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf   
details_data_s : Matched Data: 
https://www.XYZ.com/ex-js/frobs/all-categories/all-cities/all-states/?s=&p=2&t=&loc=Toronto, **ON**&lat=&lng=&pid=&rid=EC676EE4-2867-47EC-ADA4-04C32E75E61A&range=50 
found within REQUEST_HEADERS:Referer: 
https://www.XYZ.com/ex-js/frobs/all-categories/all-cities/all-states/?s=&p=2&t=&loc=Toronto, **ON**&lat=&lng=&pid=&rid=EC676EE4-2867-47EC-ADA4-04C32E75E61A&range=50_   

We tried to replicate this by going to https://regex101.com/ and provided regex as : (?i)([\s\"'`;\/0-9\=\x0B\x09\x0C\x3B\x2C\x28\x3B]+on[a-zA-Z]+[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=) 

And we tried to match this, but it is not matching. This proves there is some issue with Regex.
https://www.XYZ.com/ex-js/frobs/all-categories/all-cities/all-states/?s=&p=2&t=&loc=Toronto, **ON**&lat=&lng=&pid=&rid=EC676EE4-2867-47EC-ADA4-04C32E75E61A&range=50

Microsoft is using this in their WAF(Web application Firewall). And they could not find the reason to this either. They asked us to contact you. 

The issue is on the 'ON' Check. We know this because the exact same url without ON is not blocked(in the request as well as referrer). And it is caused by some regex (if not tell us what is causing it). We cannot find the right regex. We had to remove the 941100 rule and it is okay now. But we would need to know what exactly caused the block.

**Comment by zimmerle** [comment]
Hi @theBlueclouds,

The best project to answer that question is the CRS project -
 https://github.com/SpiderLabs/owasp-modsecurity-crs

Here we take care of the ModSecurity core. The CRS project is the one that provides the rule that you are concerned about.
