### ISSUE TITLE
IP collection is behaving like more of a primitive variable than HashMap.

### ISSUE THREAD

**Issue by nasirbas1** [SpiderLabs/ModSecurity#2211]
Hi Team ,
We are facing a very trivial issue with modsecurity in conjunction with Nginx.
We have been constantly trying to get hands on the working of the persistant
collection storages, but they are behaving vaguely for each and every request.
If IP collection is indeed a hashmap and it uniquely maps each IP address to a
certain characteristic that we want, then its not working as described. 
Even if we put a simple counter on the IP collection and update it on subsequent
requests, it behaves more of a primitive variable than a collection. Each new 
request (even from a differnet IP) is able to update the same counter in IP collection.
Each new request should have added a unique entry in IP collection, with a private 
counter variable.
♦️ We even tried the global persistant collection but had no success. 
♦️ Also there was this issue with SecDataDir directive to set path for the 
   persistant storage. Even after providing all the permissions, it was not
   able to create any .pag file for the same.

Please find below the rule set which initialises IP collection and sets the counter, 
and on every new request updates the counter.

Can anyone please look into it asap .

OS Version : CentOS Linux 7
Nginx Version : 1.16.1
Modsecurity version : 3.03

**_True-Client-IP is provided by AKAMAI as real ip address of the user_**

#SecRule REQUEST_HEADERS:True-Client-IP "^\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b" "id:150001,phase:1,t:none,pass,log,capture,setvar:tx.true_client_ip=%{tx.0}"

SecRule &TX:TRUE_CLIENT_IP "!@eq 0" "id:'900021',chain,phase:1,t:none,initcol:ip=%{tx.true_client_ip},log,pass"

**_Reset the counter to start at 0_**

SecRule REQUEST_URI "@contains /hotels-near-me" "id:'900022',phase:2,t:none,setvar:ip.auth_attempt=+1,log,chain"

**_If collection is working request should be droped_**

SecRule IP:AUTH_ATTEMPT "@gt 3" "id:'900024',phase:2,t:none,log,msg:'%{MATCHED_VAR_NAME}', logdata:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',drop"

**Comment by prashan9775** [comment]
I am also facing the same issue

**Comment by nasirbas1** [comment]
**_To anyone in future_** : There was this thing that we figured out for **DDoS protection** , we were initialising collections in SecRule , whereas this works only if done in SecAction .
