### ISSUE TITLE
Escaped Quotes causing nginx emerg errors 

### ISSUE THREAD

**Issue by ledzepp4eva** [SpiderLabs/ModSecurity#2213]
**Describe the bug**

When the following SecRule is created it generates an Nginx configuration error

`SecRule MATCHED_VARS "@contains \"TX\"" "id:1, phase:1, t:none, nolog, pass, ctl:ruleEngine=Off"`

**Logs and dumps**

2019/12/05 14:57:11 [emerg] 1852#1852: "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/example.com.conf. Line: 36. Column: 97. Invalid input:  id:8, phase:1, t:n
one, nolog, pass, ctl:ruleEngine=Off" in /etc/nginx/conf.d/example.com.conf:77

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

Add the rule `SecRule MATCHED_VARS "@contains \"TX\"" "id:1, phase:1, t:none, nolog, pass, ctl:ruleEngine=Off"` to an nginx configuration using ModSecurity 3. And then run an nginx configuration test `nginx -t`

**Expected behavior**

I'd expect this to be a valid rule as we are escaping the quotes in the operator. I have tested this rule using Apache 2.4 and ModSecurity 2.9 and it passes without issues.

**Server (please complete the following information):**
 - ModSecurity 3.0.3
 - WebServer: nginx 1.16.1
 - OS (and distro): Centos 7

**Comment by martinhsv** [comment]
Hi @ledzepp4eva,

Thanks for the report.

If you're looking for a workaround, something like "@rx \x22TX\x22" should accomplish the same thing.

**Comment by ledzepp4eva** [comment]
Thanks, I have tested this and it no longer fails the nginx configuration change and it does whitelist the quotes
