### ISSUE TITLE
error: /usr/bin/ld: cannot find -llibmaxminddb 

### ISSUE THREAD

**Issue by prakash9999in** [SpiderLabs/ModSecurity#2215]
While following the wiki 
https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x

I tried to install Modsecurity on Centos 7 Minimal
in the first step while libModSecurity
**I am getting the error as below when I am trying the make command:**

```
/usr/bin/ld: cannot find -llibmaxminddb
collect2: error: ld returned 1 exit status
make[3]: *** [libmodsecurity.la] Error 1
make[3]: Leaving directory `/usr/local/src/ModSecurity/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/local/src/ModSecurity/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/ModSecurity/src'
make: *** [all-recursive] Error 1
```

**The output of the configuration command is as below:**
 
```
ModSecurity - v3.0.3-114-g6624a18 for Linux
 
 Mandatory dependencies
   + libInjection                                  ....v3.9.2-30-gbf234eb
   + SecLang tests                                 ....c8cf2c5
 
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (MaxMind) v
         /usr/local/lib//libmaxminddb.so, /usr/local/include, -DWITH_MAXMIND -I/usr/local/include
      * (GeoIP) v1.5.0
         -lGeoIP  , -I/usr/include/  
   + LibCURL                                       ....found v7.29.0 
      -lcurl  ,  -DWITH_CURL
   + YAJL                                          ....found v2.0.4
      -lyajl  , -DWITH_YAJL  
   + LMDB                                          ....not found
   + LibXML2                                       ....found v2.9.1
      -lxml2 -lz -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....not found
 
 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled
```
 
### Wanted to add here is that I have installed libmaxminddb-1.4.2 from source so that it can be used in Modsecurity.

Am I missing anything here. 

Thanks in advance.

**Comment by martinhsv** [comment]
Hi @prakash9999in ,

Did you think you needed to install libmaxminddb from source, or was that a choice for some reason?  I just tried a fresh install on CentOS7-Minimal and only installed packages via yum, and my make completed successfully.

**Comment by prakash9999in** [comment]
> Hi @prakash9999in ,
> 
> Did you think you needed to install libmaxminddb from source, or was that a choice for some reason? I just tried a fresh install on CentOS7-Minimal and only installed packages via yum, and my make completed successfully.

Hi Martinhsv,

Thanks for your prompt response.
I installed from source to use the latest version of libmaxminddb which I am not getting when I am trying to install from yum.

Is there any known version compatibility issues ?

Thanks & Regards

**Comment by zimmerle** [comment]
Hi @prakash9999in,

Make sure that /usr/local/lib// is your library path. Otherwise, the compilation scripts will find it, but it will no be able to use in runtime.
