### ISSUE TITLE
Modsec rule causes nginx cu spin up a lot of worker processes

### ISSUE THREAD

**Issue by davidbalazs** [SpiderLabs/ModSecurity#2218]
**Describe the bug**

Hi there, we run Nginx in a Docker container as a sidecar in a pod in a Kubernetes cluster.
We have the ModSec module (version 3.0.3) enabled for Nginx.
In our Nginx configuration, we set the number of worker processes to be 16 (we have 16 cpu cores on our machines):
```
    worker_processes 16;
    events {
      worker_connections 1024;
    }
```

- With modsec **disabled**, it all works fine, we can see in the access logs that requests are processed fine, there are 16 worker processes running and the memory usage is not higher than 200-300MB.

- However, when the modsec is **enabled**, the initial number of worker processes in nginx is 16, but over a period of 12 hours, the number of worker processes increases whenever a given modsec rule is matched by an HTTP request (in our case it is ruleID: 920350).

The number of worker processes increases until the memory limit (2GB, set at a kubernetes level) is met (at that point, nginx started up to 500 worker processes!)

When it hits the memory limit, nginx stops handling requests (according to the access log, we cannot see any requests being handled anymore). Furthermore, the issue is causing the entire machine where the nginx container is running to crash.

**My question is**: is there something at the modsec level that causes nginx to spin up a lot more worker processes (around 500) than configured (16) when the modsec rule 920350 matches http requests? Could it be a resource leak?

**Logs and dumps**

Output of:
 1. NGINX access log example when a given HTTP request is matched to modsec rule 920350 
 ```
"GET /healthcheck HTTP/1.1" 200 0 "-" "ELB-HealthChecker/2.0" "-"
{"transaction":{"client_ip":"<IP_HIDDEN>","time_stamp":"","server_id":"<replaced>","client_port":<replaced>,"host_ip":"<replaced>","host_port":<replaced>,"unique_id":"<replaced>","request":{"method":"GET","http_version":1.1,"uri":"/healthcheck","headers":{"Host":"10.0.0.11:12345","Connection":"close","User-Agent":"ELB-HealthChecker/2.0","Accept-Encoding":"gzip, compressed"}},"response":{"http_code":200},"producer":{"modsecurity":"ModSecurity v3.0.3 (Linux)","connector":"ModSecurity-nginx v0.1.1-beta","secrules_engine":"DetectionOnly","components":["OWASP_CRS/3.0.2\""]},"messages":[{"message":"Host header is a numeric IP address","details":{"match":"Matched \"Operator `Rx' with parameter `^[\\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `1<replaced_numberic_ip_and_port>' )","reference":"o0,15v32,15","ruleId":"920350","file":"/usr/local/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf","lineNumber":"777","data":"<replaced>","severity":"4","ver":"OWASP_CRS/3.0.0","rev":"2","tags":["application-multi","language-multi","platform-multi","attack-protocol","OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST","WASCTC/WASC-21","OWASP_TOP_10/A7","PCI/6.5.10"],"maturity":"9","accuracy":"9"}}]}}
```

**To Reproduce**

Start nginx with modsec enabled and ensure that ruleID: 920350 is present.
Configure nginx to use maximum 16 worker processes (or a similar, fixed number)
Start multiple HTTP requests that match that given rule (ID: 920350) 

**Expected behavior**

Nginx will not spin up more than 16 worker processes in total (16 is the number of worker processes configured in nginx).

**Server (please complete the following information):**
 - ModSecurity version: 3.0.3 connector: ModSecurity-nginx v1.0.0
 - WebServer: NGINX (nginx version: nginx/1.15.4 built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) built with OpenSSL)
 - OS (and distro): CentOS 7 

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? rule set OWASP CRS 3.0.2
 - What is the version number? 3.0.2

**Additional context**

Note: I have raised a bug in owasp-modsecurity-crs as well: https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1649

**Comment by airween** [comment]
_Server (please complete the following information):
    ModSecurity version: 3.0.3 connector: ModSecurity-nginx **v0.1.1-beta**_

Sorry for the question, but are you sure you have this version?

**Comment by davidbalazs** [comment]
the connector version we use is actually v1.0.0, thanks for the heads up! I've updated the issue description.

Interestingly enough, in the nginx access logs it appears as `"connector":"ModSecurity-nginx v0.1.1-beta"`

**Comment by airween** [comment]
Could you try with the code from current master?

**Comment by martinhsv** [comment]
Hi @davidbalazs ,

I have tried a few things to try to recreate what you've seen but have not been successful so far (although my test environment is not particularly close to your deployment).

Clarification question:  Do I understand correctly that if you remove rule 920350, you don't see the problem any more?

**Comment by davidbalazs** [comment]
hi @martinhsv

From the behavior that I have seen so far, the number of processes increases over a period of 12 hours to a big number, it doesn't increase immediately.

To work around the issue, I whitelist the endpoint that is being hit via numeric ip (that used to trigger the rule 920350):

```
    SecRule REQUEST_URI "@contains /healthcheck" \
    "id:1005,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleEngine=Off"
```

If I whitelist this endpoint, then all the healthcheck requests that are coming via direct IP won't be intercepted anymore by modsec and the memory remains constant + there are exactly 16 worker processes running in nginx (which is the desired number)

**Comment by martinhsv** [comment]
Hi @davidbalazs ,

Thanks, that clarifies your workaround.

What I would be interested in doing, however, is narrowing down whether processing of the rule itself is what is triggering the bad result, or if the content of the request is causing the bad result irrespective of whether that particular rule is active.

If you are willing to try an experiment or two, my first suggestion would be to alter the rule you are currently using to whitelist.  Instead of using 'ctl:ruleEngine=Off', try 'ctl:ruleRemoveById=920350'.  That would result in those requests still otherwise being processed by ModSecurity, but avoiding that one particular rule (and any processing due to that detection including logging).  If the problem does not occur when using ctl:ruleRemoveById, then that is a safer (from a security standpoint) customization than turning off the engine entirely for those requests.

Also, could you please clarify/confirm the version of ModSecurity that you're using.  You mentioned v3.0.3.  Is that from a distro package?  Or is it built directly from the v3.0.3-tagged commit in github?  Or is it possibly from a more recent github 'v3/master' commit that still happens to be labelled as 3.0.3?

**Comment by davidbalazs** [comment]
Thanks @martinhsv 

I will try now and let it run over the weekend to see that happens.

The ModSecurity version is v3.0.3 and it is built from the v3.0.3 tagged commit in github

**Comment by martinhsv** [comment]
Hi @davidbalazs ,

You could also consider proceeding with the suggestion from @airween , and use the code from HEAD of v3/master.

There have been quite a few bug fixes implemented over the past year+, at least one of which might be relevant ( https://github.com/SpiderLabs/ModSecurity/issues/1927 ). The symptoms reported in that bug aren't exactly the same as what you're seeing, but there are a few points of commonality that make we wonder if that fix might also have resolved your issue.

**Comment by davidbalazs** [comment]
hi @martinhsv 

I did the change to whitelist the endpoint for that specific rule as suggested (but still using ModSecurity v3.0.3):
```
  SecRule REQUEST_URI "@contains /healthcheck" \
    "id:1005,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=920350"
```
and I can confirm that Nginx with ModSecurity worked properly over this period. The number of worker processes remained constant to 16 (which is the configured number) and the memory remained constant as well. So the issue seems to be around rule 920350.

I will try the latest master version as well and I will let you know.

Thanks!

**Comment by martinhsv** [comment]
Hi @davidbalazs ,

I was just curious if you had had opportunity to try current v3/master code.  Thanks.

**Comment by davidbalazs** [comment]
hi @martinhsv sorry for the long delay, I was involved in something else in the meantime, but I have some great news to share:
with modsecurity":"ModSecurity v3.0.4 (Linux)
and ModSecurity-nginx v1.0.1 connector, it worked fine.
I ran the same test over the weekend and the number of processes remained constant and the memory didn't go higher than 200MB

Thanks for the assistance!

**Comment by martinhsv** [comment]
Hi @davidbalazs ,

That's great to hear.  Thanks for posting the update.
