### ISSUE TITLE
modsecurity 2.9.3 does not work in nginx proxy.

### ISSUE THREAD

**Issue by ggghuilei** [SpiderLabs/ModSecurity#2221]
**Describe the bug**

 - ModSecurity version: modsecurity 2.9.3 
 - WebServer: nginx 1.14
 - OS : Linux

modsec.conf
Include "./modsecurity.conf"
Include "./owasp-modsecurity-crs-3.2.0/crs-setup.conf"
Include "./owasp-modsecurity-crs-3.2.0/rules/*.conf"

**Additional context**
I use Nginx configuration content as follows：

user root root;
worker_processes auto;
worker_cpu_affinity auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    keepalive_timeout  65;

	upstream 1 {
		server 192.168.74.201:80;
	}

	server
	{
		listen 1100;
		server_name  192.168.74.200;
		location / {
			ModSecurityEnabled on;                         
			ModSecurityConfig /tos/etc/ssloffload/conf/modsec.conf;
																   
			proxy_pass http://1;                                   
			session_sticky_hide_cookie upstream=1;                 
			#root   html;                                          
			#index  index.html index.htm;     
		}
	}
}

**********************************************************
       Rules work when location is a local resource.But when I changed location to a proxy, the rules didn't work and I couldn't block the attack.
       Is there a problem with my configuration？

**Comment by zimmerle** [comment]
Hi @ggghuilei,

For nginx, you may want to use libModSecurity with Nginx connector - https://github.com/SpiderLabs/ModSecurity-nginx
