### ISSUE TITLE
This is an enhancement request to expose parsed rule results and default values.

### ISSUE THREAD

**Issue by rperper** [SpiderLabs/ModSecurity#2223]
We are a web server vendor and as an optimization, we'd like to avoid calling mod_security functions like msc_append_request_body and msc_append_response body (along with the associated intervention processing) when request/response body processing is disabled.  We'd sure like to have the parsed results of that info made available to us as API.

We see that msc_create_rules_set() gives us the parsed rules and they appear usable once the merge has been done.  However, items like the default values for unset m_requestBodyLimit are not visible.  If you could:
   - Verify that the use of the `Rules` object can legally be used within a transaction.
   - At some point expose the defaults for unset values.

Thanks so much!

**Comment by zimmerle** [comment]
The idea is that the parser state can be disabled or enable in run time. having said that, the parsed values may not be represented as the value could be changed later on. Same for the limits.
