### ISSUE TITLE
Some questions about ModSecurity 3.0.3 with Apache

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#2224]
1.Problem with the unicode map file
I have created the unicode map file,but it still reports error：
`Failed to open the unicode map file from: /usr/local/apache/conf/modsecurity/unicode.mapping`
My temporary solution is disable SecUnicodeMapFile,but I don't know whether there are other hidden dangers.
There is no such problem with ModSecurity 2.9.3.

2.Where is mlogc
I can't find mlogc after installation,do I need to install it by myself?

3.Including rule files
Does `modsecurity_rules_file` only can include one file at a time? I put OWASP rule files in a folder,then I include them like this:
`modsecurity_rules_file /usr/local/apache/conf/modsecurity/rules/*.conf`
but it reports error.

4.Auditlog part missing
Request body and Response body can't be recorded in auditlog.

**Comment by zimmerle** [comment]
Please, do not use libModSecurity with apache. Apache connector is still alpha, not ready for production.
