### ISSUE TITLE
SecDataDir is not working in version 3 

### ISSUE THREAD

**Issue by nasirbas1** [SpiderLabs/ModSecurity#2226]
I have tried every path with the SecDataDir. Have also tried everything with the permissions but have not been able to get the modsecurity to write to the disk . It just doesn't write to the disk.
It always keeps the collections in memory . 

**SecDataDir /usr/local/secdatadir/**

Have provided secdatadir each and every permission but still have not been able to get the collections written . Can anyone help?

**Comment by martinhsv** [comment]
Hi @nasirbas1 ,

It sounds like you're talking about two different things.

SecDataDir is indeed not currently supported in ModSecurity v3.  Moreover, that is not intended to be the log location.

If you're using Parallel logging as your SecAuditLogType, the directory location is specified using SecAuditLogStorageDir.

**Comment by nasirbas1** [comment]
Hi @martinhsv ,
There were some misnomers in there , have updated the description.
I actually meant the collection persistence only, not the logs . The logs part is working fine
and its correctly writing to the **/var/logs/modsec_audit.log**. Folder name might have 
confused you. 
So if SecDataDir is not supported in V3 as of now , is there no way around to persist the collections 
to the disk , because with Nginx they vanish every-time a reload of Nginx happens.

**Comment by nasirbas1** [comment]
@zimmerle @martinhsv  Anything on this?

**Comment by zimmerle** [comment]
Hi @nasirbas1,

The Persistent collection on v3 depends on the backend support. By default, the memory back end is selected. It means that the collection indeed vanishes on every restart. You may want to enable the lmdb backend if you want to persist the collections on disk.
