### ISSUE TITLE
cannot compile Modsecurity in openwrt for Mediatek platform

### ISSUE THREAD

**Issue by amelroua** [SpiderLabs/ModSecurity#2228]
**Describe the bug**
whenever I type make I got an error indicating that librt is not found
`
 /usr/bin/ld: cannot find -lrt.Code:/usr/bin/ld: cannot find -lrt collect2: error: ld returned 1 exit status make[3]: *** [Makefile:1601: libmodsecurity.la] Error 1 make[3]: Leaving directory '/root/ModSecurity/src' make[2]: *** [Makefile:3222: all-recursive] Error 1 make[2]: Leaving directory '/root/ModSecurity/src' make[1]: *** [Makefile:1015: all] Error 2 make[1]: Leaving directory '/root/ModSecurity/src' make: *** [Makefile:1025: all-recursive] Error 1
--`
At first, I tried to search for librt but I cannot find it in my system and when I perform
> opkg install librt
> Package librt (1.1.24-2) installed in root is up to date.
However, when I search I cannot find librt.so and I find only librt.control, librt.list, and librt.premrm files
Another solution I tried is to remove the librt from the Makefile but I got the same error even after removing LD=/usr/bin/ld and GLOBAL_LDADD= -lrt. in the following lines:
`GLOBAL_LDADD = -lrt
GREP = /bin/grep
INSTALL = ./install-sh -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS =  -L/usr/local/lib -lpcre`

**Comment by zimmerle** [comment]
Hi @amelroua,

Can you try to re-install that package? Also, try to list if the files are really part of the package. It might be a transitional package.

**Comment by amelroua** [comment]
I tried to reinstall it but now I got a "cc1plus: out of memory allocating 6404724 bytes after a total of 34328576 bytes" error.  But, I have enough space in my device.

**Comment by zimmerle** [comment]
@amelroua, The linker is very memory intensive. You may want to cross-compile or use a bigger swap space

**Comment by amelroua** [comment]
Our system is implemented based on musl libc and not glibc. So, I got many errors related to librt and libpthread that are not identified. How can I compile Modsecurity in our system?

**Comment by zimmerle** [comment]
Hi @amelroua,

I am afraid I cannot help you promptly because o don't know all the details of your environment. Is there o virtual machine/docker image that I can use to replicate your environment?
