### ISSUE TITLE
Register a mime type for ModSecurity audit log format with IANA

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#223]
MODSEC-73: I'd like to get a mime type registered w/IANA for the ModSecurity audit log format.

http://www.iana.org/assignments/media-types/

Perhaps: {{application/vnd.breach.modsecurity.auditlog}}

**Comment by zimmerle** [comment]
Since the audit are JSON, such registration is no longer needed.
