### ISSUE TITLE
Warnings when execute make command with modsecurity2.9.3

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#2230]
These are  warnings when I execute make command with modsecurity2.9.3:
`libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../apache2 -DLINUX -D_REENTRANT -D_GNU_SOURCE -DVERSION_NGINX -I/usr/include/apr-1 -I/usr/include/apr-1 -I/usr/include/httpd -DWITH_CURL -I/usr/include/libxml2 -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500 -DREQUEST_EARLY -DWITH_APU_CRYPTO -DWITH_REMOTE_RULES -g -O2 -I/usr/include/apr-1 -MT standalone_la-config.lo -MD -MP -MF .deps/standalone_la-config.Tpo -c config.c  -fPIC -DPIC -o .libs/standalone_la-config.o`
`config.c: In function ‘process_command_config’:`
`config.c:1107:5: warning: passing argument 1 of ‘apr_filepath_root’ from incompatible pointer type [enabled by default]`
`     status = apr_filepath_root(&rootpath, &incpath, APR_FILEPATH_TRUENAME | APR_FILEPATH_NATIVE, ptemp);`
`In file included from /usr/include/apr-1/apr_file_io.h:29:0,`
`                 from /usr/include/apr-1/apr_network_io.h:26,`
`                 from /usr/include/apr-1/apr_buckets.h:29,`
`                 from /usr/include/httpd/util_filter.h:26,`
`                 from /usr/include/httpd/http_core.h:32,`
`                 from config.c:18:`
`/usr/include/apr-1/apr_file_info.h:336:27: note: expected ‘const char **’ but argument is of type ‘char **’`
` APR_DECLARE(apr_status_t) apr_filepath_root(const char **rootpath,`
`config.c:1107:5: warning: passing argument 2 of ‘apr_filepath_root’ from incompatible pointer type [enabled by default]`
`     status = apr_filepath_root(&rootpath, &incpath, APR_FILEPATH_TRUENAME | APR_FILEPATH_NATIVE, ptemp);`
`In file included from /usr/include/apr-1/apr_file_io.h:29:0,`
`                 from /usr/include/apr-1/apr_network_io.h:26,`
`                 from /usr/include/apr-1/apr_buckets.h:29,`
`                 from /usr/include/httpd/util_filter.h:26,`
`                 from /usr/include/httpd/http_core.h:32,`
`                 from config.c:18:`
`/usr/include/apr-1/apr_file_info.h:336:27: note: expected ‘const char **’ but argument is of type ‘char **’`
` APR_DECLARE(apr_status_t) apr_filepath_root(const char **rootpath,`

All commands executed are：
`yum install -y gcc make libxml2 libxml2-devel httpd-devel pcre-devel curl-devel libtool`
`tar -zxvf modsecurity-2.9.3`
`cd modsecurity-2.9.3`
`./configure --enable-standalone-module --disable-mlogc`
`make`

**Comment by zimmerle** [comment]
Hi @prince-java,

Is that actually an error or just a warning message?

**Comment by prince-java** [comment]
@zimmerle 
Thank you for reply.It's just a warning message,such as:
`/usr/include/apr-1/apr_file_info.h:336:27: note: expected ‘const char **’ but argument is of type ‘char **`

**Comment by zimmerle** [comment]
That is not comfortable, however I believe it to be quite common in v2.x.
