### ISSUE TITLE
Strange logging behaviour in v3.1 against v3.0 and v.2

### ISSUE THREAD

**Issue by airween** [SpiderLabs/ModSecurity#2232]
As I know the 3.1 is coming soon, and I know there isn't a published code, but I grabbed the v3/dev/3.1-experimental, and made some tests.

I created two test for the regression test framework, you can find here:

https://gist.github.com/airween/7afda23a9979e2add46228c8f2f2d316

Note, that both tests are wrong, I set up a non-expected value for response to see the full output.

**How to reproduce**

In case of first test, with v3.0 the result is this:
```
[client 200.249.12.31] ModSecurity: Access denied with code 400 (phase 2). Matched "Operator `Rx' with parameter `bar' against variable `ARGS:foo' (Value: `bar' ) [file "errorlog1.json"] [line "3"] [id "1234"] [rev ""] [msg "Test message"] [data "Test logdata"] [severity "2"] [ver "OWASP-CRS"] [maturity "9"] [accuracy "9"] [hostname "200.249.12.31"] [uri "/"] [unique_id "157840332039.346291"] [ref "o0,3v10,3"]
```
The log contains all necessary argument, including filename, line, **id**, and so on...

With 3.1, the result is this:
```
[client 200.249.12.31] ModSecurity: Access denied with code 400 (phase -1). Matched "Operator `Rx' with parameter `bar' against variable `ARGS:foo' (Value: `bar' ) [file ""] [line "0"] [id "0"] [rev ""] [msg "Test message"] [data "Test logdata"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "200.249.12.31"] [uri "/"] [unique_id "1578403341"] [ref "o0,3v10,3"]
```
As you can see, there are so many fields are missing, like the **id**, filename, line. (But the **phase -1** is also very interesting...)

I can't decide that is this a bug or a new feature?

Take a look to the second test.

With 3.0, the (relevant) result (Error log) is empty:
```
Error log:
[EMPTY]
```
which is correct I guess.

With 3.1 the result is at my side:
```
ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `TX:inbound_anomaly_score_threshold' (Value: `0' ) [file ""] [line "0"] [id "0"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "200.249.12.31"] [uri "/"] [unique_id "1578403426"] [ref ""]
```
As you can see, the rule with a `nolog` action (and without **any** disruptive action) creates a log - and also without so many relevant fields, like **id**, filename, line - any many others.

As I wrote above, may be these are known problems/features - but I hope it was help to you.

**Comment by zimmerle** [comment]
thank you @airween. This code is under development, we expect to have a final version soon.
