### ISSUE TITLE
Leakage in Modsecurity WAF 3.0.1 with Nginx 

### ISSUE THREAD

**Issue by nasirbas1** [SpiderLabs/ModSecurity#2238]
Hi Team ,
We are facing a very strange and serious issue with modsecurity on 🆖**INX.**
 We have a 4 core machine with 4096 worker_connections for nginx .
**1️⃣** When any IP is blocked via modsecurity, it takes some time (_which is few minutes to half an hour sometimes_) to reflect properly ; that is even when an IP is blocked some of the requests from that **blocked IP** still go through , and the number of requests that go through decrease with respect to the time, when the block request for that IP was sent to modsecurity.
_Is this because of the fact that synchronisation is needed between the worker_connections ? Even after blocking the IP in Modsecurity, some worker-connections serve the requests as they don't know yet that the IP has been blocked_
> If this is the case how do we instantly synchronise all the worker_connections, so that each of the worker_connection instantly knows that the requests from that particular blocked IP are to be dropped.

**2️⃣** Even after blocking and synchronisation among all the worker connections(_after some hours of blocking when every worker-connection knows that IP was blocked_), some of the requests still manage to go through **(which is highly strange)** . If the number of requests from attacker IP come at a higher rate e.g. 20,000 req / minute, and given the fact that some of the requests from that blocked IP  go through, it causes lots of problems. At times when the footfall on the application server is already very high , this along with the number of leaked requests (even if **1%** ) causes immense slowdown.
So can Modsecurity WAF leak requests from an IP even after that IP was blocked ? ☹️

_We are using In memory storage for collections _
**OS Version : CentOS Linux 7
Nginx Version : 1.16.1
Modsecurity version : 3.03**

**Comment by zimmerle** [comment]
Hi @nasirbas1,

The memory storage is independent by worker. There is no sync. In order for you to get a sync you have to enable the LMDB collections.

**Comment by nasirbas1** [comment]
@zimmerle @martinhsv Guys Why is it that even after hours of blocking , some requests from **blocked IP** still manage to go through? 

Memory is independent per worker that is fine. The communication take place between all workers at intervals with **SMDB** which contains the entry of IPs blocked ? This should take some time, which is okay . But some requests from IPs still manage to go through after hours . Why is it so and will compilation with **lmdb** instead of **smdb** stop this leakage?
