### ISSUE TITLE
F-Secure marks modsecurity-v3.0.4.tar.gz as infected by VEX.Webshell (Malware.HTML/Infected.WebPage.Gen2)

### ISSUE THREAD

**Issue by blaksec** [SpiderLabs/ModSecurity#2242]
F-Secure marks modsecurity-v3.0.4.tar.gz as infected by VEX.Webshell (Malware.HTML/Infected.WebPage.Gen2)

See https://www.virustotal.com/gui/file/b4231177dd80b4e076b228e57d498670113b69d445bab86db25f65346c24db22/detection

EDIT: This might have something to do with the fact that xss-html5secorg.txt and xss-xenotix.txt carry various signatures. Still would be nice to get a sign-off from the Mod Sec team even if this is a false positive.

**Comment by afoxdavidi** [comment]
Checked with F-Secure and they confirmed it to be a false positive, you can check your link again for the latest scan of the same file, it's not longer flagged by F-Secure.
