### ISSUE TITLE
ModSecurity cannot consider the defined security rules

### ISSUE THREAD

**Issue by amelroua** [SpiderLabs/ModSecurity#2243]
I installed Modsecurity in nginx but when I test the following basic rule: 
SecRule ARGS:testparam "@contains test" "id:1234,deny,status:403" 
the output of the test : 
curl localhost?testparam=test
the result should give 403 status. However, 
I get : <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">

**Comment by nasirbas1** [comment]
@amelroua Try setting phase:1 to the last part . Can you also please attach the modsec debug logs against this request

**Comment by zimmerle** [comment]
Hi @amelroua,

You have to identify if this 301 happens before the ModSecurity inspection. Or if it is a consequence of the 403. What happens if you try the **curl** without ModSecurity?

**Comment by amelroua** [comment]
> Hi @amelroua,
> 
> You have to identify if this 301 happens before the ModSecurity inspection. Or if it is a consequence of the 403. What happens if you try the **curl** without ModSecurity?

Yes, the curl without modsecurity gives the same 301 status.

**Comment by nasirbas1** [comment]
@amelroua So **301**  is not because of modsecurity. Check your debug logs against this request . You will get a fair idea what is happening

**Comment by nasirbas1** [comment]
> > Hi @amelroua,
> > You have to identify if this 301 happens before the ModSecurity inspection. Or if it is a consequence of the 403. What happens if you try the **curl** without ModSecurity?
> 
> Yes, the curl without modsecurity gives the same 301 status.

@amelroua  So **301** is not because of modsecurity. Check your debug logs against this request . You will get a fair idea what is happening
