### ISSUE TITLE
Fix Documentation link for 3.x reference manual. 

### ISSUE THREAD

**Issue by z0r0** [SpiderLabs/ModSecurity#2244]
Hello, in trying to access the reference manual for 3.x, it appears to be unavailable. The link on the [wiki](https://github.com/SpiderLabs/ModSecurity/wiki) points to an unavailable page for the 3.x [reference manual](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29)

**Comment by zimmerle** [comment]
Hi @z0r0,

The manual for 3.x does not exist yet. Please use the one for 2.x

**Comment by NeckBeardPrince** [comment]
Any plans to write the manual?
