### ISSUE TITLE
Cannot send any image on prestashop from API

### ISSUE THREAD

**Issue by gfau** [SpiderLabs/ModSecurity#2246]
Hi, 
From our ERP, we try to send a image into Prestashop throught they API.
We have an issue in one hoster, ModSecurity reject it from with rules.
We have this return : 
SecRule REQBODY_ERROR "!@eq 0" \
"id:'200002', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"

The body is encoded in BINARY code.

What can we do to solve it without disable this rules ? 

Thx a lot in advance.

**Comment by airween** [comment]
That would be a big help if you can show the relevant part of debug log. And if possible, the body of the request.

**Comment by gfau** [comment]
Thx for your answer.
This is an example but not with the true website, on another hoster that's working well.
[http://tiny.cc/de70iz](http://tiny.cc/de70iz)

**Comment by airween** [comment]
Thanks - I don't know is that a *real* request, or you just forgot to copy the last line.

The final boundary missing from that request, that could triggered this.
There should be one more line with content:
```
--------------------------------
```
(same as the boundary at top of file, but plus 2 more `--`)

**Comment by gfau** [comment]
Thanks for your answer;
There are already a boundary "----------------------------" + "--" at start and at end of the body in the sample.

**Comment by airween** [comment]
I played with your request, and I think I found two things which can trigger the error above:
* don't use a hyphen-only boundary (`-----`), put some alphanumerical characters
* you have to terminate the lines with CR-LF

[Here](https://www.dropbox.com/s/2r7ysv8hsng4psk/modsec_reqbody.txt) is a request "file", grab it (but take care when you save that - save it as Windows like text file), and try it with this command:

`cat modsec_reqbody.txt | netcat localhost 80`

Hope this helps.
