### ISSUE TITLE
compilation error for v3.0.4

### ISSUE THREAD

**Issue by vieridipaola** [SpiderLabs/ModSecurity#2247]
Making all in reading_logs_with_offset
make[2]: Entering directory '/var/tmp/portage/www-apache/mod_security-3.0.4/work/modsecurity-v3.0.4/examples/reading_logs_with_offset'
x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../src   -std=c++11 -I../../headers -I../.. -g -I../others -fPIC -O3 -DWITH_GEOIP -I/usr/include/  -DWITH_MAXMIND       -DPCRE_HAVE_JIT -I/usr/include/libxml2 -DWITH_LIBXML2   -O2 -pipe -c -o read-read.o `test -f 'read.cc' || echo './'`read.cc
make[2]: *** No rule to make target '../../src/.libs/libmodsecurity.a', needed by 'read'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/www-apache/mod_security-3.0.4/work/modsecurity-v3.0.4/examples/reading_logs_with_offset'
make[1]: *** [Makefile:544: all-recursive] Error 1

Replacing libmodsecurity.a with libmodsecurity.la solves the problem.

Making all in reading_logs_via_rule_message
make[2]: Entering directory '/var/tmp/portage/www-apache/mod_security-3.0.4/work/modsecurity-v3.0.4/examples/reading_logs_via_rule_message'
x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../src   -std=c++11 -I../../headers -I../.. -g -I../others -fPIC -O3 -DWITH_GEOIP -I/usr/include/       -DPCRE_HAVE_JIT -I/usr/include/libxml2 -DWITH_LIBXML2   -O2 -pipe -c -o simple_request-simple_request.o `test -f 'simple_request.cc' || echo './'`simple_request.cc
make[2]: *** No rule to make target '../../src/.libs/libmodsecurity.a', needed by 'simple_request'.  Stop.
make[2]: Leaving directory '/var/tmp/portage/www-apache/mod_security-3.0.4/work/modsecurity-v3.0.4/examples/reading_logs_via_rule_message'
make[1]: *** [Makefile:544: all-recursive] Error 1

Same thing here.

make[2]: Entering directory '/var/tmp/portage/www-apache/mod_security-3.0.4/work/modsecurity-v3.0.4/examples/using_bodies_in_chunks'
x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../src   -std=c++11 -I../../headers -I../.. -g -I../others -fPIC -O3 -DWITH_GEOIP -I/usr/include/  -DWITH_MAXMIND       -DPCRE_HAVE_JIT -I/usr/include/libxml2 -DWITH_LIBXML2   -O2 -pipe -c -o simple_request-simple_request.o `test -f 'simple_request.cc' || echo './'`simple_request.cc
make[2]: *** No rule to make target '../../src/.libs/libmodsecurity.a', needed by 'simple_request'.  Stop.
make[2]: Leaving directory '/var/tmp/portage/www-apache/mod_security-3.0.4/work/modsecurity-v3.0.4/examples/using_bodies_in_chunks'
make[1]: *** [Makefile:544: all-recursive] Error 1

Same thing here.

**Comment by zimmerle** [comment]
Hi @vieridipaola,

What is your env? where did you get this modsec from?

**Comment by vieridipaola** [comment]
Hi,

I'm on Gentoo Linux.
Building from https://github.com/SpiderLabs/ModSecurity/releases/download/v3.0.4/modsecurity-v3.0.4.tar.gz

As a side question I'd like to know why I see this below while configuring:

configure: Support for GeoIP was disabled by the utilization of --without-yajl or --with-yajl=no
configure: Nothing about GeoIP was informed during the configure phase. Trying to detect it on the platform...
configure: using GeoIP v1.6.12
configure: Nothing about MaxMind was informed during the configure phase. Trying to detect it on the platform...
configure: using MaxMind v1.4.2

Isn't yajl a JSON library? In any case, I didn't specify --without-yajl. What does it have to do with GeoIP?

Coming from version 2, I see now in version 3 that the following are unknown options to the configure script:

--enable-request-early, --with-apxs, --disable-mlogc, --disable-lua-cache, --disable-pcre-jit, --disable-docs

I'm just trying to sort out a decent Gentoo ebuild for this package.

Thanks

**Comment by airween** [comment]
Just my 2 cents', but I ran into a similar problem, when I had both of these packages:
```
libluajit-5.1-dev
liblua5.1-0-dev
```
I've removed the `libluajit-5.1-dev`, and problem solved. May be this helps...

**Comment by vieridipaola** [comment]
@zimmerle,

Here's some more info on my environment:

bash:          4.4
cmake:           3.14.6
autoconf:       2.69
automake:       1.16.1
binutils:       2.32
gcc:            9.2.0
gcc-config:     2.1
libtool:        2.4.6
make:           4.2.1
glibc:           2.29

**Comment by zimmerle** [comment]
Hi @vieridipaola,

Version 3 is a re-write, those configuration flags has changed from v2 to v3. Here is an example of a package and its configuration flags:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/libmodsecurity

**Comment by vieridipaola** [comment]
I take it that to avoid the compilation error you suggest to use --disable-examples like in the archlinux example.
