### ISSUE TITLE
What happend to the experimental rules from v2?

### ISSUE THREAD

**Issue by JStyle21** [SpiderLabs/ModSecurity#2248]
Hi,

This is more of a question than a bug, i was looking to use a rule that was in v2's experimental folder but i don't see it on v3, can i just copy paste to add a new regex as a rule for v3?

**Comment by martinhsv** [comment]
Hi @JStyle21,

It sounds like you're asking about the OWASP ModSecurity Core Rule Set (CRS) and its v2 rules that were found in the /experimental_rules/ directory.

Your question would be better directed here:

https://github.com/SpiderLabs/owasp-modsecurity-crs

**Comment by JStyle21** [comment]
@martinhsv  Are you sure? rules are static, i'm asking why isn't it implemented or supported.
