### ISSUE TITLE
Does modsec v3 have any methods for get statistic about ip collection?

### ISSUE THREAD

**Issue by unix196** [SpiderLabs/ModSecurity#2256]
Good day. I install modsec v 3.0.3 with nginx; wrote some simple rules which blocked ip address if it exist in ip collection. 
Example code: https://pastebin.com/fMf4Es5L

When my rules are triggered, in nginx error log I see:
```
2020/02/03 09:29:24 [error] 5162#0: *1891479 [client 1.1.1.1] ModSecurity: Access denied with code 403 (phase 1). Matched "Operator `Eq' with parameter `1' against variable `IP:1.1.1.1::::block_flag' (Value: `1' ) [file "/etc/nginx/modsec/main.conf"] [line "55"] [id "500"] [rev ""] [msg ""] [data "Blacklist ip.block_flag - 1, real_ip - 1.1.1.1"] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "1.1.1.1"] [uri "/modsecurity/my-test.cfg"] [unique_id "158071136413.409238"] [ref ""], client: 1.1.1.1, server: ...."
```
If I send bad request several times, then I receive _forbidden_ in following requests.
It would be cool, if I can get some statistic about blocked ip:
- how many ip addresses in collection?
- does this ip address exist in ip collection?

This information may be important, because need understand how works my WAF rules. Of course, I can read logs, but It is very uncomfortable - I find that ip address was blocked, but is it locked yet or not?
I found this backends for modsecurity v3 - https://github.com/SpiderLabs/ModSecurity/tree/v3/master/src/collection/backend. In my case, I use in_memory backend(SDBM) (because after nginx reload, bad ip addresses don't blocking).
Is it any chance get this statistic (may be get access to SDBM)?

**Comment by zimmerle** [comment]
Hi @unix196,

There are too many options to block IP address, to have total control of what has been blocked or not, you may want to consider Lua scripts. Or even use an external server such as RBL. That way you will have modsec blocking the selected IPs and keep the history on how/when an IP got blocked.
