### ISSUE TITLE
Fails to compile with MaxMind DB

### ISSUE THREAD

**Issue by mdunc** [SpiderLabs/ModSecurity#2259]
Compilation currently fails if the MaxMind DB library is in use.

`utils/geo_lookup.cc:124:13: error: no matching function for call to 'MMDB_lookup_string'
        r = MMDB_lookup_string(&mmdb, target.c_str(), &gai_error, &mmdb_error);
            ^~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/maxminddb.h:195:33: note: candidate function not viable: 1st argument ('const MMDB_s *') would lose const qualifier
    extern MMDB_lookup_result_s MMDB_lookup_string(MMDB_s *const mmdb,
                                ^
1 error generated.
Makefile:2929: recipe for target 'utils/libmodsecurity_la-geo_lookup.lo' failed
make[3]: *** [utils/libmodsecurity_la-geo_lookup.lo] Error 1
`

I suspect it comes from changing to a const here - https://github.com/SpiderLabs/ModSecurity/commit/ff590174dad90b209ad9efe0468fa3a479cce07f#diff-468637eeb7c0ed7f867a0b24cca85e0aR109

**Comment by airween** [comment]
Same error at #2254, see the comments.

**Comment by mdunc** [comment]
Yep, that's the same thing.  Thanks!
