### ISSUE TITLE
Compile faile with useing centos7 mininal version

### ISSUE THREAD

**Issue by Archerkong** [SpiderLabs/ModSecurity#2268]
**Describe the bug**

Error at compile time

**Logs and dumps**
Making all in src
make[1]: 进入目录“/opt/ModSecurity1/src”
make  all-recursive
make[2]: 进入目录“/opt/ModSecurity1/src”
make[3]: 进入目录“/opt/ModSecurity1/src”
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/      -DWITH_YAJL    -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/include  -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT parser/libmodsecurity_la-seclang-parser.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-parser.Tpo -c -o parser/libmodsecurity_la-seclang-parser.lo `test -f 'parser/seclang-parser.cc' || echo './'`parser/seclang-parser.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_GEOIP -I/usr/include/ -DWITH_YAJL -DPCRE_HAVE_JIT -DWITH_SSDEEP -I/usr/include -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT parser/libmodsecurity_la-seclang-parser.lo -MD -MP -MF parser/.deps/libmodsecurity_la-seclang-parser.Tpo -c parser/seclang-parser.cc  -fPIC -DPIC -o parser/.libs/libmodsecurity_la-seclang-parser.o
In file included from ../src/rule_script.h:21:0,
                 from seclang-parser.yy:20,
                 from parser/seclang-parser.cc:40:
../headers/modsecurity/rules_set.h: In constructor 'modsecurity::RulesSet::RulesSet()':
../headers/modsecurity/rules_set.h:51:9: error: expected identifier before ',' token
         ,m_secmarker_skipped(0)
         ^
make[3]: *** [parser/libmodsecurity_la-seclang-parser.lo] 错误 1
make[3]: 离开目录“/opt/ModSecurity1/src”
make[2]: *** [all-recursive] 错误 1
make[2]: 离开目录“/opt/ModSecurity1/src”
make[1]: *** [all] 错误 2
make[1]: 离开目录“/opt/ModSecurity1/src”
make: *** [all-recursive] 错误 1

**To Reproduce**

I followed the installation tutorial with https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x Centos 7 Minimal dynamic,but step to "make" ,it has an error,Error message is on it

**Comment by zimmerle** [comment]
Hi @Archerkong,

What is the latest commit in your ModSecurity git-tree?

**Comment by Archerkong** [comment]
@zimmerle II see you updated the version and the problem has been solved，thanks
