### ISSUE TITLE
Reference Manual links for 3.x in the wiki are not working

### ISSUE THREAD

**Issue by shibumi-matt** [SpiderLabs/ModSecurity#2270]
Navigating to the following link for 3.x docs:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29

Gives the message:
"You do not have permission to update this wiki."

**Comment by zimmerle** [comment]
Hi @shibumi-matt 

Indeed, the reference manual for version 3 does not exist yet.
