### ISSUE TITLE
Hook For run script after block

### ISSUE THREAD

**Issue by hammedsadeghi** [SpiderLabs/ModSecurity#2271]
hi
i want to run scripot for send email or SMS after blocking request in modSecurity in Nginx
can you guide me for this problem ?

**Comment by jkurek1** [comment]
You can use SecRule with operator exec:
SecRule: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecRule
Exec operator: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#exec

Check this also: https://gryzli.info/2015/12/25/modsecurity-using-lua-scripts-with-secrulescript/
SecRuleScript: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecRuleScript
