### ISSUE TITLE
rule not logged with SecRuleEngine On

### ISSUE THREAD

**Issue by stefan-kos** [SpiderLabs/ModSecurity#2274]
I use ModSecurity 3.0.4 and CRS 3.2.0 ruleset with Apache 2.4.41 ModSecurity-apache connector compiled from master, CentOS 8.1.1911

Using the ruleset with the scoring feature, on a blocking situation there is a rule logging the total score, rule ID 949110

This is not working if SecRuleEngine is set to "on". The total score with this rule, or this rule is logged if SecRuleEngine is set to DetectionOnly. Same behavior compiled with pcre 8 and 10.

It works as expected with ModSecurity 2.9.3, the total score is logged also with set SecRuleEngine On with some useful additional infos.

This is in error log.

When using modsecurity_rules 'SecDebugLog /var/log/sec_debug.log' with debug level 9 some info is found that it processing the rule, but not logged.

Also I'm wondering if the unique_id seems to be logged differently as well.
And, is there a plan to have the ModSecurity-apache connector stable?

Thanks

**Comment by airween** [comment]
> with Apache 2.4.41 ModSecurity-apache connector

Please note, that ModSecurity-apache connector is not stable, and **very** not recommended to use it.

**Comment by stefan-kos** [comment]
Hi, thanks for your answer. What would then be the recommended way to use v3?

**Comment by airween** [comment]
I'm sorry, I don't have any information about that.

**Comment by stefan-kos** [comment]
Ok thank you. Apache connector is quiet long in beta now…

 

Is connector for nginx stable?

 

Von: Ervin Hegedus <notifications@github.com>
Antworten an: SpiderLabs/ModSecurity <reply@reply.github.com>
Datum: Samstag, 29. Februar 2020 um 12:02
An: SpiderLabs/ModSecurity <ModSecurity@noreply.github.com>
Cc: Stefan <stefan@koebeli.ch>, Author <author@noreply.github.com>
Betreff: Re: [SpiderLabs/ModSecurity] rule not logged with SecRuleEngine On (#2274)

 

I'm sorry, I don't have any information about that.

**Comment by airween** [comment]
Hi Stefan,

> Ok thank you. Apache connector is quiet long in beta now…

For Apache HTTP server you can use the mod_security2 Apache module.

> Is connector for nginx stable?

ModSecurity-nginx connector is officially released, as I know it's production ready.

**Comment by stefan-kos** [comment]
Hi, no worries, it's fine for me. I give nginx a chance for our reverse proxy, and wait for apache connector is prod ready.
Thanks for your answers, I close this issue.
