### ISSUE TITLE
Where is mlogc in ModSecurity 3?

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#2275]
I can't find mlogc after installing ModSecurity 3.0.4, do I need to install it by myself?
Or just it only can work with ModSecurity 2?

**Comment by zimmerle** [comment]
Hi @prince-java,

The **mlogc** utility is no longer available as part of v3. Withing v3, the default logging alternative is a JSON that can be sent straight to your event processing database (such as _logstash_). Therefore you may not need something like the **mlogc**.
