### ISSUE TITLE
[Question]: nginx location configuration

### ISSUE THREAD

**Issue by aledbf** [SpiderLabs/ModSecurity#2276]
I am using this configuration:

- http section:
```
modsecurity on;
modsecurity_rules_file /etc/nginx/modsecurity/modsecurity.conf-recommended;
modsecurity_rules_file /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf;
```

- a particular location:

```
modsecurity_rules '
	Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
	SecRuleEngine On
	SecRequestBodyAccess On
	SecResponseBodyAccess Off
	SecAuditEngine RelevantOnly
	SecRuleRemoveById 911100
';
```

The issue here is related to `modsecurity_rules` configuration. There is no enforced mode in the location
Is this the right way to configure the module?

How is it possible to debug this misconfiguration?
Thanks

xref: https://github.com/SpiderLabs/ModSecurity-nginx/issues/183

**Comment by zimmerle** [comment]
Let's have this conversation at SpiderLabs/ModSecurity-nginx#183
