### ISSUE TITLE
httpd services is taking more time to restart

### ISSUE THREAD

**Issue by Vaibhavgoe** [SpiderLabs/ModSecurity#2280]
Hi All,
 We have configured modsecurity on httpd server. after mod security configuration, it is taking more time to restart the httpd services. it is taking around 2 mins. can anyone suggest, how to resolve the issue

**Comment by airween** [comment]
Just an idea... Does your `SecStatusEngine` variable set to `On`? If yes be sure, your another network component (eg. firewall, ...) doesn't blocks the status request.

**Comment by zimmerle** [comment]
Hi @Vaibhavgoe,

Are you using **SecRemoteRules**?

**Comment by Vaibhavgoe** [comment]
> Just an idea... Does your `SecStatusEngine` variable set to `On`? If yes be sure, your another network component (eg. firewall, ...) doesn't blocks the status request.

No SecStatusEngine is off.



> Hi @Vaibhavgoe,
> 
> Are you using **SecRemoteRules**?

No we are not using SecRemoteRules

**Comment by Vaibhavgoe** [comment]
[Thu Mar 12 10:49:44.752873 2020] [mpm_prefork:notice] [pid 27788] AH00171: Graceful restart requested, doing restart
[Thu Mar 12 10:50:35.332727 2020] [auth_digest:notice] [pid 27788] AH01757: generating secret for digest authentication ...
[Thu Mar 12 10:50:35.334046 2020] [lbmethod_heartbeat:notice] [pid 27788] AH02282: No slotmem from mod_heartmonitor
While reloading the httpd service, the following is line from Error Logs. it tooks aroud 1 min to reload the service. Please suggest 

[Thu Mar 12 10:50:35.334697 2020] [ssl:warn] [pid 27788] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Thu Mar 12 10:50:35.336162 2020] [mpm_prefork:notice] [pid 27788] AH00163: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips configured -- resuming normal operations
[Thu Mar 12 10:50:35.336180 2020] [core:notice] [pid 27788] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by zimmerle** [comment]
Is there any ruleset loaded? is it ModSecurity version 2 or 3? What is the specific version?

**Comment by Vaibhavgoe** [comment]
default core rule set are loaded.. it is ver 2

**Comment by zimmerle** [comment]
What happens if you disable the CRS? While restarting apache, do you get any **version mismatch** warning?

**Comment by Vaibhavgoe** [comment]
after disabling the core rule set, it is still taking time and don't getting any version mismatch error.

**Comment by zimmerle** [comment]
Hi @Vaibhavgoe,

Have you installed the packages using the distribution or have you compiled it? Is there any other component associated with ModSecurity?

**Comment by zimmerle** [comment]
@Vaibhavgoe ping
