### ISSUE TITLE
Azure AD redirect login with modsecurity

### ISSUE THREAD

**Issue by sithara** [SpiderLabs/ModSecurity#2282]
I've problem with Azure AD redirect login throwing modSecurity

this what i see in logs :
1) 942430 Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (12): 
 `"message": "Warning. Pattern match \"((?:[\\\\~\\\\!\\\\@\\\\#\\\\$\\\\%\\\\^\\\\&\\\\*\\\\(\\\\)\\\\-\\\\+\\\\=\\\\{\\\\}\\\\[\\\\]\\\\|\\\\:\\\\;\\\"\\\\'\\\\\\xc2\\xb4\\\\\\xe2\\x80\\x99\\\\\\xe2\\x80\\x98\\\\`\\\\<\\\\>][^\\\\~\\\\!\\\\@\\\\#\\\\$\\\\%\\\\^\\\\&\\\\*\\\\(\\\\)\\\\-\\\\+\\\\=\\\\{\\\\}\\\\[\\\\]\\\\|\\\\:\\\\;\\\"\\\\'\\\\\\xc2\\xb4\\\\\\xe2\\x80\\x99\\\\\\xe2\\x80\\x98\\\\`\\\\<\\\\>]*?){12})\" at ARGS:code ....",`
2) 942440 SQL Comment Sequence Detected
`    "message": "Warning. Pattern match \"(/\\\\*!?|\\\\*/|[';]--|--[\\\\s\\\\r\\\\n\\\\v\\\\f]|(?:--[^-]*?-)|([^\\\\-&])#.*?[\\\\s\\\\r\\\\n\\\\v\\\\f]|;?\\\\x00)\" at ARGS:code ....",`

Output of Azure AD redirect login is expected to be in the below format:

`:provider => "azureactivedirectory",
  :uid => "123456abcdef",
  :info => {
    :name => "John Smith",
    :email => "jsmith@contoso.net",
    :first_name => "John",
    :last_name => "Smith"
  },
  :credentials => {
    :code => "ffdsjap9fdjw893-rt2wj8r9r32jnkdsflaofdsa9"
  },
  :extra => {
    :session_state => '532fgdsgtfera32',
    :raw_info => {
      :id_token => "fjeri9wqrfe98r23.fdsaf121435rt.f42qfdsaf",
      :id_token_claims => {
        "aud" => "fdsafdsa-fdsafd-fdsa-sfdasfds",
        "iss" => "https://sts.windows.net/fdsafdsa-fdsafdsa/",
        "iat" => 53315113,
        "nbf" => 53143215,
        "exp" => 53425123,
        "ver" => "1.0",
        "tid" => "5ffdsa2f-dsafds-sda-sds",
        "oid" => "fdsafdsaafdsa",
        "upn" => "jsmith@contoso.com",
        "sub" => "123456abcdef",
        "nonce" => "fdsaf342rfdsafdsafsads"
      },
      :id_token_header => {
        "typ" => "JWT",
        "alg" => "RS256",
        "x5t" => "fdsafdsafdsafdsa4t4er32",
        "kid" => "tjiofpjd8ap9fgdsa44"
      }
    }
  }`

Could you please let know if we should white-list these rules or do they have threats associated which needs to be fixed?

**Comment by martinhsv** [comment]
Hello @sithara ,

It looks like you are using OWASP Core Rule Set (CRS) rules.  Those rules are mostly intended to be generic, which means that the rules are not associated with a particular CVE (for example) that you could go ahead and patch.

Those types of generic rules are supposed to identify suspicious patterns in any context, but as a result, they can be prone to false positives.   See, for example, the comments associated with rule 942430: 'Expect a lot of false positives with this rule.'

If you want to leave the rule mostly in place but get rid of a particular false positive, one option is to remove the target with another rule.  For example, you could test for the URI and then use ctl:ruleRemoveTargetById to exclude a particular argument name from being tested..

(Note that if you have questions about the content of CRS rules, there is a separate group that creates and manages them: https://github.com/SpiderLabs/owasp-modsecurity-crs )
