### ISSUE TITLE
[Feat] No way to evaluate rule performance time ModSec v3

### ISSUE THREAD

**Issue by jeremyjpj0916** [SpiderLabs/ModSecurity#2283]
So I wanted to figure out why WAF takes 40 seconds on one type of payload thats not very big. So I see this:

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#secruleperftime

Was gonna do this:
```
#Custom PERF Tracker
SecRulePerfTime 1000
SecRule PERF_RULES "@qt 1000" "id:999,phase:3"
```

But then I notice v3 outputs:
```
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs-3.2.0/crs-setup.conf. Line: 802. Column: 132. SecRulePerfTime is not yet supported.  in /usr/local/kong/nginx.conf:101
```

Is there an alternative method to track rule performance time or am I just out of luck on the v3 series for now xD ? Seems like a super helpful feature that was not ported from 2.x to 3.x, hopefully its not super complex to add.

**Comment by zimmerle** [comment]
Hi @jeremyjpj0916,

ModSecurity was made to be used with Linux instrumentation. Follow the details here - https://github.com/SpiderLabs/ModSecurity-nginx/blob/master/ngx-modsec.stp and here https://en.wikipedia.org/wiki/SystemTap
