### ISSUE TITLE
Issue with make modules

### ISSUE THREAD

**Issue by ahmedelfaleh** [SpiderLabs/ModSecurity#2285]
**Error appears when run make modules inside nginx connector folder**
After compiling Modsecurity successfully and I downloaded http://nginx.org/download/nginx-1.10.3.tar.gz
I chose this version to be compatible with the running nginx, And I can't upgrade it because it is compatible with BigBlueButton Application.

Then `cd` into `nginx-1.10.3`
I ran:
`# ./configure --with-compat --add-dynamic-module=../ModSecurity-nginx`
But option `--with-compat` was wrong, so I removed it
So I ran
`# ./configure --add-dynamic-module=../ModSecurity-nginx << done`
And then I ran:
`# make modules`
I faces this error:

**Logs and dumps**

`../ModSecurity-nginx/src/ngx_http_modsecurity_rewrite.c: In function ‘ngx_http_modsecurity_rewrite_handler’:
../ModSecurity-nginx/src/ngx_http_modsecurity_rewrite.c:79:27: error: implicit declaration of function ‘ngx_inet_get_port’ [-Werror=implicit-function-declaration]
         int client_port = ngx_inet_get_port(connection->sockaddr);
                                   ^`
`cc1: all warnings being treated as errors
objs/Makefile:1210: recipe for target 'objs/addon/src/ngx_http_modsecurity_rewrite.o' failed
make[1]: *** [objs/addon/src/ngx_http_modsecurity_rewrite.o] Error 1
make[1]: Leaving directory '/usr/local/src/ModSecurity/nginx-1.10.3'
Makefile:14: recipe for target 'modules' failed
make: *** [modules] Error 2`

I followed this [link](https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/)

**Comment by ahmedelfaleh** [comment]
Anyone can help me with that?

**Comment by ahmedelfaleh** [comment]
I repeated the steps but with older modsecurity version 2.9, and the same issue appears.

**Comment by zimmerle** [comment]
Hi @ahmedelfaleh, it is very likely that you have multiple versions of nginx on your system and the **make modules** are using the wrong one. Is your nginx installed via compilation or installation package?

**Comment by ahmedelfaleh** [comment]
My nginx installed within an installation script of BigBlueButton.
It's installation package

**Comment by zimmerle** [comment]
you have to get the exact same source code that as used in this script.

**Comment by ahmedelfaleh** [comment]
Do you mean that I need to re-compile the same nginx version again, while I have existed one?

**Comment by zimmerle** [comment]
you have to use the same source files that you have used to compile the one that you have installed. also, you may need to use the exact same configuration flags.

**Comment by ahmedelfaleh** [comment]
I think that I have to uninstall the exist nginx and compile the same version from the source code.
If yes, I am worry of make the BigBlueButton stop working, because I don't know what flags I should use, and also worry if BigBlueButton is some how compatible with the existed nginx.
I am confuse of how to do that.

**Comment by zimmerle** [comment]
I am afraid I can't help with the specificities of BigBlueButton as I am not familiar with it. The process to compile the ModSecurity module is no different from other modules. Do they have documentation on how to add an extra module?

**Comment by ahmedelfaleh** [comment]
Unfortunately BBB doesn't mention anything regarding this needs.
I think that I need to use ModSecurity v2.9 not v3 because the nginx as you see is v1.10.x.
I will let you know if i fix it.

**Comment by ztbh** [comment]
sed -i 's|ngx_inet_get_port(connection->sockaddr|htons(((struct sockaddr_in *) connection->sockaddr)->sin_port|' /opt/ModSecurity-nginx/src/ngx_http_modsecurity_rewrite.c
sed -i 's|ngx_inet_get_port(connection->local_sockaddr|htons(((struct sockaddr_in *) connection->listening->sockaddr)->sin_port|' /opt/ModSecurity-nginx/src/ngx_http_modsecurity_rewrite.c

**Comment by luckygo666** [comment]
> Anyone can help me with that?

https://github.com/SpiderLabs/ModSecurity/issues/2285#issuecomment-605604085

**Comment by ztbh** [comment]
> Anyone can help me with that?

sed -i 's|ngx_inet_get_port(connection->sockaddr|htons(((struct sockaddr_in *) connection->sockaddr)->sin_port|' /opt/ModSecurity-nginx/src/ngx_http_modsecurity_rewrite.c
sed -i 's|ngx_inet_get_port(connection->local_sockaddr|htons(((struct sockaddr_in *) connection->listening->sockaddr)->sin_port|' /opt/ModSecurity-nginx/src/ngx_http_modsecurity_rewrite.c
