### ISSUE TITLE
Unable to use custom REQUEST_HEADER on whitelist action

### ISSUE THREAD

**Issue by vlameiras** [SpiderLabs/ModSecurity#2286]
I'm trying to use a custom request header on a ModSecurity whitelist rule so I can remove specific rules contained in this header.
```
SecRule REQUEST_URI "^/admin/index\.html$" \
   "id:1004,\
    phase:2,\
    pass,\
    nolog,\
    ctl:ruleRemoveById=%{request_headers.x-rules-excluded}"
```
However, when I try to do it I get the following error on NGINX:

>  Mar 20 16:18:42 develop-node ip[16035]: nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /tmp/test.modsec.conf. Line: 1062. Column: 96. Expecting an action, got: ctl:ruleRemoveById=%{request_headers.x-rules-excluded}" in /tmp/test.nginx.conf:28

I wonder if this is even possible to do...

**Comment by martinhsv** [comment]
Hello @vlameiras ,

So what you're trying to do is have an HTTP Request Header like:
```
x-rules-excluded: 200002
```
result in disabling a ModSecurity rule with an id 200002.

I'm not surprised that the rule you've written doesn't work as you'd hoped, and I cannot think of an alternative way to accomplish what you're trying to do.

I would moreover caution you against the whole approach.  In many types of web application attacks, request headers may be under the control of the attacker, and you wouldn't want to provide an attacker with the ability to turn off your WAF rules.

**Comment by vlameiras** [comment]
Hello @martinhsv ,

Exactly, this is what I was trying to achieve.

Thanks also for pointing that out, the idea was to sanitize the header before so we would prevent that. But since there is no way to achieve this I guess we will have to find an alternative.

Thank you once again.
