### ISSUE TITLE
How to trigger Correlated Attack

### ISSUE THREAD

**Issue by jkurek1** [SpiderLabs/ModSecurity#2287]
Hi,
I'm preparing monitoring solution for Mod Security. How can I trigger easy Correlated Successful Attack and Correlated Attack or any other rule?

**Comment by zimmerle** [comment]
Hi @Chivolta,

That depends on the ruleset that you have loaded. Did you have created your own rules?

**Comment by jkurek1** [comment]
Hi @zimmerle,
No I don't have any custom rules.

**Comment by zimmerle** [comment]
ModSecurity by itself won't protect your website. You have to load a set of rules. You can opt to: create your own rules, use commercial ones or even use open-source ones.

**Comment by jkurek1** [comment]
Yes, I know about it, but I'm looking for an easy way to trigger specific rules. Of course I can use vulnerable applications like owasp-juice, webgoat and trigger rules manually. I'm looking for a way, for example script that will trigger all rules or specific rules. I'm preparing solution based on ELK and I want to test all logs messages that may appear in audit logs/error logs in realtime.

**Comment by zimmerle** [comment]
That depends on what the rule is checking for. Without the rule, it will be impossible to tell.
