### ISSUE TITLE
Bug about modsecurity 2.9.3 when it work with nginx

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#2288]
**Describe the bug**

I report a bug about auditlog,the configuration in modsecurity.conf file is as follows:
`SecAuditEngine RelevantOnly`
`SecAuditLog /var/log/modsec_audit.log`
`SecAuditLogParts ABIJDEFHZ`
`SecAuditLogType Serial`
`SecAuditLogRelevantStatus ^(?:5|4(?!04))`

I know it means that modsecurity will only log the transaction which response status code is 5xx or 4xx, excluding 404,but the reality is that modsecurity records all the logs.

**Comment by zimmerle** [comment]
Hi @prince-java,

I would strongly recommend using 3.x with Nginx. The 2.x version is known to have some problems. Please upgrade to 3.x
