### ISSUE TITLE
Missing Audit Log with Nginx and custom errors

### ISSUE THREAD

**Issue by kfkawalec** [SpiderLabs/ModSecurity#2290]
I have nginx 1.16.1 with new version of modsecurity and all newest rules.
But on every request, event simple I have data in audit logs.

I have `SecAuditEngine RelevantOnly`
All configuration from:
https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended
https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.3/dev/crs-setup.conf.example

My nginx site config
```
server {
    listen 443 ssl http2;
    server_name domain.pl;

    ssl_certificate     /fullchain;
    ssl_certificate_key /privkey;

    error_page 403 /errors/403.html;
    location ^~ /errors/ {
        #modsecurity off;

        internal;
        root /var/www/default;
    }

    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/main.conf;

    location / {
        include proxy_params.conf;
        proxy_pass http://default_backend;
    }
}
```

Rules:
```
Include "/etc/nginx/modsec/modsecurity.conf"
Include "/etc/nginx/modsec/crs-setup.conf"
Include "/etc/nginx/modsec/rules/*.conf"
```

When I comment line `error_page 403 /errors/403.html;` audit logs works.
But with enabled this line audit log is empty (but nginx return proper 403 code, debug logs also works).

**Comment by kanitan** [comment]
the line after SecAuditEngine RelevantOnly:
```
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
```
So only the requests with response code 5xx,4xx(except 404) will be loged.

**Comment by martinhsv** [comment]
Hi @kfkawalec ,

Are you still having an issue?

**Comment by kfkawalec** [comment]
In this case I switch from my own WAF installation to Azure WAF (also with ModSecurity).
So I dont known if this in still a problem.
