### ISSUE TITLE
GeoIP error while starting nginx

### ISSUE THREAD

**Issue by Blason** [SpiderLabs/ModSecurity#2291]
Hi,

CentOS 7.7 Minimal, nginx/1.17.9 and owasp-modsecurity-crs-3.2.0 & Modsecurity, ModSecurity-nginx v1.0.1 and unable to start nginx with this error.

I a tried searching all the forum/Google but unable finding the exact resolution. Can someone please help? Or direct me to the resolution?

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /opt/owasp-modsecurity-crs-3.2.0/rules/REQUEST-910-IP-REPUTATION.conf. Line: 71. Column: 22. This version of ModSecurity was not compiled with GeoIP or MaxMind support.  in /etc/nginx/testcustomer/testcustomer.conf:6
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by zimmerle** [comment]
Hi @Blason,

ModSecurity version 3 has optional dependency support for the  GeoIP and/or MaxMind. You need to install one of them in your system and recompile ModSecurity. Notice by the end of './configure' there will be a summary of what dependencies are found. Make sure GeoIP or MaxMind are enabled.

**Comment by Blason** [comment]
Any link or documentation would be really appreciated. Would be really grateful

TIA
