### ISSUE TITLE
This version of ModSecurity was not compiled with GeoIP or MaxMind support

### ISSUE THREAD

**Issue by mhrznamn068** [SpiderLabs/ModSecurity#2293]
This version of ModSecurity was not compiled with GeoIP or MaxMind support
nginx version: nginx/1.16.1

**Comment by zimmerle** [comment]
Hi @mhrznamn068 how can we help you?

**Comment by Piju99** [comment]
Hi, I also got this error. Can help me to solve it?
Im using nginx 1.16.1

**Comment by zimmerle** [comment]
Hi @Piju99,

Have you compiled ModSecurity from GitHub or are you using a package from your distribution?

**Comment by Piju99** [comment]
yes, I have compiled that. But still got the error. Also checked and update GeoIP 

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/owasp-modsecurity-crs/rules/REQUEST-910-IP-REPUTATION.conf. Line: 75. Column: 22. This version of ModSecurity was not compiled with GeoIP or MaxMind support.  in /etc/nginx/nginx.conf:50

**Comment by zimmerle** [comment]
@Piju99 you need to make sure that you have GeoIP and/or MaxMind development packages in your server. Notice the summary after the execution of ```./configure```. There will be detailed info on the dependencies support.
