### ISSUE TITLE
Incorrect location for 32/64 architecture dll files.

### ISSUE THREAD

**Issue by NeoTheCapt** [SpiderLabs/ModSecurity#2294]
**Describe the bug**

Incorrect location for 32/64 architecture dll files.
Open the modules list in IIS management.
The file path for "ModSecurity IIS (64bits)" is "%SystemRoot%\System32\inetsrv\ModSecurityIIS.dll" which is actually 32bit folder.

The file path for "ModSecurity IIS (32bits)" is "%SystemRoot%\SysWOW64\inetsrv\ModSecurityIIS.dll" which is actually 64bit folder.

This issue does not cause any crash and ModSecurity is actually works well for both 32 and 64 architecture.
But when I try to modify the binary file(due to some reason), this issue makes me confused,I can not identify which dll is 64 bits dll.

**Logs and dumps**

N/A

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

Download the installer for IIS from official website.
url: https://www.modsecurity.org/tarball/2.9.3/ModSecurityIIS_2.9.3-64b.msi

A **curl** command line that mimics the original request and reproduces the problem. Or a ModSecurity v3 test case.

N/A

**Expected behavior**

N/A

**Rule Set (please complete the following information):**

N/A

**Additional context**

**Comment by zimmerle** [comment]
Here there is a brief description of what may be happening - https://stackoverflow.com/questions/949959/why-do-64-bit-dlls-go-to-system32-and-32-bit-dlls-to-syswow64-on-64-bit-windows
