### ISSUE TITLE
how can i use the lua script to control the final action?

### ISSUE THREAD

**Issue by vskunkka** [SpiderLabs/ModSecurity#2298]
**Describe the bug**
hi:
i write the secrule with a lua script as a more accurate detection,howerver, i don't know how to use the lua script to make the deny or pass action as the final action?can you help me 
the secrule is as following:

SecRule ARGS "@rx \.\.\/" "phase:2,id:113,pass,exec:/usr/local/nginx/conf/file.lua"

the lua script is as following:

local string_find = string.find
local m_getvars = m.getvars
function main()
   local get_vars = m_getvars("ARGS",{"lowercase","htmlEntityDecode"})
   for _,v in pairs(get_vars) do
        if(string_find(v.value,"/etc")) then
           return("Suspected attack in variable: " .. v.name .. ".")
        end
   end
   return nil
end

and also i find ,the function of "m.getvars" must appoint the name of the parameter ,such as 
local get_vars = m_getvars("ARGS.x",{"lowercase","htmlEntityDecode"})
only this the script can execute successfully ,and i use the version Mod3.x

**Comment by zimmerle** [comment]
The return code of yours lua script, will indicate if the disruptive action will take place or not. Another option is to use the ENV variables.
