### ISSUE TITLE
The json of auditlogs is broken the format by [] beside messages

### ISSUE THREAD

**Issue by yamazakikaede** [SpiderLabs/ModSecurity#2307]
When I use the json to output auditlogs, the ”[]“ appearing in messages causes the json parsing to fail.
you see in the log at `"messages":[{ `  
the **”[“** break the json format.

how do I remove this []. THX

log is follow here：
`{"transaction":{"client_ip":"12.24.16.9","time_stamp":"Sun May 10 10:13:40 2020","server_id":"1287d9501043e60b8fb10a1f6742211ec2b29164","client_port":0,"host_ip":"172.16.2.138","host_port":80,"unique_id":"1589076820","request":{"method":"GET","http_version":1.1,"uri":"/favicon.ico","headers":{"accept":"image/webp,image/apng,image/*,*/*;q=0.8","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36","sec-fetch-site":"same-origin","Connection":"close","sec-fetch-mode":"no-cors","referer":"https://xx.xx.xx/login?id=1%27%20select%20*%20from%20xx%20order%20by%202","X-Forwarded-For":"12.24.16.9","sec-fetch-dest":"empty","Host":"xx.xx.xx","RemoteIp":"12.24.16.9","accept-encoding":"gzip, deflate, br","accept-language":"zh-CN,zh;q=0.9"}},"response":{"body":"<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n","http_code":405,"headers":{"Server":"nginx","Date":"Sun, 10 May 2020 02:13:40 GMT","Content-Length":"552","Content-Type":"text/html","Connection":"close"}},"producer":{"modsecurity":"ModSecurity v3.0.4 (Linux)","connector":"ModSecurity-nginx v1.0.1","secrules_engine":"Enabled","components":["OWASP_CRS/3.2.0\""]},"messages":[{"message":"SQL Injection Attack Detected via libinjection","details":{"match":"detected SQLi using libinjection.","reference":"v381,78t:urlDecodeUni","ruleId":"942100","file":"/usr/local/nginx/conf/modsecurity/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf","lineNumber":"45","data":"Matched Data: sEokn found within REQUEST_HEADERS:referer: https://xx.xx.xx/login?id=1' select * from xx order by 2","severity":"2","ver":"OWASP_CRS/3.2.0","rev":"","tags":[],"maturity":"0","accuracy":"0"}}]}}`

**Comment by zimmerle** [comment]
According to the RFC 8259, that is a valid JSON. What kind of error are you getting? What is your consumer?

**Comment by yamazakikaede** [comment]
My log server can only parse the JSONObject, and from the above the log format is Object except messages.
I see the messages use JSONArray.But I want to maintain the unity of the log.
So I want to know how to make  united format to JSONObject. THX

**Comment by zimmerle** [comment]
Hi @yamazakikaede, We follow the JSON RFC. That is a perfect valid JSON Object. You can use online resources such as https://jsonformatter.curiousconcept.com/ or https://jsonformatter.org/ or even your browser console. I am afraid if we change it to support something else may impact negatively other users.

It is very likely that the implementation that you are using to read the logs is not respecting what is proposed on RFC 8259 or they have a custom JSON format, either way, that seems to be a use case scenario very close to your environment.
