### ISSUE TITLE
Where is information about supporting IIS version per ModSecurity version?

### ISSUE THREAD

**Issue by woodyu995** [SpiderLabs/ModSecurity#2308]
Hello,
Could I find information about supporting IIS version per ModSecurity version?
Where is it?
Thank you.

**Comment by martinhsv** [comment]
Hello @woodyu995 ,

I see this issue has been unresponded to for an extended period.

I'm not sure what information exactly you were looking for. Information on how to use ModSecurity for IIS is comparable to other v2.9.x versions. One version of the Reference Manual can be found here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29-%28Split%29

Information on what fixes and enhancements have occurred with each release is available in several places. You could examine the CHANGES file or check the individual releases under /tags
