### ISSUE TITLE
Quest about SecRemoteRules

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#2309]
I have many servers. Every time I update the rules, I need to upload the rule files one by one. So I want to put the rules I wrote in one server and load the rules through 'SecRemoteRules'. I tried to print the rules directly in a PHP file, but Apache failed to start, with the following error:
`/usr/local/apache/bin/apachectl: line 79:  4404 Segmentation fault               $HTTPD "$@"`

The SecRemoteRules directive is configured as follows：
`SecRemoteRules MkIe2c8pIK8AI2g5mXipvl4x https://rules.mydomain.com/getrule.php`

The contents of PHP file are as follows：
`<?php`
`print("SecRule REMOTE_ADDR \"@ipMatch 116.255.132.12\" \"id:1000,phase:1,pass,nolog,ctl:ruleEngine=Off\"");`
`?>`

To query the reason, I also installed ModSecurity in the server used to place the rules. Through the audit log, I found that the server received the access to get the rules. The audit log is as follows:
`--c320d800-A--`
`[16/May/2020:04:02:56 +0800] Xr71cJA7C@K1kZv65h2ZLAAAAMY 116.255.132.12 33278 172.21.0.15 443`
`--c320d800-B--`
`GET /getrule.php HTTP/1.1`
`User-Agent: modesecurity`
`Host: rules.mydomain.com`
`Accept: */*`
`ModSec-unique-id: e781ee72979d16cd91ed89c716dc087f195d7cb8`
`ModSec-status: 2.9.3,(null),1.5.2/1.5.2,8.43/8.43 2019-02-23,Lua 5.1,2.9.9,e781ee72979d16cd91ed89c716dc087f195d7cb8`
`ModSec-key: MkIe2c8pIK8AI2g5mXipvl4x`
`--c320d800-F--`
`HTTP/1.1 200 OK`
`Upgrade: h2`
`Connection: Upgrade, close`
`Vary: Accept-Encoding`
`Content-Length: 92`
`Content-Type: text/html; charset=UTF-8`
`--c320d800-E--`
`SecRule REMOTE_ADDR "@ipMatch 116.255.132.12" "id:1000,phase:1,pass,nolog,ctl:ruleEngine=Off"`
`--c320d800-H--`
`Apache-Handler: proxy:unix:/tmp/php-cgi-56.sock|fcgi://localhost`
`Stopwatch: 1589572976792227 3103 (- - -)`
`Stopwatch2: 1589572976792227 3103; combined=1871, p1=785, p2=721, p3=59, p4=196, p5=109, sr=133, sw=1, l=0, gc=0`
`Response-Body-Transformed: Dechunked`
`Producer: ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/); OWASP_CRS/3.2.0.`
`Server: Apache`
`Engine-Mode: "ENABLED"`
`--c320d800-Z--`

Is the way I return rules to the server wrong?

At the same time, I found an error. The value of user agent should be 'modsecurity', but according to the log, the value of user agent is 'modesecurity', with an extra letter of E.

Thank you for your response.

**Comment by zimmerle** [comment]
Hi @prince-java,

Yes, you can use the SecRemoteRules for that. There are a couple of regression tests that you may be interested in looking: 
 - [SecRemoteRules](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/tests/regression/misc/40-secRemoteRules.t.in)
 - [IpMatch](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/tests/regression/misc/50-ipmatchfromfile-external.t.in)
 - [pm](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/tests/regression/misc/60-pmfromfile-external.t.in)

Some of the tests are using resources from modsecurity.org. As example:
https://www.modsecurity.org/modsecurity-regression-test-secremoterules.txt
