### ISSUE TITLE
Let's Encrypt SSL certificate generation - 403 Forbidden

### ISSUE THREAD

**Issue by ShopixRo** [SpiderLabs/ModSecurity#2310]
**Describe the bug**
SSL certificate generation using Let's Encrypt result in 403 Forbidden error.

**Logs and dumps**
```
Output of modsec_audit.log

--dde07d07-A--
[18/May/2020:16:27:44 +0300] XsKNUBSLv@CtAoRchMQbWwAAAAU <<IP>> 54146 <<IP>> 80
--dde07d07-B--
GET /.well-known/acme-challenge/g0xtVr2JZjrCGgaXXH1xC8Fp-EXRRdiEAdL3Cm9B3QA HTTP/1.1
Accept-Encoding: identity
Host: autoconfig.domain.tld
Content-Type: application/jose+json
Connection: close
User-Agent: acme-tiny

--dde07d07-F--
HTTP/1.1 403 Forbidden
Content-Length: 272
Connection: close
Content-Type: text/html; charset=iso-8859-1

--dde07d07-E--

--dde07d07-H--
Message: Access denied with code 403 (phase 2). Operator EQ matched 0 at REQUEST_HEADERS. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_21_protocol_anomalies.conf"] [line "47"] [id "960015"] [rev "1"] [msg "Request Missing an Accept Header"] [severity "NOTICE"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"]
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client <<IP>>] ModSecurity: Access denied with code 403 (phase 2). Operator EQ matched 0 at REQUEST_HEADERS. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_21_protocol_anomalies.conf"] [line "47"] [id "960015"] [rev "1"] [msg "Request Missing an Accept Header"] [severity "NOTICE"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "autoconfig.domain.tld"] [uri "/.well-known/acme-challenge/g0xtVr2JZjrCGgaXXH1xC8Fp-EXRRdiEAdL3Cm9B3QA"] [unique_id "XsKNUBSLv@CtAoRchMQbWwAAAAU"]
Action: Intercepted (phase 2)
Stopwatch: 1589808464029236 20211 (- - -)
Stopwatch2: 1589808464029236 20211; combined=2753, p1=1779, p2=877, p3=0, p4=0, p5=97, sr=484, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.4.6
Engine-Mode: "ENABLED"

--dde07d07-Z--
```

**Expected behavior**
SSL certificate generation should be successful as it is when disabling mod security.

**Server (please complete the following information):**
- ModSecurity 2.9.2
- Apache/2.4.6
 - CentOS 7.8

**Rule Set**
- CRS ruleset only

**Comment by zimmerle** [comment]
Hi @ShopixRo,

What you meant by ModSecurity disabled? It seems like it is still enabled and the rule id 960015 blocked your request.

**Comment by ShopixRo** [comment]
Hi @zimmerle 

If I disable ModSecurity everything works fine. But the problem is that with ModSecurity enabled, SSL certificate generation with Let's Encrypt fails.

Is this the normal behavior? Shouldn't ModSecurity allow for Let's Encrypt access?
If this is the expected behavior, how can it be bypassed so we can generate the certificates?

Thanks!

**Comment by zimmerle** [comment]
@ShopixRo, that is likely to be a false positive. However, there are two different entities: **ModSecurity** and **the Rule Set**. **ModSecurity** is the engine, that is what this GitHub project is about.

It seems that you are running OWASP CRS as Rule Set, in that case, you should reach them at https://github.com/coreruleset/coreruleset

**Comment by ShopixRo** [comment]
@zimmerle Thanks for the clarification, now I understand what you mean. Are there any official Rule Set that I can install? I believe having ModSecurity without any Rule Set is useless, right?

**Comment by zimmerle** [comment]
> @zimmerle Thanks for the clarification, now I understand what you mean. Are there any official Rule Set that I can install? I believe having ModSecurity without any Rule Set is useless, right?

There are different options on that front: You can create _our own ruleset_ based on your specifics needs, use a _commercial ruleset_, or even use an _open-source_ one.

The commercial ones: [Trustwave](https://certs.securetrust.com/web-application-firewall), [Atomiccorp](https://wiki.atomicorp.com/wiki/index.php/Atomic_ModSecurity_Rules_FAQ).

The public ones: [Comodo](https://waf.comodo.com/) and [OWASP CRS](https://github.com/coreruleset/coreruleset)

Those are the ones a the top of my head.
