### ISSUE TITLE
v2 master doesn't compile in CentOS 8

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#2312]
The following declarations appear in modsecurity.h:
```
static char auditlog_lock_name[L_tmpnam];
static char geo_lock_name[L_tmpnam];
#ifdef GLOBAL_COLLECTION_LOCK
static char dbm_lock_name[L_tmpnam];
#endif
```
These static variables are only used inside modsecurity.c, so they should be declared inside modsecurity.c, and not in an include file.

On CentOS 8, gcc (8.3.1) refuses to compile the file:
```
modsecurity.c:136:12: error: ‘auditlog_lock_name’ undeclared (first use in this function); did you mean ‘apr_os_sock_make’?
     tmpnam(auditlog_lock_name);
            ^~~~~~~~~~~~~~~~~~
            apr_os_sock_make
modsecurity.c:136:12: note: each undeclared identifier is reported only once for each function it appears in
modsecurity.c:158:12: error: ‘geo_lock_name’ undeclared (first use in this function); did you mean ‘getsockname’?
     tmpnam(geo_lock_name);
            ^~~~~~~~~~~~~
            getsockname
```

Moving the definitions to modsecurity.c solves the problem

**Comment by Hello-Linux** [comment]
孙子,你的环境有问题,自己仔细看看

**Comment by zimmerle** [comment]
Is this a standalone version or that is a regular version for Apache? Why have you used ```--enable-collection-global-lock``` during the configuration phase?

**Comment by marcstern** [comment]
Regular version for Apache.
I didn't use --enable-collection-global-lock; I added dbm_lock_name in the scope because it has the same problem as the 2 other variables, although I don't use it actually.

**Comment by zimmerle** [comment]
I am afraid I am not following it up. What variables are you referring to and what are their problems?

Regarding that specific feature it seems like you are by-passing the build script and have put the build in an inconsistent state, leading to the error message that you have faced. My concern is that: if I manage to apply this "fix" that works in your use case scenario, it will break the build for the ones, who actually are using the build scripts (e.g. all distributions that are delivering ModSecurity to their users).

Could you please share the motivation that you have had, to enable the global collection lock in an Apache build?

**Comment by marcstern** [comment]
I didn't enable the global collection lock, so only the first 2 variables (auditlog_lock_name & geo_lock_name) are actually posing problems. Just ignore my remark about dbm_lock_name is you prefer, as GLOBAL_COLLECTION_LOCK is not defined.

I tested my fix under Linux (CentOS 8) with the build script and it works.

**Comment by zimmerle** [comment]
@marcstern the compilation of ModSecurity version 2 is **working fine** with **CentOS 8** as demonstrated:
![2312](https://user-images.githubusercontent.com/428268/83906498-11fdaa00-a73a-11ea-8678-d7845ab81e8a.gif)



The steps to compile ModSecurity version 2 on CentOS is very straight forward:
```
yum group install "Development Tools"
yum install httpd-devel pcre-devel libxml2-devel
git clone --single-branch --branch v2/master https://github.com/SpiderLabs/ModSecurity.git
cd ModSecurity
./autogen.sh && ./configure && make -j20 && make check
```

Closing this issue as the compilation is working fine, as demonstrated.

**Comment by marcstern** [comment]
I imagine some default compile options are different (like optimization-related ones) and that leads to the problem. The declaration is at the wrong place anyway. It's, inthe best case, a bad practice.

**Comment by zimmerle** [comment]
> I imagine some default compile options are different (like optimization-related ones) and that leads to the problem. The declaration is at the wrong place anyway. It's, inthe best case, a bad practice.

I agree with the static analysis utility: the declaration is not following the best practice. However, this particular declaration is not causing compilation to broken or any further issue, as demonstrated in the video posted at https://github.com/SpiderLabs/ModSecurity/issues/2312#issuecomment-639658190.

If the compilation is not working for you, please do paste the error so we can start a debug process.

**Comment by marcstern** [comment]
I already pasted the error.
I retried with the latest updates and the problem doesn't appear anymore.
Hoping it won't come back some time ...
