### ISSUE TITLE
SecRemoteRules doesn't work

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/ModSecurity#2314]
Thank you for reminding me to find out how to use SecRemoteRules in [SecRemoteRules](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/tests/regression/misc/40-secRemoteRules.t.in),but I write the following rule into modsecurity.conf by running with Nginx and Apache,both failed.
`SecRemoteRules 123 "https://www.modsecurity.org/modsecurity-regression-test-secremoterules.txt"`

No error is reported when Nginx starts,but the log shows that the number of rules downloaded is zero:
`2020/05/20 03:38:50 [notice] 331#0: ModSecurity-nginx v1.0.1 (rules loaded inline/local/remote: 0/901/0)`

Apache failed to start, with the following error:
`/usr/local/apache/bin/apachectl: line 79: 4404 Segmentation fault $HTTPD "$@"`

I appreciate and need your help.

**Comment by zimmerle** [comment]
nginx: To counter on your Nginx load may be broken. Make sure that the rule is really loaded.

apache: The segmentation fault is very likely something related to a version mismatch. If you have compiled your ModSecurity or Apache manually, make sure that all versions: run time and compilation time are the same. 

Both Nginx and Apache have support for regression and unit tests. Are those passing?

**Comment by prince-java** [comment]
I‘m sure the local rules are loaded successfully when nginx start,I tried an intrusion and was successfully intercepted by ModSecurity.

**Comment by zimmerle** [comment]
> I‘m sure the local rules are loaded successfully when Nginx start,I tried an intrusion and was successfully intercepted by ModSecurity.

Good, so the issue is really the counter. Going to open an issue related to that.

**Comment by prince-java** [comment]
The counter isn't the issue,I solved the problem after attempts.
The reason is that quotes cannot be used for remote rule file when the rule is wrote into modsecurity.conf,the correct rule is as follows:
`SecRemoteRules 123 https://www.modsecurity.org/modsecurity-regression-test-secremoterules.txt`

After that,the number of rules loaded when nginx starts has changed from 901 to 902.

I will try it with apache later.
Thank you for help!

**Comment by prince-java** [comment]
@zimmerle 
After attempts,I find out that SecRemoteRules really doesn't work in ModSecurity 2.9.3,apache always failed to start,but it works in 2.9.2.
The softwares and environment I installed are as follows:
`yum install -y perl-devel readline-devel curl-devel gcc gcc-c++ python-devel yajl-devel libxml2-devel`
System:CentOS 7.6_64;
apr:1.5.2;
apr-util:1.5.4;
pcre:8.43;
Apache:2.4.41;

I will try SecRemoteRules in ModSecurity 2.9.3 with nginx later to find out whether it work or not.
I hope my attempts can help you.
