### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by nikolas** [SpiderLabs/ModSecurity#2318]
Hi,
I wasn't sure where to open this issue, but the ModSecurity website has some problems I'd like to help fix.

The info on this page: https://modsecurity.org/download.html in the "ModSecurity for Nginx" section, seems out of date. I've got ModSecurity working with nginx, without the `enable-standalone-module` configure flag. Also, the note about the nginx_refactoring branch can be removed - that branch is from 2014 and it seems the ModSecurity is now compatible with nginx, with the move to libmodsecurity, and decoupling from apache.

**Comment by zimmerle** [comment]
Thank you @nikolas. Indeed the website needs to be updated. Although that is not the better place to keep it, I will keep this issue open as a reminder that as a community we have to have some sort of landing page.

**Comment by martinhsv** [comment]
The out-of-date page referenced in this item was removed entirely (more than a year ago, I believe).

Closing ...
