### ISSUE TITLE
Modsecurity chain rule bug!!!

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2319]
Please look at my old question first: https://github.com/SpiderLabs/ModSecurity/issues/2311

I think is modsecurity some bug? In addition, I have not changed other rule files, only modified REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf

Now I found a modsecurity bug. If I use regular to match all rule files, like this
```
/usr/local/openresty/nginx/conf/modsecurity/owasp-modsecurity-crs/rules/*.conf
```
then I  run nginx -t is error
```
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/openresty/nginx/conf/modsecurity/owasp-modsecurity-crs/rules/REQUEST-901-INITIALIZATION.conf. Line: 1. Column: 75. Expecting an action, got:  # ------------------------------------------------------------------------ in /usr/local/openresty/nginx/conf/vhosts/cswww.conf:5
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
```
But  if I put each rule configuration file separately in modsecurity.conf,like this
![2020-05-21 10-53-48 的屏幕截图](https://user-images.githubusercontent.com/17851645/82518198-622d1780-9b51-11ea-97e2-08c4ec091adb.png)
 Then run nginx  -t is ok !
```
nginx: the configuration file /usr/local/openresty/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test is successful
```
Why????All my configuration is no problem

**Comment by zimmerle** [comment]
Closing this on the favor of SpiderLabs/ModSecurity#2311
