### ISSUE TITLE
the rule is not working

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2320]
my audit log is 
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Rx' with parameter `^(?i:file|ftps?|https?):\/\/(?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' against variable `ARGS:url' (Value: `http://127.0.0.1:8071/EliteGeneralHttpTask/GeneralService/Call_PolicySave' ) [file "/usr/local/openresty/nginx/conf/modsecurity/owasp-modsecurity-crs/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf"] [line "36"] [id "931100"] [rev ""] [msg "Possible Remote File Inclusion (RFI) Attack: URL Parameter usingIP Address"] [data "Matched Data: http://127.0.0.1 found within ARGS:url: http://127.0.0.1:8071/EliteGeneralHttpTask/GeneralService/Call_PolicySave"] [severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag"language-multi"] [tag "platform-multi"] [tag "attack-rfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "OWASP_CRS/WEB_ATTACK/RFI"] [hostname "192.168.30.50"] [uri "/commons/xhr/post"] [unique_id "1590036705"] [ref "o0,16v897,73"]

the I add whitelist rule to REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf file the rule is
```
SecRule REQUEST_URI "@beginsWith /commons/xhr/post" "id:1000,phase:1,pass,nolog,chain"
    SecRule ARGS:url "@rx ^(?i:file|ftps?|https?):\/\/(?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})" "t:none,ctl:ruleRemoveById=931100"
```
But no effect, the request is still intercepted! why?

**Comment by martinhsv** [comment]
Hi @Hello-Linux ,

I don't see anything that is actually incorrect in rule 1000 the way you have it.  Indeed, I tried it in one of my test environments and it worked just fine and removed rule 931100 for that request.

One important caveat to note is that yours is a phase 1 rule testing ARGS.  This is fine if 'url' is a query argument.  But if it appears in the body of the request, then rule 1000 does not have access to it.

One suggestion in terms of strategy with this type of whitelisting rule:  You could try something like using a non-chained rule with REQUEST_URI and have as one of its actions 'ctl:ruleRemoveTargetById=931100;ARGS:url'.  This would give you the whitelisting functionality that you're looking for, while also handling the case where url is in the body, and also reduce a method for a hacker to bypass a detection (i.e. your existing rule 1000 will stop rule 931100 from detecting the suspicious pattern in other parts the request if the 'url' has it).
