### ISSUE TITLE
-DDEBUG_CONF leads to compile error

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#2323]
In re.c, msre_actionset_generate_action_string is declared as static.
When compiling with DEBUG_CONF, it is referenced in apache2_config.c.

Fix: don't declare it as static and and the prototype in re.h.
Potentially do it only when DEBUG_CONF  is defined.

re.h:
```
#ifdef DEBUG_CONF
 char DSOLOCAL* msre_actionset_generate_action_string(apr_pool_t* pool, const msre_actionset* actionset);
#endif

```

re.c:
```
#ifndef DEBUG_CONF
 static 
#endif
char *msre_actionset_generate_action_string(...
```

**Comment by zimmerle** [comment]
That seems to be more suitable for a pull request than a regular issue. A pull request will help others users to apply this fix easily and be better for the review process.

**Comment by zimmerle** [comment]
I am assuming that **this issue** as issue #2312 is a problem with your environment. My suggestion is to clean up the development environment. The ``--enable-debug-conf`` works like a charm here. Compilation and tests went well.

**Comment by marcstern** [comment]
This is definitely not a problem with my environment. The code is invalid: it's declared as a global function, then it's defined as static. It's against the C standard and some compilers(correctly)  choke on this (i.e. Microsoft Visual C++).

**Comment by zimmerle** [comment]
ModSecurity for IIS is compiled using Visual Studio. Same for ModSecurity for Apache/Win. The compilation is working fine. It will be a pleasure to assist you if you can provide the associated error message.

The scripts for windows compilation are on the repository, in case you want to give it a try.

**Comment by marcstern** [comment]
If you define -DDEBUG_CONF when compiling Apache/Win, you get that result:
2>apache2_config.obj : error LNK2019: unresolved external symbol msre_actionset_generate_action_string referenced in function update_rule_action
2>C:\Cache\httpd-Debug\modules\mod_security2.so : fatal error LNK1120: 1 unresolved externals

This error disappears by applying the fix above.
