### ISSUE TITLE
libmodsecurity api issue

### ISSUE THREAD

**Issue by Magicskys** [SpiderLabs/ModSecurity#2327]
**Describe the bug**
When I was using libmodsecurity v3 c api, I didn't find any documentation on this aspect. May I ask if there is an api to get the detection result synchronously, or documentation on this aspect.

**Expected behavior**

I hope there is documentation in this regard, or tell me the api function of synchronous or asynchronous callback.

**Server (please complete the following information):**
 - ModSecurity version (and connector): ModSecurity v3.0.4
 - OS (and distro): Centos7

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? OWASP modsecurity
 - What is the version number? latest

**Comment by zimmerle** [comment]
Hi @Magicskys,

The API documentation is built along with the code. You can use [Doxygen](https://www.doxygen.nl/index.html) to transform it into whatever feels more comfortable to you.

Here is an example of a piece of documentation:
https://github.com/SpiderLabs/ModSecurity/blob/a2be19d8e53f4d2d90d435e187086afa2396c373/headers/modsecurity/modsecurity.h#L18-L57

The C API is just a wrapper for the C++, the same documentation is valid for both, the specificities are noted on the C wrapper.

Atop of the documentation, there are some examples on the examples folder:
- [multiprocess_c](https://github.com/SpiderLabs/ModSecurity/tree/v3/master/examples/multiprocess_c)
- [simple_example_using_c](https://github.com/SpiderLabs/ModSecurity/tree/v3/master/examples/simple_example_using_c)
- [using_bodies_in_chunks](https://github.com/SpiderLabs/ModSecurity/tree/v3/master/examples/using_bodies_in_chunks)

More: [examples](https://github.com/SpiderLabs/ModSecurity/tree/v3/master/examples)
