### ISSUE TITLE
Reverse Proxy Setup

### ISSUE THREAD

**Issue by zeroploitable** [SpiderLabs/ModSecurity#2333]
Hi,

I have installed and tested modsecurity and everything is working fine.
I just to configure the reverse proxy in order to inspect and redirect the traffic comming from my website to the hosting server.

Please let me know how?
Thank you.

**Comment by martinhsv** [comment]
Hi @zeroploitable ,

I'm not entirely sure what you are asking.

With a ModSecurity RP setup, a Client connection typically proceeds something like this:
Client --> Machine#1: RP (with ModSec) --> Machine#2: Web Server

If, for example, you are using Apache HTTP Server and you are saying that you have successfully set up Machine#1 as if it were the server sendpoint, and with ModSecurity running ... and now you're wondering how to instead have that (non-blocked) traffic flow the Machine#2 ...

In that case, you're really asking more of web server question.

But, if again by example you are using Apache HTTP Server, mod_proxy is the key thing you're looking for.  One site with some simple instructions is here:

https://www.techrepublic.com/article/how-to-setup-a-reverse-proxy-on-ubuntu-server-18-04/
(note especially the a2enmod lines and the ProxyPass and ProxyPassReverse lines for the .conf file)

And more complete documentation can be found here:
https://httpd.apache.org/docs/2.4/mod/mod_proxy.html

**Comment by zeroploitable** [comment]
Hi @martinhsv,

This is what i was looking for !
Thank you so much.
