### ISSUE TITLE
Modsecurity GUI

### ISSUE THREAD

**Issue by zeroploitable** [SpiderLabs/ModSecurity#2339]
Hi,

I am having difficulties in handling the logs of several websites behind Modsecurity.

Maybe a better way of visualizing attacks, is there any GUI interface that can be added? 
 
Thank you.

**Comment by zimmerle** [comment]
Hi @zeroploitable,

As the auditlog can be saved in JSON format, you can easily import it in our logging tool: Logstash, Grafana, influxdb, and any tool that can handle JSON data.
