### ISSUE TITLE
SQL Injection rule flags up contact forms with A tags

### ISSUE THREAD

**Issue by ragudesign** [SpiderLabs/ModSecurity#2343]
Hello

For our WordPress sites, we use Gravity forms as a plugin.

The form includes a user consent checkbox, we link the privacy policy to the relevant page using an 'a href' tag. Now for whatever reason, Gravity form makes the value of the field the same as the label. For example:

`<input type="hidden" name="input_9.2" value="I consent to xxxx holding and retaining my personal details as described in the <a href=" class="gform_hidden" privacy-cookies-policy="">`

This triggers the  942100: SQL Injection Attack Detected via libinjection rule and returns a 403 when submitting. However, if i was to amend the 'a' href' tag and include 'target="_blank"', the form submits perfectly without returning 403 and triggering the rule.

Ruleset Version: V3.0 
Platform: cPanel/WHM
OS: centOS 7.8
Webserver: LiteSpeed 5.4.7

From experimenting around, you can add A tags within inputs, however, they need to have target="blank" to not trigger the rule. We have over 80 sites so if there was a server-sided solution apart from turning the rule off, that'd be really helpful!

Kind Regards.

**Comment by martinhsv** [comment]
Hi @ragudesign ,

Typically the strategy in such cases is to turn off the rule causing false positives ... but turn it off as selectively as possible.

There are a couple of different ways to do this, but one common one is to create a separate rule whose only purpose is to turn off the rule that is causing FPs.

In your case, suppose you know that the relevant args all have a name beginning with 'gravity_', and the ones causing FPs always have values that start as you describe ("<input"), you could then do something like this:
```
SecRule ARGS:'/^gravity_/' "@rx ^<input" "id:1216,phase:2,log,pass,ctl:ruleRemoveById=942100"
```

How you specify such a rule can vary depending on what information you have to distinguish these FP-causing requests. (E.g. test the url?  test a larger portion of argument value?)

If you are using CRS (and I assume you are given your reference to 942100), there are examples of ctl:ruleRemoveById in some of those rule files.

**Comment by ragudesign** [comment]
Hi @martinhsv 

So sorry for the late response.

Thanks a lot for looking into this, I'll take your example and amend as I see fit!

Thanks again and enjoy your weekend :D

Kind Regards.
