### ISSUE TITLE
Help /Read me is not updated for new verion!

### ISSUE THREAD

**Issue by HadiAbbasi** [SpiderLabs/ModSecurity#2346]
I have tried to run my old nodejs A-NPI code which was connected to and used c++ modsc 3.0 lib, and also I have updated my modsec lib to latest version but I think there are some changes in libraries, but I can't find any document or example to solve my problems!
I wanna call this method:
         _rules->m_parserError.str() in below line
	Napi::Error::New(env, _rules->m_parserError.str()).ThrowAsJavaScriptException();
but the error is this:
	 error: ‘class modsecurity::Rules’ has no member named ‘m_parserError’

also I wanna load rule file using:
	int res = _rules->loadFromUri(rulePath);
but it has below error result:
	error: ‘class modsecurity::Rules’ has no member named ‘loadFromUri’
	
and also this line:
	_transaction = new modsecurity::Transaction(_modsec, _rules , NULL);

has an error:
	 error: no matching function for call to ‘modsecurity::Transaction::Transaction(modsecurity::ModSecurity*&, modsecurity::Rules*&, NULL)’
 _transaction = new modsecurity::Transaction(_modsec, _rules , NULL);
 
 I could't find  any updated documents  or examples  about new ModSec Lib structure.

**Comment by zimmerle** [comment]
Hi @HadiAbbasi,

The class **Rules** was renamed to **RulesSet**, that seems to be the kernel of the issues that you are facing. 

That is the new home for loadFromUri:
https://github.com/SpiderLabs/ModSecurity/blob/7e0bc2691727b8c75f74638cdc4d1c45a689a7b6/src/rules_set.cc#L35-L50

For a full example, you may want to look here:
https://github.com/SpiderLabs/ModSecurity/blob/b7e28c246f35a0a4f5f3594d8799e9a26d66f3a7/examples/using_bodies_in_chunks/simple_request.cc#L1-L279
