### ISSUE TITLE
Modsecurity periodically generate warning in SecAction "initcol"

### ISSUE THREAD

**Issue by unix196** [SpiderLabs/ModSecurity#2347]
**Describe the bug**

We try use modescurity by a little on our servers. We enable it on some servers on some virtualhosts with small load - all OK. Then I enable modsecurity on other server with with a greater load and begin receive warnings in nginx log file:
```
my.test.ru/error.log:12290:2020/06/22 13:35:30 [info] 6902#0: *11796330 ModSecurity: Warning.  [file "/home/modsecurity/config/main.conf"] [line "6"] [id "5"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "1.1.1.1"] [uri "/"] [unique_id "159282213087.094353"] [ref ""], client: 1.1.1.1, server: my.test.ru, request: "GET / HTTP/1.1", host: "my.test.ru"
```
This messages are repeated in log file
```
grep -rni "ModSecurity: Warning" /home/nginx/*/logs/error.log | wc -l
108480
```

In my modsecurity config line 6:
```
SecAction "initcol:ip=%{REMOTE_ADDR},id:5,pass,phase:1"
```
Modsecurity module is working (blocking bad ip), but periodically generate this  warning messages.

**Logs and dumps**

server version: `Debian GNU/Linux 9.12 (stretch)`

Nginx version: `nginx -V` - https://pastebin.com/ruisbGvR

Modsecurity version (build as debian package):
```
dpkg -l | grep modsec
ii  modsecurity                      3.0.4-1~stretch                                       amd64        Open Source Web Application Firewall 
```

`ldd  /usr/local/modsecurity/lib/libmodsecurity.so`  - https://pastebin.com/A19iysq5
Module was build with LMDB support (https://github.com/SpiderLabs/ModSecurity/issues/2262)

Modsecurity logs looks like good (logs when generated warning message in nginx log):
https://pastebin.com/VHzcB7LD
https://pastebin.com/aw9exY9r

What exactly  blocking rules of modsec are doing: if bad ip try send 3 bad attempts (with bad url), then this ip is block.
```
cat -n /home/modsecurity/config/main.conf  | less
6  SecAction "initcol:ip=%{REMOTE_ADDR},id:5,pass,phase:1"
...
SecRule REQUEST_FILENAME \
    46  "@rx (\.asp|\.aspx|\.cgi|\.cfg|\.jspa|\.jsp|\.ashx|sqlitemanager/main\.php|agsearch/sqlite/main\.php)$" \
    47   "id:80,t:lowercase,phase:1,pass,chain"
    48      SecRule &ip:allowed "@eq 0" \
    49      "id:100,phase:1,setvar:ip.bad_attempts=+1,\
    50      setvar:'ip.attempts_flag_expire_timestamp=%{TIME_EPOCH}',\
    51      setvar:'ip.attempts_flag_expire_timestamp=+86400', \
    52      setvar:ip.real_ip=%{remote_addr}"
... 
    56  SecRule ip:bad_attempts "@ge 3" "id:'200',phase:1,pass,nolog,setvar:ip.block_flag=1"
    57  SecRule ip:block_flag "@eq 1" "id:500,phase:1,drop,log,logdata:'Blacklist ip.block_flag - %{ip.block_flag}, real_ip - %{ip.real_ip}'"

```
as if it looks like this, that sometimes modsecurity cannot initialize ip collection (but these are just my thoughts). I repeat - modsecurity is working (it block bad ip),  but a little confused this warning messages in nginx log file (on other servers with enabled modsec this warnings are absent). What can they mean?

**To Reproduce**

Build modsecurity with LMDB support, send on nginx some load (r/s), write rule which will block ip.

**Comment by martinhsv** [comment]
Hi @unix196 ,

I don't believe this had anything to do with initcol specifically; it was more of a general pattern 

While what you describe did happen in v3.0.4, it had already been changed around 3 months before you posted this. And of course, it would not occur with v3.0.5 or v3.0.6.
