### ISSUE TITLE
Portability issue: == in configure shell script

### ISSUE THREAD

**Issue by jbarfield** [SpiderLabs/ModSecurity#2350]
**Describe the bug**

**The configure shell script has a portability issue with the '==' operator when attempting to build from source.** 

The "test" command, as well as the "[" command, are not required to know
the "==" operator. Only a few implementations like bash and some
versions of ksh support it.

When you run "test foo == foo" on a platform that does not support the
"==" operator, the result will be "false" instead of "true". This can
lead to unexpected behavior.

**Logs and dumps**

NA

**To Reproduce**

cd ${WRKSRC}; grep == ./configure

**Expected behavior**

Expect configure and other shell scripts to use the '=' operator for portability to a wide variety of platforms. 

**Server (please complete the following information):**
 - ModSecurity v3.0.4
 - NA
 - illumos, SmartOS joyent_20200326T183047Z,
- Package Manager: pkgsrc

**Rule Set (please complete the following information):**
NA

**Additional context**

This is a portability only bug report for building from source

**Comment by zimmerle** [comment]
@jbarfield

The _configure script_ is automatically generated as the result of [autogen tools](https://www.gnu.org/software/autogen/) and [automake](https://www.gnu.org/software/automake/). Among of other things the build scripts make usage of a set of m4 scripts on the [build folder](https://github.com/SpiderLabs/ModSecurity/tree/v3/master/build) as foment.



One can generate the _configure_ script, by running the bulid.sh -
``` 
./build.sh
``` 
 Or even: 

https://github.com/SpiderLabs/ModSecurity/blob/0eb3c123f447b8787ea726ad4d4439018a07ee31/build.sh#L1-L11


Have said that, do we happens to have those issues issues on the auto-generated code? I have notice the existence of ```==``` on the m4 scripts, but i think it translates to marking an existent dependency as not existent, therefore expected deterministic behavior.

**Comment by jbarfield** [comment]
I am building the package automatically with pkgsrc. I wonder if I just tell pkgsrc to delete the configure script if it will regenerate automatically using automake autoconf,etc, just like the build script is doing. Ill test this and see.
