### ISSUE TITLE
SecRuleUpdateTargetById does not work with multiple target and range id

### ISSUE THREAD

**Issue by anhkhoa14592** [SpiderLabs/ModSecurity#2355]
Hi, 
While testing Modsecurity, I found some bugs relating to SecRuleUpdateTargetById . 

**Describe the bug**
I has 2 rules:
```
SecRule ARGS "100" "id:100,deny,phase:2"
SecRule ARGS "200" "id:200,deny,phase:2"
```

1. Case 1: SecRuleUpdateTargetById does not work with multiple target 

**Exception Rules**
```
SecRuleUpdateTargetById 100 "!ARGS:/^x$/,!ARGS:/^y$/"
```
**Request and output**
```
http://modsec.demo.com/?x=100 (Allowed)
==> parameter x is ignored

http://modsec.demo.com/?y=100 (Blocked)
==>parameter y is still blocked
```

2. Case 2: SecRuleUpdateTargetById does not work without regular
**Exception Rules**
```
SecRuleUpdateTargetById 100 "!ARGS:x,!ARGS:y"
SecRuleUpdateTargetById 200 "!ARGS:x"
```

**Request and output**
```
http://modsec.demo.com/?x=100 (Blocked)
http://modsec.demo.com/?y=100 (Blocked)
==> Parameter x and y still blocked. 

http://modsec.demo.com/?x=200 (Blocked)
==> Parameter x still blocked. 
```

**Additional Note:** Looks like SecRuleUpdateTargetById works only with regular

3. Case 3: Range id does not work as expected
**Exception Rules**
```
SecRuleUpdateTargetById 100-200  "!ARGS:/^x$/"
```
**Request and output**
```
http://modsec.demo.com/?x=100 (Allowed)
http://modsec.demo.com/?x=200 (Blocked)
==> Rule Id 100 is ignored. Rule id 200 still works.
```

4. Case 4: SecRuleUpdateTargetById does not support group in regx
**Exception Rules**
```
SecRuleUpdateTargetById 100 "!ARGS:/^(x|y)$/"
```
**Request and output**
```
==> Show error: ** Expecting a variable, got:  :  y)$/"**
```

**Logs and dumps**

**Error log in Case 4:**
`nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /xxx/xxx/modsec.demo.com.conf. Line: 4. Column: 46. Expecting a variable, got:  :  y)$/" in /xxx/xxx/modsec.demo.com.conf:20`

**Server (please complete the following information):**
 - ModSecurity version (and connector): ModSecurity v3.0.4 with ModSecurity-nginx v1.0.1
 - WebServer: nginx/1.18.0
 - OS (and distro): Centos 7

**Additional Notes**
I've tried to add these exceptions rule before and after SecRule id 100, 200 but all of them does not work.

**Comment by martinhsv** [comment]
Hi @anhkhoa14592 ,

1) SecRuleUpdateTargetById does not work with multiple target
Aren't you using the wrong format?  target items are separated by '|' . Try
"!ARGS:/^x$/|!ARGS:/^y$/"

2) SecRuleUpdateTargetById does not work without regular
There was a bug to that effect that has been fixed.  See https://github.com/SpiderLabs/ModSecurity/issues/2251

3) Range id does not work as expected
This is a known issue duplicating https://github.com/SpiderLabs/ModSecurity/issues/2110

4) SecRuleUpdateTargetById does not support group in regx
Certain regex metacharacters necessitate encapsulating in single quotes like this:
SecRuleUpdateTargetById 100 "!ARGS:'/^(x|y)$/'"

**Comment by anhkhoa14592** [comment]
hi @martinhsv ,

Thanks you for your help. In the case 1, I follow the document in https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecRuleUpdateTargetById. 
Anyway, I've tried the new rule as your suggestion and it work perfectly. It help me a lot.

I have another question relating to performance. Should I combine many SecRules into 1 line or separate them? Which one is better performance? 
Exp:
**Case 1:**
SecRuleUpdateTargetById 100 "!ARGS:/^x$/|!ARGS:/^y$|!ARGS:/^z$/"
**Case 2**
SecRuleUpdateTargetById 100 "!ARGS:/^x$/"
SecRuleUpdateTargetById 100 "!ARGS:/^y$/"
SecRuleUpdateTargetById 100 "!ARGS:/^z$/"
Or 
**Case 1:**
SecRuleRemoveById 100 200 300
**Case 2**
SecRuleUpdateTargetById 100
SecRuleUpdateTargetById 200
SecRuleUpdateTargetById 300

Thanks you

**Comment by martinhsv** [comment]
Hi @anhkhoa14592 ,

In neither case is one choice likely to be particularly more performant.

Cheers.

**Comment by kinekt4** [comment]
I was going to create a new issue to report on "Case 4". Luckily I found it here.

> Case 4: SecRuleUpdateTargetById does not support group in regx Exception Rules:
> SecRuleUpdateTargetById 100 "!ARGS:/^(x|y)$/"

Of which the solution is:

> SecRuleUpdateTargetById does not support group in regx
> Certain regex metacharacters necessitate encapsulating in single quotes like this:
> SecRuleUpdateTargetById 100 "!ARGS:'/^(x|y)$/'"

Can this be added to the documentation please. Thanks

[Reference Manual - v3.29](wiki/Reference-Manual-%28v3.x%29)

**Comment by airween** [comment]
hi @kinekt4,

> Can this be added to the documentation please. Thanks
> 
> [Reference Manual - v3.29](wiki/Reference-Manual-%28v3.x%29)

Thanks, it's done - please take a [look](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v3.x)#secruleupdatetargetbyid).
