### ISSUE TITLE
Error 1722 on Repair/Uninstall ModSecurityIIS_2.9.3-64b for IIS

### ISSUE THREAD

**Issue by mmojadad** [SpiderLabs/ModSecurity#2356]
Windows 2016
IIS 10
ModSecurityIIS_2.9.3-64b
Visual Studio 2013 Runtime (vcredist) installed
-----------------
When i try uninstall/repair ModSecurity 2.9.3 for IIS, the following error is displayed:
![photo_2020-07-13_01-37-43](https://user-images.githubusercontent.com/13836821/87256683-19874000-c4aa-11ea-85de-db4d9b312761.jpg)
In log :
------------
Product: ModSecurity IIS -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action UninstallModule64, location: C:\Program Files\ModSecurity IIS\, command: "C:\WINDOWS\system32\inetsrv\appcmd.exe" uninstall module /module.name:"ModSecurity IIS (64bits)"
--------------
![install](https://user-images.githubusercontent.com/13836821/87256911-e2199300-c4ab-11ea-90b5-99525d86537f.jpg)

**Comment by zimmerle** [comment]
Hi @mmojadad,

Can you provide the logging information for the msi execution?

You can collect such information by using:
``` 
msiexec /i  yourfile.msi /L*v  c:\temp\yourinstall.log
```
Further information here: https://www.advancedinstaller.com/user-guide/qa-log.html

**Comment by mmojadad** [comment]
Hello
I fixed it. I used MicrosoftProgram_Install_and_Uninstall.meta.diagcab based on advise on the following URL :
https://github.com/SpiderLabs/ModSecurity/wiki/IIS-Troubleshooting#running-the-installer-in-verbose-mode

Thanks

**Comment by mguinness** [comment]
I had another problem using the Windows installer which was seeing error 2503 followed by error 2502 in the event log.

If you encounter these errors it can be resolved by granting appropriate permissions to C:\WINDOWS\TEMP for the user.
