### ISSUE TITLE
regular expression is still not available for SecRuleUpdateTargetById in v3.0.4

### ISSUE THREAD

**Issue by kanitan** [SpiderLabs/ModSecurity#2359]
I still have the same problem as issue: https://github.com/SpiderLabs/ModSecurity/issues/1872 when using SecRuleUpdateTargetById. It seems fixed in v3.0.4 with the commit:
https://github.com/SpiderLabs/ModSecurity/commit/1b1fdc055b8071ad3b24573abfe9b96e546c7abf

But actually it doesn't works.Here is my config:
```
SecRuleUpdateTargetById 942100 !REQUEST_COOKIES:/^_id/
```
Send a request with the cookie below and it was blocked by ruleId 942100.
```
Cookie: _idbnaa=16778240#217623#kNDxUN8UsVvg--gXz8eKfQ
```

I confirmed that normal match like ``!REQUEST_COOKIES:_idbnaa`` is avalible, only regular expressions have problem.

**Comment by martinhsv** [comment]
Hi @kanitan ,

Your sample SecRuleUpdateTargetById works for me with both v3.0.4 (from January) and current code.

You might want to double check which rule is still being triggered.  With CRS and your cookie key-value pair,, I found I had to also disable rule 942421.
