### ISSUE TITLE
SecRuleRemoveById on web.config

### ISSUE THREAD

**Issue by mmojadad** [SpiderLabs/ModSecurity#2362]
IIS 10
Windows 2016
------------------
Hello
How can i Disable the ModSecurity using ID on web.config for a specific domain?

**Comment by martinhsv** [comment]
Hi @mmojadad ,

There may be a way, in IIS, to use SecRuleRemoveById, to remove a rule from a particular configuration context that maps to only a particular domain, but I'm a little rough on IIS integration.

Another option would be to instead use the action "ctl:ruleRemoveById".  The only tricky part might be to determine what ModSecurity VARIABLE meets your needs for this rule.  SERVER_NAME, or SERVER_ADDR are likely starting points, but if those do not supply what you need in your environment, you may have to explore other options (like perhaps there is a distinctive portion of REQUEST_FILENAME that could be used).
