### ISSUE TITLE
Multipart: Invalid boundary in C-T (malformed).

### ISSUE THREAD

**Issue by zeridon** [SpiderLabs/ModSecurity#2365]
Modsecurity is not correctly parsing content-type header in the case of multipart/form-data if charset is present

Sample
```"Content-Type": "multipart/form-data;charset=UTF-8;boundary=QXlbjhZWInGKObWZWJrwvszWcDGNUmVEctCmI1r2",```

Error:
```
"messages": [
      "Multipart parsing error (init): Multipart: Invalid boundary in C-T (malformed).",
      "Access denied with code 400 (phase 2). Match of \"eq 0\" against \"REQBODY_ERROR\" required. [file \"/etc/modsecurity/modsecurity.conf\"] [line \"60\"] [id \"200002\"] [msg \"Failed to parse request body.\"] [data \"Multipart: Invalid boundary in C-T (malformed).\"] [severity \"CRITICAL\"]"
    ],
```

The reason for the error is: https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/request_body_processor/multipart.cc#L1273

The parser just does not have support for `charset=something;` being present (anywhere on the line)

Issue is present in both v2.x and v3.x

**Comment by martinhsv** [comment]
Hi @zeridon ,

I beleve this is the same as https://github.com/SpiderLabs/ModSecurity/issues/1900 

I'll go ahead close this issue as a duplicate at end-of-day.

**Comment by zeridon** [comment]
Agreed it is the same. Funny how i couldnt find it
