### ISSUE TITLE
Proxy action corrupting HTTP sessions under high load

### ISSUE THREAD

**Issue by emerzon** [SpiderLabs/ModSecurity#2366]
When using the proxy action, under high load, some HTTP sessions become corrupt.
Seems like a race condition or context isolation issue.
In some cases, if 2 requests are sent at the same time, the first request gets proxied twice and the second one is ignored.

1) Create a proxy action like this:
```
SecRuleEngine on
SecRule REMOTE_ADDR "@unconditionalMatch" nolog,id:id-proxy,pass,proxy:https://backend.local%{REQUEST_URI}
```

2) Generate a list of unique requests to be proxied to the backend:
`$ for i in {1..1000}; do echo https://frontend.local/test/$(uuidgen) >> ~/url.txt; done`

3) Perform requests in parallel:
`$ cat ~/url.txt | xargs -P 20 -n 20 curl -k `

4) Check backend log for duplicate requests:
```
$ cat access.log  | cut -f 2 -d \"  | sort | uniq -D | wc -l
47
```
Alternatively, the duplicated requests can also be seen on DumpIO logs.

**Server:**
 - ModSecurity version (and connector): 2.9.3
 - WebServer: Apache httpd 2.4.39
 - OS (and distro): Linux, Centos 7

**Comment by zimmerle** [comment]
Hi @emerzon,

Could you please confirm the version of ModSecurity is question?

**Comment by emerzon** [comment]
@zimmerle : Tested with ModSecurity 2.9.3 - Sorry, fixed this on the description.

**Comment by zimmerle** [comment]
@emerzon That is very likely to be a problem related the version mismatch of the APR library. On the Apache's/ModSec's initialization there is information about the loaded libraries. Is there any warning mentioning about a possible version mismatch?
