### ISSUE TITLE
geo_lookup.cc:124:32: error: invalid conversion from ‘const MMDB_s*’ to ‘MMDB_s*’ [-fpermissive]

### ISSUE THREAD

**Issue by gitcnd** [SpiderLabs/ModSecurity#2371]
On CentOS Linux release 8.2.2004 (Core);

bash: git clone https://github.com/SpiderLabs/ModSecurity.git
bash: cd ModSecurity/
bash: ./build.sh
bash: ./configure
bash: git submodule init
bash: git submodule update
bash: ./configure
bash: make

...

utils/geo_lookup.cc: In member function ‘bool modsecurity::Utils::GeoLookup::lookup(const string&, modsecurity::Transaction*, std::function<bool(int, const std::__cxx11::basic_string<char>&)>) const’:
utils/geo_lookup.cc:124:32: error: invalid conversion from ‘const MMDB_s*’ to ‘MMDB_s*’ [-fpermissive]
         r = MMDB_lookup_string(&mmdb, target.c_str(), &gai_error, &mmdb_error);
                                ^~~~~
In file included from ../src/utils/geo_lookup.h:22,
                 from utils/geo_lookup.cc:25:
/usr/include/maxminddb.h:195:66: note:   initializing argument 1 of ‘MMDB_lookup_result_s MMDB_lookup_string(MMDB_s*, const char*, int*, int*)’
     extern MMDB_lookup_result_s MMDB_lookup_string(MMDB_s *const mmdb,
                                                    ~~~~~~~~~~~~~~^~~~
make[3]: *** [Makefile:3169: utils/libmodsecurity_la-geo_lookup.lo] Error 1
make[3]: Leaving directory '/usr/local/bin/src/ModSecurity/src'
make[2]: *** [Makefile:3463: all-recursive] Error 1
make[2]: Leaving directory '/usr/local/bin/src/ModSecurity/src'
make[1]: *** [Makefile:1218: all] Error 2
make[1]: Leaving directory '/usr/local/bin/src/ModSecurity/src'
make: *** [Makefile:1029: all-recursive] Error 1
[ModSecurity]$

**Comment by zimmerle** [comment]
That is a duplicate of #2364.

**Comment by lxjlxk** [comment]
> 这是 #2364 的副本。

这个怎么解决
