### ISSUE TITLE
How i can send audit logs to remote host. Do you have instructions?

### ISSUE THREAD

**Issue by ibsteklodom** [SpiderLabs/ModSecurity#2383]
I need help. I have searched instructions how i can do this, but not success.
For example, i want send log through this setup in modsecurity.conf: 
SecAuditLogType HTTPS
SecAuditLog https://192.168.10.176
SecAuditLogFormat JSON
--
What i should setup on remote host for save log data in /var/log/modsecurity.log? (Further, using the plugin in Alienvault OSSIM, I will parse it)

**Comment by zimmerle** [comment]
Hi, @ibsteklodom 

That depends. I am assuming that you are using ModSecurity version 3 with the Nignx, am I right?

Depending on your "SIEM" utility it already comes with the tools to send the logs to a concentrator. As an example of the [Logstash](https://www.elastic.co/logstash). For Alienvault, ti may be an option to use this [ASM anywhere](https://cybersecurity.att.com/documentation/usm-anywhere/deployment-guide/setup/about-log-management.htm)

**Comment by ibsteklodom** [comment]
@

> Hi, @ibsteklodom
> 
> That depends. I am assuming that you are using ModSecurity version 3 with the Nignx, am I right?
> 
> Depending on your "SIEM" utility it already comes with the tools to send the logs to a concentrator. As an example of the [Logstash](https://www.elastic.co/logstash). For Alienvault, ti may be an option to use this [ASM anywhere](https://cybersecurity.att.com/documentation/usm-anywhere/deployment-guide/setup/about-log-management.htm)

We using modsecurity 3 and nginx proxy, right.
1) We have Open Source version AlienVault OSSIM. OSSIM includes ossec. Yes, we can install ossec agent on remote host and agent will check log. But ossec server have not rules for modsecurity log.
2) OSSIM have syslog server. But how i can send data in syslog format?
3) At the same time, OSSIM has an already written plugin for parsing the modsecurity log. Plugin start process "apache2". I thought this plugin was built to work by https. Maybe we need to put a script for save the sent data on server OSSIM.

**Comment by ibsteklodom** [comment]
I found a way to transfer modsecurity logs to OSSIM. 

1) I created file /etc/rsyslog.d/modsecurity.conf on host with modsecurity and reboot service rsyslog. Config:
$ModLoad imfile
$InputFileName /var/log/modsec_audit.log
$InputFileTag modsecurity:
$InputFileStateFile modsec_audit_log
$InputFileSeverity info
$InputFileFacility local6
$InputRunFileMonitor
*.*  @@OSSIM IP

2) On side ossim create /etc/rsyslog.d/modsecurity.conf and reboot service rsyslog. File conf:
if( $fromhost-ip == 'IP host with modsecurity' and $programname == 'modsecurity') then {action(type="omfile" file="/var/log/modsecurity.log")
stop}

3) I enabled plugin "modsecurity" on OSSIM. However, this plugin cannot parse the resulting log file.(

**Comment by zimmerle** [comment]
Hi, @ibsteklodom 

You may need an specific parser for version 3. Notice that version 3 is capable to output logging is json format. This json format can be easily parsed.

**Comment by kwaazaar** [comment]
I found that SecAuditLogType HTTPS doesn't seem to do anything at all (nginx ingress controller), so I used fluend (tail input) to post all json data to a custom api that takes the json and posts a custom event to Application Insights. If you can use an existing output plugin for fluentd (like Elastic), then you don't need the custom code for transformation.
