### ISSUE TITLE
Jitsi meet and REQUEST-941-APPLICATION-ATTACK-XSS

### ISSUE THREAD

**Issue by ibsteklodom** [SpiderLabs/ModSecurity#2384]
We have nginx proxy server with nginx-modsecurity. [Jitsi](https://jitsi.org) installed behind this proxy. It is in the nginx logs:
1) _Aug 17 08:34:24 nginx-01 nginx: 2020/08/17 08:34:24 [info] 32747#32747: *685627 ModSecurity: Warning. Matched "Operator `Rx' with parameter
`\xbc[^\xbe>]*[\xbe>]|<[^\xbe]*\xbe' against variable `XML:/*' (Value:
`\xd0\x92\xd1\x8b\xd0\xba\xd0\xb8\xd0\xb4\xd1\x8b\xd0\xb2\xd0\xb0\xd0\xb5\xd1\x82 \xd0\xbc\xd0\xb5\xd (134 characters omitted)' ) [file
"/etc/nginx/owasp/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "527"] [id "941310"] [rev ""] [msg "US-ASCII Malformed Encoding XSS
Filter - Attack Detected"] [data "Matched Data: \xbc\xd0\xb5\xd0\xbd\xd1\x8f\xd0\x95\xd0\xb2\xd0\xb3\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f
\xd0\x9a\xd0\xbe found within XML:/*: \xd0\x92\xd1\x8b\xd0\xba\xd0\xb8\xd0\xb4\xd1\x8b\xd0\xb2\xd0\xb0\xd0\xb5\xd1\x82
\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x8f\xd0\x95\xd0\xb2\xd0\xb3\xd0\xb5\xd0\xbd\xd0\xb8\xd1\x8f
\xd0\x9a\xd0\xbe\xd1\x80\xd0\xbe\xd1\x82\xd0\xba\xd0\xb8\xd1\x85"] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag
"application-multi"] [tag "language-multi"] [tag "platform-tomcat"] [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag
"capec/1000/152/242"] [hostname "10.30.88.66"] [uri "/http-bind"] [unique_id "1597635264"] [ref
"o22,26t:urlDecodeUni,t:lowercase,t:urlDecode,t:htmlEntityDecode,t:jsDecode"], client: xxx.xxx.xxx.xxx, server: jitsi.xxx.com, request:
"POST /http-bind?room=%d0%be%d0%b1%d1%83%d1%87%d0%b5%d0%bd%d0%b8%d0%b5%d0%b4%d0%b8%d0%b7%d0%b0%d0%b9%d0%bd%d0%b5%d1%80%d1%8b17.08 HTTP/2.0",
host: "jitsi.xxx.com"_ 

AND

2)_Aug 17 08:44:25 nginx-01 nginx: 2020/08/17 08:44:25 [error] 32747#32747: *690897 [client 10.1.62.9] ModSecurity: Access denied with code 403
(phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file
"/etc/nginx/owasp/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total
Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag
"platform-multi"] [tag "attack-generic"] [hostname "10.30.88.66"] [uri "/http-bind"] [unique_id "1597635865"] [ref ""], client: 10.1.62.9,
server: jitsi.xxx.com, request: "POST
/http-bind?room=%d0%be%d0%b1%d1%83%d1%87%d0%b5%d0%bd%d0%b8%d0%b5%d0%b4%d0%b8%d0%b7%d0%b0%d0%b9%d0%bd%d0%b5%d1%80%d1%8b17.08 HTTP/1.1", host:
"jitsi.xxx.com", referrer:
"https://jitsi.xxx.com/%D0%9E%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%D0%B4%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD%D0%B5%D1%80%D1%8B17.08"_ 

**Does this mean a false positive?**

**Comment by zimmerle** [comment]
Hi @ibsteklodom this is very likely to be a false positive. That is not really a ModSecurity issue, is more likely to be a issue with the rule set that you have loaded. Said that, the better place to have this issue is within the rule set repository.
