### ISSUE TITLE
Unable to retrieve collection 

### ISSUE THREAD

**Issue by sina-grz** [SpiderLabs/ModSecurity#2386]
i am running a httpd(apache2) image on docker
the problem is mod security cannot cash objects so i cant use indexer or counter to use in my rules 
this is a simple log off a simple get request where i have configed in a location scope
```
SecRuleEngine On
SecStatusEngine On
<Location "/index">
  SecAction initcol:resource=%{REQUEST_URI},pass,nolog,id:132
  SecRule RESOURCE:COUNTER "@ge 5" "phase:3,pause:10,deny,status:429,setenv:RATELIMITED,skip:1,nolog,id:232"
  SecAction "phase:2,setvar:resource.counter=+1,pass,nolog,id:332"
  SecAction "phase:2,deprecatevar:resource.counter=10/60,pass,nolog,id:432"
  Header always set Retry-After "60" env=RATELIMITED
</Location>
```
```
[Fri Aug 21 15:38:24.627852 2020] [:error] [pid 8:tid 140654115591936] [client 127.0.0.1:38918] [client 127.0.0.1] ModSecurity: collection_store: Unable to store collection (name "resource", key "/index"). Use SecDataDir to define data directory first. [hostname "localhost"] [uri "/index"] [unique_id "Xz-qcEpEOEI3fjkSIIERPQAAAAA"]
127.0.0.1 - - [21/Aug/2020:15:38:24 +0000] "GET /index HTTP/1.1" 404 196
```
does it need any especial config to store object in memory?

i also tried to use SecDataDir but i got permission denied stuff which it seems doesnt have solution duo to docker container envirment

**Comment by zimmerle** [comment]
Hi @sna-king 

Within v2 it is possible to have persistent collections. They work via **sdbm**. The communication in between different process (and/or threads) happens via a file managed via **sdbm**. Without the file won't be communication in between the threads therefore the functionality will not work to satisfaction.

Please review your docker configuration and make sure that the **sdbm** files are being created.

**Comment by sina-grz** [comment]
> **sdbm**

i havnt found any thing about dbm and sdbm configs in docker

`[Sat Aug 22 10:10:12.465295 2020] [:error] [pid 11:tid 140217980487424] [client 127.0.0.1:38304] [client 127.0.0.1] ModSecurity: collection_store: Failed to access DBM file "/usr/local/apache2/logs/data/daemon-resource": Permission denied [hostname "localhost"] [uri "/index"] [unique_id "X0DvBKl@v3PoFyiZrWSEWgAAAIA"]`

what about the standard way i mean collecting data in memory isn't that possible :|

------
note : /usr/local/apache2/logs/data is where i defined by SecDataDir

**Comment by sina-grz** [comment]
problem solved in alternative way:
-------
i haven't found any solution to store collections in memory but i have fixed it by giving SecDataDir a folder with full access for any body in my case because i have used a directory witch was inside a parent directory created by httpd apache image (usr/local/apache2/*)

using data session file and handling this variable in a file is not good and optimized way . as now a day a lot of people work in a containerize environment i think that a kind of bug.

**Comment by zimmerle** [comment]
Hi @sna-king, is the same thing for logging; If you try to save it in a folder that you don't have permission ModSercurity will fail to save the file. Regardless being in the container or not, ModSecurity will respect the permission on the file system.
