### ISSUE TITLE
how make my modsecurity send log to syslog

### ISSUE THREAD

**Issue by LDR0305** [SpiderLabs/ModSecurity#2388]
Hello,
how make my modsecurity send log to syslog,
thank you.

**Comment by LDR0305** [comment]
Can you answer me in detail

**Comment by LDR0305** [comment]
modsecurity-v3

**Comment by dl213** [comment]
I am looking for this solution too, no detail guide for this on nginx with modsecurity

**Comment by martinhsv** [comment]
Hi,

ModSecurity produces logging in nginx's error.log file.  If you want to send these log messages to syslog, nginx configuration does support that.  There are some instructions here:
https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#syslog
http://nginx.org/en/docs/syslog.html

If you are instead inquiring about ModSecurity's audit log (typically called modsec_audit.log), I don't believe there is any native way to redirect that logging to syslog.  However, one way you could probably accomplish this is to use the 'HTTPS' option for SecAuditLogType and then have the receiver write to syslog.
