### ISSUE TITLE
There may be a mispell in src/engine/lua.cc

### ISSUE THREAD

**Issue by denity** [SpiderLabs/ModSecurity#2389]
In src/engine/lua.cc, on row 158. 

Compared to the previous version is '#ifndef WITH_LUA_5_1' and the latest version is '#if defined(WITH_LUA_5_1) and !defined(WITH_LUA_5_4)', which will break the configure progress on Lua 5.1.

**Comment by zimmerle** [comment]
Hi @denity 

I will have a look at it. That change was made to support 5.4. Going to fix it.

**Comment by zimmerle** [comment]
Fixed by 377fb72
