### ISSUE TITLE
IIS Missing GeoIP and optional Dependencies?

### ISSUE THREAD

**Issue by ChrisBurgdorff** [SpiderLabs/ModSecurity#2390]
Does IIS on Windows support the GeoIP Dependency for ModSecurity?

Hi,
I'm not sure if this is the write place to post this, but I have IIS 8 running on Windows Server 2012 with ModSecurity IIS 3 installed. It works, however I can't seem to use the GeoIP dependency (which is listed as optional for Linux). Here is the output from dumpbin.exe:

Dump of file ModSecurityIIS.dll

File Type: DLL

  Image has the following dependencies:

    libapr-1.dll
    libaprutil-1.dll
    pcre.dll
    libxml2.dll
    KERNEL32.dll
    ADVAPI32.dll
    OLEAUT32.dll
    WS2_32.dll
    IPHLPAPI.DLL
    lua5.1.dll
    yajl.dll
    MSVCR120.dll

Is there a way to add GeoIP (and other optional) dependencies to IIS or are they just not supported?

**Comment by zimmerle** [comment]
Hi @ChrisBurgdorff

Can you share more details on how you got this ModSecurity installed?  It was the MSI that we have available here? or other source?

**Comment by ChrisBurgdorff** [comment]
I think it was through the Web Platform Installer in IIS actually.

**Comment by ChrisBurgdorff** [comment]
Hi,
It seems I had the path to the .db file formatted incorrectly. Once i fixed that it works.
Sorry. If anyone finds this, the path to the Geo DB file in Windows is written just like in linux.
