### ISSUE TITLE
REMOTE_ADDR variable or initcol action doesn't work probably 

### ISSUE THREAD

**Issue by sina-grz** [SpiderLabs/ModSecurity#2391]
im trying to set up a simple anti ddos rule  
like:
```
SecAction initcol:ip=%{REMOTE_ADDR},pass,nolog,id:1
SecAction "phase:2,pass,setvar:ip.counter=+1,nolog,id:13"
SecAction "phase:5,deprecatevar:ip.counter=10/10,pass,nolog,id:10"
SecRule REMOTE_ADDR "127.0.0.1" "id:11,pass,ctl:ruleRemoveById=102;"
SecRule IP:COUNTER "@ge 10" "phase:2,deny,status:429,setenv:RATELIMITED,msg:'%{REMOTE_ADDR} has exceded reate limit',id:101"
SecRule IP:COUNTER "@ge 5" "phase:2,deny,status:429,setenv:RATELIMITED,id:102"
```

at first it seams fine and evrything work well , when i reach max limit for my ip in Chrome browser it blocked me and let me pass after 10 sec passed, if i try to connect to server with diffrent browser like firefox i can access server till i reach the max rate with firefox or curl actually it seems it doesn't work with ip ,it more using header 

this sample log show the situation that i send five via Chrome then i got blocked and by changing  my client app like using a script i gain access to sending 5 request although that 10 second limit for my ip had not finished :
`
ng. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "810"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address"] [data "172.16.111.117"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "172.16.111.117"] [uri "/ddos.htmldd"] [unique_id "X0-FTpZK-VsqDXVHNyHbwQAAAoE"]
[Wed Sep 02 16:16:14.934509 2020] [:error] [pid 813:tid 139688107046656] [client 172.16.200.241:51274] [client 172.16.200.241] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "810"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address"] [data "172.16.111.117"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "172.16.111.117"] [uri "/ddos.htmldd"] [unique_id "X0-FTpZK-VsqDXVHNyHbwgAAAoI"]
[Wed Sep 02 16:16:15.278819 2020] [:error] [pid 813:tid 139688056690432] [client 172.16.200.241:51274] [client 172.16.200.241] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "810"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address"] [data "172.16.111.117"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "172.16.111.117"] [uri "/ddos.htmldd"] [unique_id "X0-FT5ZK-VsqDXVHNyHbwwAAAog"]
[Wed Sep 02 16:16:15.606690 2020] [:error] [pid 813:tid 139687838611200] [client 172.16.200.241:51274] [client 172.16.200.241] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "810"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address"] [data "172.16.111.117"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "172.16.111.117"] [uri "/ddos.htmldd"] [unique_id "X0-FT5ZK-VsqDXVHNyHbxAAAAok"]
[Wed Sep 02 16:16:15.953986 2020] [:error] [pid 813:tid 139687830218496] [client 172.16.200.241:51274] [client 172.16.200.241] ModSecurity: Access denied with code 429 (phase 2). Operator GE matched 5 at IP:counter. [file "/etc/apache2/mods-enabled/ddos_security2.conf"] [line "6"] [id "102"] [hostname "172.16.111.117"] [uri "/ddos.htmldd"] [unique_id "X0-FT5ZK-VsqDXVHNyHbxQAAAoo"]
[Wed Sep 02 16:16:16.312771 2020] [:error] [pid 813:tid 139687930865408] [client 172.16.200.241:51274] [client 172.16.200.241] ModSecurity: Access denied with code 429 (phase 2). Operator GE matched 5 at IP:counter. [file "/etc/apache2/mods-enabled/ddos_security2.conf"] [line "6"] [id "102"] [hostname "172.16.111.117"] [uri "/ddos.htmldd"] [unique_id "X0-FUJZK-VsqDXVHNyHbxgAAApA"]
[Wed Sep 02 16:16:16.666398 2020] [:error] [pid 813:tid 139687704393472] [client 172.16.200.241:51274] [client 172.16.200.241] ModSecurity: Access denied with code 429 (phase 2). Operator GE matched 5 at IP:counter. [file "/etc/apache2/mods-enabled/ddos_security2.conf"] [line "6"] [id "102"] [hostname "172.16.111.117"] [uri "/ddos.htmldd"] [unique_id "X0-FUJZK-VsqDXVHNyHbxwAAApI"]
[Wed Sep 02 16:16:17.076624 2020] [:error] [pid 813:tid 139687696000768] [client 172.16.200.241:51274] [client 172.16.200.241] ModSecurity: Access denied with code 429 (phase 2). Operator GE matched 5 at IP:counter. [file "/etc/apache2/mods-enabled/ddos_security2.conf"] [line "6"] [id "102"] [hostname "172.16.111.117"] [uri "/ddos.htmldd"] [unique_id "X0-FUZZK-VsqDXVHNyHbyAAAApM"]
[Wed Sep 02 16:16:19.917110 2020] [:error] [pid 651:tid 139688194471680] [client 172.16.200.241:51278] [client 172.16.200.241] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "810"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address"] [data "172.16.111.117"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "172.16.111.117"] [uri "/ddos.html"] [unique_id "X0-FU6mt7dtkGAeZky@c6AAAAQA"]
[Wed Sep 02 16:16:20.231734 2020] [:error] [pid 651:tid 139688186078976] [client 172.16.200.241:51278] [client 172.16.200.241] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "810"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address"] [data "172.16.111.117"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "172.16.111.117"] [uri "/ddos.html"] [unique_id "X0-FVKmt7dtkGAeZky@c6QAAAQE"]
[Wed Sep 02 16:16:20.576689 2020] [:error] [pid 651:tid 139688107046656] [client 172.16.200.241:51278] [client 172.16.200.241] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "810"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address"] [data "172.16.111.117"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "172.16.111.117"] [uri "/ddos.html"] [unique_id "X0-FVKmt7dtkGAeZky@c6gAAAQI"]
[Wed Sep 02 16:16:20.925755 2020] [:error] [pid 651:tid 139688098653952] [client 172.16.200.241:51278] [client 172.16.200.241] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "810"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address"] [data "172.16.111.117"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "172.16.111.117"] [uri "/ddos.html"] [unique_id "X0-FVKmt7dtkGAeZky@c6wAAAQM"]
[Wed Sep 02 16:16:21.268113 2020] [:error] [pid 651:tid 139688090261248] [client 172.16.200.241:51278] [client 172.16.200.241] ModSecurity: Access denied with code 429 (phase 2). Operator GE matched 5 at IP:counter. [file "/etc/apache2/mods-enabled/ddos_security2.conf"] [line "6"] [id "102"] [hostname "172.16.111.117"] [uri "/ddos.html"] [unique_id "X0-FVamt7dtkGAeZky@c7AAAAQQ"]
[Wed Sep 02 16:16:21.627260 2020] [:error] [pid 651:tid 139688073475840] [client 172.16.200.241:51278] [client 172.16.200.241] ModSecurity: Access denied with code 429 (phase 2). Operator GE matched 5 at IP:counter. [file "/etc/apache2/mods-enabled/ddos_security2.conf"] [line "6"] [id "102"] [hostname "172.16.111.117"] [uri "/ddos.html"] [unique_id "X0-FVamt7dtkGAeZky@c7QAAAQY"]
[Wed Sep 02 16:16:21.988739 2020] [:error] [pid 651:tid 139688081868544] [client 172.16.200.241:51278] [client 172.16.200.241] ModSecurity: Access denied with code 429 (phase 2). Operator GE matched 5 at IP:counter. [file "/etc/apache2/mods-enabled/ddos_security2.conf"] [line "6"] [id "102"] [hostname "172.16.111.117"] [uri "/ddos.html"] [unique_id "X0-FVamt7dtkGAeZky@c7gAAAQU"]
`

**Comment by sina-grz** [comment]
![image](https://user-images.githubusercontent.com/22452466/92011355-3597b700-ed60-11ea-9896-6533d9892464.png)
more friendly log

**Comment by zimmerle** [comment]
Hi @sna-king,

The counter are precise within the worker, multiple workers can have different. Your threshold should considers this fact while considering some requests set to be a DoS.
