### ISSUE TITLE
Looking for permission to mention ModSecurity logo in conf talk

### ISSUE THREAD

**Issue by jeremyjpj0916** [SpiderLabs/ModSecurity#2397]
We have been leveraging ModSecurity v3 on nginx for awhile (its why you have seen me raise issues + pr's here and in the nginx bridge repo). 

We would like to give just a quick shout out to mod security opensource waf as well as the folks over at OWASP CRS(we got their permisison already for their logo use).

We were hoping to include this in a slide:

![image](https://user-images.githubusercontent.com/31913027/92643861-776cb400-f2b0-11ea-8aa6-61948f585a1e.png)

@zimmerle is this something you can approve here for us to use as project lead or does someone else from Spiderlabs need to grant permission?

Thanks.

**Comment by zimmerle** [comment]
Hi @jeremyjpj0916 

Glad to hear that you want to promote ModSecurity. I do not have the authority to make such authorization, but I can connect you to the right pears. Do you mind dropping me an email at fcosta@trustwave.com ?

**Comment by jeremyjpj0916** [comment]
Doing so now, thanks.
