### ISSUE TITLE
Variable for DetectionOnly and On

### ISSUE THREAD

**Issue by ledzepp4eva** [SpiderLabs/ModSecurity#2398]
Hey,
Not really a bug request more a question if at all possible.

Is there a way to log a variable with a rule that tells me if the mode is DetectionOnly or On

For example like:
`logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}`
Or using
`tag:'attack-rfi',`

But tag with a variable that returns the status of SecRuleEngine

I think it would useful so we can see just by looking at one log line if the status is On or DetectionOnly.

Thanks,
Liam

**Comment by martinhsv** [comment]
Hi @ledzepp4eva ,

I'm not aware of a way to do that.

**Comment by ledzepp4eva** [comment]
Thanks okay. I just wanted to ask, just in case. :)
