### ISSUE TITLE
modsec_audit.log not show when i make the SecRuleEngine On

### ISSUE THREAD

**Issue by xx-zhang** [SpiderLabs/ModSecurity#2402]
**Describe the bug**

**Logs and dumps**

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs
 3. Error logs
 4. If there is a crash, the core dump file.

**there is no any modsec_audit.log and modsec_debug.log . and when i set SecRuleEngine  DetectOnly, it will show.**

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

A **curl** command line that mimics the original request and reproduces the problem. Or a ModSecurity v3 test case.

[e.g: curl "modsec-full/ca/..\\..\\..\\..\\..\\..\\/\\etc/\\passwd" or [issue-394.json](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/test/test-cases/regression/issue-394.json)]

ENV:
- nginx-1.18
- modsecurty-nginx 1.0.1 
- modsecurity v3.0.4 
- crs-rules  latest 

## Modsecurity 
![image](https://user-images.githubusercontent.com/47806549/93187527-789b5680-f772-11ea-9a79-5a9f5986b2df.png)

## Nginx 
![image](https://user-images.githubusercontent.com/47806549/93187616-91a40780-f772-11ea-9e42-76e11c9da4b3.png)

## ldd lib_ngx_http_modsecurity 
```
[root@localhost ~]# ldd /builds/software/nginx/modules/ngx_http_modsecurity_module.so
        linux-vdso.so.1 =>  (0x00007fffc577d000)
        libmodsecurity.so.3 => /builds/software/plugins/modsecurity/lib/libmodsecurity.so.3 (0x00007faa142ee000)
        libc.so.6 => /lib64/libc.so.6 (0x00007faa13f19000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00007faa13caf000)
        libGeoIP.so.1 => /lib64/libGeoIP.so.1 (0x00007faa13a7f000)
        librt.so.1 => /lib64/librt.so.1 (0x00007faa13876000)
        libxml2.so.2 => /lib64/libxml2.so.2 (0x00007faa1350c000)
        libz.so.1 => /lib64/libz.so.1 (0x00007faa132f6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007faa130f1000)
        liblua-5.1.so => /lib64/liblua-5.1.so (0x00007faa12ec3000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007faa12c61000)
        libyajl.so.2 => /lib64/libyajl.so.2 (0x00007faa12a56000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007faa1274f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007faa1244d000)
        /lib64/ld-linux-x86-64.so.2 (0x000055f99732e000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007faa12236000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00007faa12003000)
        libssh2.so.1 => /lib64/libssh2.so.1 (0x00007faa11dd6000)
        libssl3.so => /lib64/libssl3.so (0x00007faa11b7c000)
        libsmime3.so => /lib64/libsmime3.so (0x00007faa11954000)
        libnss3.so => /lib64/libnss3.so (0x00007faa11625000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007faa113f4000)
        libplds4.so => /lib64/libplds4.so (0x00007faa111f0000)
        libplc4.so => /lib64/libplc4.so (0x00007faa10feb000)
        libnspr4.so => /lib64/libnspr4.so (0x00007faa10dac000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007faa10b90000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007faa10943000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007faa1065a000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007faa10427000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007faa10223000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007faa10013000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007faa0fdbf000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007faa0fb99000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007faa0f926000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007faa0f4c5000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007faa0f2b6000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007faa0f0b2000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007faa0ee98000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007faa0ec7a000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007faa0ea53000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007faa0e81b000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007faa0e618000)
[root@localhost ~]#
```
**Expected behavior**

**Server (please complete the following information):**
 - ModSecurity version (and connector): [e.g. ModSecurity v3.0.1 with nginx-connector v1.0.0]
 - WebServer: [e.g. nginx-1.15.5]
 - OS (and distro): [e.g. Linux, archlinux]

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? [e.g. SpiderLabs commercial rules]
 - What is the version number? [e.g. 2018-08-11]

**Additional context**

**Comment by martinhsv** [comment]
Hi @xx-zhang ,

I'm not entirely sure I understand what problem you are describing.  In particular, I don't know what you mean by "and when i set SecRuleEngine DetectOnly, it will show."

Nevertheless, I'll try to provide you with a few tips/suggestions:

1) if there is no modsecurity debug file at all, it probably means one of A) you don't have SecDebugLog specified, which is usually done in your modsecurity.conf file (or perhaps the line is commented out?), or B) you do have that set but there is a permissions issue with writing to the file location that you have specified, or C) the ModSecurity configuration is not being read

2) one way to confirm that the ModSecurity config is being read, is to make an intentional misspelling in the configuration.  For example, change SecDebugLog to ScDebugLog.  If you try to start nginx, you should get an error (both on the cli where you did the start, and in nginx's error.log)

3) if that doesn't happen, then recheck your nginx configuration files to ensure that you have included ModSecurity config correctly (and set 'modsecurity on'!) -- and that it is active for the correct server/location.

**Comment by xx-zhang** [comment]
i have make modsecurity-v3.0.4 -> 3.0.3 and or the config is the same. then have solved that problem . thank you. i think maybe someone else will meeting the same problem. then i will come to see .
