### ISSUE TITLE
undefined reference to 'lua_pcallk'...

### ISSUE THREAD

**Issue by HL123** [SpiderLabs/ModSecurity#2403]
**Describe the bug**

I will use modsecurity( support lua) .when i do "make ", modesecurity will error as follow:

../../src/.libs/libmodsecurity.so: undefined reference to `lua_pcallk'
../../src/.libs/libmodsecurity.so: undefined reference to `lua_getglobal'
../../src/.libs/libmodsecurity.so: undefined reference to `lua_setglobal'

When i have doen this
1、upload LuaJIT-2.0.2.tar.gz
2、tar -zxvf LuaJIT-2.0.2.tar.gz
3、cd LuaJIT-2.0.2/
4、mkdir /home/upki/luajit
5、make install PREFIX=/home/upki/luajit
6、echo "/home/upki/luajit/lib/" > /etc/ld.so.conf.d/usr_local_luajit_lib.conf
7、export LUAJIT_LIB=/home/upki/luajit/lib/
8、export LUAJIT_INC=/home/upki/luajit/include/luajit-2.0

 rpm -ivh lua53-devel-5.3.4-lp152.4.112.x86_64.rpm --nodeps --force

my  operating system is suse linux.
lua version is 5.2.

**Comment by zimmerle** [comment]
What is likely to be happening is that you are having a conflict of Lua versions. One version is used during the compilation, and a second version is being used on run time. Is that a reason why you keep three different Lua versions on the machine?

**Comment by HL123** [comment]
> What is likely to be happening is that you are having a conflict of Lua versions. One version is used during the compilation, and a second version is being used on run time. Is that a reason why you keep three different Lua versions on the machine?


the  lua 5.2 was default on  suse linux，

the LuaJIT-2.0.2 was i install, while i cannot compile rightly.

so i have install the lua53-devel-5.3.4-lp152.4.112.x86_64.rpm, and the modsecrity can execute "./configure " but execute "make and make install " show error .

OR  I don't know how to  reference the version .  can you help me ,which step i can do . Or where have a tutorial ?

Thank you very much ！

**Comment by zimmerle** [comment]
Hi @HL123 

We recommend you to choose one version of Lua to use. Once you have pick the version that you are going to use, we can identify what is going on. I recommend you to use the version that comes with the distribution. That way you avoid to have conflicting versions on runtime.

**Comment by zimmerle** [comment]
@HL123 closing the issue. I am assuming that you have it sorted. If not, please re-open.

**Comment by HL123** [comment]
ok thanks~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SpiderLabs/ModSecurity"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 凌晨2:38
收件人:&nbsp;"SpiderLabs/ModSecurity"<ModSecurity@noreply.github.com&gt;;
抄送:&nbsp;"HL_"<1939018754@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [SpiderLabs/ModSecurity] undefined reference to 'lua_pcallk'... (#2403)





 
@HL123 closing the issue. I am assuming that you have it sorted. If not, please re-open.
