### ISSUE TITLE
"SecRuleEngine On"  No message in audit log

### ISSUE THREAD

**Issue by MapTracy** [SpiderLabs/ModSecurity#2404]
hi
i'm using modsecurity-v3.0.4 Release . When i use DetectionOnly mode, there are messages in auditlog. When i use "SecRuleEngine On" , there are no messages in auditlog, even if the rule is trigged. But i can find the record in nginx's error.log

and here is my modsecurity.conf

SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABCDFHZ
SecAuditLogType Concurrent
SecAuditLogStorageDir /var/log/gateway/

I really dont know the reason. please help me solve this problem.

**Comment by martinhsv** [comment]
Hi @MapTracy ,

By 'modsecurity-v3.0.4 Release' you mean the official tagged version? -- either from an installed repo version, or if from github the tagged version ( https://github.com/SpiderLabs/ModSecurity/commit/753145fbd1d6751a6b14fdd700921eb3cc3a1d35 )

If you can see the expected output in the audit log when using DetectionOnly, but not when 'On' then that rules out several types of configuration errors.

When 'On' and you cannot see entries in the audit log,
- Is there an entry in nginx's error.log ?
- if you turn DebugLog level on (and set the level to 9), can you see the same relevant rule processing for both DetectionOnly and On?  (In particular, the rule that you expect to report, should include 'Rule returned 1' in the DebugLog).

Also:
- if you change the SecAuditLogType to Serial, do you still have the same problem?
- if you change SecAuditEngine from 'RelevantStatus' to 'On', do you then always see the entries in the audit log?

**Comment by MapTracy** [comment]
Hi @martinhsv

I had solved my problem with victorhora/ModSecurity-nginx@ac3e8a9

Thank you for replying to my message.
