### ISSUE TITLE
error: 'LUA_ERRGCMM' was not declared in this scope case LUA_ERRGCMM

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2406]
Compilation error on centos7.7

`engine/lua.cc: In member function 'int modsecurity::engine::Lua::run(modsecurity::Transaction*, const string&)':
engine/lua.cc:160:18: error: 'LUA_ERRGCMM' was not declared in this scope
             case LUA_ERRGCMM:
                  ^
make[3]: *** [engine/libmodsecurity_la-lua.lo] Error 1
make[3]: Leaving directory `/www/ModSecurity/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/www/ModSecurity/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/www/ModSecurity/src'
make: *** [all-recursive] Error 1`

What should I do?

**Comment by zimmerle** [comment]
Duplicate of #2403. Please, use v3.0.4 instead.

**Comment by zimmerle** [comment]
The dup is actually #2389
