### ISSUE TITLE
modsec's parser

### ISSUE THREAD

**Issue by LDR0305** [SpiderLabs/ModSecurity#2410]
hello,can you tell me how the two files seclang-scanner.ll and seclang-parser.yy are compiled,I am currently working on related development,thank you very much.

**Comment by LDR0305** [comment]
@zimmerle

**Comment by LDR0305** [comment]
If compile directly with flex and bison, it will produce different results

**Comment by LDR0305** [comment]
can you help me？

**Comment by airween** [comment]
```bash
./configure --help
...
  --enable-parser-generation
                          Enables parser generation during the build
```
I think this is what you want: `./configure --enable-parser-generation ...other-options...`

**Comment by martinhsv** [comment]
> If compile directly with flex and bison, it will produce different results

It does depend, at least, on which version of software was used.  I believe the current version of v3/master used bison v3.5.3.

You can try matching that version to minimize changes.  But, depending on what you're trying to do, you might not care that bison-generated code is different from what is in the ModSecurity depo.

**Comment by LDR0305** [comment]
Thank you very much.
@martinhsv @airween

**Comment by zimmerle** [comment]
@LDR0305 are you willing to use the LALR to to a different scenario that is not modsec? By default we distribute that compiled, in our dev environments we generate it we avoid to generate on all compilation to avoid creating too many dependencies.
