### ISSUE TITLE
How to encrypt  "username" and "Password" in response body of audit log by using Modsecurity 3.0.4

### ISSUE THREAD

**Issue by satchidipu174** [SpiderLabs/ModSecurity#2414]
How to encrypt  "username" and "Password" in response body of audit log by using Modsecurity 3.0.4.
Please share what changes need to do in Modsecurity and Nginx as well.

**Comment by zimmerle** [comment]
Hi @satchidipu174,

I think you are referring to [log sanitizer](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#sanitiseArg). Log Sanitizer is not yet ready on v3.

**Comment by satchidipu174** [comment]
Hello zimmerle,
Yes I am taking about Log sanitizer. On which version we can expect it.
