### ISSUE TITLE
Rule id:920350 block only in PL=4

### ISSUE THREAD

**Issue by askifyouneed** [SpiderLabs/ModSecurity#2415]
**Describe the bug**

On the new server RHEL 8.2 I have to move to the CRS 3:
```
mod_security-2.9.2-8.el8.x86_64
mod_security_crs-3.0.0-5.el8.noarch
```
I do not understand the logic, because the rule # 920350 block requests when I set in the crs-setup setvar:tx.paranoia_level=4 only.

When I verify the file REQUEST-920-PROTOCOL-ENFORCEMENT.conf
``` 
 771 SecRule REQUEST_HEADERS:Host "^[\d.:]+$" \
 772   "msg:'Host header is a numeric IP address',\
 773    phase:request,\
 774    rev:'2',\
 775    ver:'OWASP_CRS/3.0.0',\
 776    maturity:'9',\
 777    accuracy:'9',\
 778    t:none,\
 779    block,\
 780    logdata:'%{matched_var}',\
 781    severity:'WARNING',\
 782    id:920350,\
 783    tag:'application-multi',\
 784    tag:'language-multi',\
 785    tag:'platform-multi',\
 786    tag:'attack-protocol',\
 787    tag:'OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST',\
 788    tag:'WASCTC/WASC-21',\
 789    tag:'OWASP_TOP_10/A7',\
 790    tag:'PCI/6.5.10',\
 791    setvar:'tx.msg=%{rule.msg}',\
 792    setvar:tx.anomaly_score=+%{tx.warning_anomaly_score},\
 793    setvar:tx.%{rule.id}-OWASP_CRS/POLICY/IP_HOST-%{matched_var_name}=%{matched_var}"
```
there is no tag: paranoia-level
so how to manage this rule, and how to find out on which paranoia-level will be activated if there is no tag?
how to activate this rule in another global paranoia-level for example 2?

**Comment by zimmerle** [comment]
Hi @askifyouneed you may want to ask that question on the OWASP CRS project - https://github.com/coreruleset/coreruleset

**Comment by askifyouneed** [comment]
Which exactly https://github.com/coreruleset/coreruleset/issues/new/choose.
Help and support redirect to the stackexchange which is empt,
OWASP Core Rule Set mailing list redirect to the Google groups which are used by nobody
:(

**Comment by zimmerle** [comment]
I am sorry to hear that. They have moved recently to a new home. Trustwave note on that - https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.3/dev/README.md

**Comment by askifyouneed** [comment]
sorry but I still can not find the issue where I can put my question (besides Google groups, but it looks dead)

**Comment by airween** [comment]
Hi @askifyouneed,

> mod_security_crs-3.0.0-5.el8.noarch

that's a bit old, there are so many modification in newer versions.
 
> I do not understand the logic, because the rule # 920350 block requests when I set in the crs-setup setvar:tx.paranoia_level=4 only.

you mean eg. if the PL=2 then this rule isn't activated?

> When I verify the file REQUEST-920-PROTOCOL-ENFORCEMENT.conf
> 771 SecRule REQUEST_HEADERS:Host "^[\d.:]+$" \
> 772 "msg:'Host header is a numeric IP address',\
> 773 phase:request,\
> 774 rev:'2',\
> 775 ver:'OWASP_CRS/3.0.0',\
> 776 maturity:'9',\
> 777 accuracy:'9',\
> 778 t:none,\
> 779 block,\
> 780 logdata:'%{matched_var}',\
> 781 severity:'WARNING',\
> 782 id:920350,\
> 783 tag:'application-multi',\
> 784 tag:'language-multi',\
> 785 tag:'platform-multi',\
> 786 tag:'attack-protocol',\
> 787 tag:'OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST',\
> 788 tag:'WASCTC/WASC-21',\
> 789 tag:'OWASP_TOP_10/A7',\
> 790 tag:'PCI/6.5.10',\
> 791 setvar:'tx.msg=%{rule.msg}',\
> 792 setvar:tx.anomaly_score=+%{tx.warning_anomaly_score},\
> 793 setvar:tx.%{rule.id}-OWASP_CRS/POLICY/IP_HOST-%{matched_var_name}=%{matched_var}"

I assume the lines above begins with the line numbers in rule - but it's a bit weird, because this rule in the v3.0/master starts in line [788](https://github.com/coreruleset/coreruleset/blob/v3.0/master/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L788).

> there is no tag: paranoia-level

yes, [we still found](https://github.com/coreruleset/coreruleset/pull/1882/files) rules without PL tags. That's a bug, and any reports are very welcome.

> so how to manage this rule, and how to find out on which paranoia-level will be activated if there is no tag?

you can find the previous and next control rule, eg:
```
25   SecRule TX:PARANOIA_LEVEL "@lt 1" "phase:1,id:920011,nolog,pass,skipAfter:END-REQUEST-920-PROTOCOL-ENFORCEMENT"
26   SecRule TX:PARANOIA_LEVEL "@lt 1" "phase:2,id:920012,nolog,pass,skipAfter:END-REQUEST-920-PROTOCOL-ENFORCEMENT"
```
and
```
1440 SecRule TX:PARANOIA_LEVEL "@lt 2" "phase:1,id:920013,nolog,pass,skipAfter:END-REQUEST-920-PROTOCOL-ENFORCEMENT"
1441 SecRule TX:PARANOIA_LEVEL "@lt 2" "phase:2,id:920014,nolog,pass,skipAfter:END-REQUEST-920-PROTOCOL-ENFORCEMENT"
```
Because this rule are **before** the `skipAfter` action in case of `@lt 2`, it means this rule activated on PL 1.

> how to activate this rule in another global paranoia-level for example 2?

CRS PL follows the logic, that every rule activated which is on less or equal PL what you choose. Eg. if your PL is 4, then it means all rules are active.

> sorry but I still can not find the issue where I can put my question (besides Google groups, but it looks dead)

[here](https://github.com/coreruleset/coreruleset#contributing-to-the-crs) you can find some more info. I think Google groups is [alive](https://groups.google.com/a/owasp.org/g/modsecurity-core-rule-set-project/about).

But if you think this behavior is a bug, open an issue [here](https://github.com/coreruleset/coreruleset/issues/new?assignees=&labels=Bug&template=03_bug-report.md&title=).

**Comment by askifyouneed** [comment]
The packages from the RedHat repo are a little bit old, so I copy .conf, .data and crs-setup.conf from the 
https://github.com/coreruleset/coreruleset/archive/v3.3.0.tar.gz

```
 718 SecRule REQUEST_HEADERS:Host "@rx ^[\d.:]+$" \
 719     "id:920350,\
 720     phase:2,\
 721     block,\
 722     t:none,\
 723     msg:'Host header is a numeric IP address',\
 724     logdata:'%{MATCHED_VAR}',\
 725     tag:'application-multi',\
 726     tag:'language-multi',\
 727     tag:'platform-multi',\
 728     tag:'attack-protocol',\
 729     tag:'paranoia-level/1',\
 730     tag:'OWASP_CRS',\
 731     tag:'capec/1000/210/272',\
 732     tag:'PCI/6.5.10',\
 733     ver:'OWASP_CRS/3.3.0',\
 734     severity:'WARNING',\
 735     setvar:'tx.anomaly_score_pl1=+%{tx.warning_anomaly_score}'"
```

But it is worse, when I set PL=4 in crs-setup.conf
```
176 SecAction \
177   "id:900000,\
178    phase:1,\
179    nolog,\
180    pass,\
181    t:none,\
182    setvar:tx.paranoia_level=4"
```

I get only warning without real block:

```
[Tue Oct 06 20:42:29.971059 2020] [:error] [pid 22536:tid 140528410670848] [client 1.1.1.1:60947] [client 1.1.1.1] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/httpd/modsecurity.d/github_rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "735"] [id "920350"] [msg "Host header is a numeric IP address"] [data "10.64.40.32"] [severity "WARNING"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "1.2.3.4"] [uri "/api/settings"] [unique_id "X3y6lfFXDXTXMQ@BGmJDZAAAAFI"], referer: https://1.2.3.4/login
```

**Comment by airween** [comment]
hi @askifyouneed,

> But it is worse, when I set PL=4 in crs-setup.conf
> `176 SecAction \ 177 "id:900000,\ 178 phase:1,\ 179 nolog,\ 180 pass,\ 181 t:none,\ 182 setvar:tx.paranoia_level=4"`

this is correct,
 
> I get only warning without real block:
> 
> `[Tue Oct 06 20:42:29.971059 2020] [:error] [pid 22536:tid 140528410670848] [client 1.1.1.1:60947] [client 1.1.1.1] ModSecurity: Warning. Pattern match "^[\\\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/httpd/modsecurity.d/github_rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "735"] [id "920350"] [msg "Host header is a numeric IP address"] [data "10.64.40.32"] [severity "WARNING"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "1.2.3.4"] [uri "/api/settings"] [unique_id "X3y6lfFXDXTXMQ@BGmJDZAAAAFI"], referer: https://1.2.3.4/login`

Please check your `SecRuleEngine` setting in your modsecurity.conf file.

**Comment by askifyouneed** [comment]
```
  1 <IfModule mod_security2.c>
  2     # Default recommended configuration
  3     SecRuleEngine On
  4     #SecRuleEngine DetectionOnly
  5     SecRequestBodyAccess On
  6     SecRule REQUEST_HEADERS:Content-Type "text/xml" \
  7          "id:'200000',phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"
  8     SecRequestBodyLimit 13107200
  9     SecRequestBodyNoFilesLimit 131072
 10     SecRequestBodyInMemoryLimit 131072
 11     SecRequestBodyLimitAction Reject
 12     SecRule REQBODY_ERROR "!@eq 0" \
 13     "id:'200001', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"
 14     SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
 15     "id:'200002',phase:2,t:none,log,deny,status:400,msg:'Multipart request body \
 16     failed strict validation: \
 17     PE %{REQBODY_PROCESSOR_ERROR}, \
 18     BQ %{MULTIPART_BOUNDARY_QUOTED}, \
 19     BW %{MULTIPART_BOUNDARY_WHITESPACE}, \
 20     DB %{MULTIPART_DATA_BEFORE}, \
 21     DA %{MULTIPART_DATA_AFTER}, \
 22     HF %{MULTIPART_HEADER_FOLDING}, \
 23     LF %{MULTIPART_LF_LINE}, \
 24     SM %{MULTIPART_MISSING_SEMICOLON}, \
 25     IQ %{MULTIPART_INVALID_QUOTING}, \
 26     IP %{MULTIPART_INVALID_PART}, \
 27     IH %{MULTIPART_INVALID_HEADER_FOLDING}, \
 28     FL %{MULTIPART_FILE_LIMIT_EXCEEDED}'"
 29 
 30     SecRule MULTIPART_UNMATCHED_BOUNDARY "!@eq 0" \
 31     "id:'200003',phase:2,t:none,log,deny,status:44,msg:'Multipart parser detected a possible unmatched boundary.'"
 32 
 33     SecPcreMatchLimit 1000
 34     SecPcreMatchLimitRecursion 1000
 35 
 36     SecRule TX:/^MSC_/ "!@streq 0" \
 37             "id:'200004',phase:2,t:none,deny,msg:'ModSecurity internal error flagged: %{MATCHED_VAR_NAME}'"
 38 
 39     SecResponseBodyAccess Off
 40     SecDebugLog /var/log/httpd/modsec_debug.log
 41     SecDebugLogLevel 0
 42     SecAuditEngine RelevantOnly
 43     SecAuditLogRelevantStatus "^(?:5|4(?!04))"
 44     SecAuditLogParts ABIJDEFHZ
 45     SecAuditLogType Serial
 46     SecAuditLog /var/log/httpd/modsec_audit.log
 47     SecArgumentSeparator &
 48     SecCookieFormat 0
 49     SecTmpDir /var/lib/mod_security
 50     SecDataDir /var/lib/mod_security
 51 
 52     # ModSecurity Core Rules Set and Local configuration
 53     IncludeOptional modsecurity.d/*.conf
 54     IncludeOptional modsecurity.d/github_rules/*.conf
 55     IncludeOptional modsecurity.d/local_rules/*.conf
 56    
 57 </IfModule>
```

**Comment by airween** [comment]
I think this happens because the rule [920350](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L721) has the [`block`](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#block) action, which performs the disruptive action defined in `SecDefaultAction` [here](https://github.com/coreruleset/coreruleset/blob/v3.3/master/crs-setup.conf.example#L97). If you just simple downloaded the default config files, then it's `pass`.

**Comment by askifyouneed** [comment]
Sorry but I do not understand. In my opinion it should be blocked despite these lines in crs-setup.conf?
```
 96 SecDefaultAction "phase:1,log,auditlog,pass"
 97 SecDefaultAction "phase:2,log,auditlog,pass"
```

**Comment by airween** [comment]
> In my opinion it should be blocked despite these lines in crs-setup.conf?

I think no. Please read how [`block`](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#block) action works.

**Comment by zimmerle** [comment]
I delighted to see that knowledgement is built atop of this discuss, and @askifyouneed is mitigating doubts. Perhaps you want to move this subject to a more adequate place such as the CRS GitHub issues. There you will be able to address it better. Thank you.

**Comment by askifyouneed** [comment]
@zimmerle of course you are right, the problem is that there is no place where these questions could be set.
If you point me the right link I will move the discussion to this place :)
