### ISSUE TITLE
Failed to map segment from shared object: Permission denied) in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by Piju99** [SpiderLabs/ModSecurity#2418]
I have check _nginx -t_ and the configuration file is ok and successful. But it failed when I want to _systemctl start nginx.service_ . I got the following error.

 [emerg] 8572#0: dlopen() "/etc/nginx/modules/ngx_http_modsecurity_module.so" failed (/etc/nginx/modules/ngx_http_modsecurity_module.so: failed to map segment from shared object: Permission denied) in /etc/nginx/nginx.conf:10

**Comment by zimmerle** [comment]
You are like to be using fine access controls such as (SELinux or AppArmor). Make sure to bless **ModSecurity library** and/or **ngnix elf** with the permission to use _shared memory_. This is needed to provide communication in between the different nginx workers.

Let me know you distribution and details, I may be able to give you further assistance.

**Comment by Piju99** [comment]
Need your further assistance.

OS: CentOs 7
Nginx 1.6
Modsec v3

I have tried _setenforce 0_ but still got the error.

**Comment by ghost** [comment]
I have same issue. Can anybody help ? @zimmerle  it's possible open this ticket again ?

**Comment by zimmerle** [comment]
@msavara Do you happens to have the file ```ngx_http_modsecurity_module.so``` at ```/etc/nginx/modules/```? What is the output of: ```ldd /etc/nginx/modules/ngx_http_modsecurity_module.so```

**Comment by Piju99** [comment]
You can try to disable SELinux temporarily. It will works.. The error are caused by SELinux
