### ISSUE TITLE
MaxMind legacy database gone

### ISSUE THREAD

**Issue by dbergan** [SpiderLabs/ModSecurity#2420]
Hi,

I have a new server with ModSecurity (via WHM/cPanel) and I'd like to filter web requests from foreign countries. The [wiki here says to enable geolocation we have to get the legacy database from MaxMind](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secgeolookupdb). However, MaxMind [no longer has the legacy database for download on their website](https://dev.maxmind.com/geoip/legacy/downloadable/). And they [explained why in this blog post](https://blog.maxmind.com/2020/06/01/retirement-of-geoip-legacy-downloadable-databases-in-may-2022/).

Please help me enable geolocation on my server.

Kind regards,
David

**Comment by dbergan** [comment]
I emailed MaxMind if I could get a legacy database for this, and here is their response:

Hello David,

Apologies, but we stopped hosting and maintaining the GeoLite Legacy databases at the beginning of 2019 - we now only offer that database in the current GeoLite2 format. As a consequence, I believe that ModSecurity integration is no longer functional. Even if you were able to locate an old version of that database online somewhere, the data would be mostly outdated by now.

I'm sorry we couldn't be of more help! Please let me know if you have any questions or if I can be of further assistance.

Regards,

Nick Bishop
Customer Support
MaxMind, Inc.

**Comment by zimmerle** [comment]
Hi @dbergan,

ModSecurity 3.0 already support the new format. The version 2.x does not. However there are scripts which aiming to convert one format to another, such as - https://github.com/sherpya/geolite2legacy

**Comment by tomsommer** [comment]
See #1727
