### ISSUE TITLE
Calling libmodsecurity from my application, is it possible?

### ISSUE THREAD

**Issue by TheLegent27** [SpiderLabs/ModSecurity#2421]
Hey, it is possible to create standalone application? I was looking in [examples/](https://github.com/SpiderLabs/ModSecurity/tree/v3/master/examples/), I read some of the documentation and try to understand it. I know you can embed it into nginx or apache. But I want to call ModSecurity from my own app to check if requests are safe, it is possible?
EDIT: Maybe I specify more I want to use libmodsecurity core to process requests on my own without webserver is this possible to achieve? 
Sorry for silly question but I'm obviously missing something. 
Best regards.

**Comment by zimmerle** [comment]
Hi @TheLegent27,

Sure thing. That is  the idea behind v3. It is now a library and you can embed it on your application without a problem. The examples folder is the place to start your research.
