### ISSUE TITLE
Steps required to install nginx with modsecurity 2.9.3

### ISSUE THREAD

**Issue by satchidipu174** [SpiderLabs/ModSecurity#2422]
Hello Team,
Please share any document or link how to install Nginx with Modsecurity 2.9.3.

**Comment by zimmerle** [comment]
Hi @satchidipu174 for nginx we recommend you to use the libModSecurity aka version 3.0. 

Is there any particular reason for you to use the version 3?

**Comment by satchidipu174** [comment]
As there is no Log sanity in v3. So for Log sanity or for password encryption in audit log I want to use modsecurity 2.9.3 with Nginx. I am unable to get any proper installation documents so please share any documentation link or if there is any compatibility issue please suggest me for the same.

**Comment by satchidipu174** [comment]
Please help me to to install modsecurity 2.9 with nginx
