### ISSUE TITLE
Space in REQUEST_COOKIE is triggering 941100 XSS attack rule

### ISSUE THREAD

**Issue by danielwrayois** [SpiderLabs/ModSecurity#2426]
Hi,

The following userid cookie ```rXXAAl OnJK6gwAXXXXeAg==``` generated by Nginx appears to trigger the xss rule 941100, the uuid is generated per user session so it is intermittent, however the only consistent pattern is that the userid cookies that are blocked contain a space " ", rather than a plus "+" character.

```
[client xxx.xxx.xxx.xxx] ModSecurity: Access denied with code 403 (phase 2). detected XSS using libinjection. [file "/etc/nginx/conf.d/modsecurity/rules/3.0.2/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "37"] [id "941100"] [rev "2"] [msg "XSS Attack Detected via libinjection"] [data "Matched Data: rXXAAl OnJK6gwAXXXXeAg== found within REQUEST_COOKIES:id: rXXAAl OnJK6gwAXXXXeAg=="] [severity "2"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"] [hostname "xxx.xxx.xxx.xxx"] [uri "/summary"] [unique_id "160319605595.840815"] [ref "v668,24t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls"]
```
Nginx: 1.17.9
CRS ruleset: 3.0.2
ModSecurity: v3/master from around 29th April 2020

From testing it appears to be related to the space, which I believe with base64 encoded is a legal character, but typically ignored during parsing. I am not sure if this space is triggering a rule that would normally detect something like a CRLF-type attack i.e. if a space, page return, et al are in a value it is automatically assumed to be an XSS?

**Comment by zimmerle** [comment]
Ha @danielluke. Thanks for the report. That seems to be an [libInjection](https://github.com/libinjection/libinjection) issue. Let me dig a little bit on that and I will get back to you.

**Comment by danielluke** [comment]
Hi @zimmerle, I think you meant to tag @danielwrayois and not me :)

**Comment by zimmerle** [comment]
> Hi @zimmerle, I think you meant to tag @danielwrayois and not me :)

sorry :) 

Hi @danielwrayois :P

**Comment by zimmerle** [comment]
Kamino closed and cloned this issue to [libinjection/libinjection](https://github.com/libinjection/libinjection/issues/9)
