### ISSUE TITLE
modescurity.conf is Not Valid According to Apache2

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2429]
System: Ubuntu 20.04
ModSecurity branch: v3/master (compiled from source)
ModSecurity version: 3.0.4
Apache version: 2.4

**Describe the bug**
modsecurity.conf is not being properly interpreted by apache2.

**Logs and dumps**
_AH00526: Syntax error on line 7 of /etc/apache2/mods-available/modsecurity.conf: Invalid command 'SecRuleEngine', perhaps misspelled or defined by a module not included in the server configuration_

**To Reproduce**
I believe this error is self-explanatory; I think I am just missing a configuration detail.

**Expected behavior**
I expect apache2 to restart and run as normal, but I receive the error mentioned above. As if modsecurity.conf is not being read correctly; as if security3_module from within apache2.conf is not being correctly loaded (see the following code).

At the top of apache2.conf:
`LoadModule security3_module /usr/lib/apache2/modules/mod_security3.so`

**Rule Set (please complete the following information):**
Rule set does not apply here; error results before rule set is necessary to load.

**Additional context**
I apologize if this is not the place to ask; there does not seem to be a more useful place to pose my question, as most articles online do not use 3.0.4.

**Comment by zimmerle** [comment]
Hi @DrewPlots,

v3 for Apache is not yet stable. You can check for further info here -
https://github.com/SpiderLabs/ModSecurity-apache/blob/master/README.md#modsecurity_rules_file

**Comment by ghost** [comment]
@zimmerle 

If I am able to get ModSecurity running on apache (which I believe I'm on the verge of doing), is there a place I can submit a Wiki page on the setup for apache2?
