### ISSUE TITLE
nginx restart error: libmodsecurity.so undefined symbol ngx_module

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2438]
I sincerely thank _you smart people_ for the passion & work you commit in thought process & problem solving. I envy that level of intelligence.

Without further ado - here is my issue:

**Describe the bug**

I set libmodsecurity.so & modsecurity.conf directives in nginx.conf & restart nginx:
I get an error regarding an undefined symbol in "ngx_module".

**Logs and dumps**

`nginx: [emerg] dlsym() "/usr/local/modsecurity/lib/libmodsecurity.so", "ngx_modules" failed (/usr/local/modsecurity/lib/libmodsecurity.so: undefined symbol: ngx_modules) in /etc/nginx/nginx.conf:7`

Line 7 of nginx.conf is `load_module /usr/local/modsecurity/lib/libmodsecurity.so;`

**Server:**
 - ModSecurity version: `ModSecurity v3.0.4 with nginx-connector v3.3`
 - WebServer: `nginx 1.18.0`
 - OS: `Ubuntu 20.10 (Groovy)`
 
**Additional context**
sudo systemctl status nginx
```
Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-10-29 01:04:34 UTC; 2h 4min ago
       Docs: man:nginx(8)
    Process: 9841 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, status=1/FAILURE)
   Main PID: 687 (nginx)
      Tasks: 3 (limit: 4611)
     Memory: 14.9M
     CGroup: /system.slice/nginx.service
             ├─687 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
             ├─689 nginx: worker process
             └─690 nginx: worker process

nginxBox systemd[1]: Reloading A high performance web server and a reverse proxy server.
nginxBox nginx[9841]: nginx: [emerg] dlsym() "/usr/local/modsecurity/lib/libmodsecurity.so", "ngx_modules" failed (/usr/local/modsecurity/lib/l>
nginxBox systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
nginxBox systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
```

My nginx.conf
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

# libmodsecurity & ModSecurity-nginx modules
load_module /usr/local/modsecurity/lib/libmodsecurity.so;
load_module /etc/nginx/modsec/ngx_http_modsecurity_module.so;


events {
        worker_connections 768;
        # multi_accept on;
}

http {
        # modsec configs
        include /etc/nginx/modsec/modsecurity.conf;
        include /etc/nginx/modsec/crs-setup.conf;
        include /etc/nginx/modsec/rules/*.conf;
...
```
libmodsecurity configuration
`sudo ./configure --with-curl=/usr --with-lmdb=/usr --enable-parser-generation --enable-mutex-on-pm`
```
ModSecurity - v3.0.4-90-g2672db10 for Linux

 Mandatory dependencies
   + libInjection                                  ....v3.9.2-30-gbf234eb
   + SecLang tests                                 ....d03f4c1

 Optional dependencies
   + GeoIP/MaxMind                                 ....found
      * (MaxMind) v
         /usr/lib/x86_64-linux-gnu//libmaxminddb.so, /usr/include/x86_64-linux-gnu/, -DWITH_MAXMIND -I/usr/include/x86_64-linux-gnu/
      * (GeoIP) v1.6.12
         -lGeoIP, -I/usr/include/
   + LibCURL                                       ....found v7.68.0
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl, -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....found
      -llmdb, -DWITH_LMDB -I/usr/include
   + LibXML2                                       ....found v2.9.10
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....found v503
      -llua5.3 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -DWITH_LUA_5_3 -I/usr/include/lua5.3

 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....enabled
   + Treating pm operations as critical section    ....enabled
```

**Comment by zimmerle** [comment]
Hi @DrewPlots,

Thank you, for using ModSecurity :+1: 

It seems like you have an issue during the compilation. Is this ```libmodsecurity.so``` compiled by you? or you got it via **apt-get** ?

**Comment by airween** [comment]
@DrewPlots,

you wrote:

> My nginx.conf

```
# libmodsecurity & ModSecurity-nginx modules
load_module /usr/local/modsecurity/lib/libmodsecurity.so;
```
you can't load this module directly. The next line in your config will load this module, you can check that:

```bash
ldd /etc/nginx/modsec/ngx_http_modsecurity_module.so
```
if the .so file is there. You have to see something similar:

```
# ldd /usr/share/nginx/modules/ngx_http_modsecurity_module.so 
	...
	libmodsecurity.so.3 => /usr/local/modsecurity/lib/libmodsecurity.so (0x0000....)
```

**Comment by ghost** [comment]
Thank you @zimmerle and @airween for replying.

> 
> Hi @DrewPlots,
> 
> Thank you, for using ModSecurity 👍
> 
> It seems like you have an issue during the compilation. Is this `libmodsecurity.so` compiled by you? or you got it via **apt-get** ?

@zimmerle 

Yes, I compiled libmodsecurity with the following command:

`sudo ./configure --with-curl=/usr --with-lmdb=/usr --enable-parser-generation --enable-mutex-on-pm`

The configuration output is listed at the bottom of the first post.

I also did not receive any explicit error, however I did receive these messages after ./configure:

```
checking if libcurl is linked with gnutls... no
checking string usability... no
checking string presence... no
checking for string... no
checking iostream usability... no
checking iostream presence... no
checking for iostream... no
checking for dlltool... no
checking for sysroot... no
checking if mt is a manifest tool... no
checking if gcc supports -fno-rtti -fno-exceptions... no
checking whether -lc should be explicitly linked in... no
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking whether a statically linked program can dlopen itself... no
```

These are the dependencies I have installed:
```
automake
bison
build-essential
dh-autoreconf
doxygen
flex
git
libcurl4-openssl-dev
libgeoip-dev
liblmdb-dev
liblua5.3-dev
libmaxminddb-dev
libpcre3-dev
libxml2-dev
libyajl-dev
lua5.3
pkg-config
valgrind
```
>
> ...
> you can't load this module directly. The next line in your config will load this module, you can check that:
> 
> ```shell
> ldd /etc/nginx/modsec/ngx_http_modsecurity_module.so
> ```
> ...

@airween 

This resolved the undefined symbol issue. However, now I am receiving this error:

`nginx: [emerg] unknown directive "SecRuleEngine" in /etc/nginx/modsec/modsecurity.conf:54`

**Comment by zimmerle** [comment]
> -enable-parser-generation --enable-mutex-on-pm

Is that any reason for you to use: ```--enable-parser-generation --enable-mutex-on-pm```  the ```--enable-mutex-on-pm``` this option will make your ModSecurity slower.

Once you have libModSecurity workable you have to get the nignx connector workable. That is the one that you need to load on your nginx - 
https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by ghost** [comment]
> 
>
> > -enable-parser-generation --enable-mutex-on-pm
> 
> Is that any reason for you to use: `--enable-parser-generation --enable-mutex-on-pm` the `--enable-mutex-on-pm` this option will make your ModSecurity slower.
> 
> Once you have libModSecurity workable you have to get the nignx connector workable. That is the one that you need to load on your nginx -
> https://github.com/SpiderLabs/ModSecurity-nginx

I'm looking to post a Wiki page once I resolve my errors; that is the main reason for including all the extra features (mainly to make note of working dependencies).

I removed the old libmodsecurity.so & recompiled it using `sudo ./configure --with-curl=/usr --with-lmdb=/usr --enable-parser-generation`.
I also placed the crs-setup.conf & rules includes in modsecurity.conf and added the `modsecurity on;` and pasted the correct intiation for modsecurity `modsecurity_rules_file` directive to the nginx.conf.

I have developed a new error.
Let me know if I should submit this issue for help at https://security.stackexchange.com/questions/tagged/owasp-crs.

```
nginx: [emerg] "modsecurity_rules_file" directive Rules error.
File: /etc/nginx/modsec/rules/REQUEST-913-SCANNER-DETECTION.conf.
Line: 33. Column: 34. Failed to open file: scanners-user-agents.data.
Looking at: 'scanners-user-agents.data', 'scanners-user-agents.data', '/etc/nginx/modsec/rules/scanners-user-agents.data', '/etc/nginx/modsec/rules/scanners-user-agents.data'.
in /etc/nginx/nginx.conf:19
```
Line 33 of REQUEST-913-SCANNER-DETECTION.conf is:
`SecRule REQUEST_HEADERS:User-Agent "@pmFromFile scanners-user-agents.data" \`

Line 19 of nginx.conf is where `modsecurity_rules_file /etc/nginx/modsec/modsecurity.conf;` lies.
At the top of modsecurity.conf is where I've placed the includes for crs-setup & rules:
```
include /etc/nginx/modsec/crs-setup.conf
include /etc/nginx/modsec/rules/*.conf
```

**Comment by zimmerle** [comment]
Do you have the file **scanners-user-agents.data** on your disk?

**Comment by ghost** [comment]
Thank you for that!

I forgot to copy the entire rules directory from coreruleset.

Error resolved by removing /etc/nginx/modsec/rules and using `sudo cp -r /opt/coreruleset/rules /etc/nginx/modsec/`.
