### ISSUE TITLE
Add Wiki Page | Request

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2439]
Apologies for making an issue report that isn't related to an issue.
However, I am trying to locate a way to add a Wiki page of the nginx setup guide I've written for the ModSecurity community.

It is formatted in AsciiDoc and is a complete guide (not a Compilation Recipe).
Where is the correct place to submit this document to get it online?

**Comment by zimmerle** [comment]
Hi @DrewPlots,

Yep, the wiki page is welcomed. You can try the ModSecurity-nginx wiki, here:
https://github.com/SpiderLabs/ModSecurity-nginx/wiki

**Comment by ghost** [comment]
Unfortunately for me, there is no "Edit" or green "New Page" button for me on the ModSecurity-nginx or ModSecurity Wiki pages. There are those buttons on the ModSecurity-apache Wiki, however.

Edit:
I reopened this issue because I want privileges to post the installation instructions I have created for the ModSecurity Wiki.

**Comment by DrewPlots** [comment]
Here is the guide: https://pastebin.com/Es0aEHGq

Perhaps someone with WIki priviliges can post it (using AsciiDoc) on the ModSecurity Wiki.
All the necessary information is included (WAF, OS, Server, Module, and Rule Set).

Please do not attribute the work to me.

Don't mind the content warning; it's safe.

**Comment by DrewPlots** [comment]
I cannot access the Wiki, so I provided the guide via pastebin; case closed.
