### ISSUE TITLE
Rules blocking Google OAuth2 redirect (callback) URLs

### ISSUE THREAD

**Issue by tanvir-retailai** [SpiderLabs/ModSecurity#2448]
**Describe the bug**

I implemented Google OAuth2 authentication on my website. After user authenticates successfully on Google login screen, Google redirects the browser to an URL on my site that looks like this: https://site/somepath/somescript.php?state=#####&code=#####&scope=email+profile+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email

(https://site/somepath/somescript.php is predefined by me, but all the parameters after "?" are appended by Google and necessary for the authentication to work). However, the request is blocked and I get a 403 error.

The part "userinfo.profile" is what causes the issue - because of presence of the ".profile" string in the URL. If I manually copy the URL and remove the "+https://www.googleapis.com/auth/userinfo.profile" part, then the request gets through (however, there is no way to tell Google to not use that part in the URL).

The particular string "https://www.googleapis.com/auth/userinfo.profile" should be an exception form the general rule that blocks ".profile".

**Logs and dumps**

---4GyeTXdD---F--
HTTP/2.0 403
Server: nginx
Date: Wed, 11 Nov 2020 01:56:25 GMT
Content-Length: 548
Content-Type: text/html
Connection: close

---4GyeTXdD---H--
ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `lfi-os-files.data' against variable `ARGS:scope' (Value: `email profile openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/ (16 characters omitted)' ) [file "/etc/nginx/modsec/owasp-modsecurity-crs-3.0.2/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "84"] [id "930120"] [rev "4"] [msg "OS File Access Attempt"] [data "Matched Data: .profile found within ARGS:scope: email profile openid https:/www.googleapis.com/auth/userinfo.email https:/www.googleapis.com/auth/userinfo.profile"] [severity "2"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "OWASP_CRS/WEB_ATTACK/FILE_INJECTION"] [tag "WASCTC/WASC-33"] [tag "OWASP_TOP_10/A4"] [tag "PCI/6.5.4"] [hostname "10.146.0.6"] [uri "/ja/admin/auth/google/callback"] [unique_id "1605059785"] [ref "o106,8v167,116t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/etc/nginx/modsec/owasp-modsecurity-crs-3.0.2/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "44"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "10.146.0.6"] [uri "/ja/admin/auth/google/callback"] [unique_id "1605059785"] [ref ""]

Output of:
 1. AuditLogs
 
**Expected behavior**

Modsecurity should not block google ouath redirect call as 403

**Server (please complete the following information):**
 - ModSecurity version (and connector): ModSecurity v3.0.2 with ]
 - WebServer: nginx/1.18.0
 - OS (and distro): Centos 7 (5.7.9-1.el7.elrepo.x86_64)

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? Yes
 - What is the version number? https://github.com/coreruleset/coreruleset.git [v3.4/dev]

**Comment by martinhsv** [comment]
Hello @tanvir-retailai ,

It looks like you are inquiring about a specific CRS rule.  CRS rules are handled by a separate group:
https://github.com/coreruleset/coreruleset

They have a reporting mechanism including for false positives.

In general, generic rule sets (like CRS) can be very useful but they often do generate at least some false positives that necessitate rule customization for a particular deployment.

In your case you could consider an exclusion rule that is something like:   test for your path (somepath/somescript.php) and then have as one of the actions ctl:ruleRemoveTargetById to exclude that particular query arg from analysis by that particular rule.

**Comment by deployer-retailai** [comment]
Hi @martinhsv,

Thank you for your valuable response.

I will contact the group which you recommended.

**Comment by tanvir-retailai** [comment]
Hi @martinhsv,

Thank you for your valuable response.

I will contact the group which you recommended.
