### ISSUE TITLE
hmac settings failed

### ISSUE THREAD

**Issue by pengyejun** [SpiderLabs/ModSecurity#2450]
**Describe the bug**

reference the link https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/modsecurity-advanced-topic-of-the-week-hmac-token-protection/
I try to configure hmac in modsecurity, but the homepage is loaded disorderly。

**Logs and dumps**

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs
 3. Error logs
 4. If there is a crash, the core dump file.
debug log
[modsecurity_debug.log](https://github.com/SpiderLabs/ModSecurity/files/5529172/modsecurity_debug.log)
audit log
[modsec_audit.log](https://github.com/SpiderLabs/ModSecurity/files/5529183/modsec_audit.log)
nginx error log
[error.log](https://github.com/SpiderLabs/ModSecurity/files/5529188/error.log)

_Notice:_ Be carefully to not leak any confidential information.

**Expected behavior**

**Server (please complete the following information):**
 - ModSecurity version (and connector): 2.9.2
 - WebServer: [e.g. nginx-1.15.5]nginx 1.11.12
 - OS (and distro): [e.g. Linux, archlinux] MacOS

hmac_debug file

![hmac](https://user-images.githubusercontent.com/31479786/98913444-54ee5580-2502-11eb-9414-19c00548ded4.png)
hmac config file

![hmac_config](https://user-images.githubusercontent.com/31479786/98913454-5881dc80-2502-11eb-970b-5755b0e1b2ed.png)

old page
<img width="1773" alt="old_page" src="https://user-images.githubusercontent.com/31479786/98913620-8cf59880-2502-11eb-9bc4-27f27d522025.png">

destory page
<img width="1437" alt="destroy" src="https://user-images.githubusercontent.com/31479786/98913649-9a128780-2502-11eb-8cd5-f3299cb2190d.png">

**Comment by ghost** [comment]
I'm going to ask forgiveness from the DevGods if I am wrong here.

Does this potentially have to do with the ModSecurity dependency of the _flex_ package and configure option "--enable-parser-generation"?

**Comment by martinhsv** [comment]
Hello @pengyejun ,

I haven't examined your posting in detail, but I did notice immediately:
```
ModSecurity version (and connector): 2.9.2
WebServer: [e.g. nginx-1.15.5]nginx 1.11.12
```

If you are you really using nginx with ModSecurity v2.9.2, please be aware that that is not recommended.

With nginx, it is recommended to use ModSecurity v3.x

**Comment by pengyejun** [comment]
Hi @martinhsv 
   thank you for your reply, But due to some historical reasons, I cannot quickly upgrade to v3 version now. Is there any other alternative?

**Comment by martinhsv** [comment]
Not really, I'm afraid.  Again, it's simply a not-recommended (and hence not-supported) deployment.

For use with nginx, please upgrade to ModSecurity v3.0.x.  Thanks.
