### ISSUE TITLE
Can modsecurity-nginx be used in a production environment now？

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2452]
Can modsecurity-nginx be used in a production environment now? And what are the benefits of business rules? what are the advantages of modsecurity business rules compared with commercial waf products on the market?

**Comment by zimmerle** [comment]
Hi @Hello-Linux,

Yes, ModSecurity v3 for nginx is production ready.

As of the business rules, I recommend you to contact which individual provider in their own site and ask those questions. For Trustwave commercial rules you can go ever here - https://modsecurity.org/commercial-rules.html#:~:text=Trustwave%20now%20provides%20a%20commercial,Cross%2Dsite%20Scripting%20(XSS)
