### ISSUE TITLE
[Question]Is branch "Master" is more stable than branch "3.0.4"? I need install on ubuntu with nginx.

### ISSUE THREAD

**Issue by liuyi** [SpiderLabs/ModSecurity#2457]
NOT BUG, Just want to know which branch can be use in production env.

Thanks!

**Comment by zimmerle** [comment]
Hi @liuyi,

v3/master contains the latest modification on v3. If you know well ModSecurity you can have it working. The difference may not be applicable to stability but other concerns, here are the differences from the released version to v3/master -



https://github.com/SpiderLabs/ModSecurity/blob/afefda53c69bb17e2ec16d24dd6fbc2c8fd7d063/CHANGES#L4-L33

👍
