### ISSUE TITLE
Modsecurity Lua External Module Usage

### ISSUE THREAD

**Issue by frkngksl** [SpiderLabs/ModSecurity#2460]
Hi,

I want to develop some rules using Lua scripts. All things in terms of Lua are okay, ModSecurity sees and executes rules, runs the Lua script etc. However, whenever I want to add a Lua module that is downloaded and installed with using Luarocks packet manager. For example let's say this module is 'bit' module that allows user to perform some bit manipulations. I add the following line to script:

`local bits = require "bit"`

However, in debug log, it says:

>  module 'bit' not found:

So my question is what is the problem? Doesn't Modsecurity support external Lua module usage? Thanks in advance for your answers.

**Comment by zimmerle** [comment]
Hi @frkngksl,

Is **luarocks** installed in the system or for your user? Remember that your webserver user is very likely to be a different user with different *env* vars.

**Comment by frkngksl** [comment]
Hi @zimmerle,

Thanks for your help, I wasn't aware that I should also change the Apache's env vars. However, there is still an error that avoids me to run my script. The debug.log says that:

`/usr/local/lib/lua/5.1/bit.so: undefined symbol: luaL_register`

Do you know anything related to the cause?

**Comment by frkngksl** [comment]
I guess the problem was solved after installing lua 5.2 instead of lua 5.1 . Should I report it as a bug?

**Comment by zimmerle** [comment]
That is very likely to be an environment variable problem as well. Check the **LD_LIBRARY_PATH** env. variable. It should contains a path towards you _lua*.so_ file
