### ISSUE TITLE
MediaWiki redirects to the homepage after editing the post (with many external links)

### ISSUE THREAD

**Issue by ofmarconi** [SpiderLabs/ModSecurity#2462]
**Describe the bug**

Hi, I don't have anything to do with security, I updated it as WHM sent it to "OWASP CRS v3.x for ModSec 2.9 (via RPM)"

It turns out that now I can't put many external links in a publication in MEDIAWIKI, would that have any solution besides disabling security?

Thanks!

**Logs and dumps**

https://imgur.com/a/mca3e7m

The interesting thing is that this is not my IP, so why does another IP appear?

Thank you for helping lay people like me.

**Comment by zimmerle** [comment]
Hi @ofmarconi,

I think you are facing some issues with the rules. The best place to ask such question is on the OWASP CRS project.

**Comment by ofmarconi** [comment]
THX 👍
