### ISSUE TITLE
[emerg] 1035#1035: unknown directive "modsecurity"

### ISSUE THREAD

**Issue by super-23** [SpiderLabs/ModSecurity#2466]
[emerg] 1035#1035: unknown directive "modsecurity"

This error appears in the nginx log.

What's the problem?

**Comment by zimmerle** [comment]
@super-23 it is very likely that you don't have the ModSecurity connector running in yours nginx.

Here is the manual with others configuration directives -
https://github.com/SpiderLabs/ModSecurity-nginx#usage

Make sure you have the module loaded.
