### ISSUE TITLE
Question regarding rotating logs of modsec

### ISSUE THREAD

**Issue by albgen** [SpiderLabs/ModSecurity#2470]
Hello dears,

i'm running modsec on latest nginx on centos7. The problem is that i cannot rotate the logs with logrotate.

My logrotate config file for modsec is the following:

> /var/log/modsec_audit.log {
> daily
> rotate 7
> missingok
> compress
> postrotate
> [ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`
> endscript
> }

**Comment by zimmerle** [comment]
Hi @albgen,

libModSecurity is not implementing the support for ``` kill -USR1```. Try **nginx reload** instead.

To follow the development of this feature, keep an eye on this issue: #2304

**Comment by albgen** [comment]
i tried with the following config 
```
/var/log/modsec_audit.log {
daily
rotate 7
missingok
compress
postrotate
/usr/sbin/nginx -s reload
endscript
}
```
but the result was the following which means the new log for the day is 0:

![image](https://user-images.githubusercontent.com/7231968/101474062-e5c22080-394a-11eb-8579-c7a2d9a9ed58.png)
