### ISSUE TITLE
Incorrect function

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#2477]
In msc_logging.c, line 1458:
msr_log(..., apr_proc_mutex_lockfile(msr->modsecurity->auditlog_lock), ...

apr_proc_mutex_lockfile() must be replaced by apr_global_mutex_lockfile() because msr->modsecurity->auditlog_lock is of type 'apr_global_mutex_t *'.
It simply avoids a warning but could become a bug in future version of libapr.

**Comment by zimmerle** [comment]
There is no such content on line 1458. At 1458 that is what we have -
https://github.com/SpiderLabs/ModSecurity/blob/12cefbd70f2aab802e1bff53c50786f3b8b89359/apache2/msc_logging.c#L1457-L1459

If we rollback the code to March of 2016 ([2.9.1](https://github.com/SpiderLabs/ModSecurity/tree/v2.9.1)), the content of 1458 is something somewhat similar to the content that you have highlighted -
https://github.com/SpiderLabs/ModSecurity/blob/88bffb1e3eda8cc5e24965c9e06dec15f91be11a/apache2/msc_logging.c#L1457-L1459

But, as you can see, it is using the **apr_global_mutex_unlock** not **apr_proc_mutex_lockfile** as you claim. I have rollback the code for years and yet did not saw the **apr_proc_mutex_lockfile**.

Like the other issues you have open weekly, it seems like you have your custom version of ModSecurity, with its problems.

Please check the latest version before report an issue. It worth reading the [GitHub markdown](https://guides.github.com/features/mastering-markdown/) document. If you do the exercise of reference the actual real code, you will have better issues report.

**Comment by marcstern** [comment]
Indeed, sorry for the false positive, I mixed up 2 repos.
