### ISSUE TITLE
Not able to remove 200003 with ruleRemoveById

### ISSUE THREAD

**Issue by skwokie** [SpiderLabs/ModSecurity#2481]
**Describe the bug**

200003 still being triggered after it has been removed in REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf as followed:
```
SecRule REQUEST_URI "@beginsWith /xx/action/user/requestnewpassword" \
        "phase:2,log,pass,id:26620,ctl:ruleRemoveById=200003"
```

**Logs and dumps**

Output of:
 AuditLogs
 ```
 ModSecurity: Access denied with code 400 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `MULTIPART_STRICT_ERROR' (Value: `1' ) [file "/usr/local/openresty/nginx/conf/modsecurity.conf"] [line "61"] [id "200003"] [rev ""] [msg "Multipart request body failed strict validation: \\x0a    XX 1, \\x0a    XX 0, \\x0a    XX 0, \\x0a    XX 0, \\x0a    DA 0, \\x0a    HF 0, \\x0a    LF 0, \\x0a    SM 0, \\x0a    IQ 0, \\x0a    IP 0, \\x0a    XX 9, \\x0a    XX "] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "172.18.0.2"] [uri "/xx/action/user/requestnewpassword"] [unique_id "160827094182.915348"] [ref "v402,1"]
 ```
 Error logs
 ```
 2020/12/17 21:55:41 [error] 258#258: *1903220373 [client xx.xx.xx.xx] ModSecurity: Access denied with code 400 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `MULTIPART_STRICT_ERROR' (Value: `1' ) [file "/usr/local/openresty/nginx/conf/modsecurity.conf"] [line "61"] [id "200003"] [rev ""] [msg "Multipart request body failed strict validation: \\x0a    XX 1, \\x0a    XX 0, \\x0a    XX 0, \\x0a    XX 0, \\x0a    DA 0, \\x0a    HF 0, \\x0a    LF 0, \\x0a    SM 0, \\x0a    IQ 0, \\x0a    IP 0, \\x0a    XX 9, \\x0a    XX "] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "172.18.0.2"] [uri "/xx/action/user/requestnewpassword"] [unique_id "160827094182.915348"] [ref "v402,1"], client: xx.xx.xx.xx, server: www.xyz.com, request: "POST /xx/action/user/requestnewpassword HTTP/1.1", host: "www.xyz.com", referrer: "https://www.xyz.com/xx/account/forgotten_password.php"
 ```
 
**Expected behavior**

Should the rule be disabled for the specified uri?

**Server (please complete the following information):**
 - ModSecurity version (and connector): Modsec verion: v3.0.3
 - WebServer: Nginx version: 1.13.6
 - OS (and distro): Ubuntu 18.04.3

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? owasp modsecurity
 - What is the version number? crs 3.0.2

**Comment by martinhsv** [comment]
Hi @skwokie ,

You are likely experiencing an effect of rule execution order.  Since 200003 (assuming you're using the rule with that id from modsecurity.conf-recommended) and your exception rule are both phase:2 rules, the order in which the rules are included matters.

In your case, likely the simplest way to address this is to change your exclusion rule to run in phase:1.  Since it is testing REQUEST_URI, the necessary information to run the rule already exists at that phase.

**Comment by skwokie** [comment]
Thx, @martinhsv .
