### ISSUE TITLE
  Can ModSecurity create a GUI panel?

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2484]
Can ModSecurity create a GUI panel?

**Comment by zimmerle** [comment]
I am afraid I did not get exactly what you meant. Do you mind to explain a little bit what you want to accomplish? Is that a UI for logging? ui for rules configuration? ui using ModSecurity _secrule_ language?

**Comment by airween** [comment]
> Can ModSecurity create a GUI panel?

No.

May be you're looking something like this:

https://fossil.include-once.org/modseccfg/index

It's available through PyPI:

https://pypi.org/project/modseccfg/

HTH.

**Comment by zimmerle** [comment]
@Hello-Linux: Please re-open the issues if you did not found your answer already.
