### ISSUE TITLE
SecConnEngine

### ISSUE THREAD

**Issue by mr-djan** [SpiderLabs/ModSecurity#2487]
ModSecurity for Apache/2.9.1
Apache/2.4.25
Debian 9.13

SecConnEngine, SecConn[Read|Write]StateLimit - does not work and does not detect slowhttp dos attack.
I test my web server with - slowhttptest -c 1000 -B -g -o my_server_stats -i 110 -r 200 -s 8192 -t FAKEVERB -u https://tost.ua -x 10 -p 3
After starting my web server immediately stops serving content - [mpm_prefork:error] [pid 16788] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting.
My /etc/modsecurity/modsecurity.conf
SecConnEngine On
SecConnReadStateLimit 50
SecConnWriteStateLimit 50

Only these options do not work with the rest of the problems. Thanks for any help.

**Comment by zimmerle** [comment]
Hi @d-mihaylenko is there any reason why you are not using [v2.9.3](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.3)?

**Comment by mr-djan** [comment]
> v2.9.3

Ok, i upgrade and create new https://github.com/SpiderLabs/ModSecurity/issues/2488
