### ISSUE TITLE
SecConnEngine not work with ModSecurity for Apache/2.9.3

### ISSUE THREAD

**Issue by mr-djan** [SpiderLabs/ModSecurity#2488]
ModSecurity for Apache/2.9.3
Apache/2.4.38
Debian 10.7

SecConnEngine, SecConn[Read|Write]StateLimit - does not work and does not detect slowhttp dos attack.
I test my web server with - slowhttptest -c 1000 -B -g -o my_server_stats -i 110 -r 200 -s 8192 -t FAKEVERB -u https://tost.ua -x 10 -p 3
After starting my web server immediately stops serving content - [mpm_prefork:error] [pid 16788] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting.
My /etc/modsecurity/modsecurity.conf
SecConnEngine On
SecConnReadStateLimit 50
SecConnWriteStateLimit 50

Only these options do not work with the rest of the problems. Thanks for any help.

**Comment by zimmerle** [comment]
I have tested it here, and it seems to be working as expected. Check the attached video.

https://user-images.githubusercontent.com/428268/103562750-5c930080-4e9a-11eb-9b61-669e14a2730f.mp4

**Comment by mr-djan** [comment]
> I have tested it here, and it seems to be working as expected. Check the attached video.
> 
>  output.mp4

Thanks for the help. It turns out that I enabled it incorrectly or did not enable it at all. Can you please help with the configuration?

I added three lines in the file /etc/modsecurity/modsecurity.conf
```
SecConnEngine On
SecConnReadStateLimit 50
SecConnWriteStateLimit 50
```

Next, I use the file in /etc/apache2/mods-enabled/security2.conf

```
cat security2.conf
<IfModule security2_module>
        # Default Debian dir for modsecurity's persistent data
        SecDataDir /var/cache/modsecurity

    # Include all the * .conf files in / etc / modsecurity.
        # Keeping your local configuration in that directory
        # will allow for an easy upgrade of THIS file and
        # make your life easier
        IncludeOptional /etc/modsecurity/*.conf

        # Include OWASP ModSecurity CRS rules if installed
        IncludeOptional /usr/share/modsecurity-crs/*.load
    IncludeOptional "/usr/share/modsecurity-crs/*.conf"
</IfModule>
```


Am I doing something wrong? I also attached modsecurity directory.
[modsec.tar.gz](https://github.com/SpiderLabs/ModSecurity/files/5766087/modsec.tar.gz)

**Comment by zimmerle** [comment]
> Thanks for the help. It turns out that I enabled it incorrectly or did not enable it at all. Can you please help with the configur

My pleasure. In that cases, I prefer to isolate blocks of the configuration to narrow down the problem. I would place the the **SecConn** configurations inside the ```<IfModule security2_module>``` block. Afterwards, I would enable the external configurations one-by-one. Initially I would use: 

```
<IfModule security2_module>
   SecConnEngine On
   SecConnReadStateLimit 50
   SecConnWriteStateLimit 50
</IfModule>
```
Once that is working I would move forward to include it as external file, and so on... The wildcard inclusion (*) sometimes lead to you including something that overwrites a previous configuration.

Also, make sure to test the web-server from a second machine. The machine that is performing the attack is going to be blocked.

**Comment by mr-djan** [comment]
> > Thanks for the help. It turns out that I enabled it incorrectly or did not enable it at all. Can you please help with the configur
> 
> My pleasure. In that cases, I prefer to isolate blocks of the configuration to narrow down the problem. I would place the the **SecConn** configurations inside the `<IfModule security2_module>` block. Afterwards, I would enable the external configurations one-by-one. Initially I would use:
> 
> ```
> <IfModule security2_module>
>    SecConnEngine On
>    SecConnReadStateLimit 50
>    SecConnWriteStateLimit 50
> </IfModule>
> ```
> 
> Once that is working I would move forward to include it as external file, and so on... The wildcard inclusion (*) sometimes lead to you including something that overwrites a previous configuration.
> 
> Also, make sure to test the web-server from a second machine. The machine that is performing the attack is going to be blocked.



I made the configuration as you wrote and still does not work, the server does not block the attacking host, help please.

<img width="1440" alt="Screenshot 2021-01-04 at 20 07 48" src="https://user-images.githubusercontent.com/17220673/103565197-924ede00-4ec8-11eb-88ed-28af0941d52b.png">
<img width="606" alt="Screenshot 2021-01-04 at 20 07 57" src="https://user-images.githubusercontent.com/17220673/103565199-93800b00-4ec8-11eb-9341-493639368a04.png">

**Comment by zimmerle** [comment]
> 
> <img alt="Screenshot 2021-01-04 at 20 07 57" width="606" src="https://user-images.githubusercontent.com/17220673/103565199-93800b00-4ec8-11eb-9341-493639368a04.png">

What if you disable all the others configurations by removing all the **IncludeOptional**?

**Comment by mr-djan** [comment]
> > <img alt="Screenshot 2021-01-04 at 20 07 57" width="606" src="https://user-images.githubusercontent.com/17220673/103565199-93800b00-4ec8-11eb-9341-493639368a04.png">
> 
> What if you disable all the others configurations by removing all the **IncludeOptional**?

Yes, and I have the same result(
<img width="261" alt="Screenshot 2021-01-04 at 20 44 01" src="https://user-images.githubusercontent.com/17220673/103568101-a3e6b480-4ecd-11eb-984d-c2f840d1fc6b.png">

**Comment by zimmerle** [comment]
What if you remove the IfModule? How are you testing that the server is hanging?

**Comment by mr-djan** [comment]
> What if you remove the IfModule? How are you testing that the server is hanging?

Nothing, its still not work, but other modsecurity options and rules works without problems, I have problems only with SecConnEngine
I'm testing with - slowhttptest -c 1000 -B -g -o my_server_stats -i 110 -r 200 -s 8192 -t FAKEVERB -u https://test.com.ua -x 10 -p 3
and after that in /var/log/apache2/error.log I saw:
[mpm_prefork:error] [pid 27648] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
Its all, after that apache2 stops responding.

**Comment by zimmerle** [comment]
> I'm testing with - slowhttptest -c 1000 -B -g -o my_server_stats -i 110 -r 200 -s 8192 -t FAKEVERB -u https://test.com.ua -x 10 -p 3
> and after that in /var/log/apache2/error.log I saw:
> [mpm_prefork:error] [pid 27648] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting

I would expect to have something like this -
```
... ModSecurity: Access denied with code 400. Too many threads [51] of 50 allowed in WRITE state from ::1 - Possible DoS Consumption Attack [Rejected]
```

**Comment by mr-djan** [comment]
> > I'm testing with - slowhttptest -c 1000 -B -g -o my_server_stats -i 110 -r 200 -s 8192 -t FAKEVERB -u https://test.com.ua -x 10 -p 3
> > and after that in /var/log/apache2/error.log I saw:
> > [mpm_prefork:error] [pid 27648] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
> 
> I would expect to have something like this -
> 
> ```
> ... ModSecurity: Access denied with code 400. Too many threads [51] of 50 allowed in WRITE state from ::1 - Possible DoS Consumption Attack [Rejected]
> ```

I am also waiting for this, but whatever I do, nothing helps
Other options works correctly, like this
[Mon Jan 04 23:48:21.929912 2021] [:error] [pid 30141] [client 10.0.174.221:56041] [client 10.0.174.221] ModSecurity: Warning. Pattern match "^$" at REQUEST_HEADERS:User-Agent. [file "/etc/modsecurity/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "671"] [id "920330"] [msg "Empty User Agent Header"] [severity "NOTICE"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/EMPTY_HEADER_UA"] [hostname "www.lantrace.com.ua"] [uri "/"] [unique_id "X-ONJR8EYp2eokSO983ZEAAAAAE"]

**Comment by zimmerle** [comment]
@d-mihaylenko it could be something related to your general Apache configuration. Are they __SecConn*__ directives expressed on the main Apache configuration? You may want to temporarily disable the vhosts, making the configuration as plain as possible.

**Comment by mr-djan** [comment]
> @d-mihaylenko it could be something related to your general Apache configuration. Are they **SecConn*** directives expressed on the main Apache configuration? You may want to temporarily disable the vhosts, making the configuration as plain as possible.

I brought up a test VM today. I installed only Apache and modsecurity there and still the Secconn does not work. I tried to enable it both in the Apache modules and in the modsecurity config. The result is the same. Please help me with correct config for apache.

**Comment by mr-djan** [comment]
Help me please, anybody. SeccConnEngine it still doesn't work, which configuration I would not use

**Comment by zimmerle** [comment]
Hi @d-mihaylenko,

Did you managed to solve the problem?  Is it possible for you to upgrade Apache to __Apache/2.4.46__ ?

**Comment by zimmerle** [comment]
I am assuming that the problem was resolve, closing the issue. Please re-open if that still an issue.
