### ISSUE TITLE
Modsecurity Supported protocols 

### ISSUE THREAD

**Issue by cyndy08** [SpiderLabs/ModSecurity#2493]
Hello everyone,

i want to know if Modsecurity supports other protocols than HTTP like FTP, DNS , LDAP or anything else.
And also where can i find information about the supported encoding-types in Modsecurity?

Any help will be appreciated.
Thank you

**Comment by airween** [comment]
> if Modsecurity supports other protocols than HTTP like FTP, DNS , LDAP or anything else.

it supports only HTTP.

You can take a look to Zorp if you want other protocols:

http://balasys.github.io/zorp/about/

It has a commercial support, which supports many-many others.

**Comment by zimmerle** [comment]
@cyndy08 what exactly you meant by encoding-types? like **multipart/form-data**?

**Comment by cyndy08** [comment]
> > if Modsecurity supports other protocols than HTTP like FTP, DNS , LDAP or anything else.
> 
> it supports only HTTP.
> 
> You can take a look to Zorp if you want other protocols:
> 
> http://balasys.github.io/zorp/about/
> 
> It has a commercial support, which supports many-many others.

Thank you, i will have a look at it.

**Comment by cyndy08** [comment]
> @cyndy08 what exactly you meant by encoding-types? like **multipart/form-data**?

@zimmerle yes i mean like application/x-www-form-urlencoded, multipart/form-data, application JSON or anything else.

**Comment by zimmerle** [comment]
Implementation-wise we call those as **request body processor**; Currently, we support the following -

   - JSON - [request_body_processor/json.cc](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/request_body_processor/json.cc)
   - XML - [request_body_processor/xml.cc](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/request_body_processor/xml.cc)
   - Multipart - [request_body_processor/multipart.cc](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/request_body_processor/multipart.cc)


Multipart is little different from JSON or XML; JSON and XML are specified on the [modsecurity.conf-recommended](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended) -

https://github.com/SpiderLabs/ModSecurity/blob/310cbf899bf55f101cfa595b6da5ed1cd0af90fa/modsecurity.conf-recommended#L22-L23

https://github.com/SpiderLabs/ModSecurity/blob/310cbf899bf55f101cfa595b6da5ed1cd0af90fa/modsecurity.conf-recommended#L29-L30

As for the protocols that ModSecurity supports, It was build to interpret and dissect HTTP requests. Currently we are aware of people using it with different protocols - HTTP/0.9, HTTP/1.0, HTTP/1.1, HTTP/2.0 and [HTTP/3.0](https://github.com/SpiderLabs/ModSecurity-nginx/pull/225/commits/7b8d7de4d8ca197f2066f13710de87e0597a9804)

**Comment by cyndy08** [comment]
@zimmerle  
Is JSON also supported for the responses? Or is it only possible for requests processing?

**Comment by zimmerle** [comment]
Not at this point. There is a request to support the JSON decoding more generically, allowing it to apply to generic fields via transformation. The issue is here: #687. We miss effort to have it implemented. 

IMHO, the inspection of the response body struct is less prevalent. For example, when the **response body** is inspected against data leak, the **rule writer** is looking for a pattern like a _credit card_ number or a _valid id_; in that scenario, the data format is less relevant.

Given your questions, it sounds like you are written a fantastic dissertation :) a pleasure to help.

**Comment by cyndy08** [comment]
I really appreciate your help and your answers help me a lot for my dissertation on Modsecurity.

 That means there is actually no support for response processing in Modsecurity but there is a general way to inspect a response body against data leak. Am i right?
Related to my issue #2483 the response body contains data leak because the response of the webserver gives information about the database.
Why is this response not block by the waf? Is there also a pattern for such a case? 

Once again thanks for answering my question
