### ISSUE TITLE
Improper handling of relative paths by exec action

### ISSUE THREAD

**Issue by azurit** [SpiderLabs/ModSecurity#2495]
**Describe the bug**

When using `exec` action with relative path to the Lua script, the absolute path is resolved to "CWD of running process + path specified as argument". I believe this is a bug as all other places where relative path can be specified (for example `SecRuleScript`) are resolved to "path of file in which rule is saved (parent file) + path specified as argument".

**Expected behavior**

Resolving of relative paths should be consistent.

**Server (please complete the following information):**
 - ModSecurity version (and connector): 2.9.3, embedded
 - WebServer: Apache 2.4
 - OS (and distro): Linux

**Comment by zimmerle** [comment]
@azurit 

The path resolution for _external resources_ in v2 depends on each feature. That is different for version 3, where a pattern is in place -

https://github.com/SpiderLabs/ModSecurity/blob/310cbf899bf55f101cfa595b6da5ed1cd0af90fa/src/utils/system.cc#L65-L108 

The general rule in version 3 - 

   -  absolute path;
   -  relative to the current dir;
   -  relative to the configuration file.

Changing in version 2 is undesired as it may break a lot of configurations out there, thus, demanding a significant/major upgrade (aka v3).
