### ISSUE TITLE
"949110": False positive

### ISSUE THREAD

**Issue by ashishkpal** [SpiderLabs/ModSecurity#2500]
Hi,

I am observing Error. please help to resolve the same

2021/01/12 11:04:00 [error] 3102#3102: *899 [client 127.0.0.1] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator Ge' with parameter 5' against variable TX:ANOMALY_SCORE' (Value: 8' ) [file "/usr/local/coreruleset-3.3.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 8)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "127.0.0.1"] [uri "/"] [unique_id "1610449440"] [ref ""], client: 127.0.0.1, server: xxx.xxx.xxx, request: "PURGE / HTTP/1.1", host: "xxx.xxx.xxx.xxx"

CRS version - 3.3.0
Modsecurity 3.0.2
Nginx - 1.18.0

**Comment by zimmerle** [comment]
Hi @ashishkpal,

That is likely to be a false positive that is due to your **ruleset**. You may want to open an issue on **CRS github** repository. There, they will be able to assist you in fixing this issue.
