### ISSUE TITLE
Problem in unblocking IP after brute-force detection

### ISSUE THREAD

**Issue by manishnss** [SpiderLabs/ModSecurity#2501]
Hello Folks, 

I have created a rule to detect the Brute-force detection on a login page. The detection works as intented but on providing a valid login details rules doesn't trigger. Also, the counter doesn't change if the defined duration passed. 

Can anyone please help me in resolving the issue?

Environment Details:

- Local setup in Virtual Box
- Docker environment (Nginx)
- CRS 3.0.2

Follwing is the rule, I have created:

```
SecRule ip:bf_block "@gt 0"\
"deny,status:403,log,msg:'Brute Force Attack Detected.',id:700011"

# Checks for the Valid login attempt
SecRule RESPONSE_HEADERS:Location "@endsWith index.php" "phase:5,t:none,nolog,pass,setvar:ip.bf_counter=0,id:700012"

# Checks for the invalid login attempt
SecRule RESPONSE_HEADERS:Location "@endsWith login.php"\
"phase:5,chain,t:none,nolog,pass,setvar:ip.bf_counter=+1,id:700013"

# Blocks IP if, failed attempts are more than 5. 
SecRule ip:bf_counter "@gt 5" "t:none,setvar:ip.bf_block=1,expirevar:ip.bf_block=120,setvar:ip.bf_counter=0"
```

Thanks, 
Manish

**Comment by zimmerle** [comment]
@manishnss  is that ModSecurity version 3 or version 2?

**Comment by manishnss** [comment]
@zimmerle Version 2.x

is there a chance that I am using a local env to test this rule and causing this issue? As my IP will be same all the time even after passing the defined time.

**Comment by zimmerle** [comment]
Best thing to do in those cases is to use the **DebugLogs** to understand what is going on. I would do: 

   - Reduce the number of nginx workers to 1 - https://nginx.org/en/docs/ngx_core_module.html#worker_processes
   - Enable the DebugLogs on ModSecurity -   
```
SecDebugLogLevel 9
SecDebugLog /tmp/something.txt
```

Once it notice it is working in the way you expect, try to increase the _work_numbers_ to the default value. The multiple workers will make the counter a little bit fuzzy, as every worker has its own counter. Eventually they sync up.

**Comment by kirana2507** [comment]
Hi I wanna ask, is modsecurity protect and give log when brute force attack web app based on Apache?

**Comment by martinhsv** [comment]
Closing due to no feedback from OP.
