### ISSUE TITLE
It often leads memory leak on nginx reload

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2502]
**Describe the bug**

**We publish more frequently every day, and often reload nginx，every few days nginx has a memory leak,How to fix it?**

**Logs and dumps**

Output of:
```
2021/01/21 11:04:08 [alert] 25264#25264: fork() failed while spawning "worker process" (12: Cannot allocate memory)
2021/01/21 11:04:08 [alert] 25264#25264: sendmsg() failed (9: Bad file descriptor)
2021/01/21 11:04:08 [alert] 25264#25264: sendmsg() failed (9: Bad file descriptor)
2021/01/21 11:04:08 [alert] 25264#25264: sendmsg() failed (9: Bad file descriptor)
```

**Expected behavior**

**Server (please complete the following information):**
 -  Modsecurity:   v3.0.4-92-gd72be1c  for  Linux with nginx-connector v1.0.1
 - WebServer:     nginx-1.17.8
 - OS:                 Centos7.6

**Comment by zimmerle** [comment]
Duplicate of #2381

**Comment by Hello-Linux** [comment]
@zimmerle  From #2381, I don't see how to fix this problem? Now what do I need to do

**Comment by Hello-Linux** [comment]
@zimmerle  How to solve this problem?　The impact of this problem is very serious. I hope that the government will pay close attention to the repair and repair version 3.0.4 as soon as possible

**Comment by zimmerle** [comment]
@Hello-Linux copy in paste the same comments across multiple issues is not good for the project index. Please avoid doing it.

 Typically, users search for the existing issues before opening a new topic. Sometimes they get a response by just reading a similar problem.

**Comment by Hello-Linux** [comment]
@zimmerle Sorry, I don't know what you mean. What I want to ask is how to solve this memory leak?

**Comment by Abce** [comment]
maybe this PR (https://github.com/SpiderLabs/ModSecurity/pull/2580) can resovle you probole @Hello-Linux

**Comment by hebo209812** [comment]
I also encountered the same problem. It is the same with the latest 3.0.7. After nginx - s reload, there is a lot of memory leakage, and the memory is basically consumed after several more executions. This problem is very serious and has a great impact on the production environment

**Comment by martinhsv** [comment]
Closing in favour of #2848
