### ISSUE TITLE
Dynamic IP can't get a static on MTN lte

### ISSUE THREAD

**Issue by GarethHards** [SpiderLabs/ModSecurity#2503]
I recently installed mod security for apache2 on my pi4 4gb, running a Samsung 250G ssd without a GUI, I went and installed RaspAp, with a VPN and DNS server aswell, with a DNS client 

All installed and set my above servers and clients with a router allocated IP, called them yesterday and said my router has an eth0 issue and my eth0 data connection has failed and has little or no connectivity, further more I wanted the eth0 from the router to be static so all the above can be accurate, sadly I can't get static IP from my ISP on the package I have.

I went to no-ip and registered a hostname with them for free and added it to my router configuration, this configuration was under WLAN DDns here I'm a little confused to this adding it in the router, as far as I'm aware it's so that I can do a search via a device and the hostname can be identified to my router to pass the html page to the device via my router, my confusion is this done at my description in other words I can somehow select the settings to allow the html page to be accessed via RaspAp only or via my router WiFi, or both perhaps in the situation of creating a LAN/ home network for a hostname that could be viewed on the world wide web aswell, which I don't know how to setup for the three options and wether the DDns hostname I registered was needed actually if it was only for a home/LAN network via the router or RaspAp.

If someone can assist me please with a little bit of information to this settings I'll need and if the DDns from no -ip was needed for a home/business LAN please.

Also in hosts I created a name that I had in hosts previously with an router IP number plus a dot number behind it, I thought that seeing that I have a VPS and DNS that I can create a host for these two to assist with when the hostname is searched for, also I need settings to make sure that they are working together and that such is/was the right thing to do so that a page can be accessed, further if it's to be viewed on the world wide Web do I need settings to enable it, is it enable already to do that, I'm unsure but can reach it via my cell phone, some help with this will help me tremendously, and is mod security apart of these three Ie.RaspAp,DNS,and VPN, if so can I please have assistance in securing these three with mod security please.

In hosts I have a hostname with a different shorter IP /27.0.0.1 I'm not sure if these are all suppose to be static IP set from my router...are they? Please help me to know more about this, and the no IP hostname is this name with the 27.0.0.1 and is also the IP with a dot, in my mind I'm thinking with settings both can be used but I'm unsure if only the one with the dot is needed or not, I know I've written alot here above I hope it's only easy to help me, and thank you very much for helping with this, 
I'm wondering if I need to add hostnames to no-ip and add them them to my router, I really thought that if I registered a name in my system that it would do the same thing as No-ip system does, unfortunately my router is Pre programmed and I'm unable to add any other other than no-ip and ddns.org, so my other question is was registering a hostname with no-ip necessary if it is listed in my hosts ?

**Comment by zimmerle** [comment]
Hi @GarethHards,

What exactly ModSecurity role in this system? is it the one to block access to your "AP web interface"?

**Comment by GarethHards** [comment]
Hi I want to add a blacklist for a captive portal to be running on the RaspAp and don't know how to yet, I would like to have connected users of RaspAp browzer my html host, would mod security block my eth0 connection from my router and prevent my current internet sharing?

**Comment by GarethHards** [comment]
Cool thanks
