### ISSUE TITLE
Just curious

### ISSUE THREAD

**Issue by GarethHards** [SpiderLabs/ModSecurity#2504]
My apache2 is secured with mod security 2 basic rules so far which is installed on my raspberry Pi 4, with Ubuntu and no GUI, 
Does mod security provide the security for hosts on my local machine and remote clients /and or remote PC's with html folders that are using my system for the VPN,DNS, servers and FTP server,  where can I get more help with regards to rules for this situation I want to "iron out" so that my system is perfect.

**Comment by zimmerle** [comment]
ModSecurity is a WAF engine. It depends on **rules** to protect you against any potential threat. Together with ModSecurity, it is necessary to deploy a set of rules to implement some "protection" level.
