### ISSUE TITLE
ModSecurity: APR compiled version="1.6.2"; loaded version="1.6.3"

### ISSUE THREAD

**Issue by realseanwatson** [SpiderLabs/ModSecurity#2507]
**Describe the bug**
Hi Team, I have been getting this warning in apache log, so far my server is utilizing over 70% of my system RAM since I installed mod_security:
ModSecurity: Loaded APR do not match with compiled!
Tutorial followed: https://www.inmotionhosting.com/support/server/apache/install-modsecurity-apache-module/

I checked out issue: [#2139](https://github.com/SpiderLabs/ModSecurity/issues/2139) along with other searches on the internet however it did not help.

**Logs and dumps**

[:notice] ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/) configured.
[:notice] ModSecurity: APR compiled version="1.6.2"; loaded version="1.6.3"
[:warn] ModSecurity: Loaded APR do not match with compiled!
[:notice] ModSecurity: PCRE compiled version="8.39 "; loaded version="8.39 2016-06-14"
[:notice] ModSecurity: LUA compiled version="Lua 5.1"
[:notice] ModSecurity: YAJL compiled version="2.1.0"
[:notice] ModSecurity: LIBXML compiled version="2.9.4"
[:notice] ModSecurity: StatusEngine call: "2.9.2,Apache,1.6.2/1.6.3,8.39/8.39 2016-06-14,Lua 5.1,2.9.4"
[:notice] ModSecurity: StatusEngine call successfully sent. For more information visit: http://status.modsecurity.org/
[mpm_prefork:notice] AH00163: Apache/2.4.46 (Ubuntu) OpenSSL/1.1.1i configured -- resuming normal operations
[core:notice] [pid 6585] AH00094: Command line: '/usr/sbin/apache2'

**Server (please complete the following information):**
 - ModSecurity for Apache/2.9.2
 - WebServer: Apache/2.4.46
 - OS (and distro): Ubuntu 18.04

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? OWASP Core Rule Set
 - What is the version number? v3.3.0

Your help would be greatly appreciated,
Thank you

**Comment by zimmerle** [comment]
Hi @realseanwatson,

That means that your ModSecurity was compiled using the source files for APR 1.6.2 and it is loading in runtime the version 1.6.3. That incompatibility leads to unexpected behavior such this high memory usage that you are facing. My advice to you is to re-compile your ModSecurity using the same version of the APR that you have in run-time.

**Comment by realseanwatson** [comment]
@zimmerle - Thank you for your quick response, I figured much... Do you have a guide on how to do so? I am pretty new to this, my apologies for the back and forth.
