### ISSUE TITLE
SecRemoteRules what frequency to update rules

### ISSUE THREAD

**Issue by tRamq** [SpiderLabs/ModSecurity#2511]
I'm thinking about using SecRemoteRules feauture. But i want to learn about after i add the line in my conf. file . My url continuously updated. After every update am i need the reload my web server . Is mod_sec control the link freqeuntly or do it for just one time .

 - ModSecurity version (and connector): [ModSecurity v3.0.1 with nginx-connector v1.0.0]
 - WebServer: [nginx-1.19.5]
 - OS (and distro): ubuntu

**Comment by zimmerle** [comment]
Currently is necessary to reload ModSecurity in order to get the rules updated.
