### ISSUE TITLE
sudo ./build.sh not building correctly

### ISSUE THREAD

**Issue by albgen** [SpiderLabs/ModSecurity#2516]
hello,

I have two installation of modsec module and basically whenever there is a new version of nginx, i recompile modsec from the main branch.
Unfortunately, i have a problem with only the compilation in one installation instead the other one is ok.
Basically the commands i execute are the following:

```
cd /root
rm -rdf /root/ModSecurity/
sudo git clone --depth 1 -b v3/master --single-branch https://github.com/SpiderLabs/ModSecurity 
cd /root/ModSecurity
sudo git submodule init 
sudo git submodule update 
sudo ./build.sh # Multiple fatal: No names found - normal! - Here i have the problem
....
....etc
```

the script ./build.sh does not create the makefile.in and i have no idea why.
A solution is to create the whole folder from the other installation and it works but it would be nice to understand the issue and fix it..

thank you

**Comment by zimmerle** [comment]
@albgen can you paste the output of the ./build.sh script?

**Comment by albgen** [comment]
![image](https://user-images.githubusercontent.com/7231968/108549778-f0efe000-72ed-11eb-996e-f1e7c16f585c.png)

**Comment by zimmerle** [comment]
Double check if you have the following installed -
   - libtoolize
   - aclocal
   - autoheader
   - autoconf
   - automake

**Comment by albgen** [comment]
they are installed...

- libtoolize - libtool package
- aclocal - automake package
- autoheader - autoconf
- autoconf -  autoconf  package
- automake - automake package

![image](https://user-images.githubusercontent.com/7231968/108728411-db66fa00-7529-11eb-9ff2-6f1ea09409bc.png)


![image](https://user-images.githubusercontent.com/7231968/108727588-09980a00-7529-11eb-8de1-ff33bd2d5428.png)


but the question is how come it broke only on this installation while no changes has been done...except yum update :)

**Comment by zimmerle** [comment]
Maybe you want to run a ```git status```and ```git diff``` to understand what has been changed.

**Comment by zimmerle** [comment]
@albgen any progress?

**Comment by albgen** [comment]
Nope...i have no idea what to check. There are a lot of changes and i'm not familiar with the solution. All i can give is that from when it broke...but nothing else

**Comment by zimmerle** [comment]
@albgen  there is something out of the ordinary. I would expect to have a small list of changes, not a huge one.

**Comment by albgen** [comment]
hi @zimmerle,

as written previously, i usually compile ModSec everytime a new version of nginx is shipped.
So, basically nginx 1.19.6 released on 15 Dec 2020, worked perfectly.  Current version of nginx is 1.19.7  released on                                     16 Feb 2021 showd me some issues.

So, the commits  on ModSec between 15dec and 16 feb, broke the build. Make sense?

**Comment by zimmerle** [comment]
It is hard to investigate with limited details on the issue/machine, the build is working fine on the buildbots; I have tried to replicate the scenario that you have with the details provided here and I manage to compile it well.

The reason why you have -
```
fatal: No names found, cannot describe anything.
```
Is because you are downloading a specific branch from git, without the tags information. Tags are use to name the version. You may want to change that in yours "installation" script.

It is not necessary to update _libModSecurity_ on every new version of **nginx**, maybe the connector.

This should fix your issues -
```
libtoolize && aclocal && autoheader && autoconf && automake --add-missing
```

Why you are having this issues is what wonders me.

**Comment by albgen** [comment]
The issue with "fatal..."is not a problem.

![image](https://user-images.githubusercontent.com/7231968/109659107-a2510a00-7b67-11eb-90ca-45304bc58038.png)


i can give access on the server, i have no issue

**Comment by zimmerle** [comment]
[configure.ac](https://github.com/SpiderLabs/ModSecurity/blob/a18d18a28f486894b26c4f7258fe05a6d0300a2f/configure.ac) is part of the repository. You can download this file.

https://github.com/SpiderLabs/ModSecurity/blob/a18d18a28f486894b26c4f7258fe05a6d0300a2f/configure.ac#L1-L10

the output of ```git status``` will tell us more about what is missing.

**Comment by albgen** [comment]
sorry but i was not on the ModSec directory.
so basically now, the following command fixed the issue:
 libtoolize && aclocal && autoheader && autoconf && automake --add-missing
![image](https://user-images.githubusercontent.com/7231968/109677466-fbc23480-7b79-11eb-9bc3-5f4b74f9d7a0.png)

**Comment by zimmerle** [comment]
> libtoolize && aclocal && autoheader && autoconf && automake --add-mis

Yes, that is the command that I shared with you. I cannot tell you why you have the missing configure.ac and/or if there are more files missing.
