### ISSUE TITLE
JSON extraction from an API request

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2521]
Hello,

I want to extract information that is in body JSON following the execution of an API request.

Here is the Body JSON when transmitting the API request: 
> {
  "emails": [
    {
      "test_label": "Email",
      "primary": true,
      "type": "work",
      "value": "name.familyname@test.com",
      "x": 2,
      "x": 2,
      "x": true
    }
  ],
  "test": {
    "username": "name.familyname@test.com",
  },
  "name": {
    "familyName": "Familyname",
    "formatted": "Name Familyname",
    "givenName": "Name"
  }
}

Voici la règle que j'ai mis en place : 
> SecRule REQUEST_HEADERS:Content-Type "application/json" "phase:2,id:10,log,t:none,t:lowercase,pass,log,ctl:requestBodyProcessor=JSON,msg:'Mail : %{ARGS:test.username}',chain"
  SecRule REQUEST_METHOD "PUT" "chain"
  SecRule REQUEST_URI "^/api/test(\?.+)?$"

I used this to write my rule: https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/modsecurity-advanced-topic-of-the-week-json-support/

The result : 
![image](https://user-images.githubusercontent.com/79596092/109037645-3e43c700-76cb-11eb-8b7a-1e1aa48d2f60.png)
There is not the information that I wish to report. I am quite confused, it seems quite complicated to upload the JSON information in the access.log document. 

I want to extract this: 

> "username": "name.familyname@test.com",
> "familyName": "Familyname",
> "givenName": "Name"

Thanks a lot for your help..

**Comment by zimmerle** [comment]
@vova91 What is your ModSecurity version? Apache or Nginx?

**Comment by ghost** [comment]
@zimmerle Hello, it's **ModSecurity 2.9.2-1.el7** and **Apache/2.4.6**

**Comment by ghost** [comment]
Hello, 
Do you have any idea why the solution suggested on the link does not work in my case. Is there a solution to extract these 3 pieces of information from the Json body, when executing the API request in PUT.

Thank you very much @zimmerle

**Comment by zimmerle** [comment]
@vova91 The best thing to do in those cases is broken down the rules (remove the chained rules), and read the output of the **debuglogs**. The **debuglogs** contains all the information that you may need, including the value of the variables in question. 

You can place a rule like "@pm ARGS" and double check how the keys are computed from the JSON.

To enable the debuglogs, you can use -
```
SecDebugLogsLevel 9
SecDebugLogs "/path/to/debuglogs.txt"
```

**Comment by martinhsv** [comment]
I suspect the problem in this case is that you are trying to do incompatible things in the same rule.

For a request body to be processed as JSON, the JSON parser must be enabled before the request body is read -- i.e. in phase:1.  Your rule is setting ctl:requestBodyProcessor=JSON in phase:2 which is too late as the request body has already been processed at that point.

Of course you cannot just take your existing chained rule and switch it to phase 1 because the what you are trying to access (  %{ARGS:test.username} ) will not have been populated yet.
