### ISSUE TITLE
Nginx process has an abnormal exit, and the number of 'Reading' increases every time the nginx process exits unexpectedly

### ISSUE THREAD

**Issue by senzi-jp** [SpiderLabs/ModSecurity#2524]
openresty:1.19.3.1
modsecurity-nginx-v1.0.1
modsecurity-v3.0.4

modsecurity.conf:
SecRuleEngine DetectionOnly

I found that the nginx process has an abnormal exit, and the number of 'Reading' increases every time the nginx process exits unexpectedly.

Thanks.

**Comment by zimmerle** [comment]
Hi @senzi-jp,

I did not quite understood the problem. Did you observed a bad behavior based o [stub_stastus](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html) output or is it something that happens due to the usage of  [stub_stastus](http://nginx.org/en/docs/http/ngx_http_stub_status_module.html)?

**Comment by senzi-jp** [comment]
@zimmerle ，Let me see if something else is causing it, Thanks.

**Comment by zimmerle** [comment]
@senzi-jp any news?

**Comment by senzi-jp** [comment]
@senzi-jp Thank you very much.The problem still exists.

openresty-1.19.3.1
modsecurity-nginx-v1.0.1
modsecurity-v3.0.4

modsecurity.conf:
SecRuleEngine DetectionOnly

---------------------------------------------------------------------------------

./configure -j4 --prefix=/usr/local/openresty --conf-path=/usr/local/openresty/nginx/conf/nginx.conf --error-log-path=/opt/ngx_log/error.log --http-log-path=/opt/ngx_log/access.log --with-cc='ccache gcc -fdiagnostics-color=always' --with-cc-opt='-O2 -DTCP_FASTOPEN=23 -DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC' --with-compat --with-debug --with-file-aio --with-http_degradation_module --with-http_drizzle_module --with-http_iconv_module --with-http_perl_module --with-http_postgres_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module --with-google_perftools_module --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib' --with-libatomic --with-luajit --with-luajit-xcflags='-DLUAJIT_NUMMODE=2 -DLUAJIT_ENABLE_LUA52COMPAT' --with-mail_ssl_module --with-pcre=../pcre-8.44 --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-stream_geoip_module --with-stream_realip_module --with-threads --with-zlib=../zlib-1.2.11 --with-openssl=../openssl-1.1.1g --with-openssl-opt="enable-tls1_3 enable-ec_nistp_64_gcc_128" --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-poll_module --without-select_module --add-module=../ngx_cache_purge-2.3 --add-module=../nginx-module-vts-master --add-module=../nginx-module-sts-master --add-module=../nginx-module-stream-sts-master --add-module=../modsecurity-nginx-v1.0.1

---------------------------------------------------------------------------------

debug logs:

2021/03/19 18:10:07 [debug] 51490#51490: worker cycle
2021/03/19 18:10:07 [debug] 51490#51490: epoll timer: -1
2021/03/19 18:10:07 [notice] 51489#51489: signal 17 (SIGCHLD) received from 51492
2021/03/19 18:10:07 [alert] 51489#51489: worker process 51492 exited on signal 11 (core dumped)
2021/03/19 18:10:07 [debug] 51489#51489: shmtx forced unlock
2021/03/19 18:10:07 [debug] 51489#51489: shmtx forced unlock
2021/03/19 18:10:07 [debug] 51489#51489: shmtx forced unlock
2021/03/19 18:10:07 [debug] 51489#51489: wake up, sigio 0
2021/03/19 18:10:07 [debug] 51489#51489: reap children
2021/03/19 18:10:07 [debug] 51489#51489: child: 0 51490 e:0 t:0 d:0 r:1 j:0
2021/03/19 18:10:07 [debug] 51489#51489: child: 1 51491 e:0 t:0 d:0 r:1 j:0
2021/03/19 18:10:07 [debug] 51489#51489: child: 2 51492 e:0 t:1 d:0 r:1 j:0
2021/03/19 18:10:07 [debug] 51489#51489: pass close channel s:2 pid:51492 to:51490
2021/03/19 18:10:07 [debug] 51489#51489: pass close channel s:2 pid:51492 to:51491
2021/03/19 18:10:07 [debug] 51489#51489: pass close channel s:2 pid:51492 to:51493
2021/03/19 18:10:07 [debug] 51489#51489: channel 19:20
2021/03/19 18:10:07 [debug] 51491#51491: epoll: fd:18 ev:0001 d:00007FE3ACF2F2C8
2021/03/19 18:10:07 [debug] 51491#51491: channel handler
2021/03/19 18:10:07 [debug] 51491#51491: channel: 32
2021/03/19 18:10:07 [debug] 51491#51491: channel command: 2
2021/03/19 18:10:07 [debug] 51491#51491: close channel s:2 pid:51492 our:51492 fd:9
2021/03/19 18:10:07 [debug] 51491#51491: channel: -2
2021/03/19 18:10:07 [debug] 51491#51491: timer delta: 0
2021/03/19 18:10:07 [debug] 51491#51491: worker cycle
2021/03/19 18:10:07 [debug] 51491#51491: epoll timer: -1
2021/03/19 18:10:07 [notice] 51489#51489: start worker process 58529
2021/03/19 18:10:07 [debug] 51489#51489: pass channel s:2 pid:58529 fd:19 to s:0 pid:51490 fd:3
2021/03/19 18:10:07 [debug] 51489#51489: pass channel s:2 pid:58529 fd:19 to s:1 pid:51491 fd:17
2021/03/19 18:10:07 [debug] 51489#51489: pass channel s:2 pid:58529 fd:19 to s:3 pid:51493 fd:21
2021/03/19 18:10:07 [debug] 51489#51489: child: 3 51493 e:0 t:0 d:0 r:1 j:0
2021/03/19 18:10:07 [debug] 51489#51489: sigsuspend
2021/03/19 18:10:07 [debug] 51493#51493: epoll: fd:22 ev:0001 d:00007FE3ACF2F2C8
2021/03/19 18:10:07 [debug] 51493#51493: channel handler
2021/03/19 18:10:07 [debug] 51493#51493: channel: 32
2021/03/19 18:10:07 [debug] 51493#51493: channel command: 2
2021/03/19 18:10:07 [debug] 51493#51493: close channel s:2 pid:51492 our:51492 fd:19
2021/03/19 18:10:07 [debug] 51493#51493: channel: 32
2021/03/19 18:10:07 [debug] 51493#51493: channel command: 1
2021/03/19 18:10:07 [debug] 51493#51493: get channel s:2 pid:58529 fd:9
2021/03/19 18:10:07 [debug] 51493#51493: channel: -2
2021/03/19 18:10:07 [debug] 51493#51493: timer delta: 0
2021/03/19 18:10:07 [debug] 51493#51493: worker cycle

---------------------------------------------------------------------------------

core file:

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/openresty/nginx/sbin/nginx...done.
[New LWP 51492]
[New LWP 51683]
[New LWP 51684]
[New LWP 51685]
[New LWP 51686]
[New LWP 51687]
[New LWP 51688]
[New LWP 51689]
[New LWP 51690]
[New LWP 51691]
[New LWP 51692]
[New LWP 51693]
[New LWP 51694]
[New LWP 51695]
...
...
...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `nginx: worker process                '.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fe3c56d27b1 in __strlen_sse2_pminub () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install GeoIP-1.5.0-14.el7.x86_64 cyrus-sasl-lib-2.1.26-20.el7_2.x86_64 glibc-2.17-323.el7_9.x86_64 gperftools-libs-2.6.1-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libcom_err-1.42.9-9.el7.x86_64 libcurl-7.29.0-59.el7_9.1.x86_64 libgcc-4.8.5-44.el7.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgomp-4.8.5-44.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libidn-1.28-4.el7.x86_64 libmaxminddb-1.2.0-6.el7.x86_64 libselinux-2.5-6.el7.x86_64 libssh2-1.8.0-4.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libxml2-2.9.1-6.el7.5.x86_64 libxslt-1.1.28-6.el7.x86_64 lmdb-libs-0.9.22-2.el7.x86_64 lua-5.1.4-15.el7.x86_64 nspr-4.25.0-2.el7_9.x86_64 nss-3.53.1-3.el7_9.x86_64 nss-softokn-freebl-3.53.1-6.el7_9.x86_64 nss-util-3.53.1-1.el7_9.x86_64 openldap-2.4.40-13.el7.x86_64 openssl-libs-1.0.1e-60.el7_3.1.x86_64 pcre-8.32-17.el7.x86_64 perl-libs-5.16.3-291.el7.x86_64 postgresql-libs-9.2.24-4.el7_8.x86_64 ssdeep-libs-2.14.1-1.el7.x86_64 sssd-client-1.14.0-43.el7_3.18.x86_64 xz-libs-5.2.2-1.el7.x86_64 yajl-2.0.4-4.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64

------------------------------------------

I noticed that "Reading connections" increased every time the nginx  worker process exited abnormally.

**Comment by senzi-jp** [comment]
I started four nginx processes, but one of them would periodically abort.

**Comment by senzi-jp** [comment]
@

> @senzi-jp any news?


Thank you very much,The issue has been resolved.This is because the nginx-module-vts module was used when compiling nginx.I think there might be a compatibility problem.

**Comment by senzi-jp** [comment]
> @senzi-jp any news?

Thank you very much.The problem still exists, and I haven't figured out why.

**Comment by senzi-jp** [comment]
@zimmerle 
I found that the nginx process has an abnormal exit, and the number of 'Reading' increases every time the nginx process exits unexpectedly.

'2021/04/01 02:29:59 [alert] 61058#61058: worker process 21869 exited on signal 11 (core dumped)'

**Comment by martinhsv** [comment]
Hello @senzi-jp ,

I'm going to need more information to do anything with this. To start with:

You write: "I found that the nginx process has an abnormal exit"
How frequently does this occur?
Is it while it is processing some particular type of HTTP Request? Some other common condition? Or can it happen even if there is no HTTP Request currently being processes?
How does this relate to ModSecurity? Is it the case that if set 'ModSecurity Off' in your configuration that the problem stops happening?

"and the number of 'Reading' increases every time"
I have no idea what this means.
