### ISSUE TITLE
Github site links broken, cannot buy Spiderlabs rules

### ISSUE THREAD

**Issue by sorin-costea** [SpiderLabs/ModSecurity#2531]
Neither the project link, nor the buying link, nor the applications list are working, they receive 404 or just redirect to the main page. I cannot even buy the rules package because there's no way to figure out the shop page.

**Comment by zimmerle** [comment]
Hi @sorin-costea,

Please contact sales@trustwave.com they will help you in this process.

**Comment by sorin-costea** [comment]
I don't think sales can fix the website links...

**Comment by zimmerle** [comment]
@sorin-costea sales can help you with the commercial rules license and commercial information. As for ModSecurity, what kind of information are you looking for that is not on the GitHub project page?

**Comment by sorin-costea** [comment]
I'm talking about the v2 GitHub site: [https://github.com/SpiderLabs/ModSecurity/tree/v2/master](https://github.com/SpiderLabs/ModSecurity/tree/v2/master)
Image 1: the project link (in red) is broken, the download link does NOT lead to any download at all:
 
![image](https://user-images.githubusercontent.com/3449432/111455054-a2c7d400-8715-11eb-9442-2dd31553be57.png)


Image 2 further below, another broken link regarding applications coverage:

 
![image](https://user-images.githubusercontent.com/3449432/111455089-a8bdb500-8715-11eb-8b78-649481b285dc.png)

**Comment by zimmerle** [comment]
@sorin-costea fixed! thank you for let us know.
