### ISSUE TITLE
Next release version and date 

### ISSUE THREAD

**Issue by artemMartynenko** [SpiderLabs/ModSecurity#2534]
Hello. I`m trying to create ModSecurity binding for Java.  I saw that your last published release was [3.0.4 ](https://github.com/SpiderLabs/ModSecurity/releases/download/v3.0.4/modsecurity-v3.0.4.tar.gz) but there are a lot of significant changes in the master branch. My question is what will be the next release number and went it could be released? Thanks!

**Comment by zimmerle** [comment]
Hi, @artemMartynenko  thanks for the interest in expanding ModSecurity bindings! That is awesome!!! :1st_place_medal: :+1: 

Our effort towards releases is expressed on [GitHubProjects](https://github.com/SpiderLabs/ModSecurity/projects). What kind of bindings do you want to provide? To cover all library functionality or to cover pieces such as the rules parser?

I would focus on [v3/master](https://github.com/SpiderLabs/ModSecurity), that is the code that will be used on a possible [3.0.5](https://github.com/SpiderLabs/ModSecurity/projects/7) and it is the code that is the base for [v3.1](https://github.com/SpiderLabs/ModSecurity/tree/v3/dev%2F3.1). Meaning changing from [v3/master](https://github.com/SpiderLabs/ModSecurity) to [3.1.0](https://github.com/SpiderLabs/ModSecurity/tree/v3/dev%2F3.1) should be easier than from [3.0.4 ](https://github.com/SpiderLabs/ModSecurity/tree/v3.0.4)to [v3.1](https://github.com/SpiderLabs/ModSecurity/tree/v3/dev%2F3.1).

**Comment by henricook** [comment]
This issue caught my eye, thanks for the projects link. Does that mean 3.1.0 is ready to go and will be released any day now?

**Comment by artemMartynenko** [comment]
Hello. Thanks a lot. The binding will cover main library functionality like Transaction, RuleMessage and so on. 
From my personal plan, the first step will be just to allow usage of library functionality from Java. [Pull Request](https://github.com/bytedeco/javacpp-presets/pull/1012) for this is already created. The next step will be a WebFilter for Spring Framework which will allow using ModSecurity as a WAF on the framework level independently of the type of embedded web server.

**Comment by zimmerle** [comment]
@artemMartynenko it sounds like an exciting project indeed! 

Good to see that you already have significant progress. Great! 👍 👍 💯 


There should be version 3.0.5 by next week. Likely to happen on Tuesday -- Jul, 06.
