### ISSUE TITLE
create secremoteruls server

### ISSUE THREAD

**Issue by aminbaik88** [SpiderLabs/ModSecurity#2537]
Hello, 
how i can create a secremoterulss server ?
i try to search but i don't  find any thing about it.
Thanks.

**Comment by zimmerle** [comment]
Hi @aminbaik88,

**SecRemoteRules** performs a regular HTTP request on a _webserever_. ModSecurity expects to process a text file that is no different from a regular file that you may want to load using the **include** directive.

As part of the request headers, ModSecurity also includes:
   * ModSec-status: [further info](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secstatusengine)
   * ModSec-unique-id: [further info](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secstatusengine)
   * ModSec-key: key provided while the user entered the SecRemoteRules directive.

You can programmatically deliver different rules based on the information above.
