### ISSUE TITLE
SecRuleRemoveBy does not work with regexp

### ISSUE THREAD

**Issue by c4simba** [SpiderLabs/ModSecurity#2540]
**Describe the bug**

SecRuleRemoveBy does not work with regexp

**Logs and dumps**

Error log:
`[8:38 PM] Line: 1. Column: 39. Invalid input:  |wp_theme`

**To Reproduce**

Example of config

`modsecurity_rules "SecRuleRemoveByTag ^(wp_core|wp_theme)$"`

**Server (please complete the following information):**
Centos 8 + Cpanel server with installed ModSecurity3 from cpanel repository
https://docs.cpanel.net/knowledge-base/experimental-software/modsecurity-3/

**Comment by martinhsv** [comment]
Hello @c4simba ,

For ModSecurity v3, the tag matching behaviour was intentionally implemented to not use regex.

Please see the discussion in https://github.com/SpiderLabs/ModSecurity/issues/2109 , regarding SecRuleRemoveTargetByTag.
