### ISSUE TITLE
Mod Security not detect Brute force attack on Apache server

### ISSUE THREAD

**Issue by kirana2507** [SpiderLabs/ModSecurity#2543]
Hi, I wanna ask. Why mod security not detect Brute force attack on Log? and where can I find rules to protect brute force on mod security? thank you

**Comment by martinhsv** [comment]
Hello @kirana2507 ,

ModSecurity is WAF engine with functionality to support detection of a wide variety of attacks.  However, you need rules to actually utilize that functionality.

There are numerous providers of rule sets, both paid commercial rules and free rule sets (the latter typically are generic rule sets).  One popular generic rule set is https://github.com/coreruleset/coreruleset.  Depending on what your needs are, that rule set includes some rules to detect what one might think of as 'brute force' attacks (for example:  a large number of requests from a single IP address within a short period of time).
