### ISSUE TITLE
How to tell mod Security to use TLSv1.2 by default while Communicating with Auditconsole?

### ISSUE THREAD

**Issue by sachintendulkar10** [SpiderLabs/ModSecurity#2544]
How to tell mod Security to use TLSv1.2 by default while Communicating with Auditconsole?

Currently modsecurity is  using tlv1.1 by default and working see [1]. 

If i update Auditconsole SSL Protocol to use TLS1.2 then communication fails with unsupported protocol. see [2]

[1]
CURL: HEADER_IN HTTP/1.1 200 OK
CURL: HEADER_IN Server: Apache-Coyote/1.1
CURL: HEADER_IN Set-Cookie: JSESSIONID=0186B0FE0E5566A7DA262C6A21983AE0; Path=/; Secure
CURL: HEADER_IN Content-Length: 0
CURL: HEADER_IN Date: Tue, 30 Mar 2021 14:53:01 GMT
CURL: HEADER_IN Connection: close
CURL: HEADER_IN
CURL: Closing connection 327
CURL: TLSv1.1 (OUT), TLS alert, Client hello (1):
CURL: HEADER_IN HTTP/1.1 200 OK
CURL: HEADER_IN Server: Apache-Coyote/1.1
CURL: HEADER_IN Set-Cookie: JSESSIONID=xxxxxxxx; Path=/; Secure
CURL: HEADER_IN Content-Length: 0
CURL: HEADER_IN Date: Tue, 30 Mar 2021 14:53:01 GMT
CURL: HEADER_IN
CURL: Connection #319 to host xx.xx.xx.xx left intact
Request returned with status "200 OK": xxxxxxxxxxxxxxx
Removing: /xxx/apache2/logs/modsecdata/audit/xxx/xxxx/xxx-xxx
[9966/154b2b0] Entry completed (0.020 seconds, 934 bytes): xxxxxxxxxx

[2]
CURL: TCP_NODELAY set
CURL: Connected to xxx.xxx.xx.xx port xxx 
 CURL: ALPN, offering http/1.1
CURL: Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
 CURL: successfully set certificate verify locations:
CURL: TLSv1.1 (OUT), TLS header, Certificate Status (22):
CURL: TLSv1.1 (OUT), TLS handshake, Client hello (1):
CURL: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
CURL: Closing connection 82
Flagging server as errored after failure to submit entry xxxxxxxxxx (cURL code 35): error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol 

**Describe the bug**

**Logs and dumps**

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs
 3. Error logs
 4. If there is a crash, the core dump file.

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

A **curl** command line that mimics the original request and reproduces the problem. Or a ModSecurity v3 test case.

[e.g: curl "modsec-full/ca/..\\..\\..\\..\\..\\..\\/\\etc/\\passwd" or [issue-394.json](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/test/test-cases/regression/issue-394.json)]

**Expected behavior**

**Server (please complete the following information):**
 - ModSecurity version (and connector): [e.g. ModSecurity v3.0.1 with nginx-connector v1.0.0]
 - WebServer: [e.g. nginx-1.15.5]
 - OS (and distro): [e.g. Linux, archlinux]

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? [e.g. SpiderLabs commercial rules]
 - What is the version number? [e.g. 2018-08-11]

**Additional context**

**Comment by zimmerle** [comment]
@sachintendulkar10 What is your Modsecurity version? Can you share the logs?
