### ISSUE TITLE
It often leads memory leak on nginx reload 

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2545]
@zimmerle   It often leads memory leak on nginx reload using modsecurity branch 3.1-experimental and master,I hope that the official will fix this problem as soon as possible, which has a serious impact on the production environment.

And There is also why this problem #2381 was closed without being resolved!!!

I suggest that you officially do a test yourself. First, create a lot of virtual hosts, each virtual host quotes the modsecurity rules separately, and then constantly reload, the memory leak should be reproduced! 
Describe the bug

We publish more frequently every day, and often reload nginx，every few days nginx has a memory leak,How to fix it?

Logs and dumps

Output of:
```
2021/01/21 11:04:08 [alert] 25264#25264: fork() failed while spawning "worker process" (12: Cannot allocate memory)
2021/01/21 11:04:08 [alert] 25264#25264: sendmsg() failed (9: Bad file descriptor)
2021/01/21 11:04:08 [alert] 25264#25264: sendmsg() failed (9: Bad file descriptor)
2021/01/21 11:04:08 [alert] 25264#25264: sendmsg() failed (9: Bad file descriptor)
```

**Comment by martinhsv** [comment]
Hi @Hello-Linux ,

What is this issue meant to convey that is different from your issue https://github.com/SpiderLabs/ModSecurity/issues/2502 ?

**Comment by zimmerle** [comment]
Duplicate of #2502.
