### ISSUE TITLE
The modsecurity log is output to the nginx error log instead of /var/log/modsec_audit.log 

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity#2546]
I set the input log to /var/log/modsec_audit.log in the modsecurity configuration file, why doesn't it take effect? 
the config is
![2021-03-31 14-05-59 的屏幕截图](https://user-images.githubusercontent.com/17851645/113097886-47740680-922a-11eb-86ea-46debc11f222.png)

**Comment by martinhsv** [comment]
Hi @Hello-Linux ,

Logging is impacted by several different settings.

First, What code branch are you talking about?  (I think you've looked at 3.1-experimental in the context of other issues)  Or should I assume that you are using ModSecurity v3.0.4 or the current v3/master.

Also:
- what rule is being logged to the server's error log, but that is not being logged to the audit_log?
- what disruptive actions (e.g. block/deny) are relevant (both in the rule itself and in any default actions)?
- what logging actions do you have set in each (log,noauditlog, etc.)
- are you using error redirects or anything similar?  Or just a basic nginx configuration?
- are you never able to see anything in the audit_log or is it only for some transactions?

**Comment by zimmerle** [comment]
No feedback from the user, closing the issue.
