### ISSUE TITLE
SecRuleEngine in VirtualHost

### ISSUE THREAD

**Issue by willyamcts** [SpiderLabs/ModSecurity#2547]
In mod_security2 it was possible to use "SecRuleEngine" in VirtualHost, however in version 3 I am not able to use it. When I make the identical change from version 2, when trying to start Apache it returns a syntax error:
AH00526: Syntax error on line 8 of apache2/conf/extra/httpd-vhosts.conf:

```
Invalid command 'SecRuleEngine', perhaps misspelled or defined by a module not included in the server configuration
```

Within the VirtualHost:
```
 <IfModule security3_module>
      SecRuleEngine Off
 </IfModule>
```

In version 3 not is possible use de SecRuleEngine in VirtualHost ?

**Comment by martinhsv** [comment]
Hi @willyamcts ,

ModSecurity v3 (aka libmodsecurity) is not recommended for use with Apache HTTP Server.

If using that web server, ModSecurity v2.9.x is still the recommended version to use.

**Comment by willyamcts** [comment]
Hi @martinhsv,

I saw this recommendation on the main page, but nowhere does it say why. Could you tell me why?

Version 3 was announced in 2018 on the SpiderLabs blog by @zimmerle, for this reason we are in doubt.

Very thanks.

**Comment by martinhsv** [comment]
libmodsecurity with Apache is alpha code.  Although large portions of the functionality work correctly, it is not considered production ready.

**Comment by willyamcts** [comment]
Hi, thanks for explanation #martinhsv.

just to keep it registered, using **modsecurity on** and **modsecurity_rules_file** it is possible to use it by VirtualHost.

Very thanks.
