### ISSUE TITLE
Parser breaks on % char

### ISSUE THREAD

**Issue by tomsommer** [SpiderLabs/ModSecurity#2553]
This rule breaks the 3.0.4 parser

```
  SecRule REQUEST_METHOD "@streq POST" "id:26,msg:'ASP malware upload',chain,t:none"
  SecRule REQUEST_BODY "@contains <%" "chain"
  SecRule REQUEST_BODY "@rx (CreateObject|FileSystemObject|OpenTextFile|execute|eval)"

```

The `%`-char results in a "directive Rules must have an ID." error

**Comment by martinhsv** [comment]
Hi @tomsommer ,

While the error message that you are seeing is misleading, the underlying problem is that certain characters do need different treatment.  The '%' has special meaning for macro expansion, so I expect that is the reason you are encountering a problem.

For the rule in question, I would suggest trying one of these alternatives:
"@rx <[%]"
"@rx <\x25"

**Comment by tomsommer** [comment]
Should add this doesn't produce any errors in v2 (but now I'm unsure if it even works in v2)

**Comment by martinhsv** [comment]
It may be possible to amend the v3 rule parser to accept '%' as a plain character.

But given that there are fully-functional alternatives, I think it's unlikely such a change would make the priority list anytime soon.

Closing ...

**Comment by tomsommer** [comment]
Could you at least improve the error message then? It was a real pain to debug.

**Comment by martinhsv** [comment]
Fair point.  I have reopened.

**Comment by zimmerle** [comment]
> Could you at least improve the error message then? It was a real pain to debug.

Further 3.1-ish, the parser will support **warning** atop of **errors**; it will be smooth to tell the user when something does not appear to be correct. Or even be more verbose/clear/detailed on error messages, contemplating this use case.

**Comment by airween** [comment]
I think this issue is duplicated of [#2145](https://github.com/SpiderLabs/ModSecurity/issues/2145).

We use `\x25` as workaround.

**Comment by martinhsv** [comment]
@airween.  Thanks for noting that.

I'll close this as a duplicate then.
