### ISSUE TITLE
SecConnReadStateLimit not yet supported

### ISSUE THREAD

**Issue by willyamcts** [SpiderLabs/ModSecurity#2555]
In the current ModSecurity version 3.0.4, the SecConnReadStateLimit Apache directive does not initialize, return:
"SecConnReadStateLimit is not yet supported."

Not will have support to limit from connection in the current version?

**Comment by martinhsv** [comment]
Hi @willyamcts ,

I have never actually used that configuration item, but it may not be practical (or at least advisable) to implement that in ModSecurity v3 (at least not for nginx).

A primary motivation of SecConnReadStateLimit was to restrict the number of connections from a single IP address even when those connections have not finished sending the HTTP Request Header.

ModSecurity v3 does not have direct access to the TCP stack and is dependent on what the nginx API can provide.  And it's not clear to me that that sort of state information is available (I might be wrong ... I haven't looked that closely).

But even if ModSecurity _could_ implement that with nginx, I might wonder aloud whether that would be the best approach.  WAFs focus on the Application Layer, whereas limiting the number of concurrent TCP connections is is more of a Transport Layer issue.  As such, one might ask whether that sort of limiting is best done by a WAF like ModSecurity.

Have you explored whether you can do this another way?  You might be able to do something with nginx configuration items (although I don't see controls for connections that have not yet completed sending of the request header), but conventional network firewalls tend to include that sort of functionality (e.g. iptables).
