### ISSUE TITLE
ModSecurity C Function Binding for Lua on Apache

### ISSUE THREAD

**Issue by frkngksl** [SpiderLabs/ModSecurity#2558]
Hi,

I want to use a C binded Lua script in my ModSecurity v3.0.4 setup. This lua script heavily uses Libxml2 because its main job is XML Schema Validation. I can run this script on Lua, and it works. However, when I want to add this script as a rule (SecRuleScript), it doesn't work as intended. The code block that is problematic is below (at least for executing over ModSecurity-Apache because it perfectly runs on standalone Lua) :

```
static int lua_xmlSchemaParser(lua_State *L)
{
	xmlSchemaPtr schema;
	xmlSchemaParserCtxtPtr pctxt;

    const char* filename = (char *) luaL_checkstring(L, 1);

	if ((pctxt = xmlSchemaNewParserCtxt(filename)) == NULL) {
        lua_pushnil(L);
        return 1;
	}

	schema = xmlSchemaParse(pctxt);
    xmlSchemaFreeParserCtxt(pctxt);

    if (schema == NULL) {
        lua_pushnil(L);
        return 1;
    }

    lua_pushlightuserdata(L, schema);
    return 1;
}
```

After xmlSchemaParse function call (it belongs to libxml2) the returning value is NULL. I looked at the errno, and it is 11 : Resource Temporarily Unavailable. I couldn't figure out what is the problem. The things that I want to summarize:

1- I looked at pmap of Apache threads, all of them loads libxml2.so
2- I checked the permissions of the script file. Also I can read the all content of file (ie. I confirmed that Lua script can read the file during the transaction)
3- Again, it totally works when I directly run it
4- As you can see from the code block, xmlSchemaNewParserCtxt which is another function from libxml2 doesn't return NULL.

**Comment by zimmerle** [comment]
@frkngksl In the use case scenario you have reported, the libxml library seems to share the address space with Apache and ModSecurity ( + any other Apache module loaded).

While sharing the address space, you need to consider that someone another piece of software already instantiates and perhaps configured the shared resource. You have to also consider permission issues for file and (special) memory access. The kernel will consider the Apache user as opposed to your local user.

As best practices, I would recommend threatening the errors on the libxml calls, making it part of your code. Once you have the errors treated, please share the code and the error messages, then we will help you better.

**Comment by frkngksl** [comment]
Hi @zimmerle 

Thanks for your advises, I solved the issue, each time before loading a schema we should call a function that cleanups the parser. However, the tricky part is although I restarted the apache several times, this doesn't cleanup the parser interestingly.

You can close the issue thanks for your help.

**Comment by PsycheSloLo811** [comment]
creative commons
