### ISSUE TITLE
Windows Version 2.9.3 seems broken for Apache 2.4.46.0 How can we get this going for Windows?

### ISSUE THREAD

**Issue by KrillinsWorld** [SpiderLabs/ModSecurity#2561]
**Describe the bug**
Windows Users Want to update to 3.x version but "no library" or info can be found. We would like to escalate this and figure this out for windows users? As version 2.9.3 doesn't work in setup tutorials we have followed, the SM runs, but doesn't protect? Documentation seems to outdated as well, 2.5.3? We would like to this change to protect our servers as well, as I am not too keened on running Apache on our game server with Apache (looks a lot more complicated than the simplistic configurations found on windows).

I have a old HP Proliant DL380 G5 server we can use to allow remote access to with Windows Server 2016 or 2019 we can use to assist on getting this rolled out for Winodws' users.

I have been checking this mod for some time and windows has been left out for far too long and it is time to get this addressed, now. I do have a HP Proliant DL360p G8 server but it run Debian 10 for the game servers we host.

If you need anymore information please let me know, I will be glad to help!

-Krillin

**Comment by zimmerle** [comment]
Hi @KrillinsWorld

The recommended version for Apache users (regardless of the operational system) is version 2.9.3; Is anything wrong with Apache Lounge distribution https://www.apachelounge.com/download/?

**Comment by KrillinsWorld** [comment]
We downloaded, installed 2.9.3, documentation is "outdated" and it was stated:  As version 2.9.3 doesn't work in setup tutorials we have followed, the SM runs, but doesn't protect?

> Call your site with: 
> 
> http://www.xxxx.com/?abc=../../ 
> 
> You should get a access denied and is logged in the Apache error.log, it is triggered by the above rule

This absolutely FAILED. Documentation unclear and confusing to webmasters like myself. What is unclear is where are these "rules" supposed to be placed as they can be put in so many locations. Apache in Windows Operating System is VERY simplistic unlike Linux. Linux makes it hard to even host a single website due to ownership of root for /var/www/html but that is another subject

We tried to set up SM in windows with the latest Apache (released March, 27th, 2021 still v2.4.46.0) and the example above didn't do anything as the page loaded, even with localhost/?abc=../../ the page did NOT get denied.

The error.log file gave me my first clue:

> [Mon Apr 26 22:52:11.385830 2021] [:notice] [pid 6356:tid 712] ModSecurity: Status engine is currently disabled, enable it by set SecStatusEngine to On.

Using the included modsecurity.conf-recomended has the final line as "SecStatusEngine On" and it didn't work. We had to build a .conf file from nothing with just a few lines in it and it didn't work.

This is what we saw after our own .conf in the /logs/error.log file:
> [Mon Apr 26 22:53:49.700403 2021] [:notice] [pid 8008:tid 744] ModSecurity for Apache/2.9.3 (http://www.modsecurity.org/) configured.
> [Mon Apr 26 22:53:49.700403 2021] [:notice] [pid 8008:tid 744] ModSecurity: APR compiled version="1.7.0"; loaded version="1.7.0"
> [Mon Apr 26 22:53:49.700403 2021] [:notice] [pid 8008:tid 744] ModSecurity: PCRE compiled version="8.43 "; loaded version="8.44 2020-02-12"
> [Mon Apr 26 22:53:49.700403 2021] [:warn] [pid 8008:tid 744] ModSecurity: Loaded PCRE do not match with compiled!
> [Mon Apr 26 22:53:49.700403 2021] [:notice] [pid 8008:tid 744] ModSecurity: LUA compiled version="Lua 5.2"
> [Mon Apr 26 22:53:49.700403 2021] [:notice] [pid 8008:tid 744] ModSecurity: YAJL compiled version="2.1.0"
> [Mon Apr 26 22:53:49.700403 2021] [:notice] [pid 8008:tid 744] ModSecurity: LIBXML compiled version="2.9.9"
> [Mon Apr 26 22:53:49.731651 2021] [:notice] [pid 8008:tid 744] ModSecurity: StatusEngine call: "2.9.3,Apache/2.4.46 (Win64),1.7.0/1.7.0,8.43/8.44 2020-02-12,Lua 5.2,2.9.9,dd7b703de840f6760d0df98695cc84fa07bc486b"

We went looking on the web for setting up 2.9.3 for apache for windows, there was hardly anything out there except the same broken methods which proved to be nonfunctioning.

So at this point, we are stuck. We 'Un-did' everything we started to do to get SM working as we are back to square one.

-Krillin

**Comment by zimmerle** [comment]
@KrillinsWorld ModSecurity is just the engine. Together with ModSecurity you have to set up a set of rules.  ModSecurity itself won't give you mitigation for any attack.

Perhaps you want to look over a project such as OWASP CRS.

**Comment by KrillinsWorld** [comment]
I have never heard of OWASP CRS. I do see some content in ModSecurity logs. I need to dig into Apache a bit more, as some functions there do not appear to be working. But as for rules, documentation is a joke. I will read them a bit more in detail when I have more time. Right now I am a bit busy with work as we are planning to leave for a weekend at the end of the month. Maybe I will find some time that week to take up some reading here and take notes. Mind you, I am not a programmer and no one wants to read documents written by a programmer for a general public who is making far to many assumptions about the user who is reading the document. This is 101 writing. Being too general like the document provided in the 2.9.3 package is lame and so generic it prompts more questions than answers. And thus far I have gotten nothing helpful, so this speaks volumes.

-Krillin

P.S. Apache also updated to 2.4.47 on 4/29 and we updated to this version on 4/30.

**Comment by KrillinsWorld** [comment]
Well, I took some time this evening to take a look at OWASP CRS and I have it set up and running on my Apache Web Server with mod_security. I gained interests in MS because the hosting company who hosts the core of my website uses this and there have been many problems with it with files on my account with my SMF forums, so I am curious as to why. Not sure if they have OWASP CRS set up on their servers, but I am giving it a whirl and it is working using the example they gave in the installation instructions out of the box so I am pleased. Not too thrilled about all the logging, but we will see if these snoopers who think I am dumb enough to use wordpress for anything on the small handful of subdomains I use on my apache server. I am tired of blocking ISPs from brute-force attacks on phpmyadmin from hong kong the the snoopers fishing for a wordpress install and other attacking methods. Thanks for the info.

-Krillin

**Comment by KrillinsWorld** [comment]
Would it be possible to build 3.0.4 in Linux and then copy the compiled file(s) for the module to windows to use? Also know as stated before Apache is now 2.4.47.

**Comment by zimmerle** [comment]
> Would it be possible to build 3.0.4 in Linux and then copy the compiled file(s) for the module to windows to use?

No. it is not possible.


> Also know as stated before Apache is now 2.4.47.

Is there any problem with this particular version?

**Comment by KrillinsWorld** [comment]
There are a lot of problems with out-of-the-box for OWASP CRS with wordpress and a few other PHP modules we use on the website of URL being carelessly blocked. So in all I have to say NO and disable SM from our website when these modules are needed. I just hope the module is NOT blocking bans from the game server. I am still learning how this works but it is working, just a bit overbearing when the URLS passes from clicks are blocked. It's a bit too much.

Thank you for your assistance. This may be abandoned due to no support for Windows with SM 3.0.4.

We offered to help, but lack of supporting windows is a major flaw when it was developed for windows hosted webservers.

Good Luck!

**Comment by zimmerle** [comment]
In the first post I mentioned this url: https://www.apachelounge.com/download/ there you can find all the support for windows. Including 2.4.47, since April 29th.

OWASP CRS is a separated project and you can read more about it here- https://owasp.org/www-project-modsecurity-core-rule-set/

**Comment by KrillinsWorld** [comment]
All pointless information regarding getting this BUILT for Windows. Being
as you like dragging your feet on this subject I have since MOVED my
subdomains to my Linux server and I am now running 3.0.4 after almost 25
minutes to install from building. But it is working. With the GeoIP being
depreciated and all the .dat files I could find NEVER WORKED, I
mainly wanted to use v3 to use the .mmdb file for GeoIP (Country Blocking).
This is / was the main problem with Mod_Security 2.93, as it is slowly
becoming too deprecated and relying on crippled technology to use just
about rendering it useless.

Thanks AnyhoW
Krillin's World Server System-Operator
