### ISSUE TITLE
Recommended rules: Expand 200001 / JSON body processor rule

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/ModSecurity#2564]
OWASP ModSec CRS project here. We have a pull request to override the very basic Content-Type definition in the
ModSec recommended rule 200001 (-> `REQUEST_HEADERS:Content-Type "application/json"`) with a much more comprehensive list of JSON CTs: [CRS PR 2049](https://github.com/coreruleset/coreruleset/pull/2049).

This is what IANA lists for JSON:

```
curl -s 'https://www.iana.org/assignments/media-types/application.csv' | grep json | awk 'BEGIN{FS=","}{print $2}'
```

I would rather keep things separate, since I think this belongs into ModSec recommended rules.

But that depends on your interest to update 200001. We're happy to provide a PR, but please give us a signal first.

**Comment by martinhsv** [comment]
Overall I think this makes sense.  Given the already-established practice of having the included recommended rules engage the relevant parser, expanding to include more valid json types seems appropriate.

One initial caveat:

Of the types listed, I suspect we should exclude:
```
application/json-seq
```

The definition of this type seems to specifically define the body as not being a single json object, but as a sequence of json objects with defined separators.  In fact, I expect the ModSecurity json parser would fail if we did engage it in these cases.

I'm also slightly wary of this one:
```
application/vnd.apache.thrift.json
```

For all of the ones with a structure 'application/[anything]+json' (this is the vast majority, with well over a hundred subtypes) ...

... these ought to be reasonably safe based on RFC-6838, e.g.:

'Media types that make use of a named structured syntax SHOULD use the appropriate registered "+suffix" for that structured syntax when they are registered.  By the same token, media types MUST NOT be given names incorporating suffixes for structured syntaxes they do not actually employ.'

In that spirit, I think it would be both a low-risk enhancement to update  rule 200001 to match the structure:
application/[anything]+json
