### ISSUE TITLE
Response Body Rules are Not Executed

### ISSUE THREAD

**Issue by frkngksl** [SpiderLabs/ModSecurity#2567]
Hi,

Response Body Phase rules are not executed by ModSecurity, although content-type haeder of response is matched. Specifically, when I check the debug log, it says 
```
[162029056252.586970] [/student.xml] [4] Starting phase RESPONSE_BODY. (SecRules 4)
[162029056252.586970] [/student.xml] [5] Response Content-Type is . It is not marked to be inspected.
```
I guess, it couldn't reach out the content-type header. I sent the GET request using Postman, and I can see the response headers contain a valid Content-Type header.

Debug log: https://gist.github.com/frkngksl/ae0e2744f04cde6e9801a313f92c46a7
Conf file: https://gist.github.com/frkngksl/e51083e894affc856822b763d7fb743b

Example Rule: any phase 4 rule actually. But for example:

```
SecRule RESPONSE_CONTENT_TYPE "^.*/xml"\
    "id:875324,\
    phase:4,\
    deny,\
    t:none,\
    msg:'POST without Content-Length or Transfer-Encoding headers',\
    log,\
    setvar:tx.schemafile='/var/www/student.xsd',\
    exec:/var/www/check_schema.lua"

```

To reproduce:

1- Put an XML file to Apache Web Directory
2- Send a GET request to that file

**Comment by martinhsv** [comment]
Hi @frkngksl 

What version of ModSecurity are you using?

Could you please also provide the actual Content-Type response header.

Your config line:

```
SecResponseBodyMimeType text/plain text/html application/xml text/xml 
```

... appears to be correct for those two "/xml" types.

**Comment by frkngksl** [comment]
Hi @martinhsv ,

I'm using v3.0.4 . The content type of  the response header is application/xml. From the logs, I suspected that it couldn't analyze the content-type header right?

**Comment by martinhsv** [comment]
Hi @frkngksl ,

Yes, that is what appears to be happening.

I was not able to reproduce what you have reported in my 3.0.4 test environment.

If you'd like to share a .pcap file -- or other format that preserves all bytes  -- of a minimal reproduction, I could investigate further.

If you prefer not to do that, one thing you could try to do on your end is narrow down whether it is the header name that is not being found or if the header name is being found but something is going wrong with the associated value of the header.

For example, you could confirm whether the former is the case with something like:

```
SecRule RESPONSE_HEADERS_NAMES "@rx content-type" "id:1003,phase:3,pass,log,auditlog,t:none,t:lowercase"
```

**Comment by martinhsv** [comment]
Was there anything further on this?

There are no known parsing -- or related -- bugs that would cause what you have reported.  Without additional information there really isn't anything that can be done with this item.
