### ISSUE TITLE
Regarding library documentation

### ISSUE THREAD

**Issue by Vaibhavgoe** [SpiderLabs/ModSecurity#2569]
Dear Team,
  We are trying to create html formation of the library documentation written in Doxygen format.  After conversion , it shows the blank html file. Can anyone please help to get the library documentation.

Thanks

**Comment by zimmerle** [comment]
Hi @Vaibhavgoe,

It is a while since the last time I generate those. I am going to look. Maybe we had an update on Doxygen/Doxygen m4 that broke our integration. I am going to check and I will get back to you.

**Comment by zimmerle** [comment]
@Vaibhavgoe how exactly you are trying to generate the HTML files?

**Comment by Vaibhavgoe** [comment]
I am using Doxygen GUI frontend to generate the html. pls see attachment
![Capture](https://user-images.githubusercontent.com/41989159/118931031-1ed3d780-b964-11eb-8a2e-608b9032ce72.JPG)

**Comment by zimmerle** [comment]
Try to use the command line -- inside the folder doc, use:

```
doxygen doxygen.cfg
```

you should have the **htmls** inside the **html** folder.
