### ISSUE TITLE
Compatibility of "FilterInFrame" rule and Rainloop webmail 

### ISSUE THREAD

**Issue by Alinthda64** [SpiderLabs/ModSecurity#2571]
**Describe the bug**
The "FilterInFrame" rule blocks the installation of Rainloop 1.15.0 

**A clear and concise description of what the bug is.**
Rainloop 1.14.0 and modsecurity works fine. But the rule "FilterInFrame" blocks the update and creates a 403 error.
Once the rule is disabled, everything works normally

**Logs and dumps**
[client xx.xx.xx.xx] ModSecurity: Access denied with code 403 (phase 4). Pattern match "(?i:<[\\\\t\\\\n\\\\r ]{0,}IFRAME[\\\\t\\\\n\\\\r ]{0,}?[^>]{0,}?src=\\\\x22javascript:)" at RESPONSE_BODY. [file "/etc/apache2/modsecurity.d/rules/comodo_free/19_Outgoing_FilterInFrame.conf"] [line "21"] [id "214550"] [rev "1"] [msg "COMODO WAF: Malicious iframe+javascript tag in output||mailtest.xxxx.com|F|3"] [data "Matched Data: <iframe src=\\x22javascript: found within RESPONSE_BODY: <!DOCTYPE html><html class=\\x22no-js rl-booted-trigger rl-started-trigger glass\\x22 dir=\\x22ltr\\x22><head><noscript><meta http-equiv=\\x22refresh\\x22 content=\\x220; URL=./?/NoScript\\x22/></noscript><meta charset=\\x22utf-8\\x22/><meta http-equiv=\\x22X-UA-Compatible\\x22 content=\\x22IE=edge,chrome=1\\x22/><meta name=\\x22viewport\\x22 content=..."] [severity "ERROR"] [tag "CWAF"] [tag "FilterInFrame"] [hostname "mailtest.xxxxx.com"] [uri "/index.php"] [unique_id "YKcu0F-MpB9Bn3Pmzga9UAAAAFg"]

**To Reproduce**

The fault is systematically reproduced when Rainloop 1.15.0 and mod security are activated. All rainloops users are affected 

**Expected behavior**

Normal operation of Rainloop, which can be found when you deactivate the "FilterInFrame" rule .

**Dedecated server**
 - ModSecurity version 2.9.3.2-v.ubuntu.18.04+p18.0.35.0+t210414.0038
 - WebServer: Apache
 - OS Ubuntu 18.04.1 LTS & Plesk 

**Rule Set Comodo**
 - Running any public or commercial rule set? public

**Comment by martinhsv** [comment]
Hi @Alinthda64 ,

This github project is really about the ModSecurity engine.  Rule sets are provided separately.

It sounds like your question is related to a particular rule from Comodo.  Specific questions about that rule are better directed to them.
