### ISSUE TITLE
Can't install YAJL with ModSecurity

### ISSUE THREAD

**Issue by PedroRTomas** [SpiderLabs/ModSecurity#2572]
Hello,
Is there any updated script that I can follow in order to compile ModSecurity with YAJL in order to parse JSON content present in POST requests?
I've tried to follow: https://gist.github.com/rpfilomeno/1140359f4bd360137a98
But, some libraries not found related issues were thrown. (Mainly libxml2 and pcre)

At the moment, is there any way to accomplish what has been described without having to manually compile the code? If not, once again, is there any place where I can found the most updated instructions?

Thanks in advance,

**Comment by zimmerle** [comment]
Hi @PedroRTomas,

Can you share yours **config.log** file?

**Comment by zimmerle** [comment]
@PedroRTomas: ping

**Comment by PedroRTomas** [comment]
Hi there,
Sorry for the delay. I end up being able to successfully compile YAJL, but with the 2.x mod_security version 
(From: https://github.com/SpiderLabs/ModSecurity/tree/v2/master)

Despite that, in the next days I will try to replicate the process with 3.x version and share the config.log file, as requested.

**Comment by zimmerle** [comment]
Please re-open the issue whenever you have the info ready ;)
