### ISSUE TITLE
 exec: Lua support was not enabled. 

### ISSUE THREAD

**Issue by HL123** [SpiderLabs/ModSecurity#2575]
os: open suse 12.

1）When I compile ModSecurity，prompt lua was not enabled.

ModSecurity - v3.0.4 for Linux
 
---------------------------------------
 Mandatory dependencies
   + libInjection                                  ....v3.9.2-30-gbf234eb
   + SecLang tests                                 ....c8cf2c5
 
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (GeoIP) v1.5.0
         -lGeoIP , -I/usr/include/ 
   + LibCURL                                       ....not found
   + YAJL                                          ....found v2.0.4
      -lyajl , -DWITH_YAJL 
   + LMDB                                          ....not found
   + LibXML2                                       ....not found
   + SSDEEP                                        ....not found
   + LUA                                           ....not found     

----------------------------------------
2） While  the os have lua .

----------------------------------------
linux-3z0f:/home/suse/modsecurity-v3.0.4 # whereis lua
lua: /usr/bin/lua /usr/bin/lua5.2 /usr/lib64/lua /usr/share/lua /usr/share/man/man1/lua.1.gz
-----------------------------------------

 thanks

**Comment by willyamcts** [comment]
@HL123  is required liblua. Check if there is a **liblua** installed. The installation lua not accompany the liblua, but obviously lua is requeriment to liblua. 

If necessary compile liblua from source view https://www.linuxfromscratch.org/blfs/view/8.3/general/lua.html

**Comment by HL123** [comment]
Thanks , When I install liblua, it has work。 While when I run it, it doesn't work。

I use nginx  + modsecurity + lua . The  modsecurity.conf  have this 
   SecRuleScript ARGS:p “/appl/gap-nginx/nginx/lua/exec.lua” “block”

When I execute ./nginx -t ，it  prompt   the following information 
“modsecurity_rules_file" directive Rules error. File: /appl/gap-nginx/nginx/conf/modsecurity.conf. Line: 34. Column: 20. exec: Lua support was not enabled.  in /appl/gap-nginx/nginx/conf/nginx.conf:41”

**Comment by willyamcts** [comment]
You compiled ModSecurity with "--with-lua" option?
See in output from compilation if liblua was included

MAYBE do you needs input full path dir or "lib" from lua:
`   --with-lua=/path/lua/lib`

**Comment by zimmerle** [comment]
Since there is no feedback from the user, I am assuming that the issue was fixed.
