### ISSUE TITLE
Question about IIS and Modsecurity

### ISSUE THREAD

**Issue by KernelPan1k** [SpiderLabs/ModSecurity#2576]
Hello to all,

I'm not reporting a problem, it's some questions. I am interested in using modsecurity on IIS. 

- Do you have plan to make an installer (.msi) for version 3 on IIS?
- If I start with an installation of version 2.9 and then upgrade to version 3, will my rules still be compatible?
- How long do you plan to stop maintenance on version 2?
- If you were to use modsecurity on IIS for a new installation and for the long term would you advise to start with version 2 or 3?

I thank you in advance for your answers and good day

KP

**Comment by martinhsv** [comment]
Hello @KernelPan1k ,

If you wish to use ModSecurity with IIS you should use 2.9.x.

There is no current plan to stop maintenance on ModSecurity v2.

Regarding your final question:  If using ModSecurity for IIS, you should use 2.9.x.
