### ISSUE TITLE
SecUploadKeepFiles generate multiples files 

### ISSUE THREAD

**Issue by willyamcts** [SpiderLabs/ModSecurity#2577]
**Describe the bug**
I'm using file scan script via clamav ([coreruleset](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/util/av-scanning/runav.pl)) and I ran into a problem apparently in the parameter "SecUploadKeepFiles". 

In using "SecUploadKeepFiles" with Off value in conjunction with file scan rule via clamav, all uploaded files match the created rule, that is, all files are considered as viruses.

Using "SecUploadKeepFiles" with On value, the scan works correctly but generates several files that are incremented by a few KB at a time until reaching the total file size. For example: I have a 1MB file, when uploading it generates a file with 10KB, 2nd with 15KB, 3rd with 25KB and so on until reaching the file size, so a 1MB file became 100MB in multiple files.

```
total 148444
-rw------- 1 httpd httpd 1104384 Jun 10 10:06 20210610-100609-162334110498.227595-file-HIuoO0
-rw------- 1 httpd httpd 1101848 Jun 10 10:06 20210610-100608-162334110498.227595-file-S7mlzp
-rw------- 1 httpd httpd 1097051 Jun 10 10:06 20210610-100608-162334110498.227595-file-YvgRbQ
-rw------- 1 httpd httpd 1094832 Jun 10 10:06 20210610-100607-162334110498.227595-file-KEMSDi
-rw------- 1 httpd httpd 1086640 Jun 10 10:06 20210610-100607-162334110498.227595-file-fJ8GUM
-rw------- 1 httpd httpd 1086640 Jun 10 10:06 20210610-100606-162334110498.227595-file-lN3IZi
-rw------- 1 httpd httpd 1078448 Jun 10 10:06 20210610-100606-162334110498.227595-file-XuGDTQ
-rw------- 1 httpd httpd 1078448 Jun 10 10:06 20210610-100605-162334110498.227595-file-wM8yBq
-rw------- 1 httpd httpd 1069838 Jun 10 10:06 20210610-100605-162334110498.227595-file-KfAZ61
-rw------- 1 httpd httpd 1069838 Jun 10 10:06 20210610-100604-162334110498.227595-file-c92BvF
-rw------- 1 httpd httpd 1064692 Jun 10 10:06 20210610-100604-162334110498.227595-file-EjS9Fk
-rw------- 1 httpd httpd 1059632 Jun 10 10:06 20210610-100603-162334110498.227595-file-kJIYw1
-rw------- 1 httpd httpd 1056100 Jun 10 10:06 20210610-100603-162334110498.227595-file-E0mE3J
-rw------- 1 httpd httpd 1054738 Jun 10 10:06 20210610-100603-162334110498.227595-file-LwELeu
-rw------- 1 httpd httpd 1047077 Jun 10 10:06 20210610-100602-162334110498.227595-file-tA5i4f
-rw------- 1 httpd httpd 1047077 Jun 10 10:06 20210610-100602-162334110498.227595-file-EkPeB3
-rw------- 1 httpd httpd 1036341 Jun 10 10:06 20210610-100601-162334110498.227595-file-O0UmPS
-rw------- 1 httpd httpd 1036341 Jun 10 10:06 20210610-100601-162334110498.227595-file-V5hzQJ
-rw------- 1 httpd httpd 1028149 Jun 10 10:06 20210610-100600-162334110498.227595-file-ewTrHC
....
```

Rule test:
```
SecTmpDir /tmp
SecUploadDir /tmp/clam
SecUploadKeepFiles On

SecRule FILES_TMPNAMES "@inspectFile /usr/local/modsecurity/crs_rules/util/av-scanning/runav.pl" \
 "id:160,phase:2,t:none,deny,log,\
  msg:'ClamAV: Suspect file',\
  tag:'MALICIOUS_SOFTWARE/VIRUS'"
```

**To Reproduce**
- Have a simple web-upload page ([example here](https://gist.github.com/willyamcts/1db627b17505421f592edfad0eedab5c))
- Set block rule above
- Upload file

**Expected behavior**
- With "SecUploadKeepFiles" On it should not generate multiple files for a single uploaded file.
- Regardless of the value of "SecUploadKeepFiles" On or Off the scan should occur correctly.

**Server (please complete the following information):**
 - ModSecurity version (and connector): ModSecurity v3.0.4 with apache-connector branch master
 - WebServer: Apache v2.4.43
 

**Rule Set (please complete the following information):**
 - Running Coreruleset version 3.3

**Comment by martinhsv** [comment]
Hello @willyamcts ,

It is not recommended to use ModSecurity v3 with Apache.  There are still enough portions of functionality that do not work correctly that it is not considered production-ready.

With Apache, ModSecurity v2.9.x is still the recommended version to use.

**Comment by willyamcts** [comment]
Thanks @martinhsv.

If it is feasible to keep the issue open for resolution in version 3.

I tested in version 2.9.3 and not generated multiple files in upload, i.e working ok

**Comment by martinhsv** [comment]
It would only be a valid issue in ModSecurity v3 if it occurs with supported software.  E.g. if used with nginx and the nginx connector.
