### ISSUE TITLE
2.9.4 released (and CHANGES wrong) or is the tag just an RC?

### ISSUE THREAD

**Issue by rainerjung** [SpiderLabs/ModSecurity#2579]
There's a 2.9.4 tag (6 days old), but CHANGES says July 14 2021 as release date.
So is that a typo in CHANGES and it was already released (what date please?), or is the tag just a release candidate or similar and you expect to release on July 14th?

**Comment by dune73** [comment]
I do not know what's happening, but said release was quickly removed again. I wish the developers would explain what's going on.

**Comment by zimmerle** [comment]
@rainerjung can you share the commit hash?

Indeed we have had a release scheduled for today -- have it announced here: [v2.9.4](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.4).

There may be something wrong with the automation scripts that let the release tag out before the expected date, even with the typo in the CHANGES, as you have mentioned. If you happen to know the commit hash, DevOps will be pleased. Thank you for noticing and having it reported :eyes: :eyes:

**Comment by rainerjung** [comment]
No, I on't have the original commit hash and the tag unfortunately seems to be overwritten now.

**Comment by dune73** [comment]
Would this help @zimmerle ?

![tmp](https://user-images.githubusercontent.com/618722/123053199-efe9cf00-d403-11eb-9c64-e59d98d3a234.png)

-> 782ede2

Also: Your repo links modsecurity.org on the front page, but the website redirects back to the repo. Is this temporary or have you given up on the website for good?

**Comment by martinhsv** [comment]
Is there any reason to keep this issue open?

**Comment by dune73** [comment]
Not from my side. @rainerjung?

**Comment by rainerjung** [comment]
No, I would say it is obsolete.
