### ISSUE TITLE
Whitelisting headers and all cookies

### ISSUE THREAD

**Issue by archletekke** [SpiderLabs/ModSecurity#2581]
Hey all,

I am veery new to ModSecurity and trying to figure out how one would go by whitelisting some request headers by their names (for example, "referer") and *all cookies* from scanning. I was deep in the source code already, but couldn't quite figure out how

What I tried so far is as follows but does not work:
```
    SecRule REQUEST_HEADERS "^(.*)$ "phase:1,nolog,allow,ctl:ruleEngine=Off"
    SecRule REQUEST_COOKIES "^(.*)$ "phase:1,nolog,allow,ctl:ruleEngine=Off"
```

What I am thinking for the headers stuff is as follows:
```
SecRule REQUEST_HEADERS:referer "^(.*)$" "id:1,phase:1,skip:1"
```

However I don't get it how I could ignore all cookies from analysis.

Any help is appriciated :)

**Comment by martinhsv** [comment]
Hi @archletekke ,

Assuming you want other portions of the request to still be scanned against your rule set, you don't really want to do things like that.

You don't mention which version of ModSecurity you are using, but typically the approach would be to use something more like SecRuleUpdateTargetById.

I usually suggest being more discriminating and only turn off analysis of rules/parts where necessary.  But if you really want to do everything, and your rule set has ids 300000-399999 you should be able to do that with something like 

Never analyze any Cookies
SecRuleUpdateTargetById 300000-399999 !REQUEST_COOKIES

Never analyze Referer header:
SecRuleUpdateTargetById 300000-399999 !REQUEST_HEADERS:referer
