### ISSUE TITLE
Could not set variable “USER.user_false_counter” as the collection does not exist in ModSecurity logs Apache (Windows OS)

### ISSUE THREAD

**Issue by devikandixit** [SpiderLabs/ModSecurity#2582]
We are using apache module for our web server(windows OS). We need to prevent unsuccessful authentication attempt by the user. Hence we thought to use Mod Security module. I uses this standard configuration setting in "modsecurity-minimal.conf" as below SecStatusEngine On SecRule IP:bf_block "@eq 1"
"id:'2000004',phase:4,deny,
logdata:'Access denied [by IP] IP: @%{REMOTE_ADDR}, user: %{USER.name}' SecRule USER:bf_block "@eq 1"
"id:'2000005',phase:4,deny,
logdata:'Access denied [by USER] IP: @%{REMOTE_ADDR}, user: %{USER.name}'

SecRule REQUEST_HEADERS:authorization "Basic ([a-zA-Z0-9]+=*)$" "phase:3,nolog,pass,id:2000012,chain,capture"
    SecRule TX:1 "^([-a-zA-Z0-9_]+):" "t:base64Decode,chain,capture"                
    SecAction initcol:USER=%{TX.1},setvar:USER.name=%{TX.1},initcol:IP=%{REMOTE_ADDR}
    
    
SecRule RESPONSE_STATUS "401" \
    "phase:5,pass,id:2000015,chain,logdata:'basic auth de @%{IP}, var: %{IP.begin}, user: %{USER.name}, ufc: %{USER.user_false_counter}, block: %{USER.bf_block}, IPblock: %{IP.bf_block}, ifc: %{IP.ip_false_counter}'"        
    SecAction setvar:USER.user_false_counter=+1,setvar:IP.ip_false_counter=+1,expirevar:USER.user_false_counter=300,expirevar:IP.ip_false_counter=300

# Check for too many failures for a single username, blocking 30 seconds after 3 tries
SecRule USER:user_false_counter "@ge 2" \
            "id:'2000020',phase:3,t:none,pass,\
            setvar:USER.bf_block,\
            setvar:!USER.user_false_counter,\
            expirevar:USER.bf_block=30"

# Check for too many failures from a single IP address. Block for 5 minutes after 10 tries.
    SecRule IP:ip_false_counter "@ge 2" \
            "id:'2000021',phase:3,pass,t:none, \
            setvar:IP.bf_block,\
            setvar:!IP.ip_false_counter,\
            expirevar:IP.bf_block=300"      
However when I see the modsec_debug.log, I get following error.

Could not set variable "USER.user_false_counter" as the collection does not exist.

Could not set variable "IP.ip_false_counter" as the collection does not exist.

Please help me how to resolve this issue.

**Comment by martinhsv** [comment]
Hello @devikandixit ,

You don't mention which version of ModSecurity that you have, but one likely problem that stands out immediately in your chained rule 2000012 is that:

- the first rule in the chain is matching (in the capture group) a string of alphanumerics followed by zero or more '=' characters.
- the second rule in the chain is then attempting to match that capture against the regex '^([-a-zA-Z0-9_]+):'.  I.e. it is requiring a colon character (:) to be present in the string ... but one will never exist in the capture from the first rule in the chain

You can confirm this in the debug log (use level 9).  Follow the execution of your rule 2000012 rule.  My guess is that the first rule in the chain is resulting in 'Rule returned 1' but that the second rule in the chain shows 'Rule returned 0'.

**Comment by devikandixit** [comment]
Hello @martinhsv,

I am using ModSecurity  2.x.
Thank you for your suggestion.
I will use debug log level 9 and check the log value.

**Comment by devikandixit** [comment]
I have matched capture group with regex. Still I am getting the error. 

**Could not set variable "USER.user_false_counter" as the collection does not exist.
Could not set variable "IP.ip_false_counter" as the collection does not exist.**

I believe  **SecAction initcol:USER=%{TX.1}**  should initialize collection USER. 
Please let me know whether anything I am missing.

**Comment by martinhsv** [comment]
Which rule is being processed when you see those messages?

**Comment by martinhsv** [comment]
Does your newer issue (#2585 ) imply that this issue is resolved?

**Comment by devikandixit** [comment]
This issue is not resolved. Still I am getting this issue.

**Comment by martinhsv** [comment]
> I believe SecAction initcol:USER=%{TX.1} should initialize collection USER.

Yes.

I tried a version of your rules and I did not get the error messages that you report.  (Although my test was on Ubuntu.)

I'm going to need more information to do anything further with this.

At a minimum, per my question from 6 days ago: 'Which rule is being processed when you see those messages?'

And actually, the relevant debug log output would likely be useful.

**Comment by devikandixit** [comment]
> Which rule is being processed when you see those messages?

Rule **1168948** is being processed when I see the error message.

Please have a look at below logs for the same

Initialising logging.
Starting phase LOGGING.
This phase consists of 2 rule(s).
Recipe: Invoking rule 1176f20; [file "./Apache/conf/extra/modsecurity-minimal.conf"] [line "19"] [id "2000015"].
Rule 1176f20: SecRule "RESPONSE_STATUS" "@rx 401" "phase:5,log,auditlog,pass,id:2000015,chain,logdata:'basic auth de @%{IP}, var: %{IP.begin}, user: %{USER.name}, ufc: %{USER.user_false_counter}, block: %{USER.bf_block}, IPblock: %{IP.bf_block}, ifc: %{IP.ip_false_counter}'"
Transformation completed in 0 usec.
Executing operator "rx" with param "401" against RESPONSE_STATUS.
Target value: "401"
Operator completed in 0 usec.
Rule returned 1.
Match -> mode NEXT_RULE.
Recipe: Invoking rule 1168948; [file "./Apache/conf/extra/modsecurity-minimal.conf"] [line "20"].
Rule 1168948: SecAction "setvar:USER.user_false_counter=+1,setvar:IP.ip_false_counter=+1,expirevar:USER.user_false_counter=300,expirevar:IP.ip_false_counter=300"
Transformation completed in 0 usec.
Executing operator "unconditionalMatch" with param "" against REMOTE_ADDR.
Target value: "10.102.13.8" 
Operator completed in 0 usec.
Setting variable: USER.user_false_counter=+1
Could not set variable "USER.user_false_counter" as the collection does not exist.
Setting variable: IP.ip_false_counter=+1
_**Could not set variable "IP.ip_false_counter" as the collection does not exist.**_
Expiring variable: USER.user_false_counter=300
_**Could not expire variable "USER.user_false_counter" as the collection does not exist.**_
Expiring variable: IP.ip_false_counter=300
Could not expire variable "IP.ip_false_counter" as the collection does not exist.
Failed to resolve macro %{IP}: Missing mandatory parameter for variable IP.
Rule returned 1.
Match -> mode NEXT_RULE.

**Comment by devikandixit** [comment]
> > I believe SecAction initcol:USER=%{TX.1} should initialize collection USER.
> 
> Yes.
> 
> I tried a version of your rules and I did not get the error messages that you report. (Although my test was on Ubuntu.)
> 
> I'm going to need more information to do anything further with this.
> 
> At a minimum, per my question from 6 days ago: 'Which rule is being processed when you see those messages?'
> 
> And actually, the relevant debug log output would likely be useful.

We are using Apache server on Windows. We do not have our own custom login page for our web server. We are relying on OS controlled(NTLM/Kerberos Authentication)log in page. However log in page do not prevent user log in (delayed log in for ex)  after unsuccessful authentication. Hence we thought to use Mod Security to prevent it.

**Comment by martinhsv** [comment]
The 200015 in that case is the relevant rule id.

You'd have to inspect earlier in the debug log, but it seems likely that the initcol in 200012 is not being executed for those transactions where you see the 'Could not set variable ...' messages.

If that is in fact the case, it would be useful to know whether:
a) 200012 is not being executed at all
b) 200012 is being executed, but the conditions in the first two portions of the chain have not been satisfied.

One possible reason for (a) -- and actually you may want to change this anyway -- may be related to the phase in which you are running 200012.  Since that rule is only using data that is already available in phase:1, it would be more usual to run the rule in that phase (or at least no later than phase:2).

**Comment by martinhsv** [comment]
Anything further on this?
