### ISSUE TITLE
Performance bug; GCC 4 to 9.x with O1/O2/03 inline strlen() to a slower inlined expansion

### ISSUE THREAD

**Issue by monkburger** [SpiderLabs/ModSecurity#2583]
While doing some performance auditing of Mod Security (perf record/stat), I noticed that certain hot paths of code are slightly slower, after doing more investigation it appears that with Mod Security 2.9.4 that built with GCC 4.8.5 to 9.x, -O2 (and -O3) generate slow inline expansions of things like strlen(). I tested this out on CentOS 7 with GCC 4.8.5 to GCC 9, and my results are below; 

-O0 (or no optimizations at all), the generated code calls the libc strlen() function (which is fast on modern distros, glibc uses cpuid to either use a sse2 strlen() or a more elaborate one based on SSE4 (or AVX?) 
-O1 the generated code uses a simple inline expansion (which is slow) 
-O2/-03, the generated code uses another inline expansion. (again, slow) 

This is a known bug with GCC that is not going to be backported; 

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88809

Also see;

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95458

Reproduction/More information: 

Run Apache in single mode with perf record (ie: perf record /usr/sbin/httpd -X -d /usr/local/apache -D FOREGROUND) 
On another SSH session, just send some dummy traffic to the server (via lynx/curl/wget) 
Stop the single mode. Look at the perf data and it should begin with msre_ruleset_process_phase and scroll down to the repnz instruction. 

Here is a perf report that shows the repnz issues; 

https://i.imgur.com/rQKLnIh.png

Here's the 'fix' - notice how it's directly calling glibc's strlen() instead of using it's own inline expansion (see the solution) 

https://i.imgur.com/EAidCjM.png

Using h2load with the fix I noticed a slight decrease in CPU usage and more RPS, but I need to do some more profiling of that and other functions. I'm going to wrap msre_ruleset_process_phase() in a rdtsc/clock_gettime to measure cycles. 

Solutions:

- Mod Security will probably need a configure hack to detect if GCC && GCC_version = <10 and then use either '-fno-builtin' (recommended) or '-fno-builtin-strlen' 
- Use a home grown strlen() that calls the libc strlen (ugly)

**Comment by marcstern** [comment]
use either '-fno-builtin' (recommended) or
      '-fno-builtin-strlen'
    The problem also seems to be present with many other string
    functions, like strncmp.
    '-fno-builtin' would probably add a penalty in a lot of functions
    (memcpy, ...).
    Wouldn't the best be to list all sting functions?
    
    On 27-06-2021 02:13, monkburger wrote:
    
    
      
      While doing some performance auditing of Mod Security (perf
        record/stat), I noticed that certain hot paths of code are
        slightly slower, after doing more investigation it appears that
        with Mod Security 2.9.4 that built with GCC 4.8.5 to 9.x, -O2
        (and -O3) generate slow inline expansions of things like
        strlen(). I tested this out on CentOS 7 with GCC 4.8.5 to GCC 9,
        and my results are below;
      -O0 (or no optimizations at all), the generated code calls the
        libc strlen() function (which is fast on modern distros, glibc
        uses cpuid to either use a sse2 strlen() or a more elaborate one
        based on SSE4 (or AVX?)
        -O1 the generated code uses a simple inline expansion (which is
        slow)
        -O2/-03, the generated code uses another inline expansion.
        (again, slow)
      This is a known bug with GCC that is not going to be
        backported;
      https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88809
      Also see;
      https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95458
      Reproduction/More information:
      Run Apache in single mode with perf record (ie: perf record
        /usr/sbin/httpd -X -d /usr/local/apache -D FOREGROUND)
        On another SSH session, just send some dummy traffic to the
        server (via lynx/curl/wget)
        Stop the single mode. Look at the perf data and it should begin
        with msre_ruleset_process_phase and scroll down to the repnz
        instruction.
      Here is a perf report that shows the repnz issues;
      https://i.imgur.com/rQKLnIh.png
      Here's the 'fix' - notice how it's directly calling glibc's
        strlen() instead of using it's own inline expansion (see the
        solution)
      https://i.imgur.com/EAidCjM.png
      Using h2load with the fix I noticed a slight decrease in CPU
        usage and more RPS, but I need to do some more profiling of that
        and other functions. I'm going to wrap
        msre_ruleset_process_phase() in a rdtsc/clock_gettime to measure
        cycles.
      Solutions:
      
        Mod Security will probably need a configure hack to detect
          if GCC && GCC_version = <10 and then use either
          '-fno-builtin' (recommended) or '-fno-builtin-strlen'
        Use a home grown strlen() that calls the libc strlen (ugly)
      
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/SpiderLabs/ModSecurity/issues/2583",
"url": "https://github.com/SpiderLabs/ModSecurity/issues/2583",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by monkburger** [comment]
According to my testing of a simple C program, repnz scasb is VERY slow, about 1 byte per CPU clock cycle on a Xeon. This is an actual GCC bug that is Present from GCC 3.x to GCC9/10 which was fixed upstream. At -O1/-O2/-O3, gcc always (even without known alignment) chooses to inline strlen as repnz scasb!

Agner Fo's optimization manual says that REPNE SCASB is to be avoided. The Intel optimization manual says this: “However, using a REP prefix with string scan instructions (SCASB, SCASW, SCASD, SCASQ) or compare instructions (CMPSB, CMPSW, SMPSD, SMPSQ) is not recommended for high performance. Consider using SIMD instructions instead."

**Comment by zimmerle** [comment]
Hi @monkburger,

Interesting findings. Considering the maintainability of the code, I would suggest the utilization of a GCC without this issue (patched or newer version) -- or clang, as oppose to having ModSecurity acting differently depending on the compiler version. Is it not an option?

**Comment by marcstern** [comment]
Any way to check if a GCC is buggy?
Not based on the version number, because a provider (Redhat for instance) patches the applications while keeping the same version number.

**Comment by monkburger** [comment]
> Any way to check if a GCC is buggy?
> Not based on the version number, because a provider (Redhat for instance) patches the applications while keeping the same version number.

```
#define _POSIX_C_SOURCE 199309L
#include <err.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

static size_t len = 512;
static char *buffer;
static int count = 10000;

__attribute__ ((weak))
size_t
call_strlen (const char *s)
{
  return strlen (s);
}

__attribute__ ((weak, cold))
size_t
slow_strlen (const char *s)
{
  return strlen (s);
}

__attribute__ ((weak))
size_t
call_slow_strlen (const char *s)
{
  return slow_strlen (s);
}

static void
bench (const char *what, size_t (*fptr) (const char *))
{
  struct timespec start;
  if (clock_gettime (CLOCK_MONOTONIC, &start) != 0)
    err (1, "clock_gettime");

  for (int i = 0; i < count; ++i)
    fptr (buffer);

  struct timespec end;
  if (clock_gettime (CLOCK_MONOTONIC, &end) != 0)
    err (1, "clock_gettime");

  double delta = (end.tv_sec - start.tv_sec) * 1e9;
  delta += end.tv_nsec - start.tv_nsec;
  printf ("%s: %f ns/call\n", what, delta / count);
}

int
main (void)
{
  buffer = malloc (len + 1);
  if (buffer == NULL)
    err (1, "malloc");
  memset (buffer, 'a', len);
  buffer[len] = 0;

  for (int i = 0; i < 10; i++)
    {
      bench ("strlen", call_strlen);
      bench ("strlen (cold)", call_slow_strlen);
    }

  free (buffer);

  return 0;
}

```

Save that and then compile it with this to show the slowness; 

gcc -O2 -std=c99 strlen.c -o strlen

vs Turning off inline expansion; 

gcc -O2 -std=c99 strlen2.c -o strlen2 -fno-builtin

**Comment by marcstern** [comment]
For those interested, here is the result on a CentOS 8 fully updated:

Inline on:
strlen: 6.855100 ns/call
strlen (cold): 244.259200 ns/call
strlen: 9.960600 ns/call
strlen (cold): 240.903600 ns/call
strlen: 9.806600 ns/call
strlen (cold): 246.326100 ns/call
strlen: 9.407400 ns/call
strlen (cold): 249.770800 ns/call
strlen: 9.563400 ns/call
strlen (cold): 244.109700 ns/call
strlen: 10.503800 ns/call
strlen (cold): 240.026000 ns/call
strlen: 9.796900 ns/call
strlen (cold): 242.260500 ns/call
strlen: 9.922000 ns/call
strlen (cold): 557.132000 ns/call
strlen: 6.829200 ns/call
strlen (cold): 249.128900 ns/call
strlen: 7.761400 ns/call
strlen (cold): 266.049900 ns/call

Inline off:
strlen: 6.854800 ns/call
strlen (cold): 9.484400 ns/call
strlen: 6.827800 ns/call
strlen (cold): 7.375700 ns/call
strlen: 6.825800 ns/call
strlen (cold): 7.376300 ns/call
strlen: 6.165800 ns/call
strlen (cold): 6.573700 ns/call
strlen: 6.274000 ns/call
strlen (cold): 6.574900 ns/call
strlen: 6.275200 ns/call
strlen (cold): 6.572600 ns/call
strlen: 6.274500 ns/call
strlen (cold): 6.575100 ns/call
strlen: 13.067700 ns/call
strlen (cold): 12.048100 ns/call
strlen: 6.164000 ns/call
strlen (cold): 6.571100 ns/call
strlen: 6.162000 ns/call
strlen (cold): 6.572500 ns/call

I guess the results are clear ...

Thanks a lot to @monkburger for this useful info.

**Comment by martinhsv** [comment]
While this was indeed an interesting finding ...

Given that that this is really a compiler idiosyncrasy that has been corrected in recent versions of gcc, the most appropriate approach here is probably to take no action within the ModSecurity project.

I'll go ahead and close this.
