### ISSUE TITLE
why the rules load function calls sys_wait4 and csx_rethrow

### ISSUE THREAD

**Issue by leyao-daily** [SpiderLabs/ModSecurity#2584]
In the src/parser/seclang-parser.cc and src/parser/driver.cc, there are a few system calls to sys_wait4 but I can not locate the code s. Do I make a mistake?

**Comment by martinhsv** [comment]
Hello @leyao-daily ,

Perhaps I have misunderstood you somehow, but I don't see the calls to which you refer in either of these two files:

https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/driver.cc
https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/seclang-parser.cc

**Comment by leyao-daily** [comment]
> Hello @leyao-daily ,
> 
> Perhaps I have misunderstood you somehow, but I don't see the calls to which you refer in either of these two files:
> 
> https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/driver.cc
> https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/parser/seclang-parser.cc

What confused me is that, when I call rulesset.load(...), the application will look for symbol sys_wait4, but I do not find anything about this in Modsecurity rules load. (driver.load)

**Comment by martinhsv** [comment]
The source code for system functions would not typically be part of an application's code base.
