### ISSUE TITLE
Clear collections data (question)

### ISSUE THREAD

**Issue by willyamcts** [SpiderLabs/ModSecurity#2594]
I would like to clean up ModSecurity collections eventually, any way to do this need to manually delete the "SecDataDir" files?

**Server (please complete the following information):**
 - ModSecurity version (and connector): ModSec v2.9.3
 - WebServer: Apache 2.4

**Comment by martinhsv** [comment]
Hi @willyamcts ,

If you want to delete an individual collection variable, a typical way to do this is with something like (from https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#setvar):

```
To remove a variable, prefix the name with an exclamation mark: setvar:!TX.score
```

But it sounds like maybe want something broader than that.

You may want to have a look at relevant pages in 'ModSecurity Handbook' (pp. 123-124 in this edition; p. 128 in the 2nd edition):

https://books.google.ca/books?id=HnQl5OVtOYgC&pg=PA123&lpg=PA123&dq=modsecurity+delete+setvar+%22!ip.key%22&source=bl&ots=0GmnXfCgNh&sig=ACfU3U3TE8lIrWkmZJz9Kuc5lIFUcrOV0A&hl=en&sa=X&ved=2ahUKEwi-9Kb34PHxAhXKG80KHX4fCS4Q6AEwCHoECAoQAw#v=onepage&q=modsecurity%20delete%20setvar%20%22!ip.key%22&f=false

**Comment by willyamcts** [comment]
Hi @martinhsv, thanks your explanation.

Good, this worked. But exist any way to remove without using rules (including script that is invoked via rule) ??

For clear all collections, i'm delete files in path "SecDataDir". But afect all collections.

**Comment by willyamcts** [comment]
Hi,

Found sdbm-utils to remove specific collections.

Here is the repository: https://github.com/SpiderLabs/modsec-sdbm-util

Thanks @martinhsv.
