### ISSUE TITLE
modsecurity-2.9.4.tar.gz.asc is not a detached signature 

### ISSUE THREAD

**Issue by KIC-8462852** [SpiderLabs/ModSecurity#2599]
Hi, can you please check the modsecurity-2.9.4.tar.gz.asc signature file? It is not a detached signature as it used to be. Thx.

**Comment by martinhsv** [comment]
Hi @KIC-8462852 ,

Thanks for drawing attention to this.

You are correct that it is not a detached signature.  I don't believe this alternative way of signing was a deliberately chosen change from past practice (as you may have perhaps guessed from the fact that the similar-timeframe v3.0.5 does use detached signatures).

You can assume that with future releases, detached signatures will be the preferred option.

I hope the current status with respect to v2.9.4 isn't causing you more than minor inconvenience?

**Comment by martinhsv** [comment]
With no further activity on this, I'll go ahead and close ...
