### ISSUE TITLE
ปัญหา LCP: นานกว่า 4 วินาที (อุปกรณ์เคลื่อนที่) องค์ประกอบที่คลิกได้อยู่ใกล้กันเกินไป ข้อความมีขนาดเล็กเกินไป

### ISSUE THREAD

**Issue by kriskhunthong** [SpiderLabs/ModSecurity#2608]
Content removed.

**Comment by martinhsv** [comment]
I'm going to simply close this.

There is no actual information in the ticket, and there are some suspicious indicators re: the linked web site.
