### ISSUE TITLE
ModSecurity 3.3 doesn't block POST requests

### ISSUE THREAD

**Issue by Dosyk** [SpiderLabs/ModSecurity#2610]
ModSecurity 3 (for Apache) doesn't seem to be blocking anything sent through post (like forms). Logs say:

> ModSecurity: Access denied with code 200 (phase 2). detected XSS using libinjection. [file "/usr/local/coreruleset-3.3.0/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "37"] [id "941100"] [rev ""] [msg "XSS Attack Detected via libinjection"] [data "Matched Data: XSS data found within ARGS:text:
> 
> alert('XSS')"] [severity "2"] [ver "OWASP_CRS/3.3.0"]
> [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [hostname "hostname.net"] [uri "/directory/page.php"] [unique_id "1630221362"] [ref "v1106,29t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls"]

But the request is being sent straight into database and added there.

GET requests like that are momentarily blocked in browser with 403.

I tried setting

> SecDefaultAction "phase:1,log,auditlog,deny,status:403"
> 
> SecDefaultAction "phase:2,log,auditlog,deny,status:403"

But no luck there, nothing changed.

Am I being dumb or what is the problem and how can I solve it?

**Comment by Dosyk** [comment]
Another issue is that it doesn't block pages with php errors, even though php-errors.data is inside the rules directory.

**Comment by martinhsv** [comment]
Hi @Dosyk ,

The ModSecurity engine and the Core Rule Set (CRS) have separate versioning and are handled by different groups.  3.3 is the version of CRS that you have, not the version of ModSecurity.

If you are actually using v3.0.x of ModSecurity with Apache HTTP Server, be aware that that is not recommended.  The functionality is sufficiently incomplete that it is not recommended for production.

If you are actually using v2.9.x of ModSecurity with Apache HTTP Server, one thing that could be happening is that you are set to 'DetectionOnly'.  This is typically in the modsecurity.conf file:
```
SecRuleEngine DetectionOnly
```

**Comment by martinhsv** [comment]
Was there anything further on this?  If not, I'll go ahead and close the issue.
