### ISSUE TITLE
Request body truncated (Multipart: Final boundary missing) even if SecRequestBodyLimit is set to a higher limit

### ISSUE THREAD

**Issue by agjini** [SpiderLabs/ModSecurity#2611]
**Describe the bug**

We use modsecurity with nginx.

We have set the parameter `SecRequestBodyLimit` to 150 Mb.
When we try to upload a file of 23Kb, we receive a 400 bad request from mod security with the message :

"Multipart: Final boundary missing."

We expect that the file will be not truncated. We tried lots of different configuration without success.
Are we doing things wrong ? What are-we missing ?

Thanks for help

Here is our configuration (modsecurity-override.conf) :
```
SecResponseBodyLimit 1048576
```

**Logs and dumps**

1. DebugLogs :

```
Starting phase REQUEST_BODY. (SecRules 2)
Multipart: Boundary: ---------------------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Multipart: Added part header "Content-Disposition" "form-data; name="file"; filename="logo.jpg"".
Multipart: Added part header "Content-Type" "image/jpeg".
Multipart: Content-Disposition name: file.
Multipart: Content-Disposition filename: logo.jpg.
MultipartPartTmpFile: Create filename= /tmp/modsecurity/upload/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-file-XRHLon
Multipart: Failed to create file: /tmp/modsecurity/upload/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-file-XRHLon
Multipart: Final boundary missing.
Multipart: Cleanup started (keep files set to Not set)
```

 2. AuditLogs

```
"message": "Failed to parse request body.",
"details": {
	"ver": "",
	"severity": "2",
	"reference": "v1096,1",
	"ruleId": "200002",
	"tags": [
		"modsecurity"
	],
	"rev": "",
	"maturity": "0",
	"file": "/etc/modsecurity.d/modsecurity.conf",
	"lineNumber": "60",
	"data": "Multipart parsing error: Multipart: Final boundary missing.",
	"match": "Matched \"Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' )",
	"accuracy": "0"
}
```

 3. Error logs

```
ModSecurity: Access denied with code 400 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/etc/modsecurity.d/modsecurity.conf"] [line "60"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "Multipart parsing error: Multipart: Final boundary missing."] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "modsecurity"]"
```

**To Reproduce**

We upload a file with a POST query (multipart form)

```
curl -v -F 'file=@/home/agjini/Downloads/logo.jpg' "https://XXXXX/file"
> user-agent: curl/7.78.0
> accept: */*
> content-length: 23201
> content-type: multipart/form-data; boundary=------------------------df94c79c49b2f044
>
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 400
< server: nginx
< date: Wed, 01 Sep 2021 09:27:03 GMT
< content-type: text/html
< content-length: 150
<
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Expected behavior**

We expect that the file will be not truncated.

**Server (please complete the following information):**
docker image `owasp/modsecurity:3`
ModSecurity-nginx v1.0.2
ModSecurity v3.0.5 (Linux)
nginx/1.20.1
OS : Debian GNU/Linux 10 (buster) (inside docker)

**Rule Set (please complete the following information):**
Spider labs Core Rule Set v3.3.2

**Comment by agjini** [comment]
Ok. I've found the problem :-)

According to the logs mod security failed to create the file on tmp upload dir.
So i've ensured that the folder /tmp/modsecurity/upload folder exists and nginx has the permission to write into !!

And its works.
The missing boundary was a consequence not the real problem.

So i'm closing the isse

**Comment by bfamzz** [comment]
Hello @agjini,

How did you resolve the issue? 

The `/tmp/modsecurity/upload` directory exists on the docker container. How did you give nginx permission to write into it?

Thanks.

**Comment by agjini** [comment]
Hello,

I've added the following commands inside a RUN step inside my Dockerfile :

RUN mkdir -p /tmp/modsecurity/upload && mkdir -p /tmp/modsecurity/tmp && chmod -R 777 /tmp/modsecurity

-------- Message d'origine --------

**Comment by bfamzz** [comment]
Thanks for your response @agjini 

See this coreruleset/modsecurity-docker#82 for a fix from upstream.
