### ISSUE TITLE
SecRule with nolog is still logging. 

### ISSUE THREAD

**Issue by ledzepp4eva** [SpiderLabs/ModSecurity#2614]
**Describe the bug**

We have created a `SecRule` to allow a certain type of request, however despite the rule working the below is still logged into the nginx error log, this is happening in `DetectionOnly` mode, so it's hard to know the rule we have added has actually worked without setting `SecRuleEngine` to `On`, again where it logs however is not blocked.

**Logs and dumps**

```
2021/09/02 08:21:12 [info] 45611#45611: *691956 ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?:^|[\\/])\.\.(?:[\\/]|$)' against variable `ARGS:reference.refAddress1' (Value: `..' ) [file "/opt/openresty/site/modsecurity/coreruleset/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "52"] [id "930110"] [rev ""] [msg "Path Traversal Attack (/../)"] [data "Matched Data: .. found within ARGS:reference.refAddress1: .."] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [hostname "1.2.3.4"] [uri "/Applicants/Reference_Edit"] [unique_id "25764-c64035d41d54aeec7c1c707399424d62"] [ref "o0,2v236,2"], client: 1.2.3.4, server: example.com, request: "POST /Applicants/Reference_Edit?refid=925A65C4654A926053FA05568BA67265 HTTP/1.1", host: "example.com"
2021/09/02 08:21:12 [info] 45611#45611: *691956 ModSecurity: Warning. Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/opt/openresty/site/modsecurity/coreruleset/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "1.2.3.4"] [uri "/Applicants/Reference_Edit"] [unique_id "25764-c64035d41d54aeec7c1c707399424d62"] [ref ""], client: 1.2.3.4, server: example.com, request: "POST /Applicants/Reference_Edit?refid=925A65C4654A926053FA05568BA67265 HTTP/1.1", host: "example.com"
```

```
SecRule ARGS_NAMES "@contains reference.refAddress1" "id:7, phase:2, t:none, nolog, pass, ctl:ruleEngine=Off"
```

**To Reproduce**

```
curl --resolve example.com:443:1.2.3.4 https://example.com/Applicants/Reference_Edit?refid=1234 -d 'reference.refAddress1=..'
```

**Expected behavior**

I would expect for this request to be allowed, but also respect `nolog` 

**Server (please complete the following information):**
 - modsecurity-nginx-v1.0.1 / ModSecurity v3.0.4
 - nginx version: openresty/1.17.8.2
 - CentOS Linux release 7.9.2009 (Core)

**Rule Set (please complete the following information):**
 - OWASP CRS `3.3.0`

**Additional context**

**Comment by void-in** [comment]
Depends on where you have added your own rule. If the CRS is being loaded and processed before your rule, it would match before your rule and will be logged. Also, I think instead of pass, you need to use allow so stop further processing of the rules if that is what you want.

Or you need to use SecRuleUpdateTargetById
```
SecRuleUpdateTargetById 930110 !ARGS:reference.refAddress1
```

**Comment by martinhsv** [comment]
Hi @ledzepp4eva 

Just to add one extra note of clarification here, when you say:

> I would expect for this request to be allowed, but also respect nolog

The nolog action means 'do not perform the logging for the current rule'.  It does _not_ mean 'perform no logging for this transaction'.

The log excerpt that you have included is consistent with this.  Rules 930110 and 949110 have been logged but rule 7 (which has the nolog action) has not been.

**Comment by martinhsv** [comment]
Was there anything more on this?  If not, I will proceed to close this issue.

**Comment by ledzepp4eva** [comment]
Apologies. Feel free to close it and thank you all for the feedback.
