### ISSUE TITLE
src read help 

### ISSUE THREAD

**Issue by ffashion** [SpiderLabs/ModSecurity#2624]
Can you tell me the function of the AnchoredSetvariable:: set offset parameter and the function of the VariableOrigin class

**Comment by martinhsv** [comment]
Hello @ffashion ,

Unfortunately that's not really the sort of question that I can allocate any time to. (This is particularly true for code that I either did not originate myself. )  I had left this issue open in case anyone else in the community chose to respond, but I will proceed to close it.

However, to answer a portion of your question: offset is used to identify a location within a larger string. For example in a application/x-www-form-urlencoded body, it will identify parm2 as having an offset of 8 within parm1=1&parm2=2
