### ISSUE TITLE
Apache stop's to accept requests abruptly after install mod-sec and mlogc

### ISSUE THREAD

**Issue by felipediefenbach** [SpiderLabs/ModSecurity#2626]
**Describe the bug**

Apache abruptly stops accepting requests

**Logs and dumps**

mlogc[22171]: segfault at 7f479571b9b0 ip 00007f47952dcc26 sp 00007f478e8eddb0 error 4
mlogc[22748]: segfault at 7f5f2d0009b0 ip 00007f5f2cbc1c26 sp 00007f5f261d2db0 error 4

mlogc[24451]: segfault at 7f6b762be04c ip 00007f6b75e9a870 sp 00007ffeb127e770 error 6 in libapr-1.so.0.6.3[7f6b75e81000+33000]

--  unit apache2.service
set 27 13:54:51 rs4304705asp001 systemd[1]: apache2.service: State 'stop-sigterm' timed out. Killing.
set 27 13:54:51 rs4304705asp001 systemd[1]: apache2.service: Killing process 13438 (mlogc) with signal SIGKILL.
set 27 13:54:51 rs4304705asp001 systemd[1]: apache2.service: Failed with result 'timeout'.
set 27 13:54:51 rs4304705asp001 systemd[1]: Stopped The Apache HTTP Server.
-- Subject: unit apache2.service 
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs
 3. Error logs
 
 [qui set 30 06:21:01 2021] mlogc[9369]: segfault at 7fc9af7029a8 ip 00007fc9af2c3c26 sp 00007fc9a88d4db0 error 4 in libapr-1.so.0.6.3[7fc9af2aa000+33000]
read(0, "", 65536)                      = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7efda7a5a04c} ---
+++ killed by SIGSEGV (core dumped) +++

 4. If there is a crash, the core dump file.

Still work on it

**Expected behavior**

Apache does not stop accepting requests

**Server (please complete the following information):**
ModSecurity Log Collector (mlogc) v2.9.2
   APR: compiled="1.6.2"; loaded="1.6.3"
  PCRE: compiled="8.39"; loaded="8.44 2020-02-12"
  cURL: compiled="7.55.1"; loaded="libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.3.0 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3"

apache2  2.4.29-1ubuntu4.18 amd64 Apache HTTP Server

php5.6 5.6.40-53+ubuntu18.04.1+deb.sury.org+1
php5.6-fpm 5.6.40-53+ubuntu18.04.1+deb.sury.org+1

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set?
 Public, no rules, just collecting log

 - What is the version number? 
 - modsecurity-crs  3.0.2-1 OWASP ModSecurity Core Rule Set

**Additional context**

The problem occours after somtime of the apache running normal, the segfault occurs in the syslog at the dmesg command,
this a virtual machine in openstack environment running ubuntu

**Comment by martinhsv** [comment]
Hi @conexaoinfraestrutura ,

I had noted your comment:
```
If there is a crash, the core dump file.
Still work on it
```

Since there has been no update since you posted this issue, I thought I'd inquire if you had made any progress on this.

I will note that, since you are using ModSecurity v2.9.2, you might get relief from whatever issue you are experiencing by upgrading your version.  Whatever caused your crash may well have been fixed in the four years since v2.9.2.

If this problem still occurs with an upgrade to ModSecurity v2.9.4, it's likely that either a reproducible test case or a stack trace of the crash would be required to investigate this properly.

**Comment by martinhsv** [comment]
Closing due to lack of response.
