### ISSUE TITLE
Rules (Location Match)

### ISSUE THREAD

**Issue by ramil1973** [SpiderLabs/ModSecurity#2629]
Hi i have problem with whitelist 

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs-3.0.0/rules/whitelist.conf. Line: 3. Column: 48. Invalid input:  <LocationMatch "/epg/rest/finish3dsPayment.do"> in /etc/nginx/conf.d/default.conf:44

**Comment by martinhsv** [comment]
Hello @ramil1973 ,

I noticed that your ruleset version is quite old -- you might benefit from simply updating that.

In any case, questions about CRS (coreruleset) are best addressed to the group that manages it: https://github.com/coreruleset/coreruleset
