### ISSUE TITLE
Does modsecurity 2.9.0 support Transfer-Encoding: Chunked?

### ISSUE THREAD

**Issue by DeveloperInMe** [SpiderLabs/ModSecurity#2631]
modsecurity version: 2.9.0
Apache 2.4.6/centos

I have a request coming from mobile using encoding chunked which modsec is not able to read at all. So can you advise if 2.9.0 version supports chunked encoding or not? If not then from which version will get that or is there any workaround involved for processing the request.

**Comment by martinhsv** [comment]
Hi @DeveloperInMe ,

I just tried this with ModSecurity 2.9.0 and I did not encounter any problems.

One thing you could check is that your request is not incorrectly sending both a Content-Length header and a Transfer-Encoding header.

You could also try submitting a simplified version of the request with curl:
```
curl -H "Transfer-Encoding: Chunked" -d "your_post_args" http://localhost/whateverurl.php
```

**Comment by marcstern** [comment]
It doesn't work with SecStreamInBodyInspection - see https://github.com/SpiderLabs/ModSecurity/issues/2628

**Comment by martinhsv** [comment]
With no further activity on this, I'll go ahead and close it.
