### ISSUE TITLE
Question: Isn't PUT default HTTP Method?

### ISSUE THREAD

**Issue by vitordatasafer** [SpiderLabs/ModSecurity#2632]
Why isn't PUT a default HTTP Method that a client is allowed to use?

**Comment by martinhsv** [comment]
Hello @vitordatasafer ,

What exactly do you mean by "allowed to use"?  What is constraining you from using that?  E.g. what actual error message(s) are you encountering (if that is what is happening)?

**Comment by martinhsv** [comment]
I did also just do a quick re-test of this and confirmed that ModSecurity processes PUT requests just fine.

With no further information from the poster, I'll go ahead and close this ...
