### ISSUE TITLE
How to add `community_id` with NTA or NIDS flow 

### ISSUE THREAD

**Issue by xx-zhang** [SpiderLabs/ModSecurity#2641]
**Describe the bug**

**Logs and dumps**

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs
 3. Error logs
 4. If there is a crash, the core dump file.

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

A **curl** command line that mimics the original request and reproduces the problem. Or a ModSecurity v3 test case.

[e.g: curl "modsec-full/ca/..\\..\\..\\..\\..\\..\\/\\etc/\\passwd" or [issue-394.json](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/test/test-cases/regression/issue-394.json)]

**Expected behavior**

**Server (please complete the following information):**
 - ModSecurity version (and connector): [e.g. ModSecurity v3.0.1 with nginx-connector v1.0.0]
 - WebServer: [e.g. nginx-1.15.5]
 - OS (and distro): [e.g. Linux, archlinux]

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? [e.g. SpiderLabs commercial rules]
 - What is the version number? [e.g. 2018-08-11]

**Additional context**

**Comment by martinhsv** [comment]
Hello @xx-zhang ,

There really isn't any information here with which to do anything.  The body of your posting appears to just be the template with nothing filled in with your information.  The title alone is insufficient to understand what issue or question you have.

Please supply additional information.

**Comment by martinhsv** [comment]
No response from poster.  Closing ...
