### ISSUE TITLE
GPG key F2FC4E45883BCBA4 for modsecurity 3.0.6 could not be found on public keyservers

### ISSUE THREAD

**Issue by mtorromeo** [SpiderLabs/ModSecurity#2646]
modsecurity-3.0.6 was recently released, but the source tarball appears to be signed by a different gpg key that I cannot verify.

Where am I supposed to find it?

Thanks

**Comment by martinhsv** [comment]
Hi @mtorromeo ,

Apologies if there are difficulties with this aspect -- this is my first time going through this particular process.

My understanding was that github keys could be retrieved from:
curl https://github.com/martinhsv.gpg

**Comment by mtorromeo** [comment]
I wasn't aware of that, thanks!
I would still suggest sending the key to a public key server like keyserver.ubuntu.com to make it easier to retrieve it.
