### ISSUE TITLE
/lib/libstdc++.so: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by InputOutputZ** [SpiderLabs/ModSecurity#2650]
**Describe the bug**

Make fails once it reaches compiling examples and test directory and throws " `/usr/local/lib/../lib/libstdc++.so: error adding symbols: File in wrong format ", while when I run configure with --disable-example, it throws the same error yet with benchmarking testing.

I run centos 7.

This bug report it's for both version 3 and 2.

Output of:

Examples error

```
/usr/local/lib/../lib/libstdc++.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [simple_request] Error 1
make[2]: Leaving directory `/user/ModSecurity/examples/using_bodies_in_chunks'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/user/ModSecurity/examples'
make: *** [all-recursive] Error 1
```

Testing benchmark error

```
make[2]: Entering directory `/user/ModSecurity/test/benchmark'
g++ -DHAVE_CONFIG_H -I. -I../../src  -std=c++11 -I../../headers  -DPCRE_HAVE_JIT  -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT benchmark-benchmark.o -MD -MP -MF .deps/benchmark-benchmark.Tpo -c -o benchmark-benchmark.o `test -f 'benchmark.cc' || echo './'`benchmark.cc
mv -f .deps/benchmark-benchmark.Tpo .deps/benchmark-benchmark.Po
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -g -O2 -L../../src/.libs/  -lmodsecurity -lpthread -lm -lstdc++  -L/usr/local/lib/   -L/usr/local/lib/ -L/usr/local/lib64/  -o benchmark benchmark-benchmark.o -lcurl   -lGeoIP   -lmaxminddb -lpcre -lpcre -lyajl   -llmdb   -lfuzzy -llua -lxml2 -lz -lm -ldl -lrt   
libtool: link: g++ -g -O2 -o .libs/benchmark benchmark-benchmark.o  -L../../src/.libs/ /user/ModSecurity/src/.libs/libmodsecurity.so -L/usr/local/lib64/ -L/usr/local/lib/ -L/usr/local/lib /usr/local/lib/../lib64/libstdc++.so -lpthread /usr/local/lib/../lib/libstdc++.so -lcurl -lGeoIP /usr/local/lib/libmaxminddb.so -lpcre -lyajl -llmdb /usr/local/lib/libfuzzy.so -llua -lxml2 -lz -lm -ldl -lrt -Wl,-rpath -Wl,/usr/local/modsecurity/lib -Wl,-rpath -Wl,/usr/local/lib/../lib64 -Wl,-rpath -Wl,/usr/local/lib/../lib -Wl,-rpath -Wl,/usr/local/lib
/usr/local/lib/../lib/libstdc++.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [benchmark] Error 1
```

**To Reproduce**

git clone v3.0.6 or v3.0.4, v2.9.5, to test difference cases described below.

```
yum install gcc-c++ flex bison yajl yajl-devel curl-devel curl GeoIP-devel doxygen zlib-devel pcre-devel
sh build.sh
git submodule init
git submodule update
./configure --with-lua=/luadirectory/lua-5.3.0/src --enable-parser-generation --enable-mutex-on-pm
yum install https://archives.fedoraproject.org/pub/archive/fedora/linux/updates/23/x86_64/b/bison-3.0.4-3.fc23.x86_64.rpm
yum install https://archives.fedoraproject.org/pub/archive/fedora/linux/updates/23/x86_64/b/bison-devel-3.0.4-3.fc23.x86_64.rpm
make

```

**Expected behavior**

Successful make.

**Additional context**

I noticed this problem is not present with the same configuration options params passed to configure, whilst being tailored to meet configure options difference with v2.9.5, referencing apr, apu and apxs as well as lua accordingly.  Also, its not present in v3.0.4 but only 3.0.5 and 3.0.6.

I have several gcc compilers installed, including, 4.8.5, 7, 8, and 12. I ssh-ed in server from unprivileged user and switched to root which messes up the bash_profile and I've to run source ~/.bash_profile to get the libraries and binaries working normally except with gcc compiler and I found its being set default to 4.8.5 OS prebuilt one unlike if I log in from root and if it was due to this mess up I struggled to understand why 2.9.5 and 3.0.4 working fine whilst logged and switched in same manner and ran same commands.

Note, I was able to fix the problem when I ran following commands, and the last line was due to another error thrown, requesting 64 bit shared file for libstdc++ in 32 bit meant to be directory in /usr/lib, which is what I've concluded from my understanding given /usr/lib64 clearly its for 64 bit, and when I copied, /usr/local/lib64/libstdc++.so.6 to /usr/lib/libstdc++.so.6, I was able to successfully compile the latest ModSecurity. I take it the recent significant commits, expecting for benchmarking and testing to succeed in make, only with a libstdcstd++ 64 bit shared file. If my conclusion is not correct, any information as well as any better way to mitigate this issue would be very much appreciated.

```
scl enable devtoolset-8 -- bash
cp /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.so /usr/local/lib64/libstdc++.so.8
cp /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/32/libstdc++.so /usr/local/lib/libstdc++.so.8
rm /usr/local/lib/libstdc++.so
rm /usr/local/lib64/libstdc++.so
ln -s /usr/local/lib64/libstdc++.so.8 /usr/local/lib64/libstdc++.so
ln -s /usr/local/lib/libstdc++.so.8 /usr/local/lib/libstdc++.so
cp /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.so /usr/lib64/libstdc++.so.8
# Ran this command to in response to another error thrown from make call referenced above.
cp /usr/local/lib64/libstdc++.so.6 /usr/lib/libstdc++.so.6
ldconfig
```

With thanks.

**Comment by martinhsv** [comment]
Hello @InputOutputZ ,

That does not happen for me when building ModSecurity v3.0.6 on CentOS 7.

What happens if you just use "./configure" , i.e. with none of the three options that you used in your pasted steps?

(Incidentally, why are you separately installing bison packages from fedoraproject.org? Was the yum install of bison from the first line of your steps insufficient?)

**Comment by InputOutputZ** [comment]
> Hello @InputOutputZ ,
> 
> That does not happen for me when building ModSecurity v3.0.6 on CentOS 7.
> 
> What happens if you just use "./configure" , i.e. with none of the three options that you used in your pasted steps?
> 
Same result?
> (Incidentally, why are you separately installing bison packages from fedoraproject.org? Was the yum install of bison from the first line of your steps insufficient?)

I followed recommended instructions here https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x ?

**Comment by martinhsv** [comment]
Regarding the extra download in that published compilation recipe:

Most people building ModSecurity actually don't need bison at all -- you really only need it if you have made changes to the code within src/parser and need to regenerate the bison-generated code. But, if doing so you do need a bison version of at least v3.0.2. My guess is that that extra install from fedoraproject.org (in the recipe that you've linked to) was there because the default available in CentOS 7 at the time was less than that version. That should not be an issue now as the bison version available via plain yum install meets that requirement. In any case, there's no particularly strong reason to think that that is the source of your problem.

I did a fresh build this morning on a fresh VM and again did not encounter the problem you report.

I can only speculate that some of the complexity you mentioned in 'Additional context' is causing the problem. The best I can suggest is to start with a fresh CentOS 7 VM and go from there with plain instructions.

**Comment by InputOutputZ** [comment]
> Regarding the extra download in that published compilation recipe:
> 
> Most people building ModSecurity actually don't need bison at all -- you really only need it if you have made changes to the code within src/parser and need to regenerate the bison-generated code. But, if doing so you do need a bison version of at least v3.0.2. My guess is that that extra install from fedoraproject.org (in the recipe that you've linked to) was there because the default available in CentOS 7 at the time was less than that version. That should not be an issue now as the bison version available via plain yum install meets that requirement. In any case, there's no particularly strong reason to think that that is the source of your problem.
> 
> I did a fresh build this morning on a fresh VM and again did not encounter the problem you report.
> 
> I can only speculate that some of the complexity you mentioned in 'Additional context' is causing the problem. The best I can suggest is to start with a fresh CentOS 7 VM and go from there with plain instructions.

Thanks for your clarification. I expected it to work if I attempt configuring from a fresh installation yet I had to keep current setup and therefore above symlinking resolved the issue for me yet you can close this issue, with thanks.

Zakaria.
