### ISSUE TITLE
[Feature Request] Connector for Caddy

### ISSUE THREAD

**Issue by hypervtechnics** [SpiderLabs/ModSecurity#2653]
Will there be a connector for the Caddy web server? https://caddyserver.com

**Comment by jptosso** [comment]
Hey @hypervtechnics [Coraza](https://github.com/jptosso/coraza-waf) fully supports Caddy and OWASP Core ruleset, you can see the connector here: [Coraza Caddy Connector](https://github.com/jptosso/coraza-caddy) There is also a working docker image: jptosso/coraza-caddy

**Comment by hypervtechnics** [comment]
This looks great! Thank you very much :)
