### ISSUE TITLE
Reproduce this rule from ModSecurity 2 on ModSecurity 3 (brute force login)

### ISSUE THREAD

**Issue by EvannG1** [SpiderLabs/ModSecurity#2654]
I'm trying to set up a rule to prevent bruteforce on a login page.
I found this [article](https://www.loadbalancer.org/blog/brute-force-login-modsecurity-waf/), but it is based on ModSecurity 2 and Apache.

Here is what I use :
ModSecurity v3.0.5
Nginx v1.20.1
ModSecurity-nginx v1.0.2

I adapted the "Location" part of the article using [modsecurity_rules](https://github.com/SpiderLabs/ModSecurity-nginx/blob/master/README.md#modsecurity_rules).
But there is still a problem with the "deprecatevar" directive which is not implemented in ModSecurity 3 yet :
`nginx: [emerg] "modsecurity_rules" directive Rules error. DeprecateVar is not yet supported.  in /etc/nginx/conf.d/backend.conf:44`

Do you have a suggestion for me to adapt this rule for ModSecurity 3 ?

**Comment by martinhsv** [comment]
Hi @EvannG1 ,

It seems your question is fundamentally a duplicate of https://github.com/SpiderLabs/ModSecurity/issues/1944 . I will close this item on that basis

I have recently made a comment in that other issue about a possible workaround for the lack of deprecatevar in v3. Have a look and see if that might be helpful to you.
