### ISSUE TITLE
periodically updates of OWASP Core Rule Set (CRS) / cron?

### ISSUE THREAD

**Issue by un99known99** [SpiderLabs/ModSecurity#2655]
I have downloaded latest OWASP CRS from GitHub (wget https://github.com/coreruleset/coreruleset/archive/v3.3.0.tar.gz).
What kind of possibilities are available to keep the rules up-to-date?
Where to check if a new version is available **OR** download automated via cron periodically updates?
Thanks in advance.

**Comment by airween** [comment]
@un99known99, I think this is more CRS (or even more an operating system) question.

If you use any (supported) Debian or any (supported LTS) Ubuntu system, you can use this repository:
https://modsecurity.digitalwave.hu

I maintain this repository, and CRS is part of it.

If you run any different system, you can check how does it work on Debian/Ubuntu, and see the [watch](https://salsa.debian.org/modsecurity-packaging-team/modsecurity-crs/-/blob/master/debian/watch) file. Note, this file is used by [uscan](https://salsa.debian.org/debian/devscripts/-/blob/master/scripts/uscan.pl), which is part of Debian's [devscripts](https://packages.debian.org/bullseye/devscripts) package.

**Comment by un99known99** [comment]
Hi, thanks for the quick answer.
I saw the possiblility to update (sudo python /etc/apache2/owasp-modsecurity-crs/util/upgrade.py --crs) but seems not to work: sudo /usr/share/modsecurity-crs/util/upgrade.py --crs => **_crs: Not a git repository: /usr/share/modsecurity-crs_**. I do have /etc/apache2/modsecurity-crs/coreruleset-3.3.0 installed ....?

**Comment by un99known99** [comment]
answered in google groups
