### ISSUE TITLE
How to get realtime updates regarding the attacks via webhooks in mod security

### ISSUE THREAD

**Issue by anasabdullahysfzai** [SpiderLabs/ModSecurity#2659]
I am working on a web based antivirus solution where i need to get the updates regarding the attacks in my application (PHP App in Cpanel) via webhooks , i wanna know if there is anyway to achieve this
thanks

**Comment by martinhsv** [comment]
Hello @anasabdullahysfzai ,

ModSecurity's support for remote logging varies depending on whether you are using v2 or v3. In v2, the most obvious way to do this is with mlogc. In v3, while one can still set something up with mlogc, likely the simplest way is with 'SecAuditLogType HTTPS' (see https://github.com/SpiderLabs/ModSecurity/issues/1770#issuecomment-388986535)
