### ISSUE TITLE
ModSecurity-nginx with "@contains %" cause directive Rules error

### ISSUE THREAD

**Issue by jwillberg** [SpiderLabs/ModSecurity#2662]
Above rule cause that nginx wont start:

`SecRule REQUEST_HEADERS "@contains %" "id:426003,phase:2,t:none,deny,log,msg:'DEBUG Referer: attack'"
`

Also if change to:

`SecRule REQUEST_HEADERS "@rx \%" "id:426003,phase:2,t:none,deny,log,msg:'DEBUG Referer: attack'"
`

Nginx complains:

`modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/modsecurity.conf. Line: 280. Column: 161. Expecting an action, got:  DEBUG Referer: attack'" in /etc/nginx/nginx.conf:17`

If change this to this:

`SecRule REQUEST_HEADERS '@rx \%' "id:426003,phase:2,t:none,deny,log,msg:'DEBUG Referer: attack'"
`
or
`SecRule REQUEST_HEADERS '@contains %' "id:426003,phase:2,t:none,deny,log,msg:'DEBUG Referer: attack'"
`

nginx will start but rule wont triggering:

**Example:**
`curl -v -XGET --header "X-Forwarded-For: %1.1.1.1" "http://localhost"`

**Server:**
 - ModSecurity v3.0.6 with nginx-connector v1.0.2
 - nginx-1.21.4
 - Linux, Debian 11

Apache with ModSecurity this same rule working as it should.

**Comment by martinhsv** [comment]
Hello @jwillberg ,

What you are seeing is https://github.com/SpiderLabs/ModSecurity/issues/2145.

There are a couple of alternative ways to specify your rule that do work. See https://github.com/SpiderLabs/ModSecurity/issues/2145#issuecomment-917608017
