### ISSUE TITLE
[msg ""] empty field after update to ModSecurity 3.0.6 in AuditLogs

### ISSUE THREAD

**Issue by xlabssecurity** [SpiderLabs/ModSecurity#2664]
After upgrading to ModSecurity 3.0.6 the [msg ""] field in the logs for some rules appears empty.

One rule causing this behavior is "942100" from OWASP_CRS/3.2.0 in the REQUEST-942-APPLICATION-ATTACK-SQLI.conf file
there is also the behavior in other rules, however, we identified this as the example.

**Logs and dumps**

Output of:
 1. DebugLogs (level 9)
In debug mode 9 the MSG referring to the rule name appears

 2. AuditLogs
```
ModSecurity: Warning. detected SQLi using libinjection. [file "/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "71"] [id "942100"] [rev ""] [msg ""] [data ""] [severity "0"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [hostname "xxxxxxxx"] [uri "/"] [unique_id "1640795023"] [ref "v891,54"]
ModSecurity: Warning. detected SQLi using libinjection. [file "/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "71"] [id "942100"] [rev ""] [msg ""] [data ""] [severity "0"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [hostname "xxxxxxxx"] [uri "/"] [unique_id "1640795023"] [ref "v891,54v826,54"]
```

**To Reproduce**

a simple curl to reproduce:
curl "https://target/?id=this%27is%27OR%27'2'='2'--injection"

**Expected behavior**

```
ModSecurity: Warning. detected SQLi using libinjection. [file "/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "71"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: sosc found within ARGS:id: this'is'OR''2'='2'--injection"] [severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [hostname "xxxxxxxx"] [uri "/"] [unique_id "164079719414.670894"] [ref "v9,29"]
```
Observe the value in [msg "SQL Injection Attack Detected via libinjection"]

**Server:**
 - ModSecurity 3.0.6  (connector): nginx-connector v1.0.2 OR nginx-connector v1.0.1
 - WebServer: nginx-1.16.1
 - OS : Linux, CentOS 7

**Rule Set (please complete the following information):**
OWASP_CRS/3.2.0

**Additional information**

When returning to the use of ModSecurity 3.0.4 the logs apparently returned to displaying contents internally in the field [msg ""] normally

**Comment by martinhsv** [comment]
Hello @xlabssecurity ,

It sounds like what you have seen is this already-reported issue:  https://github.com/SpiderLabs/ModSecurity/issues/2573

**Comment by xlabssecurity** [comment]
Hi @martinhsv,
Thanks for the quick response, I followed the issue #2573 , but it was said that it would be able to reproduce the behavior in version 3.0.4, here it was precisely version 3.0.4 that returned to work correctly. I don't know if this information would be important.

**Comment by martinhsv** [comment]
Hi @xlabssecurity ,

Good catch. It looks like that portion of what I wrote back then (' ... both v3.0.4 and ...') was incorrect.

The problem is not reproducible in v3.0.4 and was only introduced afterwards. I have updated the comment in that issue.

In any case, I think it's safe to say that what you have raised here is a duplicate of that other issue, so I will go ahead and close this.
