### ISSUE TITLE
Add support for PCRE2

### ISSUE THREAD

**Issue by martinhsv** [SpiderLabs/ModSecurity#2668]
The legacy PCRE implementation (more recently referred to as PCRE1) is no longer being updated, with v8.45 (from June 2021) expected to be the final version.

Also, nginx has recently (nginx/1.21.5) changed to use PCRE2 by default, and this will cause problems if not using the --without-pcre2 flag when building (see https://github.com/SpiderLabs/ModSecurity-nginx/pull/260, https://github.com/SpiderLabs/ModSecurity-nginx/pull/261 ).

**Comment by airween** [comment]
Is there any plan to replace? Perhaps some milestone?

**Comment by defanator** [comment]
Thanks @martinhsv for bringing this one. From my pov, thorough testing for any memory leaks either in library or in connector should be the part of the effort. Existing hacks for PCRE1 are known to work, but I don't have any knowledge of how PCRE2 is handling memory allocations in comparison to older one.
