### ISSUE TITLE
Help needed to handle performance issue v3.x

### ISSUE THREAD

**Issue by Fillonj** [SpiderLabs/ModSecurity#2669]
Hello, im setting up Modsecurity for my WebApp in a Kubernetes cluster using the docker image owasp/modsecurity-crs:3.3.2-nginx.
Im not done handling false positives actually, i work on rules for that and im facing some performance issues on some endpoints.

I have an Api working with json payloads, some endpoints can process singles complexe objects and some endpoints can process list of complex objects.
In some case the json payload may have more than 8k-10k args.
I've made a rules to check the numbers of args :
SecRule &ARGS "@ge 2000" "id:110100,phase:2,pass,t:none,log,auditlog,msg:'Le flux contient beaucoup de parametres (2000+)',severity:'CRITICAL'"

The fact is that a request that take 200ms when the engine is off, can take up to 10s when the engine is on.
I have tried to use the directive SecArgumentsLimit but the request cannot be processed because the payload seems to be broken

Is there a way to tell the engine to stop processing rules when an amount a time has allready been used ? it's not perfect because the whole crs rules may not have been checked. I could accept that a request normally processed in 200ms can take up to 600ms/800ms or even 1s in the worst case, but not 10s like actually.

What would be the best (or the less worst) solution to resolve that case and keeping a certain security level with acceptable performance ?

Thx for your help

**My configuration is**
SecRuleEngine On
SecRequestBodyAccess On

SecRequestBodyLimit 13107200  
SecRequestBodyNoFilesLimit 131072 #not working with v3.x
SecRequestBodyLimitAction ProcessPartial
#SecArgumentsLimit 2000

SecPcreMatchLimit 1000
SecPcreMatchLimitRecursion 1000
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml application/json
SecResponseBodyLimit 131072
SecResponseBodyLimitAction ProcessPartial
SecTmpDir /tmp/
SecDataDir /tmp/

SecArgumentSeparator &
SecCookieFormat 0
SecUnicodeMapFile unicode.mapping 20127
SecStatusEngine On

# Logging
SecAuditEngine RelevantOnly
SecAuditLogType HTTPS
SecAuditLogFormat JSON
SecAuditLog elk_url
SecAuditLogRelevantStatus "^(?:5(?!02)|4(?!04))"
SecAuditLogParts ABCHIJKZ

**Comment by martinhsv** [comment]
Hello @Fillonj ,

There is an inherent challenge with a very large number of arguments run against a substantial set of rules that test them. There doesn't need to be a major issue with any particular rule -- the mere volume of this M x N use case can degrade performance. This is exactly the sort of situation that motivated the creation of SecArgumentsLimit.

In your case, with a very large number of json args being legitimate, that particular configuration item is, of course, less helpful.

There is no control within ModSecurity to stop running rules after a given amount of dwell time.

Your strategy of reducing the rule execution when these very-numerous-args situations are encountered is probably reasonable.

You could explore implementing a rule that tests for this situation and then does something like remove lower-priority rules in its actions. For example, using ctl:ruleRemoveById.

Some additional things to keep in mind:
1) if you are running that sort of rule in phase:2, you'll want to make sure that it runs before the phase:2 rules that you wish to remove or modify
2) some rules impacting performance may run against numerous targets. In such cases you might want to leave the rule still running but only against the non-problem targets (e.g. REQUEST_HEADERS) and use ctl:ruleRemoveTargetById instead to accomplish this.
3) some rules might examine ARGS and/or ARGS_NAMES. If you use the previous item to remove targets from a rule, be aware that the rule in question will also no longer examine query args. If you care, you could probably address this use case by first having a global SecRuleUpdateTargetById to explicitly add ARGS_GET and/or ARGS_GET_NAMES and then remove ARGS and/or ARGS_NAMES with the ctl: action.

Just some initial thoughts. I hope they are of some assistance.

**Comment by Fillonj** [comment]
Hello @martinhsv,

I've just made a rule for this situation, my rule is very imperfect, but it help a bit before dealing with the final rule.

```
SecRule REQUEST_URI "@pm /api/" "id:1,phase:1,t:none,pass,nolog,chain,ctl:requestBodyAccess=Off"
SecRule REQUEST_HEADERS:Content-Type "(?i)application/json" "t:none,chain"
SecRule REQUEST_HEADERS:Content-Length "@ge 131072" "t:none"
```

>     1. if you are running that sort of rule in phase:2, you'll want to make sure that it runs before the phase:2 rules that you wish to remove or modify

Initially i was thinking that working in phase 2 was too late for my case

>     2. some rules impacting performance may run against numerous targets. In such cases you might want to leave the rule still running but only against the non-problem targets (e.g. REQUEST_HEADERS) and use ctl:ruleRemoveTargetById instead to accomplish this.

=> im going to explore that way. I must now identify what rules are expensive or not.

Thank you, this helps me a lot

**Comment by martinhsv** [comment]
Hi @Fillonj ,

Something like that set of rules is another option. Just be aware that in ModSecurity v3, ctl:requestBodyAccess=Off currently behaves in a non-intuitive manner. Specifically, it will turn off processing of all phase:2 rules. One consequence of this is that phase:2 rules that examine ARGS will stop running against both arguments populated from the body **and** query args.
