### ISSUE TITLE
Feature proposal: Compile to wasm library to use it in wasm application

### ISSUE THREAD

**Issue by leyao-daily** [SpiderLabs/ModSecurity#2671]
I wish there could be a official version of ModSecurity which can be compiled into WASM library and then it can be linked into wasm application and take the advantages of the WebAssembly.

To compile the ModSecurity to WASM Library using Emscripten, we should remove some unsupport system call (eg, ipc) in WebAssembly. So I am wondering if there can be a official version for users to compile to WASM Library instead of my simple demo version.

**Comment by martinhsv** [comment]
Hello @leyao-daily ,

It sounds like this is essentially a duplicate of #2590 .

**Comment by leyao-daily** [comment]
@martinhsv  Yes. And for #2590 I have compiled the ModSecurity to WASM library with removing some functions from source code. So I am wondering if there is any chance to make it a official version/upstream?

**Comment by martinhsv** [comment]
With the confirmation that this is a duplicate, I'll go ahead and close this. Relevant postings can be added to that older WASM issue.
