### ISSUE TITLE
Email address of your security team.

### ISSUE THREAD

**Issue by u21h2** [SpiderLabs/ModSecurity#2674]
**Security Team Email**

Hi, I'd like to report some flaws in JSON parsing. I would be appreciated if you could provide the email address of your sec team.
Thanks a lot.

**Comment by airween** [comment]
@u21h2

well, have you checked the [README](https://github.com/SpiderLabs/ModSecurity#security-issue) page?

**Comment by u21h2** [comment]
@airween I am so sorry.
