### ISSUE TITLE
Load Data File Event/Callback/Function

### ISSUE THREAD

**Issue by HadiAbbasi** [SpiderLabs/ModSecurity#2679]
Hello

I'm looking for an event/callback for the while that a rule content needs to load a data file! so modsec framework is trying to load it!
the input argument is data file/key name and the output (return) value is the data file content!
so I can override or use it to load the data from another way like a database or redis or ... (instead of loading from data file)
is it possible? is there any event/callback to change the way of load the data content?

**Comment by HadiAbbasi** [comment]
I'm wondering how can modsec (RulesSet) component knows the directory of rules related data files when we call RulesSet->load (with rule data plain text) instead of calling RulesSet->loadFromUri?
I mean, [this ](https://github.com/SpiderLabs/ModSecurity/issues/2676)option can be essential for our purposes!

**Comment by martinhsv** [comment]
Hello @HadiAbbasi ,

I'm not at all clear on what, overall, you are trying to do.

Since you've linked that other issue, you can review there how the pmFromFile operator can use a remote source.

For local files, the pmFromFile operator most often is used to reference a data file in the same directory as the rule that references it. You can, however, also opt to make the path absolute by using a '/'. E.g.
```
SecRule ARGS:whateverarg "@pmFromFile /tmp/myfile.txt" "id:3092,phase:2,log,deny,status:403"
```

**Comment by HadiAbbasi** [comment]
> Hello @HadiAbbasi ,
> 
> I'm not at all clear on what, overall, you are trying to do.
> 
> Since you've linked that other issue, you can review there how the pmFromFile operator can use a remote source.
> 
> For local files, the pmFromFile operator most often is used to reference a data file in the same directory as the rule that references it. You can, however, also opt to make the path absolute by using a '/'. E.g.
> 
> ```
> SecRule ARGS:whateverarg "@pmFromFile /tmp/myfile.txt" "id:3092,phase:2,log,deny,status:403"
> ```

Thanks a lot @martinhsv...

yes! total path can solve my problem!

in other words All I wanna say is:

There are other pm data types that we can cover them all!

`like pmFromRedis , pmFromDB , pmFromURL!
`
so for the while that your rule.conf + data.data are in redis and you could load rule.conf content using:

`ruleset->load(rule_plain_content_from_redis);
`
it's better to be able to load data.data from redis too!

so for example, pmFromRedis can access the data using: Redis_IP:Port,DB_NO,Redis_Key

it's the cause of linking my post to yours!

All the Best,
Hadi
