### ISSUE TITLE
... rules

### ISSUE THREAD

**Issue by k4n5ha0** [SpiderLabs/ModSecurity#2687]
.

**Comment by martinhsv** [comment]
Hello @k4n5ha0 ,

When reporting an issue that might enable a malicious party to carry out an attack by bypassing existing protections, it's almost always preferable to report it (at least initially) using a less public communication channel. I have blanked out the content that you posted here for that reason.

If you'd like to send a report to the email address listed here:
https://github.com/SpiderLabs/ModSecurity#security-issue

... I can respond to you that way.

Thanks.
