### ISSUE TITLE
modsecurity version 3.0.6 does not log correctly for the rules with ID 942100, 921180 and 1010

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2689]
when these three rules (942100, 921180, 1010) are fired, no correct info is registered. for example they have no message.

 - ModSecurity version (and connector): [ModSecurity v3.0.6 with nginx-connector (2497e6ac654d0b117b9534aa735b757c6b11c84f)]
 - WebServer: [nginx-1.20.2]
 - OS (and distro): [ Linux, ubuntu 18.04.5]

**Comment by martinhsv** [comment]
Hi @ssh81 ,

This sounds like a duplicate of https://github.com/SpiderLabs/ModSecurity/issues/2573 , which has been fixed in v3/master. I'm pretty certain of that in particular for 942100.
