### ISSUE TITLE
XML format detection problem.

### ISSUE THREAD

**Issue by whale-baby** [SpiderLabs/ModSecurity#2690]
How can I check class="java.beans.XMLDecoder" data in XML?

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header>
    <work:WorkContext xmlns:work="http://bea.com/2004/06/soap/workarea/">
      <java>
        <java version="1.4.0" class="java.beans.XMLDecoder">
          <object class="java.io.PrintWriter"> 
            <string>servers/AdminServer/tmp/_WL_internal/wls-wsat/54p17w/war/test.logs</string>
            <void method="println">
              <string>yes</string>
            </void>
            <void method="close"/>
          </object>
        </java>
      </java>
    </work:WorkContext>
  </soapenv:Header>
  <soapenv:Body/>
</soapenv:Envelope>`

**Comment by martinhsv** [comment]
What version of ModSecurity are you using?
Are you experiencing a specific problem/issue? Or are you unsure how to use XPath expressions?

For, the last of those questions, I just used the following in v2.9.x:
```
SecRule XML://java/@class "@streq java.beans.XMLDecoder" ...
```

(The above example assumes that you don't care about specifying all of the parents.)

**Comment by martinhsv** [comment]
With nothing further on this, I'll go ahead and close ...
