### ISSUE TITLE
feature request: multiMatch exit if match

### ISSUE THREAD

**Issue by liudongmiao** [SpiderLabs/ModSecurity#2691]
There is `multiMatch`.

> Normally, variables are inspected only once per rule, and only after all transformation functions have been completed. With multiMatch, variables are checked against the operator before and after every transformation function that changes the input. 

In our cases, we'd like to check every alternative transformed value, but want to exit only once then exit.

For example, when the value is `%2F%2A%21u%256eion%2A%2F%20%2F%2A%21se%256cect%2A%2F%201%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C0%2C11` (from waf_bypass project), which can be
- `/*!u%6eion*/ /*!se%6cect*/ 1,2,3,4,5,6,7,8,9,0,11`, after `t:urlDecodeUni`
- `/*!union*/ /*!select*/ 1,2,3,4,5,6,7,8,9,0,11'`, after second `t:urlDecodeUni`
- `1,2,3,4,5,6,7,8,9,0,11`, after `t:removeComments`

If we use `multiMatch`, the value will be checked for several times. However, in the actual pattern, IMO, it should break once matched.

In our project, we just add a `break` after `globalRet = true;` in `src/rule_with_operator.cc`. However, if it's a feature, it should be on option.

**Comment by martinhsv** [comment]
Hi @liudongmiao ,

Could you describe what your underlying goal is? I.e. what tangible problem or inconvenience does the current functionality result in?

**Comment by liudongmiao** [comment]
@martinhsv I'd like to discuss in #2692, and named it as rule score mode.
