### ISSUE TITLE
How to check if transaction intercepted or not (QUESTION)

### ISSUE THREAD

**Issue by willyamcts** [SpiderLabs/ModSecurity#2694]
1. How to check that the transaction intecepted? Some variable the utilizing? 
In my view this must in phase 5 but I dont my be how

Context: I need to analyze whether the transaction was intercepted or not to run a chained rule with specific log blocks

**Comment by martinhsv** [comment]
Hi @willyamcts ,

It might depend on what exactly your underlying motives and goals are. And also what your overall deployment is (including which version of ModSecurity).

A couple of things you could consider:
- have a rule that tests the RESPONSE_STATUS variable
- if your main detection rules use 'block' as their disruptive action and use SecDefaultAction to do the actual 'deny', you could add something to that configuration item that would be useful to you, like perhaps setting a transaction variable that you can test later

**Comment by willyamcts** [comment]
Hi @martinhsv , thanks for atttention.

- ModSecurity in version 2.9.4.
- SecActionDefault is "pass".
- I using CRS rules too.

About the context: I would like to suppress auditLogPart blocks (like the H - audit_data JSON) when the 403 return was from the application/website, not from ModSecurity.

By using RESPONSE_STATUS I would be covering all returns, including the application's return. For example: if my application returns 403 when trying to access pages that require authentication, then the return 403 is from the application and not due to ModSecurity rules.

So if I suppress LogPart H for example, my rules with "deny" and "drop" won't insert LogPart H in the log, so the rule matches won't show up in the log.

Because of this I would like to analyze RESPONSE_STATUS with a chained rule analyzing a variable that indicates that it request was intercepted

One example.
modsecurity.conf:
```
SecAuditEngine On
SecAuditLogParts ABIJDFHZ
SecAuditLogFormat JSON
....
```

rule: 
```
SecRule RESPONSE_STATUS "403" \
 "id:116, phase:5, pass, nolog, auditlog"
  chain"
  SecRule [collection]:[var] "@eq 0" \   // consider 0 how intercepted=false
   "ctl:auditLogParts=-H"
```
The rule above would analyze the 403 return and a possible ModSecurity environment variable that stores whether the request was intercepted or not


Other option alternative would be to insert a variable in TX when the rule has "deny" or "drop" disruptive action, but it's not a good idea to make these changes.

**Comment by liudongmiao** [comment]
@willyamcts You can add `severity` to the `deny` rule, then use `HIGHEST_SEVERITY` to solve this problem.

Or, use another error code, like `493`, and show `request_id` in the page. (I have make a PR on modsecurity-nginx to solve the `error_page` or `internal redirect` issue).

**Comment by martinhsv** [comment]
@willyamcts ,

Yes, if you want to distinguish a 403 generated by ModSecurity from a 403 generated by the web app, then merely checking RESPONSE_STATUS in phase:5 will not be sufficient.

If you don't want to make use of extra variables or settings (as in the second bullet point in my original or reply, or the severity suggestion made yesterday), there is another option that might work for you:

Create a phase:3 rule that checks RESPONSE_STATUS.

If ModSecurity intercepts the request during phase:1 or phase:2, and the request does not reach the web server at all, then phase:3 rules will not get run. However, if the request did reach the web server and the web server returns a 403, then your new phase:3 rule *will* get run and you can test the RESPONSE_STATUS that was returned.
