### ISSUE TITLE
feature request: anti-evasion for %25 in urlDecode / urlDecodeUni

### ISSUE THREAD

**Issue by liudongmiao** [SpiderLabs/ModSecurity#2703]
`%` would be encoded into `%25`.

- `<`
- `%3C`
- `%253C`
- `%25253C`
- `...`

Would urlDecode / urlDecodeUni support to auto decode `%25`, or as an option?

The code would be easy:

```c
    while (i < input_len) {
        if (input[i] == '%') {
            /* decode all % */
            while (i + 2 < input_len && input[i + 1] == '2' && input[i + 2] == '5') {
                i += 2;
                input[i] = '%';
            }
            /* continue to normal decode */
    }
```

**Comment by martinhsv** [comment]
This isn't a good idea.

Attempting to evade a detection through double-encoding (or more) has been a well-known technique in the web application space for a long time. But for a tool like ModSecurity, the responsibility for when and how much to decode, it only makes sense for that to be the responsibility of rule writers. The same is true for detecting such patterns as being in themselves suspicious.

"as an option".

This functionality is already effectively available. Rule writers can add an extra 't:urlDecode' -- or not.

**Comment by liudongmiao** [comment]
`t:urlDecode` cannot do such thing:

- `+`
- `%2B`

Then, when decode twice, `+` would be turn to ` `(space).

**Comment by martinhsv** [comment]
Huh? I don't see what your point is.

I'm going to have to ask you to be more descriptive in your postings -- not just this one. This typically involves providing actual payload examples and actual rules where you think you have some difficulty.

With respect to encoding, the overall issue that WAFs face is to interpret data the same way the web server would. A particular input item, let's say "parm1", will get url-decode some number of times by the web server -- normally once, but sometimes twice (and very occasionally, three times).

If the value of "parm1" will be url-decoded twice then you do in fact want ModSecurity to replicate that by doing:
'%2561' ==> '%61 ==> 'a'
 *and* you would like want:
'%2b' ==> '+' ==> ' '
