### ISSUE TITLE
Question: DURATION

### ISSUE THREAD

**Issue by liudongmiao** [SpiderLabs/ModSecurity#2704]
Currently, the `DURATION` is using `CLOCK_PROCESS_CPUTIME_ID` since 2015, introduced in commit a4cf218a3e6396a7d21f2b831c052933d5b70a5c.

For time, nginx switch to `CLOCK_MONOTONIC` /  `CLOCK_MONOTONIC_FAST` since 2018.

For openjdk, `nanoTime` using `CLOCK_MONOTONIC`. For macOS, openjdk use `mach_absolute_time` and `mach_timebase_info`, however, `CLOCK_MONOTONIC` is available to.

Would it ok to switch `CLOCK_MONOTONIC`?

**Comment by liudongmiao** [comment]
@zimmerle is the original author of this. And @martinhsv is very active for this project.

**Comment by liudongmiao** [comment]
However, `DURATION` returns seconds, cannot be used for performance time.

**Comment by liudongmiao** [comment]
#1011 for related perf_*

**Comment by martinhsv** [comment]
> However, DURATION returns seconds, cannot be used for performance time.

I don't understand that comment.

DURATION is implemented as a variable of type double, which means it can and will return a number like 0.024000 indicating 24 milliseconds -- or 1.315 indicating 1315 milliseconds.

**Comment by liudongmiao** [comment]
Sorry for the `double`.
