### ISSUE TITLE
ModSecurityIIS_2.9.5 HTTP Error 500.19 after uninstall

### ISSUE THREAD

**Issue by mmojadad** [SpiderLabs/ModSecurity#2706]
Installed version ModSecurityIIS_2.9.5-64b.msi

Issue : 

After uninstall ModSecurityIIS_2.9.5 all websites return :

HTTP Error 500.19 - Internal Server Error
Detailed Error Information:
Module | IIS Web Core
Unknown
Not yet determined
0x8007000d
 
\\?\C:\HostingSpaces\domain\domain.com\wwwroot\web.config

Config Source:
-1: 
    0:

**Comment by martinhsv** [comment]
Hi @mmojadad ,

I just tried that with my test setup (right-click on the installer file, then select uninstall).

The uninstall proceeded without error. And I accessed an IIS test page afterwards with no problem.

**Comment by martinhsv** [comment]
Is this still a problem for you?

If so, I'd suggest looking at what other error messages you may be getting (particularly in Event Viewer). Beyond that, have a look the online documentation ( https://docs.microsoft.com/en-us/troubleshoot/developer/webapps/iis/health-diagnostic-performance/http-error-500-19-webpage ) and see if anything makes sense.

If you still cannot resolve it, or generate any extra information that you can share, _and_ you are having an ongoing problem, then alternative you could consider is to _not_ uninstall ModSecurity but simply to turn it off (SecRuleEngine Off).

**Comment by mmojadad** [comment]
@[martinhsv](https://github.com/martinhsv)
Hi
I found reason of the issue and fixed it.
When uninstall ModSecurity , Still ModSecurity tags remain in web.config of all websites , I manually removed <ModSecurity enabled="false" ...> and fixed.

**Comment by mmojadad** [comment]
The main reason i uninstalled ModSecurity was slow performance on IIS

**Comment by martinhsv** [comment]
Okay. Good to hear that you resolved your issue.

Thanks for updating here too in case that's helpful to someone in future.
