### ISSUE TITLE
The information of client IP after multi-layer nginx proxy is not real IP

### ISSUE THREAD

**Issue by floretisme** [SpiderLabs/ModSecurity#2712]
The information of client IP after multi-layer nginx proxy is not real IP

example:
nginx1  ip 0.0.0.1
nginx2  ip 0.0.0.2
nginx3  ip 0.0.0.3

ModSecurity  client_ip is  nginx2   ip 0.0.0.2    

but i need user's real IP

**Comment by martinhsv** [comment]
Hi @zxp2mmy ,

If you have one or more intermediate proxies between the untrusted internet and your instance running ModSecurity, then, yes, you cannot simply use what has been recorded from the transport layer as the client address.

Usually such intermediate proxies can be configured to (or already do by default) record the client address that *they* received in a request header (most commonly X-Forwarded-For, but there are others with a similar purpose).
