### ISSUE TITLE
Any method to count specific attacks type in modsecurity logs?

### ISSUE THREAD

**Issue by m1hamedCS** [SpiderLabs/ModSecurity#2713]
eg. I want to count how many XSS attacks my application exposed?
I want this so much to be able to write attacks report to my organization.

thanks in advance

**Comment by martinhsv** [comment]
Hi @MoCs1 ,

ModSecurity itself is the engine; attack types will be tied to and defined by the rules that you are using for those detections.

But supposing you have a rules set where five of the rules are intended to detect XSS attacks, a couple of different ways you could generate counts are:
- those five rule could each increment a counter that is stored in persistent memory
- those five rules could each include a tag (e.g. 'attack-XSS'); and you could do post-ModSecurity processing of the logs
