### ISSUE TITLE
Failed to load the GeoDB from: /usr/share/GeoIP/GeoLite2-Country.mmdb

### ISSUE THREAD

**Issue by 236765966** [SpiderLabs/ModSecurity#2716]
I used SecGeoLookupDB to load the geolite2-country. MMD file, but it failed.  Whether it's V2 or V3 GeoLiteDB  ,Configuration is as follows 
# For ModSecurity v3:
SecGeoLookupDB /usr/share/GeoIP/GeoLite2-Country.mmdb

Error reading file /usr/share/GeoIP/GeoLite2-Country.mmdb
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/conf.d/modsecurity/crs-setup.conf. Line: 97. Column: 43. Failed to load the GeoDB from: /usr/share/GeoIP/GeoLite2-Country.mmdb. Can't open:  /usr/share/GeoIP/GeoLite2-Country.mmdb. Support enabled for: GeoIP. GeoIP: Can't open: /usr/share/GeoIP/GeoLite2-Country.mmdb.  in /etc/nginx/nginx.conf:30
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by martinhsv** [comment]
Hello @236765966 ,

I just tried that (with a fresh file from the maxmind site) in ModSecurity v3 and I did not get that error.

Based on the error message that you have shown above, it looks like the filename that you specified with SecGeoLookupDB is being successfully found.

You could check the permissions on the file. Or it could be that the file's content are not in the valid .mmdb format.

One other thing to check, is that when you run ./configure, you see suitable output, e.g.
```
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (GeoIP) v1.6.12
         -lGeoIP  , -I/usr/include/  

```

(For ModSecurity v2, I don't believe support for GeoIP2 was ever implemented. Have a look at https://github.com/SpiderLabs/ModSecurity/issues/1727 and https://github.com/SpiderLabs/ModSecurity/issues/2420 )
