### ISSUE TITLE
SecRuleEngine logs only SecRuleID 949110

### ISSUE THREAD

**Issue by tarmo-profi** [SpiderLabs/ModSecurity#2722]
**Describe the bug**

If SecRuleEngine is set to On and a ShellShock attack is made, logs only present a SecRuleID 949110 Inbound Anomaly Score Exceeded (Total Score: 5). ModSecurity has a SecRule against ShellShock, ID 932170 but it won't be logged.

**Logs and dumps**

> 2022/04/21 09:08:11 [error] 7814#7814: *1431691 [client IPADDRESS] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "192.168.149.9"] [uri "/"] [unique_id "1650532091"] [ref ""], client: IPADDRESS, server: DOMAIN.COM, request: "GET / HTTP/2.0", host: "DOMAIN.COM"

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs
 3. Error logs
 4. If there is a crash, the core dump file.

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

A **curl** command line that mimics the original request and reproduces the problem. Or a ModSecurity v3 test case.

`curl -H 'User-Agent: () { :; }; echo' DOMAIN.COM`

**Expected behavior**

After curl, the ModSecurity will block the request and logs it with SecRuleID 932170.

**Server (please complete the following information):**
 - ModSecurity version (and connector): ModSecurity v3.x.x
 - WebServer: nginx-1.19.10
 - OS (and distro): Linux Ubuntu

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? [e.g. SpiderLabs commercial rules] OWASP CRS
 - What is the version number? [e.g. 2018-08-11] 3.3.2

**Additional context**

**Comment by airween** [comment]
I'm not sure this is the right place for this question, it's rather a [ModSecurity-nginx](https://github.com/SpiderLabs/ModSecurity-nginx) issue.

Btw, how looks like your `error.log` directive in your `nginx.conf`?

The expected is something like this:

```
	error_log /var/log/nginx/error.log info;
```

**Comment by tarmo-profi** [comment]
> I'm not sure this is the right place for this question, it's rather a [ModSecurity-nginx](https://github.com/SpiderLabs/ModSecurity-nginx) issue.
> 
> Btw, how looks like your `error.log` directive in your `nginx.conf`?
> 
> The expected is something like this:
> 
> ```
> 	error_log /var/log/nginx/error.log info;
> ```

It shows 

`error_log  /var/log/nginx/error.log notice;`

Could adjusting this provide better logs?

**Comment by airween** [comment]
> `error_log /var/log/nginx/error.log notice;`
> 
> Could adjusting this provide better logs?

Why don't you try that? :)

Btw IMHO `notice` isn't enough, I checked. For more info, see Nginx's [docs](https://nginx.org/en/docs/ngx_core_module.html#error_log).

**Comment by ghost** [comment]
گزارش   هرزه  نامه

**Comment by ghost** [comment]
ناالل

**Comment by ghost** [comment]
نت

**Comment by ghost** [comment]
مهینیژنزنزل

**Comment by ghost** [comment]
ژوژوزو

**Comment by ghost** [comment]
تاففقثثیرذ

**Comment by ghost** [comment]
نتالب

**Comment by ghost** [comment]
الب

**Comment by ghost** [comment]
هرزه نامه .حذف کنید همه را

**Comment by ghost** [comment]
الب

**Comment by tarmo-profi** [comment]
> > `error_log /var/log/nginx/error.log notice;`
> > Could adjusting this provide better logs?
> 
> Why don't you try that? :)
> 
> Btw IMHO `notice` isn't enough, I checked. For more info, see Nginx's [docs](https://nginx.org/en/docs/ngx_core_module.html#error_log).

I tried setting error_log: error in nginx config file but it didn't log anything more i think.

I will look into this next monday.

**Comment by tarmo-profi** [comment]
Adjusting error_log didn't solve this issue. I will put new issue into https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by martinhsv** [comment]
Hi @tarmo-profi ,

I'm a little confused about your more recent updates prior to closing.

You stated that your setting originally was
```
error_log /var/log/nginx/error.log notice;
```

And that you later tried changing 'notice' to 'error' without that providing anything extra.

However, the suggestion made by @airween was the correct thing to try. I.e.:
```
error_log  /var/log/nginx/error.log info;
```

**Comment by ghost** [comment]
@airween I tried to ask @martinhsv , but it seems that he is not active anymore, so I would like to ask you instead:

Why are the rules prefixed with [info] in the error log, although the severity is "2" for example?

Is there really no way to display the rule that ultimately led to the 403 in addition to the 403 error? I once saw somewhere in an Apache environment a one-liner in the apache error log like ‘ModSecurity: Access denied with code 403 ... ‘ together with the (last) rule that triggered it.

My goal is to use Wazuh to have a GUI for ModSecurity, but of course it doesn`t look for [info] inside the nginx error log.

I am using `ModSecurity-nginx v1.0.3` and `libmodsecurity3 version 3.0.12`
Any help is appreciated.

**Comment by airween** [comment]
Hi @derMatze82,

* yes, @martinhsv is no longer active in this project
* I have to investigate this issue, thanks for bringing up

**Comment by hofq** [comment]
I have the same problem with ingress-nginx for k8s
