### ISSUE TITLE
ModSecurity (v3) Sending logs to syslog server

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2726]
I built ModSecurity using the following tutorial:
https://www.netnea.com/cms/nginx-modsecurity-tutorials/
I searched a lot about sending ModSecurity v3 logs to a Syslog server. Using pipe is not supported and I don't know how to send my logs. My Syslog server is not an HTTP server. It just listened on a specific port (514). I don't know how to compile and use mlogc according to the tutorial: https://www.netnea.com/cms/nginx-modsecurity-tutorials/
Please help me.

**Comment by martinhsv** [comment]
@Mahboubi68 

I cannot comment on resources belonging to that company. If you have questions specific to their pages, you should probably contact them directly.

I may be able to help with your general question, however. 

Which logs are you talking about? There are three different logs relevant to ModSecurity: 1) The web server's own error.log file (for ModSecurity v3, I assume you're talking about nginx) 2) ModSecurity's audit_log and 3) ModSecurity's debug log

If you are talking about 1), it is possible to configure that for syslog redirection, but that is really an nginx configuration matter.

If you are talking about 2), the standard way to direct audit log output to another machine is with the http logging option. See for example #1498 and https://github.com/SpiderLabs/ModSecurity-nginx/issues/135

**Comment by ghost** [comment]
Tnx a lot @martinhsv for the comment
