### ISSUE TITLE
Wrong link in wiki

### ISSUE THREAD

**Issue by Delet0r** [SpiderLabs/ModSecurity#2740]
The link 

https://www.trustwave.com/2008/07/three-modsecurity-rule-language-annoyances.html/ 

on the wiki page 

https://www.trustwave.com/2008/07/three-modsecurity-rule-language-annoyances.html/

is not correct anymore and returns a 404. This should be the updated version

https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/three-modsecurity-rule-language-annoyances/

**Comment by martinhsv** [comment]
Changed.
