### ISSUE TITLE
Directive Rules Error

### ISSUE THREAD

**Issue by skrlance** [SpiderLabs/ModSecurity#2743]
The latest modsecurity.conf that I am using from this Github on my server with NGINX gives the following error:

`nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/conf.d/modsec/modsecurity.conf. Line: 10. Column: 32. Invalid input:  SecRequestBodyJsonDepthLimit 64 in /etc/nginx/conf.d/vhosts/default.conf:8`

Server details:

```
nginx version: nginx/1.20.2
libmodsecurity-3.0.5
nginx-more-module-modsecurity-1.20.2
```
This error can be resolved by removing or commenting:

`SecRequestBodyJsonDepthLimit 512`

I have also tried providing other values but the error doesn't gets resolved.

What should I do? Can somebody help please!!

**Comment by airween** [comment]
libmodsecurity3 version [v3.0.6](https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.6) was released on Nov 20, 2021.

Version [v3.0.5](https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.5) on Jul 08, 2021.

`SecRequestBodyJsonDepthLimit` has been [added](https://github.com/SpiderLabs/ModSecurity/commit/ac79c1c29b7e6323e26cc984ad4f76ef62c731cd) on Nov 16, 2021, so the v3.0.6 contains it, but v3.0.5 does not. Latest `modsecurity.conf` was [aligned]( https://github.com/SpiderLabs/ModSecurity/commit/0275c8847b3d8e2bc818d42306b0b362c68b6084) to this version on Dec 21, 2021.

You should upgrade your library, or have to remove this directive.
