### ISSUE TITLE
cannot proceed compile process with tag version 3.0.6

### ISSUE THREAD

**Issue by chenjinlei** [SpiderLabs/ModSecurity#2745]
I cannot proceed compiling with v3.0.6.
I uncompressed tarball ModSecurity-3.0.6.tar.gz, and run build.sh

> [root@localhost ModSecurity-3.0.6]# ./build.sh 
> libtoolize: putting auxiliary files in '.'.
> libtoolize: copying file './ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build'.
> libtoolize: copying file 'build/libtool.m4'
> libtoolize: copying file 'build/ltoptions.m4'
> libtoolize: copying file 'build/ltsugar.m4'
> libtoolize: copying file 'build/ltversion.m4'
> libtoolize: copying file 'build/lt~obsolete.m4'
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> configure.ac:50: installing './ar-lib'
> configure.ac:50: installing './compile'
> configure.ac:140: installing './config.guess'
> configure.ac:140: installing './config.sub'
> configure.ac:45: installing './install-sh'
> configure.ac:45: installing './missing'
> parallel-tests: installing './test-driver'
> examples/multiprocess_c/Makefile.am: installing './depcomp'
> configure.ac: installing './ylwrap'
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> fatal: not a git repository (or any of the parent directories): .git
> 

apparently, it's not a git repository, and building process need it to be a git repository.
And I run ./configure --prefix=/usr/local/modsec, I got a configure error:

> configure: error: 
> 
>   libInjection was not found within ModSecurity source directory.
> 
>   libInjection code is available as part of ModSecurity source code in a format
>   of a git-submodule. git-submodule allow us to specify the correct version of
>   libInjection and still uses the libInjection repository to download it.
> 
>   You can download libInjection using git:
> 
>      $ git submodule init
>      $ git submodule update
> 

> [root@localhost ModSecurity-3.0.6]# git submodule init
> fatal: not a git repository (or any of the parent directories): .git

How can I deal with this situation?
Is there any way to compile with a released version?

Thanks!

**Comment by martinhsv** [comment]
Hello @chenjinlei ,

When you are using a ModSecurity release's tar.gz file as your starting point you don't need to do the two ```git submodule``` steps or ```build.sh```.

Just start with the ```./configure``` step.

**Comment by chenjinlei** [comment]
I don't think I can find configure..., from README it seems configure is generated by running build.sh...

> Hello @chenjinlei ,
> 
> When you are using a ModSecurity release's tar.gz file as your starting point you don't need to do the two `git submodule` steps or `build.sh`.
> 
> Just start with the `./configure` step.

**Comment by martinhsv** [comment]
Hello @chenjinlei ,

You are mistaken. The file 'modsecurity-v3.0.6.tar.gz' located at: https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.6

includes the file 'configure'.

**Comment by chenjinlei** [comment]
> Hello @chenjinlei ,
> 
> You are mistaken. The file 'modsecurity-v3.0.6.tar.gz' located at: https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.6
> 
> includes the file 'configure'.

Oh, thanks martin! I downloaded from tag version...
the release version tarball works just fine.
