### ISSUE TITLE
Add weak password detection for modsecurity failed

### ISSUE THREAD

**Issue by chenjinlei** [SpiderLabs/ModSecurity#2759]
I add a new conf named `REQUEST-914-WEAKPASSWORD-DETECTION.conf` for modsecurity.
And write a rule within as below:
```
SecRule REQUEST_FILENAME|ARGS "@pmFromFile weak-passwords.data" \                            
    "id:914100,\                                                                             
    phase:2,\                                                                                
    block,\                                                                                  
    capture,\                                                                                
    t:none,\                                                                                 
    msg:'Found weak passwords in filename/argument',\                                        
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\       
    tag:'application-multi',\                                                                
    tag:'language-multi',\                                                                   
    tag:'platform-multi',\                                                                   
    tag:'attack-reputation-weak-password',\                                                  
    tag:'paranoia-level/1',\                                                                 
    tag:'OWASP_CRS',\                                                                        
    tag:'capec/1000/118/224/541/310',\                                                       
    tag:'PCI/6.5.10',\                                                                       
    ver:'OWASP_CRS/3.4.0-dev',\                                                              
    severity:'CRITICAL',\                                                                    
    setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}',\                            
    setvar:'ip.reput_block_flag=1',\                                                         
    setvar:'ip.reput_block_reason=%{rule.msg}',\                                             
    expirevar:'ip.reput_block_flag=%{tx.reput_block_duration}'"
```

weak-passwords.data I used is from kali dictionary located at /usr/share/wordlists/rockyou.txt.gz, which aroud 133MB.

I added this to nginx conf, and launched nginx with messages:

> modsec *** ngx_http_modsecurity_create_main_conf: main conf created at: '0x10aa538', instance is: '0x1089490' at 
> /root/exp/ModSecurity-nginx/src/ngx_http_modsecurity_module.c line 648.
> modsec *** ngx_http_modsecurity_create_conf: conf created at: '0x10aa578' at /root/exp/ModSecurity-nginx/src/ngx_http_modsecurity_module.c line 711.
> modsec *** ngx_http_modsecurity_create_conf: conf created at: '0x10de3c8' at /root/exp/ModSecurity-nginx/src/ngx_http_modsecurity_module.c line 711.
> modsec *** ngx_http_modsecurity_create_conf: conf created at: '0x10e46f0' at /root/exp/ModSecurity-nginx/src/ngx_http_modsecurity_module.c line 711.

It seems like nginx failed to call modsecurity interface, and failed to dump rules, and system memory is highly escalated.
When I disinclude the rule file I created, nginx launched correct.

Is it because of size of the file?

[192.168.10.221_2022-06-07_10_12_16.log](https://github.com/SpiderLabs/ModSecurity/files/8849632/192.168.10.221_2022-06-07_10_12_16.log)

**Comment by martinhsv** [comment]
@chenjinlei ,

I'm not clear on what you are reporting.

The messages that you have pasted into your posting "modsec *** ..." are not meaningful to any problem that you experienced.

Are you saying that there was a core dump? If so, can you provide a backtrace?

Or are you saying that when you attempted to start the service you got a message like this?:
```
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
```

If so, the suggested commands to get details may be useful.
