### ISSUE TITLE
The nginx worker process exits unexpectedly？

### ISSUE THREAD

**Issue by lalilalali** [SpiderLabs/ModSecurity#2769]
**Describe the bug**
The nginx worker process exits unexpectedly？

linux centos 7（kernel:5.4.200-1.el7.elrepo.x86_64）

nginx version: openresty/1.21.4.1

**Logs and dumps**

2022/06/30 04:27:49 [alert] 162739#162739: worker process 101475 exited on signal 11 (core dumped)

[Thu Jun 30 04:27:42 2022] nginx[101475]: segfault at 0 ip 00007ff453910b67 sp 00007ffda0306a40 error 4 in libmodsecurity.so.3.0.7[7ff45376f000+220000]

**Comment by martinhsv** [comment]
Hello @lalilalali ,

Have a look at the issue template and add any additional information that you can, including logs, steps to reproduce, connector version, and any other context, including choices during the build process and any non-default configuration.

Often, particularly useful in the case of a core dump, is the stack trace from the core.

**Comment by lalilalali** [comment]
> 
@martinhsv 
Redeploy on a different server and the problem will be solved.
Thanks.
