### ISSUE TITLE
compile the Modsecurity module

### ISSUE THREAD

**Issue by karzanahmed** [SpiderLabs/ModSecurity#2771]
![image](https://user-images.githubusercontent.com/16222353/178165116-a72718c8-0005-45fa-88e6-cb8497bc9e16.png)

how can i fix it?

**Comment by airween** [comment]
Based on your image, it looks like you want to build Nginx from Debian package source, but I'm afraid you forgot/mistype something...

Can you copy here your steps, what did you do exactly?

Btw: there are pre-build packages on [this](https://modsecurity.digitalwave.hu) site. This repository contains Nginx 1.18.0 for Debian 11 and Ubuntu 20.04, it seems you want to use that version.

Also you can grab the modified `debian/` [package](https://modsecurity.digitalwave.hu/debian/pool/main/n/nginx/nginx_1.18.0-6.2~20210903+debian11~1.debian.tar.xz) of Nginx, and make your own build (eg. with `dpkg-buildpackage -us -uc`).
