### ISSUE TITLE
URI fragments as ARGS

### ISSUE THREAD

**Issue by victorserbu2709** [SpiderLabs/ModSecurity#2784]
Hello. 
It is possible to map URI fragments to ARGS?

Eg.
Route path: /users/:userId/books/:bookId
Request URL: http://localhost:3000/users/34/books/8989
I would like ARGS to be populated with userId=34, bookId=8989.

Or there exists other generic method to sanitise these parameters in CRS?

**Comment by martinhsv** [comment]
Hello @victorserbu2709 ,

To clarify terminology, "URI fragments" usually refers to the content after a '#' character in a URI that is normally not sent to the server.

You appear to be talking about path segments.

The short answer is, no, there is no way to have ModSecurity populate the ARGS collection with strings from path segments of a request URI.

You can create rules that inspect the URI as is (for example via REQUEST_URI or REQUEST_URI_RAW). Alternatively, You could also parse the request line yourself and populate some transaction variables which you could in turn inspect with a separate rule.

I'm not aware that CRS has anything that does something like that already. You could consider inquiring with them (it is a separate project).
