### ISSUE TITLE
Is it possible to change Loaded PCRE version from 8.44 to 8.8

### ISSUE THREAD

**Issue by Rip-P** [SpiderLabs/ModSecurity#2787]
A different perspective for a solution to:

```
ModSecurity: Loaded PCRE do not match with compiled!
ModSecurity: PCRE compiled version="8.39 "; loaded version="8.44

```
Is it possible to change PCRE loaded version _from_ "8.44" "8.39"?
If so how can that be accomplished?

Any advice or assistance will be appreciated.

**Comment by martinhsv** [comment]
Hello @dave-w-wilson ,

You haven't provided very much information but it sounds like you are *probably* using Apache HTTP Server with ModSecurity v2.9.x. If so, it's important that the version of pcre 8.x that is used for building ModSecurity is the same as that used to build Apache. If you're not building Apache yourself (for example you got it from a repo) then your build of ModSecurity must use the same version of pcre 8.x that is used in the Apache binary.

If that doesn't answer your question, please include information about your environment and what you are doing. The bug report templates provide a list of things that are useful, but at minimum:
- what web server and version are you using?
- what version of ModSecurity?
- describe your starting point and what exactly you are trying to do

**Comment by airween** [comment]
Hi @dave-w-wilson,


> ```
> ModSecurity: Loaded PCRE do not match with compiled!
> ModSecurity: PCRE compiled version="8.39 "; loaded version="8.44
> ```
> 
> Is it possible to change PCRE loaded version _from_ "8.44" "8.39"? If so how can that be accomplished?

how did you build your mod_security module for your Apache?

We have a [ModSecurity repository for Debian](https://modsecurity.digitalwave.hu), I make the packages. I always use the standard system packages, but in some cases, the guest system where the users installed that module use different PCRE version, eg. because they use [Sury's PHP packages](https://packages.sury.org/php/). Those packages uses newer version of PCRE.

Your mentioned versions are the same as the systems where I ran into this issue (8.39 vs 8.44).

So, the Debian uses pcre3 ver [8.39](https://packages.debian.org/bullseye/libpcre3) (both in 11 and [10](https://packages.debian.org/buster/libpcre3)), and Sury's repository provides [8.44](https://packages.sury.org/php/pool/main/p/pcre3/) (also for 11 and 10).

I assume you are in a similar situation like this.

**Comment by Rip-P** [comment]
Thanks for the responses. So 20 years ago I used to build everything from source. Now I suppose I am getting lazy. (rethinking that now.)

- Server Version: Apache/2.4.54 (Ubuntu)
- PHP 8.0.22 (cli) (built: Aug 15 2022 09:40:14)
- PCRE compiled version="8.39 "; loaded version="8.44 2020-02-12"  

Installed from repo:
ppa.launchpad.net/ondrej/php/ubuntu jammy/main
ppa.launchpad.net/ondrej/apache2/ubuntu jammy/main

I was being a bit over anal and upgraded my php to 8.0 because of other errors on the system. I am certain this is related.
So now I suppose I need to ask if the compiled version vs loaded version of PCRE is something I need to be concerned about or not. 

I suppose I am looking for best practice here.  And in spite of the  embarrasing situation I have placed mysel in, I think others in this situation could benefit from a resolution. 

Thanks for the help and advice!
Dave

**Comment by airween** [comment]
> Installed from repo:
> ppa.launchpad.net/ondrej/php/ubuntu jammy/main
> ppa.launchpad.net/ondrej/apache2/ubuntu jammy/main

Yes, I think these are the same packages as on packages.sury.org. The maintainer is the same, he is a Debian/Ubuntu developer/maintainer.

But then I do not understand his idea: if he uses newer PCRE version for X, Y and Z packages, why didn't he build with all of them...? It's not so consistent...

> So now I suppose I need to ask if the compiled version vs loaded version of PCRE is something I need to be concerned about or not.

I think the adequate answer this is not good.

PCRE is one of the core component of the whole system, without that your system won't start.

You can check the reverse dependencies with this command:

```
apt-cache rdepends --installed libpcre3
```

All of the listed packages depend on PCRE, so those are in same situation as Apache (and not just the libapache2-mod-security2, but the core httpd too, as you will see).

The ugly answer is while all of these packages work, you shouldn't worry about this.

> I suppose I am looking for best practice here. And in spite of the embarrasing situation I have placed mysel in, I think others in this situation could benefit from a resolution.

First, you should ask Ondrej why does he use the newer version of libpcre3, and why does not he use the same version for all packages.

If I were you I would rebuild only the PHP packages for myself on an own build system, with the correct versions. But the question is still open: why did he build with the newer version? Is there any reason?

**Comment by Rip-P** [comment]
Fair enough and thanks. I'll ask the maintainer but realistically even though everything is _apparently_ working, I'll most likely rebuild the php from source with the correct modules.

apt-cache rdepends --installed libpcre3
libpcre3
Reverse Depends:
  libpcrecpp0v5
  libpcrecpp0v5
  libpcrecpp0v5
  libpcrecpp0v5
  apache2-bin
  libpcrecpp0v5
  lnav
  libapache2-mod-security2
  libpcrecpp0v5
  libpcrecpp0v5
  grep
  libglib2.0-0
  grep
  apache2-bin
Thanks Again.

**Comment by airween** [comment]
> Fair enough and thanks. I'll ask the maintainer but realistically even though everything is _apparently_ working, I'll most likely rebuild the php from source with the correct modules.

I checked the libpcre3's changelog:

https://www.pcre.org/original/changelog.txt

and found these changes, which theoretically _can_ affect the API - but I'm sure those do not.

```
8.43
----
1. Some time ago the config macro SUPPORT_UTF8 was changed to SUPPORT_UTF
because it also applies to UTF-16 and UTF-32.
...
9. Improve MAP_JIT flag usage on MacOS. Patch by Rich Siegel.

...

8.42
----
...
2.  Fixed outdated real_pcre definitions in pcre.h.in (patch by Evgeny Kotkov).
```

Well, this is just my opinion, but after I checked the changelog, I wouldn't worry about this version mismatch (including PHP - I would keep it as it is).

**Comment by Rip-P** [comment]
This is probably going to work out. i am checking the logs to verify any weird functionality or false positives. (ModSecurity)
Seems to be ok but I'll sit on it for a week and report back one way or another.

Thank you!

**Comment by martinhsv** [comment]
I'm going to go ahead and assume that there is nothing further here from the perspective of the ModSecurity project ...

**Comment by africabloe** [comment]
`Feb 29, 2024] [:warn] ModSecurity: Loaded PCRE do not match with compiled!`
`ModSecurity: PCRE compiled version="8.39 "; loaded version="8.45 2021-06-15"`

```
Operating system: Ubuntu Linux 22.04.4
Firewall version: ConfigServer Security & Firewall 14.20
Apache version: 2.4.52
PHP versions: 8.3.3  repo: https://ppa.launchpadcontent.net/ondrej/php/ubuntu/
ModSecurity for Apache/2.9.5 OWASP_CRS/4.0.1-dev libapache2-mod-security2 2.9.5-1ubuntu0.1~esm1 amd64
```
1.5 years later the difference between the versions is even greater but apart from some warnings when restarting Apache2 no other problems in the operation of the server and websites.

Thanks for bringing the issue to light @martinhsv and @Rip-P

**Comment by airween** [comment]
> `ModSecurity: PCRE compiled version="8.39 "; loaded version="8.45 2021-06-15"`

I'm afraid if you use PHP from that repository, then that package use an own PCRE2 library. But the official upstream (Ubuntu) uses the "standard" PCRE2 library, this is why you see this mismatch.

Download the source package and build an own one with the specific PCRE.
