### ISSUE TITLE
Stripe checkout return url respond 403

### ISSUE THREAD

**Issue by ofmarconi** [SpiderLabs/ModSecurity#2790]
When the checkout is finished, Stripe sends the customer to the origin site, in this return there is a query parameter:

/?session_id=21312412321...

With current CyberPanel rules and standards this URL responds with 403.

How can I resolve this?
Shouldn't block Stripe, right?

Thanks

**Comment by ofmarconi** [comment]
How can I disable only this specific rule for a specific set of URL's in OLS + CyberPanel?

I've tried via HTACCESS without success:
https://community.cyberpanel.net/t/mod-security-how-to-create-and-edit-specific-rules-for-a-website/36529/2

**Comment by ofmarconi** [comment]
### LOG:

> ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `REQUEST_HEADERS:Referer' (Value: `0' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf"] [line "79"] [id "943120"] [rev ""] [msg "Possible Session Fixation Attack: SessionID Parameter Name with No Referer"] [data "Matched Data: session_id found within REQUEST_HEADERS:Referer: 0"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-fixation"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/225/21/593/61"] [hostname "site.com.br"] [uri "/landingpages/moto/"] [unique_id "1661220656"] [ref "o0,10v86,10t:urlDecodeUni,t:lowercase"]
> ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/lsws/conf/modsec/owasp-modsecurity-crs-3.0-master/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "site.com.br"] [uri "/landingpages/moto/"] [unique_id "1661220656"] [ref ""]

**Comment by martinhsv** [comment]
Hello @ofmarconi ,

A fairly common way to deal with individual false positives of that sort is to use the ctl:ruleRemove* family of actions within a phase:1 rule. E.g.

```SecRule REQUEST_URI "<whatever conditions>" "id:1001,phase:1,t:none,pass, nolog,ctl:ruleRemoveById=943120"```

**Comment by ofmarconi** [comment]
> SecRule REQUEST_URI "<whatever conditions>" "id:1001,phase:1,t:none,pass, nolog,ctl:ruleRemoveById=943120"

**Thanks for the help**, I added this:

`SecRule REQUEST_URI "@contains landingpages" "id:1001,phase:1,t:none,pass, nolog,ctl:ruleRemoveById=943120",`
`SecRule REQUEST_URI "@contains landingpages" "id:1001,phase:1,t:none,pass, nolog,ctl:ruleRemoveById=949110",`

And I didn't succeed, I want all URLs that contain "landingpages" to have this disabled.

**example:**
site .com/_landingpages_/?stripe=1&session_id=312312312312321321

**Comment by martinhsv** [comment]
Hi @ofmarconi ,

I wouldn't recommend using that second line. CRS's rule 949110 is intended (in anomaly scoring mode) to decide, based on what earlier rules have been triggered, whether to block or not. In other words, removing 949110 means you will stop blocking requests that contain other types of attacks (SQLi, XSS, etc.) as well.

If you used both of those rule lines, the most likely explanation is that your rules were not included by ModSecurity at all. I say this because both of those lines have the same id. Rule ids must be unique for the ModSecurity instance or an error should be triggered at startup.

**Comment by ofmarconi** [comment]
> If you used both of those rule lines

Thanks for the warning, I hadn't noticed that!
I just left one now, and the 403 error still persists, I'm using CRS, I opened an issue there too, I'm really confused and I have no idea where to go next.

Maybe disable completely on that specific page? I also tried and failed with new rules.

**Comment by martinhsv** [comment]
One way to confirm that a single rule is not being included in your ModSecurity configuration is to deliberately misspell a keyword. In your case, you could use 'RQUEST_URI'. This should generate an error somewhere. If it doesn't it probably implies that   the rule isn't being included.

You can also enable the ModSecurity debug log (level '9' will show the most detail), and confirm that that rule id is not being processed.

**Comment by dune73** [comment]
Thanks for the support here @martinhsv.

We're covering this now over at https://github.com/coreruleset/coreruleset/issues/2762.
