### ISSUE TITLE
Can ModSecurity use the value in $proxy_protocol_addr for GeoIP Checks ?

### ISSUE THREAD

**Issue by okdn85** [SpiderLabs/ModSecurity#2804]
Hello,

I have an nginx + mod_security (v3.3.2) + CRS sitting behind a L4 TCP LoadBalancer with PROXY protocol enabled ( meaning the TCP LB can send information about the original Client IP only though the PROXY protocol).

Now, nginx can indeed extract that information and does so in the $proxy_protocol_addr variable (http://nginx.org/en/docs/http/ngx_http_core_module.html):

`$proxy_protocol_addr - 
client address from the PROXY protocol header (1.5.12)`

I can tell it's the correct value because I dumped it to access_log and it indeed shows the actual source IP.

I am trying to do GeoIP filtering using mod_security and unfortunatelly, looking at the refference manual here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x) the only relevant values are:

- REMOTE_ADDR: This variable holds the IP address of the remote client. ; however, in my case because traffic is coming from a TCP LB this value is the LBs IP
- REQUEST_HEADERS: Where I could place the value in a header like X-Forwarded-For; npow this would work if I had an HTTP LB in front instead of a TCP LB

So my question is : Can the same information that nginx stores in the **$proxy_protocol_addr** variable be accessible to be used by mod_security, to have something like:

SecRule PROXY_PROTOCOL_ADDR "@geolookup" .... ?

Thanks a lot.

**Comment by okdn85** [comment]
Not specifically an answer to this exact feature, but I did find a way to achieve the goal by using  ngx_http_realip_module: http://nginx.org/en/docs/http/ngx_http_realip_module.html 

http {
...
set_real_ip_from  192.168.1.0/24; <= which LB IP ranges I allow the overwrite to REMOTE_ADDR to happen
real_ip_header    proxy_protocol;
}

This way REMOTE_ADDR is actually overwritten by nginx before GeoIP check, and since mod_security knows how to work with REMOTE_ADDR, all is good 💯 

Leaving this here in case other people try to solve the same isue.

**Comment by martinhsv** [comment]
Hello @okdn85 ,

The short answer to your question about your hypothesized rule ('SecRule PROXY_PROTOCOL_ADDR ... ') is no. ModSecurity rules do not have direct access to arbitrary nginx variables. In particular, a variable name that follows 'SecRule' must be one that is defined within ModSecurity (or set by the rule set as with collections like TX.).

Thanks for your tip, though, that may be helpful to some other users.

Another way to achieve what you want (assuming that I've understood you correctly) is to simply use the @geoLookup operator against whatever variable is appropriate -- it is not restricted to use only against REMOTE_ADDR.

If you know that the relevant remote address that you wish to test is always contained in a request header with the name 'Proxy', you can simply test that value.

If you have a priority list of where the relevant remote address is located, you can test values and populate a TX variable that you can later test with @geoLookup.
