### ISSUE TITLE
Wrong hostname in modsecurity ModSecurity API function, which accepts a server IP address as an argument

### ISSUE THREAD

**Issue by alfonsoalongi** [SpiderLabs/ModSecurity#2808]
**Describe the bug**
We have HAProxy Enteprise which uses ModSecuirty v2.x. In the modsecurity logs, such as shown below, the private IP address of HAProxy appears in the host name field, i.e. 10.X.Y.Z, so the host name is missing.  This issue makes it extremely difficult to understand which hostname matches with a ModSecurity rule. I have already contacted HAProxy technical support who answered me like this:

_"I've got the answer from the engineering team, the ModSecurity API function, which is used to process the connection, accepts a server IP address as an argument (in our case that's IP address used on haproxy), which is later used in the logs. It says "hostname", but it's actually an IP address. Other ModSecurity implementations, such as the one for nginx also uses IP address, not hostname, as it's the most used implementation and we don't want to fork this code part we will leave it like this."_

**Logs and dumps**
Sep XX 00:XX:XX localhost hapee-lb[2135709]: https-in/owasp_crs ModSecurity: Warning. detected XSS using libinjection ... [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [hostname "10.X.Y.Z"] ... (omitted)

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

Install HAProxy Enteprise and enable ModSecurity module

**Expected behavior**
hostname as the word itself says should refer to an FQDN (see https://en.wikipedia.org/wiki/Hostname) and not contain an IP address which is the internal one of the proxy.

**Server (please complete the following information):**
 - ModSecurity version  with HAProxy Connector 
 - HAProxy Enteprise 2.4r1 LTS
 - OS (and distro): RHEL 8

**Rule Set (please complete the following information):**
All rules

**Comment by martinhsv** [comment]
Hello @alfonsoalongi ,

I cannot speak directly to HAProxy per se, but in general, in a standard ModSecurity v2 deployment with Apache HTTP Server ...

ModSecurity will populate the audit log's hostname from Apache's ```ServerName``` configuration directive **if** the ```UseCanonicalName On``` is set.

If ModSecurity does not have access to the name that way, it will use the value of the 'Host' header. If this value is name like "modsecurity.org" then that will be output. If the value of the Host header is a decimal-dot IP address, then that will be used.

**Comment by alfonsoalongi** [comment]
Hello @martinhsv,
thank you so much for your answer. I have reopened a ticket on HAProxy support and am awaiting a response from the engineering team. I'll let you know as soon as I have any updates on this.

**Comment by martinhsv** [comment]
Was there anything further on this?

Based on what has been presented so far, this should probably get closed from a ModSecurity perspective.
