### ISSUE TITLE
The mpm_itk module causes the dos configuration to fail

### ISSUE THREAD

**Issue by 7nightingale** [SpiderLabs/ModSecurity#2811]
**Describe the bug**
When I load both security2_module and mpm_itk，like:
    LoadModule mpm_itk_module modules/mpm_itk.so
    LoadModule security2_module modules/mod_security2.so

`<IfModule mpm_itk_module>
    LimitUIDRange 0 5000
    LimitGIDRange 0 5000
</IfModule>
<IfModule security2_module>
    SecAction  "id:900700,phase:1,nolog,pass,t:none,setvar:'tx.dos_burst_time_slice=60',setvar:'tx.dos_counter_threshold=10',setvar:'tx.dos_block_timeout=600'"
</IfModule>`

modsecurity's dos protection will fail，but When I comment out the mpm_itk module：
     #LoadModule mpm_itk_module modules/mpm_itk.so
dos protection takes effect again

Server (please complete the following information):

ModSecurity version (and connector): ModSec 2.9.6
WebServer: Apache 2.5.54

**Comment by martinhsv** [comment]
Hello @7nightingale ,

More information would be useful.

If by "DoS protection" you mean limiting the number of transactions that are allowed in a given time period (perhaps transactions per originating IP address), keep in mind that ModSecurity is the engine and any rules that accomplish a goal like that are separate.

So what exactly do mean by "modsecurity's dos protection will fail"? Do you mean that you are not seeing HTTP requests resulting in "deny" at a point that you expect? Or do you mean some more severe failure?

I've never used mpm-itk. Perhaps you could describe how you are using this and why.

Just from browsing the module's description, if your setup works as expected without mpm-itk, and is not having the same effect with it, it may be related to the variables you are using and how they are shared (or not). One useful resource here may be the ModSecurity debug log (at level 9), as it will show you quite a bit of information about what is happening with the variables you are using.
