### ISSUE TITLE
Sanitize directive in modsecurity v3

### ISSUE THREAD

**Issue by seema3377** [SpiderLabs/ModSecurity#2814]
Hi,
Nginx WAF modsecurity version 3 ( this is the current version supported for nginx open source) doesn't support the feature for sanitizing the sensitive information from WAF logs  https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#sanitiseRequestHeader) . Is there any alternative solution to either remove query parameters from being logged or mask these parameters in logs? What is the ETA for this feature to be available in v3? This feature unavailability is blocking us from using the WAF functionality in Nginx.
Thanks

**Comment by martinhsv** [comment]
Hello @seema3377 ,

One strategy is to remove the audit log "parts" that contain the sensitive information. You can do this on a global basis with ```SecAuditLogParts``` or selectively with ```ctl:auditLogParts```.

The disadvantage here, of course, is that some removed information may be important for analysis of the logs. But you always have the option to separately log the key pieces of information that you still want. For example, if you remove part "B" to avoid always logging query arguments, you could choose to separately log the content of the REQUEST_FILENAME variable.

**Comment by seema3377** [comment]
hi @martinhsv ,
I still see the query parameters being logged even after making the changes to SecAuditLogParts. Is there a way I can just strip of all the query parameters from the REQUEST_URI before logging ?  I'm trying to block the URLs where the REQUEST_URI doesn't match the value specified as per the regex pattern.

**Comment by martinhsv** [comment]
@seema3377 ,

You'll have to provide more detail. The template for opening an issue provides guidance on what you should provide.

For example: Where are you seeing the information logged? I gave you a way to avoid logging of the query arguments in the part 'B' section of the log. You say "still see the query parameters being logged", but you don't say where.

**Comment by seema3377** [comment]
@martinhsv I have the below config for nginx modsecurity. When I try to access my application say `curl http://<IP>/xyz?param1=value1` then I can see that the request gets blocked as per the SecRule configured below and the query parameter `param1=value1` gets logged to /dev/stdout along with the REQUEST_URI. I want to skip logging the query parameters in REQUEST_URI. 
  ```
enable-modsecurity: "true"
  modsecurity-snippet: |
    SecRuleEngine On
    SecRequestBodyAccess On
    SecAuditEngine On
    SecAuditLogRelevantStatus \"^(?:5|4(?!04))\"
    SecAuditLogParts AKHZ
    SecAuditLog /dev/stdout
    SecAuditLogFormat JSON
    SecRule REQUEST_URI \"!@rx ^(\/abc\/.*)(\?.*$|$)\" \"t:lowercase,id:105,deny,status:403,log,msg:\'requestUriNoRegexMatchBlock\'\"
    Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf 
```

**Comment by martinhsv** [comment]
Hello @seema3377 ,

So I guess you're talking about part 'H' output. In that case, one option would then be to remove part 'H' from the audit log parts. But in this particular case you likely have at least one or two better options.

Summarizing your regex, it looks like you basically want to match on anything that does **not** begin with the 5 character string '/abc/'.

In that case (and assuming I haven't misread the intent), perhaps the simplest option is to revisit your use of REQUEST_URI. Since it seems you only care about the filename, consider using REQUEST_FILENAME instead

Because the REQUEST_FILENAME variable does not include the query arguments, they will not be printed in part H audit log output by default.

**Comment by seema3377** [comment]
@martinhsv  Thanks for the above solution. It is working as expected. Thanks again!
