### ISSUE TITLE
Unable to use ctl:requestBodyLimit (syntax error)

### ISSUE THREAD

**Issue by AnnoyingTechnology** [SpiderLabs/ModSecurity#2819]
**Describe the bug**

When setting the requestBodyLimit from within a rule, the config parser throws an error.

The rule 
```
# increase the accepted body size for some base64 encoded data, provided in JSON which is not covered by the file body size rule
SecRule REQUEST_URI "@beginsWith /api/photos/upload/" \
    "phase:1,nolog,pass,id:2000900015,ctl:requestBodyLimit=6291456"
```

**Logs and dumps**

```
2022/10/17 10:27:17 [emerg] 743014#743014: "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/redacted.conf. Line: 62. Column: 63. Expecting an action, got:  ctl:requestBodyLimit=6291456" in /etc/nginx/conf.d/redacted.conf:7
```

**Expected behavior**

I would expect the configuration to be valid and accepted by ModSec. 
This ctl is described in modsecurity handbook at page 82 (paragraph _special actions_).

**Server (please complete the following information):**
 - ModSecurity version (and connector): 3.0.8 (1.0.3)
 - WebServer: nginx-1.18.0
 - OS (and distro): debian 11

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? owasp CRS
 - What is the version number? [e.g. 2018-08-11] 3.3.4

**Comment by airween** [comment]
Hi @AnnoyingTechnology,

unfortunately `ctl`'s `requestBodyLimit` is unsupported in libmodsecurity3. See the [manual](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#ctl):

> 6. **requestBodyLimit** - Not supported in ModSecurity v3

**Comment by AnnoyingTechnology** [comment]
Well, that sucks :) 

Any recommended way to circumvent that ? Appart from bumping this setting globally ?

**Comment by airween** [comment]
I have never used this, but it could be work:
```
http {
    ...
    server ... {
        ...
        location /api/photos/upload/ {
            modsecurity_rules '
                SecRequestBodyLimit 6291456
                SecRequestBodyNoFilesLimit 131072
            ';
        }
    }
}
```
Btw: you want to decrease the max length of request body? Or you want to modify the `SecRequestBodyNoFilesLimit`?

**Comment by AnnoyingTechnology** [comment]
Thanks for the tip, i saw this alternative on a sourceforge thread but wouldn't want to mess with nginx's own configuration. 

I want to **increase** the max `requestBodyLimit`, but modifying `SecRequestBodyNoFilesLimit` could probably yield the same results ?

I have documents encoded in base64 and uploaded within a JSON payload. 
So I need to up the limit for the URL that receives these payloads. 

edit: these get denied with a `400 Request body excluding files is bigger than the maximum expected.`  by modsec.

**Comment by airween** [comment]
> I want to **increase** the max `requestBodyLimit`, but modifying `SecRequestBodyNoFilesLimit` could probably yield the same results ?

No, those control different values. Please take a look to the documentation:

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#SecRequestBodyLimit
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#secrequestbodynofileslimit

> I have documents encoded in base64 and uploaded within a JSON payload. So I need to up the limit for the URL that receives these payloads.

Then you need to increase the `SecRequestBodyNoFilesLimit`.

**Comment by AnnoyingTechnology** [comment]
Alright, thanks.
