### ISSUE TITLE
how about rewrite ModSecurity3 with Rust

### ISSUE THREAD

**Issue by k4n5ha0** [SpiderLabs/ModSecurity#2820]
google's KataOS use rust with security reason
how about rewrite ModSecurity3 with Rust？

**Comment by martinhsv** [comment]
Hello @k4n5ha0 ,

That suggestion is what I would conservatively classify as "very large" with no reasonable prospect of doing so in the near future. For that reason, I will just go ahead and close this.

**Comment by trapeye** [comment]
I agree with this, rust is better
