### ISSUE TITLE
Error creating rule: Unknown variable: &MULTIPART_PART_HEADERS

### ISSUE THREAD

**Issue by UncleRaymondo** [SpiderLabs/ModSecurity#2821]
Hello,

Brand New Install of ModSec on Apache and on restarting Apache, I get the following error

AH00526: Syntax error on line 43 of /usr/share/modsecurity-crs/rules/REQUEST-922-MULTIPART-ATTACK.conf
apachectl[39236]: Error creating rule: Unknown variable: &MULTIPART_PART_HEADERS
apachectl[39233]: Action 'start' failed.
apachectl[39233]: The Apache error log may have more information.
systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE

Disabling this file from running seems to allow the service to restart.

Appreciate the assistance.

Cheers,
Ray

**Comment by martinhsv** [comment]
Hello @UncleRaymondo ,

MULTIPART_PART_HEADERS is a new collection. It is only present in the newest versions of the ModSecurity engine (v2.9.6 for Apache and v3.0.8 for nginx). If you are using an older version of ModSecurity you will indeed see the error that you have posted.

The coreruleset (CRS) team highlighted in some of their communications that their newest rules do have that dependency. See for example: https://coreruleset.org/20220919/crs-version-3-3-3-and-3-2-2-covering-several-cves/

**Comment by UncleRaymondo** [comment]
Thanks @martinhsv  - Looks like the Repositories have not been updated; I literally just installed this 20 minutes ago and it's deploying 2.9.5-1 on Ubuntu 22.04 LTS

Do you know if there's a DEB package for 2.9.6 yet?

Cheers,
Ray

**Comment by UncleRaymondo** [comment]
All good - found it on a German Debian Repository

http://ftp.de.debian.org/debian/pool/main/m/modsecurity-apache/libapache2-mod-security2_2.9.6-1_amd64.deb

Confirmed that Apache restarts now with the file :)

Cheers,
Ray

**Comment by airween** [comment]
> All good - found it on a German Debian Repository
> 
> http://ftp.de.debian.org/debian/pool/main/m/modsecurity-apache/libapache2-mod-security2_2.9.6-1_amd64.deb

I think this package is the mirrored copy of [Debian's Bookworm](https://packages.debian.org/search?suite=bookworm&searchon=names&keywords=libapache2-mod-security2) package.

I don't know Ubuntu 22.04 LTS which Apache version has, may be this would work.

But from [here](https://modsecurity.digitalwave.hu) you can download the mentioned system's own package (note, that this is a non-official repository).

Also you can find here CRS package (last release, of course).
