### ISSUE TITLE
SecAuditLogType HTTPS How to configure

### ISSUE THREAD

**Issue by floretisme** [SpiderLabs/ModSecurity#2824]
modsecurity.conf   What parameters need to be set for the file

**Comment by martinhsv** [comment]
Hello @zxp2mmy ,

For that ModSecurity v3 functionality, you need to:
- set ```SecAuditLogType HTTPS``` (as described in https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29-Configuration-Directives#secauditlogtype)
- and then set the address with SecAuditLogType parameter. E.g.: ```SecAuditLog http://xxx.xxx.xxx.xxx:port```
