### ISSUE TITLE
Now that 941120 FPs are fixed, tighten up rule 941120 targets

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2825]
```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|
REQUEST_HEADERS:User-Agent|REQUEST_HEADERS:Referer|ARGS_NAMES|ARGS|XML:/* 
"(?i)([\s\"'`;\/0-9\=\x0B\x09\x0C\x3B\x2C\x28\x3B]+on(?:pointer(?:(?:lea|mo)ve|
o(?:ver|ut)|cancel|enter|down|up)|s(?:(?:elec(?:tstar)?|ubmi)t|croll)|
c(?:l(?:ick|ose)|ontextmenu|hange)|mouse(?:o(?:ver|ut)|down|move|up)|
touch(?:cancel|start|move)|key(?:press|down|up)|(?:abor|inpu)t|
(?:erro|blu)r|res(?:ize|et)|dblclick|focus|load)[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=)" \
        "msg:'XSS Filter - Category 2: Event Handler Vector',\
        id:941120,\
        ...
```

_Originally posted by @franbuehler in https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/675#issuecomment-290208352_
      

Unless I'm mistaken, "!REQUEST_COOKIES:/__utm/" in this rule was added to deal with FPs on Google tracking cookies. I would suggest removing this from the target list, otherwise a hacker can bypass this rule by placing their XSS event code in a fake __utm cookie.

**Comment by wpkc** [comment]
Unless I'm mistaken, "!REQUEST_COOKIES:/__utm/" in this rule was added to deal with FPs on Google tracking cookies.  I would suggest removing this from the target list, otherwise a hacker can bypass this rule by placing their XSS event code in a fake __utm cookie.

**Comment by franbuehler** [comment]
Hi @wpkc, 
this is the wrong repository. It's for ModSecurity. 
Could you please close it here and open a new one in the OWASP Core Rule Set repo https://github.com/coreruleset/coreruleset?

**Comment by ghost** [comment]
Sorry @franbuehler.  I opened it in the right place.  Thanks.
