### ISSUE TITLE
initcol with some IPv6

### ISSUE THREAD

**Issue by willyamcts** [SpiderLabs/ModSecurity#2826]
## Describe the bug
Using DoS protection as an example, requests are counted according to source address using collections, whose KEY is the IP address itself. Using IPv6, I noticed that requests originating from some IPv6 addresses do not define collection as it should, IPs where the block starts with 1 or does not have another character before 1 (that is different from 0) do not create collections, so DoS protection, for example, is not applied.

I don't know if this is the correct place for the issue, maybe it's in sdbm, I don't know. If anyone can give me an idea.

Thankful.

## Logs and dumps
The blocks per score or violations there working, but other blocks that need collection not applicable. In the logs, everything seems to be normal:

```
[04/Nov/2022:12:16:25.564657 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][5] Rule 561d8ad25408: SecAction "phase:1,id:10,pass,nolog,noauditlog,initcol:ip=%{REMOTE_ADDR},initcol:global=geral"
[04/Nov/2022:12:16:25.564739 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][4] Transformation completed in 1 usec.
[04/Nov/2022:12:16:25.564743 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][4] Executing operator "unconditionalMatch" with param "" against REMOTE_ADDR.
[04/Nov/2022:12:16:25.564758 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][9] Target value: "fd00::1a54"
[04/Nov/2022:12:16:25.564760 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][4] Operator completed in 1 usec.
[04/Nov/2022:12:16:25.564783 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][9] Resolved macro %{remote_addr} to: fd00::1a54
[04/Nov/2022:12:16:25.564869 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][9] collection_retrieve_ex: collection_retrieve_ex: Retrieving collection (name "ip", filename "/var/run/modsecurity/daemon-ip")
[04/Nov/2022:12:16:25.564902 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][4] Creating collection (name "ip", key "fd00::1a54").
[04/Nov/2022:12:16:25.564905 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][4] Setting default timeout collection value 3600.
[04/Nov/2022:12:16:25.564908 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][9] Recorded original collection variable: ip.UPDATE_COUNTER = "0"
[04/Nov/2022:12:16:25.564910 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][4] Added collection "ip" to the list.
[04/Nov/2022:12:16:25.564936 --0300] [fd00::1/sid#561d8ad1a420][rid#561d8c78e9c0][/][9] collection_unpack: Read variable: name "__expire_KEY", value "1667577151".
````

## To Reproduce

1. See your data using sdbm in server, for example:
` watch -n1 modsec-sdbm-util -du <PATH>/daemon-ip.dir `

2. In client, use different IPs IPv6 and see create collection

3. Now, use the following IPs, see the "problem" happen:
- fd00::1:\*:\*:* / 64
- fd00::0100:\*:\*:* / 64
- fd00::0010:\*:\*:* / 64
- fd00::1xxx:\*:\*:*

Example for usage:
`fd00::1:0:0:255/64`
`fd00::0100:a:b:c/64`
`fd00::0010:a:b:c/64`
`fd00::1a:250/64`
`fd00::1a54:a234:c/64`

Iam using in client:
`curl -6 -ikL --noproxy '*' https://[fd00::1]`

## Expected behavior
That collections were created independent of the IPv6 address, following hexadecimal limitations

## Enviroment
**Server:**
 - ModSecurity version (and connector): 2.9.6
 - WebServer: Apache v2.4
 - OS (and distro): Debian

**Rule Set:**
 - Running any public or commercial rule set? CRS public
 - What is the version number? v3.3.4

**Comment by martinhsv** [comment]
Hello @willyamcts ,

I have never looked at the implementation details within sdbm but I'm not sure that checking for activity on .dir file is a good indicator of correct processing.

A better indicator is to look at actual results. If you set up something like the following:
```
SecAction "phase:1,id:502012,pass,log,auditlog,capture,initcol:ip=%{REMOTE_ADDR}"
SecAction "phase:1,log,pass,id:502013,setvar:'IP.var1=+1'"
SecAction "phase:1,log,pass,id:502014,msg:'var1=%{IP.var1}'"
```

... do you see the values accumulate correctly?

**Comment by willyamcts** [comment]
Hi @martinhsv ,

apparently it is something in my rules that is causing the problem. In my scenario, the collection is not even created when one of the IPv6 blocks starts with 0 (as explained above).

Result test requested:
`watch -n1 modsec-sdbm-util -du <PATH>/daemon-ip.dir`
```
Opening file: /var/lib/modsecurity/daemon-ip.dir
Database ready to be used.
Key: "fd00::1a:2:3:123", Value len: 209
 - ModSecurity variables:
                  __expire_KEY: 1669032264
                           KEY: fd00::1a:2:3:123
                       TIMEOUT: 3600
                         __key: fd00::1a:2:3:123
                        __name: ip
                   CREATE_TIME: 1669028664
                UPDATE_COUNTER: 12
                          var1: 12
              LAST_UPDATE_TIME: 1669028664
Key: "00::1a:2:3:123", Value len: 0
 - ModSecurity variables:
Key: "a:2:3:123", Value len: 0
 - ModSecurity variables:
Key: "", Value len: 0
 - ModSecurity variables:
``` 


As soon as I can, I'll take a better look at what it could be and I'll answer you here, thanks for your attention so far

**Comment by willyamcts** [comment]
Hi @martinhsv ,

apparently it is something in my rules that is causing the problem. In my scenario, the collection is not even created when one of the IPv6 blocks starts with 0 (as explained above).

Result test requested:
`watch -n1 modsec-sdbm-util -du <PATH>/daemon-ip.dir`
```
Database ready to be used.
Key: "fd00::1a:2:3:123", Value len: 209
 - ModSecurity variables:
                  __expire_KEY: 1669032264
                           KEY: fd00::1a:2:3:123
                       TIMEOUT: 3600
                         __key: fd00::1a:2:3:123
                        __name: ip
                   CREATE_TIME: 1669028664
                UPDATE_COUNTER: 12
                          var1: 12
              LAST_UPDATE_TIME: 1669028664
Key: "00::1a:2:3:123", Value len: 0
 - ModSecurity variables:
Key: "a:2:3:123", Value len: 0
 - ModSecurity variables:
Key: "", Value len: 0
 - ModSecurity variables:
``` 


As soon as I can, I'll take a better look at what it could be and I'll answer you here, thanks for your attention so far

**Comment by willyamcts** [comment]
Hi @martinhsv 

I already understand the problem, in my rules I have an exception for requests generated from the server itself forhimself, when the IP addresses of the server and the client are similar, a match happens in this rule.

For example:
Server IP: `fd00::2/64`
Client IP: `fd00::2a:3542:9999/64`

rule for test:
```
SecRule REMOTE_ADDR "%{SERVER_ADDR}" \
 "id:512025, phase:1, pass, log, auditlog, msg:'MATCHED', \
  setvar:'ip.var1=+1'"

SecRule REMOTE_ADDR "!@streq %{SERVER_ADDR}" \
 "id:512026, phase:1, pass, log, auditlog, msg:'NO MATCH: %{SERVER_ADDR} != %{REMOTE_ADDR}', \
  setvar:'ip.var1=+1'"


```


Access web page in client.
My audit_data log:
```
"audit_data":{
"messages":["Pattern match \"fd00\\\\:\\\\:2\" at REMOTE_ADDR. [file \"/etc/modsecurity/custom.conf\"] [line \"1\"] [id \"512025\"] [msg \"MATCHED\"]","Match of \"streq %{SERVER_ADDR}\" against \"REMOTE_ADDR\" required. 

[file \"/etc/modsecurity/custom.conf\"] [line \"5\"] [id \"512026\"] [msg \"NO MATCH: fd00::2 != fd00::2a:3542:9999\"]"],

"stopwatch":{"p1":267,"p2":3,"p3":1,"p4":0,"p5":108,"sr":97,"sw":97,"l":0,"gc":0},"producer":"ModSecurity for Apache/2.9.6 (http://www.modsecurity.org/)","server":"Apache","engine_mode":"ENABLED"
}
```

To confirme no match with address no similar: Change IP in my client for `fd00::1a:250`. 
My audit_data log:
```
"audit_data":{
"messages":["Match of \"streq %{SERVER_ADDR}\" against \"REMOTE_ADDR\" required. [file \"/etc/modsecurity/custom.conf\"] [line \"5\"] [id \"512026\"] [msg \"NO MATCH: fd00::2 != fd00::1a:250\"]"],

"stopwatch":{"p1":176,"p2":2,"p3":1,"p4":0,"p5":126,"sr":76,"sw":112,"l":0,"gc":0},"producer":"ModSecurity for Apache/2.9.6 (http://www.modsecurity.org/)","server":"Apache","engine_mode":"ENABLED"
}
```

I will test parsing with streq* to try bypass the problem.

**Comment by willyamcts** [comment]
My fault in using the operator, I will be closing this issue, I ask you to reopen it if you think it's relevant.

Using operator `@streq` work for IPv4 and IPv6 normally. In my rule i do not declare operator, then is `@rx`

Grateful for the attention.
