### ISSUE TITLE
geoip not working

### ISSUE THREAD

**Issue by czirakim** [SpiderLabs/ModSecurity#2829]
Hi ,everybody!
I am trying to enable geoip on my nginx webserver (nginx/1.18.0 (Ubuntu).
And here is what I get:

_Nov 11 12:33:25 server1 modsec_debug.log [/favicon.ico] [4] (Rule: 100) Executing operator "GeoLookup against REMOTE_ADDR.
Nov 11 12:33:25 server1 modsec_debug.log [/favicon.ico] [9] Target value: "188.24.16.62" (Variable: REMOTE_ADDR)
Nov 11 12:33:25 server1 modsec_debug.log [/favicon.ico] [4] Rule returned 0.
Nov 11 12:33:25 server1 modsec_debug.log [/favicon.ico] [9] Matched vars cleaned.
Nov 11 12:33:25 server1 modsec_debug.log [/favicon.ico] [4] (Rule: 111) Executing operator "Pm" with param "CN HK US" against GEO:COUNTRY_CODE.
Nov 11 12:33:25 server1 modsec_debug.log [/favicon.ico] [4] Rule returned 0.
Nov 11 12:33:25 server1 modsec_debug.log [/favicon.ico] [9] Matched vars cleaned._

I've placed my config in file (REQUEST-100-CUSTOM-RULES.conf) under the rules folder:

_SecGeoLookupDb /usr/local/nginx/conf/GeoLite2-Country.mmdb
SecRule REMOTE_ADDR "@geoLookup" "chain,id:100,phase:1,t:none,pass,log"
SecRule GEO:COUNTRY_CODE "@streq RO"

###  block China,Hong Kong US
SecRule GEO:COUNTRY_CODE "@pm CN HK US" \
    "id:111,\
    phase:1,\
    t:none,\
    log,\
    logdata:'%{MATCHED_VAR}',\
    deny,\
    msg:'Deny Client IP from %{MATCHED_VAR}',\
    ver:'OWASP_CRS/3.3.4'"_

I 've cloned Modsecurity and piled it from this version.

My ./configure looks like this:
_ModSecurity - v3.0.8-12-gde01b027 for Linux
 
 Mandatory dependencies
   + libInjection                                  ....v3.9.2-46-gbfba51f
   + SecLang tests                                 ....a3d4405
 
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (GeoIP) v1.6.12
         -lGeoIP, -I/usr/include/
   + LibCURL                                       ....found v7.68.0 
      -lcurl,  -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL
   + YAJL                                          ....found v2.1.0
      -lyajl, -DWITH_YAJL -I/usr/include/yajl
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.10
      -lxml2, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....not found
   + LUA                                           ....found v503
      -llua5.3 -L/usr/lib/x86_64-linux-gnu/, -DWITH_LUA -DWITH_LUA_5_3 -I/usr/include/lua5.3
   + PCRE2                                          ....not found
 
 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled_

Any help is appreciated.

thanks!

**Comment by czirakim** [comment]
I think I'll answer myself as it seems I've fixed it , and probably would be a good idea to share it in case anybody else has same issues.

It seems the issues were regarding the geoip libraries.
I have removed/uninstalled  these:
_ibgeoip-dev/focal,now 1.6.12-6build1 amd64 [installed]
libgeoip1/focal,now 1.6.12-6build1 amd64 [installed]_

And you have to have these installed:
_libmaxminddb-dev/focal,now 1.7.1-0+maxmind1
libmaxminddb0/focal,now 1.7.1-0+maxmind1_

Next, I have recompiled modsecurity , and at ./configure step , you should have this:
 _+ GeoIP/MaxMind                                 ....found 
      * (MaxMind) v
         /usr/lib/x86_64-linux-gnu//libmaxminddb.so, /usr/include/x86_64-linux-gnu/, -DWITH_MAXMIND -I/usr/include/x86_64-linux-gnu/_

And that was it for me. It worked after that.
Basiacally you need to use maxmind libraries, nad not the geoip ones.

Hope it helps somebody!

**Comment by martinhsv** [comment]
Hello @czirakim ,

Just to clarify, do you mean that you had libgeoip packages installed **in** **addition** to the libmaxminddb ones? Or **instead** of?
