### ISSUE TITLE
Ubuntu/NGINX: there are no modsec-shared-collections anywhere, not being created, persistent variables does not persist

### ISSUE THREAD

**Issue by feanorknd** [SpiderLabs/ModSecurity#2835]
Problem is that: cannot make use of persistent variables, and there is not modsec-shared-collections being created anywhere...

SO: Ubuntu 20.04

Libmodsecurity v.3.0.8 compiled with --with-lmdb

Nginx connector being used.

`ldd libmodsecurity.so.3.0.8

        linux-vdso.so.1 (0x00007ffdae1fc000)
        libcurl.so.4 => /lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f8438671000)
        libGeoIP.so.1 => /lib/x86_64-linux-gnu/libGeoIP.so.1 (0x00007f8438633000)
        libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f843847b000)
        liblmdb.so.0 => /lib/x86_64-linux-gnu/liblmdb.so.0 (0x00007f8438463000)
        liblua5.3.so.0 => /lib/x86_64-linux-gnu/liblua5.3.so.0 (0x00007f8438428000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f84383b4000)
        libmaxminddb.so.0 => /lib/x86_64-linux-gnu/libmaxminddb.so.0 (0x00007f84383ad000)
        libyajl.so.2 => /lib/x86_64-linux-gnu/libyajl.so.2 (0x00007f84383a1000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f84381bf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8437fcd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8438978000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8437fb2000)
        libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f8437f87000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f8437f65000)
        librtmp.so.1 => /lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f8437f45000)
        libssh.so.4 => /lib/x86_64-linux-gnu/libssh.so.4 (0x00007f8437ed7000)
        libpsl.so.5 => /lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f8437ec4000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f8437e31000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f8437b59000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f8437b0c000)
        libldap_r-2.4.so.2 => /lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f8437ab6000)
        liblber-2.4.so.2 => /lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f8437aa5000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f8437a97000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8437a7b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8437a56000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8437a50000)
        libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f843786a000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f8437841000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f84376f2000)
        libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f843756e000)
        libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f8437398000)
        libhogweed.so.5 => /lib/x86_64-linux-gnu/libhogweed.so.5 (0x00007f8437361000)
        libnettle.so.7 => /lib/x86_64-linux-gnu/libnettle.so.7 (0x00007f8437327000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f84372a3000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f84371c4000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f8437193000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f843718c000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f843717d000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f8437161000)
        libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f8437144000)
        libgssapi.so.3 => /lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f84370fd000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f84370da000)
        libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f8435619000)
        libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f84354e3000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f84354cd000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f84354c4000)
        libheimntlm.so.0 => /lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f84354b8000)
        libkrb5.so.26 => /lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f8435425000)
        libasn1.so.8 => /lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f843537e000)
        libhcrypto.so.4 => /lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f8435346000)
        libroken.so.18 => /lib/x86_64-linux-gnu/libroken.so.18 (0x00007f843532b000)
        libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007f843531f000)
        libwind.so.0 => /lib/x86_64-linux-gnu/libwind.so.0 (0x00007f84352f5000)
        libheimbase.so.1 => /lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f84352e3000)
        libhx509.so.5 => /lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f8435295000)
        libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f843516c000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f843512f000)`
       
 And nginx connector being used:
 
 `ldd ngx_http_modsecurity_module.so
 
        linux-vdso.so.1 (0x00007fffdbb0d000)
        libmodsecurity.so.3 => /usr/local/modsecurity/lib/libmodsecurity.so.3 (0x00007fbf4512d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbf44f31000)
        libcurl.so.4 => /lib/x86_64-linux-gnu/libcurl.so.4 (0x00007fbf44e9f000)
        libGeoIP.so.1 => /lib/x86_64-linux-gnu/libGeoIP.so.1 (0x00007fbf44e61000)
        libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fbf44ca9000)
        liblmdb.so.0 => /lib/x86_64-linux-gnu/liblmdb.so.0 (0x00007fbf44c8f000)
        liblua5.3.so.0 => /lib/x86_64-linux-gnu/liblua5.3.so.0 (0x00007fbf44c54000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fbf44be2000)
        libmaxminddb.so.0 => /lib/x86_64-linux-gnu/libmaxminddb.so.0 (0x00007fbf44bdb000)
        libyajl.so.2 => /lib/x86_64-linux-gnu/libyajl.so.2 (0x00007fbf44bcf000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbf449ed000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbf4539f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbf449d0000)
        libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007fbf449a7000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007fbf44985000)
        librtmp.so.1 => /lib/x86_64-linux-gnu/librtmp.so.1 (0x00007fbf44965000)
        libssh.so.4 => /lib/x86_64-linux-gnu/libssh.so.4 (0x00007fbf448f7000)
        libpsl.so.5 => /lib/x86_64-linux-gnu/libpsl.so.5 (0x00007fbf448e4000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fbf4484f000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fbf44579000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fbf4452c000)
        libldap_r-2.4.so.2 => /lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007fbf444d6000)
        liblber-2.4.so.2 => /lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007fbf444c5000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007fbf444b7000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbf44499000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbf44476000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbf44470000)
        libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007fbf4428a000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fbf44261000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbf44112000)
        libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007fbf43f8e000)
        libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fbf43db8000)
        libhogweed.so.5 => /lib/x86_64-linux-gnu/libhogweed.so.5 (0x00007fbf43d81000)
        libnettle.so.7 => /lib/x86_64-linux-gnu/libnettle.so.7 (0x00007fbf43d47000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fbf43cc3000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fbf43be4000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fbf43bb3000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fbf43bac000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fbf43b9d000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fbf43b81000)
        libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fbf43b64000)
        libgssapi.so.3 => /lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007fbf43b1d000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007fbf43afa000)
        libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007fbf42039000)
        libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fbf41f03000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fbf41eed000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fbf41ee4000)
        libheimntlm.so.0 => /lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007fbf41ed8000)
        libkrb5.so.26 => /lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007fbf41e45000)
        libasn1.so.8 => /lib/x86_64-linux-gnu/libasn1.so.8 (0x00007fbf41d9e000)
        libhcrypto.so.4 => /lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007fbf41d66000)
        libroken.so.18 => /lib/x86_64-linux-gnu/libroken.so.18 (0x00007fbf41d4b000)
        libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007fbf41d3f000)
        libwind.so.0 => /lib/x86_64-linux-gnu/libwind.so.0 (0x00007fbf41d15000)
        libheimbase.so.1 => /lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007fbf41d03000)
        libhx509.so.5 => /lib/x86_64-linux-gnu/libhx509.so.5 (0x00007fbf41cb5000)
        libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fbf41b8c000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fbf41b4f000)`
        
Testing, for example, these rules...

> SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "id:'5000',phase:1,t:none,initcol:ip=%{remote_addr},log,auditlog,pass"
> SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "id:'5001',phase:2,t:none,setvar:ip.auth_attempt=+1,setvar:'tx.testvar=hereiam',log,auditlog,pass"
> SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "id:'5002',phase:2,t:none,logdata:'%{ip.auth_attempt} and tx var: %{tx.testvar}',log,auditlog,pass"
> SecRule IP:auth_attempt "@eq 1" "id:'5005',phase:2,t:none,log,msg:'%{MATCHED_VAR_NAME}',auditlog, logdata:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',drop,chain"
>     SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "t:none"
> SecRule IP.auth_attempt "@eq 1" "id:'5006',phase:2,t:none,log,msg:'%{MATCHED_VAR_NAME}',auditlog, logdata:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',drop,chain"
>     SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "t:none"
> SecRule IP:AUTH_ATTEMPT "@eq 1" "id:'5007',phase:2,t:none,log,msg:'%{MATCHED_VAR_NAME}',auditlog, logdata:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',drop,chain"
>     SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "t:none"
> SecRule IP.AUTH_ATTEMPT "@eq 1" "id:'5008',phase:2,t:none,log,msg:'%{MATCHED_VAR_NAME}',auditlog, logdata:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',drop,chain"
>     SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "t:none"
> SecRule ip:auth_attempt "@eq 1" "id:'5009',phase:2,t:none,log,msg:'%{MATCHED_VAR_NAME}',auditlog, logdata:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',drop,chain"
>     SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "t:none"
> SecRule ip.auth_attempt "@eq 1" "id:'5010',phase:2,t:none,log,msg:'%{MATCHED_VAR_NAME}',auditlog, logdata:'%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',drop,chain"
>     SecRule REMOTE_ADDR "@ipMatch 81.37.87.169/24" "t:none"

I do create a 'tx.testvar' with a value just to test values at auditlog... Rules are only affecting to my IP...

Results at auditlog:

> 
> ---8WmpCzQC---A--
> [22/Nov/2022:18:38:19 +0100] 166913869973.228975 81.37.87.169 46618 SERVERIP 443
> ---8WmpCzQC---B--
> GET /ip HTTP/2.0
> host: DOMAIN
> user-agent: curl/7.81.0
> accept: */*
> 
> 
> ---8WmpCzQC---H--
> ModSecurity: Warning. Matched "Operator `IpMatch' with parameter `81.37.87.169/24' against variable `REMOTE_ADDR' (Value: `81.37.87.169' ) [file "/etc/modsecurity/custom-rules/ratelimit.conf"] [line "2"] [id "5000"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "157.90.252.60"] [uri "/ip"] [unique_id "166913869973.228975"] [ref "v0,12"]
> ModSecurity: Warning. Matched "Operator `IpMatch' with parameter `81.37.87.169/24' against variable `REMOTE_ADDR' (Value: `81.37.87.169' ) [file "/etc/modsecurity/custom-rules/ratelimit.conf"] [line "4"] [id "5001"] [rev ""] [msg ""] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "157.90.252.60"] [uri "/ip"] [unique_id "166913869973.228975"] [ref "v0,12"]
> ModSecurity: Warning. Matched "Operator `IpMatch' with parameter `81.37.87.169/24' against variable `REMOTE_ADDR' (Value: `81.37.87.169' ) [file "/etc/modsecurity/custom-rules/ratelimit.conf"] [line "6"] [id "5002"] [rev ""] [msg ""] [data " and tx var: hereiam"] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "157.90.252.60"] [uri "/ip"] [unique_id "166913869973.228975"] [ref "v0,12"]
> 
> ---8WmpCzQC---Z--

You may see tx.testvar value is being logged, but it is NULL for persistent variable....

Of course, the drop rules does not affect because ip.auth_attempt seems to contain nothing at all...

Checked debug logs... lines are:

> [166913892959.923440] [/ip] [4] (Rule: 5001) Executing operator "IpMatch" with param "81.37.87.169/24" against REMOTE_ADDR.
> [166913892959.923440] [/ip] [9] Target value: "81.37.87.169" (Variable: REMOTE_ADDR)
> [166913892959.923440] [/ip] [9] Matched vars updated.
> [166913892959.923440] [/ip] [4] Running [independent] (non-disruptive) action: setvar
> [166913892959.923440] [/ip] [8] Saving variable: IP:auth_attempt with value: 1
> [166913892959.923440] [/ip] [4] Running [independent] (non-disruptive) action: setvar
> [166913892959.923440] [/ip] [8] Saving variable: TX:testvar with value: hereiam
> [166913892959.923440] [/ip] [4] Rule returned 1.
> [166913892959.923440] [/ip] [9] Running action: log
> [166913892959.923440] [/ip] [9] Saving transaction to logs
> [166913892959.923440] [/ip] [9] Running action: auditlog
> [166913892959.923440] [/ip] [9] Saving transaction to logs
> [166913892959.923440] [/ip] [9] Running action: log
> [166913892959.923440] [/ip] [9] Saving transaction to logs
> [166913892959.923440] [/ip] [9] Running action: auditlog
> [166913892959.923440] [/ip] [9] Saving transaction to logs
> [166913892959.923440] [/ip] [4] Running (disruptive)     action: pass.
> [166913892959.923440] [/ip] [8] Running action pass
> [166913892959.923440] [/ip] [4] (Rule: 5002) Executing operator "IpMatch" with param "81.37.87.169/24" against REMOTE_ADDR.
> [166913892959.923440] [/ip] [9] Target value: "81.37.87.169" (Variable: REMOTE_ADDR)
> [166913892959.923440] [/ip] [9] Matched vars updated.
> [166913892959.923440] [/ip] [4] Rule returned 1.
> [166913892959.923440] [/ip] [9] Running action: log
> [166913892959.923440] [/ip] [9] Saving transaction to logs
> [166913892959.923440] [/ip] [9] Running action: auditlog
> [166913892959.923440] [/ip] [9] Saving transaction to logs
> [166913892959.923440] [/ip] [9] Running action: log
> [166913892959.923440] [/ip] [9] Saving transaction to logs
> [166913892959.923440] [/ip] [9] Running action: auditlog
> [166913892959.923440] [/ip] [9] Saving transaction to logs
> [166913892959.923440] [/ip] [4] Running (disruptive)     action: pass.
> [166913892959.923440] [/ip] [8] Running action pass
> [166913892959.923440] [/ip] [4] (Rule: 5005) Executing operator "Eq" with param "1" against IP:auth_attempt.
> [166913892959.923440] [/ip] [4] Rule returned 0.
> [166913892959.923440] [/ip] [9] Matched vars cleaned.
> [166913892959.923440] [/ip] [4] (Rule: 5006) Executing operator "Eq" with param "1" against IP:auth_attempt.
> [166913892959.923440] [/ip] [4] Rule returned 0.
> [166913892959.923440] [/ip] [9] Matched vars cleaned.
> [166913892959.923440] [/ip] [4] (Rule: 5007) Executing operator "Eq" with param "1" against IP:AUTH_ATTEMPT.
> [166913892959.923440] [/ip] [4] Rule returned 0.
> [166913892959.923440] [/ip] [9] Matched vars cleaned.
> [166913892959.923440] [/ip] [4] (Rule: 5008) Executing operator "Eq" with param "1" against IP:AUTH_ATTEMPT.
> [166913892959.923440] [/ip] [4] Rule returned 0.
> [166913892959.923440] [/ip] [9] Matched vars cleaned.
> [166913892959.923440] [/ip] [4] (Rule: 5009) Executing operator "Eq" with param "1" against IP:auth_attempt.
> [166913892959.923440] [/ip] [4] Rule returned 0.
> [166913892959.923440] [/ip] [9] Matched vars cleaned.
> [166913892959.923440] [/ip] [4] (Rule: 5010) Executing operator "Eq" with param "1" against IP:auth_attempt.
> [166913892959.923440] [/ip] [4] Rule returned 0.
> [166913892959.923440] [/ip] [9] Matched vars cleaned.

And... not modsec-shared-collections anywhere...

`SecTmpDir /var/modsecurity
SecDataDir /var/modsecurity`

Given 777 permissions, also tested with /tmp.... no new files everywhere when restarting nginx.

Could someone help? I cannot find where is my mistake.

**Comment by martinhsv** [comment]
Hello @feanorknd ,

I suspect what you are encountering is a side effect of some corrections earlier this year to how the LMDB API is used within ModSecurity.

The nginx worker thread is attempting to write the file and what its working directory is what matters -- and the default may not be (ordinarily) writeable.

Probably the simplest way to address this is to use the nginx configuration item 'working_directory' to specify the location. E.g.
```
working_directory /tmp;
```

Let me know if that resolves your issue.

(You can read a bit more of the background on this at #2755 . )

**Comment by feanorknd** [comment]
Hello @martinhsv

you were completely certain...

That  'working_directory' in my nginx.conf fixes my issue and now I have that modsec-shared-collections to work... collection variables seems to be working now.

Everything is fine.

THANKS so much, you're all awesome.
