### ISSUE TITLE
Persistent IP collection is always using hash on user-agent when storing keys at database

### ISSUE THREAD

**Issue by feanorknd** [SpiderLabs/ModSecurity#2837]
Hi there...

Using libmodsecurity v3 latest 3.0.8.

I can start a new collection by:
initcol:ip=%{remote_addr}

but have noticed there is a hash just after the IP in the lmdb keys being stored...

> key: 0x7f52e789122c 85.58.150.151_8fa902c8b3f6ce55c295f79d74a9caf267c02599::::hits_count, data: 0x7f52e7891270 2
> key: 0x7f52e78912d0 85.58.150.151_c0bf39a203266f322cafe8b44bb1a036eec5a58d::::hits_count, data: 0x7f52e7891314 598

I have noticed, this hash from "85.58.150.151_c0bf39a203266f322cafe8b44bb1a036eec5a58d", is just the user-agent being used, so it is just "IP_(hash of user-agent)" for the keys.

I think it is a bit strange, since I only have initialized the collection with the variable '%{remote_addr}'.

Whats the main problem here? Common xploiters do usually modify their user-agents on several multiple requests, so this IP collection is almost useless: cannot track correctly the IP of the "attacker".

Last night, had almost 60-70 keys for the same IP in the lmdb database... couldn't apply my rules for the offending IP, as the counters did not trigger limits.

I guess this is not the ideal situation. If I were interested in attaching user-agent to the IP in the collection keys, I would have done it via 'initcol:ip='. For me, user-agent is not important here since I only want to have a look at IPs... that's my collection for.

So, could this suppose a bug or is it something fixable?

Thanks so much for your work and efforts.

**Comment by feanorknd** [comment]
Even noticed I could init collection by using:
initcol:ip="fixed"

and it doesn't really matter... it is going to perform exactly the same:
keys = IP_<hash over user-agent>

**Comment by martinhsv** [comment]
Hi @feanorknd ,

It shouldn't be the ModSecurity engine itself that is doing that.

My assumption is that the rule you are using to do the initcol is explicitly doing that. For example, if you happen to be using coreruleset (CRS), then I believe they have a rule that does exactly that sort of concatenation during initcol.

Doing that concatenation has advantages for some use cases, but potential disadvantages for others. If you're curious to inquire further, you may wish to raise this with coreruleset (the CRS rules are managed by a separate group).

**Comment by feanorknd** [comment]
Hi @martinhsv,

you were certain.... I have been using my own rules, but have checked and CRS initalization is creating the collection on its own, although not being used later because I do not include their DOS controller.....

> root@ispconfig /etc/modsecurity/owasp/rules # grep initcol *
> REQUEST-901-INITIALIZATION.conf:    initcol:global=global,\
> REQUEST-901-INITIALIZATION.conf:    initcol:ip=%{remote_addr}_%{tx.ua_hash},\

Once again, it's my fault to open an issue for this... didn't check everything I guess.

Thanks so much for your words.
