### ISSUE TITLE
When will modsecurity support caddy web server？

### ISSUE THREAD

**Issue by aipach** [SpiderLabs/ModSecurity#2838]
The connector for modsecurity-caddy is currently missing, caddy is a web server developed by golang

**Comment by airween** [comment]
If you want to use Caddy anyway: [coraza](https://github.com/corazawaf/coraza) has connector for [caddy](https://github.com/corazawaf/coraza-caddy).

**Comment by martinhsv** [comment]
Hello @aipach ,

With Caddy only having 0.1% market share (according to w3techs) this has not been regarded as a priority item by staff employed by ModSecurity's sponsor.

That said, since ModSecurity is an open source project, Caddy enthusiasts can initiate work on such a connector if they choose.
