### ISSUE TITLE
Warning when compiling about discarded 

### ISSUE THREAD

**Issue by Steve8291** [SpiderLabs/ModSecurity#2843]
This is a compile warning that I think would be easy to fix.
The output from my compiler is:
```
configure.ac:18: installing 'build/compile'
configure.ac:17: installing 'build/missing'
alp2/Makefile.am: installing 'build/depcomp'
mod_security2.c: In function ‘version’:
mod_security2.c:125:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 125 |     pcre_loaded_vrs = pcre_version();
     |                     ^
```

**To Reproduce**
```
cd ModSecurity/
./autogen.sh
./configure --disable-mlogc --enable-pcre-jit --enable-lua-cache
make clean
make
```

**Server (please complete the following information):**
 - ModSecurity version (and connector):
 - ModSecurity: 2.9.6
	ModSecurity: APR compiled version="1.6.5"; loaded version="1.6.5"
	ModSecurity: PCRE compiled version="8.39 "; loaded version="8.39 2016-06-14"
	ModSecurity: LUA compiled version="Lua 5.2"; installed version="Lua 5.2.4"
	ModSecurity: YAJL compiled version="2.1.0"
	ModSecurity: LIBXML compiled version="2.9.10"
 - WebServer: `Apache 2.4.41`
 - OS (and distro): `Ubuntu 20.04.5 LTS (focal)`

**Additional context**
Error occurs on line 125 of `mod_security2.c`
I think it could be fixed easily by changing line 109 of that same file to a `const` char pointer:
`    const char *pcre_vrs = NULL;`
I don't have an easy way of testing this so I didn't want to submit a pull request.

**Comment by martinhsv** [comment]
Resolved via https://github.com/SpiderLabs/ModSecurity/commit/583b465fdb8bfbaf7fbb85afdeb3ad58e6e69a7b

Thx.
