### ISSUE TITLE
SecAuditLogType:HTTPS

### ISSUE THREAD

**Issue by floretisme** [SpiderLabs/ModSecurity#2856]
![image](https://user-images.githubusercontent.com/37258275/210336073-323892e7-e494-41a1-89ba-5da71d682cc9.png)
I have a question
Why use synchronization instead of asynchrony?
Why not use  curl_multi_init？

**Comment by martinhsv** [comment]
Hello @zxp2mmy ,

If you think there is a problem or deficiency in the code, please fully explain (there are issue templates that can help guide you in describing the problem). If you want to propose a change, describe why it is better (you can even create a pull request to that effect).

I don't have the background for "why"; I didn't write that code so I don't have any more background than what is available to everyone else in github (it was written 7 years ago, incidentally).

Also, it looks (?) like this issue creation may be talking about the same issue as the one you created a couple of weeks ago ( https://github.com/SpiderLabs/ModSecurity/issues/2847 ) . Is that the case? If so, please don't create duplicates. I left that other issue open to allow you opportunity to more fully elucidate your concern.
