### ISSUE TITLE
Attack packets cause high cpu usage

### ISSUE THREAD

**Issue by swzaaaaaaa** [SpiderLabs/ModSecurity#2859]
[redacted]

**Comment by martinhsv** [comment]
Hello @swzaaaaaaa ,

At least in some cases, a report like that may warrant treatment in a more secure and confidential manner.

For issues like that, using the more confidential channel mentioned at https://github.com/SpiderLabs/ModSecurity#security-issue is preferable.

Please contact me at the aforementioned email address.

Thanks.
