### ISSUE TITLE
SecRequestBodyNoFilesLimit Not Working in Nginx Config

### ISSUE THREAD

**Issue by peppies** [SpiderLabs/ModSecurity#2863]
ModSecurity 3.0.8
ModSecurity-nginx v1.0.3
Nginx/1.23.2
CRS 4.0.0-rc1
Ubuntu 22.04

Greetings,

I am trying to deal with false positives and ran into an issue where users submit heavily formatted listings, but ModSecurity flagged them because the Request Body (Without Files Upload) was too large. It is not unusual for some of the listings to be over 200KB in size. I asked about it here: https://security.stackexchange.com/questions/267536/modsecurity-how-to-increase-secrequestbodylimit-for-specific-website-request-ur/267585#267585 , and thought I had a solution by writing a Nginx rule exclusion in the Nginx Virtual Host file for my website, but today I'm noticing that this rule appears to be ignored.

Users submit their full listing at the url "/add/submit.php", so I wanted to make a ModSecurity exception just for that one URL, not for the full website.

Here is what I have in my Nginx config:

```
server {
    server_name www.*****.com;
   ....

    location /add/submit.php {
      modsecurity_rules 'SecRequestBodyNoFilesLimit 300000';
    }

    ....
```

Here is the ModSecurity audit log details:

```
---27vkMc5I---A--
[18/Jan/2023:23:02:05 +0000] 167408292596.435482 ***.***.***.*** 50358 ***.***.***.*** 443
---27vkMc5I---B--
POST /add/submit.php HTTP/2.0
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
sec-fetch-site: same-origin
content-type: application/x-www-form-urlencoded
origin: https://www.******.com
sec-ch-ua-mobile: ?0
upgrade-insecure-requests: 1
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
cache-control: max-age=0
sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
sec-fetch-user: ?1
sec-ch-ua-platform: "Windows"
referer: https://www.*****.com/
content-length: 217490
host: www.*****.com
sec-fetch-mode: navigate
sec-fetch-dest: document
accept-encoding: gzip, deflate, br
cookie: *****

---27vkMc5I---F--
HTTP/2.0 302
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: public
Location: /item/*********/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-XSS-Protection: 1; mode=block
Pragma: no-cache
Connection: close
Content-Type: text/html; charset=UTF-8
Date: Wed, 18 Jan 2023 23:02:06 GMT
Server: nginx
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Referrer-Policy: strict-origin
Permissions-Policy: geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()

---27vkMc5I---H--
ModSecurity: Warning. Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/etc/nginx/modsec/modsecurity.conf"] [line "75"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "Request body excluding files is bigger than the maximum expected."] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "***.***.***.***"] [uri "/add/submit.php"] [unique_id "167408292596.435482"] [ref "v0,1"]
```

According to the log, it looks like the POST request content length is "217490", which should be allowed if SecRequestBodyNoFilesLimit is set to 300000.

I was wondering if someone could take a look at this and let me know if I'm writing the rule wrong or if this is some kind of bug related to Nginx and ModSecurity.

Thanks

**Comment by martinhsv** [comment]
Hello @peppies ,

There are at least a couple of possibilities.

One is that the configuration setting that you have supplied is being overridden by a different configuration setting elsewhere in your setup. You could try removing the one that you have specified above and see if there is any change.

Another possibility (although probably less likely) is that the request body is bigger than what is indicated by the request header. One way to check this is with a rule like:
```
SecRule REQUEST_BODY "@rx .*" "id:9001,phase:2,t:length,log,logdata:'request body size =%{MATCHED_VAR}'"
```

**Comment by martinhsv** [comment]
Hello @peppies ,

Just FYI that a recent change has been made to v3/master ( at 3311dda0e55d8c6e630a78fd83337d9d60a64f8a ), such that, when the limit is exceeded, the associated debug log message will output the value of the limit that was used for the check. This might help you identify if it's the first possibility that I mentioned in the previous comment.
