### ISSUE TITLE
https://www.modsecurity.org/ website is down

### ISSUE THREAD

**Issue by iosifnicolae2** [SpiderLabs/ModSecurity#2871]
**Describe the bug**

The https://www.modsecurity.org/ website is down.
<img width="868" alt="image" src="https://user-images.githubusercontent.com/7108834/215456386-13cce03a-736b-4897-ad42-b6ff5c51d45a.png">

**Comment by martinhsv** [comment]
The IT issue involved here was resolved some days ago.

Thank for the notification about this, @iosifnicolae2
