### ISSUE TITLE
SecDefaultAction is changed in 3.X

### ISSUE THREAD

**Issue by tomsommer** [SpiderLabs/ModSecurity#2878]
Using modsec 3.0.9 (from master) and nginx

```
location / {
modsecurity_rules '
  SecRuleEngine on
  SecDefaultAction "phase:1,status:406,deny"
  SecDefaultAction "phase:2,status:406,deny"
  SecRule REQUEST_URI "@contains foobar" "id:4"
';
}

```
`SecDefaultAction` does nothing here, it is completely ignored and `status:406` and `deny` needs to be added to `SecRule` directly

```

[167749170712.959422] [/?foobar] [4] Adding request argument (GET): name "foobar", value ""
[167749170712.959422] [/?foobar] [4] Starting phase REQUEST_HEADERS.  (SecRules 1)
[167749170712.959422] [/?foobar] [9] This phase consists of 1 rule(s).
[167749170712.959422] [/?foobar] [4] (Rule: 4) Executing operator "Contains" with param "foobar" against REQUEST_URI.
[167749170712.959422] [/?foobar] [9] Target value: "/?foobar" (Variable: REQUEST_URI)
[167749170712.959422] [/?foobar] [9] Matched vars updated.
[167749170712.959422] [/?foobar] [4] Rule returned 1.
[167749170712.959422] [/?foobar] [4] Starting phase REQUEST_BODY. (SecRules 2)
[167749170712.959422] [/?foobar] [9] This phase consists of 0 rule(s).
[167749170712.959422] [/?foobar] [4] Starting phase RESPONSE_HEADERS. (SecRules 3)
[167749170712.959422] [/?foobar] [9] This phase consists of 0 rule(s).
[167749170712.959422] [/?foobar] [4] Starting phase LOGGING. (SecRules 5)
[167749170712.959422] [/?foobar] [9] This phase consists of 0 rule(s).
[167749170712.959422] [/?foobar] [8] Checking if this request is suitable to be saved as an audit log.
[167749170712.959422] [/?foobar] [8] Checking if this request is relevant to be part of the audit logs.
[167749170712.959422] [/?foobar] [5] Saving this request as part of the audit logs.
[167749170712.959422] [/?foobar] [8] Request was relevant to be saved. Parts: 4430

```

the rule triggers, but stuff from `SecDefaultAction` is not applied.

**Comment by airween** [comment]
Could you try to add a `block` action to the rule?

I mean:

```
  ...
  SecRule REQUEST_URI "@contains foobar" "id:4,phase:1,block"
  ...
```

(`phase` is just a bit more precise setting :))

**Comment by tomsommer** [comment]
That works and it also applied the `status` from `SecDefaultAction` 
```
  SecRule REQUEST_URI "@contains foobar" "id:4,phase:1,deny"
```
also works

**Comment by tomsommer** [comment]
```
  SecRule REQUEST_URI "@contains foobar" "id:4,phase:1"
```
does not work

**Comment by airween** [comment]
> That works and it also applied the `status` from `SecDefaultAction`

yes.

As I know, `block` needs to "inherit" the `SecDefaultAction` behavior:

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#block

> ```
>   SecRule REQUEST_URI "@contains foobar" "id:4,phase:1,deny"
> ```
> 
> also works

but this is not the same.

> ```
> SecRule REQUEST_URI "@contains foobar" "id:4,phase:1"
>```
>
> does not work

yes, because there isn't any disruptive action. `block` needs, I guess. (And `phase` does not solve your issue, just clarifies the phase.)

**Comment by tomsommer** [comment]
This is a clear deviation from ModSec 2 though, where `block` is not required for `SecDefaultAction` to be applied

**Comment by airween** [comment]
May be I'm wrong, I haven't used it yet without `block` (none of both versions).

May be you are right, and that's the normal behavior. But please check the [documentation](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#secdefaultaction), especially the bold text:

**_Warning : SecDefaultAction is not inherited across configuration contexts._**

Unfortunately the blog post is unavailable. I don't know is that relevant or not.

**Comment by tomsommer** [comment]
It's not about configuration contexts though, it's about the action is not applied unless `block` is used, it should be noted in the 3.X documentation for `SecDefaultAction`, as it's not even mentioned there currently. A bit counter-intuitive that everything from `SecDefaultAction` is inherited except the action, unless `block` is used.

Thank you for the hint to fixing this :)

**Comment by airween** [comment]
> It's not about configuration contexts though

you showed your config, which starts a `location / {`, so I thought that's a `server` context. May be that's the cause of the issue...

> it's about the action is not applied unless `block` is used

you should try it - put the rule (and the config) outside of the context. If then it works, that's a context issue. If not, then it's a regular behavior. :smile:

**Comment by tomsommer** [comment]
It seems `phase:2` is not applied from `SecDefaultAction` either, so in ModSec 2.x having one `SecDefaultAction` with `phase:2` in, was enough (and would maybe force all rules to be phase:2?), but in ModSec 3 you need both a `SecDefaultAction` for` phase:1` and `phase:2` (and maybe 3,4,5?), but that's fine - at lease there is a fix :)

So to summarize, I fixed it by adding `block` to all `SecRule` and adding an `SecDefaultAction` for `phase:1`

**Comment by airween** [comment]
As I wrote, I never used this scenario, used `SecDefaultAction` only with `block` ([CoreRuleSet](https://github.com/coreruleset/coreruleset) uses this), so I have no idea about the "correct" behavior :).

> (and would maybe force all rules to be phase:2?)

You mean force rules to `phase:2` which do not have `phase` action?

Yes, in case of mod_security2, if a rule does not have the `phase` action, then the engine evaluates it in `phase:2`, that's the default phase. In case of libmodsecurity3, this "default phase" is 1.

**Comment by tomsommer** [comment]
From https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#phase
> Description: Places the rule or chain into one of five available processing phases. It can also be used in SecDefaultAction to establish the rule defaults.

This is not the case in v3 then :)

**Comment by martinhsv** [comment]
Hi @tomsommer ,

I think you're misreading that quotation from the documentation -- by which I mean reading it differently, at least, from how the original composer intended. Although I suppose I can see how it might be misinterpreted.

The wording of those two sentences is the same in both the v2 doc and the (Draft) v3 doc. In neither case is the second sentence intended to mean
"It can also be used in SecDefaultAction to establish a default phase for rules where phase has not been specified."

but rather to mean:

"It can also be used in SecDefaultAction to establish default actions for rules within a particular phase."

If unspecified in a particular rule, phase defaults are as described by @airween -- although I would recommend always specifying the phase to minimize confusion. Note that phase also cannot be changed by configuration items like ```SecRuleUpdateActionById```

**Comment by tomsommer** [comment]
Makes sense, should rephrase it for clarity :)

**Comment by martinhsv** [comment]
I have expanded the wording in the documentation somewhat. Hopefully this will reduce the risk of confusion.
