### ISSUE TITLE
Node.js Bindings

### ISSUE THREAD

**Issue by kevinwu-0103** [SpiderLabs/ModSecurity#2879]
I'm tempted to ask, why isn't there any Node.js Bindings that can screw me up

**Comment by martinhsv** [comment]
Hello @kevinwu-0103 ,

I'm not sure I understand your question. (Or perhaps it's not meant to be a real question? More of an amused observation/quip?)

**Comment by kevinwu-0103** [comment]
Well, I have a gateway based on Node.js, and now I want to integrate ModSecurity. At present, I only see the solution of https://github.com/manishmalik/Modsecurity-nodejs/blob/master/README.md, but I encounter many problems, do you consider developing Bindings for Node.js?

**Comment by martinhsv** [comment]
No such work is currently planned. However, since ModSecurity is a open-source project, members of the community who are interested are free to work on such an initiative themselves.

**Comment by kevinwu-0103** [comment]
Thank you, so I'll go on studying
