### ISSUE TITLE
How to install Modsecurity + Nginx on OpenBSD

### ISSUE THREAD

**Issue by claudn1ne** [SpiderLabs/ModSecurity#2884]
**Describe the bug**

I cannot install complie Modsecurity on OpenBSD
 Anyone can show me how to install or guideline for this OS.

Tks so much

**Comment by martinhsv** [comment]
Hello @copph33 ,

It might help if you described in detail what steps you have been attempting to follow, which of those you believe you have done successfully, at what point you encounter difficulty, and what error message(s) or problems you encounter at that point.

There are several compilation guides at https://github.com/SpiderLabs/ModSecurity/wiki/Compilation-recipes-for-v3.x that might be of some assistance in understanding generally what is required.
