### ISSUE TITLE
urlDecodeUni maybe  Abnormal decoding?

### ISSUE THREAD

**Issue by sunskyyao** [SpiderLabs/ModSecurity#2889]
**Describe the bug**

When there is a Chinese character (%U) in the load, urlDecodeuni may decoding errors, causing the hits the rules 920270

urlDecodeUni
Like urlDecode, but with support for the Microsoft-specific %u encoding. If the code is in the range of FF01-FF5E (the full-width ASCII codes), then the higher byte is used to detect and adjust the lower byte. Otherwise, only the lower byte will be used and the higher byte zeroed.

 "Otherwise, only the lower byte will be used and the higher byte zeroed." may be problems?

abnormal  payload is  "%u5F00%u653E%3B5G%u667A%u4EAB%u5957%u9910" 

eg:
 curl 'http://172.30.2.254:8080/'  -H "Cookie: appid=appId001; appId001_appuid=83104643-8134-b0a0-1534-6512610a7d38; tracksessionid=5a5f7433-6134-b101-15f9-178cf480ecf8; cookie_user_log=fabfe935ced34ce185dff25684f806c4; collect_id=32ivoqune333rrmriygw5ef61cq7mnfp; cfDefUserId=14462524912326705000222312424060; shop-history=aXBob25lLOiLueaenCzor4TkvLAscGluZ2d1byw1R%2BaZuuS6q%2BWll%2BmkkCw%3D; arialoadData=true; ariawapChangeViewPort=false; historyWord=%u5F00%u653E%3B5G%u667A%u4EAB%u5957%u9910; trace_referer=ad90d0a18e944457be8dc22b66ce2718; CmLocation=311|311; CmProvid=he; CmLocation=100|100; CmProvid=bj; CmLocation=100|100; CmProvid=bj; WT_FPC=id=2437331a2acab11a9931679044278597:lv=1680534770715:ss=1680534235563" 

**Logs and dumps**

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs
 3. Error logs
 4. If there is a crash, the core dump file.

_Notice:_ Be careful to not leak any confidential information.

**To Reproduce**

A **curl** command line that mimics the original request and reproduces the problem. Or a ModSecurity v3 test case.
eg:
 curl 'http://172.30.2.254:8080/'  -H "Cookie: appid=appId001; appId001_appuid=83104643-8134-b0a0-1534-6512610a7d38; tracksessionid=5a5f7433-6134-b101-15f9-178cf480ecf8; cookie_user_log=fabfe935ced34ce185dff25684f806c4; collect_id=32ivoqune333rrmriygw5ef61cq7mnfp; cfDefUserId=14462524912326705000222312424060; shop-history=aXBob25lLOiLueaenCzor4TkvLAscGluZ2d1byw1R%2BaZuuS6q%2BWll%2BmkkCw%3D; arialoadData=true; ariawapChangeViewPort=false; historyWord=%u5F00%u653E%3B5G%u667A%u4EAB%u5957%u9910; trace_referer=ad90d0a18e944457be8dc22b66ce2718; CmLocation=311|311; CmProvid=he; CmLocation=100|100; CmProvid=bj; CmLocation=100|100; CmProvid=bj; WT_FPC=id=2437331a2acab11a9931679044278597:lv=1680534770715:ss=1680534235563" 

[e.g: curl "modsec-full/ca/..\\..\\..\\..\\..\\..\\/\\etc/\\passwd" or [issue-394.json](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/test/test-cases/regression/issue-394.json)]

**Expected behavior**

**Server (please complete the following information):**
 - ModSecurity version (and connector): [e.g. ModSecurity v3.0.8 with nginx-connector v1.0.3]
 - WebServer: [e.g. nginx-1.18.0]
 - OS (and distro): [e.g. Linux, archlinux]

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? [e.g. SpiderLabs commercial rules]
 - What is the version number? [e.g. 2018-08-11]

**Additional context**

**Comment by martinhsv** [comment]
Hell @sunskyyao 

From the rule number that you cited, I assume that you are using coreruleset. That ruleset is managed in a separate github than this one (which is for the engine itself). Your question might best be directed to the group managing those rules: https://owasp.org/www-project-modsecurity-core-rule-set/

**Comment by sunskyyao** [comment]
hi, martinhsv
   thank you for your reply.
   I think the current URLDECODEUNI decoding may be abnormal in certain character sets. If the user uses escape to encodes characters, for non -ASCII characters, it may be encoded to %UXXXX.

eg:
  "%u5F00"  urlDecodeUni decode is  "NULL" 
https://www.utilities-online.info/urlencode
 "%u5F00"  --> " 开"

**Comment by sunskyyao** [comment]
hi, martinhsv
  "Microsoft-specific %u encoding"  is the subset of " UTF-16BE" ?

**Comment by martinhsv** [comment]
@sunskyyao ,

Many ModSecurity transformations may have a undesirable effect if used against input where the transformation in question is not appropriate. For example, even something as simple as urlDecode can be bad if the input is not, in fact, url-encoded and it includes a '+' sign.

Ideally, many such transformations are used to precisely match what the server backend will do with the input. This, of course, creates additional challenges for writers of generic rule sets.

What you have described so far does not suggest that urlDecodeUni is behaving inappropriately (based on its intended functionality). However, it can definitely be the case that either the rule should be adjusted, or set to not be included (or perhaps only excluded for certain inputs).
