### ISSUE TITLE
Nginx  compile Installation lua-nginx-module，modsecurity integration lua5.3，starting nginx will result in an error？

### ISSUE THREAD

**Issue by swzaaaaaaa** [SpiderLabs/ModSecurity#2897]
How is it compatible with nginx using Lua, and modsecurity also supports Lua?

**Comment by martinhsv** [comment]
Hello @swzaaaaaaa ,

I'm not sure I understand your question.

If you are actually receiving an error, consider using the issue template to detail as much information as possible about your situation.

**Comment by swzaaaaaaa** [comment]
> Hello @swzaaaaaaa ,
> 
> I'm not sure I understand your question.
> 
> If you are actually receiving an error, consider using the issue template to detail as much information as possible about your situation.

Hello,
I configured the following instruction in the nginx configuration file:
   load_module /xx/xx/ngx_http_modsecurity_module.so;
   load_module /xx/xx/ngx_http_lua_module.so,
Starting nginx will result in an error:
  PANIC:unportected error in call to Lua API(attemp to index a nil value) Aborted(core dumped).
However, nginx starts normally when I comment the following statement:
  #load_module /xx/xx/ngx_http_lua_module.so,

So I suspect that there is a conflict between modsecurity's lua and nginx's compiled lua. What is your best solution to enable both modsecurity and nginx to support lua?

**Comment by martinhsv** [comment]
I have not encountered that error.

A version conflict is a reasonable possibility. You'd probably want to determine which version of lua you are getting via load_module /xx/xx/ngx_http_lua_module.so, and make sure you're using the same version in your build of ModSecurity.

**Comment by swzaaaaaaa** [comment]
Hello.
What is the Lua version of NGINX and the Lua version in WAF?

**Comment by martinhsv** [comment]
For ModSecurity the ```configure``` step will tell which version it used in its build. E.g.
```
configure:6289: LUA library found at: /usr/lib/x86_64-linux-gnu//liblua5.2.so
configure:6294: LUA headers found at: /usr/include/lua5.2
```

This information will also be captured in the config.log file.

I have never used the separate lua module for nginx, but I expect you could check using any standard way to check for module versions. One that I would think might work ...
```
strings ngx_http_lua_module.so | grep -e "5\."
```

**Comment by swzaaaaaaa** [comment]
"Is this part still being updated?"

**Comment by martinhsv** [comment]
@swzaaaaaaa ,

I don't understand your question.

The previous update to this issue was from me, providing some specific information about lua versions. Did you use that information to check your installation?
