### ISSUE TITLE
Rules for ModSecurity to prevent Bruteforce Attacks coming from BurpSuite

### ISSUE THREAD

**Issue by mohankk1297** [SpiderLabs/ModSecurity#2903]
Hi , I am testing DVWA using BurpSuite for Brute Force attacks . 
My engine is On and I dont see ModSecurity Blocking any login requests . 

My Stack 
Kali Linux , DVWA , apache2, Modsecurity version 2.9.5

**Comment by martinhsv** [comment]
Hello @mohankk1297 ,

The ModSecurity engine (i.e. this github repository) provides the tools for detections.

You need to have rules in place to make use of those tools. You would need to review the rules that you are using to attempt to block such attacks (which you may have sourced from a third party).
