### ISSUE TITLE
sudo make fails compiling ModSecurity

### ISSUE THREAD

**Issue by adrianrss** [SpiderLabs/ModSecurity#2907]
**Describe the bug**

**sudo make** fails compiling ModSecurity 3(latest) on Debian 11 + nginx 1.24.0

**Logs and dumps**

Omake[2]: Entering directory '/opt/ModSecurity/examples/multiprocess_c'
gcc -DHAVE_CONFIG_H -I. -I../../src    -I../../headers -I../..  -g -O2 -MT multi-multi.o -MD -MP -MF .deps/multi-multi.Tpo -c -o multi-multi.o `test -f 'multi.c' || echo './'`multi.c
mv -f .deps/multi-multi.Tpo .deps/multi-multi.Po
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -I../../headers -I../..  -g -O2 -L../../src/.libs/ -L/usr/lib/x86_64-linux-gnu  -lmodsecurity -lpthread -lm -lstdc++    -L/usr/lib/x86_64-linux-gnu   -o multi multi-multi.o    -lrt   
libtool: link: gcc -I../../headers -I../.. -g -O2 -o .libs/multi multi-multi.o  -L../../src/.libs/ -L/usr/lib/x86_64-linux-gnu /opt/ModSecurity/src/.libs/libmodsecurity.so -lpthread -lm -lstdc++ -lrt -Wl,-rpath -Wl,/usr/local/modsecurity/lib
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_global_init@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_easy_perform@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_slist_free_all@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_easy_strerror@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_slist_append@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ModSecurity/src/.libs/libmodsecurity.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:506: multi] Error 1
make[2]: Leaving directory '/opt/ModSecurity/examples/multiprocess_c'
make[1]: *** [Makefile:553: all-recursive] Error 1
make[1]: Leaving directory '/opt/ModSecurity/examples'
make: *** [Makefile:1049: all-recursive] Error 1

Could you please help with this? I'm not able to install ModSecurity at all.

**Comment by airween** [comment]
I assume you need to install these packages:

```bash
sudo apt install curl libcurl3-gnutls:amd64 libcurl4:amd64 libcurl4-gnutls-dev:amd64
```
On my Debian 11 (ModSecurity) build machine has these packages, and those are enough.

Btw you could try the pre-compiled packages from [here](https://modsecurity.digitalwave.hu).

**Comment by adrianrss** [comment]
Hello,

I've tried installing those packages but that doesn't help either, I get the same error.

I then tried the instructions on your link, step by step, but when simulating an attack, the response is as usual, response 200, like it never detected any attack using the `curl -v -H "User-Agent: Nikto" 'http://localhost'` line

**Comment by airween** [comment]
> I've tried installing those packages but that doesn't help either, I get the same error.

If you have installed package `libcurl4-openssl-dev`, try to remove it.

> I then tried the instructions on your link, step by step, but when simulating an attack, the response is as usual, response 200, like it never detected any attack using the curl -v -H "User-Agent: Nikto" 'http://localhost' line

Is there any new lines in your error.log? (Did you add the severity `info` to your error.log?)
What is the `SecRuleEngine` value in your `modsecurity.conf` file?

**Comment by adrianrss** [comment]
Okay so I managed to remove `libcurl4-openssl-dev`

Unfortunately, I can't get pass the `sudo make`, so there's no modsecurity.conf or modesecurity folder in /etc/nginx ....

**Comment by airween** [comment]
> Okay so I managed to remove `libcurl4-openssl-dev`

Cool.
 
> Unfortunately, I can't get pass the `sudo make`, so there's no modsecurity.conf or modesecurity folder in /etc/nginx ....

Without that file it will hard to wake up the WAF :smiley:.

You should copy the file from the source tree, it's there with name `modsecurity.conf-recommended` - [see](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended) the original file.

You should include it. Also you have to install a rule set - I suggest [Core Rule Set](https://github.com/coreruleset/coreruleset), which is also available from the mentioned repository above.

**Comment by adrianrss** [comment]
Just remembered that I actually followed this documentation `https://modsecurity.digitalwave.hu/` and the conf file is in `/etc/nginx/modsecurity.conf`

The `SecRuleEngine` value is `DetectionOnly`

I also added the Core Rule Set I think using the same documentation.
I have these in /etc/nginx/modsecurity_includes.conf
```
include modsecurity.conf
include /usr/share/modsecurity-crs/owasp-crs.load
```

**Comment by airween** [comment]
Fine.

Did you include the file `/etc/nginx/modsecurity_includes.conf`?

You should put that into your nginx.conf, for eg.:

```
http {
        ...
        modsecurity_rules_file /etc/nginx/modsecurity_includes.conf;
```

also do not forget to turn on the feature with:
```
        modsecurity on;
```

You can do that in same place or if you want to apply that only for specific sites, then you can put it only there, eg:

```
server {
        server_name ...;
        ....
        modsecurity on;
```

Please do not forget to add minimum severity to your error.log:

```
        error_log /var/log/nginx/error.log info;
```

After these modifications, what do you see in your log with the request above?

Note, that in file `/usr/share/modsecurity-crs/owasp-crs.load` you must replace the `IncludeOptional` to `Include`.

**Comment by adrianrss** [comment]
I already have those added in /etc/nginx/sites-available/default, shouldn't that be enough? If I add them to nginx.conf, nginx will not start anymore saying in detected duplicates.

This is how they look like in that file, I've added them under root /var/www/html:
```
        root /var/www/html;
        modsecurity on;
        modsecurity_rules_file /etc/nginx/modsecurity_includes.conf;
```

I already changed everything to `Include` before, this is how they look like:
```
Include /etc/modsecurity/crs/crs-setup.conf
Include /etc/modsecurity/crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
Include /usr/share/modsecurity-crs/rules/*.conf
Include /etc/modsecurity/crs/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
```

I have now added the minimum severity for the error.log, here are some log fragments:

```
2023/05/24 21:49:19 [info] 307208#307208: *1 client 127.0.0.1 closed keepalive connection
2023/05/24 21:53:02 [info] 307208#307208: *2 ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `scanners-user-agents.data' against variable `REQUEST_HEADERS:User-Agent' (Value: `Nikto' ) [file "/usr/share/modsecurity-crs/rules/REQUEST-913-SCANNER-DETECTION.conf"] [line "34"] [id "913100"] [rev ""] [msg "Found User-Agent associated with security scanner"] [data "Matched Data: nikto found within REQUEST_HEADERS:User-Agent: nikto"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-reputation-scanner"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/224/541/310"] [tag "PCI/6.5.10"] [hostname "127.0.0.1"] [uri "/"] [unique_id "168496518265.345772"] [ref "o0,5v55,5t:lowercase"], client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost"
2023/05/24 21:53:02 [info] 307208#307208: *2 ModSecurity: Warning. Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/share/modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "127.0.0.1"] [uri "/"] [unique_id "168496518265.345772"] [ref ""], client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost"
2023/05/24 21:53:02 [info] 307208#307208: *2 ModSecurity: Warning. Matched "Operator `PmFromFile' with parameter `scanners-user-agents.data' against variable `REQUEST_HEADERS:User-Agent' (Value: `Nikto' ) [file "/usr/share/modsecurity-crs/rules/REQUEST-913-SCANNER-DETECTION.conf"] [line "34"] [id "913100"] [rev ""] [msg "Found User-Agent associated with security scanner"] [data "Matched Data: nikto found within REQUEST_HEADERS:User-Agent: nikto"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-reputation-scanner"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/224/541/310"] [tag "PCI/6.5.10"] [hostname "127.0.0.1"] [uri "/"] [unique_id "168496518275.052508"] [ref "o0,5v55,5t:lowercase"], client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost"
2023/05/24 21:53:02 [info] 307208#307208: *2 ModSecurity: Warning. Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/usr/share/modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "127.0.0.1"] [uri "/"] [unique_id "168496518275.052508"] [ref ""], client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost"
2023/05/24 21:53:02 [info] 307208#307208: *2 client 127.0.0.1 closed keepalive connection
```

But for some reason it still doesn't block the access when I run `curl -v -H "User-Agent: Nikto" 'http://localhost'` , it would still display the page content as usual.

**Comment by airween** [comment]
> But for some reason it still doesn't block the access when I run `curl -v -H "User-Agent: Nikto" 'http://localhost'` , it would still display the page content as usual.

In a previous comment above you wrote:

> The `SecRuleEngine` value is `DetectionOnly`

if you want to really block the request, change it to `On`:

```
SecRuleEngine On
```

`DetectionOnly` means the engine execute the rules, analyses the request, but does not intervene. With `On` it will follow the behavior what the rule describes. `Off` means the engine does not process the request at all.

As you can see at the rule [949110](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-949-BLOCKING-EVALUATION.conf#L81-L94), the disruptive action is `deny`, which will block the request.

**Comment by martinhsv** [comment]
Is there still an issue here?

As has been pointed out by @airween , the error messages in the original posting appear to be caused by missing dependencies. If you believe you have the necessary dependencies, the output of the ```./configure``` step should show that.
