### ISSUE TITLE
Need a GUI tool for Modsecurity

### ISSUE THREAD

**Issue by mohankk1297** [SpiderLabs/ModSecurity#2908]
This is my current Setup , 
ModSecurity version 2.9.5, Kali Linux , Mysql and PHP . 
I need a visual tool so as to Turn on / Off Modsecurity Engine , See Attack Logs , Monitoring , Set alerts and Integration with Teams / Email / Slack .  
Is there any tool with the said features available in market ?

**Comment by martinhsv** [comment]
Hello @mohankk1297 ,

The ModSecurity project itself does not include such a GUI tool.

I have seen a couple of individuals/groups produce such tools in the past, but I'm not at all sure about the quality or usefulness (or even if they still exist and are maintained).

I'll leave this item open for at least another week or two in case anyone in the community has a suggestion to make.
