### ISSUE TITLE
ModSecurity: APR compiled version="1.7.0"; loaded version="1.7.2" in Debian Sid package

### ISSUE THREAD

**Issue by logopk** [SpiderLabs/ModSecurity#2910]
**Describe the bug**

Apache logs `ModSecurity: APR compiled version="1.7.0"; loaded version="1.7.2"` on startup

I use the package from debian sid and apparently the build is not using sids preinstalled libapr, as sid uses 1.7.2:

https://packages.debian.org/sid/libapache2-mod-security2

` dep: [libapr1](https://packages.debian.org/sid/libapr1) (>= 1.2.7)`

**Logs and dumps**

Output of:
# less logs/error.log
[2023-05-31 13:11:05.165026] [security2:notice] - - ModSecurity for Apache/2.9.7 (http://www.modsecurity.org/) configured.
[Wed May 31 13:11:05.165477 2023] [security2:notice] [pid 8:tid 1996017088] ModSecurity: APR compiled version="1.7.0"; loaded version="1.7.2"
[Wed May 31 13:11:05.165508 2023] [security2:warn] [pid 8:tid 1996017088] ModSecurity: Loaded APR do not match with compiled!
_[Wed May 31 13:11:05.165530 2023] [security2:notice] [pid 8:tid 1996017088] ModSecurity: PCRE2 compiled version="10.42 "; loaded version="10.36 2020-12-04"
[Wed May 31 13:11:05.165549 2023] [security2:warn] [pid 8:tid 1996017088] ModSecurity: Loaded PCRE do not match with compiled!_
[Wed May 31 13:11:05.165566 2023] [security2:notice] [pid 8:tid 1996017088] ModSecurity: LUA compiled version="Lua 5.1"
[Wed May 31 13:11:05.165583 2023] [security2:notice] [pid 8:tid 1996017088] ModSecurity: YAJL compiled version="2.1.0"
[Wed May 31 13:11:05.165599 2023] [security2:notice] [pid 8:tid 1996017088] ModSecurity: LIBXML compiled version="2.9.14"
[Wed May 31 13:11:05.165617 2023] [security2:notice] [pid 8:tid 1996017088] ModSecurity: Status engine is currently disabled, enable it by set SecStatusEngine to On.

_PCRE is my "fault"_

Installed in the container is:

#dpkg -l "libapache2-mod-security2*" | grep ^ii
ii  libapache2-mod-security2 2.9.7-1      armhf        Tighten web applications security for Apache

#dpkg -l "libapr1*" | grep ^ii
ii  libapr1:armhf  1.7.2-3      armhf        Apache Portable Runtime Library

#dpkg -l "apache*" | grep ^ii
ii  apache2                         2.4.57-2     armhf        Apache HTTP Server
ii  apache2-bin                     2.4.57-2     armhf        Apache HTTP Server (modules and other binary files)
ii  apache2-data                    2.4.57-2     all          Apache HTTP Server (common files)
ii  apache2-utils                   2.4.57-2     armhf        Apache HTTP Server (utility programs for web servers)

**To Reproduce**

Docker file:

FROM debian:bullseye-slim

```
RUN set -x  && apt-get -t sid install -o APT::Immediate-Configure=false -y --no-install-recommends \
                               libapache2-mod-security2 \
                               modsecurity-crs \
                               openssl libssl1.1 \
                               apache2
...
```
**Expected behavior**

Well: no warning?

**Server (please complete the following information):**
 - see above
 - WebServer: Debian Sid Apache 2.4.57-2
 - OS: Docker 24.0.2 on Debian Linux (armhf, arm64,amd64)

**Rule Set (please complete the following information):**
 - CRS 3.3.4-1 from Debian Sid

Thanks

Peter

**Comment by airween** [comment]
Just a quick note: this is not a ModSecurity (upstream) issue, but a Debian issue.

The reason is simple:

libapache2-mod-security2 was uploaded 23rd of January, after the release:

https://tracker.debian.org/pkg/modsecurity-apache
```
[2023-01-23] Accepted modsecurity-apache 2.9.7-1 (source) into unstable (Ervin Hegedüs) (signed by: Alberto Gonzalez Iniesta)
```
but the libapr (1.7.2-3) was uploaded later:

https://tracker.debian.org/pkg/apr
```
[2023-02-02] Accepted apr 1.7.2-1 (source) into unstable (Stefan Fritsch) 
[2023-02-26] Accepted apr 1.7.2-3 (source) into unstable (Stefan Fritsch) 
```
Please close this issue, and if you think, open a new one in Debian's bug tracker. I'm going to try to rebuild the package.

And thanks for the info.

**Comment by logopk** [comment]
@airween I don't have access to the debian bug tracker (I think) but I trust you that you will rebuild the package ;-)
