### ISSUE TITLE
serverLogCallback response as JSON format. 

### ISSUE THREAD

**Issue by mattk0stka** [SpiderLabs/ModSecurity#2911]
With the help of the msc_set_log_cb function i can already retrieve the AuditLogs. Unfortunately, these Logs are not output in JSON format, although SecAuditLogFormat is configured as JSON. Is it possible to customize this ?

I have already checked the whole documentation but nothing found. Is there any other method to get the AuditLogs in JSON via a callback function ?

**Comment by martinhsv** [comment]
Hello @mk0stka ,

Would you like to describe in a little more detail what you are already doing and what your functional goal is?

**Comment by mattk0stka** [comment]
@martinhsv thank you for your repsonse and motivation to help .

Let's take the Simple example here from the repo. 
https://github.com/SpiderLabs/ModSecurity/blob/v3/master/examples/simple_example_using_c/test.c

I have written a reverse proxy in C and would like to analyze each incoming request. The relevant code is pretty much identical to the one in the example. AutiLogs can now be forwarded via HTTP or saved to files. This works without any problems. 

However, I want a callback function to be called as soon as something is detected and audit logs are created. 
As far as I could try it out, I can use the 'msc_set_log_cb' function to retrieve these AuditLogs also. 
Unfortunately, the AutiLogs are not formatted in JSON as via HTTP or in the file, although SecAuditLogFormat is configured as JSON. 

Or is there another way to get the AuditLogs as a string? I don't want to read the AuditLogs from files or have an HTTP service to get the logs. 

I hope I was able to clarify my request a little more and would be happy to receive an answer. 

edit: I want to use the C API, because I want to use the ModSecruity lib also in other languages via bindings.

**Comment by airween** [comment]
> I have written a reverse proxy in C

sorry for the question, but is it available anywhere?

**Comment by mattk0stka** [comment]
Hi @airween, it is not publicly available. It is a private hobby project and not in a public repo. I don't want to abuse anyone with my code. :)

Surely I could use Nginx. But it's more learning by doing.

**Comment by mattk0stka** [comment]
Hi @martinhsv It's been a while since your last comment. Do you have a suggestion for me how to get the AuditLogs as JSON ?  Hope to hear from you and thanks in advance.

`

    msc_process_connection(transaction, "127.0.0.1", 12345, "127.0.0.1", 80);
    msc_process_uri(transaction,
        "http://www.modsecurity.org/test?key1=value1&key2=value2&key3=value3",
        "GET", "1.1");
    msc_process_request_headers(transaction);
    msc_process_request_body(transaction);
    msc_process_response_headers(transaction, 200, "HTTP 1.3");
    msc_process_response_body(transaction);
    msc_process_logging(transaction);
    // <--- additional method to get AuditLogs as json string ?
`

**Comment by airween** [comment]
I assume you are using [this](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/examples/simple_example_using_c/test.c) example, so perhaps you have [this](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/examples/simple_example_using_c/test.c#L41) line in your code.

If it's true, you should add the audit.log related configuration directives to that config, what you use.

For eg. see [this](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#secauditlogformat).

**Comment by mattk0stka** [comment]
Hi @airween, thank you for your reply. Your assumption is correct and the necessary configuration is also made. As mentioned before, I receive the logs as JSON via file or HTTP request. It works without any problems at all. 

What I would like to have is something like this:

```
const char *audit_log = NULL;      // 
.
.
.
msc_process_connection(transaction, "127.0.0.1", 12345, "127.0.0.1", 80);
msc_process_uri(transaction,
    "http://www.modsecurity.org/test?key1=value1&key2=value2&key3=value3",
    "GET", "1.1");
msc_process_request_headers(transaction);
msc_process_request_body(transaction);
msc_process_response_headers(transaction, 200, "HTTP 1.3");
msc_process_response_body(transaction);
msc_process_logging(transaction);

msc_process_audit_log(&audit_log);    // <- now i should have AuditLogs as JSON to be able to work with it further in audit_log.
```


Here in the next example, where I get AuditLogs but not in JSON format, although configured. 
```
SecAuditLogFormat JSON
```

```
void modSecurity_log(void *log, const void* data) {
    const char *msg;
    if (log == NULL) {
        return;
    }
    msg = (const char *) data;
    printf("%c", *msg); // <- not in JSON format
}

msc_set_log_cb(conf->modSecurity, modSecurity_log);
```

Hope the examples help a bit.

**Comment by airween** [comment]
> It works without any problems at all.

Sorry, but then I don't see your problem.

> ```
> msc_process_audit_log(&audit_log);    // <- now i should have AuditLogs as JSON to be able to work with it further in audit_log.
> ```

And sorry, but what is the function `msc_process_audit_log()`? There isn't any function with this name. Moreover, what is the variable `audit_log`? As I know audit log is written by the engine, not the application (which embeds the engine), so you can't access it directly (fix me please if I'm wrong).

> ```
>     ....
>     printf("%c", *msg); // <- not in JSON format
>     ....
> ```
yes, because the `msg` derived from the `log`, which is the error log. This message is produced [here](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/rule_message.cc#L26-L52).

> ```
> msc_set_log_cb(conf->modSecurity, modSecurity_log);
> ```
this function sets the error log callback handler.

> Hope the examples help a bit.

I'm really sorry, but now I'm totally confused :).

**Comment by mattk0stka** [comment]
Hi @airween, Sorry for the confusion.
 
> And sorry, but what is the function msc_process_audit_log()? There isn't any function with this name. Moreover, what is the variable audit_log? As I know audit log is written by the engine, not the application (which embeds the engine), so you can't access it directly (fix me please if I'm wrong).

You are completely right, the methods do not exist. That was also only to be understood as an example of how I would have liked to realize it. So there is no possibility to access the AuditLogs written by the engine through the application ?

I would like to have the AuditLogs in the application level. Is there a possibility here ? But not by reading a file or opening an HTTP service.

**Comment by airween** [comment]
> So there is no possibility to access the AuditLogs written by the engine through the application ?

IMHO no, at least not in (native) C. Please take a look to files under `headers/` directory, especially to `extern "C"` blocks. What you see in those blocks, that's what you can use.

> I would like to have the AuditLogs in the application level. Is there a possibility here ?

No, as I wrote IMHO you can't. But there would be many problems, eg. transactions run parallel, you have to care about file locking... Another issue: consider user sets the audit log properties in the configuration file, now you overwrite those settings?

**Comment by martinhsv** [comment]
@mk0stka ,

Have you considered reading the the audit log file to retrieve the information you're interested in?
