### ISSUE TITLE
Modsecurity is blocking wordpress actions

### ISSUE THREAD

**Issue by alisacorporation** [SpiderLabs/ModSecurity#2913]
**Describe the bug**

When i went to Wordpress Admin panel -> Tools -> Site health getting error (), editing category => error, do i need to whitelist somehow my ip or i should not use wordpress at all? xD

**1.** Editing description of category in wordpress about operating system

```
HTTP/1.1 403
Server: nginx/1.24.0
Date: Wed, 07 Jun 2023 17:18:38 GMT
Content-Length: 555
Content-Type: text/html
Connection: keep-alive

---2hSC3X80---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i)\b(?:s(?:e(?:t(?:_(?:e(?:xception|rror)_handler|magic_quotes_runtime|include_path)|defaultstub)|ssion_s(?:et_save_handler|tart))|qlite_(?:(?:(?:unbuffered|single|array)_)?query|create_(?:aggregate (2095 characters omitted)' against variable `ARGS:description' (Value: `\x0d\x0aAn operating system (OS) is a software that manages computer hardware and software resources (459 characters omitted)' ) [file "/etc/nginx/conf.d/crs/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf"] [line "330"] [id "933160"] [rev ""] [msg "PHP Injection Attack: High-Risk PHP Function Call Found"] [data "Matched Data: system (OS) found within ARGS:description: \x0d\x0aAn operating system (OS) is a software that manages computer hardware and software resources. It acts as an intermediary between the user and (410 characters omitted)"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "Local Lab Service"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-injection-php"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [hostname "10.0.0.242"] [uri "/wp-admin/edit-tags.php"] [unique_id "168615831838.415159"] [ref "o15,11v2163,553"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/etc/nginx/conf.d/crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "Local Lab Service"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "10.0.0.242"] [uri "/wp-admin/edit-tags.php"] [unique_id "168615831838.415159"] [ref ""]
```

**2.** Wordpress Site-health displaying php/mysql information on admin page

```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i)(?:System\.Data\.OleDb\.OleDbException|\[Microsoft\]\[ODBC SQL Server Driver\]|\[Macromedia\]\[SQLServer JDBC Driver\]|\[SqlException|System\.Data\.SqlClient\.SqlException|Unclosed quotation mark  (641 characters omitted)' against variable `RESPONSE_BODY' (Value: `<!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-US">\x0a<head>\x0a<meta http-equiv="Cont (40305 characters omitted)' ) [file "/etc/nginx/conf.d/crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"] [line "323"] [id "951220"] [rev ""] [msg "mssql SQL Information Leakage"] [data "Matched Data: SQL server is up to date\x22,\x22status\x22:\x22good\x22,\x22badge\x22:{\x22label\x22:\x22Performance\x22,\x22color\x22:\x22blue\x22},\x22description\x22:\x22<p>The SQL server is a required piece of software for the database WordPress uses  (43336 characters omitted)"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-mssql"] [tag "attack-disclosure"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/116/54"] [hostname "10.0.0.242"] [uri "/wp-admin/site-health.php"] [unique_id "168615846966.472742"] [ref "o31899,5608v1436,37885"]
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?:\b(?:f(?:tp_(?:nb_)?f?(?:ge|pu)t|get(?:s?s|c)|scanf|write|open|read)|gz(?:(?:encod|writ)e|compress|open|read)|s(?:ession_start|candir)|read(?:(?:gz)?file|dir)|move_uploaded_file|(?:proc_|bz)open|ca (43 characters omitted)' against variable `RESPONSE_BODY' (Value: `<!DOCTYPE html>\x0a<html class="wp-toolbar"\x0a\x09lang="en-US">\x0a<head>\x0a<meta http-equiv="Cont (40305 characters omitted)' ) [file "/etc/nginx/conf.d/crs/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "53"] [id "953110"] [rev ""] [msg "PHP source code leakage"] [data "Matched Data: session_start found within RESPONSE_BODY: <!DOCTYPE html>\x0a<html class=\x22wp-toolbar\x22\x0a\x09lang=\x22en-US\x22>\x0a<head>\x0a<meta http-equiv=\x22Content-Type\x22 content=\x22text/html; charset=UTF-8\x22 />\x0a\x09<title>Sit (37741 characters omitted)"] [severity "3"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/118/116"] [tag "PCI/6.5.6"] [hostname "10.0.0.242"] [uri "/wp-admin/site-health.php"] [unique_id "168615846966.472742"] [ref "o31664,13v1436,37885"]
ModSecurity: Access denied with code 403 (phase 4). Matched "Operator `Ge' with parameter `5' against variable `TX:OUTBOUND_ANOMALY_SCORE' (Value: `9' ) [file "/etc/nginx/conf.d/crs/rules/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "69"] [id "959100"] [rev ""] [msg "Outbound Anomaly Score Exceeded (Total Score: 9)"] [data ""] [severity "0"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "10.0.0.242"] [uri "/wp-admin/site-health.php"] [unique_id "168615846966.472742"] [ref ""]
```

**To Reproduce**

1. Install wordpress latest, go to admin cp -> tools ->site health
2. update posts category with description: An operating system (OS) is a software that manages computer hardware and software resources. It acts as an intermediary between the user and the computer, providing a user-friendly interface and enabling the execution of various applications. The OS handles tasks such as memory management, process scheduling, file management, and device control. Its primary function is to facilitate the efficient and secure utilization of computer resources, ensuring that multiple programs can run simultaneously and interact with the hardware without conflicts.

**Expected behavior**

A clear and concise description of what you expected to happen. ?? cmon.. its should work lol

**Server (please complete the following information):**
 - ModSecurity version (and connector): [ModSecurity v3.0.9 with nginx-connector v1.0.3]
 - WebServer: [nginx-1.24.0]
 - OS (and distro): [ubuntu]

**Comment by martinhsv** [comment]
Hello @alisacorporation ,

Let me first mention that the ModSecurity engine (this repo) provides the tools for rule writers to produce detections. Particular rule sets are managed separately. If what I mention here does not provide enough information for you, you may want to consult with the rule publishers (although you don't say so explicitly, it looks like you're using coreruleset rules).

Your rule 933160 appears to be being triggering due to multiple keywords in your (presumably freeform) 'description' that, in some contexts may be suspicious -- strings like 'exec' and 'file'.

It's pretty common to experience at least some false positives with any ruleset (especially with generic rulesets like CRS). The most common strategy is simply to write exclusions that remove the detection. To do so as safely as possible, it's normally preferable to make the exclusion as specific as practical.

For example if the update you are trying to do involves a specific filename (e.g. 'wp-admin') and another specific ARG vluae (e.g. 'page' or 'action'), one could write a rule that tests for these and then in the actions removes 'description' from consideration for rule 933160 with 'ctl:ruleRemoveTargetById=933160;ARGS:description'.

**Comment by alisacorporation** [comment]
I'm using OWASP ModSecurity CRS: https://github.com/SpiderLabs/owasp-modsecurity-crs
I see there more than produce detections, it it is WAF, detector, analyzer recommender etc :D Thanks for your time ;)

**Comment by alisacorporation** [comment]
Ok, with providing logs to ChatGPT go it working.  First tried to do by examples from https://www.netnea.com/cms/nginx-tutorial-7_including-owasp-modsecurity-core-rule-set/ where i followed tutorial to compile that all, but that give me error, because they used id in middle which gives me error:  "phase:1,nolog,pass,id:15000,ctl:ruleRemoveTargetById=932160;ARGS:password"

Here is the rues I applied:
```
# === ModSec Core Rules: Runtime Exclusion Rules (ids: 10000-49999)

SecRule REQUEST_URI "@beginsWith /wp-admin/site-health.php" \
    "id:15000,phase:1,nolog,allow,ctl:ruleRemoveById=959100"

SecRule REQUEST_URI "@beginsWith /wp-admin/edit-tags.php" \
    "id:15001,phase:1,nolog,allow,ctl:ruleRemoveById=949110"

# ...
```

Thanks!
