### ISSUE TITLE
ModSecurity clientip matching rule

### ISSUE THREAD

**Issue by nathangary** [SpiderLabs/ModSecurity#2914]
hi
Which variable does clientip output?
I deployed in the k8s cluster and tried to output the correct client ip, but now I'm output like the cluster virtual ip.
The log output is as follows:
 ModSecurity "[client 172.30.0.15] ModSecurity: Access denied with code 403 (phase 1). Matched \x22Operator `Rx' with parameter

**Comment by martinhsv** [comment]
Hello @nathangary 

The short answer is that REMOTE_ADDR contains the correct client IP.

The longer answer is that, if there are intermediaries, there may be many client IPs relevant to the transaction and, by default, REMOTE_ADDR will normally contain the IP address actually making the TCP connection to the receiver associated with the ModSecurity process.

If there are intermediate IPs within your trusted network, the IP address just prior to the trusted network can usually be preserved via special request headers (X-Forwarded-For is perhaps the most common, but there are others). Depending on installation details (including what web server you're using with which version of ModSecurity), your web server may have tools to help you populate REMOTE_ADDR with which IP address you prefer. In other cases, you may need to manage that yourself with a rule, and populate a transaction variable based on your knowledge of what information (like special request headers) is reliably populated within your trusted network.
