### ISSUE TITLE
attack type in response on the 403 page

### ISSUE THREAD

**Issue by meisamrce** [SpiderLabs/ModSecurity#2917]
Hi 
How can the attack type be displayed to the user as a response on the 403 page?

for example 

http://localhost/?id=1+union+select+           # 403 response send message attack detection SQL Injection

**Comment by martinhsv** [comment]
Hello @meisamrce ,

I would recommend against considering that. Providing detailed information in the response is of high value to attackers.

**Comment by martinhsv** [comment]
Hi @meisamrce ,

I would again highlight my earlier caution, but if you really want to do that for experimental or research purposes ...

There are a few different ways to do something like what you are asking for. If it were me I would probably consider something like using the redirect action to send the id of the relevant rule to an error page (and then have the error page return the information to the client).

E.g.
```
... setvar:'tx.errorurl=http://localhost/errorrule.php?%{RULE.id}',redirect:%{tx.errorurl}"
```

Text categorizations (like 'SQL Injection') are typically done via either the 'msg' action or the 'tag' actions (depending on the ruleset). You should also be able to use the following.
```
... setvar:'tx.errorurl=http://localhost/errorrule.php?%{RULE.msg}',redirect:%{tx.errorurl}"
```
