### ISSUE TITLE
NEW FEATURE: modsecurity should detect more PII information 

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#2920]
ModSecurity currently detects credit card numbers, social security numbers, and Brazilian social number. It would be a big help if ModSecurity could also include more PII's as well such as Aadhar card number (India), PAN card number (India), Driving License Number, UPI (India), Passport Number, Cheque Number, Income Tax Return Number, Email Id, Vehicle Registration Numbers, mobile numbers.

**Comment by marcstern** [comment]
You can write your own extension (operator) to ModSecurity for that, it's not very complex (once you wrote your first one 😉).
And, for most of these, there's no need for a custom operator, a simple regex fits the bill. A custom operator is needed, for instance, to check the Luhn check digit of a credit card, but there's nothing to check for an email address on top of the regex itself.
