### ISSUE TITLE
Skip XML element from mod sec rule scanning from xml payload 

### ISSUE THREAD

**Issue by Vikasjava60** [SpiderLabs/ModSecurity#2929]
Hi Team,

We have the below xml payload getting blocked due to mod sec rule 

{"messages":["Access denied with code 403 (phase 2). Pattern match \"(/\\\\*!?|\\\\*/|[';]--|--[\\\\s\\\\r\\\\n\\\\v\\\\f]|(?:--[^-]*?-)|([^\\\\-&])#.*?[\\\\s\\\\r\\\\n\\\\v\\\\f]|;?\\\\x00)\" at XML. [file \"mod_perl\"] [line \"409\"] [id \"942440\"] [rev \"2\"] [msg \"SQL Comment Sequence Detected.\"] [data \"Matched Data: --ZXbyVq6U8rOy6un57Q1Z7k97CQpDudZSDekE3ng1enjF3dKfiuHk4zpyfq_MMy_qj_0w_z5zmkHMgIQw- found within XML:     REG_CODE    0273771812    600            ****FCM:<data causing issue>****                  \"] [severity \"CRITICAL\"] [ver \"OWASP_CRS/3.0.2\"] [maturity \"8\"] [accuracy \"8\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-sqli\"] [tag \"OWASP_CRS/WEB_ATTACK/SQL_INJECTION\"] [tag \"WASCTC/WASC-19\"] [tag \"OWASP_TOP_10/A1\"] [tag \"OWASP_AppSensor/CIE1\"] [tag \"PCI/6.5.2\"] [tag \"paranoia-level/2\"]"],"error_messages":["[file \"apache2_util.c\"] [line 271] [level 3] [client 172.17.0.1] ModSecurity: Access denied with code 403 (phase 2). Pattern match \\\\\"(/\\\\\\\\\\\\\\\\*!?|\\\\\\\\\\\\\\\\*/|[';]--|--[\\\\\\\\\\\\\\\\s\\\\\\\\\\\\\\\\r\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\v\\\\\\\\\\\\\\\\f]|(?:--[^-]*?-)|([^\\\\\\\\\\\\\\\\-&])#.*?[\\\\\\\\\\\\\\\\s\\\\\\\\\\\\\\\\r\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\v\\\\\\\\\\\\\\\\f]|;?\\\\\\\\\\\\\\\\x00)\\\\\" at XML. [file \\\\\"mod_perl\\\\\"] [line \\\\\"409\\\\\"] [id \\\\\"942440\\\\\"] [rev \\\\\"2\\\\\"] [msg \\\\\"SQL Comment Sequence Detected.\\\\\"] [

<RegisterRequest>
    <registrationSecurityMethod>xxxxx</registrationSecurityMethod>
    <notificationProfiles>
        <notificationProfile>FCM:xxxx/notificationProfile>
    </notificationProfiles>
</RegisterRequest>

we would like to rewrite the rule to update it to skip the element  <notificationProfile>FCM:xxxx/notificationProfile> from scanning in case of xml payload.

I am able to rewrite it for json payload like below and its working for me.
SecRuleUpdateTargetById 942440 "!ARGS:notificationProfiles.notificationProfiles"

For XML payload i am trying to use it like below but its not working and request is still getting blocked. Kindly suggest

SecRuleUpdateTargetById 942440 "!XML:/RegisterRequest/notificationProfiles"

Overall :
SecRuleUpdateTargetById 942440 "!XML:/RegisterRequest/notificationProfiles"
SecRuleUpdateTargetById 942440 "!ARGS:notificationProfiles.notificationProfiles"

**Comment by martinhsv** [comment]
Hello @Vikasjava60 ,

Could you please post the payload? (Or at least a representative payload with the relevant tags included, and with any confidential information sanitized.)

Also: Are you using ModSecurity v2 or v3?

**Comment by Vikasjava60** [comment]
Hi @martinhsv 
Please find the payload:

<RegisterRequest>
    <registrationSecurityMethod>RXXXXCODE</registrationSecurityMethod>
    <registrationCode>0273771812</registrationCode>
    <validityPeriodSecs>600</validityPeriodSecs>
    <notificationProfiles>
        <notificationProfile>FCM:dVxH7htmS8aaebk4egDxAw:APA91bHmfz****************</notificationProfile>
    </notificationProfiles>
</RegisterRequest>

and want to skip the <notificationProfiles> element from scanning. I am able to do it for json payload using
SecRuleUpdateTargetById 942440 "!ARGS:notificationProfiles.notificationProfiles"

when trying for xml payload request using : SecRuleUpdateTargetById 942440 "!XML:/RegisterRequest/notificationProfiles"

ModSecurity V3 we are using

**Comment by martinhsv** [comment]
Hi @Vikasjava60 ,

My wording was a bit imprecise; what I meant by payload is the actual xml request body (or equivalent, but including the tags). But I'll go ahead and give some explanation in general terms ...

The XML collection is quite a bit different from ARGS, as it uses XPath expressions for specifying elements within the collection. This allows for a lot of functionality and flexibility in specifying what you want. But it does have the consequence that constructs like ```SecRuleUpdateTargetById``` cannot be used in quite the same way as with those other collections.

The best way, in principle, to perform your desired exclusion is to do so with the initial XPath specification. I.e. instead of including something like ```XML:/*``` in the list of targets, just perform your exclusions directly in that XPath string.

(This has a downside, of course, if you're using externally-sourced rules, as it means some extra maintenance if/when the ruleset has a newer version published.)

**Comment by Vikasjava60** [comment]
[request_payload.txt](https://github.com/SpiderLabs/ModSecurity/files/12081386/request_payload.txt)

Hi @martinhsv 
Thanks for your suggestion.

Attaching the actual xml request body. Could you please help me here to rewrite this rule id 942440 in order to exclude the elements:
<notificationProfiles>
        <notificationProfile>

**Comment by martinhsv** [comment]
If you simply want to exclude anything that has RegisterRequest as the first tag in the path, you could do something like this:
```
XML:/*[local-name()!='RegisterRequest']
```

However, perhaps you wish to be more cautious and only exclude /RegisterRequest/notificationProfiles and not all of /RegisterRequest. You could combine the above with the following to specifically include those other items within /RegisterRequest:
```
XML:/*[local-name()='RegisterRequest']/*[local-name()!='notificationProfiles']
```

Putting those together, you could replace the existing ```XML:/*``` in the rule with:
```
XML:/*[local-name()!='RegisterRequest']|XML:/*[local-name()='RegisterRequest']/*[local-name()!='notificationProfiles']
```

(Note: I'm not a XPath expert so be cautious with the above suggestion and test it out yourself.)

**Comment by Vikasjava60** [comment]
Hi @martinhsv 
Thanks a lot for sharing the xpath expression i tried it with sec rule but not luck as i am getting below errors

**Tried to update the rule target but error out as below:**
SecRuleUpdateTargetById 942440 "XML:/*[local-name()!='RegisterRequest']"
Error: add_config() has failed: Error to update target - [='RegisterRequest']] is not valid target

**Tried to rewrite the rule but error out as below:**
SecRule XML:/*[local-name()!='RegisterRequest'] "phase:2,id:942440"
add_config() has failed: ModSecurity: Rules must have at least id action

**Comment by martinhsv** [comment]
Hi @Vikasjava60 ,

It doesn't surprise me that your example using SecRuleUpdateTargetById does not work.

Rewriting the rule will work -- I tried it myself before posting my previous response. If your attempted rewrite is as you've shown above, note that you are missing the Operator. E.g. you need something like:
```
SecRule XML:/*[local-name()!='RegisterRequest'] "@rx ..." "id:98100,phase:2, ..."
```

**Comment by martinhsv** [comment]
Closing due to no further activity.

**Comment by vsharm22** [comment]
Hi @martinhsv ,

Thanks a lot for your suggestion. It worked for me partially. Looking for your experties suggestion as i saw some strange behviour. 

As per your suggestion i updated the rule defination as shown below. The expection was to skip the notificationProfiles xml element from validation which is now working and data inside the element is not validating against the pattern. 

but in case if i am sending the same set of data in other xml element of the same request my expection was the request should be blocked like if i sending the same data in registration code it should be blocked. 

but i am observing the warning messeage in the logs and request is getting passed but not getting blocked. Anything i am missing here.

ModSecurity: Warning. Pattern match \"(?:/\\\\*!?|\\\\*/|[';]--|--[\\\\s\\\\r\\\\n\\\\v\\\\f]|--[^-]*?-|[^&-]#.*?[\\\\s\\\\r\\\\n\\\\v\\\\f]|;?\\\\x00)\" at XML. [file \"mod_perl\"] [line \"142\"] [id \"MSM_DIS_942440\"] [msg \"SQL Comment Sequence Detected\"] [data \"Matched Data: --D7R_Nexck3kgv- found within XML: FCM:f3AK3nt3Zd4:APA91bHvq21zkMuZcCtJ-e4oYAF0VbJgpKaPLZRwov88dpxBFQFSU6m--D7R_Nexck3kgv-NNomPDIGxCQZcAvp5ePVDFkCWAeWjLFDJoJvJ_cw_pj6DqAViXf-01yO88_wFtcYKYgju\"] [severity \"CRITICAL\"] [ver \"OWASP_CRS/3.3.0\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-sqli\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/152/248/66\"] [tag \"PCI/6.5.2\"] [tag \"paranoia-level/2\"]

"audit_data":{"messages":["Warning. Pattern match \"(?:/\\\\*!?|\\\\*/|[';]--|--[\\\\s\\\\r\\\\n\\\\v\\\\f]|--[^-]*?-|[^&-]#.*?[\\\\s\\\\r\\\\n\\\\v\\\\f]|;?\\\\x00)\" at XML. [file \"mod_perl\"] [line \"142\"] [id \"MSM_DIS_942440\"] [msg \"SQL Comment Sequence Detected\"] [data \"Matched Data: --D7R_Nexck3kgv- found within XML: FCM:f3AK3nt3Zd4:APA91bHvq21zkMuZcCtJ-e4oYAF0VbJgpKaPLZRwov88dpxBFQFSU6m--D7R_Nexck3kgv-NNomPDIGxCQZcAvp5ePVDFkCWAeWjLFDJoJvJ_cw_pj6DqAViXf-01yO88_wFtcYKYgju\"] [severity \"CRITICAL\"] [ver \"OWASP_CRS/3.3.0\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-sqli\"] [tag \"OWASP_CRS\"] [tag \"capec/1000/152/248/66\"] [tag \"PCI/6.5.2\"] [tag \"paranoia-level/2\"]"],"error_messages":["[file \"apache2_util.c\"] [line 280] [level 3] [client 172.17.0.1] ModSecurity: Warning. Pattern match \\\\\"(?:/\\\\\\\\\\\\\\\\*!?|\\\\\\\\\\\\\\\\*/|[';]--|--[\\\\\\\\\\\\\\\\s\\\\\\\\\\\\\\\\r\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\v\\\\\\\\\\\\\\\\f]|--[^-]*?-|[^&-]#.*?[\\\\\\\\\\\\\\\\s\\\\\\\\\\\\\\\\r\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\v\\\\\\\\\\\\\\\\f]|;?\\\\\\\\\\\\\\\\x00)\\\\\" at XML. [file \\\\\"mod_perl\\\\\"] [line \\\\\"142\\\\\"] [id \\\\\"MSM_DIS_942440\\\\\"] [msg \\\\\"SQL Comment Sequence Detected\\\\\"] [data \\\\\"Matched Data: --D7R_Nexck3kgv- found within XML: FCM:f3AK3nt3Zd4:APA91bHvq21zkMuZcCtJ-e4oYAF0VbJgpKaPLZRwov88dpxBFQFSU6m--D7R_Nexck3kgv-NNomPDIGxCQZcAvp5ePVDFkCWAeWjLFDJoJvJ_cw_pj6DqAViXf-01yO88_wFtcYKYgju\\\\\"] [severity \\\\\"CRITICAL\\\\\"] [ver \\\\\"OWASP_CRS/3.3.0\\\\\"] [tag \\\\\"application-multi\\\\\"] [tag \\\\\"language-multi\\\\\"] [tag \\\\\"platform-multi\\\\\"] [tag \\\\\"attack-sqli\\\\\"] [tag \\\\\"OWASP_CRS\\\\\"] [tag \\\\\"capec/1000/152/248/66\\\\\"] [tag \\\\\"PCI/6.5.2\\\\\"] [tag \\\\\"paranoia-level/2\\\\\"] [hostname \\\\\"dispatcher-ecm-demo.rnd.gemaltodigitalbankingidcloud.com\\\\\"] [uri \\\\\"/dispatcher/domains/default/users/defaultUser/applications/defaultApp/register\\\\\"] [unique_id \\\\\"ZVymQ_3bisqLPPTC9IuAtAABWAA\\\\\"]"],"handler":"proxy-server","stopwatch":{"p1":777,"p2":3259,"p3":189,"p4":607,"p5":219,"sr":49,"sw":0,"l":0,"gc":0},"response_body_dechunked":true,"producer":["ModSecurity for Apache/2.9.4 (http://www.modsecurity.org/)","OWASP_CRS/3.3.4"],"server":"WAF","engine_mode":"ENABLED"}}


original request passing
<RegisterRequest>
    <registrationCode>123456789</registrationCode>
    <notificationProfiles>
	<notificationProfile>FCM:XXXXXXXX-YYYYYYY</notificationProfile>
    </notificationProfiles>
</RegisterRequest>

modified request expected to be blocked.

<RegisterRequest>
    <registrationCode>FCM:XXXXXXXX-YYYYYYY</registrationCode>
 </RegisterRequest>

SecRuleRemoveById 942440
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*[local-name()!='RegisterRequest']|XML:/*[local-name()='RegisterRequest']/*[local-name()!='notificationProfiles'] "@rx (......)" \
    "id:XXX_942440,\
    phase:2,\
    block,\
    capture,\
    t:none,t:urlDecodeUni,\
    msg:'SQL Comment Sequence Detected',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-sqli',\
    tag:'OWASP_CRS',\
    tag:'capec/1000/152/248/66',\
    tag:'PCI/6.5.2',\
    tag:'paranoia-level/2',\
    ver:'OWASP_CRS/3.3.0',\
    severity:'CRITICAL',\
    setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}',\
    setvar:'tx.sql_injection_score=+%{tx.critical_anomaly_score}'"
