### ISSUE TITLE
Allow more data from matches and new operators to extract this data

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#293]
MODSEC-143: It would be nice to get a list of all the matches from an operator within a collection.  Additionally more info on each match would be nice (ie location in target, etc) and operators to flatten this data and extract this and other data would be helpful.  Probably easier if this was all exported so Lua could get at it easily.

Some ideas for metadata to store:
- Offset of each match 
- How many times a particular pattern matched
- Order of the match (ie did a "select" match prior to a "from"# Use a huge prequal static list of values
# Match a huge list of static phrases compiled from the rules in use

SecRule REQUEST_BODY "@pmf hugePrequalList.dat" "metacol:PM,..."
# Now check if "select" matched within 30 bytes of "from"

SecScript "foo.lua" "..."
# Rules and/or Lua would then be able to see if "select" was matched prior to
# "from" and within 30 bytes of each other, then perform some other more expensive matches
# if all this checked out.

The examples above suck, but the idea here is to be able to optimize matches.

**Comment by zimmerle** [comment]
Within v3.0 the offset of the matches are registered as part of the logging allowing the user to easily identify where the match came from. Including all the transformations applied on the content.
