### ISSUE TITLE
connection between nginx and modsecurity

### ISSUE THREAD

**Issue by sushmakummari** [SpiderLabs/ModSecurity#2936]
in multi.c example file, modsec = msc_init() is used to initiate, modsecurity, how is it connecting to nginx??

**Comment by sushmakummari** [comment]
where is the Modsecurity class defined, I am not able to find it in the repo?

**Comment by martinhsv** [comment]
@sushmakummari 

See https://github.com/SpiderLabs/ModSecurity-nginx.

See modsecurity.cc
