### ISSUE TITLE
connection between modsecurity and core rule set

### ISSUE THREAD

**Issue by sushmakummari** [SpiderLabs/ModSecurity#2937]
I could find the modsecurity and core rule set headers and .cc files but I am not able to find how the modsecurity is connecting with core rule set other than exmples provided, can anyone please let me know where the modsecurity connects with core rules set (but not in the examples)??

**Comment by martinhsv** [comment]
Hello @sushmakummari ,

How to work with individual rule sets is usually best addressed to the rule set provider (this github is for the engine itself -- coreruleset is managed separately).

There are several online guides that can be found fairly quickly. One example is Step 7 at https://www.tecmint.com/install-modsecurity-nginx-debian-ubuntu/
