### ISSUE TITLE
how correspondence between modsecurity phase(1--5) and nginx phase(1--11)?

### ISSUE THREAD

**Issue by successjian** [SpiderLabs/ModSecurity#2938]

**Comment by successjian** [comment]
i find modsecurity-nginx begins from rewrite phase, so i think just modsecurty divides into phase 1 and phase 2 to process bussiness, it is right?

**Comment by martinhsv** [comment]
Hello @successjian 

There are descriptions of the phases at:
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#phase and
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29#processing-phases
