### ISSUE TITLE
Modsecurity v3 lua script

### ISSUE THREAD

**Issue by Grayl1** [SpiderLabs/ModSecurity#2974]
Hello,

I am trying to use lua scripts for data masking in logs. Could you help me with several questions?

1. What achieves better performance SecRule with exec .lua or SecRuleScript directive?
Modsecurity Handbook v2 states that if the script path ends with .lua, ModSecurity will process the script using the embedded Lua interpreter and won't fork a new process. Is it still true for v3?

2. Is it possible to globally change for example a cookie value before writing it to audit logs?
I tried m.setvar("REQUEST_COOKIES.smth", "*") in lua script during phase 5 (and before crs) but it doesn't seem to work.

**Comment by martinhsv** [comment]
Hello @Grayl1 ,

1. I don't think you'd find a meaningful performance advantage of one mechanism compared to the other. The comment about ModSecurity v2 with Apache (regarding forking) is not meaningful in a v3 with nginx environment.

2. No. However, you can choose to copy a cookie value to a TX variable, alter that, and then choose to output that to the logs.
