### ISSUE TITLE
nginx centos 7

### ISSUE THREAD

**Issue by koteshr-tml** [SpiderLabs/ModSecurity#2978]
2023/08/26 09:45:37 [emerg] 8709#8709: dlopen() "/etc/nginx/modules/ngx_http_headers_more_filter_module.so" failed (/etc/nginx/modules/ngx_http_headers_more_filter_module.so: failed to map segment from shared object: Permission denied) in /etc/nginx/nginx.conf:9
I have loaded headers-more-nginx-module in nginx.conf and tested nginx -t its ok but  I am unable to restart nginx when I reload nginx getting the above error

**Comment by martinhsv** [comment]
Hello @koteshr-tml ,

I do not see anything in your report that is related to ModSecurity -- which is what this github is about.

Closing.
