### ISSUE TITLE
rsub Not supported in v3.x？

### ISSUE THREAD

**Issue by swzaaaaaaa** [SpiderLabs/ModSecurity#2979]
rsub Not supported in v3.x？Is there any good way to replace keywords inside the response body？

**Comment by martinhsv** [comment]
Content substitution is not (in general) supported with ModSecurity v3 with nginx -- at least not directly (some indirect ways may be possible, depending on your configuration, but probably not advisable.)

There are other tools and modules for nginx that are used for such purposes. You may want to take a look, for example, at ngx_http_sub_module.

**Comment by swzaaaaaaa** [comment]
Okay, thank you.
