### ISSUE TITLE
update the wiki page for SecRuleRemoveByID 

### ISSUE THREAD

**Issue by Guiteguit** [SpiderLabs/ModSecurity#2981]
**Error on the Wifi v3.X**

The problem is a syntax problem on the SecRuleRemoveById functionnality

**Logs and dumps**

**To Reproduce**

Trying to put the variable SecRuleRemoveById instead of SecRuleRemoveByID

**Expected behavior**

The problem is that nothing do without error but the functionnality doesn't work.

**Rule Set (please complete the following information):**

For correct the problem, just update your wiki page and replace the good sentive case in your syntax:

Replace:
`Syntax: SecRuleRemoveById ID ID RANGE ... `
by
`Syntax: SecRuleRemoveByID ID ID RANGE ...  `

**Additional context**

**Comment by martinhsv** [comment]
Hello @Guiteguit ,

The parser is set up to accept most ModSecurity keywords in a case-insensitive manner -- and that is the case for SecRuleRemoveById in particular. I have also confirmed this equivalence in a live ModSecurity v3 environment.

You may want to check what you have done.

**Comment by Guiteguit** [comment]
Hello @martinhsv ,

Hum ok because without the capital 'D', it's doesn't work in my environment so If it's take in account in other environment, it's not problem so :)

Thanks for you quick response.

**Comment by martinhsv** [comment]
@Guiteguit ,

As far as the ModSecurity itself is concerned, I don't see any way that environment could make a difference. In fact, the one ending with lower case 'd' is the 'standard' name (while allowing for case insensitivity). See:

https://github.com/SpiderLabs/ModSecurity/blob/8594cb8a7d44da6bb319e65f7d2f6715189ee247/src/parser/seclang-scanner.ll#L387

So unless you are using some sort of intermediate software (I wasn't sure if your remark 'Error on the Wifi v3.X' was just a typo or what), that shouldn't be possible.

If you want to pursue this, please report from whence you got your build, or if you are building yourself, how you did that (e.g. did you using the --enable-parser-generation option) and what version you are building.

**Comment by martinhsv** [comment]
Closing due to no further activity.
