### ISSUE TITLE
Is nginx 1.24 incompatible with 3.0.10?

### ISSUE THREAD

**Issue by xujili8691** [SpiderLabs/ModSecurity#2982]
2023/09/15 14:53:26 [notice] 115450#0: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/8/0)
2023/09/15 14:53:26 [notice] 115450#0: signal process started
2023/09/15 14:53:26 [emerg] 35919#0: module "/usr/local/nginx/modules/ngx_http_modsecurity_module.so" version 1022001 instead of 1024000 in /usr/local/nginx/conf/nginx.conf:12

nginx version: nginx/1.24.1
modsecurity-v3.0.10.tar.gz

**Comment by xujili8691** [comment]
[root@localhost nginx]# ./sbin/nginx -v
Tengine version: Tengine/3.0.0
nginx version: nginx/1.24.0

2023/09/15 14:53:26 [notice] 115450#0: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/8/0)
2023/09/15 14:53:26 [notice] 115450#0: signal process started
2023/09/15 14:53:26 [emerg] 35919#0: module "/usr/local/nginx/modules/ngx_http_modsecurity_module.so" version 1022001 instead of 1024000 in /usr/local/nginx/conf/nginx.conf:12

What is the reason for this problem? Is nginx 1.24 incompatible with 3.0.10?

**Comment by airween** [comment]
```
> 2023/09/15 14:53:26 [notice] 115450#0: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/8/0) 2023/09/15 14:53:26 [notice] 115450#0: signal process started 2023/09/15 14:53:26 [emerg] 35919#0: module "/usr/local/nginx/modules/ngx_http_modsecurity_module.so" version 1022001 instead of 1024000 in /usr/local/nginx/conf/nginx.conf:12
> 
```
> What is the reason for this problem? Is nginx 1.24 incompatible with 3.0.10?

seems like you've built your module (the [connector](https://github.com/SpiderLabs/ModSecurity-nginx)) with Nginx 1.22.1, but now you want to use that with Nginx 1.24.0.
