### ISSUE TITLE
SecRuleRemoveById inside Apache virtual host

### ISSUE THREAD

**Issue by mirawara** [SpiderLabs/ModSecurity#2986]
I have this apache configuration:
```
<LocationMatch "/pippo">
                <IfModule security2_module>
                        SecRuleRemoveById 949110 941100
                        # SecRuleEngine On
                </IfModule>
</LocationMatch>
```
In the modsecurity configuration file there is 'SecRuleEngine On". For any other location except '/pippo' Modsecurity blocks malicious requests, but for '/pippo' malicious requests are not blocked at all but only detected. Seems a bug, can you confirm or is there something I miss?

Thank you in advance.

**Comment by martinhsv** [comment]
Hello @mirawara ,

Have a look at #502 and #515 and see if those explanations help you.

**Comment by mirawara** [comment]
Hello @martinhsv, thanks for your answer.
Unfortunately, they didn't help me. I managed to disable the rules per virtual host or per path via the SERVER_NAME and REQUEST_URI variables, the SecRule directive and the ctl:removeById operator, but there is no way to disable them for virtual host plus path, such as for "server.com/test". The REQUEST_URI_RAW variable would have been perfect but is inexplicably empty. 
Instead, inside the virtual host configuration, the modsecurity directives seem to work badly or not at all. They only work in the default apache configuration.

**Comment by martinhsv** [comment]
Hello @mirawara ,

I would be surprised if using the ```ctl:ruleRemoveById``` alternative does not work as expected. If it does not, it may be a matter of rule execution order (i.e. the rule with that action needs to run before the rule that you want removed). You could try checking the debug log to see the rule execution order.

But perhaps I'm not clear on your use case. If the comments in the previous paragraph do not clarify things and you need more assistance, please provide your full configuration.

**Comment by mtso86** [comment]
Hello,

I know it is too late for the answer, but you can exclude inside directory, as below 
`<Directory /var/www/html/phpMyAdmin-5.2.2-english>
        <IfModule security2_module>
            SecRuleRemoveById '200003'
        </IfModule>
    </Directory>`

keep in mind id must be single quoted
