### ISSUE TITLE
cannot upload files such as .jpg, .jpeg, .png, .pdf, .doc

### ISSUE THREAD

**Issue by nuroji** [SpiderLabs/ModSecurity#2988]
I am using ModSecurity v3.0, and I have applied it to Ubuntu v22.4 to secure a web server.
The installation was successful, but there is an issue when the admin tries to update the website content. They cannot upload files such as .jpg, .jpeg, .png, .pdf, .doc, and so on. Is there a solution?

For example, when uploading a file, it shows: "The uploaded file was only partially uploaded."

**Comment by void-in** [comment]
What does the error load shows? If ModSecurity is blocking anything, it will be logged in the site error logs.

**Comment by nuroji** [comment]
ModSecurity: Access denied with code 200 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/etc/apache2/modsecurity.d/modsecurity.conf"] [line "64"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "Multipart parsing error: Multipart: Final boundary missing."] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "domain.com"] [uri "/wp-admin/async-upload.php"] [unique_id "1695711906"] [ref "v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1"]

**Comment by void-in** [comment]
What web server are you using? Nginx or Apache?

**Comment by nuroji** [comment]
Server version: Apache/2.4.41 (Ubuntu)

**Comment by airween** [comment]
> ```
> ModSecurity: Access denied with code 200 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/etc/apache2/modsecurity.d/modsecurity.conf"] [line "64"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "Multipart parsing error: Multipart: Final boundary missing."] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "domain.com"] [uri "/wp-admin/async-upload.php"] [unique_id "1695711906"] [ref "v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1v2070,1"]
> ```

You can disable the rule [200002](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended#L75-L76). Unfortunately it generates many false positive results.

**Comment by nuroji** [comment]
Does disabling rule 200002 affect its security?

**Comment by airween** [comment]
> Does disabling rule 200002 affect its security?

I don't think so.

The other chance is that you inspect the whole request to find the root cause. (I bet you will find a wrong behavior of multipart parser.)

**Comment by void-in** [comment]
Apart from @airween suggestion, using ModSecurity 3 with Apache used to be discouraged (not sure about the latest guidelines). It is better to use ModSecurity 2.9 with Apache and ModSecurity 3.x with nginx along with the nginx connector.

**Comment by martinhsv** [comment]
Per the comment from @void-in , ModSecurity v3 is not recommended for use with Apache -- the Apache connector required to do so is simply not considered production ready. So, yes, it continues to be the recommendation that, with Apache, to use ModSecurity v2.9.x.

(For ModSecurity implementations as a whole, the only case I can think of that causes such an issue (when the request is compliant) is if one is using size limits but with ```SecRequestBodyLimitAction ProcessPartial```. That configuration option is not recommended.
