### ISSUE TITLE
[Help] `SecAuditLogType HTTPS` is only suport with `SecAuditLogFormat JSON`？

### ISSUE THREAD

**Issue by actanble** [SpiderLabs/ModSecurity#2995]
[Help] `SecAuditLogType HTTPS` is only suport with `SecAuditLogFormat JSON`？

i tried `SecAuditLogFormat NATIVE` not active. 
and i see the code is application/json, and can't transport `ABCD text part` to https server?

what i wanted is parse some requestbody to local file stored, and i can't get the binarry data if i configure `SecAuditLogFormat  JSON`
 
https://github.com/SpiderLabs/ModSecurity/blob/135d1fa42b62393ae4652a29368e7a652139b696/src/audit_log/writer/https.cc#L55

**Comment by martinhsv** [comment]
Hello @actanble ,

Yes, ```SecAuditLogType HTTPS``` produces JSON output.

Any binary data that has been selected for logging should be included in the json log via '\x' hex encoding.

**Comment by martinhsv** [comment]
Closing due to no further activity.
