### ISSUE TITLE
Question about rule syntax

### ISSUE THREAD

**Issue by marcogiorgio** [SpiderLabs/ModSecurity#2998]
Hi,
I am trying to write a rule that blocks the incoming requests coming from some countries OR from some regions of a country. This is an example of what I currently have:

```
SecRule REMOTE_ADDR "@geoLookup" "phase:1,chain,id:10,drop,log,msg:'Blocking Country IP Address'"
SecRule GEO:COUNTRY_CODE "@pm COUNTRY1 COUNTRY2" "t:none"
SecRule REMOTE_ADDR "@geoLookup" "phase:1,chain,id:20,drop,log,msg:'Blocking Country 3 subdivisions IP Addresses'"
SecRule GEO:COUNTRY_CODE "@pm COUNTRY3" "chain"
SecRule GEO:REGION "@pm REGION1 REGION2"
```
Could you confirm that the logic/syntax is correct?
Thanks

**Comment by martinhsv** [comment]
Hello @marcogiorgio ,

GEO:COUNTRY_CODE will be a two-letter code. There is an example in the Reference Manual.

(The ModSecurity reference manual for v2 is here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29 . The information for GEO is essentially the same for both ModSecurity v2 and ModSecurity v3.)

**Comment by marcogiorgio** [comment]
Hi @martinhsv thanks for your reply, I apologize, I should have explained things more in depth:
I know that COUNTRY_CODE and REGION will be a 2 letter code.
 Assume that I'll replace these 2 vars with appropriate values, my question is more about the correctness of the actions/chains of the 2 rules: is this the correct way to implement a rule that blocks the incoming connections from COUNTRY 1-2 and from REGION 1-2 of COUNTRY 3?

**Comment by martinhsv** [comment]
Hi @marcogiorgio ,

Your 5th rule has no actions. That may cause you difficulties in at least some circumstances. I always include at least t:none or an empty string (i.e. just the two double quotes ```""```.

If you are having some difficulty other than that getting things to work, it's probably most efficient if you can provide relevant output -- especially relevant debug output (at level 9).

**Comment by marcogiorgio** [comment]
@martinhsv thanks again, I didn't include actions in the last rule because I thought it was not necessary, given this [example](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#user-content-GEO), but I'll follow your suggestion to include at least a t:none.
The rule seems to work correctly, I'll let you know if I encounter some difficulties
