### ISSUE TITLE
ModSecurity always log our "400" request ?

### ISSUE THREAD

**Issue by guldil** [SpiderLabs/ModSecurity#3000]
Hi,

We have a specific url on our site to test some values, in case of errors, the response is a 400 http code.

ModSecurity always log this as an alert...

Do we have a chance to exclude it from logging or do we have change logic from our url ?

Thanks,

Guldil

**Comment by airween** [comment]
What version do you use?

**Comment by guldil** [comment]
ModSecurity 3.0.10 + ModSecurity-nginx v1.0.3 + OWASP Core rule set.

**Comment by airween** [comment]
Could you show us a log line with that response? (400)

**Comment by guldil** [comment]
```
---SYRXoaj1---A--
[20/Oct/2023:08:45:56 +0000] 16977915563.605959 xx.xx.xx.xx 8184 xx.xx.xx.xx 81
---SYRXoaj1---B--
GET /validate-data?data=xxxxxxxxxxxxxxxxxxxxxx HTTP/2.0
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
sec-gpc: 1
sec-ch-ua-platform: "Windows"
referer: https://xxxxxxxxxxxxxx/login
sec-ch-ua-mobile: ?0
dnt: 1
x-requested-with: XMLHttpRequest
accept: text/html, */*; q=0.01
sec-ch-ua: "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-fetch-dest: empty
sec-fetch-mode: cors
host: xxxxxxxxxxxxxx
accept-encoding: gzip, deflate, br
cookie: SESS=xxxxxxxxxxxxxx; hl=fr; __zlcmid=xxxxxxxxxxxxxx
accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7

---SYRXoaj1---D--

---SYRXoaj1---F--
HTTP/2.0 400
Server: nginx
Date: Fri, 20 Oct 2023 08:45:56 GMT
Date: Fri, 20 Oct 2023 08:45:56 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: max-age=0, must-revalidate, private
Expires: Fri, 20 Oct 2023 08:45:56 GMT

---SYRXoaj1---H--

---SYRXoaj1---I--

---SYRXoaj1---J--

---SYRXoaj1---Z--
```

**Comment by guldil** [comment]
For the moment, we're on surveillance only, we haven't activated any blocking.

**Comment by airween** [comment]
If the `H` section is empty ([see documentation](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#user-content-SecAuditLogParts)), IMHO then it means the engine does not intervened. May be the response comes from the backend/application?

What happens (with the same request) if you turn off (I mean remove the module) ModSecurity?

**Comment by guldil** [comment]
Yes response come from our backend / application as i wrote first when data are invalid. I wasn't necessarily expecting ModSecurity to log calls with a 400 response in his file.

**Comment by martinhsv** [comment]
@guldil ,

You are probably using the SecAuditLogRelevantStatus configuration item. If 400 is included in the regex for that (and it is by default in modsecurity.conf-recommended), then audit logging will happen.

**Comment by airween** [comment]
@guldil - sorry for my mistake, I didn't realized the main issue. As @martinhsv wrote you have to check your `SecAuditLogRelevantStatus` directive.

**Comment by guldil** [comment]
Thanks a lot, we'll test this soon !
