### ISSUE TITLE
New Feature: Length of different parameters of the request

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#3002]
Is it possible to calculate the length (in bytes) of URL, Query, Request, Request Line and so on.

**Comment by airween** [comment]
Please see the [length](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#user-content-length) transformation in reference.

**Comment by ghost** [comment]
Thank you so much. @airween Can you please tell me how to use this transformation. Because I have never used it and there is no example regarding the same

**Comment by airween** [comment]
Please take a look - for example - to CRS rule [920520](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L1181-L1198).

`t:length` gives back the length of used target(s) in the rule, so you can match with the length(s) with operator `@gt` (or `@eq`, `@lt`...)

**Comment by martinhsv** [comment]
Closing this one as answered.
