### ISSUE TITLE
Mask the PII in response 

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#3006]
Is modsecurity capable to mask any PII (such as credit card no.) in response so that client browser will only see masked number (such as last 4 digits) and rest would be masked with 'X'

**Comment by martinhsv** [comment]
Hello @shubhagarwal14 ,

ModSecurity v2 with Apache does have some rewrite capabililty that could be used for such purposes.

There is no such capability in ModSecurity v3 with nginx. Note, however, that there are other nginx tools more expressly intended for such purposes.
