### ISSUE TITLE
Skip XML element from mod sec rule scanning from xml payload

### ISSUE THREAD

**Issue by vsharm22** [SpiderLabs/ModSecurity#3018]
Hi @martinhsv 

Thanks a lot for your suggestion inside the ticket : https://github.com/SpiderLabs/ModSecurity/issues/2929
 It worked for me partially i would say and i am creating this new ticket as i need you further experties suggestion as i saw some strange behviour and older ticket got closed.

As per your suggestion i updated the rule defination as shown below. The expection was to skip the notificationProfiles xml element from validation which is now working and data inside the element is not validating against the pattern.

but in case if i am sending the same set of data in other xml element of the same request my expection was the request should be blocked like if i sending the same data in registration code it should be blocked.

but i am observing the warning messeage in the logs and request is getting passed but not getting blocked. Anything i am missing here.

ModSecurity: Warning. Pattern match "(?:/\\!?|\\/|[';]--|--[\\s\\r\\n\\v\\f]|--[^-]?-|[^&-]#.?[\\s\\r\\n\\v\\f]|;?\\x00)" at XML. [file "mod_perl"] [line "142"] [id "MSM_DIS_942440"] [msg "SQL Comment Sequence Detected"] [data "Matched Data: --D7R_Nexck3kgv- found within XML: FCM:f3AK3nt3Zd4:APA91bHvq21zkMuZcCtJ-e4oYAF0VbJgpKaPLZRwov88dpxBFQFSU6m--D7R_Nexck3kgv-NNomPDIGxCQZcAvp5ePVDFkCWAeWjLFDJoJvJ_cw_pj6DqAViXf-01yO88_wFtcYKYgju"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/66"] [tag "PCI/6.5.2"] [tag "paranoia-level/2"]

"audit_data":{"messages":["Warning. Pattern match "(?:/\\!?|\\/|[';]--|--[\\s\\r\\n\\v\\f]|--[^-]?-|[^&-]#.?[\\s\\r\\n\\v\\f]|;?\\x00)" at XML. [file "mod_perl"] [line "142"] [id "MSM_DIS_942440"] [msg "SQL Comment Sequence Detected"] [data "Matched Data: --D7R_Nexck3kgv- found within XML: FCM:f3AK3nt3Zd4:APA91bHvq21zkMuZcCtJ-e4oYAF0VbJgpKaPLZRwov88dpxBFQFSU6m--D7R_Nexck3kgv-NNomPDIGxCQZcAvp5ePVDFkCWAeWjLFDJoJvJ_cw_pj6DqAViXf-01yO88_wFtcYKYgju"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/66"] [tag "PCI/6.5.2"] [tag "paranoia-level/2"]"],"error_messages":["[file "apache2_util.c"] [line 280] [level 3] [client 172.17.0.1] ModSecurity: Warning. Pattern match \\"(?:/\\\\\\\\!?|\\\\\\\\/|[';]--|--[\\\\\\\\s\\\\\\\\r\\\\\\\\n\\\\\\\\v\\\\\\\\f]|--[^-]?-|[^&-]#.?[\\\\\\\\s\\\\\\\\r\\\\\\\\n\\\\\\\\v\\\\\\\\f]|;?\\\\\\\\x00)\\" at XML. [file \\"mod_perl\\"] [line \\"142\\"] [id \\"MSM_DIS_942440\\"] [msg \\"SQL Comment Sequence Detected\\"] [data \\"Matched Data: --D7R_Nexck3kgv- found within XML: FCM:f3AK3nt3Zd4:APA91bHvq21zkMuZcCtJ-e4oYAF0VbJgpKaPLZRwov88dpxBFQFSU6m--D7R_Nexck3kgv-NNomPDIGxCQZcAvp5ePVDFkCWAeWjLFDJoJvJ_cw_pj6DqAViXf-01yO88_wFtcYKYgju\\"] [severity \\"CRITICAL\\"] [ver \\"OWASP_CRS/3.3.0\\"] [tag \\"application-multi\\"] [tag \\"language-multi\\"] [tag \\"platform-multi\\"] [tag \\"attack-sqli\\"] [tag \\"OWASP_CRS\\"] [tag \\"capec/1000/152/248/66\\"] [tag \\"PCI/6.5.2\\"] [tag \\"paranoia-level/2\\"] [hostname \\"dispatcher-ecm-demo.rnd.gemaltodigitalbankingidcloud.com\\"] [uri \\"/dispatcher/domains/default/users/defaultUser/applications/defaultApp/register\\"] [unique_id \\"ZVymQ_3bisqLPPTC9IuAtAABWAA\\"]"],"handler":"proxy-server","stopwatch":{"p1":777,"p2":3259,"p3":189,"p4":607,"p5":219,"sr":49,"sw":0,"l":0,"gc":0},"response_body_dechunked":true,"producer":["ModSecurity for Apache/2.9.4 (http://www.modsecurity.org/)","OWASP_CRS/3.3.4"],"server":"WAF","engine_mode":"ENABLED"}}

original request passing

123456789

FCM:XXXXXXXX-YYYYYYY

modified request expected to be blocked.

FCM:XXXXXXXX-YYYYYYY
SecRuleRemoveById 942440
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/[local-name()!='RegisterRequest']|XML:/[local-name()='RegisterRequest']/*[local-name()!='notificationProfiles'] "@rx (......)"
"id:XXX_942440,
phase:2,
block,
capture,
t:none,t:urlDecodeUni,
msg:'SQL Comment Sequence Detected',
logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',
tag:'application-multi',
tag:'language-multi',
tag:'platform-multi',
tag:'attack-sqli',
tag:'OWASP_CRS',
tag:'capec/1000/152/248/66',
tag:'PCI/6.5.2',
tag:'paranoia-level/2',
ver:'OWASP_CRS/3.3.0',
severity:'CRITICAL',
setvar:'tx.anomaly_score_pl2=+%{tx.critical_anomaly_score}',
setvar:'tx.sql_injection_score=+%{tx.critical_anomaly_score}'"

**Comment by martinhsv** [comment]
Hi @vsharm22 ,

What version of ModSecurity are you using? The tagged version of v3.0.10 (from July 25)? Or have you built ModSecurity yourself from current v3/master?

If your configuration is otherwise the same as when you posted your previous item, I would have expected the transaction that generated the message above would have resulted in a 403.

However, if you have been making other changes, you may want to review:
- have you changed to ```DetectionOnly``` ?
- it looked like in your previous issue that you were using the CRS ruleset's self-contained mode rather than anomaly scoring mode. If that has changed, then a separate rule (not 942440) would check the accumulated anomaly score and reject if necessary; you should check the debug log for what that reported
- the 'block' action that you have in 942440 will defer to whatever is action in any SecAction directive you have (i.e. 'pass' or 'deny'). You should check what you have for that.

If none of that clears things up for you, please provide more information, especially the debug log (level 9). Note that the issue template can be quite useful in listing what information is helpful for an issue report.

**Comment by martinhsv** [comment]
Closing due to no further activity.
