### ISSUE TITLE
Compilation failing with libxml-related errors (with libxml 2.12.0 - 2.12.2)

### ISSUE THREAD

**Issue by Marcool04** [SpiderLabs/ModSecurity#3023]
**Description**

Hi there,
I have been trying my hand at maintaining an Arch User Repository package for modsecurity: https://aur.archlinux.org/packages/modsecurity. For a short while now, compilation of modsecurity 3 is failing on Arch with the following:

```
mv -f audit_log/writer/.deps/libmodsecurity_la-parallel.Tpo audit_log/writer/.deps/libmodsecurity_la-parallel.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL     -DWITH_YAJL -I/usr/include/yajl  -DPCRE_HAVE_JIT -I/usr/include  -DWITH_MAXMIND  -DWITH_LUA -DWITH_LUA_5_4 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2   -g -O2 -MT libmodsecurity_la-modsecurity.lo -MD -MP -MF .deps/libmodsecurity_la-modsecurity.Tpo -c -o libmodsecurity_la-modsecurity.lo `test -f 'modsecurity.cc' || echo './'`modsecurity.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -std=c++11 -I.. -g -I../others -fPIC -O3 -I../headers -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -DWITH_YAJL -I/usr/include/yajl -DPCRE_HAVE_JIT -I/usr/include -DWITH_MAXMIND -DWITH_LUA -DWITH_LUA_5_4 -I/usr/include -I/usr/include/libxml2 -DWITH_LIBXML2 -g -O2 -MT libmodsecurity_la-modsecurity.lo -MD -MP -MF .deps/libmodsecurity_la-modsecurity.Tpo -c modsecurity.cc  -fPIC -DPIC -o .libs/libmodsecurity_la-modsecurity.o
modsecurity.cc: In constructor ‘modsecurity::ModSecurity::ModSecurity()’:
modsecurity.cc:89:5: error: ‘xmlInitParser’ was not declared in this scope
   89 |     xmlInitParser();
      |     ^~~~~~~~~~~~~
modsecurity.cc: In destructor ‘modsecurity::ModSecurity::~ModSecurity()’:
modsecurity.cc:102:5: error: ‘xmlCleanupParser’ was not declared in this scope
  102 |     xmlCleanupParser();
      |     ^~~~~~~~~~~~~~~~
make[3]: *** [Makefile:2168: libmodsecurity_la-modsecurity.lo] Error 1
make[3]: Leaving directory '/home/mark/Software/AUR_PACKAGES/modsecurity/src/build/src'
make[2]: *** [Makefile:3505: all-recursive] Error 1
make[2]: Leaving directory '/home/mark/Software/AUR_PACKAGES/modsecurity/src/build/src'
make[1]: *** [Makefile:1239: all] Error 2
make[1]: Leaving directory '/home/mark/Software/AUR_PACKAGES/modsecurity/src/build/src'
make: *** [Makefile:1049: all-recursive] Error 1
```

**Logs and dumps**

N/A

**To Reproduce**

```
git clone "https://github.com/SpiderLabs/ModSecurity/"
cd ModSecurity
git submodule init
git submodule update
./build.sh
./configure --prefix=/usr
make
```

**Expected behavior**

Successful build.

**Server (please complete the following information):**

- OS (and distro): [e.g. Linux, archlinux]
```
# uname -a
Linux t480 6.6.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 29 Nov 2023 00:37:40 +0000 x86_64 GNU/Linux
```

**Rule Set (please complete the following information):**
N/A

**Additional context**

Maybe the version of libxml2 is relevant? 

```
$ pacman -Qi libxml2
Name            : libxml2
Version         : 2.12.1-1
[clip]
Provides        : libxml2.so=2-64
```

I see there are reports on the libxml2 tracker of 2.11.0 breaking things: https://gitlab.gnome.org/GNOME/libxml2/-/issues/526. For info, the progression of changes to libxml2 on Arch can be found here: https://gitlab.archlinux.org/archlinux/packaging/packages/libxml2/-/commits/main

I'd be grateful for any help debugging this further, or for anybody's time looking into this.
Best,
Mark.

**Comment by pgnd** [comment]
building libmodsecurity on Fedora v39 & rawhide @ COPR,

 https://copr.fedorainfracloud.org/coprs/pgfed/nginx-mainline/build/6726088/

the rawhide build, with libxml2 v2.12x fails similarly as above
the F39 build, with libxml2 v2.10.x succeeds

the detailed rawhide build's log is here,

  https://download.copr.fedorainfracloud.org/results/pgfed/nginx-mainline/fedora-rawhide-x86_64/06726088-libmodsecurity/builder-live.log.gz

also, ref:

 libxml2 2.12.0 (and 2.12.1) in rawhide, with some API breaks
  https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/KGVNEKKZZ7WFXGUMONH7YSLJUOZHZQMM/

**Comment by Marcool04** [comment]
I attempted a downgrade of libxml, and confirmed that it works with the 2.11.5 release, and not with any of the 2.12.x ones

**Comment by martinhsv** [comment]
Thanks for noting this.

It looks like the maintainers of that project have made a patch very recently: https://gitlab.gnome.org/GNOME/libxml2/-/issues/642

ModSecurity is asserted to be one of the projects that now build correctly (  https://gitlab.gnome.org/GNOME/libxml2/-/issues/642#note_1936430  )

It seems likely that we (the ModSecurity project) won't need to do anything about this issue.

**Comment by pgnd** [comment]
@martinhsv 

> It seems likely that we (the ModSecurity project) won't need to do anything about this issue.

here's a still FAILed build of libmodsecurity, with libxml2.12.2:

https://download.copr.fedorainfracloud.org/results/pgfed/nginx-mainline/fedora-39-x86_64/06735554-libmodsecurity/builder-live.log.gz

i don't yet know if this is an issue of libmodsecurity build, or whether any 'downstream' fix mentioned here:

  https://gitlab.gnome.org/GNOME/libxml2/-/issues/642#note_1937004

needs be applied

**Comment by pgnd** [comment]
this additional patch -- for missing headers --

https://gitlab.archlinux.org/archlinux/packaging/packages/libmodsecurity/-/blob/main/libxml-includes.patch?ref_type=heads

appears to do the trick.

@martinhsv 
FYI, simple fix, PR ->
  https://github.com/SpiderLabs/ModSecurity/pull/

**Comment by Marcool04** [comment]
Confirmed that the patch mentioned by @pgnd,  adding `#include <libxml/parser.h>` to `modsecurity.cc` and `request_body_processor/xml.h`, allows for successful compilation of current `modsecurity` `v3/master` branch with with libxml 2.12.x on Arch Linux.

**Comment by martinhsv** [comment]
The build works again with libxml 2.12.x if using >= 2.12.3. See related PR (#3205) for some additional detail.

Closing.
