### ISSUE TITLE
How to reduce FPs from Request Missing an Accept Header (9200300) rule in the Azure Web Application Gateway (WAF)?

### ISSUE THREAD

**Issue by JacobChua12345** [SpiderLabs/ModSecurity#3028]
Hello everyone,

I oversee the monitoring of Azure WAF logs through Splunk. Currently, there's a significant volume of false positive traffic generated by Azure WAF, leading to frequent triggers of anomaly detection and creating a considerable amount of noise. The browser do show that there are Accept header when I Inspect the web page however the rule is still being trigger. Therefore, I'm seeking ways to address this issue. 

[Refer to the screenshots below]

<img width="937" alt="image" src="https://github.com/SpiderLabs/ModSecurity/assets/154485060/97d16259-0d2a-4b48-bb6c-9a3f07445f9f">

<img width="247" alt="image" src="https://github.com/SpiderLabs/ModSecurity/assets/154485060/3332be3f-ca7d-429e-a13e-9b77c77b4a1c">

My initial solution was to use Exclusion List in Azure Portal to exclude this specific type of traffic but no avail. In addition, I submitted a support ticket to Microsoft Azure to address this concern. However, the suggested solution was to disable the rule, which isn't ideal for my requirements. Disabling the rule would mean that any potentially malicious traffic might go unnoticed, as the rule wouldn't be able to flag it.

![image](https://github.com/SpiderLabs/ModSecurity/assets/154485060/7c7f2659-2fb1-4339-9fcb-430cfda53d94)

Do you have any pro tips or alternative solutions? Thanks.

**Comment by martinhsv** [comment]
Hello @JacobChua12345 ,

In some cases, it may be reasonable to disable a rule entirely per the suggestion that you received previously. Rules that do not directly identify an attack string, but merely identify something unusual can be decent candidates for such consideration.

However, it is also often a good idea to see if one can resolve an issue with false positives by limiting when the rule is executed, rather than disabling a rule entirely.

You don't specify what you mean by 'this specific type of traffic'. If there are clear conditions under which these FPs occur, then you can exclude the action of 920300 by using a new rule that checks for those conditions and then uses (for example) the ctl:ruleRemoveById action.

**Comment by JacobChua12345** [comment]
Good morning @martinhsv.

Q: What is ctl:ruleRemoveById? and how does it help to reduce/remove these FPs?

The specific type of rule I meant was the Request Missing an Accept Header. However, the web page do have Accept header.

By referencing this website: https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1751

Definition of the rule is as followed:
The rule is designed to identify and raise an alert for requests that do not include an "Accept" header, except in cases where it is an OPTIONS request or the request is coming from specific User Agents (WebKit or Android)

This is my Accept header and it obviously doesn't statisfy the rule but it is still being triggered.

<img width="652" alt="AcceptHeader" src="https://github.com/SpiderLabs/ModSecurity/assets/154485060/65bed7ce-34fe-4c3b-bcba-fa6abbf3a5bf">

If that is the case how do I solve it? I tried to exclude the Accept Header, HTTP Request Method & the Cookie but it didn't work.

**Comment by EarlRoth** [comment]
@JacobChua12345 the CoreRuleSet project is not part of Trustwave's ModSecurity engine, but a separate project run by OWASP, you might have more luck with your question on their github project [https://github.com/coreruleset/coreruleset](https://github.com/coreruleset/coreruleset)

**Comment by JacobChua12345** [comment]
@EarlRoth Alright, I have submitted a issue to coreRuleSet. Can I request to keep this issue open? Thank you.

**Comment by martinhsv** [comment]
Hello @JacobChua12345 ,

I don't think there's an advantage to keeping this item open in addition to your new one on the other repo (absent any discovery of an actual engine issue).
