### ISSUE TITLE
After using WAF forwarding, the custom header "authorization_bar" is missing

### ISSUE THREAD

**Issue by net-lin-dev** [SpiderLabs/ModSecurity#3029]
My version is: tengine-2.4.1, ModSecurityv3, modsecurity-nginx-v1.0.3. My environment is client -> modsecurity -> nginx -> app server. When the client successfully authenticates, the app server requires the client to carry the parameter "authorization_bar:xxxxx" in the HTTP header. However, after using modsecurity, I found that the client is always in an unverified state. I tried to capture packets on the client and found that the client is already carrying the parameter, but in the /var/log/modsec_audit.log of modsecurity, I found that the "authorization_bar" parameter is missing. Even setting SecRuleEngine Off does not help. Please help me with this issue.

**Comment by martinhsv** [comment]
Hello @net-lin-dev ,

I don't really follow the situation you are attempting to describe.

Please make use of the issue template to detail as much information as you can. ( You can find a link for the v3.x issue template here: https://github.com/SpiderLabs/ModSecurity/issues/new/choose )

**Comment by net-lin-dev** [comment]
Sorry for not following the format, but I have found the issue. It is not related to Modsecurity, but rather a configuration problem with nginx. Thank you again for your attention.
