### ISSUE TITLE
Body response is not logged for some requests

### ISSUE THREAD

**Issue by tigrouind** [SpiderLabs/ModSecurity#3030]
**Describe the bug**

For a reason that is unclear, the body response (the --E-- part) is not logged for some requests (while they have a response body as shown by Fiddler). Furthermore, the response header (the --F-- part) is incorrect (different than Fiddler).

**Logs and dumps**

> --23480000-A--
> [30/Dec/2023:01:09:35.067426 +0100] ZY9fvQqbJhHmwWvxrO2TTQAAAD4 127.0.0.1 62339 127.0.0.1 443
> 
> --23480000-B--
> GET https://foo/bar HTTP/1.1
> Host: fooserver.com
> Connection: keep-alive
> sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
> sec-ch-ua-mobile: ?0
> sec-ch-ua-platform: "Windows"
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
> Sec-Fetch-Site: same-origin
> Sec-Fetch-Mode: navigate
> Sec-Fetch-Dest: frame
> Referer: https://foo/bar
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en,en-US;q=0.9,de-DE;q=0.8,de;q=0.7
> Cookie: ...
> 
> --23480000-F--
> HTTP/1.1 200 OK
> Upgrade: h2,h2c
> Connection: Upgrade
> 
> --23480000-Z--

**What is returned by Fiddler**

Request header : same
Response header:
> HTTP/1.1 200 OK
> Content-Type: text/html; charset=utf-8
> Set-Cookie: ...
> Cache-Control: no-cache
> Connection: Close
> Date: Sat, 30 Dec 2023 00:06:33 GMT
> Expires: Thu, 29 Oct 1998 17:04:19 GMT
> Pragma: no-cache
> Set-Cookie: ...

Response body:
> \<html\>  \<head\> ...

**Example of one request correctly logged**

> --be180000-A--
> [30/Dec/2023:01:09:32.239908 +0100] ZY9fvAqbJhHmwWvxrO2TSQAAAD8 127.0.0.1 62326 127.0.0.1 443
> 
> --be180000-B--
> POST https://foo/bar HTTP/1.1
> Host: fooserver.com
> Connection: keep-alive
> Content-Length: 357
> sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
> sec-ch-ua-mobile: ?0
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
> Content-Type: text/xml
> Accept: application/xml, text/xml, */*; q=0.01
> X-Requested-With: XMLHttpRequest
> SOAPAction: login
> sec-ch-ua-platform: "Windows"
> Origin: https://foo/bar
> Sec-Fetch-Site: same-origin
> Sec-Fetch-Mode: cors
> Sec-Fetch-Dest: empty
> Referer: https://foo/bar
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en,en-US;q=0.9,de-DE;q=0.8,de;q=0.7
> Cookie: ...
> 
> --be180000-C--
> \<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"\> ...
> 
> --be180000-F--
> HTTP/1.1 200 OK
> X-Frame-Options: SAMEORIGIN
> Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
> CACHE-CONTROL: no-cache
> EXPIRES: Thu, 29 Oct 1998 17:04:19 GMT
> PRAGMA: no-cache
> CONTENT-LENGTH: 543
> Keep-Alive: timeout=5, max=98
> Connection: Keep-Alive
> Content-Type: text/xml; charset=UTF-8
> 
> --be180000-E--
> \<?xml version="1.0" encoding="UTF-8" ?\> ...

**Expected behavior**

The body response and header are always logged, with same content as what is shown by Fiddler.

**Server**
 - ModSecurity : 2.9.7
 - WebServer: Apache/2.4.58 (Win64) OpenSSL/3.1.3
 - OS : Windows 10.0.14393

**Additional context**

I have enabled logs with SecDebugLogLevel 9
The only relevant lines I see : 

> Starting phase REQUEST_HEADERS
> ...
> Rule returned 0.
> No match, not chained -> mode NEXT_RULE.
> Input filter: This request does not have a body.
> Starting phase REQUEST_BODY.
> ...
> Rule returned 1.
> Match -> mode NEXT_RULE.
> Match, intercepted -> returning.

I have set the following parameters while trying to make it work :

> SecRuleEngine On
> SecAuditEngine On
> SecResponseBodyAccess On
> SecStreamInBodyInspection On
> SecStreamOutBodyInspection On
> SecResponseBodyMimeType text/plain text/html text/xml application/xml application/json application/x-www-form-urlencoded null
> SecDisableBackendCompression On
> SecAuditLogParts ABCEFZ

**Comment by tigrouind** [comment]
The request body and header is logged when [registering the output filter](https://github.com/SpiderLabs/ModSecurity-apache/blob/master/src/mod_security3.c#L593) with AP_FTYPE_CONNECTION instead of AP_FTYPE_CONTENT_SET.

The reason is that these requests are handled by a custom apache module (from a third party company). Upon handling the request, it removes all registered output filters which types are below AP_FTYPE_CONNECTION. Because of that, the output filters registered as AP_FTYPE_CONTENT_SET are never called.

Additionally, this module will add some custom headers after the request is processed (at a late stage). That is why they looks incomplete regarding what is logged by Fiddler.

**Comment by martinhsv** [comment]
Thanks, @tigrouind , for the update. It may prove helpful to others seeing a similar issue.
