### ISSUE TITLE
modsecurity.org is not available: 502 Proxy Error

### ISSUE THREAD

**Issue by Daijobou** [SpiderLabs/ModSecurity#3033]
For https://www.modsecurity.org/ I get this:

> Proxy Error
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request [GET /](https://www.modsecurity.org/).
> 
> Reason: DNS lookup failure for: slr-mod-web-elk-01.trustwave.com

**Comment by martinhsv** [comment]
Hello @Daijobou ,

It works for me. Would you like to try it again -- there may have been a temporary issue.
