### ISSUE TITLE
ModSecurity blocks ERDDAP queries containing '(' and ')' characters

### ISSUE THREAD

**Issue by LorenzoCorgnati** [SpiderLabs/ModSecurity#3077]
I have installed ModSecurity on a XUbuntu 22.04 virtual machine running ERDDAP and ncWMS for data distribution.
I installed ModSecurity viai apt install libapache2-mod-security2 and then I enabled it via a2enmod security2
I have then installedOWASP Core ùruel Set v3.3.0.

While running ERDDAP I noticed that the queries for requesting data were blocked if containing '(' or ')' characters.

Is this a bug or should I set a rule for this? If the latter is the case, how the rule should be set?

Thanks

**Comment by airween** [comment]
Hi @LorenzoCorgnati,

thanks for reporting. I'm afraid this isn't a ModSecurity issue, rather a (so-called) "false positive" of CRS.

Under the CRS Github issue page you can open a [new issue](https://github.com/coreruleset/coreruleset/issues/new?assignees=&labels=%3Aheavy_plus_sign%3A+False+Positive&projects=&template=01_false-positive.md&title=). Please follow the template and give as many information as you can (without any sensitive data).

I'm going to close this issue, but feel free to re-open it if you think it's a ModSecurity related problem.

**Comment by LorenzoCorgnati** [comment]
Dear @airween,
thanks for the response.
Betst
