### ISSUE TITLE
SecStatusEngine should be "Off" in modsecurity.conf-recommended

### ISSUE THREAD

**Issue by fzipi** [SpiderLabs/ModSecurity#3085]
**Describe the bug**

v2 states that
```
# NB: As of April 2022, there is no longer any advantage to turning this
# setting On, as there is no active receiver for the information.
```
and has the setting turned off for in https://github.com/owasp-modsecurity/ModSecurity/blob/705002be2ba23b01bd9c895a8d01ebd9fd141ceb/modsecurity.conf-recommended#L239

But v3 has it enabled in https://github.com/owasp-modsecurity/ModSecurity/blob/4e4f3291ad2f65df7b945d3fdc4ef67d6fcc631d/modsecurity.conf-recommended#L284.

**Expected behavior**

Both should be in sync, and turned off.

**Comment by dune73** [comment]
Thanks for pointing this out.
