### ISSUE TITLE
SecAuditLogPart 'E' is logged even if it is not configured

### ISSUE THREAD

**Issue by rahulthackkar** [SpiderLabs/ModSecurity#3113]
Hello Team,

I have enabled only few parts of audit log to be logged.

_SecAuditLogParts AHZ_

But still part 'E' is being logged.

```
--2f30c324-A--
[26/Mar/2024:05:28:01.867837 +0000] ZgJbtUFThpcR0UJWIHSyaAAAAU4 51.161.54.5 9493 172.31.1.33 443
--2f30c324-E--

--2f30c324-H--
Apache-Error: [file "mod_proxy_fcgi.c"] [line 1006] [level 3] [status 70007] AH01075: Error dispatching request to : (polling)
Apache-Handler: proxy:fcgi://mydomain.com
Stopwatch: 1711430581763470 300104389 (- - -)
Stopwatch2: 1711430581763470 300104389; combined=2648, p1=722, p2=1419, p3=109, p4=190, p5=208, sr=133, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.5 (http://www.modsecurity.org/); OWASP_CRS/3.3.2.
Server: Apache
Engine-Mode: "DETECTION_ONLY"

--2f30c324-Z--
```

**Comment by dune73** [comment]
Please upgrade to the latest ModSecurity version of the 2.9.x line and report back if that solves your problem.

**Comment by rahulthackkar** [comment]
It is 2.9.5-1


```
root@hostname:/# dpkg -l | grep libapache2-mod-security2
ii  libapache2-mod-security2           2.9.5-1                                      amd64        Tighten web applications security for Apache
root@hostname:/#
```

**Comment by dune73** [comment]
I see this in the log line above. Please upgrade to 2.9.7 and then check again.

**Comment by rahulthackkar** [comment]
Do I need to build it from source or is it available in apt repository? latest version of 2.9.x?
I am using ubuntu 22.04.

**Comment by rahulthackkar** [comment]
As If I build it from source, I need to manually configure rules, loading module in apache etc.. I can do it , but if I can install it using simple command like 'apt install libapache2-mod-security2' what I previously did it will be helpful.

As it automatically installs crs , creates appropriate directory /etc/modsecurity and appropriate conf inside it which I can directly use without any additional configuration.

**Comment by airween** [comment]
You should try this non-official Debian/Ubuntu repository:

https://modsecurity.digitalwave.hu

**Comment by rahulthackkar** [comment]
> I see this in the log line above. Please upgrade to 2.9.7 and then check again.

Thanks, By upgrading it to 2.9.7, this issue is fixed.
