### ISSUE TITLE
docs, contributing: shorten description to improve flow for GitHub contributors, rewrite for owasp

### ISSUE THREAD

**Issue by eflanagan0** [SpiderLabs/ModSecurity#3130]
**Describe the bug**

This project's repository description exceeds the 350 character limit imposed by GitHub. That leads to an error when forking the repository in the web UI.
Furthermore, the description still mentions Trustwave.

## desired change

- simpler copy < 350 characters that captures the renewed OWASP stewardship of ModSecurity

**Comment by airween** [comment]
Hi @eflanagan0,

thanks for reporting this.

Could you help me to point that where is the Github documentation which describes the mentioned limit? I tried to find that but I'm a bit confused, because there are many different values.

Thanks!

**Comment by eflanagan0** [comment]
sure thing @airween! 
As an admin, you can edit the description using the gear icon visible from the home page of the project.
On my fork, I was able to see that at https://github.com/eflanagan0/ModSecurity.
<img width="359" alt="Screen Shot 2024-04-23 at 4 59 40 PM" src="https://github.com/owasp-modsecurity/ModSecurity/assets/163922304/3bd6e8c6-9e7e-401c-bb45-cc76a888ba83">

**Comment by airween** [comment]
> sure thing @airween! As an admin, you can edit the description using the gear icon visible from the home page of the project. 

Thanks, I already found that - I need the Github documentation where I can find the limit exactly (eg. that you mentioned, 350 characters).

**Comment by eflanagan0** [comment]
Ah, my apologies @airween; I misread your question.
I couldn't find any documentation that explicitly mentions the 350 character limit.
They have some for topics which mention character limits: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics.

You can see the inline documentation if you attempt to create a new repository and copy and paste the current description (I took this from the wiki)
> ModSecurity is an open source, cross platform web application firewall (WAF) engine donated to OWASP in 2024. It has a robust event-based programming language which provides protection from a range of attacks against web applications and allows for HTTP traffic monitoring, logging and real-time analysis. Securing tens of millions of domains, ModSecurity is the most widely deployed WAF engine in existence.


<img width="991" alt="image" src="https://github.com/owasp-modsecurity/ModSecurity/assets/163922304/0ac64a30-2856-470c-aa31-ba83c14035f8">

**Comment by airween** [comment]
Hi @eflanagan0, no worries, and thanks! Now it's clear: it's a "lazy" (undocumented) rule :smile:.

Never mind, thanks for letting know this, I'm going to reduce the length of the text.

**Comment by airween** [comment]
Thanks again, I modified - closing the issue.
