### ISSUE TITLE
How to disable audit logging of some HTTP_CODE?

### ISSUE THREAD

**Issue by ShaiMagal** [SpiderLabs/ModSecurity#3147]
Hi,

we have in folder _/var/log/apache2/modsec/www-data/YYYYMMDD/*_ a lot of http_codes logs what we don't care.

For any internal reasons, we don't want to log http_code for example **406** (because it makes about **90%** of logs in this folder)

It is logging from rules (not our), is possible to remove this logging for one specific http_code for example **406**?

NOTE:
**406 is only example, we use this http code for internal reasons.**

**Logs and dumps**

Audit log (_/var/log/apache2/modsec_audit.log_):
`XXX XXX - - [21/May/2024:14:46:58.119386 +0200] "GET /?sdasdasdasdasdasdasddas HTTP/2.0" 406 249 "-" "-" ZkyXwnl54haRrMnxz27mkQAAzAs "-" /www-data/20240521/20240521-1446/20240521-144658-ZkyXwnl54haRrMnxz27mkQAAzAs 0 1743 md5:b8111bdfcaf29b8a0ad246ca13fb26fe`
Detail log:
```
--6397c64b-A--
[21/May/2024:14:46:58.119186 +0200] ZkyXwnl54haRrMnxz27mkQAAzAs XXX 57709 XXX 443
--6397c64b-B--
GET /?sdasdasdasdasdasdasddas HTTP/2.0
Pragma: no-cache
Cache-Control: no-cache
Sec-Ch-Ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9,cs;q=0.8
Priority: u=0, i
Host: XXX
GEOIP_ADDR: XXX
GEOIP_CONTINENT_CODE: XXX
GEOIP_COUNTRY_CODE: XXX
GEOIP_COUNTRY_NAME: XXX

--6397c64b-F--
HTTP/1.1 406 Not Acceptable
Content-Length: 249
Connection: close
Content-Type: text/html; charset=iso-8859-1
Date: Tue, 21 May 2024 12:46:58 GMT
Server: Apache

--6397c64b-E--
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>Not Acceptable</h1>
<p>An appropriate representation of the requested resource could not be found on this server.</p>
</body></html>

--6397c64b-H--
Stopwatch: 1716295618111722 7610 (- - -)
Stopwatch2: 1716295618111722 7610; combined=3446, p1=721, p2=2355, p3=49, p4=156, p5=165, sr=126, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.5 (http://www.modsecurity.org/); OWASP_CRS/3.3.5.
Server: Apache
Engine-Mode: "DETECTION_ONLY"

--6397c64b-Z--
```

**To Reproduce**

**Expected behavior**

Stop logging this HTTP CODE 406.

**Server (please complete the following information):**
 - ModSecurity 2.9.5
 - Apache 2.4.59
 - Ubuntu 22.04 LTS

**Rule Set (please complete the following information):**
 - OWASP Core Rule Set 3.3.5

**Additional context**

**Comment by airween** [comment]
Hi @ShaiMagal,

perhaps I would try something like this:

```
SecRule RESPONSE_STATUS "@within 406" \
    "id:1000,\
    phase:3,\
    t:none,\
    nolog,\
    pass,\
    ctl:auditEngine=Off"
```

References:
* [RESPONSE_STATUS](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)#response_status)
* [@within](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)#within)
* [ctl](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v2.x)#user-content-ctl)

I would put it before the other rules, eg. as I see you use CRS, then you can add it into `REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf` file.

**Comment by ShaiMagal** [comment]
Hi @airween,

thank you for example, it's not working, BUT, it was **very** **helpful**, and this is working example for us :)
`SecRule RESPONSE_STATUS "@streq 406" "id:XXX,phase:5,t:none,nolog,pass,ctl:auditEngine=Off"`

Thank you again, you saved my day! :)
