### ISSUE TITLE
Not Working with IIS

### ISSUE THREAD

**Issue by hadiloghman** [SpiderLabs/ModSecurity#3167]
Hi

Ibuilt the libModSecurity.dll and add it to my IIS modules in windows 2019. After resetting the IIS I got Service Unavailable when I checked the eventviewer I had this error

Failed to find the RegisterModule entrypoint in the module DLL C:\inetpub\ModSecurity\libModSecurity.dll.  The data is the error.

**Comment by airween** [comment]
Hi @hadiloghman,

thanks for reporting - but I'm a bit confused.

You wrote you built `libmodsecurity.dll` (which came from libmodsecurity3 source code), but added label `2.x`.

Also: libmodsecurity3 is a library, it needs a connector for a specified HTTP server that you want to use it with. Do you have a connector for IIS?

**Comment by hadiloghman** [comment]
Sorry for the wrong version that I selected.

No, I didn't use any connector. I registered the DLL in the modules of IIS. Is there a need to add a connector? I didn't see it in the docmentation

**Comment by airween** [comment]
No worries. [Here](https://github.com/owasp-modsecurity/ModSecurity?tab=readme-ov-file#it-is-no-longer-just-a-module) is the relevant part in the documentation:

_"This library is consumed by what we have termed 'Connectors' these connectors will interface with your webserver and provide the library with a common format that it understands. Each of these connectors is maintained as a separate GitHub project. For instance, the Nginx connector is supplied by the ModSecurity-nginx project (https://github.com/owasp-modsecurity/ModSecurity-nginx)."_

**Comment by hadiloghman** [comment]
Dear @airween

Thanks for the link and description
I couldn't find any connector for IIS, can I use any other connector for IIS?

**Comment by airween** [comment]
No, actually there is only one (known) stable connector for this library, only for Nginx (see the link in quoted text).

There is a very beta version for Apache, but no other (published) connector.

**Comment by hadiloghman** [comment]
So I should use ModSecurity 2 for IIS. Am I right?

**Comment by airween** [comment]
Well, I don't know - I'm not sure about that. Few months ago I tried to run some part of code (of mod_security2) which is related to IIS, but as I remember it was broken. I don't know in which state is the IIS support.

@marcstern do you know anything about that?

**Comment by hadiloghman** [comment]
Dear @airween 
Thanks for your comments. You save my time struggling with version 3.
I have another issue with version 2. It does not log and when I check the eventviewer I saw this error 
"The description for Event ID 1 from source ModSecurity cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer."
do you know what causes this error? I use version 2.9.7

**Comment by airween** [comment]
Unfortunately I have never used mod_security2 on Windows (neither Apache), so I'm afraid I can't help you in this.

Perhaps @marcstern.

**Comment by hadiloghman** [comment]
Thanks @airween for your comments. I can finally add modsecurity 2.9.7 to IIS and enable the Logs. Thanks, guys for your great job.

**Comment by airween** [comment]
@hadiloghman - glad to see your issue has solved. I'm going to close this issue.

**Comment by podorozhkin** [comment]
Hi @airween  I noticed that in the latest ModSecurity v 3.0.13 release Windows port has been added and I was even able to produce binaries following the instructions,  however I see that no IIS connector still exists for it.  Are there plans to implement it and if so any estimations on that? Thanks in advance

**Comment by mike-nelson** [comment]
I have seen a lot of reference to ModSecurity being cross platform and working with IIS, and even in intro for modsec3 saying that is the whole point of the rewrite to unshackle from Apache. But without a connector for IIS it is not gonna work is it??

**Comment by mike-nelson** [comment]
So, if I am reading correctly, modsec2 does work with IIS, but no modsec3. I can't find any links anywhere to any downloads for IIS. Does anyone have a link?

**Comment by mike-nelson** [comment]
Ah found it! Might be good to mention on the modsecurity homepage which platforms are supported on v2 and v3. https://github.com/owasp-modsecurity/ModSecurity/releases/tag/v2.9.7

**Comment by airween** [comment]
> Hi @airween I noticed that in the latest ModSecurity v 3.0.13 release Windows port has been added and I was even able to produce binaries following the instructions, however I see that no IIS connector still exists for it. Are there plans to implement it and if so any estimations on that? Thanks in advance

@podorozhkin sorry for the late answer - currently there is no plan to add IIS port because of the lack of available resources. If you had capacity/knowledge to add that, it would be awesome. Btw fixing the Apache connector is more important.

**Comment by airween** [comment]
> Ah found it! Might be good to mention on the modsecurity homepage which platforms are supported on v2 and v3. https://github.com/owasp-modsecurity/ModSecurity/releases/tag/v2.9.7

Hi @mike-nelson, unfortunately we don't have any good description about how to make an IIS module (from mod_security2). If you start to make your own, could you make a short brief about how to done that?

**Comment by mike-nelson** [comment]
> > Ah found it! Might be good to mention on the modsecurity homepage which platforms are supported on v2 and v3. https://github.com/owasp-modsecurity/ModSecurity/releases/tag/v2.9.7
> 
> Hi @mike-nelson, unfortunately we don't have any good description about how to make an IIS module (from mod_security2). If you start to make your own, could you make a short brief about how to done that?

Yeah, I am sure that would be a worthwhile thing to do but may be outside my capability, probably not something I can do, but I will certainly update you if I go down that track.
