### ISSUE TITLE
None human readable AuditLog examples.

### ISSUE THREAD

**Issue by s3rj1k** [SpiderLabs/ModSecurity#3168]
In  [Concurrent Audit Log Format section](https://github.com/owasp-modsecurity/ModSecurity/wiki/ModSecurity-2-Data-Formats#concurrent-audit-log-format) examples of log entries are not human readable.

```
$LOGGING&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;HOME/20081128/20081128&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;1414/20081128&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;141417&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;
  egDKy38AAAEAAAyMHXsAAAAA
```

vs

```
$LOGGING-HOME/20081128/20081128-1414/20081128-141417-egDKy38AAAEAAAyMHXsAAAAA
```

and

```
192.168.0.111 192.168.0.1 &amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59; &amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59; &amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;91&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;28/Nov/2008&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;58&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;15&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;58&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;06&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;58&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;32 +0000&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;93&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;  &amp;amp&#59;amp&amp;&#35;59&#59;quot&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;GET /?p&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;61&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;\\ HTTP/1.1&amp;amp&#59;amp&amp;&#35;59&#59;quot&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59; 200 69 &amp;amp&#59;amp&amp;&#35;59&#59;quot&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;&amp;amp&#59;amp&amp;&#35;59&#59;quot&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59; &amp;amp&#59;amp&amp;&#35;59&#59;quot&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;&amp;amp&#59;amp&amp;&#35;59&#59;quot&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59; NOfRx38AAAEAAAzcCU4AAAAA  &amp;amp&#59;amp&amp;&#35;59&#59;quot&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;&amp;amp&#59;amp&amp;&#35;59&#59;quot&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59; /20081128/20081128&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;1506/20081128&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;150632&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;45&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;NOfRx38AAAEAAAzcCU4AAAAA  0 1183 md5&amp;amp&#59;amp&amp;&#35;59&#59;&amp;amp&#59;&amp;&#35;35&#59;35&amp;&#35;59&#59;58&amp;amp&#59;&amp;&#35;35&#59;59&amp;&#35;59&#59;ffee2d414cd43c2f8ae151652910ed96
```

vs

```
192.168.0.111 192.168.0.1 - - [28/Nov/2008:15:06:32 +0000] "GET /?p=\\ HTTP/1.1" 200 69 "-" "-" NOfRx38AAAEAAAzcCU4AAAAA "-" /20081128/20081128-1506/20081128-150632-NOfRx38AAAEAAAzcCU4AAAAA 0 1183 md5:ffee2d414cd43c2f8ae151652910ed96
```

**Comment by airween** [comment]
Hi @s3rj1k,

please follow our issue [template](https://github.com/owasp-modsecurity/ModSecurity/blob/v3/master/.github/ISSUE_TEMPLATE/bug-report-for-version-2-x.md) when you open a new issue.

Unfortunately I'm not sure anyone can help with these shared information, so I'm closing this issue.

You can click [here](https://github.com/owasp-modsecurity/ModSecurity/issues/new?assignees=&labels=2.x&projects=&template=bug-report-for-version-2-x.md&title=) (or if your engine is libmodsecurity3 [here](https://github.com/owasp-modsecurity/ModSecurity/issues/new?assignees=&labels=3.x&projects=&template=bug-report-for-version-3-x.md&title=)) and fill the template correctly.

Thanks.

**Comment by s3rj1k** [comment]
@airween How is that template relevant to documentation text encoding error?

**Comment by s3rj1k** [comment]
**Describe the bug**

Documentation text encoding error!

**Logs and dumps**

None

**To Reproduce**

Read the manual at [link](https://github.com/owasp-modsecurity/ModSecurity/wiki/ModSecurity-2-Data-Formats#concurrent-audit-log-format).

**Expected behavior**

I expect human readable text encoding in manual and not garbled text.

**Server (please complete the following information):**

Irrelevant.

**Rule Set (please complete the following information):**

Irrelevant.


**Additional context**

None.

**Comment by s3rj1k** [comment]
@airween Something like the above?

**Comment by airween** [comment]
> @airween Something like the above?

No.

Please attach these details:

* relevant config, or the full, eg `grep -v "^#" /path/to/modsecurity.conf | grep -v "^$"`
* a `curl` request which with anyone can reproduce the issue
* your server version is not irrelevant at all; please describe your accurate version, eg. 2.9.X; more details - more help for us, eg. you can share that you use it from source or your OS package (then you can share your OS version too)

**Comment by s3rj1k** [comment]
@airween You serious? I don't have any setup, I just went reading on documentation, I see a huge level on incompetence from you and I am not planing to use modsecurity after seeing that you struggle to understand that sometimes people read documentation **before** using the product, hence the version of product is irrelevant and not sure how you can reproduce **bad documentation** with curl to application.

**Comment by airween** [comment]
Ah, sorry, now I see you thought about the project documentation, not a real issue.

Thanks, we will fix it soon.
