### ISSUE TITLE
Bazel build on Windows

### ISSUE THREAD

**Issue by varkey98** [SpiderLabs/ModSecurity#3186]
**Describe the bug**
Not exactly a bug, more like a help request. I'm trying to build a simple c++ client which uses Modsec on windows. I want to use bazel for building my client. I have followed the steps listed [here ](https://github.com/owasp-modsecurity/ModSecurity/blob/v3/master/build/win32/README.md?plain=1#L36) for building the dll and it works fine. This is the bazel rule I have added for importing modsec to my client.
```
cc_import(
    name = "libmodsecurity",
    hdrs = glob(["modsecurity/**/*.h"]),
    static_library = "modsecurity/libModSecurity.lib",
    visibility = ["//visibility:public"],
)
```
where I've copied all the headers and `libModSecurity.lib` to a folder called `modsecurity` in the build directory. 

This is my main
```
#include<iostream>

#include "modsecurity/modsecurity.h"
#include "modsecurity/rules_set.h"

const char *request = "" \
    "GET /index.html?param1=value1&param2=value1&param3=value1 HTTP/\n" \
    "AuThOrIzAtIoN: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==\n" \
    "Host: localhost\n" \
    "Content-Length: 27\n" \
    "Content-Type: application/x-www-form-urlencoded\n";

int main() {
  std::cout<<"Hello world!\n";
  modsecurity::actions::disruptive::AllowType TYPE;
  modsecurity::ModSecurity* modsec = new modsecurity::ModSecurity();
  modsecurity::RulesSet* rules = new modsecurity::RulesSet();
  // modsecurity::Rules* rules = new modsecurity::Rules();
  modsec->setConnectorInformation("ModSecurity-test v0.0.1-alpha (ModSecurity test)");


    std::string json("");
    const char *err = NULL;
    int ret = 0;

    ret = modsec->processContentOffset(request, strlen(request),
        "o0,4v64,13v114,4v130,14v149,12t:lowercase", &json, &err);

    if (ret >= 0) {
        std::cout << json << std::endl;
    } else {
        std::cout << err << std::endl;
    }

  std::cout<<"Hello world!\n";
}
```

**To Reproduce**

1. Please clone this repo, https://github.com/varkey98/cppclient/blob/main/BUILD 
2. Run `.\bazel-6.4.0-windows-x86_64.exe run //:hello_world-load-dll-at-runtime`

**Expected behavior**

It works just fine and prints the output of `processContentOffset`

**Actual behavior**

It just exits without printing any error. 
**Additional context**

It sometimes works fine without any issues after hitting bazel run & bazel clean combination a number of times, but not a consistent behavior.

edit: Even the hello world statements are not getting printed

**Comment by varkey98** [comment]
Update:
on modifying my import rule to this, it started working
```
cc_import(
    name = "libmodsecurity",
    hdrs = glob(["modsecurity/**/*.h"]),
    interface_library = "modsecurity/libModSecurity.lib",
    shared_library = "modsecurity/libModSecurity.dll",
    visibility = ["//visibility:public"],
)
```
Would be great if someone can confirm what I'm doing is indeed the correct way. Not very familiar with bazel as well, but want to learn how to use it as that's we use in my organization.

**Comment by airween** [comment]
@eduar-hte - could you help in this?

**Comment by eduar-hte** [comment]
We're mostly a MSBuild/CMake shop for C/C++ code, so I'm not a bazel expert. However, I think your approach is correct, as [cc_import](https://bazel.build/reference/be/c-cpp#cc_import) rules are intended for C/C++ precompiled  libraries, which would be the case for libModSecurity as it's built using CMake on Windows.

My only recommendation would be to organize the modsecurity headers, import library and shared library into an `install` like directory structure as follows:

```
project/
├── WORKSPACE
├── BUILD
├── main.cpp
└── install/
    ├── include/
    │   └── modsecurity (files from headers/modsecurity)
    ├── lib/
    │   └── libModSecurity.lib
    └── bin/
        └── libModSecurity.dll
```

The `install` directory would be useful to integrate other precompiled 3rd party libraries. Most CMake libraries have support for an `install` step that would generate and copy these files into a specified target path. However, the current Windows CMake build configuration doesn't have this yet, and you have to do it manually.

Then the `cc_import` rule for `modsecurity` would be:

```bazel
cc_import(
    name = "modsecurity",
    hdrs = glob(["install/include/modsecurity/**/*.h"]),
    includes = ["install/include"],
    interface_library = "install/lib/libModSecurity.lib",
    shared_library = "install/bin/libModSecurity.dll",
    visibility = ["//visibility:public"],
)
```

Finally, I'd also check with your organization in case they have already guidelines on how to build and integrate 3rd party libraries not build using Bazel (and not rely on having a specific precompiled version).

**Comment by varkey98** [comment]
Got it, thanks a lot @airween @eduar-hte. Closing this issue :)
