### ISSUE TITLE
[FEATURE] Add a new `t:removeSQLComments` transformation

### ISSUE THREAD

**Issue by fzipi** [SpiderLabs/ModSecurity#3195]
## Summary

Writing rules for SQLi is difficult enough. Also, there could be plenty of evasions by using `/**/` inside partial SQL queries.

### Basic example

- Raw: 
```sql
select tags from tags WHERE 1=0 OR'{"name":"asd"}'?|/**/array/**/[/**/'a'/**/,'name'];
```
- With `t:removeSQLComments` applied: 
```sql
select tags from tags WHERE 1=0 OR'{"name":"asd"}'?|array['a','name'];
```

### Motivation

By creating a new `t:removeSQLComments` transformation, that substitutes everything commented out using `/**/`, regular expressions to catch injections will get way simpler and cover more cases.

Caveat: some databases will interpret commands inside comments. Luckily this can be handled by an specific rule for this case.

### Edge cases

- we need to review if space needs to be substituted for the actual command to work, or we can remove everything that is commented. Example:
`WHERE 1=0 OR a=/**/b` -> `WHERE 1=0 OR a=b`
vs.
`WHERE 1=0 OR a=/**/b` -> `WHERE 1=0 OR a= b` (`/**/` is substituted for a "space" character ` ` )

**Comment by marcstern** [comment]
Isn't it redundant with replaceComments/removeCommentsChar/removeComments?

**Comment by fzipi** [comment]
🤦 Good question. I need to test it. For now I'm closing.
