### ISSUE TITLE
Mod3 ./configuration show missing 

### ISSUE THREAD

**Issue by crs-web** [SpiderLabs/ModSecurity#3196]
**Describe the bug**

The error appears even after having the libpcre2-dev. 

checking for libpcre config script... no
configure: *** pcre library not found.
configure: error: pcre library is required

**Comment by crs-web** [comment]
Done after libpcre3 
Thank you.

**Comment by airween** [comment]
Hi @crs-web,

thanks for reporting.

First of all: could you explain which version do you use? You've added the title for this issue "Mod3" but later you added label `2.x`.

Anywhere, yes, both engines (mod_security2 and libmodsecurity3) still requires the "old" PCRE library, aka PCRE3, even if the PCRE2 (the new version) is already installed.

I saw you installed the old version, but I suggest you to use the new version (PCRE2).

You only need to append the necessary configure option:

```bash
./configure --with-pcre2
```
(and the others, what you want).

This will prepare the build environment to compile the code with PCRE2.

This is the expected procedure for both version.
