### ISSUE TITLE
after scan coreruleset-main.zip by Microsoft defender for business version.

### ISSUE THREAD

**Issue by langenggithub** [SpiderLabs/ModSecurity#3201]
I got a message  " Malware incident on one endpoint ,Dirtelti' backdoor was prevented"
Microsoft defender has detected a computer virus.
The name is Chopper ,high-severity malware. https://www.virustotal.com/gui/file/4a8d05c406d87672d2129f530739e44098cd53e14707730dd337f23015338552
Does anyone have the same situation? 

thanks for reply.

**Comment by langenggithub** [comment]
scan by virutotal website.
https://www.virustotal.com/gui/file/2829be8d468eca58fd99579176a94278a1318f40d8444871db9f240fe2b2e1a3?nocache=1
https://www.virustotal.com/gui/file/4a8d05c406d87672d2129f530739e44098cd53e14707730dd337f23015338552
any help!?

**Comment by airween** [comment]
_after scan coreruleset-main.zip_ - perhaps you should have open this issue under [Coreruleset](https://github.com/coreruleset/coreruleset) repository - this is the ModSecurity repository :smiley:.

If I'm right, the "infected" file is [933111.yaml](https://github.com/coreruleset/coreruleset/blob/main/tests/regression/tests/REQUEST-933-APPLICATION-ATTACK-PHP/933111.yaml), which is a regression test file, written in YAML.

I'm not sure that's a virus, so I assume this is a false positive hit in the defender.
