### ISSUE TITLE
Query latest release returns a 2.x version rather than a 3.x version

### ISSUE THREAD

**Issue by rweijnen** [SpiderLabs/ModSecurity#3246]
In my workflow for building a docker image I query latest release by checking https://api.github.com/repositories/1320594/releases/latest

Today, however 2.9.8 was released as latest build, so previously v3.0.12 was returned but now it's 2.9.8

Was this the intent? If so should I find another method of determining latest release ?

**Comment by airween** [comment]
Hi @rweijnen,

yes, that was - perhaps - an accident (I kept the default checkbox "on"), but please wait a bit and the newest v3 release will be there.

**Comment by rweijnen** [comment]
Thanks for checking.

I changed my workflow to make sure I get a release tagged with v3, which seems a good idea anyway...
```
      - name: Fetch Latest ModSecurity Version
        id: fetch_modsecurity_version
        run: |
          LATEST_MODSECURITY_VERSION=$( curl -s https://api.github.com/repositories/1320594/releases | jq -r 'map(select(.tag_name | startswith("v3."))) | .[0].tag_name')
          echo "Latest ModSecurity Release: $LATEST_MODSECURITY_VERSION" 
          echo "LATEST_MODSECURITY_VERSION=$LATEST_MODSECURITY_VERSION" >> $GITHUB_ENV
```

**Comment by airween** [comment]
Here is it:

https://github.com/owasp-modsecurity/ModSecurity/releases/tag/v3.0.13

Feel free to close this issue if you think everything is right.

**Comment by rweijnen** [comment]
Thanks, that fixed it!
