### ISSUE TITLE
can't start nginx 

### ISSUE THREAD

**Issue by huanxiren0** [SpiderLabs/ModSecurity#3286]
**Describe the bug**
environment: centos7、modsecurity-v3.0.12、[modsecurity-nginx-v1.0.3.tar.gz](https://github.com/owasp-modsecurity/ModSecurity-nginx/releases/download/v1.0.3/modsecurity-nginx-v1.0.3.tar.gz)、nginx-1.16.1
describe: When I followed the installation tutorial on the wiki, I couldn't start nginx

errormessage: /usr/local/nginx/sbin/nginx: error while loading shared libraries: libmodsecurity.so.3 : cannot open shared object file : no such file or directory

**Comment by huanxiren0** [comment]
Add /usr/local/lib to LD_LIBRARY_PATH to solve this problem

**Comment by airween** [comment]
Probably it would also be a solution if you pass `--prefix=/usr` to the `./configure` script. Then the library and archive files (`.so`, `.a`) will be installed into `/usr/lib` and the headers into `/usr/include`. On most systems, the `/usr/lib` is part of the `LD_LIBRARY_PATH`.
