### ISSUE TITLE
Disable some log parts

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#329]
MODSEC-175: It would be handy to have an option to disable logging of some parts of the H part. Typically: Stopwatch, Producer, Server, Sanitised-Request-Headers.

In some cases, we are not interested in these fields. On sites with a lot of alerts, this can spare several GB.

**Comment by victorhora** [comment]
Disable logging of parts of H part was implemented, merged to master and included on 2.9.2:

{dis|en}able-stopwatch-logging: https://github.com/SpiderLabs/ModSecurity/issues/1067

{dis|en}able-server-context-logging: https://github.com/SpiderLabs/ModSecurity/issues/1069

{dis|en}able-dechunk-logging: https://github.com/SpiderLabs/ModSecurity/issues/1068

{dis|en}able-handler-logging: https://github.com/SpiderLabs/ModSecurity/issues/1381

{dis|en}able-collection-delete-problem-logging: https://github.com/SpiderLabs/ModSecurity/issues/1380

{dis|en}able-server-logging:  https://github.com/SpiderLabs/ModSecurity/issues/1070 

{dis|en}able-filename-logging: https://github.com/SpiderLabs/ModSecurity/issues/1065

Thanks @marcstern and @zimmerle.
