### ISSUE TITLE
示例代码提示 Server log callback is not set -- 

### ISSUE THREAD

**Issue by dkwang2024** [SpiderLabs/ModSecurity#3293]
版本：modsecurity-v3.0.13
代码位置：modsecurity-v3.0.13/examples/simple_example_using_c/test.c

问题：编译运行后提示Server log callback is not set --  没有设置回调函数
在代码中修改transaction = msc_new_transaction(modsec, rules, log_callback); 发现不起作用
增加代码msc_set_log_cb(modsec, log_callback); 后编译运行，程序崩溃。

**Comment by airween** [comment]
Sorry @dkwang2024,

could you explain your problem in English?

**Comment by dkwang2024** [comment]
I added a callback function void log_callback (void * data, const void * ruleMessage) to the test.c file
I traced the execution of the program with gdb and found that the cause of the program crash was to print the log information matching the rule in the function
```C
void log_callback (void * data, const void * ruleMessage) {
    const ModSecurityIntervention * intervention = (const ModSecurityIntervention *) ruleMessage;
    if (intervention->log! = NULL) {
        printf ("Log:% s\ n", intervention->log);
    }
}
```

How to print the result log of matching rules in the callback function

**Comment by dkwang2024** [comment]
Under the guidance of AI, I created a new CPP file and generated a dynamic library to print the matching rule results
```C++
#include "modsecurity/rule_message"
#include < cstring >//for strdup

extern "C" {
    const char * get_rule_message_log (const void * ruleMessage) {
        //remove the const qualifier
        Modsecurity :: Rule Message * rm = const_cast < modsecurity :: Rule Message * > (static_cast < const modsecurity :: Rule Message * > (ruleMessage));
        if (rm! = nullptr) {
            std :: string log = rm- > log ();
            if (! log.empty ()) {
                //Copy strings to dynamically allocated memory using strdup
                return strdup (log. c_str ());
            }
        }
        return nullptr;
    }
}
```
Call the generated dynamic library in the test.c file to read the matching results
```C
void log_callback (void * data, const void * ruleMessage) {
    const char * log = get_rule_message_log (ruleMessage);
    if (log! = NULL) {
        printf ("Log:% s\ n", log);
        free ((void *) log);//Free dynamically allocated memory
    }
}
```
But it will still cause the program to report an error.

**Comment by dkwang2024** [comment]
Under the guidance of AI, I created a new CPP file and generated a dynamic library to print the matching rule results
```C++
#include "modsecurity/rule_message"
#include < cstring >//for strdup

extern "C" {
    const char * get_rule_message_log (const void * ruleMessage) {
        //remove the const qualifier
        Modsecurity :: Rule Message * rm = const_cast < modsecurity :: Rule Message * > (static_cast < const modsecurity :: Rule Message * > (ruleMessage));
        if (rm! = nullptr) {
            std :: string log = rm- > log ();
            if (! log.empty ()) {
                //Copy strings to dynamically allocated memory using strdup
                return strdup (log. c_str ());
            }
        }
        return nullptr;
    }
}
```
Call the generated dynamic library in the test.c file to read the matching results
```C
void log_callback (void * data, const void * ruleMessage) {
    const char * log = get_rule_message_log (ruleMessage);
    if (log! = NULL) {
        printf ("Log:% s\ n", log);
        free ((void *) log);//Free dynamically allocated memory
    }
}
```
But it will still cause the program to report an error.

**Comment by dkwang2024** [comment]
gdb debug result:

![image](https://github.com/user-attachments/assets/1bfee1b0-f57f-44e8-acde-13bfe94d0b38)

**Comment by airween** [comment]
[Here](https://github.com/digitalwave/ftwrunner/blob/v1.0/dev/src/engines/ftwmodsecurity/ftwmodsecurity.c#L29) you find an example (and [here](https://github.com/digitalwave/ftwrunner/blob/v1.0/dev/src/engines/engines.c#L82-L96)).

**Comment by dkwang2024** [comment]
Thank you. The problem has been solved.
