### ISSUE TITLE
audit log H appears truncated

### ISSUE THREAD

**Issue by ag-luca** [SpiderLabs/ModSecurity#3301]
Hi,

I'm not sure if this is a bug, but I've been looking for hours and I can't find similar errors, in my fresh installation of modsecurity on nginx it seems that logs that part H is truncated. Missing fields: Action, Stopwatch, Stopwatch2, Response-Body-Transformed, Producer, Server, Engine-Mode (compared to modsecurity with apache logs)
 
Current config:
Ubuntu 22.04.5 LTS, nginx/1.18.0, modsecurity-v3.0.13, modsecurity-nginx-v1.0.3, crs 4.8.0

nginx log part H
![modsec_audit](https://github.com/user-attachments/assets/eb810955-b2c1-4c7b-b86c-b35e0dff4eea)

example expected result
![expected_res](https://github.com/user-attachments/assets/f4057891-ee1f-49a5-b7a9-02e6ebf3ff85)

thank you

**Comment by airween** [comment]
Hi @ag-luca,

the second format is used by only Apache with mod_security2 module. libmodsecurity3 does not contain that format at all.

**Comment by ag-luca** [comment]
> Hi @ag-luca,
> 
> the second format is used by only Apache with mod_security2 module. libmodsecurity3 does not contain that format at all.

Thank you very much @airween

**Comment by ag-luca** [comment]
libmodsecurity3 does not contain the same log format as modsecurity2 part H. Thanks @airween

**Comment by ag-luca** [comment]
libmodsecurity3 does not contain the same log format as modsecurity2 part H. Thanks @airween
