### ISSUE TITLE
envsubst: Argument list too long

### ISSUE THREAD

**Issue by imikiani** [SpiderLabs/ModSecurity#3309]
**envsubst: Argument list too long **

When I run nginx based image of owasp/modsecurity-crs on top of kubernetes, I get this error:
/nginx/modsecurity.d/modsecurity.conf
/docker-entrypoint.d/20-envsubst-on-templates.sh: 53: envsubst: Argument list too long

`kubectl run mynginxtest --image=owasp/modsecurity-crs:4.8.0-nginx-202411071011`

**Logs and dumps**

Output of:
Error logs

` kubectl  logs -f mynginxtest`

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/01-check-low-port.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-generate-certificate.sh
/usr/local/bin/generate-certificate: generating new certificate
Warning: No -copy_extensions given; ignoring any extensions in the request
/usr/local/bin/generate-certificate: generated /etc/nginx/conf/server.key and /etc/nginx/conf/server.crt
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/modsecurity.d/modsecurity.conf.template to /etc/nginx/modsecurity.d/modsecurity.conf
/docker-entrypoint.d/20-envsubst-on-templates.sh: 53: envsubst: Argument list too long
```

**Comment by airween** [comment]
Hi @imikiani,

thanks for reporting - but I'm afraid this is more a [modsecurity-crs-docker](https://github.com/coreruleset/modsecurity-crs-docker/) issue than a ModSecurity.

**Comment by imikiani** [comment]
Dear @airween ,
Sorry, maybe it would have been better if I had opened the issue on [modsecurity-crs-docker](https://github.com/coreruleset/modsecurity-crs-docker/).

**Comment by airween** [comment]
No problem. Feel free to close this issue if you don't have any questions.
