### ISSUE TITLE
New action to forward to local file system

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#346]
MODSEC-192: We can redirect or proxy a request, but we cannot forward it to a local error page.

It would be handy to have something like
  SecRule .... phase:...,forward:'/error/invalid_character.html'

**Comment by zimmerle** [comment]
Such feature will break the compatibility within different webservers and such feature can be easily handle by the webserver itself. I cannot foresee a limitation where such feature is mandatory.
