### ISSUE TITLE
Response Body XML Processor

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#359]
MODSEC-205: It would be nice to have a Response Body XML Parser to be able to use XPath expressions in Phase 4 (not just populate the RESPONSE_BODY variable).

**Comment by victorhora** [comment]
We already have [XML parser and a collection to interact with it](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#XML). Closing this one.
