### ISSUE TITLE
SSL environment access

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#374]
MODSEC-220: The ENV collection cannot access environment variables set by mod_ssl.
It would be useful to extend it (or add another collection)

**Comment by zimmerle** [comment]
SSL variables are available via ENV variable. No need to have this feature duplicated on ModSecurity.

**Comment by marcstern** [comment]
You currently cannot test a SSL variable like ENV:SSL_CLIENT_S_DN_CN

**Comment by zimmerle** [comment]
> You currently cannot test a SSL variable like ENV:SSL_CLIENT_S_DN_CN

What you meant by DN_CN? All the **client_s** variables are correctly populated by SSL. As long as you have the client authentication is enabled, those variable will be populated accordingly. 

https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#page-header

**Comment by marcstern** [comment]
> **client_s** variables are correctly populated by SSL
Yes, but in the "SSL" space which is not available to ModSecurity rules
