### ISSUE TITLE
Investigate a mechanism for centralized/shared persistent storage

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#378]
MODSEC-224: For distributed environments, we need to extend the persistent storage mechanism to allow for centralized logging.  This would allow individual ModSec installs to access a central storage location for initcol, setsid, setuid actions.  One option may be to look at memcached.

Possible directives would be:

SecPersistentStorage Local|Centralized

- Local would be the way it is currently with local SDBM files
- Centralized would use something like a memcached server(s)

SecCentralizedStorageHost hostname|ip

- would define where the memcached server is, etc...

**Comment by matthewlenz** [comment]
Anyone know the current status of this feature?  This type of feature would be awesome for people who want to use multiple embedded solutions.  Apache 2.4 (as people have mentioned) supports this type of functionality for SSL cache and 2.4 is now in Debian stable (8.0).

**Comment by zimmerle** [comment]
This feature is being implemented as part of version 3 (aka libmodsecurity). In version 3, the collections were implemented over a interface that allow us to extend ModSecurity with different collections backends.

The interface is available here:
https://github.com/SpiderLabs/ModSecurity/blob/libmodsecurity/headers/modsecurity/collection/collection.h

Tickets were opened to track the implementation of the initial backends, they are: #1139, #1140, #1141
