### ISSUE TITLE
SecDefaultAction inheritance is buggy

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#379]
MODSEC-225:  SecAuditEngine     On
 SecRuleEngine      On
 SecRuleInheritance On
 SecAuditLogType Serial
 SecAuditLog  "logs/security/audit.log"
 SecAuditLogParts ABCEFHKZ

 SecDefaultAction "phase:2,pass,nolog,auditlog,logdata:'some data ...'"
 SecAction "phase:2,msg:'global'"
 <Location /test>
  SecAction "phase:2,msg:'/test'"
 </Location>

Result:
 Message: Unconditional match in SecAction. [msg "global"] [data "some data ..."]
 Message: Warning. Unconditional match in SecAction. [msg "/test"]

SecDefaultAction is not inherited in sub-locations (same for phases  2)

This is a huge security issue as some rules in sub-locations may not block because of that

**Comment by victorhora** [comment]
This is a known (and now expected) behaviour for ModSecurity as documented on the manual and other references: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDefaultAction

There is no current plan to change this behaviour. We might add another directive or a compile time option to change / disable this in the future if there is a community interest to do so.
