### ISSUE TITLE
Create a port of mod_security as Apache TrafficServer plugin

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#404]
MODSEC-250: The Apache Traffic Server is a proxy and cache. It's highly performant - even with its out-of-the-box config.
It offers a clean API which is used to extend the server with plugins.

When used as a reverse proxy, it would be the ideal enter point to protect back-ends with mod_security.

**Comment by victorhora** [comment]
With the advent of libModSecurity, I think the requirements are changed.

An initial implementation is ongoing here: https://github.com/shukitchan/ats-luajit-modsecurity

HAProxy + ModSecurity also seems like a viable solution: https://github.com/git001/haproxy-waf
