### ISSUE TITLE
Add DoS prevention code

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#416]
MODSEC-265: Add in new DoS prevention code similar to mod_evasive which keeps an internal hash table of IP address connection limits -
http://www.zdziarski.com/blog/?page_id=442

Look at the mod_evasive20.c file.  We could add similarly named directives -

   SecDOSHashTableSize    3097
   SecDOSPageCount        2
   SecDOSSiteCount        50
   SecDOSPageInterval     1
   SecDOSSiteInterval     1
   SecDOSBlockingPeriod   10

I would suggest that we also add a directive such as - SecDOSWhitelistURLs - where the user can specify URLs to exclude

**Comment by hamzasaeed2029** [comment]
I deployed modsecurity as default with crs and it did not protect me from DOS attack which I tried with "hulk" tool. Nothing showed up on logs (debug.log,access.log or error log) Kindly help.

**Comment by zimmerle** [comment]
> I deployed modsecurity as default with crs and it did not protect me from DOS attack which I tried with "hulk" tool. Nothing showed up on logs (debug.log,access.log or error log) Kindly help.

Hi @hamzasaeed2029  you may want to open the issue on the CRS project, they will be able to help you with the CRS rules.

**Comment by hamzasaeed2029** [comment]
> > I deployed modsecurity as default with crs and it did not protect me from DOS attack which I tried with "hulk" tool. Nothing showed up on logs (debug.log,access.log or error log) Kindly help.
> 
> Hi @hamzasaeed2029 you may want to open the issue on the CRS project, they will be able to help you with the CRS rules.

I think I haven't set the parameters. let me first try doing that. Thanks for being helpful
