### ISSUE TITLE
ModSecurity can not verify XML MTOM (SOAP Message Transmission Optimization Mechanism) requests

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#435]
MODSEC-286: If a SOAP (1.2) MTOM request is approved, then I get an error message "XML parser error: XML: Failed parsing document." and "Failed to parse request body: 1". Here is an excerpt from the log (partially anonymized):

--7fe2133e-B--
POST /WebService HTTP/1.1
SOAPAction: "urn:soapAction"
Content-Type: multipart/related; type="application/xop+xml"; start="rootpart@soapui.org"; start-info="text/xml"; boundary="----=_Part_8_127403928.1323773710920"
MIME-Version: 1.0
User-Agent: Jakarta Commons-HttpClient/3.0.1
Host: host.com
Content-Length: 1122

--c52a0a53-C--

------=_Part_8_127403928.1323773710920
Content-Type: application/xop+xml; charset=UTF-8; type="text/xml"
Content-Transfer-Encoding: 8bit
Content-ID: rootpart@soapui.org

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tran="http://www.xxx.net/namespace/xxx" 
xmlns:all="http://www.xxx.net/namespace/xxx">
   soapenv:Header
        <wsse:Security xmlns:wsse="http://docs.open.org/wss/200401-wss-wssecurity-secext-1.0.xsd">
                <wsc:SecurityContextToken xmlns:wsc="http://schemas.xmlsoap.org/ws/02/sc">
                        wsc:Id1527623436931/wsc:Id
                /wsc:SecurityContextToken
        /wsse:Security
   /soapenv:Header
   soapenv:Body
      tra:li
         tran:Req
            all:Ver2.1.0.1/all:Ver
            all:CIDID1/all:CID
            tra:KLi999999999/tra:KLi
            tr:Bnfalse/tr:Bn
         /tran:Req
      /tra:li
   /soapenv:Body
/soapenv:Envelope
------=_Part_8_127403928.1323773710920--

Is the ModSecurity not SOAP 1.2 / MTOM specification compatible?

**Comment by victorhora** [comment]
Closing this one as it's duplicate with #902 and will be handled there.
