### ISSUE TITLE
500 error when processing too large request with mod_security through proxy reverse

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#442]
MODSEC-294: The server do proxy reverse to an another apache 2.2.22 (without mod_security) and an application deployed on a JBOSS. The application seems work fine through the proxy reverse in general except when you try to send a POST request with includes digital signature. This request is quite large and we get in the apache's error log:

[Sat Mar 24 12:24:59 2012] [error](20014)Internal error: proxy: search for temporary directory failed
[Sat Mar 24 12:24:59 2012] [error] proxy: pass request body failed to 192.168.32.5:443 (my-internal.server.com) from 23.45.156.32 ()

In the mod security log, we find:
...
--35823846-B--
POST /application/action/signature/doSignature.do HTTP/1.1
Accept: application/x-ms-application, image/gif, application/xaml+xml, application/x-ms-xbap, application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, image/x-xbitmap, image/jpeg, image/pjpeg, application/x-shockwave-flash, application/vnd.ms-xpsdocument, _/_
...
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; SLCC1)
Content-Type: multipart/form-data; boundary=---------------------------7dcc839440a8a
Accept-Encoding: gzip, deflate
Host: mypublic.server.com
Content-Length: 35318
Connection: Keep-Alive
Cache-Control: no-cache
Cookie: JSESSIONID=5552CA6889E2680C89253D593E4A2D27

--35823846-I--

---- Too large request

--35823846-F--
HTTP/1.1 500 Internal Server Error
Content-Length: 548
Connection: close
Content-Type: text/html; charset=iso-8859-1

--35823846-H--
Apache-Handler: proxy-server
Stopwatch: 1332588298225593 1613861 (- - -)
Stopwatch2: 1332588298225593 1613861; combined=1555770, p1=870, p2=1554602, p3=93, p4=
186, p5=15, sr=345, sw=4, l=0, gc=0
Producer: ModSecurity for Apache/2.6.3 (http://www.modsecurity.org/); 200911012341.
Server: Apache/2.2.22 (Unix) mod_ssl/2.2.22 OpenSSL/1.0.0-fips

--35823846-Z--

If we deactivate SecRequestBodyAccess putting it to Off, it works properly. If we have tried this configurations:
- Use "SecRequestBodyLimitAction ProcessPartial" --> We get the same error.
- Increase (too much) SecRequestBodyLimit and  SecRequestBodyInMemoryLimit --> We get the same error.
- Use the proxy directive "SetEnv proxy-sendchunked 1" --> It works properly, but we obtend JBOSS exception because our application needs Content Lenght.

**Comment by SheldonLaw** [comment]
I got almost the same problem when I upload an big image （32KB）.

``` shell
[Wed May 29 21:07:23 2019] [error] proxy: pass request body failed to 127.0.0.1:8888 (localhost) from x.x.x.x ()
[Wed May 29 21:10:02 2019] [error] (20014)Internal error: proxy: search for temporary directory failed
```

But the solution list below don't work for me.
