### ISSUE TITLE
Macro expansion & delimiters detail

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#462]
MODSEC-314: We should add an explicit entry to all operators to tell if they support macro expansion.
For operators supporting a list of parameters (pm, within), we should explicitly state which delimiter is used).

**Comment by zimmerle** [comment]
On v3 this list is clear as the class that supports variable expansions has m_couldContainsMacro set to true.

https://github.com/SpiderLabs/ModSecurity/blob/587cbf39153fccb9cd129433609835fa83064bc4/src/operators/within.h#L34

**Comment by marcstern** [comment]
Maybe non-developers would also want this in the doc, no?

**Comment by zimmerle** [comment]
> Maybe non-developers would also want this in the doc, no?

Sure. Now we have the technical meaning to do this as oppose to before, where those couldn't be computed easily. This means that documentation will be easy. It is a know issue that we have to have a better documentation. Want to help us on that task?

**Comment by marcstern** [comment]
As I'm working with Apache, I'm still in 2.9 ...
