### ISSUE TITLE
urlDecodeUni & invalid sequences -> bypass

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#465]
MODSEC-317: When using urlDecode/urlDecodeUni on a string containing an invalid sequence like "%r", the sequence is ignored.
This can be used to bypass rules. Ex:
"<sc%ript>" will be interpreted by ASP as "<script>".
There is no way to transform the input to check the match against "<script>" (except adding %\* between all characters in all rules).

I see several possibilities to solve that problem:
- add new transformations "urlDecode2" & "urlDecodeUni2"
- add a new transformation "removePercents"
- add a new transformation "subst(s1,s2)" (generalization of above)
- add a tranformation-specific parameter "ignoreInvalidPercents" that is used by all url decoding variants

The last option would be the best one (although the subst would be great for a lot of other purposes) because
1. it is one option for all url-related transformations (instead of several variants of the current transformations - think about future variants leading to lots of combinations)
2. it would not remove correctly encoded % (ex: "50%25") like "removePercents" or "subst"

**Comment by zimmerle** [comment]
no feedback since 2013. closing.

**Comment by marcstern** [comment]
No feedback from _your_ side :-(
I proposed the "tfnOption:ignoreInvalidPercents" but you never replied ...
