### ISSUE TITLE
Create new collections MATCHED_IDS and MATCHED_MSGS

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#478]
MODSEC-330: It would be useful to have MATCHED_IDS and MATCHED_MSGS collections.  This is similar to MATCHED_VARS.  This would allow rule writers to check if a previous rule(s) have matched before executing other actions.

**Comment by zimmerle** [comment]
Logically-wise such feature could be achieved by having the chained rules. Closing till we have a better example why such feature will be important.
