### ISSUE TITLE
mod_security failed to build against libxml2 >= 2.9.0 [PATCH ATTACHED]

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#491]
MODSEC-343: There's an API change in libxml2 which makes mod_security fail to build (see bellow):

msc_crypt.c:1082:74: error: dereferencing pointer to incomplete type
msc_crypt.c:1084:60: error: dereferencing pointer to incomplete type
msc_crypt.c:1096:55: error: dereferencing pointer to incomplete type
msc_crypt.c:1106:59: error: dereferencing pointer to incomplete type
msc_crypt.c:1109:141: error: dereferencing pointer to incomplete type
msc_crypt.c:1113:56: error: dereferencing pointer to incomplete type
msc_crypt.c:1125:53: error: dereferencing pointer to incomplete type
msc_crypt.c:1135:57: error: dereferencing pointer to incomplete type
msc_crypt.c:1138:136: error: dereferencing pointer to incomplete type
msc_crypt.c: In function 'do_hash_link':
msc_crypt.c:1316:17: warning: format '%d' expects argument of type 'int', but argument 5 has type 'size_t' [-Wformat]
make[2]: **\* [mod_security2_la-msc_crypt.lo] Error 1
make[2]: **\* Waiting for unfinished jobs....
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -I/usr/include/httpd -I/usr/include/apr-1 -I/usr/include/apr-1 -I/usr/include/libxml2 -DWITH_LUA -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1000000 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1000000 -DREQUEST_EARLY -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c msc_tree.c -o mod_security2_la-msc_tree.o >/dev/null 2>&1
make[2]: Leaving directory `/builddir/build/BUILD/modsecurity-apache_2.7.0/apache2'
make[1]: Leaving directory`/builddir/build/BUILD/modsecurity-apache_2.7.0/apache2'
make[1]: **\* [all] Error 2
make: **\* [all-recursive] Error 1

**Comment by gurucubano** [comment]
HELLO, Where could I find the patch which fixes this? Thanks
