### ISSUE TITLE
SecRuleUpdateTargetById won't work in my virtualhost

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#502]
MODSEC-354: Hi,

In order to test modsecurity, I created this single rule that matches all request headers containing "clebrun_user_agent"

SecRule REQUEST_HEADERS clebrun_user_agent id:99999,phase:2,deny

I wanted to create an exception in an apache virtual host and added:

SecRuleUpdateTargetById 99999 !REQUEST_HEADERS:User-Agent

but it did not work, the User-Agent header still matches the 99999 rule if contained "clebrun_user_agent"

Instead, I removed the SecRuleUpdateTargetById line and added this two lines in my virtual host:
SecRuleRemoveById 99999
SecRule REQUEST_HEADERS|!REQUEST_HEADERS:User-Agent clebrun_user_agent id:99999,phase:2,deny

It worked and the User-Agent wass ignored

What's the problem with SecRuleUpdateTargetById, Can't it work in a virtualhost conf ????

Thanks for your help

Regards Cyril

**Comment by tchwpkgorg** [comment]
Does "SecRuleUpdateActionById" have a similar limitation and will not work in virtual host context, if the rule was loaded in the main apache context?
