### ISSUE TITLE
Need to add new "Encode" transformation functions

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#509]
MODSEC-361: We already have many "Decode" transformation functions which aim to help combat obfuscation attempts by attackers.  We need to also have corresponding "Encode" versions for each one.  We already have encode/decode for some -
- urlDecode/urlEncode
- hexDecode/hexEncode

We need corresponding encode versions of the following -
- jsDecode
- cssDecode
- htmlEntityDecode

Having these encoding tfns would allow users to potentially address identified XSS flaws during virtual patching by apply these encodings to inbound/outbound data and using @rsub against the STREAM variables.

**Comment by victorhora** [comment]
Already implemented:

[https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#jsDecode](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#jsDecode)
[https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#cssDecode](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#cssDecode)
[https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#htmlEntityDecode](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#htmlEntityDecode)

**Comment by csanders-git** [comment]
please read the bug report... it's looking for the jsEncode and cssEncode features which don't exist.

**Comment by victorhora** [comment]
Thanks @csanders-git. Again, is this something that the CRS and / or the community are currently missing? If yes, we'll happily tag it for libModSecurity and see if we get some traction, otherwise we don't see a reason to keep this one open after 5 years of no interest from the community.

Thanks for letting us know.

**Comment by csanders-git** [comment]
it appears yes, as the bug was made. I don't see the point in closing an issue that hasn't been fixed and is still an identified need.
