### ISSUE TITLE
modsecurity truncate modsec_debug log after 1024 characters

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/ModSecurity#537]
MODSEC-389: Hello, i have a secrule with a large number of ARGS : 
SecRule ARGS_NAMES "!^(|var1|var2|var3|.........|var50|)$" "t:lowercase,deny,status:403,phase:2" 

the secrule works fine but when the rule match, the modsec_debug is truncate after 1024 characters. 
so i can't discovery a potentialy new args. how i can increase the number of characters on each line on modsec_debug ? 

thanks a lot for your help !

**Comment by galehar** [comment]
I have the same issue. 5 years later, is it still a hardcoded limitation? Is changing the source and recompiling the only solution to having truncated log messages?
Thanks.

**Comment by zimmerle** [comment]
@galehar You may want to read the info from the audit logs, there it wont be truncated. The idea of the debugging logging is to facilitate the process to write rules. In this use case, is unlikely that you need the entire content. If so, we recommend the AuditLogs.

**Comment by galehar** [comment]
Sorry, I misread the description. My problem wasn't related to debug logs but caused by an outdated logger. Thanks for the quick response anyway.
