### ISSUE TITLE
ModSecurity strips POST data information from request in DetectionOnly mode

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#538]
MODSEC-390: For a Dutch bank we purchased the commercial ruleset from TrustWave labs. In the process of setting-up the ModSecurity in combination with IIS we hit an issue which we cannot solve and basically renders the ModSecurity module unusable for our environment.

When enabling ModSecurity for the default virtual host, POST parameters are no longer passed to the JBoss application server via the mod_jk plugin. 
We deployed on this virtual host the mod_jk ISAPI module which works as expected when ModSecurity is disabled. 

After enabling ModSecurity (DetectionOnly mode), access to the the login-page via Java ServerFaces works fine (and access to all other dynamic content which does not require POST information to be sent) until we try to submit for instance the username. 

The submitted username is received by IIS (confirmed this through our Web Debugging Proxy (Charles)), but the POST parameter data itself is empty when received by our application (confirmed by the log files produced by the application).

In the Windows EventLog Application log there are no ModSecurity errors, only warnings concerning rules have been hit.

We installed ModSecurity using the MSI installer on IIS.
Installation seems successful, we see the in Windows EventLogger the ModSecurity Information logs:

ModSecurity for IIS (STABLE)/2.7.3 (http://www.modsecurity.org/) configured.
ModSecurity: APR compiled version="1.4.6"; loaded version="1.4.6"
ModSecurity: PCRE compiled version="8.30 "; loaded version="8.30 2012-02-04"
ModSecurity: LUA compiled version="Lua 5.1"
ModSecurity: LIBXML compiled version="2.7.7"

Please advice,
All the best,
Robin Huiser

**Comment by Zetanova** [comment]
SecStreamInBodyInspection On    worked on IIS7.5 ARR2.5

**Comment by marcher233** [comment]
We are using Microsoft Dynamics NAV 2016 Web Client but POST parameters won't forward correctly when SecRequestBodyAccess is set as On.

Adding SecStreamInBodyInspection On to config file works on IIS8.5.

**Comment by pleothaud** [comment]
SecStreamInBodyInspection On to config file works on IIS8.5, Server 201212 R2 (in Azure)

Also I checked that POSTed variables were still checked : they are J

**Comment by victorhora** [comment]
[SecStreamInBodyInspection](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecStreamInBodyInspection) should be turned on for IIS.

As for Nginx, support for this module in ModSecurity 2.9.x branch is deprecated. This shouldn't be a concern with [libModSecurity](https://github.com/SpiderLabs/ModSecurity/tree/v3/master).

Thanks!
