### ISSUE TITLE
Mod Security compilation issue on ERS Apache

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#543]
MODSEC-395: When i am trying to run below command for compiling Modsecurity on ERS Apache

./configure --with-apxs=/app/ERS/x.0.x/apache2.2/bin/apxs --with-apr=/app/ERS/4.0.3/apache2.2/bin/apr-1-config --with-apu=/app/ERS/4.0.3/apache2.2/bin/apu-1-config --with-pcre=/usr/local/bin/pcre-config --disable-mlogc

Getting below error

error occured with apxs Tool while configuring Mod security.

configure: looking for Apache module support via DSO through APXS
Possible unintended interpolation of @PRODUCT_ROOT in string at (eval 1) line 1.
Use of uninitialized value in concatenation (.) or string at /app1/ERS/4.0.3/apache2.2/bin/apxs line 236.
apxs:Error: /bin/httpsd.worker not found or not executable.

when go and check under bin directory "apxs" is available with executable permission. Please advise.

**Comment by victorhora** [comment]
Closing this one after long period of no updates. Assuming user got around the issue with his environment.
