### ISSUE TITLE
Need REQUEST_COOKIES JSON Parser

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#555]
MODSEC-407: JSON formatted cookies are becoming more popular.  We need to be able to parse the JSON data and then populate key=value pairs into REQUEST_COOKIES collection.

Possible implementation option is to modify the SecCookieFormat directive to include a new option (JSON) and optionally define which Cookies need the parsing -

SecCookieFormat 0 JSON:MyCookie

This directive would use normal v0 cookie parsing for all cookies however the MyCookie payload would be parsed as JSON.

**Comment by victorhora** [comment]
Marking this one as duplicate as already being discussed at #687. Tagged for to be implemented for 3.x.
