### ISSUE TITLE
ModsecurityIIS does not pass through POST data to Popular CMS when SecRequestBodyAccess is set to On

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#562]
MODSEC-414: ModsecurityIIS does not pass through POST data to WordPress/Joomla/Modx (on Admin Panel) when SecRequestBodyAccess is set to On

**Comment by tizzythegrey** [comment]
Fantastic job guys. This fixed my issues with DNN ActionForm.

**Comment by victorhora** [comment]
Closing due to being resolved based on @smytht and @tizzythegrey comments. Thanks.
