### ISSUE TITLE
Command failed to execute (check file/folder permissions, syntax, etc.)

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#563]
MODSEC-415: Command failed to execute (check file/folder permissions, syntax, etc.), when I uncomment next directive:
SecAuditLog c:\inetpub\log\modsec_audit.log

**Comment by victorhora** [comment]
This is a known limitation with the IIS module. Depending on the environment and Windows version, recursive permission has to be given to the files being opened for writing by ModSecurity (e.g. AuditLog, DebugLog, collection files etc.)

See https://github.com/SpiderLabs/ModSecurity/issues/812

Issue https://github.com/SpiderLabs/ModSecurity/issues/812 was tagged to be addressed for 2.9.4 release. If you need to follow up on this, please do so at https://github.com/SpiderLabs/ModSecurity/issues/812 so we can better track this issue.

Thanks.
