### ISSUE TITLE
Mandatory and unique ID should be an option

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#572]
MODSEC-424: First of all, this is not backward compatible, which is always a problem. But this is more important than that.
I will show a few examples of major issues related to this decision, but this is definitely not an exhaustive list (so the goal is not to discuss a work-around for one particular case). Remember than some people (like me obviously) manage configurations with several dozens/hundreds of applications.

1. Some rules are used to set a flag (variable, counter). There is no reason to invent an ID for that (because it'll never be disabled)

2. If you use a macro or include a file with rules in different vhosts, you get duplicated ID

3. You may have a rule with an ID that you disabled in some locations.If you duplicate it with different transformations,you may want to disable the new one at the exact same locations than the old one - so giving the same ID is a perfect choice

4. Sometimes, a construction like the following one is used (yes, there may be reasons to not use chaining):
 SecRule ... skip:1
 SecRule ... id=100,...
If you disable rule 100 in some location, you screw up your config because it will skip the next rule, whereas is not the intention.
This can easily be solved by giving the same id to the "skip" rule as the rule to skip.

This simply shows that some people may have a real need to keep the old behavior.
I propose to add a directive (or a compile flag if it's not possible) to support the "old" behavior.

**Comment by marcstern** [comment]
Ryan, do you agree with my remarks?

**Comment by marcstern** [comment]
In basic configurations, this check is useful to check about rules being loaded twice. So, the default behaviour should probably stay like now.
However, I gave above practical examples (real life cases) where duplicate ID (and no ID) are needed. There is no reason to forbid a power administrator to allow that. Adding a directive (or a compile flag) to disable that restriction would solve the problem while keeping the default behaviour for basic users.

Ex; of compile flag: #https://github.com/marcstern/ModSecurity/commit/14caffbd320c3893cf2df0ecd6ab0fbe85898022

**Comment by csanders-git** [comment]
@marcstern  how are removeby id going to work without these?

**Comment by marcstern** [comment]
@csanders-git, I guess you're speaking about rules without ID.
There are some rules you never want to disable, like a rule setting a variable without any security action.
Although it's only an annoyance to be obliged to specify an ID, not a major issue as not being able to specify multiple rules with the same ID as explained above.

**Comment by csanders-git** [comment]
After this was discussed at the last State of ModSecurity meeting, it was decided that because this feature would be confusing to the end user, provides for potentially less usable rules from developers, and ultimately is only valuable for a very small amount of custom configuration purposes (which themselves are often confusing), this feature will not be added (back) into the main branch.
We have no problem accepting a pull that provides this feature as a configuration option --enable-duplicates, but please be sure if you go down this route that this pull is documented with how the option works and why it might be necessary.

**Comment by marcstern** [comment]
I can provide the patch with the documentation.
Would you include it in 2.9.1?
