### ISSUE TITLE
When using "ctl:" on first line of chained rules, modsecurity ignores chains

### ISSUE THREAD

**Issue by gitkitten** [SpiderLabs/ModSecurity#581]
First, I make code 1 and test it.
It seems works, but mod_security just ignore chained rules.
(ctl:ruleEngine=off --> Allow all block rules for "^/uploadme/*.php$". This is not good.)

/uploadme/up.php?x=../         <----Didn't block!

So I try code 2.
/uploadme/up.php?x=../ returns HTTP403(ok),
but rule id:100 doesn't work as expected. (rule doesn't turn off).
# test code 1

SecRule REQUEST_URI "^/uploadme/*.php$" "chain,id:'100',nolog,ctl:ruleEngine=off"
 SecRule REQUEST_METHOD "^POST$" "chain"
 SecRule ARGS:ffile "!^$" "t:none"
SecRule ARGS "../" "t:normalizePathWin,id:50904,msg:'Drive Access'"
# test code 2

SecRule REQUEST_URI "^/uploadme/*.php$" "chain,id:'100',nolog"
 SecRule REQUEST_METHOD "^POST$" "chain"
 SecRule ARGS:ffile "!^$" "ctl:ruleEngine=off"
SecRule ARGS "../" "t:normalizePathWin,id:50904,msg:'Drive Access'"
1. Of course I restart Apache, retry with different combination many times...
2. SecRule ARGS:ffile "!^$" "t:none" <--- means "ffile has some text"
3. I need this rule because modsecurity seriously slow down file upload speed/process time...

**Comment by victorhora** [comment]
This shouldn't be an issue with libModSecurity. Please upgrade.

Thanks.
