### ISSUE TITLE
Nginx with Modsecurity: POST request gives 500 error

### ISSUE THREAD

**Issue by pijnack** [SpiderLabs/ModSecurity#582]
Nginx with Modsecurity gives 500 errors after a POST request.

In error.log:

2013/10/23 13:21:07 [alert] 29432#0: *4 no upstream configuration, client: 88.159.16.136, server: test.huygenscollege.nl, request: "POST /proefwerk/prog/index.php?day=28&month=10&year=2013&klas=2 HTTP/1.1", host: "test.huygenscollege.nl", referrer: "http://test.huygenscollege.nl/proefwerk/prog/index.php?day=4&month=11&year=2013&klas=2"

In nginx.conf:

upstream smoothrac {
        server 88.159.13.153;
}
server {
        listen       80;
        server_name  test.huygenscollege.nl;
        location / {
         ModSecurityEnabled on;
         ModSecurityConfig modsecurity.conf;
        proxy_pass         http://smoothrac/;
        proxy_set_header Host test.huygenscollege.nl;
        proxy_read_timeout 150s;
        }
}

After changing ModSecurityEnabled on to off, the problem is gone.
I guess something is missing in my upstream configuration? 

Piet Pijnacker,
Eindhoven, Netherlands

**Comment by ton31337** [comment]
I can't sudo to root from donatas user. Can we chat in skype or gtalk,
because mail isn't a good way to go..

On Tue, Dec 30, 2014 at 9:33 PM, smtalk <notifications@github.com> wrote:

> ton31337, any news on the problem? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpiderLabs/ModSecurity/issues/582#issuecomment-68388922>
> .
>



-- 
Donatas

**Comment by rz300** [comment]
let's use gtalk

**Comment by rz300** [comment]
any news? i wait for gtalk rewired.ag@gmail.com

**Comment by sasah** [comment]
Hello, any news?

**Comment by rz300** [comment]
i 've compiled the original source and and made changes in the /etc/modsecurity/modsecurity.conf 
``SecRequestBodyAccess On`` to ``SecRequestBodyAccess Off`` it helps me.

**Comment by rm3nchaca** [comment]
Please use the nginx_refactoring branch, it appears to be solved. .

**Comment by jowrjowr** [comment]
When will the nginx refactoring branch get merged into the main branch that
OS maintainers use?

**Comment by zimmerle** [comment]
Hi @jowrjowr, nginx_refactoring still has some issues that we want to fix prior to release it as stable.

**Comment by 3skr0** [comment]
Does this mean that mod security doesn't work yet with nginx? as it cannot handle POST request... There is no workaround ?

**Comment by zimmerle** [comment]
@3skr0 read this thread -- It contains some useful information. 

Depending on your configuration it won't be stable. nginx_refactoring seems to be workable in most of the cases. I recommend you to use it. Still, there are some known bugs regarding specific setups.

**Comment by 3skr0** [comment]
@zimmerle 
I've read it, but on this thread https://github.com/SpiderLabs/ModSecurity/issues/664, it's said they have the same problem with the nginx_refactoring branch...
They seems to bypass the bug in listenning on another port than the 80 port...

**Comment by ton31337** [comment]
Use my pull request, it solves 500 and xheaders issues.

Sent from iPhone




On Mon, Feb 16, 2015 at 11:37 AM -0800, "3skr0" <notifications@github.com> wrote:












@zimmerle 

I've read it, but on this thread #664, it's said they have the same problem with the nginx_refactoring branch...

They seems to bypass the bug in listenning on another port than the 80 port...

**Comment by 3skr0** [comment]
@ton31337 . I'm performing some test with your pull request and i have 'other' issues. Now, on other port that 80 I have 404 error on each POST request. And, on a specific form on port 80, have a 404 error too... weird

**Comment by ton31337** [comment]
That's odd, because we are using on  different ports too..

Sent from iPhone




On Mon, Feb 16, 2015 at 2:20 PM -0800, "3skr0" <notifications@github.com> wrote:












@ton31337 . I'm performing some test with your pull request and i have 'other' issues. Now, on other port that 80 I have 404 error on each POST request. And, on a specific form on port 80, have a 404 error too... weird

**Comment by badcrc** [comment]
I was finally to make it work with @ton31337 's fix!

**Comment by rodehoed** [comment]
My results from the @ton31337 branch:
* < 8K files (was: 500 error) **WORK** 
* > 8K files (was: 408 error) **WORK**

So thanks @ton31337 . Any clue when this will goto refactoring branch?

**Comment by zimmerle** [comment]
Hi guys, few minutes ago I've merge #904 into nginx_refactoring branch. It should fix this issue, please confirm that the issue is fixed.

**Comment by taibd** [comment]
hi @zimmerle, I checked this fixed bug again. It's ok with normal request, but it fails if I use xenforo framework. What's happen??

**Comment by zimmerle** [comment]
Hi @taibd, I am not sure. it was working before and not working anymore? or it never worked as you expected?

**Comment by taibd** [comment]
@zimmerle: oh Yes, I have followed this bug a long time and perhaps it's difficult bug.
 Now, I use @ton31337 Modsecurity-nginx while I am waitting your full patch version.
But He is not a developer of Modsecurity-nginx. I don't realy trust him for secure reason.
Do you have any recommendation for me to deploy my system.

Thanks you so much!

**Comment by jdoss** [comment]
@taibd This is kind of how Open Source Software works. @ton31337 took the time to figure out why the 500 errors were happening in this specific case and @zimmerle who works for Trustwave's SpiderLabs, which handles the development of Modsecurity-nginx, reviewed and merged these patches. If he trusts and reviewed @ton31337 work, then one would think that his fixes are secure.

Every use case is different. What exact errors are you getting when using the current nginx_refactoring branches? @ton31337 fixed my 500 errors that I was getting with my specific PHP applications so your problems might not be exactly this specific problem, but a new one. More information from you will help track that down which is what @zimmerle was asking for in his previous response.

**Comment by taibd** [comment]
Thanks for your response, @jdoss 
I am deploying a forum which they is based on Xenforo Framework.
And I built nginx's web server from @zimmerle source then It failed. My forum uses HTTP, Not HTTPs.
It reports 500 server error when I try to send Post Data from login form.
I built again with @ton31337 source, It's OK. 
I don't think that @zimmerle made new Patches from @ton31337 source.

And my question this is "Does they have any different beween two patches??"
@zimmerle, I need your helps.

**Comment by rosmo** [comment]
@taibd, try my branch: https://github.com/rosmo/ModSecurity/commits/nginx_refactoring_rosmo

**Comment by taibd** [comment]
Hi @zimmerle @ton31337,
I checked 2 version of you and reviewed some code in build source.
My test case is:
1. build @zimmerle's version => get 500 error.
2. replace /ModSecurity_nginx_refactoring/nginx/mosecurity/ngx_http_mosecurity.c with /Modsecurity_ton31337_x-headers/nginx/modsecurity/ngx_http_modsecurity.c and build again.
=> it passed OK.
3. Reviewed different from 2 above file with diff command in Linux.
seem to be OK and no problem with secure reason.
Now, I'm choosing the solution for my system: nginx_refactoring2 + ngx_http_modsecurity.c's ton31337.

Thanks @zimmerle @ton31337 

@ton31337:thank you so much!

**Comment by zimmerle** [comment]
Hi Guys, there are two different issues, the consequence is pretty much the same (500 error). There is one issue which was fixed by this commit: 
https://github.com/SpiderLabs/ModSecurity/commit/97120aef7d159f2ec76f871c9ca84a76cc65260b

and the other one is fixed by @ton31337.

Depending on your configuration/setup you may face one or another.

**Comment by fabriciojs** [comment]
Hello guys,

please can someone help me understand here. 

Context: I would like to use Nginx w/ ModSecurity as reverse proxy in front of some web servers. For that I followed the recommendations and built ModSecurity (the nginx_refactoring branch) and Nginx 1.8.0, in a fresh CentOS 6.6 installation.

I was very excited on the possibility of using ModSecurity+Nginx as transparent proxy.

Everything seemed OK as started testing. As the tests goes, I stumbled upon the problem long related and dealt with by the community here in this issue.

The situation is: all POST requests to any Nginx server on port 80 (with ModSecurityEnabled on) give me an 500 response, and logs the **13 no upstream configuration,**. The curious thing is, one of my test proxy servers is listening on both 80 and 8999. The 80 got the problem, while the 8999 works properly.

The problem is related and open here for almost 2 yeas now. So here goes my question:

- is it possible to obtain a stable version of ModSecurity to work with Nginx?

-- if not, as I am afraid of, the use should be advised as experimental and under development (or at least not as stable, as it is now at ModSecurity's website on the downloads section).

-- if it is possible, can someone throw me some lights on how?

I noticed on the comments here in this issue people with third part branchs and patches. I did not try them, as I assumed by the commits and merges that the nginx_refactoring branch was the best option to go.

Thanks very much in advance!

regards,
Fabrício José

**Comment by ton31337** [comment]
Hi,

Try ton31337_nginx_refactoring branch.

**Comment by fabriciojs** [comment]
Thank you very much @ton31337 , I have built your branch and now the problem is gone.

Again, thanks. I thought your fixes were already in ModSecurity/nginx_refactoring.

Now, may I ask you and whoever reads here:

I was planning to test and use Nginx+ModSecurity for production soon, deploying a reverse proxy to virtual patch a set of web services. Now I am afraid I should not do that.

What do you advise on this, about stability and safeness of the setup?

Best Regards,
Fabrício José

**Comment by rm3nchaca** [comment]
I have used on production without any problem.
I tested it with some pen-test tools and everything was OK.

The platform is centos 6.6 minimal.

Best regards...

**Comment by ccaau** [comment]
Hi All,

We're seeing 500 Internal Server error with:
- Nginx 1.8.0
- ModSecurity 2.9 off nginx_refactoring branch - 8a4999891d272cf8bfbe6c9af3274d7f2b0389fa
- SecRequestBodyAccess On (No issue if this is Off)
- Affects ALL POST requests.
- We only see the issue if we have multiple server blocks configured.
   We have two server blocks. One is set to be the default_server 
      ie: listen              443 default_server ssl;
- We see the issue if the server that processes the request has a proxy_pass directive

thanks,

**Comment by ton31337** [comment]
try nginx_refactoring_ton31337 branch and give feedback.

**Comment by ccaau** [comment]
Hey Ton31337,

That's fix my issue.. Any idea when this might get merged into nginx_refactoring?

Any idea if ModSecurity 2.8 would be more stable than 2.9 with nginx?

thanks!

**Comment by ton31337** [comment]
No, idea. Just ask @zimmerle about the progress ;-)

On Tue, Oct 20, 2015 at 9:37 AM, ccaau <notifications@github.com> wrote:

> Hey Ton31337,
>
> That's fix my issue.. Any idea when this might get merged into
> nginx_refactoring?
>
> Any idea if ModSecurity 2.8 would be more stable than 2.9 with nginx?
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpiderLabs/ModSecurity/issues/582#issuecomment-149448958>
> .
>



-- 
Donatas

**Comment by zimmerle** [comment]
Hi @ccaau,

@ton31337's patch work wonderfully in certain scenarios, in other scenarios (together with other patches) it may lead to failures. That is the main reason why it was not merged into nginx_refactoring yet. It seems to be safe to use @ton31337's patch in your scenario. 

We are currently working in a new version of ModSecurity for nginx. It is something that we are targeting for ModSecurity version 3. The version 3 will no longer depend on Apache and/or APR, it will be an independent library that may be consumed by the "nginx connector", this connector is a replacement for the current nginx addon.

- ModSecurity version 3 information:
https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity

- nginx connector information:
https://github.com/SpiderLabs/ModSecurity-nginx/tree/experimental/

**Comment by ton31337** [comment]
:+1:

**Comment by ccaau** [comment]
Hey @zimmerle 

Thanks for the update..

We're testing nginx_refactoring_ton31337 with proxy_force_ranges on; so far so good.. 

Thanks!

**Comment by taibd** [comment]
Hi @zimmerle @ton31337, this bug still existed with my server,
I'm using https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring version update from July 1 2015, this is the newest version.
My reverse proxy nginx + modsecurity may be so good with only one website,
But when I try to have with 2 websites or more on nginx server then this bug come.
It response 400 bad request, invalid request headers. => with nginx 1.8.0 version
It response 500 Internal server error => with nginx 1.6.3 version

the debug log don't show anything else.

2015/10/30 14:11:02 [debug] 10200#0: *96 http cleanup add: 000000000243FB20
2015/10/30 14:11:02 [alert] 10200#0: *96 no upstream configuration, client: 117.6.95.182, server: daotao.vnu.edu.vn, request: "POST /dkmh/login.asp HTTP/1.1", host: "example.com", referrer: "http://example.com/dkmh/login.asp"
2015/10/30 14:11:02 [debug] 10200#0: *96 finalize http upstream request: 500
2015/10/30 14:11:02 [debug] 10200#0: *96 finalize http proxy request
2015/10/30 14:11:02 [debug] 10200#0: *96 http finalize request: 500, "/dkmh/login.asp?" a:1, c:2
2015/10/30 14:11:02 [debug] 10200#0: *96 http special response: 500, "/dkmh/login.asp?"
2015/10/30 14:11:02 [debug] 10200#0: *96 posix_memalign: 0000000001B831B0:4096 @16
2015/10/30 14:11:02 [debug] 10200#0: *96 HTTP/1.1 500 Internal Server Error
Server: nginx/1.6.3
Date: Fri, 30 Oct 2015 07:11:02 GMT
Content-Type: text/html
Content-Length: 594
Connection: close

 version:
nginx version: nginx/1.6.3
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
TLS SNI support enabled
configure arguments: --user=nginx --group=nginx --with-http_ssl_module --with-debug --with-http_geoip_module --with-ipv6 --add-module=../ModSecurity-nginx_refactoring/nginx/modsecurity/

I try to test all patches, but it is still failure.

Please, contact with me if you want to know more information. 

Thanks ./.

**Comment by taibd** [comment]
I had this error while i am trying to reverse a wordpress website, 
post data to wp-login.php login page...WHY?

**Comment by taibd** [comment]
2015/10/30 15:37:12 [debug] 22361#0: *8563 http cleanup add: 000000000252CD20
2015/10/30 15:37:12 [debug] 22361#0: *8563 posix_memalign: 0000000003415820:4096 @16
2015/10/30 15:37:12 [debug] 22361#0: *8563 get rr peer, try: 1
2015/10/30 15:37:12 [debug] 22361#0: *8563 socket 23
2015/10/30 15:37:12 [debug] 22361#0: *8563 epoll add connection: fd:23 ev:80002005
2015/10/30 15:37:12 [debug] 22361#0: *8563 connect to 125.212.195.249:80, fd:23 #8564
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream connect: -2
2015/10/30 15:37:12 [debug] 22361#0: *8563 posix_memalign: 0000000002516D70:128 @16
2015/10/30 15:37:12 [debug] 22361#0: *8563 event timer add: 23: 60000:1446194292506
2015/10/30 15:37:12 [debug] 22361#0: *8563 http finalize request: -4, "/wp-login.php?" a:1, c:2
2015/10/30 15:37:12 [debug] 22361#0: *8563 http request count:2 blk:0
2015/10/30 15:37:12 [debug] 22361#0: *8563 post event 00007FC2F6CA8148
2015/10/30 15:37:12 [debug] 22361#0: *8563 delete posted event 00007FC2F6CA8148
2015/10/30 15:37:12 [debug] 22361#0: *8563 http run request: "/wp-login.php?"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream check client, write event:1, "/wp-login.php"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream recv(): -1 (11: Resource temporarily unavailable)
2015/10/30 15:37:12 [debug] 22361#0: *8563 post event 00007FC2F6CA81B0
2015/10/30 15:37:12 [debug] 22361#0: *8563 delete posted event 00007FC2F6CA81B0
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream request: "/wp-login.php?"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream send request handler
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream send request
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream send request body
2015/10/30 15:37:12 [debug] 22361#0: *8563 chain writer buf fl:0 s:515
2015/10/30 15:37:12 [debug] 22361#0: *8563 chain writer buf fl:1 s:110
2015/10/30 15:37:12 [debug] 22361#0: *8563 chain writer in: 0000000003415880
2015/10/30 15:37:12 [debug] 22361#0: *8563 writev: 625 of 625
2015/10/30 15:37:12 [debug] 22361#0: *8563 chain writer out: 0000000000000000
2015/10/30 15:37:12 [debug] 22361#0: *8563 event timer del: 23: 1446194292506
2015/10/30 15:37:12 [debug] 22361#0: *8563 event timer add: 23: 60000:1446194292514
2015/10/30 15:37:12 [debug] 22361#0: *8563 post event 00007FC2F70B91B0
2015/10/30 15:37:12 [debug] 22361#0: *8563 post event 00007FC2F6CA81B0
2015/10/30 15:37:12 [debug] 22361#0: *8563 delete posted event 00007FC2F70B91B0
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream request: "/wp-login.php?"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream process header
2015/10/30 15:37:12 [debug] 22361#0: *8563 malloc: 000000000664DEF0:4096
2015/10/30 15:37:12 [debug] 22361#0: *8563 recv: fd:23 518 of 4096
2015/10/30 15:37:12 [debug] 22361#0: *8563 http proxy status 400 "400 Bad Request"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http proxy header: "Content-Type: text/html; charset=us-ascii"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http proxy header: "Server: Microsoft-HTTPAPI/2.0"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http proxy header: "Date: Fri, 30 Oct 2015 22:39:09 GMT"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http proxy header: "Connection: close"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http proxy header: "Content-Length: 339"
2015/10/30 15:37:12 [debug] 22361#0: *8563 http proxy header done
2015/10/30 15:37:12 [debug] 22361#0: *8563 modSecurity: header filter
2015/10/30 15:37:12 [debug] 22361#0: *8563 http cacheable: 0
2015/10/30 15:37:12 [debug] 22361#0: *8563 http proxy filter init s:400 h:0 c:0 l:339
2015/10/30 15:37:12 [debug] 22361#0: *8563 http upstream process upstream
2015/10/30 15:37:12 [debug] 22361#0: *8563 pipe read upstream: 1
2015/10/30 15:37:12 [debug] 22361#0: *8563 pipe preread: 339
2015/10/30 15:37:12 [debug] 22361#0: *8563 readv: 1, last:3578

**Comment by zimmerle** [comment]
Hi @taibd, 

Please use gits [1] to paste long content. You may want to try the patch available here: #740

[1] http://gits.github.com

**Comment by arianf** [comment]
@zimmerle
Is there a target date for version 3, libmodsec?

**Comment by arianf** [comment]
One of the most frustrating things about this... is the websites states that the quality of this release is stable.

> ModSecurity for Nginx (Stable Release Quality)

With an issue as big as this, I wouldn't consider this a "Stable Release Quality"

<img width="938" alt="screen shot 2016-02-12 at 4 29 30 pm" src="https://cloud.githubusercontent.com/assets/7397857/13024156/f5255d38-d1a5-11e5-8e35-f49d64f60d16.png">

**Comment by csanders-git** [comment]
@arianf I have updated the website as both @zimmerle and I thought that your complaint was valid. Please see the updated site, we apologize for the confusion: http://modsecurity.org/download.html

**Comment by chewi** [comment]
@ton31337, since it isn't clear when this whole issue will be properly resolved, would it be possible for you to rebase your branch on the latest nginx_refactoring so that we can benefit from other fixes that have been added in the meantime? This would include the other >8K fix. Thanks.

**Comment by zimmerle** [comment]
@chewi did you tested the latest version of the nginx_refactoring branch ?

**Comment by chewi** [comment]
@zimmerle, I did but the issue remains. I can only assume it is @ton31337's fix that is needed in this case.

**Comment by zimmerle** [comment]
@chewi that is interesting because @ton31337's commit was partially merged in the nginx_refactoring branch.

**Comment by chewi** [comment]
Hmmm. I don't think I went wrong anywhere but I'll double check.

**Comment by cukal** [comment]
Hi, I'm running into the same issue.Used latest nginx_refactoring and nginx 2.9.0. 
Which branch should I use to stop this issue from occurring?

Thanks!

2016/04/25 12:46:19 [alert] 25240#0: *1 no upstream configuration, client: xx.xx.xx.xx, server: xxxx.xxx, request: "POST /owncloud/index.php HTTP/1.1", host: "xxx.xx.xx"

**Comment by chewi** [comment]
I never got around to double checking though I am due to look at this again soon. I'm now quite confident that I didn't mess up if you're still seeing it.

**Comment by cukal** [comment]
Okay & Thanks! 
Branch ton31337_x-headers still works btw.

**Comment by chewi** [comment]
Okay, I have now verified this in a different environment. The nginx_refactoring branch as of 207c85d9f7511fb4ad0c158255105a0f5f6cfd82 does not fix the issue. I did not want to use @ton31337's branch as it stands because it's very old now. I rebased nginx_refactoring on v2.9.1 but skipped d135f88254722ee5fe7241d0ad112b8a6017431f so that I could apply 9abda55714d46523576bfb057c9c304d545ea852 instead. This fixed the issue. In short, @zimmerle's version of the fix does not work. You can see the result of my merge at yakara-ltd/ModSecurity@f06751544b99a9abfb740fe4221a704b8b501c06. If it helps, we are seeing this triggered by Apache commons-httpclient 3.0.1 against nginx 1.9.10. I know the former is really ancient but this still shouldn't happen.

**Comment by chewi** [comment]
Unfortunately we had to disable ModSec again after deploying this because requests were randomly having their headers mangled. I don't know the details yet but Rails was picking up the requested domain as localhost instead of the one that was really requested.

**Comment by LoadLow** [comment]
Hello,

I know, it's too late but i've perhaps found a fix.

According to: http://lxr.nginx.org/source/src/http/ngx_http_request.c#1611
server and host should be set, but on the module's context, some properties of headers_in of the new requests are not set, so it sends an internal error.
But, we can set server and host properties in header_in because they're already checked by the core module.

A workaround could be : https://gist.github.com/LoadLow/e970834ddafec73731276faf3cc3e098/revisions#diff-7553afcb7d79f17118afa7cae0e0ef12

I've tested it with OWASP rules and the current stable version of Nginx and it works properly.

Thanks for your consideration,
LoadLow.

**Comment by zimmerle** [comment]
Hi @LoadLow,

This fix is somewhat implemented in the nginx_refactoring branch, however we advice to use the ModSecurity-nginx connector instead of this implementation.

For further information on the ModSecurity-nginx connector, check here:
https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by jinri** [comment]
@ton31337    l  use this branch:  ton31337_x-headers  but get 404  ..
nginx-1.8.1 nginx-1.10.3 ModSecurity_ton31337  nginx_refactoring  .. all had try but no effect 
I use the ubuntu 12.04 .  I have been concerned about this problem for a long time and 
Try all of the above.Crashing in  ...

**Comment by zimmerle** [comment]
@jinri Did you ever tried the ModSecurity v3 with nginx? -
https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by jinri** [comment]
@zimmerle
 I have tried V3.0 master version, it solved the post 500 server error, but there are some configurations can not be achieved (or I do not know how to configure the V3.0).
eg: in modsecurity_rules'  SecRule TX:test_block "@ge" log, deny, phase:2, id:1211111, msg:'testing, block_rule=%{tx.test_id}', redirect:http://www.baidu.com, ruleid=%{tx.test_id} " '
Moreover, in the production environment, we do not dare to use V3.0 for a while until it is stable.
ModSecurity_ton31337 nginx_refactoring, there are several other versions I have tried, nginx_refactoring does not work, ModSecurity_ton31337 returns 404,
Are there any other versions available?

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master

**Comment by shigeya-t** [comment]
https://modsecurity.org/download.html

> NOTE: Some instabilities in the Nginx add-on have been reported (see the Github issues page for details). Please use the "nginx_refactoring" branch where possible for the most up to date version and stay tuned for the ModSecurity version 4.

The Github issues mentioned above is this issue? Is this NOTE still true and should wait for version 4, not version 3?
