### ISSUE TITLE
ModSecurity 2.7.5 On II7

### ISSUE THREAD

**Issue by XiaoR-Works** [SpiderLabs/ModSecurity#584]
I have installed ModSecurity 2.7.5 On II7. I have enabled in web.config.
And all config aren't edited.
But i find in my website, i can't click button in asp.net page.
My button is asp.net server controls.

So, how to fix this problem

**Comment by victorhora** [comment]
The latest build of ModSecurity 2.9.1 for IIS is known to be working fine for IIS 7.

https://github.com/SpiderLabs/ModSecurity/releases/download/v2.9.1/ModSecurityIIS_2.9.1-64b.msi
