### ISSUE TITLE
Modsecurity + nginx "proxy_buffering off" directive == segfault

### ISSUE THREAD

**Issue by mstrent** [SpiderLabs/ModSecurity#585]
I've been beating my head against these segfaults for several days and I finally found the issue. We had a "proxy_buffering off" directive. As soon as I comment that out in the nginx location config, the signal 11s stop.

I've tried compiling various versions of nginx from vanilla 1.4/1.5 sources to Ubuntu package sources, and various versions of modsecurity from the latest release tar.gz to git head and git trunk. All versions exhibited this behavior.

My setup is a reverse proxy. Here's the relevant config snippet:

server{
        listen 443 ssl;
        server_name xxxxxxx;

```
    location / {
            ModSecurityEnabled on;
            ModSecurityConfig /usr/local/modsecurity/etc/modsecurity.conf;
            proxy_pass http://xxxxxx;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_redirect off;
            proxy_buffering off;
            proxy_set_header        Host            $http_host;
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

}

I see this in nginx error log when "proxy_buffering off" and "ModSecurityEnabled on" and accessing the site in a browser:
2013/10/25 10:50:28 [alert] 11873#0: worker process 11875 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11879 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11881 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11884 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11883 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11888 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11887 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11891 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11892 exited on signal 11 (core dumped)
2013/10/25 10:50:28 [alert] 11873#0: worker process 11895 exited on signal 11 (core dumped)

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
