### ISSUE TITLE
Integrate OFDEP IP Reputation Service via a built in directive

### ISSUE THREAD

**Issue by jamuse** [SpiderLabs/ModSecurity#586]
wafsec.com provides a free IP reputation service with integration to ModSecurity via a lua script. It would easier/faster to integrate into ModSecurity if there was a simple directive that allowed integration instead of calling the lua script via ModSec rules. For more info about the API see:
http://wafsec.com/api.html
http://wafsec.com/OfdepModSec
http://wafsec.com/OfdepLua

**Comment by victorhora** [comment]
This API doesn't exist anymore. 

[https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#rbl](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#rbl) or 

[https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecGsbLookupDb](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecGsbLookupDb)

Can be used for IP reputation checks.
