### ISSUE TITLE
ModSec rejects requests larger SecRequestBodyLimit when SecRequestBodyLimitAction is set to ProcessPartial

### ISSUE THREAD

**Issue by spectrumjade** [SpiderLabs/ModSecurity#589]
With ModSec enabled (not in DetectionOnly mode), any requests with bodies larger than SecRequestBodyLimit are rejected, even when SecRequestBodyLimitAction is set to ProcessPartial. This behavior is counter intuitive: when ProcessPartial is set, ModSec should stop buffering bytes but allow the request to continue in accordance with the rules and the data that was buffered.

**Comment by mailtoyogeshpatel** [comment]
I am uploading file from IE8 with 2GB data, in mod security log i am getting error with status code 413 (Request Entity Too Large). in mod security configuration is like : SecRequestBodyLimit 2147000000
SecRequestBodyNoFilesLimit 2147000000

**Comment by gmariani** [comment]
Still getting this error. Using ModSec 2.9.3 on CentOS 7.7.

SecRequestBodyLimit 134217728
SecRequestBodyLimitAction ProcessPartial
SecResponseBodyLimitAction ProcessPartial

Someone tries to upload a 200mb+ file and i get this:
ModSecurity: Request body (Content-Length) is larger than the configured limit (134217728).
ModSecurity: Request body (Content-Length) is larger than the configured limit (134217728).
ModSecurity: Multipart parsing error: Multipart: Final boundary missing.

**Comment by zimmerle** [comment]
@gmariani those limits are also set on the webserver. please double check if that is not the case by disabling temporarily ModSecurity.

**Comment by gmariani** [comment]
@zimmerle Unfortunately the server is for a client (a school) so I can't toy with it too much. I also don't have credentials to the web application they were using on the server to test. But i do know that after I raised the limit from:
```SecRequestBodyLimit 134217728```
to 
```SecRequestBodyLimit 524288000```
they were immediately able to upload the file without issue.

But for reference, here are the other settings/limitations set on the server. As you can see, there _shouldn't_ be anything interfering with it besides ModSec.

**Apache**
```
# Added 8/28/2019 - Increase upload limit from the default to unlimited
LimitRequestBody 0
```

**PHP**
```
file_uploads = On
post_max_size = 4096M
upload_max_filesize = 4096M
```

**Suhosin**
Not enabled

**ModSec**
```
# Changed 10/21/2019 - Increased upload limit from 128M to 500M
SecRequestBodyLimit 524288000
SecRequestBodyNoFilesLimit 1048576
SecRequestBodyLimitAction ProcessPartial
SecResponseBodyLimitAction ProcessPartial
SecRequestBodyAccess On
```

**Comment by celesteking** [comment]
Which leads me to believe `SecRequestBodyLimitAction ProcessPartial` doesn't actually work in v2.9.3.

**Comment by martinhsv** [comment]
@celesteking ,

I don't think that's a correct conclusion.

Be aware, however, that ProcessPartial essentially means that ModSecurity may be examining truncated body content.

If the request is of Content-Type application/x-www-form-urlencoded, then the partial body content will likely still look validly-formatted to ModSecurity.

On the other hand, if the Content-Type is multipart/form-data, then one implication is that the final boundary is likely to be missing from the body content that ModSecurity examines -- which means that the body will appear to be malformed, and hence raise the 'Final boundary missing' condition.  Some other types of input (like json) can also have a comparable result.

**Comment by HOSTED-POWER** [comment]
> Which leads me to believe `SecRequestBodyLimitAction ProcessPartial` doesn't actually work in v2.9.3.

We have the same feeling, we have:

    SecRequestBodyLimitAction ProcessPartial
    SecResponseBodyLimitAction ProcessPartial

and yet we see:

ModSecurity: Multipart parsing error: Multipart: Final boundary missing. 
ModSecurity: Request body (Content-Length) is larger than the configured limit (13107200). 
ModSecurity: Error reading request body: Software caused connection abort
