### ISSUE TITLE
403 Forbidden after installing Mod_security v2.2.5

### ISSUE THREAD

**Issue by neo-art** [SpiderLabs/ModSecurity#590]
Hi,

I installed Mod_security on Ubuntu 12.04 x32 following this tutorial:
http://www.thefanclub.co.za/how-to/how-install-apache2-modsecurity-and-modevasive-ubuntu-1204-lts-server

and now I receive 403 Forbidden error on every page/folder on my website:
You don't have permission to access / on this server
You don't have permission to access /phpmyadmin on this server

I created /etc/modsecurity/modsecurity_custom_rules.conf
and I could probably add custom rule for every specific case i.e.
<
Directory "/var/www/somefolder">

```
<IfModule security2_module>
    SecRuleEngine Off
</IfModule>
```

</Directory>

but is there a simpler way to add more general rules? 

Also is it normal after installing Mod_security to get blocked completely or I did something wrong during the installation?

BTW, tried to install the latest version but looks like it doesn't work with my VPS configuration.

Thanks in advance

---

Copy from the apache2/modsec_audit.log: 

--37e37562-H-- 
Message: Access denied with code 403 (phase 1). Match of "streq %{SESSION.IP_HASH}" against "TX:ip_hash" required. [file "/etc/modsecurity/activated_rules/modsecurity_crs_16_session_hijacking.conf"] [line "35"] [id "981059"] [msg "Warning - Sticky SessionID Data Changed - IP Address Mismatch."] 
Action: Intercepted (phase 1) 
Stopwatch: 1383499867684968 2258 (- - -) 
Stopwatch2: 1383499867684968 2258; combined=634, p1=407, p2=0, p3=0, p4=0, p5=177, sr=109, sw=50, l=0, gc=0 
Response-Body-Transformed: Dechunked 
Producer: ModSecurity for Apache/2.6.3 (http://www.modsecurity.org/); OWASP_CRS/2.2.5; core ruleset/2.2.0. 
Server: Apache/2.2.22 (Ubuntu) 
WebApp-Info: "default" "ljo70mlrrc3rc9fh8ishmfjhu4" ""

**Comment by smashpunk** [comment]
@zimmerle @neo-art I've met the same problem now. What's the conclusion of this issue? 

2016/07/27 15:22:05 [error] 14317#0: [client 10.64.1.48] ModSecurity: Access denied with code 403 (phase 1). Match of "streq %{SESSION.IP_HASH}" against "TX:ip_hash" required. [file "/usr/local/nginx/conf/owasp-modsecurity-crs/optional_rules/modsecurity_crs_16_session_hijacking.conf"] [line "35"] [id "981059"] [msg "Warning - Sticky SessionID Data Changed - IP Address Mismatch."] [hostname "centos-zczy"] [uri "/page/system/forgetPwd.jsp"] [unique_id "3cAcAcAcAcAcAcAcAcAcAcAu"]

**Comment by zimmerle** [comment]
Hi @smashpunk,

Most likely you have a "session" that is being used by more than one IP address. Please check here: https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/optional_rules/modsecurity_crs_16_session_hijacking.conf#L35
