### ISSUE TITLE
AuditLog - Message and Rule ID not logged when long POST data provided

### ISSUE THREAD

**Issue by derhansen** [SpiderLabs/ModSecurity#598]
When an attacker tries to send system commands or a PHP Backdoor by using POST data, the audit log does not show a message and rule ID, when the POST data is very long.

Example: https://gist.github.com/derhansen/7410311

Since the POST data is very long, the Message in line 17 is stripped. It seems, that the Message is limited to **1024 chars**. This makes is hard to debug matching rules, because you do not know the rule ID causing ModSecurity to intercept the request.

At least, the message and rule ID should always be logged and the matched data should be stripped to an maximum amount of chars.

**Comment by zimmerle** [comment]
Hi @derhansen,

Indeed that is a limitation on version 2. There is a hard limit set here:
https://github.com/SpiderLabs/ModSecurity/blob/f66cd4111f08a26d4429cb0071e992deb050928a/apache2/apache2_util.c#L205-L206

This is no longer a limitation on v3.
