### ISSUE TITLE
nginx build requires apache, it shouldn't.

### ISSUE THREAD

**Issue by jvanasco** [SpiderLabs/ModSecurity#603]
it doesn't seem possible to build for nginx without installing apache - the configure script wants/needs to build the DSO with apache's APXS

it would be nice if this could be built without apache, or at least only using the apache source (without having to install apache). the most straightforward way of installing for nginx on an ubuntu machine requires installing the apache2-prefork-dev package, which in turn installs a bunch of unnecessary files and will compete with nginx for control of http services.

**Comment by skeyl** [comment]
What functionality does ModSecurity require from the APR that makes it require APR for nginx?

**Comment by zimmerle** [comment]
Hi @skeyl,

ModSecurity for nginx depends on ModSecurity standalone library. ModSecurity standalone is just a wrapper to Apache internals. In other words: ModSecurity for nginx depends not only on APR but also Apache. All the memory management is made using APR pools.

We are currently working on the libModSecurity which is a version that does not depends on Apache or APR anymore. You can check more information here:

https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/

There is also a "nginx connector" here:

https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by zimmerle** [comment]
Won't fix in 2.x. libmodsecurity no longer depends on apache or apr.

Further information available here - https://github.com/SpiderLabs/ModSecurity-nginx
