### ISSUE TITLE
In Windows Apache, mod_security2 failed to apply 2 rules

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ModSecurity#616]
http://security.stackexchange.com/questions/47002/why-these-2-regexp-wont-work-as-expected-in-mod-security2

Tested & confirmed.
I also think that both regex syntax are okay.

**Comment by wrowe** [comment]
To be clear, httpd requires all path uri components (walking each dir and final filename through the "filesystem" tree) to be a DIR or REG file entry. 

httpd examines each directory path elt to figure out it's 'canonical case' and name (dropping 8.3 etc). These specific file names are actual *files*, they show up as CHR filetype - not DIR or REG, so are rejected immediately as forbidden. Not a mod_sec bug, not an httpd bug. Correct behavior.

Any such pattern rule would simply be idiotic. CON, con, Con., Con<sp> all resolve to the filename. You can't make the correct regex to capture all varieties, if you try you'll end up rejecting perfectly correct entities such as /config/app.php.
