### ISSUE TITLE
SecRuleEngine off - still performance numbers drop

### ISSUE THREAD

**Issue by mitha** [SpiderLabs/ModSecurity#644]
Hi 

modsecurity version - 2.7.5
nginx versoin - 1.4.2
owasp rules set - 2.2.8

I am using modsecurity as WAF inline with nginx serving as reverse proxy.
I am trying to measure the performance of nginx with mod security with SecRuleEngine - off,detection,on and without modsecurity.
What i find is as soon as modsecurity is introduced in nginx.conf ,though SecRuleEngine  is set to off,the performance - transaction per second - TPS drops.There is no significant difference between SecRuleEngine  being set to on/off/detection in TPS measurement.
I could see in the modsecurity debug log that the transactions are not processed 
# My question is :

What i dont understand is,even though the transactions are not processed in modsecurity when SecRuleEngine is off  why the performance should drop when it is introduced in nginx?

configuration                                                       TPS
nginx only                                                             3594
nginx+modsec+SecRuleEngine-off               1399
nginx+modsec+SecRuleEngine-detection    342
nginx+modsec+SecRuleEngine-on                 580

Load generator/Stress tool used  - weighttp(WG)
Configuration:
            The following configuration is kept on for all the below given tests
   total request - 500000
    connection rate - 100/s
    keep alive - on
    file size fetched - 1kb
    cpu - 1

All the fetches are genuine ,No threats were injected
VM size - small
nginx running process - 1 each master,worker,cache manager process

**Comment by zimmerle** [comment]
Marking as won't fix in 2.x. That is already Ok in libmodsecurity. 

https://github.com/SpiderLabs/ModSecurity/tree/v3/master
