### ISSUE TITLE
Support reload rules without stop/start http server

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#648]
Support to reload ModSecurity rules without need to stop the HTTP server.

**Comment by valeriano-manassero** [comment]
Hi, there are news on this feature implementation?
Thanks.

**Comment by umarfarook882** [comment]
Hi, is there any news on this feature? Do anyone working on it. Thanks in advance :)

**Comment by thehelix112** [comment]
Hey @umarfarook882, I think I laid the groundwork for this a while back, however the actual work to reload was done in the http server used by the Edgecast CDN.

We've since moved to a [different WAF engine](https://github.com/VerizonDigital/waflz) that supports this natively.

**Comment by zimmerle** [comment]
This is a feature of 3.1. Already implemented.

**Comment by afeno** [comment]
Hi. How can I reload the rules without restarting http server?  
3.1 seems to suppor that but how can I do it?
