### ISSUE TITLE
How would one configure ModSecurity to handle multiple input/output languages correctly. (western, chinese, japanese)

### ISSUE THREAD

**Issue by kriskater** [SpiderLabs/ModSecurity#651]
How would one configure ModSecurity to handle multiple input/output languages correctly. It seems as though the configuration (SecUnicodeMapFile) only supports one codepage. Is it possible to instruct ModSecurity at runtime using request/response headers for example?

We are running ModSecurity on IIS7.5.

**Comment by victorhora** [comment]
Closing for lack of feedback from reporter. 

Feel free to reopen the issue if the problem persists with the newest installer: https://github.com/SpiderLabs/ModSecurity/releases/download/v2.9.1/ModSecurityIIS_2.9.1-64b.msi
