### ISSUE TITLE
Couldn't find APXS while trying to compile mod security for Nginx on Ubuntu 13.10

### ISSUE THREAD

**Issue by hyperfocus1338** [SpiderLabs/ModSecurity#654]
Trying to compile ModSecurity when directly downloading it directly from the master branch, but no luck yet.

Steps

sudo apt-get install git build-essential libtool autoconf automake libxml2 libxml2-dev libxml2-utils libaprutil1 libaprutil1-dev -y

git clone https://github.com/SpiderLabs/ModSecurity.git mod_security

cd mod_security

sudo ./autogen.sh

./configure --enable-standalone-module

make

Short error:
- stderr: configure: error: couldn't find APXS
- configure: looking for Apache module support via DSO through APXS

Long error: https://gist.github.com/hyperfocus1337/8803328

What am I missing? I prefer not to install Apache libraries to make this work.

**Comment by JingoBD** [comment]
I use nginx and i found same error too.

**Comment by aghontpi** [comment]
on ubuntu 14-lts this should work
apt install apache2-dev,

edit: i used "apache" & came around this issue, solved it by above fix.

**Comment by zimmerle** [comment]
Hi there,

Please use ModSecurity connector instead: https://github.com/SpiderLabs/ModSecurity-nginx
