### ISSUE TITLE
Incomplete Nginx mod security documentation on main website

### ISSUE THREAD

**Issue by hyperfocus1337** [SpiderLabs/ModSecurity#655]
Hello,

On the following page http://www.modsecurity.org/projects/modsecurity/nginx/, there's a link to this downloads page https://github.com/SpiderLabs/ModSecurity/downloads.

Which contains no mod security version for Nginx, and seems to have outdated binaries, which is confusing. It also doesn't tell you the required packages for compilation.

Maybe clarify this for your new users?

**Comment by zimmerle** [comment]
ModSecurity for nginx now has an independent home -
 https://github.com/SpiderLabs/ModSecurity-nginx

This is no longer a concern.
