### ISSUE TITLE
Machine Parseable Audit Log Formats

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/ModSecurity#656]
It would be great to have a new directive such as "SecAuditLog Format" where the user can specify a new output format such as JSON or XML that is more suited for parsing by SIEM systems.  

Example directive usage -
SecAuditLogFormat [TEXT JSON XML]

TEXT would be how it is now, with multi-line entries.
JSON would be JSON formatted and XML would be put into an XML schema.

We would need to think about how to tokenize the audit log data into JSON/XML elements.  We could simply break it up into the audit log PARTS as defined here -
https://github.com/SpiderLabs/ModSecurity/wiki/ModSecurity-2-Data-Formats#wiki-Parts

**Comment by p0pr0ck5** [comment]
I ended up completely refactoring the idea for presenting audit logs as JSON here: https://github.com/p0pr0ck5/ModSecurity/tree/json_audit_logging

This uses yajl and is a much cleaner approach, in that it doesn't stomp on message generation function signatures.

**Comment by zimmerle** [comment]
Pull request #914 was merged. It will be available as part of ModSecurity version 2.9.1
