### ISSUE TITLE
RequestHeader does not work with nginx

### ISSUE THREAD

**Issue by yippibrian** [SpiderLabs/ModSecurity#660]
I am trying to get mod_security 2.7.7 working with nginx 1.2.9 and it seems to work okay until I try to start using the OWASP modsecurity crs.  If I try to use the following configuration file, modsecurity_crs_49_header_tagging.conf, then I get this error when trying to start nginx:

nginx: [emerg] ModSecurityConfig in /usr/local/etc/nginx.conf:157: Unknown command in config: RequestHeader

After spending hours searching for solutions for this problem, I was only able to find a single person who seems to have reported having this kind of problem:

http://comments.gmane.org/gmane.comp.apache.mod-security.owasp-crs/962

In that email, it is pointed out that the nginx HeadersMoreModule (http://wiki.nginx.org/HttpHeadersMoreModule) could perhaps be used to provide the same functionality, but it is not clear to me how it might be possible to make use of an nginx module here instead.  Simply replacing "RequestHeader" lines with "more_set_header" syntax does not seem to work.

I am trying to integrate modsecurity with repsheet (http://getrepsheet.com/), which depends on modsecurity putting the X-WAF-Events & X-WAF-Score headers with the above rule, so I am hoping that there might be some way to get modsecurity to be able to do this with our nginx server.  If the modsecurity code may need to be modified to make this work, I would appreciate any pointers about how to go about implementing this.

**Comment by aminrastgoo** [comment]
I have the same problem but there is no reason why the issue is closed?
Does it mean i should ignore this crs rule file?

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
