### ISSUE TITLE
META-BUG: Reduce the dependency of libapr and apache from the standalone version (nginx and IIS)

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#661]
Due to historical reasons ModSecurity depends on Apache and libapr, even the standalone module which today is used by the Nginx version and IIS. It means that the users have to have Apache and Libapr in order to get ModSecurity build for Nginx.

This meta bug was created to keep register of any effort or ideas in order to get standalone module independent of Apache or libapr.

**Comment by zimmerle** [comment]
#686 depends on this issue.

**Comment by zimmerle** [comment]
This is no longer a concern with libModSecurity. Further information here: https://github.com/SpiderLabs/ModSecurity/tree/v3/master

**Comment by Vincent--** [comment]
Hi,

Is libModSecurity ready for production? Do we have a stable release?
Thanking you in advance.

**Comment by zimmerle** [comment]
There is no official release yet, I would recommend to give it a try.
