### ISSUE TITLE
DURATION fails to accurately work for requests that take more than one second

### ISSUE THREAD

**Issue by aweits** [SpiderLabs/ModSecurity#662]
apr_time_usec is apparently defined as follows:
# define apr_time_usec (   time)    ((time) % APR_USEC_PER_SEC)

Which leads re_variables.c:1740 to not behave as expected when duration exceeds one second.

**Comment by victorhora** [comment]
Fixed as of: https://github.com/SpiderLabs/ModSecurity/commit/3044ad012b7fe0b417374bd032dc183b50ab4fbc
