### ISSUE TITLE
NGINX and SecRequestBodyAccess On option, don't pass POST request to Upstream Server

### ISSUE THREAD

**Issue by zotgene** [SpiderLabs/ModSecurity#664]
On Debian 7.3 64bit, same issue whit nginx 1.4.4 and 1.5.1, ModSecurity is 2.7.7 . Have try whitout rules, whitout SSL and have recompiling many times Nginx and ModSecurity whit different configure option, same issue : if on modsecurity.conf SecRequestBodyAccess is set on On, nothing arrive on upstream Server ( Wireshark checked ) .

```
#nginx.conf
upstream sharepoint  {
      server 192.168.1.100:80; #Sharepoint
}
server {
        listen 192.168.2.20:80;
        server_name pippo.pluto.it;
          location /      {
                        proxy_pass              http://sharepoint; 
                        proxy_redirect          off;
                        proxy_buffering         off;
                        proxy_set_header        Host                pippo.pluto.it;
                        proxy_set_header        X-Real-IP           $remote_addr;
                        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
                        ModSecurityEnabled      on;
                        ModSecurityConfig       modsecurity.conf;
                        }
}
```

```
#modsecurity.conf
SecRuleEngine On
#
SecRequestBodyAccess On
#
SecRule REQUEST_HEADERS:Content-Type "text/xml" \
     "id:'200000',phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"
#
SecRequestBodyLimit 13107200
#
SecRequestBodyNoFilesLimit 131072
#
SecRequestBodyInMemoryLimit 131072
#
SecRequestBodyLimitAction Reject
#
SecRule REQBODY_ERROR "!@eq 0" \
"id:'200001', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"
#
SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
"id:'200002',phase:2,t:none,log,deny,status:44, \
msg:'Multipart request body failed strict validation: \
PE %{REQBODY_PROCESSOR_ERROR}, \
BQ %{MULTIPART_BOUNDARY_QUOTED}, \
BW %{MULTIPART_BOUNDARY_WHITESPACE}, \
DB %{MULTIPART_DATA_BEFORE}, \
DA %{MULTIPART_DATA_AFTER}, \
HF %{MULTIPART_HEADER_FOLDING}, \
LF %{MULTIPART_LF_LINE}, \
SM %{MULTIPART_MISSING_SEMICOLON}, \
IQ %{MULTIPART_INVALID_QUOTING}, \
IP %{MULTIPART_INVALID_PART}, \
IH %{MULTIPART_INVALID_HEADER_FOLDING}, \
FL %{MULTIPART_FILE_LIMIT_EXCEEDED}'"
#
SecRule MULTIPART_UNMATCHED_BOUNDARY "!@eq 0" \
"id:'200003',phase:2,t:none,log,deny,msg:'Multipart parser detected a possible unmatched boundary.'"
#
SecPcreMatchLimit 1000
SecPcreMatchLimitRecursion 1000
#
SecRule TX:/^MSC_/ "!@streq 0" \
        "id:'200004',phase:2,t:none,deny,msg:'ModSecurity internal error flagged: %{MATCHED_VAR_NAME}'"
#
SecResponseBodyAccess Off
#
SecResponseBodyMimeType text/plain text/html text/xml
SecResponseBodyLimit 524288
#
SecResponseBodyLimitAction ProcessPartial
#
SecTmpDir /tmp/
#
SecDataDir /tmp/
#
SecDebugLog /var/log/mod_security/debug.log
SecDebugLogLevel 9
#
SecAuditEngine On
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Concurrent
SecAuditLog /var/log/mod_security/audit.log
#
SecArgumentSeparator &
#
SecCookieFormat 0
#
SecUnicodeMapFile unicode.mapping 20127
```

```
#Modsecurity log
--398c3027-A--
[20/Feb/2014:12:11:56 +0100] AcAcxcAcAcAcAcYcAcACAcAc 11.22.33.44 54093 127.0.0.1 80
--398c3027-B--
POST /_layouts/login.aspx?ReturnUrl=%2f HTTP/1.1
Accept: image/gif, image/jpeg, image/pjpeg, image/pjpeg, application/x-shockwave-flash, application/x-ms-application, application/x-ms-xbap, application/vnd.ms-xpsdocument, application/xaml+xml, */*
Referer: http://pippo.pluto.it/_layouts/login.aspx?ReturnUrl=%2f
Accept-Language: it
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; .NET4.0E)
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
Host: pippo.pluto.it
Content-Length: 569
Connection: Keep-Alive
Cache-Control: no-cache

--398c3027-C--
__LASTFOCUS=&__VIEWSTATE=%2FwEPDwUKMTc0NDQ2ODg4OQ9kFgJmD2QWAmYPZBYCAgMPZBYCAjUPZBYCAgEPZBYCZg9kFgICDQ8QDxYCHgdDaGVja2VkaGRkZGQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgEFJmN0bDAwJFBsYWNlSG9sZGVyTWFpbiRsb2dpbiRSZW1lbWJlck1l1qeKl1MHLq6QY7t46OHWkizdEl8%3D&__EVENTTARGET=&__EVENTARGUMENT=&__EVENTVALIDATION=%2FwEWBQKh1oXMDwLE96mtBQLLtsPBAgLkkP7MCgK%2FlZyyB7GYj%2B2NXtzlE%2BKZXCcgMOT2hSGC&ctl00%24PlaceHolderMain%24login%24UserName=admin&ctl00%24PlaceHolderMain%24login%24password=xxxxxxxx&ctl00%24PlaceHolderMain%24login%24login=Accesso&__spDummyText1=&__spDummyText2=
--398c3027-F--
HTTP/1.1 500 Internal Server Error

--398c3027-H--
Apache-Handler: IIS
Stopwatch: 1392894716000050 257181 (- - -)
Stopwatch2: 1392894716000050 257181; combined=73343, p1=1583, p2=70903, p3=0, p4=0, p5=701, sr=88, sw=156, l=0, gc=0
Producer: ModSecurity for nginx (STABLE)/2.7.7 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: ModSecurity Standalone
Engine-Mode: "ENABLED"

--398c3027-Z--
```

nginx debug log : http://bpaste.net/show/EZwvs4TsjkA64abviKMW/

**Comment by jowrjowr** [comment]
It would be fantastic if this issue was resolved in mainstream. I just setup nginx with mod_security and while I'm loving how well it works (after a bit of tuning with the OWASP rules), it would be nice if I could have both the ability to do POST requests and the ability to have modsec to work on them.

**Comment by wangxianwei** [comment]
Hi @zimmerle @csanders-git, the issue Deny all the POST request #813  have been closed ,but I have installed the modsecurity-2.9.0-RC1 in the Nginx server, the issue is still appearing, after i set the SecRequestBodyAccess to Off, the problem not appear.

**Comment by wangxianwei** [comment]
Hi @zimmerle,
I find the issue is very insteresting!   if I  use the Domina name to vist the website ,all the post request been stoped by the modsecurity. but when I use the IP address to visit the website,the post request can pass.  when use the HTTPS protocal, use the domina name to visit the website,  the post request can pass.

**Comment by zimmerle** [comment]
Hi @wangxianwei for those nginx modifications please use the branch nginx_refactoring, available here:

https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

The modification of the branch nginx_refactoring will be merge into mainline and released once we mitigate all the issues listed here.

**Comment by wangxianwei** [comment]
Hi @Zimmerle, I have download the version from the branch nginx_refactoring, but i dont know how to compile it, because there is no configure file . can you please give me the complete installation package.

**Comment by zimmerle** [comment]
Hi @wangxianwei, that is a development version. The configure is generated after the execution of the ./autogen.sh

**Comment by wangxianwei** [comment]
Hi @Zimmerle,

I have installed the version from the branch nginx_refactoring,but the issue is not resolved. please see the folliowing information.

wwwlogs
192.168.1.250 - - [21/Jan/2015:09:39:01 +0800] "POST /common/memberLogin.jsp HTTP/1.1" 500 186 "http://www.352.com/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0" -0.034

Error Nginx
2015/01/21 09:39:01 [alert] 11601#0: *354 no upstream configuration, client: 192.168.1.250, server: www.352.com, request: "POST /common/memberLogin.jsp HTTP/1.1", host: "www.352.com", referrer: "http://www.352.com/"

Data
--1ff89643-A--
[21/Jan/2015:09:39:01 +0800] AcAcAcAQqcAcA8AcAcAcAcAc 192.168.1.250 59224 127.0.0.1 80
--1ff89643-B--
POST /common/memberLogin.jsp HTTP/1.1
Host: www.352.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Referer: http://www.352.com/
Content-Length: 18
Cookie: 
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

--1ff89643-C--
date=1421804526217
--1ff89643-F--
HTTP/1.1
Content-Type: text/html
Content-Length: 186
Connection: close

--1ff89643-E--
<html>^M
<head><title>500 Internal Server Error</title></head>^M
<body bgcolor="white">^M
<center><h1>500 Internal Server Error</h1></center>^M
<hr><center>nginx</center>^M
</body>^M
</html>^M

--1ff89643-H--
Apache-Handler: IIS
Stopwatch: 1421804341000041 75947 (- - -)
Stopwatch2: 1421804341000041 75947; combined=329, p1=136, p2=179, p3=0, p4=0, p5=13, sr=0, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for nginx (STABLE)/2.9.0-RC2 (http://www.modsecurity.org/).
Server: ModSecurity Standalone
Engine-Mode: "ENABLED"

--1ff89643-K--

--1ff89643-Z--

**Comment by wangxianwei** [comment]
Hi @Zimmerle,
we have found that when we used the 80 port the Post requests failure to pass, but they can success to pass if we used any other ports . by now we don't know how to troubleshoot the issue. any advice is appreciated.

Regards,

**Comment by wangxianwei** [comment]
Hi @Zimmerle,
we have found that when we used the 80 port the Post requests failure to pass, but they can success to pass if we used any other ports . by now we don't know how to troubleshoot the issue. any advice is appreciated.

Regards,

**Comment by wangxianwei** [comment]
Hi @Zimmerle,
we have found that when we used the 80 port the Post requests failure to pass, but they can success to pass if we used any other ports . by now we don't know how to troubleshoot the issue. any advice is appreciated.

Regards,

**Comment by wangxianwei** [comment]
Hi @Zimmerle,
we have found that when we used the 80 port the Post requests failure to pass, but they can success to pass if we used any other ports . by now we don't know how to troubleshoot the issue. any advice is appreciated.

Regards,

**Comment by zotgene** [comment]
I think that if we use a redirect the problem go away. Someone can try?                                                                                                                                                                                                                                                                           Inviata da dispositivo mobile.                                                                                                                                                                                                                                          Da: wangxianweiInviato: giovedì 22 gennaio 2015 14:39A: SpiderLabs/ModSecurityRispondi a: SpiderLabs/ModSecurityCc: zotgeneOggetto: Re: [ModSecurity] NGINX and SecRequestBodyAccess On option, don't pass POST request to Upstream Server (#664)Hi @Zimmerle,
we have found that when we used the 80 port the Post requests failure to pass, but they can success to pass if we used any other ports . by now we don't know how to troubleshoot the issue. any advice is appreciated.

Regards,

—Reply to this email directly or view it on GitHub.

**Comment by ton31337** [comment]
@zotgene, try this https://github.com/SpiderLabs/ModSecurity/pull/826

On Thu, Jan 22, 2015 at 5:11 PM, zotgene <notifications@github.com> wrote:

> I think that if we use a redirect the problem go away. Someone can try?
> Inviata da dispositivo mobile. Da: wangxianweiInviato: giovedì 22 gennaio
> 2015 14:39A: SpiderLabs/ModSecurityRispondi a: SpiderLabs/ModSecurityCc:
> zotgeneOggetto: Re: [ModSecurity] NGINX and SecRequestBodyAccess On option,
> don't pass POST request to Upstream Server (#664)Hi @Zimmerle,
> we have found that when we used the 80 port the Post requests failure to
> pass, but they can success to pass if we used any other ports . by now we
> don't know how to troubleshoot the issue. any advice is appreciated.
>
> Regards,
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpiderLabs/ModSecurity/issues/664#issuecomment-71034461>
> .
>



-- 
Donatas

**Comment by sasah** [comment]
Hello, any news?

**Comment by daniilyar-confyrm** [comment]
Hello, 
Fix in https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring branch works well for us.
Is there any chance for it to be released in nearest stable version?

**Comment by zimmerle** [comment]
Hi @daniilyar-confyrm, 

The `nginx_refactoring' branch in fact contains a lot of fixes, however, some of those fixes may be a problem depending on your environment. We are studying this possibility to release it.

Most likely the next stable release for nginx will be the version 3.0 with the ModSecurity nginx connector: https://github.com/SpiderLabs/ModSecurity-nginx 

We don't have a release date yet.

**Comment by maxmonterumisi** [comment]
Example of error:
2016/11/18 17:34:15 [alert] 13738#0: *18 no upstream configuration, client: 194.183.77.239, server: waf.xxxx.xxxx.cloud, request: "POST /2016F/Session/KeepSessionAliveJson HTTP/1.1", host: "waf.xxxx.xxxx.cloud", referrer: "http://waf.xxxx.xxxx.cloud/2016F/Booking?Albergo=900000&Lingua=0&IdRequest=1078489321"

My system:
root@waf:/usr/local/nginx/logs# uname -a
Linux waf 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

root@waf:/usr/local/nginx/logs# nginx -v
nginx version: nginx/1.10.2

Version of ModSecurity installed:
https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

cd /usr/src/
git clone https://github.com/SpiderLabs/ModSecurity.git
cd /usr/src/modsecurity
./autogen.sh
./configure --enable-standalone-module --disable-mlogc

**Comment by zimmerle** [comment]
Hi @maxmonterumisi 

Please use the ModSecurity-nginx connector: 
https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by zimmerle** [comment]
Marking as won't fix in 2.x. It is no longer a concern in libModSecurity: https://github.com/SpiderLabs/ModSecurity/tree/v3/master
