### ISSUE TITLE
iis: Pack ModSecurity to Windows Web Application Gallery

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#667]
ModSecurity version 2.7.5 is available trough "Windows Web Application Gallery". We want to have our latests version available, for that, we have to build a windows web application gallery compatible package. Those guides explains more about it:
- http://www.iis.net/learn/develop/windows-web-application-gallery/windows-web-application-gallery-principles
- http://www.iis.net/learn/develop/windows-web-application-gallery/package-an-application-for-the-windows-web-application-gallery

**Comment by martinhsv** [comment]
This item would have been iffy to keep open in any case; if it didn't get done in the past seven years, it obviously was not a priority.

In any case, the Windows Web Application Gallery was retired in 2021.

Closing.
