### ISSUE TITLE
@pmf file path and mod_macro

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#670]
mod_macro and it modifies the path of the current config file to "macro 'XXXX' (defined on line XXX of XXX) used on line 5 of XXX".
This breaks the use of a relative path in @pmf.
Although it's a mod_macro issue, we could support this in ModSecurity

**Comment by victorhora** [comment]
The problem stated on the issue was found to be on mod_macro. A proposed patch is available at #745
