### ISSUE TITLE
 SecGsbLookupDb usage

### ISSUE THREAD

**Issue by cello86** [SpiderLabs/ModSecurity#680]
Hi,
I'm trying to test the SecGsbLookupDb feature on mod_security 2.7, but i can't find a correct matching with a malaware domain and I suspect that the GSB file isn't correct.

Could you identify the best way to retrieve a valid database for mod_security or I can't use this feature?

Thanks,
Marcello

**Comment by victorhora** [comment]
Deprecated in 2.7.0 after Google dev team decided to not allow the database download anymore. After registering and obtaining a Safe Browsing API key, you can automatically download the GSB using a tool like wget. For further information on how to proceed with the download, please visit Google's website: https://developers.google.com/safe-browsing/v3/update-guide

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecGsbLookupDb

**Comment by adarshmadrecha** [comment]
The docs on v3 says
> The Safe Browsing Update API (v3) is now deprecated. If you are new to Google Safe Browsing or want to upgrade, use the Safe Browsing Update API (v4).

**Comment by rpharrison** [comment]
I can get the v4 database but instead of one single file there are multiple .gsb4 files, how can these be used with mod security?
