### ISSUE TITLE
Modecurity 2.7.5 incorrect Georgian handling

### ISSUE THREAD

**Issue by nika-chkhikvishvili** [SpiderLabs/ModSecurity#689]
Hi,
I have problem with ModSecurity 2.7.5 and Georgian language. Georgian
is UTF8, has no special code page, any Georgian character considered
as a threat, for example just POSTing: "აბგდევზთი" through simple html
form produces the 403 on server.

apache error_log:
[Mon Mar 24 21:05:09.796806 2014] [:error] [pid 28436] [client
127.0.0.1] ModSecurity: Access denied with code 403 (phase 2). Pattern
match "\\W{4,}" at ARGS:name. [file
"/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_40_generic_attacks.conf"]
[line "37"] [id "960024"] [rev "2"] [msg "Meta-Character Anomaly
Detection Alert - Repetative Non-Word Characters"] [data "Matched
Data: \xe1\x83\x90\xe1\x83\x91\xe1\x83\x92\xe1\x83\x93\xe1\x83\x94\xe1\x83\x95\xe1\x83\x96\xe1\x83\x97\xe1\x83\x98
found within ARGS:name:
\xe1\x83\x90\xe1\x83\x91\xe1\x83\x92\xe1\x83\x93\xe1\x83\x94\xe1\x83\x95\xe1\x83\x96\xe1\x83\x97\xe1\x83\x98"]
[ver "OWASP_CRS/2.2.8"] [maturity "9"] [accuracy "8"] [hostname
"localhost"] [uri "/site.ge/process.php"] [unique_id
"UzBlxfswX8uruQ9JOgLvwwAAAAA"]

rule: 900016 is enabled.
disabling rule: 960024 does not make sense, the next 981318 rule
blocks with the same manner.
any suggestions?

Thanks,
Nick 

other collected information:

env:
$ uname -a
Linux lithium.ge 3.13.6-200.fc20.x86_64

$ cat /etc/redhat-release
Fedora release 20 (Heisenbug)

$ httpd -V
Server version: Apache/2.4.7 (Fedora)
Server built:   Mar  3 2014 12:12:09
Server's Module Magic Number: 20120211:27
Server loaded:  APR 1.5.0, APR-UTIL 1.5.3
Compiled using: APR 1.5.0, APR-UTIL 1.5.3
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

$ httpd -l
Compiled in modules:
  core.c
  mod_so.c
  http_core.c

$ rpm -qa mod_security*
mod_security-2.7.5-2.fc20.x86_64
mod_security_crs-2.2.8-2.fc20.noarch

**Comment by victorhora** [comment]
I would suggest migrating to libModSecurity (3.x) or 2.9.3 and CRS 3.x as well. 

In addition make sure that SecUnicodeCodePage is adjusted as discussed at https://github.com/SpiderLabs/ModSecurity/issues/1587#issuecomment-375710035
