### ISSUE TITLE
ModSecurity for IIS 2.7.3 stops website login action

### ISSUE THREAD

**Issue by atitan** [SpiderLabs/ModSecurity#69]
WinSrv 2008 R2 x64 IIS7.5 with PHP 5.4 via FastCGI

I found this issue existed after enabled Modsec in web.config.
At first, I thought it might be caused by crs rules. However, even I only include modsecurity.conf, it still act the same.

Here are debug log during login process. The webpage couldn't respond until connection timed out.

`Initialising transaction (txid 12538021364746957633).
Transaction context created (dcfg 969290).
First phase starting (dcfg 969290).
Starting phase REQUEST_HEADERS.
Recipe: Invoking rule 299ec08; [file "c:\inetpub\wwwroot\owasp_crs\modsecurity.conf"] [line "24"] [id "200000"].
Transformation completed in 0 usec.
Executing operator "rx" with param "text/xml" against REQUEST_HEADERS:Content-Type.
Operator completed in 0 usec.
Rule returned 0.
Second phase starting (dcfg 969290).
Input filter: Reading request body.
Input filter: Completed receiving request body (length 109).
Starting phase REQUEST_BODY.
Recipe: Invoking rule 299d168; [file "c:\inetpub\wwwroot\owasp_crs\modsecurity.conf"] [line "55"] [id "200001"].
Transformation completed in 0 usec.
Executing operator "!eq" with param "0" against REQBODY_ERROR.
Operator completed in 0 usec.
Rule returned 0.
Recipe: Invoking rule 29a04a8; [file "c:\inetpub\wwwroot\owasp_crs\modsecurity.conf"] [line "76"] [id "200002"].
Transformation completed in 0 usec.
Executing operator "!eq" with param "0" against MULTIPART_STRICT_ERROR.
Operator completed in 0 usec.
Rule returned 0.
Recipe: Invoking rule 29a44d0; [file "c:\inetpub\wwwroot\owasp_crs\modsecurity.conf"] [line "81"] [id "200003"].
Transformation completed in 0 usec.
Executing operator "!eq" with param "0" against MULTIPART_UNMATCHED_BOUNDARY.
Operator completed in 0 usec.
Rule returned 0.
Recipe: Invoking rule 29a5408; [file "c:\inetpub\wwwroot\owasp_crs\modsecurity.conf"] [line "95"] [id "200004"].
Rule returned 0.
Hook insert_filter: Adding input forwarding filter (r 29a9440).
Hook insert_filter: Adding output filter (r 29a9440).`

**Comment by beatinger** [comment]
There is actually another issue with ModSecurity with IIS, and that is, it does not allow objects to be created (error '80004005').  Took quite a while for us to figure this out.  Using very latest version, and problem still exists.
