### ISSUE TITLE
centos6X64 nginx modsercurity 2.7.7 none Cache-Control

### ISSUE THREAD

**Issue by zhangyc0816** [SpiderLabs/ModSecurity#691]
hi
Linux web12 2.6.32-220.el6.x86_64 #1 SMP Tue Dec 6 19:48:22 GMT 2011 x86_64 x86_64 x86_64 GNU/Linux
Nginx 
modsercurity2.7.7
if   include  mod_sercurity.conf none Cache-Control:max-age=900
else  OK.
thank you very much!!!

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
