### ISSUE TITLE
Potentially unexpected result in utf8toUnicode?

### ISSUE THREAD

**Issue by Gonococcus** [SpiderLabs/ModSecurity#694]
ModSecurity/apache2/msc_util.c
Inside utf8toUnicode()
On line 124-125, there is a call to x2c on a single character.
x2c treats the argument passed in as an array of at least length 2.
The char, c, is not an array, but what I am actually unsure about is why
1. data does not increment like all the other instances of data (i.e. data++ = character)
2. a call to x2c(&c) only occurs when (c == 0) or when c is the null character.
x2c and xsingle2c only handles alphabet characters too. So what was the expected result of detecting the null character?

**Comment by victorhora** [comment]
This shouldn't be an issue with libModSecurity (3.x) or 2.9.3.

Please let us know if it's not the case. Thanks!
