### ISSUE TITLE
Add SessionID/RequestID/IP/Host to Debug Log Entries

### ISSUE THREAD

**Issue by DOSarrest** [SpiderLabs/ModSecurity#713]
The debug logs sent through nginx differ than the logs sent to the debug.log file. The debug.log file contains the values...
[localhost/sid#9b5880][rid#21d7f0c0]
But these values are not put sent to the nginx log. The host value also is the local system hostname rather than the hostname of the server running the nginx daemon rather than the hostname of the website that was accessed.
Without this information it's almost impossible to figure out what log entry is for what website. We run multiple websites through nginx via reverse proxying.
Could you please add the sid/rid into the logs sent to nginx along with a proper IP/Host of the site rather than the local server hostname.
We are willing to arrange monetary compensation to have this functionality fixed asap.

**Comment by victorhora** [comment]
Nginx support in ModSecurity 2.9.x branch is deprecated. This shouldn't be a concern with [libModSecurity](https://github.com/SpiderLabs/ModSecurity/tree/v3/master).

Thanks!
