### ISSUE TITLE
nginx segmentation fault with ModSecurity 2.8.0

### ISSUE THREAD

**Issue by defanator** [SpiderLabs/ModSecurity#719]
nginx fails to start worker process in case when no http context is defined in nginx.conf, resulting in cycling segmentation faults.

Proposed fix:
https://github.com/SpiderLabs/ModSecurity/pull/718

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
