### ISSUE TITLE
nginx 1.6/modsecurity 2.8 http request hangs

### ISSUE THREAD

**Issue by ebaron-instart** [SpiderLabs/ModSecurity#724]
Content update by @zimmerle on 2014-May-23, as it may contains sensitive information. The reported bug was not verified, it is under analysis. I will place it back the full report as soon as we verify.

@ebaron-instart whenever you think that something may be a security issue contact the developers directly, otherwise you will publish recipe for attackers. Thanks for the report.

**Comment by tovbinm** [comment]
@oddjobz @zimmerle  I experience the same issue ("Out of memory") with POST requests on Nginx 1.8.0/2.9.2 using ["modsecurity.conf-recommended"](https://github.com/SpiderLabs/ModSecurity/blob/master/modsecurity.conf-recommended) config on Debian. Any suggestions?

**Comment by zimmerle** [comment]
Hi @tovbinm are you using the nginx_refactoring branch ?

https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

**Comment by tovbinm** [comment]
@zimmerle no,  I was using 2.9.0 release. 

As you suggested, I checked out the `nginx_refactoring` branch and recompiled the plugin and nginx. Everything seems to be working just fine now. Thank you.

Are there any plans for a proper release?

**Comment by zimmerle** [comment]
Hi @tovbinm,

Glad to know that nginx_refactoring is working in your environment. It will be merged once we got all known nginx issues fixed.
