### ISSUE TITLE
Phase-1 drop leaves Apache-Handler proxy-server stuck

### ISSUE THREAD

**Issue by ferrieux** [SpiderLabs/ModSecurity#725]
When a rule decides a drop in phase 1, the TCP is immediately closed (which is good and intended), however the handler behind is still somehow called. If this handler is "proxy-server", it will stay stuck until the global request timeout (5mn) shuts it down.
This has the nasty side-effect of keeping an Apache thread of process busy all that time.

Example with a (CRS-inspired) rule that drops GETs with a content-length:

SecRule REQUEST_METHOD "^(?:GET|HEAD)$" \
  "msg:'GET or HEAD Request with Body Content.',\
  severity:'2',\
  id:'960011',\
  phase:1,\
  drop,\
  logdata:'%{matched_var}',\
  t:none,\
  tag:'OWASP_CRS/PROTOCOL_VIOLATION/INVALID_HREQ',\
  tag:'CAPEC-272',\
  chain"
        SecRule REQUEST_HEADERS:Content-Length "!^0?$"\
          "t:none,\
          setvar:'tx.msg=%{rule.msg}',\
          setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},\
          setvar:'tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/INVALID_HREQ-%{matched_var_name}=%{matched_var}'"

The %D (duration) log pattern, for such cases, expands to 300000000 (5 minutes), though tcpdump shows that the TCP was terminated quickly (FINs exchanged with client).

**Comment by victorhora** [comment]
Closing this one as the bug was found to be on libapr.

**Comment by csanders-git** [comment]
has the issue been fixed upstream in libapr? are they aware of the issue?

**Comment by victorhora** [comment]
I don't think so @csanders-git. But feel free to submit the pull request if you want to help us: https://github.com/apache/apr/blob/1.6.x/support/unix/waitio.c =)

Thanks!

**Comment by marcstern** [comment]
Did you reproduce it in Apache 2.4?

**Comment by marcstern** [comment]
This looks a very safe patch (useless in the worth case), so I created a pull request for it.
https://github.com/apache/apr/pull/5

**Comment by victorhora** [comment]
Nice @marcstern!

But I just noticed something: I'm not sure if Apache will eventually accept that pull request on Github. It looks like this is only a mirror and there's some pending PR over there which looks like nobody is looking at.

Maybe pull requests needs to be submitted using their own process: 

https://apr.apache.org/patches.html
https://git-wip-us.apache.org/

What you think about trying submitting to these ones as well to make sure it will be on their pipeline? :)

**Comment by marcstern** [comment]
Patch submitted on https://bz.apache.org/bugzilla/show_bug.cgi?id=61985
