### ISSUE TITLE
Piping audit log though mlogc does not work

### ISSUE THREAD

**Issue by oniric85** [SpiderLabs/ModSecurity#727]
Hi,
I'm using ModSecurity 2.8.0 with IIS 7.5 on Windows Server 2008 R2. I would like to pipe audit log through mlogc but somehow it is not working. Here is the error message I get:

```
Syntax error in config file C:\Program Files\ModSecurity IIS\modsecurity.conf, line 200: ModSecurity: Failed to open the audit log pipe: C:/PROGRA~1/MODSEC~1/mlogc.bat
```

I don't know if this is a limitation of the IIS version, could you please state it if this is the case?

**Comment by victorhora** [comment]
The build process was [refactored](https://github.com/SpiderLabs/ModSecurity/pull/1487) and should be easier to test these changes if needed.

MLogC should be working as of the current v2 code in master. Please let us know if this issue persist with the current release/code. 

Thanks.
