### ISSUE TITLE
nginx with modsecurity-2.8.0 coredump

### ISSUE THREAD

**Issue by 316953425** [SpiderLabs/ModSecurity#732]
nginx compile with modsecurity-2.8.0,when reload nginx ,the error log print the following message:
2014/06/04 01:08:31 [alert] 7076#0: worker process 7251 exited on signal 11 (core dumped)

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
