### ISSUE TITLE
nginx reverse proxy strips response headers from backend

### ISSUE THREAD

**Issue by pwyliu** [SpiderLabs/ModSecurity#735]
In a set up like this:

```
(client) <--> (nginx+modsec reverse proxy) <--> (backend web server)
```

If the backend server adds a new response header, modsec doesn't pass it to the client. 

This happens even if all the rules are disabled and `SecRuleEngine Off` is set. It seems anything new that is added by the backend will get dropped. 

We noticed this because we were trying to byte serve a PDF from the backend. Chrome uses range requests, but modsec drops the `Content-Range` header from the response, so it makes the client download the file forever.

I set up a super tiny test environment with `nginx 1.6.0` and `modsec 2.8.0` and could recreate the issue there. [Here is a gist](https://gist.github.com/pwyliu/2c38aca0cd0b92139ace) with some logs and the configs. We also saw this in another similar set up which was `nginx 1.4.4` and `modsec 2.7.7`.

I hope I didn't miss anything, please let me know if any more info is needed.

**Comment by zimmerle** [comment]
Fixed by: #749.

**Comment by davidgenn** [comment]
Hi @zimmerle Has this been included in a release? 

I've just compiled the latest version of Nginx (1.11.6) with Modsecurity (2.9.1). Nginx is acting as a reverse proxy for a Jetty server. I'm using the default OWASP rules (3.0.0).

The Java app is adding headers to the response which are being stripped out by Modsecurity. It was fine before Modsecurity was added. 

Thanks in advance!

**Comment by zimmerle** [comment]
Hi @davidgenn,

Please use the `nginx_refactoring' branch. Or the ModSecurity-nginx connector:
https://github.com/SpiderLabs/ModSecurity-nginx
