### ISSUE TITLE
Post request lead to nginx crash on nginx 1.7.0 and ModSecurity nginx_refactoring branch 

### ISSUE THREAD

**Issue by yicol** [SpiderLabs/ModSecurity#748]
when I have two or more virtual hosts,and config these vhosts (modsecurity on and SecRequestBodyAccess On),then a normal post request lead nginx crash,and gdb debug as fallows:
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1402153440824304 (LWP 84515) ]
ngx_http_upstream_init_request (r=0x794d00) at src/http/ngx_http_upstream.c:598
 594     if (u->resolved == NULL) {
 595
 596         uscf = u->conf->upstream;
 597 #if (NGX_HTTP_SSL)
 598         u->ssl_name = uscf->host;
 599 #endif
 600
uscf is NULL
but this will not happen when only one vhost,Can guys help me, thanks!

**Comment by zimmerle** [comment]
There are some configuration changes that may temporary fix this issue on yours environment, please see: #664

**Comment by CFJSGeek** [comment]
I am also having the issue where as modSecurity blocks POST requests to IIS/Lucee ColdFusion on Windows 2012R2 server using the default modsecurity.conf with SecRequestBodyAccess turned on. If I turn off SecRequestBodyAccess then POST params go through as expected. I looked at #664 for a temp fix, but it seems to be directly related to nginx only.

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
