### ISSUE TITLE
Nginx: infinite loop->crash with http response 302 with no content.

### ISSUE THREAD

**Issue by scaarup** [SpiderLabs/ModSecurity#750]
In the process of setting up Nginx as reverse proxy in front of my apaches I have come across a bug which crashes nginx.
When the client sends the following:
POST /netbank/invoice_ok HTTP/1.1
Host: 172.26.11.11
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:30.0) Gecko/20100101 Firefox/30.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: Chunked
DNT: 1
Cookie: PMLCID=XXXXXXXXXXXXXXXXXX
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 3
x=x

Nginx crashes in an infinite loop at src/http/ngx_http_write_filter_module.c:116
The response Nginx receives from apache is (which never comes back to the client):
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.6.0
Date: Mon, 30 Jun 2014 14:44:54 GMT
Content-Type: text/plain
Content-Length: 0
Connection: keep-alive
Location: ​http://google.com

And after some debugging it is discovered that it only happens with POST requests and only with Content-Length: 0 on the response-header. If I add content to the response-body and a corresponding Content-Length in the response, it works fine. I have compiled Nginx with version 2.8 of modsecurity and this problem only occurs if I enable modsecurity (Detection mode only does not matter)! However, the infinite loop is occuring in the Nginx code, but as I can only reproduce it when modsecurity enabled, Nginx has refused to help me. I have tested both Nginx 1.7.1 and 1.6.0 and they act the same way.
To easier reproduce this I created a perl-script (below) which can be served with netcat and sends the above response. Running it in a loop like this: while true; do perl redirect.cgi | nc -l -p 1500 ; sleep 1; done.

redirect.cgi (perl):
# !/usr/bin/perl

print "HTTP/1.1 302 Moved Temporarily\r\n";
print "Date: Mon, 30 Jun 2014 12:25:15 GMT\r\n";
print "Server: Apache\r\n";
print "X-Server-Name: server11\r\n";
print "Jokum: server11\r\n";
print "Location: http://google.com\r\n";
print "Content-Length: 0\r\n";
print "Connection: close\r\n";
print "Content-Type: text/plain\r\n";
print "\r\n";

**Comment by scaarup** [comment]
Do we still have to run refactoring branch to not crash on Nginx?

**Comment by baiys** [comment]
@scaarup hello ,i have same issue with you ,when i request with Request Method:POST,Status Code:302 Found ,the nginx was crash  ,and i can't find any useful information to modsec_audit.log or debug.log ,Do you have any idea ?thank you.

**Comment by scaarup** [comment]
@baiys Hello! The only workaround for me, is to use the refactoring branch. Is even that one not working for you?

**Comment by scaarup** [comment]
@zimmerle will this ever be merged to master?

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
