### ISSUE TITLE
IIS 2.8.0 breaking updatepanel 

### ISSUE THREAD

**Issue by doublej42** [SpiderLabs/ModSecurity#754]
I've installed ModSecurity IIS 2.8.0 and have SecRuleEngine DetectionOnly

My modsecurity_iis.conf looks like:
Include modsecurity.conf
# Include modsecurity_crs_10_setup.conf
# Include owasp_crs\base_rules*.conf
# Include Nanaimo_whiteList.conf

But it's still doing something to my requests.
I'm submitting a request form an ms ajax update panel that ms magic should respond to with something like
1|#||4|15978|updatePanel|ContentPlaceHolder1_objUpdate|
            <div>
But I'm getting raw HTML

If I comment the first line (Include modsecurity.conf) my app works as expected.

I noticed that when it works it also returns text/plain not text/html

The javascript error varies depending on what version of webforms I'm using but I've confirmed it in multiple version.

 My setup: Windows Server 2008 SP2

To create a test project in visual studio create a new webforms project

default:.aspx:

``` ASPX
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <asp:UpdatePanel ID="UpdatePanel1" 
                 UpdateMode="Conditional"
                 runat="server">
    <ContentTemplate>
       <fieldset>
       <legend>UpdatePanel content</legend>
        <!-- Other content in the panel. -->
        <%=DateTime.Now.ToString() %>
           <asp:TextBox ID="tbInput" runat="server"></asp:TextBox>
           <asp:Label ID="lblInput" runat="server" Text="Label"></asp:Label>
        <br />
        <asp:Button ID="Button1" 
                    Text="Refresh Panel" 
                    runat="server" OnClick="Button1_Click" />
        </fieldset>
    </ContentTemplate>
</asp:UpdatePanel>
```

default.aspx.cs:

``` C#
  public partial class _Default : Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            lblInput.Text = tbInput.Text;
        }
    }
```

Possible information related to the page life cycle: http://weblogs.asp.net/leftslipper/sys-webforms-pagerequestmanagerparsererrorexception-what-it-is-and-how-to-avoid-it

**Comment by victorhora** [comment]
Hi @doublej42 

You probably need to set SecStreamInBodyInspection to On. See #1300 (comment).
