### ISSUE TITLE
X forwarded for not passed in REQUEST_HEADERS_NAMES

### ISSUE THREAD

**Issue by ahmedqadeer1989** [SpiderLabs/ModSecurity#756]
Hello 

I have been trying to get X forwarded for for the past couple of days but no luck and when i try to get all the headers i only get these headers 

Expanded "REQUEST_HEADERS_NAMES" to "REQUEST_HEADERS_NAMES:Host|REQUEST_HEADERS_NAMES:Connection|REQUEST_HEADERS_NAMES:Cache-Control|REQUEST_HEADERS_NAMES:Accept|REQUEST_HEADERS_NAMES:Pragma|REQUEST_HEADERS_NAMES:User-Agent|REQUEST_HEADERS_NAMES:Accept-Encoding|REQUEST_HEADERS_NAMES:Accept-Language|REQUEST_HEADERS_NAMES:Cookie".

is there any possibility of getting x forwarded for in it ? 
I am using 2.7.7 and i can see x forwarded for in a trace captured so which means my apache is sending x forwarded for but mod security is not processing it 

I would appreciate a reply

Thanks

Ahmed

**Comment by benwilliams** [comment]
If you have mod remoteip directive "RemoteIPHeader X-Forwarded-For" modsecurity will not see the header.
