### ISSUE TITLE
disrupt action doesn't get a chance to execute

### ISSUE THREAD

**Issue by mariodsantana** [SpiderLabs/ModSecurity#765]
When performing disruptive actions, the execute function of the intercept action (if any) should be performed as well, since the intercept action might have some fixups to do.  (E.g., if the intercept action is proxy, it might want to expand macros in the uri...)

Here's a small patch that fixes it for me.

```
--- modsecurity-apache_2.7.4/apache2/re.c   2013-05-26 21:33:36.000000000 -0600
+++ modsecurity-apache_2.7.4_expand_macros_in_proxy/apache2/re.c    2014-08-01 00:21:51.000000000 -0600
@@ -2447,6 +2447,11 @@
             }
         }
     }
+    if (actionset->intercept_action_rec->metadata->type == ACTION_DISRUPTIVE) {
+        if (actionset->intercept_action_rec->metadata->execute != NULL) {
+            actionset->intercept_action_rec->metadata->execute(msr, mptmp, rule, actionset->intercept_action_rec);
+        }
+    }

     /* If "noauditlog" was used do not mark the transaction relevant. */
     if (actionset->auditlog != 0) {
```

PS, thanks for the work and the software!  I've been a fan for a long time, and finally have time to follow up on some interesting ideas from a while back.  Obviously, the interesting stuff I'm doing has to do with the proxy action.  These two patches I've submitted fix these issues for me, I apologize if they're not up to snuff with the coding standards for the project.  I'd be happy to fix any problems with the patches and resubmit... or if these issues aren't really code-level issues, I'd love to learn how to use the software correctly.

Thanks again!

**Comment by victorhora** [comment]
This was fixed as of https://github.com/SpiderLabs/ModSecurity/commit/258e5545a2ba4a064004ccfedba015c1904cbdaa
