### ISSUE TITLE
Plesk Panel 12 and ModSecurity 2.8.0

### ISSUE THREAD

**Issue by BugsFinder** [SpiderLabs/ModSecurity#773]
Dear Developers,

For default modsecurity.conf set next settings:
::::::::::::::::::::::::::::::::::::::::
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
::::::::::::::::::::::::::::::::::::::::

On Plesk Panel web-server IIS have next settings for upload files:
::::::::::::::::::::::::::::::::::::::::
2147483647
::::::::::::::::::::::::::::::::::::::::

on php.ini
::::::::::::::::::::::::::::::::::::::::
upload_max_filesize=2147483647
::::::::::::::::::::::::::::::::::::::::

When users try to upload files more that 10mb, Plesk Panel freeze (down), help only recycling Application Pool. Could you help me understand, how can I configure to send error page like 403, not freeze Plesk Panel?

**Comment by victorhora** [comment]
Closing for lack of feedback. Let us know if the issue still happens with the latest version of ModSecurity.
