### ISSUE TITLE
mod_security bug with random numbers generation

### ISSUE THREAD

**Issue by gilperon** [SpiderLabs/ModSecurity#781]
I finally could create a way to reproduce the bug that I am having. When 2 or more users call a page at the same second modsecurity generates the same random number (using rand() function from php) to all users.

Here is a demonstration of the bug:

http://quemfazsite.com.br/em_criacao/modelo9/teste.php

Opening this page 2 iframes will load and each one should be generating random numbers independetly of each other but both frames are generating the same random numbers! The very simple source code can be seen at:

http://pastebin.com/8ELAnmdp

If this is not the right place to post this kind of bug please tell me the right place. This is my first contribution and I dont know too much about this community.

**Comment by zimmerle** [comment]
Hi @gilperon the current mainline code contains the fix for that issue. The fix was provided by @micha137. Thank you for the report and thanks @micha137 for the fix [#838]  ;)

It will be release as of v2.9.1. The release date is not defined yet.
