### ISSUE TITLE
modsecurity high memory usage 60-70%

### ISSUE THREAD

**Issue by ton31337** [SpiderLabs/ModSecurity#785]
Hello,

is it possible to avoid caching all the rules including body content in memory? Because after 2-3 days we have 60-70% memory usage.. Extracting memory dumps there are as expected, rules and body cached inside the memory.

Any idea how to bypass this caching? Or maybe is any way to reduce to minimal this behavior?

Donatas.

**Comment by zimmerle** [comment]
Hi @men18,

I recommend you to switch to libModSecurity and nginx connector:
https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by men18** [comment]
Hello @zimmerle 

Thanks for your answer !

It's precisely what i use (with CRS rule in v3.0), but my problem is about increasing memory in Nginx.
For now i can't be sure that the increasing memory (or memory leak) is on ModSecurity or other part of Nginx, how to be sure ?


My conf  : 
nginx version: nginx/1.11.9
built by gcc 4.9.2 (Debian 4.9.2-10)
built with OpenSSL 1.0.1t  3 May 2016
TLS SNI support enabled
configure arguments: --add-module=../ModSecurity-nginx --with-debug --with-cc-opt='-O0 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' 
<img width="1203" alt="capture d ecran 2017-02-07 a 14 02 55" src="https://cloud.githubusercontent.com/assets/1558463/22692566/ec78bfa2-ed3f-11e6-9ad1-34070d504615.png">
--with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro' --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --with-pcre-jit --with-http_ssl_module --with-http_realip_module

**Comment by zimmerle** [comment]
Do you mind to open another issue to keep track of this memory problem? Initially #785 refers to ModSecurity version 2.x

**Comment by men18** [comment]
Ok, Done #1318
