### ISSUE TITLE
Correcting the default log locations in IIS version of modsecurity.conf

### ISSUE THREAD

**Issue by brianclark** [SpiderLabs/ModSecurity#788]
Hello,

The default version of modsecurity.conf that gets installed via the 2.8.0 installer contains references to incorrect log locations. The effect of these incorrect references is that ModSecurity is prevented from logging anything. 

I believe this is the file that needs to be modified:
https://github.com/SpiderLabs/ModSecurity/blob/master/iis/wix/modsecurity.conf

It is the SecAuditLog directives which cause the most problems as they appear correct at first glance, but are actually incorrect (\log\ should be \logs).

Currently, the directives are:
# SecAuditLog c:\inetpub\log\modsec_audit.log
# SecAuditLogStorageDir c:\inetpub\log\

These should be changed to reflect the actual default directories in c:\inetpub:
# SecAuditLog c:\inetpub\logs\modsec_audit.log
# SecAuditLogStorageDir c:\inetpub\logs\

Also, since we are setting correct default log locations for IIS, I suggest setting a correct location for SecDebugLog as well.

It is currently set to:
# SecDebugLog /opt/modsecurity/var/log/debug.log

This should be changed to:
# SecDebugLog c:\inetpub\logs\debug.log

Thanks,
Brian Clark

**Comment by victorhora** [comment]
Fixed as of https://github.com/SpiderLabs/ModSecurity/commit/22322ce355a24e50de18b530b52b0bf9e57660cb

Thanks!
