### ISSUE TITLE
nginx/1.7.2 with modsecurity-2.8.0 high cpu load

### ISSUE THREAD

**Issue by Pilotat** [SpiderLabs/ModSecurity#793]
When i want to use mod securtiy for filtering REQUEST_BODY i must enable SecRequestBodyAccess in order to be able to filet the requests.

When i set 'SecRequestBodyAccess On' when i make POST request with post data not bigger than a word the nginx worker hags at 100% CPU usage and does nothing. I tried to strace the worker and it seems to make 3 read from /dev/urandom and then does nothing.

Even if i have no rules that process REQUEST_BODY with SecRequestBodyAccess enabled the worker uses 100% CPU.

If i disable SecRequestBodyAccess there is no such problem but filters that include REQUEST_BODY are NOT working.

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
