### ISSUE TITLE
Breaks NGINX stub_status module

### ISSUE THREAD

**Issue by infinitnet** [SpiderLabs/ModSecurity#803]
A recent compilation of the nginx_refactoring branch causes stub_status to break - it keeps increasing the "Active connections" and "Waiting connections" counters (normally the values should be sub 2k):

``` shell
# curl localhost/server-status
Active connections: 11393 
server accepts handled requests request_time
 29955 29955 84845 17087726
Reading: 8 Writing: 455 Waiting: 10609
```

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
