### ISSUE TITLE
nginx 1.6.2 Cannot open config file: /etc/nginx/modsecurity.conf

### ISSUE THREAD

**Issue by rz300** [SpiderLabs/ModSecurity#805]
I have installed mod-security on my debian 7.7 and nginx 1.6.2 with https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Installation_for_NGINX, than i make my nginx with
<code>--add-module=/home/anubis/downloads/modsecurity-2.8.0/nginx/modsecurity</code> and install it.
My nginx -V

<pre>
nginx version: nginx/1.6.2 
built by gcc 4.7.2 (Debian 4.7.2-5) 
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx
--conf-path=/etc/nginx/nginx.conf
--error-log-path=/var/log/nginx/error.log 
--http-client-body-temp-path=/var/lib/nginx/body 
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi 
--http-log-path=/var/log/nginx/access.log 
--http-proxy-temp-path=/var/lib/nginx/proxy 
--http-scgi-temp-path=/var/lib/nginx/scgi 
--http-uwsgi-temp-path=/var/lib/nginx/uwsgi 
--lock-path=/var/lock/nginx.lock 
--pid-path=/var/run/nginx.pid 
--with-pcre-jit 
--with-debug 
--with-http_addition_module 
--with-http_dav_module 
--with-http_geoip_module 
--with-http_gzip_static_module 
--with-http_image_filter_module
--with-http_realip_module 
--with-http_stub_status_module 
--with-http_ssl_module 
--with-http_sub_module 
--with-http_xslt_module 
--with-ipv6 
--with-sha1=/usr/include/openssl 
--with-md5=/usr/include/openssl 
--with-mail --with-mail_ssl_module 
--add-module=/home/anubis/modsecurity-2.8.0/nginx/modsecurity 
--add-module=/home/anubis/testcookie-nginx-module-master
</pre>

and i added in config <code>ModSecurityEnabled on; ModSecurityConfig modsecurity.conf;</code> but when i start the nginx, i see this: <code>Starting nginx: nginx: [emerg] ModSecurityConfig in /etc/nginx/sites-enabled/id-st.ru.conf:99: Cannot open config file: /etc/nginx/modsecurity.conf nginx: configuration file /etc/nginx/nginx.conf test failed</code> 
What am i doing wrong?

**Comment by kulitkerang** [comment]
> `adding module in /home/anubis/modsecurity-2.8.0/nginx/modsecurity`
> ` `
> 
>     ` `
> 
>     * `ngx_http_modsecurity was configured`
>       but when make i see:
>       objs/ngx_modules.o \
>             /home/anubis/modsecurity-2.8.0/nginx/modsecurity/../../standalone/.libs/standalone.a -lpthread -lcrypt -L/usr/lib -lapr-1 -L/usr/lib -laprutil-1 -I/usr/include/apache2 -L/usr/lib -lxml2 -L/usr/lib/x86_64-linux-gnu -lpcre -L/usr/lib -lm -L/usr/lib/x86_64-linux-gnu -lpcre -lpcre -lssl -lcrypto -ldl -lz -lxml2 -lxslt -lexslt -lgd -lGeoIP
>       cc: error: /home/anubis/modsecurity-2.8.0/nginx/modsecurity/../../standalone/.libs/standalone.a: No such file or directory
>       make[1]: **\* [objs/nginx] Error 1
>       make[1]: Leaving directory `/home/anubis/nginx-1.6.2'
>       make: **\* [build] Error 2

i have same trouble at it
