### ISSUE TITLE
Newbie - how do I disable or add a rule? 500 error

### ISSUE THREAD

**Issue by hcanning2014** [SpiderLabs/ModSecurity#809]
Hi All,
On Ubuntu 14.04 how do I disable a rule say 981143 for my domain or just disable mod_security2 totally in htaccess or another file?
Thanks

**Comment by shrv** [comment]
SecRuleRemoveById 981143 in conf file
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleRemoveById
or
comment out this set of rules in a file modsecurity_crs_43_csrf_protection.conf
#SecRule &ARGS "@ge 1" "chain,phase:2,id:'981143',t:none,block,msg:'CSRF Attack Detected - Missing CSRF Token.'"
 #SecRule &ARGS:CSRF_TOKEN "!@eq 1" "setvar:'tx.msg=%{rule.msg}',setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:tx.%{rule.id}-WEB_ATTACK/CSRF-%{matched_var_name}=%{matched_var}"

**Comment by zimmerle** [comment]
@hcanning2014, @shrv: remember to use SecRuleRemoveById after the rule in question be loaded. (Use SecRuleRemoveById after all the includes...)
