### ISSUE TITLE
Wrong IP in error_log, right IP in modsec_audit.log

### ISSUE THREAD

**Issue by dallasproit** [SpiderLabs/ModSecurity#811]
WHM
Apache 2.4
PHP 5.5
Nginx/Varnish from Unixy v12.2

We have 4 servers that are setup using templates so that settings are unified between all 4 boxes. Everything has been working fine. We then needed to upgrade one to new hardware and followed the same templates and transferred accounts from one box to the new one. I copied over the WordPress rules I have to monitor WP login failures and block when 10 are detected. On this new box, the Hits List shows the right client IP address, the modsec_audit.log shows the right IP address, but when it logs to the apache error_log, it is logging the servers main IP address for client IP so CSF can't block the attack. Other kinds of attacks such as FTP and failed POP/IMAP are being blocked, so Nginx is configured properly. We then copied all the configuration files over thinking there was just something that was missed, but we have the same behavior. The last box we rolled out was in August and it worked fine, so I can't seem to find why modsec is logging the right IP address in one log, but the server IP in the error_log. Please see the log entries below. 173.244.xxx.xx is the server IP and the 173.245.xx.xx was the network I was testing from.

Apache error_log
[Mon Dec 08 01:29:45.871388 2014] [:error] [pid 10322] [client 173.244.xxx.xx] ModSecurity: Access denied with code 401 (phase 2). Operator GT matched 0 at USER:bf_block. [file "/usr/local/apache/conf/modsec2.user.conf"] [line "10"] [id "5000135"] [msg "ip address blocked for 5 minutes, more than 10 login attempts in 3 minutes."] [hostname "www.xxxxxxxxxxxx.com"] [uri "/wp-login.php"] [unique_id "VIVTaa30lGIAAChSWpsAAAAU"]

Modsec_audit.log
--818ab839-A--
[08/Dec/2014:01:29:47 --0600] VIVTaq30lGIAACf8C3IAAAAA 173.245.xx.xx 56966 173.244.xxx.xx 8083
--818ab839-B--
GET /wp-login.php HTTP/1.0
Host: www.xxxxxxxxxx.com
Cookie: PHPSESSID=617fd3602a6e0018b6fd4827562b9bd5; __utmc=11403297; __cfduid=dd7aab3f69fff2a06a55505c2fdb6e5721418023589; __utma=11403297.351384672.1418023677.1418023677.1418023677.1; __utmb=11403297.1.10.1418023677; __utmz=11403297.1418023677.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1; wordpress_test_cookie=WP+Cookie+check
X-Real-IP: 173.245.xx.xx
X-Forwarded-Host: www.xxxxxxxxxxx.com
X-Forwarded-Server: www.xxxxxxxxxxx.com
CF-IPCountry: US
CF-RAY: 195740fe00d00932-DFW
X-Forwarded-Proto: http
CF-Visitor: {"scheme":"http"}
Accept: text/html, application/xhtml+xml, _/_
Accept-Language: en-US
User-Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)
DNT: 1
CF-Connecting-IP: 64.183.236.50
True-Client-IP: 0
X-Forwarded-For: 173.244.xxx.xx
connection: close
X-Varnish: 638255431

--818ab839-F--
HTTP/1.1 302 Moved Temporarily
X-Powered-By: PHP/5.5.19
Vary: Cookie
X-CF-Powered-By: WP 1.3.14
X-Pingback: http://www.xxxxxxxxxxx.com/xmlrpc.php
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Pragma: no-cache
Location: http://www.xxxxxxxxxxx.com/wp-login.php
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8

--818ab839-H--
Message: Access denied with code 401 (phase 2). Operator GT matched 0 at USER:bf_block. [file "/usr/local/apache/conf/modsec2.user.conf"] [line "10"] [id "5000135"] [msg "ip address blocked for 5 minutes, more than 10 login attempts in 3 minutes."]
Action: Intercepted (phase 2)
Apache-Handler: fcgid-script
Stopwatch: 1418023786890304 312026 (- - -)
Stopwatch2: 1418023786890304 312026; combined=306, p1=88, p2=17, p3=0, p4=0, p5=117, sr=63, sw=84, l=0, gc=0
Producer: ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/).
Server: Apache
Engine-Mode: "ENABLED"

**Comment by furysama** [comment]
Are you using mod_rpaf on apache, or mod_remoteip?

**Comment by dallasproit** [comment]
You can ignore. We have switched because we got nowhere with Unixy on the issue. We tried both rpaf and remoteip.

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master

**Comment by iraqiboy90** [comment]
Sorry for reviving an old thread, but has this ever been fixed in 3.x? I currently have v2.9

**Comment by martinhsv** [comment]
@iraqiboy90 ,

This dates from well before my time on the project, but the comment before yours (from 2017) says that it was fixed in libModSecurity (aka ModSecurity v3), so you should assume that that is correct.

**Comment by Rdago** [comment]
im having the same issue on the standalone modsec version. not sure if i need to change the source files or if theres a way to customize the log format on standalone on modsec config
