### ISSUE TITLE
SecAuditLogParts not working: mod_security keeps logging response body

### ISSUE THREAD

**Issue by san7812** [SpiderLabs/ModSecurity#819]
I have set SecAuditLogParts in modsecurity.conf to just log ABFH, but the modsecurity audit log keeps logging -E- part (response body) making the audit log too large.

What can I do to disable response body logging?

**Comment by 3skr0** [comment]
up

**Comment by glennslaven** [comment]
I'm also seeing this behaviour,  I have this in the config

`SecAuditLogParts ABCFHZ`

But my log ends up with parts ABFEHZ

Running modsecurity 2.7.7 with apache 2.4.7 on ubuntu 14.04

**Comment by p0pr0ck5** [comment]
@glennslaven is it possibly because you have 'C' in part of your directive?

**Comment by glennslaven** [comment]
@p0pr0ck5 'C' is the request body, not the response body.  Is there a connection between them in the audit log?

**Comment by p0pr0ck5** [comment]
@glennslaven ah, sorry, i misread that. My bad!

Is it possible that you are using rules whose actionset contains 'ctl:auditLogParts=+E'? This would enable audit logging of response body even if that part isn't enabled in the `SecAuditLogParts` config directive. I believe a number of the CRS base rules contains this action:

<pre>
poprocks@soter:~/code/SpiderLabs-owasp-modsecurity-crs/base_rules$ grep -l 'ctl:auditLogParts=+E' *
modsecurity_crs_40_generic_attacks.conf
modsecurity_crs_41_sql_injection_attacks.conf
modsecurity_crs_41_xss_attacks.conf
modsecurity_crs_42_tight_security.conf
modsecurity_crs_45_trojans.conf
modsecurity_crs_50_outbound.conf
</pre>

**Comment by glennslaven** [comment]
@p0pr0ck5 yep, that's it the sql_injection rules are putting it back in!

Using `SecResponseBodyAccess Off` at least stops the bloat of the audit log

Thanks

**Comment by san7812** [comment]
Thanks @p0pr0ck5 and @glennslaven! I had lost my hopes with this issue...

**Comment by victorhora** [comment]
Confirmed this is not an issue with ModSecurity. As mentioned, ctl:auditLogParts=+E adds the E log parts to the AuditLog.

**Comment by adelca** [comment]
Setting `SecResponseBodyAccess Off` does not stop modsecurity audit log from logging response body on OWASP_CRS/3.3.2
