### ISSUE TITLE
gzip encoding / OWASP_CRS/LEAKAGE/SOURCE_CODE_ASP_JSP

### ISSUE THREAD

**Issue by ArnCo** [SpiderLabs/ModSecurity#821]
Hi,

I encountered a problem on our Apache reverse proxy running ModSecurity (embedded mode). I am currently getting a considerable amount of "OWASP_CRS/LEAKAGE/SOURCE_CODE_ASP_JSP" warnings, as ModSecurity does not seem to recognize gzip content as such (the pattern <% is matched in the encoded content).

Of course, the encoding is disabled between the backend and the reverse Proxy, as content is encoded directly on this very reverse proxy. 

I am using the default Ubuntu 14.04 ModSecurity configuration and CRS, repo version. 
The VirtualHost configuration is really simple as well,

```
<VirtualHost *:15080>
  DocumentRoot /var/www/www.<host>.com/html
  ServerName host.com
  ServerAlias www.host.com

  ProxyPreserveHost On

  ProxyPass / http://<host>/ retry=0
  ProxyPassReverse / http://<host>/
</VirtualHost>
```

I have read a significant amount of (quite old) threads about the problem but each one of them seem to be a dead end.

Waiting for yor feedback,

ArnC

**Comment by victorhora** [comment]
Please let us know if the issue persists with a newer version of ModSecurity such as 2.9.2 or v3 ([libModSecurity](https://github.com/SpiderLabs/ModSecurity/tree/v3/master))

Also would suggest updating to the latest version (3.x) of [OWASP CRS](https://github.com/SpiderLabs/owasp-modsecurity-crs/) to avoid false positives.

Thanks!
