### ISSUE TITLE
nginx reverse proxy + mod_security = segfault

### ISSUE THREAD

**Issue by dusty73** [SpiderLabs/ModSecurity#823]
I just made a test with nginx 1.7.9 and mod_security for nginx, following this tutorial: http://www.nginxtips.com/how-to-install-mod_security-on-nginx/

I configured nginx as reverse proxy with mod_security enabled. After few requests nginx was segfaulting, always when serving images. I checked the coredump, this is the output:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  ngx_http_upstream_copy_allow_ranges (r=0x2678680, h=0x7fff406e6f40, offset=<optimized out>) at src/http/ngx_http_upstream.c:4571

4571        if (r->upstream->conf->force_ranges) {

so I tried to set proxy_force_ranges flag (which was unset) in configuration and the segfault went away.

Note that if I turn off modsecurity the proxy alone works fine.

**Comment by driehuis** [comment]
This appears to be an issue in nginx. The ngx_http_upstream_copy_allow_ranges routine just gets the ngx_http_request_t *r, that modsecurity got passed as an (opaque) parameter. Modsecurity doesn't appear to touch the ngx_http_request_t. Setting proxy_force_ranges as you suggested works around the issue by causing r->upstream->conf to be defined, but I think this would be preferable:

This diff works around this issue for me, without having to force proxy ranges:
````c
--- orig/nginx-1.7.9/src/http/ngx_http_upstream.c	2014-12-23 16:28:40.000000000 +0100
+++ nginx-1.7.9/src/http/ngx_http_upstream.c	2015-02-10 14:29:10.211240721 +0100
@@ -4569,5 +4569,5 @@
     ngx_table_elt_t  *ho;
 
-    if (r->upstream->conf->force_ranges) {
+    if (r->upstream->conf && r->upstream->conf->force_ranges) {
         return NGX_OK;
     }
````

**Comment by gnought** [comment]
I have tried the version before v1.7.7 does not have any segmentation issue until reaching to 1.7.7. The proxy_force_ranges directive appears from v1.7.7 and it is default to off. To solve, i suggest to turn it on if using Modsecurity modules for Nginx.
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_force_ranges

**Comment by kipras** [comment]
Nice, @driehuis patch fixes the issue, thanks! :)

**Comment by driehuis** [comment]
The official answer from the nginx maintainers is [https://trac.nginx.org/nginx/ticket/690](https://trac.nginx.org/nginx/ticket/690). To quote:

> The ngx_http_upstream_copy_allow_ranges() function is a handler called to copy headers within upstream module. It is expected to be only called when r->upstream exists and r->upstream->conf is set. If it's called with r->upstream->conf not set - it means the bug is elsewhere.

So, the workaround patch has been rejected and the mod_security interface must be rewritten to eliminate the `ngx_http_upstream_copy_allow_ranges()` call, or make it at the appropriate time. I do not know enough of the innards of both nginx and mod_security to be able to help here, unfortunately.

**Comment by andrepearce** [comment]
I have just ran into this issue also, using modsecurity-2.9.1.

Do we know if this will be getting correctly handled in the mod_security interface?

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
