### ISSUE TITLE
How to define the SecAuditLog ?

### ISSUE THREAD

**Issue by wangxianwei** [SpiderLabs/ModSecurity#829]
I have install the modsecurity in Nginx, Now I need to use the mlogc. when I set the SecAuditLog '|/usr/local/modsecurity/bin/mlogc /etc/mlogc.conf' to SecAuditLog. Restart the Nginx,
the error like this:
nginx: [emerg] ModSecurityConfig in /app/soft/nginx/conf/nginx.conf:64: Syntax error in config file /app/soft/nginx/conf/modsecurity.conf, line 201: ModSecurity: Failed to open the audit log pipe: /usr/local/modsecurity/bin/mlogc /etc/mlogc.conf

**Comment by leonelr** [comment]
Mate, from memory... back in the day you could not use mlogc piped with Nginx module version. But there was a python script that you could use instead (mlogc-batch-load.pl), that script is still there, at least on the 2.8 steam, have a look it may shed some light.

**Comment by zimmerle** [comment]
@wangxianwei check if ia permission issue.
Hi @wangxianwei,

More information on SecAuditLog is available here: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLog

The mlogc-batch-load.pl that @leonelr is referring to, is available here: 
https://github.com/SpiderLabs/ModSecurity/blob/master/mlogc/mlogc-batch-load.pl.in

if mlogc-batch-load.pl is not available in our distro, download ModSecurity code run ./automake.sh &&
./configure this should create the .pl file with the correct paths.

**Comment by wangxianwei** [comment]
Hi @leonelr @zimmerle ,
I can find the mlogc-batch-load.pl in the /opt/modsecurity-2.9.0-RC1/mlogc.
If in set the value , SecAuditLog '/usr/local/modsecurity/bin/mlogc /etc/mlogc.conf'
the error info:
nginx: [emerg] ModSecurityConfig in /app/soft/nginx/conf/nginx.conf:64: Syntax error in config file /app/soft/nginx/conf/modsecurity.conf, line 201: ModSecurity: Failed to open the audit log file: /usr/local/modsecurity/bin/mlogc /etc/mlogc.conf
nginx: configuration file /app/soft/nginx/conf/nginx.conf test failed

 If i set the value like this in the modsecurity.conf like:
  SecAuditLog '/etc/mlogc.conf'
  SecAuditLog '/usr/local/modsecurity/bin/mlogc'
restart the nginx ,there is no error.but I can find the erro in the mlogc-error.log
[Mon Jan 19 14:23:32 2015] [3] [12158/0] Configuring ModSecurity Audit Log Collector 2.9.0-RC1.
[Mon Jan 19 14:23:32 2015] [3] [12158/0] Delaying execution for 5000ms.
[Mon Jan 19 14:23:37 2015] [3] [12158/0] Queue file not found. New one will be created.
[Mon Jan 19 14:23:55 2015] [3] [12158/0] Caught SIGINT, shutting down.
[Mon Jan 19 14:23:55 2015] [3] [12158/0] ModSecurity Audit Log Collector 2.9.0-RC1 terminating normally.
~

**Comment by zimmerle** [comment]
Hi @wangxianwei, there is a mlogc-batch-load.pl.in in your mlogc directory?

**Comment by wangxianwei** [comment]
Hi @zimmerle, 
I have installed the new version from the  branch nginx_refactoring, I can find the following info:
root@SZ-TEST-RD01 bin]# pwd
/usr/local/modsecurity/bin
[root@SZ-TEST-RD01 bin]# ll
total 132
-rwxr-xr-x. 1 root root 113018 1月  21 08:26 mlogc
-rwxr-xr-x. 1 root root   3370 1月  21 08:26 mlogc-batch-load.pl
-rwxr-xr-x. 1 root root  12796 1月  21 08:26 rules-updater.pl

After, I set the SecAuditLog value , the error is still can be found when restart the Niginx. I confire the Modsecurity use the folloing command:
./configure --enable-standalone-module  --with-apr=/usr/local/apr --with-pcre=/usr/local/pcre
Is there any problem to install the Mlogc with the Modsecurity?

**Comment by wangxianwei** [comment]
Hi @zimmerle,
I using the following command to inactive the mlgoc:
./mlogc-batch-load.pl /log/modsecurity/data /usr/local/modsecurity/bin/mlogc /etc/mlogc.conf
The error info  in the following


[Wed Jan 28 08:58:25 2015] [3] [30569/0] Configuring ModSecurity Audit Log Collector 2.9.0-RC2.
[Wed Jan 28 08:58:25 2015] [3] [30569/0] Delaying execution for 5000ms.
[Wed Jan 28 08:58:32 2015] [3] [30569/0] Loaded 10948 entries from the queue file.
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:08:19 +0800] \"POST /communication/getPartnerInfo.do HTTP/1.1\" - 186 \"http://www.352.com/\" \"-\" AcAcAcJJkcAcAcA1A@AcMcAg \"-\" /20150119/20150119-1708/20150119-170819-AcAcAcJJkcAcAcA1A@AcMcAg 0 1576 md5:90f7408c67e767c785a7c36f4cf4cb72
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:12:37 +0800] \"POST /communication/getPartnerInfo.do HTTP/1.1\" - 186 \"http://www.352.com/information/financing_list.jsp?type=%E8%B5%84%E4%BA%A7&typeName=%E6%94%B6%E8%B4%B9%E6%9D%83\" \"-\" AcocAcbc6cAcKcAyAcAcAcAc \"-\" /20150119/20150119-1712/20150119-171237-AcocAcbc6cAcKcAyAcAcAcAc 0 1710 md5:274199c512e5a369bc2139bacc073bb7
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:12:37 +0800] \"POST /common/memberLogin.jsp HTTP/1.1\" - 186 \"http://www.352.com/information/financing_list.jsp?type=%E8%B5%84%E4%BA%A7&typeName=%E6%94%B6%E8%B4%B9%E6%9D%83\" \"-\" Acac@cABAcjxAsAcBcAcjcAc \"-\" /20150119/20150119-1712/20150119-171237-Acac@cABAcjxAsAcBcAcjcAc 0 1781 md5:62fc43657f77210ec82b415784430155
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:12:13 +0800] \"POST /communication/getPartnerInfo.do HTTP/1.1\" - 186 \"http://www.352.com/\" \"-\" AnAcAcAyAcAcAcAwAcAcAhA5 \"-\" /20150119/20150119-1712/20150119-171213-AnAcAcAyAcAcAcAwAcAcAhA5 0 1599 md5:45b812fe3048c79a14b4524d7e4976c9
[Wed Jan 28 08:58:32 2015] [2] [30569/7f8d140009c0] Invalid entry (failed to match regex): SZ-TEST-RD01 192.168.1.250 - - [19/Jan/2015:17:12:12 +0800] \"POST /common/memberLogin.jsp HTTP/1.1\" - 186 \"http://www.352.com/\" \"-\" A6pcIpAcAcAcApAcAcAcAcAc \"-\" /20150119/20150119-1712/20150119-171212-A6pcIpAcAcAcApAcAcAcAcAc 0 1433 md5:1ea05ec580f1d19564908088138d47ed
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d14000ae0] Flagging server as errored after failure to submit entry AcJcAc9cAcAcAcAcAbAcAcAc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d14000c90] Flagging server as errored after failure to submit entry lcAcAcAcAcAcAcAcAcAcAcWc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d14000e40] Flagging server as errored after failure to submit entry AcAcJcAcAcAcAXgcAcAcAcAc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d14000ed0] Flagging server as errored after failure to submit entry AcZcAcAGAcArAeAcAcAcAcAc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [2] [30569/7f8d140009c0] Flagging server as errored after failure to submit entry AcAcAcAwActcAMAcAUAcAcAc with HTTP response code 403: Forbidden
[Wed Jan 28 08:58:33 2015] [3] [30569/0] No more data to read, emptying buffer: End of file found
[Wed Jan 28 08:58:33 2015] [3] [30569/7f8d206d4158] Running final transaction checkpoint.
[Wed Jan 28 08:58:33 2015] [3] [30569/0] ModSecurity Audit Log Collector 2.9.0-RC2 terminating normally.

**Comment by wangxianwei** [comment]
Hi @zimmerle @leonelr

It always print the error log in the error log using the  mlogc-batch-load.pl, so the log can not be pushed to the log receiver.any advice is appreciated.

[Fri Mar 27 11:55:54 2015] [3] [28916/254a7e8] Running final transaction checkpoint.
[Fri Mar 27 11:55:54 2015] [3] [28916/0] ModSecurity Audit Log Collector 2.9.0 terminating normally.
[Fri Mar 27 12:00:01 2015] [3] [29519/0] Configuring ModSecurity Audit Log Collector 2.9.0.
[Fri Mar 27 12:00:01 2015] [3] [29519/0] Delaying execution for 5000ms.
[Fri Mar 27 12:00:06 2015] [3] [29519/0] No more data to read, emptying buffer: End of file found
[Fri Mar 27 12:00:06 2015] [3] [29519/0] Waiting for queue to empty (2 active).
[Fri Mar 27 12:00:06 2015] [2] [29519/16578f0] Invalid entry (failed to match regex): GZ-APP-NGINX(FW)01 192.168.1.250 - - [27/Mar/2015:11:24:35 +0800] \"GET /communication/js/chat-web/1.0.0/chat_window/ChatWindow.js HTTP/1.1\" - 162 \"http://www.352.com/\" \"-\" AcAYA3AcAcAcAcAcXcAkeXAc \"-\" /20150327/20150327-1124/20150327-112435-AcAYA3AcAcAcAcAcXcAkeXAc 0 3466 md5:e797bdc7a88d573114f5b51535c46a7d
[Fri Mar 27 12:00:06 2015] [2] [29519/1657860] Invalid entry (failed to match regex): GZ-APP-NGINX(FW)01 192.168.1.250 - - [27/Mar/2015:11:39:48 +0800] \"GET /images/ad/tip_right_hover.png HTTP/1.1\" - 162 \"http://www.352.com/style/alltop.css?cssVersion=2015032709\" \"-\" AcArAcADqcAcOcAcAcAcAcAc \"-\" /20150327/20150327-1139/20150327-113948-AcArAcADqcAcOcAcAcAcAcAc 0 3536 md5:ed27f6881b20e66d141e283986d64792
[Fri Mar 27 12:00:06 2015] [3] [29519/15e47e8] Running final transaction checkpoint.
[Fri Mar 27 12:00:06 2015] [3] [29519/0] ModSecurity Audit Log Collector 2.9.0 terminating normally.

Regards,

**Comment by charlymps** [comment]
I think it's related to #977

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
