### ISSUE TITLE
Modsecurity and websockets

### ISSUE THREAD

**Issue by sk1981** [SpiderLabs/ModSecurity#831]
We are using NGINX with modsecurity. The setup works very nicely with json rest.
Is it possible to do the same with Websockets ? If yes, is there any example for this ?

Thanks in advance !

**Comment by xaionaro** [comment]
Confirm. Modsecurity forces status code "200" instead of "101". WebSockets doesn't work…

**Comment by csanders-git** [comment]
@xaionaro is this unique to Nginx? While testing I was able to send a response code of 101 cleanly through a stock modsec instance. Can you elaborate on the problem a bit more?

**Comment by zimmerle** [comment]
As explained in #1368, ModSecurity is not capable to inspect WebSockets. It is only capable to understand the http requests.
