### ISSUE TITLE
RHEL6 no apr_crypto.h

### ISSUE THREAD

**Issue by martinjina** [SpiderLabs/ModSecurity#834]
Hi,

(Rhel 6.6, modsecure-2.9.0-RC2, 6.2.2015)
rhel6 apr-devel rpm was not compiled with crypto support - apr_crypto.h. 
Please use parametr for ./configure and don't use apr_crypto.h in h and c file.

Quickly
I use mod_secure and download from GITLAB (6.2.2015)

https://github.com/SpiderLabs/ModSecurity

and press button "DOWNLOAD ZIP"

Untar,unzip ModSecurity-master.zip

2.

./autogen.sh
./configure --enable-standalone-module

make - make error arp_crypto.h not file

I change source file modsecurity.h and msc_remote_rules.c (msc_remote_rules.h), then it is ok.

vi apache2/modsecurity.h

line 55

#include "apr_crypto.h"

change and comment

//#include "apr_crypto.h"

vi apache2/msc_remote_rules.c

line 27 comment //#include "apr_crypto.h"

and

make

make is OK...

**Comment by zimmerle** [comment]
Thank you for the report @martinjina.

Fixed by #f9464b46bf3cddcf857c453cc2524b2cacf2b73b

It will be include on the release 2.9.0.

See the commit comments to have more details on how the problem got fixed.
