### ISSUE TITLE
Mod Security Installation issue in AIX 6.1

### ISSUE THREAD

**Issue by anil4376** [SpiderLabs/ModSecurity#846]
Hi, I tried Installing Mod Security in AIX Box, it blews with below issue during compilation it self.. 

I used below list of versions 
1. Mod Security 2.9
2. Apache 2.2.29 and/or 2.4.12
3. libxml - 2.9.2
4. PCRE - 8.36
5. apr 1.5.1 (used only for Apache 2.4 version)
6. apr-util - 1.5.4(used only for Apache 2.4 version)

I installed Apache and other things successfully. but when i configure and make modsecurity.. its blowing with below issues.. 

 /bin/sh ../libtool  --tag=CC    --mode=link gcc -I/home/apps/apache/apache2/include   -I/opt/freeware/include -DWITH_CURL  -I/home/apps/apache/pcre8.36/include -g -O2  -I/home/apps/apache/apache2/include   -lpthread     -o mlogc mlogc-mlogc.o /home/apps/apache/apache2/lib/libapr-1.la  -L/opt/freeware/lib -lcurl -lidn -lssh2 -lssl -lcrypto -llber -lldap -lssl -lcrypto -lz  -L/home/apps/apache/pcre8.36/lib -lpcre
libtool: link: cannot find the library `/opt/freeware/lib/libldap.la' or unhandled argument`/opt/freeware/lib/libldap.la'
make: 1254-004 The error code from the last command is 1.

I tried with Apache libtool file as well.. but no luck.

Thanks
AK

**Comment by zimmerle** [comment]
Hi @anil4376, 

that seems to be related to the mlogc compilation. Do you mind to try to compile with the following configuration options:

```
$ ./configure --disable-mlogc --with-curl=/tmp
```

Let me know if the compilation works with those flags.

**Comment by anil4376** [comment]
Thanks for you reply Zimmerle , 

Gr8, Now I can compile it successfully.. but when i include it with Apache webserver, i can see 
./apachectl[101]: 7864534 Segmentation fault(coredump)

below is the dbx trace included.. 
----------------------------------------------
dbx httpd core
------------------------------
Type 'help' for help.
[using memory image in core]
reading symbolic information ...internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found 's__LC_locale:,768,32;__meth_ptr:90,800,32;__data_ptr:90,832,32;;'
internal error: 1283-228 expected char ',', found '__LC_locale:,768,32;__meth_ptr:90,800,32;__data_ptr:90,832,32;;'
internal error: 1283-228 expected char ';', found '_LC_locale:,768,32;__meth_ptr:90,800,32;__data_ptr:90,832,32;;'
internal error: unexpected value 44 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found '768,32;__meth_ptr:90,800,32;__data_ptr:90,832,32;;'
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found 's_LC_locale_objhdl:,64,32;;'
internal error: 1283-228 expected char ',', found '_LC_locale_objhdl:,64,32;;'
internal error: 1283-228 expected char ';', found 'LC_locale_objhdl:,64,32;;'
internal error: unexpected value 44 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found '64,32;;'
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found 'sapr_file_t:,704,32;;'
internal error: 1283-228 expected char ',', found 'apr_file_t:,704,32;;'
internal error: 1283-228 expected char ';', found 'pr_file_t:,704,32;;'
internal error: unexpected value 44 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found '704,32;;'
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found 'sprochr:,3776,32;pv_cached_credp:90,3808,32;pv_handlers_lock:1901,3840,32;pv_wlm_nvpages:-32,3904,64;pv_vmm_xproc_data:2112=*2113=xsvm_xproc_data:,3968,32;pv_eyec:2094,4000,32;pv_kcid:2093,4032,16;pv_secflag:-3,4048,16;pv_mcrp:90,4064,32;;'
internal error: 1283-228 expected char ',', found 'prochr:,3776,32;pv_cached_credp:90,3808,32;pv_handlers_lock:1901,3840,32;pv_wlm_nvpages:-32,3904,64;pv_vmm_xproc_data:2112=*2113=xsvm_xproc_data:,3968,32;pv_eyec:2094,4000,32;pv_kcid:2093,4032,16;pv_secflag:-3,4048,16;pv_mcrp:90,4064,32;;'
internal error: 1283-228 expected char ';', found 'rochr:,3776,32;pv_cached_credp:90,3808,32;pv_handlers_lock:1901,3840,32;pv_wlm_nvpages:-32,3904,64;pv_vmm_xproc_data:2112=*2113=xsvm_xproc_data:,3968,32;pv_eyec:2094,4000,32;pv_kcid:2093,4032,16;pv_secflag:-3,4048,16;pv_mcrp:90,4064,32;;'
internal error: unexpected value 44 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found '3776,32;pv_cached_credp:90,3808,32;pv_handlers_lock:1901,3840,32;pv_wlm_nvpages:-32,3904,64;pv_vmm_xproc_data:2112=*2113=xsvm_xproc_data:,3968,32;pv_eyec:2094,4000,32;pv_kcid:2093,4032,16;pv_secflag:-3,4048,16;pv_mcrp:90,4064,32;;'
internal error: unexpected value 120 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found 'svm_xproc_data:,3968,32;pv_eyec:2094,4000,32;pv_kcid:2093,4032,16;pv_secflag:-3,4048,16;pv_mcrp:90,4064,32;;'
internal error: 1283-228 expected char ',', found 'vm_xproc_data:,3968,32;pv_eyec:2094,4000,32;pv_kcid:2093,4032,16;pv_secflag:-3,4048,16;pv_mcrp:90,4064,32;;'
internal error: 1283-228 expected char ';', found 'm_xproc_data:,3968,32;pv_eyec:2094,4000,32;pv_kcid:2093,4032,16;pv_secflag:-3,4048,16;pv_mcrp:90,4064,32;;'
internal error: unexpected value 44 at line 5160 in file stabstring.c
internal error: 1283-228 expected char ',', found '3968,32;pv_eyec:2094,4000,32;pv_kcid:2093,4032,16;pv_secflag:-3,4048,16;pv_mcrp:90,4064,32;;'
internal error: unexpected value 120 at line 5160 in file stabstring.c


Thanks
AK

**Comment by zimmerle** [comment]
Hi @anil4376 

Great to hear that it is compiling :) Sorry we don't have AIX on our build bots yet.

When this coredump happened there was any ModSecurity configuration loaded? Or simple the .so file?

**Comment by anil4376** [comment]
I tried with simple .so load, and also with base configurations too.. here is the config

LoadModule security2_module modules/mod_security2.so
 
<IfModule security2_module>
                # Basic configuration options
               SecRuleEngine On
               SecRequestBodyAccess On
               SecResponseBodyAccess Off

                # Debug log
               SecDebugLog logs/modsec_debug.log
               SecDebugLogLevel 0

                # Maximum request body size we will;
                # accept for buffering 2048*1024 (2 MB)
               SecRequestBodyLimit 2097152
</IfModule>

and with out mod_security package apache is up and running as expected..

**Comment by victorhora** [comment]
This shouldn't be an issue with libModSecurity (3.x) or 2.9.3. 

Please let us know if it's not the case. Thanks!
