### ISSUE TITLE
nginx + modsecurity as reverse proxy

### ISSUE THREAD

**Issue by taibd** [SpiderLabs/ModSecurity#847]
I have some questions when i install modsecurity on nginx.

1. Some frameworks have a option which calls "rewrite url". I want to know that modsecurity can detect parameters sent from client or data from server sent to client when it is hidden in url rewrite.
2. I am developing a big project relevant to modsecurity on nginx, but i have a problem which many topics are discussed. this is error "worker process exited on signal 11 (core dumped)". i want to know that this bug is fixed and how to fix it??

**Comment by zimmerle** [comment]
Hi @taibd,

For nginx, please use our refactoring branch:
 - https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

What you mean by hidden in url rewrite? 

For faster answer you may want to use our users ml: 
- https://lists.sourceforge.net/lists/listinfo/mod-security-users
