### ISSUE TITLE
@ipMatch "Could not add entry" on slash/32 notation in 2.9.0

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/ModSecurity#849]
Bug https://github.com/SpiderLabs/ModSecurity/issues/706 is back, but in a much less harmful way.

The following rule does not work in 2.9.0
`SecRule REMOTE_ADDR "@ipMatch 127.0.0.1/32" "phase:1,nolog,pass,msg:’Localhost connection’,id:1"` 

resulting in the following error on startup:
`Error creating rule: Could not add entry "127.0.0.1/32" from: 127.0.0.1/32.`

`SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" "phase:1,nolog,pass,msg:’Localhost connection’,id:1"` 
works though.

Unfortunately, there does not seem to be a test in
https://github.com/SpiderLabs/ModSecurity/blob/master/tests/op/ipMatch.t
to catch this misbehavior.

**Comment by victorhora** [comment]
Fixed as of https://github.com/SpiderLabs/ModSecurity/commit/619a5ae7f483235281fba69fa758119c54114218

**Comment by dune73** [comment]
Thank you @victorhora. 

This has the 2.x label, but I think it is only fixed for the 3.x line. Correct?
