### ISSUE TITLE
SecRuleUpdateActionById does not work in vhost context

### ISSUE THREAD

**Issue by tchwpkgorg** [SpiderLabs/ModSecurity#850]
I'm trying to use mod_security with a large number of vhosts.

What I found out, is Apache refuses to start on a small VM (512 MB) with 20-30 vhosts and mod_security rules loaded per vhost.

Therefore, I've decided to load the rules globally (no memory pressure in that case) and modify them in vhost context with SecRuleUpdateActionById.

Unfortunately, it doesnt work.

I've tried loading modsecurity_crs_35_bad_robots.conf in global context and then allow it to bypass the traffic (but still logging the violators) with the following rule in vhost context:

SecRuleUpdateActionById 990012 "allow"

It has no effect and bad robots are still blocked.

Is it a bug or a feature?

**Comment by zimmerle** [comment]
Closing this in favor of #89
