### ISSUE TITLE
nginx: intentionally removed response headers are added back in

### ISSUE THREAD

**Issue by eyz** [SpiderLabs/ModSecurity#853]
This is regarding the nginx version of ModSecurity 2.9.0

I am removing headers such as "Server" and "X-Powered-By" in an ngx lua script within the "server" block.

When I have ModSecurity enabled in the context of the "server" block, the removed headers are added back in, but with empty values. Such as -

Server: [EMPTY]
X-Powered-By: [EMPTY]
^ field values are blank, but fields are added back in

However, when I enable ModSecurity in the "location" block context, the headers are left removed as intended -- not added back in -- working correctly.

I had tried activating ModSecurity in the "server" context to workaround behavior that I've reported in #854, which caused me to find the behavior in this issue.  

nginx version: nginx/1.6.2 (on x86_64)
built by gcc 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) 
TLS SNI support enabled
configure arguments: --with-ld-opt=-Wl,-rpath,/usr/local/lib --with-cc-opt='-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC' --add-module=/root/lua-nginx-module-0.9.16rc1 --add-module=/root/ngx_devel_kit-0.2.19 --add-module=/root/modsecurity-2.9.0/nginx/modsecurity --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_spdy_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-pcre --with-google_perftools_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt=-Wl,-E

I have seen some commits regarding adding response headers back in within the nginx refactoring branch, and wonder if this behavior could be a side effect of anything in those areas.. ?

**Comment by zimmerle** [comment]
Hi @eyz,

Interesting behavior. In fact, that could be a consequence. Did you had a chance to test it before and after those changes? What is your currently version?

**Comment by eyz** [comment]
GitHub had another outage as I was adding that info in -- added in now.

I'm using ModSecurity 2.9.0 (master) at the moment, and it's occurring there. Sorry, I did not mean to imply I am running nginx refactoring at the moment. I could try the current nginx refactoring branch if that would help.

**Comment by zimmerle** [comment]
I am having a hard time to post stuff on GH as well... lets hope it get back to work soon.

Regarding the nginx_refactoring, if you don't mind that is a good opportunity to give it try.

Are you using this nginx server as a proxy?

**Comment by eyz** [comment]
It is not doing proxy_pass at all. 

My default location block checks memcached via try_files, and then sends off to php-fpm -

location / {
    try_files $uri $uri/ @memcached;
}

location ~ \.php$ {
  # typical settings here
}

I will try the refactoring branch later on, and post my results

**Comment by eyz** [comment]
I rebuilt nginx with the current nginx_refactoring, and the behavior is slightly different, but not improved -

Server:
Server:nginx/1.6.2
X-Powered-By:

^ 1) the server header is left empty, but then also duplicated with the original value
2) the X-Powered-By header remains empty still (no change there)

I am reverted back to master for now. Please let me know if I can assist in troubleshooting.

**Comment by eyz** [comment]
This issue does not occur when ModSecurity is enabled in the "location" block, however. I am leaving it activated in the "location" block due issue #855

**Comment by Airis777** [comment]
I have a same problem on the [nginx_refactoring](https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring) branch. But activation at the level of location does not help.

**Comment by zimmerle** [comment]
Hi @Airis777,

Please use the ModSecurity-nginx connector:
http://www.github.com/SpiderLabs/ModSecurity-nginx

**Comment by Airis777** [comment]
Hi @zimmerle,

As a temporary solution, I changed "ngx_http_modsecurity_save_headers_out_visitor.c" for use "copy_handler" like in master branch. It's works for me in conjunction with proxy_pass.

**Comment by zimmerle** [comment]
Hi @Airis777,

Why not the ModSecurity-nginx connector ?

**Comment by Airis777** [comment]
@zimmerle,

As described in ModSecurity-nginx connector, libmodsecurity has not a stable release candidate. Therefore I have some doubts, that current functionality will be reached.

**Comment by theMiddleBlue** [comment]
Same problem for me with the nginx_refactoring. I've solved, as @Airis777 said, by replacing the `ngx_http_modsecurity_save_headers_out_visitor` of the nginx_refactoring branch with the same function of the master branch.

Thanks!

-theMiddle

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master

**Comment by NisariAIT** [comment]
@theMiddleBlue / @zimmerle ,
How did you solve this? 
I have the same issue: I compiled nginx with modsecurity and headers_more_module and stopped getting Server: nginx. But later when I enabled modsecurity in the nginx configuration, the header shows up again in the response. When I disable modsecurity, I see that the header is hidden. 
Could you please enlist the steps to completely stop showing the server header when nginx has modsecurity enabled?

**Comment by zimmerle** [comment]
Hi @NisariAIT,

One option is to use the nginx connector:
https://github.com/SpiderLabs/ModSecurity-nginx

Did you had the opportunity to try it?

**Comment by NisariAIT** [comment]
Thank you so much @zimmerle ! The server header is not displayed when I compiled modsecurity with the nginx connector.
