### ISSUE TITLE
nginx: serial audit log shows HTTP response code as 0 when config'd within "location" block

### ISSUE THREAD

**Issue by eyz** [SpiderLabs/ModSecurity#854]
This is regarding the nginx version of ModSecurity 2.9.0

I've found that when I enable ModSecurity directives within a "location" block, the ModSecurity serial audit log returns 0 for the HTTP response code under most conditions.

I am using the following directives -

  ModSecurityEnabled on;
  ModSecurityConfig modsecurity.conf;
  ^ I can share the modsecurity.conf if that helps

For instance, the first 0 should be a 200 -

 X.Y.X.Y -  [27/Mar/2015:06:03:12 --0700] "GET / HTTP/1.1" 0 0 "-" "-" qXAVAcAkAcAZAvACAcmckcAH "-" /20150327/20150327-0603/20150327-060312-qXAVAcAkAcAZAvACAcmckcAH 0 2196 md5:18fbb37d2553f800c55e97f13193ae44

However, when I move the ModSecurity directives to the "server" block, I get the response codes as expected (the 200 is logged) -

 X.Y.X.Y -  [27/Mar/2015:07:47:48 --0700] "GET / HTTP/1.1" 200 0 "-" "-" AcAcA8AcAcAcAcAcAcrcAVAc "-" /20150327/20150327-0747/20150327-074748-AcAcA8AcAcAcAcAcAcrcAVAc 0 45577 md5:1a9712b4e2de310481ffc0ccb1b6b00d 

nginx version: nginx/1.6.2 (on x86_64)
built by gcc 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) 
TLS SNI support enabled
configure arguments: --with-ld-opt=-Wl,-rpath,/usr/local/lib --with-cc-opt='-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC' --add-module=/root/lua-nginx-module-0.9.16rc1 --add-module=/root/ngx_devel_kit-0.2.19 --add-module=/root/modsecurity-2.9.0/nginx/modsecurity --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_spdy_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-pcre --with-google_perftools_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt=-Wl,-E

Let me know if anyone can benefit from further detail. Thanks

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
