### ISSUE TITLE
/ in SecWebAppId

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/ModSecurity#858]
/ cannot be used inside SecWebAppId parameter (because of the namespace handling?).
This is a strong annoyance when using macros: it is not possible to use the location to proxy as the WebAppId.
Can this be fixed? Even by replacing the / by another character.

**Comment by marcstern** [comment]
Any answer?

**Comment by zimmerle** [comment]
The WebAppId is also used to name the collection file created after it. That is why "/" is not allowed.

**Comment by marcstern** [comment]
could be replaced by an underscore
