### ISSUE TITLE
Application Server Redirects for CRS Fails

### ISSUE THREAD

**Issue by anil4376** [SpiderLabs/ModSecurity#859]
Hi, I have Installed ModSecurity in Apache Server, Here Apache Server Proxying my App Server Requests and Validating the Request Details Using ModSecurity,  
If any Error with Request Data like SQL Injection Issue Or XSS Attack etc , I am redirecting My Request to App Server with Custom Error Code, and I am Generating User Defined Error Response to User.. 
 But Here the Problem is in CRS, we have so Many Rules, and It is pain ful for me to Update Each SecRule by Adding proxy:myAppServerURL to Handle Validation Errors. 

Can you Suggest me any better Design in this Context? I want to Generate My Custom Error in XML Format, i.e. where i go for App Server Call..

**Comment by csanders-git** [comment]
Have you considered placing it in the SecDefaultAction area?

**Comment by anil4376** [comment]
Thanks for the update cansders, Actually I want to Send a different ErrorCodes for Different Types of Errors, Like for SQL Injection Errors I should redirect to https://myAppServerHost:port/Appcontext/ErrorHandler?errorCode=SQLINJ01&User=myUser
here errorCode is based on the Error Type(SQLInjection/XSSAttack). and User is the Header value from my Actual Request.. (It will be gr8 if i know how to append the actula request header values in the Error Request)

As i am new to mod_Sec, I am not sure How this SecDefaultAction can be used here.. Can you please explain a bit more if possible..

**Comment by csanders-git** [comment]
In general this would be better handled by using the mailing list in the future :). But i'll answer here for now. The easiest modifications I can think of would be to enable anomaly mode (https://www.trustwave.com/Resources/SpiderLabs-Blog/Advanced-Topic-of-the-Week--Traditional-vs--Anomaly-Scoring-Detection-Modes/) and then modify the correlation rules (modsecurity_crs_60_correlation.conf in 2.x) to fire separately redirecting to a different location for each type. Keep in mind that doing this will likely (depending on how you do it) break your ability to upgrade CRS seamlessly
