### ISSUE TITLE
'Unknown action: \\' - parser error?

### ISSUE THREAD

**Issue by oleyansen** [SpiderLabs/ModSecurity#860]
Hi

I'm using ruleset with following syntax (<------> is TAB symbol):
SecRule REQUEST_METHOD "@streq POST" \
<------>"id:220460,\
<------>chain,\
<------>msg:' CVE 2014-0793 attack',\
<------>phase:2,\
<------>deny,\
<------>status:403,\
<------>log"
SecRule ARGS_GET:option "@streq com_komento" \
<------>"chain"
SecRule ARGS_POST:website "@rx <"

Now I decide to move to 2.9.0 and suddenly it stop working. Error message is following:
Starting httpd: AH00526: Syntax error on line 48 of /usr/local/waf/rules/27_Apps_WordPress.conf:
Error parsing actions: Unknown action: \\\\

Line 48 contain ordinary Mod Security commands (its phase:2 line):
SecRule REQUEST_FILENAME "@contains /wp-content/plugins/sexy-contact-form/includes/fileupload/files/" \
<------>"id:240020,\
<------>chain,\
<------>msg:' Protecting WordPress Creative Contact Form Files folder',\
<------>phase:2,\
<------>deny,\
<------>status:403,\
<------>t:'none', t:'urlDecodeUni', t:'lowercase', t:'normalisePath'"
SecRule REQUEST_FILENAME "@endsWith .php" \
<------>"t:'none', t:'urlDecodeUni', t:'lowercase'"

On ModSecurity 2.8.0 it works. Here is my system information:
AH00489: Apache/2.4.4 (Unix) OpenSSL/1.0.0-fips PHP/5.4.15 configured
ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/) configured.
ModSecurity: APR compiled version="1.4.6"; loaded version="1.4.6"
ModSecurity: PCRE compiled version="7.8 "; loaded version="7.8 2008-09-05"
ModSecurity: LIBXML compiled version="2.7.6"
ModSecurity: Status engine is currently disabled, enable it by set SecStatusEngine to On.

Please let me know if you need something else.

With best regards, Oleg

**Comment by csanders-git** [comment]
This is actually a known issue.... with Apache. Prior 2.4.11 Apache had issues with line continuations. See here for more details: https://bz.apache.org/bugzilla/show_bug.cgi?id=55910
The solution is an easy one thankfully just add a space before the line continuation and you should be good to go.

**Comment by oleyansen** [comment]
Thanks! It fixed this for me.

**Comment by ossie-git** [comment]
Just to add something.  If you accidentally add a space after the \ at the end of the line, you'll also run into this issue (even on 2.4.18).  The solution is to remove any spaces after the \ at the end of each line
