### ISSUE TITLE
SecRule For ARGS_NAMES and Host

### ISSUE THREAD

**Issue by mailtoyogeshpatel** [SpiderLabs/ModSecurity#861]
I want to allow request arguements "request.ui_dispatch_app and request.ui_dispatch_view" from "test.local.com" From other domain this should not allow and arguements other than these 2 like "request.something" from any domain including "test.local.com" should not allow in modsecurity. How to achieve this ?

**Comment by zimmerle** [comment]
Hi @mailtoyogeshpatel are you using Apache, nginx, IIS, or other options? If it is Apache, depending on the rule you can have it set inside the VirtualHost scope of your Apache configuration.
