### ISSUE TITLE
nginx + modsec not starting with base_rules

### ISSUE THREAD

**Issue by anners** [SpiderLabs/ModSecurity#862]
modsecurity.conf :
include owasp-modsecurity-crs-master/base_rules/*.conf;
include owasp-modsecurity-crs-master/modsecurity_crs_10_setup.conf;

        location / {
                ModSecurityEnabled on;
                ModSecurityConfig /opt/nginx/conf/modsecurity.conf;
                proxy_pass http://localhost:8080;
                proxy_read_timeout 180s;
                }
/opt/nginx/sbin/nginx -V
nginx version: nginx/1.7.9
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
configure arguments: --add-module=../ModSecurity/nginx/modsecurity --prefix=/opt/nginx

Starting nginx: nginx: [emerg] unexpected end of file, expecting ";" or "}" in /opt/nginx/conf/owasp-modsecurity-crs-master/base_rules/modsecurity_crs_21_protocol_anomalies.conf:109

**Comment by csanders-git** [comment]
First you should likely include setup.conf before the rules. Also try downloading the latest rules from git. See if this helps.

**Comment by anners** [comment]
! changed the ordering of the ordering of the includes in modsecurity.conf : 
include owasp-modsecurity-crs-master/modsecurity_crs_10_setup.conf;
include owasp-modsecurity-crs-master/base_rules/*.conf;

and downloaded the latest rules from:
https://github.com/SpiderLabs/owasp-modsecurity-crs/archive/master.zip

but I am still getting:

/sbin/service nginx start
Starting nginx: nginx: [emerg] unexpected end of file, expecting ";" or "}" in /opt/nginx/conf/owasp-modsecurity-crs-master/modsecurity_crs_10_setup.conf:436
                                                           [FAILED]

thanks for your help.

**Comment by zimmerle** [comment]
Hi @anners did you managed to get it working?

**Comment by anners** [comment]
No, I didn't get it working. I am using Apache instead of nginx.

**Comment by bgc8080** [comment]
FYR.

```
# nginx conf
server {
    ModSecurityEnabled on;
    ModSecurityConfig /etc/nginx/modsec_includes.conf;
}
```

```
# /etc/nginx/modsec_includes.conf
include /etc/nginx/owasp-modsecurity-crs/modsecurity.conf
include /etc/nginx/owasp-modsecurity-crs/crs-setup.conf
include /etc/nginx/owasp-modsecurity-crs/rules/*.conf
```

you should NOT include the configuration of modsecurity in nginx.

**Comment by lungati** [comment]
Related to this issue.. I've built nginx v1.15 with Libmodsecurity v3.0 and Modsecurity-nginx connector. When I include the OWASP CRS config files, I get the error below. I've tried changing the order of imports, nothing changes.

How I include the owasp crs:

http {
    include       mime.types;
    include       /usr/local/nginx/conf/owasp-modsecurity-crs/crs-setup.conf;
    include       /usr/local/nginx/conf/owasp-modsecurity-crs/rules/*.conf;

Error:

nginx: [emerg] unexpected end of file, expecting ";" or "}" in /usr/local/nginx/conf/owasp-modsecurity-crs/crs-setup.conf:5

**Comment by alih70442** [comment]
> FYR.
> 
> ```
> # nginx conf
> server {
>     ModSecurityEnabled on;
>     ModSecurityConfig /etc/nginx/modsec_includes.conf;
> }
> ```
> 
> ```
> # /etc/nginx/modsec_includes.conf
> include /etc/nginx/owasp-modsecurity-crs/modsecurity.conf
> include /etc/nginx/owasp-modsecurity-crs/crs-setup.conf
> include /etc/nginx/owasp-modsecurity-crs/rules/*.conf
> ```
> 
> you should NOT include the configuration of modsecurity in nginx.

works for me.
