### ISSUE TITLE
Not able to Append ModSecurity Dynamic Data to RequestHeader

### ISSUE THREAD

**Issue by anil4376** [SpiderLabs/ModSecurity#863]
Hi, I am using ModSecurity as a Validation Service for my Application, I enabled Anamoloy Mode to validate my Request Data, Once the validation is completed i want to inform my Application with Validation Status with ErrorCode. Here ErrorCode is a Custom Error Code and Validation Status is Anamoly Scores. if I have SQLI Score and XSS Score then i want to Add Two Headers X-SQLI and X_XSS with Anamoly Scores. for that i tried like this in my modsecurity_crs_60_corelation.conf file. 

RequestHeader set "SQLi" %%{TX.SQL_INJECTION_SCORE}
RequestHeader set "XSS" %%{TX.XSS_SCORE}

But i can't see the Actual Score in my result. where as i can see same strings i.e
SQLi - %{TX.SQL_INJECTION_SCORE}
XSS -  %{TX.XSS_SCORE}

Can some one Please let me know whether it is a Bug, or am i missing some thing here ?

**Comment by anil4376** [comment]
I tried with below option as well, but i can see null in my Header value,,,

RequestHeader set "SQLi" "%{TX.SQL_INJECTION_SCORE}e"

**Comment by zimmerle** [comment]
Hi @anil4376, 

One thing that you can do to help you during the rules creation process is to enable the SecDebugLog and SecDebugLevel. Those two together can help you a lot, there are more information here:
 - https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDebugLogLevel
 - https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#secdebuglog

You may want to use the setenv to make the ModSecurity variables available to RequestHeader, check here:
 - https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#setenv
