### ISSUE TITLE
nginx1.21 + modsecurity2.90   Centos 5.5 32bit

### ISSUE THREAD

**Issue by baiys** [SpiderLabs/ModSecurity#865]
when i add modsecuriy module with nginx ,i get a error message:/usr/local/src/modsecurity-2.9.0/standalone/../apache2/mod_security2.c:686: undefined reference to `ap_get_server_version',
what should i do,Thanks !

**Comment by zimmerle** [comment]
Hi @baiys, did you managed to get it compiled? do you have the most recent version of apache and apr (dev) installed?
