### ISSUE TITLE
nginx: hostname blank in audit

### ISSUE THREAD

**Issue by uxbod** [SpiderLabs/ModSecurity#866]
NGINX 1.5.11 with ModSec 2.9.0 is showing that the hostname field is empty when writing to error and audit logs.  Seems for some reason that msr->hostname is always blank/NULL in msc_logging.c ?

**Comment by zimmerle** [comment]
Hi @uxbod,

Is your nginx running as a proxy? or end-server?

**Comment by uxbod** [comment]
Hi @zimmerle 

am running NGINX as an end-server.

**Comment by uxbod** [comment]
Hello @zimmerle ... seen anything in the code which could be causing this ? Thanks.

**Comment by mheese** [comment]
I'm running into the same issue. Running nginx-1.8 with ModSecurity 2.9. My nginx is running as a proxy. And the only purpose of it is running ModSecurity.

I can also see that the local_user field seems to be affected.

I'm helping myself at the moment with these 2 sed commands to get stuff remotely logged with mlogc:

```
| sed 's/^/hostname/' | sed 's/  / - /g' | mlogc mlogc.conf
```

**Comment by mheese** [comment]
And I just right now developed a quick patch which is at least helping in getting a correct log output again, although I would like to see that the hostname is there of course.

It turns out that the reference to msr->hostname is not NULL, otherwise "hostname" would be set to "-" anyway. It turns out though, that the hostname variable is 0 length (at least after running through that escaping function). A check afterwards on that and setting it to "-" easily fixes that.

Here is the patch:
```
diff -Naur ModSecurity.orig/apache2/msc_logging.c ModSecurity/apache2/msc_logging.c
--- ModSecurity.orig/apache2/msc_logging.c	2015-06-23 12:21:39.032634781 -0700
+++ ModSecurity/apache2/msc_logging.c	2015-06-23 12:20:50.177755226 -0700
@@ -90,18 +90,22 @@

     /* hostname */
     hostname = (msr->hostname == NULL ? "-" : log_escape_nq(msr->mp, msr->hostname));
+    if (strlen(hostname) == 0) hostname = "-";

     /* remote log name */
     if (msr->remote_user == NULL) remote_user = "-";
     else remote_user = log_escape_nq(msr->mp, msr->remote_user);
+    if (strlen(remote_user) == 0) remote_user = "-";

     /* authenticated user */
     if (msr->local_user == NULL) local_user = "-";
     else local_user = log_escape_nq(msr->mp, msr->local_user);
+    if (strlen(local_user) == 0) local_user = "-";

     /* unique id */
     if (msr->txid == NULL) uniqueid = "-";
     else uniqueid = log_escape(msr->mp, msr->txid);
+    if (strlen(uniqueid) == 0) uniqueid = "-";

     /* referer */
     referer = "-";
@@ -121,6 +125,7 @@

     /* sessionid */
     sessionid = (msr->sessionid == NULL) ? "-" : log_escape(msr->mp, msr->sessionid);
+    if (strlen(sessionid) == 0) sessionid = "-";

     the_request = (msr->request_line == NULL) ? "" : log_escape(msr->mp, msr->request_line);
```

If you want to keep it, I can also make a pull request for that. In general it seems like a good safety check to produce good formatted log output.

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
