### ISSUE TITLE
ModSecurity default config on OpenBSD + Nginx - Error:Abort Trap (Core Dumped)

### ISSUE THREAD

**Issue by singold** [SpiderLabs/ModSecurity#873]
I've installed Nginx + ModSecurity from source on OpenBSD, without problems.

But when I try to configure modsecurity with the default config, upon starting nginx I get: 

"apr_table_copy: t's pool is not an ancestor of p
Abort Trap (Core Dumped)"

AFAICT the problem lies in the modsecurity.conf rules that start with "SecRule", if I comment this lines out nginx starts without problems.

I've also installed the OWASP CRS (only base_rules), and didn't have any problems with the SecRule rules.

Any ideas on what I may be doing wrong?

Thanks in advance

**Comment by zimmerle** [comment]
Are you using the nginx_refactoring branch?

https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

If not, please give it a try and let as know the result.

**Comment by gwurr3** [comment]
having same issue on OpenBSD 5.9 with 1.9.10  and latest nginx_refactoring branch
also with normal 2.9 from https://www.modsecurity.org/tarball/2.9.1/modsecurity-2.9.1.tar.gz

**Comment by zimmerle** [comment]
Hi @gwurr3,

Please try the ModSecurity-nginx connector: https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by asterite3** [comment]
This would happen if APR is compiled with `APR_POOL_DEBUG` (configure option `--enable-pool-debug=yes`).

In this case `apr_table_copy` will make an assetion that memory pool for the new table is a descendant of a pool of original table, which is violated at least here https://github.com/SpiderLabs/ModSecurity/blob/9675653/apache2/re.c#L1250
