### ISSUE TITLE
Implement proper regex parsing in targets

### ISSUE THREAD

**Issue by celesteking** [SpiderLabs/ModSecurity#874]
Okay, so now I hit another bug. So i'm opening a new ticket.

```
SecRuleUpdateTargetByTag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION" "!REQUEST_COOKIES:/^cto\w{4,}/"
```

This doesn't work. Because somehow your config parser thinks I'm willing to supply more args after the comma. You should really fix that. 

``` Error to update target - [}/] is not valid target ```

And of course, PIPE characters are essential part of ANY regex, they should be supported. Make your config parser to split by PIPE, but when PIPE found inside //, skip it.

**Comment by zimmerle** [comment]
Hi @celesteking, 

Thanks for you report. What is your ModSecurity version and platform? We currently use the Apache configuration parsers, if escape such characters does not work we probably want to fix that on Apache side.

**Comment by celesteking** [comment]
Escaping doesn't work, actually, nothing works. I wish there could be a workaround.

apache 2.2 latest linux, modsec 2.8.0

**Comment by marcstern** [comment]
Adding sigle quotes should solve the problem:
REQUEST_COOKIES:'/^cto\w{4,}/'

**Comment by zimmerle** [comment]
Hi @celesteking,

Closing the issue based on @marcstern comment.
