### ISSUE TITLE
facebook redirect login with modsecurity

### ISSUE THREAD

**Issue by abunour22** [SpiderLabs/ModSecurity#876]
I've problem with facebook redirect login after install modSecurity 

this what i see in apache log : 

      ModSecurity: Access denied with code 403 (phase 2). Pattern match "([\\\\~\\\\!\\\\@\\\\#\\\\$\\\\%\\\\^\\\\&\\\\*\\\\(\\\\)\\\\-\\\\+\\\\=\\\\{\\\\}\\\\[\\\\]\\\\|\\\\:\\\\;\\"\\\\'\\\\\\xc2\\xb4\\\\\\xe2\\x80\\x99\\\\\\xe2\\x80\\x98\\\\`\\\\<\\\\>].*?){4,}" at ARGS:code. [file "C:/Apache/conf/crs/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "159"] [id "981173"] [rev "2"] [msg "Restricted SQL Character Anomaly Detection Alert - Total # of special characters exceeded"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] 

is there any way to exclude facebook redirects ?! 
redirect link : example.com/?code=FACEBOOK_REDIRECTION_CODE

**Comment by csanders-git** [comment]
Looks like you're using CRS. This really looks like an issue with how SQL special char detection worked in CRS 2.x. This issue has been fixed in the 3.x branch (https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/v3.0.0-dev) take a look. I think you'll find it performs a bit better :)
