### ISSUE TITLE
Mod security installation on windows not successful

### ISSUE THREAD

**Issue by GireeshaRS** [SpiderLabs/ModSecurity#877]
Hi

I installed SP1 as per your recommendations. Not sure where the problem is but cannot get it to work.

This is what I have done so far

1.Installed VC++ 2008, 2010 SP1, 2012 and 2013 64 bit.
2.Downloaded ModSecurityIIS_2.9.0-64b.msi for 64 bit Windows
3.In the installation of the software choose 64 bit option from the feature list after agreeing to licence terms.
4.Completed installation successfully and restarted IIS
5.The files were downloaded to 'Drive:\Program Files\ModSecurity IIS'
6.Located 'modsecurity_iis.conf' under '\Program Files\ModSecurity IIS' path and used this to do the necessary web config entry for the web site as shown in readme.txt
7.Switched on the SecRuleEngine by setting it as 'On' in modsecurity.conf located at the same path as 'modsecurity_iis.conf' file.
8.Performed IIS reset.
9.Included a test rule SecRule ARGS "../" "t:normalisePathWin,id:99999,severity:4,msg:'Drive 10.Access'" in the modsecurity.conf file.
11. Attempted to browse the URL of the web site by passing invalid query string as mentioned in point 9.
12. Web site does not throw access denied page

Event logs under application logs 'The description for Event ID 1 from source ModSecurity cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.' This error is logged just after the installation is complete and continues logging it for 4 -5 time there after.

Is there something I am missing or have not done correctly for it to work. I can see that in the temp folder under IIS for application pool, the module being loaded and every time I try to use the web site an entry being made in windows log file. I am sure the module is not the issue, is it the supporting reference files or my configurations that is the problem? Please advice.

Thanks
Gireesha

**Comment by zimmerle** [comment]
Hi @GireeshaRS,

Did you had a chance to look into the IIS Troubleshooting? it is available here: 
https://github.com/SpiderLabs/ModSecurity/wiki/IIS-Troubleshooting

**Comment by GireeshaRS** [comment]
Hi
 I made some progress on the issue by uninstalling all pre-requites and attempting to re install. This time around, it looks the installation went through well. The mod security module seems to have been configured and working. But I have the following two issues

1. The module is loaded for all the websites in my IIS and my application log is full of entries for the websites I do not want the detection. I have made an entry in the config files for the websites that I do not want mod security to be implemented by adding the remove module tag. This has still not helped.

2. The windows logs that are generated for breach of rule does provide description of the error but it still says some files are corrupted. Please see the screen shot attached,

![image](https://cloud.githubusercontent.com/assets/9250485/7513476/50214738-f4ac-11e4-9711-c5baccbff4c5.png)


The web site using mod security filters the response object which is affecting the display and action during page navigation. I see an error as shown in screen shot above which says header is not accepted. I may have to go through the rules config and edit it to let it through, but that is second part of the problem which I am currently working on.

Please could you advice on the above.

Thanks
Gireesha

**Comment by ssh30** [comment]
Did you fix it? if so, can you explain how you did it?

**Comment by dmz006** [comment]
I am also getting the same "source ModSecurity cannot be found" message.  Anyone have any suggestions?

**Comment by zimmerle** [comment]
Hi @dmz006,

This is just an warning. That is actually the ModSecurity letting you know something about a given request. The "windows description" of the event can be ignored. Look at the content...

**Comment by mguinness** [comment]
I know this is an old issue, but for others that want to get rid of the annoying "The description for Event ID 1 from source ModSecurity cannot be found" text, you can run the following command as an administrator.

`eventcreate /ID 1 /L APPLICATION /T INFORMATION  /SO ModSecurity /D "Test entry"`

This creates an event source in the registry at HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Application\ModSecurity.
