### ISSUE TITLE
to deal with %u by urlDecodeUni

### ISSUE THREAD

**Issue by van3day** [SpiderLabs/ModSecurity#878]
if I want to match a payload with %u encoding for IIS env, I need urlDecodeUni. But, this will lead some variables to be decode twice. Server do this for one time, this action do another time, so an %2b will be treated as a space, and we cannot match + anymore. And there is a lot of rules in CRS with t:urlDecodeUni action, they cannot match a '+' !!!!!
So I suggest u to add an independent action for %u decoding.

And my previouse question has no reply, about t:cmdLine, i have no idea about matching ;ifconfig to avoid positive false.

Is there any one can explain these two question?

**Comment by martinhsv** [comment]
Hello @van3day ,

I'm going to go ahead and close this issue due its extreme age.

However, I will make a few comments in case you still care about this.

In general, it is up to rule writers to decide what their needs are for matching in transformations. This can occasionally be a challenge.

It's hard to make specific suggestions without understanding what exactly you are trying to do. However, I'll walk through one scenario that it sounds like may be close to what you are talking about.

With a query argument something like this:
```
parm1=aaa%u00afbbb%2bccc
```

... this will automatically get converted to 'aaa%u00afbbb+ccc' before you use any of ModSecurity's 't:' transformations.

If you want to detect *both* the literal '+' character and %u00af *after* it has been transformed by urlDecodeUni, then you do indeed have a slightly more complicated situation than average.

A couple of options, depending on your needs:
- use a chained rule to test for for the literal '+' in the first rule without the t:urlDecodeUni, then test for the post-transform %u content in a subsequent rule (perhaps combined with also checking for the space character)
- use REQUEST_URI_RAW as your target; in this case the '%2b' will not have been automatically converted to literal '+', and then you can use a single t:urlDecodeUni to both convert '%2b' to '+' and to transform '%u00af'
