### ISSUE TITLE
Configure: error: couldn't find APXS [nginx]

### ISSUE THREAD

**Issue by JingoBD** [SpiderLabs/ModSecurity#880]
When i am trying to install mod_security on nginx server it was saying 

"checking if libcurl is linked with gnutls... no
configure: using curl v7.35.0
configure: looking for Apache module support via DSO through APXS
configure: error: couldn't find APXS" 

I don't know why they are looking for Apache module in nginx server. -_-

**Comment by zimmerle** [comment]
Hi @JingoBD unfortunately the nginx version is a wrapper on the top of Apache. It demands some Apache pieces during the compilation time and APR during the run time. See #661 for further details.
