### ISSUE TITLE
How to capture and analys request POST 

### ISSUE THREAD

**Issue by ngocthach** [SpiderLabs/ModSecurity#888]
Hello everyone,

I'm newbie about modsecurity.

I run modsecurity in reserve proxy betwen client and web server
I want to capture and analys request POST before It go to web server.

I trying read code c in mod_security2.c and modsecurity.c  and ... etc... in project on github
and Now I can't find function to do that.

Who can't help me resolve this problem !

tks .

**Comment by csanders-git** [comment]
Not sure what type of analyses you want to do but what you are likley looking for is the SecResponseBodyAccess directive (https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecResponseBodyAccess). Setting this in your configuration should allow you to access data and parameters from POST requests.

**Comment by ngocthach** [comment]
thanks you, but I knows that. I don't know function C/C++ in mod_security2.c can get content of POST request

**Comment by zimmerle** [comment]
Hi @ngocthach, if you want to use ModSecurity to inspect POST requests don't need to change or update anything inside ModSecurity core rather you just need to write the rules (using the SecRules) for it.

What you really want to achieve?

**Comment by ngocthach** [comment]
tks @zimmerle . I want to read and save POST request (include header and body)  into file before this request go to webserver

Can you help me ?

**Comment by zimmerle** [comment]
Hi @ngocthach, well, the variables are available among others as described here:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Variables

You may want to use a Lua or Python script to save it into a file in the fashion that you need:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleScript

Are you sure you need to save a file? That may make your webserver very slow.

**Comment by ngocthach** [comment]
hi @zimmerle, I monitor my webserver in one week, i need auto statistics traffic go through proxy.

Can you help me, some example about #Variables and #SecRuleScript

**Comment by ngocthach** [comment]
hi. I need save content (include payload) POST request into output.txt or database

**Comment by csanders-git** [comment]
No matter what you do this will have major performance impacts but you should consider using LUA in order to push data to a database.

**Comment by ngocthach** [comment]
I want to use "SecRule FULL_REQUEST" to get content POST and  use "SecRuleScript /path/to/script.lua [ACTIONS]" to save it to database.

But i don't know how use it ?  I need example ! thanks

**Comment by zimmerle** [comment]
Hi @ngocthach 

There is an example of a lua script in our manual:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleScript

Also you may be intereset in the auditlogs:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecAuditLog

**Comment by ngocthach** [comment]
hi @zimmerle, thanks you. 
I had read that, i need detail example. If you have it, can you reply me !

I will search and read more ! :D

**Comment by zimmerle** [comment]
Hi @ngocthach,

I am sorry i don't have a more detailed example. As said before i am not sure if this idea is good as it may reduce significantly the performance of your webserver.

**Comment by ngocthach** [comment]
tks @zimmerle , i known. thanks you and @csanders-git  help me.
