### ISSUE TITLE
where can I get the latest help file for compile ModSecurity for iis

### ISSUE THREAD

**Issue by languanghao** [SpiderLabs/ModSecurity#889]
I found the file in path iis\dependencies\howto.txt is not for current version. 

For example, there is no dir named 'winbuild' and also no file named 'buildall.bat'.

**Comment by zimmerle** [comment]
Hi @languanghao,

You can follow the steps of our buildbot:
- http://www.modsecurity.org/developers/buildbot/builders/Win7%20-%20%28VS%202011%2032b%29%20-%20IIS/builds/117

check the steps 2 and 3,
