### ISSUE TITLE
SecRuleUpdate*ById not working inside VirtualHost scope

### ISSUE THREAD

**Issue by derhansen** [SpiderLabs/ModSecurity#89]
The [documentation](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#wiki-SecRuleUpdateTargetById) shows, that SecRuleUpdateTargetById can be used in any scope.

The config for my vhost looks like this:

```
<VirtualHost *:80>
  SecRuleUpdateTargetById 973020 !REQUEST_COOKIES
  ... 
</VirtualHost>
```

As soon as I restart the Apache with the SecRuleUpdateTargetById inside the virtualhost config, Apache refuses to start and claims the following error message

```
Updating target by ID with no ruleset in this context
```

I'm using the latest version of ModSecurity and the OWASP CRS.

Is this a bug, is the documentation wrong or am I missing something?

**Comment by marcstern** [comment]
Any plan to fix this?
Using ctl:removeTargetById is not always possible, especially in a shared environment where you can only add rules after the default ones.
The behavior should be, for any location:
 - remove the rule with specified id
 - create a new version of that rule (same id) with the exception

**Comment by marcstern** [comment]
Seems to be solved in 2.9 - even in a <Location>
Any confirmation that the fix is supposed to be complete?

**Comment by odesk2dot2by** [comment]
Main problem:
 ctl:removeTargetById doesn't know how to work with regex . For instance:

ctl:ruleRemoveTargetByID=981248;ARGS:widget-text[4][text]    - OK
ctl:ruleRemoveTargetByID=981248;ARGS:/^widget/                   -  BAD

**Comment by odesk2dot2by** [comment]
This situation not problem, need trick with chains. However so as ctl action doesn't uses macros, you can make so:

      # For -> ARGS_NAMES:columns[numbers][text][text]
      SecRule REQUEST_URI "@rx ^/admin/path.*" \
                           "id:'1013',phase:1,t:none,log,chain,\
                            msg:'MATCHED_VAR_NAME - %{MATCHED_VAR_NAME}'"
      SecRule ARGS_NAMES  "@rx columns\[[0-9]+\]\[[a-z]+\]\[[a-z]+\]" "ctl:ruleRemoveByID=981173"

If add some small patch and make recompilation of module, then results may be more restrictive. In this case we could make exception for each MACHED_VAR_NAME exactly.

     SecRule ARGS_NAMES  "@rx columns\[[0-9]+\]\[[a-z]+\]\[[a-z]+\]" \
                                            "ctl:ruleRemoveTargetByID=981173;%{MATCHED_VAR_NAME}"

best regards, Andrei
upwork.link

**Comment by syragon** [comment]
> This situation not problem, need trick with chains. However so as ctl action doesn't uses macros, you can make so:
> 
> ```
>   # For -> ARGS_NAMES:columns[numbers][text][text]
>   SecRule REQUEST_URI "@rx ^/admin/path.*" \
>                        "id:'1013',phase:1,t:none,log,chain,\
>                         msg:'MATCHED_VAR_NAME - %{MATCHED_VAR_NAME}'"
>   SecRule ARGS_NAMES  "@rx columns\[[0-9]+\]\[[a-z]+\]\[[a-z]+\]" "ctl:ruleRemoveByID=981173"
> ```
> 
> If add some small patch and make recompilation of module, then results may be more restrictive. In this case we could make exception for each MACHED_VAR_NAME exactly.
> 
> ```
>  SecRule ARGS_NAMES  "@rx columns\[[0-9]+\]\[[a-z]+\]\[[a-z]+\]" \
>                                         "ctl:ruleRemoveTargetByID=981173;%{MATCHED_VAR_NAME}"
> ```
> 
> best regards, Andrei
> upwork.link

This does not work in ModSecurity 2.9 and Apache. Am able to log a %{MATCHED_VAR} and %{MATCHED_VAR_NAME}, so it detects the array fine, but ctl does not appear to be taking %{MATCHED_VAR_NAME} or %{MATCHED_VAR} when it's passed to it. The only solution was moving rules to the global config outside the VirtualHost. Really bad. Not impressed with Modsecurity team, so many open issues and bugs like this for years. It blows my mind that ctl:ruleRemoveTargetById does not simply accept regex in the target name - most websites make use of arrays and other dynamically named REQUEST variables.

**Comment by zimmerle** [comment]
SecRuleUpdate*ById is no longer an issue with version 3.0.

**Comment by henkworks** [comment]
It is great to read that this bug is fixed. At least in theory. Considering that this fix only exists in modsec3 which is a completely different product (quote from the mainpage: »Libmodsecurity is a complete rewrite of the ModSecurity platform« »It is no longer just a module.«) and especially that there is no connector for apache (https://github.com/SpiderLabs/ModSecurity-apache »This project should be considered under development and not production ready. The functionality is not complete and so should not be used. With Apache HTTP Server, the recommended version of ModSecurity is v2.9.x.«), in practice I consider it misleading to mark this bug fixed for most users of modsec.

Please reopen this bug and fix it in modsec2.

(For the future: please consider finding a new name, not just increasing the version number, if you create a new product.)
