### ISSUE TITLE
Modsecurity doesn't work: win server 2012 R2 ,  IIS 8.5

### ISSUE THREAD

**Issue by bmeden** [SpiderLabs/ModSecurity#892]
Hi,
I'm trying to configure Modsecurity to protect our website deployed on IIS 8.5, windows server 2012 R2.

In README instructions says that procedure is: install Modsecurity for windows and then add lines in webconfig (system.webserver section, add module Modsecurity enabled=true configfile="path to modsecurity.conf")
After installation, we added this lines in our website's webconfig but seems it doesnt work.
In EventViewer we see only Information about dlls. 
But, when we remove lines from webconfig, it works! In eventviewer there are logs level "Warning" with description about potential threats (that is sign that Modsecurity works)

I don't understand, do we have to add this lines in particular webconfig or it's enough to install it on computer and Modsecurity is enabled?

Second problem is, if don't add anything in webconfig of our website, (Modsecurity works - we see that because we go to website by writting IP address instead URL) we can't login into website! 
Do you have idea why? In eventviewer we don't see nothing about it.

Please helps us configure out procedure to enable Modsecurity, without having this issues.

Tnx for support, 
Barbara

**Comment by zimmerle** [comment]
Hi @bmeden,

Currently your installer adds the configuration lines by itself. It asks you if you want it do to it during the installation wizard. Given the scenario i guess you have opted for the wizard configuration, so no other change on the configs file are needed.

Looking at your webserver logs you will see that there is an specific rule to avoid access on ip address. That is done to avoid scanner and so on. You can disable that rule using the directive:
```
SecRuleRemoveById <rule id>
```

Check the manual here for further information:
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleRemoveById
