### ISSUE TITLE
ModSecurity interferes with "access_log off" in Nginx in the case of multiple server blocks

### ISSUE THREAD

**Issue by hwdsl2** [SpiderLabs/ModSecurity#893]
Hello,

I am observing a possible bug with ModSecurity (version 2.9.0) and Nginx 1.8.0. 

When there are multiple "server blocks" configured in Nginx.conf, and ModSecurity is enabled in the config, the "access_log off" directives have no effect.

Example configuration:

``` Nginx
user nginx;
worker_processes 1;
events { worker_connections 1024; }
http {
    ModSecurityEnabled on;
    ModSecurityConfig modsecurity.conf;

    server_names_hash_bucket_size 64;
    server {
        listen 80 default_server;
        server_name test1.example.com;
        location / {
            root html;
            access_log off;
        }
    }
    server {
        server_name test2.example.com;
        location / {
            root html;
            access_log off;
        }
    }
}
```

In the configuration above, the "access_log off" directives will have no effect, i.e. access attempts are still logged in the Nginx "access.log". But as soon as I remove the ModSecurityEnabled line and restart Nginx, the "access_log off" directives work as expected.

In addition, if I remove one of the "server" blocks above, and leave only one "server" block in Nginx.conf, then the "access_log off" directives work as expected with ModSecurityEnabled set to on. In conclusion, the problem occurs when ModSecurityEnabled is on and there are multiple server blocks in Nginx.conf.

I enabled Nginx debug logging but unfortunately was not able to find any relevant info.

Thank you for looking into this.

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
