### ISSUE TITLE
Problem with Arabic characters and rule id 960024

### ISSUE THREAD

**Issue by abunour22** [SpiderLabs/ModSecurity#894]
Hi,

Our environment: 
Windows 2012 Server R2 Standard; 
Apache/2.4.12 (Win64) OpenSSL/1.0.1m PHP/5.6.9; 
ModSecurity for Apache/2.8.0; OWASP_CRS/2.2.9

We have Arabic version of website with pages that contains Arabic letters. We don't have any problem with ModSecurity when Post any English letters. Problem exist when Anyone POST comments with Arabic letters.

This Message form Apache Log : 

    Message: Access denied with code 403 (phase 2). Pattern match "\\W{4,}" at ARGS:comment. 
    [file "C:/Apache24/conf/crs/activated_rules/modsecurity_crs_40_generic_attacks.conf"] 
    [line "37"] [id "960024"] [rev "2"] [msg "Meta-Character Anomaly Detection Alert - Repetative Non-Word Characters"] 
    [data "Matched Data: \xd8\xb5\xd8\xa8\xd8\xa7\xd8\xad \xd8\xa7\xd9\x84\xd8\xae\xd9\x8a\xd8\xb1 
    found within ARGS:comment: \xd8\xb5\xd8\xa8\xd8\xa7\xd8\xad \xd8\xa7\xd9\x84\xd8\xae\xd9\x8a\xd8\xb1"] 
    [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"]

We Add these in httpd.conf m but still the same issue !!

    SecUnicodeMapFile crs\unicode.mapping
    SecUnicodeCodePage 1256

Best regards,
shadi

**Comment by csanders-git** [comment]
This seems to be because arabic letters (and Russian) are considered non-word characters. But this is really an issue with CRS. Please see the ticket here... We ask you to please add your bug report to there. CRS 3.0 solves this problem by removing this rule however. Thank you for your report.
