### ISSUE TITLE
finding yajl fails with  2.9.0 on RHEL6

### ISSUE THREAD

**Issue by kurtseifried** [SpiderLabs/ModSecurity#896]
modsecurity-2.9.0 source from main site
Red Hat Linux 6.6 up to date with yajl and yajl-devel 1.0.7-3.el6-x86_64 installed, so the following files are present:

/usr/include/yajl/yajl_common.h
/usr/include/yajl/yajl_gen.h
/usr/include/yajl/yajl_parse.h
/usr/lib64/libyajl.so
/usr/share/doc/yajl-devel-1.0.7
/usr/bin/json_reformat
/usr/bin/json_verify
/usr/lib64/libyajl.so.1
/usr/lib64/libyajl.so.1.0.7

I confirmed that build/find_yajl.m4 is indeed looking for yajl_parse.h, so I set the --with-yajl to /usr/include/yajl/, I even tried manually editing build/find_yajl.m4 to look for it, no dice. 

Do I need to update to yajl 2.x? I tried that, downloaded and built the source in /usr/local/include/yajl/ and fed that to --with-yajl, no luck. 

If needed I can provide a RHEL 6 host for testing this on. Thanks.

**Comment by zimmerle** [comment]
Hi @kurtseifried,

Thanks for the report. yajl version 2 is needed. Please try:

```
--with-yajl /usr/local/include
```

Anyhow, I will investigate this find_yajl.m4

**Comment by kurtseifried** [comment]
using:

--with-yajl /some/path/

results in "configure: error: invalid value of canonical build", it needs the "=" in there. 

Using --with-yajl=/usr/local/include (no trailing slash)

yajl still fails, ditto for /usr/local/include/yajl (also without trailing slash).

**Comment by kurtseifried** [comment]
ping, any progress on this?

**Comment by systeminsightsbuild** [comment]
I have the same problem with 2.9.1 on ubuntu 14.04

**Comment by zimmerle** [comment]
Hi @kurtseifried, did you managed to upgrade to yajl version 2?

**Comment by zimmerle** [comment]
Hi @systeminsightsbuild, I am confused. Do you have yajl version 1 or 2? i came to the impression that you have an Ubuntu 12.04 which comes with yajl v2, is that right?

**Comment by patsevanton** [comment]
Hi @zimmerle 
I added /usr/lib64 to configure script:

Before:
```
case "${with_yajl}" in #(
  no) :
    test_paths= ;; #(
  yes) :
    test_paths="/usr/local/libyajl /usr/local/yajl /usr/local /opt/libyajl /opt/yajl /opt /usr" ;; #(
  *) :
    test_paths="${with_yajl}" ;;
esac
```

After
```
case "${with_yajl}" in #(
  no) :
    test_paths= ;; #(
  yes) :
    test_paths="/usr/local/libyajl /usr/local/yajl /usr/local /opt/libyajl /opt/yajl /opt /usr /usr/lib64" ;; #(
  *) :
    test_paths="${with_yajl}" ;;
esac
```

Log:
```
checking for yajl install... /usr/lib64/ /usr/include
configure: using yajl v2
```

```
 yum list yajl
Installed Packages
yajl.x86_64   1.0.7-3.el6 
```

**Comment by zimmerle** [comment]
The most recent version (v2.9.2) already includes _/usr/lib64_ as a valid path for yajl.
