### ISSUE TITLE
Sending Logs in JSON format

### ISSUE THREAD

**Issue by nginxsantos** [SpiderLabs/ModSecurity#897]
Can someone please point me to the work where the logs can be sent in JSON format when the violation happens. 
Sending the logs in JSON format makes it simple to analyze/parse.

I looked at the following, but the author says it is incomplete. Is there any solution/patch to this?

https://github.com/p0pr0ck5/ModSecurity/tree/json_logging

Thanks...Santos

**Comment by pieterlange** [comment]
Hate to say it, but +1 on this.

Having to parse the current format is an absolute nightmare. And everyone should know that custom parsing/formats ALWAYS come with a higher amount of (security) bugs.

@nginxsantos you could consider parsing your logs with logstash and https://github.com/bitsofinfo/logstash-modsecurity. logstash can create the necessary output formats/locations for you (including JSON). But make sure to use logstash 1.4.2, the newly released 1.5.1 broke the before-mentioned parser. Which is why i'm here again.. googling how to parse this impossible format.

**Comment by zimmerle** [comment]
Guys, you may want to check this:

https://github.com/SpiderLabs/modsecurity-mlogc-ng

**Comment by pieterlange** [comment]
For anyone wondering if you should invest time into exploring that option: not right now.

**Comment by zimmerle** [comment]
This is related to issue #656

**Comment by zimmerle** [comment]
Hi,

Do you guys have any feedback on the format presented here: 
https://gist.github.com/zimmerle/b22660ab33bd6df444fd

Missing something?

**Comment by pieterlange** [comment]
Hi,

that looks very usable!

Not sure if i'm a fan of spaces in the JSON keys though. But they look like typo's (there are a few others, i'm not going to nitpick about that)

FWIW/anyone googling: as i was using modsec purely for audit logging i'm going to replace the logging part with packetbeat as it serves my needs just fine..

**Comment by nginxsantos** [comment]
Hi @zimmerle - The format suggested by you @ https://gist.github.com/zimmerle/b22660ab33bd6df444fd looks good.

But, I am wondering how to generate in that format.
Can https://github.com/SpiderLabs/modsecurity-mlogc-ng generate in that format or you have developed something else.

Thanks....

**Comment by zimmerle** [comment]
Hi @nginxsantos,

"modsecurity-mlogc-ng" will be upgraded to support that format, also we are working on this libmodsecurity (ModSecurity without Apache dependency -- for nginx, IIS and other bindings) so I was thinking about having the JSON format as the default option.

More information about libmodsecurity: https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/

**Comment by nginxsantos** [comment]
Hi @zimmerle ,

Thank you libmodsecurity is a good idea. If you are planning the JSON default logging format there, then it will be good.

Please update it here once done for the benefit of the others.

Many thanks....

**Comment by SECURITI** [comment]
Definitely a necessity with the big upswing of MongoDB usage, so people can
easily log straight to their database.

On Tue, Jul 7, 2015 at 2:53 AM, nginxsantos <notifications@github.com>
wrote:

> Hi @zimmerle <https://github.com/zimmerle> ,
>
> Thank you libmodsecurity is a good idea. If you are planning the JSON
> default logging format there, then it will be good.
>
> Please update it here once done for the benefit of the others.
>
> Many thanks....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpiderLabs/ModSecurity/issues/897#issuecomment-119092296>
> .
>



-- 

*_________________________*

*John Martinelli*
*Digital Security & Internet Marketing Consultant*

*Office Landline (feel free to call 24/7)  *  +1 (317) SECUR-17
*Direct Cell (M-F, 9-5 EST) * +1 (412) 888-6090

**Comment by p0pr0ck5** [comment]
I ended up completely refactoring the idea for presenting audit logs as JSON here: https://github.com/p0pr0ck5/ModSecurity/tree/json_audit_logging

This uses yajl and is a much cleaner approach, in that it doesn't stomp on message generation function signatures.

**Comment by nginxsantos** [comment]
HI @p0pr0ck5 ,

Thanks. Would you please put an example here.

**Comment by nginxsantos** [comment]
Thanks...Let me take a look.

**Comment by p0pr0ck5** [comment]
Just a heads up, I updated my branch (and the associated pull request) to no longer rely on a compile-time option. Instead, we define a new config directive, `SecAuditLogFormat`, to be defined as either 'JSON' or 'Native' (default is native).

**Comment by nginxsantos** [comment]
Hi @p0pr0ck5 ,
How is your branch differ from the main ModSecurity repo, I mean what are the changes you have done apart from JSON log format?

**Comment by p0pr0ck5** [comment]
@nginxsantos my branch is called 'json_audit_logging' (https://github.com/p0pr0ck5/ModSecurity/tree/json_audit_logging), whereas the the upstream branch to which I believe you're referring is just called' 'json_logging'. As for differences between the two, the upstream branch only logs a few small items as JSON, whereas my branch replaces the entire audit log entry with a JSON structure.

**Comment by leprechaun** [comment]
:+1:

There'd be tremendous value in parsing the current log format, but it's scarier than it should be. JSON solves the problem.

**Comment by nginxsantos** [comment]
Hi @p0pr0ck5 - Thank you. I am still evaluating. Your branch (p0pr0ck5/ModSecurity) is off SpiderLabs/ModSecurity and I am really concerned about the delta of the changes. As I requested earlier, were there  any other  changes you have done apart from JSON log format?

**Comment by p0pr0ck5** [comment]
@nginxsantos sorry for the delayed response, I've been on vacation. FTR, 'p0pr0ck5/ModSecurity' and 'SpiderLabs/ModSecurity' are projects, not branches. The branch I'm referencing in this thread, https://github.com/p0pr0ck5/ModSecurity/tree/json_audit_logging, is 5 commits ahead of the SpiderLabs:master branch; all 5 of those commits are related exclusively to JSON audit logging.

Can you please clarify your concern a little more? What _specific_ parts of the delta concern you?

**Comment by nginxsantos** [comment]
Hi @p0pr0ck5  , Thank you for the reply. I have been using SpiderLabs/ModSecurity . So , I was looking for the changes/patch for the JSON log format only. 

Looks like if I patch the following diff to "SpiderLabs/ModSecurity", I can get the JSON logging working. Can you please confirm.
https://github.com/SpiderLabs/ModSecurity/compare/master...p0pr0ck5:json_audit_logging

Thank you once again for the great work, it helps.

**Comment by p0pr0ck5** [comment]
Why don't you just clone my branch? Seems a lot simpler than trying to apply patches. Just clone the branch and run through the build process as your normally would.

yajl_gen.h is provided by the YAJL C library; existing code within ModSecurity references this library (i.e. in msc_json.h there is '#include <yajl/yajl_parse.h>'), so you don't need to install any additional libraries to build this. As long as you have the YAJL library (which you need to build ModSecurity without the patch anyway), you should be able to build without a problem.

I think you're making this more complicated than you need to  ;)

**Comment by zimmerle** [comment]
Hi @nginxsantos, not sure why you want to do this, but you can generate the patches using:

````
git --format-patch
```

After the patch generation you can apply in our tree using: 

```
git am /path/to/path
```

That is what I do to merge the code into mainline.

**Comment by zimmerle** [comment]
Pull request #914 was merged. It will be available as part of ModSecurity version 2.9.1

**Comment by umarfarook882** [comment]
Nice Finally Mod security support JSON log format and it is working good.
I have been working  on to setup realtime analytic over modsecurity audit log(json) with ELK Stack (Elasticsearch, Logstash, Kibana). so if any one working on that  please let me know?

**Comment by zimmerle** [comment]
Hi @umarfarook882 one of the transport available is the HTTPS transport. It was built as a demo, but you may want to give it a try. Depending on the amount of request that you have, it may be suitable.

Instead of using Serial or Parallel in the auditlog type, specify https. Use the URL of your endpoint instead of the path to a file.
