### ISSUE TITLE
modsecurity auto remove user defined  http headers

### ISSUE THREAD

**Issue by lanzsec** [SpiderLabs/ModSecurity#898]
for example:  i set 2 headers。 
header('X-Powered-By: PHPxxxxx/5.3.3');
header('A-Powered-By: PHPxxxxx/5.3.3');

but only found  " X-Powered-By: PHPxxxxx/5.3.3"  in response headers。
A-Powered-By being deleted by modsecurity without any logs.

**Comment by csanders-git** [comment]
What ruleset are you using? Can you try disabling all rules and trying again?

**Comment by lanzsec** [comment]
of cause I  disabed all rules;  even  'echo "" > modsecurity.conf'  to make sure there is no rules at all。
problem still  exits 。
only remove  modsecurity in  nginx.conf then  become normal
       " # ModSecurityEnabled on;  
         # ModSecurityConfig modsecurity.conf;"

**Comment by zimmerle** [comment]
Hi @lanzsec,

Please use the nginx_refactoring branch:

https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring
