### ISSUE TITLE
ModSec rejects requests larger SecRequestBodyLimit when SecRequestBodyLimitAction is set to ProcessPartial 

### ISSUE THREAD

**Issue by kbernas** [SpiderLabs/ModSecurity#899]
hi,
it is related to https://github.com/SpiderLabs/ModSecurity/issues/589

 we created a Custom Rule to validate the Request Size.

SecRule FULL_REQUEST_LENGTH "@gt 2097152" \
"phase:2,rev:'2',ver:'OWASP_CRS/2.2.9',maturity:'9',accuracy:'8',capture,multiMatch,t:none,t:urlDecodeUni,t:replaceComments,ctl:auditLogParts=+E,block,msg:'REQ BODY More than 2MB: Body size Detected.',id:'950999',logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',severity:'2',tag:'OWASP_CRS/WEB_ATTACK/REQ_BODY_SIZE ',tag:'WASCTC/WASC-19',tag:'OWASP_TOP_10/A1',tag:'OWASP_AppSensor/CIE1',tag:'PCI/6.5.2',setvar:'tx.msg=%{rule.msg}',setvar:tx.file_size_score=+%{tx.critical_anomaly_score},setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/REQ_BODY_SIZE-%{matched_var_name}=%{matched_var_name}"

 but unfortunately We are seeing Request Entity To Large Error for more than 1 MB Request , so later we added 

SecRequestBodyNoFilesLimit 4097152.

Now I am not seeing Request Entity To Large Error, but my Rule is not picking for more than 2 MB Request Body..

**Comment by hellointeractiv** [comment]
same problem...

**Comment by zimmerle** [comment]
Hi @kbernas and @hellointeractiv 

Can you increase your SecDebugLogLevel and check the value of the FULL_REQUEST_LENGTH variable?

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDebugLogLevel

**Comment by zimmerle** [comment]
@kbernas, @hellointeractiv did you checked the logs? did you managed to get it working?

**Comment by victorhora** [comment]
Please give it a try with release [2.9.2](https://github.com/SpiderLabs/ModSecurity/releases/tag/v2.9.2).

Closing this one because of lack of feedback from reporters. If the problem persists let us know.
