### ISSUE TITLE
How to optimize the performance of modsecurity?

### ISSUE THREAD

**Issue by zhangyc0816** [SpiderLabs/ModSecurity#901]
Hello :
I am here Environment nginx + modseurity2.9
After loading rules, site opens speed greatly affected, but the impact is very slow to refresh the site.
Ask the next. How to optimize the performance of modsecurity.
Thank you

**Comment by quantumpacket** [comment]
https://github.com/SpiderLabs/ModSecurity/wiki/ModSecurity-Frequently-Asked-Questions-%28FAQ%29#will-using-a-large-amount-of-negative-filtering-rules-impact-performance
