### ISSUE TITLE
libmodsecurity branch compile fails with Fedora 22 / GCC 5.1.1

### ISSUE THREAD

**Issue by LinuxJedi** [SpiderLabs/ModSecurity#905]
```
g++ -DHAVE_CONFIG_H -I. -I../src  -std=c++11 -Icommon -O0 -g -I../headers -DWITH_YAJL    -g -O2 -MT regression/regression_tests-custom_debug_log.o -MD -MP -MF regression/.deps/regression_tests-custom_debug_log.Tpo -c -o regression/regression_tests-custom_debug_log.o `test -f 'regression/custom_debug_log.cc' || echo './'`regression/custom_debug_log.cc
regression/custom_debug_log.cc: In member function ‘bool modsecurity_test::CustomDebugLog::contains(const string&)’:
regression/custom_debug_log.cc:40:53: error: use of deleted function ‘bool std::regex_search(const std::basic_string<_Ch_type, _Ch_traits, _Ch_alloc>&&, std::match_results<typename std::basic_string<_Ch_type, _Ch_traits, _Ch_alloc>::const_iterator, _Alloc>&, const std::basic_regex<_Ch_type, _Rx_traits>&, std::regex_constants::match_flag_type) [with _Ch_traits = std::char_traits<char>; _Ch_alloc = std::allocator<char>; _Alloc = std::allocator<std::sub_match<__gnu_cxx::__normal_iterator<const char*, std::basic_string<char> > > >; _Ch_type = char; _Rx_traits = std::regex_traits<char>; typename std::basic_string<_Ch_type, _Ch_traits, _Ch_alloc>::const_iterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >]’
     return (std::regex_search(m_log.str(), match, re) && match.size() >= 1);
                                                     ^
In file included from /usr/include/c++/5.1.1/regex:61:0,
                 from regression/custom_debug_log.cc:20:
/usr/include/c++/5.1.1/bits/regex.h:2263:5: note: declared here
     regex_search(const basic_string<_Ch_type, _Ch_traits, _Ch_alloc>&&,
     ^
Makefile:623: recipe for target 'regression/regression_tests-custom_debug_log.o' failed
make[2]: *** [regression/regression_tests-custom_debug_log.o] Error 1
make[2]: Leaving directory '/home/linuxjedi/Programming/Git/ModSecurity/test'
Makefile:677: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/linuxjedi/Programming/Git/ModSecurity/test'
Makefile:452: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by csanders-git** [comment]
This is a known issue with how c++14 handles  regex_search(). For now to get it to compile you may just comment out that value and return True. We will fix this particular issue in future version. After removing this offending line it should compile fine.

**Comment by zimmerle** [comment]
Hi @LinuxJedi,

Nice that you are interested in libmodsecurity. As you may have noticed, "libmodsecurity" is under development, actually it is in the initial development stages.

What is your Linux distribution? Any particular interest on libmodsecurity?

**Comment by LinuxJedi** [comment]
Hi Felipe,

> On 3 Jul 2015, at 20:35, Felipe Zimmerle <notifications@github.com> wrote:
> 
> Hi @LinuxJedi,
> 
> Nice that you are interested in libmodsecurity. As you may have noticed, "libmodsecurity" is under development, actually it is in the initial development stages.

Cool, thanks for letting me know.

> What is your Linux distribution? Any particular interest on libmodsecurity?

My distribution is Fedora 22. And my interest is I'm the Senior Developer Advocate for Nginx. It is my job to work with you guys to make Mod Security work well with Nginx :)

Kind Regards
--
Andrew Hutchings - LinuxJedi - http://www.linuxjedi.co.uk/

**Comment by zimmerle** [comment]
Hi @LinuxJedi :)

Feel free to test and send us feedback and bug reports :)

You probably saw the ModSecurity-nginx project already, but, just to keep a note in this issue:
https://www.github.com/SpiderLabs/ModSecurity-nginx

**Comment by LinuxJedi** [comment]
Hi,

> On 3 Jul 2015, at 20:45, Felipe Zimmerle <notifications@github.com> wrote:
> 
> Hi @LinuxJedi :)
> 
> Feel free to test and send us feedback and bug reports :)

I certainly will, and I may send patches your way too (depending on time constraints, etc...).

> You probably saw the ModSecurity-nginx project already, but, just to keep a note in this issue:
> https://www.github.com/SpiderLabs/ModSecurity-nginx

Absolutely. That is what I intended to play with. But the README states it requires libmodsecurity and hence the wall I hit on my main dev machine. If there is another source for this I should use please let me know. Otherwise I'll dive into an Ubuntu VM.

Kind Regards
--
Andrew Hutchings - LinuxJedi - http://www.linuxjedi.co.uk/

**Comment by zimmerle** [comment]
This particular error is happening on the regression test utility. It is safe to comment this line as @csanders-git suggested. 

Regression utility may not work as expected, but the patch is coming soon.

**Comment by LinuxJedi** [comment]
Excellent, many thanks to both of you for jumping on this so quickly :)

**Comment by csanders-git** [comment]
I pushed a fix for the issue that solves the problem. It appears that c++ 5.x > doesn't like stringstream with conversions to c++ strings sent as input to the first argument of regex_search(). This is extremely odd behavior. Explicitly casting the stringstream to a string before hand i.e std::string s = stringstream.str(); and then passing s as the first parameter of regex_search, seems to solve the issue.
