### ISSUE TITLE
[libmodsecurity] Bison version requirement to high on RHEL 7

### ISSUE THREAD

**Issue by rodehoed** [SpiderLabs/ModSecurity#907]
Trying to create a RPM for libmodsecurity. But it fails buidling because RHEL 7 comes with Bison 2.7 and  libmodsecurity requires Bison 3.0.2:

```
/bin/sh ../ylwrap parser/seclang-parser.yy y.tab.c parser/seclang-parser.cc y.tab.h `echo   parser/seclang-parser.cc | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output parser/seclang-parser.output -- bison -y  
/builddir/build/BUILD/ModSecurity-libmodsecurity/src/parser/seclang-parser.yy:2.10-16: error: require bison 3.0.2, but have 2.7
make[2]: *** [parser/seclang-parser.cc] Error 63
```

Is this version really required for building? Requiring version 3.02 will rule out a lot of (enterprise) LTS systems.

**Comment by zimmerle** [comment]
Hi @rodehoed, thanks for your interest in libmodsecurity. I think it should be workable with Bison 2.7. I will investigate.

As a side note keep in mind that this is just the start of this libmodsecurity, i don't think it is a good idea to place it under production yet.

**Comment by rodehoed** [comment]
Sure I know, but I would like to have a SPEC file ready and do some testing internally :+1:  

Let me know if I need to test stuff on RHEL 7.

**Comment by autrejacoupa** [comment]
@zimmerle On CentOS 6.7 which by default has bison 2.4.1 rpms.

**Comment by zimmerle** [comment]
Hi @autrejacoupa, what is the version of your gcc?

**Comment by autrejacoupa** [comment]
@zimmerle $ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

**Comment by csanders-git** [comment]
The compilation works fine on Fedora 22:
gcc 5.1.1 20150618 (red hat 5.1.1-4)
bison 3.0.2
lex 2.5.37

**Comment by zimmerle** [comment]
Compilation no longer demands the generation of the parser. It already came with the standard version. Generate the parser is only needed for those who wants to change the parser.
