### ISSUE TITLE
css  and js file unable to access

### ISSUE THREAD

**Issue by yaschiro** [SpiderLabs/ModSecurity#909]
All reference file(css,js..) under this site cannot be accessed(http://syk.testin.com/homeimg/ad001.png net::ERR_EMPTY_RESPONSE), 
only the reference of other sites can be accessed.(http://abc.com/base.css is ok!)

**Comment by yaschiro** [comment]
nginx+modsecurity2.9 
 location / {
		ModSecurityEnabled on;  
		ModSecurityConfig modsecurity.conf;
        proxy_pass http://syk.testin.com;
		proxy_redirect default;

        }

**Comment by zimmerle** [comment]
Please use the nginx_refactoring branch:

https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

**Comment by yaschiro** [comment]
Thank you very much, problem solved
