### ISSUE TITLE
ModSecurity 2.9 on IIS 7

### ISSUE THREAD

**Issue by tetreaultcrt** [SpiderLabs/ModSecurity#910]
I've installed ModSecurity on Windows Server 2008 R2 Enterprise but it does not seem to be working.

I installed the prerequisite Visual C++ Redistributable for Visual Studio 2013.
I ran the installer in verbose mode and did not see any major issues.
I set the engine on with a basic rule to test the protection.
I updated the web configs of my applications to enable ModSecurity.
I turned on the debug log to level 9 yet no logs are being written.

The only messages I see in the Event Viewer are

The description for Event ID 1 from source ModSecurity cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

ModSecurity for IIS (STABLE)/2.9.0 (http://www.modsecurity.org/) configured.

There are a total of 6 of these messages, the above and one each for APR, PCRE, LUA, YAJL and LIBXML.

Any help on this issue would be greatly appreciated!

Thanks

**Comment by csanders-git** [comment]
What is the rule that you have configured.

**Comment by tetreaultcrt** [comment]
Hi thanks for getting back to me,

Some important config options I have set up...

SecRuleEngine On
#default action on rule match
SecDefaultAction "phase:1,deny,status:403,log"

SecDebugLog C:\Program Files\ModSecurity IIS\logs\modsec_debug.log
SecDebugLogLevel 9

SecRequestBodyAccess On

SecRule ARGS "\.\./" "t:normalisePathWin,id:99999,severity:4,msg:'Drive Access'"


the above rule I found was from https://www.apachelounge.com/viewtopic.php?t=2520 which supposedly will block a request of type http://www.xxxx.com/?abc=../../

I assumed that those messages from my original post indicated some sort of issue with the install, is that not the case?

**Comment by csanders-git** [comment]
Try something a bit more simple. like

SecRule ARGS:test "@contains test" "id:5,block,deny,status:403"

Then you can use:
http://localhost/?test=test

You should get a 403 forbidden.

**Comment by tetreaultcrt** [comment]
k I just gave that one a try, unfortunately it reaches the site successfully, as well as not providing any messages in the Event Viewer.

Is there any other information I could provide which might be helpful?

Thanks

**Comment by straav** [comment]
I'll second this problem.  Spent some time grappling with this exact issue.  IIS shows it as an active model, tracing the process shows a file open of the config file.

**Comment by zimmerle** [comment]
Hi @tetreaultcrt,

Is there any log message that indicates ModSecurity initialization?

**Comment by tetreaultcrt** [comment]
Hi @zimmerle 

Unfortunately the only log messages I'm seeing are the ones I mentioned in my original post. Do you have any idea what might be causing that message? or causing that to be the only message?

Thanks

**Comment by dahanmeir** [comment]
Did you manage to make it work? Im having the same issuses

**Comment by dmz006** [comment]
I made the reference to those other tickets because they all mention the "source ModSecurity cannot be found" which I'm still working through myself.

**Comment by ghost-atl** [comment]
Has anyone solved this issue, I don't understand why it keeps getting closed in every thread I've seen a similar issue with no resolution, yet the case gets closed!?

**Comment by victorhora** [comment]
Hey @tetreaultcrt, @dmz006 and @ghost-atl the "source ModSecurity cannot be found" message are just warnings that the Event registered by ModSecurity was not defined according to [strict Microsoft event handling](https://msdn.microsoft.com/en-us/library/aa363680.aspx). You should be able to safely ignore it for now.

If you haven't done so, I suggest giving it a go with the [latest version](https://github.com/SpiderLabs/ModSecurity/releases/download/v2.9.1/ModSecurityIIS_2.9.1-64b.msi).

If you look a bit further down on to "The following information was included with event:" you can see the actual ModSecurity log. Alternatively you can also see the plain log by switching to the "Details" tab of the Event like so:

![image](https://cloud.githubusercontent.com/assets/15767386/25757756/d040ea14-3199-11e7-8d86-36c86658ce77.png)

On these log events, If you see the something in these lines (versions may vary of course):

ModSecurity for IIS (STABLE)/2.9.1 (http://www.modsecurity.org/) configured. 
ModSecurity: LUA compiled version="Lua 5.1
ModSecurity: YAJL compiled version="2.0.1"
ModSecurity: LIBXML compiled version="2.9.1"
ModSecurity: APR compiled version="1.4.8"; loaded version="1.4.8"
ModSecurity: PCRE compiled version="8.33 "; loaded version="8.33 2013-05-28"
ModSecurity: StatusEngine call: "2.9.1,IIS,1.4.8/1.4.8,8.33/8.33 2013-05-28,Lua 5.1,2.9.1"

It means its all good and ModSecurity should be correctly installed and enabled.

As CRS is already configured by default you can give it a quick test by just firing the following on your browser: http://localhost/?a=><script>alert(1)</script> and you should get some warnings similar to the one in the screenshot above.

You can also test that the request is being properly blocked with a 403 by changing SecRuleEngine to "On" on the C:\Program Files\ModSecurity IIS\modsecurity.conf file.

**Comment by victorhora** [comment]
Closing this one. If problem still persists feel free to reopen.
