### ISSUE TITLE
2.9 SecUploadKeepFiles

### ISSUE THREAD

**Issue by MichaelHaas** [SpiderLabs/ModSecurity#912]
Hello,

In 2.9 when SecUploadKeepFiles is Off the inspectfile is not working anymore. With Relevantonly and "on" its working.
In 2.7 and 2.8 it was also working with Off.
Is this an intended change or a bug?

Thanks in Advance

**Comment by csanders-git** [comment]
Be advised that this change has been previously noted in the reference manual: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#inspectFile

**Comment by MichaelHaas** [comment]
ok, thank you.
Didn't see it, was only looking in then CHANGES file.
