### ISSUE TITLE
apt-get ubuntu 14.4

### ISSUE THREAD

**Issue by marknfischer** [SpiderLabs/ModSecurity#913]
The ubuntu trusty repository is stuck at 2.7, and we need 2.9.  Is there a modsecurity repository I missed for apt-get libapache2-mod-security that is 2.8 or 2.9?  Would Trustwave consider hosting such a thing?  It would really make a difference for staying current.

**Comment by zimmerle** [comment]
Hi @marknfischer,

The packages are maintained by the community. Looking at Ubuntu repositories the maintainer for the package seems to be "Alberto Gonzalez Iniesta". - http://packages.ubuntu.com/trusty/httpd/libapache2-modsecurity

However, you can always built it from source.
