### ISSUE TITLE
mod_security DoS and Brute Force rules barely usable, IP collection is very slow, ip.pag grows enormously

### ISSUE THREAD

**Issue by georgipetrovtph** [SpiderLabs/ModSecurity#915]
We are trying to implement the rules for brute force attacks and DoS attacks that are available in the core rule set under the experimental folder:

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/experimental_rules/modsecurity_crs_11_brute_force.conf

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/experimental_rules/modsecurity_crs_11_dos_protection.conf

Unfortunately we ran into series of issues that make these rules barely usable. First issue, when we enable these rules (and turn off the mod_evasive), is that these rules cause huge CPU spike usage on the Apache's processes. We have spikes of like 500 processes taking up all the CPU for like 5 seconds, some times more. Then the load goes back to normal. This turns out to happen when there is a DoS attack (somebody sending a lot of requests that should be blocked by the rule). Further investigation showed that the attacking IP is indeed blocked, but the search through the IP collection (which is used for keeping track of the IPs) is extremely slow in these situations.

Issue 1: It looks like the search/update of the IP collection is very slow. The more hits and the more IPs it becomes so slow it eventually takes all the CPU.

We tried to tune the parameters and we only reduced the load a bit by putting high limits (so few IPs are tested and blocked) and very low burst time (like 1 or 2 seconds), so the reads/updates on the collection are less.

We kept researching and we ran into another, connected problem: The ip.pag file which is used for storing the IP collection data grows to 5-6 Gigabytes. No wonder why the search/update operations are so slow. We reduced then the SecCollectionTimeout to 300 seconds and this reduced the file size to 2GB. This also reduced a bit the load (as the file is smaller now) but didn't solve the problem, as both the file and the load are still too high.

Issue 2: The ip.pag file (the collection itself) grows very big, probably causing the slow search/update. After delete, goes back to normal. Looks like record stay there and never get flushed.

In result of all that we had to abandon these rules and turn back to mod_evasive (which works extremely fast in the same environment/load).

We tried with the latest version of mod_security from the GIT hub - no change.

Our questions:

1. Do you recognize this problem? In my opinion or the collection is unnecessary big, does not cleanup properly or the search/update algorithm is extremely ineffective.
2. Is there a fix/patch/workaround?

Thanks!

**Comment by csanders-git** [comment]
We do recognize the problem. At this point under heavy loud it might be best to use mod_evasive. The issue tends to deal with how internal collections are stored. We are certainly looking into solutions for this problem actively. In future versions we will likely include other mechanisms that allow for the usage (and sharing) of data via 3rd party datastores like redis and memcache. In fact, there is already a memcache build (https://github.com/SpiderLabs/ModSecurity/tree/memcache_collections). We are also looking into other more advanced techniques like using built in Net_Filter rules in *nix to prevent such overhead.
