### ISSUE TITLE
Error message issued when "SecRequestBodyLimitAction ProcessPartial" parameter set

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/ModSecurity#918]
When the parameter "SecRequestBodyLimitAction ProcessPartial" is set an error message "Partial results are valid but processing is incomplete" is issued in the error log whenever a request body was encountered that was longer than the configured Request Body Limit. While the message in itself may have some justification it is not correct to flag this message as an error. It is not an error. It should be an informational message, at most. ModSecurity does exactly what it was configured to do and an operation that acts within the configured realm should never be an error.

**Comment by xformerfhs** [comment]
I forgot to mention the modSecurity version: ModSecurity for Apache/2.8.0 running on Linux

**Comment by xformerfhs** [comment]
Relevant configuration parameters are as follows:

SecRuleEngine On
SecRequestBodyAccess On
SecRequestBodyLimitAction ProcessPartial
SecRequestBodyInMemoryLimit 131072
SecRequestBodyLimit 131072

**Comment by xformerfhs** [comment]
And this is the error message:

apache error log:[Wed Jul 29 08:40:22.576897 2015] [:error] [pid 1234:tid 12345678] [client nn.nn.nn.nn] ModSecurity: Error reading request body: Partial results are valid but processing is incomplete [hostname "somehost.domain.com"] [uri "/some/uri"] [unique_id "Whatever"]

The problem is the "[:error]" in this messge and the wording "Error reading request body". This is not an error when ModSecurity was instructed not to read the entire request body via the "SecRequestBodyLimitAction ProcessPartial" parameter.

**Comment by tomsommer** [comment]
See this too

**Comment by zimmerle** [comment]
Hi @xformerfhs please check out a newest version of ModSecurity. Version 2.9.2 was released recently. I think this specific issue was fixed in 2.9.0.

**Comment by edgreenberg** [comment]
>>> Hi @xformerfhs please check out a newest version of ModSecurity. Version 2.9.2 was released recently. I think this specific issue was fixed in 2.9.0.<<<

Hi Zimmerle,  I have this in 2.9.1.
