### ISSUE TITLE
getting permission denied in ModSecurity error_log

### ISSUE THREAD

**Issue by pkhadka56** [SpiderLabs/ModSecurity#919]
I have installed modsecurity OWASP rules in my **CENTOS 6.6 WHM 11.50.0 (build 29)** and getting following errors in /usr/local/apache/logs/error_log. These are separate three errors I am getting.

```
ModSecurity: collection_store: Failed to access DBM file "/var/cpanel/secdatadir/ip": Permission denied
ModSecurity: Rule processing failed.
ModSecurity: Geo Lookup: Failed to lock proc mutex: Permission denied
```

**Comment by udha** [comment]
Still no solutions to this yet?

**Comment by csanders-git** [comment]
what are the permissions on that file? this seems like an OS configuration issue not a ModSecurity issue.

**Comment by pkhadka56** [comment]
(root)-(jobs:0)-(/var/cpanel/secdatadir)-> ls -lh
total 1.5M
drwxrwx--T  3 root   nobody 4.0K Aug 24 07:18 ./
drwx--x--x 92 root   root    12K Oct  9 21:37 ../
-rw-r-----  1 nobody nobody    0 Feb 11  2015 global.dir
-rw-r-----  1 nobody nobody    0 Feb 11  2015 global.pag
-rw-r-----  1 nobody nobody 4.0K Oct  7 10:19 ip.dir
-rw-r-----  1 nobody nobody  15M Oct  9 21:38 ip.pag
-rw-r-----  1 nobody nobody    0 Aug 24 07:18 user.dir
-rw-r-----  1 nobody nobody    0 Aug 24 07:18 user.pag

**Comment by csanders-git** [comment]
Can you try chowning those to the same person who owns your webserver (likely apache)? also lets try changing the permissions to 777. Check to see if that helps!

**Comment by pkhadka56** [comment]
nope it is still giving same error. Any other way? FYI it's a cpanel.

**Comment by ConnorLinfoot** [comment]
Also having this same issue with a Wordpress Brute Force rule I've wrote. Any solution would be great.

**Comment by csanders-git** [comment]
@ConnorLinfoot  adding one rule should not cause this issue.... @pkhadka56  i'm unsure of what effects cpanel could have on it, coule you should me the ls -l of both the apache executable and the secdatadir?

**Comment by ConnorLinfoot** [comment]
@csanders-git I'm using cPanel also, if that helps at all.

**Comment by udha** [comment]
@pkhadka56 if you are using cPanel with apache chroot jailed vhosts and mod_ruid2 then you will need to change /var/cpanel/secdatadir in the modsec2.cpanel.conf file to /var/log/secdatadir, then make that directory and chmod 1733 it, and copy the *.dir and *.pag files into it with ugo+rw set.
This is because the apache 'nobody' process needs to read those files, and the users need to write to those files, which chroot environments cannot do to the /var/cpanel/secdatadir directory, but can for /var/log/*

Hope that helps.

**Comment by pkhadka56** [comment]
Thanks for the answer @udha but no luck. 

inside /var/log
drwx-wx-wt   2 root     nobody 4.0K Oct 14 00:56 secdatadir/

 inside secdatadir

drwx-wx-wt  2 root   nobody 4.0K Oct 14 00:56 ./
drwxr-xr-x. 8 root   root   4.0K Oct 14 00:53 ../
-rw-rw-rw-  1 nobody nobody    0 Jul 30 07:36 global.dir
-rw-rw-rw-  1 nobody nobody    0 Jul 30 07:36 global.pag
-rw-rw-rw-  1 nobody nobody 6.4M Sep 12 16:26 ip.dir

**Comment by hrace009** [comment]
@udha new cpanel will force it to default again. is there a configuration to keep SecDataDir at "/var/log/secdatadir" ?

**Comment by pkhadka56** [comment]
@hrace009 do following and see if it helps:

```
$ sudo vi /etc/apache2/conf.d/modsec_rule_01.conf
paste following
SecDataDir "/var/log/secdatadir"
```

save and exit

```
# sudo cp -R /var/cpanel/secdatadir /var/log/
# sudo chmod 1733 /var/log/secdatadir
# sudo chown -R nobody:nobody /var/log/secdatadir
# sudo chmod ugo+rw ip.*
```

Restart httpd and see if it helps.

**Comment by shunkica** [comment]
I did the steps described by @pkhadka56 but now i get this error - "Failed to access DBM file "/var/log/secdatadir/user": Permission denied"
Should I do "chmod ugo+rw /var/log/secdatadir/user.*" ?

**Comment by pa-de-solminihac** [comment]
@shunkica do you have some feedback about the security risk now that some time has passed?
