### ISSUE TITLE
POST body not logged

### ISSUE THREAD

**Issue by hacktek** [SpiderLabs/ModSecurity#922]
Using a (mostly default) install of the latest mod_security for Ubuntu 14.04 and with an Apache 2.4.7, I can't get POST data to show up in my log. Request inspection is on and I'm logging parts ABCJDEFHZ, however my logs look like this:

--f427934a-A--
[20/Aug/2015:17:38:27 --0400] VdZI06dYeLAAAE-MX80AAAAD x.x.x.x. 54611 y.y.y.y. 8000
--f427934a-B--
POST / HTTP/1.1
User-Agent: curl/7.37.1
Accept: _/_
Content-Length: 11
Content-Type: application/x-www-form-urlencoded

--f427934a-F--
HTTP/1.1 200 OK
Last-Modified: Wed, 18 Dec 2013 19:39:15 GMT
ETag: "b1-4edd43337fec0"
Accept-Ranges: bytes
Content-Length: 177
Edge-Control: max-age=600
Content-Type: text/html

Where's part C?

This was tested using a simple curl:

curl -XPOST -d "THISISATEST" http://somewhere

What do you need to debug this further?

**Comment by p0pr0ck5** [comment]
Can you show the ruleset that's triggering this audit log entry? Can you provide the full audit log entry as well (part H looks missing).

**Comment by hacktek** [comment]
Virtual Host has this: 
LogLevel debug
DumpIOInput On
DumpIOOutput On
SecRuleEngine On
SecAuditEngine on
SecAuditLog /var/log/apache2/website-audit.log
SecRequestBodyAccess on
SecStreamInBodyInspection On
SecAuditLogParts ABIJDEFHZ

Rest of modsecurity config: http://pastebin.com/0FJ3d6Av

**Comment by p0pr0ck5** [comment]
Your included paste shows 'SecAuditLogParts ABCJDEFHZ' but you also posted that your VirtualHost contains the directive 'SecAuditLogParts ABIJDEFHZ' (no part C).

**Comment by hacktek** [comment]
Not it, same behavior if I comment that out from the virtualhost settings or if I add C to it. Isn't I basically the same as C though?

	LogLevel debug
	DumpIOInput On
	DumpIOOutput On
	SecRuleEngine On
	SecAuditEngine on
	SecAuditLog /var/log/apache2/website-audit.log
	SecRequestBodyAccess on
	SecStreamInBodyInspection On
	#SecAuditLogParts ABIJDEFHZ

[25/Aug/2015:13:45:16 --0400] VdyprKdYeLAAABMgSe4AAAAD 23.79.232.14 41965 x.x.x.x 80
--919c853a-B--
POST / HTTP/1.1
User-Agent: curl/7.37.1
Host: xxxxx
Accept: */*
Content-Length: 11
Content-Type: application/x-www-form-urlencoded

--919c853a-F--
HTTP/1.1 200 OK
Last-Modified: Wed, 18 Dec 2013 19:39:15 GMT
ETag: "b1-4edd43337fec0"
Accept-Ranges: bytes
Content-Length: 177
Set-Cookie: poodle=noodle;Expires=Wed, Jan 01 2010 2:02:02 GMT
Edge-Control: max-age=600
Content-Type: text/html

--919c853a-E--
<html><body><h1>It works!</h1>
<p>This is the default web page for this server.</p>
<p>The web server software is running but no content has been added, yet.</p>
</body></html>

--919c853a-H--
Apache-Error: [file "mod_authz_core.c"] [line 802] [level 7] AH01626: authorization result of %s: %s
Apache-Error: [file "mod_authz_core.c"] [line 802] [level 7] AH01626: authorization result of %s: %s
Apache-Error: [file "mod_authz_core.c"] [line 802] [level 7] AH01626: authorization result of %s: %s
Apache-Error: [file "mod_authz_core.c"] [line 802] [level 7] AH01626: authorization result of %s: %s
Stopwatch: 1440524716319379 964 (- - -)
Stopwatch2: 1440524716319379 964; combined=50, p1=31, p2=15, p3=0, p4=0, p5=4, sr=0, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.7.7 (http://www.modsecurity.org/).
Server: Apache/2.4.7 (Ubuntu)
Engine-Mode: "ENABLED"

--919c853a-Z--

**Comment by hacktek** [comment]
Anything?

**Comment by zimmerle** [comment]
Hi @hacktek, did you tried to explicit enabled "C" into your audit log parts, for this specific virtual host? 

```
SecAuditLogParts ABIJDEFHZ
```

**Comment by jkdihenkar** [comment]
I'm getting a similar error as above which says : [ Below modsec_audit.log entry for reference ]

`---------------------------------------------------------------------

--3e24cc0c-A--
[29/Feb/2016:15:50:31 +0530] VtQbb2Qv@wVBBLWe4AIUAQAAAAo 127.0.0.1 37342 127.0.0.1 80
--3e24cc0c-B--
GET / HTTP/1.1
User-Agent: Curl
Host: 127.0.0.1
Accept: */*

--3e24cc0c-F--
HTTP/1.1 200 OK
Last-Modified: Tue, 11 Aug 2015 07:32:18 GMT
ETag: "1731-51d041a205758"
Accept-Ranges: bytes
Content-Length: 5937
Content-Type: text/html; charset=UTF-8

--3e24cc0c-E--

--3e24cc0c-H--
Message: Warning. Matched phrase "Curl" at REQUEST_HEADERS:User-Agent. [file "/etc/httpd/modsecurity.d/local_rules/modsecurity_localrules.conf"] [line "10"] [id "980001"] [rev "1"] [msg "All Bot Rule: Bot detected."] [severity "CRITICAL"]
Apache-Error: [file "mod_authz_core.c"] [line 809] [level 7] AH01626: authorization result of %s: %s
Apache-Error: [file "mod_authz_core.c"] [line 809] [level 7] AH01626: authorization result of %s: %s
Apache-Error: [file "mod_authz_core.c"] [line 809] [level 7] AH01626: authorization result of %s: %s
Apache-Error: [file "mod_authz_core.c"] [line 809] [level 7] AH01626: authorization result of %s: %s
Stopwatch: 1456741231759495 779 (- - -)
Stopwatch2: 1456741231759495 779; combined=71, p1=4, p2=59, p3=1, p4=0, p5=6, sr=0, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/).
Server: Apache/2.4.16 (Fedora) OpenSSL/1.0.1k-fips PHP/5.6.15 mod_wsgi/4.4.1 Python/2.7.8 mod_apreq2-20090110/2.8.1-dev
Engine-Mode: "ENABLED"

--3e24cc0c-Z--

-------------------------------------------------------------------
`
