### ISSUE TITLE
Is it possible to update secRule argument using regular expression?

### ISSUE THREAD

**Issue by stonecold123** [SpiderLabs/ModSecurity#923]
I have a POST request sending some youtube ids from their api. It is raising an warning from rule 981173 because the data has some special characters like dashes or underscores.  The tricky part is that the $_POST key is dynamic. It can be `video[400][]` or `video[431][]`.

Log:
```
Message: Access denied with code 403 (phase 2). 
  Pattern match "([\\~\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\-\\+\\=\\{\\}\\[\\]\\|\\:\\;\"\\'\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98\\`\\<\\>].*?){4,}" 
at ARGS_NAMES:video[391][]. [file "/etc/httpd/crs-tecmint/owasp-modsecurity-crs/base_rules/modsecurity_crs_41_sql_injection_attacks.conf"] 
[line "159"] [id "981173"] [rev "2"] 
[msg "Restricted SQL Character Anomaly Detection Alert - Total # of special characters exceeded"] 
[data "Matched Data: ] found within ARGS_NAMES:video[391][]: video[391][]"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] 
[accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"]
```
I was wondering if it is possible to update the rule like this:

`SecRuleUpdateTargetById 981173 !ARGS:video[*][]`

**Comment by zimmerle** [comment]
Hi @stonecold123,

Check it here:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleUpdateTargetById

There is this REQUEST_COOKIES example:

```
SecRuleUpdateTargetById 981172 "!REQUEST_COOKIES:/^appl1_.*/"
```

I think it will help you.
