### ISSUE TITLE
Semaphore leak

### ISSUE THREAD

**Issue by ia97lies** [SpiderLabs/ModSecurity#924]
If we start modsecurity in our proxy we get a leak of two semaphores after shutdown the proxy.

```
ipcs -s
------ Semaphore Arrays --------
key        semid      owner      perms      nsems     
0x00000000 28573696   root       600        1         
0x00000000 28606465   root       600        1         
```

This two semaphores never get destroied:

```
rc = apr_global_mutex_create(&msce->auditlog_lock, NULL, APR_LOCK_DEFAULT, mp);
```

and

```
rc = apr_global_mutex_create(&msce->geo_lock, NULL, APR_LOCK_DEFAULT, mp);
```

created int modsecurity_init. They should be destroied here:

```
/**
 * Releases resources held by engine instance.
 */
void modsecurity_shutdown(msc_engine *msce) {
    if (msce == NULL) return;
}
```

But yeah you see not much happens here.

**Comment by zimmerle** [comment]
Hi @ia97lies we are working on the libmodsecurity, check it here:

https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity

The idea is to replace the standalone module by libmodsecurity, so this will not be a problem anymore.

I guess you are using the nginx version, right?

**Comment by ia97lies** [comment]
Hi Zimmerle

Thanks for your response.
We use the standalon library, like nginx and IIS.
I'm looking forward for this new "standalone" library :-)

Regards
Christian

**Comment by WGH-** [comment]
APR prefers sysv semaphores by default. They have undesirable effect of being persistent. Since APR uses `IPC_PRIVATE`, their persistency is not used anywhere. Why can't ModSecurity switch to different type of mutex?

**Comment by zimmerle** [comment]
Won't fix in 2.x and fixed in libmodsecurity

Further information available here - https://github.com/SpiderLabs/ModSecurity-nginx

**Comment by ia97lies** [comment]
What does "Won't fix in 2.x and fixed in libmodsecurity" mean exactly? Is it now fixed or not? I also do not totally understand your link to ModSecurity-nginx...

**Comment by victorhora** [comment]
Hey @ia97lies,

"Won't fix in 2.x and fixed in libModSecurity" means that this bug in particular will not be fixed for the 2.x branch and it is already fixed on libModSecurity ("v3").

ModSecurity-nginx is one of the new connectors for libModSecurity. There's a nice blogpost on libModSecurity on this link: http://blog.zimmerle.org/2016/01/an-overview-of-upcoming-libmodsecurity.html
