### ISSUE TITLE
Instructions for building Libmodsecurity 

### ISSUE THREAD

**Issue by skynet** [SpiderLabs/ModSecurity#925]
How do we build Libmodsecurity and how do we integrate with Nginx as a module?

**Comment by csanders-git** [comment]
LibModSecurity is not ready for public consumption at this point. If the instructions provided don't make sense for how to build it to TEST then you most likely are not the target audience (this is not meant in an insulting way). We are working hard to make it viable as quickly as possible but of course its going to take some time. Thank you for your patience.

**Comment by skynet** [comment]
How soon do you think it will be ready?

**Comment by skynet** [comment]
I got it installed btw. Only problem is the requirementt for bison 3, and not sure what's the impact of installing bison 3 from source, instead of bison from yum.

**Comment by skynet** [comment]
Moving on to installing the nginx module.

**Comment by zimmerle** [comment]
@skynet are you using the v3 already? Any feedback so far?

**Comment by skynet** [comment]
I was but gave up since I was told that it is not for dummies like me ;)

**Comment by csanders-git** [comment]
@skynet at this point it is probably far closer to being production ready then the last time you were dealing with it :) might be time to give it another shot... should work with packages from repo's on modern OS's (tested with fedora 22) ... :-D

**Comment by skynet** [comment]
Will do, thank you and appreciate your work on this.
