### ISSUE TITLE
ModSecurity IIS disable rule by locationmatch

### ISSUE THREAD

**Issue by jimmychippewa** [SpiderLabs/ModSecurity#926]
Hello

I’m trying to disable rules based on location. I’ve seen many post for this for non-IIS based installations but I’m not able to use the same logic for IIS.

I’ve tried to use the <LocationMatch “/<url>”> approach and mod-security issues an error that the “<location” tag is not recognized.

Perhaps I’m missing something obvious but how I can disable rules for a URL with mod-security for IIS? I running mod-security 2.9.

 Thanks in advance

Jim

**Comment by zimmerle** [comment]
Hi Jim,

This location thing is just available in Apache, You may want to skip the rules with a certain path match, check here:

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#skip
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#skipAfter
