### ISSUE TITLE
modsecurity package not found

### ISSUE THREAD

**Issue by coolsivakrishna** [SpiderLabs/ModSecurity#929]
Hi,

I'm trying to install modsecurity for apache server on command line but getting "No package found" error

Commands I've tried are,

Ubuntu 14.04 server:
"sudo apt-get install libapache2-modsecurity"
"sudo apt-get install libapache2-mod-security"

centOS:
"sudo yum mod_security"

I'm trying it from few days and unable to install modsecurity.

Your responce will be of great value to me.

Thankyou.

**Comment by zimmerle** [comment]
Please use:
```
$ apt-cache search modsecurity 
```
or 
```
$ yum search modsecurity
```
To get the correct name of the package.

**Comment by coolsivakrishna** [comment]
![capture](https://cloud.githubusercontent.com/assets/13213029/9985805/c93b4000-6050-11e5-8a9c-967eac480b47.PNG)

**Comment by csanders-git** [comment]
as I mentioned in the other post you'll have to search for mod_security on RHEL because the word 'modsecurity' is not in the description and mod_security is the package name. If its not there it is a problem with your repo's
