### ISSUE TITLE
Unable to install ModSecurity on Windows Server 2016

### ISSUE THREAD

**Issue by skvoboo** [SpiderLabs/ModSecurity#931]
Unable to install ModSecurity 2.9.0 on Windows Server 2016 technical preview 3 (IIS 10) : This setup requires IIS 7.0 or 8.0.

Please change LaunchCondition in installer from
(IIS="#7") OR (IIS="#8")
to
(IIS="#7") OR (IIS="#8") OR (IIS="#10")

**Comment by zimmerle** [comment]
Hi @skvoboo did you tested 2.9.0 on 2016? is it working right?

**Comment by zimmerle** [comment]
Fix on branch: 

```
https://github.com/SpiderLabs/ModSecurity/tree/issue_931
```

Waiting for confirmation that ModSecurity really working with IIS 10.

**Comment by pvasilevich** [comment]
Are there any news on this patch? when it will be merged in master?

**Comment by zimmerle** [comment]
Hi @pvasilevich,

It won't be merged until we got the confirmation that it is really working. Do you mind to test it?

This specific patch only adds the IIS 10 as accepted on the installer validation.

**Comment by pvasilevich** [comment]
It is pretty hard to test how Modsecurity is working without ability to install it. I can manually apply MSI transformation, but I guess there will be more chances to find bugs on this platform, if other people will be able to install Modsecurity as well.

I will check basic functionality anyway and report you if there are other issues.

**Comment by csanders-git** [comment]
@pvasilevich I wanted to confirm you're running technical preview 3.. is this correct?

**Comment by pvasilevich** [comment]
Now we are testing on tech preview 4

**Comment by csanders-git** [comment]
@pvasilevich A quick way to test the install is to change (temporarily) "HKLM\SOFTWARE\Microsoft\InetStp" from 10 to 8 then after install change back.

**Comment by csanders-git** [comment]
From initial tests it seems to be working fine. I will conduct more through tests....
![image](https://cloud.githubusercontent.com/assets/4632287/11769746/4e8012d4-a1bc-11e5-9c2f-681241b8e02e.png)

**Comment by zimmerle** [comment]
Hi @csanders-git,

That was a beautiful hack :+1: 

I guess it is safe to merge to our mainline.

Thank you guys.

**Comment by zimmerle** [comment]
@skvoboo what is your full name?

I want to mention your name on the changelogs.

**Comment by skvoboo** [comment]
Hi @zimmerle.

**Comment by zimmerle** [comment]
Thank you guys, the patch was merged. ModSecurity v2.9.1 will be compatible with IIS 10.
