### ISSUE TITLE
modsecurity package not found

### ISSUE THREAD

**Issue by coolsivakrishna** [SpiderLabs/ModSecurity#932]
Hi,

I'm trying to install modsecurity for apache server on command line but getting "No package found" error

Commands I've tried are,

Ubuntu 14.04 server:
"sudo apt-get install libapache2-modsecurity"
"sudo apt-get install libapache2-mod-security"

centOS:
"sudo yum mod_security"

I'm trying it from few days and unable to install modsecurity.

I also tried,

$ apt-cache search modsecurity 

and

$ yum search modsecurity

but not getting...
here I attached a pic of terminal

![capture](https://cloud.githubusercontent.com/assets/13213029/9985835/37cefc64-6051-11e5-83a1-8c60c1ac711f.PNG)

**Comment by csanders-git** [comment]
you see to be all over a bunch of different OS's in general here is the breakdown.... on RHEL based OS's modsecurity is typically refereed to as mod_security. so the command would be 'yum install mod_security'. In general the search functionality doesn't work very well as the description doesn't have the word 'ModSecurity' in it the only thing that comes up is mod_security_crs (when you do yum search modsecurity). If you can still not install it obviously check your repo's :)... But I just looked and its still in there (not that i'd expect it to go anywhere :-P )
