### ISSUE TITLE
modsecurity record my server ip as source of attack instead of real attacker ip

### ISSUE THREAD

**Issue by macnux** [SpiderLabs/ModSecurity#937]
Hi
im using Mod Security 2.9.0 and i found that all source ip for all attacks is my server ip address !!!
and due to this the firewall cannot block any attack
so what to do to make modsecurity record the attacker ip not my server ip
thanks in advance.

**Comment by csanders-git** [comment]
we're going to need slightly more detail :). What kind of webserver are you using. what kind of deployment (inline, reverse proxy, etc) and lastly can you provide us a wonderful capture of either the error log or audit log where this happening. Thanks!

**Comment by zimmerle** [comment]
Hi @macnux, closing this issue until we've got more information about it.

**Comment by macnux** [comment]
im sorry that was nginx used as proxy needs to reinstalled 
thanks
