### ISSUE TITLE
2.9.0 wont compile apr_crypto broken

### ISSUE THREAD

**Issue by chrcoluk** [SpiderLabs/ModSecurity#938]
2.8 compiles fine.

System is FreeBSD 9.3
Apache version is 2.4.x
I have tried with different APR packages.

Compile stops at following.

 'apache2_config.c' || echo './'`apache2_config.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/local/include/apr-1 -I/usr/local/include/apr-1 -I/usr/local/include -I/usr/local/include/db5 -I/usr/include/apache -I/usr/local/include -DWITH_CURL_SSLVERSION_TLSv1_2 -DWITH_CURL -I/usr/local/include/libxml2 -I/usr/local/include -DWITH_LUA -I/usr/local/include/lua51 -DWITH_PCRE_STUDY -DMODSEC_PCRE_MATCH_LIMIT=1500 -DMODSEC_PCRE_MATCH_LIMIT_RECURSION=1500 -DREQUEST_EARLY -DWITH_APU_CRYPTO -DWITH_REMOTE_RULES -I/usr/local/include -g -O2 -I/usr/local/include/apr-1 -I/usr/local/include -I/usr/local/include/db5 -MT mod_security2_la-apache2_config.lo -MD -MP -MF .deps/mod_security2_la-apache2_config.Tpo -c apache2_config.c  -fPIC -DPIC -o .libs/mod_security2_la-apache2_config.o
In file included from modsecurity.h:49,
                 from apache2_config.c:17:
msc_remote_rules.h:54: error: expected declaration specifiers or '...' before 'apr_crypto_key_t'
msc_remote_rules.h:55: error: expected declaration specifiers or '...' before 'apr_crypto_t'
apache2_config.c: In function 'cmd_rule_update_action_by_id':
apache2_config.c:2432: warning: comparison is always false due to limited range of data type
apache2_config.c:2432: warning: comparison is always false due to limited range of data type
*** [mod_security2_la-apache2_config.lo] Error code 1

**Comment by zimmerle** [comment]
Hi @chrcoluk,

What version are you trying to compile: the release .tar.gz or the code straight from git?

Give a try on the git repo, if not working please paste your config.log on gist (https://gist.github.com/) and paste the link here.

**Comment by chrcoluk** [comment]
The release tarball, will try pulling from git tomorrow after some sleep.

**Comment by zimmerle** [comment]
Hi @chrcoluk, let me known your findings :)

**Comment by chrcoluk** [comment]
Hi, I finally got round to testing your git code.

Is same error.

**Comment by chrcoluk** [comment]
Seems related to this in 2.9 changelog "Fix apr_crypto.h include, now checking if apr_crypto.h is available by checking the definition WITH_APU_CRYPTO. [martinjina and ModSecurity team]"

**Comment by lifeforms** [comment]
Hi @chrcoluk, this is unrelated to your error, but is there any reason that you can't use the `www/mod_security` FreeBSD port?

**Comment by chrcoluk** [comment]
Yes, it is a directadmin server which compiles web tools from src code.

**Comment by chrcoluk** [comment]
https://gist.github.com/chrcoluk/f41f4beab787c290ef759c05dfcd6fb6

**Comment by chrcoluk** [comment]
trying to find a way to compare 2.90-rc1 and 2.90-rc2 branches but will only let me compare to master.

**Comment by chrcoluk** [comment]
I am doing manual rollbacks now one at a time for each commit to try and find cause but I have already found 2 errors, where the file content doesnt match what is in git commit log, errors may have been made..

**Comment by chrcoluk** [comment]
This is over my head with all the changes, after I manually backed out one commit I get an aclocal error.

But given these are crypto related warnings it is probably one of these 2 commits especially as the first one modifies the line which is failing.

https://github.com/SpiderLabs/ModSecurity/commit/23823bb2c310b19a1ee4556454a1627ce4773d17
https://github.com/SpiderLabs/ModSecurity/commit/6c0cdab35a7cf35a61dc8b7d8bfe4363660c14c2

The first removes curl dependency, and the second openssl, both are crypt dependencies.  Seems this was done without proper testing.

**Comment by chrcoluk** [comment]
here is config log for the git code and no configure flags used

https://gist.github.com/chrcoluk/18d0ea99e5af0db04bdd45c20d89cdb8

**Comment by chrcoluk** [comment]
Problem is resolved now.  I cannot explain why it did not break things on 2.90-rc1 and older, I guess the configure and build scripts had more leniancy then but the problem was as follows.

Directadmin build scripts compile apache with included apr libraries put in /usr/ib/apache and /usr/include/apache
The FreeBSD devel/apr1 package dumps its own apr libraries in /usr/local/lib

The modsecurity config was checking the libraries in /usr/local/lib and enabling APR_CRYPTO support, but then the compiler was compiling against the libraries in /usr/lib/apache and /usr/include/apache which did not have this support so it bombed out.  On my servers i cleared out those 2 folders and now compile apache against the FreeBSD apr libraries and modsecurity now compiles fine. 

I reported the issue to the directadmin developer with some ideas of how to resolve.

**Comment by zimmerle** [comment]
Hi @chrcoluk, thank you for the report.
