### ISSUE TITLE
PUT body not processed

### ISSUE THREAD

**Issue by balinju** [SpiderLabs/ModSecurity#939]
According to the following, PUT body is not processed, only POST body is. In many REST services, PUT is used very frequently and SQL injection (and other) attacks can be caught if mod security processes these requests.

https://github.com/SpiderLabs/ModSecurity/blob/master/nginx/modsecurity/ngx_http_modsecurity.c#L1011-L1021

(thanks very much Felipe Costa for the help in identifying this out)

More information in this thread here: http://sourceforge.net/p/mod-security/mailman/message/34499810/

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
