### ISSUE TITLE
modsecurity Custom policy

### ISSUE THREAD

**Issue by houhuijian** [SpiderLabs/ModSecurity#942]
1、The combination rule, such as when you access a URL, and then the referer head is the specified string, useragent version is specified on the deny, this rule I tried not to do a few times。Can you help me to write a rule for me to write a rule for me
2、modsecurity Whether you can set the frequency of access to a URL，If you can, please give me an example.Thanks！

**Comment by csanders-git** [comment]
Since this isn't a bug i'll direct you towards Ivan Ristic's work on writing rules, you can also contact the mailing list if you need additional help... https://www.feistyduck.com/books/modsecurity-handbook/modsecurity-rule-writing-workshop.pdf

**Comment by houhuijian** [comment]
I've figured it out, the first is the regular expression need to be familiar, and secondly, when I made the first detection of Strategy useragent, then you can achieve detection url blocked, but the first test url, then test useragent has failed, do not know why
