### ISSUE TITLE
nginx installed modsecurity case of how to open mlogc

### ISSUE THREAD

**Issue by houhuijian** [SpiderLabs/ModSecurity#943]
When installed on my nginx modsecurity module, and install selected mlogc, have generated mlogc executable file, but is configured in the configuration file, he said after being given mlogc always unsuccessful, fully configured according to the official configuration is no problem , is there any configuration ever before

**Comment by zimmerle** [comment]
Hi @houhuijian are you trying to run mlogc inline with nginx? or using the batch script?

**Comment by houhuijian** [comment]
@zimmerle Please guide us, do mlogc or batch script in the error log will log output alone，
[Thu Oct 22 12:49:31 2015] [4] [63864/0] Checkpoint not required.
[Thu Oct 22 12:49:36 2015] [5] [63864/1ae32a8] Management thread: Processing
[Thu Oct 22 12:49:36 2015] [5] [63864/1ae32a8] Management thread: Last checkpoint was 5 seconds ago.
[Thu Oct 22 12:49:41 2015] [5] [63864/1ae32a8] Management thread: Processing
[Thu Oct 22 12:49:41 2015] [5] [63864/1ae32a8] Management thread: Last checkpoint was 10 seconds ago.
[Thu Oct 22 12:49:46 2015] [5] [63864/1ae32a8] Management thread: Processing
[Thu Oct 22 12:49:46 2015] [5] [63864/1ae32a8] Management thread: Last checkpoint was 15 seconds ago.
[Thu Oct 22 12:49:51 2015] [5] [63864/1ae32a8] Management thread: Processing
[Thu Oct 22 12:49:51 2015] [4] [63864/1ae32a8] Management thread: Initiating a checkpoint (previous was 20 seconds ago).
[Thu Oct 22 12:49:51 2015] [4] [63864/0] Checkpoint not required.
Is this normal for you

**Comment by zimmerle** [comment]
Hi @houhuijian do you mind to elaborate a little bit more your question ?

**Comment by houhuijian** [comment]
Hi @zimmerle After I installed modsecurity, do not open mlogc everything is normal, but after opening mlogc, when starting nginx service when the show Failed to open the audit log pipe, execution mlogc alone, show more information

**Comment by victorhora** [comment]
Nginx support in ModSecurity 2.9.x branch is deprecated. This shouldn't be a concern with [libModSecurity](https://github.com/SpiderLabs/ModSecurity/tree/v3/master) where the [SecAuditLogType](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#SecAuditLogType) HTTPS directive is available instead of MlogC. 

Thanks!
