### ISSUE TITLE
Installation libmodsecurity Debian 8

### ISSUE THREAD

**Issue by rz300** [SpiderLabs/ModSecurity#946]
When installing libmodsec on my debian 8, i've some problems during installation: build.sh
http://pastebin.com/1fhX7jrF
And ./configure
http://pastebin.com/hUgRJvdS
Folder "others/libinjection" is empty. What have i do to fix this problem?

**Comment by zimmerle** [comment]
Hi @rz300,

Libinjection is now part of ModSecurity project as a gitsubmodule [1]. In order to download our submodules, please try:

```
$ git submodule init
$ git submodule update
```

The warning messages that you saw on the ./build.sh is probably because you don't have the pkg-config installed.

[1] https://git-scm.com/docs/git-submodule

**Comment by rz300** [comment]
another problem 
```/etc/nginx/sbin/nginx -V: error while loading shared libraries: libmodsecurity.so.3: cannot open shared object file: No such file or directory```
Although the file exists
```
root@box-host:/home/anubis/downloads/nginx-1.8.0# locate libmodsecurity.so.3
/usr/local/modsecurity/lib/libmodsecurity.so.3
/usr/local/modsecurity/lib/libmodsecurity.so.3.0.0
```
What have i do for fix it?

**Comment by zimmerle** [comment]
Hi @rz300,

Sorry about that. This problem was also reported by @LinuxJedi. I have to fix that during the configuration/compilation time. In the meanwhile set the LD_LIBRARY_PATH should fix it for you.

Notice that you are setting the LD_LIBRARY_PATH to your current shell, my feeling is that the "service" script does not have access to this env var.

The easiest way to go is probably to run the nginx process in your current shell, instead of using the service script.

```
$ /usr/local/nginx/sbin/nginx
```

There are other options, like change the file "auto/options" to set NGX_RPATH to YES. You can also configure nginx using the --with-ld-opt, as following:
```
./configure --prefix=/your/prefix \
         --with-ld-opt="-Wl,-rpath,/path/to/libmodsec" \
...
```

**Comment by rz300** [comment]
Hi @zimmerle, i'll wait for compilation fix. Don't forget tell me about it ;-)

**Comment by LinuxJedi** [comment]
@zimmerle NGX_RPATH doesn't seem to work right in Linux (which might be why it is only enabled for Solaris by default). I recommend something like this in the module config file:

```
        if [ $NGX_RPATH = YES ]; then
            ngx_feature_libs="-R/usr/local/modsecurity/lib -L/usr/local/modsecurity/lib -lmodsecurity"
        elif [ $NGX_SYSTEM = "Linux" ]; then
            ngx_feature_libs="-Wl,-rpath,/usr/local/modsecurity/lib -L/usr/local/modsecurity/lib -lmodsecurity"
        else
            ngx_feature_libs="-L/usr/local/modsecurity/lib -lmodsecurity"
        fi
```

Whilst it isn't the most elegant solution it should work long-term

**Comment by zimmerle** [comment]
Hi @LinuxJedi 

Made the following change: https://github.com/SpiderLabs/ModSecurity-nginx/commit/0b27aff93617c5952d054339a855920f1b2bc5c8

That will enable rpath if the target platform is Linux.

**Comment by rz300** [comment]
it doesn't work for me
```
root@box-host:/home/anubis/downloads/nginx-1.9.5# systemctl status nginx.service
● nginx.service - LSB: Stop/start nginx
   Loaded: loaded (/etc/init.d/nginx)
   Active: failed (Result: exit-code) since Tue 2015-10-27 15:18:15 MSK; 5s ago
  Process: 17402 ExecStop=/etc/init.d/nginx stop (code=exited, status=0/SUCCESS)
  Process: 23883 ExecReload=/etc/init.d/nginx reload (code=exited, status=0/SUCCESS)
  Process: 17456 ExecStart=/etc/init.d/nginx start (code=exited, status=127)

Oct 27 15:18:15 box-host.ru nginx[17456]: /usr/sbin/nginx: error while loading shared libraries: libmodsecurity.so.3: cannot open shared object file: No such file or directory
Oct 27 15:18:15 box-host.ru systemd[1]: nginx.service: control process exited, code=exited status=127
Oct 27 15:18:15 box-host.ru systemd[1]: Failed to start LSB: Stop/start nginx.
Oct 27 15:18:15 box-host.ru systemd[1]: Unit nginx.service entered failed state.
```

**Comment by LinuxJedi** [comment]
there is a bug in that patch, the whitespace is important before the closing square brace

**Comment by zimmerle** [comment]
Buildbots just complained about it. Let me fix that.

**Comment by zimmerle** [comment]
Sorry guys, it is on a better shape now. Buildbots are also testing it.
