### ISSUE TITLE
NGINX and mutex permission issues

### ISSUE THREAD

**Issue by uxbod** [SpiderLabs/ModSecurity#951]
I have modsecurity compiled against NGINX 1.9.5 and have enabled the Geo Loopup capability.  

Am having an issue that for every URL request an audit entry is created with the following:

Message: Geo Lookup: Failed to lock proc mutex: Permission denied

After stracing the process I found that a semop() call was failing so when I checked the semaphores I saw:

------ Semaphore Arrays Creators/Owners --------
semid      perms      cuid       cgid       uid        gid
0          600        root       root       4294967295 4294967295
32769      600        root       root       4294967295 4294967295
65538      600        root       root       4294967295 4294967295
98307      600        root       root       4294967295 4294967295

the problem being that the NGINX workers are running as the 'nginx' user therefore unable to write to the semaphore mutex.

In https://github.com/SpiderLabs/ModSecurity/blob/master/standalone/server.c I have had to open the permissions up from 0600 to 0666:

buf.sem_perm.uid = ap_unixd_config.user_id;
buf.sem_perm.gid = ap_unixd_config.group_id;
buf.sem_perm.mode = 0666;

and once compiled and installed no more permission denied errors are generated by the Geo lookup function.

Hopefully this can be fixed as we do not like have to open up writes to the world, least it better than running NGINX as root!

Thanks, Phil

**Comment by zimmerle** [comment]
To be fixed in libmodsecurity

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
