### ISSUE TITLE
Is standalone truly standalone?

### ISSUE THREAD

**Issue by skeyl** [SpiderLabs/ModSecurity#952]
Apologies if this is more or less a question than a bug. But, after reading over the documentation and compiling ModSecurity a few times I'm under the impression that standalone means I can run ModSecurity as a proxy without building it into IIS/nginx/httpd; is that true? If so how do I do this? I was looking over the source code in `standalone/` and it looks like it's possible but I'm not able to find any information on how?

**Comment by zimmerle** [comment]
Hi @skeyl,

Standalone is a wrapper to Apache internals that allows ModSecurity to be executed. That wrapper still demand Apache pieces. It is true that you can extend your application using the Standalone version although, you will need some Apache pieces (See #661 and #686).

You may be interested in the libModSecurity (still under development), which is available here: 
https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity

The libModSecurity is a complete re-write of ModSecurity free of Apache or libapr.

There is an example on how to extend your software with libModSecurity here:
https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/examples/simple_example_using_c

There is also the nginx connector:
https://github.com/SpiderLabs/ModSecurity-nginx
