### ISSUE TITLE
Using variables with action exec

### ISSUE THREAD

**Issue by pakxpakx** [SpiderLabs/ModSecurity#954]
Hi there, 

I am trying to use "exec" in SecRule to run a shell script.
I wrote the action as following:
exec:/root/test.sh
It works. But after that, I want to pass request uri to the shell script.
I wrote the following action:
exec:'/root/test.sh %{REQUEST_URI}'
This action just pass the string "%{REQUEST_URI}" to the shell script. This is not what I want.
Does anyone know how to use variables with "exec"?

**Comment by zimmerle** [comment]
Hi @pakxpakx,

It seems that we don't have variable resolution in the command execution. You may want to set a environment variable prior to the execution of the script. See: https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#setenv
