### ISSUE TITLE
Covert Channel Awareness

### ISSUE THREAD

**Issue by morpheushax** [SpiderLabs/ModSecurity#958]
Hello. When will modsecurity be implementing TCP header logging? I am very worried about covert channels within TCP headers and would like to be able to detect these threats. Additionally, have you considered any layer 2 protections? These threats should be taken much more seriously than most people think.

**Comment by wavedong** [comment]
How was this not noticed previously? Please comment.... NOW!!!!

**Comment by csanders-git** [comment]
Currently ModSecurity targets only data that is exchanged in the HTTP data portion of each packets. For more information please see the following texts: Web Application Defender's Cookbook: Battling Hackers and Protecting Users  and ModSecurity Handbook: The Complete Guide to the Popular Open Source Web Application Firewall. If you are interested in adding additional functionality, the project is open source and you can feel free to fork it and add TCP header logging. Be aware however that most webservers do not maintain this information. You are more aptly looking for an IDS/IPS.
