### ISSUE TITLE
modsecurity only allowed to upload pictures 8k

### ISSUE THREAD

**Issue by houhuijian** [SpiderLabs/ModSecurity#959]
After nginx install mod_security, you can not upload more than 8k size image，I should be how to solve this problem？

**Comment by zimmerle** [comment]
Hi @houhuijian,

Please use nginx_refactoring branch.

**Comment by houhuijian** [comment]
@zimmerle I've replaced nginx refactoring branch, but still the same problem

**Comment by zimmerle** [comment]
Hi @houhuijian,

Once using the nginx_refactoring, you may want to set:

```
https://github.com/SpiderLabs/ModSecurity/issues/839
```

See #839.

**Comment by nilsher** [comment]
I have the same problem have tried with latest version of nginx_refactor branch.

I do not get any coredump so do not se why issue 839 would be involved.

**Comment by zimmerle** [comment]
Hi @nilsher,

Did you had chance to set proxy_force_ranges? As demonstrated below:

```
proxy_force_ranges on;
```

**Comment by nilsher** [comment]
I tried setting in in http and location directive and it did not solve the issue.

**Comment by gago08** [comment]
Hello  I tried to upload base64 images with php post and in safari i keep getting a lost connection response, i have also discovered that if i turn mod security off, everything work just fine, do you know if there is some detail i have to add to my code to let me upload the base64 images with out turning mod security off

Thank you!!
