### ISSUE TITLE
How to run SecRuleScript python ?

### ISSUE THREAD

**Issue by ngocthach** [SpiderLabs/ModSecurity#962]
I write rule, run script shell script: post.sh, this is ok
but, now I want to run script by Python "post.py", i don't know write rule, error when use rule 

- Shell script:
SecRule ARGS,REQUEST_METHOD "^(POST)$" "id:112,pass,auditlog, setenv:bodypost=%{REQUEST_BODY}, exec:/usr/local/bin/post.sh"

      + post.sh:
              #!/bin/sh
              a=$bodypost
               // --- I will process string here---//
   --> OK

- Python:
    SecRule ARGS,REQUEST_METHOD "^(POST)$" "id:112,pass,auditlog, setenv:bodypost=%{REQUEST_BODY}, exec:/usr/local/bin/post.py"
    + post.py:
        #!/usr/bin/python
         import string
         rx_data=$bodypost
      --> Error, no define "bodypost"

Who can help me ? Thanks

**Comment by zimmerle** [comment]
Hi @ngocthach,

The **setenv** action sets a environment variable, like described here:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#setenv

To access those environment variables from Python, you may want to use **os.environ**, like described here: https://docs.python.org/2/library/os.html#process-parameters

The Python script will be something like this:
```
#!/usr/bin/python

import os

yourVar = os.environ['bodypost']
```
