### ISSUE TITLE
Implement the support to t:cmdLine into libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#965]
Transformation **cmdLine** needs to be implemented inside libmodsecurity.

The documentation of the transformation can be found here:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#cmdLine

The file already exist in the repository:
https://github.com/SpiderLabs/ModSecurity/blob/libmodsecurity/src/actions/transformations/cmd_line.cc

**Comment by zimmerle** [comment]
Feature added. c855291

**Comment by zimmerlezen** [comment]
Test cases at SpiderLabs/secrules-language-tests@8089e2ef12e8572c7d9feb8463e608b20de928ba
