### ISSUE TITLE
Large JSON request payload causes nginx out-of-memory error in DetectionOnly mode

### ISSUE THREAD

**Issue by puneetx** [SpiderLabs/ModSecurity#975]
Hi there,

I have an API that receives a large JSON payload (300KB) via a POST request. The nginx process crashes with out-of-memory error in DetectionOnly mode, whereas it works just fine in the blocking mode (i.e. the request passes ok from nginx to the backend server). Is there a configuration option that I may be missing? Or an incompatible library/version?

System:
ubuntu 14.04
2GB RAM
nginx 1.8.0
CRS ver.2.2.9

JSON library:
libyajl.so.2.1.0

Config:
SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecRequestBodyLimit 1310720

Rest of the rules have been left unmodified from the original downloaded OWASP CRS, etc.

Sample JSON:
https://www.dropbox.com/s/c9de5cuas1kll1b/json_data.txt?dl=0

**Comment by zimmerle** [comment]
Hi @puneetx, are you using the nginx_refactoring branch?

**Comment by puneetx** [comment]
Hi @zimmerle, I just tried with nginx_refactoring branch as well. However, I ran into the same out-of-memory error.

**Comment by zimmerle** [comment]
Hi @puneetx, I am trying to identify if the problem is related to the malfunction of upload (request body) or if it specific to JSON. Can you try to upload something different from a XML and check if it is working as expected?

**Comment by zimmerle** [comment]
No longer a concern in libModSecurity. Marking it as won't fix for 2.x. Further information about libModSecurity available here:
https://github.com/SpiderLabs/ModSecurity/tree/v3/master
