### ISSUE TITLE
modsecurity only allowed to upload pictures 8k

### ISSUE THREAD

**Issue by nilsher** [SpiderLabs/ModSecurity#976]
Hello I am running modsecurity 2.9 with nginx 1.8
I also tried to compile with nginx_refactoring branch but the problem persisted.

When posting a large image modsecurity gets stuck trying to send the 8192 bytes and then eventually fail.

I have read issues and these do not help.
https://github.com/SpiderLabs/ModSecurity/issues/959
https://github.com/SpiderLabs/ModSecurity/issues/839

**Comment by zimmerle** [comment]
Hi @nilsher,

I will close this issues because its content (even its subject) is the very same of the issue #959. I don't see why we need a new issue for that. This duplicated issue may confuse other users. Our issues are also knowledge base.
