### ISSUE TITLE
Missing Sanity Check for malloc() plus possible NULL pointer dereference in modsecurity-2.9

### ISSUE THREAD

**Issue by dogbert2** [SpiderLabs/ModSecurity#979]
Hello All,

In reviewing source code in modsecurity-2.9, sub-directory 'apache2',
file 'msc_remote_rules.c', there is a call to 'malloc()' in function
'msc_remote_download_content()' at approximately line 312 where it is
NOT tested for a return value of NULL, indicating failure.  The patch
file below should address/correct this error:

```
--- msc_remote_rules.c.orig     2015-11-19 09:43:23.974453067 -0800
+++ msc_remote_rules.c  2015-11-19 09:49:49.812453231 -0800
@@ -312,6 +312,11 @@
         struct curl_slist *headers_chunk = NULL;
 #ifdef WIN32
         char *buf = malloc(sizeof(TCHAR) * (2048 + 1));
+       if (buf == NULL) { /* malloc failed... */
+           *error_msg = apr_psprintf(mp, "Unable to allocate memory");
+           ret = -2;
+           goto failed;
+       }
         char *ptr = NULL;
         DWORD res_len;
 #endif
```
# 

In sub-directory 'apache2', file 'msc_util.c', there are calls to
malloc() which are not checked for a return value of NULL, but immediately
afterwards, a call to memset() is made, but if the first parameter
to memset() is NULL, a segmentation violation/fault will occur, resulting
in the program crashing/aborting.  The patch file below should correct
and/or address these issues:

```
--- msc_util.c.orig     2015-11-19 09:57:34.588453429 -0800
+++ msc_util.c  2015-11-19 10:11:31.360453785 -0800
@@ -2783,11 +2783,20 @@
     if (mem->size == 0)
     {
         mem->memory = malloc(realsize + 1);
+       if (mem->memory == NULL) {
+           *error_msg = apr_psprintf(mp, "unable to allocate buffer for mem->memory");
+           return 0;
+       }
         memset(mem->memory, '\0', sizeof(realsize + 1));
     }
     else
     {
-        mem->memory = realloc(mem->memory, mem->size + realsize + 1);
+       void *tmp;
+       tmp = mem_memory;
+        tmp = realloc(mem->memory, mem->size + realsize + 1);
+       if (tmp != NULL)
+           mem_memory = tmp;
+           
         memset(mem->memory + mem->size, '\0', sizeof(realsize + 1));
     }
```
# 

Bill Parker (wp02855 at gmail dot com)

**Comment by zimmerle** [comment]
Hi @dogbert2,

Thank you for the review, in fact those sanity checks are very important. Do you want to send your observations in a format of a patch (pull request)? I would love to merge it into our code.

**Comment by dogbert2** [comment]
That would be fine, only thing I ask is to get credit for the find/fix in
the Changelog :)

Bill Parker

**Comment by csanders-git** [comment]
@dogbert2 I'd reckon you'd get credit even without asking for it, this is a good finding thanks for reporting it :)

**Comment by dogbert2** [comment]
If you want to take the existing diff and work it into a pull against
github, that would be fine, the code gives a clean compile on Fedora 22
Server (aka Deadrat :)

Bill

**Comment by zimmerle** [comment]
Hi @dogbert2,

Your first diff is perfect, working as expected. I think we have a copy and paste error in the second one, as it won't compile. Do you mind to give it a look ?

I've just created this branch "issue_979": 
https://github.com/SpiderLabs/ModSecurity/tree/issue_979

Your first first diff is committed in this branch. I am waiting for the second diff to send it to mainline.

**Comment by dogbert2** [comment]
I'll take a look at this later today :)

Bill

**Comment by victorhora** [comment]
The proposed patch has been fixed and the improvement was added to the master branch as of https://github.com/SpiderLabs/ModSecurity/commit/9be0a407ebc8a7972b129a76109d54500e19bb41.

Thanks! :)
