### ISSUE TITLE
Nginx with Modsecurity: POST request gives 500 error

### ISSUE THREAD

**Issue by houhuijian** [SpiderLabs/ModSecurity#985]
Nginx with Modsecurity: POST request gives 500 error，use no 80 port ，no problem，Is there a way to solve this problem you

**Comment by zimmerle** [comment]
Hi @houhuijian,

We have a couple of issues opened regarding this very same subject. You can list those here:
https://github.com/SpiderLabs/ModSecurity/labels/Platform%20-%20Nginx

Inside the issues you will find discussion and possible solution to your problem. 

Our proposal to solve all that issues is by the utilization of ModSecurity version 3 which is currently under development.
