### ISSUE TITLE
Filter requests without filename

### ISSUE THREAD

**Issue by gilperon** [SpiderLabs/ModSecurity#986]
Hi,

I want to filter the type of request below on phase1 only if it translates to a PHP file:

http://www.example.com/

My server may translate that request to an index.html file, or index.php file... depending on it's configuration. I really need this cause I was working on a customer's server that was under attack and I wanted to mitigate it and filter only the connections that translate to a php file and I can do that only when the filename is explicit on the URL like http://www.example.com/index.php however when the filename is not present how do I filter it if it translates to a .php file?

I know I can use SCRIPT_FILENAME however it does not look to be available at phase 1. Could someone please check that information?

**Comment by zimmerle** [comment]
Hi @gilperon, Do you really need to block the request in phase 1 ?

**Comment by gilperon** [comment]
@zimmerle it would be best cause I am using that code to mitigate a huge attack my server receives once in a while. I use mod_security which helps me A LOT to mitigate the attack without paying $ 500 to DDOS companies like blockddos. Mod_security does a really great job mitigating it but it would be really nice to be able to use SCRIPT_FILENAME at phase1 cause I could use much more precise rules to block the attack.

**Comment by zimmerle** [comment]
Hi @gilperon,

The reason why we don't have the SCRIPT_FILENAME in phase 1 is because, at this phase, Apache does not knows the SCRIPT_FILENAME yet. As we depend on Apache, we don't have this information as well.

For ModSecurity version 3 (aka libmodsecurity) we are creating some intermediate phases to cover exactly that case. But it is not ready for release yet.

**Comment by gilperon** [comment]
Thank you, I appreciate your version 3! I will follow it to make sure I get that release.

**Comment by zimmerle** [comment]
@gilperon if you want to follow it closer, have a look here:

https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/

Thanks ;)

**Comment by gilperon** [comment]
Nice really nice :)
