### ISSUE TITLE
ModSecurity: XML parser error: XML: Failed parsing document. 

### ISSUE THREAD

**Issue by pfeiffebe** [SpiderLabs/ModSecurity#989]
Hey!

Found some problem, parsing XML-Documents. The problem is, that modsecurity_crs_10_config.conf Line: ~ 407

SecRule REQUEST_HEADERS:Content-Type "text/xml" \
  "id:'900017', \
  phase:1, \
  t:none,t:lowercase, \
  nolog, \
  pass, \
  chain"
        SecRule REQBODY_PROCESSOR "!@streq XML" \
          "ctl:requestBodyProcessor=XML"

 It is parsing every content, which includes "text/xml". I think it would be better, 

SecRule REQUEST_HEADERS:Content-Type "^text/xml"

Do you agree with it?!

Hope for an answer.

Greets,
Bernhard

**Comment by csanders-git** [comment]
Often people will include other headers within the content-type header and they still was XML parsed out of it. In general, we expect when we see this header anywhere in the content-type that the data will be XML. There are however some improvements to consider I think it should be changed to better reflect the line present in the OWASP rules which is more complete. Even here there is room for the update you suggested, i'm just not sure how often people provide the xml header and then don't provide xml.

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-dev/modsecurity_crs_10_setup.conf.example#L527

**Comment by pfeiffebe** [comment]
Hey!

Thank you for that answer, but same ERROR:

Content-Type: multipart/related; type="application/xop+xml"; boundary="uuid:75029ae6-7608-4ff1-b7d2-2c6ba6e794f3"; start="<root.message@cxf.apache.org>"; start-info="text/xml"
--c998fb01-H--
Message: XML parser error: XML: Failed parsing document.
Apache-Handler: jakarta-servlet
Stopwatch: 1449474779958659 1393275 (- - -)
Stopwatch2: 1449474779958659 1393275; combined=2993, p1=983, p2=1723, p3=4, p4=209, p5=74, sr=66, sw=0, l=0, gc=0
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache
Engine-Mode: "ENABLED"

Do you have any other ideas?

Greets,

Bernhard

Von: Chaim Sanders [mailto:notifications@github.com]
Gesendet: Sonntag, 06. Dezember 2015 23:30
An: SpiderLabs/ModSecurity
Cc: Pfeiffer, Bernhard
Betreff: Re: [ModSecurity] ModSecurity: XML parser error: XML: Failed parsing document. (#989)


Often people will include other headers within the content-type header and they still was XML parsed out of it. In general, we expect when we see this header anywhere in the content-type that the data will be XML. There are however some improvements to consider I think it should be changed to better reflect the line present in the OWASP rules which is more complete. Even here there is room for the update you suggested, i'm just not sure how often people provide the xml header and then don't provide xml.

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-dev/modsecurity_crs_10_setup.conf.example#L527

**Comment by csanders-git** [comment]
perhaps this is actually invalid XML?

**Comment by pfeiffebe** [comment]
The problem ist, that the modsecurity-auditLogFile shows me:

Content-ID: <http://tempuri.org/0>^M
Content-Transfer-Encoding: 8bit^M
Content-Type: application/xop+xml;charset=utf-8;type="text/xml"^M
…
</s:Envelope>^M

Do have any idea, why it shows ^M?!

Greets

Von: Chaim Sanders [mailto:notifications@github.com]
Gesendet: Mittwoch, 09. Dezember 2015 05:19
An: SpiderLabs/ModSecurity
Cc: Pfeiffer, Bernhard
Betreff: Re: [ModSecurity] ModSecurity: XML parser error: XML: Failed parsing document. (#989)


perhaps this is actually invalid XML?

**Comment by mysterious911** [comment]
My ex hacked my devices and he used that site so i tried to unhack it and
failed again cuZ im not the device administratorm

**Comment by zimmerle** [comment]
Hi @pfeiffebe,

I think you are having problems with related to the line terminator, please check:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#multipart_crlf_lf_lines
and:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#multipart_strict_error

You may want to test with an "LF" terminated xml.

**Comment by pfeiffebe** [comment]
Hey!

Du have an example for MULTIPART_CRLF_LF_LINES –RULE for xml-Requests?
Greets,
Bernhard


Von: Felipe Zimmerle [mailto:notifications@github.com]
Gesendet: Mittwoch, 09. Dezember 2015 14:49
An: SpiderLabs/ModSecurity
Cc: Pfeiffer, Bernhard
Betreff: Re: [ModSecurity] ModSecurity: XML parser error: XML: Failed parsing document. (#989)


Hi @pfeiffebe<https://github.com/pfeiffebe>,

I think you are having problems with related to the line terminator, please check:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#multipart_crlf_lf_lines
and:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#multipart_strict_error

You may want to test with an "LF" terminated xml.

**Comment by pfeiffebe** [comment]
Hey!

Do you have an example for MULTIPART_CRLF_LF_LINES –RULE for xml-Requests?
Greets,
Bernhard


Von: Felipe Zimmerle [mailto:notifications@github.com]
Gesendet: Mittwoch, 09. Dezember 2015 14:49
An: SpiderLabs/ModSecurity
Cc: Pfeiffer, Bernhard
Betreff: Re: [ModSecurity] ModSecurity: XML parser error: XML: Failed parsing document. (#989)


Hi @pfeiffebe<https://github.com/pfeiffebe>,

I think you are having problems with related to the line terminator, please check:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#multipart_crlf_lf_lines
and:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#multipart_strict_error

You may want to test with an "LF" terminated xml.
