### ISSUE TITLE
Mod Security + Proxy Protocol

### ISSUE THREAD

**Issue by ericofusco** [SpiderLabs/ModSecurity#990]
I use the module myfixip with apache to read proxy headers coming from my AWS Load Balancer with Proxy Protocol enabled. (TCP mode on port 80 and 443).

When a mod security rule is triggered it logs and parses the load balancer IP instead of the original external IP. myfixip adds the HTTP header X-Cluster-Client-Ip with the original IP so I tried to use remoteip module to work around that but no success.

Ubuntu 14.04.3
Apache 2.4.7
Mod Security 2.7.7

```
<IfModule mod_myfixip.c>
    RewriteIPResetHeader on
    RewriteIPAllow 10.0.0.0/16 127.0.0.1
</IfModule>

<IfModule mod_remoteip.c>
    RemoteIPHeader X-Cluster-Client-Ip
    # Just 10.0.0.0/16 listed on file
    RemoteIPInternalProxyList /etc/apache2/trusted-proxies.lst
</IfModule>
```

Mod security logs showing the correct external IP address:
```
Dec  7 19:55:28 dev www_dev[5836]:  [client 54.165.XXX.XXX] ModSecurity: Access denied with code 403 (phase 2). Pattern match ..."
````

Mod security audit logs parsing the load balancer IP instead.
```
--90491855-A--
[07/Dec/2015:19:35:54 +0000] VmXfmn8AAAEAAANSL4MAAABw 10.0.220.75 14882 10.0.220.50 443
--90491855-B--
GET /?test_xss=%3Cscript%3Ealert(1)%3C/script%3E HTTP/1.1
Host: devl
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: pt-BR,pt;q=0.8,en-CA;q=0.6,en;q=0.4,en-US;q=0.2
X-Cluster-Client-Ip: 54.165.XXX.XXX
```

**Comment by zimmerle** [comment]
Hi @ericofusco,

On our users' mailing list "Reindl Harald" suggested you the utilization of mod_rpaf or mod_remoteip are those feasible options to you?

For reference, the discussion on our users' mailing list: http://sourceforge.net/p/mod-security/mailman/message/34677020/

**Comment by ericofusco** [comment]
Hi @zimmerle,

Not really, mod_remoteip doesn't understand PROXY protocol.

This topic on the mailing list is mine too. :)
