### ISSUE TITLE
Implement support to gsbLookup operator into libmodsecurity

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/ModSecurity#998]
Operator **gsbLookup** needs to be implemented inside libmodsecurity.

The documentation of the operator can be found here:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#gsbLookup

The file already exist in the repository:
https://github.com/SpiderLabs/ModSecurity/blob/libmodsecurity/src/operators/gsblookup.cc

**Comment by victorhora** [comment]
I'm wondering if we are still able to use this feature after Google haven changed the API as per comment:

"Note : Deprecated in 2.7.0 after Google dev team decided to not allow the database download anymore. After registering and obtaining a Safe Browsing API key, you can automatically download the GSB using a tool like wget. For further information on how to proceed with the download, please visit Google's website: https://developers.google.com/safe-browsing/v3/update-guide"

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecGsbLookupDb

**Comment by zimmerle** [comment]
I think it is safe to not support it. Closing this issue based on @victorhora comment. Thanks @victorhora  ;)
